### ISSUE TITLE
CP: creating a new user, 3 steps of the creation process are always displayed in English

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1000]
My CP is displayed in French. When creating a new user, the 3 steps of the creation process (at the top of the screen) are still displayed in English

![Capture d'écran 2019-11-26 22 02 21](https://user-images.githubusercontent.com/1823359/69675160-4e22c480-109e-11ea-940f-ea5543c72820.png)

**Comment by jackmcdade** [comment]
Thanks!
