### ISSUE TITLE
CP: creating a Blueprint : untranslated string (i18n)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1001]
1/ Missing a translation here (small grey print)

![Capture d'écran 2019-11-26 22 50 02](https://user-images.githubusercontent.com/1823359/69675595-431c6400-109f-11ea-8673-a612796d8607.png)

2/ Save button is displaying...Save

3/ Tab Sections still is displayed in English
![Capture d'écran 2019-11-26 22 53 08](https://user-images.githubusercontent.com/1823359/69675759-ad350900-109f-11ea-8bc4-03e85f73e925.png)

EDIT:
Same behaviour as the one described above (1/) when creating a Fieldset 
![Capture d'écran 2019-11-26 23 03 45](https://user-images.githubusercontent.com/1823359/69676524-3731a180-10a1-11ea-94c2-e5f2ee3ec28e.png)

**Comment by jackmcdade** [comment]
Thanks!
