### ISSUE TITLE
CP: linking field or fieldset to a Blueprint: displayed modal mostly unlocalized (i18n)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1002]
My CP is in French. When clicking on "Lier un existant" during the Blueprint creation process, a modal is displayed in order to allow the user to link either a single field or a fieldset to the blueprint.

This modal is mostly displayed in English:
![Capture d'écran 2019-11-26 23 12 59](https://user-images.githubusercontent.com/1823359/69677207-b1aef100-10a2-11ea-840a-25dcc33b19e4.png)

**Comment by jasonvarga** [comment]
If you don't mind, could you try to consolidate all your translation related findings into one issue? You can leave the existing ones open, but I have a feeling you're going to open more. :)

**Comment by ebeauchamps** [comment]
as you say!
