### ISSUE TITLE
Statamic not installable with PHPUnit 11

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#10028]
### Bug description

Statamic 5.0.1 and PHPUnit 11 don't install together.

### How to reproduce

On a fresh Laravel app (without Statamic) it comes with PHPUnit 11 now.
Try to install Statamic, and Composer will complain about dependency conflicts.

Downgrade to PHPUnit 10, installing Statamic works fine.

### Environment

```yaml
Statamic 5.0.1
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

https://discord.com/channels/489818810157891584/1238143162476662856

**Comment by duncanmcclean** [comment]
For added context, this is the Composer output:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ajthinking/archetype[v1.0.3, ..., v1.1.5] require nikic/php-parser ^4.11 -> found nikic/php-parser[v4.11.0, ..., 4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - statamic/cms 5.x-dev requires ajthinking/archetype ^1.0.3 -> satisfiable by ajthinking/archetype[v1.0.3, ..., v1.1.5].
    - Root composer.json requires statamic/cms * -> satisfiable by statamic/cms[5.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require statamic/cms:*" to figure out if any version is installable, or "composer require statamic/cms:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

It looks like Laravel 11 is using `nikic/php-parser` v5. However, `ajthinking/archetype`, which we require in our `composer.json` depends on `php-parser` and hasn't yet been updated to support v5.

**Comment by jasonvarga** [comment]
I've opened a PR for archetype to support php-parser 5.

https://github.com/ajthinking/archetype/pull/85
