### ISSUE TITLE
CP: Localize Fieldtype Settings Instructions (i18n)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1003]
Will it be possible in the near future to get localized strings for all fieldtype-related strings, as this was done in V2? 

Perhaps could we even "drop" the already localized folder from v2 somewhere in ressources/lang ?

(just dreaming)

**Comment by jasonvarga** [comment]
What exactly are you referring to?

**Comment by ebeauchamps** [comment]
Bard in V2:
![Capture d'écran 2019-11-26 23 42 12](https://user-images.githubusercontent.com/1823359/69678668-829a7e80-10a6-11ea-8bd1-1ccca9c97a37.png)

Bard in V3:
![Capture d'écran 2019-11-26 23 42 46](https://user-images.githubusercontent.com/1823359/69678681-8af2b980-10a6-11ea-9809-76a37d0c6247.png)

Each and every settings of most fieldtypes were localized in V2. here is my folder structure of the French locale for the CP in V2
![Capture d'écran 2019-11-26 23 45 06](https://user-images.githubusercontent.com/1823359/69678779-cee5be80-10a6-11ea-9fe8-2e771a9cce54.png)

**Comment by ebeauchamps** [comment]
Spectacular improvement!
