### ISSUE TITLE
Sortable-List does not update order

### ISSUE THREAD

**Issue by psren** [statamic/cms#1005]
When I edit a fieldsets fields and try to reorder them the order is not reflected properly in the Vue-Component. When i press "save" the wrong order is beeing stored in the `.yaml` file.

Reordering the `yaml`-contents directly in the `.yaml` works.

![image](https://user-images.githubusercontent.com/1016798/69707996-1433db80-10fb-11ea-8121-bb7e706485ff.png)

**Comment by jasonvarga** [comment]
It seems to working fine. Perhaps you have outdated javascript.

Yesterday we had to adjust our workflow to using tagged releases.

In your `composer.json`, change `"statamic/cms": "dev-master"` to `"3.0.*@beta` and then run `composer update statamic/cms`

**Comment by psren** [comment]
Yep, solved :-)
