### ISSUE TITLE
Bard Relationship-Fieldtype: create new entries does not work completely

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1006]
We've built a Relationship-Fieldtype in a bard field. Using the Relationship-Fieldtype we can create new entries `create: true`.
It works that we create a new entry for the collection. But when we switch to the Live-Preview the link is not taken over and the Relationship-Fieldtype value is empty.

I have also no possibility to save the newly linked entry. Error Message: `TypeError: payload.container is undefined`

**Comment by jasonvarga** [comment]
Are you able to show some screenshots or video of what's happening? I'm not really following, sorry. Does this still happen since #1062 has been merged?

**Comment by WiebkeVog** [comment]
Now you can create new entries with the Relationship Fieldtype. 
However, the main entry cannot be saved after a new on is created. The error message is different now `TypeError: Cannot read property 'setFieldValue' of undefined` The GIF is pretty slow but hopefully understandable. ;-)

![Bildschirmvideo aufnehmen 2019-12-05 um 14 07 37](https://user-images.githubusercontent.com/54707973/70238474-9c545980-1769-11ea-90d9-e343a4782a3d.gif)
