### ISSUE TITLE
Error in statamic:install after update

### ISSUE THREAD

**Issue by vguerrerobosch** [statamic/cms#1007]
After updating to the lastest commit trying to get the fix for #955 i get the error

`Can't locate path: <{path_to_site}/vendor/statamic/cms/src/Providers/../../resources/dist>`

and the CP appears kind of broken with no icons. Have tried several times running `composer update` and `composer update statamic/cms`. This last one gave me a composer satisfiable problem with package `scrumpy/html-to-prosemirror`. Thank you!

**Comment by jasonvarga** [comment]
In your `composer.json` please change your `statamic/cms` version from `dev-master` to `3.0.*@beta` and then run `composer update statamic/cms`

**Comment by vguerrerobosch** [comment]
Fixed! Thank you for blazing fast response.
