### ISSUE TITLE
Collection tag offset bug in v5

### ISSUE THREAD

**Issue by wookba** [statamic/cms#10074]
### Bug description

Using` collection` tag with the `offset` parameter causes an error: `Cannot assign string to property Statamic\Query\Dumper\Dumper::$columns of type array`

### How to reproduce

```
{{ collection:pages offset="1" }}
{{ /collection:pages }}
```

### Logs

```shell
[2024-05-14 17:16:12] local.ERROR: Cannot assign string to property Statamic\Query\Dumper\Dumper::$columns of type array {"userId":"***","exception":"[object] (TypeError(code: 0): Cannot assign string to property Statamic\\Query\\Dumper\\Dumper::$columns of type array at /app/vendor/statamic/cms/src/Query/Dumper/Dumper.php:31)
# stacktrace redacted
```

### Environment

```yaml
Statamic: 5.1.0
PHP: 8.2.18, tested on 8.3 as well,
Laravel: 10.48.10
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by wookba** [comment]
Workaround:
```
{{ collection:pages as="pages" }}
{{ pages offset="1" }}
...
{{ /pages }}
{{ /collection }}
```

**Comment by jasonvarga** [comment]
Does your collection really just look like `{{ collection:pages offset="1" }}`?

**Comment by wookba** [comment]
Not really, I just wanted to simplify the issue, as I tested other parameters:

``` {{ collection:posts paginate="12" as="posts" sort="date:desc" offset="1" }}```
Another one in the same template is:
```{{ collection:posts sort="date:desc" limit="1" }}```

**Comment by jasonvarga** [comment]
The issue only seemed to happen when using the `paginate` parameter.
