### ISSUE TITLE
Too many clicks to get to blueprints

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1014]
Have to click Blueprints, then View All.

Would prefer to have them avail right from the menu on the left.

**Comment by steveooo1** [comment]
@edalzell Yeah, I agree. I added a issue that was moved to statamic/ideas:
https://github.com/statamic/ideas/issues/44

Maybe it also would be great to list all blueprints and fieldsets in the overvie section (where you have the 2 columns with the blue buttons)... You could have the 2 columns with "Create XYZ" and below of them list all the stuff. I don't have Statamic available, so I don't know the exact url, but is it /fields/?
