### ISSUE TITLE
section titles styled wrong

### ISSUE THREAD

**Issue by stefankempf** [statamic/cms#10159]
### Bug description

in `5.4`, the section titles look pretty big

![Screenshot von 2024 05 22 um 10 55 09](https://github.com/statamic/cms/assets/20299885/c7f0aceb-a6a4-49df-95a8-43a09b8520d0)

### How to reproduce

install 5.4

### Environment

```yaml
Version: 5.4.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Can you share the full output of `php please support:details`?
