### ISSUE TITLE
wrong inherited border color in cp light mode

### ISSUE THREAD

**Issue by stefankempf** [statamic/cms#10155]
### Bug description

There are a few border colors in lightmode, getting inherited from `cp.css` with 
```css
*, ::before, ::after {
    border-color: currentColor;
```
which render the wrong color

### How to reproduce

open cp in statamic v 5.4.0

### Environment

```yaml
Version: 5.4.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by stefankempf** [comment]
![Screenshot von 2024 05 22 um 09 54 49](https://github.com/statamic/cms/assets/20299885/cf2a29b0-5737-4a11-ae02-3b05b0b63b47)

**Comment by stefankempf** [comment]
![Screenshot von 2024 05 22 um 10 00 33](https://github.com/statamic/cms/assets/20299885/20f143fe-88ff-40dc-8c65-422d2b826c1c)
![Screenshot von 2024 05 22 um 10 00 28](https://github.com/statamic/cms/assets/20299885/cb7ec4b3-69b9-4b4d-af88-5d256ab55ebb)

**Comment by stefankempf** [comment]
# screenshot collection
![Screenshot von 2024 05 22 um 09 38 57](https://github.com/statamic/cms/assets/20299885/c0c6354b-06d9-4a53-9271-1046a0fb5fb7)
![Screenshot von 2024 05 22 um 09 38 52](https://github.com/statamic/cms/assets/20299885/605bc0b1-a135-44b7-aeb3-478a98136c44)
![Screenshot von 2024 05 22 um 09 38 48](https://github.com/statamic/cms/assets/20299885/6b9794aa-6722-469a-86a0-5a15f947f4a6)
![Screenshot von 2024 05 22 um 10 01 39](https://github.com/statamic/cms/assets/20299885/d390e6a9-6de4-4248-8862-e2ba116173de)
![Screenshot von 2024 05 22 um 09 54 49](https://github.com/statamic/cms/assets/20299885/cf2a29b0-5737-4a11-ae02-3b05b0b63b47)
![Screenshot von 2024 05 22 um 10 00 33](https://github.com/statamic/cms/assets/20299885/20f143fe-88ff-40dc-8c65-422d2b826c1c)
![Screenshot von 2024 05 22 um 10 00 28](https://github.com/statamic/cms/assets/20299885/cb7ec4b3-69b9-4b4d-af88-5d256ab55ebb)

**Comment by duncanmcclean** [comment]
Hmm, all the borders you screenshotted look fine to me.... 🤔 

![CleanShot 2024-05-22 at 10 19 19](https://github.com/statamic/cms/assets/19637309/c0c2cdbc-a256-4723-994b-ab91fa5b2b24)

![CleanShot 2024-05-22 at 10 20 53](https://github.com/statamic/cms/assets/19637309/807272c0-5690-4cc9-9c51-4908ee032994)

![CleanShot 2024-05-22 at 10 21 12](https://github.com/statamic/cms/assets/19637309/129b605d-0315-4ca0-ac11-516f79c7a060)

Can you share the full output of `php please support:details`?

**Comment by stefankempf** [comment]
ah damn, I'm in darkmode hustle fever 🙈 started implementing in the one backend, I've restyled quite a bit. should have tested further before creating issue. sorry!

**Comment by duncanmcclean** [comment]
No worries!
