### ISSUE TITLE
View [errors.404] not found

### ISSUE THREAD

**Issue by vguerrerobosch** [statamic/cms#1017]
When installing Statamic into an existing Laravel app, the default antlers views are not created. I'm ok with this, but then when hitting a 404 the `Statamic\Exceptions\NotFoundHttpException` class throws `InvalidArgumentException: View [errors.404] not found.`.
I think it would be nice if it could fallback to the `Illuminate\Foundation\Exceptions\Handler::renderHttpException()`.

I think I would do something like
```php
<?php

namespace Statamic\Exceptions;

use Statamic\View\View;
use Facades\Statamic\View\Cascade;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException as SymfonyException;

class NotFoundHttpException extends SymfonyException
{
    public function render()
    {
        if (view()->exists('errors.404')) {
            return response($this->contents(), 404);
        }
    }

    // ...
}
```

Thank you!

**Comment by jasonvarga** [comment]
Good find.
