### ISSUE TITLE
Double Forward Slash On Search Update

### ISSUE THREAD

**Issue by ThaoPhia** [statamic/cms#10188]
### Bug description

It doesn't look like the generated preset images path are correct. There is a double forward slash in between the image and asset folders. In this case, it's between `articles` and `study-habits.jpeg` folders. 

Ex:
https://cms-test-assets.americanbookcompany.com/cache/containers/articles//study-habits.jpeg/1bbeb4cc64df553918ecf123f54851ef/study-habits.webp

### How to reproduce

Add a preset in config/statamic/assets.php file. Then in app/Providers/AppServiceProvider.php add the attributes in extendModels(). When you add, edit a collection entry or manually run the command `php please search:update`, it define the preset image path. Right now it contains double forward slash, which the images are broken.

### Environment

```yaml
Statamic: 5.5
Laravel: 10
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
> Then in app/Providers/AppServiceProvider.php add the attributes in extendModels().

What is `extendModels`?

**Comment by ThaoPhia** [comment]
It's a method in app/Providers/AppServiceProvider.php.

**Comment by duncanmcclean** [comment]
> It's a method in app/Providers/AppServiceProvider.php.

What's in that method? Can you share the code?

**Comment by ThaoPhia** [comment]
` protected function extendModels()
    {
        $generator = app(ImageGenerator::class);
        $server = $generator->getServer();

        // Articles
        Collection::computed('articles', 'photo', function ($entry, $value) use ($server) {
            return $this->getCacheImageUrl($entry->cover_image, 'article-photo', $server);
        });
        Collection::computed('articles', 'photo_lg', function ($entry, $value) use ($server) {
            return $this->getCacheImageUrl($entry->cover_image, 'article-photo-lg', $server);
        });
}`

**Comment by duncanmcclean** [comment]
Thanks! What does that `getCacheImageUrl` method do? Can you share its code too?

**Comment by ThaoPhia** [comment]
`protected function getCacheImageUrl($image, $preset, $server)
    {
        if (! $image) {
            return null;
        }

        $path = $image['path'];
        $params = ['p' => $preset];
        $cacheFileName = $server->getCachePath($path, $params);
        $containerName = $image->container['handle'];
        $cachePath = "containers/$containerName/$cacheFileName";

        return Storage::disk('assets_cache')->url($cachePath);
    }`


It looks like before `$cacheFileName` start with a forward slash, which before it didn't have that, but I guess we can adjust that on our end to fix this.

**Comment by jasonvarga** [comment]
> we can adjust that on our end to fix this.

Great!
