### ISSUE TITLE
Intercepting Gate Checks conflict

### ISSUE THREAD

**Issue by vguerrerobosch** [statamic/cms#1018]
When using Statamic in an existing Laravel app with Eloquent Users and having an intercepting gate check defined like
```php
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;

class AuthServiceProvider extends ServiceProvider
{
    protected $policies = [
        // ...
    ];

    public function boot()
    {
        $this->registerPolicies();

        Gate::before(function ($user, $ability) {
            if ($user->isSuperAdmin()) {
                return true;
            }
        });
    }
}
```
as documented in https://laravel.com/docs/6.x/authorization#intercepting-gate-checks, when accessing CP with an unauthorized user the following exception is thrown:

`Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Statamic\Auth\Eloquent\User::isSuperAdmin()`

The exception is not thrown if the user is in fact super, I'm guessing because a previous gate passes and the execution never reach this point. If we comment this `Gate::before`, then everything works fine and the user is redirected to `/cp/auth/unauthorized`.

I guess it's all because the class `Statamic\Auth\Eloquent\User` doesn't know anything about the custom methods defined in `App\User` model. Not sure if there would be a way to actually extend `App\User` or we should take a whole different approach for this.

Thank you!

**Comment by jasonvarga** [comment]
Thanks for pointing this out!

I believe `$user->isSuperAdmin()` should be changed to `\Statamic\Facades\User::fromUser($user)->isSuperAdmin()`

**Comment by vguerrerobosch** [comment]
Thank you. Finally I adopted the following

```php
namespace App\Providers;

use App\User;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use Statamic\Facades\User as StatamicUser;

class AuthServiceProvider extends ServiceProvider
{
    protected $policies = [
        //
    ];

    public function boot()
    {
        $this->registerPolicies();

        Gate::before(function ($user, $ability) {
            if ($user instanceof StatamicUser && $user->isSuper()) {
                return true;
            } elseif ($user instanceof User && $user->isSuperAdmin()) {
                return true;
            }
        });
    }
}
```
since I liked the idea of being able to separate the logic of being considered super the in Statamic domain or the App domain, even I'm not sure I really need it yet. At first it felt strange to have `$user` being something else than `App\User`. Closing this, thank you!

**Comment by jasonvarga** [comment]
I think this might be solved. Please re-open if that's not the case.
