### ISSUE TITLE
CP (i18n): additional missing translations

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1025]
LAST EDIT: 2020/02/17

1/ Creating a collection, assigning a Taxonomy but none has been created yet (dropdown)
![Creating collection - no Taxonomy](https://user-images.githubusercontent.com/1823359/69890387-adc6dd00-12f5-11ea-971d-af30665ed092.png)

2/ Creating an entry, past and future dated entry behaviour (dropdown)
![Past   future dated entry behavior dropdown](https://user-images.githubusercontent.com/1823359/69890416-cf27c900-12f5-11ea-9a22-6f9766df37eb.png)

3/ Sort direction : dropdown
![Ordering - sort direction dropdown](https://user-images.githubusercontent.com/1823359/69890438-eff01e80-12f5-11ea-8d13-ebf82f2a2a55.png)

4/ User page, 3 dots button : send password reset
![User page - send password reset](https://user-images.githubusercontent.com/1823359/69890454-0e561a00-12f6-11ea-97f4-67fe9f71229e.png)

5/ Managing columns (article in a collection): Author isn't localizable
![Capture d'écran 2019-12-01 15 00 37](https://user-images.githubusercontent.com/1823359/69915094-62264780-144b-11ea-91de-29df1c73aad2.png)

6/ Managing filters (article in a collection): operators
![Capture d'écran 2019-12-01 15 01 49](https://user-images.githubusercontent.com/1823359/69915107-90a42280-144b-11ea-9e8f-b8d7846c7ada.png)

7a/ Structure: creating the first page. Various keys, apart form the button
![Capture d'écran 2019-12-01 15 07 52](https://user-images.githubusercontent.com/1823359/69915183-86365880-144c-11ea-83f7-f196d1795632.png)

7b/ Structure: editing an existing structure (Title, Handle, purpose, radio buttons, etc.)
![Capture d'écran 2019-12-01 15 11 37](https://user-images.githubusercontent.com/1823359/69915208-e4fbd200-144c-11ea-80b5-fc157b37f99a.png)

8a/ Editing assets: Move and Rename buttons (and actions)
![Capture d'écran 2019-12-01 15 19 30](https://user-images.githubusercontent.com/1823359/69915324-fee9e480-144d-11ea-92e1-89f1c48b5761.png)

![Capture d'écran 2019-12-01 15 20 44](https://user-images.githubusercontent.com/1823359/69915344-30fb4680-144e-11ea-930f-a757843854d7.png)

9/ Bard-related missing translation: 
When configuring a Bard field, most icons are localizable, except for ```Expand/Collapse Sets```.
Strangely enough, a description related to the icon provider (??) appears as you hover on this icon

![Capture d'écran 2019-12-04 22 55 22](https://user-images.githubusercontent.com/1823359/70185044-5e175580-16e9-11ea-97fc-560629a2ef9f.png)

10/ ```Search...```placeholder text (translated text is included in fr.json but not rendered)
![Capture d'écran 2019-12-04 23 05 52](https://user-images.githubusercontent.com/1823359/70185794-c61a6b80-16ea-11ea-86d8-185dd435e86d.png)

11/ Live Preview dropdown values (except for Responsive)
![Capture d'écran 2019-12-12 21 45 34](https://user-images.githubusercontent.com/1823359/70747733-dc4aac00-1d28-11ea-8e77-bd4135f2bf09.png)

12/ Manipulating Structure (pages/subpages):
![Capture d'écran 2019-12-13 21 47 35](https://user-images.githubusercontent.com/1823359/71413710-c6f04e80-2653-11ea-824e-0917c513492f.png)

13/ "Are you sure?" in modal:
![Capture d'écran 2019-12-13 21 18 21](https://user-images.githubusercontent.com/1823359/71413837-54cc3980-2654-11ea-8b0e-193c60805388.png)

**Comment by helloDanuk** [comment]
14/ "(default)" in entries per page
<img width="298" alt="Bildschirmfoto 2020-01-18 um 01 34 03" src="https://user-images.githubusercontent.com/8265902/72655080-e482b080-3992-11ea-80b7-06afa0782c5c.png">

**Comment by helloDanuk** [comment]
15/ Array Fieldtype: "Key", "Value"
<img width="562" alt="Bildschirmfoto 2020-01-18 um 22 46 12" src="https://user-images.githubusercontent.com/8265902/72671170-84e5dd00-3a46-11ea-8a20-50b8e9d5ef91.png">

16/ Markdown Fieldtype: "Enter URL"
<img width="538" alt="Bildschirmfoto 2020-01-18 um 23 25 23" src="https://user-images.githubusercontent.com/8265902/72671403-eb202f00-3a49-11ea-942c-bac0808d3420.png">

**Comment by helloDanuk** [comment]
17/ Replicator and Bard Fieldtyp "Collapse Set" and opposite "Expand Set"
<img width="292" alt="Bildschirmfoto 2020-01-19 um 13 25 28" src="https://user-images.githubusercontent.com/8265902/72680970-c49cdb00-3abf-11ea-9240-cc4c181a70f2.png">
<img width="282" alt="Bildschirmfoto 2020-01-19 um 13 28 46" src="https://user-images.githubusercontent.com/8265902/72680977-c9618f00-3abf-11ea-83df-d7830f43145a.png">

/18 When revisions are disabled: Green Confirmation box in the bottom left corner after click save & publish: "Saved"
<img width="185" alt="Bildschirmfoto 2020-01-19 um 14 47 50" src="https://user-images.githubusercontent.com/8265902/72682181-b607f100-3aca-11ea-8d1b-5fadfc85a7e6.png">

**Comment by helloDanuk** [comment]
### /19 Asset Browser

In addition to the already described missing translations8a/ and 8b above, there are a few others:

- "Search…" placeholder (already described above, similar for collection use → 10/)

- "Loading" spinner, when open assets (this loading spinner is not translated in similar other parts i.e. opening a collection)
<img width="137" alt="Bildschirmfoto 2020-01-19 um 23 49 15" src="https://user-images.githubusercontent.com/8265902/72689869-70711580-3b16-11ea-8017-5f7e2094eafb.png">

- Rename File Modal: "Rename" and "Filename"
<img width="683" alt="Bildschirmfoto 2020-01-19 um 23 56 44" src="https://user-images.githubusercontent.com/8265902/72689944-67347880-3b17-11ea-9bcf-5c96bd941e2a.png">

- Move Modal: "Move" and "Folder"
<img width="650" alt="Bildschirmfoto 2020-01-19 um 23 58 21" src="https://user-images.githubusercontent.com/8265902/72689966-ae226e00-3b17-11ea-8165-2b6b6a77024c.png">

- Saving a change in an asset → same green box "Saved" as in /18

- Create a folder → Error message when using spaces in foldername "The given data was invalid"
<img width="478" alt="Bildschirmfoto 2020-01-19 um 23 43 45" src="https://user-images.githubusercontent.com/8265902/72689821-035d8000-3b16-11ea-839a-7cbd424fd920.png">

**Comment by helloDanuk** [comment]
/20 Collection wizard → "Draft"
<img width="649" alt="Bildschirmfoto 2020-01-19 um 22 49 10" src="https://user-images.githubusercontent.com/8265902/72690068-d5c60600-3b18-11ea-924b-71f3fee5c029.png">

/21 Revision Sidebar
- labels "Unpublish", "Publish", "Current", "Revision"
- date order does not respect localization. In german it should be 19. Januar 2020
<img width="394" alt="Bildschirmfoto 2020-01-20 um 00 13 48" src="https://user-images.githubusercontent.com/8265902/72690211-7e289a00-3b1a-11ea-960b-0d34c094a7c8.png">

/22 Collection wizard → 3 → Collection → Link Existing Item: Table Header Cells "Title", "Entries"
<img width="624" alt="Bildschirmfoto 2020-01-20 um 00 57 07" src="https://user-images.githubusercontent.com/8265902/72690799-268d2d00-3b20-11ea-8c8b-2775d878f783.png">

**Comment by helloDanuk** [comment]
/23 Under Edit Structure Config a bunch of titles and sentences (Purpose and Collection)
<img width="839" alt="Bildschirmfoto 2020-01-20 um 01 37 16" src="https://user-images.githubusercontent.com/8265902/72691446-bc778680-3b25-11ea-83e1-3d31bbd2084b.png">

**Comment by helloDanuk** [comment]
/24 Cache Manager
- "Refresh" and "Disabled"
- green confirmation messages: 
  - "All caches cleared"
  - "Stache cleared"
  - "Application cache cleared"
  - "Image cache cleared"
<img width="1440" alt="Bildschirmfoto 2020-01-20 um 09 52 41" src="https://user-images.githubusercontent.com/8265902/72712348-25352200-3b6b-11ea-99f7-62b2015704fe.png">

/25 Update Search Indexes: green confirmation box "Indexes sucessfully updated"
<img width="292" alt="Bildschirmfoto 2020-01-20 um 10 02 26" src="https://user-images.githubusercontent.com/8265902/72712827-2155cf80-3b6c-11ea-851f-b079d7b19f96.png">

/26 Send test email: green confirmation box "Attempt to send email completed successfully"
<img width="658" alt="Bildschirmfoto 2020-01-20 um 10 18 51" src="https://user-images.githubusercontent.com/8265902/72714217-a510bb80-3b6e-11ea-8c8e-297bdc2efeb9.png">

/27 In addition to 4/: same text in button and modal "Send password reset"
<img width="1201" alt="Bildschirmfoto 2020-01-20 um 10 33 19" src="https://user-images.githubusercontent.com/8265902/72715190-52d09a00-3b70-11ea-8558-9b023cd88f0d.png">
<img width="626" alt="Bildschirmfoto 2020-01-20 um 10 36 56" src="https://user-images.githubusercontent.com/8265902/72715453-ce324b80-3b70-11ea-896d-515fb09761e2.png">

/28 Fieldtypes: Validation
- "Add Rule" in dropdown
<img width="486" alt="Bildschirmfoto 2020-01-20 um 10 57 00" src="https://user-images.githubusercontent.com/8265902/72717073-a42e5880-3b73-11ea-9e10-524d169b1bcf.png">

/29 Collection > Edit
- Section Dates: Pretty much everything (toggle, dropdown)
- Section Ordering: Nothing is translated yet (toggle, dropdown and "Structure")
- Section Content Model: "Content Model" and "Default Publish State" 
- Section Routing: "Routing", "Route" and "Mount"
<img width="1209" alt="Bildschirmfoto 2020-01-20 um 11 25 37" src="https://user-images.githubusercontent.com/8265902/72719176-9f6ba380-3b77-11ea-8915-9f29f9349c9b.png">
<img width="1221" alt="Bildschirmfoto 2020-01-20 um 11 08 20" src="https://user-images.githubusercontent.com/8265902/72717931-426eee00-3b75-11ea-9e98-4e75487cab6e.png">
<img width="1203" alt="Bildschirmfoto 2020-01-20 um 11 08 29" src="https://user-images.githubusercontent.com/8265902/72717947-4864cf00-3b75-11ea-8e89-16053214c543.png">

/30 Taxonomy > Edit: "Content Model"

/31 Form > Edit: lots of fields and section names
<img width="1198" alt="Bildschirmfoto 2020-01-20 um 11 41 47" src="https://user-images.githubusercontent.com/8265902/72720339-fd998600-3b79-11ea-86a3-44df5f96b927.png">

**Comment by ebeauchamps** [comment]
Great work @helloDanuk  !

**Comment by ebeauchamps** [comment]
32/ New collection workflow

https://www.dropbox.com/s/252lo941qcmual8/Capture%20d%27%C3%A9cran%202020-02-15%2021.08.49.png?dl=0

**Comment by helloDanuk** [comment]
As for 32/ New collection workflow:
There are keys in the en/messages.php file, but not all of them are generated using `php translator generate eo`.

**Comment by ebeauchamps** [comment]
Typically, Orderable was in my previous fr.json file but isn't there anymore in the latest one.

As for the untranslated text in the new Collection Workflow, I don't quite understand because we have the keys in message.php and with have the reference to those keys in the empty.blade.php file.

**Comment by ebeauchamps** [comment]
18/ has been corrected with beta16
19/ is far more complete than 8b/ I deleted this one

**Comment by helloDanuk** [comment]
33/ Permissions → Helper Text is missing

<img width="953" alt="Bildschirmfoto 2020-02-20 um 13 19 20" src="https://user-images.githubusercontent.com/8265902/74933415-2b295780-53e4-11ea-9d50-f861a8880a2a.png">
<img width="915" alt="Bildschirmfoto 2020-02-20 um 13 19 29" src="https://user-images.githubusercontent.com/8265902/74933417-2bc1ee00-53e4-11ea-8e5a-06d72373cea4.png">


34/ Users → Helper Text is missing

<img width="935" alt="Bildschirmfoto 2020-02-20 um 14 09 16" src="https://user-images.githubusercontent.com/8265902/74936669-dd641d80-53ea-11ea-81e1-5b60eaffdd62.png">
<img width="933" alt="Bildschirmfoto 2020-02-20 um 14 09 31" src="https://user-images.githubusercontent.com/8265902/74936672-de954a80-53ea-11ea-84e6-33ea7ff9e23a.png">


As of /33 and /34: All checkboxes display a missing helper text. That's different form the other chapters (collections, structures…), where only the first checkbox has a helper text.


35/ Send Test Email → Confirmation message

<img width="504" alt="Bildschirmfoto 2020-02-20 um 09 42 56" src="https://user-images.githubusercontent.com/8265902/74916411-176ef880-53c6-11ea-86c1-4f8b996c823d.png">

**Comment by ebeauchamps** [comment]
36/ Dashboard - Partially translated introductory text about Statamic

![Capture d'écran 2020-03-25 11 25 27](https://user-images.githubusercontent.com/1823359/77526839-7e7f4180-6e8b-11ea-82fa-ae8ae47f94be.png)
