### ISSUE TITLE
CP: UI glitch when viewing entry content with bold formatting (markdown)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1026]
I created a very basic blog entry with the default markdown content field in which I added some text with bold formatting. The text is rendering as expected in the field after saving.

But when viewing the entry excerpt in the CP, and especially the Content column, the bold formatting isn't rendered as expected and one * isn't aligned with the others.

Browser: SAFARI 12.1.2 on MAC OS 10.12.6

![UI glitch when entry content contains bold markdown](https://user-images.githubusercontent.com/1823359/69890617-ffbc3280-12f6-11ea-9b2b-c43f1686f9bc.png)

**Comment by vladdu** [comment]
This is the same as #1024. The content is included verbatim, and so markdown is not formatted, and html can contain formatting. I think the value should be cleaned up of all formatting when displayed in the table.

**Comment by jasonvarga** [comment]
Funny that you opened these issues so close to each other.

**Comment by vladdu** [comment]
You know what they say about great minds and how they think 😉

**Comment by ebeauchamps** [comment]
Europeans have some connections...

**Comment by steveooo1** [comment]
Yeah, I can reproduce this issue also on latest Firefox on Mac.
