### ISSUE TITLE
CP: unexpected infinite loading spin wheel when creating global set

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1027]
Just wanted to create my first global set.

Something is spinning, spinning, spinning...(hard to render this with a screen copy!)

![Creating global set - infinite loading spin wheel](https://user-images.githubusercontent.com/1823359/69890704-76f1c680-12f7-11ea-89d9-0d791315f3ff.png)

**Comment by jackmcdade** [comment]
Is this still an issue? I can't recreate it.

**Comment by ebeauchamps** [comment]
can't recreate either
