### ISSUE TITLE
Collection Tag using data from Collection fieldtype results in error

### ISSUE THREAD

**Issue by andymswick** [statamic/cms#1028]
In v2 I had the following:

```
{{ collection from="{collection}" limit="{limit}" scope="item" }}
  <div class="px-4 w-full lg:{{ width }} mb-8">
    {{ partial src="{fieldset}" }}
  </div>
{{ /collection }}
```

I've updated it to be (I simplified it a bunch to verify the from was the issue):

```
{{ collection :from="collection" }}
  <div class="px-4 w-full mb-8">
    <p>hi</p>
  </div>
{{ /collection }}
```

By updating from `from="collection"` to `:from="collection"` my error message changed from:

```
Facade\Ignition\Exceptions\ViewExceptionWithSolution
Collection [] not found
```
[Flare](https://flareapp.io/share/v5pzl6PE)

to:

```
Facade\Ignition\Exceptions\ViewExceptionWithSolution
Collection [collection] not found
```
[Flare](https://flareapp.io/share/xPQD0ym1)

I also tried:

```
{{ collection :from="{collection}" }}
  <div class="px-4 w-full mb-8">
    <p>hi</p>
  </div>
{{ /collection }}
```

Which resulted in `Collection [collection] not found` again.

I tried changing my collection variable to posts but it still didn't change anything.

When I dump my page, the collection variable is a Collection object, not a string.

<img width="360" alt="Screen Shot 2019-11-29 at 3 48 16 PM" src="https://user-images.githubusercontent.com/6541180/69891115-b56b8f00-12bf-11ea-8996-aa26220e046f.png">

I can make my repo available if that helps :)

**Comment by jasonvarga** [comment]
Where is that `collection` tag pair being used? Is it inside another loop?

**Comment by andymswick** [comment]
Yes, its inside a Replicator

**Comment by jasonvarga** [comment]
Can you show the blueprint?

**Comment by andymswick** [comment]
Yup!

[Blueprint](https://github.com/andymswick/yosemite/blob/master/resources/blueprints/sections.yaml)
[Page Data](https://github.com/andymswick/yosemite/blob/master/content/collections/pages/home.md)

[Top Loop view](https://github.com/andymswick/yosemite/blob/master/resources/views/sections.antlers.html)

[Collection Section](https://github.com/andymswick/yosemite/blob/master/resources/views/partials/sections/collection_section.antlers.html)

**Comment by andymswick** [comment]
It's a bit of a dozy of a blueprint 🙃
