### ISSUE TITLE
Collection without Blueprint empty state is unclear.

### ISSUE THREAD

**Issue by andrewcgregory** [statamic/cms#1034]
This is for a minor user experience improvement. You can create a new Collection without selecting a Blueprint. However, after the Collection is created you When creating a new Collection if you do not select a Blueprint, it will still let you create the Collection. You are then brought to the main screen for the Collection that says _“Create your first [collection name] entry now”_

However, you cannot create a new entry until a Blueprint has been linked which is not clear from this screen. 

<img width="1219" alt="collection-without-blueprint" src="https://user-images.githubusercontent.com/1779776/69893809-e01c0e80-12e4-11ea-9f18-2c358120eff8.png">

**Comment by jackmcdade** [comment]
No longer an issue after the Create Collection flow redesign.
