### ISSUE TITLE
Not every translations fetch from the same folder (i18n): path problem

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1036]
In ```my-site/resources/lang```I have a ```fr.json``` file and a ```fr``` folder.

When displaying the CP in French, some messages are fetch from ```my-site/vendor/statamic/cms/resources/lang/fr/messages.php```and not from ```my-site/resources/lang/fr/messages.php```

Those messages are especially the instructions found on the default Dashboard, such as:
```
'getting_started_widget_addons'
'getting_started_widget_blueprints'
'getting_started_widget_collections'
etc.
```

Those keys were initially untranslated and this was corrected after my initial report.

I discovered that problem when creating a new translation (for Italian), adding all files in the default ```resources/lang```folder and getting untranslated strings (simply because no Italian files are in the ```vendor```path.

**Comment by jasonvarga** [comment]
In our code, we use translation helpers like `__('something')`.

The translations in the json files are generally short words or phrases. We reference these in our code directly, eg. `__('Save')`.

We store longer phrases in php files and reference by key. eg. `__('statamic::messages.getting_started_widget_addons')`

What I think you're seeing is that when a translation is not available, it will just output whatever is between our `__()` tag. The shorter phrases are already in English so they look translated. 

I could be misunderstanding the issue though. Feel free to reopen.

**Comment by ebeauchamps** [comment]
My initial idea was to only work on the files located in ```my-site/resources/lang/```in order to update the translations.

1. if I change something in ```fr.json``` (located in this folder), changes are immediately taken into account (i.e. new translations added when I run ```php translator generate```and ```php translator translate```)

2. if I change something in ```my-site/resources/lang/fr/messages.php```, changes are not available, at least as you said it for long keys. In such a case, I have either to put the modified file in ```my-site/vendor/statamic/cms/resources/lang/fr/```or wait for my PR to be merged and for the update to be done. I think I could benefit from a better workflow here.

**Comment by jasonvarga** [comment]
You can override a "vendor's" translation by placing them in `resources/lang/vendor/vendor-name`.

So, for example to override Statamic's `messages.php` you can put it in `your-site/resources/lang/vendor/statamic/fr/messages.php`

**Comment by ebeauchamps** [comment]
hum...ok. I'll keep that in mind. Thanks Jason :-)
