### ISSUE TITLE
Adding more than one user causes an exception to be thrown when trying to access the cp

### ISSUE THREAD

**Issue by websmarts** [statamic/cms#10416]
### Bug description

I am very new to statamic and did not (yet) realise that multiple users was a pro feature. I added a second user and then found I could not access the control panel and the following exception error was thrown: Statamic\Exceptions\StatamicProRequiredException::getSolution(): Return value must be of type Spatie\Ignition\Contracts\Solution, Statamic\Ignition\Solutions\EnableStatamicPro returned 

### How to reproduce

To reproduce the issue  create  an extra user yaml file and you can no longer access the control panel.

### Environment

```yaml
Using DDev development environment with Statamic 5.13
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
That's intentional. 

You'll need to either [enable Statamic Pro](https://statamic.dev/licensing#content) (which you can do for free while in development) or delete one of the users. 

Although... it should have a more helpful error message. I'll get that fixed.

**Comment by websmarts** [comment]
All good, a more helpful message would be a perfect solution - thanks Ian

**Comment by duncanmcclean** [comment]
After doing some digging, it seems this error is happening due to changes in the Ignition package we rely on. I've opened an issue on the package's repository: https://github.com/spatie/error-solutions/issues/5

**Comment by duncanmcclean** [comment]
The latest version of `spatie/error-solutions` includes a fix for this.
