### ISSUE TITLE
Large number of collection blueprints not selectable via dropdown.

### ISSUE THREAD

**Issue by wizzer711** [statamic/cms#10436]
### Bug description

I have a collection that has around 40 blueprints. When I think go to create a new entry and open the dropdown to select the blueprint I wish to use the dropdown is too tall for the screen and has no vertical scroll, meaning I can't select any blueprints lower in the list unless I manually zoom out the browser window.

See the attached screengrab to see the problem.
![Screenshot 2024-07-11 at 11 32 24](https://github.com/statamic/cms/assets/18171767/b18a4ffd-2b26-4444-a9b5-1e045304ab90)

### How to reproduce

Create a collection and add a large number of blueprints.

### Environment

```yaml
Statamic CMS version 5.14.0.
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Out of curiosity, why do you have so many blueprints for a single collection?

**Comment by wizzer711** [comment]
We have a collection to create pages, a collection to create ribbons (page elements). The user then uses a replicator field to either populate a ribbon straight in the replicator ribbon or alternatively if they wish to pull in a ribbon from the ribbons collection (this is the one with many blueprints) they can do.

The reason for a separate ribbons collection is to allow users the option to re-use specific ribbons across the site if they wish.
