### ISSUE TITLE
View [post] not found.

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/cms#1045]
When creating a new site, anything outside of the home page is looking for a post template, even pages.

**Comment by jasonvarga** [comment]
Expected behavior. The views can be configured in config/statamic/theming.php.

Or define a template at the collection level.

**Comment by jackmcdade** [comment]
In v3 we decided it was better to show an error when a template is missing instead of showing the wrong template (e.g. falling back to default or anything you have). This way you know right away, as you dev.

**Comment by sheldonkotyk** [comment]
It's just a bit confusing with a default template sitting there from the installation, not being used. Not sure where it is getting the idea it should look for a post template. I looked in all the yaml files but didn't see that template called anywhere. My expectation was for it to use the default template, not try and find an uncalled for post template.

I don't mind an error, but the default template file should get deleted then and it should complain that a template has not been chosen, rather than sending me on a hunt to find where the post template was called.

**Comment by jackmcdade** [comment]
I agree. This should be more streamlined and intuitive.

**Comment by billmn** [comment]
@jackmcdade this PR could be reconsidered? https://github.com/statamic/cms/pull/933

**Comment by jasonvarga** [comment]
@billmn that would still mean that "default" is a magic thing that you need to know about, rather than "post" which is actually configurable.

Sounds to me like we can just remove the default.antlers.html from statamic/statamic.

Or, maybe we just make all of [these](https://github.com/statamic/statamic/blob/master/config/statamic/theming.php#L18-L20) `default`, by default. 😄

**Comment by billmn** [comment]
@jasonvarga Yes, you're right.

I'm not sure that remove default.antlers.html it's the best thing to do ... personally I prefer a **it-works-out-of-the-box**® approach 😄

**Comment by sheldonkotyk** [comment]
I think its either make it work out of the box so devs have a starting point or just stick the statamic logo up there like you have now. post has either a "blog" connotation to it or worse yet, a form post connotation like a default laravel controller.

Default is at least something that people will recognize as the thing that works out of the box.

**Comment by jasonvarga** [comment]
Another option, now that I'm looking at the `theming.php` file, is to remove it entirely. It's kinda pointless. It only has 3 items in it:

- **Default views:** We could just always fall back to `default` for views . If you want to customize defaults, you can do it on a collection/taxonomy level, which I think most people do anyway.
- **Default blueprints:** Same as views. Just fall back to default, and customize on a collection level.
- **Error directory:** Laravel just assumes its an `errors` subdirectory and doesn't let you change it. https://laravel.com/docs/6.x/errors#custom-http-error-pages If they don't let you customize it, I'm fine with removing it. I doubt there's a reason to change it from errors anyway.

@jackmcdade we can talk this over in Slack if you prefer.

**Comment by sheldonkotyk** [comment]
You have my vote Jason.

**Comment by jasonvarga** [comment]
![](https://media.giphy.com/media/yJ1KSiTxaAw5G/giphy.gif)

**Comment by billmn** [comment]
@jasonvarga Totally agree 🙌

**Comment by jackmcdade** [comment]
Sold to the man in the yellow hat!
