### ISSUE TITLE
Error when using Eloquent

### ISSUE THREAD

**Issue by tolawho** [statamic/cms#1048]
1. Config to use eloquent `statmic.users.repository = eloquent`
2. Create an group, link a roles and Save.
After redirect you can see this error.

![image](https://user-images.githubusercontent.com/12527881/69953012-f7e4d400-152a-11ea-8c83-ce1ea2e9665f.png)

Same error at `/cp/users` when I filter user by role or group
![image](https://user-images.githubusercontent.com/12527881/69954339-a558e700-152d-11ea-9ce6-33468f6a4dcf.png)

**Comment by edalzell** [comment]
did you run the migrations?

**Comment by tolawho** [comment]
Yes. I did it

**Comment by edalzell** [comment]
are those columns in the tables?

**Comment by tolawho** [comment]
All table migrated. 
![image](https://user-images.githubusercontent.com/12527881/70016135-0d511100-15b2-11ea-9543-94ec54a9e49d.png)
![image](https://user-images.githubusercontent.com/12527881/70016157-1f32b400-15b2-11ea-921c-ee4eb4db35d7.png)
![image](https://user-images.githubusercontent.com/12527881/70016214-4b4e3500-15b2-11ea-86d3-0002360b2860.png)
