### ISSUE TITLE
Video fieldtype doesn't work with Vimeo file links

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/cms#10508]
### Bug description

When you paste in a Vimeo file link the iFrame shows an error, this appears to be because the URL is altered.

### How to reproduce

In a video fieldtype enter a direct Vimeo link, for example `https://player.vimeo.com/progressive_redirect/playback/990017866/rendition/1080p/file.mp4?loc=external&log_user=0&signature=225090dffedcfd0f6a1adb15e8bf69092b8400c069f54e78fe48b44bddf37240`

This will just show an error message (Sorry, we're having a little trouble).

The source of the iframe when inspecting is `https://player.vimeo.com/progressive_redirect/playback/990017866/rendition/1080p?h=file.mp4&loc=external&log_user=0&signature=225090dffedcfd0f6a1adb15e8bf69092b8400c069f54e78fe48b44bddf37240`

It appears the `...1080p/file.mp4?loc=...` is changed to `...1080p?h=file.mp4&loc=...` which doesn't work. Looks like it's the code in VideoFieldtype.vue that breaks this

```
if (embed_url.includes('vimeo')) {
    embed_url = embed_url.replace('/vimeo.com', '/player.vimeo.com/video');
    if (embed_url.split('/').length > 5) {
        let hash = embed_url.substr(embed_url.lastIndexOf('/') + 1);
        embed_url = embed_url.substr(0, embed_url.lastIndexOf('/')) + '?h=' + hash.replace('?', '&');
    }
}
```

Not sure if this code just needs removing or updating. 

### Environment

```yaml
Statamic 5.17.0
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Are you able to provide the URL of a valid Vimeo video that we can test with?

**Comment by dannyuk1982** [comment]
Sorry, that one was working yesterday, someone  mjst have deleted. This one working for you?

https://player.vimeo.com/progressive_redirect/playback/990169258/rendition/1080p/file.mp4?loc=external&log_user=0&signature=275be15f3630d1ca3e7a51456a911e11e3ba9fddf89911f49140f6de95357e05

**Comment by duncanmcclean** [comment]
Yup, thanks!

**Comment by dannyuk1982** [comment]
Do you know if this is on the roadmap for the near future? Launching a site this month and just need to know whether to use a video field or not.

**Comment by duncanmcclean** [comment]
> Do you know if this is on the roadmap for the near future? Launching a site this month and just need to know whether to use a video field or not.

Just opened a PR to fix it: #10552.

**Comment by dannyuk1982** [comment]
Still broken for me in 5.19

Adding
`https://player.vimeo.com/progressive_redirect/playback/993448976/rendition/720p/file.mp4?loc=external&log_user=0&signature=e91f71fbb491621a358d9927623272b288279bbbce92f62b460ba0816015a18d`

gets changed to 
`https://player.vimeo.com/progressive_redirect/playback/993448976/rendition/720p?h=file.mp4&loc=external&log_user=0&signature=e91f71fbb491621a358d9927623272b288279bbbce92f62b460ba0816015a18d`

**Comment by duncanmcclean** [comment]
The fix hasn't been released yet. It'll be included in the next release.

**Comment by dannyuk1982** [comment]
Oh, sorry, my bad. Thanks
