### ISSUE TITLE
UI: Handle many tabs

### ISSUE THREAD

**Issue by dougstjohn** [statamic/cms#1050]
This is an edge case if you have many tabs on your content.

1) Tabs go beyond the content box when large screen.
<img width="1268" alt="wide-screen" src="https://user-images.githubusercontent.com/3673451/69991408-d244d400-1504-11ea-97d9-d9a349079693.png">

2) Some tabs are cut off or hidden when smaller screen.
<img width="821" alt="narrow-screen" src="https://user-images.githubusercontent.com/3673451/69991403-cf49e380-1504-11ea-87a2-9ba74c1d269c.png">

**Comment by jackmcdade** [comment]
This is a fair bug report. Gotta solve it, but it's quite a bit of work to check how many they are, collapse the rest of em into a final tab when we run out of room, and work out the cases for paginating which tabs are visible based on the current one. 

We'll get to it, but I'm just not quite sure when give its slightly edge-casey nature.

**Comment by goellner** [comment]
Running into this problem too now. 

We had the same problem with an interface we did for a software. I attach an image, how we solved this.

![tabs](https://user-images.githubusercontent.com/3986748/78145048-b1e44200-7430-11ea-87db-486c86ea372c.png)

If you want I can share our vue.js code for this with you @jackmcdade

**Comment by sebabal** [comment]
Another possibility when you have many tabs is to stack them vertically on the side

**Comment by twd3** [comment]
My 2 cents, I think these tabs should just change to accordions on small or medium screens. Or who knows, maybe just start as accordions and stay accordions...

**Comment by twd3** [comment]
I forgot that my admins are going to see asset containers for ONLY THEM via their role so this really is not a problem anymore for me. The super admin is the only one who see's all of these tabs so no biggie.

**Comment by jimblue** [comment]
A simple fixe that could also be nice for mobile user is a horizontal scroll system.

**Comment by philipboomy** [comment]
Ran into this problem too. Perhaps just vertically stack them on flex-wrap. I prefer not looking perfect vs not being able to see or select the tabs. Right now my client cant edit the last 2 tabs.

**Comment by goellner** [comment]
@philipboomy 

cp.css
```
@media (min-width: 768px) {
  .tabs a {
      min-width: 0 !important;
  }
}
```

and in AppServiceProvider.php in the boot method:

```
Statamic::style('app', 'cp');
```

**Comment by jelleroorda** [comment]
A neat solution I saw from Ant design, not 100% sure how you would implement that. You can play with it on this page: https://antdv.com/components/tabs/#Tabs

![tabs](https://user-images.githubusercontent.com/9193686/102472329-7e952200-4056-11eb-80b9-cea9a913848b.gif)


Note: it only shows the arrows when they don't fit in the viewport; you might have to resize with the 'mobile inspector' view. to see it on action.

**Comment by callum-veloxcommerce** [comment]
+1

This needs some sort of resolution, at this point I'd pay for a third party extension that fixes it with a really nice solution.

**Comment by rrelmy** [comment]
Would be great if there is a fix for it in core soon, we use a hacky custom css like goellner to make it possible to reach the tabs

<img width="916" alt="Edit_Global_Set_‹_Statamic" src="https://user-images.githubusercontent.com/442683/117475375-3f5f6300-af5c-11eb-98bd-a268265bc811.png">

**Comment by jasonvarga** [comment]
I just noticed GitHub does this very nicely.

![Screen%20Capture%20on%202021-07-24%20at%2015-17-23](https://user-images.githubusercontent.com/105211/126879184-2e842a8f-a999-48db-a14a-b3e56a63eebd.gif)
