### ISSUE TITLE
Adding structure through CP wizard on Multi-Site breaks CP

### ISSUE THREAD

**Issue by aerni** [statamic/cms#1052]
Creating a structure in the CP on a multi-site setup ends in `Page Not Found`. This is because it doesn't automatically create the `sites` handle in the structure's `yaml` file. After adding it manually the CP works again.

It would probably be a good idea to let the user choose the sites, where a structure should be available, through the CP wizard. The same when creating a collection.

**Comment by jackmcdade** [comment]
Thanks for the heads up! Structures are getting a bit of a rework this week. Stay tuned.

**Comment by jasonvarga** [comment]
Should be resolved in the next release.
