### ISSUE TITLE
shortcut for opening the revision publish pane

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1053]
Would it be possible to provide another shortcut for saving and publishing in addition to the shortcut for saving (cmd+s)?

**Comment by jackmcdade** [comment]
What key command would you suggest?

**Comment by WiebkeVog** [comment]
Maybe `mod+shift+l` for _launch_

**Comment by jackmcdade** [comment]
I think i'm going to pass on this one. I'd like to avoid the possibility of accidentally publishing something with a key combo you weren't aware of. If the default behavior is publish, `cmd+s` will do so, otherwise it should be an explicit [click] action. 👍

**Comment by abasse** [comment]
> I think i'm going to pass on this one. I'd like to avoid the possibility of accidentally publishing something with a key combo you weren't aware of. If the default behavior is publish, `cmd+s` will do so, otherwise it should be an explicit [click] action. 👍

-> This was actually to trigger the publish dialog on the sidebar for publishing/revisions. There is is still a final click needed for publishing.

**Comment by jasonvarga** [comment]
Closing in favor of statamic/cms#65
