### ISSUE TITLE
PHP 7.4 - join requires correct order

### ISSUE THREAD

**Issue by codedge** [statamic/cms#1055]
In PHP 7.4 the order of params for the [`join()`](https://www.php.net/manual/en/function.join.php) function respects the order of params passed.

1. Currently in method [`assemble`](https://github.com/statamic/cms/blob/master/src/Facades/Endpoint/Path.php#L139) the wrong order is used.

* Wrong: `join($args, '/')`
* Right: `join('/', $args)`

2. Another one in [`getParent`](https://github.com/statamic/cms/blob/master/src/Tags/ParentTags.php#L89)

# How to reproduce

1. Use PHP 7.4 for the project
2. Try to upload an asset in control panel

![image](https://user-images.githubusercontent.com/4409904/70059966-fb876200-15e1-11ea-9276-e30dddf1e77b.png)

**Comment by jasonvarga** [comment]
Nice catch

**Comment by codedge** [comment]
Do prefer a PR or quickly fix it yourself? Just asking also for further things I might spot.

**Comment by jasonvarga** [comment]
I can fix this one, but feel free to open PRs in the future. Up to you.
