### ISSUE TITLE
Creating UL/OL elements inside bard wraps li content in p

### ISSUE THREAD

**Issue by twd3** [statamic/cms#1058]
In a bard if you make a ul or ol it wraps the content of the li in a p tag.
What I wanted:
```
<ol>
<li>Something</li>
<li>Something</li>
<li>Something</li>
</ol>
```
What I get:
```
<ol>
<li><p>Something</p></li>
<li><p>Something two</p></li>
<li><p>Something three</p></li>
</ol>
```

I think this is separate from #619

**Comment by jackmcdade** [comment]
Yep, that's how ProseMirror works. There's nothing we can do about that. We'll just all need to style accordingly 😊

**Comment by jasonvarga** [comment]
(Because it's perfectly fine to have multiple paragraphs or whatever else inside a list item)

**Comment by pevawi** [comment]
Maybe this helps for someone. To create a simple ul/ol layout add this to your CSS:
`
ul {
  list-style-type: disc;
  padding-inline-start: '1em';
}
ol {
  list-style-type: decimal;
  padding-inline-start: '1em';
}
`

**Comment by brianlangley** [comment]
Has anyone found a solution for this? Having the exact problem, each is being wrapped in a p tag

**Comment by hlorofos** [comment]
you can use `preg_replace('/(<li>)(<p>)+/', '$1', $articleDetail->content);`

**Comment by replete** [comment]
Did not expect to see this weird markup, but it's a simple enough fix in antlers as ugly as it is
```antlers
{{ if type == "text" }}
    {{ text | replace ('<li><p>','<li>') | replace('</p></li>','</li>') }}
```

If there's a way to permanently fix this I would love to know, because this markup does not make sense.

**Comment by jackmcdade** [comment]
There is no native way to "fix" it because that's the way ProseMirror handles lists. It _does_ make sense if you think about how many different elements could all be inside a list and this ensures that all content inside a list item has a wrapping element. It's a structural thing.

**Comment by replete** [comment]
I understand why it's a wontfix, seems like other people have also given up on trying to fix this semantic content issue
https://discuss.prosemirror.net/t/removing-the-default-paragraph-p-inside-a-list-item-li/2745

I guess I'll see I get on with <span>:

```antlers
{{ if type == "text" }}
    {{ text | replace ('<li><p>','<li><span>') | replace('</p></li>','</span></li>') }}
```

Having to override paragraph styles when in a list (because they are always in list items) feels hacky

**Comment by replete** [comment]
Is there a way to configure ProseMirror to only allow text in list items?

Google Lightspeed DOM element count is a part of the ranking, so there is incentive to not use unnecessary tags.

**Comment by jackmcdade** [comment]
Nope. This comes up a lot. 

More context:

https://github.com/statamic/cms/issues/1058
https://discuss.prosemirror.net/t/removing-the-default-paragraph-p-inside-a-list-item-li/2745/14

**Comment by twd3** [comment]
> Is there a way to configure ProseMirror to only allow text in list items?
> 
> Google Lightspeed DOM element count is a part of the ranking, so there is incentive to not use unnecessary tags.

Replete just use this addon. It can get rid of those and do A TON MORE! [https://statamic.com/addons/jacksleight/bard-mutator](url) See: [https://jacksleight.dev/docs/bard-mutator/examples#remove-paragraph-tags-inside-list-items](url)
