### ISSUE TITLE
Deleting a user group results in error Call to a member function handle() on null

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1064]
I created a Permission
I created a Group to which I assign this Permission
I created a User to which I assigned this Group
I deleted the Permission: OK
I deleted the Group: OK
I clicked on Users in the sidebar: I got a debug bar message ```Call to a member function handle() on null```
Shouldn't it be possible to access users related to a deleted group?

**Comment by jesseleite** [comment]
Can't recreate anymore, I think this has been fixed.  Feel free to reopen if you're still experiencing 👍
