### ISSUE TITLE
Bard issue when inserting code block after image

### ISSUE THREAD

**Issue by peimann** [statamic/cms#1069]
In bard insert image then in whitespace right bottom of image block try to add code block, it will remove image. But nothing work in that space (right bottom of image). Try to add anything else, nothing working correctly.

**Comment by jackmcdade** [comment]
Confirmed.

**Comment by OleksiiBrylin** [comment]
The same issue. Only Enter and Backspace work. 
![Screenshot](https://user-images.githubusercontent.com/13660488/85049351-3c6d4f80-b19d-11ea-91d2-019ef3bd7b01.png)

**Comment by jelleroorda** [comment]
Open sesame
