### ISSUE TITLE
Ability for filters to reset sort column to default

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#1070]
When the collections filter changes, the sort column should revert to the default/initial value, since it's possible that a single collection left in the filter doesn't have the field that was sorted on before.

**Comment by jasonvarga** [comment]
I can see where resetting the sort would be useful for some filters but not all of them.
Perhaps filters can somehow define whether they want to trigger resetting of sorting.

**Comment by sauerbraten** [comment]
Yeah, that sounds useful!

**Comment by sauerbraten** [comment]
Will this be addressed/affected by https://github.com/statamic/cms/pull/1405?

**Comment by jackmcdade** [comment]
Is this still something you'd find useful or have you solved this in a custom way?

**Comment by jasonvarga** [comment]
Hey there, we haven’t heard back on this for a while so I’m going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!
