### ISSUE TITLE
API/Headless Mode Globals missing

### ISSUE THREAD

**Issue by strebl** [statamic/cms#1071]
Thanks for the great CMS - I like it a lot so far!

I noticed, that the globals controller in the api mode isn't returning any data:

```
class GlobalsController extends CpController
{
    use TemporaryResourcePagination;

    public function index(Request $request)
    {
        // TODO: Need to think this one through more.
        return [];
    }
}
```

Is there an issue to track the progress or priority on that? I didn't find one.

**Comment by jasonvarga** [comment]
API is not ready yet, we'll scream it from the rooftops when it is.

https://github.com/statamic/cms/issues/53

**Comment by strebl** [comment]
Thanks @jasonvarga
