### ISSUE TITLE
Structure of type "collection" cannot be changed to "navigation"

### ISSUE THREAD

**Issue by codedge** [statamic/cms#1073]
After I created a structure as _"Manage a Collection"_ and I want to later change it to _"Build a Navigation"_  the changes are not saved.

There is also no error in the console.

**Comment by jackmcdade** [comment]
Thanks for the heads up! Structures are getting a bit of a rework this week. Stay tuned.

**Comment by jackmcdade** [comment]
Structures will not be "changeable" anymore after the upcoming refactor. It'll make sense when it's ready, stay tuned! :)
