### ISSUE TITLE
Blueprint tab section "maximise" button doesn't work

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#1076]
When adding sections to a blueprint, there's a little "full screen"-style icon that when clicked, makes the section go full-width:

![image](https://user-images.githubusercontent.com/545339/70379374-a9b54380-1923-11ea-9883-ba062edad59b.png)

I assumed this would then make this section full-width when adding an entry, however when saving the blueprint, it doesn't seem to save that this button was clicked, and goes back to how it was before:

![image](https://user-images.githubusercontent.com/545339/70379365-9013fc00-1923-11ea-9912-a01f7755200a.png)

Am I misunderstanding what this button does, or is this broken?

**Comment by jasonvarga** [comment]
It just gives the panel a little more room so you can see your field widths better.
