### ISSUE TITLE
User login/register tags and controllers need love

### ISSUE THREAD

**Issue by andrewying** [statamic/cms#1080]
By default, the login POST action in v3 has an url of `!/auth/login`. However, when using the `user:login_form` tag the form is submitted to `login`.

**Comment by syntheticminds** [comment]
Same with `user:register_form`. Getting /register instead of [!/auth/register](url)

**Comment by jasonvarga** [comment]
Thanks for pointing that out. Looks like those tags need a bit of love in general. We brought them over as-is from v2. Will get on that soon!

**Comment by syntheticminds** [comment]
Hi guys. We're kinda blocked by this. Can you give any indication of when this might be ready? Thanks.

**Comment by jesseleite** [comment]
Should be good, closing this.  More form/login/register tag polish coming in next beta as well 👍
