### ISSUE TITLE
Can't upload image after updating to beta.5

### ISSUE THREAD

**Issue by strebl** [statamic/cms#1083]
I can't upload images and see following javascript error in the CP after updating to beta.5: `t(...).dmUploader is not a function`.

I tried to run `php artisan statamic:install` which didn't resolve the problem.

Downgrading to beta.4 "resolved" the issue.

Do I miss something or is that a new bug?

**Comment by jasonvarga** [comment]
Bug, sorry about that, thanks for pointing it out.

**Comment by strebl** [comment]
No problem 👍

**Comment by jasonvarga** [comment]
Fixed in 2832c1d3
