### ISSUE TITLE
CP UI: missing styles for Multi-Site

### ISSUE THREAD

**Issue by psren** [statamic/cms#1084]
![image](https://user-images.githubusercontent.com/1016798/70522040-a64ad380-1b40-11ea-940c-51bcd0bf2426.png)

The UI for Structures is no yet implemented correctly :-)

**Comment by peterkelm** [comment]
@psren, fully agree. That UI part is very confusing and quite counter-intuitive (using statamic 3.0b11). 

Possible workaround: use the site/language switcher in the top menu (right of the search field) to switch between the sites/languages. That displays the "structures" in the selected language.

**Comment by jasonvarga** [comment]
Should be resolved in the next release.
