### ISSUE TITLE
CP UI: "prepend" is not <label>

### ISSUE THREAD

**Issue by psren** [statamic/cms#1085]
When I click on the "Date"-Icon of a date field the field itself isn't focused and the calendar popup does not open. Same for the Time.

Maybe this should be `<label>`s for the field?

![image](https://user-images.githubusercontent.com/1016798/70531711-c5a02b80-1b55-11ea-84c5-3b5271ff26c0.png)

**Comment by jackmcdade** [comment]
Note for Future Jack™

This involves moving all the `date-container` markup into the `v-date-picker` [custom slot](https://vcalendar.io/datepicker.html#custom-slot) and moving the `slot-scope`, `v-bind`, and `v-on` attributes on the input, as well as the`:class` bindings on the picker. And accounting for inline mode. And read only mode.

**Comment by jasonvarga** [comment]
Oh is that all.

**Comment by jackmcdade** [comment]
Because how how widely varied the possibilities are with prepend and appends, I've decided to not implement this.
