### ISSUE TITLE
assets validation fails when using s3

### ISSUE THREAD

**Issue by krokusmoen** [statamic/cms#10859]
After recent update I can't upload to my s3 in my Bard.

It works manually directly in assets, but not in creating an entry in any collection.

![image](https://github.com/user-attachments/assets/7022c5ea-74f7-4f00-9665-6231c3a9ca58)

**Comment by ryanmitchell** [comment]
Duplicate of https://github.com/statamic/cms/issues/10856 ?

**Comment by krokusmoen** [comment]
Ah, yes. Same issue, @ryanmitchell

**Comment by duncanmcclean** [comment]
Closing in favour of #10856.
