### ISSUE TITLE
Date + time field too large for sidebar

### ISSUE THREAD

**Issue by psren** [statamic/cms#1086]
If i add a Date+Time-Field to the `sidebar` the default date-Format is too large.

![image](https://user-images.githubusercontent.com/1016798/70533397-4d3b6980-1b59-11ea-8efc-1516c966198e.png)

**Comment by jackmcdade** [comment]
Is this still an issue?I can't recreate this anymore so I'm going to assume it's been fixed in some of the recent CSS fiddling. Please feel free to reopen with browser details if you can recreate!

**Comment by psren** [comment]
It's fixed already
