### ISSUE TITLE
Asset upload (to S3) only works outside of root

### ISSUE THREAD

**Issue by dwyer14** [statamic/cms#1088]
**v3.0.0-beta.6**

Trying to upload assets to S3, but it only works when uploading into a folder (ie, not the root). When in the root, I'm getting the following error:

`Found 1 error while validating the input provided for the PutObject operation: [Key] expected string length to be >= 1, but found string length of 0`

Let me know if there's anything else I can provide that would be helpful. 👍

**Comment by codedge** [comment]
I spent some time debugging:

- Issue only comes up when upload a file directly to the asset container root
- Problem exists in creating a directory: If not (sub) directory is specified, it tries to create it at `/` which obviously is not correct.

## Findings

- [Filesystem/AbstractAdapter](https://github.com/statamic/cms/blob/master/src/Filesystem/AbstractAdapter.php#L29) tries to create a directory with `.`
- [Filesystem/AbstractAdapter](https://github.com/statamic/cms/blob/master/src/Filesystem/AbstractAdapter.php#L111): Path gets _normalized_ from `.` to `/`
- Boom, error..

## Possible solution

Maybe something like 
```php
if(pathinfo($path)['dirname'] !== '.') {
    $this->makeDirectory(pathinfo($path)['dirname']);
}
```

would prevent the creation of the directory. Then the file upload afterwards runs fine.

This is tested with and without subfolder - works so far.

@jasonvarga What do you think?

**Comment by jasonvarga** [comment]
Nice sleuthing! 🔍

**Comment by dwyer14** [comment]
@jasonvarga After updating to beta.8, I'm now getting "Server Error" on every ajax request...any idea what's happening, there? No details in the actual response, just:
```json
{
    "message": "Server Error"
}
```
