### ISSUE TITLE
Global with multiple Replicators not processed correctly

### ISSUE THREAD

**Issue by JesperWeCode** [statamic/cms#1090]
Statamic V3 Beta 6

I've got this Global called Navigation, which has:
Logo -> Asset
Links -> Replicator
Righthand Links -> Replicator

They're saved correctly into the .yaml file, but when it's sent to the view, it seems like the second replicators values isn't being processed correctly, and therefore can't be used correctly in the Antlers template

Output from Laravel debugger
```
array:3 [▼
  "logo" => Statamic\Fields\Value {#1129 ▶}
  "links" => Statamic\Fields\Value {#1136 ▶}
  "righthand_links" => array:2 [▼
    0 => array:5 [▶]
    1 => array:5 [▶]
  ]
]
```

**Comment by jasonvarga** [comment]
Can you please post your blueprint?

**Comment by JesperWeCode** [comment]
After i've had the second Replicator removed (because i found another way), and not inserting it again, then it works perfectly fine, and the values in the debug bar is correct.
So i can't really seems to replicate this issue again.. :/

**Comment by jasonvarga** [comment]
Magic! Let us know if you run into it again.
