### ISSUE TITLE
Activating Site on Page returns 404

### ISSUE THREAD

**Issue by JesperWeCode** [statamic/cms#1094]
I'm having a one page site, which i needs to be translated, and therefore i'm using multisite to do this.
It has to be in english (default), and then Danish and German.
The problem is that when i press on a Site on the actual Page (on the righthand side), i can see in the network console that it just returns a 404, and a loader is just keeping on going, and of course nothing happens.

My sites.php file looks like the following:
```
'sites' => [

    'default' => [
        'name' => config('app.name'),
        'locale' => 'en_US',
        'url' => '/',
        'flag' => 'en'
    ],
    'dk' => [
        'name' => config('app.name') . ' - DK',
        'locale' => 'da_DK',
        'url' => '/dk/',
        'flag' => 'dk'
    ],
    'de' => [
        'name' => config('app.name') . ' - DE',
        'locale' => 'de_DE',
        'url' => '/de/',
        'flag' => 'de'
    ],

]
```

And where all the magic should happen, is when i press the following "inactive sites":
![Screenshot 2019-12-11 at 12 33 56](https://user-images.githubusercontent.com/58592276/70693625-1c287980-1cbe-11ea-9be1-6983e5dc216f.png)

**Comment by manogi** [comment]
I have the same problem. Here's my sites array:
```
'sites' => [
        'default' => [
            'name' => 'LIR Mainz',
            'locale' => 'de_DE',
            'url' => '/',
        ],
        'en' => [
            'name' => 'LIR Mainz / English',
            'locale' => 'en_US',
            'url' => '/en/',
        ],
 ]
```

**Comment by manogi** [comment]
As you can see my default is German. The 404 happens when the following url is called (on my "home" page): 
<img width="314" alt="CleanShot 2019-12-13 at 11 19 02@2x" src="https://user-images.githubusercontent.com/1419634/70792853-64b56500-1d9a-11ea-9683-fc7d51cd1017.png">

**Comment by abinadi** [comment]
I have the same issue. Here is my site array:

```
    'sites' => [
        'english' => [
            'name' => config('app.name'),
            'locale' => 'en_US',
            'url' => '/',
        ],
        'spanish' => [
            'name' => config('app.name_es'),
            'locale' => 'es_MX',
            'url' => '/es/',
        ],
    ]
```

**Comment by abinadi** [comment]
I followed the multi-site knowledgebase article: https://statamic.dev/knowledge-base/converting-from-single-to-multi-site

**Comment by jasonvarga** [comment]
Thanks everyone, no need to post your site arrays anymore 👍
