### ISSUE TITLE
Plus sign between replicator sets kinda small

### ISSUE THREAD

**Issue by manogi** [statamic/cms#1106]
I have the feeling this was meant to be styled a bit dfferently. Maybe also a round button? This way it is really hard to see.

![CleanShot 2019-12-13 at 14 14 34@2x](https://user-images.githubusercontent.com/1419634/70802913-12cd0900-1db3-11ea-9354-1627fbf9d290.png)

**Comment by jasonvarga** [comment]
There’s supposed to be more top margin, but otherwise that’s intended.

**Comment by manogi** [comment]
I am sure more top margin does the trick.
