### ISSUE TITLE
Markdown and noparse - no output

### ISSUE THREAD

**Issue by codedge** [statamic/cms#1111]
When I write the following content in my markdown file, I get no output. Just blank.
````
```
{{ noparse }}
    {{ structure:pages }}
    <a class="block lg:inline-block mt-4 lg:mt-0 mr-10 text-gray-500 hover:text-gray-800 font-bold {{ if is_current || is_parent }} border-b-4 border-gray-400{{ /if }}"
       href="{{ url }}">
        {{ title }}
    </a>
    {{ /structure:pages }}
{{ /noparse }}
```
````

## Expected output

```
{{ structure:pages }}
<a class="block lg:inline-block mt-4 lg:mt-0 mr-10 text-gray-500 hover:text-gray-800 font-bold {{ if is_current || is_parent }} border-b-4 border-gray-400{{ /if }}"
       href="{{ url }}">
{{ title }}
</a>
{{ /structure:pages }}
```

Do I use the  `noparse` wrongly with the Markdown backticks?

### Update 1

Even when putting the `noparse` tag into the template file - it just does output blank lines.

```
<div class="container mx-auto flex flex-col max-w-4xl md:pt-8">
    <h1 class="text-4xl mb-6">
        {{ title }}
    </h1>
    {{ content | noparse }}
</div>
```

**Comment by jasonvarga** [comment]
Using `{{ content | noparse }}` in your template would be the better way to do it.

When you tried it that way, did you remove the noparse tag pair from inside your markdown?

**Comment by codedge** [comment]
Yes, I did that.

**Template**
````
<div class="container mx-auto flex flex-col max-w-4xl md:pt-8">
    {{ content | noparse }}
</div>
````

**my-blog-post.md**
````
Here comes the code snippet:
```
<div class="container mx-auto flex flex-col pt-8">
    <h1 class="text-4xl mb-6">
        {{ title }}
    </h1>
    {{ content }}
</div>
```
You can see... nothing.
````

**Rendered result**
![image](https://user-images.githubusercontent.com/4409904/70945329-3e6f1e00-2055-11ea-9e33-5e606e0c6259.png)

No idea if I do something wrong or if the `noparse` just works wrongly.

**Comment by jasonvarga** [comment]
Are you using Vue?

**Comment by codedge** [comment]
Yes, I do. I guess I now know why it doesn't work..

**Comment by jasonvarga** [comment]
You can wrap your template in v-pre:

```
<div v-pre>
  {{ content | noparse }}
</div>
```

**Comment by codedge** [comment]
Superb! That's it!
