### ISSUE TITLE
[feature request] add-button for replicator with single set adds item directly

### ISSUE THREAD

**Issue by manogi** [statamic/cms#1113]
This would be a nice to have: we have lots of replicators with just one kind of set. It would be a smoother experience in the CP if a click on the plus button would not open a dropdown showing just the one set but add the item immediately.

**Comment by mikemartin** [comment]
Duplicate FR in statamic/ideas: https://github.com/statamic/ideas/issues/29

**Comment by manogi** [comment]
Dammit - didn't know about statamic/ideas
