### ISSUE TITLE
Entry links in Bard field break if "Save as HTML" 

### ISSUE THREAD

**Issue by wesort** [statamic/cms#11168]
### Bug description

Links from a Bard to an entry work at first but later link to blank pages. 

The link has broken by pointing to the `entry::123...` (where `123...` is the ID of the entry being linked to).

### How to reproduce

- Have a Bard field with the "Save as HTML" toggle set to `true`. (not an issue if this toggle is `false`)
- Use this Bard field to select text and create a link using the "Entry" option.
- Visit the front-end and initially this works as expected. 
- However, on further visits to edit the page in the CP (or after a page refresh), saving that page will break the link: 
  - The link is broken on the front-end as the link is pointing to `entry::{id}`
  - eg: `<a href="entry::b1d7640f-4921-4f65-ab73-bfaa82a2a64e">`
  - Broken as the "Entry" option has reverted to "URL" on the Bard link button.

_Workaround_
- Don't use the "Save as HTML" option (not even sure why I was using that option on the project I experienced the bug on!)

[statamic-broken-entry-link.webm](https://github.com/user-attachments/assets/932d7810-6e3f-41e7-860d-098d43138796)

### Environment

```yaml
Tested on [demo.statamic.com/cp](https://demo.statamic.com/cp) running `v5.39.0`
```

### Installation

Other (please explain)

### Additional details

`demo.statamic.com`

**Comment by duncanmcclean** [comment]
Are you able to provide the full output of `php please support:details`?

**Comment by wesort** [comment]
I recreated it on `demo.statamic.com` to remove the complexity from the project I discovered it in.

I presume that's far easier to debug right?

**Comment by wesort** [comment]
Fair enough. 

```
Environment
Application Name: Redacted
Laravel Version: 10.48.25
PHP Version: 8.2.1
Composer Version: 2.8.3
Environment: dev
Debug Mode: ENABLED
URL: dev.redacted.co.uk
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.41.0 Solo

Statamic Addons
jacksleight/statamic-bard-mutator: 3.0.3
```
