### ISSUE TITLE
Table ui mobile scroll checkbox 

### ISSUE THREAD

**Issue by vitalijalbu** [statamic/cms#11169]
### Bug description

![IMG_5478](https://github.com/user-attachments/assets/cd9a6b8d-dbb0-4aea-bdee-70c1026555f6)

as you can see the checkbox must have a bg with z-index, something like fixed col.
Also the action … button i think must be fixed

### How to reproduce

Just add multiple columns in a table entries 

### Environment

```yaml
Latest cms version
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Are you able to provide the full output of `php please support:details`?

**Comment by duncanmcclean** [comment]
I think this behaviour is intentional so you can run actions, whilst viewing more info about a particular entry. It was introduced in #7676.

**Comment by vitalijalbu** [comment]
> Are you able to provide the full output of `php please support:details`?

i jsut opened the demo statamic link (from github) [https://demo.statamic.com/cp/auth/login](here)

**Comment by Upending36** [comment]
Thank you.


Sent from the all new AOL app for iOS


On Tuesday, November 26, 2024, 4:27 PM, Vitalie ***@***.***> wrote:





Are you able to provide the full output of php please support:details?


i jsut opened the demo statamic link (from github) https://demo.statamic.com/cp/auth/login
