### ISSUE TITLE
Ability to customize the API return values

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1118]
Right now the controller returns an EntryResource that just does $entry->toAugmentedArray().

People may want to provide more or less data.

Maybe the resource class could be configurable, and they could just create their own.

**Comment by jesseleite** [comment]
User can now:

```php
Resource::map([
    \Statamic\Http\Resources\EntryResource::class => \App\Http\Resources\EntryResource::class,
]);
```

**Comment by jasonvarga** [comment]
Would a regular binding not work?

``` php
app()->bind(
  \Statamic\Http\Resources\EntryResource::class, 
  \App\Http\Resources\EntryResource::class
);
```

**Comment by jesseleite** [comment]
Tried that first.  It throws error without the closure.

**Comment by jesseleite** [comment]
Also, this allows them to map multiple at once via array:

```php
Resource::map([
    \Statamic\Http\Resources\EntryResource::class => \Custom\EntryResource::class,
    \Statamic\Http\Resources\TermResource::class => \Custom\TermResource::class,
    \Statamic\Http\Resources\UserResource::class => \Custom\UserResource::class,
]);
```

...In an app or addon service provider.
