### ISSUE TITLE
API should adjust entry URLs in its responses

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1119]
In the entry index or show routes, the `url`/`uri`/`permalink` uses the value coming from the collection's `route`.

If you're only using the API, you _could_ change your collection's route to `/api/collections/blog/entries/{id}`, but that's an extra step that seems a little unnecessary. If you're using the API _and_ the front-end, that wouldn't work anyway because you couldn't have regular front-end entry URLs.

The EntryResource could override `url` etc with the API urls.

**Comment by jesseleite** [comment]
What about leaving `url` and adding an explicit `api_url`?

**Comment by jasonvarga** [comment]
Sounds like a nice solution.
