### ISSUE TITLE
Entries API endpoints

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1120]
Should be able to:
 - list entries in a collection (`/api/collections/{collection}/entries`)
    - filter them, sort them, and paginate them.
 - view individual entries (`/api/collections/{collection}/entries/{id}`)

**Comment by Sulyci** [comment]
Hi,

I have a problem.
This is not working: /api/collections/{collection}/entries/{id}

My api.php snippet:

```
'resources' => [
        'collections' => [
            'pages' => true
        ],
    ],
]
```

What am I missing?

**Comment by duncanmcclean** [comment]
This issue is over 4 years old, please [open a discussion](https://github.com/statamic/cms/discussions/new/choose) if you need help.

**Comment by Sulyci** [comment]
Thank you for your response! It's working now. I had to add filter maybe because of I use multisite.
