### ISSUE TITLE
Migrating from v2: {{ theme:output }}

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1125]
In the Storyteller theme, ```{{ theme:output image.svg}}``` sends .svg image to the front-end.
What could be a nice way to do that in v3?
I tried with a global, but no dice:
In my partial:
```
{{ global:footer_img }
```

In my global.yaml:
```
data:  
  footer_img:
    - img/image.svg
  ```

Thanks

**Comment by ebeauchamps** [comment]
This is working!
```{{ global:footer_img | image }}```

**Comment by jackmcdade** [comment]
You can also do `{{ global:footer_img:url }}` 👍

**Comment by jackmcdade** [comment]
Also, you can still use the theme:output tag, just make sure the file is in your `resources` dir instead of `site/themes/`
