### ISSUE TITLE
Migrating from v2: array_key_exists(): The first argument should be either a string or an integer

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1126]
Migrating the Storyteller theme for sandbox purpose.
Visiting ```http://storyteller.local/articles/bard```brings an exception, perhaps related to a modifier: ```Statamic\Modifiers\Modify::modify
:0```

Full exception here:
https://flareapp.io/share/Bm06J67x#F73

Wondering if this is still possible in v3:
```
{{ if image | get:alt }}<p class="text-base text-grey-dark text-center mt-2 mb-5 italic">{{ image | get:alt }}</p>{{ /if }}
```

Would appreciate a little help!

**Comment by jasonvarga** [comment]
This is fixed for next release, however in v3 you don't need the `get` modifier. You can simply do `{{ if image:alt }}`
