### ISSUE TITLE
When the locales template tag is on 404-page, then the 404 page displays a internal server error

### ISSUE THREAD

**Issue by matrad** [statamic/cms#1135]
If we have the `{{ locales }}` tag on a page-layout containing the 404-page a internal server error ocurrs.

`layout.antlers.html`:

```
    {{ locales }}
        <link rel="alternate" hreflang="{{ locale:key }}" href={{ url }}" />
    {{ /locales }}
```

![Bildschirmfoto 2019-12-19 um 16 34 52](https://user-images.githubusercontent.com/660903/71186479-938d7880-227d-11ea-9653-3468697c2915.png)

**Comment by jasonvarga** [comment]
What do you expect it to show?

**Comment by matrad** [comment]
When a page is not found we should render a 404 error, not a 500 internal server error (also http status code).

BTW this Tag does not work: https://github.com/statamic/v2-hub/issues/46
`{{ if response_code == "404" }}`

**Comment by jasonvarga** [comment]
Sorry yes I understand that it shouldn't throw an error, but I'm asking what you expect the locales tag should do on a 404 page.

**Comment by matrad** [comment]
That's a good question, it would be ok if the locales is an empty array because there exists no page and also no translations

**Comment by jasonvarga** [comment]
That's probably the right behavior. 👍 

I'm looking at the response_code variable too. It should return 404, not 200.
