### ISSUE TITLE
Collections shouldn't have all columns "on" by default.

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#1137]
It can be pretty crazy if you have a big blueprint. Let's stick to title, slug, date (if present), and author (if present).

**Comment by jasonvarga** [comment]
We have `listable` option that you can set, which defaults to `true`.

Should we default to `hidden`? https://statamic.dev/blueprints#unlisted-fields

**Comment by jackmcdade** [comment]
Yes, let's do that. And also add that setting in the UI I guess?

**Comment by jasonvarga** [comment]
~The setting is already there~ I thought it was. Yep, definitely need it!
