### ISSUE TITLE
Delete Taxonomy doesn't work

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#1139]
![image](https://user-images.githubusercontent.com/44739/71212640-bc167200-227f-11ea-84a6-f8b217458770.png)

**Comment by jonassiewertsen** [comment]
I can confirm that. 

I can't delete a taxonomy entry. This part is still WIP ?

For reference

```
production.ERROR: Illegal offset type in unset {"userId":"xxxxxxxxxxxxx","exception":"[object] (ErrorException(code: 0): Illegal offset type in unset at /vendor/statamic/cms/src/Stache/Stores/BasicStore.php:73)
[stacktrace]
```

**Comment by jasonvarga** [comment]
The issue is still open 👍

**Comment by jonassiewertsen** [comment]
It seems to have deleted the entry sometimes, after deleting the cache and stache.

**Comment by jesseleite** [comment]
This is fixed on master now 👍
