### ISSUE TITLE
error template doesn't fin layout when layout in own folder

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1140]
Since layout.antlers.html has been moved to its own folder inside views, my 404 error template located in views/errors/404.antlers.html cannot find the layout and the 404 error message is then displayed on a basic blank default screen.

Moving the layout outside of its folder solved this.

**Comment by jasonvarga** [comment]
What do you mean the layout moved?

**Comment by ebeauchamps** [comment]
Sorry. When using MIGRATOR, the layout is automatically put in a layouts folder inside the views folder.

**Comment by jasonvarga** [comment]
Ok I understand, thanks!
