### ISSUE TITLE
CP: Lost after saving using East Asian text as blueprint section‘s title

### ISSUE THREAD

**Issue by taoguangc** [statamic/cms#1141]
When adding multiple sections to the blueprint, if you use East Asian text as the title, only the last one will be saved after saving. Such as title “幻灯片”, "功能". The same situation also occurs when adding the set of Replicator or bard. Suggest adding Handle field for section or set like v2.

**Comment by jasonvarga** [comment]
Ah, because we create the handle by slugifying the title, and it doesn't know what to do for Asian characters. I guess we'll need that handle field.

**Comment by jackmcdade** [comment]
Closing this in favor the more clear and instructive https://github.com/statamic/cms/issues/1667.
