### ISSUE TITLE
CP: When adding links to a new collection you need to add them twice

### ISSUE THREAD

**Issue by rosswintle** [statamic/cms#1147]
I have created a new structure for "Main Nav"

The structure is linked to the "Pages" collection.

```
title: 'Main Nav'
collections:
  - pages
max_depth: 1
```

In the control panel, when I use the "Add link" button, choose "Link to Entry" and select some pages and add them, they do not appear. I have to click "Add link", "Link to Entry" and "Select" again.

Here's a video showing it: https://share.getcloudapp.com/bLuG0kb1

I also note that this demonstrates the issue in #957 where, when adding links to entries, entries from ALL collections are shown when it feels like only entries from the linked collections should be shown.

**Comment by rosswintle** [comment]
I note that there is no console output when this happens, and the network tab in dev tools shows only 200's so no server errors. Looks like a UI-only thing.

**Comment by rosswintle** [comment]
There's another bug that applies to adding links to a new, empty structure whereby you can add the same entry links multiple times. I'm not sure if this is a feature (it's entirely possible you might want to add the same link more than once), but it only happens when adding to an empty structure, not when editing an existing structure.

Here's a video: https://share.getcloudapp.com/RBuX9lbP

Steps are:

* Create new structure
* Link to a collection
* Edit structure
* Click "Add link"
* Click "Link to entry"
* Select some entries
* Click "Select" button
* NOTE: No entries show in the list
* Click "Add link"
* Click "Link to entry"
* NOTE: Entries are already selected
* Click "Select" button
* NOTE: Entries are now listed
* Click "Add link"
* Click "Link to entry"
* Entries are already selected
* Click "Select" button
* NOTE: Duplicate entries added! (This is the issue described in this comment)
* Click "Save changes"
* Click on the structure name in the CP nav on the left to open the edit screen again
* Click "Add link"
* Click "Link to entry"
* Entries are already selected
* Click "Select" button
* NOTE: Duplicate entries are NOT added (This is the issue described in this comment - it's inconsistent with behaviour above)

**Comment by jasonvarga** [comment]
Should be resolved in the next release as part of all the structure-related changes.
