### ISSUE TITLE
By default taxonomy tag should exclude terms that haven't been used

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#1149]

**Comment by ebeauchamps** [comment]
FWIW:
when I am on a page using taxonomy tag, url related to terms are on this format:
site.local/{tags}/{term}

expected behavior: with 2.11.15, url are on this format:
site.local/{collection}/{tags}/{term}

**Comment by jasonvarga** [comment]
I disagree with this issue. This default behavior trips every other person up. We should just have a min_count=“1” param IMO.

**Comment by jackmcdade** [comment]
Ah yes you’re right. I remember working through this. Also, with a parser fix on #1151 will be easily addressed.

**Comment by ebeauchamps** [comment]
Would you mind sharing how we can (or how we will be able to) limit the outputted terms to the ones really in use in the collection? thanks.

**Comment by jackmcdade** [comment]
@jasonvarga nailed it:

> We should just have a `min_count=“1”` param

**Comment by ebeauchamps** [comment]
As per the docs and as per the above thread, I tried ```{{ taxonomy:topics min_count="1" as="topics" }}``` but still ALL 6 terms are displayed though my 3 entries are only using 3 of them.

When I write
```
{{ topics }}
                <a href="{{ url }}">{{ title }}</a>{{ results }}<br>
{{ /topics}}
```
there are no values for ```{{ results }}}```

**Comment by ebeauchamps** [comment]
@jackmcdade Sorry to bug you Jack, did you have any chance looking into this or am I doing something wrong in my markup?

**Comment by jackmcdade** [comment]
Haven't had a chance to look into it yet, sorry man!
