### ISSUE TITLE
taxonomy {tags} not displaying term values related to entries inside a {{collection}} loop

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1153]
EDITED

So I have a Blog collection
in blog.yaml I have
```
taxonomies:
  - tags
```
I want to display blog entries on the homepage with their associated tags' term(s)

My default.antlers.html template has this code:
```
{{ collection:blog taxonomy="true" }}
...
{{ tags }}
...
{{ /collection:blog }}
```
On the frontend, terms are displayed like this:
[{},{},{}] when there are 3 terms attached to the entry, [{}] when there is only one term, and so on

Entries are .md files that includes the tags'term(s) such as:
```
tags:
  - term1
  - term2
```

**Comment by jasonvarga** [comment]
What URL are you using this on? `/blog`?

**Comment by ebeauchamps** [comment]
no, I am on the home page, calling the default layout and the default template

**Comment by jasonvarga** [comment]
The taxonomy="true" tag is meant to read the taxonomy term from the URL. Using it on the home page doesn't make sense. What are you trying to do?

**Comment by ebeauchamps** [comment]
I removed it (the homepage was OK priori to beta11, but you have a point).
On the homepage, i want to display my blog entries (title, link, date..AND all terms associated to each particular blog entry)
But instead go getting the terms to display, I am only getting what I wrote on the first post above

**Comment by jasonvarga** [comment]
The `taxonomy` param before beta 11 did nothing, that's why there were no errors.

The parameter is intended for filtering your entries. You don't need it for what you're trying to do.

Where you display `{{ tags }}`, it's an array of stuff, so you need to loop over it. Try something like this:

```
{{ tags }}<a href="{{ url }}">{{ title }}</a>, {{ /tags }}
```

**Comment by ebeauchamps** [comment]
ok. Different behaviour compared to V2 so?

**Comment by jasonvarga** [comment]
{{ tags }} on its own wouldn't have done anything in v2 either.

You can try {{ tags | raw | sentence_list }} if that's what you want to do.

In v3 the augmentation feature would convert your `tags` variable from a list of strings into an array of term objects. That's why you can use nested fields like `title` and `url` in there now.

**Comment by ebeauchamps** [comment]
{{ tags }}{{ title }}{{ /tags }} is displaying terms indeed, but in one word: blueredyellow
{{ tags | raw | sentence_list }} is perfect: blue, red and yellow
in v2 I had {{ tags | sentence_list }}

I guess I can close this
Thanks once again Jason!
