### ISSUE TITLE
yaml in front-matter of antlers template not read

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1154]
In order to get the same behavior as with v2, how can we declare some yaml in an antlers template?
1st example:
tags.antlers.html
```
---
title: Terms in use throughout entries
---
```
I want {title} to be available for layout.antlers.html

2nd example
default.antlers.html
```
---
header_class: rednav
---
```
I want to use {header_class} directly inside the template it has been declared in

**Comment by jasonvarga** [comment]
Variables defined in your views now need a `view` prefix. eg `view:header_class`.

But they don't work yet if you define in your template and want to get it in your layout, see #501

**Comment by ebeauchamps** [comment]
All good!

**Comment by marzvrover** [comment]
I know this is an old issue, but just adding some additional context for other folks that may find this:

To use a variable defined in your template:

```antlers
{{# layout.antlers.html #}}
{{ view:name ?? "John Smith" }}
```

Define variables like normal
```antlers
{{# template.antlers.html #}}
---
name: "Jane Smith"
---
```
