### ISSUE TITLE
Asset::findByPath not working as expected

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1155]
The code in my controller looks like:
```
dd($video->url, Asset::all(), Asset::findByPath($video->url));
```

As the third result, I would expect the full URL of the asset, but not null.

<img width="686" alt="Bildschirmfoto 2019-12-23 um 00 25 53" src="https://user-images.githubusercontent.com/38906163/71328656-2c8cef80-251b-11ea-8d3a-ca607a5f9d48.png">

**Comment by jasonvarga** [comment]
findByPath needs the asset container's path too. eg. `assets/videos/1-Series-Chapters.mp4`

**Comment by jonassiewertsen** [comment]
This seems not to fix it. I tried different variations. 

```php
dd(
  Asset::findByPath('/assets/1-Series-Chapters.mp4'), 
  Asset::findByPath('assets/1-Series-Chapters.mp4'), 
  Asset::findByPath('/assets/1-Series-Chapters'), 
  Asset::findByPath('assets/1-Series-Chapters'));
```

Every value is returning null. 

Calling the path in my browser does show the video:
```
http://mydevdomain.test/assets/1-Series-Chapters.mp4
```

**Comment by jackmcdade** [comment]
Do those files exist inside a proper asset container?

**Comment by jonassiewertsen** [comment]
How do you define a proper asset container?

The Asset has been uploaded via the Statamic Backend, inside the existing standard Statamic container.

**Comment by jackmcdade** [comment]
Then you have done it. Must be a bug I suppose!

**Comment by aerni** [comment]
I can confirm this bug on Beta 35. The `Asset::findByPath()` method just doesn't work. No matter what I'm feeding it.

**Comment by jonassiewertsen** [comment]
I will close this issue in favor of https://github.com/statamic/cms/issues/2119
