### ISSUE TITLE
Cache tag not working

### ISSUE THREAD

**Issue by rpensek** [statamic/cms#1157]
Tried to do a test-run migrating our site from V2 -> V3 and while the migration wizard haven't found any issues we stumbled upon the following error when launching the website. 
We use {{ cache }} in the main template file and it appears to trigger the following:
- Undefined property: Statamic\Tags\Cache::$cache
... looking at stack $cache is not available [in here](https://github.com/statamic/cms/blob/master/src/Tags/Cache.php#L27) which throws an error. Tried finding up any changes in the upgrade guide but nothing seemed relevant - the documentation for using {{ cache }} is the same.

**Comment by jasonvarga** [comment]
Thanks for pointing that out. We must have just brought over the cache tag without updating it for v3.
