### ISSUE TITLE
BindingResolutionException when working with PHPUnit in addon context

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1158]
There is a Binding Resolution Exception when working with PHPUnit to create a custom addon. 

```php
Illuminate\Contracts\Container\BindingResolutionException : Unresolvable dependency resolving [Parameter #1 [ <required> $basePath ]] in class Illuminate\Foundation\PackageManifest
```

I think I could nail the problem down, to the following method, called in the boot method from the `Statamic\Providers\AddonServiceProvider`:

```php

namespace Statamic\Extend;

use Statamic\Extend\Management\Manifest;

class AddonRepository
{
    (...)
    public function all()
    {
        return app(Manifest::class)->addons()->map(function ($addon) {
            return $this->make($addon);
        });
    }
```

The issue seems to be, that the manifest cant get resolved out of the container: `app(manifest::class)` and will be triggered via the addonDiscovered() method.

```php
namespace Statamic\Providers;

use Illuminate\Support\ServiceProvider;

abstract class AddonServiceProvider extends ServiceProvider
{
   (...)

    public function boot()
    {
        if (! $this->addonDiscovered()) {
            return;
        }
     
        (...)
```

By overwriting the boot method in the serviceProvider by simply not calling `parent::boot();`, the error disappears. This is no option though, because routes, views etc cant be working correctly then.

If it helps, I could share the specific test setup, but maybe it's not needed. 

PS: The Orchestra Test Bench has been pulled in :-)
PPS: When not testing, the addon does run as expected.

**Comment by jonassiewertsen** [comment]
The binding resolution exception can be resolved, if the ServiceProvider will be loaded later in the request lifecycle.

```php
 protected function getPackageProviders($app)
    {
        $app->booted(function () {
            return [
                ServiceProvider::class,
            ];
        });
    }
```

There are still problems with tests in packages. 
Maybe those issues are related? https://github.com/statamic/cms/issues/1159

**Comment by jasonvarga** [comment]
Your base test case needs to load Statamic's provider in addition to your own.

See https://github.com/statamic/cms/blob/master/tests/TestCase.php#L47-L55

**Comment by jonassiewertsen** [comment]
Ok, that makes sense. Thanks!

Just for reference. The next issue will be the ErrorException class not found. To resolve it, as stated by @damcclean, you need to require the file just before your `parent::setUp()' method. Just copy the file and save it in the tests folder.

In my case the TestCase class does look like:

```php
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Orchestra\Testbench\TestCase as OrchestraTestCase;
use Statamic\Statamic;

class TestCase extends OrchestraTestCase
{
    use DatabaseMigrations;

    /**
     * Setup the test environment.
     */
    protected function setUp(): void
    {
        require_once(__DIR__.'/ExceptionHandler.php');

        parent::setUp();

        // $this->withFactories(__DIR__.'/../database/factories');
    }

    /**
     * Load package service provider
     * @param  \Illuminate\Foundation\Application $app
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            \Statamic\Providers\StatamicServiceProvider::class,
            \Jonassiewertsen\AddonName\ServiceProvider::class,
        ];
    }

    /**
     * Load package alias
     * @param  \Illuminate\Foundation\Application $app
     * @return array
     */
    protected function getPackageAliases($app)
    {
        return [
            'Statamic' => Statamic::class,
//          'YourAddon' => ...
        ];
    }
}
```
