### ISSUE TITLE
Routes not loaded when testing with phpunit in addon context

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1159]
When the routes are defined in the **ServiceProvider**, extended from `Statamic\Providers\AddonServiceProvider`, they will not be loaded, when testing with PHPUnit and Orchestra Testbench.

```php
protected $routes = [
        'cp' => __DIR__.'/../routes/cp.php',
    ];
```

It is important an important feature to test custom views and similar in the cp or public front (web routes).

**Comment by damcclean** [comment]
I've also noticed the same bug while setting up tests for my addon today 😂

**Comment by jasonvarga** [comment]
See https://github.com/statamic/cms/issues/1158#issuecomment-569277033

**Comment by damcclean** [comment]
Even with both my service provider and the Statamic service provider added to my TestCase, it still can't recognise any named routes. I wonder if this has to do with how Control Panel routes have `statamic.cp` or whatever it is added to the start of the route names.

For reference this is where I reference the service providers inside my TestCase.

```
protected function getPackageProviders($app)
    {
        return [
            StatamicServiceProvider::class,
            CommerceServiceProvider::class,
        ];
    }
    protected function getPackageAliases($app)
    {
        return [
            'Statamic' => Statamic::class,
        ];
    }
```

**Comment by jonassiewertsen** [comment]
Seems like the issues do not belong to each other. 

I can load Statamic core routes now, after resolving this issue (https://github.com/statamic/cms/issues/1158#issuecomment-569277033) but not those from my package. 

It seems that there is an issue to load routes, when binding as seen in my code example.

**Comment by jonassiewertsen** [comment]
Are there updates on this issue?

It is fundamental to test addons via phpunit. Right now i cant go any further with my statamic paypal ecommerce plugin.

If more infos are needed, i gladly provide those 😎

**Comment by jasonvarga** [comment]
We're off for the holiday break so haven't been able to work on this. I've reopened this and will take a closer look once we're back.

**Comment by jonassiewertsen** [comment]
Thanks @jasonvarga !

**Comment by jasonvarga** [comment]
This is obviously not the final solution I'm suggesting, but it should get you going for now.

In your base `TestCase`:

``` php
protected function getEnvironmentSetUp($app)
{
    parent::getEnvironmentSetUp($app);

    $app->make(\Statamic\Extend\Manifest::class)->manifest = [
        'your-vendor/your-package' => [
            'id' => 'your-vendor/your-package',
            'namespace' => 'Your\\Package\\Namespace\\',
        ],
    ];
}
```

**Comment by jonassiewertsen** [comment]
That does work as a workaround. Thank you.

(I did change the Manifest namespace to get it working)

```
protected function getEnvironmentSetUp($app)
{
    parent::getEnvironmentSetUp($app);

    $app->make(\Statamic\Extend\Management\Manifest::class)->manifest = [
        'your-vendor/your-package' => [
            'id' => 'your-vendor/your-package',
            'namespace' => 'Your\\Package\\Namespace\\',
        ],
    ];
}
```

**Comment by damcclean** [comment]
Hmm, yeah. The [`Manifest.php`](https://github.com/statamic/cms/blob/master/src/Extend/Manifest.php) file actually moved into `Extend` so it needs a `composer update`

**Comment by jasonvarga** [comment]
Agh sorry, I was confused why you both were saying it's the wrong namespace. I hadn't tagged that change yet, thought it was done much earlier.

It'll be `\Statamic\Extend\Manifest` in beta 9, tagging in a moment.
