### ISSUE TITLE
Don't allow fields with the same handle in a Blueprint

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1160]
I've just managed to create two fields in a Blueprint that both have the same handle. When going to edit an entry that uses this blueprint, I get an error: `**Duplicate field [customer] on blueprint [order].**`

I'm guessing that some validation should be added to make sure no two (or more) fields can be added in a single blueprint with the same handle.

**Comment by jackmcdade** [comment]
Closing this in favor of https://github.com/statamic/cms/issues/1667.
