### ISSUE TITLE
Help text translation not working

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1165]
When I go to create a blueprint in the Control Panel, there's some what looks like help text next to the button but the help text is not being translated properly.

![image](https://user-images.githubusercontent.com/19637309/71550450-55ecc600-29c8-11ea-9b51-d5ef6a7ebe7c.png)

**Comment by ebeauchamps** [comment]
Which CP language do you want to use?
Only those locales are available for the CP:
- fr
- pt
- es
- de
- it

2 solutions to get it working:
1/ if all you CP users are using the same locale: in Config/app.php, change 'locale => en' to your locale
2/ if settings are different between users: in your useryaml file, set
```
preferences:
  locale: fr
````
(or whatever is your locale)

**Comment by damcclean** [comment]
This issue is the same as #1169. As adding `statamic::` to the start of the translation code in the view fixes the issue.

**Comment by stvnthomas** [comment]
The PR fixes the blueprint, fieldset and login translations. I couldn't find any other blade templates that had the problem. I'll update the PR if you can point me to any I missed.

**Comment by damcclean** [comment]
> The PR fixes the blueprint, fieldset and login translations. I couldn't find any other blade templates that had the problem. I'll update the PR if you can point me to any I missed.

Awesome!
