### ISSUE TITLE
Asset fieldtype's optional container setting isn't exactly optional

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#1166]
After deleting an asset, it still says that 1 file is selected. The upload button is not shown.

Statamic-Version: Beta 8
PHP: 7.4.0
Server: Valet

**Comment by jonassiewertsen** [comment]
Got a similar problem.

When I want to change an image: After deleting the old, I can‘t upload or select a new one.

**Comment by jonassiewertsen** [comment]
From the log
```
[2020-01-31 16:20:24] local.ERROR: Call to a member function id() on null {"userId":"49705ced-47d(...)","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function id() on null at (...)vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:23)
[stacktrace]
#0 (...)vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php(132): Illuminate\\Http\\Resources\\Json\\JsonResource->forwardCallTo(NULL, 'id', Array)
#1 (...)vendor/statamic/cms/src/Http/Resources/CP/Assets/Asset.php(14): Illuminate\\Http\\Resources\\Json\\JsonResource->__call('id', Array)
#2(...) vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(94): Statamic\\Http\\Resources\\CP\\Assets\\Asset->toArray(Object(Illuminate\\Http\\Request))
```

**Comment by jackmcdade** [comment]
I can't recreate this. Does anyone have it happening on an open repo somewhere we can check?

**Comment by jackmcdade** [comment]
What's your field config?

**Comment by jasonvarga** [comment]
Looks like the issue is when a `container` isn't set. We removed that requirement in v3 if you only have one container. Thanks!

**Comment by jonassiewertsen** [comment]
Adding the container manually did resolve my issue.

Thanks for your support!

**Comment by jackmcdade** [comment]
Okay, glad to know we've honed in the cause :)

**Comment by sjclark** [comment]
I stumbled across this after I added an asset container to a virtually vanilla install. Suddenly even just viewing the dashboard resulted in:
```
Assets fieldtype is missing the "container" option.
Since you have multiple asset containers, you need to specify which one should be used in the field.
```
Eventually I narrowed it down (thanks @damcclean ) to `user.yaml` which technically has an asset field for the **avatar** - not that I'd actually set an avatar. Specifying a container resolved it.
