### ISSUE TITLE
When creating a collection or an item, the first field in the form does not get the focus

### ISSUE THREAD

**Issue by peterkelm** [statamic/cms#1167]
When creating a collection, an item a term,... the associated form opens but the (text input) focus is not on the first (editable) field. So starting to enter text requires a separate click on said first field before one can start typing.

Using latest Safari on macOS Mojave with latest patches installed, the focus border is shown on the first field but entering text does not go anywhere. Latest Firefox on macOS does not even show the focus border on that first field.

Statamic version is 3.0.0-beta.8

**Comment by jackmcdade** [comment]
This is fixed.
