### ISSUE TITLE
Ability to customize the Assets fieldtype button label

### ISSUE THREAD

**Issue by derekjones** [statamic/cms#1176]
Given an Assets field constrained to a specific container, say "Photos":

<img width="1091" alt="Screen Shot 2020-01-07 at 1 33 50 PM" src="https://user-images.githubusercontent.com/763613/71931482-b01d2200-3152-11ea-8480-416dc43e3388.png">

It appears to label the button with "Assets":

<img width="799" alt="Screen Shot 2020-01-07 at 1 33 30 PM" src="https://user-images.githubusercontent.com/763613/71931494-b57a6c80-3152-11ea-95ae-9e1386084f72.png">

I'm not 100% sure what the intent is for that button label, but my assumption was that it would use the Asset container's name.

**Comment by jasonvarga** [comment]
The call to action would be to choose assets. The location is not really relevant to the person using the form.

That's the reasoning behind the label anyway.

If you wanted to customize the button label, I'd opt for a dedicated setting rather than just using the container's name. I can see someone else asking why the button all of sudden says Photos instead of Assets.

**Comment by derekjones** [comment]
Gotcha. I tend to use semantic names for my asset containers, which helps the end user know what goes (and doesn't go) there. No biggie!

**Comment by jackmcdade** [comment]
Fair enough! I can see it both ways pretty easily. One thing to factor is that you can choose from _multiple_ containers, which would definitely make a dynamic label kinda awkward.

"Choose from Photos, Videos, or Secure PDF Files [For Clients Only]". 🤔 

Either way, a customizable button label could be nice.

**Comment by derekjones** [comment]
> "Choose from Photos, Videos, or Secure PDF Files [For Clients Only]". 🤔

Yeah that would be mess, good point. Maybe a verb instead of a noun—but it's probably fine as-is.

> Either way, a customizable button label could be nice.

Customization is overrated. Should already be possible in v3 anyway with some arbitrary JS, eh?

**Comment by jackmcdade** [comment]
Oh yes, anything is possible with arbitrary JS!

**Comment by jackmcdade** [comment]
It just says "Browse" now. Nice and generic.
