### ISSUE TITLE
Issue when running composer install on Statamic V3

### ISSUE THREAD

**Issue by christian-thomas** [statamic/cms#1177]
This is related, or looks like the same issue as https://github.com/statamic/cms/issues/551.

On the server if I run...

```bash
composer install -vvv
```

It comes back with the following error:

```bash
Generating optimized autoload files
> post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
> post-autoload-dump: @php artisan package:discover --ansi
Executing command (CWD): '/usr/bin/php7.2' -d allow_url_fopen='1' -d disable_functions='' -d memory_limit='1536M' artisan package:discover --ansi

In Repository.php line 636:

  Call to undefined method Illuminate\Cache\FileStore::rememberWithExpiration
  ()


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

It doesn't do the same on my local machine, and I've tried removing the `vendor` directory, as well as the `composer.lock` file, and nothing seems to sort it. I've also tried on two different servers - Both built through forge, but no luck.

Can anyone shed any light? It looks like it's the macro possibly isn't getting registered in `Statamic\Providers\CacheServiceProvider` — If I try outputting something in the `boot` method on my local machine, and then run `composer dump-autoload` it will output. If I try doing the same on the server, no output and it dies with the error above.

**Comment by jasonvarga** [comment]
What's in your composer.json?

**Comment by christian-thomas** [comment]
Ok by questioning that, it made me think of anything additional that it might have. It's just the default v3 json file, with the addition of a private package requirements - Deploying the site through forge, the composer command is:

`composer install --no-interaction --prefer-dist --optimize-autoloader`

The server needed a token generating to access the package, but with `--no-interaction` you don't get a prompt. The error I was receiving I _think_ may have been unrelated to the error above, so by adding a token to the server this is now 

Thanks for the prompt, and the quick response @jasonvarga. 👍

**Comment by jonassiewertsen** [comment]
By doing a repository change on Forge, I did run into this error (took me 2 hours).
I expected a Laravel problem, so I did not look here with the same and the error is not self-explaining.

It would suggest putting this into the documentation. It's not Statamics fault but would save Statamic users a lot of trouble

**Comment by jasonvarga** [comment]
Putting what in the docs? I don’t understand the cause of that error. Did you work it out?

**Comment by jonassiewertsen** [comment]
Yes, I did. 

A part of Forge default composer script, which works really good with Laravel only.
```
composer install --no-interaction --prefer-dist --optimize-autoloader
```

Using --no-interaction with Statamic, does throw the error:
```
Call to undefined method Illuminate\Cache\FileStore::rememberWithExpiration
  ()
```

**Comment by jonassiewertsen** [comment]
Something in the docs, like:
If running Statamic with Laravel Forge, remember to remove the --no-interaction attribute from the composer install command

**Comment by jasonvarga** [comment]
What do you see if you remove that?

**Comment by jonassiewertsen** [comment]
Forge does provide this command, which is running perfectly fine with most Laravel applications. When setting up a repository, it's in the Forge boilerplate for installing the composer dependencies and other stuff.

```
composer install --no-interaction --prefer-dist --optimize-autoloader
```

If you do deploy Statamic V3 (at least in a few cases), you will get the follwoing error message:
```
Call to undefined method Illuminate\Cache\FileStore::rememberWithExpiration()
```

The deployment will fail and you are not able to setup Statamic with Forge. 

To avoid this failure, you need to change the default provide Forge script and remove --no-interaction, so it looks like this:

```
composer install --prefer-dist --optimize-autoloader
```

After removing, everything is fine and you can deploy.

**Comment by jasonvarga** [comment]
Are you sure removing `--no-interaction` is what solved your problem? Christian said something about a token. Did you do anything about that?

**Comment by jonassiewertsen** [comment]
In my case, it did.

**Comment by jasonvarga** [comment]
Ok thanks.

**Comment by jonassiewertsen** [comment]
Yes. Two of my own. 

I thought about it and removed them and retried. No Change.

**Comment by jasonvarga** [comment]
Okay, that's the problem. I replicated it. Removing the --no-interaction doesn't solve it.

**Comment by jonassiewertsen** [comment]
Hmmm ... the `--no-interaction` seemed to solve my problem on the server. But you are right, it did not seem to solve the problem totally.

**Comment by jonassiewertsen** [comment]
Just run into this error again ...

I think my PR does resolve this issue.
