### ISSUE TITLE
Add filter to search:results to filter published entries

### ISSUE THREAD

**Issue by owenconti** [statamic/cms#1178]
It would be nice to be able to filter search results to only show published entries (and possibly by other filters too).

Currently getting by via:

```
{{ search:results }}
  {{ if no_results }}
    <h2>No results.</h2>
  {{ elseif published }}
    {{ partial:partials/summary }}
  {{ /if }}
{{ /search:results }}
```

**Comment by sheldonkotyk** [comment]
Also if blogs are dated, it should not show entries in the future.

**Comment by jasonvarga** [comment]
This is possible now.

`{{ search:results status:is="published" }}` or `published:is="true"`
