### ISSUE TITLE
Structures that have no associated collections still show popup 'Link to Entry' in Admin UI

### ISSUE THREAD

**Issue by admench** [statamic/cms#1180]
![Screenshot 2020-01-08 at 11 24 09](https://user-images.githubusercontent.com/672916/71974465-6e02e780-3209-11ea-848b-c20ab314d4b2.png)

Config `content/structures/social_links.yaml`:
```
title: 'Social Links'
max_depth: 1
```
The UI button 'Add Link' should directly trigger the manual link modal instead of asking the user to select an option where only 'Link to URL' works anyway.

**Comment by jackmcdade** [comment]
Thanks for the heads up! Structures are getting a bit of a rework this week. Stay tuned.

**Comment by jasonvarga** [comment]
Should be irrelevant in the next release because of the structure-related changes.
