### ISSUE TITLE
Streamline addon test suites

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1184]
As shown in #1159 and probably some other issues, testing addons needs some love.

I think it would be good to have our own abstract TestCase for developers to extend that does extra necessary bootstrapping, rather than them needing to extend from Testbench's and do a bunch of wiring.

There's also the ExceptionHandler issue, and Statamic config loading, both of which could probably be done as part of this abstracted class.

There's a bunch of useful fake classes used in our own tests that could be useful to addon devs. Stuff should probably be moved out from our `tests` directory and into a real `Statamic\Testing` namespace.

**Comment by jackmcdade** [comment]
Closing as we try to avoid these broad issue types now and will look at opening smaller, bite sized tasks going forward.
