### ISSUE TITLE
Grid should display minimum rows rather than "add row" button

### ISSUE THREAD

**Issue by that0n3guy** [statamic/cms#1187]
There are a couple things here:
- If minimum rows is set, the grid should be displayed by default.
You should never see this (photo size is the name of the grid): 
![image](https://user-images.githubusercontent.com/113870/72079035-d14f5100-32bf-11ea-9645-0ef18b1f365e.png)

You should see this: 
![image](https://user-images.githubusercontent.com/113870/72079229-225f4500-32c0-11ea-9209-0519209e1cfa.png)

- If minimum rows == maximum rows, the form should just display the number of rows without a delete button (See #647 ), without a duplicate button, and without a "add row" button (like bullet above)
![image](https://user-images.githubusercontent.com/113870/72079108-ee841f80-32bf-11ea-9ebd-67cde5d0758d.png)

**Comment by jackmcdade** [comment]
Agreed. Thou has discovered a bug! We shall dispatch the bug-slaying knights posthaste!

**Comment by jackmcdade** [comment]
Hmmm, I can't recreate this issue.  Is there anything else that might be a factor? Is this Grid field inside another field perhaps?

**Comment by that0n3guy** [comment]
Yes, Its inside a bard.   Here is the whole blueprint: https://gist.github.com/that0n3guy/cc9f60ff56df5278dbdf4adf486c579b

**Comment by jackmcdade** [comment]
Confirmed.

**Comment by jelleroorda** [comment]
Open sesame

**Comment by jesseleite** [comment]
Fixed by https://github.com/statamic/cms/pull/3235 🎉
