### ISSUE TITLE
S3 Assets Showing Container Is Empty

### ISSUE THREAD

**Issue by edolyne** [statamic/cms#1188]
Connecting an asset source to S3 with proper credentials shows a loading icon for some time before showing `Container is empty`.

Changing `env` variables produces errors that the key is incorrect, or the bucket can not be found.

When uploading, a file is created on S3, but shows in Statamic `Gateway timeout`. If creating a folder, the folder is created in Statamic and S3, but upon refresh the same `Container is empty` message appears again.

**Comment by edolyne** [comment]
When updating to a much smaller size bucket, `4.5mb` vs `11.2gb` I'm able to upload and see all of the contents of the bucket.

**Comment by jackmcdade** [comment]
Yikes, 11.2gb! Are they all in one flat directory or organized into lots of subdirectories? I have a feeling Statamic is trying to inhale them all in one shot and then, as one would expect, it times out.

**Comment by edolyne** [comment]
@jackmcdade The files are in multiple subdirectories. I have that same feeling, at first I had 128mb set for my php.ini which  produced an error saying that it had requested too much memory. I then increased it to 512mb which removed the memory error and I believe we're now in a timeout situation.

**Comment by jasonvarga** [comment]
I believe in discord @edolyne said there's only a few in the root, the rest are organized into directories.

**Comment by nathobson** [comment]
I've just been playing with Digital Ocean spaces using the S3 driver ([per Flysystem](https://flysystem.thephpleague.com/v1/docs/adapter/digitalocean-spaces/)).

I'm hitting this same issue. Vanilla Statamic install (v3.0.0-beta.17), aside from the S3 driver being added and configured.

With a fresh DO Space, I can add and browse files. However, I've just tried connecting a test Space with some file in. Nothing crazy, 45.5 MB / 234 items. The items are organised into directories by year and then by month with only directories in the root. 

Looks like it times out after 1 minute:

![Screenshot 2020-02-20 at 16 45 56](https://user-images.githubusercontent.com/6664210/74958288-9ed95d80-5400-11ea-916c-8472820795bb.png)

I've tried increasing the PHP `max_input_time` and `max_execution_time` but no joy.

**Comment by edolyne** [comment]
Any updates on this, or a potential workaround for the time being?

**Comment by GioChocolateBro** [comment]
Yes i have this problem as well..

5k files.

Tried on directory with 1.7k files, let it create all the yamls, refreshed couple times. Afterwards still timing out.
So tried a dir with only 200.. same thing.

Creating a new folder and uploading will work tho. But my clients are probably gonna have a lot more assets in the future.

**Comment by GioChocolateBro** [comment]
I think this is the same issue?
#2145
