### ISSUE TITLE
resources/dist folder missing

### ISSUE THREAD

**Issue by glennjacobs** [statamic/cms#1192]
Trying to publish the CP resources, but they appear to be missing?

```
Can't locate path: </Volumes/Projects/valet/website/vendor/statamic/cms/src/Providers/../../resources/dist>
```

**Comment by jasonvarga** [comment]
What version of `statamic/cms` is in your `composer.json`'s `require` block?

**Comment by glennjacobs** [comment]
```
statamic/cms": "dev-master
```

**Comment by jasonvarga** [comment]
Use `3.0.*@beta`

**Comment by jackmcdade** [comment]
@glennjacobs In case you're curious why that was – the JavaScript, CSS, and other assets are only compiled on tagged releases as part of an automated release process. 🤘

**Comment by scil** [comment]
i have the same error with v3.0.10.
i tried ` "statamic/cms": "3.0.*@beta"` and failed.

**Comment by jeremydouglas** [comment]
I just got this error when installing `3.1.11`.

**Comment by dionvogliqi** [comment]
> I just got this error when installing `3.1.11`.

Me too using the same version. 
Can't locate path: </var/www/vendor/statamic/cms/src/Providers/../../resources/dist>

**Comment by jasonvarga** [comment]
What's your composer requirement for `statamic/cms`? It should be `3.1.*`

**Comment by dionvogliqi** [comment]
> What's your composer requirement for `statamic/cms`? It should be `3.1.*`

It is 3.1.*. 

I'm trying to set this up on docker. Everything else works fine.

**Comment by duncanmcclean** [comment]
Can you share your full `composer.json` file with us?

**Comment by dionvogliqi** [comment]
```
{
    "name": "statamic/statamic",
    "description": "Statamic",
    "keywords": ["statamic", "cms", "flat file", "laravel"],
    "type": "project",
    "require": {
        "php": "^8.0",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0",
        "statamic/cms": "3.1.*"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.5",
        "facade/ignition": "^2.3.6",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "pre-update-cmd": [
            "Statamic\\Console\\Composer\\Scripts::preUpdateCmd"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan statamic:install --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

```

And this is how I run composer on docker 

```
RUN composer install \
  --ignore-platform-reqs \
  --no-interaction \
  --no-plugins \
  --no-scripts \
  --prefer-dist
```

**Comment by duncanmcclean** [comment]
Remove `"minimum-stability": "dev",` and try again, does that sort your problem?

**Comment by osmanzeki** [comment]
It seems like the "dist" has not been produced for this release of Statamic? Since by default the `/public/vendor/statamic` folder is git ignored, I had the surprise of having the js and css for the control panel upon deploying on a different machine. This worked well before on my local dev machine because I had a version of Statamic installed since before the latest 3.1.* release.

In anyone is still looking for a workaround, here goes:

### From the root of the Laravel project:

1. `composer install` or `composer update` as usual.
2. `cd` into the `vendor/statamic/cms` folder
3. `npm install`, followed by a `npm prod`
4. `cd` back to the root of the Laravel project
5. `php artisan vendor:publish --tag=statamic-cp`

**Comment by duncanmcclean** [comment]
Did you try `php artisan statamic:install`, it will re-publish Statamic's assets if you have them ignored?

**Comment by mundgold** [comment]
I just got this error when upgrading from 3.1.15 to 3.1.16

Can't locate path: ../vendor/statamic/cms/src/Providers/../../resources/dist>

I removed "minimum-stability": "dev", and run composer update

same problem 

try php artisan statamic:install

same problem

my composer.json

```
{
    "name": "statamic/statamic",
    "description": "Statamic",
    "keywords": ["statamic", "cms", "flat file", "laravel"],
    "type": "project",
    "require": {
        "php": "^7.3 || ^8.0",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0",
        "statamic/cms": "3.1.*"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.5",
        "facade/ignition": "^2.3.6",
        "fakerphp/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "pre-update-cmd": [
            "Statamic\\Console\\Composer\\Scripts::preUpdateCmd"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan statamic:install --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

**Comment by jasonvarga** [comment]
Run `composer install` again. Maybe there was a clog in the internet tube?

**Comment by mundgold** [comment]
Thank you for your reply: 

but I get the same result:

![_topbar_antlers_html_—_agruber](https://user-images.githubusercontent.com/5293053/119167829-8e2ef180-ba60-11eb-8c10-16e01af41539.png)

**Comment by jasonvarga** [comment]
What does `composer update statamic/cms` output?

**Comment by mundgold** [comment]
![site_css_—_agruber](https://user-images.githubusercontent.com/5293053/119169203-05b15080-ba62-11eb-8936-b8912172e57e.png)

**Comment by jasonvarga** [comment]
Delete your vendor directory and run composer install.

**Comment by mundgold** [comment]
I have done that ...

... now I get no error messages any more.

Thank you very much!

**Comment by jtomek** [comment]
It didn't help.

**Comment by duncanmcclean** [comment]
@jtomek If you're running into an issue, please open a new issue, instead of commenting on an old one. This issue hasn't been updated in over 6 months.

**Comment by ktross** [comment]
If you run into this issue, make sure that `config.allow-plugins.pixelfear/composer-dist-plugin` is set to `true` in composer.json

![image](https://user-images.githubusercontent.com/126944/158634227-812a9ccf-761d-4ead-b524-80830b4d9899.png)

**Comment by miclf** [comment]
Thanks a lot, @ktross, that fixed the issue for me!
