### ISSUE TITLE
Laravel log in breaks when using custom guard due to SetLastLoginTimestamp listener

### ISSUE THREAD

**Issue by chrisbjr** [statamic/cms#1194]
Hi @jasonvarga found another bug related to using custom guards.

I've let Statamic use the default guard and my User guard is now using another guard. However, the log in for my User guard breaks due to one of the listeners Statamic uses to log the last login timestamp ([SetLastLoginTimestamp](https://github.com/statamic/cms/blob/master/src/Auth/SetLastLoginTimestamp.php)).

I get the error below:

![Screenshot 2020-01-11 01 42 17](https://user-images.githubusercontent.com/571279/72174306-64010480-3414-11ea-93f1-296eb84f4b69.jpg)

**Comment by jasonvarga** [comment]
Your user guard is using another guard? Wha?

**Comment by chrisbjr** [comment]
@jasonvarga well, yes - it's not usually our standard but we do have a handful of projects that require the need to use custom guards.

Personally though, I would much prefer to see Statamic enable us to define its own guard so it doesn't interfere with the default `web` (or some other) guard where we could be doing other things not related to Statamic.

**Comment by chrisbjr** [comment]
Also, since a feature of Statamic v3 is that it enables integration to existing Laravel apps and Laravel *does* enable you to define custom guards, wouldn't it make sense not to generally fire off a listener in the Login event that only accepts a "StatamicUser"?

**Comment by jasonvarga** [comment]
We don't have a custom guard, just the provider. Are you overriding that too?

**Comment by chrisbjr** [comment]
Nope, I left it as is. I am using the `statamic` driver in the provider though, as shown here: https://statamic.dev/knowledge-base/storing-laravel-users-in-files

**Comment by chrisbjr** [comment]
So basically, my actual Users use the `session` driver, and Statamic users are using the `statamic` driver.

**Comment by jasonvarga** [comment]
Can you show your `config/auth.php` ?

**Comment by chrisbjr** [comment]
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'statamic',
        'passwords' => 'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'statamic' => [
            'driver' => 'session',
            'provider' => 'statamic_users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'spice',
            'model' => App\Models\User::class,
        ],

        'statamic_users' => [
            'driver' => 'statamic',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];

```

**Comment by jasonvarga** [comment]
So when you're manually using your `web` guard, that's when you get the error?

**Comment by jasonvarga** [comment]
Anyway, you _are_ using a custom provider. Makes sense now.

**Comment by chrisbjr** [comment]
That's right - even if my `web` guard were using the default driver, this would still be an issue. I get that error when my `web` guard is trying to log in.

**Comment by jasonvarga** [comment]
I assume where you are logging in using the web guard, there is absolutely nothing Statamic related happening?

**Comment by chrisbjr** [comment]
Yes, nothing Statamic related. But it still does fire off the `\Illuminate\Auth\Events\Login::class` event which Statamic has the said listener attached: https://github.com/statamic/cms/blob/master/src/Providers/EventServiceProvider.php#L20
