### ISSUE TITLE
Algolia-Search Index not updating automatically

### ISSUE THREAD

**Issue by HellPat** [statamic/cms#1199]
The class `Statamic\Search\UpdateItemIndexes` should index an Entry on every `EntrySaved` or `EntryDeleted`-Event.

Currently this seems to be broken somehow.

1. I have no elements in the index

![image](https://user-images.githubusercontent.com/1016798/72225718-fde9be00-3588-11ea-9ab4-97c95e8b0aa0.png)

2. I Add an element via Control-Panel.

still no elements in the index.

3. I edit an existing element via Control-Panel

still no elements in the index.

4. I use `/cp/utilities/search` to update the complete Index

-> here we go.

**It updates the index only if I run a complete update manually``

Is this intentional?
In my understanding `Statamic\Search\UpdateItemIndexes` should update them automatically.
There was a Plugin for v2, I think should be obsolete? https://statamic.com/marketplace/addons/collection-search-updater

I'm not sure if this a bug or not :-)

**Comment by psren** [comment]
Eventually this is related to https://github.com/statamic/cms/issues/123 ?
I have a multi-lingual site. My test was in the primary-language thought.

**Comment by jasonvarga** [comment]
Probably related to #1910

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
