### ISSUE TITLE
Abstract Search\Index misses some methods.

### ISSUE THREAD

**Issue by psren** [statamic/cms#1202]
At least the `delete` and the `update` method in use for the internal search adapters.
https://github.com/statamic/cms/blob/v3.0.0-beta.9/src/Search/UpdateItemIndexes.php#L30

If one provides his own adapter he will most likely forget to implement this two methods und `UpdateItemIndexes` will fail.

https://github.com/statamic/cms/blob/v3.0.0-beta.9/src/Search/Index.php#L12-L15

Should we declare the messages as Abstract on `Search\Index` or event provide an interface?

**Comment by jasonvarga** [comment]
I don't think an interface is necessary. You should be extending the base index class.

**Comment by psren** [comment]
Yep, now its fine :-) Thanks a lot.
