### ISSUE TITLE
Statamic tries to set last_login when I log in

### ISSUE THREAD

**Issue by syntheticminds** [statamic/cms#1208]
My project has database users that are separate from Statamic's file-based users. However, when the  `\Illuminate\Auth\Events\Login` event is called, Statamic fires its `\Statamic\Auth\SetLastLoginTimestamp` which tries to update the last_login for my user through the UserRepository. This of course fails because my user isn't in Statamic's user database.

**Comment by jasonvarga** [comment]
Try upgrading statamic/cms? This should have been fixed in #1195

**Comment by syntheticminds** [comment]
Yes, upgrading fixed this issue. I'll be sure to be running the latest version next time.
