### ISSUE TITLE
NotFoundHttpException when deleting collections with modified CP_ROUTE

### ISSUE THREAD

**Issue by BrandonJamesBorders** [statamic/cms#1209]
Testing integrating Statamic into an existing Laravel 6.2 project. Changed statamic/cp.php route to 'cms' to avoid route conflicts in the existing project. 

Created structures and collections worked fine, but I'm unable to delete them. Changing the config back to 'cp' (and changing my Laravel project routing) is the only way to delete the collection. 

````
{
    "message": "",
    "exception": "Statamic\\Exceptions\\NotFoundHttpException",
    "file": "/var/www/my-project/vendor/statamic/cms/src/Http/Controllers/FrontendController.php",
    "line": 47,
    "trace": [
        {
            "function": "index",
            "class": "Statamic\\Http\\Controllers\\FrontendController",
            "type": "->"
        },
        ...
    ]
}
````

**Comment by jasonvarga** [comment]
Thanks!

**Comment by BrandonJamesBorders** [comment]
Thank you!
