### ISSUE TITLE
Tags wont be parsed correctly in conditions

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1213]
I am using custom Tag, to fetch errors from the error bag. Putting the custom tag inside a condition will throw an error:

```{{ error:name }}``` 
This will show the output and does behave as expected. I want to wrap the error message inside a span as shown in the error exception.

<img width="1124" alt="Screen Shot 2020-01-15 at 21 45 43" src="https://user-images.githubusercontent.com/38906163/72470087-9b8afa80-37e0-11ea-96ab-212eb2d704fe.png">

As we can see, the {error:name} tag won't be parsed correctly, so the if condition stays empty. I think this is where the error comes from.

This is the dd() from the Antlers Parser.
<img width="1124" alt="Screen Shot 2020-01-15 at 21 49 10" src="https://user-images.githubusercontent.com/38906163/72470404-118f6180-37e1-11ea-83c2-777d0a600bab.png">

I would expect the Tag result inside the if condition, which is empty and causing the error.
<img width="518" alt="Screen Shot 2020-01-15 at 21 49 42" src="https://user-images.githubusercontent.com/38906163/72470453-279d2200-37e1-11ea-9c29-5097fb8088fa.png">

**Comment by jonassiewertsen** [comment]
It stays the same, when the tag is returning a boolean.

**Comment by jasonvarga** [comment]
Are you on the latest version of statamic/cms?

**Comment by jonassiewertsen** [comment]
I am on beta 9

**Comment by jonassiewertsen** [comment]
It's solved with beta 10.

haven't seen the new version. Sorry!

**Comment by jasonvarga** [comment]
I forgive you!
