### ISSUE TITLE
Permission groups appear as 'Miscellaneous'

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1215]
Whenever I create permission groups, like I do below, the permissions appear in the right group but the title of it says `Miscellaneous` instead of `Commerce` which is what I want it to be.

```php
Permission::register('view products', function ($permission) {
                $permission->children([
                    Permission::make('edit products')
                        ->label('Edit Products')
                        ->group('Commerce')
                        ->children([
                            Permission::make('create products')
                                ->label('Create Products')
                                ->group('Commerce'),
                            Permission::make('delete products')
                                ->label('Delete Products')
                                ->group('Commerce'),
                        ]),
                ]);
            })->label('View Products')->group('Commerce');
```

Here's also a screenshot of what's going wrong.

![image](https://user-images.githubusercontent.com/19637309/72544185-c7f55400-387e-11ea-8982-ea01dbe3c614.png)

As it's not documented, I could be doing this wrong.

**Comment by jasonvarga** [comment]
It's documented: https://statamic.dev/extending/permissions#groups

Wrap that whole block in `Permission::group`, and then you don't need to add `->group()` to each one.

**Comment by damcclean** [comment]
🤦‍♂️ I'm sure it wasn't there when I last looked. Must be near the weekend.

**Comment by jasonvarga** [comment]
Before it was documented, it was undocumented. You aren't lying.
