### ISSUE TITLE
Text for messages.collection_wizard_structure_instructions is missing

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1216]
One instruction sentence in the collection wizard is missing:
 
messages.collection_wizard_structure_instructions

<img width="951" alt="Bildschirmfoto 2020-01-17 um 10 39 58" src="https://user-images.githubusercontent.com/8265902/72601593-fa9e5b80-3915-11ea-9e49-2550639128c2.png">

**Comment by jackmcdade** [comment]
Nice catch, thanks!
