### ISSUE TITLE
Select Fieldtype won't store key correctly when integer

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1217]
The Fieldtype is only storing the keys if those are strings containing chars.

```
'handle' => 'taxes_id',
'field'  => [
    'type'         => 'select',
     'display'      => 'taxes',
      'options' => [
             3       => 'Label 3', // NOT saving 3
             '4'      => 'Label 4', // NOT saving '4'
             'five'  => 'Label 5', // Saving  'five'
            ],
  ...
```

All labels will be shown correctly. 

Unless the key is a string containing chars, it won't be saved.

In my case, I want to save related IDs inside an SQLite database, but the select field does save the label instead of the value.

**Comment by jackmcdade** [comment]
How are you using an SQLite database?

The select field should store (and does in my tests w/ default YAML) the key, but Augmentation will display the value unless you use the `raw` param. https://statamic.dev/fieldtypes/select#templating

**Comment by jonassiewertsen** [comment]
I am fetching data from an SQLite database (it's an addon), am showing the relations inside a dynamically created Blueprint. The user can select his choice and will save it afterward. 

It is working correctly with slugs, but I wanted to use it with ids (integers). 

Let me show my code for the slug version. Exactly the same version is not willing to work with integers. I am not sure how to use the raw param here?

The Blueprint part
```
Blueprint::make()->setContents([
// more stuff
[
      'handle' => 'tax_id',
          'field'  => [
                'type'         => 'select',
                'display'      => __('statamic-butik::cp.taxes'),
                'options'      => $this->fetchTaxOptions(),
                'width'         => '25',
                'validate'      => 'required|exists:taxes,slug'
             ],
     ],
// more stuff
 private function fetchTaxOptions() {
    return Tax::pluck('title', 'slug')->toArray();
 }
```

My store method does look something like this
````
$blueprint = new ProductBlueprint();
$fields = $blueprint()->fields()->addValues($request->all());
$fields->validate();
$values = $fields->process()->values();
Product::create($values->toArray());
```

**Comment by ReneWeCode** [comment]
I don't think it has anything to do with the choice of database or database at all. I got the same issue when just using default setup without database.
When creating the select fieldtype and adding options where the keys are integers it seems like it only saves the labels.

**Comment by jackmcdade** [comment]
Hmm, it's possible Statamic is assuming it's just a regular indexed array instead of one keyed with specific indexes. @jasonvarga, thoughts?

**Comment by jasonvarga** [comment]
Haven't confirmed yet, but that definitely sounds feasible.

**Comment by ReneWeCode** [comment]
Do you guys need any info for this issue?

**Comment by jackmcdade** [comment]
Fixed on `master`.
