### ISSUE TITLE
Error when creating a structure

### ISSUE THREAD

**Issue by nouce** [statamic/cms#1218]
![Schermopname 2020-01-17 om 13 24 38](https://user-images.githubusercontent.com/45368779/72614988-e5d0c080-3933-11ea-9e8b-7c1357fd491f.gif)
See GIF!

**Comment by jackmcdade** [comment]
Thanks for the heads up! Structures are getting a bit of a rework this week. Stay tuned.

**Comment by jackmcdade** [comment]
Closing this because the Structures section is being replaced by a "Nav Builder" feature and collections are gaining the ability to be "structured".
