### ISSUE TITLE
Link existing item (page) into new structure fails

### ISSUE THREAD

**Issue by codedge** [statamic/cms#1223]
Hi,

I created an empty structure and try to link existing pages into it.

**`footer.yml` structure file**
```yml
title: 'Footer section'
```

This fails with the following error message:

`Cannot read property 'linkExistingItem' of undefined`

![image](https://user-images.githubusercontent.com/4409904/72656425-5f4fc980-399b-11ea-8df1-3bba5ca630ad.png)

I run the latest beta-`11`.

**Comment by codedge** [comment]
Works without problems now. Maybe some side effect of another issue.

**Comment by orlyapps** [comment]
@codedge i got the same problem. How did you solved this?

**Comment by codedge** [comment]
As I wrote, I didn't do anything special. I upgraded to the latest version of Statamic, deleted the affected structures by hand and created everything from scratch using the UI.
