### ISSUE TITLE
Can not get the get the key of a select fieldtype

### ISSUE THREAD

**Issue by lightbringer93** [statamic/cms#1230]
I have a select field for button variants, where i can chose my button color. 
![Screenshot](https://user-images.githubusercontent.com/27002677/72667329-1a6b7780-3a1b-11ea-9302-9200b81fdae6.png)
But in my partial I can not access the key of the selected option. In my btn_class the label is stored instead and that is why I have to slugified. In my opinion the key should also be in the variable. Is there a modifier to get the key? 
```
<!-- Button
============================================= -->
<a class="btn btn-{{ btn_class | slugify }}{{ btn_triangle ??= ' btn-triangle' }}"
   href="{{ btn_internal_link:slug ?? btn_external_link }}"
   target="{{ btn_external_link ? '_blank' : '_self' }}"
   role="button">
    {{ btn_text }}
</a>
```

**Comment by jackmcdade** [comment]
Yep! `{{ select_field | raw }}` You can read more in the docs: http://docs.test/fieldtypes/select#templating

**Comment by lightbringer93** [comment]
Thank you for your help. 
But even after I added the raw modifier my btn_class still gets the label value. 
```
<!-- Button
============================================= -->
<a class="btn btn-{{ btn_class | raw }}{{ btn_triangle ??= ' btn-triangle' }}"
   href="{{ btn_internal_link:id | url ?? btn_external_link }}"
   target="{{ btn_external_link ? '_blank' : '_self' }}"
   role="button">
    {{ btn_text }}
</a>
```
`{{ btn_class | raw | dump }}` I dumped the value and receive "Primary"?
