### ISSUE TITLE
Wrong title is displayed when edit forms

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1235]
Edit form window shows wrong title: It should be 'Forms' instead of 'Collections' I guess?
<img width="586" alt="Bildschirmfoto 2020-01-20 um 12 11 27" src="https://user-images.githubusercontent.com/8265902/72722289-3f2c3000-3b7e-11ea-8195-e2647e68cf56.png">

**Comment by damcclean** [comment]
It looks like this is because the forms use the Collections edit form instead of their own edit form. If it had it's own edit form, that would fix it.

https://github.com/statamic/cms/blob/master/resources/js/components/collections/EditForm.vue#L19

**Comment by jackmcdade** [comment]
Good one, thanks!
