### ISSUE TITLE
Password tokens sometimes invalid for invited CP user

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1236]
When inviting users in the CP by sending them a mail, they do get the error message that the password reset token is invalid. 

The time between sending the mail and trying to set the password via the invitation link has only been 2 hours.

**Comment by jasonvarga** [comment]
They expire after one hour. https://github.com/statamic/statamic/blob/master/config/auth.php#L102

**Comment by jonassiewertsen** [comment]
Must be a bug then
<img width="839" alt="Screen Shot 2020-01-20 at 16 20 04" src="https://user-images.githubusercontent.com/38906163/72737950-d6a27a80-3ba0-11ea-9834-d7616579c535.png">

**Comment by jasonvarga** [comment]
Ah just incorrect text.

**Comment by jasonvarga** [comment]
You're free to change it.

**Comment by jonassiewertsen** [comment]
Is it possible to cover two use cases, which would make sense in my opinion:

**Normal password reset**
The user does request it himself, so one hour is fine.

**Inviting a user to 'create his account**
Will be done by an admin. That the user is around exactly that hour can't be expected.

**Comment by jasonvarga** [comment]
Opened an issue in statamic/ideas on your behalf.
