### ISSUE TITLE
UX: Adding a page from the structure overview doesn't change the navigation correctly

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#1239]
- On the pages structure
- Click "Create page"
- Breadcrumbs show "Structures -> Pages -> Create Entry"
- Nav shows "Collections -> Pages"
- Click Save & Publish
- Nav changes to "Structures -> Pages"

The whole Structures vs Collections thing is overall pretty hard to wrap your head around, but I do know you gents are still working on that.

**Comment by jackmcdade** [comment]
Thanks for the heads up! Structures are getting a bit of a rework this week. Stay tuned.

**Comment by jasonvarga** [comment]
Should be irrelevant in the next release because of the structure-related changes.
