### ISSUE TITLE
Cannot find collections when using multiple sites

### ISSUE THREAD

**Issue by codedge** [statamic/cms#1240]
Hey,

there seems to be some issue in finding collections when in multi-site mode.

**`CollectionEntryStore..php`**

* [Line 34](https://github.com/statamic/cms/blob/master/src/Stache/Stores/CollectionEntriesStore.php#L34): `$collection` is `"/Users/holger/code/stmr/stmr-website/content/collections/links"`
* [Line 35](https://github.com/statamic/cms/blob/master/src/Stache/Stores/CollectionEntriesStore.php#L35): `$collection ` is only `links`

Now on [line 38](https://github.com/statamic/cms/blob/master/src/Stache/Stores/CollectionEntriesStore.php#L38) the following thing fails

```php
/**
 * explode() returns an array
 * array [
 *    0 => "links"
 * ]
 * 
 * list() cannot access the first [1] index and fails
*/
list($collection, $site) = explode('/', $collection);
```

Now this fails with `Undefined offset: 1`.

<img width="997" alt="grafik" src="https://user-images.githubusercontent.com/4409904/72759684-ae357300-3bd6-11ea-8b29-a8761a964681.png">

**Comment by jasonvarga** [comment]
Do you have your entries in site subdirectories?

```
content/collections/links/
|-- site1/
|   |-- entry.md
|-- site2/
```

**Comment by codedge** [comment]
That was it. Thanks!
Is there somewhere some guideline what to check or how to built a multi-lang site? What to take care of? How should the site name be? How to change the `sites.yml`? Do I always need a `default` key for one of the sites in `sites.php` ? etc.

I just can find small pieces scattered across various pages sometimes 6 years old.

**Comment by jasonvarga** [comment]
What do you mean 6 years old?

**Comment by codedge** [comment]
So for example I am missing a kind of "How to built a multi-lang site with Statamic" where things are explained in detail, what issues may arise, where to look first. Most of the things around multi-language are in the Statamic forum (good thing) - [example here ](https://statamic.com/forum/36-multi-language-support) from 2014, [another one](https://statamic.com/forum/2347-how-to-localize-a-statamic-page) from 2016.

**Comment by jasonvarga** [comment]
Got it. Well this is v3 so it'll be in the v3 docs. https://statamic.dev/multi-site
We'll improve that page.
