### ISSUE TITLE
Missing "Create Entry" button when a collection doesn't have a blueprint defined

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1241]
It looks like only after creating the first collection (from 0 to 1) are no buttons displayed.

### Steps to reproduce 

1. Start with a brand new installation via composer, make:user, CP login
2. Create a collection

There are no 'Create Entry' buttons visible.

3. Create another collection

'Create Entry' buttons are visible on both collections.

4. Delete one collection

'Create Entry' buttons are still visible.

5. Delete the second collection too.
6. Create a new collection again

There are again no 'Create Entry' buttons visible.

<img width="1427" alt="Bildschirmfoto 2020-01-21 um 00 12 02" src="https://user-images.githubusercontent.com/8265902/72763454-25bdcf00-3be4-11ea-9d2d-dedb36de647f.png">

**Comment by jasonvarga** [comment]
The reason is because you haven't defined a blueprint. That'll get you going.

I'll leave this open though, because we obviously need to fix the UX. Thanks!

**Comment by helloDanuk** [comment]
Yup, that's it!

I thought, I could go with the 'default' blueprint, if I did not choose one explicit.

**Comment by jasonvarga** [comment]
Actually, yes you're right. You should be able to do that.

**Comment by jackmcdade** [comment]
All fixed!
