### ISSUE TITLE
UserRegistrar is broken

### ISSUE THREAD

**Issue by syntheticminds** [statamic/cms#1242]
`Call to undefined method Statamic\Fields\FieldsetRepository::get()`

I guess this bit isn't done yet because `Statamic\Auth\UserRegistrar` is still looking for my user Fieldset instead of Blueprint (and using `get()` instead of `find()`). Additionally, it is trying to handle usernames too.

**Comment by jasonvarga** [comment]
Duplicate of #1080, sorta. We'll just track it there.
