### ISSUE TITLE
Collection new entry not working

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1244]
After clicking new entry, there is no shown blueprint:
New entry:
![image](https://user-images.githubusercontent.com/3351449/72887468-091cb680-3d0c-11ea-9208-f41dea271ba4.png)
After click empty blueprint:
![image](https://user-images.githubusercontent.com/3351449/72887505-1cc81d00-3d0c-11ea-9cd8-f27efd6b4eda.png)
Collection settings:
![image](https://user-images.githubusercontent.com/3351449/72887566-3ec19f80-3d0c-11ea-85f6-5ca00ffcd0ef.png)
Bluerpint with fieldsets:
![image](https://user-images.githubusercontent.com/3351449/72887594-4f721580-3d0c-11ea-8770-b6dd29a99ac2.png)

**Comment by Pfeifakopf** [comment]
If you create new collections or taxonomies as multi-site, the array
```
sites
  - site1
  - site2
```
is not written into the yaml files by the control panel. If you add the array manual, the blueprint loads normally.

**Comment by jackmcdade** [comment]
Should be all sorted now!
