### ISSUE TITLE
Bard: Inserting a set between two existing sets duplicates the set below the cursor instead of inserting the new set

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#1247]
Sometimes, when two sets are right after one another, we can reproduce the following in Chrome:

1. click between the sets to get a cursor (there will be a horizontal and a vertical one, strangely)
2. hit Enter to get a proper paragraph and make the + appear on the left
3. select a set to insert from the button's drop down
4. instead of a new set of the selected type, the set below the empty paragraph is duplicated

![Screencast](https://i.imgur.com/QHCdhjn.mp4)

It doesn't matter what type the two sets have at the beginning, and what type of set is selected from the + button.

This is not reproducible starting from the "new entry" but happens with migrated data. Bard works fine with the migrated data apart from this issue. I can't paste the raw data due to copyright, unfortunately, but I'll dm it to you on Discord.

**Comment by sauerbraten** [comment]
I reduced the Bard content by deleting stuff piece by piece and it happens with just two sets:

    > JSON.stringify($0.__vue__.$children[0].json)
    
    [{"type":"set","attrs":{"id":"set-3","enabled":true,"values":{"type":"video","video":null,"placement":"center"}}},{"type":"set","attrs":{"id":"set-4","enabled":true,"values":{"caption":"[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"Protest f\\u00fcr Klimaschutz: Norwegische Umweltsch\\u00fctzer sonnen sich am Fjord von Longyearbyen - normalerweise ist er um diese Jahreszeit noch v\\u00f6llig zugefroren\"}]}]","image":["97dec13f-0001-0005-0000-000000855933"],"placement":"right","type":"image","zoomable":false}}}]

where `$0` is the `<div class="bard-fieldtype">`.

And I realized now that there is an error message:

    vue.common.prod.js:6 TypeError: Cannot read property 'replicator_preview' of undefined
        at ManagesPreviewText.js:13
        at underscore.js:255
        at Function.v.each.v.forEach (underscore.js:191)
        at Function.v.filter.v.select (underscore.js:254)
        at v.each.v.<computed> [as filter] (underscore.js:1639)
        at a.previewText (ManagesPreviewText.js:11)
        at pn.get (vue.common.prod.js:6)
        at pn.evaluate (vue.common.prod.js:6)
        at a.previewText (vue.common.prod.js:6)
        at a.<anonymous> (Set.vue?36d6:1)

**Comment by joroe** [comment]
@sauerbraten have you found a way around this bug? I get similar behavior in a bard field with the same error Cannot read property 'replicator_preview' of undefined

Is this scheduled to be investigated and fixed? Thanks, guys!

**Comment by sauerbraten** [comment]
I don't think so, but I tried to reproduce it just now and was not able to... 🤔

**Comment by joroe** [comment]
Was it solved after update or after other changes?

**Comment by sauerbraten** [comment]
Probably just an update. We regularly integrate the master branch into our setup, so I can't tell you exactly when this was fixed for us. Does it happen for you on the current master? Maybe it reappeared in a recent commit. We're currently on cc4b3bd77921faec64af799fcfc27a4c7c6b9022 I believe.

**Comment by edalzell** [comment]
@joroe is this still happening for you?

**Comment by jasonvarga** [comment]
Hey there, we haven’t heard back on this for a while so I’m going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!
