### ISSUE TITLE
Unintended rewrite of field handle

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#1249]
When you reopen a newly created field, the handler is rewritten back to if it wasn't set.

This happens before the field is saved.

![handle-rewrite](https://user-images.githubusercontent.com/43215436/72982954-8fa2c800-3de0-11ea-83de-d7a94eaa046a.gif)

**Comment by AndreasSchantl** [comment]
This is one annoying bug. Just writing this comment in the hopes that this one get's a higher priority. 

I am used to look up the handles after being done with creating the blueprints. This keeps me looking in the files directly, which is not that convenient in my current workflow.

**Comment by miclf** [comment]
I’ve encountered the same issue. Screenshot:

<img width="1132" alt="foo" src="https://user-images.githubusercontent.com/3188746/89674534-9a3e2e00-d8e8-11ea-9eb4-0685fd252eef.png">

The second field here (handle) has the correct value in the YAML file of the blueprint. But that value is not loaded here (or it is immediately overwritten by this automatic slug thing). If I save the config as is, the YAML file then gets the new, incorrect value.

So, if we’re not careful to manually rewrite the handle every time we update the field config, the handle gets wrongly modified and then everything breaks.

**Comment by jesseleite** [comment]
Just a note (worked this out with @miclf in Discord) that it doesn't happen on a saved blueprint field, only when creating a new field.
