### ISSUE TITLE
Renaming role or user group should update all users

### ISSUE THREAD

**Issue by Sceko** [statamic/cms#1250]
I find bug i create role and role group add role in group, set user role and thats all okej, but if change role name, user not exist anymore

after change in file users 
roles:
  - etc
i back user in admin panel

that not working and 1 more set only 1 role and display 2 role 
![Screenshot 2020-01-23 at 10 40 52](https://user-images.githubusercontent.com/2323952/72973071-d5559580-3dcc-11ea-82a3-a805c8178677.png)

and add name of permision not number

![Screenshot 2020-01-23 at 10 44 18](https://user-images.githubusercontent.com/2323952/72973294-50b74700-3dcd-11ea-9a4b-1552b37e40bc.png)
Better add to display what permision your sellect like Configure Globals and not number 1

**Comment by jasonvarga** [comment]
If you assign a role or group to a user, they get the handles added to their account.

If you change the handle, the user's files don't get updated - they will still have the old handle in their account.

You could do a find/replace inside all the user files.

**Comment by Sceko** [comment]
i know that i write that but better add that future

**Comment by damcclean** [comment]
Looks like there's now a warning when you try to rename the handle of a role. I think this is probably the best Statamic can really do. 

The same thing can be said about issues. When you rename an asset, you will also lose all links to that asset in entries and anywhere else you've referenced it.
