### ISSUE TITLE
Mail change but nothing

### ISSUE THREAD

**Issue by Sceko** [statamic/cms#1251]
Configuration
Mail settings are configured in /Users/sceko/code/statamic3/config/mail.php

I change in .env but not displey in panel always old config

/// edit work fine my error 

but i find what not include in .env 
MAIL_FROM_ADDRESS=
MAIL_FROM_NAME=

Add like default

**Comment by jasonvarga** [comment]
Hi, looks like you edited your comment to say it was your error.

Is there still a problem?

**Comment by Sceko** [comment]
No fix but in .env better add 
MAIL_FROM_ADDRESS=
MAIL_FROM_NAME=
To people know what missing
