### ISSUE TITLE
Cannot delete fieldsets

### ISSUE THREAD

**Issue by Sceko** [statamic/cms#1252]
![Screenshot 2020-01-23 at 10 57 38](https://user-images.githubusercontent.com/2323952/72974384-32eae180-3dcf-11ea-9570-700924989c10.png)
after create and wont delete can not nothing after click delete
and for blueprints same

DELETE http://statamic3.test/cp/cp/fields/fieldsets/naslov 404 (Not Found)

**Comment by jasonvarga** [comment]
Fixed in #1231
