### ISSUE TITLE
Entry CP page, responsiveness "issue"

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1259]
On my wee little MacBook, the edit entry has this at the bottom, which is a bit weird

<img width="1057" alt="Edit Entry ‹ Addons ‹ Collections ‹ Statamic 2020-01-23 18-03-33" src="https://user-images.githubusercontent.com/6069653/73039411-cdb4e180-3e0a-11ea-9e80-0eee89de67f5.png">

**Comment by jackmcdade** [comment]
What’s wrong?

**Comment by edalzell** [comment]
I would have expected that stuff at the top?

**Comment by jackmcdade** [comment]
So that when you finish writing you have scroll back up to save?

**Comment by edalzell** [comment]
Save is at the top though, have to scroll back up there (yes I know you can use cmd-s to save).

Perhaps I'm alone here...feel free to close if it's not inline with what you had in mind.
