### ISSUE TITLE
Custom fieldtype properties displayed twice

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1264]
I've built a custom fieldtype and when I look at the settings of it in my Blueprint some of the fields are being duplicated.

I'm not adding anything to the fieldtypes settings myself so this must be a Statamic bug.

![image](https://user-images.githubusercontent.com/19637309/73119577-dff26500-3f5b-11ea-9108-7ec915f250b1.png)

**Comment by jackmcdade** [comment]
Hmmmmm. I can't recreate this. At first I thought it might have been the Relationship field but that didn't do it either. I looked at SimpleCommerce's fieldtype configs and mimicked em as best i could but also, nope. 

Are you still having this issue? I'm a bit stumped!

**Comment by damcclean** [comment]
Seems to be gone now. 

I think I remember it actually coming up on all fieldtypes but that could be a dream 😂
