### ISSUE TITLE
Cannot select taxonomy in the UI for the taxonomy field

### ISSUE THREAD

**Issue by lightbringer93** [statamic/cms#1268]
In the Taxonomy fields there should be an option to add the specific taxonomy group, so users are not able to choose from unwanted taxonomies. 
![Screenshot](https://user-images.githubusercontent.com/27002677/73137960-c3d6ec80-405d-11ea-8753-707f490aa05f.png)

**Comment by jackmcdade** [comment]
I think the fact that you can pick Taxonomy at all is a bit of a bug. Taxonomies are defined on the Collection level, not the blueprint.

**Comment by jonassiewertsen** [comment]
I just ran into the same problem, to let the user choose from a specific taxonomy. 

The option to select a taxonomy seems to be missing, as shown in the picture above.

**Comment by lightbringer93** [comment]
I solved the problem now by simple creating a collection of employees and not handling it with the users.

**Comment by syntheticminds** [comment]
I was just about to create an issue for this. In my use case, I want users to only be able to select one term. I believe the collection-level tagging doesn't allow this.

Plus, I may want to limit allow the users to select from multiple taxonomies in a single field.

I have this working at the moment by manually setting the `taxonomy` option in the blueprint and it's working well.

**Comment by mikemartin** [comment]
@jasonvarga The `taxonomies` config field doesn't appear to restrict the field to a single taxonomy. Setting the `taxomony` option manually seems to do it but it's not possible from the fieldtypes UI.

Here's my example. I'm using the `taxonomy` fieldtype to output a list of terms.
```
    handle: zone
    field:
      mode: default
      type: taxonomy
      localizable: false
      listable: hidden
      display: Zones
      taxonomy: zones
```
