### ISSUE TITLE
Addons can't be installed

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1273]
Addons can't be installed via composer at the moment.

```
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In AddonServiceProvider.php line 273:

  Call to a member function id() on null


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

It could be related to the beta 12 update.

**Comment by jackmcdade** [comment]
What addon are you trying to install?

**Comment by jonassiewertsen** [comment]
https://github.com/jonassiewertsen/butik-test/

**Comment by damcclean** [comment]
What does the addon's `composer.json` file look like?

**Comment by jonassiewertsen** [comment]
The repo is public now

**Comment by jackmcdade** [comment]
That repo is a site though not an addon. What addon are you trying to install?

**Comment by jonassiewertsen** [comment]
Sorry, my fault. Did a copy and paste error. 

Now the correct repo has been referenced.

**Comment by jonassiewertsen** [comment]
https://github.com/jonassiewertsen/statamic-butik

**Comment by jonassiewertsen** [comment]
@jackmcdade Can you reproduce the issue?

**Comment by damcclean** [comment]
Was about to give it a try myself but the repo seems to be private again or have been deleted.

**Comment by jackmcdade** [comment]
Same.

**Comment by jonassiewertsen** [comment]
made it private again to minutes ago.

**Comment by jonassiewertsen** [comment]
public again!

**Comment by jasonvarga** [comment]
![](https://media.giphy.com/media/3j2aS43hyNJW8/giphy.gif)

**Comment by jackmcdade** [comment]
Ah, I can't test this right now as it requires PHP 7.4 and I don't have time to switch my dev environment around today. Tomorrow perhaps!

**Comment by jonassiewertsen** [comment]
It seems to relate to the beta 12 update. When forcing composer to use the beta 11 version, the installation goes through.
