### ISSUE TITLE
Improve the way we access next/previous entries

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#1276]
## We have some bugs

Right now the `collection:next` and `collection:previous` tags are reversed when in a dated context. Given the most common use case of beginning to read/browse at the beginning/newest entry (LTR) and going onwards to the older, you would have these links:

`<< Previous (already read, newer) || Next (haven't read, older) >>`

This is easily confusing though, and I know we've had it wrong a dozen times at various phases of dev (v1, v2, v3) and maybe I have it wrong now and am thinking backwards. Please correct me if so.

I tried to fix it locally in the template by adjusting the sorting (`date:desc`), but the param wasn't respected.

## We could be clearer

I think we should also add `collection:newer` and `collection:older` tags/aliases to make this much easier to intuit. Way less confusing, and would only apply to dated collections.

**Comment by edalzell** [comment]
I never ever ever remember which way is "next" due to sorting, I'd love something clearer like `newer` that looks at the sorting, for date collections.

**Comment by jesseleite** [comment]
Fixed, and added `collection:newer` and `collection:older`.
