### ISSUE TITLE
Duplicated Grid row with Asset column

### ISSUE THREAD

**Issue by dougstjohn** [statamic/cms#1277]
If you duplicate a Grid row that has an Asset column and then remove the Asset from the new row, it also removes the Asset from the original row.

Steps to reproduce:
- Set up the starter-kit-cool-writings site
- Go to Globals > Settings
- Duplicate any row that has an Icon asset
- Remove the asset from the new row by clicking the trash bin
- Asset is removed from the both rows

Duplicating row:
<img width="1023" alt="duplicate-row" src="https://user-images.githubusercontent.com/3673451/73393341-b48fb300-4298-11ea-8375-9dd485359183.png">

After removing asset from new row:
<img width="1016" alt="both-assets-removed" src="https://user-images.githubusercontent.com/3673451/73393342-b5284980-4298-11ea-82b8-90380c8b3a4a.png">

**Comment by jackmcdade** [comment]
Confirmed! Thanks for the report.

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
