### ISSUE TITLE
Pages collection entry requiring a structure

### ISSUE THREAD

**Issue by dougstjohn** [statamic/cms#1279]
I'm getting an error when I create a Pages collection entry (it's auto-added to the structure), and then I delete it from the structure and go back and look at the collection entry.

Call to a member function parent() on null 
Statamic\Entries\Entry::parent :496

A Pages collection entry appears to need a structure.

**Comment by jasonvarga** [comment]
Obviously this part needs some love, but I'm curious why you want an entry in there that's not in the structure?

**Comment by dougstjohn** [comment]
In this case I was using the cool writings starter kit and it uses the Pages structure as the top nav listing so every Page entry added ended up in the top nav.

**Comment by marflow** [comment]
I ran into this for the same reason: I want to exclude two pages (legal, privacy) from my main pages navigation, but that´s not possible. Also, `{{ nav:pages exclude="legal|privacy" }}` is not working. Also it seems, if a page is not included in the pages structure, it can not be reached from the front-end. Getting 404.

**Comment by jasonvarga** [comment]
Should be irrelevant in the next release because of the structure-related changes. Please re-open if not.
