### ISSUE TITLE
Glide Tag Pair doesn't work

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#1280]
Hello,

Getting this error when using glide pair tag:

```bash
Facade\Ignition\Exceptions\ViewException
Call to a member function disk() on null
```

I'm using `https://github.com/statamic/starter-kit-cool-writings`.
I've just changed the content of the first article to add an image:

**1996-11-18.dance.md**
```yaml
image:
  - content/reebok-pumps.jpg
```

As explained here: https://statamic.dev/tags/glide#tag-pair
I then add in the template:

**show.antlers.html**
```twig
{{ glide:image width="600" }}
    <img src="{{ url }}" width="{{ width }}" height="{{ height }}">
{{ /glide:image }}
```

Thanks

**Comment by jackmcdade** [comment]
Did you add the `image` field to your Blueprint and choose the proper asset container?

**Comment by jimblue** [comment]
Ya I did had an asset field in the article blueprint:

```md
-
        handle: image
        field:
          container: assets
          mode: grid
          restrict: false
          allow_uploads: true
          type: assets
          localizable: false
          listable: hidden
          display: Image
```

**Comment by jimblue** [comment]
And this is working in the article template:

```twig
{{ image }}
        <img src="{{ glide:url width='400' }}">
{{ /image }}
```

**Comment by jackmcdade** [comment]
Ah yeah cuz it's an array. Add `max_files: 1` if you only want to have 1 image and it'll work fine, otherwise do the loop. You're good to go! 👍

**Comment by jimblue** [comment]
I'm having the same error with an array @jackmcdade

**Comment by jackmcdade** [comment]
If you resave the entry it'll be saved as a string and will snap into place.

**Comment by jimblue** [comment]
I've select 3 images in the control panel and saved, now it looks like this

```md
image:
  - content/lagoa.jpg
  - content/reebok-pumps.jpg
  - content/surge.jpg
```

Still getting:
```bash
Facade\Ignition\Exceptions\ViewException
Call to a member function disk() on null
```

**Comment by jackmcdade** [comment]
You said it was working? Are you doing this?

```
{{ image }}
    {{ glide:url width='400' }}
        <img src="{{ url }}">
    {{ /glide:url }}
{{ /image }}
```

**Comment by jimblue** [comment]
You read a bit too fast 😄 

I said this is working:
```twig
{{ image }}
        <img src="{{ glide:url width='400' }}">
{{ /image }}
```

but this it not:

```twig
{{ glide:image width="600" }}
    <img src="{{ url }}" width="{{ width }}" height="{{ height }}">
{{ /glide:image }}
```

So maybe the doc is wrong? Has I said I'm following this exemple: https://statamic.dev/tags/glide#tag-pair

**Comment by jasonvarga** [comment]
I think the confusion is probably that the glide tag pair doesn't loop over multiple images. It just exposes variables _about one image_ between the tag pair.

You still need to loop over `image`.

**Comment by jackmcdade** [comment]
The docs are for a single asset, not an array of assets. Follow this example here: <https://github.com/statamic/cms/issues/1280#issuecomment-580457651>

**Comment by jasonvarga** [comment]
Saying that, there's not really any reason we can't make it loop through multiple images.

**Comment by jimblue** [comment]
Hum ok, I understood that Glide tag pair was a loop.

**Comment by jimblue** [comment]
Tough it was an abstraction of a loop+glideTag to resize an array of images.

**Comment by jackmcdade** [comment]
Nope, nor is that anywhere in the docs. Sorry for any confusion! But like Jason said, we could add support for that. It's just not how it works.

**Comment by jimblue** [comment]
No worries now it's clear and it's perfectly working.
I'm just wondering if the doc could be improved for other.
But it's maybe just me that miss understood.

**Comment by jimblue** [comment]
Ya as Jason said it could be nice to support looping trough an array of image with a glide tag.
Shorter version is always better nope? :)
Thank you for your help ! 🙏

**Comment by jasonvarga** [comment]
Supported in the next release.

**Comment by jimblue** [comment]
Wow that was fast 🚀 !
 Thanks Jason

**Comment by jimblue** [comment]
Hey @jasonvarga,
I'm having this exact same error again just after upgrading to v3.0.0-beta.32
This release might have introduced a regression has I didn't change anything on my side.

**Comment by jasonvarga** [comment]
Should be fixed in beta 33 which I'm releasing in a couple of minutes.
