### ISSUE TITLE
Cannot create term in taxonomy on multi-site

### ISSUE THREAD

**Issue by AndersMFJ** [statamic/cms#1284]
I get an error when trying to save and publish a new term in a taxonomy, and no new term is created. I'm using a multi-site setup (two sites) and the taxonomy is set up to work with both sites:

```
title: 'Article types'
blueprints:
  - taxonomy
sites:
  - en
  - sv
```

The error message I get is as follows: "Something went wrong"

I have a couple of other taxonomies that are only set up for one the sites (the 'sv' site) and those work fine.

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
