### ISSUE TITLE
bard field - fixed toolbar is broken

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#1289]
Just tried the option fixed  of bard field toolbar and the style seems broken:

<img width="2160" alt="Screenshot 2020-02-01 at 17 51 28" src="https://user-images.githubusercontent.com/10623367/73596668-81f9ea80-4524-11ea-8fc0-9d84cb8d3c44.png">

**Comment by jackmcdade** [comment]
Dude, that looks hot! It's just a 2020 design trend.

😉

**Comment by jimblue** [comment]
My grandma already love it 😝

**Comment by jackmcdade** [comment]
![image](https://user-images.githubusercontent.com/44739/73884463-eaeaa680-4833-11ea-9e0e-af99a2fb010d.png)

**Comment by jimblue** [comment]
Actor studio grandma! I bet the screen is black haha 🙈
