### ISSUE TITLE
User avatar broken in users list page

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#1290]
The control panel does properly use the `avatar` field image in the top right button.
But for some reason in the user list view of the control panel it doesn't.

<img width="1024" alt="Screenshot 2020-02-01 at 19 35 01" src="https://user-images.githubusercontent.com/10623367/73597214-f420fe00-4529-11ea-94ef-306649239228.png">

**Comment by jackmcdade** [comment]
Confirmed! Thank you for the report, @jimblue!

**Comment by jimblue** [comment]
You're welcome and thank for the 🚀comit !!!
