### ISSUE TITLE
Blueprint / fieldset deletion confirmation

### ISSUE THREAD

**Issue by JonKaric** [statamic/cms#1291]
It's possible to accidentally delete an item, or delete the wrong one. A confirmation would help to make sure you want to bin it, or an undo popup `'Deleted [fieldset]. Undo this action?`.

**Comment by jackmcdade** [comment]
Thanks for the report. The "delete" actions are a bit rough around the corners. We'll make sure to address this.

**Comment by jesseleite** [comment]
There is now a confirmation modal 👍
