### ISSUE TITLE
Existing app custom namespace

### ISSUE THREAD

**Issue by philbenoit** [statamic/cms#1295]
When installing statimic into an existing app with a custom namespace the installation fails. 

`PHP Fatal error:  Uncaught Error: Class 'App\Exceptions\Handler' not found in /XXX/vendor/statamic/cms/src/Exceptions/Handler.php:12
Stack trace:
#0 /XXX/vendor/composer/ClassLoader.php(444): include()
#1 /XXX/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/philbeno...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Statamic\\Except...')
#3 [internal function]: spl_autoload_call('Statamic\\Except...')
#4 /XXX/vendor/laravel/framework/src/Illuminate/Container/Container.php(803): ReflectionClass->__construct('Statamic\\Except...')
#5 /XXX/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('Statamic\\Except...')
#6 /XXX/vendor/larav in /XXX/vendor/statamic/cms/src/Exceptions/Handler.php on line 12`

To replicate this, 

1. Load an existing application with a custom namespace for the application. 
2. Follow the install instructions for existing applications. 
3. Watch the world burn :)

**Comment by jackmcdade** [comment]
Thanks for the heads up! We'll see what can be done. I'm sure there are things.
