### ISSUE TITLE
Mixed content warning when accessing Assets browser

### ISSUE THREAD

**Issue by sfdrummer** [statamic/cms#1299]
We're getting a mixed content error when trying to access the Assets browser on the backend.  Statamic is trying to access the assets API (I presume) over HTTP instead of HTTPS, yet the rest of the site is running on HTTPS.

**Comment by jasonvarga** [comment]
Are you using Cloudflare?

**Comment by sfdrummer** [comment]
@jasonvarga Yes

**Comment by jasonvarga** [comment]
Cloudflare's IPs need to be added to your trusted proxies. 

Maybe look into using this package.
https://github.com/monicahq/laravel-cloudflare

**Comment by sfdrummer** [comment]
Many thanks, we'll look into that!

**Comment by sfdrummer** [comment]
We've installed the laravel-cloudflare package and we're still getting this issue.

**Comment by jasonvarga** [comment]
Did you remove the old middleware?

**Comment by sfdrummer** [comment]
Yes.  One of our developers has discovered that two slashes are being added on to the end of the API call which is redirecting to HTTP, _"/admin/assets/browse/folders/assets//?page=1&perPage=30&sort=basename&order=asc&search="_.

He has proposed a change to the htaccess 
```
# Redirect Trailing Slashes If Not A Folder...
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteCond %{REQUEST_URI} (.+)/$
 RewriteRule ^ %1 [L,R=301]
```

To 

```
# Redirect Trailing Slashes If Not A Folder...
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteCond %{REQUEST_URI} (.+)/$
RewriteRule ^ https://%{HTTP_HOST}%%1 [L,R=301]
```

**Comment by jasonvarga** [comment]
When there's a single slash at the end it works fine? (Before your rewrite rule change)

**Comment by sfdrummer** [comment]
Ok, so apparently there aren't two slashes added onto the end.  It sounds like the redirect is happening when the system gets a request for `/admin/assets/browse/folders/assets/?page=1&perPage=30&sort=basename&order=asc&search=`.  Then it gets redirected to http.

**Comment by sfdrummer** [comment]
Looks like the request to `/admin/assets/browse/folders/assets/` was being redirected to `/admin/assets/browse/folders/assets` by Laravel, and coupled with our server setup it was causing the HTTP redirect to happen.

It looks like the JS in Browser.vue (line 442) should be trimming that last slash off but it isn't.

**Comment by Pixney-William** [comment]
Having this issue too now: 
![image](https://user-images.githubusercontent.com/31292231/91465179-c4529280-e88d-11ea-81cd-69a6637242fc.png)

**Comment by FrankPeters** [comment]
I also ran into this issue on Azure. To remove the trailing slash directive in htaccess solved the issue for me.

Did anyone encounter any issues with this workaround? Did it break anything else?

**Comment by ninjaparade** [comment]
If you're using cloudflare for SSL and are not using the FULL SSL option, just update your trusted proxies middleware

```php
protected $proxies = '*';
```

using URL force schema is the wrong fix for this problem.
