### ISSUE TITLE
Shortcut CMD+X remove bard field

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#1301]
Using the shortcut `CMD+X` to edit the content of a bard field it remove the entire field instead.

**Comment by jackmcdade** [comment]
I'm not _entirely_ sure what you mean here. `CMD+X` is the shortcut for "cut", which would copy and delete all the selected content. If you select the contents of the field and press `CMD+X` it does what I expect, and I can even paste it back in. 

See it in action: 
![2020-02-05 15 21 45](https://user-images.githubusercontent.com/44739/73879908-47959380-482b-11ea-8101-3d758ae62b88.gif)

What am I missing?

**Comment by jimblue** [comment]
Hey @jackmcdade,
I've also made a screen capture to help you understand.
![Feb-05-2020 22-17-58](https://user-images.githubusercontent.com/10623367/73884107-77618d00-4865-11ea-98cb-ce33867ba6bf.gif)
Has you can see `CMD+X / CMD+V` does work in the bard field body... like in your screen capture.
But if you do the same in a the body of a bard field set it doesn't. The entire set is going to be `CUT`... at least on my side 😭

**Comment by jackmcdade** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh!

**Comment by jimblue** [comment]
Hurrayyyy !!! 🚀 🚀 🚀
