### ISSUE TITLE
Please bring back Link to Asset in Bard

### ISSUE THREAD

**Issue by manogi** [statamic/cms#1302]
In V2 one could link to an asset by selecting text and than clicking the "link to asset" button. That would be nice in V3 too:

![image](https://user-images.githubusercontent.com/1419634/73834610-4b65ed80-480c-11ea-9eda-94ab8c8f4157.png)

**Comment by jackmcdade** [comment]
You can still do this, but it's a bit different in v3. We have Assets pre-integrated into the "Image" button. You can choose your container(s) and it'll put the image inline where you can set a unique alt tag for this one instance.

If you want to add non-image assets, we recommend using Sets. Just add a set with an Assets field and you'll have much more control than "inlining" a PDF or something. 👍

**Comment by manogi** [comment]
Ah - this is not what I meant. You are able to select some text and link it directly to an asset in V2:



![Feb-06-2020 10-18-35b](https://user-images.githubusercontent.com/1419634/73922930-46677380-48ca-11ea-9399-bed7c35451a8.gif)

**Comment by jasonvarga** [comment]
It still works the same, except that I just now noticed that it doesn't replace your selection, it only inserts the image after.

**Comment by manogi** [comment]
I am sorry, but I don't understand - in V2 the function is to make a `a href` link out of the selected text and put the path to the asset in the `href` attribute. That does not happen anymore, if I am not mistaken. Which would be fine with me, if the Link button 
![image](https://user-images.githubusercontent.com/1419634/73946306-fe5e4600-48f5-11ea-981c-3d771eb4e24a.png)
could be enhanced so that it would be possible to somehow select assets to link to right in the link button.

**Comment by jasonvarga** [comment]
I’m agreeing with you, it should work that way, but isn’t.

**Comment by manogi** [comment]
Ah - sorry I misunderstood. 
One further note on this subject: I personally would prefer the functionality to happen inside the link button, because one might want users to be able to link to assets, but not to insert images inside the editor. Just my two cents.

**Comment by j3ll3yfi5h** [comment]
@manogi is this possible and works or not?

I'm having the same «problem»: How can I link a specific word in a bard field to e.g. a pdf without copying the path from somewhere else?

**Comment by manogi** [comment]
@j3ll3yfi5h no, not working for me yet. Maybe this issue needs to be reopened - or is this functionality not planned anymore, @jackmcdade @jasonvarga ?

**Comment by j3ll3yfi5h** [comment]
@manogi --> #2199

**Comment by manogi** [comment]
@j3ll3yfi5h Thanks!
