### ISSUE TITLE
date_format ignored on cp listings

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#1310]
The date fields are not rendered in the collection table correctly. 
```
    'date_format' => 'd.n.Y',
```
"Beginn" is the default date field from the filename. "Ende" is an added field.
![image](https://user-images.githubusercontent.com/3351449/73935766-969e0000-48e1-11ea-812f-f0543e3e6077.png)

I know, there is a format setting inside the date field. But if I change this, I'm getting an error.
So I don't know, if this field is for backend or frontend.

**Comment by jackmcdade** [comment]
Good point on this one. The _intention_ of the `date_format` setting was just the "publish date", or default system date field. Need to look at how we resolve that with a format setting on the field, and check that error too. Thanks for the heads up!

**Comment by timack** [comment]
Another non-American here having similar problems - I'm not sure if this is related to the above or a separate issue, I've changed the date format in `config/statamic/cp.php` to 'd/m/Y' but datepicker dates are still showing America style:

![image](https://user-images.githubusercontent.com/1098068/85717814-ffc3ca00-b741-11ea-9e61-1fa49f450f69.png)

Also noticed that error when trying to set the date format on the field itself

**Comment by Pfeifakopf** [comment]
@timack Did you change the time_format in  `config/statamic/system.php` too? 
Normally this should work.
![image](https://user-images.githubusercontent.com/3351449/85782230-b9ad3d00-b726-11ea-9667-f346c3aa26ba.png)

**Comment by timack** [comment]
@Pfeifakopf thanks for the tip but it didn't make a difference for me

![image](https://user-images.githubusercontent.com/1098068/85800578-57d7ec00-b795-11ea-8234-ad4a267acc6e.png)

![image](https://user-images.githubusercontent.com/1098068/85800703-8950b780-b795-11ea-8aad-b49d527ebb54.png)

**Comment by ebeauchamps** [comment]
Related to #2053

**Comment by wesort** [comment]
Please keep this issue alive. For true locali**s**ation this is critical. So confusing to UK clients to read dates in US (or even ISO) format.

**Comment by duncanmcclean** [comment]
I've added a PR for the CP listings, #3264.

> Another non-American here having similar problems - I'm not sure if this is related to the above or a separate issue, I've changed the date format in `config/statamic/cp.php` to 'd/m/Y' but datepicker dates are still showing America style:
> 
> ![image](https://user-images.githubusercontent.com/1098068/85717814-ffc3ca00-b741-11ea-9e61-1fa49f450f69.png)
> 
> Also noticed that error when trying to set the date format on the field itself

Regarding the date fieldtype mentioned above, I think the date fieldtype actually has it's own date format setting you can use for that, see screenshot. 

![image](https://user-images.githubusercontent.com/19637309/108245271-fd3a3880-7147-11eb-9366-4fe7634d5595.png)

**Comment by jasonvarga** [comment]
Since this issue is about the format within listings, and Duncan has fixed it in #3264, I've opened another issue for the fieldtype display issue in the form itself here: #3265
