### ISSUE TITLE
Taxonomy field not showing more than 15 items

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1311]
The Taxonomy has been linked to a collection.

The 15 first entries will be loaded and shown. When scrolling down or typing inside the field, there won't be loaded more taxonomies. 

<img width="344" alt="taxonomy_max_15" src="https://user-images.githubusercontent.com/38906163/73947429-b809e680-48f7-11ea-8eca-d9afc193e1dc.png">

**Comment by jonassiewertsen** [comment]
This issue is related to the defaultPerPageSize function.
https://github.com/statamic/cms/blob/master/src/Query/Builder.php#L51-L54

Could it be a temporary fix to increase the number, or would this blow up a lot of other things?

**Comment by syntheticminds** [comment]
I just stumbled across this and spent some time hacking and I think changing the value in the vendor folder is the only way for now.

**Comment by jasonvarga** [comment]
Closing in favor of #1727
