### ISSUE TITLE
Modifier [] not found

### ISSUE THREAD

**Issue by alexharrell** [statamic/cms#1314]
This happens when I try to use a double pipe ||  instead of or in an if statement

`{{ if contacts:dc_email || contacts:dc_phone }}`

Gives the following error: 
Facade\Ignition\Exceptions\ViewExceptionWithSolution
Modifier [] not found
Cannot render an array variable as a string: {{ value }}

`{{ if contacts:dc_email or contacts:dc_phone }}`

works fine.

This is in a partial, pulling from info from a globals file

**Comment by jackmcdade** [comment]
There is no double pipe syntax anymore, you can do `??` or `or` though.

**Comment by jackmcdade** [comment]
I'm sorry I misremembered. Thanks for bug report, we'll take a look! 😅

**Comment by jackmcdade** [comment]
This is fixed on `master`.
