### ISSUE TITLE
Error when switching the Assets "Disk" option in Control Panel

### ISSUE THREAD

**Issue by cnc137** [statamic/cms#1315]
Should the other filesystem disks be commented out in "/config/filesystems.php" file after installing Statamic v3 by default? 

If a user edits the "Assets" area and switches the "Disk" option to "local", "public" or "s3" instead of "assets" in the Control Panel (CP) they will receive an error when they try to go to the "Dashboard". 

Maybe the other disk options should be available to view in the file, but commented out so they don't appear in the CP until enabled and configured.

I am running Statamic 3.0.0 Beta 14 and I tried this with the basic Statamic install and the Cool Writings starter kit and the same thing happens.

**Comment by jasonvarga** [comment]
The disk field is just a simple mapping of configured filesystems. As the filesystem disks can be used elsewhere throughout Statamic, not necessarily in the assets area, we can't just remove them.

As a developer doing admin-ish things like creating/editing asset containers, I think it's probably fine for you to see an appropriate error if you choose a misconfigured disk.
