### ISSUE TITLE
Error when creating Eloquent user

### ISSUE THREAD

**Issue by syntheticminds** [statamic/cms#1316]
Saving superusers is fine but if you try to attach roles, it fails with:

> Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into `role_user` (`user_id`, `role_id`) values (?, editor))

Looking at saveToDatabase() in Statamic\Auth\Eloquent\User, it seems it's trying to save the roles before the user has been saved. That won't work because there isn't a user ID yet.

Would simply reordering them fix it?

**Comment by syntheticminds** [comment]
I've just had time to try this out and yes, reordering does fix the issue.

**Comment by jasonvarga** [comment]
Perhaps, yes, but there may be a reason they were done in that order. We'll check it out.
