### ISSUE TITLE
env tag not working

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/cms#1318]
I've been using the env tag to pull in things like Stripe keys, but this appears to have stopped working in the latest update. The format I'm using is {{ env:VALUE }}. Adding a default **does** generate the default value.

**Comment by theblacksheepltd** [comment]
Follow-up: env variables were also not available in my separate app I'm using for stripe transactions, unless I repeatedly ran "php artisan config:cache". Ended up doing a hard reset from my remote repository to fix (with git clean -ffdx and a composer update). So, not sure if this is related to Statamic or just something else that got corrupted.

**Comment by jasonvarga** [comment]
If you use the `config:cache` command, `env` will not work. (Only in config files)

Actually I would like to remove the `env` template tag.

It's best/better practice to place your `env()` calls within your config file, then reference the config where necessary.

You can reference the `config` from within your templates.
For example, the `route` variable in the `config/statamic/cp.php` file:

```
{{ config:statamic:cp:route }}
```
