### ISSUE TITLE
Navigation structure: Cannot add existing entry using control panel

### ISSUE THREAD

**Issue by tobiaseichert** [statamic/cms#1323]
Steps to reproduce:

- Create a "Navigation" structure
- Select your newly created structure using the control panel's sidebar
- Click "Add link" button, then "Link to entry" in the top right
- Select an appropriate entry you would like to add only to recognize that an "Add" button is nowhere to be found.

Workaround:
- Manually add your entry by directly editing the structure's YAML file.

**Comment by jesseleite** [comment]
Fixed 👍
