### ISSUE TITLE
Preview for extra-wide images not generated properly

### ISSUE THREAD

**Issue by tobiaseichert** [statamic/cms#1325]
Steps to reproduce:

- Go to "Assets"
- Upload an extra-wide image (s. attached example image)
- There's no preview image

![IMG_0401](https://user-images.githubusercontent.com/29119234/74168402-f9690180-4c29-11ea-85eb-2a9e037f47ae.JPG)
<img width="1089" alt="Screenshot 2020-02-10 at 17 23 12" src="https://user-images.githubusercontent.com/29119234/74168478-19002a00-4c2a-11ea-8d70-d35d22ed8915.png">

**Comment by jasonvarga** [comment]
In `config/statamic/assets.php`, there is a `thumbnails.max_width`/`height` setting that you are likely running into.

This prevents memory issues you may run into when generating thumbnails for enormous images.

You can bump this setting up if you like.

**Comment by tobiaseichert** [comment]
Perfect, that did the trick!
