### ISSUE TITLE
Forgot Password Error - Call to a member function table() on null

### ISSUE THREAD

**Issue by cnc137** [statamic/cms#1328]
I am running Statamic v3 Beta 14 in my [Laragon](https://laragon.org/) development environment and when I enter my email address and click "Submit" I get the following error:

```
Symfony\Component\Debug\Exception\FatalThrowableError
Call to a member function table() on null
```
```
Illuminate\Auth\Passwords\DatabaseTokenRepository::getTable :234
D:\laragon\www\cool-writings\vendor\laravel\framework\src\Illuminate\Auth\Passwords\DatabaseTokenRepository.php:234
```
The following is on line 234:
```
protected function getTable() {
   return $this->connection->table($this->table);
}
```
The line 234 is the first item in the "Stack trace" tab that appears below the error message.

I have tried this on two different systems and the same thing happens. 

I only have the one administrator account I created when setting up the site. I can use that user to log into the CP. I thought I would try the forgot password option to see what the email looked like and ran into the above error.

I tried it using the "Cool Writing" starter kit and the default Statamic v3 installation and they both give me the same error.

**Comment by jasonvarga** [comment]
When you say you used the starter kit and default install - have you made any modifications? Like, trying to use database users?

**Comment by cnc137** [comment]
I followed the instructions on https://github.com/statamic/starter-kit-cool-writings and https://statamic.dev/installation and created the first user using the following command:

- php please make:user

They are bare bone installs. I haven't even added any other users, articles, etc. to the installs, since I am still reading through the documentation. They are right out of the box installs. The one install I configured https://mailtrap.io, since I thought maybe not having the email server set up was causing the problem, but that didn't solve it.

I also tried adding another user to the one install and tried the "Forgot password" function for the new user (2nd user account) and I still received the same error.

**Comment by syntheticminds** [comment]
I thought it might have been my config so I quickly tried it on a fresh copy.

```
git clone https://github.com/statamic/statamic.git
cd cms
cp .env.example .env
php artisan key:generate
php artisan statamic:make:user admin@example.com
php artisan serve
```
1. Go to the control panel login.
2. Click 'Forgot password?'
3. Enter admin@example.com
4. See error

**Comment by cnc137** [comment]
I wanted to let you know that I upgraded to Statamic v3 Beta 15 and I am still receiving the error when using the "Forgot Your Password" form.

**Comment by jasonvarga** [comment]
Cheers. This issue wasn't closed so I wouldn't have expected to be fixed. 👌

**Comment by cnc137** [comment]
True. :) I was just letting you know. 

I was hoping it might magically fixed itself. I wasn't complaining or trying to be a pain. 

Thank you for all your hard work. :)

**Comment by edalzell** [comment]
I get a different error now `Password resetter [resets] is not defined`, but it is fixed in this [PR](https://github.com/statamic/cms/pull/2417#issuecomment-693098261)
