### ISSUE TITLE
Groups must have role

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1330]
Trying to create a membership site, where the different tiers give different access to the site. Looks like `Groups` are the "right" way to do this? Or is it roles?

If it's groups, roles seems to be required which won't work (as they don't need roles). If it's roles, is one w/ no permissions going to work?

**Comment by jesseleite** [comment]
A **_role_** defines specific permissions for a user or user group.  Example:
- A `Blog Author` may have permission to do A and B.
- A `Product Author` may have permission to C and D.
- A `Proofreader` may have permission to E.

A **_group_** is just _**a way to apply multiple roles**_ to a large group of users in a more efficient way.  Example:
- I want to apply multiple blog related roles to a large group of users quickly, so I create a `Blog` user group and assign the `Author` and `Proof Reader` roles to that group, then throw users in the group.

Not sure there's a "right" way.  It depends on how how many roles and users you have, and whether you think groups will streamline role assignment for you.

**Comment by edalzell** [comment]
I'm looking for FRONT end groupings. In V2 we used roles, as you can make those, natively, in the CP.

I'll see if permission-less roles work as I don't want to make a custom thing for this, if possible.

**Comment by jesseleite** [comment]
>where the different tiers give different access to the site

Wouldn't you need roles assigned to those groups to give them access to things, as you say?

**Comment by jasonvarga** [comment]
You should be able to have a group without a role.
I know you're working on stuff with database users, so maybe there's just a bug.

If you want to group users for whatever reason, permissions or otherwise, groups would be the way.

**Comment by jasonvarga** [comment]
Nevermind, I see we're just adding required validation to it. We can get rid of that.

**Comment by edalzell** [comment]
> > where the different tiers give different access to the site
> 
> Wouldn't you need roles assigned to those groups to give them access to things, as you say?

Nope, this is front end. Roles are for CP access things

**Comment by jasonvarga** [comment]
Roles don't have to be just for the CP.

**Comment by jasonvarga** [comment]
Removed the requirement for a group to have a role in 0456d9bdb5717b5fe523a4f52317d9c1b3f62b0b
