### ISSUE TITLE
Roles aren't in `resources/users/roles.yaml`

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1331]
...they're in `config/statamic/user_roles.yaml`.

Not sure if this is a docs issue or they're in the wrong spot.

If docs, I can PR to fix.

**Comment by jasonvarga** [comment]
Where do you see that?

**Comment by edalzell** [comment]
https://statamic.dev/users#permissions

**Comment by edalzell** [comment]
Same issue w/ Group, `user_groups.yaml` in config vs resources.

**Comment by jasonvarga** [comment]
Right. Where are you seeing the other one?

**Comment by edalzell** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/6069653/74203870-ea805000-4c25-11ea-933d-1e9d4c79eb22.png">

**Comment by jasonvarga** [comment]
Where’s that?

**Comment by edalzell** [comment]
<img width="228" alt="image" src="https://user-images.githubusercontent.com/6069653/74203920-10a5f000-4c26-11ea-9cde-baf1fd6933d9.png">

**Comment by edalzell** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/6069653/74203930-1996c180-4c26-11ea-9726-bd37f3b48293.png">

**Comment by jasonvarga** [comment]
Looks like an old project

**Comment by edalzell** [comment]
Well it is running latest version of Statamic. But started a while back ya.

**Comment by jasonvarga** [comment]
https://github.com/statamic/statamic/tree/master/resources/users

It was relocated a while ago.

**Comment by edalzell** [comment]
Yes I HAVE those files...but they aren't used. The data is written to the config files.

**Comment by jasonvarga** [comment]
Because you also have the old path here https://github.com/statamic/statamic/blob/master/config/statamic/users.php#L26
