### ISSUE TITLE
Bard: Minimal UI improvements

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#1333]
Back in V2 land, I might have used the markdown field to add *bold* and *italic* to text areas. 

It looks like Bard is a great option for this in V3, if you remove all buttons except **Bold** and _Italic_ and use the _Floating toolbar mode_. 

Blueprint settings:
<img width="915" alt="Screen Shot 2020-02-12 at 2 33 46 pm" src="https://user-images.githubusercontent.com/414211/74300731-d020b080-4da4-11ea-8523-ea23c17d95ff.png">

Publish form:
<img width="904" alt="Screen Shot 2020-02-12 at 2 38 16 pm" src="https://user-images.githubusercontent.com/414211/74300891-56d58d80-4da5-11ea-95b7-30406757812f.png">

The UI is 98% there, but needs some final tweaks until it's 👌 

1) Remove toolbar container when ALL buttons are removed.
2) Set the min-height to be equal to the textarea field

**Comment by jackmcdade** [comment]
Fixed in the `feature/ui-ux-improvements` branch. Thanks for the heads up!
