### ISSUE TITLE
Empty bard field causes ErrorException

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#1335]
After updating to beta.15 an empty bard field gives me:
"Invalid argument supplied for foreach()"

Screenshot of the error: https://nimb.ws/GwRYDm

If I type some text and deletes it again in the field so the bard field is represented in the md-file like ...
```
bard_fieldname:
  -
    type: paragraph
```
... Then everything is fine.

**Comment by jasonvarga** [comment]
Thanks for that. FYI you can use the "share" button on the error screen instead of taking a screenshot.

**Comment by ReneWeCode** [comment]
I know – I'm just afraid to share some sensitive customer data 😉
Let me know if you need more info to fix this.

**Comment by jasonvarga** [comment]
Gotcha, fair enough. 👌
