### ISSUE TITLE
format_localized ignoring locale

### ISSUE THREAD

**Issue by AndersMFJ** [statamic/cms#1336]
I'm using the format_localized modifier on a date field like so: 

`{{ date format_localized="%e %B %Y" }}`

But despite the locale being set to sv_SE I'm getting the names of the months in English. I'm running a multisite setup (sv_SE is default, the second site is en_US) which might have something to do with it, though I'm testing this on the Swedish site.

**Comment by jackmcdade** [comment]
Looks like we need to update the Carbon localization method: https://carbon.nesbot.com/docs/#api-localization

Thanks for the heads up!

**Comment by jonassiewertsen** [comment]
+1

**Comment by jonassiewertsen** [comment]
It seems a bit strange. 

To get the correct translation for carbons `formatLocalized` function, you need to do something like
```
setlocale(LC_TIME, config('app.locale'));
```

`Carbon::locale()` is not working for the formatLocalized function. It does work for `diffForHumans()`, but thats not helping here.

I did work on a PR yesterday, but am not sure where to put `setlocale(LC_TIME, config('app.locale'));` and if it would work correctly with multisites. Maybe there is a better solution at all?
