### ISSUE TITLE
Search Index for Collection must be set in the Collections yaml

### ISSUE THREAD

**Issue by Buffalom** [statamic/cms#1337]
I tried to add a search index for a specific collection and just spent two hours figuring out how to get it to work.

I defined the following search index in the `search.php` config file:
```php
'customers' => [
    'driver' => 'local',
    'searchables' => 'collection:customers,
    'fields' => ['title', 'email', 'phone'],
],
```

Eventually I realised that I also have to set `search_index: customers` in the collections yaml file.
I could not find that in the [documentation](https://statamic.dev/search#indexes).

I expected it to automatically work on the customers collection since I defined it so in the `searchables` property of the search index.

Am I doing something wrong and that's the expected behaviour or is this a bug?
If it is expected, could you maybe elaborate on it in the documentation?

**Comment by jasonvarga** [comment]
This is intentional, and has been [clarified in the docs](https://statamic.dev/search/#connecting-indexes).
