### ISSUE TITLE
Can't log into control panel using database sessions

### ISSUE THREAD

**Issue by syntheticminds** [statamic/cms#1338]
Not high priority for us because we've switched back to file sessions for now but thought you might like to know. To reproduce:

```
git clone https://github.com/statamic/statamic.git
cd statamic
composer install
cp .env.example .env
php artisan key:generate
```
Create a user.
Set database details in _.env_ and set session driver to `database`
```
php artisan session:table
php artisan migrate
```

Now to go the control panel and try and log in. It just refreshes the page; no errors or anything in the logs. Switch _SESSION_DRIVER_ to _file_, refresh the page for a new CSRF token and bingo - it works.

**Comment by damcclean** [comment]
Sorry for the long wait. I found a fix for this a couple of weeks back, you can read the whole thread over here: #2608.

I'm going to close this issue now as the fix over there should get it working for you. If not, please comment on here and I can re-open this issue.
