### ISSUE TITLE
Ability to disable "updated_by" on save

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#1339]
I like this being on by default, but would also like to disable it when i know for sure I don't want it.

**Comment by jackmcdade** [comment]
Config name suggestion: **Track Last Update**

```php
    /*
    |--------------------------------------------------------------------------
    | Track Last Update
    |--------------------------------------------------------------------------
    |
    | Automatically sets "updated_by" user id and "updated_at" timestamp
    | when content is updated.
    |
    */

    'track_last_update' => true,
```

**Comment by zedix** [comment]
Would be a nice option. 

I just noticed that `lastModifiedBy` produces a lot of queries on every page.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/27975/86476380-b6c5d400-bd46-11ea-916f-afc57950d3f8.png">

<img width="878" alt="image" src="https://user-images.githubusercontent.com/27975/86476417-c8a77700-bd46-11ea-8e96-941615ea74f9.png">
