### ISSUE TITLE
Attempting to edit an asset results in error

### ISSUE THREAD

**Issue by techdaddies-kevin** [statamic/cms#1340]
Set-Up: Install V3
Create a blueprint and add an 'Asset' field to it
Assign that blueprint to a collection
Go to the create form for that collection
Select an image asset for your field
Hover over the thumbnail and click the edit icon

The modal never loads and the laravel log gets the following entry:

`[2020-02-12 18:18:04] local.ERROR: Call to a member function handle() on null {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function handle() on null at /home/vagrant/Projects/site/vendor/statamic/cms/src/Providers/RouteServiceProvider.php:113)`

**Comment by mkriegeskorte** [comment]
I can confirm this behavior. Already tried to rollback the assigned blueprint, but that doesn't resolve the issue. I am using current v3.0.0-beta.15.

**Comment by syntheticminds** [comment]
Same here. We're using the old release again. Use this in composer.json

`"statamic/cms": "dev-master#e47b23d"`

**Comment by ReneWeCode** [comment]
Just confirming
