### ISSUE TITLE
Asset mime validation not functioning

### ISSUE THREAD

**Issue by techdaddies-kevin** [statamic/cms#1341]
**Version:** v3.0.0-beta.15

I have created an 'Asset' field and for the validation, have tried *EACH* of the following separately to ensure the selected asset is an image:

1. Selected the `Image (File)` validation rule
1. Selected the `mimes:jpg,png,jpeg` validation rule

In both situations, the field fails validation when an image is selected and the save button is pressed.

**Comment by jesseleite** [comment]
See Jason's comment here for more info: https://github.com/statamic/cms/issues/1956#issuecomment-646866146
