### ISSUE TITLE
Variable inside noparse tag won't get rendered

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1344]
Never knew about this tag until today so I could be expecting something else. But when I try and put the `noparse` tag around a variable, nothing is returned, it's just empty.

This is how I'm using it in my code block partial.

```
<pre><code class="hljs {{ language }}">{{ noparse }}{{ code }}{{ /noparse }}</code></pre>
```

I also tried using `noparse` as a modifier but that returned the same thing, absolutely zilch.

```
<pre><code class="hljs {{ language }}">{{ code | noparse }}</code></pre>
```

As I said, never used this tag in v2 but I don't think it should be returning nothing😂

**Comment by jackmcdade** [comment]
Yeah that's gonna be a bug.

![bug](https://i.gifer.com/OHow.gif)

**Comment by damcclean** [comment]
This seems to have been resolved.

In the first example, obviously `{{ code }}` would not have been parsed because that's the job of the `noparse` tag.

And the second example seems to be working fine on my site, which is on the latest beta build.

**Comment by jackmcdade** [comment]
🎉
