### ISSUE TITLE
Password required when creating DB user

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1346]
If you set up Users to use the DB, then try to create a user, don't assign group or roles and don't send the email, you get an exception:
```
SQLSTATE[HY000]: General error: 1364 Field 'password' doesn't have a default value (SQL: insert into `users` (`email`, `name`, `avatar`, `updated_at`, `created_at`) values (test@test.com, Test Test, ?, 2020-02-13 05:42:53, 2020-02-13 05:42:53))
```

It's because the `password` column in the DB is required and we don't set on in the wizard.

**Comment by jasonvarga** [comment]
The migration we provide changes the column to nullable.
14375a47006fec2c655defaff28ec16bf64d461f
