### ISSUE TITLE
Can't edit Eloquent User

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1347]
In the CP, when you try to edit an Eloquent user: https://flareapp.io/share/J7oa6Gm8

**Comment by techdaddies-kevin** [comment]
I can confirm this behavior in Beta 15

**Comment by damcclean** [comment]
I wonder if this is still an issue after 1461d39 as it fixes how the user is found for the user edit screen.

**Comment by davidsneal** [comment]
This fixes it for me, have opened a PR https://github.com/statamic/cms/pull/1574

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
