### ISSUE TITLE
Non-super users can create super users

### ISSUE THREAD

**Issue by syntheticminds** [statamic/cms#1348]
My client will need to add new users to Statamic. To do this, I've granted their role the _Create users_ permission. However, with this permission they can create super users. This means granting _Create users_ is like granting super user privilege since you could make yourself a new super user account and go to town on the CMS.

Is this something Statamic will address or do I need to make an extension for it?

**Comment by jackmcdade** [comment]
Good catch! The server side validation would have prevented `super` from actually being applied, but the form _was_ showing the toggle. It's fixed on `master`.
