### ISSUE TITLE
Taxonomy entries will still be shown after they have been deleted

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1349]
After deleting a Taxonomy Entry, the entry itself is not disappearing. 

After deleting the stache, everything is fine. 

STATAMIC VERSION: Beta 15

![out](https://user-images.githubusercontent.com/38906163/74432736-58fc2280-4e5f-11ea-8317-a02735d76bb3.gif)

**Comment by jackmcdade** [comment]
I can't recreate this issue. :think: Have you changed any of the cache settings in `config/statamic`?

**Comment by jasonvarga** [comment]
I believe this happens when you still have entries using that term.

Deleting the term only deletes the file. If you still have it in the entry it will just get magically recreated (without a term file).

**Comment by jonassiewertsen** [comment]
@jackmcdade The cache settings are the default settings. 
@jasonvarga I did only create a test taxonomy entry for the demo above. No entries are using the term.

**Comment by syntheticminds** [comment]
I've found some weirdness with this.

Create a term called FBI. It saves but it's now fbi in the listing.
Clear Stache and refresh the taxonomy term listing. It's now FBI.
Delete it and it's gone.

Create a term called FBI. It saves and shows as FBI in the listing.
Delete it and the YAML file is gone but it shows fbi in the listing.
Clear Stache and it's gone.

**Comment by marcomezzavilla** [comment]
The same problem happens to me when I change the slug of a term. Then it is no longer possible to delete it via UI.

Even if I try to erase the whole taxonomy, recreating a new one with the same name, I see the "old term" waiting for me (:
