### ISSUE TITLE
Z-index of search bar contextual items

### ISSUE THREAD

**Issue by alexharrell** [statamic/cms#1354]
If I have am editing an entry with several tabs displayed and the active tab is located under the search bar, when I try to search, the tab shows up over the contextual results. I've added a screenshot as I'm sure that description was not very clear.
<img width="439" alt="Screen Shot 2020-02-13 at 9 51 06 AM" src="https://user-images.githubusercontent.com/11863220/74463627-f1d27400-4e46-11ea-9930-327bc1c8cf60.png">

**Comment by jackmcdade** [comment]
Good one! Fixed on `master`.
