### ISSUE TITLE
The entries var inside a taxonomy term should be a query builder

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1356]
If its an EntryQueryBuilder, then we can do nice stuff like adding sort="" etc params.

It's already been converted to a collection by the time you want to use it in Antlers.

**Comment by jesseleite** [comment]
Context...

![Screen Shot on 2020-02-13 at 15-04-54](https://user-images.githubusercontent.com/5187394/74475024-a3d46500-4e74-11ea-8eff-af9336151a6c.png)
