### ISSUE TITLE
Suggestion - Only Enable Required Variables in .env.example by Default

### ISSUE THREAD

**Issue by cnc137** [statamic/cms#1358]
I believe the ".env.example" file has environment variables included and enabled in it that are not required to get Statamic up and running. For example, the "DB_CONNECTION" variable is set to "mysql" by default, but the "DB" variables won't even be used by most people if they use the standard flat file system.

Should the top of the ".env.example" file have instructions like the following?

```
# Remove the "#" at the beginning of the lines required for your advanced Statamic installation. 
```

Then the "DB" section and others that are not needed by default would have "#" at the beginning of each line as follows:

```
# === Database Connection Settings ===
# DB_CONNECTION=mysql
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=homestead
# DB_USERNAME=homestead
# DB_PASSWORD=secret
``` 

From a beginner's perspective that would make the ".env.example" file less intimidating and allow them to know what environment variables are optional and which ones are required to get Statamic working.

**Comment by jasonvarga** [comment]
The env file comes from Laravel. We try to stick as close as possible.

You’re free to create a fork of statamic/statamic with any modifications you like, and you can use that as a starting point for your sites.
