### ISSUE TITLE
[content API] Exception error on /api/collections/{collection}/entries

### ISSUE THREAD

**Issue by igregson** [statamic/cms#1361]
First off, super excited to see the content API live! Thank you :)

I'm seeing an exception error on GET requests to `/api/collections/{collection}/entries`. Here's the error report: https://flareapp.io/share/OmVBDnm8#F48

Another API issue I'm seeing is that bard field values are always returned as HTML, even when the field's "Save HTML" setting in the blueprint is set to `false`. Since the above error is coming from TipTap, maybe these two issues are related (?). I can create a separate issue for this if that would be helpful.

**Comment by jackmcdade** [comment]
@igregson A separate issue for the bard item would be super helpful, thanks!

**Comment by igregson** [comment]
> @igregson A separate issue for the bard item would be super helpful, thanks!

Created #1417.

**Comment by igregson** [comment]
It looks like this is fixed (!), I think via https://github.com/statamic/cms/releases/tag/v3.0.0-beta.20. 

I've just updated from a pre `vbeta-20` to `vbeta-22` and GET requests to `/api/collections/{collection}/entries` now work as expected.
