### ISSUE TITLE
Column Heading still shows for hidden fieldtype in Grid

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1368]
When you have a hidden fieldtype inside a Grid fieldtype, the heading still shows and it messes the table up.

![image](https://user-images.githubusercontent.com/19637309/74588309-22efa780-4ff3-11ea-8d0b-b371424ba2cd.png)

**Comment by jackmcdade** [comment]
Went with a `v-show` on the `th` itself so the whole column would collapse. Thanks for the push, @damcclean!
