### ISSUE TITLE
New 'Pin to Favorites' UI: Not enough space for translations

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1370]
With the new option 'Make start page' there is not enough space for a good translation (to german). It would be helpful to have some more space for both tabs available.

<img width="375" alt="Bildschirmfoto 2020-02-15 um 17 29 53" src="https://user-images.githubusercontent.com/8265902/74591595-6ceb8400-5019-11ea-8e0a-68e8b6661fb7.png">

**Comment by ebeauchamps** [comment]
Same in French

**Comment by jackmcdade** [comment]
###
