### ISSUE TITLE
Blueprints stored in directories can't be updated

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1371]
If a blueprint is placed in a subdirectory like `resources/blueprints/something/myblueprint.yaml` then it will be unable to be edited from the Control Panel.

My guess is because the URL `http://commerce.test/cp/fields/blueprints/simple-commerce.product/edit` has a dot in it instead of a `/`.

Here's a [flare link](https://flareapp.io/share/17DKZ6Pv).

(In my case the subdirectory is `simple-commerce` and the blueprint is called `product`.)

**Comment by damcclean** [comment]
I've done a little bit of debugging. You just need to replace `.` with `/` in the blueprint variable in the `BlueprintController`'s `edit` function. Like this: (I've added the `str_replace` line)

```php
public function edit($blueprint)
    {
        $blueprint = str_replace('.', '/', $blueprint);

        $blueprint = Facades\Blueprint::find($blueprint);

        return view('statamic::blueprints.edit', [
            'blueprint' => $blueprint,
            'blueprintVueObject' => $this->toVueObject($blueprint)
        ]);
    }
```

I'm not sure if this is the cleanest way to go about it, there might be a helper that could be used to clean this up.

**Comment by jackmcdade** [comment]
We don't support blueprints in subdirectories at the moment, but we can certainly add support in the future. It's a bit low priority at the moment though!

**Comment by damcclean** [comment]
I'm closing this now, not sure it's a big deal anymore.
