### ISSUE TITLE
Markdown fieldtyp in fullscreen mode: No options for closing is visible

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1374]
When expand a markdown fieldtyp to fullscreen mode, there is no closing button available. The `esc`-key work though, but that's not obvious at first. Maybe this could be done more understandable?

**Comment by jackmcdade** [comment]
Yeah whoops! The new fixed-top global nav bar overlaps the markdown bar. Fix coming in the next update :)

**Comment by jackmcdade** [comment]
Fixed in 9d8b2486fd467444df4d2adc46fb9aa7f5126f7e
