### ISSUE TITLE
Profile > Change Password: password is revealed all the time

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1375]
The checkbox 'reveal password' does not have an impact: the password is revealed all the time

<img width="592" alt="Bildschirmfoto 2020-02-16 um 01 25 42" src="https://user-images.githubusercontent.com/8265902/74597211-7eee1680-505b-11ea-863b-647b74753783.png">

**Comment by jackmcdade** [comment]
Fixed in 3fd0d3073172cf19aee57a922eb36b139098b392
