### ISSUE TITLE
X-Statamic-Draft header being set on all requests blocking static caching

### ISSUE THREAD

**Issue by brighttank** [statamic/cms#1376]
I'm trying to get full static caching working but the X-Statamic-Draft header is being set regardless of the published status preventing the page from being cached later on.

Seems like the handleDraft function should check $this->data->published() before setting the header.

    protected function handleDraft()
    {
        if (! method_exists($this->data, 'published')) {
            return $this;
        }

        if (!$this->isLivePreview() && !$this->data->published()) {
            throw new NotFoundHttpException;
        }

        $this->headers['X-Statamic-Draft'] = true;

        return $this;
    }

**Comment by jasonvarga** [comment]
Wow. 🤦‍♂
