### ISSUE TITLE
Global header masking editor controls in full screen mode

### ISSUE THREAD

**Issue by tobiaseichert** [statamic/cms#1378]
How to reproduce:

Enable full screen mode when editing text using markdown editor or Bard. Editor controls took precedence in 3.0.14, in 3.0.16 the global header takes precedence (s. screenshots) due to a higher z-index.

<img width="1664" alt="editor-3 0 14" src="https://user-images.githubusercontent.com/29119234/74604545-526be600-50bf-11ea-9941-93e5850231e8.png">
<img width="1677" alt="editor-3 0 16" src="https://user-images.githubusercontent.com/29119234/74604548-54ce4000-50bf-11ea-9658-0c39b94640f8.png">

**Comment by jackmcdade** [comment]
Fixed in 9e4349dbe0a6e3939334b42ce30e6f715e9f7a5d.
