### ISSUE TITLE
Bard's dirty state is wrong

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#1386]
Hitting the edit url of any entry with a Bard field will trigger the "Changes you made may not be saved." dialog.

**Comment by jesseleite** [comment]
I remember this happening, but can't reproduce anymore.  Can re-open if it creeps in again.

**Comment by j3ll3yfi5h** [comment]
I do have this problem on a client site. But I can't reproduce what exactly the problem is, because it happens not on every page...

**Comment by j3ll3yfi5h** [comment]
I'm also getting this on non bard blueprints...strange
![Bildschirmfoto 2021-04-08 um 16 50 55](https://user-images.githubusercontent.com/6337411/114048500-ed5aed00-988a-11eb-8fe0-ab88381393fb.png)

**Comment by duncanmcclean** [comment]
> I'm also getting this on non bard blueprints...strange
> ![Bildschirmfoto 2021-04-08 um 16 50 55](https://user-images.githubusercontent.com/6337411/114048500-ed5aed00-988a-11eb-8fe0-ab88381393fb.png)

If you're still hitting this issue, I'd suggest opening a fresh issue, with information on how to reproduce. Thanks!

**Comment by j3ll3yfi5h** [comment]
@duncanmcclean I can't reproduce, nothing strange in the logs, nothing in the console – is there a way to turn on a secret debug mode with more informations?

**Comment by duncanmcclean** [comment]
> @duncanmcclean I can't reproduce, nothing strange in the logs, nothing in the console – is there a way to turn on a secret debug mode with more informations?

I don't think there's anything like that, unfortunately.

**Comment by j3ll3yfi5h** [comment]
#3500
