### ISSUE TITLE
Parser doesn't handle a date range var with param-style modifiers 

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#1387]
This doesn't work: `{{ dates:start format="M j, Y" }}`
This works: `{{ dates:start | format:M j, Y }}`

I haven't done a code dive yet but I expect the parser is seeing the `:` and thinks it's a tag/callback instead of a variable.

**Comment by AndreasSchantl** [comment]
Just on note here: I think ``{{ dates.start format="M j, Y" }}`` would also be nice as it would somehow reflect an object usage in JS

**Comment by jackmcdade** [comment]
@AndreasSchantl That would significantly increase the complexity of our parser. Alas, it's not feasible to support that right now. Maybe ever.

**Comment by AndreasSchantl** [comment]
No big deal. Was just a little input I wanted to give as I saw this issue. I am fine with ``:`` as well.

**Comment by jackmcdade** [comment]
This is working now.
