### ISSUE TITLE
Add docblocks to facades

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1390]
For example: https://github.com/laravel/framework/blob/6.x/src/Illuminate/Support/Facades/Cache.php#L5-L25

**Comment by jonassiewertsen** [comment]
I did create a PR and hope it's exactly as needed. Let me know if changes are required.

https://github.com/statamic/cms/pull/1761

**Comment by edalzell** [comment]
Can I push to your PR or do I have to make my own @jonassiewertsen?

**Comment by jonassiewertsen** [comment]
Feel free to push to mine!

**Comment by Konafets** [comment]
This issue can be closed as the PR from @jonassiewertsen was merged.
