### ISSUE TITLE
Live Preview Background is distracting

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#1391]
The grey background of the live preview is creating distraction on sites that haven't specified a white background-color by default. 

![image](https://user-images.githubusercontent.com/9936988/74700967-88b37d80-5205-11ea-8051-7ddc48744e39.png)
All of this should be white instead of grey. I would like to not have to workaround this.

**Comment by mikemartin** [comment]
This gets me every time too.

**Comment by jonassiewertsen** [comment]
Same here.
