### ISSUE TITLE
Call to a member function id() on null viewing collection

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/cms#1396]
Upgraded a v2 site to v3 using the migrator and running into this issue in the CP.

Here's the full error https://flareapp.io/share/Vmer9GPQ#F105

Don't think it has anything to do with the content in the collection as I tried hosing it all but the error persists.

**Comment by jasonvarga** [comment]
Can you send us a zip of your content?

**Comment by 1stevengrant** [comment]
spotted a duped entry from ages ago. Removed that and it looks to be good now 🤷🏻‍♂️

can close this off.
