### ISSUE TITLE
Custom Auth Guard for CP

### ISSUE THREAD

**Issue by fragkp** [statamic/cms#1397]
Hey!

**Problem:**
In one of our projects we tried to test Statamic v3, but encountered some errors.
It's currently not possible to have a custom guard explicit set for the CP.

**How to reproduce:**
`config/auth.php`
```
    'guards' => [
        ...
        'backend' => [ // this guard should be used for the CP
            'driver' => 'session',
            'provider' => 'statamic',
        ],
    ],
...
    'providers' => [
       ...
        'statamic' => [
            'driver' => 'statamic',
        ],
    ],
```

I tracked down many places in which just `auth()` or `Auth::guard()` is used without setting a guard name.

**My proposal:**
Add a config option to define the custom guard which should be used.

If you want, I could make a PR for this.

**Comment by jasonvarga** [comment]
What’s your reason for wanting to do this?

**Comment by fragkp** [comment]
My default Auth Guard (web) is already used by my website customers and handled complete differently (external API).

I could switch the name of my Auth Guard and all places where I used it but, a CMS should not force me to do that.

**Comment by jasonvarga** [comment]
And you don't want to use that same guard to log into the CP?

**Comment by fragkp** [comment]
Yes correct. They are completely different kind of "users" and should'nt authenticate into anything related to Statamic (CP).

**Comment by jasonvarga** [comment]
Alright, and you plan to just use the yaml based users for Statamic.

Cool. We'll need to make the guard configurable, and use it explicitly in the code like you suggested. Thanks for the info.

**Comment by fragkp** [comment]
Exactly!

I would make a PR for this :smiley:
