### ISSUE TITLE
Install command doesn't use stache configured directories

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1400]
If you change the directories in [config/statamic/stache.php](https://github.com/statamic/cms/blob/master/config/stache.php#L31-L69), it still uses the hardcoded directories in [the command](https://github.com/statamic/cms/blob/master/src/Console/Commands/Install.php#L48-L55).

**Comment by edalzell** [comment]
#goodfirstissue

**Comment by damcclean** [comment]
It's not my first issue by any means but I've made a pull request to implement this, in #2888.
