### ISSUE TITLE
Date field uses 'date' as the default handle

### ISSUE THREAD

**Issue by dougstjohn** [statamic/cms#1402]
This creates an issue where the Date field doesn't save data.

Steps:
- Create a Blueprint and create a Date field
- Add the Blueprint to a collection
- Create an entry and set the Date value

Result:
- The date isn't stored
- If you change the handle, the date is stored correctly

Expected:
- User shouldn't be able to save invalid handles from the UI

I haven't tested all fieldtypes but this may be an issue with others.

**Comment by jesseleite** [comment]
This is fine.  Solved by adding unique field validation to blueprint builder instead. See https://github.com/statamic/cms/commit/e6e2b0f3eddeaa632daed100f435cdc8f2dc3c2d
