### ISSUE TITLE
Asset upload layout width 25% width

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1403]
Right now it does look like this with a 25% width:

<img width="903" alt="asset_upload" src="https://user-images.githubusercontent.com/38906163/74776310-9dd8ec80-5297-11ea-9ce4-1f9fdbfa89eb.png">

Something like this would be great :-)
<img width="903" alt="asset_upload_optimized" src="https://user-images.githubusercontent.com/38906163/74776376-bb0dbb00-5297-11ea-8a45-e77c9de7daeb.png">

**Comment by jackmcdade** [comment]
Honestly the 25% width size is just pretty unfeasible to be really usable. Even if I can fix that (which will require eqcss which i don't love having on all the time just for edge cases), the rest of the field will be pretty janky as well. Your best bet is to use a wider field container. 😊 

Wish I had better news for ya!

**Comment by jonassiewertsen** [comment]
It is a really handy and good looking size when images have been selected. 

<img width="931" alt="Screen Shot 2020-02-19 at 08 43 22" src="https://user-images.githubusercontent.com/38906163/74812537-fa69f500-52f3-11ea-8a4c-1d7c7a4b4cf5.png">

I do use it often when organizing a selection of images. An excellent way for the root page to create an image overview with only a few pictures and to make sure the user selects precisely X images.

There are other ways, but this seems to be the most intuitive set up to use for my clients. 

I do something like this on 75% of my page.

Fair enough though, if considered an edge case!
