### ISSUE TITLE
Can't escape full-screen Bard

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1404]
I've hit a teany tiny issue with Bard. I entered full screen mode and I can't escape.

![image](https://user-images.githubusercontent.com/19637309/74777740-08872980-5292-11ea-84a7-b28b2bb1db0e.png)

**Comment by jasonvarga** [comment]
Just like vim!

Are you on beta 17?

**Comment by damcclean** [comment]
> Just like vim!
> 
> Are you on beta 17?

Good shout! I'm not, I'll upgrade now.

**Comment by damcclean** [comment]
That's better.
