### ISSUE TITLE
Driver in config/statamic/assets.php → Should it be imagick instead of imagemagick?

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1407]
I followed the instructions on line 38 in `config/statamic/assets.php` and changed the driver. But there were no thumbnails showing up in the assets browser when using imagemagick.

But it works when using `'driver' => 'imagick',` instead.

Am I missing something out or should it be `imagick` instead of `imagemagick` in the comments on line 38?

**Comment by jasonvarga** [comment]
It has already been updated. See https://github.com/statamic/statamic/blob/master/config/statamic/assets.php#L38

imagick it is. 👌
