### ISSUE TITLE
Wrong error about email in user update

### ISSUE THREAD

**Issue by peimann** [statamic/cms#1408]
Try to edit user profile in dashboard, edit only name and click save, you will get an error that user's email has already been taken.
<img width="969" alt="stus" src="https://user-images.githubusercontent.com/40042952/74816418-5d698500-5310-11ea-9a29-6240fd6269a1.png">

Notice: I have configured to save users in database.

**Comment by peimann** [comment]
I've tested with file driver. It is ok if user is saved on file.

**Comment by jasonvarga** [comment]
Fixed by #1574
