### ISSUE TITLE
Error when add a new user through the CP and have a second asset container

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1411]
I was experimenting with a second asset container:
- Added those lines in `config/filesystems.php`
- and created the new folder `/public/assets2`

```
'assets' => [
    'driver' => 'local',
    'root' => public_path('assets'),
    'url' => '/assets',
    'visibility' => 'public',
 ],
```

When I try to add a new user I receive the following error now. 
It works again when I delete the second asset container.

This might be because of the Avatar asset field in the default user.yaml blueprint?

<img width="846" alt="Bildschirmfoto 2020-02-19 um 15 40 22" src="https://user-images.githubusercontent.com/8265902/74847554-987cb000-5332-11ea-80b5-8b21e869ff95.png">

**Comment by jasonvarga** [comment]
Indeed. You'll need to add a `container` to the `avatar` field in your own `user` blueprint.

We don't add a container by default so it works nicely for most people (many only ever have one container).
