### ISSUE TITLE
Encapsulate CP from User's App

### ISSUE THREAD

**Issue by fragkp** [statamic/cms#1418]
Hey again!

**Problem:**
I'm noticed that are many "services" aren't encapsulated from the User's App.

First example: ExceptionHandler
When the default ExceptionHandler is changed to e.g. convert the json error responses into some kind of different format than, the CP can't handle this.

Second example: Middlewares
By default, the CP uses the 'web' middleware group. When adding custom middlewares you have to check every time if it's a CP Request.

I think there are more places that could create unexpected behaviors like these examples.

**My proposal:**
All required "services" like ExceptionHandle, middlewares and so on should be registered by the CPServiceProvider and also "namespaced".

This should be a major discussion since it requires a lot of changes.

**Comment by jasonvarga** [comment]
Hi! All good points, thanks!

Regarding Middleware, I just took a look through Nova because I thought they'd have the same pain points. It looks like they also use the `web` middleware. What issues are you running into where you have to check if it's a CP request?

**Comment by fragkp** [comment]
Interesting that Nova behaves the same.

In our use case, we created a middleware which sets the id (based on a customer number on the user model) for Sentry.

Example middleware:
```php
if (auth()->check() && app()->bound('sentry')) {
    configureScope(function (Scope $scope) {
        $scope->setUser([
            'id' => auth()->user()->customerNo,
        ]);
    });
}

return $next($request);
```
This would break if we use the CP since the `customerNo` not exist.
Related to https://github.com/statamic/cms/issues/1397

**Comment by jasonvarga** [comment]
You don't want Sentry error handling on Statamic?

**Comment by fragkp** [comment]
That's not the point.

The user returned by `auth()->user()` is not the same as the user used by the CP (see related Issue).

Another example for a middleware would be:
```php
$requestLocale = $request->isXmlHttpRequest()
    ? $request->header('App-Language')
    : $request->segment(1);

$locale = in_array($requestLocale, config('app.locales'), true)
    ? $requestLocale
    : config('app.fallback_locale');

app()->setLocale($locale);

return $next($request);
```

This middleware should exclusively run on our frontend and not inside CP.

I could also imagine that some users disabled the `VerifyCsrfToken` middleware, since they simply don't need them. This would also break the CP.

**Comment by jasonvarga** [comment]
Cool, thanks.
