### ISSUE TITLE
Collection variable does not work

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1420]
When trying to use the `collection` variable when looping through a collection to get information about the collection the entry is attached to, I get the error `Undefined offset: 0`.

This is my template where I'm trying to get the collection

```html
{{ collection from='docs|help_articles' }}
        <div class="border-b mb-4 py-2">
            <h2 class="font-bold text-gray-800 text-2xl"><a href="{{ url }}">{{ title }}</a></h2>
            <p>{{ content }}</p>

            <div class="mt-2 flex flex-row items-center">
                <a class="mr-4 font-semibold text-gray-800 text-sm" href="#">
                    <i class="fas fa-archive mr-2"></i>
                    {{ collection }}
                </a>
            </div>
        </div>
    {{ /collection }}
```

**Comment by jasonvarga** [comment]
Thanks! Looks like maybe we'll need to make the collection object augmentable then you'll be able to do stuff like {{ collection:title }}.

We'll need to be careful to make sure it doesn't break in the cases where you'd want to be using the actual tag but there's a collection variable so it conflicts.

**Comment by damcclean** [comment]
Hmm, this issue doesn't just effect the collection stuff but also users.

For example, you can do this:

```
{{ user }}{{ id }}{{ /user }} 
```

But you can't do:

```
{{ user:id }}
```

That last one would be the one I'd prefer to use if I needed to get the id of the current user. So it seems that any variables that have a tag of the same name are effected.

**Comment by jonassiewertsen** [comment]
Having a similar problem with code, which did work in Beta 13. 
The blueprint is visible when dumping the data, but not rendered on the view.

<img width="556" alt="Screen Shot 2020-03-17 at 14 12 27" src="https://user-images.githubusercontent.com/38906163/76859364-799e0a80-6859-11ea-9a1c-7bf1ac5af4f7.png">

The dumped output

<img width="893" alt="Screen Shot 2020-03-17 at 14 10 56" src="https://user-images.githubusercontent.com/38906163/76859390-89b5ea00-6859-11ea-975b-83c81553fac1.png">

This code will output the title, but the blueprint does stay empty. (Maybe this information does help to debug?)

<img width="485" alt="Screen Shot 2020-03-17 at 14 12 12" src="https://user-images.githubusercontent.com/38906163/76859423-976b6f80-6859-11ea-87ba-9e23e30c49dc.png">
