### ISSUE TITLE
Antlers bug?

### ISSUE THREAD

**Issue by bradlc** [statamic/cms#1422]
Hey. Bit of a weird one, sorry for the generic issue title.

Ran into an issue with Antlers, I think. In the Statamic application below, the form fields do not render, but if you edit **line 74 of resources/views/home.antlers.html** to have **exactly one `a`** it works. That's just one example of an edit that makes it work. It is seemingly random!

https://github.com/bradlc/statamic-v3-form-bug

This is a fresh install, with the only additions/changes being `resources/views/home.antlers.html`, `resources/forms/contact.yaml` and `resources/blueprints/contact_form.yaml`

**Comment by jackmcdade** [comment]
![Confused](https://media2.giphy.com/media/iAYupOdWXQy5a4nVGk/giphy.gif)

**Comment by jasonvarga** [comment]
That's something we run into fairly often. In the next release instead of it failing silently and not rendering something, you will get an error suggesting you split your template into partials.

However, that view is smaller than I would have thought would trigger this problem. 🤔

**Comment by bradlc** [comment]
Ah interesting, it's not just me then!

> That's something we run into fairly often. In the next release instead of it failing silently and not rendering something, you will get an error suggesting you split your template into partials.

It's funny you say that because in my specific case the fix was to inline one of my partials 😅
