### ISSUE TITLE
Invalidation rules are not invalidating other pages on save

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#1427]
Hi, I'm using the full static page cache options with some invalidation rules based on the examples in the docs. But when saving an entry in the collection 'articles', the cache of the homepage, articles and acticles/categories isn't cleared. Is there a mistake in my code or is this a bug?

```
'invalidation' => [
    'class' => null,

    'rules' => [
        'collections' => [
            'articles' => [
                'urls' => [
                    '/articles',
                    '/articles/categories/*',
                    '/',
                ]
            ],
        ],
        'taxonomies' => [
            'categories' => [
                'urls' => [
                    '/articles',
                    '/articles/categories/*',
                    '/',
                ]
            ]
        ]
    ]
]

```

Cheers,
Joeri

**Comment by tubsn** [comment]
Hi, on my installation even the 'all' Rule does not invalidate the cache. Maybe it´s completely broken right now? 3.0.0 Beta 23

**Comment by MattRogowski** [comment]
Can confirm still an issue on beta 28

**Comment by ianlord** [comment]
Can also confirm this, either with "half" or "full" static caching strategies, both when using `'rules' => 'all'` or trying to invalidate other pages (besides the one currently being saved) using by-collection rules (beta 28)

**Comment by jesseleite** [comment]
What `QUEUE_DRIVER` do you all have set in your env files?

The invalidation logic runs a queue job, so if your queue driver is set to anything other than `sync`, you may need further queue listener/worker configuration.  Or if it's set to the `null` driver, I think it discards the job altogether.

**Comment by Krzemo** [comment]
Its standard out of the box config in my case:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/1293123/86186165-ab9d5900-bb38-11ea-80bd-d60f48224c15.png">
<img width="254" alt="image" src="https://user-images.githubusercontent.com/1293123/86186177-b22bd080-bb38-11ea-838c-5b977e74c7e0.png">

**Comment by AndreasSchantl** [comment]
I do have the same problem. Nothing happens. Not that of a big deal though for smaller sites that don't get updated that often, but even more severe for others. Hope this will be fixed soon.
