### ISSUE TITLE
Wrong instruction text for 'Allow Uploads' and 'Blueprints' should be singular (Assets)

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1430]
- Wrong text and missing key for 'Allow Uploads' instruction text in `messages.php`
- Title 'Blueprints' should be singular, because only one blueprint can be selected

<img width="959" alt="Bildschirmfoto 2020-02-23 um 02 53 48" src="https://user-images.githubusercontent.com/8265902/75102309-d8b98800-55e9-11ea-8dbe-7e8222c9dbfb.png">

**Comment by jackmcdade** [comment]
Fixed in 6ef7c97aa1c61740bc102009266dfef42282adba. Thanks @helloDanuk!
