### ISSUE TITLE
Glides crop_focal not working in config presets

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1431]
Working as expected

```html
<img src="{{ glide:image width='200' height='200' fit='crop_focal' }}">
```

Inside config/statamic/assets.php

With `crop` the cropping is as expected, but of course ignoring focal points.
```php
'presets' => [
            // Ratio ca. 0,35
            'title_card_phone' => ['w' => 375, 'h' => 202, 'q' => 95, 'fit' => 'crop'],
             ...
```

**With `crop_focal`, the image won't be cropped at all.**
The given sizes will be ignored. 
```php
'presets' => [
            // Ratio ca. 0,35
            'title_card_phone' => ['w' => 375, 'h' => 202, 'q' => 95, 'fit' => 'crop_focal'],
             ...
```

For reference my template
```html
{{ image }}
   <img src="{{ glide src='{ url }' preset='title_card_phone' }}">
{{ /image }}
```

**Comment by jasonvarga** [comment]
Use the same template as your first snippet. glide:image, instead of passing the url as a param. 

If you need the image tag pair, then do glide:id

If you tell glide to use an asset, focal cropping should work. If you just give a url I think it might not associate with the actual asset.

**Comment by jonassiewertsen** [comment]
What I did try without success

```
{{ image }}
<picture>       
    <!-- more sources -->
    <source media="(min-width: 769px)" srcset="{{ glide:id preset='my_preset' }} 1x, ...
    <img class="w-full" alt="{{ alt }}" src="{{ glide:id preset='my_preset' }}">
</picture>
{{ /image }}
```

**Comment by jasonvarga** [comment]
I have a feeling this might be resolved. If that's not the case, please say so and we'll happily reopen the issue.

**Comment by jesseleite** [comment]
I believe this is still an issue, but only seems to happen when explicitly setting `'fit' => 'crop_focal'` in a preset.
