### ISSUE TITLE
Stacked fieldsets with a max and min of one should not render a grab handle

### ISSUE THREAD

**Issue by benfurfie** [statamic/cms#1432]
In WordPress' Advanced Custom Fields plugin, there is a fieldtype called Group. This is an incredibly useful fieldtype that allows users to 'group' together common fields to improve the UX of content entry.

![Screenshot_2020-02-23 Edit Solution ‹ IMImobile — WordPress](https://user-images.githubusercontent.com/10786699/75117050-1a881400-5666-11ea-9a06-d7b8fbc574a8.png)

The closest default fieldtype in Statamic is Grid. Stacked grids by default display with their index number and a cross to delete the set.

The problem, from a UX perspective, is that when stacked grids are configured to have a max and a min of 1 (i.e. they are required and cannot be deleted by a user), they still display the grab handle.

Visually, there's nothing wrong with the grab handle itself. However, the contents of the grab handle are a problem.

1. The index number means absolutely nothing to non-developers and shouldn't be displayed by default.
2. Even to developers, it's redundant when the min and max values are set to one, so that is always only ever going to be 0.
3. There shouldn't be a dismiss x in the top right hand corner when it's set to min one, irrespective of the max number.

It makes much more sense to remove the grab handle as a whole when the conditions are that:

if min_rows == 1 && max_rows == 1

Then don't render the grab handle.

**With redundant grab handle**
![Screenshot_2020-02-23 Home ‹ Pages ‹ Structures ‹ Statamic](https://user-images.githubusercontent.com/10786699/75117051-207df500-5666-11ea-805b-a1094774ea4f.png)

**Without redundant grab handle**
![Screenshot_2020-02-23 Home ‹ Pages ‹ Structures ‹ Statamic(1)](https://user-images.githubusercontent.com/10786699/75117055-2542a900-5666-11ea-8d45-b7cfe3902c37.png)

**Comment by benfurfie** [comment]
Sorry, hit enter by accident. 👏

**Comment by jasonvarga** [comment]
Why use a grid? Just use 3 fields and set their widths?

**Comment by benfurfie** [comment]
The main goal is to have clearly defined groups that are related to their front end component counterparts. I.e. at a high level, you might have the following grouped fields.

Banner
Block
Block
Block
Call To Action

At a more atomic level, you might have commonly used components like buttons grouped too.

As you can see from the ACF example, some of the components can end up running over multiple lines, and often use fields like the select to control conditional display of various settings.

**Comment by jasonvarga** [comment]
The box around the fields is what you like, right?

**Comment by benfurfie** [comment]
Effectively, use. It's mainly to aid the content editors and other marketing staff on our team who aren't super tech savvy with understanding which fields is related to which content.

**Comment by helloDanuk** [comment]
This reminds me of a [similar problem](https://github.com/statamic/ideas/issues/96) I stumbled upon every now and then in V2.
