### ISSUE TITLE
Avatar variable not working

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1434]
I've got a user field setup for one of my collections. I want to get the user's avatar but it returns nothing, whereas if I ask for the user's name, that gets returned perfectly fine.

If it helps I'm using Gravatar for profile pictures.

This is what my template looks like where I'm trying to use the avatar. `author` is the name of the user field.

```
<div class="flex flex-row items-center font-semibold text-xl">
                    <img class="h-12 rounded-full mr-2" src="{{ author:avatar }}" alt="{{ author:name }}'s Profile Picture">
                    {{ author:name }}
                </div>
```

**Comment by damcclean** [comment]
For the time being it is possible to get the user's gravatar using `{{ email | gravatar }}` instead.

I did a dump inside my `{{ user }}` tag, and the `avatar` field is there...
![image](https://user-images.githubusercontent.com/19637309/81308891-3c484300-907a-11ea-8dc2-7bff728be20c.png)

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.

**Comment by caseydwyer** [comment]
This is still an issue for me, in v3.0.0-beta.37 - using default `avatar` field, with file uploaded to S3.
