### ISSUE TITLE
Form Submission Templates don't work

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1439]
Alright, I've found some more issues regarding form submission emails.

My first issue is the Control Panel validation bug I mentioned in my previous issue #1438.

Another issue I've found is that you can have two different types of template for form submission emails and a different configuration from how it is done in v2 (and how it is in the v3 docs)

I did some source diving and found that instead of using `template` in the `email` array of your form config, you have to use `text` or `html`.

`text` would just output an email with plain text and `html` would render a view.

However, the way these are called don't work because the `html` and `text` items are never actually in `$this->config` in Line 62 and 63 of [`Email.php`](https://github.com/statamic/cms/blob/master/src/Forms/Email.php#L60).

Just to fake this, I hardcoded in `email/form-submission` (my Blade template - antlers templates don't work) and the email was sent with my template.

This is the template I was using

```html
<h1>New Form Submission</h1>
<table>
	<tbody>
		<tr>
			<th>Full Name</th>
			<td>{{ $full_name }}</td>
		</tr>

		<tr>
			<th>Phone Number</th>
			<td>{{ $phone_number }}</td>
		</tr>

		<tr>
			<th>Email Address</th>
			<td>{{ $email_address }}</td>
		</tr>
	</tbody>
</table>
```

I tried to use the `message` from my form's blueprint but it returned an instance of a Swift message which I don't know where that would be parsed.

I think that there needs to be some sort of way of parsing Antlers views as email templates and way of obviously displaying textarea fields within email templates.

**Comment by jesseleite** [comment]
Both blade and antlers seem to work fine on master now.  Let us know if you're still experiencing issues, and we can re-open!
