### ISSUE TITLE
Form submissions widget missing

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1442]
In v2, there was a widget available that displayed recent form submissions. However, it looks like it's not been ported over to v3.

I can have a go working on a pull request for adding it if it's something you'd like ported.

**Comment by jackmcdade** [comment]
Looks in there to me: https://github.com/statamic/cms/blob/master/src/Forms/Widget.php

🤔

**Comment by damcclean** [comment]
I looked for a solid fee minutes the other day. Once again I must be blind or be stuck in the past 😂
