### ISSUE TITLE
Responding with Entry using EntryResource throws "strtolower() expects parameter 1 to be string, object given"

### ISSUE THREAD

**Issue by Buffalom** [statamic/cms#1443]
Hi there,

I have an Entry which is inside a Structure.
In a custom api route I get the Entry and respond with it using the EntryResource.
(using the ContentAPI-route results in the same error)

```php
public function show($path = '')
{
    $entry = Entry::findByUri($path)->entry();
    abort_if(!$entry->published(), 404);
    return EntryResource::make($entry);
}
```

**Expected behaviour:**
The route responds with a json response constructed by the EntryResource.

**Actual behavious:**
An error **"strtolower() expects parameter 1 to be string, object given"** gets thrown.

**Workaround:**
I added a CustomEntryResource in between which looks as follows:

```php
class CustomEntryResource extends EntryResource
{
    public function toArray($request)
    {
        $response = parent::toArray($request);

        array_forget($response, 'parent');

        return $response;
    }
}
````

If I use this resource it works thanks to the `array_forget($response, 'parent')`.

**Additional info:** (may be useless because I'm not sure I understand the full issue)
The `toArray()` method on the Resource still works fine. The error only occurs when I `json_encode()` the return value of the `toArray()` method.
For some reason it tries to augment the `parent` including its `tree` which eventually causes the error.

**Comment by jasonvarga** [comment]
Please share your exception. (There's a share button on the page)

**Comment by Buffalom** [comment]
Here's the error: https://flareapp.io/share/qm1pR25d

As I mentioned, it's not only when I use a custom route.
Using the content api route results in the exact same error.

**Comment by jasonvarga** [comment]
Is this still an issue for you?

**Comment by Buffalom** [comment]
I don't think so. I only tried it briefly just now but couldn't reproduce it with a more recent version anymore.
