### ISSUE TITLE
Table fieldtype input problem (when within Replicator)

### ISSUE THREAD

**Issue by marflow** [statamic/cms#1447]
The fieldtype seems to be buggy in beta.17: I can only enter (or delete) one character at a time, the focus jumps out of the cell. If I click into the field again, I can enter another character.
The table is inside a replicator, if that´s important. Browser is latest Safari.

**Comment by jackmcdade** [comment]
Confirmed. The issue seems to be caused by the deep data watcher reactivity:

```
watch: {
        data: {
            deep: true,
            handler (data) {
                this.update(this.sortableToArray(data));
            }
        },
        ...
}
```

**Comment by ReneWeCode** [comment]
Table fieldtypes inside replicators are totally unusable 😔
