### ISSUE TITLE
Asset fieldtype "Browse" not loading

### ISSUE THREAD

**Issue by marflow** [statamic/cms#1448]
This is in beta.17, Asset fieldtype inside Replicator:
I can upload images into the field or browse to select images and save fine.
But if there is an image already saved in the field, the "Browse" button does not work any longer, just keeps spinning. (Upload is working with images already present in the field.)

**Comment by jackmcdade** [comment]
Can you check what the error message is in your console?

**Comment by marflow** [comment]
Will do, but MBP in repair today. Chances are it‘s fine now since there’s were other issues with JS / Vue in beta 17 that we’re fixed in beta 18 already.

**Comment by marflow** [comment]
The problem is gone in beta.19. "Browse" button is working without problem.
