### ISSUE TITLE
CP action can't use invokable controller AND namespace resolution

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1453]
(sorry if the title is wrong, no clue what to call this).

Statamic beta 18.

Use an invokable controller in a route like so does **not** work:
```php
use Illuminate\Support\Facades\Route;
use Silentz\Anvil\Http\Controllers\SiteController;
use Silentz\Anvil\Http\Controllers\ServerController;
use Silentz\Anvil\Http\Controllers\Actions\DeploySiteController;

Route::name('anvil.')->prefix('anvil')->group(function () {
    Route::get('/', [ServerController::class, 'index'])->name('index');
    Route::get('{server}/sites', [SiteController::class, 'index'])->name('sites');

    Route::name('site.')->prefix('{server}/site/{site_id}')->group(function () {
        Route::post('deploy', DeploySiteController::class)->name('deploy');
    });
});
```

It throws this error (couldn't share error for some reason, sorry): 
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/6069653/75613485-15eab200-5ae3-11ea-86e7-82013aabf5d1.png">

However this **does** work:
```php
        Route::post('deploy', '\Silentz\Anvil\Http\Controllers\Actions\DeploySiteController')->name('deploy');
```

My `DeploySiteController` is very thin:
```php
<?php

namespace Silentz\Anvil\Http\Controllers\Actions;

use Silentz\Anvil\Http\Controllers\BaseController;

class DeploySiteController extends BaseController
{
    public function __invoke(string $server, string $site)
    {
        // $site = $this->forge->site($server, $site);

        // $site->deploySite();

        return redirect(route('statamic.cp.anvil.sites', ['server'=> $server]));
    }
}
```

Directory structure, in case it's relevant: 
<img width="225" alt="image" src="https://user-images.githubusercontent.com/6069653/75613505-58ac8a00-5ae3-11ea-86b8-0e0e1b2312fd.png">

**Comment by edalzell** [comment]
Just saw this: https://statamic.dev/extending/addons#writing-routes. This is likely what's happening.

But why do the other routes I have in there work and only this one does not?

**Comment by edalzell** [comment]
My other ones work, I think, because they are the `[]` format and **not** a string.

IMO that namespace prepending should be taken out as it is unexpected (even though it's documented) "magic"

**Comment by edalzell** [comment]
@jackmcdade @jasonvarga would you be open to a PR to remove this feature (the magic namespacing) and update the docs?

**Comment by jasonvarga** [comment]
I don't want to force people to use the `::class` syntax. The namespacing is useful if they just want to do the `"MyController@show"` syntax which is super common.

You can disable the namespace in your `Route::name('anvil.')` group with `->namespace(null)` (or maybe `"\"` - haven't actually tried)

**Comment by edalzell** [comment]
Removing doesn't "force" anything though. Removing it means you gotta do it like you do in Laravel, and you have options:
1. A fully qualified string (either hard-coded or using the `::class`
2. Using the `[]` way.

Why hide something that doesn't need hiding? It doesn't really add any convenience; adding your own add-on's namespace is how you do it in Laravel Package development...and that's what an addon is.

**Comment by edalzell** [comment]
Leaving it in makes it less Laravelly, coupled with unexpected behaviour, IMO.

**Comment by jasonvarga** [comment]
The "Laravel" way assumes your controllers are in App\Http\Controllers.

If you do Route::get('MyController@show') it's gonna assume you meant Route::get('\App\Http\Controllers\MyController@show')`

Here, you're in the context of your package. So why not assume the package's namespace?

**Comment by edalzell** [comment]
For a site route sure , but not a package route. Those you always have to put your own fully qualified name. The code for this is in AddonServiceProvider so packagers. 

And those workaround look super janky to me. Addon devs should build like a package dev.

**Comment by jasonvarga** [comment]
If you want to "build like a package dev", you're free to load your routes manually rather than using the `$routes` property in your service provider.

Using a string in your routes doesn't make you less of a package developer.

Where does the Laravel docs even suggest to use the `::class` syntax?

**Comment by edalzell** [comment]
It’s a way nicer syntax, see all Spatie packages and works better with IDEs and better handles refactoring. 

Clearly we disagree on this, close as you see fit and I’ll modify my addons as needed.

**Comment by jasonvarga** [comment]
Which Spatie packages use it?

**Comment by edalzell** [comment]
https://freek.dev/1210-a-better-way-to-register-routes-in-laravel.

I can find it in their packages too, one moment.

**Comment by edalzell** [comment]
Turns out finding routes in their packages is hard, here's one, with the tuple notation: https://github.com/spatie/laravel-web-tinker/blob/master/src/WebTinkerServiceProvider.php#L49. Trying to find one with a Single Action Controller...maybe Mailcoach?

**Comment by edalzell** [comment]
Yup: https://github.com/spatie/laravel-web-tinker/blob/master/src/WebTinkerServiceProvider.php#L49

**Comment by edalzell** [comment]
FYI, here's what the code looks like w/ existing functionality. Not ideal, but not terrible, for a single action controller:
```php
Route::post('deploy', [DeploySiteController::class, '__invoke'])->name('deploy');
```

**Comment by jasonvarga** [comment]
Freek's article is a opinionated recommendation. He mentions you have to manually change the namespace prefixing anyway:

![image](https://user-images.githubusercontent.com/105211/75616549-56b4ec00-5b20-11ea-9388-75e5c6549d7b.png)

While I do honestly prefer that way in a lot of cases, it's not the "Laravel way".

The tuple syntax works fine already as you noted. Laravel doesn't prefix a namespace there because it's an array, not a string. What you posted: `Route::post('deploy', [DeploySiteController::class, '__invoke'])->name('deploy');` is a workaround for that exact issue.

If you want to do it Freek's way, you'll have to manually null out the namespace. Just pop it on your route group. Or use tuples with __invoke.
