### ISSUE TITLE
Tags fieldtype overflow

### ISSUE THREAD

**Issue by bradlc** [statamic/cms#1454]
Version: **3.0.0-beta.18**

![image](https://user-images.githubusercontent.com/2615508/75613671-4bfe5500-5b28-11ea-90d1-5cf67f642902.png)

As well as the overflow there is a blank button (outlined in red) that doesn’t seem to do anything

**Comment by jackmcdade** [comment]
Yeah I'm waiting on some updates to https://github.com/sagalbot/vue-select so I can run this list _outside_ the input and avoid overflow issues. Hang tight!

**Comment by jackmcdade** [comment]
Closed via 9a9bfd43
