### ISSUE TITLE
Custom fieldtype icons do not display on blueprint edit view

### ISSUE THREAD

**Issue by bradlc** [statamic/cms#1455]
Version: **3.0.0-beta.18**

When defining an icon for a custom fieldtype, this icon is not displayed on the blueprint edit view (`cp/fields/blueprints/{handle}/edit`):

![image](https://user-images.githubusercontent.com/2615508/75625896-4c473080-5bba-11ea-88c5-5e46afc4fe63.png)

The icon displays fine when creating a new field:

![image](https://user-images.githubusercontent.com/2615508/75625809-78ae7d00-5bb9-11ea-86a8-922bd7fac073.png)

Example class:

```php
class Example extends \Statamic\Fields\Fieldtype
{
    protected $icon = 'radio';
}
```

**Comment by peterkelm** [comment]
Still exists in Statamic 3.0.5.

Just add a field to a blueprint: Although the field is added, its icon is missing.
Pressing "Save" and reopening the edit dialogue for the blueprint and the icon's there...
