### ISSUE TITLE
User and contains modifier

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1457]
I'm building a likes system. A user can like an entry, which sends an ajax request to a custom controller that actually does the like. 

The likes button and counter are inside a Vue component I built. This is how I'm using it in my template:

```html
<likes
    key="like-{{ id }}"
    initial-count="{{ likes | count }}"
    initial-liked="{{ user }}{{ if (likes | contains:id) }}true{{ else }}false{{ /if }}{{ /user }}"
    logged-in="{{ logged_in }}"
    entry="{{ id }}"
    csrf-token="{{ csrf_token }}"
></likes>
```

Everything in there works, apart from the `initial-liked` prop. In there I'm trying to get a `true` or `false` value to whether or not the logged in user's id is in the `likes` array. However, every time, it's returning `false` even if the user's id does defiantly exist in the entry yaml file.

The `likes` array is a users field in the entry blueprint.

**Comment by jasonvarga** [comment]
If you want a boolean, you need to add the colon.

`:initial-count=""`

**Comment by damcclean** [comment]
> If you want a boolean, you need to add the colon.
> 
> `:initial-liked=""`

Sorry, I don't understand what you mean.

**Comment by damcclean** [comment]
> If you want a boolean, you need to add the colon.
> 
> `:initial-liked=""`

OK, thanks. That converts it to a boolean properly but still having the issue where Statamic is reporting it as `false` even though the user's id is definatly in the yaml file.

This is what I've got right now:

```
:initial-liked="{{ user }}{{ if (likes | contains:id) }}true{{ else }}false{{ /if }}{{ /user }}"
```

**Comment by jasonvarga** [comment]
Gotcha, I misunderstood your issue.

What's `likes`? A variable on the user?

**Comment by damcclean** [comment]
Yeah, it's a users field. This is what it looks like in the yaml file:

```yaml
likes:
  - ba3bbc64-9eb8-4639-a849-1317728bd503
```

**Comment by damcclean** [comment]
Found a workaround. I converted the `likes` array to json, then used the `contains` modifier to search through the json string.

The code looks like this:

```html
:initial-liked="{{ user }}{{ if (likes | to_json | contains:id) }}true{{ else }}false{{ /if }}{{ /user }}"
```
