### ISSUE TITLE
Parser could use some optimizing

### ISSUE THREAD

**Issue by twd3** [statamic/cms#1461]
I really thought my partials were ok size wise but after updating to V3 beta18 I kept getting the "strtolower() expects parameter 1 to be string, object given" error. I eventually figured out it was a bard set template partial that I guess was to big.

**Comment by mikemartin** [comment]
I ran into the same issue on Beta18. Refactoring my partial from 70 lines to 37 fixed the issue.

OG partial:
```
<section class="relative py-16 lg:py-32">
  {{ if careers_background }}
    <img src="{{ careers_background }}" class="absolute inset-0 z-0 hidden object-contain object-right-bottom w-full h-96 lg:block {{ if raise }}md:-mt-20{{/if}}"/>
  {{/if}}

  <div class="container">
    <div class="flex flex-wrap items-center -mx-6 {{ if left }}md:flex-row-reverse{{/if}}">
      <div class="px-6 md:w-1/2">
        <div class="md:max-w-lg reveal-seq {{ if left }}ml-auto{{ /if }}">
          {{ if careers_tagline }}
            <h2 class="mb-6 font-medium tracking-widest text-blue-500 uppercase">{{ tagline }}</h2>
            <h3 class="max-w-sm text-3xl font-bold leading-tight text-gray-800 lg:text-5xl em-indigo">
              {{ careers_headline|markdown|striptags:p|widont }}
            </h3>
          {{ else }}
            <h2 class="max-w-sm text-3xl font-bold leading-tight text-gray-800 lg:text-5xl em-indigo">
              {{ careers_headline|markdown|striptags:p|widont }}
            </h2>
          {{ /if }}

          <div class="mt-6 lg:text-xl content">{{ careers_content }}</div>
          </div>
      </div>
      <div class="z-10 px-6 mt-6 md:w-1/2 md:mt-0">
        <figure class="reveal-seq">
          {{ careers_image }}
            <picture>
              <source media="(min-width: 768px)"
              srcset="{{ glide:url w='800' q='90' fm='pjpg' }} 1x, {{ glide:url w='1600' q='90' fm='pjpg' }} 2x">
              <source media="(min-width: 640px)"
              srcset="{{ glide:url w='640' q='90' fm='pjpg' }} 1x, {{ glide:url w='1280' q='90' fm='pjpg' }} 2x">
              <source
              srcset="{{ glide:url w='375' q='90' fm='pjpg' }} 1x, {{ glide:url w='750' q='90' fm='pjpg' }} 2x">
              <img src="{{ glide:url q='90' fm='pjpg' w='750' }}" class="block rounded-lg shadow-2xl {{ if last }}mt-20 w-3/4 {{ if left }}ml-auto -mr-6{{else}}-mr-6{{/if}}{{/if}}" alt="{{ alt }}">
            </picture>
          {{ /careers_image }}
          <figcaption class="mt-6 italic">{{ careers_caption }}</figcaption>
        </figure>
      </div>
    </div>

    <div class="flex flex-wrap mt-32 -mx-6">
      <div class="px-6 md:w-1/2">
        <div class="md:max-w-lg">
          <h2 class="text-3xl font-bold leading-none text-gray-800 lg:text-4xl em-indigo">
            {{ join_headline }}
          </h2>

          <div class="mt-6 lg:text-xl content">{{ join_content|widont }}</div>

          {{ join_button }}
            {{ partial:actions }}
          {{ /join_button }}
        </div>
      </div>

      <div class="px-6 mt-6 md:w-1/2 md:mt-0">
        <h3 class="text-xl font-bold leading-none text-gray-900 lg:text-2xl">{{ benefits_headline }}</h3>
        <ul class="mt-8 lg:text-xl max-width-sm">
          {{ benefits }}
            <li class="flex mt-4 align-start">
              {{ svg src="check" class="flex-shrink-0 w-5 h-5 mt-1 mr-3 lg:mr-4 lg:w-8 lg:h-8"}}
              {{ value }}
            </li>
          {{ /benefits }}
        </ul>
      </div>
    </div>
  </div>
</section>
```

Workaround:
```
<section class="relative py-16 lg:py-32">
  {{ if careers_background }}
    <img src="{{ careers_background }}" class="absolute inset-0 z-0 hidden object-contain object-right-bottom w-full h-96 lg:block {{ if raise }}md:-mt-20{{/if}}"/>
  {{/if}}

  <div class="container">
    <div class="flex flex-wrap items-center -mx-6 {{ if left }}md:flex-row-reverse{{/if}}">
      <div class="px-6 md:w-1/2">
        <div class="md:max-w-lg reveal-seq {{ if left }}ml-auto{{ /if }}">
          {{ partial:elements/header 
            :heading="careers_headline"
            :summary="careers_content" 
            large="true"
          }}  
        </div>
      </div>
      <div class="z-10 px-6 mt-6 md:w-1/2 md:mt-0">
        <figure class="reveal-seq">
          {{ careers_image }}
            <picture>
              <source media="(min-width: 768px)"
              srcset="{{ glide:url w='800' q='90' fm='pjpg' }} 1x, {{ glide:url w='1600' q='90' fm='pjpg' }} 2x">
              <source media="(min-width: 640px)"
              srcset="{{ glide:url w='640' q='90' fm='pjpg' }} 1x, {{ glide:url w='1280' q='90' fm='pjpg' }} 2x">
              <source
              srcset="{{ glide:url w='375' q='90' fm='pjpg' }} 1x, {{ glide:url w='750' q='90' fm='pjpg' }} 2x">
              <img src="{{ glide:url q='90' fm='pjpg' w='750' }}" class="block rounded-lg shadow-2xl {{ if last }}mt-20 w-3/4 {{ if left }}ml-auto -mr-6{{else}}-mr-6{{/if}}{{/if}}" alt="{{ alt }}">
            </picture>
          {{ /careers_image }}
          <figcaption class="mt-6 italic">{{ careers_caption }}</figcaption>
        </figure>
      </div>
    </div>

    {{ partial:components/careers_benefits}}
  </div>
</section>
```

**Comment by twd3** [comment]
Just as a side note, after I updated to .18 this morning I also got the new error that said my default layout was too big but that layout was really small as well. I made tiny then the new error pointed me to my header partial so I went and simplified that. So this new "too big" error is working I just don't know why it failed on these partials. The partial the new error worked on was in the root of /resources/views/partials. The partial that got the strtolower error was in /resources/views/partials/sets. Maybe that is a clue?

**Comment by damcclean** [comment]
I came across the same issue yesterday (the one that says my layout was too big) but I didn't think it was that big, only 110~ lines. 

After I moved stuff into a partial it started working again.

**Comment by jasonvarga** [comment]
It's interesting to me that the threshold for template size seems to be lower now.

Only two real changes were made to the parser for beta 18.
- Regex error handling (so you get the "its too big" error)
- Letting the limit be configurable.

I removed where we manually set the limit to `1000000` and instead only set it if you explicitly set it in your config. I did this because I read that the default was `1000000` anyway.

Perhaps that's not the default for everyone?

Anyone who is noticing views need to be smaller... can you tell me your default values?

You can open `public/index.php` and drop in `die(ini_get('pcre.backtrack_limit'));` right after the `<?php`

**Comment by twd3** [comment]
Mine says 1000000.

**Comment by marflow** [comment]
Mine too.

**Comment by alexharrell** [comment]
Same here, I had a footers partial that was 77 lines - too big. so i had to make it into several smaller partials. :/

**Comment by jasonvarga** [comment]
We did some testing and wanted to know:

If you roll back to beta 17, were those "too big" views **actually** working? Was _everything_ being rendered correctly?

We noticed that the same template that gives you the error in beta 18, was only _partially_ rendering in beta 17. So at first glace, you wouldn't see an error, and some of it looked ok, but there were bits missing.

Regardless, you bump up the point where it breaks by adding `'pcre_backtrack_limit' => 1000000,` to your `config/statamic/system.php`.

10 million is the default. Maybe 20 million will work for you.
Setting it to `-1` will mean no limit, but may mean you run into memory issues at some point. (But you might not, and it might be perfectly fine.) We're considering just making that the default.

**Comment by marflow** [comment]
Just rolled back, now templates gives me same strtolower() error as with beta 18. CP says beta 17. Maybe some other package needs to be rolled back as well? (Template was working with beta 17).

**Comment by jasonvarga** [comment]
Comment out [these lines](https://github.com/statamic/cms/blob/master/src/Entries/Collection.php#L215-L220) from `vendor/statamic/cms/src/Entries/Collection.php` temporarily to see the _actual_ error that's happening.

**Comment by marflow** [comment]
Sorry Jason, my fault. I commented those lines out and Statamic said it could not find a partial. That was because I renamed folders between yesterday and today. So I renamed the partials folder to the old version, undid the commenting out and now beta 17 is showing the complete template again without error. Nothing in the template is cut off.

**Comment by twd3** [comment]
I rolled back and yes all partials I had to edit yesterday were working. So we went from 10 million to one million as the default? Just making sure. I'm leaving alone I like small partials. At least now I know what to enter in to 'pcre_backtrack_limit' because someone yesterday told me to put 10,000 and it of course did not work. People can go up by one million to troubleshoot/fix. Like:
'pcre_backtrack_limit' => 2000000, Nope didn't work ok:
'pcre_backtrack_limit' => 3000000, Awesome worked, so on.

**Comment by jasonvarga** [comment]
When you asked me in Discord yesterday I said 10 million and corrected myself. It was always 1 million.

**Comment by twd3** [comment]
Oh u say 10m above though. Does what I say make sense? Go up by 1m?

**Comment by jasonvarga** [comment]
Hah, yes I made the same mistake again. 1 million. It's 1 million. try 2 million. I'll edit my comment.
