### ISSUE TITLE
publishing section in sidebar is too small for translations

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1463]
for german translation the size isn't optimal

![Bildschirmfoto 2020-03-03 um 10 36 53](https://user-images.githubusercontent.com/54707973/75763264-45e0c200-5d3c-11ea-888b-f1f12c0bd692.png)

**Comment by helloDanuk** [comment]
I work on an overhauled german translation (PR #1655). Instead of *'URL besuchen'* I use *'URL öffnen'* *(Open URL)* so that the text does not become too wide.

**Comment by edalzell** [comment]
Duplicate of https://github.com/statamic/cms/issues/2081, for which there is a PR: https://github.com/statamic/cms/pull/2423
