### ISSUE TITLE
UI: Select options appear outside field

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#1464]
<img width="325" alt="Screen Shot 2020-03-03 at 9 26 04 pm" src="https://user-images.githubusercontent.com/414211/75767104-59b91200-5d96-11ea-8592-288340e6ff1b.png">

**Comment by jackmcdade** [comment]
Yeah I'm waiting on some updates to https://github.com/sagalbot/vue-select so I can run this list outside the input and avoid overflow issues. Hang tight!

**Comment by jackmcdade** [comment]
Closed via 9a9bfd43
