### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1467]
Laravel 7 has been released!

I've had a go at adding support for Laravel 7 in Statamic but I kept getting strange composer messages that I can't be bothered dealing with . So, sorry about that or I would be pull requesting instead of creating an issue.

**Comment by edalzell** [comment]
This is the issue I've run into so far: https://github.com/mrclay/minify/issues/664. Working on a PR but stuck because that package's dependencies are quite old.

**Comment by damcclean** [comment]
Theres a free Laravel Shift that can do it - see the tweet https://twitter.com/laravelshift/status/1236710858299973635?s=19

**Comment by edalzell** [comment]
It's a dependency problem that I don't believe can be resolved by Shift as the actual dependency needs to be changed (via PR).

**Comment by edalzell** [comment]
Here's the PR to watch: https://github.com/mrclay/minify/pull/666

**Comment by edalzell** [comment]
Made a draft PR: https://github.com/statamic/cms/pull/1521
