### ISSUE TITLE
Strange alert message when creating asset container

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#1469]
When i am creating an asset container, an alert box appears saying "Changes you made may not be saved.".  At first, i felt something was wrong, and i clicked leave. But the container was created.

This UI probably need to change a little. I would expect to just see a saved toast message instead. 

![image](https://user-images.githubusercontent.com/31292231/75871816-717fad00-5e0d-11ea-9f05-fe415960bc2e.png)

![image](https://user-images.githubusercontent.com/31292231/75871866-7e040580-5e0d-11ea-8de4-f5df42889aac.png)

**Comment by jackmcdade** [comment]
That message means you have unsaved changes. You may have already saved _some_, but there was at least one change that wasn't saved. I really really want to make a better alert, but it's very difficult.

**Comment by jasonvarga** [comment]
Looks like we aren't releasing the dirty state when saving there.
