### ISSUE TITLE
Taxonomy: entries_count and min_count="1"

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1481]
1. To get the number of entries that use this taxonomy term:
"There are {{ count }} 'news' entries" isn't the right way
"There are {{ entries_count }} 'news' entries." is good

2. min_count="1" doesn't appear to be working. It should restrict the display of taxonomies to the ones with at least one entry in the collection. I cannot make this work. I tried min_entries_count. No dice.

**Comment by jasonvarga** [comment]
Fixed by b550fa925989ac0bdb1217c84778b2eabaa521f6
