### ISSUE TITLE
When using eloquent for users, Debug mode causes memory issues.

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/cms#1484]
All users have roles and groups.

v3.0.0-beta.19

**Comment by sheldonkotyk** [comment]
OK, I switched back to file. Debug mode doesn't kill my site now.

Not sure if relevant but with eloquent it took 4.5 seconds to send the page from the stache without debug. Without eloquent 3.5 seconds without debug.

**Comment by jasonvarga** [comment]
Can you provide some more details? This whole issue description seems really vague to me sorry.

**Comment by jackmcdade** [comment]
Hey there, we haven't heard back on this for a while so I'm going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!
