### ISSUE TITLE
Serializing an AugmentedEntry gives empty object as collection

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#1487]
Some time ago, serializing `$entry->toAugmentedArray()` had the collection handle in the resulting JSON object under the key `collection` because of the old `augmentedArrayData()` in Entry.php.

Now, serializing `$entry->toAugmentedArray()` still has the `collection` key in the resulting JSON object (because `collection` is one of the keys in AugmentedArray.php), but its value is `{}`, an empty object. It seems the Collection class is not serializable?

**Comment by sauerbraten** [comment]
Might be somehow related to #1420, not sure.

**Comment by jasonvarga** [comment]
Thanks for pointing this out.

**Comment by jasonvarga** [comment]
In the next release, collection will still be an object (not a string) but it will have stuff in it.

```
{
  "title": "Entry title",
  "collection": {
    "title": "Articles",
    "handle": "articles"
  }
}
```

**Comment by sauerbraten** [comment]
I don't see the `handle` field. Instead, there's `title`, `id` (that has the handle), and `api_url` (null for us).
