### ISSUE TITLE
Bard toolbar shows for set

### ISSUE THREAD

**Issue by HellPat** [statamic/cms#1488]
I'm not sure if this is a feature I'm not understanding.
Bard shows the floating Toolbar when I click inside a `set` included.

<img width="883" alt="Bildschirmfoto 2020-03-09 um 22 41 09" src="https://user-images.githubusercontent.com/1016798/76260026-33441c80-6257-11ea-961c-61fb072e8d9b.png">

**Comment by jackmcdade** [comment]
I tried my best but couldn't figure out how to fix this. Tag! /cc @jasonvarga
