### ISSUE TITLE
Multisite toggle not changing content in inputs

### ISSUE THREAD

**Issue by manogi** [statamic/cms#1492]
I am on Statamic v3.0.0-beta.19
Trying on latest Chrome, Firefox and Safari.

When I have a field (tried text and textarea) which is localizable and I have different contents for each site, the content of the field does not change when I toggle the other site. Only after a refresh does it change. Please see the example gif (the short flashes are when I refresh the browser).

![Mar-11-2020 13-58-18](https://user-images.githubusercontent.com/1419634/76419693-13207480-63a1-11ea-816f-d57514f7e611.gif)

**Comment by jasonvarga** [comment]
Thanks!
