### ISSUE TITLE
Audio preview from S3 Asset container doesn't load

### ISSUE THREAD

**Issue by tao** [statamic/cms#1506]
When loading a preview for a podcast episode stored on an S3 container in the collection edit page, the Audio preview seems to try load the file from the local filesystem instead of using the S3 container path.

The file is trying to load from `/podcasts/episodes/083.mp3` but I believe it should be loading from: 
`https://{{ config:filesystems:disks:s3:bucket }}.s3.amazonaws.com{{ audio:url }}`

The Statamic SVG icon is also not loading correctly:
`404 Not Found: /vendor/statamic/cp/svg/file-audio.svg`

**Comment by jackmcdade** [comment]
Have you set the `AWS_URL` in your `.env` file?

**Comment by tao** [comment]
So simple... silly mistake.
