### ISSUE TITLE
Wrong top position for Bard Fixed Toolbar in Live Preview

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1508]
The class `bard-fixed-toolbar` has a top position of 52px. The position doesn't work within the Live Preview.

<img width="596" alt="Bildschirmfoto 2020-03-16 um 15 00 29" src="https://user-images.githubusercontent.com/54707973/76765578-e8fef600-6796-11ea-9db4-11684abec3bc.png">

**Comment by jackmcdade** [comment]
It's fixed in dev :)
