### ISSUE TITLE
Page from site ones listed on second site's structures 

### ISSUE THREAD

**Issue by peimann** [statamic/cms#1510]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/40042952/76772327-eeb80400-67b5-11ea-96bc-7faaa752e79d.png">

Page `home` is for `site one` and `home 2` is for `site two`. While I switch to site 1, only `home` is listed, but when switching to site two, both pages are listed. 
Both two pages' slug is 'home', so I assume they have to be alternative for each other on corresponding sites.

**Comment by jasonvarga** [comment]
Most likely solved for next release with all the new structures stuff. Please re-open if that's not the case.
