### ISSUE TITLE
Infinite recursion when augmenting user with relationship fieldtype

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#1513]
We have a user blueprint that allows linking an 'author' entry as a relationship field. When the same user U that has author A linked in his data is the last to save author A, augmenting the user U (when serializing it for the frontend) leads to an infinite recursion: U links to A through the relationship fieldtype, which in turn gets U augmented and serialized into it's 'updated_by' field, which in turn links to A, etc.

I assume there is a cycle check missing in the augmentation logic? We will look into this on our end and send a PR when we find a fix.

**Comment by sauerbraten** [comment]
It seems to also happen with entries in general, at least when Statamic tries to display them as results of the global search: entry X (collection A) -> entry Y (collection B) -> entry Z (collection C) -> entry X (collection A). Is there a reason augmentation is done beyond one level during serialization?

**Comment by sauerbraten** [comment]
As a workaround, we disabled from inside Value.php's jsonSerialize() method:

```php
    public function jsonSerialize($options = 0)
    {
        $value = $this->value();

        #if ($value instanceof Augmentable || $value instanceof Collection) {
        #    $value = $value->toAugmentedArray();
        #}

        return $value;
    }
```

We couldn't find a problem with this change so far, so maybe this is where a fix could begin to be implemented?

**Comment by jasonvarga** [comment]
Are you manually getting the augmented array somewhere in your own code? Or is this happening in the CP somewhere?

**Comment by sauerbraten** [comment]
We have dashboard widgets that fetch and serialize entries to pass them to a Vue component, but we don't touch the user or author entry that seem to cause this issue for us.

In the dashboard widgets we use the following code:

```php
$breakingNews = Facades\Entry::query()->where('is_breaking', true)->limit(20)->get();
$breakingNews = $breakingNews->values()->toAugmentedArray(['id','slug','title','channel','publish_date']);

// work around https://github.com/statamic/cms/issues/1487
$breakingNews = array_map(function ($e) {
    $e['collection'] = 'article';
    return $e;
}, $breakingNews);

$breakingNews = json_encode($breakingNews);
```

**Comment by sauerbraten** [comment]
Oh and yes, all of this is inside the Control Panel.
