### ISSUE TITLE
Switch tag doesn't allow colons

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#1528]
I can't do this:
![image](https://user-images.githubusercontent.com/9936988/77277387-15e26a00-6cbd-11ea-8871-5c8a5345dbb4.png)

I am getting a Modulo by Zero Exception

**Comment by jackmcdade** [comment]
That is correct. The colon defines a repeat:  https://statamic.dev/tags/switch#repeating-values.

You could move the `md:` outside the tag: `class="md:{{ switch between="order-2|order-1" }}.

**Comment by jackmcdade** [comment]
Got it to work with d88799ccd1011587f5e248ef1196cbc96949eb29 anyway though. 👍
