### ISSUE TITLE
Add primary buttons alway to top

### ISSUE THREAD

**Issue by steveooo1** [statamic/cms#1532]
Primary buttons (the blue ones) are sometimes found in the right hand corner in the top or at the bottom of the page.

I like to have this button always on the top right and bottom right. So from a UX standpoint, the enduser can "Save" by scrolling up and click "Save" or scrolling down.

Currently, this isn't always the case. Sometimes it's above, sometimes below.

**Comment by jackmcdade** [comment]
It's above on content (and have plans to make it sticky), and _below_ on settings/configs. This is so you have a chance to review *all* settings so you know what's available. It's not 100% rolled out to all areas of the CP yet, we're aware of that, but that's the direction we're taking.

**Comment by steveooo1** [comment]
Well, if you have to explain the logic behind the "Where is Waldo...ehh Button", you have some thing to make better :)

So all buttons either on top or on bottom or all buttons on top and bottom. I prefer the last one, because it doesn't matter where you are, you are able to decide for yourself (have trust in users) that they know to go up or down. Because with both buttons, the user is always right.

If you have some complex logic on why the button is on the bottom, you have some bad behavior. I tested these new buttons with 2 test subjects (just a casual test) and both moved their mouse to the top right, then they didn't find the button. One of them scrolled down and clicked the other one, but the other subject tried to go back by clicking the breadcrumb on the top left of the content area.

Just FYI

**Comment by jasonvarga** [comment]
Pretty standard to have buttons at the end of a form.

**Comment by jackmcdade** [comment]
Thanks for the feedback. I knew i would get some people saying this exact thing. Just FYI I’m never done tinkering. There a whole other angle on this this but not ready to get into it yet.
