### ISSUE TITLE
`Reorder` button in collection not on same line as everything else on smaller screen

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1535]
<img width="979" alt="image" src="https://user-images.githubusercontent.com/6069653/77502482-3a068e00-6e18-11ea-82c0-99f7ca806a27.png">

Maybe the `Search` field can shrink?

**Comment by mikemartin** [comment]
I think this is on all screen sizes, looks like the filter input group is set to `w-full` when maybe it should be `flex-1`?

**Comment by jasonvarga** [comment]
Fixed in 56a2f10c
