### ISSUE TITLE
Migration script for beta 20 not working on multisite

### ISSUE THREAD

**Issue by AndersMFJ** [statamic/cms#1536]
When trying to migrate a multisite setup (with two sites) from beta 19 to beta 20 using the migrate script I get the following error: 

```
Stache config config/statamic/stache.php file updated.

In console.php line 65:

  Undefined index: tree 
```

**Comment by jasonvarga** [comment]
Gist has been updated. Give it another try.

**Comment by jackmcdade** [comment]
Hey there, we haven't heard back on this for a while so I'm going to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!
