### ISSUE TITLE
Shallow augmentation of AssetContainer queries all assets

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#1549]
AssetContainer doesn't override the default shallow augmentation logic, which means it gets fully augmented with *all* assets before the default keys for shallow augmentations are selected.

In our case with a custom Elasticsearch backend and a big number of assets this leads to a delay in getting results from the global search (because SearchController shallow-augments the `container` key).

**Comment by jasonvarga** [comment]
Can you please be more specific where you're seeing this behavior?
When I do a search in the control panel, all I see is this:

![image](https://user-images.githubusercontent.com/105211/77783518-60524680-702f-11ea-8c3c-e5b3498ac4bd.png)

**Comment by sauerbraten** [comment]
Yes, that's the end result, but along the way, there is a call to AssetContainer::asset(), triggered from serializing the AugmentedCollection of results: https://blackfire.io/profiles/79de8e89-6ef1-4c04-9cbe-9c61ebe51652/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=Statamic%5CAssets%5CAssetContainer%3A%3AtoShallowAugmentedCollection&callname=main()

The problem is the default implementation of toShallowAugmentedArray() in HasAugmentedInstance calling toShallowAugmentedCollection(), which in turn does a full augmentation before selecting the shallowAugmentedArrayKeys. Somewhere, toShallowAugmentedArray() or toShallowAugmentedCollection() should be overriden to take a shortcut and provide the `id`, `title` and `api_url` values without calling AssetContainer::augmentedArrayData() (which triggers loading all assets).
