### ISSUE TITLE
Unable to change password

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#1556]
I'm getting the following error while trying to change my password.
<img width="384" alt="Screenshot 2020-03-27 at 21 07 01" src="https://user-images.githubusercontent.com/10623367/77801108-7afcdd80-7078-11ea-8683-922805c4044a.png">
I'm using Statamic v3.0.0-beta.22
Cheers

**Comment by jackmcdade** [comment]
Confirmed. Thanks for the report!

**Comment by damcclean** [comment]
The pull request has been merged, this pull request can be closed now.

**Comment by jimblue** [comment]
Your welcome Jack tks for the quickfix 👍
