### ISSUE TITLE
Pass `blueprint` value to the view

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1558]
The blueprint won't get passed to the collection

From my collection
```yaml
blueprint: entry_blog
```

My template won't output the blueprint. Everyting else does work.
```php
{{ collection:entries }}
    {{ blueprint }} {{# No output. Empty #}}
{{ /collection:entries }}
```

This is a major problem, when having different entry types, defined via the blueprint. Normally I would do:
```php
{{ collection:entries }}
    {{ partial src="partials/entry_types/{blueprint} }}
{{ /collection:entries }}
```

The view `partials/entry_types` can't be found

**Comment by steveooo1** [comment]
Probably same issue as here: https://github.com/statamic/cms/issues/1460

**Comment by jackmcdade** [comment]
@steveooo1 Not the same issue, just FYI.
