### ISSUE TITLE
Navigation doesn't work correctly with is_parent when entries not in the same collection

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#1559]
I've created the Navigation below which makes use of external links for our dropdown menus. But I can't seem to solve how to highlight the "Services" nav item when it is the current parent. 

<img width="947" alt="Screen Shot 2020-03-28 at 1 42 24 pm" src="https://user-images.githubusercontent.com/414211/77813094-fa7ec100-70f9-11ea-8371-b06abc4ee56c.png">

Views/nav.antlers.html
```
  <nav>
      {{ structure:nav }}
          {{ if children }}
               <button class="{{ if is_current || is_parent }}active{{/if}}">{{ title }}</button>
               {{ children }}
                  <a href="{{ url }}">...</a>
               {{ /children }}
          {{ else }}
            <a href="{{ url }}" class="{{ if is_current }}active{{/if}}>{{ title }}</a>
          {{ /if }}
      {{ /structure:nav }}    
  </nav>
```

Navigation/nav.yaml
```
title: Nav
collections:
  - pages
  - audiences
  - blog
root: true
tree:
  -
    entry: home
  -
    entry: 040322da-43d5-4e8e-8183-260bce79c1a4
  -
    title: Services
    url: 'services'
    children:
      -
        entry: 8355de08-3f1d-40d7-8f94-30b1213006a5
      -
        entry: 0bcbb4c8-d2b7-473d-9a67-2ee84569df4f
      -
        entry: a303e9f3-87e2-476b-8e56-435eb50b62d6
      -
        entry: 65e87b41-8d65-4012-a718-5e434f1eac71
```

collections/services.yaml
```
title: Services
route: '{slug}'
template: services.show
```

**Comment by jcohlmeyer** [comment]
I also can not get `{{ is_parent }}` to work on V3

**Comment by tomagig** [comment]
bump

**Comment by jackmcdade** [comment]
Instead of bumping, please use the thumbs up reaction on the initial issue. We can sort by them (super helpful) and to be honest, bumps are quite frustrating because we usually see them while in the middle of fixing a _different_ bug and it becomes counter-productive. Thanks! 😅
