### ISSUE TITLE
Can't set password for new user

### ISSUE THREAD

**Issue by goellner** [statamic/cms#1561]
I tried adding a new user and there is no way to active the user properly.

After adding a new user, the activation link returns a 404. 

I tried setting the password on the user page and there I get this error: 

![Screen Shot 2020-03-28 at 11 12 50](https://user-images.githubusercontent.com/3986748/77820800-365b5b80-70e5-11ea-9669-fcfe025b4b4a.png)

**Comment by damcclean** [comment]
I wonder if this issue is related to #1556
