### ISSUE TITLE
Glide Tag doesn't augment asset url after beta-20 upwards

### ISSUE THREAD

**Issue by mkriegeskorte** [statamic/cms#1564]
I experienced a problem with the glide tag after beta-20. I was unable to retrieve the asset URL in the tag pair. Using the single Tag and glide in "src" didn't work.

Example:
```
{{ glide:hero_image width="960" height="540" fit="crop_focal"}}
    <img src="{{ url }}" width="{{ width }}" height="{{ height }}" alt="{{ alt }}">
{{ /glide:hero_image }}
```

Downgraded to beta-20 and everything works fine as expected.

**Comment by edalzell** [comment]
I use the single tag in b22 and it works fine for me.

`<img class="rounded-full" src="{{ glide:image square="100" }}">`

Result here: https://silentz.co/about-me

**Comment by mkriegeskorte** [comment]
I upgraded again and was unable to reproduce this issue. Maybe just a glitch in the universe 🤷🏼‍♂️
