### ISSUE TITLE
CP "save" UX is confusing

### ISSUE THREAD

**Issue by vladdu** [statamic/cms#1565]
- The "Save" or "Finish" buttons on different pages are sometimes at the top, sometimes at the bottom.
- If a form is long, there is a lot of scrolling to reveal the "save" or "finish" buttons (and you don't know which way). The buttons should always be visible (like in v2).
- Some pages can be dismissed just by clicking in the wrong place, without a "do you want to leave?" warning. For example, if editing a replicator field in a blueprint, clicking on the sidebar with the main CP menu, the replicator goes away together with all the changes made. If multiple recursive pages are open, all disappear and are not saved.

**Comment by steveooo1** [comment]
I totally agree with you. Esp. the first two points are a pain. No good UX...

**Comment by jackmcdade** [comment]
These are two (possibly 3) separate issues. The missing "do you want to leave" notice is a bug – do you mind opening a new issue for that with details as to what fields you have there?

**Comment by vladdu** [comment]
Sure, created #1575

**Comment by sebabal** [comment]
In my opinion all toast/notification messages should appear at the top right since this where they are usually expected to appear....

**Comment by jasonvarga** [comment]
Closing this issue in favor of https://github.com/statamic/ideas/issues/335 and https://github.com/statamic/ideas/issues/336

**Comment by eliasu** [comment]
@jasonvarga or @vladdu: Any news on the save button positioning? Like a floating button or something?

**Comment by jackmcdade** [comment]
I know what I want to do but haven't had the time or opportunity to do it.
