### ISSUE TITLE
Add a way to go from a collection to its blueprint and back

### ISSUE THREAD

**Issue by vladdu** [statamic/cms#1566]
One needs a lot of clicks to go from one of the pages to the other, I think there should be a shorter way.
Alternatively, the blueprint could have a preview page

**Comment by jackmcdade** [comment]
You can go to a blueprint from the collection by clicking the "more" dropdown. You can't really go back the other way because a blueprint can be used by multiple collections.

![image](https://user-images.githubusercontent.com/44739/77924850-38065a00-7272-11ea-8429-a1cfd0113634.png)
