### ISSUE TITLE
compact CP UI

### ISSUE THREAD

**Issue by vladdu** [statamic/cms#1567]
While the whitespace is a good thing to have, I find that if that means a lot of scrolling, I'd rather have a more compact view. I'm thinking mostly about the field editor pages.

**Comment by jackmcdade** [comment]
If you have a lot of content or a lot of fields you're gonna need to do some scrolling. If you have a specific area you'd like to make some specific suggestions or thoughts on, I would love to hear it, but this issue is too vague to leave open indefinitely. Thanks @vladdu!

**Comment by vladdu** [comment]
The ideal UX that I can think of is to have a "normal" and a "compact" display view for the editors (maybe per user), that would choose different CSS styles. This could mean just removing the padding defined by .form-group for @media (min-width: 768px)

**Comment by jackmcdade** [comment]
At this point I can't begin to plan having two new modes to test every single field and nested field with, even as "simple" as this. We need to finish the CP as is and get v3 out the door before we have this kind of luxury.

You can always have your own little control panel override css file if you'd like. We even ship with it included, ready to go.

**Comment by vladdu** [comment]
Ok.
