### ISSUE TITLE
Beta22: potential tpyo in messages.php (EN)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1570]
'form_wizard_intro' => 'Forms are used to collect information from your visitors and dispatch events and notifications to your team of new submissions.',

What exactly is a "team of new submissions" ?!

'user_wizard_invitation_intro' => 'Send a welcome email with account activiation details to the new user.',

activiation => activation

**Comment by vladdu** [comment]
> What exactly is a "team of new submissions" ?!
Your team gets notifications whenever there are new submissions.

**Comment by ebeauchamps** [comment]
ok, why not, so shouldn't it be:
'Forms are used to collect information from your visitors and dispatch events and notifications of new submissions to your team.',

**Comment by jackmcdade** [comment]
It's not a "team of new submissions", it's "send notifications to your team"...

Reworded in ab9c447260d4b24be34b36ee1acb0d744666f09d.
