### ISSUE TITLE
Taxonomy handle not editable

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1572]
Edited handle is not saved.

**Comment by jackmcdade** [comment]
In what area of the control panel?

**Comment by Pfeifakopf** [comment]
In the taxonomy settings:
![image](https://user-images.githubusercontent.com/3351449/77942309-b76c4b80-72bb-11ea-84b5-ef5e277eab43.png)

**Comment by jasonvarga** [comment]
We've since removed the handle field. Renaming the handle could easily cause damage, so we'll leave it up to you to do by hand.
