### ISSUE TITLE
Parsing content in tags

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1573]
So I'm building out a form tag in my addon to make it more flexible. This is what the tag looks like in a template:

```
{{ commerce:form for='checkout' redirect='/thanks' class='flex flex-col w-full' }}
    <input type="text" name="name">
    <input type="text" name="email">

    <button>Checkout</button>
{{ /commerce:form }}
```

I have everything working fine, apart from one little thing.

If I have some sort of Statamic data inside of the tag, so like this:

```
{{ commerce:form for='checkout' redirect='/thanks' class='flex flex-col w-full' }}
    <input type="text" name="name">
    <input type="text" name="email">
    <input type="hidden" name="variant" value="{{ variant:uuid }}">

    <button>Checkout</button>
{{ /commerce:form }}
```

`{{ variant:uuid }}` would get removed and not replaced by anything 😢 

I'm not entirely sure why it's happening. Maybe I'm doing something wrong. This is the `form` method of my tag.

```php
public function form()
    {
        return (new FormBuilder())->build($this->getParam('for'), collect($this->params)->toArray(), $this->content);
    }
``` 

The `$this->content` part is where I'm getting the content inside the tag, so like the inputs and stuff.

The `FormBuilder` you're seeing there is [this class](https://github.com/doublethreedigital/simple-commerce/blob/7b3655a3fbabf6bcf5124318a6ebce56bae64f4b/src/Helpers/FormBuilder.php). It goes to the `build` function, down to one of the other functions and eventually ends up as `$contents` in the `compose` method.

In the `compose` method I'm adding things like a CSRF field and a `redirect` which works with my addon's actions.

Anyway, my hypothesis is that `$this->content` is not being parsed by Antlers, so maybe before I pass it into the `FormBuilder`, Antlers should parse it, convert it to a string and then it can be sent away to get stuff added.

**Comment by jasonvarga** [comment]
If you return a string from a tag, that's all that will happen. If you return an array, Antlers will use that to parse the contents.

Since you want a string returned (the entire html form tag), you can manually parse the contents.

Change `$this->content` to `$this->parse()`. (It'll use `$this->content`)

Check out the [form:create tag](https://github.com/statamic/cms/blob/master/src/Forms/Tags.php#L61) if you want an idea how we generate our forms.

**Comment by damcclean** [comment]
Hmm, ok.

So whenever I do `dd($this->parse())` it just returns empty content... [see screenshot](https://d.pr/free/i/eq8uxs)

Same if I just replace `$this->content` with `$this->parse()` like this:

```
return (new FormBuilder())->build($this->getParam('for'), collect($this->params)->toArray(), $this->parse());
```

**Comment by damcclean** [comment]
Got it working now! Turns out after my refactoring yesterday, I didn't realise that I wasn't actually passing in the variables in my template, no wonder nothing was displaying.

Thanks for your help Jason. I need to stop reporting bugs where I'm the issue 😂
