### ISSUE TITLE
Empty field breaks loading

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1579]
if hero__title is empty, this error comes.

{{ hero__title | markdown | strip_tags:p or title }}

Facade\Ignition\Exceptions\ViewException
Argument 1 passed to Statamic\Markdown\Parser::parse() must be of the type string, null given, called in /var/www/vhosts/domain/httpdocs/vendor/statamic/cms/src/Modifiers/CoreModifiers.php on line 1128

**Comment by jackmcdade** [comment]
Fixed.
