### ISSUE TITLE
Multi sites and collections give "Root page must be an entry "

### ISSUE THREAD

**Issue by randohinn** [statamic/cms#1583]
Fresh installation as per the Quisckstart guide. Next step was to enable multisites with the command line. After this, `cp/collections` presents an error of ` Root page must be an entry ` at `vendor\statamic\cms\src\Structures\Structure.php:113`

**Comment by jasonvarga** [comment]
I believe that's fixed by ea49999472ac8fb5ab619a85740641ba6aee4367 but I'll double check...

**Comment by jasonvarga** [comment]
You ran `php please multisite`? Did you update the `sites.php` config like the command said?

**Comment by randohinn** [comment]
yes, changed the default => "est"

**Comment by jasonvarga** [comment]
Please show config/statamic/sites.php

**Comment by jasonvarga** [comment]
The `please multisite` command instructs you on how to update the `sites.php` config file.

If I ignore the instructions, I get the same error.
If I follow them, everything seems fine.

Closing this. Please reopen if it's still a problem.
