### ISSUE TITLE
File uploads in front-end forms need to be updated

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1584]
The uploader code is still referencing older v2 features, like having fields with `type: file` etc. We now use blueprints.

**Comment by sebabal** [comment]
Hey guys just checking can we actually upload files from a form on the frontend, now?

**Comment by twd3** [comment]
Would love to know this as well.

**Comment by derekjones** [comment]
Not having success here, using the blueprint. I'm sure I'm just using the wrong syntax on the front end, but the docs are still not updated.

**Comment by jesseleite** [comment]
File uploads were fixed [in this PR](https://github.com/statamic/cms/pull/2206), but I'm leaving this issue open as file uploads could still use a bit of love.  For example, this should be possible in the front end when uploading to an asset field with `max_files: 1`:

```html
<input type="file" name="certificate" />
```

But this is required at the moment:

```html
<input type="file" name="certificate[]" />
```

**Comment by jesseleite** [comment]
Did another pass on form file uploads, to be released in beta 45.  See [updated usage info here](https://statamic.dev/forms#file-uploads).
