### ISSUE TITLE
Clicking field name's to see handles does not work in PublishForm

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1585]
When you view an entry's publish form and you click on the name of a field, it shows you the handle of the field. However, this does not seem to be true if you are using the default PublishForm component that is encouraged to be used in addons.

## In an Entry
* [See video](https://d.pr/free/v/Y4MQPT)

## In a PublishForm
* [See Video](https://d.pr/free/v/6oOJgr)

**Comment by jasonvarga** [comment]
Add a `:can-toggle-labels="true"` to `<publish-sections />`

**Comment by damcclean** [comment]
I don't have access to the `publish-sections` component, just the `publish-form` one. See https://github.com/doublethreedigital/simple-commerce/blob/master/resources/views/cp/products/edit.blade.php

**Comment by jasonvarga** [comment]
Ooh forgot all about that wrapper. I'll add the prop.

**Comment by jasonvarga** [comment]
Added in c1cab9defc2f8719fbba8b6ae415c63a9763144d
