### ISSUE TITLE
Greater/less than conditions cause parse error

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#1589]
**Describe the bug**
When using less than or greater than conditions in an antlers template, they appear to get stripped out during parsing

**To Reproduce**
1. Have a condition such as `{{ if now | format:"ymd his" < deadline | format:"ymd his" }}` - this works on v2
2. Load the page and it will error, saying `syntax error, unexpected 'null' (T_STRING)`, and the generated template looks like this: `<?php if ('"200331' null): ?>` - there is an extra `"` before the first date, and the `<` has gone missing entirely.

**Expected behavior**
For it to parse this a a condition

**Environment (please complete the following information):**
 - Statamic version:
    3.0.0-beta.22 and 23
 - Install method: 
    Fresh install from statamic/statamic
 - PHP version:
   7.4.2
 - Operating System:
    macOS

**Comment by jackmcdade** [comment]
What format is `deadline` in by itself? Is it necessary to format both into that string format?

Also, does this work?

```
{{ if (now format="ymd his") < (deadline format="ymd his") }}
```

**Comment by MattRogowski** [comment]
In the .md file it is stored as `deadline: '2020-04-28'`

I had tried brackets around it as well as the other modifier format too, this seemed to make it go even more wonky

`<?php if (('March 31st, 2020' format="ymd his") < ('2020-04-28' format="ymd his")): ?>`

**Comment by MattRogowski** [comment]
So I forgot that there's the handy `is_past` and `is_future` modifiers so I have used those instead (derp), however will keep this open for now as it looks like there's still a regression with something that worked before.

Thanks again for all the work on v3 👍

**Comment by jasonvarga** [comment]
Any chance beta23 fixed it?

**Comment by MattRogowski** [comment]
Negative on that :(

**Comment by jackmcdade** [comment]
This actually works as intended. The issue is you were blending syntaxes – using the pipes _and_ an argument inside "quotes".

This here works just fine, as I would expect:

```
{{ if now | format:ymdhis < deadline | format:ymdhis }}
    show thing
{{ /if }}
```
