### ISSUE TITLE
Replicator Fieldtype doesn't work in user blueprint

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1590]
It isn't possible to add a Replicator Fieldtype to the blueprint `user.yaml` -> [user.txt](https://github.com/statamic/cms/files/4413333/user.txt)

Error Message: `meta is undefined`

![Bildschirmvideo aufnehmen 2020-04-01 um 09 02 27](https://user-images.githubusercontent.com/54707973/78108759-50a07c80-73f8-11ea-8259-182c232afb0d.gif)

**Comment by jasonvarga** [comment]
This was fixed in 3a6b920e490bb5472b3929152d70f46861184471
