### ISSUE TITLE
Column select pop-up could be wider

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#1597]
We have German field names and quite a few of them wrap aroung because the pop-up where you enable and disable them is very narrow:

![image](https://user-images.githubusercontent.com/1760908/78152814-a0079c80-743a-11ea-871e-a39f2b34c04e.png)

**Comment by jasonvarga** [comment]
Oh right. I also noticed this when I had a `Donaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaft` column.

**Comment by sauerbraten** [comment]
Good to know you're testing with a realistic setup! 🙌

**Comment by damcclean** [comment]
I'm not able to replicate this issue on the latest release, looks like it's been fixed...

![image](https://user-images.githubusercontent.com/19637309/95743093-165a4680-0c89-11eb-902a-e99356c13e98.png)
