### ISSUE TITLE
Users Data Table don't show column configuration

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#1598]
**Describe the bug**
The users data list table does not give you the option to configure what fields are shown.

However, the column settings are shown on the entry data list tables (see screenshot).

**To Reproduce**
1. Go to `Control Panel > Users`
4. See no column settings/configuration

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/19637309/78157154-8a44a800-7437-11ea-9428-50c111cfe6d4.png)
![image](https://user-images.githubusercontent.com/19637309/78157307-b829ec80-7437-11ea-962b-17a5de0a37f9.png)

**Environment (please complete the following information):**
 - Statamic version: Statamic 3.0.0-beta.22
 - Install method: installed into existing Laravel app
 - PHP version: PHP 7.4.3
 - Operating System: MacOS
 - Browser: Google Chrome

**Comment by jackmcdade** [comment]
We're planning to add it but it wasn't priority at this time. Thanks for the poke!
