### ISSUE TITLE
Can't see `Fields` on small screen with debug bar showing

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1600]
**Describe the bug**
If you have a small screen (like a 12" MacBook) and have the debugbar enabled, you can't see the `Fields`

**To Reproduce**
1. Make screen same size as 12" MacBook
2. Enable debugbar
3. Visit control panel

**Expected behavior**
See the `Fields`

**Screenshots**

<img width="277" alt="image" src="https://user-images.githubusercontent.com/6069653/78187992-5318cb80-7424-11ea-85da-1414ce3d18ca.png">

**Environment (please complete the following information):**
 - Statamic version: beta23
 - Install method: fresh install
 - PHP version: 7.4
 - Operating System: macOS
 - Browser: safari

**Comment by jackmcdade** [comment]
The only way to 100% reliably solve that is to add a watcher for whether the debug bar is on and what the current margin is applied to the fixed element on the `body` tag. It'll be an expensive repaint kind of thing and likely slow the control panel down. You can't just add padding-bottom unfortunately.

Can you live with having to close the debugbar if it covers something up?

**Comment by edalzell** [comment]
![](https://media.giphy.com/media/qDIeQmPWXbo3e/giphy.gif)
