### ISSUE TITLE
The "make:action" command is missing

### ISSUE THREAD

**Issue by aryehraber** [statamic/cms#1604]
_Apologies if this is already possible, might have missed it in the docs. I did attempt a quick code dive into core but also couldn't see an "easy" way to do this._

For my Impersonator addon, I'd like to add a shortcut action to start an impersonating session from the Users Listing views:

![Screenshot 2020-04-02 at 11 28 54](https://user-images.githubusercontent.com/5065331/78238806-46a47980-74dd-11ea-827d-c22d7262e957.png)

Had a quick peek at the V2 Duplicate addon and hope it's not going to be this complex in V3:
https://github.com/dannyuk1982/statamic-Duplicate/blob/master/resources/assets/js/addButtons.js

**Comment by jasonvarga** [comment]
Yeah it's possible.

https://statamic.dev/extending/actions

Addon's can register a bunch of stuff [by listing them in arrays](https://statamic.dev/extending/addons#registering-components) but it looks like we don't support an array of actions yet. *That* we can add.

You can manually register an action in the mean time though, by calling `YourAction::register()` in your service provider's boot method.

**Comment by aryehraber** [comment]
Thanks for pointing me in the right direction @jasonvarga! 

Will give it a try this week and get back with Qs if I have any. I definitely remember skimming this page (sorry!) and it not being obvious to me that this is what I needed. Thanks again!

**Comment by aryehraber** [comment]
Right off the bat, the `make:action` command doesn't seem to exist 😅  

I'm on `Statamic 3.0.0-beta.23`

<img width="304" alt="Screenshot 2020-04-02 at 16 46 52" src="https://user-images.githubusercontent.com/5065331/78263057-c17f8b80-7501-11ea-94f1-1a2a9a8e270e.png">

Will create one manually for now as per the Docs.

**Comment by aryehraber** [comment]
Wow, works great otherwise. Awesome job on this, super powerful 👏 

Will leave open since the `please` command seems to be broken/missing.
