### ISSUE TITLE
Global Set area is pretty broken.

### ISSUE THREAD

**Issue by Sceko** [statamic/cms#1610]
After select Blueprint
Can not save not working
![Screenshot 2020-04-02 at 22 46 30](https://user-images.githubusercontent.com/2323952/78298999-ce1cd780-7533-11ea-87f8-74fdf0aec1af.png)

**Comment by jackmcdade** [comment]
Can you please fill out all the required information when opening a bug report so we can try to recreate?

**Comment by sebabal** [comment]
Hi I am having the same issue the error is as follows....

Call to a member function in() on null
/vendor/statamic/cms/src/Providers/RouteServiceProvider.php#130
Symfony\Component\Debug\Exception\FatalThrowableError

**Comment by sebabal** [comment]
It seems it was also reported here #1543

**Comment by jackmcdade** [comment]
Yeah i get a bunch of Vue errors too. 
![image](https://user-images.githubusercontent.com/44739/78363808-65147e80-758a-11ea-97b5-c04874283abd.png)

**Comment by sebabal** [comment]
As a workaround for now, you can do the wiring directly through the YAML files, then you can use the UI to update the variables, etc just fine.
