### ISSUE TITLE
UI - Minor: Entry Save & Publish always active

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1615]
## Bug Description
If an entry is not "dirty" then the Save & Publish button should be greyed out like it is in the Term screen.

## How to Reproduce
Here's how I can recreate the bug:
1. Create an entry
2. Save it
3. Notice the state of the Save & Publish button

## Expected Behavior
I expected the Save & Publish to act like it does in Term, and be inactive when it doesn't need saving.

## Screenshot/Exception
Here's where you can add screenshots, screencasts, or a link to a Flare exception message to help explain the problem.

## Environment

**Statamic version:** 3.0.0.-beta-22

**Browser:**
Safari

**Comment by jackmcdade** [comment]
We did that on purpose because sometimes people just want to click save to feel safe. 🤔
