### ISSUE TITLE
Grid field used as a configField doesn't work properly

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#1616]
## Bug Description
When I add a grid field inside an Addon's configFields, everything is displayed properly, but when adding a row, nothing happens and a console error is shown.

## How to Reproduce
Here's how I can recreate the bug:
1. Create an addon with a grid field inside configFields
2. Try to add a row
3. See JS error in console

## Expected Behavior
The ability to add a row to the grid

## Screenshot/Exception
![image](https://user-images.githubusercontent.com/3626559/78337935-1ff44a80-7592-11ea-843d-2a6a011d8d4a.png)

## Environment

**Statamic version:** 3.0.0.-beta-22

**Install method:**
Fresh install from `statamic/statamic`

**PHP version:** 7.4

**Operating System:**
MacOS

**Browser:**
Firefox

**Comment by riasvdv** [comment]
It's here https://github.com/riasvdv/statamic-button-box/blob/master/src/ButtonBox.php#L10

**Comment by jackmcdade** [comment]
Ah, this is because "meta" fields (fields that have their own fields) are not currently supported for use in as config fields.

**Comment by riasvdv** [comment]
Still needs fixin' 😉

**Comment by theutz** [comment]
This is still broken over a full year later. :(

**Comment by riasvdv** [comment]
Make sure to thumbs up, some day it'll get on the priority list! 😅
