### ISSUE TITLE
parameter attr of form tag is not working

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#1620]
## Bug Description
Using the parameter `attr` of the `form` tag is not working as expected.

## How to Reproduce
this
```twig
{{ form:contact attr="class:pretty-form|id:contact" }}
```
should output
```html
<form action="//localhost:3001/!/forms class="pretty-form"  id="contact" method="POST">
```
but it output
```html
<form action="//localhost:3001/!/forms" attr="class:pretty-form|id:contact" method="POST">
```

## Environment

**Statamic version:** 3.0.0.-beta-23

**Install method:** fresh install from `statamic/statamic`

**PHP version:** 7.4.4

**Operating System:** MacOS

**Browser:** Chrome

**Comment by jasonvarga** [comment]
We changed that, maybe it didn't make it into release notes. Now you can just use regular attributes.

```
{{ form:contact class="pretty-form" id="contact" }}
```

**Comment by jimblue** [comment]
Thank Jason :D
So the doc is not up to date here https://statamic.dev/tags/form-create#parameters
