### ISSUE TITLE
A more streamlined connection between rootpage and navigations

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1627]
The new kind of integrated structures inside collections became great! As well having a navigation section does make sense and is a good UX improvement. 

## Actual Behavior
When creating a fresh installation, there is a default pages collection, connected with a structure. The first entry of this collection will be the root page and displayed as first page. 

If using a navigation to structure the page, it will not take any influence to select the root page.
Meaning: I need to create a pages structure, even if not needed to define a root page to prevent any error. 
On top of that, I need to create the same or similar structure in the navigation, to create the belonging navigation.  

## Expected Behavior
To streamline this behavior, I would wish for the following behavior
- The default pages collection without a structure
- Default navigation, prepared for the user after install
- To require exactly one navigation to be the default / main navigation
- Statamic selecting the root page from the defaut / main navigation

## Environment

**Statamic version:** 3.0.0.-beta-23

**Install method:**
- Existing Statamic app

**PHP version:** 7.4

**Operating System:**
- MacOS

**Browser:**
- Chrome

**Comment by jackmcdade** [comment]
@jonassiewertsen I didn't quite follow all of that, but the way the base install is set up now is the way it's going to stay. You are more than welcome to — _encouraged even_ — to fork `statamic/statamic` and set up the base configuration however you want, and use that for all your new sites. That way, it's just the way you like it, every time.

**Comment by jonassiewertsen** [comment]
It feels wrong to me, not to define the root page in the navigation itself.

That´s the way it does work in most cms and does feel most natural. But I think you do disagree.

**Comment by jackmcdade** [comment]
I don't understand. You _can_ define the root page in a navigation, there's a setting for that.

**Comment by jasonvarga** [comment]
You typically wouldn’t need a separate navigation alongside your pages collection.

**Comment by jonassiewertsen** [comment]
@jackmcdade 
Let's say I don't use a structure in my page collection but have defined a root page in my navigation, my base URL `mypage.com/' would throw an error. Reason: The entry point for the statamic page is defined in the structure of my page collection. That does not make sense for me.

@jasonvarga 
In my opinion, it should be the other way around: That I do need a main Navigation, where the entry point for the root page is defined. Basically:
When opening `mypage.com/`, that the entry page is defined in the navigation.

**Comment by jasonvarga** [comment]
If you don't use a structured collection, how would you like to define your home page?

**Comment by jonassiewertsen** [comment]
In the navigation, where one navigation is required as root navigation as an entry point.

**Comment by jasonvarga** [comment]
Navigations are just arrangements of links or references to entries. They aren't intended to actually define content URLs.

**Comment by jackmcdade** [comment]
Think of that structured Pages collection exactly like v2's "Pages" feature. It's basically the same intention.

**Comment by jonassiewertsen** [comment]
It's more flexible to structure your page in a navigation. Let's say I want to structure my page and need to add internal or external links, which is pretty common.

**Comment by jonassiewertsen** [comment]
If I need that, the page collection structure does not work. Then I need to keep the page collection as the entry point, but need to structure everything in the navigation to make that happen. 

So using the navigation for it, would avoid that problem, accomplish the same and would be more flexible and more open to more additions.

**Comment by jasonvarga** [comment]
You can do that in your pages collection. Edit the collection and make it linkable:

![image](https://user-images.githubusercontent.com/105211/78572203-29312180-77f5-11ea-9ae3-0a0994774c8a.png)

Then when you try to create a page, you are given the option to create a link.

![image](https://user-images.githubusercontent.com/105211/78572244-35b57a00-77f5-11ea-9ab1-3db928cc3b6b.png)

You can use the page to redirect to somewhere else.

![image](https://user-images.githubusercontent.com/105211/78572292-4960e080-77f5-11ea-9afa-b47a902a3e3b.png)
