### ISSUE TITLE
Setting the sites option on a multisite does not have any effect 

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1628]
## Bug Description
When defining sites in an entry on a multisite,
```php
sites:
  - en
  - fr
```

it does not have any effect as described in the docs:
https://statamic.dev/knowledge-base/localizing-entries

Even without them defined, entries can be localized.

## Expected Behavior
When not having them defined, localization should not be possible.

## Environment

**Statamic version:** 3.0.0.-beta-23

**Install method:**
- Fresh install from `statamic/statamic`

**PHP version:** 7.4

**Operating System:**
- MS-DOS 6.1

**Browser:**
- Netscape Navigator 2.0

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
