### ISSUE TITLE
localizable: false does not prevent fields to be localizable

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1629]
## Bug Description
When setting localizable explicit to false, the fields can be localized anyways. 

Something from my blueprint:
```php
        handle: header_image
        field:
          container: assets
          mode: grid
          restrict: false
          allow_uploads: false
          max_files: 1
          type: assets
          localizable: false
          listable: hidden
          display: 'Header Foto'
          validate: required
          folder: galerie
```

Still, another image can be selected. This behavior is the same for other fieldtypes.

## Expected Behavior
A field set to 'localizable: false' should not be editable, when not editing the origin entry. 

## Environment

**Statamic version:** 3.0.0.-beta-23

**Install method:**
- Fresh install from `statamic/statamic`

**PHP version:** 7.4

**Operating System:**
- MacOS

**Browser:**
- Chrome

**Comment by jasonvarga** [comment]
Are you editing an entry? Global? Taxonomy term?

**Comment by jonassiewertsen** [comment]
Sorry!
This is an Entry.

**Comment by manogi** [comment]
I have the same issue, but ONLY in globals, and I am on v3.0.0-beta.26

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
