### ISSUE TITLE
Taxonomy referencing another taxonomy throws an error

### ISSUE THREAD

**Issue by philsturgeon** [statamic/cms#1630]
## Bug Description

Getting `Call to a member function collection() on null` after setting up two taxonomies: "Solutions" and "Sectors". I dunno if a taxonomy is meant to have another taxonomy, but im trying to give "Solutions" a "Sector". Maybe it has to be done with Collections?

Either way, Solutions will not unless all the `sector: []` arrays are empty.

## How to Reproduce
Here's how I can recreate the bug:
1. Recreate sector and solutions blueprints and taxonomies like here: https://github.com/protect-earth/protect.earth/pull/33/files
2. Log in to CP 
3. Dashboard > Taxonomies > Solutions

## Expected Behavior

I'm expecting to see all the Solutions listed.

## Screenshot/Exception

<img width="1440" alt="Screen Shot 2020-04-05 at 17 01 30" src="https://user-images.githubusercontent.com/67381/78503584-88dced80-775f-11ea-9c85-3981bbd433d7.png">

## Environment

**Statamic version:** 3.0.0.-beta.20

**Install method:**
- composer create project

**PHP version:** 7.4.4

**Comment by jesseleite** [comment]
I believe that commit solves the problem.  Let us know if you're still experiencing issues around this 🤘

**Comment by philsturgeon** [comment]
Thank you! The change seems to have fixed this issue.
