### ISSUE TITLE
"multi-sites" in general do need more love 

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1631]
## Bug Description
The multi-site functionality needs more love in general. A lot of preparations are in place already.

I couldn't get a multi-site up and running. Collections do behave differently than expected but can be translated. Globals won't show up in the CP anymore, even if created and existing for each language. When referring to an origin entry, the data is not available in the view.

It seems like a more general problem, which probably will be fixed when squashing bugs in the next weeks, after the big collection/structure refactor. 

Let me know if more information about specific areas is wanted. It just felt overdue to create an issue for each. 

## Environment

**Statamic version:** 3.0.0.-beta-23

**Install method:**
- Existing Statamic app

**PHP version:** 7.4

**Operating System:**
- MacOS

**Browser:**
- Chrome
- Firefox

**Comment by jasonvarga** [comment]
I agree they need more work, but this issue isn't really useful because it's so vague.

We have a bunch of updates to globals coming in the next release.
