### ISSUE TITLE
Sidebar not showing in addon

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1632]
## Bug Description
The Sidebar is not showing in a plugin when defined as sidebar.

```
'sections' => [
                'main'    => [
                    'fields' => [
                        [
                            'handle' => 'title',
                            'field'  => [
                                'type'     => 'text',
                                'display'  => __('butik::product.title'),
                                'validate' => 'required|string',
                            ],
                        ],
                   ]
                  'sidebar' => [
                        'fields' => [
 ```

https://github.com/jonassiewertsen/statamic-butik/issues/7

## Screenshot/Exception
![Screenshot 2020-04-05 at 23 17 06](https://user-images.githubusercontent.com/38906163/78510201-eab74a80-7793-11ea-9203-9c65b8b81de3.png)

## Environment

**Statamic version:** 3.0.0.-beta-23

**Install method:**
- As a Statamic plugin

**PHP version:** 7.4

**Operating System:**
- MacOS

**Browser:**
- Chrome

**Comment by damcclean** [comment]
Had the same issue myself recently but it's easilly resolved by adding this to the affected views.

```@section('wrapper_class', 'max-w-3xl')``

**Comment by jackmcdade** [comment]
@damcclean That is the right solution, thanks for catching it!
