### ISSUE TITLE
Not able to use special characters in the variable fallback string

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#1634]
## Bug Description
Trying to do a variable fallback just as is the doc: https://statamic.dev/antlers#variable-fallbacks-null-coalescence

When I use special characters eg like æ, ø and å which is just as common as other letters here in Denmark, it simple doesn't output neither the variable or the fallback string.

## How to Reproduce
Here's how I can recreate the bug:
{{ text ?? "Las mere" }} works:
![Skærmbillede 2020-04-06 kl  12 14 28](https://user-images.githubusercontent.com/43215436/78555585-a4063680-780d-11ea-9e2b-608f799d9db6.png)

{{ text ?? "Læs mere" }} doesn't:
![Skærmbillede 2020-04-06 kl  12 15 28](https://user-images.githubusercontent.com/43215436/78555601-af596200-780d-11ea-882f-81310d56163a.png)

It doesn't matter whether the {{ text }} is empty or set.

## Environment

**Statamic version:** 3.0.0.-beta-23

**Install method:**
- Fresh install from `statamic/statamic`

**PHP version:** 7.2 (also tested 7.4)

**Operating System:**
- MacOS

**Browser:**
- Chrome

**Comment by jackmcdade** [comment]
Confirmed. Nice catch!

**Comment by jackmcdade** [comment]
Fixed in af8e4135d64769f158d8254cd944efacef6d5e0b.
