### ISSUE TITLE
Auto-populated date field fails validation

### ISSUE THREAD

**Issue by aamood** [statamic/cms#1638]
I have a date field on my blueprint. The field auto-populates to the current date, which is exactly what I'm wanting, but on submit it doesn't pass validation until I manually select the current date.

![image](https://user-images.githubusercontent.com/12301620/78605863-ed608100-7821-11ea-928d-3bf4008d9d67.png)

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
