### ISSUE TITLE
Different lines in en/*.php language files compared to a new generated translation

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1640]
I cloned `statamic/cms` (on 5th of April) and generated fresh translation files as described [here](https://statamic.dev/cp-translations).

There are some differences in the `/en/*.php` files compared to the ones when generate them with `php translator generate de-CH`. Some of them have different names, or may not be used anymore. However, I list them here, maybe this is helpful?

### fieldtypes.php

Last two lines live only in the default /en version, but not in a generated translation:

```
'textarea.config.character_limit' => '',
'relationship.config.mode' => ''
```

### messages.php

These lines are in the default /en version, but not in a generated translation:

```
'blueprints_button_help_text' => '',

'collection_configure_amp_instructions' => '',
'collection_configure_articles_description' => '',
'collection_configure_blueprints_instructions' => '',
'collection_configure_content_model_intro' => '',
'collection_configure_dates_intro' => '',
'collection_configure_default_status_draft_description' => '',
'collection_configure_default_status_published_description' => '',
'collection_configure_events_description' => '',

'collection_configure_mount_instructions' => '',
'collection_configure_no_dates_description' => '',
'collection_configure_order_intro' => '',
'collection_configure_ordered_alpha_ascending' => '',
'collection_configure_ordered_alpha_descending' => '',
'collection_configure_ordered_by_date_description' => '',
'collection_configure_ordered_by_title_description' => '',
'collection_configure_ordered_date_ascending' => '',
'collection_configure_ordered_date_descending' => '',
'collection_configure_ordered_sequentially_ascending' => '',
'collection_configure_ordered_sequentially_descending' => '',
'collection_configure_ordered_sequentially_description' => '',
'collection_configure_route_instructions' => '',
'collection_configure_routing_intro' => '',
'collection_configure_structure_instructions' => '',
'collection_configure_structure_route_instructions' => '',
'collection_configure_taxonomies_instructions' => '',

'collections_layout_instructions' => '',

'collections_structure_instructions' => '',

'collections_template_instructions' => '',
'default_value_instructions' => '',

'fieldsets_button_help_text' => '',

'getting_started_widget_addons' => '',

'navigation_configure_expect_root_instructions' => '',

'navigation_configure_max_depth_instructions' => '',

'navigation_empty' => '',
```

These lines are in a generated translation, but not in the default /en version:

```
'form_wizard_submissions_intro' => '',

'navigation_configure_expect_root_instructions' => '',

'navigation_configure_max_depth_instructions' => '',
```

**Comment by ebeauchamps** [comment]
My 1 cent:
- lines in the default /en/messages.php file but not generated in a new translation are keys that were discarded along the beta process.
- lines in the generated translation but not in the default /en version: I think it's a problem coming from the difference between the last beta version installed and the commits made to this beta version since its release. For example, fieldtypes.php isn't a file available in beta23.

**Comment by helloDanuk** [comment]
> * lines in the default /en/messages.php file but not generated in a new translation are keys that were discarded along the beta process.

Yes, that could be. But it might be worth to double check them? Or then, they need to be deleted from the en-version I guess?

> * lines in the generated translation but not in the default /en version: I think it's a problem coming from the difference between the last beta version installed and the commits made to this beta version since its release. For example, fieldtypes.php isn't a file available in beta23.

Those 3 lines are missing in the latest /en/messages.php (latest commit/HEAD, not beta.23) too.

**Comment by helloDanuk** [comment]
I can confirm, that the remaining keys in the english `messages.php` are leftovers from an earlier beta version. I deleted those and found no missing translation in the CP so far.

**Comment by ebeauchamps** [comment]
After Beta35, I compared my (French) messages.php with the (English) messages.php found in vendor/statamic/resources/lang/en/
=> same number of lines

I compared with the (English) messages.php and the (French) messages.php in my repo were I run ```php translator generate fr```: those files are identical

So I guess this issue can now be closed  @helloDanuk
