### ISSUE TITLE
Relationship Selector doesn't auto-apply filters

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#1641]
## Bug Description
The relationship selector doesn't auto-apply filters like the entry listing does.

https://github.com/statamic/cms/blob/2fe32c6bba8d8c62c78e4a7973c153ca1a2017d2/resources/js/components/Listing.vue#L67

versus

https://github.com/statamic/cms/blob/2fe32c6bba8d8c62c78e4a7973c153ca1a2017d2/resources/js/components/inputs/relationship/Selector.vue#L156

## How to Reproduce
Here's how I can recreate the bug:
1. Have a filter that auto-applies some value
2. Load an entry listing, i.e. a route rendering views/collections/show.blade.php
3. Open the select stack of a relationship

## Expected Behavior
I expected the filter's autoApply() value to be used in both cases.

**Statamic version:** HEAD

**Comment by jesseleite** [comment]
Good find, thanks!
