### ISSUE TITLE
starter app install error pixelfear/composer-dist-plugin

### ISSUE THREAD

**Issue by richardwo** [statamic/cms#1643]
Running the starter install command
`composer create-project statamic/statamic my-site --prefer-dist --stability=dev`

I get an error in Composer:

```
  - Installing pixelfear/composer-dist-plugin (v0.1.2): Loading from cache
Plugin installation failed, rolling back
  - Removing pixelfear/composer-dist-plugin (v0.1.2)

[ErrorException]
include(/home/vagrant/vendor/pixelfear/composer-dist-plugin/src/Plugin.php): failed to open stream: No such file or directory
```

and the install fails

**Comment by jasonvarga** [comment]
What does `composer -V` output?

**Comment by richardwo** [comment]
Composer version 1.10.1 2020-03-13 20:34:27

I’m running it inside a Laravel Homestead VM.

**Comment by jasonvarga** [comment]
Have you ever installed a Statamic site in there successfully?

**Comment by richardwo** [comment]
No, this is the first time I’ve attempted it.
I’ve just tried the same install command on a remote server I’ve got access to and it worked fine with the same version of Composer - so it must be something to do with the Homestead VM not Statamic.
Thanks

**Comment by jackmcdade** [comment]
That checks out. Thanks for the followup @richardwo!
