### ISSUE TITLE
Uncaught TypeError: path.split is not a function

### ISSUE THREAD

**Issue by aerni** [statamic/cms#1645]
## Bug Description
There's a JS error on some CP routes: `Uncaught TypeError: path.split is not a function`

## How to Reproduce
Here's how I can recreate the bug:
1. Go to `/cp/collections/pages/edit`
2. See error in console

## Screenshot/Exception
<img width="2672" alt="Bildschirmfoto 2020-04-07 um 20 30 55" src="https://user-images.githubusercontent.com/23167701/78706131-dea3c800-790e-11ea-8adb-94f5074b3a6d.png">

## Environment
**Statamic version:** 3.0.0-beta.23
**Install method:** Fresh install from `statamic/statamic`
**PHP version:** 7.3.15
**Operating System:** MacOS
**Browser:** Chrome

**Comment by jackmcdade** [comment]
I can't recreate this on `beta-23` or on `master`. Did you do anything else?

**Comment by aerni** [comment]
Ok, I just did a fresh install and tried to recreate the bug myself. 

It appears as soon as you open Vue Devtools. But only on certain pages like `cp/collections/pages/entries/home/home` or `/cp/collections/pages/edit`.

**Comment by jackmcdade** [comment]
Looks like this is an issue with [Vue Devtools](https://github.com/vuejs/vue-devtools/issues/919) that was just fixed. Give your Chrome extension an update and it _should_ go away :)
