### ISSUE TITLE
Loop Variables (arrays) without a space before the closing }} braces on the open tag are parsed wrong.

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#1646]
## Bug Description
Using to spacing in the opening tag of a replicator field tag doesn't work together with using partials within.

## How to Reproduce
1. Create a replicator
2. Add stuff
3. Cretate a view where you want to display data. Don't add spaces in the opening tag as image below.
4. Reference a partial within a condition as the image below.

## Expected Behavior
I expect the partial to be rendered. And using no spaces is allowed according to documentation examples: 

![image](https://user-images.githubusercontent.com/31292231/78723869-88458200-792c-11ea-9570-6a32986ec9f6.png)

## Screenshot/Exception
![image](https://user-images.githubusercontent.com/31292231/78723438-b5456500-792b-11ea-9b64-c2bc37581064.png)

## Environment

**Statamic version:** 3.0.0.-beta-{replace_me}
3.23

**Install method:**
- Fresh install from `statamic/statamic`

**PHP version:** 7.{replace_me}
7.3

**Operating System:**
- MacOS

**Browser:**
- Doesn't matter

**Comment by jackmcdade** [comment]
Fixed in f57337823477aed0abdacf17070e1f482ba19474.
