### ISSUE TITLE
Tags Fieldtype Overflow UI Glitch

### ISSUE THREAD

**Issue by ramimassoud** [statamic/cms#1648]
## Bug Description

When the length of the tags is too long, the UI element doesn't adapt to the wrapped tags

## How to Reproduce

Add enough tags to cause them to wrap

## Expected Behavior
The UI element to expand to fit all of the tags

## Screenshot/Exception

![image](https://user-images.githubusercontent.com/374033/78735275-604c2380-7918-11ea-9084-418324c0ce63.png)

## Environment

**Statamic version:** 3.0.0-beta.23

**Install method:**
- Starter kit (Cool Writings)

**PHP version:** 7.4.4

**Operating System:**
- Linux (debian)

**Browser:**
- Chrome 80.0.3987.149 (Official Build) (64-bit)

**Comment by jackmcdade** [comment]
Note to self: this is fixed in the `SelectFieldtype` but needs to be carried over to the `TagFieldtype`.

**Comment by jackmcdade** [comment]
Fixed in 277fc97710b07ac3ba163295139955c49fc22d4f.
