### ISSUE TITLE
Add support for paste events on Tag fieldtype

### ISSUE THREAD

**Issue by ramimassoud** [statamic/cms#1649]
## Bug Description

Per the [docs](https://statamic.dev/fieldtypes/tags):
> You can press `enter`, `tab`, or `,` to add a tag, navigate through tags with your arrow keys; use `backspace` or click the `x` to delete tags, and drag and drop tags to rearrange them. That’s all there is to it.

Pressing enter works, but `tab`  and `,` do not convert the text into tags. Similarly, if you paste a comma-separated list into the field, they do not convert into tags.

In this state, saving will seem to succeed but the values are not added to the file

## How to Reproduce

Enter in text and add a `,` or hit tab

OR

Paste a comma-separated list into the field

## Expected Behavior

The text converts into tags and is saved to the file.

## Screenshot/Exception

![image](https://user-images.githubusercontent.com/374033/78736097-562b2480-791a-11ea-9f61-f2d187bf7b35.png)

## Environment

**Statamic version:** 3.0.0-beta.23

**Install method:**
- Starter kit (Cool Writings)

**PHP version:** 7.4.4

**Operating System:**
- Linux (debian)

**Browser:**
- Chrome 80.0.3987.149 (Official Build) (64-bit)

**Comment by jackmcdade** [comment]
Fixed the `,` and `tab` events in 277fc97710b07ac3ba163295139955c49fc22d4f but won't be able to support pasting comma delimited strings until [vue-select](https://github.com/sagalbot/vue-select) has a `paste` event. It's been an [open issue](https://github.com/sagalbot/vue-select/issues/974) since October.

**Comment by ramimassoud** [comment]
Thanks Jack!!

**Comment by ramimassoud** [comment]
I think this is still an issue since the Vue issue is still open?

**Comment by jackmcdade** [comment]
Yeah I would assume so. Bummer!

**Comment by jackmcdade** [comment]
Still no movement on Vue Select. Opened a new, smaller feature request so we can try to work this out. 

https://github.com/sagalbot/vue-select/issues/1453
