### ISSUE TITLE
Form emails dynamic recipient

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/cms#1651]
## Bug Description
When using the CP to enter an email tag, system validates with "must be a valid email address" message. I am able to use an email tag in the config file, but it doesn't appear to be sending the email on form submit. Goal is to send a copy of the form submission to the user using their entered email address.

## How to Reproduce
Here's how I can recreate the bug:
1. Set up new email for a form
2. Enter a tag name from the form (in this case {{ applicant_email_address }}
3. Attempt to save email template.

## Expected Behavior
Have used this before in v2, so expect a copy of the submission email to send to the user. 

## Screenshot/Exception
<img width="926" alt="Screen Shot 2020-04-08 at 12 19 56 PM" src="https://user-images.githubusercontent.com/50339975/78820219-a6df6380-7994-11ea-9e88-1a424ccad0bc.png">

## Environment

**Statamic version:** 3.0.0.-beta-23
_run `php please -V` to find it._

**Install method:**
- Existing Laravel app

**PHP version:** 7.2
_run `php -v` to find it_

**Operating System:**
- MacOS

**Browser:**
- Chrome
- Brave

**Comment by jackmcdade** [comment]
This isn't so much a bug as it is just not supported at the moment. It's on the list though :)

**Comment by jackmcdade** [comment]
We should be able to use a var in any of the email address fields here.

**Comment by jesseleite** [comment]
Fixed in e57a0b9db1be50e95f0329e8bd140d0687db687b 👍
