### ISSUE TITLE
Fixed Bard Toolbar has wrong top position

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1652]
## Bug Description
The toolbar is displayed in the Live Preview as expected but in the main view of an entry, the toolbar is displayed below the header. This could be related to the fix from the ticket: #1503 

## How to Reproduce
Here's how I can recreate the bug:
1. Make sure that the `toolbar_mode` is `fixed`
2. Go to the main view of an entry
3. Scroll the page until the toolbar should stop at the top
4. Toolbar is behind the header

## Expected Behavior
Toolbar is displayed correctly in the main view and in the Live Preview

## Environment

**Statamic version:** 2c0592ac093e3389606ae3258a481e18c90be9bc

**PHP version:** 7.3.14

**Operating System:**
- MacOS

**Browser:**
- Chrome

**Comment by sauerbraten** [comment]
The reason why `top: 0;` works in the live preview view is that `.live-preview-fields` has `position: relative;`. That element is only present in the live preview DOM, so the offset of the toolbar has a different containing block in the normal view.

**Comment by WiebkeVog** [comment]
With this fix the toolbar in the Live Preview is broken again.

<img width="596" alt="76765578-e8fef600-6796-11ea-9db4-11684abec3bc" src="https://user-images.githubusercontent.com/54707973/79310227-e14c8180-7efb-11ea-94bc-bde727318459.png">

**Comment by sauerbraten** [comment]
Here's a diff that fixes this for us in all three cases: default, live preview, fullscreen.

https://pastebin.com/dasWaLfu

Since we patched an old Statamic revision with this, it includes your 4901862.

**Comment by jackmcdade** [comment]
Fixed, thanks for the heads up.
