### ISSUE TITLE
Conditionals inside replicator fields are not working

### ISSUE THREAD

**Issue by sebabal** [statamic/cms#1656]
## Bug Description
Conditionals inside replicator field is not working. I managed to quickly debug the Parser and it seems the variable from the condition is set to null.

Everything seems fine until the line 827 at the Parser.php when the condition is passed through the callback "processConditionVar" after that the condition variable is set to "null"

## How to Reproduce
Here's how I can recreate the bug:
- Create a replicator field
- Within a template try to use a conditional while looping through the replicator eg: {{ if index == 2}} Output Something {{ /if }}

## Expected Behavior
I expect to output something if the condition is met

## Environment

**Statamic version:** 3.0.0.-beta-23

**PHP version:** 7.2.4

**Operating System:**
- Windows

**Browser:**
- Chrome

**Comment by jackmcdade** [comment]
This should be fixed on ‘master’ already :)
