### ISSUE TITLE
Move assets action is giving an error

### ISSUE THREAD

**Issue by sebabal** [statamic/cms#1660]
## Bug Description
Whenever you try to move an asset from the "Asset" section the UI just keep waiting for the action to finish. 

The browser console shows the following error:

```javascript
vue.common.prod.js:6 TypeError: Cannot read property 'uncheckAllItems' of undefined
    at a.bulkActionsCompleted (Browser.vue:423)
    at Re (vue.common.prod.js:6)
    at a.n (vue.common.prod.js:6)
    at Re (vue.common.prod.js:6)
    at a.e.$emit (vue.common.prod.js:6)
    at Actions.vue:38
````

**Note:** The action seems to work since the asset is moved properly. By looking at the error it seems to be related to the check and uncheck action so it might be happening for other type of operations.

## How to Reproduce

1. Go to Assets
2. Try to move a file to another directory.

## Environment

**Statamic version:** 3.0.0.-beta-23

**PHP version:** 7.2.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Fixed on `master` :) Build coming soon.
