### ISSUE TITLE
Upload file limit size and aws s3 - allowUploads() on null

### ISSUE THREAD

**Issue by icemancast** [statamic/cms#1663]
## Bug Description

Last week I encountered an issue when uploading to s3 we would get the error below. The description of the error was not helpful. However I did find the fix to be the upload file limit size on the server. After upping that value I had no issues. Just strange that that would effect sending to s3, maybe it was a the temporary file before moving, not sure. Would be nice to have a file limit error instead I would think.

[2020-04-05 00:50:15] production.ERROR: Call to a member function allowUploads() on null {"userId":"6631af6b-dddb-45c9-bf35-1c5fd6331d7d","exception":"[object] (Symfony\Component\Debug\Exception\FatalThrowableError(code: 0): Call to a member function allowUploads() on null at /home/forge/domain.com/vendor/statamic/cms/src/Http/Controllers/CP/Assets/AssetsController.php:71) [stacktrace]

## How to Reproduce

Use aws s3 as an upload as your file driver and lower the upload file size to 2M.

## Extra Detail
Original forum post here: https://statamic.com/forum/4584-upload-error-on-v3-intermittently

## Environment

**Statamic version:** 3.0.0.-beta-22

**PHP version:** 7.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by martink635** [comment]
I have the same issue when using the "Upload file" link on assets. Everything else (using the Asset manager, drag & drop) work fine.

**Comment by marflow** [comment]
Same issue here using an asset field and local storage. I get "Call to a member function allowUploads() on null" for a larger file (+ around 2 MB) and if I try to upload several small files (around 80 KB). Max filesize is 128M and max files for the field is 16.

**Comment by johncarter-** [comment]
Related #1523 

If anyone else is struggling with this you should try adding/updating the `container` config on the asset field. 

In the control panel field config:

![image](https://user-images.githubusercontent.com/3776888/85123299-ed1c3300-b21f-11ea-9f73-e53d5723cee8.png)

Or , in the field blueprint `yaml` file:

![image](https://user-images.githubusercontent.com/3776888/85123359-0a510180-b220-11ea-877d-25d678835e52.png)

**Comment by icemancast** [comment]
Team this can be closed. @johncarter- suggestion was the fix in my case. I had an older version of statamic and on an upgrade somehow that got disconnected.
