### ISSUE TITLE
Colin syntax for collection tag broken

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#1664]
## Bug Description

Using the colin syntax the from in the collection tag does not work:
`{{ collection :from='related_collection' }}`

However using the non colin syntax works:
`{{ collection from='{related_collection}' }}`

## How to Reproduce

Relate a collection and try to template it using the collection tag.

## Environment

**Statamic version:** 3.0.0.-beta-24

**PHP version:** 7.4.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Fixed in e2b21e9c16678aa89f37a78e7c2b5882e69740d5
