### ISSUE TITLE
Redirect Failing with Page-Level Variable

### ISSUE THREAD

**Issue by danpaquette** [statamic/cms#1672]
## Bug Description
Redirect failing when referencing page-level variable for redirect url.

## How to Reproduce

Add a `redirect_location` field to a page.
https://imgur.com/99wmCZS

Attempt to use that variable to initiate a redirect in a template.
`{{ if redirect_location }}{{ redirect url="{redirect_location}" }}{{ /if }}`

See error.
https://imgur.com/usBkUS8

## Environment

**Statamic version:** 3.0.0.-beta-23

**PHP version:** 7.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
