### ISSUE TITLE
No path shown when moving assets

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1673]
When you move assets, the selected path is not shown, after selecting it.

![image](https://user-images.githubusercontent.com/3351449/79157904-b5cf7700-7dd5-11ea-90a3-8e6970cffe07.png)
![image](https://user-images.githubusercontent.com/3351449/79157937-c08a0c00-7dd5-11ea-8e43-3624350e3610.png)

Beta 24

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
