### ISSUE TITLE
Error after selecting assets and cancel

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1675]
1. Select assets
2. Click cancel in the assets browser
3. Click save for the entry

Error:
![image](https://user-images.githubusercontent.com/3351449/79159387-45762500-7dd8-11ea-8d84-98666d1a9b1f.png)

**Comment by jasonvarga** [comment]
I cannot recreate this issue by following the provided steps.

If I have a "required" validation rule on this field, then I do see it, but that's what I'd expect if I selected nothing.
