### ISSUE TITLE
Field called "url" is overriden in Content API

### ISSUE THREAD

**Issue by philsturgeon** [statamic/cms#1676]
## Bug Description

Any field called `url` will be overriden in the Content API and it'll just have a value of `"/action"`.

Notice here how url is "/actions" 

<img width="585" alt="image" src="https://user-images.githubusercontent.com/67381/79161589-a4856b00-7dd3-11ea-9cc0-3b70fff3ec66.png">

but here it's to a third party website.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/67381/79161574-9f282080-7dd3-11ea-98fb-a10084ef04b3.png">

## Extra Detail

Make a blueprint field called url, add entry to the collection, and its not showing up.

## Environment

**Statamic version:** 3.0.0.-beta-20

**PHP version:** 7.4

**Comment by jasonvarga** [comment]
We need to be better about documenting these sort of things, and/or have validation preventing you from naming the field that way, but I would definitely consider `url` a reserved word.

**Comment by philsturgeon** [comment]
Thought that might be the case, but if the UI lets me do it that's the bug. :)

**Comment by jasonvarga** [comment]
Yup. Not moving this one to feature requests.

**Comment by philsturgeon** [comment]
I think "slug" and "content" are similar. I have been populating my own "slug" and "body" and the API looks a little confused: 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/67381/79258856-ab6bb680-7e83-11ea-9561-9fda5ecf65b1.png">

I'd love to do things the right way. Any tips on how I can get back to doing things properly?

**Comment by jasonvarga** [comment]
The `slug` just comes from the filename. `content/collections/mycollection/{slug}.md`

The `content` field, hmm, yeah it's a little special. The content bit of your markdown file is your content field.

```
---
your: front
matter: here
---
anything here is considered `content`
```

- If you only have front-matter, you get an empty content field.
- If you have no `---` fences (so it looks like a yaml file) you won't get a content field. 

If it's bothering you, you could:
- rename the `body` field to `content` (you can leave it in the front-matter)
- remove the fences (but saving in the CP will just bring them back)
