### ISSUE TITLE
Collection no longer accesses view model 

### ISSUE THREAD

**Issue by forby** [statamic/cms#1678]
## Bug Description

This could totally be my error, but I have been using a view model on a collection to process data before it gets to the view. After recently doing some upgrades, I noticed that the view model is no longer seen in the view after upgrading from beta-14 to beta-15 (and beyond). I tried clearing the cache, maybe I just need to implement the view model differently? 🤷‍♂️

## How to Reproduce

I have a `projects.yaml` collection with the view model injected (as mentioned [here](https://github.com/statamic/cms/issues/1103#issuecomment-566561532)):
```yaml
inject:
  view_model: App\ViewModels\Project
```

And in `/app/ViewModels/Project.php` nothing works, not something simple like:
```php
<?php

namespace App\ViewModels;

use Statamic\View\ViewModel;

class Project extends ViewModel
{
    public function data(): array
    {
        return [
            'foo' => 'bar'
        ];
    }
}
```

The data is merged with the view data in b-14, no longer after b-15. I couldn't `dd()` from the view model either, it didn't seem to be accessed at all.

## Environment

**Statamic version:** 3.0.0.-beta-15

**PHP version:** 7.3.16

**Install method (choose one):**
- Fresh install from `statamic/cms`

**Comment by MattRogowski** [comment]
I also have this issue on beta 26. They only seem to run when attached directly to an entry, not a collection. The docs do say "in your entry data or anywhere in the cascade" so imagine this should include the collections, and makes more sense to attach them there than individual entries.

**Comment by jasonvarga** [comment]
In the middle of fixing this today.

**Comment by MattRogowski** [comment]
Just saw https://github.com/statamic/cms/issues/1103 - do we just need to place under "inject" instead?

**Comment by jasonvarga** [comment]
You do, but that's not working.

**Comment by aerni** [comment]
This issue still persists on beta 36. Did the fix ever make into a release?

**Comment by jasonvarga** [comment]
Seems fine to me. Do you have the view model under `inject`?

**Comment by MattRogowski** [comment]
Can confirm this was fixed as I've used it extensively since - syntax for including it in your collection `yaml` file:

```
inject:
  view_model: App\ViewModels\Events
```

**Comment by aerni** [comment]
Just tried it again on and it works now. No idea what I was doing wrong before. 😅
