### ISSUE TITLE
Data not passed into partial

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1680]
##  Bug Description
Data is not being passed into a partial

## How to Reproduce
I have a page with a template: 
```
<main class="relative">
  {{ partial:page_heading }}
  {{ partial:levels/tabs :collection="slug" }}
  {{ partial:activities/entries :collection="slug" }}
</main>
```

In the `entries` partial I have this and it works:
```
    {{ collection :from="collection" }}
      <li class="flex flex-1">
        {{ partial:activities/card }}
      </li>
    {{ /collection }}
```
(I don't use `entries` tag there because of a separate bug which I'll add in a bit)

In the `tabs` partial I have this:
```
  {{ taxonomy:levels :collection="collection" }}
    <a href="{{ url }}" class="{{ if !first }}ml-1 md:ml-3{{/if}} relative px-6 py-4 text-sm md:text-base" rel="tag" {{ if level == slug }}style="color: {{ color }}"{{/if}}>
      {{ if level == slug }}{{ svg:circled class="absolute inset-0 w-full h-full fill-current" }}{{/if}}
      {{ title }}
    </a>
  {{ /taxonomy:levels }}
```

But it doesn't work and if I print out `collection` on that page it's blank. I've tried passing in a variable not named `collection` and tried passing in hard coded data, none of which work. The taxonomy tag **does** work if I hard code the value so it's not a taxonomy thing.

## Environment

**Statamic version:** 3.0.0.-beta-24

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by edalzell** [comment]
I can invite to repo if that will help (in fact Jack has access already).

**Comment by jasonvarga** [comment]
Sounds like the activities/entries partial might be the issue, if it's working in the levels/tabs partial. What else is in it?

**Comment by edalzell** [comment]
nothing else is in it.

**Comment by edalzell** [comment]
oh and you have it backwards @jasonvarga it's working in `entries` NOT in `tabs`

**Comment by jasonvarga** [comment]
Oops yeah. Backwards.

So for sure if you plop {{ the_variable }} in the partial, nothing is output?

**Comment by edalzell** [comment]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/6069653/79253351-e647fd00-7e37-11ea-98cc-2c18cc822e37.png">

<img width="614" alt="image" src="https://user-images.githubusercontent.com/6069653/79253330-de885880-7e37-11ea-942b-e3b9cd9a9bd6.png">

**Comment by jasonvarga** [comment]
Does it get output in the other partial?

**Comment by edalzell** [comment]
oh no it doesn't, it must be working in that one for another reason.

**Comment by jasonvarga** [comment]
What is {{ slug }} in the parent view?

**Comment by edalzell** [comment]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/6069653/79253783-a2a1c300-7e38-11ea-97d3-6b8045aac251.png">

<img width="549" alt="image" src="https://user-images.githubusercontent.com/6069653/79253808-aa616780-7e38-11ea-8e89-aac26a400715.png">

**Comment by edalzell** [comment]
It would also be amazing if the taxonomy tag worked properly w/o passing that info in, taking it instead from the mounted collection.

**Comment by mikemartin** [comment]
@edalzell I just had a look at this and it looks like the partial wasn't an antlers template. It was named `levels/tabs.html`. 🤦 

Is it possible to add better error handling for this?

**Comment by jasonvarga** [comment]
Ah it's not really an error then. Closing in favor of #1179
