### ISSUE TITLE
The Replicator field UI breaks when adding a new Set

### ISSUE THREAD

**Issue by FR6** [statamic/cms#1685]
## Bug Description

The Replicator field UI breaks when adding a new Set.

## How to Reproduce

- Create a blueprint
- Add a Replicator field
- Add a Set
- Add a field
- Save blueprint
- Create content associated to this blueprint
- Add a Set
- UI will be broken

## Extra Detail
![image](https://user-images.githubusercontent.com/286685/79344553-fcb88c00-7efd-11ea-994d-0aa7e9178c0c.png)

## Environment

Statamic version: v3.0.0-beta.26
Brower: Firefox and Chrome
OS: Windows 10
PHP version: 7.3.11

**Install method:**
- Existing Laravel app

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
