### ISSUE TITLE
CP: Configure Asset Container → Wrong instruction text

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1686]
## Bug Description
In the 'Configure Asset Container' panel is a wrong instruction text for the toggle 'Allow Uploads' in the settings section.

<img width="952" alt="Bildschirmfoto 2020-04-15 um 16 05 22" src="https://user-images.githubusercontent.com/8265902/79346993-5b4c2d00-7f33-11ea-96c2-7bed51e31c3a.png">

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.4.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ebeauchamps** [comment]
Up
