### ISSUE TITLE
Front matter in antlers not read

### ISSUE THREAD

**Issue by nerdroid23** [statamic/cms#1689]
## Bug Description
I'm trying to use front matter inside of an antlers template but I am unable to. Instead of being parsed it is being printed as if it's plain text.

## How to Reproduce
I'm not quite sure but I would assume that using front matter in an antlers template?

## Extra Detail

![image](https://user-images.githubusercontent.com/21242932/79431086-8f553b80-7f8f-11ea-9376-7fba4863db03.png)

## Environment
Windows 10
Apache 2.4.41

**Statamic version:** 3.0.0.-beta

**PHP version:** 7.4.2

**Install method (choose one):**
Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
What's the filename of your template? Does it end with `.html` or `.antlers.html`?

**Comment by nerdroid23** [comment]
`home.antlers.html`, it's the one that comes by default

**Comment by nerdroid23** [comment]
Well, I just went back to the project and see if I could find where I went wrong and possibly find more info and add them here... And it is now working as expected, for some reason. I didn't make a single change. 😅

I think this can be closed now

**Comment by jackmcdade** [comment]
Ok! If you find it again just let us know :)
