### ISSUE TITLE
Ternary fails

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#1690]
## Bug Description
I am trying to set a class using Ternary. It outputs nothing.

## How to Reproduce

1. Add a replicator
2. Add Toggle fieldtype to a set, use the key ; long_read
3. See images how i have structured the partials. 
4. Trying to set a class using Ternary, doesn't work ( `{{ long_read ? "c-long-read":"" }}` )
5. To get it to work, i have to write `<section class="hide-it {{ if long_read }} c-long-read {{ /if }}">`

## Extra Detail
<img width="895" alt="Screenshot 2020-04-16 at 14 56 42" src="https://user-images.githubusercontent.com/31292231/79458717-8184d200-7ff2-11ea-8c3a-3f18962ffc0b.png">

<img width="886" alt="Screenshot 2020-04-16 at 14 54 53" src="https://user-images.githubusercontent.com/31292231/79458566-45ea0800-7ff2-11ea-9a9b-338085faabd5.png">

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.3.16

**Comment by jackmcdade** [comment]
Ah, I believe you need to have a space around the colon. Give this a shot:

```
{{ long_read ? "c-long-read" : "" }}
```

Also, if you only want to set a value if a var is truthy, you can also do this:
```
{{ long_read ??= "c-long-read" }}
```

**Comment by Pixney-William** [comment]
Yes! Thanks — The spacing did it!
