### ISSUE TITLE
No depth variable in nav tag

### ISSUE THREAD

**Issue by AndersMFJ** [statamic/cms#1691]
## Bug Description
When using the nav tag to build a navigation there should be a depth variable (as specified in the documentation: https://statamic.dev/tags/nav#parameters) which indicates the depth of the entry in the structure. But {{ depth }} gives no output and if I use {{ dump }} there is no depth variable in the dump. 

## How to Reproduce

Pages is a structured collection with a hierarchy of pages. {{ depth }} gives no output
```
   {{ nav:collection:pages from="/{segment_1}" max_depth="2" }}
      <li>
         <a href="{{ url }}"{{ if is_current || is_parent }} class="on"{{ /if }}>{{ title }} - {{ depth }}</a>
         {{ if is_current || is_parent }}
            {{ if children }}
               <ul>{{ *recursive children* }}</ul>
            {{ /if }}
         {{ /if }}
      </li>
   {{ /nav:collection:pages }}
```
## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.4.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jesseleite** [comment]
Fixed in https://github.com/statamic/cms/issues/1691 👍
