### ISSUE TITLE
Cannot get siblings of current entry

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#1692]
## Bug Description
I am trying to output a list of siblings, i.e. they share the same parent as the current entry.

## How to Reproduce
 - Create a collection (in my case 'products') that can be reordered and hold nested entries. 
 - Create a parent entry.
 - Create 2 entries as children of that entry.
 - Create a template and try and get the siblings.

N.B. It may be relevant that the route is `products/{slug}` **not** `products/{parent_uri}/{slug}`

I am really new to Antlers, but I tried a few ways:

```
{{ nav:products from="{parent:url}" }}
{{ url }}
{{ /nav:products }}
```

```
{{ nav:products from="{parent:url}" }}
{{ children }}
{{ url }}
{{ /children }}
{{ /nav:products }}
```

And finally:
```
{{ collection:products parent:is="parent" }}
{{ url }}
{{ /collection:products }}
````

None of those options get the siblings.

## Environment

**Statamic version:** 3.0.0.-beta-26
**PHP version:** 7.3
**Install method:** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
You can use the `uri:starts_with` condition and add a slash.

```
{{ collection:products uri:starts_with="{parent:uri}/" }}
```

That'll match `/products/something` but not `/products`.
