### ISSUE TITLE
Plural text in language *.json file is not used for a `de-CH` translation (or for language codes with more than 2 characters?)

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1695]
## Bug Description
I am working on a `de-CH` translation. I found out, that every plural version in the *.json file does not get picked in the CP, when more than 1 item is selected. This could be…

```
":count item selected|:count items selected": ":count Eintrag ausgewählt|:count Einträge ausgewählt",
or
"Are you sure you want to publish this entry?|Are you sure you want to publish these :count entries?": "Willst du diesen Eintrag wirklich veröffentlichen?|Willst du diese :count Einträge wirklich veröffentlichen?",
```

…always the singular form will be used.

After testing I guess, it has to do something with the language code `de-CH`? When I use the same *.json file, but use it as `de.json` (change locale in app.php too), the plural version will be used.

<img width="544" alt="Bildschirmfoto 2020-04-16 um 23 09 42" src="https://user-images.githubusercontent.com/8265902/79510335-7dca6d00-803d-11ea-8b04-ccddfcc5f2ba.png">

It should be 'Einträge' instead of 'Eintrag'.

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.4.2

**Install method (choose one):**
- Fresh install from `statamic/statamic` (I put the language files in `/vendor/statamic/cms…` or in `resources/lang`, that does not make a difference.)

**Comment by ebeauchamps** [comment]
Nice catch!

**Comment by jasonvarga** [comment]
Thank you for working out that `de` worked but not `de-CH`. That was helpful in tracking down the issue. 🎉
