### ISSUE TITLE
Submission dates are displayed incorrectly at the "Forms" section

### ISSUE THREAD

**Issue by sebabal** [statamic/cms#1706]
## Bug Description
The hour shown at the submission table screen seems to be wrong, they all display the same hour although the timestamp of the filename is different for each submission.

![image](https://user-images.githubusercontent.com/210946/79621070-6dbb9780-80e8-11ea-9ddb-f8e0ed02dd01.png)

## How to Reproduce
Submit a form, check the submission screen

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by MattRogowski** [comment]
Can confirm this, presuming it's using the `m` date formatter instead of `i` so it's month `04`?

**Comment by jasonvarga** [comment]
@sebabal You say they're all the same hour. Do you mean they're all the same minute?

Looking at the format in the code, the hour part seems correct.

**Comment by sebabal** [comment]
Yeah my bad, they all have the same time, in these case to the minute. But they were submitted minutes apart.

**Comment by jasonvarga** [comment]
Thanks for confirming 👍

**Comment by jasonvarga** [comment]
Fixed by #1779
