### ISSUE TITLE
Order of addons matter, but shouldn't. Affects routing.

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1708]
## Bug Description

Addons that come after Statamic alphabetically do not get their CP routes loaded.
The Statamic provider loads the routes, and inside of that it loads any addon's pushed CP routes.
If the addon comes after Statamic, it missed its chance to load the route.

## How to Reproduce

Have an addon with a namespace after Statamic, alphabetically.
Attempt to load CP routes.

## Environment

**Statamic version:** 3.0.0-beta.26
**PHP version:** 7.4

**Comment by davidsneal** [comment]
Just a note from my experience of this issue: it didn't appear to be the namespace for me, rather the vendor name of the package repo itself.

**Comment by davidsneal** [comment]
So the github org name is `weremagine`, but the namespace I have is `Remagine`

**Comment by davidsneal** [comment]
@jasonvarga I just tested adding an `a` to the package vendor to `aweremagine` and that works no problems, so I do believe it's that part that causes the issue.

**Comment by jasonvarga** [comment]
Thanks for confirming 👍
