### ISSUE TITLE
Childs in nav are not all rendered correctly

### ISSUE THREAD

**Issue by dwainscheeren** [statamic/cms#1710]
## Bug Description
When having some child page's and try to load them with the `nav` tag gives an weird bug.

## How to Reproduce
![](http://puu.sh/FA0Ji/e1ca97359f.png)
```
{{ nav depth="2" }}
                    <li class="pb-1">
                        <a href="{{ url }}">{{ title }}</a>
                        {{ if children }}
                        <ul>
                        {{ children }}
                            {{ title }}
                        {{ /children }}
                        </ul>
                        {{ /if }}
                    </li>
                {{ /nav }}
```

## Extra Detail

It gives this: 
Tuin & Terras
Gevel
Rolluiken
Garagepoorten
tag_pair_661bc579f731bb8be88e32e61bb68e23
Raamdecoratie
tag_pair_661bc579f731bb8be88e32e61bb68e23

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.3

**Install method (choose one):**
- Starter kit

**Comment by jcohlmeyer** [comment]
I am also seeing the same issue on beta 27

**Comment by jcohlmeyer** [comment]
I found a workaround, if you put the `{{ children }}` loops in a partial it works.

**Comment by jasonvarga** [comment]
We fixed a tag_pair_garbage issue on master. This might also be fixed.

**Comment by dwainscheeren** [comment]
This is indeed fixed now in beta 28. Thanks.
