### ISSUE TITLE
Grid-Field: layout of subfields lost when dragged around

### ISSUE THREAD

**Issue by tubsn** [statamic/cms#1715]
## Bug Description
When using multiple layouted fields (eg. two elements with 50% width) in a Grid-Fieldtype, set to stacked Mode, the fields loose their CSS layout, when the surrounding grid container is being dragged around via drag&drop. This effect does not happen with other fieldtypes that can be dragged for example replicators.

![Grids loose Layout Image](https://www.artmessengers.de/stuff/grid-element-losing-layout.png)

## How to Reproduce
Dragging one of multiple grid elements around.

## Environment
Windows10, Firefox 75

**Statamic version:** 3.0.0.-beta-{23}

**PHP version:** 7.3.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I'm unable to replicate this issue on a fresh Statamic install so I'm going to close this issue for now.

If you're still encountering this issue on the latest release, please comment on here with your blueprint so I can replicate and re-open this issue.
