### ISSUE TITLE
taxonomy="true" parameter at "Collection" tag is not working

### ISSUE THREAD

**Issue by sebabal** [statamic/cms#1716]
## Bug Description

Getting a 

`Call to a member function collections() on null`

when setting the taxonomy="true" parameter.

eg `{{ collection:insights 
						limit="9" 
						as="posts" 
						taxonomy="true"
					}} stuff {{ /collection:insights }}`

Perhaps this is related to #1350 ??

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ebeauchamps** [comment]
I am pretty sure taxonomy="true" isn't a thing anymore in V3. Did you check the docs?

**Comment by jasonvarga** [comment]
Correct. Not a thing anymore. Instead, on the dedicated term url, the entries are automatically available for you. https://statamic.dev/taxonomies#listing-term-entries

**Comment by sebabal** [comment]
Ah ok thanks, so I guess I need to use different tags depending on the context, is there any documentation regarding this {{ entries }} tag I see it supports pagination does it support the rest of the stuff like sorting, etc. I haven't found anything related to this tag on the docs....
