### ISSUE TITLE
Can't change handle of navigation

### ISSUE THREAD

**Issue by jmartsch** [statamic/cms#1719]
## Bug Description
When I change the handle of a navigation and save it, a success message "Saved" appears. When I reload the page, the handle hasn't changed.

## How to Reproduce
- Create a navigation and give it a handle
- Save
- Change the handle
- Save
- Reload

## Extra Detail

![image](https://user-images.githubusercontent.com/551551/79996720-0bccaa80-84b9-11ea-8950-de44f1829c36.png)

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.3

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
Closing this in favor of #1959
