### ISSUE TITLE
Possible incompatibility with Telescope

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#1721]
## Bug Description
When installing Telescope if you have a cached config file, the following error is thrown:

```
InvalidArgumentException 
Driver [statamic] is not supported.
```

![image](https://user-images.githubusercontent.com/545339/80015145-3aeb1800-84c9-11ea-9dad-f3a70c9ce6e0.png)

I haven't changed any of the drivers from a default installation, other than the queue driver to use redis.

No idea if this is an issue with Statamic or Telescope, so feel free to close if it's not your problem.

## How to Reproduce
Install Laravel Telescope
Cache your config file with `php artisan config:cache`
The whole application will error
The only way to then fix is to set `TELESCOPE_ENABLED=false` in your `.env` file and then run `rm bootstrap/cache/config.php` followed by another `php artisan config:cache`

## Environment

**Statamic version:** 3.0.0-beta.26
**PHP version:** 7.4.2
**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by dannylepage** [comment]
Hi @MattRogowski were you ever able to resolve this problem?

**Comment by MattRogowski** [comment]
@dannylepage Still seems to happen on the latest build for me, I just disabled config caching in the end.

**Comment by dellow** [comment]
Also seeing this issue.

**Comment by jasonvarga** [comment]
You shouldn't be caching your config locally. Avoid caching your config is the solution here.

**Comment by roelofr** [comment]
I'm seeing this error too on my production environment when I have the caching method set to `file` (Redis or other memory-based caches are not an option). This is not just for local dev but it also blocks the `php artisan optimize` command.

Debug info:

```
Statamic 3.0.14 Pro
Laravel 7.28.3
PHP 7.4.8
```

**Comment by aimensasi** [comment]
Any updates on this. I need to cache the config for optimization on production and the issue still persist.

**Comment by jasonvarga** [comment]
Telescope is a development tool. We're not going to dedicate time to working on making it work in production.
If you can figure it out, we'd happily accept a pull request.

If I was to guess at a solution, I might try disabling the auto-discovery and manually register the telescope provider as per the instructions here. https://laravel.com/docs/8.x/telescope#local-only-installation
Seems like the issue is that it gets wired up before Statamic.

**Comment by jasonvarga** [comment]
Actually now that I've said I wouldn't spend time on it, I think I've found a solution. 😆
