### ISSUE TITLE
Slow page load when you have lots of collection content

### ISSUE THREAD

**Issue by tao** [statamic/cms#1723]
## Bug Description
I'm testing Statamic 3 on a new project which a journal that goes back to around 2005 so it's about 15 years or 5000 entries, as they wrote a new journal entry each day. Statamic is struggling to load pages and each request can take around 50s sometimes. I can get the page load down to a few seconds (but still a noticeable delay) if I use a $50 pro server on Heroku, however I'd like to avoid that if possible.

I am also interested in using the Statamic static site generator to create a static version later which I can host without the long page load, however it's still missing support for pagination so I won't be able to use it on our journal entries for now. The other issue is that the CMS is also slow to load (~15s) with lots of content but not as bad as the website pages.

## How to Reproduce
[Here](https://github.com/tao/statamic-slow-runnings) you can find a fork of `cool-writings` with enough content to test the problem.

I've also added another ~5000 articles in the `/collections/additional` folder if you want to test with up to 10,000 entries, but I'm unable to get the application to load at that point.

You may also have to warm up the stache first, or refresh the page a few times (to get the cache to load?) as it times out a couple of times before starts rendering the website.

## Extra Detail
![Screenshot 2020-04-22 at 23 51 56](https://user-images.githubusercontent.com/1446331/80041850-6d126f00-84f5-11ea-96be-59f1076ba14a.png)
## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.3.17

**Install method (choose one):**
- Cool Writings Starter kit

**Comment by jasonvarga** [comment]
slow-runnings lol

woulda gone with cool walkings personally

**Comment by jasonvarga** [comment]
Pulled the repo down. Yup. Definitely slow.

If you disable the file watcher, you should see a dramatic increase.
Change this to `false`: https://github.com/tao/statamic-slow-runnings/blob/master/config/statamic/stache.php#L18

Another bump in performance comes when you disable the debug bar, but you probably don't have that running on production anyway.

**Comment by tao** [comment]
Great, disabling the file watcher actually does help a lot in this case. It struggles on the first page load (~39s) as I assume it's building the stache... then the pages loads are around ~1.5s to load the articles in the pagination pages.

**Comment by jasonvarga** [comment]
I'm getting about 500-600ms here, but sure, it depends on the server. Definitely better than 50 seconds.

The initial load is always going to be long, especially with that much content. It's gotta index everything. You can reduce the initial load by running `php please stache:warm`, a great idea to throw into your deploy script. Then that first page load won't have to do any work.

Disabling the watcher has such a big jump in performance because it was looking through all your 10,000+ content files every request to check if they've changed.
