### ISSUE TITLE
Assets in Markdown fieldtype shouldn't use absolute URLs

### ISSUE THREAD

**Issue by dipsy** [statamic/cms#1726]
Stamatic last beta

```
namespace Statamic\Http\Resources\CP\Assets;

use Illuminate\Http\Resources\Json\JsonResource;
use Statamic\Facades\Action;
use Statamic\Support\Str;

class Asset extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id(),
            'path' => $this->path(),
            'filename' => $this->filename(),
            'basename' => $this->basename(),
            'url' => $this->absoluteUrl(),
```
absoluteUrl() is generating absolute url when I insert asset in editor. Absolute url is bad, because it hardcode to development env (like  http://localhost:8888/assets/image_1.JPG). Changing APP_URL doesn't matter for render.

I check $this->url() works good for local assets. But I think It will be problem for external storage.

**Comment by jackmcdade** [comment]
Which editor are you referring to? Markdown or Bard?

**Comment by dipsy** [comment]
Like that:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/1336665/80129440-bae3b180-859f-11ea-9c57-d5266c14c5e3.png">

**Comment by jackmcdade** [comment]
Markdown. Got it.
