### ISSUE TITLE
Collection:next tag does not work with orderable but works with dates.

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#1731]
## Bug Description
The collection:next tag throws an error saying `collection:next requires ordered or dated collection` when used with a orderable collection.

In **namespace Statamic\Tags\Collection** line 74 we got:

`if ($collection->orderable() && $primaryOrderBy->sort === 'order') {`

orderable() returns false if you haven't defined a max-depth in your collection. 

**$primaryOrderBy->sort** returns date which might have been because i did try to enable publish dates to see if it worked with that setting (which it did). But if i toggle that off, it still returns date which means we can't hit this condition.

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.{3}

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
That’s intended behavior.

It’s only considered orderable if it has a max depth of 1.
