### ISSUE TITLE
Using offset on asset tag returns error

### ISSUE THREAD

**Issue by vitor-ao** [statamic/cms#1732]
## Bug Description
Using offset on assets  (e.g. `{{ assets offset="1" }}{{ url }}{{ /assets }}`) returns the error:
```
Facade\Ignition\Exceptions\ViewException
array_slice() expects parameter 1 to be array, object given 
```
## How to Reproduce
- Create an entry with an asset field and add more than one asset to it.
- On the template, add `offset=1` to the Asset tag to exclude the first asset.

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.3.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
