### ISSUE TITLE
Glide tag doesn't use secure setting

### ISSUE THREAD

**Issue by roelofr** [statamic/cms#1733]
## Bug Description

Since I'm running my site on a very light VPS, I'd love to keep image resize to a minimum. 

However, when I enable the `statamic.assets.secure` setting (in `config/statamic/assets.php`), the images won't load and a "Signature is missing" message is thrown.

## How to Reproduce

```html
{{ glide:url height="180" width="1920" }}
    <img src="{{ url }}" />
{{ /glide:url }}
```

**Expected result**: An `img`-tag with a `src` that has a valid Glide signature  
**Current result**: An `img`-tag with a `src` that has no Glide signature

## Extra Detail

- The `config/statamic/assets.php` entry `secure` needs to be `true`.

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.4.5

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
Can't recreate this. The `glide` tag is outputting a url with `s=longstring` in it.
If I change `secure` to `false`, it doesn't.

Anything else you can tell me about your setup?

**Comment by jasonvarga** [comment]
Hey there, we haven’t heard back on this for a while so I’m going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!

**Comment by roelofr** [comment]
Turns out, it was an issue caused by a combination of having `statamic.assets.image_manipulation.cache` and `statamic.assets.image_manipulation.secure` both set to true, but the `statamic.assets.image_manipulation.route` and `statamic.assets.image_manipulation.cache_path` not ending up pointing to the same directory.

It should've given a 404 (since the files didn't exist), but the route must've picked it up and figured the signature would've been invalid since the file was not found.

Making sure `statamic.assets.image_manipulation.route` and `statamic.assets.image_manipulation.cache_path` end up at the same folder, solved the issue.
