### ISSUE TITLE
Adding a redirect link to a collection prevents it from being rendered in a collection tag.

### ISSUE THREAD

**Issue by tao** [statamic/cms#1734]
##  Bug Description
In my website I have a collection of `books` and `volumes` and I want to show a global news feed of recent updates that shows when new volumes are added to my parent `books` collection. However, when someone tries to view a `volume` I want to redirect them to the parent `book` page and show all the content instead.

Another example could be a podcast that has many new episodes, I want to show a list of recent episodes in my news feed but when they click on an episode link I want to redirect to the main podcast page instead. 

After added the redirect link to a book in the `volumes` collection, it no longer shows up in the news feed on the website.

## How to Reproduce
[Here](https://github.com/tao/statamic-redirects) you can find a cool-writings demo where one of the articles ('The Magic Happens at 7 1/2 Pumps') has a redirect as follows:

```
redirect: 'entry::8e4b4e60-5dfb-47b0-a2d7-a904d64aeb80'
```

The article now no longer shows up in the demo website.

![Screenshot 2020-04-24 at 16 41 42](https://user-images.githubusercontent.com/1446331/80230932-84af3c00-864a-11ea-9710-898d1e688b91.png)

Is this an intentional design choice? I can understand how you might want to hide outdated content like an old product with a special offer and redirect it to a new product page when it's sold out, but in my case I want to include the content with redirects. If it's by design maybe a `show_redirect` option could be added to the collection tag? ... but I think if someone wanted to hide an old product page it would be better to unpublished that to hide it from the website.

## Extra Detail
The article does still show up in the Dashboard widget for recent updates.

![Screenshot 2020-04-24 at 16 42 17](https://user-images.githubusercontent.com/1446331/80230960-91339480-864a-11ea-8998-3cb280c36a29.png)

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.3.17

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
Add `redirects="true"` to your `collection` tag.

This is missing from the docs, I'll update it.
