### ISSUE TITLE
{{ locales }} fails when an entry doesn't have a version for all sites

### ISSUE THREAD

**Issue by remiduval** [statamic/cms#1735]
When displaying an entry that doesn't have a version for all sites/languages, using {{ locales }} will fail.
Works fine once all languages have been created for the entry.

config/statamic/sites.yaml
```
'sites' => [
        'french' => [
            'name' => 'French',
            'locale' => 'fr_FR',
            'url' => '/fr/',
        ],
        'english' => [
            'name' => 'English',
            'locale' => 'en_US',
            'url' => '/en/',
        ],
        'portuguese' => [
            'name' => 'Portuguese',
            'locale' => 'pt_PT',
            'url' => '/pt/',
        ]
    ]
```

views/templates/pages.antlers.html
```
    <article>
        <h1>{{ title }}</h1>
        {{ locales }}
        {{ url }}
        {{ /locales }}
    </article>
```

Error
![image](https://user-images.githubusercontent.com/5139658/80246960-948c4780-866d-11ea-887b-4e9bee243c60.png)

**Comment by jasonvarga** [comment]
Closing this in favor of #1224  which has much more activity.
