### ISSUE TITLE
API not returning entries inside a taxonomy

### ISSUE THREAD

**Issue by sebabal** [statamic/cms#1737]
## Bug Description
Trying to get all entries that belong to a taxonomy but "entries" object is empty. Eg:

```/api/taxonomies/categories/terms/how-to```

```javascript
{
  "data": {
    "title": "How To",
    "content": "",
    "slug": "how-to",
    "template": "insights",
    "updated_by": "f4ebcef9-b35f-40dd-8949-b0493595e9cc",
    "updated_at": 1587510080,
    "blueprint": {},
    "id": "categories::how-to",
    "uri": "/categories/how-to",
    "url": "/categories/how-to",
    "is_term": true,
    "entries": {},
    "entries_count": 28,
    "api_url": "http://localhost:8000/api/taxonomies/categories/terms/how-to",
    "taxonomy": {}
  }
}
```
The funny thing is that "entries_count" gives the correct value....

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
`entries` shouldn't have been in there. It's since been removed.

Instead, you should query the dedicated url (just added to master) that shows a term's entries, which would be `{term endpoint}/entries`.

eg. `/api/taxonomies/categories/terms/how-to/entries`
