### ISSUE TITLE
List users by group_id when using eloquent

### ISSUE THREAD

**Issue by tolawho** [statamic/cms#1739]
##  Bug Description

- Get a list users by group_id

## Extra Detail

![image](https://user-images.githubusercontent.com/12527881/80298149-2f545700-873e-11ea-8c2d-b9f2e96c593e.png)

## Environment

**Statamic version:** 3.0.0-beta.27

**PHP version:** 7.4

**Comment by jasonvarga** [comment]
Duplicate of #1048
