### ISSUE TITLE
Bard: List points missing

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1741]
## Bug Description
List points are not shown

## How to Reproduce
Make a list ;-)

## Extra Detail

![image](https://user-images.githubusercontent.com/3351449/80307884-3fb31300-87cc-11ea-9e18-15e4879cdeae.png)

## Environment
**Statamic version:** 3.0.0.-beta-27
**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by JonKaric** [comment]
In addition to the above:
- Nested lists work, but aren't identifiable. Nested lists need some padding on the left to make them identifiable.
- Ordered lists should be numbered
