### ISSUE TITLE
User forms do not render "attr" data

### ISSUE THREAD

**Issue by vitor-ao** [statamic/cms#1743]
## Bug Description
Problem shows in these tags:

- form:create
- user:login_form
- user:register_form

The attr variable will not be generated. Will show as `attr="id:user-form"` instead of `id="user-form"`.

## How to Reproduce
- Create a template that includes the tags above and add `attr="id:user-form"` variable.
- Examine the source code of the rendered template.

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.3.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
We changed it so you can just use regular attributes. eg `id=“user-form”`
