### ISSUE TITLE
Output modifier fails if no string is given

### ISSUE THREAD

**Issue by JonKaric** [statamic/cms#1747]
## Bug Description
Using the `output` modifier fails if no string is given .

## How to Reproduce
1) Create asset fieldtype with max files equalling one. 
2) Reference the url and use the output modifier, eg: `{{ sitetheme:folder_icon | output }}`

## Expected behaviour
The modifier should silently fail if no string is passed, and output nothing. 

## Extra Detail
> Argument 1 passed to Statamic\Assets\AssetRepository::find() must be of the type string, null given, called in .../mysite/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261

## Environment

**Statamic version:** `3.0.0.-beta-27`

**PHP version:** `7.3.7`

**Install method:** Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
A similar issue also happens when using the markdown modifier.
