### ISSUE TITLE
Bard's Underline text formatting doesn't output with any HTML tags

### ISSUE THREAD

**Issue by huladesign** [statamic/cms#1750]
## Bug Description
Tried to use the underline format feature in the Bard. However, the HTML output doesn't wrap the content with any tags for me to target and add any CSS (if requires text-decoration). I assume it may use the `<u></u`> tags

## How to Reproduce
Select text in the bard and apply the underline text format. 

## Extra Detail
Bard partial for `type.antlers.html`
```html
<div class="w-3/4 mx-auto text-center bard-text">
    {{ text }}
</div>
```

Additional styling added
```css
.bard-text p {
  @apply pb-2
}

.bard-text h2 {
  @apply text-xl font-bold pt-6 pb-4
}

.bard-text strong {
  @apply font-semibold
}
```

## Screenshots
1. Bard Input:
First line under "Some Heading 2 text" contains the underlined content.

![Bard Input](https://user-images.githubusercontent.com/61718247/80547716-0c12fb80-8a0d-11ea-97cb-9d7638bc2724.png)

2. HTML Output

![HTML Output](https://user-images.githubusercontent.com/61718247/80547635-d4a44f00-8a0c-11ea-8c58-61fc5912e826.png)

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.4.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

Apologies if I've missed anything!

**Comment by jasonvarga** [comment]
Will be fixed by https://github.com/scrumpy/prosemirror-to-html/pull/16

**Comment by sheldonkotyk** [comment]
Same issue with strikethrough.
