### ISSUE TITLE
Ability to disable edit_url and api_url in API

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1756]
edit_url exposes the CP's URL.

api_url exposes the site's URL, which could be an issue for people (there is at least one 😄 ) that are just exporting the API data to create a completely separate front-end.

**Comment by jasonvarga** [comment]
I think we should probably have separate `cp_urls` and `api_urls` configs within `api.php`.
Then in `AugmentedEntry` etc, the `api_url` and `cp_url` should be conditional on whether they're enabled and it's an api route (because when it's not inside the API, like in a template, we still want to supply the vars).

**Comment by damcclean** [comment]
Keep open please.
