### ISSUE TITLE
Slow page load times when editing entries

### ISSUE THREAD

**Issue by jojotl** [statamic/cms#1760]
## Bug Description
We noticed a performance hit after upgrading to a more recent version. Previously it took about 500-600ms to render the publish form of an average entry, now the same publish form takes about 3-4 seconds to render.

## How to Reproduce
1) Open the publish form of an entry with a large number of fields (>100)

## Extra Detail
As you can see in the following call graph most of the time is spent in `Statamic\Query\Scopes\Filters::extra()`. Apparently the recently added call to `$fields->fieldtype()->filter()->fields()->toPublishArray()` adds some serious overhead when you are using a large number of fields. This also seems to manifest in the http response size. In our case the response size went from 250Kb to 2.4 MB for the publish form of an average entry (both uncompressed).

<img width="510" alt="screenshot_extra1" src="https://user-images.githubusercontent.com/25369120/80632196-338eb600-8a57-11ea-99b1-09b579d6512e.png">
<img width="510" alt="screenshot_extra2" src="https://user-images.githubusercontent.com/25369120/80632210-39849700-8a57-11ea-9009-09df6a7daee9.png">

Is there any chance to strip down the field data or optimize this by caching? 

## Environment

**Statamic version:** 2c0592ac093e3389606ae3258a481e18c90be9bc

**PHP version:** 7.3

**Install method (choose one):**
- Custom build

**Comment by jasonvarga** [comment]
Thank you for the effort that went into this report. 👍
