### ISSUE TITLE
Unable to use Laravel Nova alongside Statamic

### ISSUE THREAD

**Issue by chrisbjr** [statamic/cms#1764]
## Bug Description
Unable to use Laravel Nova alongside Statamic

## How to Reproduce
Install Laravel Nova according to documentation on an existing Statamic installation. Currently using different guards for Nova and Statamic.

## Extra Detail

After proper installation of Nova, it looks like the route of the `FrontendController` of Statamic is overriding the routes of Nova. According to a comment in a Nova issue [here](https://github.com/laravel/nova-issues/issues/445#issuecomment-418798152) by davidhemphill, this is on purpose.

I was able to make it work by following the instructions in the comment and modified `vendor/statamic/cms/routes/web.php` and added the regex to allow nova requests to be passed through:

```
/**
 * Front-end
 * All front-end website requests go through a single controller method.
 */
Route::any('/{segments?}', 'FrontendController@index')
    ->where('segments', '.*')
    ->where('segments', '^(?!nova).*$')
    ->name('statamic.site');
```

So this is not really a fix, but was wondering if Statamic can allow us to add this line somewhere without having to modify the vendor files.

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.4

**Install method (choose one):**
- Existing Laravel app

**Comment by chrisbjr** [comment]
Nevermind, found another way:

In `config/statamic/routes.php`, i set `'enabled' => false,`

Then copied and implemented the Statamic routes myself with the above route implemented.

Thanks

**Comment by raisonon** [comment]
@chrisbjr this fix worked for me too. Cheers

**Comment by raisonon** [comment]
To elaborate  on above.

1. Add these routes to your routes: https://github.com/statamic/cms/blob/master/routes/web.php
2. Amend the path as per:
```

/**
 * Front-end
 * All front-end website requests go through a single controller method.
 /
Route::any('/{segments?}', '\Statamic\Http\Controllers\FrontendController@index')
    ->where('segments', '.')
    ->name('statamic.site');
```

**Comment by raisonon** [comment]
I was too focused on nova to check the /cp route for Statamic Backend and now discovered I cannot access it (get 404). So, despite my previous messages the above approach is not working for me. :/

**Comment by chrisbjr** [comment]
Hi @raisonon you have to add all your excluded routes like below :

```
/**
 * Front-end
 * All front-end website requests go through a single controller method.
 */
Route::any('/{segments?}', 'FrontendController@index')
    ->where('segments', '^(?!nova|cp).*$')
    ->name('statamic.site');
```

**Comment by raisonon** [comment]
Thanks for code example @chrisbjr -- I just amended as per your code without luck.

I've dumped my web.php routes into this gist -- perhaps you can spot where I am going wrong.  Many Thanks!

https://gist.github.com/raisonon/ffdebd4cee9479527a14cb0a91c4b658

**Comment by damcclean** [comment]
Try adding this to your `web.php` file, it will register the Statamic CP routes.

```
require_once __DIR__.'/../vendor/statamic/cms/routes/cp.php';
```

**Comment by raisonon** [comment]
> `require_once __DIR__.'/../vendor/statamic/cms/routes/cp.php';`

Hi @damcclean -- I get the following with that added:

` Invalid route action: [App\Http\Controllers\Auth\CsrfTokenController]. `

That controller is referenced in the cp.php file we have required (line 15). I imagine we need to pass something so the reference is corrected -- any ideas? Cheers

**Comment by damcclean** [comment]
Hmm, okay, what about adding this?

```
use Illuminate\Support\Facades\Route;
use Statamic\Http\Middleware\CP\SwapExceptionHandler as SwapCpExceptionHandler;

if (config('statamic.cp.enabled')) {
    Route::middleware(SwapCpExceptionHandler::class)->group(function () {
        Route::middleware('statamic.cp')
            ->name('statamic.cp.')
            ->prefix(config('statamic.cp.route'))
            ->namespace('Statamic\Http\Controllers\CP')
            ->group(__DIR__.'/cp.php');
    });
}
```

**Comment by raisonon** [comment]
Thanks @damcclean  I get 404 for nova and working for statamic with the above. I made a gist in case I used incorrectly: https://gist.github.com/raisonon/2a07b14e91d0465706cdf7c6d4eee745

@chrisbjr perhaps this should be re-opened?

**Comment by chrisbjr** [comment]
Okay, so from what I remember, I spent a night tearing my hair out to make this work. It still works now, we have a project ongoing with this setup. Backtracking my work, here is what I remember doing:

- Disabled routes from Statamic in `config/statamic/routes.php`
- Made a new file called `routes/statamic.php` and dumped the whole `vendor/statamic/cms/routes/web.php` of Statamic here with the following change:

```
/**
 * Front-end
 * All front-end website requests go through a single controller method.
 */
Route::any('/{segments?}', 'FrontendController@index')
    ->where('segments', '^(?!nova|cp).*$')
    ->name('statamic.site');
```

- In my RouteServiceProvider, I added a method to load `routes/statamic.php` , making sure to load the Statamic routes LAST

```
class RouteServiceProvider extends ServiceProvider
{
    ...

    /**
     * Define the routes for the application.
     *
     * @return void
     */
    public function map()
    {
        $this->mapWebRoutes();

        $this->mapWebApiRoutes();

        $this->mapApiRoutes();

        // Last
        $this->mapStatamicRoutes();
    }

    ...

    private function mapStatamicRoutes()
    {
        Route::middleware(config('statamic.routes.middleware', 'web'))
            ->namespace('Statamic\Http\Controllers')
            ->group(base_path('routes/statamic.php'));
    }
}
```

- Next, in `config/app.php`, can't remember if it's part of it but I've loaded `NovaServiceProvider` before my `RouteServiceProvider`

```
'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        ...
        App\Providers\NovaServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        
        ...
    ],
```

**Comment by raisonon** [comment]
@chrisbjr Big thanks for the comprehensive walk-through. Can confirm following these steps worked. Really useful to see how you worked through this. Not sure if best to leave as closed or to flag to main team to improve this integration... Anyway, big thanks again! Cheers

**Comment by chrisbjr** [comment]
Another feature that broke for Nova is the forgot/reset password feature. Upon investigation, it looks like StatamicServiceProvider is overriding the `PasswordBroker`, and hence, the `Password` facade. The `broker()` method here ignores the "name" parameter and still uses Statamic's password broker no matter the parameter you pass.

I've fixed this by overriding Nova's ForgotPasswordController and ResetPasswordController through the routes and extending it to so that it uses Nova's password broker:

**app/Providers/RouteServiceProvider.php**
```php
...
use App\Http\Controllers\Nova\ForgotPasswordController;
use App\Http\Controllers\Nova\ResetPasswordController;

class RouteServiceProvider extends ServiceProvider
{
    ...

    /**
     * Define the routes for the application.
     *
     * @return void
     */
    public function map()
    {
        ...

        $this->overrideNovaRoutes();
    }

    ...

    private function overrideNovaRoutes()
    {
        Route::domain(config('nova.domain', null))
            ->middleware(['web'])
            ->prefix(Nova::path())
            ->group(function () {
                Route::post('/password/reset', [ResetPasswordController::class, 'reset']);
                Route::post('/password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])
                    ->name('nova.password.email');
            });
    }
```

**app/Http/Controllers/Nova/ResetPasswordController.php**
```php
use Illuminate\Auth\Passwords\PasswordBrokerManager;
use Illuminate\Contracts\Auth\PasswordBroker;

class ResetPasswordController extends \Laravel\Nova\Http\Controllers\ResetPasswordController
{
    /**
     * Get the broker to be used during password reset.
     *
     * @return PasswordBroker
     */
    public function broker()
    {
        return (new PasswordBrokerManager(app()))->broker(config('nova.passwords'));
    }
}
```

**app/Http/Controllers/Nova/ForgotPasswordController.php**
```php
use Illuminate\Auth\Passwords\PasswordBrokerManager;
use Illuminate\Contracts\Auth\PasswordBroker;

class ForgotPasswordController extends \Laravel\Nova\Http\Controllers\ForgotPasswordController
{
    /**
     * Get the broker to be used during password reset.
     *
     * @return PasswordBroker
     */
    public function broker()
    {
        return (new PasswordBrokerManager(app()))->broker(config('nova.passwords'));
    }
}
```

**Comment by chrisbjr** [comment]
FYI, @raisonon I've opened Laravel Nova integration as a feature request here: https://github.com/statamic/ideas/issues/238

**Comment by raisonon** [comment]
Thanks for adding the FR @chrisbjr and likewise for posting the password fix, which I hadn't come into (yet).. Hopefully integration will be improved soon.

**Comment by edalzell** [comment]
> Okay, so from what I remember, I spent a night tearing my hair out to make this work. It still works now, we have a project ongoing with this setup. Backtracking my work, here is what I remember doing:

OMG @chrisbjr this was amazing, thanks so much!
