### ISSUE TITLE
404 (Not Found) Tag - Not working

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [statamic/cms#1766]
## Bug Description
Using the 404 tag causes throws a Facade\Ignition\Exceptions\ViewException.

## How to Reproduce
Use the `{{ 404 }}` tag in any antlers template. 
Using it like the [docs](https://statamic.dev/tags/404) describe does not work either.

## Extra Detail
If template is called fromt at controller
```php
return (new \Statamic\View\View)
   ->template('users.show')
   ->layout('layout')
    ->with(['profile' => $user]);
```
It throws:
### Symfony\Component\Debug\Exception\FatalErrorException
Method Statamic\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException:

[flare error link](https://flareapp.io/share/KPgzo3ma)

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.2

- Fresh install from `statamic/statamic` upgraded from beta-19

**Comment by jasonvarga** [comment]
Where are you using the 404 tag?

**Comment by AlexanderLindkjaer** [comment]
at the top of my template. But does not seem to matter where i use it, or what conditional it is wrapped in (or what that evaluates to)

```html
{{ if ! logged_in }}
    {{ 404 }}
{{ /if }}

<section class="article">
<div class="container">
 <div class="top-image">
   <img src="{{ thumbnail }}" alt="">
 </div>
 <div class="container content">
     <div class="article-info">
     <h1>{{ title }}</h1>
     <h3 class="author">
        {{ user id="{{ author }}" }}
         {{name}}
        {{ /user }}
     </h3>
     <p class="date">{{ updated_at format="d F Y" }}</p>
    </div>
    <div class="article-content">
        {{ content }}
    </div>
 </div>
</div>
</section>

<div class="comments">
    <h1>Kommentarer</h1>
</div>

```

**Comment by jasonvarga** [comment]
And what's in your controller?

**Comment by AlexanderLindkjaer** [comment]
That example was just a normal collection route, no controller.

The controller one is like this:

`Route::get('profile/{slug}', 'UserController@show');`

```php
class UserController extends Controller
{
    public function show(String $slug)
    {
        $user = User::query()
            ->where('slug', $slug)
            ->first();
        
        return (new \Statamic\View\View)
            ->template('users.show')
            ->layout('layout')
            ->with(['profile' => $user]);
    }
}
```
I can 404 it from the controller if needed ^^

and the template
```html
{{ if !profile }}
    {{ 404 }}
{{ /if }}

{{ profile }}

<section class="article">
    <div class="container">
        <div class="top-image">
            <img src="{{ avatar }}" alt="">
        </div>
        <div class="container content">
            <div class="profile-info">
                <h1>{{name}}</h1>
            </div>
            <div class="article-content">
                {{ email }}
            </div>
        </div>
    </div>
</section>

<div class="comments">
    <h1>Kommentarer</h1>
</div>


{{ /profile }}
```

this only throws the error if the 404 tag is reached by the conditional
https://flareapp.io/share/17xMkK5b

**Comment by jasonvarga** [comment]
My mistake - I thought it wasn't working because you were using it from a controller.

The same behavior happens on normal Statamic content/routes if you drop a 404 tag in a template. Fixed now.
