### ISSUE TITLE
User:Profile Tag - always getting logged in user

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [statamic/cms#1767]
## Bug Description
I can't get the User:Profile Tag to work as intended
https://statamic.dev/tags/user-profile

It always returns the logged in user instead. So it seems to behave like the `{{ user }}`

## How to Reproduce
```html
{{ user:profile slug="{slug}" }}
  {{ name }}
{{ /user:profile }}
```
## Extra Detail
does not matter what i find by, or if the field even exist
`name="{name}"`, `nonfield="nonfield"`

`email="{email}"` throws error

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.2

- Fresh install from `statamic/statamic`, upgraded from beta-19

**Comment by edalzell** [comment]
Couple of things:

1. `slug` is not a thing anymore, it's either `id` or `email`
2. `email` has a bug, I'm fixing and making a PR.
