### ISSUE TITLE
Form email template field needs to be replaced by text and html fields

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1772]
When adding an email to a form, there's a Template field, which is a remnant from v2.

In v3, we have separate text and html views (mirroring Laravel Mailables). Updated in code, but not in the UI.

By not choosing either of them, you should still get the "automagic" email.

See https://github.com/statamic/cms/pull/1765#issuecomment-622414792

**Comment by jimblue** [comment]
I could also be nice to have the option `automagic` for the `text` field.
So we can only set `html` template and le the magic happen for the `text` email.

**Comment by jackmcdade** [comment]
It's fixed now.
