### ISSUE TITLE
Asset::upload() not working

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [statamic/cms#1773]
## Bug Description
Statamic\Facades\Asset::upload() throws error

"Undefined index: dirname"

the issue is this method 
```php
 public function folder()
{
    return pathinfo($this->path())['dirname'];
}
```
in vendor/statamic/cms/src/Assets/Asset.php as the path() method return null.

## How to Reproduce
```php
 //$uploadedFile is an Instance of Symfony\Component\HttpFoundation\File\UploadedFile;
 $asset = Asset::make()
    ->container('profileimages')
    ->upload($uploadedFile);
```

## Extra Detail
Making the `folder()` method return `"."` if path is null,  fixes the issue.

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.2

- Fresh install from `statamic/statamic`

**Comment by AlexanderLindkjaer** [comment]
Works if done like this
```php
$asset = Asset::make()
  ->container('profileimages')
  ->path('.')
  ->upload($uploadedFile);
```

So maybe not at bug, but just wrong usage 😃  Thought i think it should be caught imo.

**Comment by jasonvarga** [comment]
Sorry about the delay here. The `path` you provide to the asset object should the path of the file, not just the directory.

If you use the same code we do when we upload assets, you should be good to go:

https://github.com/statamic/cms/blob/master/src/Http/Controllers/CP/Assets/AssetsController.php#L74-L83
