### ISSUE TITLE
More control over the automatic taxonomy routing

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1775]
Out of the box, you get a bunch of routes for taxonomies.

1. `/{taxonomy}`
2. `/{taxonomy}/{term}`
3. `/{collection}/{taxonomy}`
4. `/{collection}/{taxonomy}/{term}`

These are great to just have it work™, but there's a few issues:

1. Duplicate content. The collection scoped routes will filter down terms that are associated with entries in that specific collection. If you only use the taxonomy on one collection, routes 1+3 and 2+4 will be identical. We should probably have a way to turn this off, or customize which ones are enabled.

2. If you didn't know about these magic routes, you have these pages on your site that might be neglected. Should they be off by default and opt-in?

3. If you don't have a `{taxonomy}.index and/or {taxonomy}.show` views, visiting the urls give you a 500 ("view not found"). Should we check if the view exists and 404? or maybe if we make the feature opt-in, a view not found error is fine.

What if the whole thing is driven by view existence?
- If you have a `{taxonomy}.index` view, you get route 1.
- If you have a `{taxonomy}.show`, view, you get route 2.
- If you have a `{collection}.{taxonomy}.index` view, you get route 3.
- If you have a `{collection}.{taxonomy}.show` view, you get route 4.

🤔

**Comment by edalzell** [comment]
Driven by view is my vote. Clean and logical.

**Comment by JonKaric** [comment]
What if you've got say, 8 collections which all share the same taxonomy & the same template? In my case, I've got multiple collections & taxonomies that all share the same template.

**Comment by jasonvarga** [comment]
I wouldn't mind having 8 different templates, and they could all use the same partial.

**Comment by JonKaric** [comment]
That makes sense. As long as you could put them inside folders like `views/taxonomies`, I'd prefer driven by view. Gives you a clean slate and lets _you_ decide what to do, instead of the cp deciding for you, and then having to remove it if you don't want a certain route.

**Comment by jackmcdade** [comment]
I like it being driven by views too, that feels clean _and_ flexible. If you want to do something really funky you can always write a route, add a controller, and inject your customized taxonomy data or something.

**Comment by Pfeifakopf** [comment]
I have a new point after testing now. I have multiple taxonomies for location, type, etc. Then I have collections with events and restaurants. 
Now I've made sites for each town and list there all events and restaurants in the town. The restaurants are categorized in type like cafe, bar, restaurant, etc. This types are shown and clickable. If I click now on the type I would expect to see all types, like cafes in this current town. But the url brings be to collection with all entries with the type.

Try to make it clearer:
I'm on the town site with listed restaurants and events:
/town/berlin
I want to see other types of restaurants in the town, so I click on the type.
I'm getting this url
/restaurant/type/cafe
But this should be something like:
/town/berlin/restaurant/type/cafe
If I click on an event type, it should bring me to something like:
/town/berlin/event/type/concert

**Comment by padders** [comment]
I came here looking to see if I could find a way of doing this differently. We much prefer the method of having a single index with a taxonomy filter on it. The base route goes to the index page. e.g.

website.com/articles

and a filter would also go to the same index page, but you could just use the collection to filter by that taxonomy e.g.

website/com/articles/topic/cheese

I'd then get exactly the same index page, but filtered for articles on cheese.

With Statamic v2, I could do this easily and the taxonomy modifier allowed this to work brilliantly. e.g. 

`{{ collection:blogs taxonomy="true" paginate="true" as="posts" limit="12"}}`

The new method feels more convoluted. It's potentially more flexible but I definitely prefer v2's method.
