### ISSUE TITLE
Sucess notification doesn't show when submiting a forgot password form

### ISSUE THREAD

**Issue by vitor-ao** [statamic/cms#1777]
## Bug Description
After filing the email and submitting to reset the password of a user, the success notification is not rendered on the template, showing the form as it is.

## How to Reproduce
The example on https://statamic.dev/tags/user-forgot_password_form can be used, but changing the `name="username"` to `name="email"`.

Fill the email field with a user in the system and submit. You should receive an email, but no notification is shown on the web page.

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.3.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Were you logged in when you tested that?

**Comment by vitor-ao** [comment]
Tested in incognito mode with no user logged in.

**Comment by jeremydouglas** [comment]
I'm having a similar experience. I receive this error:

```
InvalidArgumentException
Password resetter [resets] is not defined. 
```

**Comment by vitor-ao** [comment]
@jeremydouglas for your error check https://github.com/statamic/cms/issues/1973

**Comment by mikemartin** [comment]
@vitor-ao See my workaround for this here:
https://github.com/statamic/cms/issues/2086#issuecomment-670812267

**Comment by jesseleite** [comment]
Fixed a bunch of issues around the forgot password form tag, including this one.  Should be in next release!
