### ISSUE TITLE
Reset password form returns error when submitted: Email is required

### ISSUE THREAD

**Issue by vitor-ao** [statamic/cms#1778]
## Bug Description
After filling the `password` and `password_confirmation` fields, it returns an error that says: Email is required.

## How to Reproduce
The form on https://statamic.dev/tags/user-reset_password_form can be used. 

After receiving an email reset email and clicking the link, fill the password and password confirmation fields and the error will show after submit.

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.3.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Docs updated.
