### ISSUE TITLE
Add set button between sets is too low

### ISSUE THREAD

**Issue by JonKaric** [statamic/cms#1786]
## Bug Description
A sad flower and this icon have much in common. Needs some sunlight 

![Screen Shot 2020-05-05 at 13 09 07](https://user-images.githubusercontent.com/8028521/81064473-a96ca480-8ed1-11ea-940a-3e0d7c5548eb.png)

**Statamic version:** `3.0.0.-beta-27`
**PHP version:** `7.3.4`
**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Hah we already aligned him once. Maybe it moved again when we updated tailwind. Thanks!

**Comment by jonassiewertsen** [comment]
This issue should be fixed:
https://github.com/statamic/cms/pull/1969
