### ISSUE TITLE
UI artifact with linked fieldsets

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1787]
## Bug Description

When you have a fieldset with a linked fieldset the field in the CP looks layered.

## How to Reproduce

Make a fieldset with a linked field:
![image](https://user-images.githubusercontent.com/6069653/81084271-8084e900-8eaa-11ea-9e31-031b2d87e1cd.png)

## Extra Detail

![image](https://user-images.githubusercontent.com/6069653/81084326-909cc880-8eaa-11ea-8dde-1ce0eaa5e3e3.png)

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.4

**Install method (choose one):**
- Other (please explain this magic!): converted from v2

**Comment by jasonvarga** [comment]
The layering is intentional, to show that it's multiple fields.

**Comment by edalzell** [comment]
Hokey dokey
