### ISSUE TITLE
Cmd-S not tied to Save on Navigation CP

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1794]
## Bug Description

If you're on the Navigation screen and you have changes and hit cmd-s (like you can do on entries), you don't save the data, you get the browser save.

## How to Reproduce

1. Make a navigation
2. Add an item
3. cmd-s

## Environment

**Statamic version:** 3.0.0-beta-27

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Confirmed. You must _add a item_ to recreate the issue - simply rearranging the nav doesn't cause issue.

**Comment by jackmcdade** [comment]
Can't quite find the fix on this one, but it's only happening when you add a URL, not a link.

**Comment by arthurperton** [comment]
Hu guys, I looked into this one. The problem is that the included PageEditor component is stopping the events necessary for the keyboard shortcuts to work. The code in PageEditor could be improved to avoid that. I'll create a PR with the fix.
