### ISSUE TITLE
Search Names in Users in CP or Add Filtering

### ISSUE THREAD

**Issue by twd3** [statamic/cms#1796]
I can only search via email addresses under users in the CP. I need to be able to search via name. I see in the docs for users it shows filters but I don't see filters in my beta 28 so I don't know if you guys are planning on adding filters to users and if that will fix my issue.

**Comment by twd3** [comment]
To add to this. You can only search users period in the cp if you add users to the default index and apparently that exposes the users to the frontend.

What we need is that awesome filter bar but for users. Maybe tied to the global cp search? IDK

**Comment by jelleroorda** [comment]
Our client was also suprised that there were no filter abilities on the users screen (they have 5 pages of users) which is inconvenient. Right now they have to search for e-mail adresses through global search, which is definitely not optimal. I'd say this issue can stay open.

**Comment by mikemartin** [comment]
Currently dealing with 9000 users and search is an absolute must. Only work around is searching emails in the global search as mentioned above.

**Comment by twd3** [comment]
I think Duncan may have helped us with this issue now: https://statamic.com/addons/double-three-digital/blaze

**Comment by joseph-d** [comment]
I know this isn't a competition but, yeah, I'm actually thinking of using Statamic to manage an existing Laravel site that has almost 300,000 users so the ability to filter by email and name at  a very minimum would be very important here.
