### ISSUE TITLE
Can't render Antlers in content

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1798]
## Bug Description

I have the following in a nav structure:
```yaml
    title: '&copy; {{ misc:organization_name }}. All Rights Reserved.'
```

In my template I have this:
```html
{{ title }}
```

Which outputs: 
![image](https://user-images.githubusercontent.com/6069653/81125100-0f662580-8eec-11ea-8022-134f3cdbf7e4.png)
If I do this instead: `{{ title }}{{ misc:organization_name }}`, I get:
![image](https://user-images.githubusercontent.com/6069653/81125068-f3fb1a80-8eeb-11ea-8b7f-e7e3ff60eb8f.png)

## How to Reproduce

1. Create a global with some data.
2. Create a Nav item whose title references the above global
3. In a template, reference the nav and that item's `title`

## Environment

**Statamic version:** 3.0.0-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
What do you mean by "...unless you do?"

**Comment by edalzell** [comment]
In the second example it seems to work **if** I have another tag there? See the example? If I only do `{{ title }}` it doesn't render the global, but if I also render the global on it's own then it works in both spots.

**Comment by jasonvarga** [comment]
Notes for later:

- Adding `antlers: true` to the field (`title`, in your case) will render the global.
- You have to drop _that_ global in your template to trigger the magical reappearance. Dropping any global isn't enough.

**Comment by jelleroorda** [comment]
Open sesame
