### ISSUE TITLE
Codemirror fieldtypes (code & yaml), code overlaps lines and language

### ISSUE THREAD

**Issue by JonKaric** [statamic/cms#1799]
## Bug Description
The code overlaps the line numbers and code language.

## Extra Detail
![Screen Shot 2020-05-06 at 11 03 44](https://user-images.githubusercontent.com/8028521/81165328-b4830b80-8f89-11ea-9876-fed519338743.png)

## Environment

**Statamic version:** `3.0.0.-beta-28`

**PHP version:** `7.3.7`

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by aj-adl** [comment]
Confirming still an issue in Beta 52 -  https://share.getcloudapp.com/yAuYzBnX
