### ISSUE TITLE
The replace and upper modifier can't be used together

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1800]
It does not work to use the `replace` and `upper` modifier together. 
`{{ title | upper }}` Working as expected
`{{ title replace=" |<br>"  }}` Working as expected

`{{ title replace=" |<br>"  | upper  }}` or any other kind of order does not working. There will simply be no output. 

**I would expect the `replace` and `upper` modifier working together.** 

It made me wonder, that the replace modifier does not need a `|`as prefix as the other modifiers do.

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
You're combining modifier syntaxes. Use either parameters or pipes, not both.

```
{{ title replace=" |<br>" upper="true" }}
```

**Comment by jonassiewertsen** [comment]
For `replace`

**Comment by jasonvarga** [comment]
I don't think you can do it because it has a space. But, `{{ title | replace:a,b | upper }}`

**Comment by jonassiewertsen** [comment]
Yes. The space is the problem. 

Thanks for the solution!
