### ISSUE TITLE
UI: Long file names shown buggy

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1801]
## Bug Description
The asset field shows assets with long filenames buggy.

## How to Reproduce
Asset field in list mode.

## Extra Detail

![image](https://user-images.githubusercontent.com/3351449/81212218-da81cd80-8fd4-11ea-9296-cc2c1e053109.png)

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
I can't recreate this at all, it always wraps for me as intended. What browser are you using?

**Comment by Pfeifakopf** [comment]
Did you set the field width to 50%? 

Chrome Version 81.0.4044.138
![image](https://user-images.githubusercontent.com/3351449/81702375-798e4580-946b-11ea-88b6-64eec56ebdd8.png)

**Comment by jackmcdade** [comment]
Nope, you never said to :)

**Comment by Pfeifakopf** [comment]
I'm sorry, my fault. The Issue was unclear.
