### ISSUE TITLE
Form fieldtype is missing max items setting

### ISSUE THREAD

**Issue by lokmanm** [statamic/cms#1804]
## Bug Description
If you use a Form Fieldtype to dynamically select a form, it will automatically make it a multi-select which makes it impossible to insert in a page like so:
```
{{ form:create in=display_form:handle  }}
```
Because it reads as an array and you will get an error saying error String in Array conversion.

The solution to this is going to the blueprint and manually adding `max_items: 1`. I think this should be by default.

## How to Reproduce
1. Go to any blueprint and add Form fieldtype.
2. Go to that page and select a form.
3. Try to use it insert it dynamically on a page with `form:create`

## Environment

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.3.17

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by edalzell** [comment]
Have you tried `:in="display_form:handle"`?

**Comment by lokmanm** [comment]
Yes, and without `max_items: 1` it won't work as It's an array. I think in these cases like the form field type there should be a default of max_items, or the option to select it on Cpanel.
