### ISSUE TITLE
Taxonomy not sorted by number of results by default

### ISSUE THREAD

**Issue by JonKaric** [statamic/cms#1806]
## Bug Description
The docs are in prewriting, so not sure if this is expected behaviour or not. Thought I'd track it anyway. When using the taxonomy tag, terms are sorted by title (alphabetically, A-Z,) by default but the docs say:

> **sort** string * results * 
> Sort entries by a field. By default it will be sorted by the number of results for each taxonomy.

**Using this tag, the output is sorted by title**
```
{{ taxonomy use="tags" }}
    {{ title }}
{{ /taxonomy }}
```

**Here, output is sorted by number of results**
```
{{ taxonomy use="tags" sort="" }}
    {{ title }}
{{ /taxonomy }}
```

## Environment

**Statamic version:** `3.0.0.-beta-28`

**PHP version:** `7.3.7`

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by fitzage** [comment]
I also have this problem. The behavior mentioned in the docs is the way v2 behaves, also, and there would appear to be no reason to change it, so I think it’s a bug.

**Comment by websmyth** [comment]
@fitzage – that perfectly describes the behaviour I’m seeing, too.

**Comment by jasonvarga** [comment]
The issue here is documentation. Looks like we lifted a bunch of it from v2 but never got around to updating it. Apologies for that, I'll adjust it.

By default, it'll sort by title. I don't think we can change that at this point, since it's been like this through the entire life of v3 and would be a breaking change now. Plus, in my opinion title is a more natural default order.

You can order by the number of results by using `sort="entries_count"` (we renamed `results` to `entries_count` in v3, it made more sense)

**Comment by websmyth** [comment]
Thanks, Jason – that makes sense.

Unfortunately, I’m seeing the same behaviour with:

`{{ taxonomy:fonts limit="15" sort="entries_count" }}`

I’ve also tried `sort="entries_count|asc"` and `sort="entries_count|desc"` but the results don’t seem to be filtered by the number instances for each term. In my example, it’s returning lots of terms with zero results and `asc` / `desc` makes no difference (but I’m just guessing that those should work).

**Comment by jasonvarga** [comment]
Can you put `{{ entries_count }}` in the loop so you can see the number it thinks it's sorting by?

**Comment by websmyth** [comment]
Yeah, the template is already:

```
{{ taxonomy:fonts limit="15" sort="entries_count" }}
  <li><a href="/{{ slug }}" class="button">{{ entries_count }}) {{ title }}</a></li>			
{{ /taxonomy:fonts }}
```

The terms are showing `0`.

**Comment by jasonvarga** [comment]
Everything is zero?

**Comment by websmyth** [comment]
Yep! 😬

**Comment by jasonvarga** [comment]
Then it's sorting just fine 😆

**Comment by websmyth** [comment]
Thanks to Jason for helping with this. For others’ reference, the order can be reversed using: `sort="entries_count:desc"` 🙌

**Comment by fitzage** [comment]
Shouldn’t this still be open? Or the docs need to be changed. It’s still not sorted by the number of results by default, like the docs indicate. It’s sorted alphabetically.

**Comment by jasonvarga** [comment]
Thanks for the ping. I was in the middle of adjusting the docs and got sidetracked. I'll finish up now.

See https://github.com/statamic/cms/issues/1806#issuecomment-691267293
