### ISSUE TITLE
If we set the max_depth to = 1 in a collection and we click on a multisite on the sort-button we van sort the tree of multiple sites together and on saving an error occurrs

### ISSUE THREAD

**Issue by matrad** [statamic/cms#1810]
If we set the max_depth to = 1 in a collection and we click on a multisite on the sort-button we van sort the tree of multiple sites together and on saving an error occurrs

**Comment by matrad** [comment]
Workaround is to set the max_depth to = 2, and then we're able to sort by multisite without error on saving.

**Comment by jasonvarga** [comment]
Apologies, but I'm finding this issue hard to understand and a little vague. If you are still experiencing this issue, please reopen a new one which follows the issue template and provides more details.
