### ISSUE TITLE
Subtract modifier not converting to number when two field values are used.

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/cms#1812]
## Bug Description
I have two integer fields in a blueprint (inventory and sales_threshold). In template, the tag {{ inventory | subtract:sales_threshold }} generates the error "Object of class Statamic\Fields\Value could not be converted to number"

This works when using a hard-coded number: {{ inventory | subtract:5 }}. Does not work in the reverse {{ 100 | subtract:sales_threshold }}, though I don't know if that's supposed to or not.

## How to Reproduce
Use subtract modifier to subtract one integer field value from another.

Also tried switching integer fields to text fields, and Antlers variations: {{ inventory | subtract:{sales_threshold} }} and {{ inventory | subtract:{{sales_threshold}} }}.

## Extra Detail
Error Message:
Facade\Ignition\Exceptions\ViewException
Object of class Statamic\Fields\Value could not be converted to number

## Environment

**Statamic version:** 3.0.0.-beta-{28}

**PHP version:** 7.{3}

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by theblacksheepltd** [comment]
Seems to be related to augmentation — if I add two values in the entry's yaml that aren't tied to fieldtypes, all works as expected.

**Comment by jackmcdade** [comment]
Good catch, thanks!
