### ISSUE TITLE
Unable to reference variables in rating modifier

### ISSUE THREAD

**Issue by vootrunner** [statamic/cms#1813]
## Bug Description

Might be pilot error, but using variables in tag modifiers produces results in the tag being stripped from the generated html. 
## How to Reproduce

Both of these fail to produce the expected output.  In this example rating=4

```
{{ star | repeat:{rating} }} {{ rating }}
{{ star | repeat:rating }} {{ rating }}
```

output:

4

Hard coding the repeat value produces the expected output

`{{ star | repeat:4 }} {{ rating }}
`

⭐️⭐️⭐️⭐️ 4

## Environment

**Statamic version:** v3.0.0-beta.28

**PHP version:** 7.4.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Good catch, thanks.
