### ISSUE TITLE
User Avatar Error

### ISSUE THREAD

**Issue by karthickk1996** [statamic/cms#1816]
## Bug Description
When you try to change the avatar after changing if for the first time there is a JS error which makes the avatar overflow layer keeps on loading. 

## Extra Detail

<img width="1248" alt="Screenshot 2020-05-12 at 6 26 08 AM" src="https://user-images.githubusercontent.com/28473613/81626500-83875880-9419-11ea-99dc-1e1bceb8dafe.png">
<img width="553" alt="Screenshot 2020-05-12 at 6 26 19 AM" src="https://user-images.githubusercontent.com/28473613/81626508-86824900-9419-11ea-8708-092a0b0b204f.png">

## Environment

**Statamic version:** 3.0.0.-beta-{28}

**PHP version:** 7.{4}

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
