### ISSUE TITLE
Hidden pages not available on `nav` tag

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1817]
Filtering pages with the `nav` tag as written in the docs, does not take effect. 

[https://statamic.dev/tags/nav#hidden-pages](https://statamic.dev/tags/nav#hidden-pages)

I would guess, that it has not been ported over to v3 yet. 

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Closing in favor of #2286
