### ISSUE TITLE
Improve filter interaction

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1821]
Need a better way for one filter to see the values of other filters.

eg. Filter B might show different options in a select field based on the value of Filter A.

**Comment by sauerbraten** [comment]
Seeing the values is possible, in a hacky way, via the Vuex store.

More specifically, we'd like the default and the auto-applied values of filters to be put into the store, which is not happening at the moment.

**Comment by jelleroorda** [comment]
This would be really nice improvement :)

**Comment by jackmcdade** [comment]
I'm going to close this issue as it's gotten stale and is vague on specific use cases. It would be more valuable to open a new issue (perhaps on https://github.com/statamic/ideas) with a strong use case when one arises, making it a much more viable feature to work on at such a time.
