### ISSUE TITLE
Publish status indicator doesn't update when (un)publishing an entry

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#1822]
## Bug Description
When publishing or unpublishing an entry, the updated values for its `published`, `private` and `status` fields are received from the server, but the relevant Vue component attributes are not updated, meaning the grey dot will not turn green after you published.

This applies to the entry edit page as well as items linked via the relationship fieldtype (i.e. the dot doesn't update after you publish them through the inline edit form).

## How to Reproduce

1. create an entry
2. the dot left of the title will be grey
3. publish the entry
2. the dot left of the title will be grey
4. reload the page
4. the dot is now green

or

1. link an unpublished entry using the entries fieldtype
2. the dot left of the title will be grey
3. click on the entry title to open the inline edit form
4. publish the entry
5. close the inline form
2. the dot left of the title will be grey
4. reload the page
4. the dot is now green

## Environment

**Statamic version:** https://github.com/statamic/cms/commit/cc4b3bd77921faec64af799fcfc27a4c7c6b9022

**Comment by sauerbraten** [comment]
We use this patch for the time being: https://pastebin.com/dU3fHJg0

It's hacky in some parts (modifying `activeLocalization` like this, for example), but it should point in the right direction...

**Comment by damcclean** [comment]
I've confirmed the issue and recorded a [short Loom demonstrating the issue](https://www.loom.com/share/1a44bd60df3c42a3a09bc754c6d16c91).

**Comment by WiebkeVog** [comment]
@jesseleite the behavior unfortunately still occurs with us.
When publishing or unpublishing an entry, the status is not updated. Still affects the status in an entry next to the title and the status within a Relationship-Fieldtype.

**Comment by damcclean** [comment]
@WiebkeVog Could you try updating to the latest version of Statamic and try again? Currently the latest version if [v3.0.22](https://github.com/statamic/cms/releases/tag/v3.0.22)

**Comment by WiebkeVog** [comment]
The problem also occurs with version v3.0.22

https://www.dropbox.com/s/3qi1e5xrvwz1yh2/Aufnahme.mov?dl=0

**Comment by jesseleite** [comment]
Ah yes, was still broken with revisions enabled, thanks for video @WiebkeVog!  Fixed in above commit.
