### ISSUE TITLE
Converting to multisite just possible, if the sites config has not been touched 

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1829]
Not sure if this is a bug or worth a big and bold `hot tip` in the docs:

[Link to Statamic docs](https://statamic.dev/knowledge-base/converting-from-single-to-multi-site)

If you do run `php please multisite` after you did make changes to `config/statamic/sites.php`, it won't work. 

Not sure if the docs need an update or if it's a bug. 

![Screenshot 2020-05-14 at 14 09 06](https://user-images.githubusercontent.com/38906163/81932848-b5044d80-95ec-11ea-94d1-850cefc460b6.png)

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
The command output tells you what to add.

**Comment by jasonvarga** [comment]
Oh sorry I misread. Yes the command requires that you haven’t updated your config yet. We can make that clearer in the docs.

**Comment by jonassiewertsen** [comment]
I was not sure if this was expected or not. 

Let me close this issue then and do a PR for the docs.

**Comment by jonassiewertsen** [comment]
This might make it clearer
https://github.com/statamic/docs/pull/120
