### ISSUE TITLE
A multisite does not inherit the layout

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1830]
The layout property should be inherited automatically from the `origin` entry. 

To make it work, the layout can be added manually as shown on the screenshot. 

![Screenshot 2020-05-14 at 15 26 12](https://user-images.githubusercontent.com/38906163/81940488-edf5ef80-95f7-11ea-98c5-44f5e1dc9489.png)

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment]
When updating the translated version, **the** manual added **layout will be deleted**.

**Comment by jonassiewertsen** [comment]
Is it a problem, that i don't have a `layout` field defined in my blueprint? That could be. 

Without translations, it has been working as expected without defining the layout as a field in my blueprint. 

In case I should define a layout field, which fieldtype to use? There is a `template` and `blueprint` fieldtype but no layout fieldtype.

**Comment by AndreasSchantl** [comment]
This is also true for the template variable. It should either copy it over or look in the origin if not defined.

**Comment by jonassiewertsen** [comment]
As I learned through my process:

You can manually add a template and layout to a pages collection. 
Those values won't be removed and don't need to be defined in the blueprint. 

This does change for multisites though. The entry which is not the origin entry, will check the blueprint data and remove all fields which have not been defined. That might often be the case for the layout and template field. 

Either should the child entry look for all blueprint fields + layout and template as default or we do need to force the need for defined template and layout fields generally. 

@AndreasSchantl As a workaround, you only need to define hidden fields for the template and layout in your blueprint and everything should be fine.

**Comment by AndreasSchantl** [comment]
I agree. Thanks for letting me know that there is a workaround.

**Comment by jasonvarga** [comment]
It looks like the template and blueprint already read from the origin entry appropriately. Perhaps those were fixed since you opened this issue.

Layout has been updated now, though.
