### ISSUE TITLE
Collection:next/previous ignores other entries of the same day

### ISSUE THREAD

**Issue by jmartsch** [statamic/cms#1831]
## Bug Description
I have a collection "articles".
When I am on an article page (frontend), I want to display links to the previous and the next article.

I did this by using this code:
```
{{ collection:previous in="articles" as="posts" limit="1" sort="date:asc" }}
<!--        {{ if no_results }}-->
<!--        No more posts to read!-->
<!--        {{ /if }}-->
    {{ posts }}
    <p class="post">
        Previous article: <a href="{{ url }}">{{ title }}</a>
    </p>
    {{ /posts }}
    {{ /collection:previous }}

    {{ collection:next in="articles" as="posts" limit="1" sort="date:asc" }}
<!--    {{ if no_results }}-->
<!--    No more posts to read!-->
<!--    {{ /if }}-->
    {{ posts }}
    <p class="post">
        Next article: <a href="{{ url }}">{{ title }}</a>
    </p>
    {{ /posts }}
    {{ /collection:next }}
```

but when I am on the page of the article "Warum ProcessWire die beste Wahl für Ihre Website ist" the link to the next article "Why ProcessWire is the best choice for your website" (same article in english language) is not being displayed.

If I change the date of the latter, the link is being displayed.

Am I doing something wrong, or is this a bug?

![image](https://user-images.githubusercontent.com/551551/81940185-9e172880-95f7-11ea-9e24-8cefa3d7ba8b.png)

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.3

**Comment by jackmcdade** [comment]
Entries with the same date should be further sorted by title. "Previous" should be older/further down the list, which would be "Why ProcessWire...". Next would be new, which would be "Disable select option if already...".

Does that make sense? Is that what's happening?

**Comment by jmartsch** [comment]
What you wrote would be the expected output, but it isn't that way.

Here is a screenshot of the page "Warum ProcessWire..."
The link to the next entry is correct. But the link to the previous entry "Why ProcessWire.." is skipped. Instead the next entry in the list ist shown.

![image](https://user-images.githubusercontent.com/551551/82988725-e1ab6280-9ff9-11ea-9def-0bb9d279f9c5.png)

The same happens if I am on the page "Why ProcessWire...". The link to the entry "Warum ProcessWire..." does not appear, it is just skipped:
![image](https://user-images.githubusercontent.com/551551/82989082-67c7a900-9ffa-11ea-9268-0b7adea24632.png)

I also tried setting the sort to date:desc, but that does not make any difference in terms of showing the correct entries.

**Comment by jackmcdade** [comment]
Yeah, this is a confirmed bug here. Thanks for the report!

**Comment by mikemartin** [comment]
Can confirm. Ran into this one today too. Adjusting the dates solved the issue. 👍

**Comment by Gitsack** [comment]
Had the same issue, @jmartsch made me aware of the ongoing bug report. Manually sorting the entries by different dates unfortunately is a hacky workaround.

Further distinction is possible by setting the date picker of the respective blueprint to include time, so only the time of the dates have to be different for entries to be displayed.

Will/should the entries be distinguished by name or by id? Just curious. :)

**Comment by tao** [comment]
I encountered this bug too, I tried sorting by `slug` next but it just ignored entries with the same date.

```
{{ collection:previous in="interviews" sort="date:desc|slug:desc" limit="1" }}
```

**Comment by jmartsch** [comment]
Bug is still there though

**Comment by tao** [comment]
This bug is still giving us some problems on our production site, it would be great if it could be investigated further soon.

**Comment by tao** [comment]
I had a problem with this for ages because we had multiple entries on the same day with these kind of filenames.

```
1974-02-23.0223_01.md
1974-02-23.0223_02.md
1974-02-25.0225_01.md
1974-02-25.0225_02.md
1974-02-25.0225_03.md
```

We used different slugs `0223_01` or `0223_02` for entries on the same day, but the next / previous navigation would just skip them completely and show the next day only or the previous day only, ignoring the other files on the same day.

For anyone else interested, I wrote a custom tag to work around this. It works by getting a list of entries and slicing the collection to always get the next / previous entry in the list.

```php
<?php

namespace App\Tags;

use Statamic\Tags\Concerns\QueriesConditions;
use Statamic\Tags\Tags;
use Statamic\Facades\Entry;

class Custom extends Tags
{
    use QueriesConditions;

    /**
     * Entry ID
     */
    protected $currentId;

    /**
     * Index position of current entry in collection
     */
    protected $index;

    /**
     * Number of entries to return
     */
    protected $limit;

    /**
     * Entries collection
     */
    protected $entries;

    /**
     * Shared setup
     */
    public function setup()
    {
        // get parameters
        $collection = $this->params->get('in');
        $this->limit = $this->params->get('limit');

        // get current context
        $this->currentId = $this->context->get('id');
        $locale = $this->context->get('locale');

        // get index of current entry
        $entries = Entry::query()
            ->where('collection', $collection)
            ->where('locale', $locale);

        // filter by query conditions, i.e. type:in
        $this->queryConditions($entries);

        // save the collection
        $this->entries = $entries->get();

        // get the key of the current index
        $this->index = $this->entries->filter(function ($item) {
            return $item->id() == $this->currentId;
        })->keys()->first();
    }

    /**
     * The {{ custom:next }} tag.
     * Determine the next entry in the list
     *
     * @return array
     */
    public function next()
    {
        $this->setup();

        // splice entries by key
        $splice = $this->entries->splice($this->index);

        // get next entries (using splice)
        $next = $splice->reject(function ($item) {
            return $item->id() == $this->currentId;
        })->shift($this->limit);

        // respond with next entries
        return $next->map(function ($entry) {
            return [
                'url' => $entry->url(),
                'slug' => $entry->slug(),
            ];
        })->toArray();
    }

    /**
     * The {{ custom:prev }} tag.
     * Determine the prev entry in the list
     *
     * @return array
     */
    public function prev()
    {
        $this->setup();

        // splice entries by key
        $splice = $this->entries->splice($this->index);

        // get previous entries (using remaining entries after splice)
        $prev = $this->entries
            ->reverse()
            ->reject(function ($item) {
                return $item->id() == $this->currentId;
            })
            ->shift($this->limit);

        // respond with next entries
        return $prev->map(function ($entry) {
            return [
                'url' => $entry->url(),
                'slug' => $entry->slug(),
            ];
        })->toArray();
    }
}
```

Now in my code I can just call the custom tag. I just wrap the response in an `{{ entries }}` tag  here so it doesn't use the pages url or page slug if no response is returned (last or first entry in the collection)

```html
    <div class="flex items-center justify-between w-full">

        {{ custom:prev in="articles" type:in="{type:slug}" limit="1" as="entries" }}
            <span>
                {{ entries }}
                <a href="{{ url }}">Previous</a>
                {{ /entries }}
            </span>
        {{ /custom:prev }}

        {{ custom:next in="articles" type:in="{type:slug}" limit="1" as="entries" }}
            <span>
                {{ entries }}
                <a href="{{ url }}">Next</a>
                {{ /entries }}
            </span>
        {{ /custom:next }}
    </div>
```

Or if I want the last 5 entries for example I could change the limit:

```
<ul>
        {{ custom:prev in="articles" limit="5" }}
            <li>
                <a href="{{ url }}">
                     {{ title }}
                </a>
            </li>
        {{ /custom:prev }}
</ul>
```

You can also add any custom filtering on the tag with the `QueriesConditions` trait. So in my example I do `type:in="{type:slug}"` to filter by a specific type but you can also manually do something like `type:in="speeches|interviews". 

You should be able to use any custom filtering like `is`, `equals`, `isnt`, `contains`, etc but I haven't tested it further.

Now I've got my next / previous tags working in order with multiple entries per day.

**Comment by klickreflex** [comment]
Could this please be prioritized? It's not that uncommon to have same-date entries in a collection.

@tao Thanks for sharing your solution 🙏
