### ISSUE TITLE
Users not listed after removing fields roles and groups from blueprint

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1834]
##  Bug Description
When you remove the fields roles and groups from the user blueprint, the users are not shown anymore. 

## How to Reproduce
Remove the fields groups and roles from the user blueprint.

## Extra Detail
No error message, just blank.

## Environment
**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Users are not shown where? What’s blank?

**Comment by Pfeifakopf** [comment]
The are not shown in the user list:
![image](https://user-images.githubusercontent.com/3351449/82080145-515d4b80-96e4-11ea-9423-db310cfe5a14.png)
![image](https://user-images.githubusercontent.com/3351449/82080343-a731f380-96e4-11ea-86cb-d266faa62c6f.png)

**Comment by edalzell** [comment]
@Pfeifakopf I can't reproduce this, does this still happen to you on the latest (3.0.10) version?

**Comment by Pfeifakopf** [comment]
@edalzell I can't reproduce it anymore too, testet it on 3.0.10. I close this issue.
