### ISSUE TITLE
Multi-site default fallback

### ISSUE THREAD

**Issue by robbinjohansson** [statamic/cms#1836]
Hi,

Currently remaking a site built in statamic v2 to v3 and having some issues with translating the content/falling back to a default site.

In statamic v2 if I visited /{locale}/somepage and that page wasnt translated in `{locale}` it would fallback to the english (default) version of the site, but still keep `{locale}` in the url.

Is that still possible? I've created a multi-site with 65 different sites and would like to fallback to the english (default) version if a page doesnt exist as a translation but on the default site.

Currently this gives me 404 and I'd have to create all pages on all sites even if I don't have a translation for it.

Thanks,

**Comment by jasonvarga** [comment]
It does indeed work the opposite way in v3. For a lot of people, the v2 way was awkward.

I would like to support the v2 way though, as an option. Right now it's not possible.

I'm assuming you are on the same project being talked about over here: https://github.com/statamic/cms/issues/1971#issuecomment-679406424

**Comment by el-schneider** [comment]
I’m not sure what @777666222244466 is saying but i also noticed that there seems to be a default fallback behaviour when a single entry `page` is loaded without a localized version but not within the `collection` tag

for example `de/events/{slug}` is falling back to `events/{slug}` when there is no translated version

but at `events/index` only urls for translated versions are showing.

I think an option to include also urls to non-translated entries is necessary
