### ISSUE TITLE
Should forms be saved inside the statamic storage folder?

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1844]
Should forms be saved inside the statamic storage folder?

Is this by purpose so forms can be version controlled or should the forms folder be saved inside the statamic storage folder?

![Screenshot 2020-05-17 at 20 18 29](https://user-images.githubusercontent.com/38906163/82156680-f743be00-987c-11ea-9ad5-a753ffdfbd25.png)

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.3

**Comment by jasonvarga** [comment]
The `storage/statamic` directory is typically full of files you wouldn't want to track.

You might want to track form submissions, which is why its separate. [You can customize the directory though](https://github.com/statamic/statamic/blob/master/config/statamic/forms.php#L25).
