### ISSUE TITLE
Changing the case of a user's email address in CP deletes user

### ISSUE THREAD

**Issue by ianlord** [statamic/cms#1847]
## Bug Description
If changing the case of a user's email address (but not changing anything besides case), the user's .yaml file is deleted.

Might be related to: https://github.com/statamic/cms/issues/1834

## How to Reproduce
- Go through the create new user flow in the CP for `test@example.com`
- Via the CP, go to Users > test@example.com
- Change the case of the email address (e.g., to `Test@example.com`)
- Save

The user is gone from the CP, and `/users/test@example.com.yaml` has been deleted from the filesystem

## Extra Detail
No exception / error message is given

## Environment

**Environment:** Local environment (Laravel Valet)

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.4.0

**Install method:** Fresh install from `statamic/statamic`

**Comment by Konafets** [comment]
I investigated this issue and like to share my findings:

My test cases:

1. Change case of email address
   - Add a new user with `test@example.com` email
   - User is stored in `/users/test@example.com`
   - Change this email to `Test@example.com` 
   - User is gone

2. Change email address to another one
   - Add a new user with `test@example.com` email
   - User is stored in `/users/test@example.com`
   - Change this email to `test@example.org` 
   - New address is stored at `/users/test@example.org`

⚠️ I found a follow up issue in the first test case: After the user is deleted I can not add a user with that email address again. I get `Call to a member function selectedQueryColumns() on null`

---

So changing the email to another one works, but changing the case does not.

Lets dive into:

To store and update the user, Statamic uses `File::put()` within `ExistsAsFile::writeFile`. `File::put`
uses `file_put_contents()` to write the date to a path. `file_put_contents()` creates a new file if there is no one with the name `test@example.com` (and updates its content when I change the name). In case I change the email to something else (case two) it creates a new file and in https://github.com/statamic/cms/blob/master/src/Data/ExistsAsFile.php#L69 Statamic takes care of deleting the old file. 
`file_put_contents()` **does not** create a new file in case one ... just writes the content to the existing file. Statamic on the other hand recognize that `test@example.com` and `Test@example.com` are different and deletes the file using `File::delete()`.

Beside this issue, I am not sure if its a good idea to use the email address as a filename as there are case insensitive and case sensitive filesystems on the field and I assume this might be an ongoing source of irritation and bug reports.

**Comment by jasonvarga** [comment]
Thank you for your investigation. Very helpful!
