### ISSUE TITLE
{{ template }} tag only outputs template field

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#1848]
##  Bug Description
When using the `{{ template }}` tag, it only outputs what's in a template field, not the actual template in use. This means that when you are viewing an entry page from a collection where the template is selected via the collection config instead of an actual field in the entry, it outputs nothing.

## How to Reproduce
1. Put the `{{ template }}` tag somewhere in a template that is activated only by the collection configuration.
2. Load the page
3. The output of the `{{ template }}` tag will be empty.
4. Add a template field to the entry content file with the name of the template in it.
5. Refresh the page
6. The output of the `{{ template }}` tag will show what's in the template field.

## Extra Detail
In V2, this worked as expected. It output whatever template was in use, even if there was no template field specifically in the content file.

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.3.9

**Install method (choose one):**
- Fresh install from `statamic/statamic` (then migrated from old site)

**Comment by jasonvarga** [comment]
I tried to reproduce this but the behavior seems consistent with v2. Can you provide some more details?

**Comment by fitzage** [comment]
In V2, it will output whatever template is in use. So I’m a collection, I don’t have a template field per item, but it knows what template the collection is using. In v3, if I only have an implicit template set via collection settings, it outputs nothing.

On Jun 11, 2020, at 2:11 PM, Jason Varga <notifications@github.com> wrote:

﻿

I tried to reproduce this but the behavior seems consistent with v2. Can you provide some more details?

**Comment by fitzage** [comment]
I started writing up a new bug report, and then remembered I already reported it, so here’s the new detail that I was going to put in the new report:

## Bug Description
The `{{ template }}` tag in v3 no longer outputs the template in use. It outputs the content of the template field, which is not the same thing.

## How to Reproduce
1. If you have an entry in the page collection that’s individually assigned a custom template, that saves a template field in the actual entry. Using `{{ template }}` in your template or layout will output the name of the template.
2. If you have an entry in a collection where the template is assigned via the settings for the collection instead of individually in the entry, the `{{ template }}` tag outputs nothing.
3. If you add a template field to the entry, the contents of that field get output by `{{ template }}`.

[The documentation](https://statamic.dev/variables/template) describes the template variable as “The name of the template currently in use.” This is what it should be, and this is the way it worked in v2. However, this is not accurate. It outputs the value of the template field, which may not exist.

For a workaround I could add a template field to the related blueprint, and add a default value, but then I’d have to go update all the existing ones, and it seems like an annoyingly unnecessary extra step. Then I’d also run into issue #672.
## Environment
Statamic 3.0.0 Pro
Laravel 7.25.0
PHP 7.3.17
No addons installed

- Fresh install from `statamic/statamic`, followed by migration from v2

**Comment by jasonvarga** [comment]
Thanks for following up. I understand the issue now.

I would argue that the behavior in v3 is more correct. If you're looping through a list of entries, you might want to know what template it's going to use. Maybe. Point is, if the value exists in the entry, it should be available just like any other of the entry's values.

How would you feel about a separate dedicated variable, like `{{ current_template }}`?

**Comment by fitzage** [comment]
That makes sense. A separate variable would be fine.

On Aug 25, 2020, at 3:57 PM, Jason Varga <notifications@github.com> wrote:

﻿

Thanks for following up. I understand the issue now.

I would argue that the behavior in v3 is more correct. If you're looping through a list of entries, you might want to know what template it's going to use. Maybe. Point is, if the value exists in the entry, it should be available just like any other of the entry's values.

How would you feel about a separate dedicated variable, like {{ current_template }}?

**Comment by el-schneider** [comment]
I also ran into this. A seperate variable sounds like a smart solution!

**Comment by jonassiewertsen** [comment]
Definitly!

Maybe inside the page variable?

**Comment by fitzage** [comment]
For a workaround right now that’s easier than some of the other options, I added
```
---
template_name: use-case
---
```

to the template files, and then I can just call {{ view:template_name }} in the layout, and we’re golden.

**Comment by sjclark** [comment]
> Definitly!
> Maybe inside the page variable?
**> {{ page:template }}**

My vote would be for **{{ page:template }}** - as it's really just a scoping / cascade issue would it not make sense to just have it output at the relevant (page) level?

**Comment by damcclean** [comment]
Just looking into this issue now...

From the looks of things, `{{ page:template }}` seems to provide the correct result. However, that'll only work for entry pages.

**Comment by jmartsch** [comment]
I am on Statamic 3.0.36 and `{{ page:template}}` and `{{ template }}`outputs nothing, if I am on a page from a collection.

Getting the name of the template would desperately needed for conditional CSS (Critical CSS) or including partials, etc.

**Comment by jmartsch** [comment]
Now I used the following workaround to output a body class named "name of the template"-template (for example blog-template) so I can style some things different depending on the page:
`{{ if page:template }}{{ page:template }}-template{{else}}{{ parent:slug }}-template{{ /if }}`
