### ISSUE TITLE
nav:breadcrumbs isn't working with AMP views

### ISSUE THREAD

**Issue by twd3** [statamic/cms#1849]
nav:breadcrumbs is not rendering anything on AMP version of entry.

Use nav:breadcrumbs in a template that an AMP'ed entry uses and visit the AMP version.

3.0.0.-beta-28

**PHP version:** 7.3.4

Fresh install from `statamic/statamic`

**Comment by twd3** [comment]
As far as I know, this is still an issue. I wouldn't close it.

**Comment by jackmcdade** [comment]
At this point with AMP being officially dead, I think it's best if we focus on other issues here and start the depreciation process for the feature.
