### ISSUE TITLE
Links made via bard don't update to AMP link when viewing AMP version

### ISSUE THREAD

**Issue by twd3** [statamic/cms#1850]
Links made via bard don't update to AMP link when viewing AMP version.

Use a bard fieldtype in a blueprint for a collection that's AMP'ed then make a link in that bard and view the AMP version of the entry. That link will take them away from the AMP version.

3.0.0.-beta-28

PHP version:** 7.3.4

Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
They wouldn't if you're hardcoding them.

If you use a dynamic link tag then it would be clever about it. But we don't have that yet. 😬 See #801
