### ISSUE TITLE
Protect Settings Don't Apply to Half Static Cached Pages

### ISSUE THREAD

**Issue by ramimassoud** [statamic/cms#1858]
## Bug Description

When combining [site-wide protection](https://statamic.dev/protecting-content#sitewide-protection) with [half measure static caching](https://statamic.dev/static-caching#application-driver), any pages that are cached will not respect protection settings.

## How to Reproduce

<details>
 <summary>1. Enable static half-cache</summary>

```php
return [
    'strategy' => 'half',
    'strategies' => [
        'half' => [
            'driver' => 'application',
            'expiry' => env('HALF_CACHE_EXPIRE', 60),
        ],
    ],
];
```
</details>
<details>
 <summary>2. Enable default protection scheme</summary>

```php
return [
    'default' => 'logged_in',
    'schemes' => [
        'logged_in' => [
            'driver' => 'auth',
            'login_url' => '/cp/auth/login',
            'append_redirect' => true,
        ],
    ],
];
```
</details>

3) Clear all caches `php please static:clear && php artisan cache:clear && php please stache:refresh`

4) Verify in incogneto window that a page is protected

5) Nagivate to that page when logged in to allow it to be cached

6) Return to that page in incogneto and it will be visible again

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.3

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
If a page is cached, it doesn't care whether you're logged in or not. It's just whatever is there at the first render.

We could add more options to the half measure caching strategy, (like not kicking in on protected pages) but right now it's working as intended.

**Comment by ramimassoud** [comment]
I figured that could be the case, I wanted to sanity check after reading the [static cache docs](https://statamic.dev/static-caching#application-driver)

> The application driver will store your cached page content within Laravel’s cache. We refer to this as half measure.
>
> This will still run every request through a full instance of Statamic but will serve all request data from a pre-rendered cache, speeding up load times often by half or more. This is an easy, one-and-done setting.

I thought that `This will still run every request through a full instance of Statamic` might mean protecting pages should still have worked

**Comment by jasonvarga** [comment]
That’s true but it returns the cached page as early in the process as it can. Before any content or template data would be evaluated.

**Comment by ramimassoud** [comment]
Makes sense, thanks for replying!

**Comment by axeloz** [comment]
> We could add more options to the half measure caching strategy, (like not kicking in on protected pages) but right now it's working as intended.

I may disagree on this. It really depends on what we are talking about. I think that this may be confusing of the end-user who sets a password-protected page, he doesn't expect to let the content be accessed publicly. 
The behavior you are talking about is common with reverse proxies caching requests like Varnish as they cache everything without knowing what's good and bad to cache. Thus the admin has to make sure some resources are not cached by the proxy by exclusion rules. 
But in this case, I find this quite dangerous and avoidable as the request runs through Statamic anyways as you mentioned it. 

At least, I believe you should add a warning chapter on the Static cache documentation page : "Warning if you cache the content, the page won't potentially be protected any longer ...."

**Comment by jasonvarga** [comment]
I improved the preface on the static caching docs page.

https://statamic.dev/static-caching#important-preface

**Comment by stuartcusackie** [comment]
Might be nice to have a little text about this on the protecting content page too:
https://statamic.dev/protecting-content

I do find this requirement a bit weird though, and yes a little dangerous. Sure I can exclude my protected page from the static cache, but what happens when one of my admins changes the page url? A password protected page becomes public without my knowledge.

I'm sure it's more complicated than I think but it would be nice if this was handled automatically and we could still cache protected pages safely. Maybe the middleware can be restructured to improve this.

**Comment by jasonvarga** [comment]
Feel free to make a PR to the docs with a suggestion of how you'd like to see it worded.

We could probably make it so that protected pages are automatically excluded from static caching. If you want, you can open a feature request on the ideas repo. https://github.com/statamic/ideas

**Comment by stuartcusackie** [comment]
Done both ;)
