### ISSUE TITLE
Partials only have access to array data but not strings or other data when inside a collection tag

### ISSUE THREAD

**Issue by PhilippeGauthier** [statamic/cms#1859]
I'm using a partial inside a collection tag like so:

```
    {{ collection:projects }}
    <div class="col-span-4">
        {{ partial:card  }}
    </div>
    {{ /collection:projects }}
```
The data for one of the projects might be something like this:

```
description: very nice project
materials:
  - material 1
  - material 2
```

Inside the partial i've got something simple like:
```
{{ description }}
{{ materials }}{{ title }}{{ /materials }}
```

The materials array is rendered but `description` isn't. Nor is any built in variable like `url` or `id`. 
  
## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.45

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by cgrisar** [comment]
+1

**Comment by jasonvarga** [comment]
Please give the issue a thumbs up reaction rather than leaving a +1 comment.

**Comment by cgrisar** [comment]
@PhilippeGauthier  you might want to check your filename. Does it end with .antlers.html ?
ending filenames with plain .html does not show variables like url, ...

**Comment by cgrisar** [comment]
@jasonvarga I think the issue may be closed. It looks like it's the same thing I encountered a couple of days ago
