### ISSUE TITLE
No indication a Publish Form is being saved.

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1861]
## Bug Description

Saving a Publish Form is quite slow (at least in my case), and the Save button does not have a "saving" state so I can't tell if I've actually clicked on the button or not.

## How to Reproduce

Use my super slow Publish form (can share) and save.
## Environment

**Statamic version:** 3.0.0-beta-28

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
The flash message is how you know it saved, not the button itself. Updating the button too would be a sizable refactor I don't want to get into right now because it's not always inside Vue.

**Comment by edalzell** [comment]
could a "saving..." message be shown then? that stays visible until it is saved?

**Comment by jackmcdade** [comment]
Same thing, that area is sometimes in Vue, sometimes in PHP, sometimes injected elsewhere – it would be a full day refactor to mess with it right now.
