### ISSUE TITLE
Code field in blueprint doesn't get any height on initial load

### ISSUE THREAD

**Issue by vannut** [statamic/cms#1866]
## Bug Description
When using the `code` field type in a blue print it initially renders without any height. After clicking in the code-editor it expands to the full height of its contents. 
Also, the line-numbers seem not to push the code to the right.

## How to Reproduce
Add a code-field to a Blueprint used in a global

## Extra Detail
On initial load:
![Schermafbeelding 2020-05-26 om 10 56 01](https://user-images.githubusercontent.com/7419859/82881383-eb708f80-9f3f-11ea-883a-201239d600be.png)

After a click inside the field:
![Schermafbeelding 2020-05-26 om 10 59 22](https://user-images.githubusercontent.com/7419859/82881438-fe835f80-9f3f-11ea-9d1d-a91ab6f3be3f.png)

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.4.5

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
What browser are you using?

**Comment by vannut** [comment]
This is on Chrome 81.0.4044.138

**Comment by sauerbraten** [comment]
We also see the issue with the line numbers getting rendered on top of the content:
![Screenshot_2020-06-05 DER SPIEGEL - default ‹ Seitenkonfiguration ‹ Sammlungen ‹ Statamic](https://user-images.githubusercontent.com/1760908/83858274-89bcdc00-a71c-11ea-9419-0b5c361cab91.png)

**Comment by sauerbraten** [comment]
The line number issue doesn't happen for us when using 6aef80817764504c45d4330e10646761f81a684c (i.e. was fixed sometime earlier).

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
