### ISSUE TITLE
Stopped working with Symfony 5.1.0

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#1882]
## Bug Description
Updating composer package today loaded the latest Symfony release `v5.1.0` and Statamic stop working with this version.

## How to Reproduce
run `composer update`

## Extra Detail
**the error :**
```php
TypeError
Argument 2 passed to str_contains() must be of the type string, array given, called in [...]/vendor/statamic/cms/src/View/Antlers/Parser.php on line 1182
```
**the error stack trace :**

<img width="961" alt="Screenshot 2020-05-31 at 10 24 08" src="https://user-images.githubusercontent.com/10623367/83347958-028cf400-a329-11ea-9303-417feabe63cc.png">

## Environment

**Statamic version:** 3.0.0-beta.28

**PHP version:** 7.4.6

**Install method:** Fresh install from `statamic/statamic`

**Comment by rosswintle** [comment]
I'm seeing this too.

The Statamic `Parser.php` does

```
str_contains($key, [':', '.'])
```

Which as far as I can see was never allowed in the [PHP8 RFC for str_contains]( https://wiki.php.net/rfc/str_contains)

(Symfony is just polyfilling PHP8 by the looks of things)

I fixed this by changing that line to:

```
      if (! (str_contains($key, ':') || str_contains($key, '.'))) {
```

But there may be a more efficient way.

**Comment by edalzell** [comment]
I think they should use `Str::contains($haystack, $needles)` instead.

**Comment by edalzell** [comment]
@rosswintle / @jimblue  can you confirm my suggestion works?

**Comment by jimblue** [comment]
Just tried both :
// If there was no scope glue, there's nothing more we can check.
```php
if (!(Str::contains($key, ':')) || Str::contains($key, '.')) {
          return [false, null];
}
```
and
```php
// If there was no scope glue, there's nothing more we can check.
if (!(str_contains($key, ':') || str_contains($key, '.'))) {
         return [false, null];
}
```
both are working 👍

**Comment by jasonvarga** [comment]
Looks like that new helper from Symfony gets loaded before Laravels.  Neat.

Decent example why global functions aren’t a great idea.

**Comment by bakerkretzmar** [comment]
For now, on Forge at least, a quick

```bash
sed -i 's/str_contains/Str::contains/g' vendor/statamic/cms/src/View/Antlers/Parser.php
```

right after `composer install` will patch this up.

**Comment by jimblue** [comment]
Tks @jasonvarga ! 🎉

**Comment by jesseleite** [comment]
To be fair, Laravel deprecated `str_` and `arr_` global functions a while ago, in favour of their `Str` and `Arr` classes respectively.  Good change 👍

**Comment by jasonvarga** [comment]
![](https://media.giphy.com/media/Nl6T837bDWE1DPczq3/giphy.gif)

https://www.youtube.com/watch?v=E55t0lnp_8M
