### ISSUE TITLE
Math modifiers break when used with numeric variable in context

### ISSUE THREAD

**Issue by mattbit** [statamic/cms#1900]
## Bug Description
Antlers math modifiers (`divide`, `multiply`, `subtract`, …) break when using a context variable which is numeric, raising exception `Call to a member function value() on int`.

## How to Reproduce

I am calculating a ratio using Antlers modifiers using variables `height` and `width` obtained inside a `glide:image` tag:
```
{{ glide:image width="600" }}
    My ratio: {{ height | divide:width }}
{{ /glide:image }}
```
Both `height` and `width` are well defined and have integer value. I obtain an exception: `Call to a member function value() on int`.

## Extra Detail

I think the problem lies in `CoreModifiers::getMathModifierNumber`, due to the changes introduced in https://github.com/statamic/cms/commit/15edcb66eaad3bb2bd5a6d2892bd1bbea1bed8fa. After getting the value of the variable from the context, it tries to call `value()` and fails miserably…

## Environment

**Statamic version:** 3.0.0.-beta-29

**PHP version:** 7.3.17

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by sebabal** [comment]
Any workarounds for this?

**Comment by mattbit** [comment]
> Any workarounds for this?

In my case, I created a custom modifier. Quite easy to get started with `php please make:modifier AddonName`.
