### ISSUE TITLE
Error on linking container to a bard fieldtype

### ISSUE THREAD

**Issue by peimn** [statamic/cms#1903]
## Bug Description
There is an error while trying to link a container to a Bard fieldtype
## How to Reproduce
Try to add a Bard fieldtype to default blueprint then in bard's settings try to link a container
## Extra Detail

![image](https://user-images.githubusercontent.com/5695187/83962803-a7717900-a8b5-11ea-89b5-a29eae69789e.png)

## Environment
**Statamic version:** 3.0.0.-beta-29

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by edalzell** [comment]
I think this is related to https://github.com/statamic/cms/issues/1914 and https://github.com/statamic/cms/issues/1896
