### ISSUE TITLE
Search Index Not Auto-Updating After an Edit is Made in the CP

### ISSUE THREAD

**Issue by twd3** [statamic/cms#1910]
I've been testing search index updating (thanks for that new cp utility) and I thought if you edit something in the CP it is supposed to update the search index automatically. It is not.

**How to Reproduce:**
Configure your search, I am just using default with a couple collections and one additional field added other than title. Edit an entry in one of the collections you have configured in search to have a super custom word and save the entry. Go to the frontend and search said super custom word. You'll get no results. Now go use the manual index update under utilities to update the index and go back to the frontend and search custom word again. You'll get a result.

**search.php**

    'indexes' => [
        'default' => [
            'driver' => 'local',
            'searchables' => ['collection:blog', 'collection:pages', 'collection:faqs', 'collection:testimonials'],
            'fields' => ['title', 'page-bard', 'blog-post-bard', 'faq-bard', 'testi-bard'],
        ],
    ],

**Side Note:** I did add "search_index: default" to my collections yaml files...from:
https://github.com/statamic/cms/issues/1337

**Statamic version:** 3.0.0.-beta-30

**PHP version:** 7.4.6

**Install method:**
Fresh install from `statamic/statamic`

**Comment by Buffalom** [comment]
Not sure if I'm wrong but the `contains` method in `Searchables` looks wrong to me.
[Here](https://github.com/statamic/cms/blob/99179ec4ed7aea848d67e21a2553e05663d7b4d7/src/Search/Searchables.php#L62) `$this->all()` returns a collection of Entries in case of a searchable `collection:posts` and `->has($searchable->id())` looks for the entry's id as an index but the returned collection only contains numeric indexes.

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
