### ISSUE TITLE
Multisite question

### ISSUE THREAD

**Issue by RickCogley** [statamic/cms#1912]
Hi - I searched the statamic v3 docs for "language", "multilingual", "locale", i18n and so on, could not find anything, and finally happened on "multisite" by chance; I am not even sure how I finally found it. Perhaps the pages could be edited to include some of the more common keywords for this kind of feature? 

Anyway, when I did `php please multisite` I got a little confused on what I need to do to add a locale. At first I said "no" to the initial question, then thought perhaps it is supposed to be "default". 

When I ran the command a second time, accepted "default" as the name for English, and added "jp", you can see from the below result that the locale is set to the same as the English one, rather than ja_JP. Maybe this is by design and you just have to edit `config/statamic/sites.php` to correct the problem? 

Also, should I leave the default locale English as "default" or, change it to "English"? 

```
~/d/cool-site ❯ php please multisite                                                                            

 The current site handle is [default], content will be moved into folders with this name. Is this okay? (yes/no) [no]:
 >

[✗] Change the site handle in config/statamic/sites.php then try this command again.
~/d/cool-site ❯ php please multisite                                                                            

 The current site handle is [default], content will be moved into folders with this name. Is this okay? (yes/no) [no]:
 > yes

 Handle of the second site [two]:
 > jp

[✓] Collection [articles] updated.
[✓] Collection [pages] updated.
[✓] Global [settings] updated.
[✓] Done!
[!] Update config/statamic/sites.php's sites array to the following:
[
    'default' => [
        'name' => 'Statamic',
        'locale' => 'en_US',
        'url' => '/',
    ],
    'jp' => [
        'name' => 'jp',
        'locale' => 'en_US',
        'url' => '/jp/',
    ],
]
```

**Comment by jackmcdade** [comment]
Hey there, apologies for letting this issue get a bit stale (we were pretty heads down getting v3 ready for launch). Do you still need help or have you sorted everything out at this point?

**Comment by jackmcdade** [comment]
I haven't heard back for 2 weeks so I'm going to close this, but please reopen if you have more info that we can use to help!
