### ISSUE TITLE
Link collection while creating relationship (entries) fieldtype in cp doesn't work

### ISSUE THREAD

**Issue by twd3** [statamic/cms#1914]
Link collection while creating relationship (entries) fieldtype in cp doesn't work.

![Untitled-1](https://user-images.githubusercontent.com/16004958/84294338-4096ce80-ab06-11ea-9556-2a5fb1c46105.jpg)

Go to cp and add a new entries fieldtype to a blue print then try to link a collection. It doesn't load anything.

**Statamic version:** 3.0.0.-beta-30

**PHP version:** 7.4.3

**Install method:**
Fresh install from `statamic/statamic`

**Comment by khangvo88** [comment]
I confirm this bug in Statamic 3.0.0.-beta-30.

The older version 3.0.0.-beta-28 works fine

**Comment by edalzell** [comment]
I think this is related to https://github.com/statamic/cms/issues/1903 and https://github.com/statamic/cms/issues/1896
