### ISSUE TITLE
JS Memory Leak in Replicator-Fieldtype

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1915]
## Bug Description
When working in a Replicator Fieldtype it has been noticed that the memory usage is constantly increasing. The best way to reproduce the behaviour is to collapse and expand the Replicator-Sets more often. After a short time it is no longer possible to work on the page. When scrolling, the page builds up with delays, hover states are no longer displayed and an element often reacts to the click with a long delay. It is also no longer possible to open the Live Preview.

## How to Reproduce
1. create an entry with multiple replicator sets
2. remain in the normal view
3. change several times between collapsing and expanding (about 30 times)
4. scroll on the page or try to place a new set between two sets

## Extra Detail

<img width="1428" alt="Bildschirmfoto 2020-06-11 um 11 40 35" src="https://user-images.githubusercontent.com/54707973/84371255-a3a56580-abd9-11ea-8b3e-ec720713340c.png">

![output](https://user-images.githubusercontent.com/54707973/84371907-a5bbf400-abda-11ea-99e6-aaddfe246add.gif)

## Environment

**Statamic version:** b4b991472c37cbe02070e4b18557e3604583baca

**PHP version:** 7.3.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by sauerbraten** [comment]
Thankns for looking into this!

After your fix, performance got better, but it still feels like memory is leaking somewhere. Simply expanding/collapsing all the sets makes the memory grow, in one of our tests from 130MB to 640MB within one or two minutes of collapsing and expanding continously.

It's also still janky, for example when the tab is in the background and becomes active again. When licking somewhere immediately after switching over to the tap takes a long time to get a response. It recovers faster than before, but there is still something fishy.
