### ISSUE TITLE
`{{ taxonomy :use=something }}` doesn't work due to augmentation

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1917]
## Bug Description

If you have a taxonomy in content (not a term) and want to list the terms with `{{ taxonomy :use="taxonomy-field" }}` you get an error about expecting an array and getting an Object.

## How to Reproduce

1. Add a `Taxonomy` field to some content, let's call it `category`.
2. Add a valid taxonomy to that field.
2. In a template for that content, try:
```
{{ taxonomy :use="category" }}
  here
{{ /taxonomy }}
```

## Environment

**Statamic version:** 3.0.0-beta-30

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
