### ISSUE TITLE
Better reporting for duplicated entry ids

### ISSUE THREAD

**Issue by vladdu** [statamic/cms#1925]
If two entries get the same id (through manually copying the file, for example), the error given is " Call to a member function id() on null" at statamic/cms/src/Stache/Stores/Store.php(70), which is very unhelpful.

v2 did only had a problem with that when one would view the entry, so when migrating the site, one has no idea which entry it is, only the collection.

I think it would be much better to let the user know what is the cause and where it occurs. 

## How to Reproduce

Create entries with same id and refresh the stache.

## Environment

**Statamic version:** 3.0.0.-beta-30

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/cms`

**Comment by robdekort** [comment]
Still a valid idea in 3.0.10

**Comment by damcclean** [comment]
I looked into adding a better error message for this but gave up after an hour. For the meantime, I've [built a script](https://gist.github.com/damcclean/8124d22cd4685d76d37aeb0cc0871db8) that will identify any duplicate IDs and replace them with new ones (if you want). 

Hopefully that's a good workaround.
