### ISSUE TITLE
Unknown path in assets makes it really hard to navigate

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#1927]
## Bug Description
Had a talk with a client that pointed out that he often gets lost in the assets caused by he can't see the path of the current folder.

Adding the path at the top (just like in v2) would make it so much easier to navigate through the assets folder structure.

From v2 doc:
![statamic-v2-asset-path](https://user-images.githubusercontent.com/43215436/84594642-f9854200-ae53-11ea-8ef6-08d4c180f7b8.png)

I thought about adding this to #ideas, but then again... I see this as a missing function - not a new breaking idea.

## Environment

**Statamic version:** 3.0.0.-beta-30

**PHP version:** 7.4.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ReneWeCode** [comment]
Pls keep this issue in mind.
For those who want a structured asset management with lots of folders and subfolders it's required to be able to see the actual path.

**Comment by jasonvarga** [comment]
The path is in the URL, at least. Not the solution you want, but something to be aware of until then anyway.
