### ISSUE TITLE
Link field toggle removes the input

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#1928]
## Bug Description
Link field toggle removes the content.
Maybe the toggle should be optional. No other fields has this toggle to activate/deactivate.

## How to Reproduce
Type something into the link field.
Use the toggle to "disable" the link. Activate the link again, and then ... dadadam ... the content is gone.

## Extra Detail

![linkfieldtoggle](https://user-images.githubusercontent.com/43215436/84605228-07f74c00-ae9c-11ea-9bc2-ec7e856bd809.gif)

## Environment

**Statamic version:** 3.0.0.-beta-30

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by FlorianMoser** [comment]
I think it is normal behavior, that the variable disappears when you hide a field.

But I second that: why should there be a toggle button by default? It is cumbersome and takes up additional space, often hiding the input field.

<img width="326" alt="grafik" src="https://user-images.githubusercontent.com/8578668/92090376-a5915600-edcf-11ea-9c98-c4b334b94d6a.png">

**Comment by jackmcdade** [comment]
What fieldtype is this? I don't recognize it...

**Comment by edalzell** [comment]
> What fieldtype is this? I don't recognize it...

The `Link` one.

**Comment by jackmcdade** [comment]
Ohh okay right, gotcha
