### ISSUE TITLE
Unable to link specific collections to entries fieldtype

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#1929]
## Bug Description
Can't link to a specific collection for the entries fieldtype. An error 500 is being thrown.

## How to Reproduce
Create a new entry field in a blueprint and try to link to a specific collection.

## Extra Detail
Error message: Call to undefined method Statamic\Fieldtypes\Collections::getSelectionFilters()

## Environment
Laravel Valet

**Statamic version:** 3.0.0.-beta-30

**PHP version:** 7.4

**Install method (choose one):**
- Used v3 install from `statamic/statamic`

**Comment by jonassiewertsen** [comment]
I can confirm this. Having the same issue right now.
