### ISSUE TITLE
Error 500 if linked collection is renamed

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#1935]
## Bug Description
Currently, if a collection is being renamed (the handle),  an error 500 is thrown if an entry is tried to be edited or created where the renamed collection is linked as an entries fieldtype.  It would be great, if instead of an error, a screen is given to relink the renamed collection.

## How to Reproduce
Link a collection inside a blueprint. Rename the collection afterwards.

## Extra Detail
I know this is not a bug,  but it would be great if statamic would at lest give a clearer error message instead of throwing an error 500.

## Environment
Laravel Valet

**Statamic version:** 3.0.0.-beta-30

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Fixed in beta 31

**Comment by robdekort** [comment]
A screen to relink might be a bit much, but I agree, a more explicit error message would be nice.

**Comment by jasonvarga** [comment]
Fixed by #2422
