### ISSUE TITLE
500 when selecting a folder in asset fieldtype. 

### ISSUE THREAD

**Issue by thinkcreative-matt** [statamic/cms#1936]
## Bug Description
Can't select a folder when adding an assest to a blueprint. 

## How to Reproduce
All this is done in the control panel
- Create a new blue print
- add asset fieldtype
- link to a conatiner
- select "link to existing" under folder. 

## Extra Detail
This is what is returned from the network tab. 
"Call to undefined method Statamic\Fieldtypes\AssetFolder::getSelectionFilters()"

## Environment

**Statamic version:** 3.0.0.-beta-30

**PHP version:** 7.4.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by thinkcreative-matt** [comment]
Also noticed that this occurs when linking to a collection on a replicator field. Same response in the netwrk tab

**Comment by ryangittings** [comment]
Yeah, same with an Entries fieldtype, too.

**Comment by thinkcreative-matt** [comment]
Jason just told me it's been fixed in beta 31. Just need to update.
