### ISSUE TITLE
Contains Modifier is buggy

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1939]
## Bug Description
Modifier contains with special chars inside the string there is no result shown. 
Without special chars all works fine.

## How to Reproduce
Use contains modifier with "-" inside the string.

## Extra Detail
category: Checklisten / Lastenhefte
slug: checklisten-lastenhefte

URL: 
```
{{ current_url }}?filter={{ category | slugify }}
/downloads?filter=checklisten-lastenhefte
```
Modifier:
```
{{ if (get:filter|contains:category|slugify ) }}
{{ title }}
{{ /if }}
```

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
The issue isn't the `-`, it's that you can't run a modifier on a variable being passed as an argument to another modifier. This might be a good use case for a custom modifier or a ViewModel to manipulate the data _before_ it gets to the view.
