### ISSUE TITLE
{{ if {collection:count in="collection_name" taxonomy:year="2019"} > 0}} throws an error when taxonomy condition is added

### ISSUE THREAD

**Issue by Krzemo** [statamic/cms#1945]
## Bug Description
When a taxonomy condition is added to collection:count based "if" statment i.e.: {{ if {collection:count in="collection_name" taxonomy:year="2019"} > 0}} an error is thrown:
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/1293123/84928250-6277ee80-b0ce-11ea-93f0-6e08093636fc.png">
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1293123/84928280-6f94dd80-b0ce-11ea-8bb6-d9da30ea2f29.png">

It happens both if filtered collection has entries or not.

## How to Reproduce
Try to check it there are entries in collection with count and taxonomy filter added.
<img width="625" alt="image" src="https://user-images.githubusercontent.com/1293123/84928645-0cf01180-b0cf-11ea-8bbc-37b40c457169.png">

## Extra Detail
When taxonomy filter is removed - everything works fine.
<img width="421" alt="image" src="https://user-images.githubusercontent.com/1293123/84928799-41fc6400-b0cf-11ea-9a23-a3b819933cdc.png">

## Environment
MacOs 10.4.16, Valet, PHP 7.3.18

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.3.18

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by Pfeifakopf** [comment]
The same error with:
`{{ if { collection:count in="dates" :taxonomy:tags="tags" } > 0 }}`

**Comment by robdekort** [comment]
Reproduced. Still an issue today.

**Comment by robdekort** [comment]
Go away bot, I don't like you.

**Comment by edalzell** [comment]
I reproduced this with a plain `list:exists="true"` filter, so it's not a taxonomy thing.

**Comment by edalzell** [comment]
> might be related:
> chaining on collection:count modifier doesnt seem to work in general. example:
> 
> `{{ collection:count in="teasers" divide="3" }}`
> 
> divide is ignored.

That's not going to work as `collection` is a tag.

**Comment by alexmilde** [comment]
thanks @edalzell  
is there any built in way to do this.? i wrote my own modifier for this - as i couldn't figure out the built in way.
