### ISSUE TITLE
Action redirects stopped working

### ISSUE THREAD

**Issue by aryehraber** [statamic/cms#1946]
A little while ago, support for redirects in Actions was added and worked great -- I used this feature in my Impersonator addon on the Users data-list view.

After adding this feature, I didn't test it again until now, but it looks like the `Actions.js` component was updated to support downloads too (awesome!) but it seems this is causing issues for redirects. I only had a quick test `console.log()`ing the response, but it seems it's not a regular json response anymore but instead it's a Blob:
https://github.com/statamic/cms/blob/master/resources/js/components/data-list/Actions.js#L38

For reference, here's the relevant code in Impersonator:
https://github.com/aryehraber/statamic-impersonator/blob/statamic-3/src/ImpersonatorAction.php#L44-L51

Let me know if you need further details!

**Comment by riasvdv** [comment]
Running into the same issue
