### ISSUE TITLE
Height of textareas is not set when in another tab

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#1952]
## Bug Description
Height of textareas is not set. Resizing the window or typing anything sets the height correct. 

## How to Reproduce
Create a textarea and type more than three lines into it.
Save and reload page.

## Extra Detail

![Skærmbillede 2020-06-18 kl  18 05 47](https://user-images.githubusercontent.com/43215436/85045264-06c16a00-b18f-11ea-99a6-7573306a090f.png)

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
I can't recreate this. What browser are you using?

**Comment by ReneWeCode** [comment]
Chrome. But it also happens in Firefox.
Happens for all textareas, also those inside replicators and grids.
Same goes for incognito without any browser extensions.
And the console doesn't gives any errors.

**Comment by jasonvarga** [comment]
This only happens if the field is in another blueprint tab.

If it's in the one you see when the page loads, it's fine.

**Comment by jelleroorda** [comment]
Open sesame
