### ISSUE TITLE
Email field is not outputting the proper field type value in form

### ISSUE THREAD

**Issue by zacksmash** [statamic/cms#1960]
## Bug Description
When iterating through a `{{ form }}` tag, if the field is set to type of 'email' in the blueprint, it does not print email as the {{ field.type }}, it prints 'text'. 

## How to Reproduce
- Create a form, create a blueprint.
- In the blueprint, add a text field, with a type of 'email'.
- In an antlers file, use the `{{ form }}` tag to iterate though the fields.
- You can either do `{{ field | dump }}` to see the 'type' or just output the field.

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by vguerrerobosch** [comment]
Hi! Notice you also have available the variable `input_type`. So in your `resources/views/vendor/statamic/form/fields/text.blade.php` you can do something like

```blade.php
<input
  id="{{ $handle }}"
  type="{{ $input_type ?? 'text' }}"
  name="{{ $handle }}"
  value="{{ $old }}"
  class="w-full"
  @if (in_array('required', explode('|', $validate))) required @endif
>
```
or the antlers equivalent if you prefer.

**Comment by zacksmash** [comment]
@vguerrerobosch That's what I ended up doing, but it seems like expected behavior would be to output the type you select in the admin as the output of `{{ field.type }}`.

**Comment by jasonvarga** [comment]
There is no fieldtype named `email`. It would be a `text` fieldtype with an `input_type` of email.
