### ISSUE TITLE
Can't set or update entry parent after creation

### ISSUE THREAD

**Issue by bakerkretzmar** [statamic/cms#1961]
## Bug Description

Entry items in an ordered collection created by clicking the little options menu and selecting "Create Child Entry" have a `parent` attribute set to the UUID of their parent—this attribute is not updated when the item is moved around in the collection structure or manually attached to a different parent entry, and it's not present at all on entries created any other way.

## How to Reproduce

Create a new collection and make it orderable. View it in drag-and-drop mode. Create an entry, then click the three dots on the right and create a child entry. That child has a `parent` attribute set to the ID of the parent.

Go back to the collection view and move the child out from under the parent—the `parent` attribute doesn't update. Create another entry and move the child under that one—doesn't update. Edit the child entry and unlink it from its parent then link it to a different entry—doesn't update.

Create a new entry from scratch—it's created without a `parent` attribute. Link it to a parent—still no `parent` attribute. Drag it to be nested under another entry—no `parent` attribute.

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4

**Install method:** Fresh install from `statamic/statamic` (I think, and then manually upgraded to Laravel 7)

**Comment by bakerkretzmar** [comment]
I also tried explicitly adding a "Parent" field to the Blueprint for these collection entries, and the behaviour is the same.

**Comment by jasonvarga** [comment]
You shouldn't see `parent` on the entry, ever.
When it's not showing (which sounds like most of the time), that's correct behavior.
When it is, after creation, it shouldn't be there. Thanks for pointing that out!

**Comment by bakerkretzmar** [comment]
Interesting. Is there any way to get all of the children of a specific collection item? I was trying to filter on the id of the parent.
