### ISSUE TITLE
Slow page load when running large number of locales

### ISSUE THREAD

**Issue by mattias-persson** [statamic/cms#1971]
## Bug Description
We have a site with 65 different markets. When the page loads Statamic seems to iterate through all of them and build a tree of all pages on all markets. This takes over 100MB of memory and causes the page to load for at least 2-3 seconds.

This seems to be caused by the following code in `Statamic\Http\Controllers\FrontendController@index`: 
```
if ($data = Data::findByUri($url, Site::current()->handle())) {
    return $data;
}
```

## How to Reproduce
Create a site with many locales. Load it.

## Environment

**Statamic version:** 3.0.0.-beta-{?}

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
That's a lot of sites. 😱

**Comment by jasonvarga** [comment]
Can you elaborate on your setup? Why do you have so many sites? How are you intending to use that?

Can you show your config/statamic/sites.php ?

**Comment by mattias-persson** [comment]
It's a global site and we had no problem running the same setup using Statamic 2 🙂  Here's our `config/statamic/sites.php`: https://pastebin.com/yavxa8M1.

Since several countries may have multiple languages it quickly turns into a lot of sites.

**Comment by johanlinander** [comment]
@jasonvarga Any comment on this issue? It is stopping us from using Statamic 3 at the moment.

**Comment by jasonvarga** [comment]
Could you contact us at support@statamic.com ? We'd like to learn more about your use case you probably don't want that sort of information here in the public.

**Comment by jasonvarga** [comment]
By adding the 65 sites to my sites config, it doesn't slow down my front-end. More details are needed. Closing this and we can continue in a support request.
