### ISSUE TITLE
Handle exception when clearing non-existent static cache

### ISSUE THREAD

**Issue by rosswintle** [statamic/cms#1972]
## Bug Description

When using `php please static:clear`, if the `public/static` directory does not exist you get a `Symfony\Component\Finder\Exception\DirectoryNotFoundException`

It would be nice if this could be detected and handled more nicely with an error message incorporating the expected Statamic humour. 😉

## How to Reproduce

I've not done a from-scratch install to show a minimal reproduction but I would expect the following to work:

1. Do a clean install of Statamic 3
2. Run `php please static:clear`

## Extra Detail

You're probably wondering why on earth you would try to clear a cache that doesn't exist? Well, I was trying out different cache strategies. I had changed from no caching to "half" caching and wanted to make sure my static cache was clear so I wasn't accidentally loading an old statically-cached file.

Full error message output:

```
$ php please static:clear

   Symfony\Component\Finder\Exception\DirectoryNotFoundException  : The "/home/oikosdigital/oikos.digital/public/static" directory does not exist.

  at /home/oikosdigital/oikos.digital/vendor/symfony/finder/Finder.php:602
    598|             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? GLOB_BRACE : 0) | GLOB_ONLYDIR | GLOB_NOSORT)) {
    599|                 sort($glob);
    600|                 $resolvedDirs = array_merge($resolvedDirs, array_map([$this, 'normalizeDir'], $glob));
    601|             } else {
  > 602|                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
    603|             }
    604|         }
    605|
    606|         $this->dirs = array_merge($this->dirs, $resolvedDirs);

  Exception trace:

  1   Symfony\Component\Finder\Finder::in("/home/oikosdigital/oikos.digital/public/static")
      /home/oikosdigital/oikos.digital/vendor/statamic/cms/src/Filesystem/FilesystemAdapter.php:92

  2   Statamic\Filesystem\FilesystemAdapter::getFolders("/home/oikosdigital/oikos.digital/public/static")
      /home/oikosdigital/oikos.digital/vendor/statamic/cms/src/Filesystem/AbstractAdapter.php:141
```

## Environment

* Ubuntu 20.04 with Laravel Forge

**Statamic version:** 3.0.0.-beta-30

**PHP version:** 7.3.9

**Install method (choose one):**

- Existing Statamic site

**Comment by Konafets** [comment]
I tried to reproduce this on a vanilla installation and did not hit that error. To get this error you must: 

- Set the caching strategy to 'full' in `static_caching.php`.
- Call `php please static:clear` right after switching the strategy, because Statamic creates the folder on the first hit on a  frontend route.

However, the exception should be catched and transformed into an nice error message.

**Comment by rosswintle** [comment]
Nice. Thanks.

While I'm here I wonder if it's worth raising the fact that - I think - a static cache won't be cleared if you've set the caching strategy to `null`.

So if I do:

* Set caching strategy to 'full'
* Add nginx rules for static caching
* Visit some pages (to generate cache files)
* Set caching strategy to `null`
* Run `please static:clear`

If I do this, the static cache is NOT cleared and my site STILL serves the cached files.

This seems confusing, I feel like `please static:clear` should clear the static cache regardless of what strategy is set?

**Comment by Konafets** [comment]
I see three options:

* Bring it to the users attention, that he/she uses the null cache in case the `public/cache` folder exists
* Delete the folder also when the `null` strategy is used
* Delete the cache folder when the `null` strategy is used and the user hits the frontend first time. This is consistent to the other way around as the cache folder gets created when strategy is `full` and the user hits the frontend.
