### ISSUE TITLE
Password resetter [activations] is not defined

### ISSUE THREAD

**Issue by sebabal** [statamic/cms#1973]
## Bug Description

I am getting this "Password resetter [activations] is not defined." message after going to the user activation link eg: http://sg.homestead/!/auth/activate/204847e8eace205d4355d6bae1194bbe62821b0244f0f9f12535af78b810d856

## How to Reproduce

1. Create user
2. Try to activate the user with the generated link

## Extra Detail

https://flareapp.io/share/o7A2pz5p#F53

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.3.19

**Install method (choose one):**

- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Can you provide your `config/auth.php`?

**Comment by sebabal** [comment]
Jason sorry for the delay here it is...

```
<?php
​
return [
​
    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */
​
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
​
    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */
​
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
​
        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
​
    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "statamic", "database", "eloquent"
    |
    */
​
    'providers' => [
        'users' => [
            'driver' => 'statamic',
        ],
    ],
​
    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */
​
    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],
​
];
```

**Comment by jasonvarga** [comment]
Grab the updated auth.php from statamic/statamic

**Comment by sebabal** [comment]
Jason sorry which file? I am not sure where that one is located....

**Comment by sebabal** [comment]
Nevermind I was looking at the wrong repo..duh!

**Comment by sebabal** [comment]
Jason, now the activation page is displaying but we are getting:

"Password reset token is invalid"  

...when we try to setup the password.

Any ideas?

**Comment by jasonvarga** [comment]
What URL are you seeing that error on?

**Comment by sebabal** [comment]
It's the URL for activation that you get when you create a user...

eg: http://sg.homestead/!/auth/activate/948dc3b231a699b5b3283d038f59aa2c23fcdb810059e830cabd876fdd6e935d

**Comment by jasonvarga** [comment]
Is it an old token? Try the whole reset password workflow again. Don't click a link from an existing email.

**Comment by sebabal** [comment]
That link was used a minute after receiving the email to active the user. We will try the whole reset workflow and let you know.

**Comment by jackmcdade** [comment]
Is this still an issue?

**Comment by sebabal** [comment]
Hi yes this is still an issue. 

The whole password reset workflow is working but the activation workflow is not.

I just tried again and got the same error...running the latest beta.

![image](https://user-images.githubusercontent.com/210946/86486711-6b092f80-bd32-11ea-933d-c9871d0bc025.png)

**Comment by sebabal** [comment]
I am sorry I think we need to split out the issue since the original problem got indeed resolved and then I encounter this other issue...

Do you want me to create a new issue?

Cheers

**Comment by jasonvarga** [comment]
I have this almost fixed locally. Don’t worry about it.

**Comment by twd3** [comment]
Just got this out of my log after trying to reset password that might be new to this issue:

[2020-07-14 00:07:55] local.ERROR: Password resetter [resets] is not defined. {"exception":"[object] (InvalidArgumentException(code: 0): Password resetter [resets] is not defined. at /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBrokerManager.php:65)

**Comment by twd3** [comment]
I just had to update the auth file in my config/statamic folder to get rid of this error.

**Comment by ReneWeCode** [comment]
Dunno if related, but when I create a user, then the activation link the user gets gives a 500.

**Comment by curtisblackwell** [comment]
I'm seeing this same issue. I just verified that I already have the latest `config/auth.php`.
