### ISSUE TITLE
Live Preview not updating when editing existing linked item

### ISSUE THREAD

**Issue by sebszocinski** [statamic/cms#1975]
## Bug Description
When creating a new item using "Create & Link item" in Live Preview, it updates the preview, however when editing an existing linked item it doesn't update the live preview after saving.

## Extra Detail
We've noticed in network log, the `preview` endpoint isn't being fired when saving.

## Environment
**Statamic version:** 3.0.0.-beta-31

**Comment by WiebkeVog** [comment]
I was still able to reproduce the bug with version 3.1.11.
