### ISSUE TITLE
Incorrect url generated for collection entries with /{mount}/{slug} on a multisite

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#1977]
## Bug Description
I do have a collection that is **mounted to a page entry**. If I change the route for it to ``/{mount}/{slug}`` I am getting an incorrect output for the urls. 

**My multisite has the following two sites:**
``de-de``, ``de-at``

**Outputted urls:**
``/de-de/de-de/blog/slug``

**Expected outputted urls:**
``/de-de/blog/slug``

## How to Reproduce
Create a multisite with an URL scheme as above (subdirectory style).

Create a collection and define a route for it with ``/{mount}/{slug}`` and mount it to a page entry. See the outputted url.

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4, Laravel Valet

**Install method (choose one):**
- Existing statamic v3 install

**Comment by jreviews** [comment]
Just wanted to add a quick note to say that this doesn't appear to be multisite specific. I have the same issue with the site running from a domain sub-directory. I see duplicate sub-dir in CP visit URL link and in the front-end when using `{{ url }}` it is tripicated.

**Comment by jasonvarga** [comment]
I can't replicate this. Can you show me your config/statamic/sites.php and your collections' yaml files?

**Comment by AndreasSchantl** [comment]
```php
'sites' => [

        'default' => [
            'name' => 'Deutschland',
            'locale' => 'de-DE',
            'url' => 'http://procty.test/de-de/',
        ],
        'de-at' => [
            'name' => 'Österreich',
            'locale' => 'de-AT',
            'url' => 'http://procty.test/de-at',
        ],
        'en-gb' => [
            'name' => 'Great Britain',
            'locale' => 'en-GB',
            'url' => 'http://procty.test/en-gb/',
        ],
        'it-it' => [
            'name' => 'Italia',
            'locale' => 'it-IT',
            'url' => 'http://procty.test/it-it/',
        ],
        'es-es' => [
            'name' => 'España',
            'locale' => 'es-ES',
            'url' => 'http://procty.test/es-es/',
        ],
        'en' => [
            'name' => 'International',
            'locale' => 'en',
            'url' => 'http://procty.test/en/',
        ],

    ]
```

Mike Martin has had the same problem as he pointed out on discord. he can share a config too!

**Comment by jasonvarga** [comment]
Ah yes okay I got it. The first site's url needs to be a subdirectory. Now @jreviews comment makes sense too. Thanks!
