### ISSUE TITLE
Collection: Passing unexisting value as taxonomy filter throws an error

### ISSUE THREAD

**Issue by Krzemo** [statamic/cms#1979]
#1740 Bug Description
1) Trying to filter a collection by a taxononmy:
`{{ collection:categories taxonomy:edition="2012" }}`
when passing a value that doesnt exist for that taxonomy an error is thrown

2) Same error is thrown when trying to pass a global variable (even if it exists in the scope - checked with dump line above)
`{{site_wide_settings:last_edition_date format="Y"}} //this returns expected and existing value
 {{ collection:categories taxonomy:edition="{site_wide_settings:last_edition_date format="Y" }" }} //this throws an error`

## How to Reproduce
1. Create taxonomy and some entries
2. Create a collection with entries assigned taxonomies from p1
3. In an antler, try to output collection entries filtered by taxonomy. Compare filtering with taxonomy existing values vs non existing.

## Extra Detail
![image](https://user-images.githubusercontent.com/1293123/85550683-7d43e900-b621-11ea-905e-a7d84f6ea85b.png)

## Environment
MacOS 10.14.6
Laravel Valet

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by Krzemo** [comment]
I just noticed that taxonomy valie prop in .md files is saved this way:
`taxonomy_edition_categories: 'edition::2019'`
so I tried to change my code to `{{ collection:categories taxonomy:edition="edition::2018" }}`

Same error is thrown - no difference.

More, it looks like error is thrown not only if there is no taxaonomy entry (i.e.: year 2021) but also when there are no collection items returned (i.e. year 2020 for which there has been no event yet and categories havent been defined).

**Comment by Krzemo** [comment]
Have you done any changes related to it in beta 33? I cannot pass a variavble as taxonomy filter anymore ... Its been throwing an error since upgrade to 33:
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1293123/86185974-08e4da80-bb38-11ea-8462-26f2d1b18ef7.png">

**Comment by jasonvarga** [comment]
I think this is resolved, but feel free to reopen if not.
