### ISSUE TITLE
Taxonomy title in API is always slug instead of title

### ISSUE THREAD

**Issue by goellner** [statamic/cms#1981]
## Bug Description
Taxonomy title in API is always slug instead of taxonomies title.

## How to Reproduce
Create a taxonomy and call the endpoint for it: api/taxonomies/blog/terms/news
check returned title, its the slug, not the title

## Environment

**Statamic version:** 3.0.0.-beta-31

**Comment by jasonvarga** [comment]
Sounds the same as #1982 - I'll close this one.
