### ISSUE TITLE
No locales variable in custom statamic Routes defined with Route::statamic()

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#1992]
## Bug Description
No locales variable/data available in a custom Route defined with ``Route::statamic()``.

## How to Reproduce
Create a Route with the above command and try to access the locales variable. It's not there and is not looped over.

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4, Laravel Valet

**Install method (choose one):**
- Used V3 install

**Comment by jasonvarga** [comment]
It's because the route isn't associated with a site. It's a global thing.

We can give this some more thought.

**Comment by AndreasSchantl** [comment]
That's true. But just to make sure we are talking about the same thing: I am missing that the [locales tag](https://statamic.dev/tags/locales#parameters) isn't working.

**Comment by jasonvarga** [comment]
Yup.

**Comment by sjclark** [comment]
> That's true. But just to make sure we are talking about the same thing: I am missing that the [locales tag](https://statamic.dev/tags/locales#parameters) isn't working.

There was a user in the chat confirming that `{{ locale:full }}` outputs nothing for them. However, it does appear to work within a tag in any example like this:
```
{{ locales current_first="true" }}
        <a class="locale__item" href="{{ url }}">
            <span class="locale__item__flag locale__item__flag--{{ locale:full }}"></span>
            <span class="locale__item__name">{{ locale:name }}</span>
        </a>
        {{ /locales }}
```
The docs indicate `Only applicable in the tag pair.` which seems a bit odd - presumably people would want to use their current locale outside a pair?

**Comment by damcclean** [comment]
I've labeled this issue as a 'discussion' as I didn't really feel like it was a bug (as custom routes aren't content, like Jason already pointed out).
