### ISSUE TITLE
Partials in a folder can't start w/ `_`

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#1995]
## Bug Description

According to https://statamic.dev/views#organize-by-type, you can put partials in a `partials` folder and they will be automatically found, which is true, as long as you don't prefix the name with an `_`, like you can do in the flat folder structure.

## How to Reproduce

Put your partials in a `partials` folder and ensure they start w/ `_`, `_nav.antlers.html`.
In a template, load it `{{ partial:nav }}`

## Extra Detail

The above DOES work if you leave in the folder but change the name to `nav.antlers.html`.

## Environment

**Statamic version:** 3.0.0.-beta-32

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by edalzell** [comment]
Code to update is around here: https://github.com/statamic/cms/blob/master/src/Tags/Partial.php#L22

**Comment by jasonvarga** [comment]
That’s intended. Use one or the other.

**Comment by edalzell** [comment]
Docs need updating. I'll PR later if I can.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/6069653/85933157-d82b4980-b888-11ea-83aa-fcbfb2a711df.png">
