### ISSUE TITLE
ReferenceError: mobileNavOpen is not defined, control panel pages blank

### ISSUE THREAD

**Issue by derekjones** [statamic/cms#1998]
## Bug Description

After logging in to the control panel, I get a flash of content, then this fatal console error, and an empty page.

## How to Reproduce

Log in to the control panel. Obviously this is environmental somehow and not some global bug affecting everyone or no one would be able to use Statamic. All pages seem to be affected, as manipulating the URL to get to different sections has no impact. The error below seems to indicate that the failure occurs when Statamic tries to instantiate Vue.js.

## Extra Detail

```
ReferenceError: mobileNavOpen is not defined
    anonymous vendor.js:3
    VueJS 9
    start Statamic.js:75
    <anonymous> dashboard:361
```

## Environment

**Statamic version:** v3.0.0-beta.33

**PHP version:** 7.3.12

**Browser:** Firefox Dev Edition 78.0b9, Safari 13.1.1

**Install method (choose one):**
- Upgrade from beta originally installed from `statamic/statamic`

**Comment by jasonvarga** [comment]
Does it happen in all your browsers?

**Comment by derekjones** [comment]
Yes, confirmed now in Chrome and Cliqz as well.

**Comment by jasonvarga** [comment]
Can you show the output of `composer update`?

**Comment by derekjones** [comment]
```
> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package webuni/commonmark-attributes-extension is abandoned, you should avoid using it. Use league/commonmark instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: intervention/httpauth
Discovered Package: intervention/image
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: statamic/cms
Discovered Package: wilderborn/partyline
Package manifest generated successfully.
> @php artisan statamic:install --ansi
Addon manifest generated successfully.
Copied Directory [/vendor/statamic/cms/resources/users] To [/resources/users]
Publishing complete.
Copied Directory [/vendor/statamic/cms/resources/dist] To [/public/vendor/statamic/cp]
Publishing complete.
Compiled views cleared!
Application cache cleared!
```

**Comment by derekjones** [comment]
Just for fun I blasted the `vendor` folder and redid a `composer install`, `composer cleancache`, no change.

**Comment by derekjones** [comment]
What I didn't do, however, is catch that this install was loading from a copy of `public/` assets that was not being updated in the build process. Nothing to see here, sorry for wasting anyone else's brain matter.

**Comment by jasonvarga** [comment]
Don't quite understand to be honest, but glad you worked it out!

**Comment by derekjones** [comment]
Essentially I was running many-months stale copies of the Statamic public vendor assets, and serving my domain out of that folder instead of just using `public/`

**Comment by MattRogowski** [comment]
@derekjones I have the same issue, how did you actually force it to rebuild the assets? My cp assets are also in ./public/vendor/statamic/cp/js, is this not right?

**Comment by jasonvarga** [comment]
Run php please statamic:install

**Comment by MattRogowski** [comment]
Thanks Jason! 🙏

**Comment by jasonvarga** [comment]
That should happen automatically when you composer update or install. Did you add the statamic install command to your composer.json? https://statamic.dev/installation#exising-laravel

**Comment by derekjones** [comment]
To be clear, my issue was from not running my static assets from the repo's default location, and never updating my build process to move things around. I've since simplified and eliminated that extra bit, since I can't even remember why I decided to do that in the first place 🤣

**Comment by MattRogowski** [comment]
I do have that in my composer.json, and can see it ran after I did composer update and the dates on the files suggested it had published them, but just didn't seem to be loading the new javascript on the page. Thought was aggressive Chrome caching but noticed the URLs have the version number appended to cache-bust. Strange, I'll monitor it next time I do a composer update, but likely just a local issue somewhere.
