### ISSUE TITLE
Header bar layout has spacing issues 

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#1999]
## Bug Description
On some sites the elements in the header bar are misaligned. It happens when:
- create a taxonomy, global set, role, asset container, blueprint, fieldset…
- edit a taxonomy, global set, role, asset container, blueprint, fieldset…

## How to Reproduce
- fresh install
- use as single-site or convert to multisite, that does not make a difference

<img width="2186" alt="Bildschirmfoto 2020-06-29 um 15 50 00" src="https://user-images.githubusercontent.com/8265902/86014655-e9a75980-ba20-11ea-90b4-d6991ffd4fa8.png">

## Environment

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
I'm not sure corrupt is the right word - it's just a flex css issue :)

**Comment by helloDanuk** [comment]
Sorry, I am not a native english speaker. But obviously you know what I meant :)




Am 29.06.2020 um 16:17 schrieb Jack McDade <notifications@github.com>:


I'm not sure corrupt is the right word - it's just a flex css issue :)

**Comment by jasonvarga** [comment]
What browser and OS are you using?

**Comment by helloDanuk** [comment]
macOS 10.15.5 
Safari 13.1.1



Am 29.06.2020 um 20:00 schrieb Jason Varga <notifications@github.com>:


What browser and OS are you using?

**Comment by jackmcdade** [comment]
<img width="1839" alt="Screen Shot 2020-07-03 at 4 31 37 PM" src="https://user-images.githubusercontent.com/44739/86496281-b3344c00-bd4a-11ea-91ad-19c8360aee0e.png">

Weird, I definitely don't see this...

**Comment by helloDanuk** [comment]
Mmmh, when I see your screenshot I think you have maybe tested on an 'edit page'-view? There, the header bar looks good for me too. It only happens on some pages, mostly on the 'create a…' and 'edit a…'-pages like: create a blueprinrt, …taxonomy, …asset container,  global set, role…

I tried again in save mode with a fresh install.

<img width="1512" alt="Bildschirmfoto 2020-07-06 um 09 33 02" src="https://user-images.githubusercontent.com/8265902/86569097-3a153e80-bf6e-11ea-8da2-78c4c2bd0cd6.png">


I might have found out, that it takes somehow the space of the underlying dropdown. But I don't know why it behaves like this.

<img width="853" alt="Bildschirmfoto 2020-07-06 um 09 53 14" src="https://user-images.githubusercontent.com/8265902/86569411-a7c16a80-bf6e-11ea-87de-f26c04cfec0b.png">
 
<img width="838" alt="Bildschirmfoto 2020-07-06 um 09 56 32" src="https://user-images.githubusercontent.com/8265902/86569651-038bf380-bf6f-11ea-92a3-cedc20b4b826.png">

**Comment by robdekort** [comment]
Yeah, I always notice this since a while. On Big Sur (latest beta) as wel as the latest Catalina. For me it happens when I click around in the CP and usually when I go to the edit page of a collection.

**Comment by robdekort** [comment]
This is what the console reports, might be related:
<img width="374" alt="Screenshot 2020-09-10 at 11 52 16" src="https://user-images.githubusercontent.com/69107412/92714135-18647900-f35c-11ea-80df-a4be78f98f82.png">

**Comment by robdekort** [comment]
Removed the above labels as it's very recreatable. Happens all the time. Click around in Safari, edit a page, add an entry and there you go.

**Comment by tao** [comment]
Yes, the same occurs when you resize the browser and it gets really confused sometimes...

![Screenshot 2020-12-22 at 09 25 57](https://user-images.githubusercontent.com/1446331/102861166-e02f0500-4437-11eb-90f7-8bf7df3f5bd0.png)

**Comment by jackmcdade** [comment]
This will be fixed in 3.1! 🎉

**Comment by jasonvarga** [comment]
Bummer, unfortunately it didn't fix it. Weird issue, sometimes it's fine, sometimes not. If I sit there refreshing the page, it'll randomly be broken or correct. If it's correct and I open up devtools, it'll fix itself.

Also noticed whenever this bug presents itself, it's not just the nav with the problem. If you're on an entry edit page, there will be no sidebar. It'll be in a tab (as if you've made the page really narrow).

**Comment by tao** [comment]
I often see this warning incrementing on the browser console when I resize the window: "ResizeObserver loop completed with undelivered notifications." Perhaps it's related?

**Comment by helloDanuk** [comment]
Just read the release notes. Should be fixed in 3.1 🎉
