### ISSUE TITLE
{{ if (collection == "pages") && (parent:slug != "home")  }} causes error

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#2001]
## Bug Description
{{ if (collection == "pages") && (parent:slug != "home")  }} causes error.

## How to Reproduce
{{ if collection == "pages" && parent:slug != "home" }}
{{ if collection == "pages" && page:slug != "home" }}
{{ if collection == "pages" AND parent:slug != "home" }}
{{ if (collection == "pages") && (parent:slug != "home") }}

All versions causes an error.

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Have you tried this?

```
{{ if {collection:handle} === 'pages' && {parent:slug} !== 'home' }}
  <!-- Whatever magic you need to do here... -->
{{ /if }}
```
