### ISSUE TITLE
A locale does throw an 500 error, when showing a 404 page.

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#2004]
If you do work with localization and am having a locales selector in the header, everything does work great. 

Should a 404 page been shown, with your header including locales, a 500 error will be thrown though. 

## How to Reproduce
- Create a multisite
- Create minimum 2 languages/sites
Use something like this in your 404 layout:
```php
{{ if site === 'default' }}
       {{ locales:da }}
             <a class="switch__link switch--language" href="{{ url }}">
                  {{ svg src="language" }}
               <span>DK</span>
             </a>
       {{ /locales:da }}
 {{ else }}
    ....
```
- Visit a non existing page to get redirect to your 404 template

## Environment

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by AndreasSchantl** [comment]
You probably could work around this error by wrapping that in an if and checking against the [response_code](https://statamic.dev/variables/response_code#content) for now.

**Comment by Pixney-William** [comment]
I kind of have this on a website with two locales and trying to add a menu
for selecting language. For me it it works fine on all 1st level pages
but as soon as you go `domain.com/level1/level2` it bombs out

```
{{ locales current_first=true }}
        <li>
            <a href="{{ url }}">{{ locale:name }}</a>
        </li>
 {{ /locales }}
```
