### ISSUE TITLE
Prepended text on fieldtype won't be output.

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#2007]
![Screenshot 2020-06-30 at 15 07 09](https://user-images.githubusercontent.com/38906163/86129902-aeba2a00-bae3-11ea-9be8-2c5a08742e33.png)
When having a prepended text, I would assume that the output would be

`https://fleggaard.dk`

Instead the output is

`fleggaard.dk`

**Statamic version:** 3.0.0.-beta-32

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
It's just a UI thing. For example if you wanted to prepend a `$` but only let your user enter a number.

You can prepend it in your templates with the ensure_left modifier. Or just the text itself.

```
{{ text ensure_left="https://" }}

{{ if text }}
https://{{ text }}
{{ /if }}
```
