### ISSUE TITLE
A none structured (1 level) collection shouldn't get the parent select field

### ISSUE THREAD

**Issue by studio1902** [statamic/cms#2012]
## Bug Description
When you have a collection that is just one level deep it shouldn't get the parent select field in it's blueprint. When you select a parent item it won't get saved.

## How to Reproduce
Create a non structured collection and add an entry.

## Extra Detail
<img width="1647" alt="Screenshot 2020-07-01 at 11 50 06" src="https://user-images.githubusercontent.com/4067523/86230440-59d4ed00-bb91-11ea-97c2-af3920ab6465.png">
<img width="1647" alt="Screenshot 2020-07-01 at 11 49 59" src="https://user-images.githubusercontent.com/4067523/86230443-5b061a00-bb91-11ea-9cb1-40390dbb2494.png">

## Environment

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.4.6

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
This is not a ghost post, this is from me. Issues don't seem to migrate properly when converting to a Github organisation.

**Comment by robdekort** [comment]
Leave!
