### ISSUE TITLE
Section fields shouldn't be listable at all

### ISSUE THREAD

**Issue by studio1902** [statamic/cms#2013]
## Bug Description
Section fields shouldn't be listable. You have to explicitly set listable: false otherwise they show up in list views. I don't thinkit makes sense for them to show up at all.

## How to Reproduce
Add a section field to a blueprint with default config. 

## Extra Detail
<img width="1184" alt="Screenshot 2020-07-01 at 11 57 05" src="https://user-images.githubusercontent.com/4067523/86230988-2181de80-bb92-11ea-9cf2-9d35a9b3e2f1.png">
<img width="1647" alt="Screenshot 2020-07-01 at 11 57 02" src="https://user-images.githubusercontent.com/4067523/86230990-234ba200-bb92-11ea-8f46-aca6458e22d7.png">

## Environment

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.4.6

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
This is not a ghost post, this is from me. Issues don't seem to migrate properly when converting to a Github organisation.

**Comment by damcclean** [comment]
I've submitted a pull request that should fix this bug: #2425.
