### ISSUE TITLE
Difference behavior between {{ collection:name }} and {{ nav:collection:name }}

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2014]
## Bug Description
`{{ nav:collection:name }}` listing not always all entries.

## How to Reproduce
1 Collection is ordered by structure, collection 2 by date:
Collection 1:
```
structure:
  root: false
  max_depth: 1
```
Collection 2:
```
date: true
```

`{{ collection:name }}` shows always all entries, but `is_current` is not working.
So use `{{ nav:collection:name }}` instead, where `is_current` is working. Now are the entries of collection 1 shown all, but for  collection 2 is just the current entry shown.

## Extra Detail
```
{{ collection:name }}
<li class="level_1{{ if is_parent || is_current }} active{{ /if }}"><a href="{{ url }}" class="link"><i class="fa-icon fas fa-caret-right"></i> {{ title }}</a></li>
{{ /collection:name }}
{{ nav:collection:name }}
<li class="level_1{{ if is_parent || is_current }} active{{ /if }}"><a href="{{ url }}" class="link"><i class="fa-icon fas fa-caret-right"></i> {{ title }}</a></li>
{{ /nav:collection:name }}
```

## Environment

**Statamic version:** 3.0.0.-beta-31
**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
The nav tag is only for navigations or collections with structures.
