### ISSUE TITLE
FormSubmissionsController throws error if null is stored through form submission.

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2016]
## Bug Description
If i don't enter a value for a field in a form and submits the form, in the YAML file the field handle is added with the value null. This has the control panel throw an error.

## Extra Detail
![image](https://user-images.githubusercontent.com/31292231/86294456-d9e06e80-bbf4-11ea-85be-ed3fa22d2021.png)
![image](https://user-images.githubusercontent.com/31292231/86294473-e238a980-bbf4-11ea-98e4-92470a345572.png)

## Environment

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by Pixney-William** [comment]
Any suggestion regarding what version i should downgrade to making it work?

**Comment by Pixney-William** [comment]
Downgrading to v30 works fine. S

Since i believe 32 had the glide bug, 30 is the versions id recommend downgrading to if anyone else has this problem.

**Comment by Pixney-William** [comment]
Quick hack for now :

`return ($is_arr || !isset($values[0])) ? $values : $values[0];`

**Comment by twd3** [comment]
Confirmed. If I wrap the null in single quotes the error goes away.

**Comment by Pixney-William** [comment]
Seems i still have this issue @jasonvarga 

![image](https://user-images.githubusercontent.com/31292231/87231629-0779a480-c3b9-11ea-973a-4cfa1677b730.png)


![image](https://user-images.githubusercontent.com/31292231/87231634-16f8ed80-c3b9-11ea-986e-dacf37fb9d50.png)

**Comment by twd3** [comment]
Oh, this stuff is so fun! I cannot confirm this error is still present as the null errors went away for me after Jason's fix that I applied manually.

**Comment by jesseleite** [comment]
@Pixney-William The fix will be coming in the next beta (beta 38). It's on master, but not tagged for release yet.

**Comment by Pixney-William** [comment]
Thanks! I just missunderstood and thought it was tagged in 37... no worries
