### ISSUE TITLE
{{ avatar }} doesn't fetch value as expected. 

### ISSUE THREAD

**Issue by Rovaski** [statamic/cms#2017]
## Bug Description
When in {{ users }} {{ /users }}; if you try to fetch the avatar handle {{ avatar }} you don't get anything returned. 

## How to Reproduce
Try to grab {{ avatar }} on the front-end. 

## Extra Detail
I believe auth/users.php method, avatar is blocking {{ avatar }} from working. 

However, if you modify the following from
```

        if ($this->hasAvatarField()) {
            return $this->avatarFieldUrl();
        }

```
to 
```

        if ($this->hasAvatarField()) {
            return $this->get('avatar');
        }

```
{{ avatar }} starts working on the frontend, but in the CP, the avatar image's are broken unless you prepend /assets/ to all the avatar urls. 

Perhaps avatarFieldUrl(); isn't working/returning the correct value? 

```
    protected function avatarFieldUrl()
    {
        $value = (new Value($this->get('avatar'), 'avatar', $this->blueprint()->field('avatar')->fieldtype(), $this));

        return $value->value()->url();
    }
```

**Comment by caseydwyer** [comment]
Similar issue over here, and had same results when making @Rovaski's above change to the `avatar` method in Auth\User—an `{{ avatar }}` tag within a User context on the front end starts working, but images are broken in the cp.

**Comment by damcclean** [comment]
I've submitted a pull request (#2443) to fix this bug, you wouldn't believe it was only a three line fix 😂

Hopefully it'll be merged soon!
