### ISSUE TITLE
SVG Assets Input Breaks After Upload

### ISSUE THREAD

**Issue by jjjrmy** [statamic/cms#2021]
## Bug Description
If you upload a SVG image to an assets input on a Collection it will upload properly but the input will show blank afterwards and you cannot make any edits.

## How to Reproduce
- S3 Bucket
- Upload SVG into Collection
- RIP

## Extra Detail
https://imgur.com/a/y8NCouv

## Environment

**Statamic version:** 3.0.0.-beta-{?}

**PHP version:** 7.{?}

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
