### ISSUE TITLE
Null Coalescence doesn't return fallback if falsey variable uses a modifier

### ISSUE THREAD

**Issue by richarderoche** [statamic/cms#2022]
## Bug Description

When using ?? or "or" to display a variable with a fallback it comes back blank if the first variable is null and has a modifier applied to it, even if the fallback variable is not null. However, Ternary format does work as expected.

## How to Reproduce
Create something like this with the first variable being a null one and the second one existing, it will return nothing:
{{alt_title|upper ?? title|upper}}

This will return the title variable (as expected):
{{alt_title ?? title}}

This will return the title variable in uppercase (as expected):
{{alt_title ? alt_title|upper : title|upper}}

## Environment

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ReneWeCode** [comment]
Confirms. I was struggling for a long time with this one: `{{ title_override ?? title ensure_right=">" }}`

**Comment by jackmcdade** [comment]
Confirmed. Will see what I can do!

Weirdly enough, the issue seems more related to the `>` than the modifier itself. This works (alt syntax):

```
{{ title_override ?? title | ensure_right:.com }}
```

**Comment by jasonvarga** [comment]
Unfortunately, we have to revert the change we made as we noticed it introduced unrelated issues. We'll get back to this though!

**Comment by jelleroorda** [comment]
Open sesame

**Comment by cnc137** [comment]
I ran across this problem in the "Cool Writings" starter kit ( https://github.com/statamic/starter-kit-cool-writings ) if the "excerpt" is blank since the code uses the "widont" modifier. I submitted a pull request, mentioned above, to solve the problem in the starter kit based on the information provided above.
