### ISSUE TITLE
GlobalSetSaved Event missing

### ISSUE THREAD

**Issue by Buffalom** [statamic/cms#2023]
## Bug Description
You guys have added many Laravel events such as `EntrySaving` and `EntrySaved` which are very useful. Unfortunately there is no `GlobalSetSaving` and `GlobalSetSaved` event. There is even a `GlobalSetDeleted` event so why aren't there events for saving and saved too? Is there a reason for that?

## Extra Detail
I currently would really like to use the `GlobalSetSaved` event but while looking around I also saw that the same thing applies to taxonomies, users and possibly other resources as well.
If there is no specific reason for that I can open a PR if you'd like.

## Environment

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.3.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
It’s in the git branch that’s almost ready to be merged.
