### ISSUE TITLE
Markdown Extensions - How to

### ISSUE THREAD

**Issue by padders** [statamic/cms#2025]
#1740  Bug Description
This isn't a bug, it's more that the instructions don't seem very clear so I really have no idea on the best way to do this. I (and another dev) got myself tied in knots till we gave in! We've been loving v3 so far and wanted to start diving a bit more under the hood to learn how to extend and modify the base features.

We have some simple markdown, and we want to wrap each line in a specific set of tags. The Markdown looks like this

```
**User1:** Hi How are you
**User2:** Good thank you 
**User1:** Superb
```
We want to create a custom markdown parser, that wraps the text conversation in the right html. So it ends up looking like this

```
<blockquote class="user1 quote bg-white rounded-full p-30px my-4 w-10/12 clear-both mr-auto">Hi How are you</blockquote>
<blockquote class="user2 quote bg-white rounded-full p-30px my-4 w-10/12 clear-both ml-auto">Good thank you</blockquote>
```

Statamic v3 dev mentions that this should be possible by creating an extension for commonmark, and then including your extension in the boot method of your AppServiceProvider.

https://statamic.dev/extending/markdown#customizing-markdown-behavior

We thought we could create a custom tag, that would wrap the content we wanted, and then we'd be able to use the following in our antlers `{{ text | markdown:special }}` to utilise it.

When I look for instructions on how to extend commonmark, I didn't find it especially clear. It mentioned creating a php file but didn't mention where to put this, and I can't find any evidence of commonmark folders in my statamic install (other than a load of mentions in the composer.json and .lock)

https://commonmark.thephpleague.com/1.5/customization/extensions/

Statamic v3's guides also has a section on creating addon's that wasn't quite ready and mentioned that it would change post go live, and a different section on extending by using Laravels methods which seemed to imply that might be the best way to do it but it was very high level.

Basically, I got to a point where I couldn't see where the best place to do this was and had quite a bit of possibly conflicting information that meant I was just wasting time so I thought I'd just ask! I do think that the current docs aren't very good when it comes to extending Statamic when using php/blades. It more often than not says that you can do this if you want without being very specific, and doesn't mention how those things would relate to  using antlers templates if you did them. I realise they're still WIP so there aren't any specifics yet.

I was hoping you might be able to give me some guidance on the best way to do this and what I'm missing! Is there a simpler method? Could I just include some php in my antler file for this specific section and use that to manipulate the markdown? Would I be best to make my own fieldtype for this and use a vue component to manipulate the markdown (not that I know how to do that either, but I'm willing to have a go)

## Environment

**Statamic version:** v3.0.0-beta.33

**PHP version:** 7.4.4

**Install method (choose one):**
- Starter kit - Cool writings

**Comment by jasonvarga** [comment]
You can put the commonmark extension file anywhere you want. There's no standard location for them.

Your project's `app` directory is PSR-4 autoloaded, which means that classes will be available corresponding to the directory structure.

```
app
|-- CommonMark
    |-- MySpecialExtension.php
```

```php
<?php

namespace App\CommonMark;

use League\CommonMark\Extension\ExtensionInterface;

class MySpecialExtension implements ExtensionInterface
{
    //
}
```

You don't need to create an addon (unless you want to distribute it as one). You can just wire it up in your `app/Providers/AppServiceProvider`, the typical location for doing these sort of things.

``` php
public function boot()
{
    Markdown::extend('special', function ($parser) {
        return $parser->addExtension(function () {
            return new MySpecialExtension;
        });
    });
}
```

**Comment by padders** [comment]
Hi Jason, 
Thanks for the help. When we try this we get the following error

```
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'App\Providers\Markdown' not found

  at /Documents/Sites/statv3/app/Providers/AppServiceProvider.php:19
    15|     public function boot()
    16|     {
    17|         // Statamic::script('app', 'cp');
    18|         // Statamic::style('app', 'cp');
  > 19|         Markdown::extend('transcript', function ($parser) {
    20|             return $parser->addExtension(function () {
    21|                 return new TranscriptExtension;
    22|             });
    23|         });

```

**Comment by jasonvarga** [comment]
Add `use Statamic\Facades\Markdown;`

**Comment by padders** [comment]
Thanks Jason (and sorry for taking so long to respond). That works well and I've managed to cobble something together :)
