### ISSUE TITLE
Using Variable inside tag doesn't match another variable with a modifier.

### ISSUE THREAD

**Issue by padders** [statamic/cms#2026]
## Bug Description
I'm trying to check if a variable equals another variable, both need to be modified to be lowercase. If I put a lowercase string value in place of the second variable, it works fine. E.g. (title in this instance is 'Video')

`{{ if title|lowercase == "video" }}`

When I add in the second variable which equals "video" it doesn't return true.

`{{ if title|lowercase == "{topic}" }}`

Also, it doesn't return true when I lowercase the second variable

`{{ if title|lowercase == "{topic|lowercase}" }}`

It doesn't actually throw an error so I wondered if it was a Type issue.

## Environment

Statamic version: v3.0.0-beta.33

PHP version: 7.4.4

Install method (choose one):

Starter kit - Cool writings

**Comment by jasonvarga** [comment]
Get rid of the braces.

`{{ if title|lower == video|lower }}`

**Comment by padders** [comment]
Ahh, brill. I thought I'd tried all variations of that. Ta :)
