### ISSUE TITLE
Equivalent method of filtering collections with taxonomy to v2 taxonomy="true"

### ISSUE THREAD

**Issue by padders** [statamic/cms#2027]
## Bug Description
I don't think this is a bug. Is there a better place to raise requests for assistance?

In Statamic v2 you could use a collection, and filter it by taxonomy which was added as a variable on the url. That meant you could do something have a blog index page, route all requests to that page and it would show all of the collection if it was the base url, and filter if you went to a specific tag.

So 

example.com/blog would list all blogs

example.com/blog/tags/news would show the same index page, but only list blog posts tagged as news.

`{{ collection:blogs taxonomy="true" paginate="true" as="posts" limit="12"}}`

In v3 I'm struggling to recreate this and I'd rather have a single index than an index for taxonomies and and index for collections.

Currently I have a taxonomy called topic, that applies to our blog articles. I've added the following to the Laravel routing to point the topics to the blog index page which then passes the variable {{ topic }} to the template.

`Route::statamic('articles/topics/{topic}', 'articles.index');`

In the template, I'm trying to recreate the behaviour from v2, but struggling. I can filter by topic as below.

`{{ taxonomy:topics title:is="{topic}" collection:articles }}`

However if I want to show all articles in the collection when the base url is hit, I'm struggling. Currently I have an `{{ if topic }}` loop around the whole section which seems very rubbish (on my part).

I've tried the following, but I can't find a wildcard for `title:is"*"` that works. It just returns nothing when topic isn't assigned (which makes sense), and this wouldn't pick up anything in the collection that doesn't have a topic assigned.

`{{ taxonomy:topics title:is="{topic ?? '*'}" collection:articles }}`

I did notice you had a filter option, but the documentation hasn't been written yet so I didn't really know what to do with it!

Sorry for the bout of requests for help. We're genuinely loving how v3 works for the most part. The new Bard is super flexible and really powerful. Coupled with Tailwind and Alpine it's great.

Statamic version: v3.0.0-beta.33

PHP version: 7.4.4

Install method (choose one):

Starter kit - Cool writings

**Comment by jasonvarga** [comment]
That's all automatic now.

Visit `/blog/tags/news`, and it'll load the `tags/show.antlers.html` view.
Use `{{ entries }}...{{ /entries }}` to loop over the appropriately tagged entries.

Visit `/blog/tags` and it'll load the `tags/index.antlers.html` view.
Use `{{ terms }}...{{ /terms }}` to loop over the terms.

Make sure your collection has a URL. https://statamic.dev/collections#mounting

See https://statamic.dev/taxonomies for more details. It goes over all of this.

**Comment by padders** [comment]
Thanks Jason, I do understand the method that v3 uses but if it were possible we don't want to do it that way.

The v3 method means you have to maintain 4 separate template files when previously we'd only have needed 2 (one for the index, and one for the article). Our tags are only used for one collection so we'd much rather have one index for our collection, rather than one index for the main collection, an index for all tags, and an index for each tag itself, stored in two separate locations. This feels like a step backwards to me. I much prefer the v2 method, that felt like magic.
