### ISSUE TITLE
Custom Slug rules are ignored

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#2029]
## Bug Description

We override Routable's slug() method in our custom Entry.php in order to circumvent the Str::slug() call in there, since we'd like to allow slashes in our slugs in some special case.

```php
public function slug($slug = null)
{
    return $this
        ->fluentlyGetOrSet('slug')
        ->setter(function ($slug) {
            \Log::debug('setting slug in ' . $this->collection() . ' collection');
            \Log::debug('setting slug to ' . ($this->collection() === 'centerpage' ? $slug : Support\Str::slug($slug)));
            return $this->collection() === 'centerpage' ? $slug : Support\Str::slug($slug);
        })
        ->args(func_get_args());
}
```

We also modified the collection's createRules() (which updateRules() is just an alias for) in our EntryRepository.php:

```php
public function createRules($collection, $site)
{
    switch ($collection) {
        case 'centerpage':
            return [
                'title' => 'required',	
                'slug' => 'required|regex:/[a-z0-9\/_-]+/',	
            ];	
        default:	
            return [	
                'title' => 'required',	
                'slug' => 'required|alpha_dash',	
            ];	
    }
}
```

However, when creating or saving an Entry, the slash is still removed from the slug. It's correct in the request going to Statamic (according to the browser), but it's "tampered with" when it reaches our slug() method. I'm not sure where this happens, since EntriesController.php doesn't seem to touch it, other than passing in what it gets from the request.

## How to Reproduce

Send JSON with a slash in the slug to the create/store handlers in EntriesController.php, and log what is passed into a slug() method in Entry.php.

## Environment

**Statamic version:** cc4b3bd77921fae

**Comment by jasonvarga** [comment]
It seems to be working fine. I get the slash in there.

`$this->collection()` is a `Collection` object.

So this condition is never true, and will always get slugged:

`return $this->collection() === 'centerpage' ? $slug : Support\Str::slug($slug);`

You should check the handle:

`return $this->collection()->handle() === 'centerpage' ? $slug : Support\Str::slug($slug);`

In your Log statement, it _looks_ like it's working because `Collection`'s `__toString()` method returns the handle.

**Comment by jasonvarga** [comment]
Or use `==` instead of `===` which seems to work too, as it casts it to a string.

![image](https://user-images.githubusercontent.com/105211/88413906-088fd600-cdaa-11ea-99de-0080ce5c7e9a.png)

**Comment by xyNNN** [comment]
I've the same topic. I want to allow slashes in the slug. But when I implement this I'm gettting a "this slug is already used" ... I don't have a unique constraint on it or the slug is used by another entry in this collection... I don't get it .. What I'm doing wrong? Can anyone help me?

**Comment by duncanmcclean** [comment]
This issue is over 4 years old. To avoid past participants being notified, are you able to open a new issue instead? Feel free to reference this one.
