### ISSUE TITLE
Entries in the left navigation should be ordered by titles

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#2030]
## Bug Description
It would make so much more sense if the order in the navigation was ordered by the title - not the handle.

## How to Reproduce
Create a bunch of collections, taxonomies etc. (title and handle should be different).
Now the order in the navigation vs the order in the main section is different.

## Extra Detail

![screenshot-suzuki19 test-2020 07 06-12_08_04](https://user-images.githubusercontent.com/43215436/86582352-ced56780-bf81-11ea-9d29-0310519288e6.png)

## Environment

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Good one. 👍
