### ISSUE TITLE
Git integration: error with 'STATAMIC_GIT_PUSH' = true

### ISSUE THREAD

**Issue by studio1902** [statamic/cms#2039]
## Bug Description
With push true I get an error every time I save something (a page) in the CP. Log gives the following:

[2020-07-07 16:21:17] staging.ERROR: Undefined variable: message {"userId":"d608ffb5-b4f0-4e02-beba-9a5ad04becd8","exception":"[object] (ErrorException(code: 0): Undefined variable: message at /home/forge/ien-ingenieurs.studio1902.nl/vendor/statamic/cms/src/Git/G$
[stacktrace]

With STATAMIC_GIT_PUSH false I don't get the error. In both cases there's a commit that doesn't get pushed. 
I've tried use_authenticated true and false. Manually pushing via ssh works without issue.

## How to Reproduce
Not sure a.t.m. This could be an issue due to the way git is setup at my server. Depends on what this error is coming from.
But I've got these .env's set: 

STATAMIC_GIT_ENABLED=true
STATAMIC_GIT_PUSH=false

I'm using Forge. 

## Environment

**Statamic version:** 3.0.0.-beta-35

**PHP version:** 7.4.5

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by MattRogowski** [comment]
Can confirm - don't think it's a setup issue, looking at the code the variable just isn't defined - presuming the line was copied from `commit()` a few methods above.

Love the new functionality tho 👍

**Comment by jesseleite** [comment]
Yep good find.  Fix coming in next beta.
