### ISSUE TITLE
[i18n] Utilities page no longer translated when you set the locale in the user file and not globally

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#2041]
## Bug Description
I am viewing the CP in French. When I visit the Utilities page (which is calling ```/views/utilities/index.blade.php```) all titles and description still are in English instead of French

All titles are localized in my fr.json file and all descriptions are localized in my messages.php file

## How to Reproduce
Set locale: fr in your user .yaml file and visit "Utilitaires"

See that menu entries in the sidebar are localized, but not on the main page

## Extra Detail

![Capture d'écran 2020-07-08 23 14 55](https://user-images.githubusercontent.com/1823359/86971110-deff6980-c170-11ea-89b9-44cc24f1fb51.png)

## Environment

**Statamic version:** 3.0.0.-beta-{35}

**PHP version:** 7.{4.2}

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
I notice this only happens when you set the locale in the user file.
If you change the locale in config/app.php, it is translated properly.

So, this must be because the Utilities are translated before the user's locale preference is applied to the translator.

Thanks for pointing this out!

**Comment by ebeauchamps** [comment]
Let's not forget me, please Mr. Robot.

**Comment by arthurperton** [comment]
> So, this must be because the Utilities are translated before the user's locale preference is applied to the translator.

Some extra info on that: `CoreUtilities::boot()` – which does the translations – is called in `CpServiceProvider->boot()` before the correct locale is set by the `Localize` middleware. I tried to move the call to right after the `Localize` middleware, but that results in an error:

<img width="1286" alt="Screenshot 2021-04-19 at 10 26 53" src="https://user-images.githubusercontent.com/4067531/115207717-205b7700-a0fc-11eb-93aa-f7f59825d61f.png">

**Comment by ebeauchamps** [comment]
Closing in favor of #3467

**Comment by jasonvarga** [comment]
Fixed in #7343 and will be in 3.4.
