### ISSUE TITLE
Using a field named 'type' in a bard set crashes bard

### ISSUE THREAD

**Issue by aj-adl** [statamic/cms#2042]
## Bug Description

If any field of the slug 'type' is used within a bard set, then it crashes the Bard Instance (unable to insert new sets, page must be refreshed to correct)

## How to Reproduce

1. Create a Bard Field
2. Create a new Set
3. Add a field of any type to the set with a `slug` of `type`
4. Save the Set and Bard Field
5. Add to a Blueprint
6. Create an article that uses that blueprint
7. Insert the set with the field called `type` into the bard field
8. Editor Crashes

## Extra Detail

Screen Cast: https://share.getcloudapp.com/jkuQ86An

Issues likely come from https://github.com/statamic/cms/blob/22f9f9dd8030a7bddbe774b249f7bf3392b8d0e4/resources/js/components/fieldtypes/bard/Set.vue#L134 

## Environment

**Statamic version:** 3.0.0.-beta-35

**PHP version:** 7.3.10

**Install method (choose one):**
Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This will never be fixed. We may need to add validation instead to prevent you from choosing `type` as a field handle.

`type` is reserved for the handle of the bard set.
