### ISSUE TITLE
STATAMIC_GIT_USER_NAME is not working when configured. Still grab's current user name.

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2046]
I have STATAMIC_GIT_USER_NAME=CommitFromCp configured in my .env and it still used my logged in username for the auto commit.

## How to Reproduce:
Set a STATAMIC_GIT_USER_NAME in your .env, make a change in the cp and let it auto commit / push. Go to github look at commit. You will see logged in name for the commit not the one placed in STATAMIC_GIT_USER_NAME="Here".

**Statamic version:** 3.0.0.-beta-36

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Turn off `use_authenticated` if you wan to always use that user.

See https://statamic.dev/git-integration#git-user
