### ISSUE TITLE
Fatal error when using PHP translator generate (on post-beta36 download)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#2049]
## Bug Description
Error when running php translator generate fr on the latest download:

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Statamic\Translator\Commands\Generate::__construct(), 5 passed in /Users/cccc/Documents/Github/statamic-cms-lang/translator on line 42 and exactly 7 expected in /Users/cccc/Documents/Github/statamic-cms-lang/src/Translator/Commands/Generate.php:28
Stack trace:
#0 /Users/cccc/Documents/Github/statamic-cms-lang/translator(42): Statamic\Translator\Commands\Generate->__construct(Object(Statamic\Translator\MethodDiscovery), Object(Illuminate\Filesystem\Filesystem), Array, Array, Array)
#1 {main}
  thrown in /Users/cccc/Documents/Github/statamic-cms-lang/src/Translator/Commands/Generate.php on line 28

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Statamic\Translator\Commands\Generate::__construct(), 5 passed in /Users/cccc/Documents/Github/statamic-cms-lang/translator on line 42 and exactly 7 expected in /Users/cccc/Documents/Github/statamic-cms-lang/src/Translator/Commands/Generate.php on line 28

ArgumentCountError: Too few arguments to function Statamic\Translator\Commands\Generate::__construct(), 5 passed in /Users/cccc/Documents/Github/statamic-cms-lang/translator on line 42 and exactly 7 expected in /Users/cccc/Documents/Github/statamic-cms-lang/src/Translator/Commands/Generate.php on line 28

Call Stack:
    0.0003     397792   1. {main}() /Users/efb/Documents/Github/statamic-cms-lang/translator:0
    0.0935    3965744   2. Statamic\Translator\Commands\Generate->__construct() /Users/cccc/Documents/Github/statamic-cms-lang/translator:42

## How to Reproduce
Download latest zip from statamic/cms repo
unzip it in a repo that already contains translator
run php translator generate fr

## Environment

**Statamic version:** 3.0.0.-beta-{36}

**PHP version:** 7.{4.2}

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Are you certain you have the latest version downloaded? There are 7 arguments being passed in. https://github.com/statamic/cms/blob/master/translator#L71

**Comment by ebeauchamps** [comment]
My bad :-(
