### ISSUE TITLE
Breadcrumbs bug with redirect:"@child"

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2055]
## Bug Description
Breadcrumbs not showing children, when entry has a redirect.

## How to Reproduce
Showing children inside the breadcrumbs.

## Extra Detail

https://pastebin.com/LF9tW7Yd

## Environment

**Statamic version:** 3.0.0.-beta-36

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
This issue seems like it's been fixed so I'm going to close this issue. If it comes up again, comment and we can re-open.
