### ISSUE TITLE
Make tags in the Taggable Fieldtype orderable

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2059]
It would be great if you could manually order the tags in the `Tags Fieldtype` in a drag-and-drop fashion. I've got the case where I need the array saved in a user-defined order. Right now you have to delete all the tags and reenter in the desired order.

**Comment by aerni** [comment]
This same issue also applies to the `Collections Fieldtype`.

**Comment by jesseleite** [comment]
These will be fixed in the next update.  Good find!
