### ISSUE TITLE
External links in a navigation incorrectly trigger the condition is_parent

### ISSUE THREAD

**Issue by mattgossman** [statamic/cms#2062]
## Bug Description

When external links (Link to URL) are added to a navigation they will trigger `is_parent` when outputted with the `{{ nav }}` tag.

## How to Reproduce

I used the sample nav tag code from the documentation. Using the following code to turn on a CSS class, external links are given the class because of the condition is_parent.

`<a href="{{ url }}"{{ if is_current || is_parent }} class="on"{{ /if }}>{{ title }}</a>`

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.3.6

**Comment by damcclean** [comment]
I can't reproduce this bug, looks like it's been fixed since this issue was created.
