### ISSUE TITLE
Bard inside replicator: drag & drop for blocks doesn't work

### ISSUE THREAD

**Issue by joroe** [statamic/cms#2063]
#1740  Bug Description
When using a bard field inside a replicator the blocks inside the bard field are not sortable using drag & drop. For the outer replicator sorting using drag & drop works.

## How to Reproduce
- Use bard inside replicator
- add two or more blocks in bard
- try to drag & drop

## Environment
Chrome 83/MacOS 10.15.4

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.3.11

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- built on a base imported from statamic2 using migrator 6+ months ago

**Comment by ellimondo** [comment]
Hi

Same issue here.

- Safari 13.1.2 / Firefox 78.0.2 / MacOS 10.15.6
- Statamic version: 3.0.0.-beta-37
- PHP version: 7.4.7
- Local install from statamic/statamic

**Comment by Pixney-William** [comment]
Same here.

Chrome, Brave, Firefox. 
Statamic version: 3.0.0.-beta-43
PHP version: 7.3
Local install from statamic/statamic

**Comment by ignasmailer** [comment]
I also faced this problem. Would really appreciate it being fixed. Thank you!

Firefox, Chrome
Statamic 3.0.16

**Comment by robdekort** [comment]
Ahhh when in a replicator. Yep, same here.

**Comment by jasonvarga** [comment]
The issue appears to be some sort of conflict between the outer Replicator draggable feature and the bard draggable stuff.

If I disable the Replicator's draggable feature, the inner Bard springs back to life.

Feels like events aren't bubbling correctly, or something like that. 😅  I'm a bit stuck here.

**Comment by jasonvarga** [comment]
I was able to reproduce this in a non-Statamic context, so I've opened issues in tiptap and draggable. 🤞 

https://codesandbox.io/s/tiptap-prosemirror-draggable-issue-1f34o
https://github.com/ueberdosis/tiptap/issues/918
https://github.com/Shopify/draggable/issues/463

**Comment by jasonvarga** [comment]
Should be fixed for next release. 

I noticed that the opposite situation, a replicator inside a bard's set, becomes undraggable once you drag the set. But this happened before the change anyway.
