### ISSUE TITLE
Support collection group_by_date

### ISSUE THREAD

**Issue by tao** [statamic/cms#2064]
## Bug Description
A reminder or check-in on `group_by_date` support in the collection tags. As it's mentioned in the Statamic V3 docs (https://statamic.dev/tags/collection#group_by_date) but not working yet.

I saw that it's mentioned in this closed issue but not checked off: #189

And mentioned in this open issue #1406 has a `group_by` error but `group_by_date` is not mentioned.

## How to Reproduce
Follow the code as described in the documentation, otherwise I have a quick repo with [cool-writings-starter example](https://github.com/tao/statamic-group-by-date/blob/master/resources/views/home.antlers.html) set up.

## Extra Detail
Nothing is rendered.

## Environment

**Statamic version:** 3.0.0.-beta.37

**PHP version:** 7.4.6

**Install method (choose one):**
- Starter kit

**Comment by el-schneider** [comment]
+1

**Comment by el-schneider** [comment]
Any news on the issue? I could really use the functionality now.

**Comment by jesseleite** [comment]
While waiting for approval/implementation on feature requests, in a situation like this you can create a custom tag using `php please make:tag` to output entries grouped by date.  For more info, check out: https://statamic.dev/extending/tags#generating-a-tag-class

**Comment by edalzell** [comment]
An example of the custom tag:

```
<?php

namespace App\Tags;

use Statamic\Facades\Entry;
use Statamic\Tags\Tags;

class Archive extends Tags
{
    public function index()
    {
        return Entry::query()
            ->where('collection', 'articles')
            ->get()
            ->groupBy(function ($entry) {
                return $entry->date()->format('Y');
            })
            ->map(function ($entries, $year) {
                return ['year' => $year, 'entries' => $entries];
            })
            ->sortByDesc('year')
            ->values();
    }
}
```


```
{{ archive }}
    <h1>{{ year }}</h1>
    {{ entries }}
        {{ title }} <br>
    {{ /entries }}
{{ /archive }}
```

**Comment by tao** [comment]
I would like to keep this open and see if there's an update on the approval/implementation of the feature requests mentioned above.

**Comment by ronvdc** [comment]
+1. I would really like to see this implemented in v3, too.

**Comment by lardnicus** [comment]
date_group was pretty useful...

**Comment by jasonvarga** [comment]
Please give a 👍 reaction to the issue instead of leaving a +1 comment.

For now you can use the workaround provided Erin above.
