### ISSUE TITLE
Bard field not outputting tags added by custom tiptap extension

### ISSUE THREAD

**Issue by joroe** [statamic/cms#2065]
## Bug Description
I built a toolbar extension for bard as described here: https://statamic.dev/extending/bard
It works as far as I can see that it adds the strong tag on the text in the bard field as expected. (I used a copy of the bold extension for testing purposes) Now when I save it does not output the strong tag added and visible in the bard field before. But it outputs all other edits made by the toolbars default options (like bold). I don't know what I am missing.

## How to Reproduce
see description

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.3.11

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- based on migration from v2

**Comment by jackmcdade** [comment]
Custom bard/tiptap extensions also need a renderer on the front-end side. All the core ones are handled by this library, so you can follow that as a pattern: <https://github.com/ueberdosis/prosemirror-to-html>

**Comment by jasonvarga** [comment]
We need to give users a way to register their custom node into the renderer.
