### ISSUE TITLE
{{ select_var:label }} is not working

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2066]
To get the labels of the select field you do {{ select_var:label }}. This is not outputting anything. I can get the default of value working with {{ select_var }}.

Make a select with key and label options. Try to use in template like email or on a form submission tag with {{ select_var }}, it works, now try and do with {{ select_var:label }}, it outputs nothing.

Side note: I tried this as well: {{ select_var }}{{ label }}{{ /select_var }}

On docs there is a typo too. https://statamic.dev/fieldtypes/select#templating
```
<p id="{{ select }}"> Oh yeah? {{ select:value }}</p> <<< This is the same thing...I think you want this:
<p id="{{ select }}"> Oh yeah? {{ select:label }}</p>
```

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.3

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by twd3** [comment]
Could this be happening because in the blueprint in the options array it wraps the labels in single quotes? I see in the doc's they are double quotes.

**Comment by twd3** [comment]
Just FYI, I have a select field that has multi true and it is outputting the label with: {{ select_var }}{{ label }}{{ /select_var }} only difference is multiple true.

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.

**Comment by twd3** [comment]
Still having an issue or an issue with understanding...https://discord.com/channels/489818810157891584/489819906540568593/759143098893992007

**Comment by jasonvarga** [comment]
I missed that you said it's in a form email. Maybe that's why it's not working for you.

**Comment by twd3** [comment]
Here is what I'm doing with the form:submission
```
{{ form:set is="contact" }}
{{ form:submission }}
{{ first_name }} {{ last_name }}
{{ if case_type_con }}
{{ case_type_con:label }}
{{ /if }}
{{ hearabout:label }}
{{ /form:submission }}
{{ /form:set }}
```
Then in the email view it's just the normal ```{{ hearabout:label }}```

**Comment by twd3** [comment]
As far as I know, this is still an issue. I wouldn't close it.
