### ISSUE TITLE
Using translations in addons not working

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#2067]
## Bug Description
This is likely more of a Laravel package related issue than an addon related issue. This is the first time I've tried to setup language files in Laravel.

When I try to use my language files from my addon, like this `__('duplicator::messages.duplicate')`, all I get back is `duplicator::messages.duplicate`, not particularly useful 😂

It could be the case I'm doing something wrong or maybe the language stuff hasn't been setup yet?

## How to Reproduce

1. Create an addon
2. Create language files, directory structure shown in screenshot and with the below contents.

<img width="377" alt="Screenshot 2020-07-12 at 08 28 30" src="https://user-images.githubusercontent.com/19637309/87241318-dda49a00-c419-11ea-8990-9af0676bc4af.png">

```
<?php

return [
    'duplicate' => 'Duplicate',
];
```

3. Register language files and vendor:publish stuff in your addons service provider, like so:

```
$this->loadTranslationsFrom(__DIR__.'/resources/lang', 'duplicator');

        $this->publishes([
            __DIR__.'/resources/lang' => resource_path('lang/vendor/duplicator'),
        ], 'duplicator-translations');
```

## Extra Detail

Below is what I get when I `dd(__('duplicator::messages.duplicate'));`

```
^ "duplicator::messages.duplicate"
```

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.4.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment]
It should be working.

If returning the exact name, the translation string could not be found.

You could have a look here:
 https://github.com/jonassiewertsen/statamic-documentation

**Comment by jonassiewertsen** [comment]
I hope it does help 😊

**Comment by damcclean** [comment]
Nevermind, I was registering my action *before* loading my translations, switched it around and it fixed it.

Thanks @jonassiewertsen.
