### ISSUE TITLE
Custom actions not shown on entry ordering screen.

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#2068]
## Bug Description
I've created an addon which registers a custom action available to entries. The action shows perfectly fine on the other view (the one with the list icon, not sure what its called 😂) but it doesn't show at all on the entry ordering screen.

## How to Reproduce

1. Create a custom action, like [this one](https://github.com/doublethreedigital/duplicator/blob/master/src/DuplicateAction.php)
2. It should be shown in the action dropdown for the entry list but not on the orderable entries page.

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.4.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.

**Comment by damcclean** [comment]
This issue still seems to be happening for me, I think I probably mis-titled the issue. I'm not seeing the actions in the Entry 'Tree' view. It works fine for me in the 'List' view.

I've provided screenshots below, my custom action is called `Duplicate`, and the action's code is [available here](https://github.com/doublethreedigital/duplicator/blob/master/src/DuplicateAction.php).

**Tree Actions**
![image](https://user-images.githubusercontent.com/19637309/94185627-72595880-fe9d-11ea-955d-e1790c75bcc4.png)

**List Actions**
![image](https://user-images.githubusercontent.com/19637309/94185683-80a77480-fe9d-11ea-80e8-307880914526.png)


Sorry for the bad explanation before.

**Comment by jasonvarga** [comment]
Actions aren't shown in tree mode, you're right. That's intentional though because it's intended to work a bit differently.

**Comment by damcclean** [comment]
Ah okay. I'll close this issue then. Just had a user of my addon ask why it wasn't showing 🤔

**Comment by robdekort** [comment]
I think this might make it a little hard for users to find functionality. Would this be a FR you folks are willing to reconsider? 

It would also mean the root entry needs to get one of those fly out menu's, it's probably gonna need other options in there so it might be quite the change.

**Comment by jasonvarga** [comment]
Sure, open an issue on ideas 👍

**Comment by edalzell** [comment]
for others that encounter this, here's the FR: https://github.com/statamic/ideas/issues/575
