### ISSUE TITLE
vendor/statamic/cms/src/Providers/AuthServiceProvider.php Not Found

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2069]
My logs are now empty because debugging is going well. I got this one a minute ago on the live server and I'm wondering if I should be concerned? It looks like that file is missing.

local.ERROR: Class 'Facades\Statamic\Auth\CorePermissions' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Facades\\Statamic\\Auth\\CorePermissions' not found at /home/forge/www.domain.com/vendor/statamic/cms/src/Providers/AuthServiceProvider.php:85)
[stacktrace]
#0 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Statamic\\Providers\\AuthServiceProvider->Statamic\\Providers\\{closure}(Object(Illuminate\\Foundation\\Application))
#1 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(844): Illuminate\\Foundation\\Application->fireAppCallbacks(Array)
#2 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#3 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#4 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#5 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#6 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#7 /home/forge/www.andersonhemmat.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#8 {main}
"} 

## How to Reproduce:
Look for that file?

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.3

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Looks like a request was made to your site while Composer was still doing it's thing. I think you're fine 👍
