### ISSUE TITLE
Date Behaviors "private" don't throw a 404 in frontend

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#2070]
## Bug Description
The frontend does not throw a 404 error when visiting a page which is not published or the collection settings for date behaviors are both set to private and the date on the page is set to past or future. It seems that in no case related to publish date or published a 404 is thrown.

## How to Reproduce
1. activate the publish date option in a collection
2. set past and future behavior to private
3. create a entry inside of this collection and set the date to yesterday or tomorrow
4. visit the entry in the frontend. no 404 is thrown

## Extra Detail
![Bildschirmfoto 2020-07-12 um 19 44 05](https://user-images.githubusercontent.com/2395800/87253058-5f2b1500-c478-11ea-8811-99f1415c7140.png)
![Bildschirmfoto 2020-07-12 um 19 44 48](https://user-images.githubusercontent.com/2395800/87253059-618d6f00-c478-11ea-8233-12f7f2b58130.png)

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.4

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by ReneWeCode** [comment]
Confirming. Doesn't work in beta.42 either.

**Comment by jasonvarga** [comment]
Looks like this only happens when the collection is orderable.
