### ISSUE TITLE
Two Forms on One Page Showing Server 500 Error When Second One Submitted

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2072]
I have two forms on one page...well one shows large and up and one shows medium screens and down. I'm having an issue where one of the forms works (large screen if it matters) and the other doesn't. I made sure all form handles are unique so I know it isn't an ID or input name issue.

## How to Reproduce
Put two forms on one page with simple required validation on both. One will work, the other won't.

I have this live if you want to look for yourself DM me for the link.

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.3

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Are you using different form:set tags?

**Comment by twd3** [comment]
Yes

**Comment by jasonvarga** [comment]
Let’s see the template

**Comment by twd3** [comment]
```
{{ form:create in="quick_contact_sm" redirect="/thank-you-for-contacting-us" id="ahQuickFormSm" autocomplete="off" }}
	
{{ if errors }}
<div class="flex">
  <div class="w-full p-1 mb-2 bg-white rounded">

      <p class="m-0 text-ah_red"><i class="fas fa-ambulance text-ah_red"></i> Please check the errors below...</p>
		<div class="hidden">{{ errors }}{{ value }}{{ /errors }}</div>

  </div>
</div>
{{ /if }}

<input id="first_name_sm" name="first_name_sm" type="text" placeholder="First Name" class="validate txt-q-input placeholder-gray-300" value="{{ old:first_name_sm }}" autofocus>
{{ error:first_name_sm ensure_left="*" wrap="span.error" }}
<input id="last_name_sm" name="last_name_sm" type="text" placeholder="Last Name" class="validate txt-q-input placeholder-gray-300" value="{{ old:last_name_sm }}">
{{ error:last_name_sm ensure_left="*" wrap="span.error" }}
<input id="email_sm" name="email_sm" type="text" placeholder="Email Address" class="validate txt-q-input placeholder-gray-300" value="{{ old:email_sm }}">
{{ error:email_sm ensure_left="*" wrap="span.error" }}
<input id="phone_sm" name="phone_sm" type="text" placeholder="Phone Number" class="validate txt-q-input placeholder-gray-300" value="{{ old:phone_sm }}">
{{ error:phone_sm ensure_left="*" wrap="span.error" }}
	
<textarea id="q_message_sm" name="q_message_sm" placeholder="Your Message" class="validate txt-q-input placeholder-gray-300" value="{{ old:q_message_sm }}"></textarea>
{{ error:q_message_sm ensure_left="*" wrap="span.error" }}

{{ recaptcha }}    
<input class="hidden" id="fu-bots-sm" name="fu-bots-sm" type="text">
<input class="hidden" id="came_from_sm" name="came_from_sm" type="text" value="FULL SITE">
<button id="ahQuickSubmitSm" type="submit" class="inline-flex justify-center items-center mt-4 xl:mt-8 text-white btn btn-large btn-expanded btn-white-border btn-shadow-medium">
  <svg xmlns="http://www.w3.org/2000/svg" class="fill-current w-6 h-6 mr-2" viewBox="0 0 20 20">
  <path d="M16.9,8.8h-0.9V5.9C15.9,2.7,13.3,0,10,0S4.1,2.7,4.1,5.9v2.8H3.1c-1,0-1.9,0.8-1.9,1.9v7.5c0,1,0.8,1.9,1.9,1.9h13.8
      c1,0,1.9-0.8,1.9-1.9v-7.5C18.8,9.6,17.9,8.8,16.9,8.8z M12.8,8.8H7.2V5.9c0-1.6,1.3-2.8,2.8-2.8s2.8,1.3,2.8,2.8V8.8z"/>
  </svg>
  GET EVALUATION
  </button>  
  <p class="text-xxs text-center mt-3 text-white">Protected by reCAPTCHA. Google <a class="text-white no-underline" href="https://policies.google.com/privacy" target="_blank" rel="noreferrer noopener">Privacy </a> and <a class="text-white no-underline" target="_blank" rel="noreferrer noopener" href="https://policies.google.com/terms">Terms</a> apply.</p>
{{ /form:create }}
```

**Comment by twd3** [comment]
Here is the Other:
```
{{ form:create in="quick_contact" redirect="/thank-you-for-contacting" id="ahQForm" autocomplete="off" }}
{{ if errors }}
<div class="flex">
  <div class="w-full mb-6">
    <div class="alert callout">
      <h3 class="text-ah_red"><i class="fas fa-ambulance text-ah_red"></i> Whoops, something went wrong...please check the form errors listed in red below and resubmit:</h3>
    </div>
  </div>
</div>
{{ /if }}

<div class="callout secondary">

  <div class="flex">
    <div class="w-full text-right">
      <p class="text-sm text-ah_blue mt-2 mr-2">All items required <i class="required fas fa-asterisk"></i></p>
    </div>
  </div>

  <div class="px-3">
    <div class="flex flex-wrap -mx-3">
      <div class="w-full md:w-1/2 px-3 mb-2 md:mb-0 focus-label">
        <label for="first_name">First Name <i class="required fas fa-asterisk"></i></label>
        <input id="first_name" name="first_name" type="text" class="validate txt-input" placeholder="First Name *" value="{{ old:first_name }}">
        {{ error:first_name ensure_left="*" wrap="span.error" }}
      </div>

      <div class="w-full md:w-1/2 px-3 mb-2 md:mb-0 focus-label">
        <label for="last_name">Last Name <i class="required fas fa-asterisk"></i></label>
        <input id="last_name" name="last_name" type="text" class="validate txt-input" placeholder="Last Name *" value="{{ old:last_name }}">
        {{ error:last_name ensure_left="*" wrap="span.error" }}
      </div>
    </div>
  </div>

  <div class="px-3">
    <div class="flex flex-wrap -mx-3">
      <div class="w-full md:w-1/2 px-3 mb-2 md:mb-0 focus-label">
        <label for="email">Email <i class="required fas fa-asterisk"></i></label>
        <input id="email" name="email" type="text" class="validate txt-input" placeholder="Email *" value="{{ old:email }}">
        {{ error:email ensure_left="*" wrap="span.error" }}
      </div>


      <div class="w-full md:w-1/2 px-3 mb-2 md:mb-0 focus-label">
        <label for="phone">Phone Number <i class="required fas fa-asterisk"></i></label>
        <input id="phone" name="phone" type="text" class="validate txt-input" placeholder="Phone Number *" value="{{ old:phone }}">
        {{ error:phone ensure_left="*" wrap="span.error" }}
      </div>
    </div>
  </div>

  <div class="flex px-3 mb-2">
    <div class="w-full focus-label">
      <br>
      <label for="q_message">Your Message <i class="required fas fa-asterisk"></i></label>
      <textarea id="q_message" name="q_message" class="validate txt-area autosize" placeholder="Your Message *"></textarea>
      {{ error:q_message ensure_left="*" wrap="span.error" }}
    </div>
  </div>


<div class="flex">
    <div class="w-full">
      {{ recaptcha }}
      <input class="hidden" id="came_from" name="came_from" type="text" value="FULL SITE">
      <input class="hidden" id="fu-bots" name="fu-bots" type="text">
      <button id="ahQuickSubmit" class="btn-large btn-blue btn-expanded" type="submit" name="action">
      <i class="fas fa-paper-plane large-icon wobble-hor"></i> SUBMIT CONTACT FORM</button>
	  <p class="text-xxs text-center my-4">Anderson Hemmat, LLC is protected by Google reCAPTCHA and the Google <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer noopener">Privacy Policy</a> and <a target="_blank" rel="noreferrer noopener" href="https://policies.google.com/terms">Terms</a> of Service apply.</p>
    </div>
</div>

</div>
{{ /form:create }}
```

**Comment by twd3** [comment]
I've looked at the email views and the blueprints and anything in form yaml...all looks ok.

**Comment by twd3** [comment]
I think I have to do type="email" on these two email fields. I'm going to try that

**Comment by twd3** [comment]
BluePrints:

TOP TEMPLATE POSTED ABOVE:
title: 'Quick Contact Med Down'
sections:
  main:
    display: Main
    fields:
      -
        handle: first_name_sm
        field:
          html_type: text
          type: text
          localizable: false
          width: 50
          listable: true
          display: 'First Name'
          validate: required
          input_type: text
      -
        handle: last_name_sm
        field:
          html_type: text
          type: text
          localizable: false
          width: 50
          listable: true
          display: 'Last Name'
          validate: required
          input_type: text
      -
        handle: email_sm
        field:
          html_type: email
          type: text
          localizable: false
          width: 50
          listable: true
          display: Email
          validate: required|email
          input_type: email
      -
        handle: phone_sm
        field:
          type: text
          html_type: tel
          localizable: false
          width: 50
          listable: hidden
          display: Phone
          validate: required
          input_type: text
      -
        handle: q_message_sm
        field:
          type: textarea
          localizable: false
          listable: hidden
          display: Message
          validate: required
      -
        handle: came_from_sm
        field:
          type: text
          display: 'Form came from...'
          listable: false
          input_type: text

NEXT POSTED TEMPLATE ABOVE:
title: 'Quick Contact'
sections:
  main:
    display: Main
    fields:
      -
        handle: first_name
        field:
          html_type: text
          type: text
          localizable: false
          width: 50
          listable: true
          display: 'First Name'
          validate: required
          input_type: text
      -
        handle: last_name
        field:
          html_type: text
          type: text
          localizable: false
          width: 50
          listable: true
          display: 'Last Name'
          validate: required
          input_type: text
      -
        handle: email
        field:
          html_type: email
          type: text
          localizable: false
          width: 50
          listable: true
          display: Email
          validate: required|email
          input_type: text
      -
        handle: phone
        field:
          type: text
          html_type: tel
          localizable: false
          width: 50
          listable: hidden
          display: Phone
          validate: required
      -
        handle: q_message
        field:
          type: textarea
          localizable: false
          listable: hidden
          display: Message
          validate: required
      -
        handle: came_from
        field:
          type: text
          display: 'Form came from...'
          listable: false
          input_type: text

**Comment by twd3** [comment]
Should I be doing form:set is="contact" or form:create in="contact"?

**Comment by twd3** [comment]
HOLD OFF ON THIS. It could have been an addon. Hopefully will know shortly.

**Comment by twd3** [comment]
This for sure is not that recaptcha addon that is still in beta, I completely uninstalled it and on this second form I still still got **server error 500** when trying to submit. Below is the log I got from Forge. I checked and all email addressesare configured and formatted properly?

[2020-07-13 23:45:49] local.ERROR: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [] does not comply with RFC 2822, 3.6.2. at /home/forge/www.andersonhemmat.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)
[stacktrace]
#0 /home/forge/www.andersonhemmat.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(272): Swift_Mime_Headers_MailboxHeader->assertValidAddress('')
#1 /home/forge/www.andersonhemmat.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(117): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /home/forge/www.andersonhemmat.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(74): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /home/forge/www.andersonhemmat.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(61): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /home/forge/www.andersonhemmat.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(71): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('Reply-To', Array)
#5 /home/forge/www.andersonhemmat.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(268): Swift_Mime_SimpleHeaderSet->addMailboxHeader('Reply-To', Array)
#6 /home/forge/www.andersonhemmat.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(245): Swift_Mime_SimpleMessage->setReplyTo(Array)
#7 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Mail/Message.php(164): Swift_Mime_SimpleMessage->addReplyTo('', NULL)
#8 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Mail/Message.php(148): Illuminate\\Mail\\Message->addAddresses('', NULL, 'ReplyTo')
#9 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(344): Illuminate\\Mail\\Message->replyTo('', NULL)
#10 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(155): Illuminate\\Mail\\Mailable->buildRecipients(Object(Illuminate\\Mail\\Message))
#11 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(244): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}(Object(Illuminate\\Mail\\Message))
#12 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(159): Illuminate\\Mail\\Mailer->send(Object(Statamic\\View\\Antlers\\AntlersString), Array, Object(Closure))
#13 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#14 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(160): Illuminate\\Mail\\Mailable->withLocale(NULL, Object(Closure))
#15 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(277): Illuminate\\Mail\\Mailable->send(Object(Illuminate\\Mail\\Mailer))
#16 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(231): Illuminate\\Mail\\Mailer->sendMailable(Object(Statamic\\Forms\\Email))
#17 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Mail\\Mailer->send(Object(Statamic\\Forms\\Email))
#18 /home/forge/www.andersonhemmat.com/vendor/statamic/cms/src/Forms/SendEmails.php(33): Illuminate\\Support\\Facades\\Facade::__callStatic('send', Array)
#19 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(176): Statamic\\Forms\\SendEmails->Statamic\\Forms\\{closure}(Array, 0)
#20 /home/forge/www.andersonhemmat.com/vendor/statamic/cms/src/Forms/SendEmails.php(34): Illuminate\\Support\\Collection->each(Object(Closure))
#21 [internal function]: Statamic\\Forms\\SendEmails->handle()
#22 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#23 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#25 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#26 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#27 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#28 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Statamic\\Forms\\SendEmails))
#29 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Statamic\\Forms\\SendEmails))
#30 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Statamic\\Forms\\SendEmails), false)
#32 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Statamic\\Forms\\SendEmails))
#33 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Statamic\\Forms\\SendEmails))
#34 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(Statamic\\Forms\\SendEmails))
#36 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#37 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(45): Illuminate\\Queue\\Jobs\\Job->fire()
#38 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(182): Illuminate\\Queue\\SyncQueue->push(Object(Statamic\\Forms\\SendEmails))
#39 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(158): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(Statamic\\Forms\\SendEmails))
#40 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(Statamic\\Forms\\SendEmails))
#41 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(112): Illuminate\\Bus\\Dispatcher->dispatch(Object(Statamic\\Forms\\SendEmails))
#42 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(16): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#43 /home/forge/www.andersonhemmat.com/vendor/statamic/cms/src/Http/Controllers/FormController.php(60): Statamic\\Forms\\SendEmails::dispatch(Object(Statamic\\Forms\\Submission))
#44 [internal function]: Statamic\\Http\\Controllers\\FormController->submit(Object(Illuminate\\Http\\Request), Object(Statamic\\Forms\\Form))
#45 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#46 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('submit', Array)
#47 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\FormController), 'submit')
#48 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#49 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#50 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /home/forge/www.andersonhemmat.com/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\StaticCaching\\Middleware\\Retrieve->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#67 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#68 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#69 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#70 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#71 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home/forge/www.andersonhemmat.com/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /home/forge/www.andersonhemmat.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /home/forge/www.andersonhemmat.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#88 /home/forge/www.andersonhemmat.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#89 /home/forge/www.andersonhemmat.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#90 {main}
"}

**Comment by damcclean** [comment]
> I get **server error 500** when trying to submit that template on top. Below is the log I got from Forge. I checked and all email addressesare configured and formatted properly? Or is this because my email handle on form not working is email_sm and needs to be email?
> 
> [2020-07-13 23:45:49] local.ERROR: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [] does not comply with RFC 2822, 3.6.2. at /home/forge/www.domain.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)
> 

That error there looks like an issue with Statamic trying to send an email. Make sure to configure your mail settings in your `.env` and try again.

(If you're in local development, use the `log` mail driver and the emails will be sent to your log file.)

**Comment by twd3** [comment]
Thanks, but I know the config in my servers .env is right because it's been working. It only gives me this error when two are on one page. The config is just mailgun. So are you saying you have two forms on one page (not just a login form) working?

**Comment by twd3** [comment]
100% my fault so sorry, closing now.
