### ISSUE TITLE
Stache-related exception 

### ISSUE THREAD

**Issue by vladdu** [statamic/cms#2075]
I created a new v3 site and started copying content from another site. Then, at some moment, after editing a page, I got a PHP exception (https://flareapp.io/share/17DJqzmv#F101) and now even if I restore the last change, the exception still happens. The exception is thrown even when going to /cp/collections, and also "php please stache:clear". [edit] This happens when editing the files directly, not in the CP.

Manually removing /storage/framework/cache helps, but I don't think that should be the solution for such issues. 

## How to Reproduce

Unfortunately, I don't seem to be able to reproduce reliably. Some changes trigger it sometimes (like editing the template field in the front matter). 

## Extra Detail

Stacktrace at https://flareapp.io/share/17DJqzmv#F101

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by goellner** [comment]
I think that occurs, when files are edited directly. I've run into this problem too. If I rsync the content of a site from the production cms, sometimes I run into this exception too. 

Manually removing /storage/framework/cache helps, since the "php please stache:clear" command throws the same exception, so it can't be used.

**Comment by jonassiewertsen** [comment]
I can confirm this behavior. 

As described will `php please` commands throw the same error. 

Depending if in production or development, I am mostly using `php artisan optimize` or `php artisan optimize:clear` to clear my stache/cache etc.

**Comment by jackmcdade** [comment]
Thanks for the confirm @jonassiewertsen, we'll do our best to get this fixed.

**Comment by damcclean** [comment]
Beep bop. Go away robot!
