### ISSUE TITLE
User Login Form (UserTags) ignores error_redirect param

### ISSUE THREAD

**Issue by DanWithams7d** [statamic/cms#2078]
## Bug Description

The error_redirect param is ignored on the user:login_form.

## How to Reproduce

1. Create form as per the template code below
2. Submit invalid details into the form
3. You will be redirected back(), not to the error_redirect params

## Extra Detail

Example code:
```
{{ user:login_form redirect="/account" error_redirect="/some-other-root" }}
    {{ if errors }}
    <div class="alert alert-danger">
        {{ errors }}
        {{ value }}<br>
        {{ /errors }}
    </div>
    {{ /if }}

    {{ if success }}
    <div class="bg-green-300 text-white p-2">
        {{ success }}<br>
    </div>
    {{ /if }}

    <label>Email</label>
    <input type="text" name="email" value="{{ old:email }}" />

    <label>Password</label>
    <input type="password" name="password" value="{{ old:password }}" />

    <button type="submit">Log in</button>
{{ /user:login_form }}
```

Excerpt from Statamic\Http\Controllers\UserController 
```
        return $loggedIn
            ? redirect($request->input('_redirect', '/'))->withSuccess(__('Login successful.'))
            : back()->withInput()->withErrors(__('Invalid credentials.'));
```

The else should consider the _error_redirect form param.

## Environment

**Statamic version:** 3.0.0.-beta-35

**PHP version:** 7.2.29

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by DanWithams7d** [comment]
PR submitted #2079

**Comment by jesseleite** [comment]
Hey @DanWithams7d, Good find!  When reviewing your PR, I realized we weren't handling `_error_redirect` in a few places.  Went for a slightly different approach, but really appreciate the issue and PR ❤️
