### ISSUE TITLE
Contains modifier should support Collections

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#2080]
```
{{ if items | contains:sellable:false }}
```

WIth the given data, I would expect to get false returned.

![Screenshot 2020-07-14 at 18 41 42](https://user-images.githubusercontent.com/38906163/87452929-1c954400-c602-11ea-9014-4c005c4d9df8.png)

I am getting true instead.

A link to the docs:
https://statamic.dev/modifiers/contains

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.4

**Comment by jonassiewertsen** [comment]
The problem might be, that I am passing a collection.

**Comment by damcclean** [comment]
What if you convert it to json and then check if it contains `sellable`, like this:

```
{{ if items | to_json | contains:sellable:false }}
```

**Comment by jonassiewertsen** [comment]
Cool idea!

Not working though.

**Comment by damcclean** [comment]
If it's a Laravel collection (`Illuminate\Support\Collection`) you're talking about, what about if you convert it to an array before passing to your view/tag? Then try the `to_json` thing.

**Comment by jonassiewertsen** [comment]
That should work.

To keep a clean syntax, I will go with a custom modifier. 

```
{{ unless items | sellable }}
   Some text           
{{ /unless }}
```

My modifier simply says:
```
return ! $value->contains('sellable', false);
```

**Comment by jasonvarga** [comment]
That modifier should support collections. I'll change the subject for you.

**Comment by jackmcdade** [comment]
Actually, this is more of a task for the [where](https://statamic.dev/modifiers/where) modifier. This will work:

```
{{ if items | where:sellable }}
```
