### ISSUE TITLE
Yaml fieldtype is always localizable

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2082]
## Bug Description
The content of the `Yaml Fieldtype` can always be translated. Even when `localizable: false`.

## How to Reproduce
Make a multi-site, add a Yaml field to a blueprint, and try it yourself.

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.4.6

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment]
Those might be related: https://github.com/statamic/cms/issues/1827
