### ISSUE TITLE
The section fieldtype shouldn't be localizable

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2084]
## Bug Description
The section fieldtype shouldn't be localizable. There's nothing to localize.

## Extra Detail
<img width="1045" alt="Bildschirmfoto 2020-07-15 um 18 58 01" src="https://user-images.githubusercontent.com/23167701/87575187-d0b0d080-c6cf-11ea-97c3-bd0f216411bf.png">

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.4.6

**Install method:** Fresh install from `statamic/statamic`

**Comment by ebeauchamps** [comment]
#2034
