### ISSUE TITLE
Glide image asset URLs when using Multisite

### ISSUE THREAD

**Issue by stevan** [statamic/cms#2091]
I have a multi-site setup and when using the glide tag the URL produced is prepended with the multi-site url value, which is not correct. This is the line which prepends the multi-site url value to the Glide URL. 

https://github.com/statamic/cms/blob/cc9707423b453b2cac4e885968025e11f64156c8/src/Imaging/GlideUrlBuilder.php#L61

This line can be replaced with this, and everything seems fine. 

```
return $builder->getUrl($path, $params);
```

Let me know if you need any other details, I can try to dig them up.

**Comment by jonassiewertsen** [comment]
This PR request would fix your problem:
https://github.com/statamic/cms/pull/1953

It's an duplicate of:
https://github.com/statamic/cms/issues/1304


Please remember fill out the provided bug report. Your actual Statamic version is pretty important, especially in the beta version.
