### ISSUE TITLE
Taxonomy isn't working for AMP

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2095]
If I try to visit a taxonomy through AMP it gives 500 error and this in the log "local.ERROR: Call to undefined method Statamic\Taxonomies\LocalizedTerm::ampable()".

So if I try to view something like: domain.com/amp/blog/tags/the-tag it fails.

Turn on AMP for collection. Make sure collection uses taxonomy. Go view taxonomies amp versions.

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.3

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by twd3** [comment]
This log error might have to do with it:
```
production.ERROR: Call to undefined method Statamic\Taxonomies\LocalizedTerm::ampable() {"exception":"[object] (Error(code: 0): Call to undefined method Statamic\\Taxonomies\\LocalizedTerm::ampable() at /home/forge/domain.com/vendor/statamic/cms/src/Http/Responses/DataResponse.php:78)
```

**Comment by twd3** [comment]
As far as I know, this is still an issue. I wouldn't close it.

**Comment by jackmcdade** [comment]
At this point with AMP being officially dead, I think it's best if we focus on other issues here and start the depreciation process for the feature.
