### ISSUE TITLE
Routing with slugs from other collections

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#2096]
## Bug Description
I'm building out a section of my site for addon documentation. I've got two collections setup: addons and documentation. Addons don't have their own routes and documentation has its own routes. My documentation blueprint has a required field for an addon.

I would documentation to have a url like this: `/addons/simple-commerce/about`. However, the furthest I've managed to get to this is `/addons/c4d878eb-af7d-47e7-bfc8-c5baa162d7bf/about`, with the addon slug being replaced with the addon's entry ID instead. Here's the route patten I use for that: `/addons/{addon}/{slug}`.

Is there any way I get the slug of the related addon instead of just its ID? If not, I could write something custom to do it instead.

A side note: I have the documentation for Simple Commerce's docs sitting in a subfolder of `documentation` (`content/collections/documentation/simple-commerce/about.md` for example), could this possibly be used instead to make the routing work?

## How to Reproduce
1. Create an addons collection + blueprint
2. Create a documentation collection + blueprint with an entry field pointing to an addon entry
3. Setup `/addons/{addon}/{slug}` as the routing pattern for the documentation collection
4. Try and visit the url for one of the documentation entries. It uses the ID instead of the slug.

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.4.3

**Install method (choose one):**
- **Fresh install from `statamic/statamic`**

**Comment by damcclean** [comment]
Nevermind, I've changed my site structure so the documentation pages are just children of the addon itself.

**Comment by wesort** [comment]
I'm looking for this too. 

### Context
– Portfolio site with a collection called "Work"
– Second collection called "Shop" with an `entries` field where users can select Work entries (max 1 entry)
– I'd like the route for Shop entries to have the Work entry's `slug` in its route

So, for a Shop entry with the slug `strawberry-jam` that has its Work field set to a Work entry with the slug `brown-toast`, I want the Shop entry's route URL to be: `/brown-toast/strawberry-jam`. 

This functions `{work}/{slug}` but outputs the `id` of the `work` entry, and I would like the `slug`.
