### ISSUE TITLE
Can't send email : Target class [App\Listeners\LogSendingMessage] does not exist.

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#2097]
# Bug Description

When trying to send email with Statamic I get an error: 
```
Target class [App\Listeners\LogSendingMessage] does not exist.
```

## How to Reproduce

It happens in the frontend when submiting a form that send email and in the control panel under `Utilities/Email` page when clicking on the button `Send Test Email`.

## Extra Detail

<img width="1224" alt="Screenshot 2020-07-18 at 21 37 06" src="https://user-images.githubusercontent.com/10623367/87860593-de1fc200-c93e-11ea-8734-2e69e18a5a37.png">

## Environment

**Statamic version:** `3.0.0-beta-37`

**PHP version:** `7.4.8`

**Install method:** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
That doesn't look like a Statamic issue to me.

Do you have any addons? Or listeners registered in app/Providers/EventServiceProvider.php?

**Comment by jimblue** [comment]
Indeed 😄 ! Sorry for that, it's from my side...
