### ISSUE TITLE
Search indexes doesn't read Statamic config

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#2098]
## Bug Description

Statamic search index doesn't seems to read the config from `/config/statamic/search.php`.

## How to Reproduce

Editing `/config/statamic/search.php` like this :

```php
'indexes' => [

        'default' => [
            'driver' => 'local',
            'searchables' => ['collection:blog', 'collection:photos', 'collection:videos'],
            'fields' => ['title'],
        ],

    ],
```

Then run `php please search:update`.

The `storage/statamic/search/default.json` sould only contain data `title` fields found in the following collections: blog, photos and videos.

But `storage/statamic/search/default.json` actually contain data from all fields and all content. (collections/assets/toxaonomies...)

## Environment

**Statamic version:** `3.0.0-beta-37`

**PHP version:** `7.4.8`

**Install method:** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.

**Comment by jimblue** [comment]
Just checked, it's also fixed here ! 🙏🏼
