### ISSUE TITLE
Getting error when submitting a form with a honeypot field 

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#2099]
## Bug Description

Getting error when submitting a form with a `honeypot` field.

## How to Reproduce

As suggested in the documentation [here](https://statamic.dev/forms#honeypot), add a `honeypot` field to a form.

On submit you should get an error: `Undefined variable: submission`

## Extra Detail

<img width="1269" alt="Screenshot 2020-07-19 at 00 33 56" src="https://user-images.githubusercontent.com/10623367/87863075-8c376600-c957-11ea-8a85-0ee736f34423.png">

## Environment

**Statamic version:** `3.0.0-beta-37`

**PHP version:** `7.4.8`

**Install method:** Fresh install from `statamic/statamic`

**Comment by jeremydouglas** [comment]
I can confirm this.

**Comment by jasonvarga** [comment]
Should be fixed in beta 38.

**Comment by jimblue** [comment]
@jasonvarga I confirm it's fixed with beta 38 🎉 !!!

Tks
