### ISSUE TITLE
Overriding/Adding language file does not work.

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2103]
## Bug Description
I need to add some russian control panel translations for a client. And i'm trying to do so by adding a ru.json file to the `resources/lang/vendor/statamic/` directory as you normally override Laravel packages. But the russian file is not picked up. 

I have also tried publishing your translations, and make changes to for example de.json, and those changes are not picked up either.

I have cleared all cache within the control panel, as well as regular `config:clear / cache:clear` artisan commands. No luck.

Any help is appreciated.

## How to Reproduce
- Publish translations.
- Change app.php locale to `de`
- Change the blueprint value to something..
- Clear all caches.
- You can't see the change reflected in the control panel.

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
The json files are global, so you can put them in `resources/lang/ru.json`. There's no need to use a vendor subdirectory.

If you wanted to override stuff in the php files, then you would need the vendor subdirectory.
