### ISSUE TITLE
missing slash when using link tag 

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#2105]
## Bug Description

When using the link tag the output is missing a slash and this produce 404 links.

## How to Reproduce

In `.env`: `APP_URL=https://my-website.test`
In any template: `{{ link to='my-page' }}`

this outputs: `https://my-website.testmy-page`
instead of: `https://my-website.test/my-page`

## Environment

**Statamic version:** `3.0.0-beta-37`

**PHP version:** `7.4.8`

**Install method:** Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment]
I have created a PR to fix this.
