### ISSUE TITLE
Bard: formatting inside link breaks up the link

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#2109]
## Bug Description

When formatting (e.g. bolding) part of the link text will cause Bard to create three links (one before the bold part, the bold part, and everything after the bold part) instead of just one with bold formatting inside.

## How to Reproduce

1. select some text in Bard
2. make it a link
3. select a substring of the link text
4. make it bold

Now, hovering over the blue text will show you that there are three separate links.

## Environment

**Statamic version:** https://github.com/statamic/cms/commit/cc4b3bd77921faec64af799fcfc27a4c7c6b9022

**Comment by sauerbraten** [comment]
Any news on this?

**Comment by abasse** [comment]
@jasonvarga Could please habe a look at this.

**Comment by jasonvarga** [comment]
Still an issue.

**Comment by jackmcdade** [comment]
No longer an issue. 😊

**Comment by notnek** [comment]
@jackmcdade This is fixed in the CP, but not in the frontend. Should I make a new issue?

**Comment by damcclean** [comment]
> @jackmcdade This is fixed in the CP, but not in the frontend. Should I make a new issue?

Yes please. 🙂
