### ISSUE TITLE
Form time shown needs fixing

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/cms#2125]
Looks like the time of form submissions is hardcoded as `format('M j, Y @ h:i')`
(this appears on line 326 of `src/Forms/Form.php` and line 11 or `resources/views/forms/submission.blade.php`)

This either needs an am/pm adding or changing to `format('M j, Y @ H:i')` as it's not currently possible to tell am from pm at the moment.

If this could read from `config/system.php` or similar so it's possible to change this that would be ideal.

**Comment by jackmcdade** [comment]
Good call, thanks @dannyuk1982!

**Comment by dannyuk1982** [comment]
Cheers, I think this also needs updating in line 326 of src/Forms/Form.php - not sure if you have, the PR doesn't seem to show that though

**Comment by jackmcdade** [comment]
Yup you're right. Thanks!
