### ISSUE TITLE
The trial mode banner should not hide menu links

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#2134]
Its hiding links at the bottom
<img width="245" alt="Screenshot 2020-07-26 at 11 04 04" src="https://user-images.githubusercontent.com/38906163/88475550-3eab9200-cf31-11ea-8ff0-a3870407d5f2.png">

Without the banner
<img width="245" alt="Screenshot 2020-07-26 at 11 04 28" src="https://user-images.githubusercontent.com/38906163/88475552-410dec00-cf31-11ea-86d0-49a583296174.png">

## Environment

**Statamic version:** 3.0.0.-beta-40

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Nice catch, thanks!
