### ISSUE TITLE
Blueprint functionality broken for forms.

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2137]
## Bug Description
You are no longer able to create a blueprints for forms.

Not from the blueprints, nor from when you create a new form. After you create a new form and you are to select a blueprint no blueprints appear. If clicking save on the view attached, the blueprint is created but you can't edit it.

![image](https://user-images.githubusercontent.com/31292231/88526565-60be1680-cffc-11ea-897b-c5a8e7a8fa1c.png)

**Statamic version:** 3.0.0.-beta-40

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by MattRogowski** [comment]
Can confirm this.
