### ISSUE TITLE
Smartypants modifier causes an error

### ISSUE THREAD

**Issue by JayGeorge** [statamic/cms#2139]
## Bug Description

Using the smartypants modifier causes a page error of "The smartypants modifier was not found."

## How to Reproduce

Output a textarea with a modifier of smartypants, for example: `<meta name="description" content="{{ meta_description | smartypants }}" />`

## Extra Detail

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/693601/88546220-f618d500-d013-11ea-9a58-d8840ccb3799.png">

## Environment

**Statamic version:** 3.0.0.-beta-40

**PHP version:** 7.4.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
It can't be found because we removed it. It's baked into the markdown fieldtype now. If you make your `meta_description` a markdown fieldtype with `smartypants: true`, the rendered output will be wearing pants.

**Comment by JayGeorge** [comment]
Ah ok, thanks! Maybe a good idea to remove it from the docs then?

I found it in the v3 version of the docs—https://statamic.dev/modifiers
