### ISSUE TITLE
Blueprints for individual pages no longer possible

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#2140]
## Bug Description
I don't know if the new restructured blueprints are still a work in progress or if this is an oversight, but I can't see how to have a blueprint for one-off pages any more.

Previously I had blueprints for a meet the team page, FAQs page, and homepage, and added the blueprint to the YAML file for the page so it took on those fields. Now, these blueprints have been moved into the `blueprints/collections/pages` folder, and this means that when I go to add a page, I have the option to create a team, FAQs, and even home page, and I don't want this to be the case.

I can't move them out of the `blueprints/collections/pages` folder into just `blueprints/collections` or `blueprints` as then it can't find the blueprint when editing the page.

If I go to Collection > Edit Blueprints, or Collection > Edit Collection > Blueprints > Edit, I only have the option to delete them, and editing the blueprint itself has no option to control its use or visibility.

I may be missing something not covered by the docs, but this is a pretty major issue currently. I like the overall change of having a structure to the blueprints folder, but it seems to assume that every blueprint can be used to create new pages with, which isn't the case. Again, if this is still a WIP or there's a new way to achieve this now, then please let me know and close.

## How to Reproduce
If upgrading from a version before the blueprints refactor, blueprints that were originally only attached to one entry will now be offered as an option when creating an entry.

## Extra Detail
N/A

## Environment

**Statamic version:** 3.0.0.-beta-40

**PHP version:** 7.4

**Install method (choose one):**
Fresh install from `statamic/statamic` from an early beta (but have run the beta 38 blueprint migration script)

**Comment by jasonvarga** [comment]
An oversight, yeah.

We should have a way to hide it from the 'create' selector.

If you can look past that for now, having the blueprint in the collection's directory is still the way to go. Then you can add the blueprint handle to the individual entry like you were already doing.

**Comment by MattRogowski** [comment]
Understood, as long as it's still intended to be possible to do this that's fine! :D Thanks Jason for the lightning response as always.

**Comment by jasonvarga** [comment]
No worries, yeah definitely should be possible. I'm sure we can make this happen soon.

**Comment by nobleintegrations** [comment]
This is potentially related so I think it is worth mentioning. I upgraded a project from beta 28 to 42 and it removed the Blueprint I had for the home page. I could still see the file, but not in the control panel. The other pages were built on a 'pages' blueprint and that one was fine.

**Comment by jasonvarga** [comment]
It didn't move home.yaml into blueprints/collections/pages/home.yaml?

**Comment by nobleintegrations** [comment]
No. It's still under resources/blueprints/home.yaml.

**Comment by jasonvarga** [comment]
Did you run the migration script mentioned in the changelog? https://gist.github.com/jasonvarga/ce4f0ad8e3b6d934f8d9da489f2ef64b

**Comment by nobleintegrations** [comment]
Oops. Didn't see that. Nope, I just ran a composer update

**Comment by jasonvarga** [comment]
Closing in favor of #2419
