### ISSUE TITLE
v3 Control Panel Allows Field Handle Collisions for Blueprint Fields

### ISSUE THREAD

**Issue by grovberg** [statamic/cms#2141]
## Bug Description
The control panel allows me to create two fields in a Blueprint with the same name and saves successfully. Once that happens any attempt to load the blueprints page yields a full-page exception error.

"Exception Duplicate field [fieldname] on blueprint [blueprintname]."

Interestingly, after you do this, hitting the back button will take you back to the (presumably cached) Blueprint Edit page. Attempts to fix the problem here will result in what I assume is the intended notification-style error message (which is why I'm assuming this is a bug and not the expected behavior) but does not actually allow you to fix the problem. 

"Duplicate field [fieldname] on blueprint [blueprintname]"

The only solution I could find was to edit the YAML file directly.

## How to Reproduce
Create a Blueprint. Create two fields with the same name. Hit Save. Click the Blueprints link in the sidebar.
## Extra Detail

![exception](https://user-images.githubusercontent.com/4681855/88597876-3426f080-d036-11ea-9849-ad9c76111be8.png)

![notification](https://user-images.githubusercontent.com/4681855/88597175-ac8cb200-d034-11ea-950d-a170f0fc256b.png)

## Environment

**Statamic version:** 3.0.0.-beta-{?}

**PHP version:** 7.4.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jesseleite** [comment]
Fixed in https://github.com/statamic/cms/commit/e6e2b0f3eddeaa632daed100f435cdc8f2dc3c2d
