### ISSUE TITLE
Users Fieldtype missing default in CP

### ISSUE THREAD

**Issue by Rovaski** [statamic/cms#2143]
## Bug Description
When creating a Users field in the CP, you can't set default from the CP.
Suggest adding the default field, so that users can set 'Current' and the

`            'default' => [
                'display' => __('Default'),
                'instructions' => __('Setting to current will default the field to the currently logged in user.'),
                'type' => 'text',
                'width' => 50,
            ],`

**Comment by damcclean** [comment]
I think this issue affects more than just the User fieldtypes, there's actually no way to set the default value for any of the fields (I've tested text and form).

I think this issue is related to #672.
