### ISSUE TITLE
Cannot add related field to blueprint

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#2144]
## Bug Description
There may be 1 or 2 issues here so have put them together in case they are related.

I had a "content" fieldset added which was basically just a Bard field with all my blocks added, that I then added to blueprints.

I just re-saved two blueprints, and it seemed to convert the related fields to be directly-added fields, i.e. all the fields in the _related_ fieldset were now added directly to the blueprint (the YAML file changed the `import` key to `handle` with all the fields, see screenshot).

![image](https://user-images.githubusercontent.com/545339/88695460-d52aaf80-d0f9-11ea-9149-ae7aca47b79e.png)

Not sure why this happened, but if this is due to a change in a release at some point then can disregard this bit (but may also be a bug, I'm not sure).

The main issue is I'm now trying to re-attach the related field, but when I select it from the 'Link Fields' pane, and it posts to `/fields/edit`, I get the following error:

`Undefined index: field` - error from line 56 of `/cms/src/Fields/FieldTransformer.php`

If I then close the pane, and save the blueprint anyway, it does seem to add it:

![image](https://user-images.githubusercontent.com/545339/88695835-5a15c900-d0fa-11ea-937c-68b3fa2f5cc4.png)

I notice the syntax for importing the fieldset has changed which explains the first issue.

It does pull through when adding an entry, so seems like it's saved it properly, however the little width selector thing doesn't work on the blueprint page so I can't change it from, in this case, 66% - the hover effect works, but clicking it doesn't do anything.

![image](https://user-images.githubusercontent.com/545339/88696089-b4af2500-d0fa-11ea-8cce-8cd1dd369885.png)

## How to Reproduce
Create a fieldset
Try to link the fieldset to a blueprint
The AJAX call will fail, but if you close the pane and save the blueprint, it will save - however the width selector won't work

## Environment

**Statamic version:** I initially encountered it on 3.0.0.-beta-40 but have another installation on beta-37 which has the same issue, so doesn't appear to be a recent regression.

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic` and an older version that's been upgraded throughout the beta

**Comment by jasonvarga** [comment]
I believe this has been resolved already. Please reopen if that's not the case.

**Comment by jasonvarga** [comment]
Nope, still exists!

**Comment by jelleroorda** [comment]
Open sesame

**Comment by jacksleight** [comment]
I'm also seeing this issue in 3.0.40. Steps to reproduce:

1. Create a new fieldset
2. Add a Bard field with at least one set (it works if Bard doesn't have any sets)
3. Go to a blueprint and try to link the Bard field (just the field, not the whole fieldset)
4. The request fails and the UI stops on the loading screen:

![Screenshot 2021-02-02 at 09 57 34](https://user-images.githubusercontent.com/126740/106584280-eab3e280-653d-11eb-8244-b42fa574e8de.png)

**Comment by andymnewhouse** [comment]
My error isn't "undefined index" but `Undefined array key \"field\"`

**Comment by bakerkretzmar** [comment]
Also seeing this on 3.1 with `Undefined array key \"field\"`.

**Comment by jelleroorda** [comment]
Hi guys, please upvote the original description instead of adding a comment. The team can sort issues based on thumbs up, as well as they don't send any notifications.

**Comment by marcusand** [comment]
Just stumbled across this issue and I am on the latest release 3.1.32...how come this is still not solved after over a year???

**Comment by jasonvarga** [comment]
I can't recreate this. If you could please add exact steps to reproduce it, that would be helpful.

I followed jacksleight's steps and it worked fine.

**Comment by bakerkretzmar** [comment]
I can only reproduce it when the linked field is called `content`, but it's still there. @jasonvarga here's a repo that reproduces it (the super user is `jacob@example.com`/`password`): https://github.com/bakerkretzmar/issue-2144-related-field

Go to the Pages blueprint and try to edit the linked Bard `content` field. I used to see it _while adding_ the field too, but in a new Statamic app now that seems to work.

**Comment by stuartcusackie** [comment]
Just ran into this issue as well. My bard field is also called 'content'. Renaming it and flushing the caches did not fix it.

If I create the field directly on the blueprint instead, without fieldset linking, then it works fine. If I remove the sets from the bard field it also works fine.

It seems that the problem has something to do with adding sets to a linked bard field. I'm sure this worked fine on another site I made recently.

**Comment by sheggi** [comment]
@jasonvarga here are some steps to reproduce this issue, this time I used a replicator.

1. fresh Statamic installation with testuser
2. create fieldset with one replicator of couple sets
3. create page blueprint and save
4. refresh browser
5. link existing > link single field > select replicator
6. save blueprint
7. refresh browser and try to edit => edit window keeps loading because `Undefined array key "field"` 500 ServerError

The trick is, as long the browser isn't refreshed after saving the blueprint, the edit overlay can be opened and closed without any problem. As soon the browser is refreshed, the issue persists.

Repo with this issue
https://github.com/sheggi/statamic-linked-replicator-edit-bug
Login Credentials
https://github.com/sheggi/statamic-linked-replicator-edit-bug#login
