### ISSUE TITLE
S3 asset container list view caching

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#2145]
Look into S3 asset container list view caching.  Apparently some users are experiencing slow down and request timeouts when connecting to buckets with large file counts.

**Comment by goellner** [comment]
we implemented the cache value on a site, maybe this fixes the list view caching issue?

```
        's3assets' => [
            'driver' => 's3',
            'key' => env('AWS_ASSETS_ACCESS_KEY_ID'),
            'secret' => env('AWS_ASSETS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_ASSETS_DEFAULT_REGION'),
            'bucket' => env('AWS_ASSETS_BUCKET'),
            'url' => env('AWS_ASSETS_URL'),
            'cache' => true,
        ],
```

**Comment by edalzell** [comment]
@goellner how many assets were in that container? We have one w/ 110K+ and the CP won't display at all.

**Comment by goellner** [comment]
@edalzell not that much, only around 1k assets in total in different subfolders

**Comment by ericlbarnes** [comment]
I just hit this issue as well on v3.0.20. I have an s3 container setup and that loads fine, but inside the s3 bucket, I have an "images" folder that contains 2400 images. It's impossible to load that folder through the CP. It seems to just time out with the error "This container is empty".

**Comment by sg-modlab** [comment]
Curious if there are any updates on when a look at S3 for media management may happen.

**Comment by jasonvarga** [comment]
This issue is internally marked as a priority. We should be addressing this soon.

**Comment by goellner** [comment]
all my folders inside an s3 bucket are now listed on every paginated page in the assets browser

**Comment by jesseleite** [comment]
@goellner Good find, though this seems to be unrelated to S3 and the recent improvements; It happens in 3.0.25, and in a local asset container as well. Created an issue for it here: #2829.
