### ISSUE TITLE
PopperJS scroll handler takes a long time, impacting performance

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#2147]
## Bug Description

While profiling our Homepage edit page (and live preview mode), @jojotl noticed a lot of slow scroll handlers registered by PopperJS. It seems they purposely don't use debouncing: https://github.com/popperjs/popper-core/issues/541. Globally deactivating PopperJS's scroll listener seems to fix this:

```diff
diff --git a/resources/js/components/Popover.vue b/resources/js/components/Popover.vue
index c4ac690ad..c2278aae4 100644
--- a/resources/js/components/Popover.vue
+++ b/resources/js/components/Popover.vue
@@ -54,6 +54,13 @@ export default {
                         options: {
                             offset: this.offset
                         }
+                    },
+                    {
+                        name: 'eventListeners',
+                        options: {
+                            scroll: false,
+                            resize: true
+                        }
                     }
                 ]
             })
```

We couldn't find anything wrong with this, but we're unsure wether this could cause problems somewhere not immediately obvious.

Another thing we noticed is that EQCSS still causes some delays on mousemove, which seems like it can be safely disabled, like input in #1919:

```diff
diff --git a/resources/js/vendor/eqcss/index.js b/resources/js/vendor/eqcss/index.js
index 8337182c3..9822756f4 100644
--- a/resources/js/vendor/eqcss/index.js
+++ b/resources/js/vendor/eqcss/index.js
@@ -1493,15 +1493,15 @@ License: MIT
 
       })
 
-      window.addEventListener('mousemove', function() {
+      // window.addEventListener('mousemove', function() {
 
-        if (EQCSS_mouse_down) {
+      //   if (EQCSS_mouse_down) {
 
-          EQCSS.throttle()
+      //     EQCSS.throttle()
 
-        }
+      //   }
 
-      })
+      // })
 
       window.addEventListener('mouseup', function() {
```

## How to Reproduce

Performance degrades heavily when using the edit page and/or live preview mode with an entry that has pretty much just one replicator field, but large amounts of complicated replicator sets. Scrolling inbetween usage will be sluggish, opening and closing the "three dots" menu of a replicator set takes a second or more, etc.

## Environment

**Statamic version:** HEAD (at least still a problem after #1919)

**PHP version:** 7.3

**Comment by sauerbraten** [comment]
Here's a screenshot of our profiling results:

<img width="1440" alt="Bildschirmfoto 2020-07-16 um 14 57 33" src="https://user-images.githubusercontent.com/1760908/88773607-9e4cac00-d182-11ea-9d95-323a29fd55e1.png">

`forceUpdate` is part of PopperJS, not Vue (which we initially assumed).

**Comment by jackmcdade** [comment]
Thanks for working this out!
