### ISSUE TITLE
Form entries take a very long time to delete from the CP

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2153]
Form submissions in the CP are taking a very long time to delete. On top of that something else is going on...

I had 80 form submissions I had to delete this morning. Pagination was set to 50. I did select all and delete. That operation took over a minute with that top progress bar ticking along. So that took a while for only 50. But then when that finished and refreshed I had 30 left. I did select all, delete, it took another long time but then just refreshed with them still there?

On beta40
Live server (dedicated DO server with lots ram and cpu)

**Comment by jasonvarga** [comment]
Are you using the git features? I have a feeling maybe it was doing a commit after every deletion.

You may want to look at queueing and/or delaying commits:
https://statamic.dev/git-integration#queueing-commits

**Comment by twd3** [comment]
Yeah, I am and that sounds about right. Let me take a look.

**Comment by twd3** [comment]
I cannot use that delay commit with the sync queue driver and **I don't know how to setup a different queue driver so I'm stuck**. If I delayed that commit even by 1 minute I bet it would fix this issue.

Not sure how much more info you guys need. Using git integration with form storage and resource paths hooked up, automatic true, push true.

**Comment by jasonvarga** [comment]
Follow the documentation to learn how to set up queues.

Without a queue, it will be each deletion. Not really a way around that. Except for enabling the queue.

Or just delete the submission files.

**Comment by twd3** [comment]
Got redis going, I'll figure out from here. Thanks for letting me know!
