### ISSUE TITLE
Update via control panel fails on Windows 10

### ISSUE THREAD

**Issue by jmartsch** [statamic/cms#2156]
## Bug Description
When trying to update via Tools > Update, it does not work on Windows 10.

## How to Reproduce
Click on update
Wait for the modal to finish
See that nothing has changed

## Extra Detail

Here is a video of the issue:
http://www.youtube.com/watch?v=uaZynzNxryw

## Environment

**Statamic version:** 3.0.0.-beta-38

**PHP version:** 7.3

**OS:** Windows 10 Insider Preview 19041.1 (vb_release)

**Install method (choose one):**
Statamic from a starter repo, updated multiple times on console via `composer update`
Also does not work from a fresh installed Statamic via composer

**Comment by jasonvarga** [comment]
Related to #1918

**Comment by jmartsch** [comment]
this still affects me

**Comment by jackmcdade** [comment]
Updating in the Control Panel is no longer supported in v4, so we can close this issue as a `wontfix`.
