### ISSUE TITLE
Visiting a specific CP url as a non-admin results in too many redirects instead of a sensible error

### ISSUE THREAD

**Issue by stancl** [statamic/cms#2166]
## Bug Description

Visiting a specific CP url as a non-admin results in too many redirects instead of a sensible error

## How to Reproduce

Log in as admin, copy URL to some resource, visit it in a browser window where you're logged in as a different, non-admin user and you'll see too many redirects

## Environment

**Statamic version: latest**

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Does this issue still happen for you?

**Comment by stancl** [comment]
Should I update my version constraint to the stable one before trying?

**Comment by edalzell** [comment]
> Should I update my version constraint to the stable one before trying?

Yes

**Comment by jackmcdade** [comment]
We haven't heard back for 3 weeks so I'm going to close this. If you still have the issue even after updating your version constraint, please reopen with more details and we'll see what needs to be done!

**Comment by DrTrills** [comment]
I've been getting this error this past week. Usually after a deployment via Forge to Linode. If it. happens again i'll try to get as much details as possible and pass along
