### ISSUE TITLE
Allow using Bard without Sets (from the CP)

### ISSUE THREAD

**Issue by pryley** [statamic/cms#2171]
I want to create a Fieldset for a Hero page section. The Fieldset would contain a Bard field (for the heading and text), and a Asset or Video field. Obviously I don't want other fields inside Bard as the hero section is highly opinionated, but It would be nice to provide the flexibility for the user to decide whether they want a heading, and whether it should be H1 or H2. 

I could provide separate fields for the heading and hero text but this is an unnecessary waste of space. I could also provide a Markdown field, but I like the visual editing of the Bard field.

**Comment by pryley** [comment]
@jasonvarga I've run into an issue with Bard where the following code no longer works when all sets are removed:

```
{{ bard }}
    {{ partial src="components/{type}" }}
{{ /bard }}
```

Not sure if that commit addresses this.

**Comment by jasonvarga** [comment]
If there are no sets then you don’t have to loop over anything. {{ bard }} will just be a string.

**Comment by pryley** [comment]
Ah, that makes sense! Confirmed that this works:

```
{{ partial src="components/text" text="{ bard }" }}
```
