### ISSUE TITLE
Focal point cropping: thumbnail not loading (404 Not Found) when CP route uses non-ASCII characters

### ISSUE THREAD

**Issue by miclf** [statamic/cms#2175]
Hi ladies and gentlemen. I’m happy to report one of those lovely bugs affecting non-English speaking systems and applications :)

## Bug Description

Thumbnail does not load when trying to use the focal point picker in the control panel.

When inspecting network requests, we can see that we get a `404 Not Found` for `https://my-domain.test/r%25C3%25A9daction/thumbnails/aW1hZ2VzOjpjaGF0b24uanBn`.

The `r%25C3%25A9daction` part here is for `rédaction`. This would be `cp` with the default route to the control panel (defined via `CP_ROUTE` environment variable or the `route` option in the `config/statamic/cp.php` file).

**The problem comes from the fact that this is URL-encoded _two times_ instead of one.**
URL-encoding `rédaction` gives us `r%C3%A9daction`. But, for some reason, the URL gets encoded a _second_ time, giving us `r%25C3%25A9daction` instead.

I guess that Laravel then tries to URL-decode this _once_, then getting `r%C3%A9daction` instead of `rédaction`, thus throwing a `404 Not Found`.

## How to Reproduce

Configure a CP route with a least one non-ASCII character. Here are some to choose from: `é à û ç ï`

To do so, set a `CP_ROUTE` variable in your environment file, or update the `route` option in the `config/statamic/cp.php` file.

Then, try to use the focal point picker for any image asset.

## Extra Detail

Here is a screenshot with a lovely kitten.
 
![foo](https://user-images.githubusercontent.com/3188746/89238340-fa398980-d5f5-11ea-8cd7-8b31fc78a811.png)

## Environment

**Statamic version:** 3.0.0-beta.33

**PHP version:** 7.4.7

**Install method:** existing Laravel app

**Comment by jasonvarga** [comment]
Potential solution suggested in https://github.com/statamic/cms/issues/1931#issuecomment-644034871

**Comment by miclf** [comment]
@jasonvarga Is your comment a note to yourself and/or others from the Statamic team or is it a suggestion for people wanting to implement a workaround by themselves?

Silly question maybe, I’m asking just to be sure :)

**Comment by damcclean** [comment]
I think it was probably a note to self comment 😃

**Comment by miclf** [comment]
Don’t touch that `Close` button, you feelingless robot.

**Comment by jasonvarga** [comment]
I can't reproduce this issue. My URLs always seem to show the first, single-encoded version. 🤔

**Comment by jasonvarga** [comment]
Apparently #3421 will fix this, although I wasn't able to get it to break in the first place.

If it's still not fixed, feel free to tell us to reopen it.
