### ISSUE TITLE
Outline issue with bard sets in Safari

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2188]
## Bug Description
Bard causes extensive outlining in Safari when using the set selector.

## How to Reproduce
Add a bard, with a set, open safari en click the button.

## Extra Detail
<img width="1449" alt="Screenshot 2020-08-06 at 14 54 13" src="https://user-images.githubusercontent.com/69107412/89534191-d85a2580-d7f4-11ea-9e78-abf2aa1b3068.png">

## Environment
Safari Catalina / Big Sur

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Good one, thanks!

**Comment by robdekort** [comment]
Nice Jack. Ha, I tried to find the issue in the inspector when I was reporting this, but obviously I didn't try giving all children outline none :-)

**Comment by jackmcdade** [comment]
When nothing else words, try everything!
