### ISSUE TITLE
Bard table management icons are the wrong colour

### ISSUE THREAD

**Issue by ellimondo** [statamic/cms#2189]
## Bug Description

Bard toolbar (in **Floating** mode) is not colouring icons correctly when managing tables

## How to Reproduce

Highlight a column or row of a table inside a Bard Field to activate.

## Extra Detail

![Bard floating editor table icons](https://www.dropbox.com/s/regmff2833b4imd/Screenshot%202020-08-06%2014.26.53.png?raw=1)

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.4.7

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Thanks for reporting this! My apologies it took so long to fix something so trivial.
