### ISSUE TITLE
UI-Issue with replicator

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2190]
## Bug Description
See screen.
## How to Reproduce
Multiple assets in replicator.
## Extra Detail

![image](https://user-images.githubusercontent.com/3351449/89542760-64be1580-d800-11ea-85c3-90f215b98c5c.png)

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
