### ISSUE TITLE
Git Integration is not pushing automatically after content changes

### ISSUE THREAD

**Issue by tao** [statamic/cms#2191]
## Bug Description
I have Git Integration enabled on a Laravel Forge site, however git pushes do not happen automatically after content is changed. I expect that after a page save it would git push straight to the master branch.

```
STATAMIC_GIT_AUTOMATIC=true
STATAMIC_GIT_ENABLED=true
STATAMIC_GIT_PUSH=true
```

These are the env settings and `dispatch_delay` is not set, so it defaults to 0.

On the utilities/git page in the cms, the changes do appear, and I can manually git push them successfully, but I'm hoping to push automatically on each save so the editors don't have to think about it.

Is anyone else able to git push automatically?

## Environment

**Statamic version:** 3.0.0.-beta-42

**PHP version:** 7.4

**Comment by twd3** [comment]
Make sure you have pro enabled because this is not happening to me. Also, if you are using redis you have to set-up the worker, then it will auto-push. I am only having an issue with assets .meta not auto pushing.

**Comment by tao** [comment]
I've tried another custom server and I'm still unable to get this to push instantly, however I noticed in the Statamic docs it mentions the env `QUEUE_CONNECTION=sync` while the default queue env in Laravel is `QUEUE_DRIVER=sync`...

**Comment by tao** [comment]
After a lot more investigation and testing I found the Laravel logs have these messages, which seems to be causing the problem. So I don't believe it's a Spock issue anymore but I'm going to keep testing and see if I can fix this and give an update.

```
[2020-08-08 00:50:19] localhost.ERROR: Git Process: Could not create directory '/usr/share/httpd/.ssh'.
[2020-08-08 00:50:19] localhost.ERROR: Git Process: Host key verification failed.
[2020-08-08 00:50:19] localhost.ERROR: Git Process: fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
```

**Comment by tao** [comment]
For anyone that runs into this problem in the future, the issue is the apache server runs the code and so the SSH key also needs to belong to the apache user. I was able to verify my apache owned SSH key with Github with the following command:

```
sudo -u apache ssh -T git@github.com
``` 

I have a more details [tutorial](https://www.karuna.co.za/gists/zero-to-spock/) that I'm working on which explains the permissions issue and how I've managed to get Git Integration working on an AWS server.

**Comment by smlparry** [comment]
Thanks for that @tao 

For anyone running `nginx` you may have to use the `www-data` user instead

You can check which user is running the nginx / php-fpm process by running `ps aux` 

Then you need to make sure that you have the Github SSH key setup for _the user running the process_

In my case, it was `www-data`, I setup the SSH key for that user following this tutorial:
https://www.drupal.org/docs/8/modules/git-info-report/assign-the-user-www-data-an-ssh-key-and-add-it-to-the-remote-repo

> Check first what user is being used to run the CLI commands integrated into the module. In most cases, the user is www-data. We presume that in the rest of the instructions below. Substitute if necessary.
In the terminal:
>
> Create a new hidden directory:sudo mkdir /var/www/.ssh
>
> Change folder permission: sudo chown -R www-data /var/www/.ssh
>
> Create the ssh key as user www-data: sudo -u www-data ssh-keygen -t rsa
> 
> Open the generated key file (/var/www/.ssh/id_rsa.pub) with a text editor and copy-paste the content to your user profile SSH Keys on the remote repo. On GitLab, when logged in, this is found at https://gitlab.com/profile/keys/.
>
> Then in the terminal from a Git repo, use sudo -u www-data git ls-remote to provoke the first connection to the remote repo as user www-data manually. It will say The authenticity of host X can't be established. Confirm you would like to add it to the list of known hosts. All points above are a one-time operation, per machine, per repository service provider. Once set correctly, it does not need to be repeated, not even for another project.
>
> Refresh the Status Report and check if after the remote repo address you now see either No pull needed or Your branch is behind. If so, it works as expected.
