### ISSUE TITLE
Deleting a collection entry does not remove existing references in content 

### ISSUE THREAD

**Issue by pryley** [statamic/cms#2195]
## Bug Description

The most annoying bug I'm encountering with v3 is that deleting a page does not alway reflect across fields used in Bard Sets in other entries.

## How to Reproduce

1. Create a page, then reference that page in a fieldset on another page with the Link field (or any other field that allows you to link to an existing entry). In my case I am referencing an entry in a Link field inside a Grid field inside a Bard Set. 
2. Now delete the referenced page.

## Extra Detail

![image](https://user-images.githubusercontent.com/134939/89685530-2426d080-d8c2-11ea-91f0-fbaab1c3b8a8.png)

![unknown](https://user-images.githubusercontent.com/134939/89683583-6c43f400-d8be-11ea-97c2-0f80764a65b9.png)

The `is_local_url`modifier show in the error screenshot is a custom modifier that detects if the absolute url is a local url (see: https://gist.github.com/pryley/782c2653fe0245099f671a959adaa8a0). 

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.4.8

**Install method (choose one):**

- Fresh install from `statamic/statamic`

**Comment by leganz** [comment]
I agree with that - it is annoying but in your case a missing nullcheck in the template is causing the problem right?
Wouldn't it be more accurate to add the nullcheck instead? At least for the exeception that would be imo the proper solution.
But indeed removing deleted collection items references from other files would be neat.

**Comment by pryley** [comment]
The custom modifier is not causing the problem as it happens whether of not the custom modifier is used. The issue has to do with the reference to the missing (null) entry.
