### ISSUE TITLE
Cannot edit asset if its blueprint has a condition based on a Taxonomy field

### ISSUE THREAD

**Issue by miclf** [statamic/cms#2196]
## Bug Description

When trying to modify an asset in a container, Statamic correctly shows the asset and the three buttons to define focal point/rename the file/move it. But **it shows a blank area where the fields defined in the blueprint should appear**.

An error appears in the browser console (see **Extra Detail** section).

## How to Reproduce

I have:
- an asset container (called `images`)
- a blueprint for it
  - one of the fields in this blueprint, called `licence`, is a Taxonomy (singular, not plural). It refers to a `licences` taxonomy and is limited to 1 element max.
  - there is also a simple Text field called `author`

To reproduce the bug, add a condition on the `author` field stating that it should appear only if the `licence` field is not a given value (for context: my goal is to have the “Author” field appear only when a licence has been chosen, and one of the possible values for the `licences` taxonomy is “none” — I couldn’t find any other way to make the licence field optional #noob).

I tested all the types of conditions (except “custom”), and **was able to reproduce the bug with the following ones**:

- `equals`
- `not`
- `===`
- `!==`

## Extra Detail

Error in browser console **when using the `equals` condition type**:

```
SyntaxError: expected expression, got '=='
    passesCondition Validator.js:209
    value Validator.js:62
    Underscore 6
    value Validator.js:62
    value Validator.js:33
    showField ValidatorMixin.js:14
    a Fields.vue:1
    vt VueJS
    a Fields.vue:1
    VueJS 61
    load Editor.vue:257
    promise callback*load Editor.vue:255
    mounted Editor.vue:231
    VueJS 19
    edit Browser.vue:496
    editAsset AssetManager.vue:117
    VueJS 4
vue.common.prod.js:6:11579
```

Error in console **when using the `not` condition type**:
```
SyntaxError: expected expression, got '!='
```

Error in console **when using the `===` condition type**:
```
SyntaxError: expected expression, got '==='
```

Error in console **when using the `!==` condition type**:
```
SyntaxError: expected expression, got '!=='
```

And here is a screenshot:

<img width="1428" alt="foo" src="https://user-images.githubusercontent.com/3188746/89714206-5f4a0200-d99d-11ea-94b3-380d1eb092cc.png">

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.4.7

**Install method:** existing Laravel app

**Comment by miclf** [comment]
Don’t touch that `Close` button, you feelingless robot.

**Comment by duncanmcclean** [comment]
This issue seems to be fixed now.
