### ISSUE TITLE
Glide bug with latest facade/ignition dependency

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#2200]
## Bug Description

While re-installing all composer deps, I've notice in my `composer.lock` file that `facade/ignition` package have bien update from `2.3.5` to `2.3.6`.

This is a minor update so it should be ok but I get this error:

<img width="1235" alt="Screenshot 2020-08-10 at 18 26 54" src="https://user-images.githubusercontent.com/10623367/89806281-1b8b0000-db37-11ea-8f4e-1bc99414afc6.png">

## Environment

**Statamic version:** 3.0.0.-beta-43
**PHP version:** 7.4.9
**Install method:** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
I don't think that has anything to do with Ignition.

What image is it trying to manipulate? Is it an svg?

**Comment by jimblue** [comment]
Oh my bad... I jus notice my env also update `php imagick`.
Restarting Valet fixed my issue so nothing to do about Ignition... Sorry :sweat_smile:
