### ISSUE TITLE
Title field doesn't obey width setting

### ISSUE THREAD

**Issue by Krzemo** [statamic/cms#2203]
## Bug Description
When working with blueprints and changing TITLE field's width i.e. to fit other fields next to it, title input always stays 100% width.

## How to Reproduce
Change title's field width:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/1293123/89905508-952ff600-dbea-11ea-95cc-1ae16733a491.png">

Edit content:
<img width="968" alt="image" src="https://user-images.githubusercontent.com/1293123/89905625-b395f180-dbea-11ea-9e40-23337dbf46b1.png">

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Seems fine here. I know you had an issue with duplicate title fields recently. I'm going to assume it was related to that and this is no longer an issue. Let us know if that's not the case.
