### ISSUE TITLE
Unexpected Event Triggering

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2210]
## Bug Description
I'm not sure if the following is a bug or by design. 

The `EntrySaving` event is triggered every time you open an entry in the CP. Not just when you actually hit the save button. 
The `EntryBlueprintFound` event is triggered when loading entries on the front end. Not just when loading an entry on the CP with that blueprint.

Is this the expected behavior?

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.4.6

**Install method:** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
EntrySaving doesn't sound right.
EntryBlueprintFound does.

**Comment by jasonvarga** [comment]
Do you have any addons installed?

**Comment by aerni** [comment]
Just the one I'm working on. Nothing else. I'm listening for those events from within that addon.

**Comment by jasonvarga** [comment]
It's not happening here.

Another details about your setup you can provide?

How are you determining it's being triggered so often? What does your listener code look like?

**Comment by aerni** [comment]
This is my Listener:

```php
namespace Aerni\Snipcart\Listeners;

use Statamic\Events\EntrySaving;

class UpdateStock
{
    public function handle(EntrySaving $event): void
    {
        $event->entry->set('stock', 999);
    }
}
```

This in my addon's Service Provider:

```php
protected $listen = [
    'Statamic\Events\EntrySaving' => [
        'Aerni\Snipcart\Listeners\UpdateStock',
    ],
];
```

The `stock` will be set to `999` when loading the entry. Not just when hitting the save button.

**Comment by jasonvarga** [comment]
Do you have any other addons or custom code installed?

**Comment by aerni** [comment]
No, just the addon I'm working on. I tried reproducing the issue myself on a fresh install. Everything works as expected. Can't reproduce it. No idea why this happened before. You can close the issue for now. I will be back if I encounter it again.

**Comment by aerni** [comment]
I think I found the issue. The event only fires when there's no blueprint defined on the entry you're opening.

**Comment by jasonvarga** [comment]
Still can't replicate this. I can see no reason why that event would be dispatched when _opening_ an entry in native Statamic. Try uninstalling any addons or disabling any custom app code that you might have and see if it continues.

If you can recreate it consistently, please let us know how.
