### ISSUE TITLE
Multi-Site: Title, slug and parent are out of sync on every edit

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#2211]
## Bug Description
When having a multi site, there are currently a few problems regarding the saving and editing process:
- parent field is not localizable by default
- title, slug and parent field are out of sync on every edit -> root value by default
- parent is out of sync upon creating a new localized version -> again, root by default

Related: #2172, #2176

## How to Reproduce
Create a multisite and try the above. At least two locales necessary. 

## Environment
Laravel Valet

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.4

**Install method (choose one):**
- Used statamic install

**Comment by AndreasSchantl** [comment]
@jackmcdade Can this get a bit more attention? This is a really annoying bug for a customer of mine. Thanks. Maybe I get the time to dive into it myself.

**Comment by jackmcdade** [comment]
Yes we're going to work on multisite as a whole this week. 👍

**Comment by jasonvarga** [comment]
The out of sync issue is fixed for 3.0.2 in 2059206

The parent field not being localizable... not yet (but will probably also eventually be in 3.0.2)
