### ISSUE TITLE
{{ now }} does not work in partials

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#2214]
## Bug Description
The `{{ now }}` variable does not work in partials.

## How to Reproduce
Put the `{{ now }}` variable in a partial.

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.2.30

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Just tried to reproduce on one of my sites and it seems to work 🤔

**Comment by jcohlmeyer** [comment]
This was not actually the issue.
