### ISSUE TITLE
Stache indexes needs to be able to invalidate at a given time

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2217]
## Bug Description

Future dated entries are excluded from collection listings (with the appropriate config) which is great. Until time passes and they are supposed to be included. They don't, because the tag is querying by`status`, and it's still `scheduled` in the Stache index. Which is not great.

## How to Reproduce

Have an future dated entry.
Have a collection tag.
See the entry is missing.
Wait until its date is in the past.
See it's still missing, but should be included.

## Extra Detail

I think we can solve this by giving the Stache indexes a little more smorts.

When we insert a value, we should be able to optionally give it a timestamp for when it needs to be reindexed.
For example, when we insert a `status` of `scheduled`, we should pass the date.
When reading the value, we can see if it needs to be re-evaluated.

Or something.

## Workaround

To get around this for now though, you can use status and date params.

```
{{ collection:stuff status:exists="true" date:is_past="true" }}
```

## Environment

**Statamic version:** 3.0.0-beta.43

**Comment by ReneWeCode** [comment]
@jasonvarga Kinda related to https://github.com/statamic/cms/issues/2070

**Comment by aerni** [comment]
This workaround sadly doesn't work with full static caching. There needs to be a way to flush the static cache when an entry changes its status from `scheduled` to `published`.

**Comment by aerni** [comment]
I thought I could get around this by manually flushing the static cache when an entry changes its status. But there's no event like `EntryStatusChanged` that I can listen to.

**Comment by aerni** [comment]
The workaround mentioned above doesn't seem to work anymore. I'm on v3.2.2.

**Comment by sunscreem** [comment]
My workaround for now is to schedule a `stache:clear` for midnight.

**Comment by aerni** [comment]
@sunscreem You sure this works? I did quite some testing and even clearing the stache after an entry should change its status didn't help. The status stays at scheduled.

**Comment by sunscreem** [comment]
@aerni I'm not 100% sure, as I only discovered the bug this morning. But in order to test my theory I went onto the production server and run `php please stache:clear` and the scheduled article that should have appeared was now there. I'll schedule a test for tonight and get back to you.

**Comment by jasonvarga** [comment]
If you're using static caching you'll also have to clear the static cache.

**Comment by helloiamlukas** [comment]
The proposed workaround doesn't really work when using the API. Any ideas how to solve this without having to run `php please stache:clear` every hour?

**Comment by jasonvarga** [comment]
> The proposed workaround doesn't really work when using the API.
Why not?

**Comment by helloiamlukas** [comment]
🤦 Sorry, I completely missed out that I can use all the filters and conditions in the API too! The workaround works fine in the API too, thanks :)

**Comment by FrittenKeeZ** [comment]
Handling static cached sites, I suggest using a scheduled task running every minute, querying the stache for entries with exceeded dates and trigger invalidation for that entry.
Using proper invalidation rules (or a custom dynamic invalidator), you can purge relevant pages like an overview or anything related.
Does that make sense?

**Comment by Buffalom** [comment]
I just ran into this issue using the GraphQL-API. The workaround (filtering by dates in the past) works, but is very much a downgrade from "it just works in the API automatically and I don't have to worry about it in the frontend".

@FrittenKeeZ I suppose with a scheduled task running every minute, dates with seconds enabled would not be precise.

**Comment by FrittenKeeZ** [comment]
@Buffalom since cron only runs every minute, you'd need an external actor to trigger invalidation every second instead - the method is the same.

This is the action I trigger from cron every minute:
```php
<?php

namespace App\Actions;

use App\Contracts\Actions\InvalidatesScheduledEntries;
use Illuminate\Support\Carbon;
use Statamic\Entries\EntryCollection;
use Statamic\Facades\Entry;

/**
 * Invalidate scheduled entries.
 */
class InvalidateScheduledEntries implements InvalidatesScheduledEntries
{
    /**
     * {@inheritDoc}
     */
    public function __invoke(): EntryCollection
    {
        $entries = Entry::query()
            ->where('status', 'scheduled')
            ->where('date', '<', Carbon::now())
            ->get()
        ;

        return $entries->each->save();
    }
}
```

**Comment by Buffalom** [comment]
That's right. I thought maybe there's a different way to do it so invalidating is not even required. As in not caching the status but rather the date and filtering by date instead or something like that. I am not talking about a workaround, but rather what should be considered for a proper solution.

This is my workaround for now. It is supposed to handle every kind of outdated status. No matter how the collections are configured.

```php
collect([
    'scheduled',
    'published',
    'expired',
])->each(function ($status) {
    Entry::query()
        ->where('status', $status)
        ->get()
        ->each(function ($entry) use ($status) {
            if ($entry->status() === $status) {
                return;
            }

            // Invalidate this entry
            $entry->saveQuietly();
        });
});
```

**Comment by aerni** [comment]
Does PR https://github.com/statamic/cms/pull/5089 for solve your issue?

**Comment by Buffalom** [comment]
@aerni wow, it does. I am amazed. Thank you. That feels like a much nicer solution. It even allows enabling seconds 😍 

P.S. You really should come by our office in Bern for coffee sometime. @motion-work and I are expecting you, so we can talk about Statamic and other stuff :)

**Comment by Buffalom** [comment]
Ah, I have a question though @aerni. [In your PR](https://github.com/statamic/cms/pull/5089/files#diff-f6be6f1ce60a6fc6bc71c1272eefa109cf1b56418a4901dfdf184b9cbcca0786R38) you have a hardcoded `'scheduled'`. Does this mean it does not work for collections with date handling set so entries expire rather than being scheduled?

**Comment by aerni** [comment]
@Buffalom I don't understand your question. I suggest you try it out. If it doesn't work as you expect it to, then leave a comment on the PR.

P.S. I recently moved to Toronto. So coming by your office would involve quite some traveling 😅 But thanks for the invitation. That would have been lovely.

**Comment by Buffalom** [comment]
@aerni I've just tested it and as I expected it does not seem to work entirely. When setting the collection to "show entries with dates in the past" (scheduling) as you'd do for blogs, for instance, it works perfectly. As soon as the date is in the past but the cached status is still `'scheduled'` it gets updated.

However, when setting the collection as follows, it does not update. In this case, it should update when the cached status is `'published'` and the date is in the past. 

<img width="680" alt="CleanShot 2022-11-10 at 10 33 12@2x" src="https://user-images.githubusercontent.com/20814747/201054831-22552816-be35-4b95-b1b0-7de9cd8de108.png">

So in my opinion, [this line](https://github.com/statamic/cms/pull/5089/files#diff-f6be6f1ce60a6fc6bc71c1272eefa109cf1b56418a4901dfdf184b9cbcca0786R38) should be changes to something like this:

```php
return ($value === 'scheduled' || $value === 'published') && $this->store->index('date')->get($id)->isPast();
```

**Comment by jasonvarga** [comment]
@Buffalom and @aerni  would you be able to test out #8281 ?

**Comment by Buffalom** [comment]
@jasonvarga thanks, I've just briefly tried it and I keep getting an error when running the following GraphQL query:

```gql
query GetEvents {
  entries(collection: "events") {
    total
    from
    to
    per_page
    current_page
    last_page
    has_more_pages
    data {
      title
      id
    }
  }
}
```

The error I get is the following:

```
[2023-06-22 21:26:02] local.ERROR: Undefined array key 1 {"userId":"493a2c5c-f384-4ad7-908f-89bee9cef678","exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /Users/tom/Projects/petarde-cms/vendor/statamic/cms/src/Stache/Indexes/Entries/Status.php:46)
[stacktrace]
#0 /Users/tom/Projects/petarde-cms/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/Users/tom/Proj...', 46)
#1 /Users/tom/Projects/petarde-cms/vendor/statamic/cms/src/Stache/Indexes/Entries/Status.php(46): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Undefined array...', '/Users/tom/Proj...', 46)
#2 [internal function]: Statamic\\Stache\\Indexes\\Entries\\Status->Statamic\\Stache\\Indexes\\Entries\\{closure}('expired', 'e2ede493-f60f-4...')
#3 /Users/tom/Projects/petarde-cms/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map(Object(Closure), Array, Array)
#4 /Users/tom/Projects/petarde-cms/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(768): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#5 /Users/tom/Projects/petarde-cms/vendor/statamic/cms/src/Stache/Indexes/Entries/Status.php(53): Illuminate\\Support\\Collection->map(Object(Closure))
#6 /Users/tom/Projects/petarde-cms/vendor/statamic/cms/src/Stache/Stores/Store.php(46): Statamic\\Stache\\Indexes\\Entries\\Status->load()
#7 /Users/tom/Projects/petarde-cms/vendor/statamic/cms/src/Stache/Query/Builder.php(100): Statamic\\Stache\\Stores\\Store->index('status')
#8 /Users/tom/Projects/petarde-cms/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(85): Statamic\\Stache\\Query\\Builder->getWhereColumnKeysFromStore('events', Array)
#9 [internal function]: Statamic\\Stache\\Query\\EntryQueryBuilder->Statamic\\Stache\\Query\\{closure}('events', 0)
...
```

When I log the `$value` [here](https://github.com/statamic/cms/pull/8281/files#diff-6cc4a424e38e348e3c21a4e6da35722b2ef341615943461e2b56dccc3b9e7d58R46) it's always `expired` and never contains `::{datetime}`.

I may just be doing something wrong. Let me know if that's the case. If you need more info, just ping me again.

**Comment by aerni** [comment]
@jasonvarga I just tested it as well. And I'm running into the same issue as @Buffalom. Though, I'm not using GraphQL but Antlers:

```antlers
{{ collection:articles }}
    {{ title }}<br>
{{ /collection:articles }}
```

**Comment by jasonvarga** [comment]
If you didn't already, can you clear your cache and try again?
