### ISSUE TITLE
Data events

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#223]
Ensure all data classes have corresponding events.  ie) `EntrySaving`, `EntrySaved`, `EntryDeleting`, `EntryDeleted`, etc.

Not sure if we need to implement [all of the same model events offered by Laravel](https://laravel.com/docs/5.7/eloquent#events), but for the events that we do wish to implement, I've already implemented `EntrySaving` and `EntrySaved` as an example.

See #55 and [this doc](http://localhost:8080/guide/extending/events.html) for more info.

**Comment by edalzell** [comment]
@jesseleite @jasonvarga this has been done right? We can close?
