### ISSUE TITLE
Duplicate field [title] on blueprint [....].

### ISSUE THREAD

**Issue by Krzemo** [statamic/cms#2238]
## Bug Description
After upgrading to b44 Im getting an error
<img width="597" alt="image" src="https://user-images.githubusercontent.com/1293123/90334422-c4b97680-dfcd-11ea-9523-54eea383b996.png">

## How to Reproduce
Make sure you have a title field in your blueprint & upgrade to b.44.

## Extra Detail
Error is gone once title fields are remove from blueprint.
It looks like some kind of leftover from b.3x where title field was there wether you added it to blueprint or not.

## Environment
Statamic 3.0.0-beta.44 Pro
Laravel 7.21.0
PHP 7.3.18
No addons installed

**Statamic version:** 3.0.0-beta.44

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by MikeHarrison** [comment]
I am seeing the same issue - deleting my `title` field does the trick, but then I have no way of setting in the title in the Blueprint.

**Comment by Krzemo** [comment]
An update after small invetstigation.
Heres my blueprint:
![image](https://user-images.githubusercontent.com/1293123/90652706-a8704080-e23e-11ea-963f-ce1052a07156.png)
It has only one title field and I deliberately set required to false.

Heres what Im getting when doing some dumping in src/Fields/Blueprint.php
![image](https://user-images.githubusercontent.com/1293123/90653036-000eac00-e23f-11ea-88cb-a404161544ec.png)

There are 2 title handles but only one is with required field set to false.
Where does the other one comes from??

Is there a leftover from previous beta versions where title field wasnt in blueprints?

**Comment by Krzemo** [comment]
Indeed there was a duplicate but in fieldset not blueprint.
