### ISSUE TITLE
Field validation rules as array

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2252]
## Bug Description
I'm using this validation rule on a text field in my blueprint: `validate: 'regex:/^(\+|-)\d+(\.\d{1,2})?$/'` and get this error when saving the entry in the CP: `preg_match(): No ending delimiter '/' found`.

According to the [Laravel Docs](https://laravel.com/docs/5.1/validation#rule-regex), the problem is the pipe in the first group `(\+|-)`. It says: *When using the regex pattern, it may be necessary to specify rules in an array instead of using pipe delimiters, especially if the regular expression contains a pipe character.*

Can we do this somehow?

## Environment

Statamic 3.0.0-beta.46 Pro
Laravel 7.25.0
PHP 7.4.6
aerni/snipcart dev-develop

**Comment by jesseleite** [comment]
Yes, you can specify rules in your yaml as an array:

```yaml
validate:
  - required
  - 'regex:/(one|two)/'
```

However, if you save your blueprint from the blueprint builder, it'll be concatenated back to:

```yaml
validate: 'required|regex:/(one|two)/'
```

Pushing a fix to make the validation builder UX store an array 👍
