### ISSUE TITLE
Updates page crashes - Call to a member function extension() on null

### ISSUE THREAD

**Issue by padders** [statamic/cms#2255]
##  Bug Description
The updates page on my instance won't load. It throws the error
`Call to a member function extension() on null`

This is limited to my own instance running on laravel valet. My colleagues work correctly.

![Screenshot 2020-08-19 at 09 50 35](https://user-images.githubusercontent.com/15945371/90628281-418a6180-e215-11ea-93f6-fe94c585b0b6.png)

I think it's related to licensing in some way as my licensing page also throws an error while my colleagues does not. Every page in my control panel has the following error at the bottom
`There was an issue communicating with statamic.com. Please try again later.`

and the licensing page looks like this. Again, my colleagues don't get these issues.

![Screenshot 2020-08-19 at 12 20 08](https://user-images.githubusercontent.com/15945371/90628913-5a474700-e216-11ea-87d9-521d3b40d309.png)

## How to Reproduce
I think this is limited to my instance so I'm not sure how to reproduce it

## Environment
Statamic 3.0.0-beta.46 Pro
Laravel 6.18.35
PHP 7.4.4
spatie/statamic-responsive-images 1.2.3
statamic/ssg dev-master

**Install method (choose one):**
- Starter kit (cool writings)

**Comment by padders** [comment]
One extra piece of info, it was doing this on beta 44 first. I've had the licensing warning for a while though but the updates page was working until beta 44. I updated to beta 46 by updating the composer.json file manually and running `compser update`

**Comment by jasonvarga** [comment]
Do you still get this error on 3.0.0? Can you try clearing your cache with `php artisan cache:clear` and trying again?

**Comment by padders** [comment]
Hi, yeah it still happens on 3.0.0, and clearing the cache doesn't seem to help unfortunately!

**Comment by jasonvarga** [comment]
What operating system are you using?

**Comment by padders** [comment]
MacOS Catalina (10.15.5)

**Comment by jasonvarga** [comment]
Do you have any special firewall rules set up?

**Comment by padders** [comment]
None, this is running on Laravel Valet locally.

**Comment by padders** [comment]
Is there a way of manually testing if my local instance can access Statamic's servers to check if there is an issue with firewall rules?

**Comment by daylightstudio** [comment]
I've run into the same issue. This is locally using MAMP with no firewall. The following in `Addon::license()` method calls `LicenseManager::addons()` which returns an empty collection and thus the error if that helps.:
```
public function license()
{
      return LicenseManager::addons()->get($this->package());
}
```

**Comment by Tobiasmidskards** [comment]
We are experiencing the same issue as daylightstudio. 

We are running 3.2.29 with php 7.4.15 and we have also tried with 8.0.
Our pro license is expired.

When running please support:details we get:

```
Statamic 3.2.29 Pro
Laravel 6.20.43
PHP 7.4.15
doublethreedigital/duplicator 2.1.0
rias/statamic-link-it 2.2.3
rias/statamic-redirect 1.9.0
statamic/seo-pro 2.3.2
```


The output above is after i have updated everything by manipulating composer.json and running composer update, which i did to try to solve the problem.

Can this issue be reopened? :-)

**Comment by freshface** [comment]
Same!

```
Environment
Application Name: Statamic Peak
Laravel Version: 11.34.2
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: rodeo.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 13
Sites: 2 (Nederlands, Frans)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.42.1 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.14.0
eminos/statamic-tabs: 1.2.0
figure8/address: dev-master
figure8/instagram: dev-master
figure8/reviews: dev-master
figure8/themes: dev-master
jacksleight/statamic-bard-texstyle: 3.4.1
spatie/statamic-responsive-images: 5.2.1
statamic-rad-pack/campaign-monitor: 2.3.0
statamic-rad-pack/mailchimp: 5.2.2
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.17.0
studio1902/statamic-peak-tools: 6.5.0
```

**Comment by duncanmcclean** [comment]
This issue is over **3** years old. To avoid past participants being notified, are you able to open a new issue instead? Feel free to reference this one.
