### ISSUE TITLE
Static Caching - Content type not saved, always delivered as text/html

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#2259]
## Bug Description
With static caching enabled, as soon as a page is loaded the second time, the set content type is ignored. Instead, its content type is always ``text/html``. See a sitemap as an example

## How to Reproduce
Create a route that produces xml and enable static caching. See the above.

``Route::statamic('/{loc}/sitemap.xml', 'sitemap', ['layout' => null, 'content_type' => 'application/xml'])->name('sitemap');``

## Extra Detail

first load:
![image](https://user-images.githubusercontent.com/9936988/90699746-5eaa4900-e284-11ea-8c5c-402ebaf709c2.png)

second load onwards:
![image](https://user-images.githubusercontent.com/9936988/90699719-4afee280-e284-11ea-87d2-e12ecf9a7587.png)

## Environment
Laravel Valet

**Statamic version:** 3.0.0

**PHP version:** 7.4

**Install method (choose one):**
Used statamic install

**Comment by jasonvarga** [comment]
Full or half caching? It can't work for full.

**Comment by AndreasSchantl** [comment]
Full caching

**Comment by jasonvarga** [comment]
Full measure just saves html files and uses the server rewrite rule to look for those specifically named html files.

**Comment by AndreasSchantl** [comment]
I see. But then it should at least not cache the ones that are of a different content type

**Comment by jasonvarga** [comment]
That's fair.

You can exclude it from caching manually as a workaround though.
https://statamic.dev/static-caching#excluding-pages

**Comment by AndreasSchantl** [comment]
I actually did. It is a multi site which has the urls like this: ``domain.tld/{locale}/sitemap.xml``

I excluded the sitemaps the following way: ``/*/sitemap.xml`` - this ain't working though

**Comment by jasonvarga** [comment]
Can't use wildcards there. Add them all individually.

**Comment by sjclark** [comment]
> Full measure just saves html files and uses the server rewrite rule to look for those specifically named html files.

Just stumbled across this myself (using half caching), eventually figured out `excludes` before finding this thread. Exact same scenario (sitemap.xml).

Very possible I'm missing something..... but if content that is statically cached is **always delivered as `text/html`** then would it not make sense to restrict the function only to files/responses that are `text/html`?

Presumably there must be some sort of checking as things like by `json` files/routes don't seem to be converted when static caching?

**Comment by aerni** [comment]
I just ran into this issue as well. In my case, it's an atom feed that shouldn't be cached statically. It would be nice if non-html content types were excluded by default.

```php
```

**Comment by aerni** [comment]
I tested this with both `half` and `full` measure static caching. It's the same issue with both caching methods.
