### ISSUE TITLE
replicator_preview still showing

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2260]
## Bug Description

Trying to use `replicator_preview` to disable the preview here (in a replicator): 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/6069653/90701722-339d0680-e23e-11ea-9a7d-1916ae5161f4.png">

However we have a blueprint that imports fieldsets that import other fieldsets. Details here: https://github.com/statamic/cms/issues/2198#issuecomment-676820473

## How to Reproduce

Create a blueprint/fieldsets like the above
Put some content in
Collapse the field

## Environment

Statamic 3.0.0 Pro
Laravel 7.25.0
PHP 7.4.9
statamic/migrator dev-master
statamic/seo-pro 2.0.6

**Comment by jasonvarga** [comment]
You have to add replicator_preview: false to the fields you want to exclude from displaying in the preview.

**Comment by edalzell** [comment]
so the base base field, not the import side?

Seems like an odd choice, why not define it where we know it's in a replicator (cuz it might not be, or we might want it in one replicator and not in another)?

**Comment by jasonvarga** [comment]
You can’t just drop stuff on `import` like that.

All the fields are brought imported inline.

I mean the field inside the set. You can disable specific ones.

**Comment by edalzell** [comment]
I'm confused, say I have `field_a` in `fieldset_a`. And I have two blue prints, each having a replicator with a set that imports `fieldset_a`.

I want to see (in the preview) `field_a` in `blueprint_a` but not in`blueprint_b`.

Possible?

**Comment by jasonvarga** [comment]
```
import: fieldset
config:
  field_a:
    replicator_preview: false
```

There’s no way to do that through the UI yet though.

But, if field_a is causing you issues with how it’s being displayed in the replicator’s preview, why would you only want it disabled in one blueprint? It’s the same field.
