### ISSUE TITLE
Composer conflict with package depending on symfony/var_exporter 5

### ISSUE THREAD

**Issue by edgrosvenor** [statamic/cms#2263]
## Bug Description

Along the lines of what was fixed here: https://github.com/statamic/cms/commit/c8dec99946129590f4e3d2ab7a90a8babe46de1c

I rely on a package that uses symfony/var_exporter ^5.1. I could rework it to use the older version because I control that package, but doing so might anger some of the other people who use the package.

## How to Reproduce

Install into a Laravel installation that uses any package that relies on symfony/var_exporter 5

## Extra Detail

We've all been there. Package one depends on something. Package two depends on something's older self. We love both packages and hate to see them fighting. Happy to submit a PR if it would help.

## Environment

**Statamic version:** 3.0.0-beta.{?}

3.0.0 

**PHP version:** 7.{?}

7.4
**Install method (choose one):**
  Fresh install from `statamic/statamic`
  Starter kit
-> Existing Laravel app
  Other (please explain this magic!)

**Comment by dellow** [comment]
Also having this problem with same `symfony/var_exporter` package.
