### ISSUE TITLE
Using pagination in collection widget jumps to the top of the page

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#2264]
## Bug Description
The page scrolls to the top, when you click on the pagination of a collection widget. 
## How to Reproduce
Add collection widget and click on the pagination.
## Extra Detail

![image](https://user-images.githubusercontent.com/3351449/90889895-38d29080-e3b9-11ea-9840-6c6da2c8785f.png)

## Environment

**Statamic version:** 3.0.0

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
We use the same pagination component in the widget as other regular listings. The jump to the top of the page makes sense there, but not here. Good find.

**Comment by wm-simon** [comment]
This is still an issue.
