### ISSUE TITLE
Multisite: Can't create other locale pages sometimes.

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2265]
## Bug Description
Multisite, when i from a russian page, click on the english site to create an english version. Then change the title to something in english and click save. I get the error belowl

When this happens you are kind of stuck trying to fix it. The page id showing in the error, is the "index page id" of the russian site. So seems to be some weird connection i can not for my life figure out what it is.

## Extra Detail
![image](https://user-images.githubusercontent.com/31292231/90892684-fd869080-e3bd-11ea-9e6f-860b63bb5307.png)

![image](https://user-images.githubusercontent.com/31292231/90892574-cadc9800-e3bd-11ea-992c-81ff22544f68.png)

## Environment

**Statamic version:** 3.0.0

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by Pixney-William** [comment]
![image](https://user-images.githubusercontent.com/31292231/91026838-9a823d00-e5fb-11ea-9553-dc5a782e0ace.png)

**Comment by Pixney-William** [comment]
![image](https://user-images.githubusercontent.com/31292231/91026926-b8e83880-e5fb-11ea-946c-2f10973d673f.png)

**Comment by Pixney-William** [comment]
So basically this is all about not using the root set for the locale. Instead, it always refers to the default locale root id.

**Comment by Pixney-William** [comment]
In regular collections, where you don't require a ROOT to be set, an entry is saved without errors thrown. However, the title field is never updated. It just reverts to what is being used by the default locale.

**Comment by Pixney-William** [comment]
For your info, it is also related to : https://github.com/statamic/cms/issues/2211

**Comment by jasonvarga** [comment]
I believe this is solved now in 20592067, coming in 3.0.2
