### ISSUE TITLE
"Visit URL" Route broken when Taxonomy Name contains space

### ISSUE THREAD

**Issue by reuank** [statamic/cms#2273]
## Bug Description
When I click the "Visit URL" button while editing a Taxonomy Entry in the control panel, it leads to a 404 page when the Taxonomy Name contains a space. When creating the Taxonomy, e.g. "Application Category", the corresponding handle is "application_category", but the "Visit URL" button links to an URL containing "application-category".

## How to Reproduce
- Create a new Taxonomy called "Application Category"
- Create a new "Application Category" called "Industry"
- Create `resources/views/application_category/show.antlers.html`
- Go to the "Industry" page in the control panel and click "Visit URL"
- This leads you to `example.com/application-category/industry` instead of `example.com/application_category/industry` 

## Environment

Statamic 3.0.0 Solo
Laravel 7.23.2
PHP 7.4.8
No addons installed

Install method: Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Thanks! We'll need to make sure that the URL is kebab-cased, as per all URL-ish things, but the taxonomy is snake_cased as per handle-ish things.
