### ISSUE TITLE
Permission denied when trying to save pages

### ISSUE THREAD

**Issue by mwkcoding** [statamic/cms#2276]
## Bug Description
After deployment, (using deployer and GitHub Actions) I'm unable to edit the pages. On the site it just says "Server error".
If I go look in my laravel log, it says permission denied on `file_put_contents()` of the edited page markdown file.

File is writable by webserver user. (775) and webserver is in owner group.

## Environment
Statamic 3.0.0
Laravel 7.25.0
PHP 7.2.29
No addons installed

**Statamic version:** 3.0.0

**PHP version:** 7.2.29

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
What service are you using to deploy and host? You'll need to make sure that the deployment tool writes the files such that the PHP user will also have permission to write to them.

**Comment by mwkcoding** [comment]
I used [deployer](https://deployer.org/) to deploy this to a DigitalOcean droplet running CentOS 7 (nginx/php-fpm).

Since there's NO documentation for deployment of Statamic whatsoever, I assumed it would be the same as Laravel.
I've tried to customize it by doing the same to the `content` folder as the `storage` during deployment, meaning it moves it to a shared folder outside the project root and symlinks it. The permissions for the folder and contents are the same as storage, 775. The folder is owned by the user used for deployment, and the PHP user is in the same group making the 775 valid for read/write for the PHP user.

**Comment by jackmcdade** [comment]
Ah, flysystem doesn't handle symlinks well (or at all in some cases). You'll need to keep the `content` directory inside the project root or use a [filesystem driver](https://laravel.com/docs/7.x/filesystem#custom-filesystems) to relocate them.

If this doesn't solve it, just ping us and we'll reopen to investigate!

**Comment by mwkcoding** [comment]
How would I go about making the custom filesystem driver for content? Every time it accesses the folder, then just replace whatever it does with something that uses the custom driver? Or what?

**Comment by mwkcoding** [comment]
@jackmcdade
