### ISSUE TITLE
save on the Entry is very slow

### ISSUE THREAD

**Issue by bambamboole** [statamic/cms#2278]
## Bug Description
I have written a small Importer for our current documentation.
It works, but it becomes slower and slower.
In the process of converting form html to markdown I upload all images to S3, which is the connected Asset location.

Code looks like this:
```
 $collection = Collection::findByHandle('wiki');
        $entries = WikiEntry::all();
        foreach ($entries as $wikiEntry) {
            $title = isset($this->titleMap[$wikiEntry->name])
                ? $this->titleMap[$wikiEntry->name]
                : $wikiEntry->name;
            $entry = $this->findEntry($title);
            if ($entry !== null) {
                continue;
            }
            $markdown = $this->converter->convert($wikiEntry->content);
            $entry = new Entry();
            $entry->collection($collection);
            $entry->blueprint('wiki');
            $entry->locale('default');
            $entry->published(true);
            $entry->slug($wikiEntry->name);
            $entry->data([
                'title' => $title,
                'content' => $markdown,
                'author' => '952b9337-d2b2-4f8b-a2db-84b42843bee1',
                'template' => null,
                'parent' => null
            ]);
// this portion takes long time
            $entry->save();
        }
```

I have installed the `league/flysystem-cached-adapter` as pointed out [here](https://github.com/statamic/cms/issues/1477#issuecomment-597751210).
It makes it all a bit faster but it is still slow.

## How to Reproduce
I think it is reproducable by a large asset collection on on a EntryCollection

## Environment

Statamic 3.0.0 Pro
Laravel 7.25.0
PHP 7.4.7
aryehraber/statamic-impersonator 2.0.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by bambamboole** [comment]
The bottleneck is the update of the search index. I also think that this is only a problem of using the `sync` "queue".

Maybe there should be an option to disable the SearchIndex update if the queue connection is `sync`.

**Comment by jasonvarga** [comment]
Closing in favor of https://github.com/statamic/ideas/issues/323

**Comment by duncanmcclean** [comment]
This entry is over 4 years old, please open a new issue and we can take a look.
