### ISSUE TITLE
Page rendering  using s3 and cloudfront notably slow

### ISSUE THREAD

**Issue by sg-modlab** [statamic/cms#2279]
## Bug Description
Using the flysystem s3 driver and setting `url` to the cloudfront domain that was setup is working. Images are loading ... but notably slow. Glide was  being used, so I removed those tags from home page in case that caused the slowness. Still notably slow. Cleared all cache and no difference.

I noticed the other issue with assets list in CP being slow with s3. Seeing that as well.  It is unusably slow. Similar rendering of front end using s3/cloudfront is unusably slow.

## How to Reproduce
Wire up a site with s3 and cloudfront.

## Environment

Statamic 3.0.0 Pro
Laravel 7.25.0
PHP 7.4.9
statamic/seo-pro 2.0.7

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Does enabling caching on your s3 disk help?
See here: https://github.com/statamic/cms/issues/1477#issuecomment-597751210

**Comment by sg-modlab** [comment]
Have it enabled:

`composer.json`
<img width="344" alt="image" src="https://user-images.githubusercontent.com/529067/91083869-06bf6980-e619-11ea-9420-0453238f8350.png">

`filesystems.php` - though with correct cloudfront URL. Note that I don't have the AWS_URL set in .env variables. 
```
's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'endpoint' => env('AWS_URL'),
            'url' => 'https://#########.cloudfront.net',
            'cache' => true,
        ],
```

Takes about 6-7 seconds on local to render homepage.

**Comment by skylennard** [comment]
I am also having a similar problem here but I'm using Digital Ocean Spaces via the same basic s3 setup as @sg-modlab.

**Comment by jonatanalvarsson** [comment]
Same problem here. Using a S3-compatible cloud storage (no CDN/CloudFront).

Enabling S3 cache (`league/flysystem-cached-adapter` and `'cache' => true` in `config/filesystems.php`) improves it a lot but it's still way slower than without S3 images. Is this expected behavior?

- **120 ms**: rendering html with 9 entries without displaying any images
- **750 ms**: rendering html with 9 entries with two images (no Glide) with S3 cache enabled
- **2 500 ms**: rendering html with 9 entries with two images (no Glide) without S3 cache

**Comment by damcclean** [comment]
I wonder if this issue could have the same underlying cause as #2145.

**Comment by jonatanalvarsson** [comment]
Merely checking the image field is enough to get 750 ms rendering time.

```
{{ if images }}
    we have images!
{{ /if }}
```

Without the above code in my Antlers template page rendering time is 120 ms.

Only 6 files in the S3 folder btw.

**Comment by jonatanalvarsson** [comment]
I noticed the `.meta` folder is created on the S3 storage. I guess reading those YAML files remotely from S3 is why page rendering becomes so much slower. Maybe (optionally) store the `.meta` directory locally for remote/S3 storage?

**Comment by sg-modlab** [comment]
Jonatan, your test is great to see and makes a lot of sense to what I have been experiencing the I was exploring things. Individual pages with a minimal amount s3 assets taking a very long time to render.

**Comment by duncanmcclean** [comment]
Re-opening.

**Comment by jackmcdade** [comment]
We have an open issue for this that's on our roadmap: https://github.com/statamic/cms/issues/5143

**Comment by edalzell** [comment]
Please keep open kind robot

**Comment by nicko170** [comment]
Bad bot!

I have about 5 images on a page, that's now taking ~8 seconds to boot.

**Comment by jasonvarga** [comment]
This may have been resolved by #5143 

Try setting up an s3 disk: https://statamic.dev/image-manipulation#custom-disk-cdn

If it's still an issue, please provide a github repo with this problem.

**Comment by GioChocolateBro** [comment]
Hi @jasonvarga ,

I recently started a new project and decided to ditch my custom glide implementation in favour of the work that was done on #5725. Now with the separate disk & cache store for glide it's perfect!

Sadly I noticed that I got added quite some load for every extra image on the page.  With 7 images rolling through glide:generate I'm now up to 800/900 ms (about 100ms per image) for a server response. 

After some digging I ended up at Statamic\Imaging\Attribute::from.
`$manager->copy("source://{$path}", $destination);` 

No matter if I have the entry cached, it will copy the image from the cdn to my local disk. Commenting this line will bring me back to a very speedy 50ms server response.

Am I missing something in my configuration or should I got about thing differently? I'd really like to use statamics glide implementation.

**Comment by jasonvarga** [comment]
Does it still try to copy the image on the second page load?

**Comment by GioChocolateBro** [comment]
Yes, it does. After a glide:clear it takes longer.
When the cache is build and used it still hits this copy method.

Thing is, this function hits `getimagesize` eventually. Thats what it's copying the file to local for, after reading out the attributes it deletes this local copy again.

Sadly this kind of defeats the purpose of this whole caching layer if we still hit s3 with a copy for every image on every req. But we do need a local image to read out width/height.

Maybe we can cache these attributes as well? After glide has cropped it I don't see it changing again.

**Comment by jasonvarga** [comment]
Yeah that looks like an oversight. Seems like the image attributes are being retrieved every time.

**Comment by jasonvarga** [comment]
Are you using `glide` as a tag pair?

**Comment by GioChocolateBro** [comment]
I'm using blade I think that works the same as the tag pair.

I was thinking about making a little wrapper function to do something like `{{ glide($asset) }}`. There is no way to just do a single asset, you always have to foreach. Is there also maybe something coming to blade for this from statamic?

**Comment by GioChocolateBro** [comment]
Ah I see, this is because of the tag pair..

I just made a small helper for around glide:index for use in blade

```
function glide($source, $format = 'webp'): mixed
    {
        $quality = config('statamic.assets.image_manipulation.quality', 90);

        return Statamic::tag('glide:index')->src($source)->format($format)->quality($quality);
    }
```

No more copies from s3 now. I'm good now. That said, tag pair should probably also benefit from the caching layer, it's the purposed method for using glide with blade.

**Comment by jasonvarga** [comment]
Yeah it should work. I was just confirming a theory.

It only happens when using the tag pair, because we inject attributes, which does the copying (but could be modified to avoid copying every time).
