### ISSUE TITLE
Bard: The Fixed toolbar disappears when "Allow Source Mode/Allow Fullscreen Mode" options are disabled

### ISSUE THREAD

**Issue by pryley** [statamic/cms#2280]
## Bug Description

When you add a Bard field and set the Toolbar Mode to "Fixed", the toolbar will disappear if you disable both the "Allow Source Mode" and "Allow Fullscreen Mode" options.

## How to Reproduce

1. Add a Bard field
2. Set the "Toolbar Mode" to "Fixed"
3. Disable the "Allow Source Mode" option
4. Disable the "Allow Fullscreen Mode" option

### The default Bard field with a fixed toolbar

![image](https://user-images.githubusercontent.com/134939/90990994-5e070080-e56b-11ea-9803-2f8fe8815072.png)

### Disable these options

![image](https://user-images.githubusercontent.com/134939/90990944-ff418700-e56a-11ea-9874-59d06884fe22.png)

### The Bard no longer sings...

![image](https://user-images.githubusercontent.com/134939/90991017-8c84db80-e56b-11ea-845d-8a3b55db00a4.png)

## Environment

- Statamic 3.0.0 Pro
- Laravel 7.25.0
- PHP 7.4.8
- aerni/social-links 2.0.1
- aerni/statamic-imagekit 2.0.0
- aryehraber/statamic-impersonator 2.0.0
- aryehraber/statamic-splash 1.0.3
- doublethreedigital/duplicator 1.0.5
- rias/statamic-color-swatches 2.0.5
- spatie/statamic-responsive-images 1.2.3
- statamic/seo-pro 2.0.7

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Good catch!
