### ISSUE TITLE
Editing mounted entry throws error

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#2281]
## Bug Description
After mounting a collection it is not possible to edit it.

## How to Reproduce
Mount a collection to an entry and try to edit it.

## Extra Detail
![Bildschirmfoto 2020-08-24 um 15 03 19](https://user-images.githubusercontent.com/6337411/91051018-ca433c00-e61f-11ea-9e47-fccbf6523117.jpg)

## Environment
Statamic 3.0.0 Pro
Laravel 7.25.0
PHP 7.4.9
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
