### ISSUE TITLE
Form file uploads are not referenced at the submissions results screen

### ISSUE THREAD

**Issue by sebabal** [statamic/cms#2284]
## Bug Description

So file uploads from the frontend are working but there is no reference on the submissions screen at the control panel.

I would expect some sort of reference to the file itself from the submission detail screen.

## Extra Detail

![image](https://user-images.githubusercontent.com/210946/91079904-1770df00-e61b-11ea-82f6-98fb48254f2e.png)

## Environment

Statamic 3.0.0 Pro
Laravel 6.18.35
PHP 7.4.3
aryehraber/statamic-recaptcha dev-statamic-3
doublethreedigital/duplicator 1.0.5
doublethreedigital/simple-commerce 2.0.10
statamic/migrator dev-master

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
