### ISSUE TITLE
When initially localizing an entry, it has a date, even if the collection is not dated

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2296]
## Bug Description

When you select another site, the entry is created, but the filename has the date.

Hit save and it goes away.

## Environment

**Statamic version:** 3.0.0

**Comment by tao** [comment]
The issue #3247 is related but the issue is still present after hitting save. However, if I manually remove the date and hit save then it doesn't re-add the date to the filename.

**Comment by tao** [comment]
The issue #3247 is related but the issue is still present after hitting save. Also, if I manually remove the date from the filename and hit save again then it creates a new file with the date instead of saving to the old one.

**Comment by lamalamaMark** [comment]
Did someone find out more about this issue in the meantime? We're having similar issues with a multisite.

**Comment by simonbedard12** [comment]
### Environment
Statamic 3.2.33 Pro
Laravel 8.83.1
PHP 8.0.14

I got the exacte same issue with the new release update: 3.2.33. 
For exemple, in the [Statamic\Entries\Entry on line 346] (https://github.com/statamic/cms/blob/f3e0d4018bbf1ac2f04eee16baa1f113a14a3503/src/Entries/Entry.php#L346) 
We call the function `$this->makeLocalization(...)` that is returning a dated entry to be save. 

```
public function makeLocalization($site)
  {
     
      return Facades\Entry::make()
          ->collection($this->collection)
          ->origin($this)
          ->locale($site)
          ->slug($this->slug())
          ->date($this->date());
  
  }
```
If you remove the last line `->date($this->date())` the entry will be save without a date. This solution has not been tested properly.  

Maybe we can dive deeper in the code to check the actual function creating the filename. :)

**Comment by tao** [comment]
I had some problems with my site recently and the translated copyright text was duplicated 3 times, I think it's related to this issue:

![Screenshot 2022-05-02 at 13 27 17](https://user-images.githubusercontent.com/1446331/166226671-75802561-6b09-4c1d-a0c1-787ecd3707bf.png)

When I investigated the problem more I found the file had a date added and a version added, so there ended up being 3 different files... but the control panel was loading all of them:

![Screenshot 2022-05-02 at 13 28 59](https://user-images.githubusercontent.com/1446331/166226851-2dc853e5-8b0f-4cd7-97c0-f28fdec884bd.png)

You can see these 3 files in the list:

```bash
2021-12-22-0927.copyright.1.md
2021-12-22-0927.copyright.md
copyright.md
```

However, when I deleted these dated files it worked correctly again:

![Screenshot 2022-05-02 at 13 29 44](https://user-images.githubusercontent.com/1446331/166226927-f27bae30-08f5-45b8-ae6c-6dc9e66d22f1.png)

I think the same issue if the CMS is trying to date the entry if it can't find it and save the date on a non-dated collection, but the website is trying to load them all which might be another bug too.
