### ISSUE TITLE
Error on Outpost: Argument 1 passed to Statamic\Licensing\Outpost::cacheResponse() must be an instance of Illuminate\Support\Carbon, instance of Carbon\CarbonImmutable given,

### ISSUE THREAD

**Issue by raisonon** [statamic/cms#2300]
## Bug Description

Getting this error:

 Argument 1 passed to Statamic\Licensing\Outpost::cacheResponse() must be an instance of Illuminate\Support\Carbon, instance of Carbon\CarbonImmutable given, called in /Users/username/Laravel/sqft/vendor/statamic/cms/src/Licensing/Outpost.php on line 55 

When visiting domain.test/cp

When I goto my /blog page I also get:

ErrorException
Array to string conversion 

But not sure if that is connected..

Asked on Discord and suggested i create bug report.

Already setup with Statamic v.3 on live site, this happened with composer update and also adding SEO Pro addon. Uncertain if either of those caused the issue or by-the-by.

Thanks

## Environment

Local valet environment

**Statamic version:** 3.0.0

**PHP version:** 7.4.7

**Install method (choose one):**
Laravel and Statamic site

 Argument 1 passed to Statamic\Licensing\Outpost::cacheResponse() must be an instance of Illuminate\Support\Carbon, instance of Carbon\CarbonImmutable given, called in /Users/elliottaylor/Laravel/sqft/vendor/statamic/cms/src/Licensing/Outpost.php on line 55

**Comment by raisonon** [comment]
Looks like now() helper returns CarbonImmutable object.

In Outpost.php if I change the following:

cacheResponse(CarbonImmutable $expiration, $contents)

and use:

use Carbon\CarbonImmutable;

this fixes the issue...

**Comment by jasonvarga** [comment]
What version of Laravel are you using?

**Comment by raisonon** [comment]
Larvel v7.25.0

**Comment by jasonvarga** [comment]
![image](https://user-images.githubusercontent.com/105211/91311694-5e78e480-e781-11ea-806c-7a5c61d3d3ac.png)

🤔 

Is there something that you need to do to enable CarbonImmutable?

**Comment by jasonvarga** [comment]
Do you have `Date::use` in your app anywhere?

**Comment by raisonon** [comment]
I did - I had the following in my AppServiceProvider.php file

```
public function boot()
{
       Date::use (CarbonImmutable::class);
}
```

And now I can't determine why I added that... 

I've commented it out and the code works well. Not totally sure where to take this next. Thanks for help here.
