### ISSUE TITLE
Cannot log in on Windows new install

### ISSUE THREAD

**Issue by davidejfoster** [statamic/cms#2301]
## Bug Description

I have just installed Statamic 3 and after setting up a single user am getting the error below when attempting to log in.

I used - composer create-project statamic/statamic statamic_demo --prefer-dist --stability=dev - to create the project and am running a PHP local server.

ErrorException file_put_contents(C:\Users\david\Documents\SpiderOak Hive\projects\statamic_demo\storage\framework/cache/data/david@honeystone.com|//1/99/2d/992da7269f3be69ee99cf5fd36279a1c): failed to open stream: No such file or directory

## How to Reproduce

Setup Statamic on Windows 10

## Environment

**Windows

**Statamic version:** 3.0.

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by jasonvarga** [comment]
I'm about to tag 3.0.1, which should have a fix for this.

**Comment by davidejfoster** [comment]
Awesome thanks !

**Comment by jasonvarga** [comment]
Good timing, that issue had been open since November 😬

**Comment by davidejfoster** [comment]
Thanks Jason - I did a fresh install with composer create-project
statamic/statamic {change_me} --prefer-dist --stability=dev -  but the
problem #2301 has persisted.

Is this install pulling down 3.0.2 yet ?

Kind Regards

David Foster

*Director*

Honeystone Consulting Ltd

Direct line: 01380 730 173

Switchboard: 01373 710 810

david@honeystone.com

www.honeystone.com


Honeystone Consulting Ltd, Registered in England and Wales number 4895357

Registered office, Courtleigh House, Westbury Leigh, Westbury, Wiltshire,
United Kingdom
