### ISSUE TITLE
Call to undefined method Statamic\Taxonomies\Taxonomy::locale()

### ISSUE THREAD

**Issue by borutjures** [statamic/cms#2307]
## Bug Description

I get an error after referencing another taxonomy with a "Taxonomy Terms" field:

`Call to undefined method Statamic\\Taxonomies\\Taxonomy::locale() at `
`/Users/borut/Documents/Valet/handyreadscontent/vendor/statamic/cms/src/Fieldtypes/Terms.php:92)`

## How to Reproduce

1. composer create-project statamic/statamic example --prefer-dist --stability=dev
2. Create taxonomy "Authors". Create terms: "Alice", "Bob".
3. Create taxonomy "Books".
4. Edit blueprint "Books" and add field type "Taxonomy Terms" named "Authors" and "Taxonomies=Authors".
5. Create a book with a title but leave the "Authors" field empty. Books listing (http://example.test/cp/taxonomies/books) works.
6. Edit the book and "Link Existing Item" in the "Authors" field.
7. Books listing (http://example.test/cp/taxonomies/books) shows an error `Call to undefined method Statamic\\Taxonomies\\Taxonomy::locale()`.

## Environment

Statamic 3.0.1 Solo
Laravel 7.26.0
PHP 7.4.9
No addons installed

**Install method (choose one):**

- Fresh install from `statamic/statamic`

**Comment by cbautista103** [comment]
I can confirm this issue. Adding an empty locale() method to `vendor/statamic/cms/src/Taxonomies/Taxonomy.php` seems to resolve the issue temporarily.

**Comment by jelleroorda** [comment]
I'm experiencing the same issue as mentioned above.
