### ISSUE TITLE
"show_unpublished" and "show_published" parameters don't work

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2308]
## Bug Description
The `show_unpublished` and `show_published` parameters don't work on the collection tag. I tried setting `show_unpublished="true"` and `show_published="false"`. Both without effect.

## How to Reproduce
1. Create a collection
2. Add some published and some unpublished entries
3. Loop through the collection in the template
4. Add the parameters to the tag

## Environment
Statamic 3.0.1 Pro
Laravel 7.26.1
PHP 7.4.9
aerni/imagekit 2.1.0

**Comment by jasonvarga** [comment]
We forgot to remove that from the docs.

Use `status:is` or `status:in` instead.

- `status:is="published"` to only show published
- `status:is="draft` to only show drafts
- `status:in="published|draft"` to show both

**Comment by aerni** [comment]
Thanks Jason. Is there a reason it's `status:in` when displaying both? I find this to be confusing. `status:is` makes more sense to me.
