### ISSUE TITLE
Search for assets not working in grid view

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2318]
## Bug Description
If you search for assets, the grid view doesn't show the results. In the list view is it working.

## How to Reproduce
Search for assets.
## Environment

**Statamic version:** 3.0.2

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I've created a pull request to fix this bug, #2442.

**Comment by Pfeifakopf** [comment]
Thanks @damcclean !
