### ISSUE TITLE
Multisite Global editUrl() on null

### ISSUE THREAD

**Issue by Lampone** [statamic/cms#2319]
## Bug Description
I have created a global and only selected the default site. When you switch to subpage and try to access the globals in the cp you get error: **Call to a member function editUrl() on null**

## How to Reproduce
- Create a new statamic project. 
- Enable multisite with `php please multisite`
- Create global in the cp for the default site
- Try to access globals in subsite

## Extra Detail

https://flareapp.io/share/KPgbgJma

## Environment
Statamic 3.0.2 Pro
Laravel 7.26.1
PHP 7.2.29-1+ubuntu18.04.1+deb.sury.org+1
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`
composer create-project statamic/statamic {change_me} --prefer-dist --stability=dev

**Comment by FlorianMoser** [comment]
This happened to me too today. It seems that this happens when you access the global "your_global" in a subsite "site_handle" when there is no `content/globals/{site_handle}/{your_global.yaml}` file.

**Comment by Lampone** [comment]
Can confirm. If all the global is enabled for all sites it works. If you want to only have to global on some sites it doesn't work anymore.

**Comment by aerni** [comment]
Can confirm this too.

**Comment by rrelmy** [comment]
This is a duplicate of #1636
