### ISSUE TITLE
Syncing Global configuration in multi-site should erase content

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#2321]
## Bug Description
Imagine having a global field with different content on two subsites, for example "hello" and "bonjour" for the subsites "en" and "fr". Now, in the CP configuration of that global you activate the ORIGIN "en" for the site "fr".

What happens is that on the site "fr" the field still has "bonjour" as content, the frontend also displays "bonjour", but the field is read-only.

What should happen is that the field content should get erased and display "hello". It should also be read only, but that is already the case.

## How to Reproduce
1. Pre-requirement: Statamic with multi-site enabled (at least two sites)
2. In the CP, create a new Global. Enter a title and on the second page, enable the Global for all sites and save.
3. Edit the Global Blueprint you just created and add a text field. Save.
4. Go to the Global you just created and enter "hello" into the text field. Save.
5. Switch site and enter "bonjour" into the field. Save.
-- So far everything behaves correctly --
6. Go into the Global configuration and for the second site, choose the first site as ORIGIN. Save.

Open the Global. The first site still says "hello" (correct). Now when you switch to the second site, the field is read only (also correct) but still displays "bonjour". It should display "hello", because now it is synced to the first site.

Editing "hello" to "hello 2" also doesn't sync/reset the second site "bonjour" value.

## Environment

**Statamic version:** 3.0.2

**PHP version:** 7.3

**Install method:** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Working as intended. I don't agree that changing the origin should wipe the content. You've manually defined the value of that field at one point, essentially "de-syncing" it. If you had other fields that you've left blank, they would now start inheriting  from the origin.

**Comment by FlorianMoser** [comment]
I agree that wiping content might not be a good solution. But it is confusing when you see in the user interface that the content is supposed to be synced, but in reality it is not. Even more confusing, that you cannot edit the synced value.

This is absolutely no issue, if you work with the yaml files directly. But when using the UI (especially when you're new to it), it is confusing.
