### ISSUE TITLE
Global fields are always localizable

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#2322]
## Bug Description
Not sure if this is intended, but it is a bit confusing. Fields in Global Blueprints can always be translated, even if `localizable: false` in the .yaml file.

## How to Reproduce
On a multi-site installation, create a global. Don't activate "Localizable". The field can be translated, when switching sites.

## Extra Detail
Might be related to #2082

## Environment

**Statamic version:** 3.0.2

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.

**Comment by FlorianMoser** [comment]
I just checked. It is maybe ambigous, but not solved.

If you create a global, assign it to all sites and choose the first site as origin, everything is synced and you can only edit the global for the first site.

If you configure the global and remove all origins, the global can be edited for all sites. But, in the globals blueprint, there is also the option to make a field "localizable" using the world map icon. This option is being ignored right now.

This is very confusing. Whether a field can be translated or not should be defined by one instance only. Either the blueprint, or the global configuration.

**Comment by jasonvarga** [comment]
If you don't set an origin, it is essentially its own origin with a fresh slate, so you are able to edit all of the fields.

The whole point of a "localizable" field is to allow you to override the originating value.

**Comment by FlorianMoser** [comment]
Ok, I see now. If there is no origin, the "localizable" option in blueprints has no effect. If there is an origin, enabling "localizable" in blueprints allows you to edit the origin-value in the translation. Disabling "localizable" keeps the translation synced.

Maybe it is enough to update the docs about this behaviour?

I'm still not sure if it makes sense, how the "origin" works. I mean, entries connected through "origin" are only synced once: at the point of creation. As soon as a translation has been modified, this "origin"-relation is broken. But maybe I miss a point with all the content inheritance in place.

There is a similar option in WordPress with the WPML plugin: you can "copy content from language XYZ" and then modify/translate it. Maybe such a feature could replace the need for an origin, when fields are localizable.
