### ISSUE TITLE
The default Range field value can be incorrect when a Step value is set

### ISSUE THREAD

**Issue by pryley** [statamic/cms#2328]
## Bug Description

The default value of a range field is typically `Max - Min / 2` (i.e. `(20 - 2) / 2 = 9`). However, this does not work well if a `Step` value is set.  For example, suppose the `Step` value is 2; using the example above, this would make the default value 9 instead of 10. 

I figured out that you can add `default: 10` to the yaml file to set the default, but I think a better option would be to allow manually setting a default or starting value from the CP.

## Extra Detail

![image](https://user-images.githubusercontent.com/134939/91625026-a0fd1580-e969-11ea-9288-5893eb705453.png)

![image](https://user-images.githubusercontent.com/134939/91625038-afe3c800-e969-11ea-840c-7b03b80c2047.png)

## Environment

- Statamic 3.0.2 Pro
- Laravel 7.26.1
- PHP 7.4.8
- aerni/imagekit 2.2.0
- aerni/social-links 2.0.1
- aryehraber/statamic-impersonator 2.0.0
- aryehraber/statamic-splash 1.0.3
- doublethreedigital/duplicator 1.0.5
- kind-work/two-fa 1.0.0
- rias/statamic-color-swatches 2.0.5
- spatie/statamic-responsive-images 1.2.3
- statamic/seo-pro 2.0.10

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Where did you get that mysterious equation?

**Comment by pryley** [comment]
![image](https://user-images.githubusercontent.com/134939/91626909-add53580-e978-11ea-927c-b987d3e6bf46.jpeg)

**Comment by jasonvarga** [comment]
Neat, thanks!

**Comment by ReneWeCode** [comment]
This really confused me. No other fieldtypes get the defaults set by default.
From a UX perspective the idea is great, but I had to find this issue to actually get the idea. 
What really got me, was when I tried to set de default to 0. It's simply not possible from the backend.

If anyone find this closed issue by the same reason as me, and wants to set the default to 0, you can then set the default to '0' in the .md

**Comment by jasonvarga** [comment]
Didn't notice your reply @ReneWeCode. Someone just pointed out the same `0` issue. We're on it.
