### ISSUE TITLE
Redirect for antlers

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2330]
## Bug Description
- Parent
  - Child 1
  - Child 2 

I want to show the navigation of the siblings. My parent element is redirected to the first child.
If I use `{{ nav:collection:pages from="{parent:url}" }}` to show the siblings, they can't be shown, because `{{parent:url}}` outputs the redirected url from the child.
I don't know if it is possible no to redirect for antlers and just, when you load the site. But right know, it's not possible to shown the children of a redirected entry. 

## Environment

**Statamic version:** 3.0.2

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Try using `uri` instead of `url`
