### ISSUE TITLE
Type of search result missing in global search

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#2332]
## Bug Description

The type of the result (what collection/container/...) is missing from results in the global search.

Looking into the JSON response received in the frontend, the respective field, e.g. `collection`, is just an empty object when it should contain the handle.

## How to Reproduce

Search for anything in the global search bar. Results don't have their type in grey caps on the right side like they used to.

## Extra Detail

Before:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/1760908/91709134-98cbf280-eb82-11ea-8b2e-6eea64ecfeb5.png">

Now:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/1760908/91709104-8ce03080-eb82-11ea-8cd8-31badc5a9d73.png">

## Environment

**Statamic version:** d54f9d1507b31f6d9b5e304462b2d96495e613f9

**PHP version:** 7.3

**Comment by jasonvarga** [comment]
(Please put the commit sha in your issues rather than just HEAD. We don't know where the HEAD is.)

**Comment by sauerbraten** [comment]
Yeah that was stupid :D We found this on 6aef808177.

**Comment by jackmcdade** [comment]
Confirmed, i can recreate this. Definitely seems like a modified lower level class change somewhere did it...
