### ISSUE TITLE
Taxonomy terms field only list the first 15 items in CP

### ISSUE THREAD

**Issue by ockam** [statamic/cms#2335]
## Bug Description
I created a Taxonomy with 22 entries. I then use a Taxonomy Terms field on a collection with the Select Dropdown option. It only shows the first 15 items. Typing only find items in those 15 items.

The other 2 modes (type-ahead, stack) work correctly.

**Statamic version:** 3.0.2

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment]
That does sound like this issue, but it should be fixed by now: 
https://github.com/statamic/cms/issues/1311

Related? Maybe not?

**Comment by ockam** [comment]
Same thing: looks like we may have a regression here.

**Comment by MattRogowski** [comment]
The same issue affects the Entries field, when displaying as a select dropdown only.

**Comment by jasonvarga** [comment]
Duplicate of #1727
