### ISSUE TITLE
When we delete a Site (Multisite) what is referenced as parent. then the site crash

### ISSUE THREAD

**Issue by matrad** [statamic/cms#2336]
- Create a new Page
 - Translate the Page & Publish that
 - Delete the Main Page
 - The Dashboard crashes because it does not clean up references & parents

**Comment by damcclean** [comment]
Please could you provide more information, like the error you're getting and the Statamic version you're using?

**Comment by jasonvarga** [comment]
Hey there, we haven’t heard back on this for a while so I’m going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!
