### ISSUE TITLE
Taxonomy fieldtype only creates new terms if there are multiple words in the name

### ISSUE THREAD

**Issue by davidwarrington** [statamic/cms#2339]
## Bug Description
I'm trying to create taggable blog posts, however when the tag field is set to typeahead new taxonomies aren't automatically created after being added to a post unless there's more than one word in the term name.

## How to Reproduce
1. Create a "tags" taxonomy
1. Add a taxonomy fieldtype to a collection blueprint associated with the new taxonomy
2. Create an entry in the collection, and type the following 3 tags into the new field: tag, term, term tag
3. Hit save and publish, and refresh the page
4. The tags will change for "term" and for "tag" will have changed to what would be the term IDs, e.g. `tags::term`, `tags::tag`. The "term tag" tag will appear as expected still
5. Visit the "tags" taxonomy. It will have a term for "term tag", but not for "tag" or for "term"

## Environment

**Statamic version:** 3.0.2

**PHP version:** 7.4.9

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
That's expected. If what you type is no different from what the slug would end up being, then it won't bother creating a file. 

It's not just multi word terms. You could type a single word containing an upper case character and see the file get created.

test => test => no file needed
Test => test => file needed
test-term => test-term => no file needed
test term => test-term => file needed

**Comment by davidwarrington** [comment]
@jasonvarga Is there any reason not to create new terms regardless?

My two concerns with not creating new terms are:
1. Potential confusion to non-developer CMS users who see some terms prefixed with the taxonomy ID, e.g `tags::tag`, and others as they were originally typed, e.g. `tag 2`.
	![image](https://user-images.githubusercontent.com/9138568/91844030-a2bb2780-ec4e-11ea-8a54-698e105e1584.png)
2. Since a new term isn't created for all that are added, not all terms really exist. For example, if I visit another blog post and try to apply the same tags, only those for which files have been created will be available. Take the image below as an example, I'd added the tags `tag` and `tag 2` to a different article, and only `tag 2` is suggested here. `tag` is also not listed on the front end when I loop through the taxonomy.
	![image](https://user-images.githubusercontent.com/9138568/91843193-4277b600-ec4d-11ea-9061-c9fe36d24ebd.png)
	![image](https://user-images.githubusercontent.com/9138568/91844318-22e18d00-ec4f-11ea-8b47-eff5b40cf87d.png)

I appreciate it doesn't say anywhere "the taxonomy fieldtype will create new terms if you add one that doesn't exist", but currently it does under certain conditions, and I think that's a bit confusing.
