### ISSUE TITLE
Custom Bard Extensions can not be shown or hidden via the button config

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#2340]
## Bug Description
Custom Bard Extensions can not be shown or hidden with the button configuration in the YAML file. The buttons are always shown.

## Extra Detail

Here is an example how we register the extension in our app.js
```
// booting
Statamic.booting(() => {

    // bard extensions
    Statamic.$bard.extend(({ bard, mark }) => mark(new EntryLink(bard)));

    Statamic.$components.register('EntryLinkToolbarButton', require('./components/bard/EntryLinkToolbarButton.vue').default);

    Statamic.$bard.buttons(() => ({
        name: 'entrylink',
        text: __('Link to Entry'),
        command: 'entrylink',
        html: '<i class="icon icon-forward"></i>',
        component: 'EntryLinkToolbarButton',
    }));
});
```

## Environment

**Statamic version:** cc4b3bd77921faec64af799fcfc27a4c7c6b9022

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by sauerbraten** [comment]
Apparently, the way to do this is to use the button condition called by Statamic when adding the button callback:

```js
Statamic.$bard.buttons(() => ({
    name: 'entrylink',
    text: __('Link to Entry'),
    html: '<i class="icon icon-forward"></i>',
    component: 'EntryLinkToolbarButton',
    activeCommand: 'entrylink',
    condition: config => config.buttons.includes('entrylink'),
}));
```

Still, I think it would make sense for Statamic to check this for you.

**Comment by sauerbraten** [comment]
I'd say this is a quick fix on the CMS side and would make life easier for extensions.

**Comment by jasonvarga** [comment]
In 3.2.24 you'll be able to wrap your button object and it'll conditionally be shown based on whether you've added it to a field's buttons array.

Before:

```js
Statamic.$bard.buttons(() => ({
  name: 'entrylink',
}));
```

After:

```js
Statamic.$bard.buttons((buttons, button) => button({
  name: 'entrylink',
}));
```
