### ISSUE TITLE
Having a translation file called "search.php" throws an exception

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#2341]
## Bug Description
When you create a translation file called `search.php`, the app throws an exception. This only happens when adding the file to the `en` locale.

## How to Reproduce
1. New installation of Statamic
2. Create the file `resources/lang/en/search.php`
3. Add the content `<?php return ['anything'];`
4. Open the page (anything, front- or backend)

## Extra Detail

Here's the stacktrace. I think this is linked to line 11.

```
ErrorException: mb_strtoupper() expects parameter 1 to be string, array given in file /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 519

#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mb_strtoupper()...', '/Users/me/...', 519, Array)
#1 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Support/Str.php(519): mb_strtoupper(Array, 'UTF-8')
#2 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(224): Illuminate\Support\Str::upper(Array)
#3 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(196): Illuminate\Translation\Translator->makeReplacements(':title', Array)
#4 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Translation/Translator.php(126): Illuminate\Translation\Translator->getLine('statamic', 'permissions', 'en', 'access_utility', Array)
#5 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(864): Illuminate\Translation\Translator->get('statamic::permi...', Array, 'en')
#6 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(899): trans('statamic::permi...', Array, NULL)
#7 /Users/me/Workspace/bugtest/vendor/statamic/cms/src/Auth/CorePermissions.php(191): __('statamic::permi...', Array)
#8 /Users/me/Workspace/bugtest/vendor/statamic/cms/src/Auth/Permissions.php(29): Statamic\Auth\CorePermissions->Statamic\Auth\{closure}(Object(Statamic\Auth\Permission))
#9 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\Auth\Permissions->register(Object(Statamic\Auth\Permission), Object(Closure))
#10 /Users/me/Workspace/bugtest/vendor/statamic/cms/src/Auth/CorePermissions.php(193): Illuminate\Support\Facades\Facade::__callStatic('register', Array)
#11 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): Statamic\Auth\CorePermissions->Statamic\Auth\{closure}(Object(Statamic\CP\Utilities\Utility), 'search')
#12 /Users/me/Workspace/bugtest/vendor/statamic/cms/src/Auth/CorePermissions.php(194): Illuminate\Support\Collection->each(Object(Closure))
#13 /Users/me/Workspace/bugtest/vendor/statamic/cms/src/Auth/CorePermissions.php(57): Statamic\Auth\CorePermissions->registerUtilities()
#14 /Users/me/Workspace/bugtest/vendor/statamic/cms/src/Auth/Permissions.php(102): Statamic\Auth\CorePermissions->Statamic\Auth\{closure}()
#15 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\Auth\Permissions->group('utilities', 'Utilities', Object(Closure))
#16 /Users/me/Workspace/bugtest/vendor/statamic/cms/src/Auth/CorePermissions.php(219): Illuminate\Support\Facades\Facade::__callStatic('group', Array)
#17 /Users/me/Workspace/bugtest/vendor/statamic/cms/src/Auth/CorePermissions.php(58): Statamic\Auth\CorePermissions->group('utilities', Object(Closure))
#18 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\Auth\CorePermissions->boot()
#19 /Users/me/Workspace/bugtest/vendor/statamic/cms/src/Providers/AuthServiceProvider.php(85): Illuminate\Support\Facades\Facade::__callStatic('boot', Array)
#20 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): Statamic\Providers\AuthServiceProvider->Statamic\Providers\{closure}(Object(Illuminate\Foundation\Application))
#21 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#22 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#23 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#24 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Foundation\Application->bootstrapWith(Array)
#25 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(135): Illuminate\Foundation\Http\Kernel->bootstrap()
#26 /Users/me/Workspace/bugtest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#27 /Users/me/Workspace/bugtest/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#28 /Users/me/.composer/vendor/weprovide/valet-plus/server.php(131): require('/Users/me/...')
#29 {main}
```

## Environment

**Statamic version:** 3.0.2

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
You're getting that error because you have an array with one string in it.

```
<?php return [
  'anything'
];
```

You need an array of key value pairs.

```
<?php return [
  'anything' => 'Anything',
];
```

**Comment by FlorianMoser** [comment]
@jasonvarga I know the difference between an associative array and a normal array. I omitted the key for brevity. The issue occurs in both cases.

The error is `expects parameter 1 to be string, array given`, no matter if associative or not. The issue should be reopened.

**Comment by jasonvarga** [comment]
Can you please provide your actual array then?

**Comment by FlorianMoser** [comment]
It actually doesn't matter. You can add this content:
```
<?php return [
  'anything' => 'Anything',
];
```
It's the presence of the `resources/lang/en/search.php` that returns any array that leads to this issue. Add the same file to any other language (ie `resources/lang/fr/search.php`) doesn't produce the error. Also, rename the file (ie `resources/lang/en/search1.php`) and the error is gone.

**Comment by jasonvarga** [comment]
Okay I thought I did exactly that and didn't run into an error. My mistake.

**Comment by FlorianMoser** [comment]
> Okay I thought I did exactly that and didn't run into an error. My mistake.

No problem. I guess the file overwrites a Statamic specific translation you use in the statamic/cms package.

**Comment by jasonvarga** [comment]
I'm guessing its exactly the same issue as https://github.com/statamic/cms/issues/2342 which I just said to him 

> If this becomes a real problem for more people, we can look at finding a proper fix.

So I guess that's happening. 😆

**Comment by FlorianMoser** [comment]
Yeah, a proper fix would be nice 😊

I spent an hour debugging, after the site stopped working just by adding a (1:1 copy) english translation (with the `search.php` file) to the CMS.

**Comment by jesperlindstrom** [comment]
We are experiencing a lot of strange behavior related to this. 

We have a translation file called `form.php` with an array that we are using to translate forms in the front-end templates. The admin panel seems to do `__('form')` when showing the "Form" fieldtype, accidentally causing this:

<img width="460" alt="Skärmavbild 2020-12-09 kl  14 22 11" src="https://user-images.githubusercontent.com/1730738/101635223-f1d0df80-3a29-11eb-8314-f532482097de.png">

We have accidentally hit several reserved keywords that breaks various parts of the admin panel (some full crashes, some just weird outputs like above). This is obviously frustrating. 

Hoping for a general solution to this. Statamic is great, but the multisite/localization features feels quite unstable right now.

**Comment by jasonvarga** [comment]
Create `resources/lang/en.json` and add this:

```
{
  "Form": "Form"
}
```

**Comment by aerni** [comment]
I ran into this issue as well. I can't name language files `general.php` or `layouts.php`. Running out of ideas for a filename for general type of translations 😅

**Comment by daiwai** [comment]
Are there any plans to address this issue and what do you think would be the best way to solve it?

As far as I understand the root cause is essentially the bad design of the upstream `__()` and `trans()` helper functions: I.e. the fact that although they are explicitly documented as [String Helpers](https://laravel.com/docs/8.x/helpers#strings-method-list) in the high level docs they may return an array.

While I understand that it can be useful to retrieve the contents of a translation file, the current behavior of the `__()` function, which can both translate a string and output the full contents of a translation file, is quite unexpected, as evidenced by the way the function is used in Statamic, as well as this and the other tickets about the same problem.

Strictly speaking, in all places where the `__()` function is used, there should either also be a check that a string was indeed returned. Or it would have to be ensured by the arguments passed to the translation function that a string is always returned. But the latter will not be possible in general, because the function translates e.g. dynamic content in the backend menu, like the collection names, which are essentially "user provided". 

By the way, another factor that makes this bug difficult to understand is the fact that it is partly dependent on the operating system or file system. For example, on systems with case insensitive file names, it also occurs when the translation key is uppercase and the translation file name is lowercase.

For example, `__('Events') might work on a Linux system but return the contents of the file `resources/lang/en/events.php` on macOS, resulting in an error.

This behavior is actually mentioned in the [Laravel docs](https://laravel.com/docs/8.x/localization#using-translation-strings-as-keys), although the way they describe the workaround is not quite right, i.e. it is not enough to have `resources/lang/nl.json` file, but that file also has to contain the name of the `.php` file as a key.

**Comment by jasonvarga** [comment]
The workaround is in my last comment.

The solution is probably to have Laravel not return arrays in those situations. That's probably a fairly breaking change though.
