### ISSUE TITLE
Collection with 2 blueprints, 1 blueprint doesn't show

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/cms#2352]
## Bug Description

I've got a `blog` collection that has a `blog` and `link` blueprint assigned.

When I loop over `{{ collection:blog }}` it only spits out those entries with the `blog` blueprint the entries with the `link` blueprint are missing.

The loop is as simple as it gets

```
{{ collection:blog }}
	<h1>{{ title }}</h1>   
{{ /collection:blog }}
```

## Environment

Statamic 3.0.2 Solo
Laravel 7.27.0
PHP 7.4.9
aryehraber/statamic-splash 1.0.3

**Comment by jasonvarga** [comment]
By default, entries with redirects will be filtered out. Add `redirects="true"` (or `links`) to include them.

**Comment by 1stevengrant** [comment]
Ah, I managed to miss this in the docs 🙄
