### ISSUE TITLE
Special character in asset folder name causes 500-error

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#2353]
## Bug Description
Characters like æ, ø, å, ü, ä etc. (properly all kinds of those special characters) in folder names shouldn't be allowed.
Files in folders in these kinds of characters would cause 500-errors. 

## How to Reproduce
- Create a folder with one of those special characters from the asset browser.
- Add a file in the folder.
- Try to view/edit the file.

## Extra Detail

![Skærmbillede 2020-09-02 kl  16 00 50](https://user-images.githubusercontent.com/43215436/91995410-15ec9880-ed38-11ea-8db7-e05638272b5f.png)

## Environment

**Statamic version:** 3.0.2

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Confirmed this bug.

 It think it's happening because the special characters turn the string into a multi-byte string (at least that's what I managed to gather from a few minutes of debugging)

**Comment by AndreasSchantl** [comment]
Just got a confused customer about this. I hope to get some time this weekend to fix it myself. It's a bit of a nasty one.
