### ISSUE TITLE
Variable used in Antlers Template output is not parsed but shows as text

### ISSUE THREAD

**Issue by justinhough** [statamic/cms#2355]
## Bug Description

When adding variables using Yaml at the top of a view like `*.antlers.html` the Yaml gets outputted as text at the top of the view rather than getting parsed. I am referencing the documentation here: https://statamic.dev/variables#view-frontmatter

```
---
foo: bar
---
{{ view:foo }}
```

## How to Reproduce
1. Add Yaml to a  view `*.anters.html`
2. Check frontend of site.

## Extra Detail

![image](https://user-images.githubusercontent.com/9469422/92021960-cd24e780-ed17-11ea-8488-ba07884b7936.png)

![image](https://user-images.githubusercontent.com/9469422/92022112-03626700-ed18-11ea-929e-d5705335f49d.png)

## Environment

Statamic 3.0.2 Pro
Laravel 7.26.1
PHP 7.4.7
statamic/migrator dev-master

I am currently running a migration test from a Statamic 2 site.

**Comment by jasonvarga** [comment]
Are you sure you're using `.antlers.html` and not just `.html`?

**Comment by justinhough** [comment]
All the templates are named appropriately from what I can tell.

![image](https://user-images.githubusercontent.com/9469422/92022388-6d7b0c00-ed18-11ea-9cbf-0e2a5225ef7c.png)

**Comment by jasonvarga** [comment]
What about if you remove that extra blank line at the top of the file?

**Comment by jasonvarga** [comment]
When I add a blank line, it breaks exactly as you're describing.

Are you certain the `---` is the first line? Is your editor adding a blank line on save?

**Comment by justinhough** [comment]
I can confirm that it is the first line in that file and no lines are being added.

The way that template gets loaded is from a layout file that uses `{{ template_content }}` to load that specific template for `messages/single.antlers.yaml`.

 Is there a dependency where the Yaml is not parsed from a template file anymore, but only from the first line of the layout?

**Comment by jasonvarga** [comment]
Here's where it's happening: https://github.com/statamic/cms/blob/master/src/Facades/Endpoint/Parse.php#L65

Do you have any spaces after the first `---`?

**Comment by justinhough** [comment]
No spaces after the first line with `---` just a line break.

Here is the original Line
![image](https://user-images.githubusercontent.com/9469422/92024861-f8a9d100-ed1b-11ea-8b45-61595b7c7b19.png)

I even tried removing everything from the default layout, except for `{{ template_content }}` and it still would not parse the Yaml.
![image](https://user-images.githubusercontent.com/9469422/92024822-eaf44b80-ed1b-11ea-95fc-45a61e2d58f8.png)

**Comment by jasonvarga** [comment]
Can you show your composer.json?
What OS are you using?

**Comment by justinhough** [comment]
I am on Mac OS 10.15.6

It is the standard composer from the default CLI installer.

Composer JSON:
```
{
    "name": "statamic/statamic",
    "description": "Statamic",
    "keywords": ["statamic", "cms", "flat file", "laravel"],
    "type": "project",
    "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "statamic/cms": "3.0.*"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5",
        "statamic/migrator": "dev-master"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan statamic:install --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

**Comment by jasonvarga** [comment]
Does this happen on any view? Or just that one specific view?

**Comment by justinhough** [comment]
I think I found the issue. That file was set to `CRLF` rather than `LF`. Changing the file to LF seems to fix the problem.
