### ISSUE TITLE
Replicator options inaccessible due to trial banner

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2356]
## Bug Description
The trial banner blocks replicator options. The only way for users to add a set now is to collapse all sets and hope there screen is large enough.

## Extra Detail
<img width="1384" alt="Screenshot 2020-09-03 at 09 33 00" src="https://user-images.githubusercontent.com/69107412/92086359-5f85c380-edca-11ea-9898-edc56c69b38a.png">

## Environment
Statamic 3.0.2 Pro
Laravel 7.26.1
PHP 7.4.6
No addons installed

**Comment by jackmcdade** [comment]
What browser is that? I can't recreate it – the way that dropdown works is when it runs out of room it flips vertically. Here's what I see in every browser: 
![image](https://user-images.githubusercontent.com/44739/93141196-bedcb100-f6b1-11ea-8c53-a4b991bee4cd.png)

**Comment by robdekort** [comment]
Hey Jack, it's in Safari on Big Sur, I just recreated this in Catalina as well. I can give you a login for a staging site with steps to reproduce if you want. You could also clone Peak, add an article to a page. If your screen is tall enough and not yet filled add one or two button sets to the article and then try to add a new replicator block.

Demo:
https://www.icloud.com/iclouddrive/0wfCGiIDBnBf5erZm9SgcG_Dw#Screen_Recording_2020-09-15_at_09.00

**Comment by jasonvarga** [comment]
I can replicate in all browsers. Just slowly drag the bottom of the browser up and there will be 60-ish pixels of overlap before the popover decides to change positions. If you resize the browser quickly you might not notice it.

**Comment by edalzell** [comment]
Trial banner is now dismissible.

**Comment by robdekort** [comment]
Not sure if this should be closed as you have to dismiss the banner on every page.

**Comment by jackmcdade** [comment]
It's fixed in 90% of the use cases in which banners may show, and the banner is now dismissible. This is as good as it's gonna get for now considering other things going on :)

**Comment by robdekort** [comment]
Ok. That's up to you.
