### ISSUE TITLE
Hide trial mode message on non-plublic installation with valid license

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#2357]
## Bug Description
The trial mode message is a total valid nag for people using the software for free. But it takes up screen real-estate and should not be shown in dev mode to users who entered a valid license code. Alternatively make the message less obtrusive for installations which were paid for.

It is a bit annoying navigating around the banner, even if I paid for a license.

I know the license cannot be fully verified, as the URL will always be a test-URL (and devs can therefore always provide a valid license if they paid at least once). But hiding the banner on dev-environments when there is a license number that was registered at statamic.com should be an acceptable degree of relaxation.

## Environment

**Statamic version:** 3.0.3

**Comment by jasonvarga** [comment]
Add your development url to your site on statamic.com and the banner goes away.

**Comment by FlorianMoser** [comment]
That's what I did. Added domain "xyz.test" with the "Testing" environment on statamic.com. Now I'm on "xyz.test/cp" and it shows the banner. It's actually not "xyz", but I can't name the domain in public for now. I can DM you the details if required.

**Comment by jasonvarga** [comment]
It won't update immediately after you do something on statamic.com as we cache the calls. If you click through the trial banner then click sync, does the banner go away?

**Comment by jasonvarga** [comment]
Have you purchased a license? Did you assign it to that site?

**Comment by FlorianMoser** [comment]
Pretty sure that's the case, yes:

![grafik](https://user-images.githubusercontent.com/8578668/92117405-6fff6380-edf5-11ea-88e1-aa36affc9de8.png)

**Comment by jasonvarga** [comment]
That's a v2 license, you need v3.

**Comment by FlorianMoser** [comment]
Oookay. I see now there's an upgrad available. Pretty sure this wasn't there the last time I visited. Thought that the conversion would happen automatically.

Banner's gone now, thanks.
