### ISSUE TITLE
Context from outside a tag pair is still available from within

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2365]
## Bug Description
I have a tag pair that returns an array. Within the tag pair, I can still access the context from outside the tag pair. However, the [docs say that it shouldn't](https://statamic.dev/extending/tags#tag-pairs). I'm not sure if this is a bug or if the docs are wrong.

## How to Reproduce
1. Create a tag pair. I used the example from the docs
2. Use it in a template and use something like `{{ title }}` within the tag
3. The `{{ title }}` from the context outside of the tag pair will still render

## Environment
Statamic 3.0.3 Pro
Laravel 7.27.0
PHP 7.4.9
aerni/snipcart dev-master

**Comment by jasonvarga** [comment]
I think that's a mistake in the docs. I believe we had it working without context initially but quickly realized that was stupid.

**Comment by jasonvarga** [comment]
Adjusted in https://github.com/statamic/docs/commit/d393ce16895d3928e48ab9aeddca69ee85fb90af
