### ISSUE TITLE
Width of fieldtypes at sidebar is ignored

### ISSUE THREAD

**Issue by brnmonteiro** [statamic/cms#2366]
## Bug Description
The width of fieldtypes at sidebar is ignored.

## How to Reproduce
Just create at blueprint 3 togglefield type with width 33% on sidebar

## Extra Detail
![Screen 2020-09-04 às 09 40 00](https://user-images.githubusercontent.com/6596579/92240390-f0c06d00-ee92-11ea-904f-d8e1c211082a.jpg)
![Screen 2020-09-04 às 09 42 28](https://user-images.githubusercontent.com/6596579/92240397-f4ec8a80-ee92-11ea-9c65-5a689d8466b2.jpg)

## Environment

**Statamic version:** 3.0.3

**PHP version:** 7.3

**Comment by jasonvarga** [comment]
Yeah the sidebar fields are all 100% width, intentionally. The toggle field with a short label is pretty much the only field that would fit side by side so your example is a bit of a fluke. Pretty much everything else would look squashed.
