### ISSUE TITLE
Allow forcing of English git commit messages in a multi-lingual app

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#2367]
> We use the german locale, so the CP is translated to german for our client. We would prefer the GIT integration to use english push messages though. Is that possible?

**Comment by jesseleite** [comment]
Assuming the commit messages have translations in your app, this will be possible via [this new locale config](https://github.com/statamic/cms/blob/master/config/git.php#L134-L145) in 3.0.8

**Comment by AndreasSchantl** [comment]
@jonassiewertsen this one is for you!
