### ISSUE TITLE
Collection overview filtering issue in CP

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2368]
## Bug Description
I'm getting a `Maximum function nesting level of '256' reached, aborting!` error when removing the site filter in a collection overview. I have to `php artisan cache:clear` to get rid of it.

## How to Reproduce
I can't quite figure out how to reproduce it myself. But playing around with filters, adding, deleting, etc. eventually always ends in that error. Also, not sure if this is a multi-site issue or a general problem.

## Environment
Statamic 3.0.5 Pro
Laravel 7.27.0
PHP 7.4.9
aerni/snipcart dev-master

**Comment by jackmcdade** [comment]
Closed the wrong issue by mistake. My bad.

**Comment by jasonvarga** [comment]
Closing this because it's vague. If you encounter it again, feel free to reopen it but please make sure to include a stack trace.
