### ISSUE TITLE
php translator generate error

### ISSUE THREAD

**Issue by itrlink** [statamic/cms#2371]
## Bug Description
php translator generate don;t working fine
Made like in instruction:
1. Clone statamic/cms locally
2. Run composer install
3. Generate a new translation from source files -> error
On this step after command: php translator generate {{lang_code}} have error: Could not open input file: translator
Please help me =)

**Statamic version:** 3.0.last

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/cms`

**Comment by damcclean** [comment]
I think you'll need to change into the statamic cms folder before you can run the translator command. Like this:

```
cd vendor/statamic/cms
php translator....
```

**Comment by jasonvarga** [comment]
Are you running the composer and php translator commands inside the cms directory after you clone it?

**Comment by itrlink** [comment]
Yes, sure! 
What i do:
1. create test folder
2. in folder test copy statamic/cms folder
3. run composer install
4. run translator command - error Could not open input file: translator
change dir to vendor/statamic/cms
run composer install
run translator command - error Could not open input file: translator

What i do wrong?

**Comment by ebeauchamps** [comment]
Translator must be inside your directory. Here is my setup for running it.

![Capture d’écran 2020-09-06 à 20 58 39](https://user-images.githubusercontent.com/1823359/92333172-ca155880-f083-11ea-8ae1-b979977c80b6.png)

**Comment by itrlink** [comment]
i don't have this file. Please share =)

**Comment by jasonvarga** [comment]
@itrlink upload a screenshot of the directory you cloned

**Comment by itrlink** [comment]
All fine! Very big thanks for your help!

**Comment by maxi032** [comment]
I have the same problem. I don't have any translator file

**Comment by jasonvarga** [comment]
The translator file will only be there if you fork/clone the `cms` repo. It won't be in the `vendor` directory of your app - you shouldn't use it that way.
