### ISSUE TITLE
[i18n] Missing string (or certainly bad string) in language json file (i.e. fr.json): "Edit Blueprints" instead of "Edit Blueprint"

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#2372]
## Bug Description
"Edit Blueprints" does not appear in French in my CP
My fr.json file only has "Edit Blueprint" and not "Edit Blueprints"
I think "Edit Blueprints" is a mistake

## How to Reproduce
Visit the Collection page and click on the 3 dots button on the right hand-side

## Extra Detail

![Capture d’écran 2020-09-06 à 20 50 38](https://user-images.githubusercontent.com/1823359/92333108-36dc2300-f083-11ea-9edf-35c1830578ee.png)

![Capture d’écran 2020-09-06 à 20 55 23](https://user-images.githubusercontent.com/1823359/92333118-570be200-f083-11ea-9f1e-ab0b4aec4198.png)

## Environment

**Statamic version:** 3.0.5

**PHP version:** 7.4.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
The plural form, Edit Blueprints, is the preferred term here.

**Comment by jonassiewertsen** [comment]
Ok, sticking with the plural form is fine. The plural form is not represented in the translation files, that's why it's not being translated. 

The correct fix will be a PR for the community :-)

**Comment by ebeauchamps** [comment]
see #2381
