### ISSUE TITLE
Can't add to core permissions

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2374]
## Bug Description

Trying to add a permission to the core collection permissions and I get an error.

## How to Reproduce

```
    private function bootPermissions()
    {
        $this->app->booted(function () {
            Permission::get('edit {blog} entries')->addChild(
                Permission::register('tweet {form} entries')
            );
        });
    }
```

## Extra Detail

<img width="634" alt="image" src="https://user-images.githubusercontent.com/6069653/92347229-45770a00-f084-11ea-9f6e-ad0987d961fb.png">

<img width="524" alt="image" src="https://user-images.githubusercontent.com/6069653/92347248-558ee980-f084-11ea-85f4-3c75d75b512c.png">

## Environment

Statamic 3.0.5 Pro
Laravel 7.27.0
PHP 7.4.9
edalzell/anvil dev-master
edalzell/blade-directives dev-main
edalzell/feeds dev-master
edalzell/mailchimp dev-master
edalzell/pinboard dev-master
edalzell/rss 1.0.2
silentz/akismet dev-master

**Comment by edalzell** [comment]
If I do `Permissions::all()` the array is empty.

**Comment by damcclean** [comment]
To resolve the issue, you'll need to boot the Statamic's core permissions before you can add your own permissions.

```
use Facades\Statamic\Auth\CorePermissions;
use Statamic\Facades\Permission;

$this->app->booted(function () {
  CorePermissions::boot();

  Permission::get('edit {blog} entries')->addChild(
    Permission::register('tweet {form} entries')
  );
});
```

**Comment by edalzell** [comment]
Seems off to me that we have to do this, think this is still an issue.

Thanks for the workaround though!

**Comment by edalzell** [comment]
>   CorePermissions::boot();

Can't be called statically.

**Comment by edalzell** [comment]
@damcclean doing that duplicates all the permissions in the CP

**Comment by jasonvarga** [comment]
Here's how you can do it now in 3.4.

```php
public function boot()
{
	Permission::extend(function () {
	    Permission::get('edit {collection} entries')->addChild(
	        Permission::make('tweet {collection} entries')->label('Tweet entries')
	    );
	});
}
```

This will the permission to all collections. You can't just add it to one.
