### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2382]
I haven't tried upgrading yet and I don't know what's involved on our end. Maybe nothing (except updating the composer constraint)

Statamic 3.0.6

**Comment by gofish543** [comment]
The main conflict, package wise, is the requirement of Guzzle 7.0 for Laravel 8.0. 
Statamic is at 6.5

**Comment by jasonvarga** [comment]
laravel/laravel does, but not laravel/framework. Do we know why?

**Comment by gofish543** [comment]
laravel/laravel required Guzzle 7.0 shortly after Taylor implemented the `Http::get($uri)` suite.
I'm going to try and leave Guzzle at 6.5 for the upgrade and see what conflicts arise.

**Comment by jasonvarga** [comment]
I'm already working on the upgrade fyi

**Comment by gofish543** [comment]
After downgrading Guzzle back to 6.5 it appears that the Statamic position of dependencies was resolved.

**Comment by edalzell** [comment]
Linking: https://github.com/statamic/ideas/issues/241

**Comment by jasonvarga** [comment]
Alright this is blocked by the Guzzle flysystem adapter. No response there since July so maybe we fork it or just bring it inline. We use it to let Glide transform images from external URLs.

**Comment by damcclean** [comment]
The pull request to support Laravel 8 has been merged, #2547.
