### ISSUE TITLE
Statamic doesn’t generate metadata for assets if file already exists

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#2385]
## Bug Description
If a metadata file already exists for an asset, statamic will not generate metadata for that image, even if the metadata file does not contain all of the metadata. This leads to undefined index errors in the control panel when trying to access the asset container in question.

## Environment

**Statamic version:** 3.0.{?}

**PHP version:** 7.{?}

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by jasonvarga** [comment]
You opened this exact issue already, no?

#2338

**Comment by fitzage** [comment]
Gah, Jesse and I couldn’t find it. sorry.
