### ISSUE TITLE
Mail templates do not use the current locale

### ISSUE THREAD

**Issue by pryley** [statamic/cms#2386]
## Bug Description

Forms use a Blueprint to define its fields. Unfortunately, field Display names in Blueprints are not localizable. 

Being able to localize the display name of a form field is useful when you want to send an email notification to the sender of the form. For example, if a form is submitted on a German page, you would want a German email to be sent to the sender.

**Since we are unable to localize Blueprint field values**, a workaround is to create a `{locale}.json` file which contains the localized translation for the current locale, and use a `/resources/lang/{locale}/strings.php` file for the named translations. Now we can do this in the email template:

```
{{ trans:strings.form_mail_title }}

{{ fields }}
    {{ trans key="{display}" }}: {{ value }}
{{ /fields }}
```

**However, this does not seem to work.** If I submit a form on the German page of a multi-site, I expect the generated email to be in German but it remains in English.

## Extra Detail

**This is the contact form Blueprint:**

![image](https://user-images.githubusercontent.com/134939/92511955-ad883600-f1d3-11ea-92dc-2fca5351e1e7.png)

**This is the contact form displayed on the German page (the strings here are translated correctly):** 

![image](https://user-images.githubusercontent.com/134939/92512066-d90b2080-f1d3-11ea-8c38-314635eb62d2.png)

**This is the content of the `/resources/lang/de.json` file:**

```json
{
    "Country": "Land",
    "E-mail address": "E-Mail-Adresse",
    "First Name": "Vorname",
    "Last Name": "Nachname",
    "Message": "Nachricht",
    "Occupation": "Beruf",
    "Telephone number": "Telefonnummer"
}
```

**This is the content of the `/resources/lang/de/strings.php` file:**

```php
return [
    // Contact form
    'form_honeypot'                     => 'Fax',
    'form_mail_body_owner'              => 'Neues Formular einreichen',
    'form_mail_body_sender'             => 'Vielen Dank für Ihre Nachricht, wir werden Sie so schnell wie möglich kontaktieren.',
    'form_mail_closing'                 => 'Mit freundlichen Grüßen',
    'form_mail_from'                    => config('app.name'),
    'form_mail_greeting'                => 'Hallo',
    'form_mail_logo'                    => config('app.url').'/images/mark.png',
    'form_mail_submitted'               => 'Eingereicht',
    'form_mail_title'                   => 'Kontakt Formular',
    'form_mail_url'                     => config('app.url'),
    'form_send'                         => 'Nachricht senden',
    'form_success'                      => 'Vielen Dank, wir haben Ihre Nachricht erhalten und werden Sie so schnell wie möglich kontaktieren.',
];
```

**This is the content of the plaintext email template that is send to the sender of the form:** 

```
{{ trans:strings.form_mail_greeting }} {{ first_name or name }},

{{ trans:strings.form_mail_body_sender }}

{{ trans:strings.form_mail_closing }},
{{ trans:strings.form_mail_from }}

-
{{ fields }}
    {{ trans key="{display}" }}: {{ value }}
{{ /fields }}

-
{{ trans:strings.form_mail_submitted }} {{ now | timezone | format:r }}
{{ trans:strings.form_mail_from }}

```

**And finally, here is the email (html version) of the email that is sent that _should_ be in German:**

![image](https://user-images.githubusercontent.com/134939/92412679-6d14b380-f112-11ea-9ab9-53d9d47e8718.png)

## Environment

- Statamic 3.0.6 Pro
- Laravel 7.27.0
- PHP 7.4.8
- aryehraber/statamic-impersonator 2.0.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
I can confirm. FYI: I remember this working in v2.

**Comment by cgrisar** [comment]
I guess this is somehow related to the bug I entered #2387

**Comment by robdekort** [comment]
Great workaround for now by @AndreasSchantl:

Add a hidden input field with value `{{ config:app:locale }`} to the form and reference it in you mail templates by using `{{ trans:strings.key locale="{locale}" }}` or `{{ trans key="{key}" locale="{locale}" }}`.

**Comment by robdekort** [comment]
Unfortunately with this technique I haven't been able to translate the subject line.

**Comment by plompd** [comment]
@AndreasSchantl You are sure this is working in your email templates regarding localization?

`{{ trans:strings.key locale="{locale}" }}`

For me, this isn't doing anything.

**Comment by AndreasSchantl** [comment]
@plompd Are your translation files matching the locales? How's your file named?

**Comment by plompd** [comment]
@AndreasSchantl I have two directories:

/lang/en
/lang/nl

with some custom files.

Inside the email templates I refer to the keys inside those files.

The directories are the same as my locales.
