### ISSUE TITLE
Validation errors in frontend are not shown in the locale of the current site

### ISSUE THREAD

**Issue by cgrisar** [statamic/cms#2387]
## Bug Description
Validation errors in frontend are not shown in the locale of the current site

## How to Reproduce
Create a multisite (sites.php)
Create a form with validation on the fields
Switch from one site to the other
Validation errors are only shown in "en" locale.

## Extra Detail

Site in Dutch, validation errors in English
![Screenshot 2020-09-08 at 17 19 41](https://user-images.githubusercontent.com/7884608/92513323-68cec000-f210-11ea-9f96-6f8615c08e02.png)

## Environment

**Statamic version:** 3.0.{?}

**PHP version:** 7.{?}

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by jasonvarga** [comment]
Please share:
- your sites.php file
- the path to the translation php file

**Comment by cgrisar** [comment]
Sites.php
```
'sites' => [

        'en' => [
            'name' => 'MIQ - English',
            'locale' => 'en_EN',
            'url' => '/',
        ],
        'nl' => [
            'name' => 'MIQ - Nederlands',
            'locale' => 'nl_NL',
            'url' => '/nl/',
        ],
        'fr' => [
            'name' => 'MIQ - Frans',
            'locale' => 'fr_FR',
            'url' => '/fr/',
        ],

    ],

Tried various combinations, including removing "en" site, or using "nl" and "fr" as value to locale key.

validation.php in

/resources/lang/en
/resources/lang/fr
/resources/lang/nl

The same folders I use when using the {{ trans }} tag

**Comment by cgrisar** [comment]
Small correction: the validation errors are shown in het locale as set in config/app.php

**Comment by robdekort** [comment]
Not sure about this yet, but it seems the Dutch translations are out of date. Maybe this is why you don't see the correct error language. I'll see if I can update those a.s.a.p.

**Comment by cgrisar** [comment]
It's not that, Rob

**Comment by robdekort** [comment]
Good to know. I hope this issue can get bumped up then.

**Comment by robdekort** [comment]
I can confirm this issue and just set up a [demo project](https://www.icloud.com/iclouddrive/02U1KT5hg5So2aI5Ecdksn2Pg#statamic-issue-2387) for core team to check this out. There's a contact form on the homepage. The homepage is in Dutch and if you send the form without any values you'll get back English error messages.

**Comment by robdekort** [comment]
Is there any workaround known for this?

**Comment by jasonvarga** [comment]
Fixed for next release.

Make sure that you have the appropriate validation translation file in your `resources/lang/{lang}` directory.

For example, here's the French one: https://github.com/Laravel-Lang/lang/blob/master/src/fr/validation.php
That repo contains translations for a ton of languages.

**Comment by cgrisar** [comment]
Thanks Jason

**Comment by robdekort** [comment]
Can anyone explain to me how it localised field validation should work? It kinda confuses me.

With the current Dutch validation.php in the repo I get a 'This field is required', but then nicely in Dutch. Fine by me, but not how it should be I guess.

If I replace the Dutch  validation.php file with the one from the repo Jason mentioned, I get a 'ENGLISH FIELD NAME is verplicht' (part english, part dutch). It's nothing major but I'd like to understand :-)

**Comment by cgrisar** [comment]
Check the /nl/validation.php file
