### ISSUE TITLE
OAuth integration UserRepository::findByOAuthID() function is empty

### ISSUE THREAD

**Issue by ctwidodo** [statamic/cms#2388]
## Bug Description
Issue when integrating OAuth with different services such as Github. Note that I'm using database for the User instead of Stache. Looking at the Stache\UserRepository, it seems the findByOAuthId() is implemented correctly.
The error message is
`
TypeError
Return value of Statamic\Auth\Eloquent\UserRepository::findByOAuthId() must be an instance of Statamic\Contracts\Auth\User or null, none returned
`

## How to Reproduce
I followed the steps on the [Statamic OAuth page](https://statamic.dev/oauth)
1. Added oauth provider to statmic/oauth.php
2. Add provider credential to config/services.php
3. Update config/statamic/oauth.php with the service
4. Add login redirect route and callback route in config/statamic/oauth.php.
5. Try to login using Github from CP or try logging in with {{ oauth:github }} from frontend.

## Extra Detail

<img width="1094" alt="Screen Shot 2020-09-08 at 20 46 32" src="https://user-images.githubusercontent.com/393595/92552970-b51cfe80-f216-11ea-95c6-39c96d5888e3.png">
<img width="1115" alt="Screen Shot 2020-09-08 at 20 46 42" src="https://user-images.githubusercontent.com/393595/92552980-b8b08580-f216-11ea-95e5-698629cbdc84.png">

## Environment

**Statamic version:** 3.0.0 Pro

**PHP version:** 7.3.21

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Good catch! That must have been missed out when the gents built out the oAuth functionality.
