### ISSUE TITLE
Click on display title doesn't show the handle anymore

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#2389]
## Bug Description
As usual you would be able to click on the display title for each field to display its handle. It no longer works.

## Environment

**Statamic version:** 3.0.7

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
It was removed for accessibility reasons unfortunately. The plan is for it to be brought back as a keyboard shortcut.

statamic/ideas#302

**Comment by ReneWeCode** [comment]
Ah! Haven't seen this. Thanks.
