### ISSUE TITLE
Static Cache not invalidated when entry or term deleted, or global updates

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2393]
## Bug Description

If you use static caching and you delete an entry or a term, they are not removed from the static cache. Cache is not invalidated when globals are changed either. 

## How to Reproduce

1. Enable static caching
2. Create an entry
3. confirm exists
4. delete entry
5. attempt to visit entry...it should fail but doesn't.

## Environment

**Statamic version:** 3.0.7

**Comment by robdekort** [comment]
Confirmed!

**Comment by robdekort** [comment]
Seems critical to me, I'll leave that up to core.

**Comment by mmorkt** [comment]
Got the same problem. The same goes for collection ordering. Changing order doesn't trigger a clear cache.

**Comment by robdekort** [comment]
Two clients on the phone wondering what they did wrong. It also doesn't seem to invalidate when you edit a navigation.

**Comment by robdekort** [comment]
I might be going out of line here, but I'm labeling this critical. This makes it hard to use caching in production.

**Comment by jasonvarga** [comment]
Entry and term URLs will be invalidated when you delete them in 3.0.14

I want to get a release out today and didn't have time to add the global and nav handling. They'll come later.

**Comment by robdekort** [comment]
Very nice Jason! Thanks.

**Comment by damcclean** [comment]
I've created a PR that implements the GlobalSet and Navigation part of this issue, #2639.

**Comment by robdekort** [comment]
Nice!
