### ISSUE TITLE
Date isn't updated in filename when revisions are enabled

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2397]
## Bug Description

When revisions are enabled, and you change a dated entry, the filename isn't updated with the new date.

## How to Reproduce

Enable revisions
Change the date of an entry.
Save the entry.
Publish the entry.
See the date has not changed.

## Extra details

Works fine without revisions enabled.

## Environment

**Statamic version:** 3.0.7

**Comment by riasvdv** [comment]
Our client just hit this, they're trying to schedule entries but the date isn't changing
