### ISSUE TITLE
CP collection listing can be broken if a user is deleted

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#2398]
## Bug Description
If you have a `users` field (e.g. `author`) and add it to your listing column for the collection, the listing will break if you delete a user that has been assigned to an entry.

You'll get a `Call to member function id() on null` error on the page.

## Environment

**Statamic version:** 3.0.7

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jetwes** [comment]
I have this behaviour on a complete fresh install. No user was deleted. If I click on collections I get this error

**Comment by damcclean** [comment]
What should happen instead if the user doesn't exist, should it just display as nothing?  I'm thinking about creating a bug fix for this.

**Comment by jackmcdade** [comment]
Yes it should just null out the author, and the next time the entry is saved it'll get removed from the data

**Comment by jackmcdade** [comment]
My guess is the answer lies in here: https://github.com/statamic/cms/blob/master/src/Fieldtypes/Users.php#L68-L77

But i've been wrong many times before 😂

**Comment by damcclean** [comment]
Sweet, I'll have a look over the weekend 😃

**Comment by damcclean** [comment]
Fixed in db9968c
