### ISSUE TITLE
`site:clear` uses old config defaults

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2399]
## Bug Description

If you create a new Statamic site, then run `php please site:clear` you will find it revert several config files (git, user, stache) back to old (pre release) versions.

## How to Reproduce

1. create Statamic site
2. commit site to git
3. run `php please clear:site`
4. Note the config file changes.

**Statamic version:** 3.0.7

**Comment by jasonvarga** [comment]
Duplicate of #1880

**Comment by jasonvarga** [comment]
I mean #2305
