### ISSUE TITLE
Scope variables still available without scope

### ISSUE THREAD

**Issue by davidwarrington** [statamic/cms#2406]
## Bug Description
Apologies if the title doesn't make much sense, I couldn't think of a better way to summarise it.

I have a blog post and towards the bottom I'm trying to list the 3 most recent posts, excluding the current post. The partial I'm using also has some settings being injected from an entry in a different collection. This causes the `id` variable on the template to be overwritten so I can't prevent the current article from appearing in the recent articles list.

```
{{ id | console_log }} <- prints the current article id, let's say "abcde".

{{
	collection:pages
	slug:is="blog"
	scope="blog"
}}
	{{ blog:id | console_log }} <- Let's say "12345". As expected.
	{{ id | console_log }} <- Also "12345", despite not using the "blog" scope?

	{{
		partial:components/recent-articles
		:heading="blog:recent_articles_heading"
		:description="blog:recent_articles_description"
	}}
{{ /collection:pages }}
```

## How to Reproduce
1. Create an entry in a collection, e.g "articles".
2. Add the following to the template for the entry you've just created, e.g.
	```
	<p>Entry ID: {{ id }}</p>
	{{ collection:pages scope="page" }}
		<p>Entry ID: {{ id }}</p>
		<p>Page ID: {{ page:id }}</p>
	{{ /collection:pages }}
	```
3. Check the template. You should see that the second "Entry ID" paragraph has the same ID as the "Page ID" paragraph.

## Environment

Statamic 3.0.7 Pro
Laravel 7.22.4
PHP 7.4.9
No addons installed

**Comment by jasonvarga** [comment]
The scope parameter adds a scope (copies the data into that key), it doesn't move it.

If you want to make sure you're getting the page id, you can explicitly use `{{ page:id }}`. (`page` contains everything for that url's entry)
