### ISSUE TITLE
Toggling list and tree mode for a collection in the cp doesn't show anything

### ISSUE THREAD

**Issue by r6203** [statamic/cms#2408]
## Bug Description

When viewing a collection in the control panel, toggling the view mode between list and tree mode (default), tree mode doesn't show anything.

## How to Reproduce

![statamic](https://user-images.githubusercontent.com/4466258/92993369-5646d600-f4f1-11ea-9eda-ef381270ac1a.gif)

## Environment

Statamic 3.0.7 Solo
Laravel 7.27.0
PHP 7.4.10
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I can confirm this bug report, it's happening for me too. I've added a screenshot below of what the Vue dev tools look like for the `PageTree` component. Seems like that `pages` property which is weird.

![image](https://user-images.githubusercontent.com/19637309/92994889-4ed5fb80-f4f6-11ea-90a7-16137e5c8500.png)

**Comment by robdekort** [comment]
Note: I was only able to recreate this on a fresh install. I can't recreate it somehow on an ongoing project. Neither in the pages or in another collection after making them orderable and expecting a root page.

**Comment by sjclark** [comment]
I've had this happen to on collections of various structures, refreshing the page resolves it. To be more specific its the act of **toggling** from List to Tree that is the bug.

![Screen Shot 2020-09-16 at 3 00 46 PM](https://user-images.githubusercontent.com/4531017/93294369-9c6fa280-f82d-11ea-93eb-f458a0437d64.png)
![Screen Shot 2020-09-16 at 3 00 40 PM](https://user-images.githubusercontent.com/4531017/93294372-9da0cf80-f82d-11ea-9fca-149ad6e106ef.png)
