### ISSUE TITLE
Ability to select which blueprints are usable when creating entries

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2419]
If you have a pages collection, you might have a blueprint that is only intended to be used on a single (or limited number of) entries, like a "home" or "contact" blueprint.

The blueprint needs to exist for it to work, but you don't want it to be an option in the "Create Entry" button.

We need a way to filter which blueprints are selectable in that button.

![image](https://user-images.githubusercontent.com/105211/93105704-64296200-f67d-11ea-9d41-2611d96cacff.png)

It should also work for creating child pages:

![image](https://user-images.githubusercontent.com/105211/93105609-48be5700-f67d-11ea-802b-b37afa6940a8.png)

**Statamic version:** 3.0.7

**Comment by MikeHarrison** [comment]
This is totally not my wheelhouse, but the first thing I tried when I hit the issue was popping an underscore on the filenames of the blueprints I wanted “hidden”. Is this anything?!

**Comment by jasonvarga** [comment]
That is not anything :)

**Comment by RobertCordes** [comment]
The underscore thing doesn’t work — unfortunately. I would also love to have this feature. Or is there a different, recommended way to handle this situation?

**Comment by jasonvarga** [comment]
There's no way to do it right now, that's why I opened the issue.

**Comment by RobertCordes** [comment]
Sorry, I just thought there might be like a recommended way to structure your site if you want this kind of functionality. It’s a pretty common requirement (to say the least) to have one-off pages, so I thought the Statamic team *must* have thought about this. I feel like there are many important things missing from the documentation so I was hoping this was one of those problems that were already solved, just not documented.

**Comment by MikeHarrison** [comment]
To clarify, that was the approach that seemed to make logical sense to me, coming from another CMS. Wasn't suggesting it should work, more that it was a possible approach that occured to me.

Will leave it with you guys - you are doing an awesome job :)

**Comment by MikeHarrison** [comment]
Hi guys,

I know you are super busy, but is there any news on an approach for this? It will be a bit of a sticking point with an upcoming client handover.

Thanks!

**Comment by jelleroorda** [comment]
@jasonvarga Our customer also brought this up; so I’m willing to try and contribute a fix for this. I’d love to have your view on the general idea of how you’d like to fix this (for example with the underscores mentioned?) before I whip up something unnecessary.

**Comment by jasonvarga** [comment]
I think being able to add `selectable: false` to the blueprint would be a good solution. Similar to how when you reorder the blueprints, an `order` key gets added to it.

**Comment by damcclean** [comment]
If I remember correctly, in v2 you could specify `hidden: true` on a fieldset (what is now a blueprint) and it would be hidden when creating new entries. Could it be worth using the same term (`hidden`) for v2 compatibility?

**Comment by jasonvarga** [comment]
It was `hide`. So yeah, we can do that.

I just don't love making `true` the negative state, if that makes sense. But I'm ok with either!
