### ISSUE TITLE
Multiple prefixed fieldsets get overwritten

### ISSUE THREAD

**Issue by RobertCordes** [statamic/cms#2420]
##  Bug Description
When including the same fieldset twice — each time with a different prefix — only one of them shows up. The first instance actually gets overwritten by the second one.

## How to Reproduce
1. Create a fieldset
2. Create a blueprint and link the fieldset with a prefix
3. Link the fieldset a second time with a different prefix
4. The second link will overwrite the first one in place
5. In total the fieldset will only be linked once

## Extra Detail
There are no error messages.

## Environment
Statamic 3.0.7 Pro
Laravel 7.25.0
PHP 7.4.2
statamic/seo-pro 2.0.11

**Statamic version:** 3.0.7

**PHP version:** 7.4

**Install method:** Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I'm unable to reproduce this issue on a fresh Statamic install. 

I created a fieldset with a field, imported it twice, each with a different prefix, into the same blueprint and it saved with the two prefixes, even if I check the blueprint's YAML file.

Could you double check if it's still buggy on a new statamic site?

**Comment by robdekort** [comment]
Same, looks like this works as expected:

<img width="673" alt="Screenshot 2020-09-15 at 10 15 34" src="https://user-images.githubusercontent.com/69107412/93184343-69011b00-f73c-11ea-8d96-2cf90850740f.png">

**Comment by RobertCordes** [comment]
Sorry, I was able to find out what was causing the error. I also had a different fieldset which included the `title` field. But it seems that isn’t actually *allowed* — when I removed that fieldset, the rest started working.

**Comment by robdekort** [comment]
Cool, all done :-)
