### ISSUE TITLE
Translation of "rename_asset_warning" is in the json-file instead of messages.php 

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2429]
- Generate a new translation from https://statamic.dev/cp-translations#contributing-a-new-translation
- `"rename_asset_warning": "",` will be in the new *.json file. It should be in the messages.php file as it is in en/messages.php I guess.

**Statamic version:** Clone from statamic/cms (around 3.0.7)

**Comment by damcclean** [comment]
That would make sense, it's included in the `en` version of `messages.php`.
