### ISSUE TITLE
Too many request every second when session timeout

### ISSUE THREAD

**Issue by tolawho** [statamic/cms#2430]
## Bug Description
Like as image below

![image](https://user-images.githubusercontent.com/12527881/93179933-9364cf80-f760-11ea-814a-6e1b62f709ef.png)

## Environment

**Statamic version:** 3.0.7

**PHP version:** 7.4

**Install method:** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
What's the problem?

**Comment by jasonvarga** [comment]
This is expected. It's checking to see if you've resumed your session. Maybe you logged back in in another browser tab. If you did, it'll close the modal so you can continue working.

The requests only happen while the browser tab is visible.

**Comment by tolawho** [comment]
Sorry for not describing it, this issue is not an error. but I want to improve here to avoid bandwidth wasting. Assuming there are thousands of "session-timeout", a lot of bandwidth will be lost.
