### ISSUE TITLE
Urgent / Dashboard: bad text description for new block Enable Pro Mode

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#2432]
## Bug Description
On 3.0.8 Pro
In the dashboard there is a new block "Enable Pro Mode"
The text block associated with this is the same as the text block associated with Create a Navigation
Same when visiting the CP in French after the latest translations

## Extra Detail

![Capture d’écran 2020-09-15 à 21 00 22](https://user-images.githubusercontent.com/1823359/93253024-967ab280-f796-11ea-926b-ef68844d8f5b.png)

## Environment

**Statamic version:** 3.0.8

**PHP version:** 7.4.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I've created a pull request to fix this issue.
