### ISSUE TITLE
Getting Started licensing summary

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#2437]
The new Enable Pro Mode summary is showing the wrong text in v3.0.8
<img width="958" alt="Screen Shot 2020-09-16 at 9 13 11 am" src="https://user-images.githubusercontent.com/414211/93274191-19365880-f7fd-11ea-9376-862b8c74d40d.png">

Statamic 3.0.8 Pro
Laravel 7.28.2
PHP 7.4.9
simonridley/tracking-code-manager dev-master
statamic/migrator dev-master
statamic/seo-pro 2.0.12
statamic/ssg 0.2.0

**Comment by jasonvarga** [comment]
Already fixed for next release. Thanks!

**Comment by mikemartin** [comment]
Just realized that too. Thanks.
