### ISSUE TITLE
[Multi-Site][Collections] "Separate route for each site" values are saved correctly, but not shown when form is reloaded

### ISSUE THREAD

**Issue by piljac1** [statamic/cms#2447]
### Expected Behavior

When re-accessing a collection's edit form on a multi-site setup, previously saved route values should show when the "Separate route for each site" radio is checked.

### Current Behavior

When re-accessing a collection's edit form on a multi-site setup, previously saved route values **are not shown** within their respective input when the "Separate route for each site" radio is checked.

## How to Reproduce

1. Create a new collection
2. Edit the collection configs and select "Separate route for each site"
3. Fill up related inputs
4. Save the form
5. Reload the form
6. Saved data is not shown within "Separate route for each site" related inputs (but changes are active behind the scene)

## Extra Detail

* Values are saved if inputs are filled and submitted
* Values are lost if switching the routing option to "Single route" and back to "Separate route for each site" (I don't know if this particular behavior is expected, but doesn't seem user friendly)

## Environment

* Statamic 3.0.8 Pro (multi-site)
* Laravel 7.28.1
* PHP 7.4.3
* No addons installed

**Install method:**  Fresh install from `statamic/statamic`

**Comment by riasvdv** [comment]
Having the same issue!

**Comment by afonic** [comment]
I can confirm this bug as well, it is pretty serious as when you save the collection again the routes get lost and stop working in the frontend.

**Comment by billmn** [comment]
Yeah, same here

**Comment by piljac1** [comment]
I'll try to make a PR that solves this issue sometime this week.

**Comment by billmn** [comment]
Keep the issue open 🤖😉

**Comment by grideca** [comment]
We're having the same issue here. Routes get saved to .yaml file but don't show up again in CP after a reload

**Comment by dschenk** [comment]
We're having the same issue!

**Comment by chmoose** [comment]
Having the same issue!

**Comment by espenlg** [comment]
Same thing here.

**Comment by verybigelephants** [comment]
is there a hotfix that i could paste into vendor? this really makes the backend look unprofessional for the clients
