### ISSUE TITLE
[Collections] Can't "Create & Link Item" when the collection's "Orderable" feature is active

### ISSUE THREAD

**Issue by piljac1** [statamic/cms#2448]
#### This is a two part bug
* First part will be refered as **1**
* Second part will be refered as **2**

### Expected Behavior

1. When in the **CREATE** form, the "Create & Link Item" link should not be visible/accessible of a collection, because it is not logical to create an item and link it to a not yet existing one.

2. When in the **EDIT** form, the "Create & Link Item" should redirect to a new item creation form and when that form is published, the new item should be linked to the edited item (item where "Create & Link Item" was clicked).

### Current Behavior

1. When in the **CREATE** form, the "Create & Link Item" link is visible/accessible and redirects to a new item create form, but when that said form is submitted, a 404 error is encountered and the new entry is not linked to another.

2. When in the **EDIT** form, the "Create & Link Item" link is visible/accessible and redirects to a new item create form, but when that said form is submitted, you get redirected to the listing and the new entry is not linked to the edited one.

## How to Reproduce

1. 
   1. Create a collection and in the configs, enable the "Orderable" feature (leaving all other ordering fields to default)
   1. Go to the default collection's listing
   1. Click on "Create Entry"
   1. Click on "Create & Link Item"
   1. In the newly opened form, fill up the required fields and click on "Save & Publish"
   1. The entry gets created and a 404 page is encountered
​
2. 
   1. Create a collection and enable the "Orderable" feature (leaving all other ordering fields to default)
   1. Go to the default collection's listing
   1. Create an entry
   1. In the collection's listing, click on the existing entry to edit it
   1. Click on "Create & Link Item"
   1. In the newly opened form, fill up the required fields and click on "Save & Publish"
   1. The entry gets created **but doesn't get linked to the edited entry" and a redirection to the listing is made

## Environment

* Statamic 3.0.8 Pro (multi-site)
* Laravel 7.28.1
* PHP 7.4.3
* No addons installed

**Install method:**  Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
This one is a little hard to grasp without reproducing but confirmed in 3.0.20 as well.

1. In my case I don't get a 404 but get returned to the homepage (frontend) with the following URL: http://test.test/cp/collections/orderable/entries/create/undefined

2. Same result.

Note: I assumed in testing with `Default collection's listing` you mean the listing of the just created ordered collection. And with the `Create & Link item` button you mean the default one listed under `Parent`.
