### ISSUE TITLE
Localized entries loosing origin on unpublish

### ISSUE THREAD

**Issue by MichaelGruberGizmocraft** [statamic/cms#2451]
## Bug Description
When a localized collection entry is unpublished via the collection overview, the entry is loosing the origin.

## How to Reproduce
You need a localizable collection where an localized entry originates from the main entry.
When switching to the secondary site in the collection overview, you have to select a localized entry via checkbox.
After unpublishing the selected entry, the entry lost the origin.

## Extra Detail
This does not apply if the entry is unpublished via it's detail page.

## Environment
Statamic 3.0.9 Pro
Laravel 7.28.2
PHP 7.4.9

**Comment by robdekort** [comment]
Ah, so that's it. Yes. I can confirm, the `origin:` and value get removed.

**Comment by robdekort** [comment]
I feel like a combination of these multisite issues causes way bigger problems. My site got in an unusable state this morning where entries that lost origin got impossible to delete and kept refreshing it's ID.

**Comment by damcclean** [comment]
Just run into this bug myself, also seemed to remove the title field as well. Just left with the ID.

**Comment by jasonvarga** [comment]
I can't reproduce the title being removed, @damcclean 
If you can reproduce that, please open a separate issue.
