### ISSUE TITLE
Modifier option_list can't be used with taxonomies (as in v2)

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#2455]
## Bug Description
In v2, you could use the modifier `option_list` with taxonomies in a post. This was really useful, because with this simple logic you could display related posts, based on the post taxonomies.

This worked perfectly fine in v2:

```
{{ collection:products url:isnt="{ url }" taxonomy:brand="{ brand|option_list }" taxonomy:category="{ category|option_list }" limit="2" }}
<a href="{{ url }}">{{ title }}</a>
{{ /collection:products }}
```

## How to Reproduce
1. Create some taxonomies ("brand" and "category")
2. Create some posts and connect them to one or more of the brand and category tags.
3. Use the above code in your post.html

## Environment

Statamic 3.0.9 Pro
Laravel 7.26.1
PHP 7.4.6
statamic/migrator dev-master
statamic/ssg 0.2.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Try `:taxonomy:brand="brand"`

**Comment by robdekort** [comment]
That does seem to work! Closing this one, feel free to reopen if that was too premature.

**Comment by axelferdinand** [comment]
`:taxonomy:brand="brand"` didn't work, I'm afraid

**Comment by axelferdinand** [comment]
Reopen this issue, please?

**Comment by jasonvarga** [comment]
You definitely prefixed it with a colon?

**Comment by axelferdinand** [comment]
I definitely didn't... My bad! Works like a charm! Thanks

**Comment by brendanfalkowski** [comment]
Thanks, this helped me out while migrating a Statamic 1 "related articles" section to Statamic 3.

I wasn't sure what the `:taxonomy:tags="tags"` syntax was called, but I dug around and found it: dynamic binding.

https://statamic.dev/antlers#variables-inside-tag-parameters
