### ISSUE TITLE
Broken Conditional with Statamic Upgrade from 3.0.8 to 3.0.9

### ISSUE THREAD

**Issue by LloydThinks** [statamic/cms#2456]
## Bug Description
Upgrade from 3.0.8 to 3.0.9 breaks working code. In particular, it breaks an Antlers If statement:
```Antlers
{{ if "test" !== "test" and publication_venue:first_year }}
    Broken
{{ /if }}
```
where `publication_venue` is a linked entry from another collection and `first_year` is an Integer.

Of course, in my case, `"test" !== "test"` was a useful bit of code, but I have narrowed it down to this example. I cannot narrow down the second half of the condition with my current knowledge of Statamic.

## How to Reproduce

1. Create a collection A with an Integer fieldtype
1. Create one entry in that collection with an integer in that fieldtype (a four-digit year if you like)
1. Create a different collection B with an Entries fieldtype that links to collection A
1. Create one entry in collection B
1. Write the above Antlers code in an Antlers html file.
1. Run the above code

## Extra Detail
Here is the error I am getting:
```
Statamic\View\Antlers\SyntaxError
syntax error, unexpected 'flex' (T_STRING) on line 47 of: <li x-data="{detailsOpen:false}" class="mb-2"> <!-- Publication Header --> <div> <div class="block focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out"> <div class="px-2"> <div class="flex items-center justify-between"> <div class="text-sm leading-5 font-medium"> {{ title }} </div> <?php if (false): ?> <div class="ml-2 flex-shrink-0 flex"> <span class="inline-flex items-center px-3 py-0.5 rounded-full 
```

## Environment

Statamic 3.0.9 Solo
Laravel 6.18.35
PHP 7.4.9
statamic/ssg dev-master

**Comment by jasonvarga** [comment]
Thanks for pointing this out.

Are you able to share your actual condition? Obviously `"test" == "test"` isn't what you're really doing, and comparing two literals doesn't make sense.

If you're doing `"string" == variable`, I noticed that swapping it around to `variable == "string"` works. You can use that as a workaround for now.

**Comment by LloydThinks** [comment]
Hi @jasonvarga yes absoluately:
```Antlers
{{ if publication_venue:publication_venue_types:slug !== "journal" and publication_venue:first_year }}
  Broken
{{ /if }}
```

Switching the order to:
```Antlers
{{ if "journal" !== publication_venue:publication_venue_types:slug and publication_venue:first_year }}
  Broken
{{ /if }}
```
did not fix the error. Now I get a new error:

```
Statamic\View\Antlers\SyntaxError
syntax error, unexpected '{' on line 41 of: <li x-data="{detailsOpen:false}" class="mb-2"> <!-- Publication Header --> <div> <div class="block focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out"> <div class="px-2"> <div class="flex items-center justify-between"> <div class="text-sm leading-5 font-medium"> {{ title }} </div> <?php if (false): ?> <div class="ml-2 flex-shrink-0 flex"> <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-
```

Lloyd

**Comment by jasonvarga** [comment]
Thank you Lloyd, this is helpful.

**Comment by jasonvarga** [comment]
Should be fixed in 3.0.10

**Comment by LloydThinks** [comment]
It is not fixed in 3.0.10. Upgrading breaks my site. Deleting this portion of code makes my site work again:
```Alpine
{{ if publication_venue:publication_venue_types:slug !== "journal" and publication_venue:first_year }}
  {{ publication_year subtract="{{publication_venue:first_year}}" add="1" number_suffix="" }}
{{ /if }}
```

Lloyd

**Comment by LloydThinks** [comment]
For those that may run into this issue, I have resolved the issue by separating out the individual conditions into two separate nested {{ if }} statements. I still believe my original conceptualisation is okay, but not able to be parsed.

**Comment by damcclean** [comment]
Related to either #2614 or #2537.
