### ISSUE TITLE
Can't send emails with PHP Mail

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#2457]
## Bug Description
In v2, Statamic could send email notifications after form submission using PHP Mail. In v3, you apparently need to use a third party email provider.

```Swift_TransportException
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
 "
```

## How to Reproduce
Try submitting any form without touching the email settings.

## Environment
Statamic 3.0.9 Pro
Laravel 7.26.1
PHP 7.4.6
statamic/migrator dev-master
statamic/ssg 0.2.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Please show your `config/mail.php` and variables in your `.env` file starting with `MAIL_`

**Comment by edalzell** [comment]
FYI, this was resolved on Discord. Incorrect settings in `mail.php`

**Comment by axelferdinand** [comment]
Just wondering – in v3, can you use PHP Mail as in v2? Couldn't find out how.

**Comment by damcclean** [comment]
As Statamic 3 is a Laravel package, you can do it the same way as you would on any other Laravel app. 

Here's a few resources I could find that might be useful:

- https://github.com/jauharibill/phpmailer-laravel5
- https://blog.mailtrap.io/phpmailer/
- https://laravel.com/docs/8.x/mail

Personally I'd prefer to use a mail service like Sendgrid or Mailgun to send emails as they're more reliable and will have a higher reputation than most VPS servers.

**Comment by axelferdinand** [comment]
Thanks!

**Comment by axelferdinand** [comment]
@damcclean Just wanted to let you know that I'm up and running with PHP Mailer and Sendmail approach in less than 5 minutes. Thank you so much!!
