### ISSUE TITLE
sentence_list not translated

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2463]
## Bug Description
If you use the sentence_list modifier, the "and" is not translated.

## How to Reproduce
{{ list | sentence_list }}
Output: item1, item2**, and** item3
Should be: item1, item2 **und** item3

## Environment

**Statamic version:** 3.0.9

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
It might be nice if you can pass a localisable string in there. Something like this:
`{{ list | sentence_list:trans_file.key }}`

**Comment by ebeauchamps** [comment]
Shouldn't it rather be somewhat automatic based on the locale in use for the list items?

**Comment by robdekort** [comment]
Even better.

**Comment by jasonvarga** [comment]
FYI the argument is the glue.

```
{{ list | sentence_list:et }}
```
```
one, two, et three
```

**Comment by ebeauchamps** [comment]
That was fast!

**Comment by Pfeifakopf** [comment]
Thanks for the fast fix @jasonvarga !

If someone doesn't need the the Oxford Comma, you can remove it with `{{ list | sentence_list:und:0 }}`.
I think this should be added to the docs.
https://statamic.dev/modifiers/sentence_list#content

**Comment by jasonvarga** [comment]
I agree, but you should use the oxford comma! 😄

**Comment by Pfeifakopf** [comment]
In Germany it's allowed, but reeeaaallly not common. The most people would mark it as error.

**Comment by ebeauchamps** [comment]
So funny. And in France you should not use any kind of comma when it's located just before "et".
So It should be ```one, two et three```.....
I guess I cannot ask for that, can I?
