### ISSUE TITLE
Updating a search index shouldn't delete it

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#2464]
## Bug Description
When you run `php please search:update` it deletes the index, this is not a problem in the local driver, but with Algolia you lose all your faceting and search settings.

A better solution would be to flush/clear the index.

## How to Reproduce

- Have a search index in Algolia
- Set some faceting / search / ranking settings
- Watch `php please search:update` remove all your hard work

## Environment

Statamic 3.0.9 Pro
Laravel 7.28.1
PHP 7.4.8

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
Ah nice one
