### ISSUE TITLE
Searching Assets Broken

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#2465]
Just updated to 3.0.9.

1. Create assets:

`content/assets/assets.yaml`:
```
title: Assets
disk: assets
```

2. Add some images to container.
3. Search the assets using the search bar.
4. See no change in listing and following error in console:

![image](https://user-images.githubusercontent.com/3776888/93598982-5ba29580-f9b5-11ea-8f6b-b1f599743404.png)

**Comment by damcclean** [comment]
Are you using Grid view or List view in the asset browser?

**Comment by johncarter-** [comment]
Grid.

List works actually.

**Comment by damcclean** [comment]
Sweet. This bug has already been fixed and will be included in the next release, #2442.

Good catch though!
