### ISSUE TITLE
Table data replicating on initial load + other weirdness

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#2470]
##  Bug Description
When initially inputting data into a table, the rows are replicating content. When creating columns after entering data, right side of table breaks.

## How to Reproduce
This appears to affect a normal table fieldtype and a table nested inside a Bard field.

## Extra Detail
![table](https://user-images.githubusercontent.com/2514935/93639628-f2278480-f9be-11ea-8806-9e48bcb2f5eb.gif)

## Environment
Statamic 3.0.10 Pro
Laravel 6.18.40
PHP 7.2.33
aryehraber/statamic-captcha 1.0.3
encore/app dev-master
encore/location dev-master
spatie/statamic-responsive-images 1.2.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
![](https://i.giphy.com/media/fdRLQ2ApeAYkaXqXML/giphy.webp)
