### ISSUE TITLE
[Collections] Impossible to delete entries with nested children

### ISSUE THREAD

**Issue by piljac1** [statamic/cms#2477]
## Bug Description

**Here are multiple cases:**
1. When deleting an entry with children, nothing gets deleted (not the entry itself, nor its children);
2. When individually deleting a child/parent/grandparent before saving changes, only the child gets deleted;
3. When deleting multiple sets of child/parent/grandparent before saving changes, only the bottommost children set gets deleted;

There are possibly more cases, but I listed those I encountered.

### 1st case
![First case](https://i.imgur.com/GEelbsA.gif)

### 2nd case
![Second case](https://i.imgur.com/7JJmV3V.gif)

### 3rd case
![Third case](https://i.imgur.com/CMRUjUT.gif)

## Extra Detail
The behavior is also messed up using the list view.

## Environment

* Statamic 3.0.8 Pro (multi-site)
* Laravel 7.28.1
* PHP 7.4.3
* No addons installed

**Install method:**  Fresh install from `statamic/statamic`

**Comment by piljac1** [comment]
I haven't touched to Statamic in over a month, but I've read release notes and it seems like it has not been fixed.

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
