### ISSUE TITLE
Taxonomies field if empty not working 

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2478]
## Bug Description
I can select the terms of taxonomy list in my collection entry.

![image](https://user-images.githubusercontent.com/3351449/93689742-af0a0600-fad1-11ea-90bc-034d7a537aef.png)
![image](https://user-images.githubusercontent.com/3351449/93689753-bdf0b880-fad1-11ea-995a-824381e74def.png)

If I don't choose terms in my taxonomy field, the `{{ if gruppen_und_kreise }}` check fails and shows the content inside the condition. The dump output is an empty array.

```
{{ gruppen_und_kreise | dump }}
```
```
Statamic\Taxonomies\TermCollection {#2855 ▼
  #items: []
}
```

## How to Reproduce
```
{{ if gruppen_und_kreise }}
```

## Environment

**Statamic version:** 3.0.10

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
@Pfeifakopf How would you expect this to behave? 

I would have thought that if you don't select any terms it should be empty because there's nothing to be in there. Maybe I'm misunderstanding this?

**Comment by jasonvarga** [comment]
I think when he said the condition 'fails', he means 'it worked incorrectly'. Meaning it evaluated to `true` and showed the contents. Empty arrays should be considered falsey.

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
