### ISSUE TITLE
[Blueprints] Impossible to have a blueprint without a "title" handle

### ISSUE THREAD

**Issue by piljac1** [statamic/cms#2479]
## Bug Description

It is impossible to have a blueprint without a "title"  handle. I know it is probably a business rule, but if it is, the UI/UX is misleading.

Why ?

* It is possible to rename the "title" handle
* It is possible to delete the "Title" field (which contain the "title" handle)

If the blueprint's form is reloaded after the "title" handle has either been deleted or renamed, a new "Title" field is added on top.

## How to Reproduce

For the first case, rename the "title" handle to whatever you want and save changes.

For the second case, delete the "Title" field completely ans save changes.

In both cases, "Title" will be back on form reload.

## Environment

* Statamic 3.0.8 Pro (multi-site)
* Laravel 7.28.1
* PHP 7.4.3
* No addons installed

**Install method:**  Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Confirmed. This issue could be related to #2173.

**Comment by jasonvarga** [comment]
A title field is required at the moment as it's assumed in a bunch of places throughout Statamic. Keep an eye on https://github.com/statamic/ideas/issues/78
