### ISSUE TITLE
[Blueprints] Dragging an element to another section doubles field forms

### ISSUE THREAD

**Issue by piljac1** [statamic/cms#2480]
## Bug Description

In a blueprint, when moving a field from a section to another, it doubles the form when editing the moved item. One edit form is the clicked field's one and the other edit form is another field in the section.

## How to Reproduce

![Form doubling](https://i.imgur.com/YIulBtK.gif)

## Extra Detail

It doesn't seem to happen "all the time". In my case, it happened when moving pretty much any field to any section.

The only exception (where no form doubling is caused), is when moving the "Short biography" Bard field to the "Biography" section.

## Environment

* Statamic 3.0.8 Pro (multi-site)
* Laravel 7.28.1
* PHP 7.4.3
* No addons installed

**Install method:**  Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
I can't recreate this. Does it still happen for you? What browser are you using?

**Comment by piljac1** [comment]
@jasonvarga I'm using Chrome. I'll try to recreate it this evening.

**Comment by piljac1** [comment]
@jasonvarga I upgraded to 3.0.14 to rule out the version and it is still happening. In the "Pages" collection, simply move the "Title" field on top of the "slug" field (in the "Sidebar" section) and click on the "Title" field to edit it.

Setup:

Statamic 3.0.14 Pro (multi-site)
Laravel 7.28.1
PHP 7.4.3
No addons installed
