### ISSUE TITLE
Taxonomy Routes error when "statamic.protect.default" is null

### ISSUE THREAD

**Issue by Illizian** [statamic/cms#2481]
## Bug Description

Configuring Taxonomic Routes as described [here](https://statamic.dev/taxonomies#routing) results in broken views that throw an exception.

## How to Reproduce

- Create `content/taxonomies/tags.yaml` with the following content
```yaml
title: Tags
```
- Create `content/taxonomies/tags/test.yaml` with the following content
```yaml
title: Test
```
- Create `resources/views/tags/index.antlers.html` with the following content
```html
<h1>tags/index.antlers.html</h1>
```
- Visit http://\<server-ip\>/tags
- You will see the error in "Extra Detail" below

If you now update the config value `"statamic.protect.default"` from `null` to `false`, then the null coalesce will never fall through rendering all content "un-protectable" but, will allow these routes to render without issue.

## Extra Detail

```
Call to undefined method Statamic\\Taxonomies\\Taxonomy::value() at /var/www/vendor/laravel/framework/src/Illuminate/Support/Optional.php:127)
[stacktrace]
#0 /var/www/vendor/statamic/cms/src/Auth/Protect/Protection.php(32): Illuminate\\Support\\Optional->__call('value', Array)
#1 /var/www/vendor/statamic/cms/src/Auth/Protect/Protection.php(37): Statamic\\Auth\\Protect\\Protection->scheme()
#2 /var/www/vendor/statamic/cms/src/Auth/Protect/Protection.php(53): Statamic\\Auth\\Protect\\Protection->driver()
#3 /var/www/vendor/statamic/cms/src/Http/Responses/DataResponse.php(104): Statamic\\Auth\\Protect\\Protection->protect()
#4 /var/www/vendor/statamic/cms/src/Http/Responses/DataResponse.php(36): Statamic\\Http\\Responses\\DataResponse->protect()
#5 /var/www/vendor/statamic/cms/src/Taxonomies/Taxonomy.php(266): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#6 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(744): Statamic\\Taxonomies\\Taxonomy->toResponse(Object(Illuminate\\Http\\Request))
```

## Environment

**Statamic** 3.0.10 Solo
**Laravel** 7.28.3
**PHP** 7.4.5

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Looks like this issue has already been sorted for the next release. There was a previous issue, #2472. It's fixed in a706eb2.
