### ISSUE TITLE
SVG not displayed in asset editor modal

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2484]
## Bug Description

_via support request_

In the control panel, when I upload a SVG file (let's say https://upload.wikimedia.org/wikipedia/commons/6/67/Firefox_Logo%2C_2017.svg) to a container and then click on it on the list to display it "full-size", the popup opens but the image is not displayed (filename, size, last modified etc are displayed properly, but only a black background where the image should be). The thumbnail is displayed properly in the list of assets.

**Statamic version:** 3.0.10

**Comment by robdekort** [comment]
This has been the case in v2 as well, can't believe this never got reported before :-).
It seems that if you add SVG to the array in `src/Assets/Asset.php` on line 321 fixes this issue. But this might have security implications somewhere else. You know best.
