### ISSUE TITLE
Code field becomes read-only when attached to grid in stacked mode.

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2489]
## Bug Description
It only happen when the grid field type is set to stacked mode. If i set it to table it works. But in stacked mode, the code field becomes read only.

## Extra Detail

![image](https://user-images.githubusercontent.com/31292231/93813013-b99fd900-fc52-11ea-9d38-922caf5a6e88.png)

## Environment

**Statamic version:** 3.0.10

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by Pixney-William** [comment]
Its a multisite. And i have the field set to localizable true.

**Comment by jasonvarga** [comment]
Is the actual grid field marked as localizable?

**Comment by Pixney-William** [comment]
Nah.. my stupid false.. had to localize that too.
