### ISSUE TITLE
Renaming entry slug by renaming file causes cache-related errors

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#2492]
## Bug Description
- If I change an entry slug by renaming the file for that entry, the first load of the site after that results in an `Illegal string offset ‘entry’` error at `vendor/statamic/cms/src/Structures/Tree.php:267`.
- Subsequent reloads result in a different error, `Call to a member function id() on null` at `vendor/statamic/cms/src/Stache/Stores/Store.php:78`.
- Clearing the cache via `php please cache:clear` or `php artisan cache:clear` solves the problem.
- Clearing stache via `php please stache:clear` doesn’t work because it results in the same error.

## Extra Detail
I poked around looking for this issue assuming it already existed, but I didn’t find anything. It could possibly be related to #1148 or #136 (which is already closed), but I wouldn’t know.

## Environment
Statamic 3.0.10 Pro
Laravel 7.28.2
PHP 7.3.17
statamic/seo-pro 2.0.13
Fresh install from `statamic/statamic`, migrated from v2 with official plugin.

**Comment by damcclean** [comment]
Just re-created this issue. Only happens for entries that are linked in a navigation. Doesn't seem to affect other ones.
