### ISSUE TITLE
Error with multiple sites using redis on same vps

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#2499]
## Bug Description
If you set redis as cache driver on the same vps, there is shown an error. When you clear the cache, the error is gone on the cleared site, but the others showing now the error.
This still happens, when you set for each site a  different REDIS_DB number.

## Extra Detail
Error
```
Error
Call to a member function hasStructure() on null
```

## Environment

**Statamic version:** 3.0.11

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Have you tried changing the Redis cache prefix in your `config/cache.php` file?

**Comment by Pfeifakopf** [comment]
@damcclean Where I can do this?
```
        'redis' => [
            'driver' => 'redis',
            'connection' => 'cache',
        ],
```

**Comment by damcclean** [comment]
From what I can remember, it's at the bottom of the file.
