### ISSUE TITLE
Orderable broke sometime betwee 3.0.6 and 3.0.12

### ISSUE THREAD

**Issue by ryanAbbott** [statamic/cms#2501]
## Bug Description
Setting orderable on a new collection doesn't work. It appears to in the control panel but it doesn't affect the order on the front end. Existing collections with orderable set still work fine until orderable is turned off and back on in the collection's settings.

## How to Reproduce
Create a new collection, turn on orderable and pull collection up on the front end using the collection tag. For an existing collection that was working turn it off and back on.

## Environment

**Statamic version:** 3.0.12

**PHP version:** 7.4.10

**Install method (choose one):**
- Fresh install from `statamic/statamic` from several weeks ago

**Comment by ryanAbbott** [comment]
I figured this out. Orderable only works if max depth is set to 1. Leaving it blank or to anything else prohibits ordering. 

Leaving this open in case it isn't the intended behavior.

**Comment by edalzell** [comment]
That's intended
