### ISSUE TITLE
Modifier doesn't accept parameter

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2505]
## Bug Description
I'm trying to pass `{{ site:short_locale }}` as a parameter to a custom modifier. Is this even supposed to work?

The modifier `$params` in this example is `null`:
```html
{{ title :translate="site:short_locale" }}
```

The modifier `$params` in this example is `{site:short_locale}`:
```html
{{ title translate="{site:short_locale}" }}
```

## How to Reproduce
Create a modifier and try to pass the parameter like in the example above.

## Environment

Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.9
aerni/translator dev-feature/statamic-v3

**Comment by jasonvarga** [comment]
The `:` prefix only works for tags, not modifiers.

In a modifier we'd manually see if the value (ie. the string `"site:short_locale"`) exists in the context, and if not we fall back the literal.

However this is pretty inconsistent, so maybe it should just work like you're expecting.

**Comment by aerni** [comment]
That'd be a great enhancement. 

## Summary

I'm expecting variables to parse before they are passed to the modifier. The same way it already works with tags.

## Example

Modifier syntax: 
```html
{{ title :translate="site:short_locale" }}

or

{{ title translate="{site:short_locale}" }}
```

`site:short_locale` should parse to `en`. This is in `config/sites.php`:

```php
'sites' => [

  'default' => [
    'name' => 'English',
    'locale' => 'en_US',
    'url' => '/',
  ],

]
```

**Comment by aerni** [comment]
Still a great enhancement idea.
