### ISSUE TITLE
related content is not fetched localized

### ISSUE THREAD

**Issue by el-schneider** [statamic/cms#2507]
## Bug Description
Content that is fetched via a [relationship](https://statamic.dev/relationships) tag is not localized 

## How to Reproduce
Example project: https://github.com/el-schneider/statamicRelationshipTest

1. Go to _/events_ route
2. Switch language with the language switcher in the top right corner
3. The content of the `event` is changing to its localized version while the content of the `artist` is not

## Extra Detail
The `event` _Brunch with Bridget_ has the related `artist` _Bridget_
The routes _/artists/bridget_ and _/de/artists/bridget_ show the translated content

## Environment

**Statamic** 3.0.12 Pro
**Laravel** 7.28.3
**PHP** 7.4.9

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by el-schneider** [comment]
Had anyone the chance to look into this? I'm building a site for a festival that'll take place in november and I'm pretty much done, but this functionality is core to the site and when i was starting building i was pretty confident, that basic v2 functionality will work soon enough so i went with v3. I'm starting to get a bit nervous right now.

**Comment by robdekort** [comment]
Hey @el-schneider yeah, @jasonvarga told me he'd look into this together with another multisite issue. :-)

**Comment by el-schneider** [comment]
Great news! Right in time to save my ass.

**Comment by robdekort** [comment]
Ha yeah. I'm in the _exact_ same boat. My ass needs saving.

**Comment by Hesesses** [comment]
Count me in also 👍

**Comment by philipboomy** [comment]
A V2 site broke completely today when client was re-ordering pages so I have stated to upgrade this to V3 however its a multilingual site so a fix for this would be appreciated

**Comment by robdekort** [comment]
Fantastic news. Tested and ass is saved. Thanks Jason!

**Comment by el-schneider** [comment]
Awesome, thanks!
