### ISSUE TITLE
Revision Group Day doesn't respect the Moment Locale

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2508]
## Bug Description

…Labels in the History
- UNPUBLISH
- PUBLISH
- REVISION

…and the date format is not yet localized (bold title, 'September 18, 2020' in the screenshot). Same problem as in #2053.

<img width="420" alt="Bildschirmfoto_2020-09-19_um_00 59 17" src="https://user-images.githubusercontent.com/8265902/94006573-53c16780-fda0-11ea-8826-570d782b57a3.png">

## Environment

Statamic 3.1.1 Pro
Laravel 8.34.0
PHP 7.4.16

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by helloDanuk** [comment]
💨🤖

**Comment by jasonvarga** [comment]
The dates seem to be translated fine.

![image](https://user-images.githubusercontent.com/105211/118726098-d3ec7f80-b7fe-11eb-9a1f-332b28592a32.png)

**Comment by helloDanuk** [comment]
The format in german is different. It should be:

17. Mai 2021



Am 18.05.2021 um 23:31 schrieb Jason Varga ***@***.***>:

﻿
The dates seem to be translated fine.

**Comment by jasonvarga** [comment]
It still says Mai though, not May.

**Comment by jasonvarga** [comment]
Nevermind, I was able to get it to work how you're expecting. 👍

**Comment by helloDanuk** [comment]
Yup, it was a bit unclear, sorry. The translation were fine, the issue was only the format. Thanks!
