### ISSUE TITLE
Reset Password Page → Translations are not yet possible for the error messages

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2512]
## Bug Description
The red validation error messages are not yet possible to translate.

<img width="362" alt="Bildschirmfoto_2020-09-18_um_23 44 44" src="https://user-images.githubusercontent.com/8265902/94008708-bc5e1380-fda3-11ea-8f4a-1cb02a4d08cd.png">
<img width="368" alt="Bildschirmfoto_2020-09-18_um_23 45 04" src="https://user-images.githubusercontent.com/8265902/94008726-c3852180-fda3-11ea-95ed-cf845cf0e058.png">
<img width="345" alt="Bildschirmfoto_2020-09-18_um_23 54 55" src="https://user-images.githubusercontent.com/8265902/94008739-c7b13f00-fda3-11ea-8b64-22fe48d80fe0.png">

## Environment

Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by billmn** [comment]
To translate Laravel messages (validation errors, ...) you must add translated files in `resources/lang/{your-locale}` folder.

Here you can find translated message for a lot of languages: https://github.com/Laravel-Lang/lang

**Comment by helloDanuk** [comment]
Thanks for this hint. A fresh statamic installation contains already a `resources/lang/en` folder and I can add an other language. But the handling of the variable :attribute in the strings is still unclear for me.

Use case:

- `en` → 'string' => 'The :attribute must be at least :min characters.',
- `de` → 'string'  => ':attribute muss mindestens :min Zeichen lang sein.',

To get a grammar correct sentence in german the word in ':attribute' must be capitalized and the word 'The' could have different translation, depending on grammatical gender of the word for :attribute. For german it should be:
- '**Das Passwort** muss mindestens :min Zeichen lang sein.' …instead of… 
- '**password** muss mindestens :min Zeichen lang sein.'

This is just an example use case, there are similar problems for 'The :attribute confirmation does not match.'

Questions:
- Which strings in `validation.php` are used in statamic? 
- Are there different use cases for them or could I hardcode the word for :attribute? But that does not seem to me to be the right way.

**Comment by helloDanuk** [comment]
I just saw that the `validation-inline.php` https://github.com/Laravel-Lang/lang/issues/1268 might be a solution. The :attribute is changed to a more generic translation. For the use case above this would be:

- 'string'  => 'Die Zeichenkette muss mindestens :min Zeichen lang sein.', 

The word 'password' is changed to the more generic word 'Zeichenkette'.

Still it would be good to know, where these Laravel messages (validation errors, ...) are used throughout the statamic eco-system? If translation files for them can added with a fresh installation or if the docs needs a section on how to add these files after installation?

**Comment by helloDanuk** [comment]
💨🤖

**Comment by duncanmcclean** [comment]
Like @billmn said, these translations aren't handled by Statamic's translations but by the default Laravel ones that ship with your app. (as Statamic uses the same authentication under the hood as Laravel and therefore shares the error messages).

I've had a quick look but it doesn't look like there's official Laravel translations for authentication and basic validation. However, I've found this [community repository](https://github.com/Laravel-Lang/lang/tree/master/src) which could be helpful. You should be able to copy in the relevant translation files for your app.

I do agree though that maybe this could be documented as it would be weird for the rest of the Statamic CP to be translated but not for the authentication stuff to be. Maybe this issue belongs inside the `statamic/docs` issue instead?

**Comment by helloDanuk** [comment]
Thanks for pointing this out again. I agree, it might be something for the docs. So I close this issue here.
