### ISSUE TITLE
There is no {{ sites }} tag to loop over sites

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#2513]
## Bug Description

A `{{ sites }}` tag does not exist.

**Comment by eldor** [comment]
Agree with @riasvdv we need the `{{ sites }}`available in antlers templates to switch between multiple sites.

**Comment by riasvdv** [comment]
`{{ locales }}` seems to return sites data, but only the sites that the current entry is available & published in. There should be a way to get **all** sites

**Comment by jasonvarga** [comment]
A bit ugly, but you can do this:


```
{{ foreach:config:statamic:sites:sites as="handle|site" }}
    {{ handle }} {{ site:name }} {{ site:locale }} {{ site:url }} <br>
{{ /foreach:config:statamic:sites:sites }}
```

```
<?php
return [
    'sites' => [
        'default' => [
            'name' => 'English',
            'locale' => 'en_US',
            'url' => '/',
        ],
        'french' => [
            'name' => 'French',
            'locale' => 'fr_FR',
            'url' => '/french/',
        ],
    ]
],
```

```
english English en_US /
french French fr_FR /french/
```

**Comment by eldor** [comment]
Hi @jasonvarga, yes that is working, but as you wrote your self, its a but ugly, but will do for now.

**Comment by robdekort** [comment]
Tampering with this. With that workaround you can't get the localised url for the current entry _if_ it's their right?

**Comment by robdekort** [comment]
Haha ok. I've got two locales on this site. So I always want to show a link to the localised url for the current entry. If the entry is not localised the `{{ locales }}` wouldn't show anything and I do need to signal the visitor that there are localised pages. It's horrible but I settled for this if anyone needs it:

```
{{ locales }}
    {{ unless locale.key == current }}
        <li class="flex justify-end flex-1 md:pr-2 lg:pr-6 xl:pr-8">
            <a class="h-full flex items-end border-t-4 border-transparent leading-none text-xs font-bold uppercase text-neutral hover:text-primary" href="{{ url }}">{{ locale.key }}</a>
        </li>
    {{ /unless }}
    {{ if total_results == 1 }}
        {{ foreach:config:statamic:sites:sites as="handle|site" }}
            {{ unless locale.key == handle }}
                <li class="flex justify-end flex-1 md:pr-2 lg:pr-6 xl:pr-8">
                    <a class="h-full flex items-end border-t-4 border-transparent leading-none text-xs font-bold uppercase text-neutral hover:text-primary" href="{{ site:url }}">{{ handle }}</a>
                </li>
            {{ /unless }}
        {{ /foreach:config:statamic:sites:sites }}
    {{ /if }}
{{ /locales }}
```

**Comment by robdekort** [comment]
Oh nice Jason 👍

**Comment by verybigelephants** [comment]
can we get some docs on this? 
i just found this when dealing with this problem by accident and there is no entry "sites" in the documentation https://statamic.dev/tags/sites

**Comment by jasonvarga** [comment]
Docs: https://statamic.dev/variables/sites
