### ISSUE TITLE
Parent Field > Choose entry: Translation is not yet possible for "Selected" at the bottom

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2514]
## Bug Description
The Word "Selected" at the bottom is not yet possible to translate. This UI pattern might also be used in other parts of the CP. But I do not have a complete overview. For the fieldtype taxonomy-term the translation is already done. 

<img width="486" alt="Bildschirmfoto_2020-09-19_um_00 29 22" src="https://user-images.githubusercontent.com/8265902/94009258-81101480-fda4-11ea-8a58-cf08e5f79069.png">

## Environment

Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ebeauchamps** [comment]
I wonder if ":count selected" (this is available in language file such as fr.json or de.json) is in use in this view

**Comment by helloDanuk** [comment]
💨🤖
