### ISSUE TITLE
Default Blueprints → Translations for a few fieldtitles are not yet possible

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2519]
## Bug Description

The fieldtitles in the default blueprints after a fresh Statamic installation have mixed translations:
1. Some of the labels are already translated.
2. Some can be added manually in the language *.json file, but do not generate automatically when running `php translator generate xy`.
3. Some are currently not at all translatable via the language files.

### Default entry blueprint 
- "Content" (3)
- "Author" (3)
- "Parent" field in the sidebar (2)
- "Sidebar" (2), when the screen size is too narrow to place the sidebar on the right and always in live preview). "Main" on the other hand is already generated in the json-file when adding a new translation.

<img width="999" alt="Bildschirmfoto_2020-09-19_um_00 50 03" src="https://user-images.githubusercontent.com/8265902/94015065-a99c0c80-fdac-11ea-9f39-2ed050deb7d8.png">

### Default user blueprint
- "Email Address" (3)
- I can't say about "Name" and "Avatar" because these are the same words in german.

<img width="947" alt="Bildschirmfoto_2020-09-19_um_00 42 46" src="https://user-images.githubusercontent.com/8265902/94015080-ad2f9380-fdac-11ea-827e-a8dd7de1e01a.png">

Although I can manually edit all titles in the blueprint itself, it would be good to have them translated form the beginning. A first time Statamic user might feel uncomfy when the blueprints have fields with english text in a translated CP. And second if i.e. I create a taxonomy, the default blueprint shows already the translation for the word "Content" when creating a new term. It should be done the same everywhere I guess.

_I opened separate issue for each translation issue I found in the last hour. This is the last one. I don't have any further open translations left for now. Thanks for all the work you put into it the last few days!_

## Environment

Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ebeauchamps** [comment]
In my view, the Default User Blueprint is just that, a Default Blueprint and you can definitely modify it to put German labels as you would if you wanted to create your own User Blueprint.  I guess it's the same for the Default Entry Blueprint. If you start fresh, you won't have that Blueprint available. I am not sure I would have open those as issues then.

**Comment by helloDanuk** [comment]
I see your point. For me I am fine with your opinion. I create my own blueprints with german labels anyway.

My concern are: 
- If you install Statamic for the first time, change the locale and take a look around the CP, you get english text when edit a page/entry. You probably change the locale first, before you edit or create a new blueprint, if you are using Statamic for the first time.
- At the moment, it's a translation mixmax: if you omit those you could translate manually by inserting them yourself in the json file, you still have some others translated (titles, roles, groups...). Maybe because these translations are already used elsewhere in the CP?

@gentlemen: Feel free to close this issue, if it is not important for you.

**Comment by jasonvarga** [comment]
I think it's important, but it already exists over here: https://github.com/statamic/ideas/issues/50

**Comment by helloDanuk** [comment]
I forgot to double check the ideas-repo as well. Sorry for that.
