### ISSUE TITLE
Blueprint builder > Choose Fieldtype → "Media" and "Relationship" groups disappear in the top bar.

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2520]
## Bug Description
When changing the locale to de or de-CH "Media" and "Relationship" disappear in the top bar.
Translation.

Although both terms are already in the language *.json-file.

<img width="1232" alt="Bildschirmfoto 2020-09-23 um 15 08 11" src="https://user-images.githubusercontent.com/8265902/94016647-a99d0c00-fdae-11ea-9320-60461079b23d.png">

## Environment

Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ebeauchamps** [comment]
In French, I am only getting "Tout" which is for "All", I don't even get "Text", nor "Media" or "Relationship".

**Comment by ebeauchamps** [comment]
Any chance this could be tackled?
In my opinion this is more important than increasing the gap between columns.

**Comment by helloDanuk** [comment]
💨🤖
