### ISSUE TITLE
Show a message when logged in and visiting Password Reset or Activate Account instead of redirecting to homepage

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2521]
## Bug Description

A redirect not to the CP is confusing for me, specially if you would like to log in for the first time (as a new editor) to a Statamic control panel. You end up stucked on the homepage, not knowing how to access the cp.

It makes no difference whether the user is a super_user or an editor with permissions to access the CP.

## How to Reproduce

- Open "password reset" or "activate account" link
- Fill in credentials
- submit
- next page goes to / (homepage) instead of /cp

<img width="374" alt="Bildschirmfoto_2020-09-18_um_23 48 42" src="https://user-images.githubusercontent.com/8265902/94018319-c3d7e980-fdb0-11ea-992b-f5f3edbf1de8.png">

## Environment

Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jeremydouglas** [comment]
Yeah, this is confusing 👍

**Comment by damcclean** [comment]
Hmm, I can't seem to reproduce this error on two new installs from different starter kits. 🤔 Maybe it's no longer happening for new installs.

Two questions:
* What does the reset URL look like in the email? Does it have a `redirect` parameter set on it?
* Did you both clone down the `statamic/statamic` starter kit, if so, around when did you do it?

**Comment by helloDanuk** [comment]
Unfortunately nothing changed yet for the activate account email… I did a quick test today with a fresh install from statamic/statamic
This is the activation URL I got for an editor role with limited permissions:
http://v3-test.test/!/auth/activate/2ac2d3aaf4f69f9ed9b464e7d62ccdcb7ca40799c1d876cd5bb30d8d14f6049a?

But what I found out, if I do a password reset for my super admin account or the editor role above the URL looks different and it redirects correctly to the cp:
http://v3-test.test/!/auth/password/reset/18912145b1264b930e90c068bfcffb787b50db0829cdfbb8857060a77558374a?redirect=http%3A%2F%2Fv3-test.test%2Fcp

**Comment by damcclean** [comment]
Okay, so the issue now only seems to be for user activations?

**Comment by helloDanuk** [comment]
This seems to be the case

**Comment by jasonvarga** [comment]
The reason it works this way is because the user being activated might not have access to the Control Panel, so sending them there is strange.

However, it could just be a bit smarter.
