### ISSUE TITLE
FR: Add `antlers` toggle to field editor

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2522]
##  Bug Description

You can add `antlers: true` to text'ish fields and Antlers will be parsed, but there is no way to toggle that via the field editor.

## How to Reproduce

1. In the CP, look for a way to set `antlers` to `true` in a Blueprint/Fieldset.

## Extra Detail
<img width="554" alt="image" src="https://user-images.githubusercontent.com/6069653/94041742-8018bc00-fd7f-11ea-8027-22dced785323.png">

## Environment

**Statamic version:** 3.0.12
**PHP version:** 7.4

**Install method (choose one):**
- delivered from upon high by rainbow unicorns

**Comment by damcclean** [comment]
I've submitted a pull request to implement this issue: #2891.
