### ISSUE TITLE
Parse Antlers in Nav titles

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2523]
## Bug Description

Building a navigation, specifically a footer and we have a text-only nav item that is `'&copy; {{ now format="Y" }} {{ misc:organization_name }}. All Rights Reserved.'`.

When we to `{{ title }}` in the template, the date works (cuz it's a variable?) but the tag isn't parsed. As there's no blueprint and I can't `antlers: true` to anything.

## How to Reproduce

1. text only nav item with an Antlers tag in it
2. Render that `title`

## Extra Detail

I did try to make a modifier but calling `parse` on it doesn't work either.

**Comment by edalzell** [comment]
Still a thing

**Comment by jackmcdade** [comment]
Still a thing @edalzell?

**Comment by edalzell** [comment]
> Still a thing @edalzell?

Yes, just reproduced it in latest version

**Comment by edalzell** [comment]
[test-nav.zip](https://github.com/statamic/cms/files/11443116/test-nav.zip)

**Comment by JohnathonKoster** [comment]
If I update the navigations blueprint and explicitly add a `title` text field with `antlers: true`, things seem to work okay?

<img width="1157" alt="image" src="https://github.com/statamic/cms/assets/5232890/ecc6df52-aa79-4cb1-b4ee-331f1ac7675e">

Not sure if I'm missing something though

**Comment by JohnathonKoster** [comment]
@jackmcdade  For your specific question - seems to be in how the nav tag/system is implemented 👍

**Comment by JohnathonKoster** [comment]
The `antlers` modifier also seems like a good work around, too:

```antlers
{{ nav:main }}
    {{ title | antlers }}
{{ /nav:main }}
```

**Comment by edalzell** [comment]
> The `antlers` modifier also seems like a good work around, too:

I did not know about this modifier!

Closing as this is a nice workaround
