### ISSUE TITLE
Protected content does not work anymore

### ISSUE THREAD

**Issue by codedge** [statamic/cms#2526]
## Bug Description

When setting the `protect:logged_in` entry at a page it does not show a "Forbidden" or redirect to login page.

* Statamic 3.0.10: ✅ 
* Statamic 3.0.11: ❌ 
* Statamic 3.0.12: ❌ 

So this is broken in the last two versions - 3.0.11 and 3.0.12.

## How to Reproduce

1. Grab a fresh install of Statamic with `composer create-project statamic/statamic test-statamic --prefer-dist --stability=dev`
2. Create a fresh user and a new page, e. g. `page-2`
3. Edit the yaml file and add `protect: logged_in` according to [Protecting Content](https://statamic.dev/protecting-content#basic-usage)
4. Visit the page

I expected to see a "Forbidden" warning or a redirect to the `login/` route. But instead it just shows the content of the page.

## Extra Detail

My test page:

<img width="692" alt="grafik" src="https://user-images.githubusercontent.com/4409904/94115756-77d98300-fe4a-11ea-97c8-708bbb436762.png">

## Environment
Statamic 3.0.11, 3.0.12
Laravel 7.28.3
PHP 7.4.10
No addons installed

**Comment by robdekort** [comment]
Can confirm. Labeled it critical.

**Comment by jasonvarga** [comment]
Sorry about that! Fixed for next release.
