### ISSUE TITLE
Assigned Taxonomy Term isn't displayed in "Create Entry"

### ISSUE THREAD

**Issue by lateshift** [statamic/cms#2528]
## Bug Description

Assigning Taxonmy Terms to an Entry kinda works but the selected Terms aren't displayed in the "Create Entry" Form. Does the form take the displayed "title" from the Blueprint Title Field?

## How to Reproduce

![image](https://user-images.githubusercontent.com/179465/94119955-d9e8b700-fe4f-11ea-824e-45c610fc9e8a.png)

The selection seems to work but the "title" is missing. 

![image](https://user-images.githubusercontent.com/179465/94120015-ecfb8700-fe4f-11ea-87b6-358b82cbfd33.png)

## Environment

**Statamic version:** 3.0.12

**PHP version:** 7.3.11

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I can confirm this bug. However, I seem to also run into an issue where I have two tags attached, one of them has the titles showing, one doesn't have the tag showing.

**Comment by jasonvarga** [comment]
I can't replicate this. If you can provide some more details that would be helpful. I spoke to @damcclean and he's not able to replicate it again.

There must be some other factor at play. Can you reproduce this issue consistently?

**Comment by jasonvarga** [comment]
Hey there, we haven’t heard back on this for a while so I’m going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!
