### ISSUE TITLE
Can't use modifiers in array syntax

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2529]
## Bug Description
Not sure if this is a bug or expected behaviour but this line doesn't work:

```html
{{ pin:event_date format_localized="%A %d %B %Y" }}
```

I have to do this:

```html
{{ pin }}
    <b class="mt-2 mb-4 uppercase">{{ event_date format_localized="%A %d %B %Y"  }}</b>
{{ /pin }}
```

**Comment by jasonvarga** [comment]
What's `pin`?

**Comment by robdekort** [comment]
Oh yeah, not the best example. Sorry! It's a entry id and comes from the entries field.

**Comment by jasonvarga** [comment]
Looks like the issue is when its a multi-part tag combined with a parameter style modifier.

✅  Works: `{{ one | modifier:arg }}`
✅  Works: `{{ one:two | modifier:arg }}`
✅  Works: `{{ one modifier="arg" }}`
❌  Doesn't:`{{ one:two modifier="arg" }}`

**Comment by robdekort** [comment]
🐓

**Comment by jackmcdade** [comment]
Same as #3415 – the entries fieldtype that contains an id is an alias of the Collection tag, not a variable itself. Working as expected, sorry to say in your case!

**Comment by robdekort** [comment]
👍 makes sense, so does the other one
