### ISSUE TITLE
Entry is saved as both .md and .html

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#2530]
## Bug Description
I just discovered something weird after migrating one of my v2 sites. After saving an entry in v3, the .md file is updated, and an extra .html file is created.

I used .html extensions (instead of .md) in my v2 sites, but can't figure out where to "turn off" that setting in v3

## How to Reproduce
1. Update an entry
2. Watch an extra .html file being created in addition to .md (making the site crash)

## Extra Detail

![image](https://user-images.githubusercontent.com/10460870/94138943-28ef1600-fe69-11ea-9459-30090c06154e.png)

![image](https://user-images.githubusercontent.com/10460870/94139064-550a9700-fe69-11ea-8f9b-6b7622533632.png)

## Environment

**Statamic version:** 3.0.{?}

Statamic 3.0.9 Pro
Laravel 7.26.1
PHP 7.4.6
statamic/migrator dev-master

Install method (choose one):

Starter kit

**Comment by jasonvarga** [comment]
Are you using CodeKit?

**Comment by axelferdinand** [comment]
@jasonvarga Yeah, is _that_ the sinner?? Of course...

**Comment by jasonvarga** [comment]
Luckily someone else recently had this issue recently!
