### ISSUE TITLE
Statamic\Modifiers\ModifierException implode(): Invalid arguments passed  - Collections Fieldtype breaking the output

### ISSUE THREAD

**Issue by aadind** [statamic/cms#2531]
## Bug Description
getting error as 
`Statamic\Modifiers\ModifierException
implode(): Invalid arguments passed`

while using collection fieldtype to allow the user to select a collection and then display the entries from the selected collection in a template partial. 

## How to Reproduce
1. Create a collection fieldtype for a blueprint. 
2. select a collection for the field 
3. https://statamic.dev/fieldtypes/collections follow this document to bring up entries from the selected collection. 

## Extra Detail
![image](https://user-images.githubusercontent.com/13034288/94180263-5cf32700-febb-11ea-8363-696abb83564d.png)

Code in the partial: 
```
{{ collection from="{banner_home_collection | piped}" as="entries" }}
{{ entries }}
<div
class="hero-indi owl-single"
style="background-image: url('imgs/slider-01.png')"
>
<div class="container">
  <div class="hero-caption d-flex justify-content-between">
    <h1 class="hero-title">
      {{title}} <br /><small>The beginning for everything</small>
    </h1>
    <a href="#" class="hero-cta btn btn-primary">Learn More</a>
  </div>
</div>
</div>
{{ /entries }}
{{ /collection }}

```
## Environment
WAMP- Php 7.4 

**Statamic version:** 3.0.12

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
-migrated basic settings from v2 using migrator plugin.

**Comment by jasonvarga** [comment]
You can't pipe together a bunch of actual collections.

Instead, you can simply do: `:from="banner_home_collection"` (with the `:` prefix)

**Comment by aadind** [comment]
Oh wow @jasonvarga  thank you so much, i couldn't find this in the documentation. Works perfectly! thank you.

**Comment by aadind** [comment]
@jasonvarga could u also help me with this one? 
I need to filter the entries based on selected collection from collection fieldtype and then another taxonomy term selected by terms fieldtype. 

``` {{ collection :from="archive_collections"  taxonomy:faculty_type="advisory-board"sort="order" }}
```
I need to know how to pass the variable `{{faculty_term}}` instead of `advisory-board`

Thanks!

**Comment by jasonvarga** [comment]
The same thing. `:taxonomy:faculty_type="faculty_type"`
If you have the `:` prefix, it will treat the parameter like a variable.
