### ISSUE TITLE
Manually created user is unable to be edited from the CMS

### ISSUE THREAD

**Issue by zacksmash** [statamic/cms#2533]
## Bug Description
When creating a user manually, using the User facade, the user itself is not able to be updated from the CMS, afterwards. An error notification is show at the bottom and the user is not saved.

## How to Reproduce

Create a user manually using this method:

```
$user = Statamic\Facades\User::make()
  ->email('user@somecompany.com')
  ->data([
    'name' => 'Some User',
    'roles' => [
       'some_roles' // optional
    ]
  ])
  ->save();
```

Then, login to the CMS as a super admin and try to update that user. You'll see an error message popup.

## Extra Detail

Exception:

```
Call to a member function selectedQueryColumns() on null
/Users/me/Sites/topsecret/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php#60
Error
    public function __call($method, $parameters)
    {
        return $this->collection->{$this->method}(function ($value) use ($method, $parameters) {
            return $value->{$method}(...$parameters);
        });
    }
}
```

## Environment
Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.10
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by zacksmash** [comment]
So, this is working now. I'm not sure what changes, but no issue anymore.

**Comment by zacksmash** [comment]
Reopening with more info.

A manually created user is unable to be edited until I clear the cache before every action.

**Comment by damcclean** [comment]
I've been unable to replicate the issue using the code you provided. Could you update to the latest release (v3.0.13) and confirm if you're still running into this?

**Comment by zacksmash** [comment]
I am no longer able to reproduce it, either. Phantom exceptions, I suppose. 🤷🏻‍♂️
