### ISSUE TITLE
Multi-Site: Can delete taxonomy when read only

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2535]
## Bug Description
You can delete a taxonomy from a localized entry even when the taxonomy field isn't `localizable: true`. The field is in `read only` mode and shouldn't allow any editing.

## Environment
Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.9
aerni/snipcart dev-master

**Comment by aerni** [comment]
The issue is only with the Vue component. The actual entry data is not affected. After deleting a taxonomy and reloading the page, the taxonomy will be back.

**Comment by damcclean** [comment]
Would you mind providing steps to reproduce?

I just created two fields, a Taxonomy one and a Taxonomy Terms one, added items to the fields then made them read only and I wasn't able to delete them. I want to make sure I'm not doing it wrong.

**Comment by aerni** [comment]
You don't have to explicitly set `read_only` on the field in the blueprint. I was talking about the little `read only` label that appears in the CP when editing any site other than the root.

Here's a quick demo: [https://streamable.com/ky7gcy](https://streamable.com/ky7gcy)

## To Reproduce
1. Create a multi-site
2. Add a taxonomy field to the blueprint
3. Create an entry and add a taxonomy to it
4. Change the site
5. The taxonomy field says it's `read only`
6. Delete the taxonomy below the field

Use this for the blueprint:

```yaml
-
  handle: categories
    field:
      type: terms
      taxonomies: categories
      mode: select
```
