### ISSUE TITLE
Can't toggle field labels

### ISSUE THREAD

**Issue by tomhelmer** [statamic/cms#2538]
## Bug Description
At some point since the 3.0 release the "toogle field label" function is broken. There's a canToggleLabels check in the Vue components, but it's not set by code.

## How to Reproduce
Edit some field, try to toggle the label to se the handle

**Statamic version:** 3.0.12

**PHP version:** 7.4

**Comment by damcclean** [comment]
This feature was removed due to accessibility issues. You can read more about it over in this issue: statamic/ideas#302
