### ISSUE TITLE
Interface shows duplicated labels for validation rules

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#2540]
## Bug Description
The CP interface duplicates the label for validation rules when editing blueprints.

## How to Reproduce
See gif.

## Extra Detail
![bug](https://user-images.githubusercontent.com/9193686/94274638-31694e80-ff46-11ea-80f5-e1b8434ec481.gif)

## Environment
Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.10

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jesseleite** [comment]
I think it's a JS race condition thing. After refreshing the page a dozen times, I saw this happen at random.

**Comment by brandonferens** [comment]
I've submitted a PR against this bug. #2582
