### ISSUE TITLE
PHP error mounting page to collection

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#2542]
## Bug Description
I've just added a new collection, and when trying to select a page in the Mount field, this error pops up:

![image](https://user-images.githubusercontent.com/545339/94313001-dd765e00-ff75-11ea-86c7-aa0a7c9c898e.png)

## How to Reproduce
Create collection
Try and mount to a page

## Environment
Statamic 3.0.13 Pro
Laravel 7.28.3
PHP 7.4.6
No addons installed
Straight statamic/statamic install, freshly upgraded to .13 a couple of hours ago.

**Comment by jasonvarga** [comment]
Looks like there's a markdown field but it's being fed an array.

Do you have any Markdown fields that used to be Bard fields?
Do you have a field named the same in two collections that use two different fields? Like, `content` in your pages collection being markdown, but bard in your blog?

**Comment by MattRogowski** [comment]
I've not used any markdown fields at any point on this project so far.

Interestingly, it resolved itself when I configured the automatically-created blueprint for the collection - I removed the standard Content field and used my Bard field from within fieldsets, also called Content, and once I'd saved the blueprint, the mounting worked. Not sure if that sheds any light.

**Comment by damcclean** [comment]
Just tried to replicate this issue by creating a new collection and mounting a page but it worked fine. Could you share the blueprint you're using for the page?

**Comment by MattRogowski** [comment]
I've just created another collection too and it's not happened again 🤔 Not sure what happened before and is strange as I've never added a markdown field at any point, but will close for now until I can reproduce more reliably.

**Comment by MattRogowski** [comment]
Re-opening this as I just had it happen again, there must be something going on here.

I created a collection, went to mount a page, and get the same error:

`Argument 1 passed to Statamic\Markdown\Parser::parse() must be of the type string, array given, called in ~/vendor/statamic/cms/src/Markdown/Manager.php on line 15`

The only markdown fields that exist are the "Content" fields in the blueprints that are automatically created when I create the collection, but I do have a bard field called Content in a fieldset.

**Comment by jasonvarga** [comment]
Okay, sounds like what I thought.

> Do you have a field named the same in two collections that use two different fields? Like, content in your pages collection being markdown, but bard in your blog?

In the collection that you created but didn't edit their blueprint yet: if you make the content field a bard field (rather than the default markdown) it should get rid of the error. Or remove the content field if you don't need it.

**Comment by smlparry** [comment]
I too am getting this error
