### ISSUE TITLE
User migrations - Add down() function

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#2543]
This seems to be missing from statamic_auth_tables.php.

```
/**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('role_user');
        Schema::dropIfExists('group_user');
    }
```

**Comment by damcclean** [comment]
I've created a pull request that adds a `down` method to the auth migrations provided by Statamic, #2546. 

In addition to dropping the `role_user` and `group_user` tables, it'll also remove the columns added to the `users` table as well.
