### ISSUE TITLE
php translator generate xx command: not playing nice with arrays

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#2544]
## Bug Description
1. in commit [c0c104f](https://github.com/statamic/cms/commit/c0c104f52a0948876ff004d1a2327cf93af1535a) Jack edited two keys in the English fieldtypes.php files

Those changes were not picked up when running today ```php translator generate fr```
By chance, I found Jack's commit and I was able to correct the translation, but this was pure luck.

2. each and every time I am running ```php translator generate fr```, the translator generate a French validation.php file with empty keys though the current validation.php files already includes those translated keys. Those keys are arrays:
```
    'between.numeric' => '',
    'between.file' => '',
    'between.string' => '',
    'between.array' => '',
    'gt.numeric' => '',
    'gt.file' => '',
    'gt.string' => '',
    'gt.array' => '',
    'gte.numeric' => '',
    'gte.file' => '',
    'gte.string' => '',
    'gte.array' => '',
    'lt.numeric' => '',
    'lt.file' => '',
    'lt.string' => '',
    'lt.array' => '',
    'lte.numeric' => '',
    'lte.file' => '',
    'lte.string' => '',
    'lte.array' => '',
    'max.numeric' => '',
    'max.file' => '',
    'max.string' => '',
    'max.array' => '',
    'min.numeric' => '',
    'min.file' => '',
    'min.string' => '',
    'min.array' => '',
    'size.numeric' => '',
    'size.file' => '',
    'size.string' => '',
    'size.array' => '',
    'custom.attribute-name.rule-name' => '',
```

Current French validation.php file as it can be found in vendor/statamic/cms/resources/lang/fr/:
```
    'between.numeric' => 'Doit être compris entre :min et :max .',
    'between.file' => 'Doit être compris entre :min et :max kilo-octets.',
    'between.string' => 'Doit être compris entre :min et :max caractères.',
    'between.array' => 'Doit avoir entre :min et :max éléments.',
etc.
```

## How to Reproduce
See above

## Environment

**Statamic version:** 3.0.13 Pro

**PHP version:** 7.4.2
**Install method (choose one):**
Updated 3.0.12 local install

**Comment by jasonvarga** [comment]
I've fixed the issue with the arrays, but knowing when existing translations have been updated using the command is a different issue which you can see here: https://github.com/statamic/ideas/issues/309
