### ISSUE TITLE
Cannot update to 3.0.13

### ISSUE THREAD

**Issue by sandersjj** [statamic/cms#2548]
## Bug Description

When updating to 3.0.13 I get this following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for statamic/cms 3.0.13 -> satisfiable by statamic/cms[v3.0.13].
    - Conclusion: remove ueberdosis/html-to-prosemirror 0.7.0
    - Conclusion: don't install ueberdosis/html-to-prosemirror 0.7.0
    - statamic/cms v3.0.13 requires ueberdosis/html-to-prosemirror ^1.0 -> satisfiable by ueberdosis/html-to-prosemirror[1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0].
    - Can only install one of: ueberdosis/html-to-prosemirror[1.0.0, 0.7.0].
    - Can only install one of: ueberdosis/html-to-prosemirror[1.0.1, 0.7.0].
    - Can only install one of: ueberdosis/html-to-prosemirror[1.0.2, 0.7.0].
    - Can only install one of: ueberdosis/html-to-prosemirror[1.1.0, 0.7.0].
    - Can only install one of: ueberdosis/html-to-prosemirror[1.2.0, 0.7.0].
    - Installation request for ueberdosis/html-to-prosemirror (locked at 0.7.0) -> satisfiable by ueberdosis/html-to-prosemirror[0.7.0].
```
## How to Reproduce
Update statamic from the updater in the Control Panel

## Environment

Statamic 3.0.12 Solo
Laravel 6.18.40
PHP 7.4.10
apptender/akismet dev-master
statamic/ssg dev-master

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I believe this issue is related to the Bard updates that were done in 3.0.13. The versions of the ProseMirror package must be conflicting somehow.

Is the prose mirror-to-html package anywhere in your composer.json?

**Comment by sandersjj** [comment]
No it is not in my `composer.json`

**Comment by janpersiel** [comment]
Same issue here, pretty much a clean Statamic install with a cool writing demo installed. 3.0.12 to 3.0.13 throws the same error.

**Comment by damcclean** [comment]
I've managed to reproduce this bug using these steps:

1. Clone the [Cool Writings starter kit](https://github.com/statamic/starter-kit-cool-writings)
2. Delete the `composer.lock` file and change the `statamic/cms` version constraint in the `composer.json` file to `3.0.12`.
3. Run `composer install`
4. Then attempt an update via the Control Panel

![image](https://user-images.githubusercontent.com/19637309/94363005-02261f00-00b7-11eb-8bcb-a06d44ddff35.png)

**Comment by damcclean** [comment]
I'm going to wait until the Statamic team are online tomorrow to fix this bug. 

However, there's a workaround if you want to update in the meantime. In your terminal, change into the directory with your site in and run `composer update`. It should run the update just fine.

**Comment by jasonvarga** [comment]
Thanks for pointing this out! You can also use `composer update statamic/cms --with-dependencies` if you only want to update Statamic (and its requirements) and not everything else.

**Comment by jasonvarga** [comment]
Until we're able to fix the updater, you'll need to update via the command line using `composer update statamic/cms --with-dependencies`.

If you've previously updated using the control panel, you'll need to update the `statamic/cms` requirement in your `composer.json` to `3.0.*` before running the command.

**Comment by doifeellucky** [comment]
> Until we're able to fix the updater, you'll need to update via the command line using `composer update statamic/cms --with-dependencies`.
> 
> If you've previously updated using the control panel, you'll need to update the `statamic/cms` requirement in your `composer.json` to `3.0.*` before running the command.

Hi

I  just tried to update past .12 and then found this post.

Mine is a fresh v3 install (not touched for a few weeks) but I have no mention of statamic in vendor/composer/composer/composer.json.

In installed.json I have

        "name": "statamic/cms",
        "version": "v3.0.12",

and having changed to .* and then run composer update statamic/cms --with-dependencies my control panel is saying the version is Statamic 3.0.*  Is that correct for now?

Thanks

**Comment by doifeellucky** [comment]
Any update on when a fix is due?

**Comment by jackmcdade** [comment]
It seems like you're looking in the wrong file – it should be the `composer.json` in the root of your project, not the `vendor/` directory. You should be able to follow [this advice](https://github.com/statamic/cms/issues/2548#issuecomment-700204190) in that file and be good to go.

**Comment by doifeellucky** [comment]
Ah OK.  Apologies.  Thanks for the feedback.

**Comment by dannyuk1982** [comment]
I ran into this myself today (.8 to .20) updating the composer.json still didn't work with the CP updater, but it did update via the CLI after doing this.

**Comment by hmalaud** [comment]
Same issue here, not possible to upgrade from 3.0.12 to latest version. Changed the `composer.json` with `"statamic/cms": "3.0.*"` but still unable to update either through CP or CLI:

```
Loading composer repositories with package information
Updating dependencies
Dependency "guzzlehttp/guzzle" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Dependency "laravel/framework" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/translation v5.1.8 requires symfony/translation-contracts ^2 -> found symfony/translation-contracts[dev-master, dev-main, v2.0.0, ..., 2.3.x-dev (alias of dev-master)] but it conflicts with another require.
    - laravel/framework v7.29.2 requires nesbot/carbon ^2.31 -> satisfiable by nesbot/carbon[2.41.5].
    - nesbot/carbon 2.41.5 requires symfony/translation ^3.4 || ^4.0 || ^5.0 -> satisfiable by symfony/translation[v5.1.8].
    - laravel/framework is locked to version v7.29.2 and an update of this package was not requested.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by damcclean** [comment]
What if you just run `composer update statamic/cms` (without the parameter)?

**Comment by hmalaud** [comment]
No error is logged but I'm still stuck at 3.0.12:

```
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: hmalaud/profile
Discovered Package: intervention/httpauth
Discovered Package: intervention/image
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: statamic/cms
Discovered Package: wilderborn/partyline
Package manifest generated successfully.
> @php artisan statamic:install --ansi
Discovered Addon: hmalaud/profile
Addon manifest generated successfully.
Copied Directory [/vendor/statamic/cms/resources/users] To [/resources/users]
Publishing complete.
Copied Directory [/vendor/statamic/cms/resources/dist] To [/public/vendor/statamic/cp]
Publishing complete.
Compiled views cleared!
Application cache cleared!
70 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by jasonvarga** [comment]
If you can't **manually** upgrade on the command line past a specific version, make sure you change your composer.json as per [this comment](https://github.com/statamic/cms/issues/2548#issuecomment-700204190).

**Comment by mar627** [comment]
> No error is logged but I'm still stuck at 3.0.12:

had this issue.. a simple `composer install` fixed it

**Comment by hmalaud** [comment]
Same here, removed the vendor folder and `composer install` to be up to date.

**Comment by doifeellucky** [comment]
Now cannot update to 3.0.34

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: ueberdosis/prosemirror-to-html[2.2.0, 2.1.0].
    - Can only install one of: ueberdosis/prosemirror-to-html[2.2.0, 2.1.0].
    - Can only install one of: ueberdosis/prosemirror-to-html[2.2.0, 2.1.0].
    - statamic/cms v3.0.34 requires ueberdosis/prosemirror-to-html ^2.2 -> satisfiable by ueberdosis/prosemirror-to-html[2.2.0].
    - Installation request for statamic/cms 3.0.34 -> satisfiable by statamic/cms[v3.0.34].
    - Installation request for ueberdosis/prosemirror-to-html (locked at 2.1.0) -> satisfiable by ueberdosis/prosemirror-to-html[2.1.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by j3ll3yfi5h** [comment]
@doifeellucky

1. try to delete composer lock and vendor folder
2. do a composer install
3. update via cp should now work

**Comment by doifeellucky** [comment]
Thanks I'll try that.

**Comment by doifeellucky** [comment]
@j3ll3yfi5h 

Thanks

**Comment by jesseleite** [comment]
@doifeellucky unfortunately the fix in https://github.com/statamic/cms/pull/3045 isn't tagged yet, but should be tagged in 3.0.36 for future upgrades.
