### ISSUE TITLE
Naming a set 'image' in a bard breaks the json for the list of articles used for linking to an entry in a navigation

### ISSUE THREAD

**Issue by Eworm** [statamic/cms#2553]
## Bug Description
Naming a set 'image' in a bard breaks the json for the list of articles used for linking to an entry in a navigation.

## How to Reproduce
As far as I can see: add a set to a bard and name it image. Add some entries to the collection with this set. If you add a navigation with this collection, you shouldn't be able to link to an entry because the cp will show this error: `Undefined property: stdClass::$attrs`

## Extra Detail

If I disable [lines 223-226 here](https://github.com/statamic/cms/blob/master/src/Data/DataCollection.php#L223) the error doesn't occur.

![Schermafbeelding 2020-09-28 om 19 56 40](https://user-images.githubusercontent.com/511488/94468455-bbbee600-01c4-11eb-8c97-0a906357b064.png)

## Environment
Statamic 3.0.13 Pro
Laravel 7.28.3
PHP 7.4.3
statamic/migrator dev-master
statamic/seo-pro 2.0.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ebeauchamps** [comment]
It's a reserved word throughout the cms, so I am not surprised. Try changing it for something like "figure".

**Comment by Eworm** [comment]
That's a quick fix, but doesn't help others with the same problem. [The docs actually use the same set name](https://statamic.dev/fieldtypes/bard#templating) , suggesting people should use the name image.

**Comment by aj-adl** [comment]
This is part of a larger problem - the reserved words are not well documented, and field names, bard sets etc are never validated against this list - I encountered the same issue with the word 'type' in #2042 and basically got told to pick a better name, and that they would MAYBE consider adding a warning about this.

It should be impossible to create a bard field or set with a 'reserved' name.

**Comment by jasonvarga** [comment]
I don't think it's reserved. Seems likely a different problem.

**Comment by philipboomy** [comment]
I ran into into this issue too. I changed fieldset, deleted fieldset, started creating it again. I didnt add the image set and still it broke. Turned out the existing data with the handle "image" was enough to break it. So I had to change my .md files as well as the fieldset.

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.
