### ISSUE TITLE
New user activation link goes to front page

### ISSUE THREAD

**Issue by bambamboole** [statamic/cms#2555]
## Bug Description
A new created user gets an activation link via Email which looks like this:
```
http://statamic.test/!/auth/activate/42d2b6b3e39f0fc84bc66ab4d2ecd42f4d242ec7069001ead9142fe64c1ce3da?
```
If I click the link I end on the front page without any further information nor a password form.

## How to Reproduce
Install a new copy of Statamic via:
```
composer create-project statamic/statamic statamic --prefer-dist --stability=dev
```
Create a new super user
Enable Statamic Pro
Create a new user from the CP and try to access the url which should be send via email to the new user

## Environment
```
Statamic 3.0.13 Pro
Laravel 7.28.3
PHP 7.4.10
No addons installed
```

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Are you already logged in when you click that link?

**Comment by bambamboole** [comment]
OH damn thanks @jasonvarga ! The moment  when you get that the problem sits in front of the computer :D
It is exactly this issue...
