### ISSUE TITLE
Fieldset with options true or false are converted to strings in v3

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#2558]
## Bug Description
Noticed my fieldsets with radio buttons with options true or false was converted to strings when migrating from V2 to V3: 

`handle: media_figure_frame
    field:
      type: radio
      display: Medieramme
      options:
        'true': 'Vis ramme'
        'false': 'Skjul ramme'`

Removing the ' before and after true or false will make the site crash

`handle: media_figure_frame
    field:
      type: radio
      display: Medieramme
      options:
        true: 'Vis ramme'
        false: 'Skjul ramme'
      default: false
      width: 33`

## How to Reproduce
Make a field with type `radio` and options with `true` and `false`

## Extra Detail
![image](https://user-images.githubusercontent.com/10460870/94561256-0e031400-0264-11eb-8910-f690d9d61953.png)

## Environment

Statamic 3.0.13 Pro
Laravel 7.28.3
PHP 7.4.6
statamic/migrator dev-master

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
There's a `cast_booleans` option on the `select` fieldtype that we need to bring to the `radio` fieldtype. Thanks!

**Comment by damcclean** [comment]
I've created a pull request that brings this functionality to the Radio fieldtype: #2601.
