### ISSUE TITLE
Listing.vue should be global for addon builders

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#2559]
## Bug Description (low priority)

Right now, addon developers that want to create a listing, have to import Listing.vue in this way https://github.com/riasvdv/statamic-redirect/blob/master/resources/js/components/ErrorsListing.vue#L122

It would be nice if that was global like the Fieldtype mixin.

**Statamic version:** 3.0.13

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by edalzell** [comment]
For some context, this because more onerous when like me, you use Jason's `dist` plugin so you don't have to version control the compiled assets. This requires me to run `composer install` as part of my build process now.

**Comment by damcclean** [comment]
I've created a pull request to implement the Listing component as a Vue mixin: #2602.
