### ISSUE TITLE
Dynamic access not working when passing var to partial

### ISSUE THREAD

**Issue by philipboomy** [statamic/cms#2561]
## Bug Description

Passing for example photos:0 or photos[0] in a partial does not work.

## How to Reproduce

Try this

`{{ partial:layout/_featured_image :image="photos:0" }}`

and nothing is passed.

## Extra Detail

Jason quickly tested it and confirmed it didnt work. https://discordapp.com/channels/489818810157891584/489819906540568593/760570154605609030

**Statamic version:** 3.0.13

**PHP version:** 7.4

**Comment by damcclean** [comment]
I've tagged this issue as a bug as Jason confirmed on Discord.I've tagged this issue as a bug as Jason confirmed on Discord.

**Comment by edalzell** [comment]
@damcclean have you tagged this issue as a bug as Jason confirmed it on Discord? Wasn't sure.....lol

**Comment by damcclean** [comment]
> @damcclean have you tagged this issue as a bug as Jason confirmed it on Discord? Wasn't sure.....lol

Yeah, that's why I added the `bug` label 😄

**Comment by damcclean** [comment]
Stupid bot, keep this issue open

**Comment by philipboomy** [comment]
Yeah stupid bot. I haven't received an email about it going stale. I cant keep eye on on my issues to see if the robot is closing it.

**Comment by jasonvarga** [comment]
Fixed in 3.0.45
