### ISSUE TITLE
FR: Allow sortable Assets in list mode

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#2563]
I have a site that has about 180 images in a plain old Asset container.

If I upload a new image and don't remember the filename I have to manually search through the 180 to try and see what one was uploaded most recently.

Ideally we would be able to sort the images by whatever column, but for now could we set the default sorting to `'last_modified', 'desc'` to make new images easier to find.

**Comment by damcclean** [comment]
This issue might be better in the statamic/ideas. 

I don't have permission to move the issue - maybe one of the gents could do it? cc @statamic/core

**Comment by johncarter-** [comment]
It already exists ( https://github.com/statamic/ideas/issues/221 ), but I was hoping to get the default sort order set until sortable columns are implemented. I'll close it and try and fix it myself.
