### ISSUE TITLE
Can't delete pages

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2565]
## Bug Description
In a multisite setup (not sure if it matters in this case, didn't test without yet) I can't delete pages from the page collection. They just appear back after a refresh. I'll update with more details later.

## Environment
Statamic 3.0.13 Pro
Laravel 7.28.3
PHP 7.4.6
edalzell/mailchimp 2.0.6
jonassiewertsen/statamic-livewire 2.0.0

**Comment by jasonvarga** [comment]
Are you deleting them from the tree UI? You have to click the bright red save changes button.

**Comment by robdekort** [comment]
Yes I pressed the save button :). Will add zip and more info tonight when back at Mac.

**Comment by robdekort** [comment]
Hey Jason. I can't replicate it on a fresh install, also not with multisite turned on. Do you want access to the repo with this issue?

**Comment by robdekort** [comment]
Just added you to https://github.com/studio1902/klimaatadaptatiegroningen. Let me know if that doesn't work for you.

**Comment by piljac1** [comment]
Hey @robdekort ! It might be related to an issue I opened a couple of days ago (also on a multi-site setup, haven't tested on a single site setup).

Issue: https://github.com/statamic/cms/issues/2477

**Comment by robdekort** [comment]
Oh yeah that does look very similar. In your case with child pages. If it's indeed the same issue I wonder what our pages have in common.
