### ISSUE TITLE
User names with non english characters causes JavaScript errors on control pane

### ISSUE THREAD

**Issue by vaites** [statamic/cms#2574]
## Bug Description

After a fresh installation, when creating users with `php please make:user`, names with non english characters causes JavaScript errors on control panel and make it unusable (only a grey background is shown). 

## How to Reproduce

Use **David Martínez** as name (note the acute accent):

```
composer create-project statamic/statamic test --prefer-dist --stability=dev
cd test
php please make:user
```

After that, the yaml file on `users` folder looks like this:

```yaml
name: !!binary RGF2aWQgTWFydO1uZXo=
super: true
id: 925edeae-4d81-414e-95ac-601cd967c8cb
password_hash: $2y$10$*********************************************************
```

Replacing the name with an string solves the problem. If the user is created only a name with english characters all works well.

## Extra Detail

With spanish set as browser's language:

```
TypeError: e is null
    u translator.js:49
    l translator.js:11
    __ globals.js:52
    __ mixins.js:13
    e mixins.js:7
    anonymous vendor.js:3
    VueJS 9
    start Statamic.js:74
    <anonymous> dashboard:402
vue.common.prod.js:6:11579

// 

TypeError: this.flash is null
    flashExistingMessages Toast.js:27
    mounted Toast.js:25
    VueJS 7
    start Statamic.js:74
    <anonymous> dashboard:402
vue.common.prod.js:6:11579
    VueJS 10
    start Statamic.js:74
    <anonymous> dashboard:402
```

With english set as browser's language:

```
TypeError: Cannot read property '*.Profile' of null
    at u (translator.js:49)
    at l (translator.js:11)
    at t.__ (globals.js:67)
    at wn.<anonymous> (mixins.js:15)
    at wn.e (mixins.js:13)
    at wn.eval (eval at qa (vue.common.prod.js:6), <anonymous>:3:9380)
    at wn.e._render (vue.common.prod.js:6)
    at wn.r (vue.common.prod.js:6)
    at fn.get (vue.common.prod.js:6)
    at new fn (vue.common.prod.js:6)
qe @ vue.common.prod.js:6

///

TypeError: Cannot read property 'forEach' of null
    at wn.flashExistingMessages (Toast.js:36)
    at wn.mounted (Toast.js:31)
    at $e (vue.common.prod.js:6)
    at Qt (vue.common.prod.js:6)
    at vue.common.prod.js:6
    at wn.$mount (vue.common.prod.js:6)
    at wn.$mount (vue.common.prod.js:6)
    at wn.e._init (vue.common.prod.js:6)
    at new wn (vue.common.prod.js:6)
    at wn.start (Statamic.js:81)
```

## Environment

Statamic 3.0.14 Solo
Laravel 7.28.3
PHP 7.3.20
No addons installed

This happens at least on Windows. Didn't tried on Linux yet...

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Could have the same cause as #2353.

**Comment by vaites** [comment]
If I edit the users' YAML file through Vim to set the name with non english characters a 500 error is shown:
```
The YAML value does not appear to be valid UTF-8
```
Anyway, if I use an editor and set the encoding to UTF-8 works well even with non english characters.

**Comment by damcclean** [comment]
Looks like for whatever reason using non-english characters causes Vuex to basically be empty, which will be what is crashing the page and causing console errors to be thrown.

![image](https://user-images.githubusercontent.com/19637309/94947905-51fd4f80-04d6-11eb-8cdb-92c4e5cb9c8f.png)

**Comment by jasonvarga** [comment]
I can't replicate this. This is what I end up with in my YAML file.

``` yaml
name: 'David Martínez'
```

If I manually plop `name: !!binary RGF2aWQgTWFydO1uZXo=` in there, then yes I see the errors. I'm curious what's different though.

Can you run `composer show | grep symfony/yaml` ?

**Comment by jasonvarga** [comment]
Oh. You're running Windows. Probably that.

**Comment by vaites** [comment]
Yes, I'm using Windows and probably the encoding is not the expected, but the input is not validated. At least the command must throw an exception or show an error if the values are invalid...

**Comment by jasonvarga** [comment]
There's nothing invalid about having a name with an í in it. As you can see for me it made a string just fine. I don't know why it's doing that binary thing for you.

**Comment by vaites** [comment]
Will take a look to suggest a solution or make a pull request if I see it clear.

**Comment by vaites** [comment]
I made some tests and I think this is a Symfony problem. I created this Laravel command on the same installation:
```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class Test extends Command
{
    protected $signature = 'test';
    protected $description = 'Command description';

    public function handle()
    {
        dump($this->ask('What?'));

        return 0;
    }
}
```
The result for the input *martínez* is this:
```
C:\Develop\htdocs\testing\statamic>artisan test

 What?:
 > martínez

b"martÃ­nez"
```

I think this is related to the issue [#37385](https://github.com/symfony/symfony/pull/37385) on Symfony, because removing the call to `sapi_windows_cp_get()` doesn't return the input as binary (but with wrong encoding).

You can discard this issue. Sorry for bothering you...

**Comment by jasonvarga** [comment]
Thank you for following up!
