### ISSUE TITLE
Dashboard widgets equal height

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2578]
I'm sure I added this issue earlier but it seems gone. Anyway, widgets currently look like this:
<img width="1610" alt="Screenshot 2020-10-02 at 20 49 12" src="https://user-images.githubusercontent.com/69107412/94959159-01472000-04f1-11eb-85e7-eaf834003fed.png">

But I think this is a little easier on the eyes (h-full on the card components):
<img width="1610" alt="Screenshot 2020-10-02 at 20 50 29" src="https://user-images.githubusercontent.com/69107412/94959184-0dcb7880-04f1-11eb-8507-68e1cf28b564.png">

**Comment by jasonvarga** [comment]
I moved it to https://github.com/statamic/ideas/issues/351 😄

**Comment by robdekort** [comment]
Ahhhhhh there it is 🤣 Fair enough.
