### ISSUE TITLE
Sort Modifier - unable to sort by tree structure 

### ISSUE THREAD

**Issue by aadind** [statamic/cms#2581]
## Bug Description
trying to sort the collections entries in template just exactly how they are ordered in the tree structure in after enabling the orderable drag and drop option. 

If i use ```sort="tree:desc"``` nothing happens. Not sure if I'm using the correct syntax or its a bug? 

## Extra Detail

my code is as follows 
```
 {{ collection :from="guidance_collection" taxonomy:show_in_homepage="divine-guidance" sort="tree:desc }}
    <div class="col-md-4">
      {{featured_image}} <img src="{{ glide:url width="329" height="257" fit="crop" }}" class="img-fluid" alt="" /> {{/featured_image}}
      <div class="d-title mt-4">{{title}}</div>
      <div class="d-desc" style="text-align: justify;">
        {{ home_text }}
      </div>
      <a href="{{ url }}" class="d-block d-link mt-4 mb-5"><strong>{{ global_variables:read_more}}</strong></a>
    </div>
    {{ /collection }}
  </div>
```
## Environment
**Statamic version:** 3.0.x

**PHP version:** 7.4

**Install method (choose one):**
-migrated from v2
- Other (please explain this magic!)

**Comment by jasonvarga** [comment]
You cannot sort by tree structure in the collection tag. It's too ambiguous.

Look at this example:

```
Foods
|-- Healthy
|    |-- Salad
|        |-- Greek
|        |-- Caesar
|-- Junk
|    |-- Burger
|    |-- Fries
Drinks
|-- Coffee
|-- Tea
```

How would you expect it to be sorted?

If your collection is only a single level, make sure it has a max depth of 1, and you can sort by `order` instead. (it should be sorted by order automatically)

If sorting by structure is needed, you can use the `nav` tag.

**Comment by aadind** [comment]
Perfect @jasonvarga  thank you very much for the quick response!
