### ISSUE TITLE
Updater → Translations are not yet possible for…

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2586]
## Bug Description

…"Installing statamic/cms version 3.0.14"

It should be possible to change the sentence order in the translations. For example in german it would be:
"statamic/cms Version 3.0.14 installieren"
Please note that the word "version" is capitalized in german, so it also must be translated.

…"Installation complete!"

<img width="989" alt="Bildschirmfoto 2020-10-04 um 11 49 43" src="https://user-images.githubusercontent.com/8265902/95013146-93107380-063e-11eb-9658-ae2ab20e88c0.png">
<img width="615" alt="Bildschirmfoto 2020-10-04 um 11 48 30 Kopie" src="https://user-images.githubusercontent.com/8265902/95013149-9d327200-063e-11eb-9b71-f82cbd073e33.png">

## Environment

Statamic 3.0.14 Pro
Laravel 7.28.3
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`, update to latest version

**Comment by helloDanuk** [comment]
💨🤖

**Comment by duncanmcclean** [comment]
I believe this issue has been fixed in #3119 so I'm gonna close this issue. If you continue to run into this, let me know and I can re-open this issue.
