### ISSUE TITLE
[Blueprints][Multi-site] Entries field type shows entries in all sites/languages instead of scoping to the current site

### ISSUE THREAD

**Issue by piljac1** [statamic/cms#2594]
## Bug Description
With a multi-site setup, the "Entries" field type shows all entries of all sites within the select, whether the field is localized or not. It makes no sense that you can link your entry to another entry which isn't part of the same locale/website and it makes it a mess to select the proper entry when they have the same title in both locales/sites.

## How to Reproduce
1. Convert your single site instance to a multi-site instance (`php please multisite`)
2. Create two localizable collections
3. In one of the two collection's blueprint, add an "Entries" field type linked to the other collection
4. Add localized entries in the collection that has been referred
5. Access the entry create form of the collection containing the "Entries" field type
6. You can see all results of all locales in the select

## Environment

Statamic 3.0.14 Pro
Laravel 7.28.1
PHP 7.4.3
No addons installed

**Install method (choose one):** Fresh install from statamic/statamic

**Comment by aerni** [comment]
I'm sure there are use cases, where you would want to see all entries and not just the localized ones.

I see two possible options:
1. Work on the Entries Fieldtype UI to also show the locale of an entry. Maybe even allow filtering by locale.
2. Add a boolean to the field in the blueprint that allows to only show entries in the locale of the active site.

**Comment by piljac1** [comment]
@aerni While I agree that there might be some use cases, I see (based on the Github issues and Discord server) that most of the multi-site setups are used for localization. That being said, I believe most of the time people will use the "Entries" field type to manage some kind of hierarchy or relationships. In those cases, it wouldn't be pertinent to see all entries (especially since you have access to the other locale versions of the current entry with the `locales` Antlers tag if needs be).

As for solutions, I both of your solutions could be independent. I personally would prefer the second option for my use case, but I could see the first solution implemented by default for the "show all" behavior.
