### ISSUE TITLE
Bug UI entries listing

### ISSUE THREAD

**Issue by tolawho** [statamic/cms#2595]
## How to Reproduce
Like image below.

## Extra Detail

![image](https://user-images.githubusercontent.com/12527881/95165081-7a869180-07d5-11eb-9558-0025808cf4fc.png)

## Environment

**Statamic version:** 3.0.15 Pro

**PHP version:** 7.28.3

**Comment by ebeauchamps** [comment]
Can you detailled your issue by following the Bug Template? It's quite difficult to understand it with a linked image...

**Comment by tolawho** [comment]
Sorry cuz my english not good. Follow my step:
1. Open collections/entries list. 
2. Make sure you have a list with 3-5 records
3. Open development tool in chrome > click to **Toggle device toolbar**
4. Resize the width of screen from 768px -> 767px
You will see two bugs:
bug1: All columns are pushed to the left leaving a blank space on the right side of the screen. Like the red frame in the attached picture
bug2: There's a huge gap in the height of the screen, but here I see a **vertical scroll bar**
![Profile-20201006T184851](https://user-images.githubusercontent.com/12527881/95199940-cf430000-0807-11eb-8e91-88626cc9b05b.gif)

**Comment by jasonvarga** [comment]
What browser and operating system are you using?

**Comment by tolawho** [comment]
> What browser and operating system are you using?

**OS**: Winndows 10 Pro, v2004
**Browser**: Google Chrome, Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by damcclean** [comment]
I've been able to reproduce this bug, here are the steps I took:

1. Visit 'List' entry view
2. Open Chrome Dev Tools and the mobile simulator thingy
3. Select responsive as the device
4. Quickly change the screensize.

![image](https://user-images.githubusercontent.com/19637309/95376942-c28edc80-08d9-11eb-9b18-729d95059976.png)

**Comment by jackmcdade** [comment]
Fixed in https://github.com/statamic/cms/pull/2811
