### ISSUE TITLE
Mail template contains Illuminate\Mail\Message object

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#2597]
## Bug Description
The mail template contains the variable `message`. This is a problem when you have a form with a field called `message`. When you access `message`inside a mail template, it returns an object of `Illuminate\Mail\Message` instead of the field content.

## How to Reproduce
Create a form with a field with handle `message` and try to access that field in a mail template.

**Statamic version:** 3.0.14

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
You can't have form fields called `message` because of that exact issue. You have to use another name instead. See statamic/ideas#279.
