### ISSUE TITLE
Linking collections in multisite won't auto translate entries

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2599]
## Bug Description
In multisite when you link collection entries to each other you'd expect other locales to use the translated version of the linked entry. Just like in v2. This doesn't seem to work in v3, it always shows in the primary language. 

## How to reproduce
Create a multisite
Create two collections
Add an entry field to one of the collection blueprints
Link two entries

In the frontend of your site you'd expect for language A to see linked entry in language A and for language B in language B. Unfortunately in all non primary languages it seems linked entries will show in the primary language.

I'm sorry it's evening here and this just turned up. It's difficult to explain but a big deal breaker. Happy to explain in detail if you have any questions.

## Environment
Statamic 3.0.14 Pro
Laravel 7.28.3
PHP 7.4.7

**Install method (choose one):**
- Didn't reproduce (yet) in a fresh site. This is in an almost finished project.

**Comment by damcclean** [comment]
Possibly related to #2594?

**Comment by robdekort** [comment]
Here's a [clean install](https://www.icloud.com/iclouddrive/0FuQ4YBb4-qZSSsWWnl7mqkOQ#statamic-issue-2599) detailing this issue.

**Comment by piljac1** [comment]
@damcclean It is somewhat related, but not the same bug. Rob's is saying that if you have the EN site selected and you select an EN entry in the "Entries" field type, Statamic should automatically assign matching translated entries to other locales. So when you would switch to your FR site for example, you would have the FR entry already selected (matching the EN one that was previously selected). I would 100% expect this behavior myself, so +1 on that bug/idea.

The issue I posted is about the "Entries" select field itself that shows ALL entries in ALL locales/sites. There should be a "Only show entries of the currently selected site" option available in the field creation form, or at least some way to specify that in the blueprint's file.

**Comment by robdekort** [comment]
Yeah, thanks for explaining in good English where I clearly had some trouble @piljac1. Haha!

I do think it’s a bug though. V2 did work this way and you can’t really expect someone to relink all those entries for all languages.

**Comment by robdekort** [comment]
When you get to this @jasonvarga let me know if you need access to a repo full of linked and localised content!

**Comment by Hesesses** [comment]
I'm having the same problem, thanks @robdekort and @piljac1 for well written issue

**Comment by robdekort** [comment]
Someone whispered to me this is very much on the radar so this might this is a non issue soon! 💯

**Comment by jasonvarga** [comment]
Looks like a duplicate of #2507

**Comment by robdekort** [comment]
Yup, looks the same.
