### ISSUE TITLE
Deleting origin won't delete translation and creates 'ghost' entries

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2604]
##  Bug Description
When you have a multisite and create a localised entry, deleting the origin doesn't delete the translation. This leaves unwanted ghost entries in your collection that sometimes you can't delete. I haven't pin pointed this yet. 

If you delete this entry via the file system it will come right back if you refresh the CP until you've cleared the cache.

The remaining page still has an origin id of the deleted original. 

## How to Reproduce
- Make a multisite
- Add an entry
- Publish a localised version
- Delete the origin
- Switch to secondary language view

## Extra Detail
Possibly related to [#1713](https://github.com/statamic/cms/issues/1713) 

Here's a quick demo:
![issue](https://user-images.githubusercontent.com/69107412/95306312-8b8fdb00-0887-11eb-800f-d82e0dd35e52.gif)

You end up with:
<img width="1015" alt="Screenshot 2020-10-07 at 10 17 12" src="https://user-images.githubusercontent.com/69107412/95306455-bbd77980-0887-11eb-90cc-c8daee00eb28.png">

[Download a zip](https://www.dropbox.com/s/pasaz1n68redgps/statamic-issue-2604.zip?dl=0) of this demo here.

## Environment
Statamic 3.0.16 Pro
Laravel 8.9.0
PHP 7.4.10
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by piljac1** [comment]
I also encountered the same issue multiple times and one of those times, I tried dragging the `.md` file directly in the trash and then when I reloaded the collection listing, I got a crash, so I went back in my file system and saw that either the Origin ID (or the ID itself, can't remember exactly) of the entry was caught in an infinite loop. I had to restart valet and I also ran `composer dump-autoload` (clearing the cache only like Rob did might have worked too) to get everything to work again.

**Comment by robdekort** [comment]
Oh wow, that sounds like this weird thing I encountered this morning:

![wtf](https://user-images.githubusercontent.com/69107412/95338408-2f42b080-08b3-11eb-83e3-8cffa50e90a7.gif)

Maybe we're on to the source of misery here. That's nice :-).
