### ISSUE TITLE
SVG tag outputs aria attributes without a value

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2605]
## Bug Description
The SVG tag outputs aria attributes like `aria-hidden="true"` as `aria-hidden`. This is invalid according to lighthouse and [this article](https://web.dev/aria-valid-attr-value/?utm_source=lighthouse&utm_medium=devtools).

## How to Reproduce
Add an SVG tag
Give it an attribute like `aria-hidden=true`
Run lighthouse

## Extra Detail
This:
<img width="626" alt="Screenshot 2020-10-07 at 11 23 00" src="https://user-images.githubusercontent.com/69107412/95312666-833b9e00-088f-11eb-8871-e18f60b3eddd.png">

Outputs this:
<img width="944" alt="Screenshot 2020-10-07 at 11 23 12" src="https://user-images.githubusercontent.com/69107412/95312685-88005200-088f-11eb-8645-f55f0c8dc385.png">

## Environment
Statamic 3.0.16 Pro
Laravel 7.28.4
PHP 7.4.10

**Comment by damcclean** [comment]
This seems to happen to any attributes added to the `{{ svg }}` tag, with values that are either `true` or `false`.

**Comment by damcclean** [comment]
I've created a pull request to fix this bug.. #2613.

**Comment by robdekort** [comment]
You sir are a champ!
