### ISSUE TITLE
Antlers Template Engine if-condition broken since update from 3.02 to 3.0.16

### ISSUE THREAD

**Issue by matrad** [statamic/cms#2606]
## Bug Description

In statamic `v3.0.2` we used this condition to display a pupup (and it's still working)

```
{{ if global:show_popup && ( global:popup_url == '' || current_url == global:popup_url) && (global:popup_show_until | is_today || global:popup_show_until | is_future )}}
```

After the upgrade to `v3.0.16` the same condition stops working, there seems to be an issue with the `&&` (and) and `||` or - conditions

[Version-Diff statamic v.3.0.2 - v3.0.16](https://github.com/statamic/cms/compare/v3.0.2...v3.0.16)

## Extra Detail

Exception:

```
Facade\Ignition\Exceptions\ViewException
Use of undefined constant current_url - assumed 'current_url' (this will throw an Error in a future version of PHP)

```

```
syntax error, unexpected ')' on line 1 of: <?php if (null == '' || 'http://site.test' == null )): ?> ...... <?php endif; ?>
```

## Environment

Statamic 3.0.16 Pro
Laravel 6.18.13
PHP 7.2.33-1+0~20200807.47+debian10~1.gbpcb3068
No addons installed

**PHP version:** 7.2

**Install method:**
- Existing Laravel app

**Comment by matrad** [comment]
@edalzell don't know, it's a different condition, but it may be the same - yes...

**Comment by damcclean** [comment]
@matrad So I can verify this issue as a bug, would you mind providing the YAML for the fields you're referencing in that if statement and the values you have for them?
