### ISSUE TITLE
Long response time in local environment

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#2611]
## Bug Description
I am on macOS Catalina 10.15.5 and I am using Laravel [Homestead](https://app.vagrantup.com/laravel/boxes/homestead/versions/9.6.0) for local development. Each request has 1.6 to 2 seconds of loading time just for the CP page. 

<img width="540" src="https://user-images.githubusercontent.com/13189565/95366529-d6cfdb00-08d3-11eb-8aea-5f3bc9383dfe.png">

I also set `'watcher' => false`, but I end up at 1.3 to 1.7 seconds still.

## Random things that happened
I also saw multiple times `There was an issue communicating with statamic.com. Please try again later`.

## Environment

**Statamic version:** 3.0.16
**PHP version:** 7.4.10
**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
First thing I'd check is that since you're using homestead, make sure you have NFS enabled in your folders in your Homestead.yaml.

``` yml
folders:
    - map: ~/code/project1
      to: /home/vagrant/project1
      type: "nfs"
```

**Comment by felixstoessel** [comment]
Hey Jason! I already have NFS enabled.

**Comment by jasonvarga** [comment]
Is this a fresh installation or do you already have things happening on that page?

**Comment by felixstoessel** [comment]
Maybe Statamic Outpost is not available or slow? Because right now, the yellow message appears again with `There was an issue communicating with statamic.com. Please try again later`. Now my CP loads between 0.8 and 1.0 seconds...

**Comment by damcclean** [comment]
The issue with the Outpost where it displays that mssage is quite common for local development environments I believe where it can't talk to the Statamic server for whatever reason. I have it happen on all of my local Statamic sites.

**Comment by jasonvarga** [comment]
Are these long load times on the frontend of your site? Or just the control panel?

Can you paste the output of `curl -V` ?

**Comment by felixstoessel** [comment]
Load times on the frontend are also a little high, but not as high as the control panel.

Here is the output for the `curl -V`:
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**Comment by jasonvarga** [comment]
Could you try setting your DNS server to 1.1.1.1 temporarily and see if that fixes your speeds and "There was an issue communicating with statamic.com" message?

**Comment by felixstoessel** [comment]
Well, I think this is an issue with Vagrant and Homestead on macOS Catalina. I removed `type: nfs` and now I get <500ms. 

I used `type: nfs` for the last years but who knows why I have issues now. If anyone has a similar issue and resolved it, don't hesitate to write!
