### ISSUE TITLE
Create & Link Item (entries fieldtype) is not linking entry

### ISSUE THREAD

**Issue by mattbit** [statamic/cms#2612]
## Bug Description

The “Create & Link Item” functionality when editing an `entries` fieldtype (see screenshot below) is not working. Clicking on it will show the form for the related entry, and on submit the entry is created but it does not get linked.

I guess this must be the same problem raised in #2448, but I'm getting it for any collection regardless of the orderable setting. Some trial and error reveals that this has been present since 3.0.8, when “After saving” options have been introduced. This seems to have broken some js code, because if I look at the network requests when creating & linking the related entry I see a request being sent to `/cp/collections/pages/entries/2c0ce498-8430-4caf-bdd0-51724acf3643/undefined` (`pages` in this case is the collection having the `entries` field) . That `undefined` at the end seems to suggest that something bad is happening in the javascript code… 🙈 

## How to Reproduce

Add an `entries` relationship field to a collection, then try to edit an entry to link it with related items.

## Extra Detail

This is the field with the button I'm talking about:
<img width="822" alt="Schermata 2020-10-07 alle 19 48 40" src="https://user-images.githubusercontent.com/1101742/95368412-64142f00-08d6-11eb-94eb-0044be4d9d38.png">

## Environment

**Statamic version:** 3.0.8 and later (until 3.0.16)

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I'm unable to replicate this issue using the latest version, creating a new entry seems to work fine for me.

The only issue I could see if if you are clicking the button in the 'Go to Listing' mode (which I think is the default) when you create the new entry where it redirects the user to the entries listing and doesn't add the relationship to the entry. (there's an issue for fixing that, #2469)

You can change the 'save mode' by clicking the arrow next to the save button in the modal/stack thing that opens up with the publish form.

**Comment by mattbit** [comment]
> The only issue I could see if if you are clicking the button in the 'Go to Listing' mode (which I think is the default) when you create the new entry where it redirects the user to the entries listing and doesn't add the relationship to the entry. (there's an issue for fixing that, #2469)

Yeah, exactly! I was just clicking on “Save & Publish”, unaware of bug with the stack. I'm thus closing this since the issue should be resolved once #2469 is fixed.

Thanks!
