### ISSUE TITLE
{{ if {form:success} }} is broken

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/cms#2614]
## Bug Description
This bug appeared somewhere between 3.0.8 and 3.0.13. The problem is that with this code:

```handlebars
{{ form:set is="contact" }}
  {{ if {form:success} }}
    {{# Thank you message #}}
  {{ else }}
    {{# redirect #}}
  {{ /if }}
{{ /form:set }}
```

…the thank you message is never rendered, even on successful form submissions. It always redirects.

## How to Reproduce
Use `{{ if {form:success} }}`. I'm happy to provide more if that's helpful, but it really is this simple.

## Extra Detail
Duncan 🇬🇧 🏴  and I talked about it in Discord ([start of brief conversation](https://discordapp.com/channels/489818810157891584/489819906540568593/763479440264527903)), and [they were able to replicate](https://discordapp.com/channels/489818810157891584/489819906540568593/763482684038447104).

## Environment

Statamic 3.0.16 Pro
Laravel 7.28.3
PHP 7.4.7
aryehraber/statamic-captcha 1.0.3
doublethreedigital/duplicator 1.1.0
edalzell/mailchimp 2.0.6
highland/statamic-array-get 1.0.0
statamic/seo-pro 2.0.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Just come across this issue with one of my addon via support, the developer was doing:

{{ if {sc:coupon:has} === true }}

**Comment by granttransition** [comment]
I think I have similar issue, however, for me, no errors are shown and the redirect does not work if though the form is submitted successfully.

```
          {{ if errors }}
          <div class="alert alert-warning">
            <p>Oops, here's what went wrong:</p>
            {{ errors }}
              {{ value }}<br>
            {{ /errors }}
          </div>
          {{ /if }}

          {{ if {form:success} }}
            {{ redirect to="/thank-you" }}
          {{ /if }}
```

**Comment by curtisblackwell** [comment]
@granttransition yeah, that's the exact same issue. My redirect occurs b/c it's in the `else`. The root issue is somewhere in the parsing of `{{ if {form:success} }}`. Given @damcclean's issue with `{{ if {sc:coupon:has} === true }}` I'll bet it's parsing conditionals that require the single curly-brace pair.

@damcclean you could try removing the strict comparison, though. It might work with just `{{ if {sc:coupon:has} }}`.

**Comment by sebabal** [comment]
Any news on this issue? It is kind of a blocker in many cases...

**Comment by curtisblackwell** [comment]
Specifying the `is` param on the `form:success` tag is a functioning workaround. E.g. `{{ if {form:success is="contact"} }}`
