### ISSUE TITLE
Live preview - Error Call to a member function id() on null 

### ISSUE THREAD

**Issue by philipboomy** [statamic/cms#2615]
## Bug Description

Error Call to a member function id() on null 

## How to Reproduce

Have this in the template:
```
{{ nav from="/{segment_1}"  }}
{{ /nav }}
```
or this
```
{{ nav :from="segment_1"  }}
{{ /nav }}
```

Click "live preview"

## Extra Info

Without the "from="/{segment_1}" it works.

**Statamic version:** 3.0.15
**PHP version:** 7.4

**Comment by jasonvarga** [comment]
I believe this was fixed in 3.0.16
