### ISSUE TITLE
Taxonomy with slug of "origin" will not let you apply a term to an entry 

### ISSUE THREAD

**Issue by richarderoche** [statamic/cms#2616]
## Bug Description
Taxonomy with slug of "origin" will not let you apply a term to an entry. It will let you create the taxonomy, create terms, and even make it seem like when you apply a term to an entry that it saved, but the term is gone when you refresh.

## How to Reproduce
- Create taxonomy with slug "origin"
- Create a term in the taxomony
- Try to use the taxonomy to apply a term to an entry (through CP)
- Save and then refresh (taxonomy field will be empty)

## Extra Detail
If you try to add an origin term in a text editor, it will show an error pointing to a "hasOrigin" file. So, I believe there is a conflict with the "origin" name as a slug, which is fine. The main issue is that there is no error logged when attempted through the CP, and that it lets you create the taxonomy with that slug to begin with. I'm also reporting this in case this was actually unintended and perhaps a sign that there may be more conflicts like this.

## Environment
Statamic 3.0.14 Pro
Laravel 7.25.0
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Good catch. I'm guessing this is probably one of those 'reserved words'. Although, there might be something we can do to work around it.

Possibly related to #2495.
