### ISSUE TITLE
Static cache debug warning

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#2619]
## Bug Description
Super low priority really, but the debug notice for not setting up static caching correctly is written even when it **is** set up properly - it adds a log entry when the cache is simply being re-generated, but should only log if it's loading a cache that _already exists,_ not when it's just created it.

It's a bit misleading, and will probably create large log files over time, because it'll clear the cache when you change content, and then log this the first time newly updated page is loaded, but nothing is actually wrong. As I clear the cache on deployments, this will mean it'll log this quite a bit. It also adds a log if it's an excluded page which may also create a large log file as a contact page for example will probably get a fair amount of hits.

## How to Reproduce
Enable full page caching (properly, with the nginx config and everything)
Load a page
The cache will be created in `public/static`, but there will still be a log entry saying `production.DEBUG: Static cache loaded [<url>] If you are seeing this, your server rewrite rules have not been set up correctly.`
Future visits to the same page will be fine
Edit the page/clear the cache manually, and reload the page
It'll add the log entry again

## Environment
Statamic 3.0.16 Pro
Laravel 7.28.4
PHP 7.4.7

**Comment by MattRogowski** [comment]
Would like to re-open this if I can. I have certain routes excluded from static caching, and I have lots of logs like this:

`production.DEBUG: Static cache loaded [https://site.com/contact-us] If you are seeing this, your server rewrite rules have not been set up correctly.`

They're for excluded URLs, so it's intentional that it's not hitting them. My log file is 62MB and it's almost entirely these logs. Can I either turn them off completely, or can it at least exclude routes I've intentionally excluded?

**Comment by jasonvarga** [comment]
What version are you on? It seems fine to me.

**Comment by stanbridge-wcorrea** [comment]
@jasonvarga up to date statamic happens to me. I have no idea what to do but my logs files are huge.

**Comment by MattRogowski** [comment]
Trying again to re-open this as I am still having this issue several years later, I currently have a 1GB error log filled with nothing but these errors.

**Comment by MattRogowski** [comment]
It seems to be related to the trailing slash. If it's not removed from the URL and you go to a page that is being static cached, it doesn't hit the static cache. So I suppose the issue is the trailing slash is not being removed, or that Nginx isn't finding the static cache for this URL. The rewrite rule is set up as the docs say so i guess something needs to be done to remove the trailing slash too.

**Comment by stanbridge-wcorrea** [comment]
@MattRogowski recent versions fixed the trailing slash but I have some hard coded rules to avoid any problem with this. Also, if you use nocache tags it's going to log it anyway, they didn't work on this yet, they don't see problems somehow. The thing is when we make a nocache request (XHR) is when we have that log occuring.

**Comment by duncanmcclean** [comment]
I've re-opened since I'm also able to reproduce the trailing slash issue with my own site.

> Also, if you use nocache tags it's going to log it anyway, they didn't work on this yet, they don't see problems somehow. The thing is when we make a nocache request (XHR) is when we have that log occuring.

I can't reproduce the issue you mentioned regarding the `{{ nocache }}` tag. Can you share the relevant lines from your log for this?

**Comment by MattRogowski** [comment]
That does seem to have fixed it, can confirm no logging and response headers n longer say it's being served by Statamic.

**Comment by stanbridge-wcorrea** [comment]
> I've re-opened since I'm able to reproduce the trailing slash issue with my own site.
> 
> > Also, if you use nocache tags it's going to log it anyway, they didn't work on this yet, they don't see problems somehow. The thing is when we make a nocache request (XHR) is when we have that log occuring.
> 
> I can't reproduce the issue you mentioned regarding the `{{ nocache }}` tag. Can you share the relevant lines from your log file for this?

I'm going to check if I'm still facing this after the changes you mentioned on Nginx. I'll let you know.

**Comment by stanbridge-wcorrea** [comment]
@MattRogowski after the change you did on your web server can you try to access any URL of your website with a long query string (longer than 255) for example: 

example.com?f=eyJmaXJzdF9uYW1lIjogInRlc3QiLCAibGFzdF9uYW1lIjogInVodWwifQ==&asoidhasoidhasdlkhialkdshlkdashlkadshlkdashiohasdiohadhiosadhiosadhiodsahiodsaihodasihodsahiodashiodsbaohidashiodsahio=odosaihshdiosa](https://www-staging.stanbridge.edu/program/associate-vocational-nursing-riverside-b?f=eyJmaXJzdF9uYW1lIjogInRlc3QiLCAibGFzdF9uYW1lIjogInVodWwifQ==&asoidhasoidhasdlkhialkdshlkdashlkadshlkdashiohasdiohadhiosadhiosadhiodsahiodsaihodasihodsahiodashiodsbaohidashiodsahio=odosaihshdiosa

And check if you still have that debug message showing up on your logs. 

Thank you !

**Comment by duncanmcclean** [comment]
> after the change you did on your web server can you try to access any URL of your website with a long query string (longer than 255) for example:
> 
> And check if you still have that debug message showing up on your logs.

I've just changed the Nginx rules on my personal site to test this. Even with a big query string (I copied the one from your comment), I don't see the warning in my log.

![CleanShot 2024-03-28 at 12 09 16](https://github.com/statamic/cms/assets/19637309/ebe468b5-c9bd-4f53-8733-5744e7a85bf3)

**Comment by stanbridge-wcorrea** [comment]
Well, @duncanmcclean it seems to be working for me, however, I'll be keeping an eye in my log because I'm getting some errors still, let's see in a few days. 

In the end, since  "ignore_query_strings" is set to TRUE on my project, there is no reason to try $args on Nginx, so it's loading without the query string and it's loading the static cache files normally.

**Comment by ryanmitchell** [comment]
If you have ignore_query_strings set to false:

```bash
   set $try_location @static;
    
    if ($request_method != GET) {
        set $try_location @not_static;            
    }
    
    if ($args ~* "live-preview=(.*)") {
        set $try_location @not_static;
    }

    location / {
        try_files $uri $try_location;
    }
    
    location @static {
        try_files /static${uri}_$args.html $uri $uri/ /index.php?$args;
    }
    
    location @not_static {
        try_files $uri /index.php?$args;
    }
```

if you have it set to true:

```bash
    set $try_location @static;
    
    if ($request_method != GET) {
        set $try_location @not_static;            
    }
    
    if ($args ~* "live-preview=(.*)") {
        set $try_location @not_static;
    }

    location / {
        try_files $uri $try_location;
    }
    
    location @static {
        try_files /static${uri}_.html $uri $uri/ /index.php?$args;
    }
    
    location @not_static {
        try_files $uri /index.php?$args;
    }

```

**Comment by duncanmcclean** [comment]
In my testing, it seems like Ryan's suggested Nginx config fixes the issue(s) that have been reported here, in addition to also fixing https://github.com/statamic/cms/issues/9845.

I've opened a PR on the docs so our recommended config fixes this issue, see https://github.com/statamic/docs/pull/1334.
