### ISSUE TITLE
Control Panel UI doesn't take up full width

### ISSUE THREAD

**Issue by krsilas** [statamic/cms#2621]
## Bug Description
The unopened popover is occupying additional width on mobile, even though the x-position is transformed. Control panel UI is not 100% wide.

## How to Reproduce
Open the CP on mobile. Reload a few times if issue is not showing up.

## Extra Detail
<img width="461" alt="statamic-bug" src="https://user-images.githubusercontent.com/7888005/95498203-c129e680-09a3-11eb-9dc6-7d06cd5c0775.png">
This issue is caused by popperjs. I assume there is a conflict because of the default CSS and the inline styles that are applied after the component is mounted.

## Environment
**Statamic version:** 3.0.15
**PHP version:** 7.4
**Chrome:** 86 (desktop and mobile)

Fresh install from `statamic/statamic`

**Comment by leganz** [comment]
<img width="1243" alt="Bildschirmfoto 2020-10-08 um 23 15 11" src="https://user-images.githubusercontent.com/3373530/95514439-36091a80-09bc-11eb-8eb1-5546e72516e0.png">
It might be resolved if you add overflow:hidden to #statamic ...
at least on my local installation this resolved the problem, cause popper.js placed the div correctly....

**Comment by krsilas** [comment]
@leganz This does work, but there are other overflow issues where that would be unfavorable: 
<img width="396" alt="overflow-issue" src="https://user-images.githubusercontent.com/7888005/95517920-43c19e80-09c2-11eb-8a7c-1a2127139374.png">

**Comment by jasonvarga** [comment]
Is there a consistent way to see this behavior?

**Comment by johncarter-** [comment]
I was just playing around with a 3.0.16 install and I can confirm this happens when you have a long, **non-spaced** title. It seems like the collection view h1 needs a `class="truncate"` and to wrap the actions under/above the `h1` on smaller screens.

![ezgif-7-f0319f05e025](https://user-images.githubusercontent.com/3776888/95833780-05b2da80-0d34-11eb-80b3-73340652f11a.gif)

**Comment by krsilas** [comment]
> Is there a consistent way to see this behavior?

The behavior of the original issue shows up consistently for me. Not on the first load, but as soon as I click around. I tried it locally, on the server, with a fresh statamic installation and different browsers/devices. I wasn't able to reproduce the issue in Safari (Desktop) and Firefox (Desktop), though. Resizing the window also fixes the layout on certain breakpoints. 
So it's probably related to the time the JavaScript is executed.

**Comment by krsilas** [comment]
Popperjs recently fixed a few issues that could be related to this:
https://github.com/popperjs/popper-core/pull/1174
https://github.com/popperjs/popper-core/pull/1141

**Comment by jasonvarga** [comment]
I've merged the PR that upgrades popper. I don't think it fixes this issue but I'm happy to be wrong.

Looks like we need to do some responsive UI work in general.
