### ISSUE TITLE
Image button not displayed in Bard toolbar

### ISSUE THREAD

**Issue by damcclean** [statamic/cms#2628]
## Bug Description
I created a new Bard field and added the 'Image' feature by its icon. However, when I look at the Bard toolbar, the image button isn't there. 

It's defiantly the correct field I'm editing because I added tables to test and it displays fine on the toolbar.

**Bard toolbar**
![image](https://user-images.githubusercontent.com/19637309/95591857-c3da1980-0a3f-11eb-857d-d4410cdb0d00.png)

**Bard button settings**
![image](https://user-images.githubusercontent.com/19637309/95591872-c9cffa80-0a3f-11eb-97d0-0026642ff20f.png)

## How to Reproduce
1. Create a new Bard field, enable the `Image` toolbar icon
2. Save the blueprint with the bard field
3. Open an entry with the Bard field in, and look for 'Image' button on Bard toolbar

## Environment

```
Statamic 3.0.16 Solo
Laravel 8.9.0
PHP 7.4.6
No addons installed
```

**Comment by jasonvarga** [comment]
Have you chosen an asset container?

**Comment by damcclean** [comment]
Of course not 🙈
