### ISSUE TITLE
Slugs are not localized and uses different implementations

### ISSUE THREAD

**Issue by tomhelmer** [statamic/cms#2631]
## Bug Description

I have noticed that that slugs for text's with danish national letters is converted wrongly. It seems like most things that use the toAscii function don't pass the short locale string. Only exception seems to be the slugify modifier which passes the short locale.

Also the code uses a ASCII implementation from both the Stringy class and from \Illuminate\Support\Str. Stringy seems to include an older implementation from Illuminate whom have replaced it with voku/portable-ascii. So slugify can return another result than other parts of the codebase.

The new implementation from voku/portable-ascii used by new versions of  \Illuminate\Support\Str is more complete as it covers more languages ( including danish )

In the Admin UI the library https://github.com/pid/speakingurl is used for generating slugs. It seems abandoned as it has not been updated for 3 years (plenty of issues/pr exist). Maybe there's a more complete and maintained library, but I have not found one.

A nice workaround would be the if we could add our extra transliterations in the specific project using the 'custom' option:

    slug = getSlug('Foo and Bar or Baz', {
	    custom: {
	        'and': 'und',
	        'or': ''
	    }
	});

## How to Reproduce
     
    <?php

    namespace App\Console\Commands;

    use Illuminate\Console\Command;
    use Statamic\Facades\Entry;
    use Statamic\Facades\Collection;

    class TestSlug extends Command
    {
        /**
         * The name and signature of the console command.
         *
         * @var string
         */
        protected $signature = 'test-slug';

        /**
         * The console command description.
         *
         * @var string
         */
        protected $description = 'Create entry with Danish title/slug';

        /**
         * Create a new command instance.
         *
         * @return void
         */
        public function __construct()
        {
            parent::__construct();
        }

        /**
         * Execute the console command.
         *
         * @return int
         */
        public function handle()
        {
            $title = 'Test med æøå';
            $collection = Collection::find('pages');
            $entry = Entry::make()
                    ->collection($collection)
                    ->slug($title)
                    ->data([
                        'title' => $title
                    ]);
        
                $entry->save();
        }
    }

This command creates a file with the name: 'test-med-aeoa.md'.

I can workaround this behaviour by using:

`->slug(Str::slug($attributes->title, '-', Config::getShortLocale()))`

which would produce a file with the name : 'test-med-aeoeaa.md'

## Environment

Statamic 3.0.16 Pro
Laravel 7.28.4
PHP 7.4.9
spatie/statamic-responsive-images 1.3.0

**Statamic version:** 3.0.16

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Thanks for the script! Managed to reproduce this issue.
