### ISSUE TITLE
[Forms] Impossible to use globals in form settings

### ISSUE THREAD

**Issue by piljac1** [statamic/cms#2635]
## Bug Description
It seems impossible to use global values in forms. I have globals set named "Company information" that contain an "email" handle which serves as the company's main email. If I want to use that value as the form recipient, it throws an error (I validated the syntax by outputting the value on the frontend and it output correctly).

## How to Reproduce
1. Create a globals set containing an email field
1. Input a valid email in the email field and submit
1. Create a form
1. In the created form settings, try to output the global email value in the "Recipient (To)" form (ex.: `{{ globals:company_information:email }}`)
1. Output the form on the frontend, fill it and submit it
1. The following error is encountered: `Trying to get property 'email' of non-object`

## Environment

Statamic 3.0.14 Pro (multi-site)
Laravel 7.28.1
PHP 7.4.3
doublethreedigital/duplicator 1.1.1

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
Pretty sure this is a duplicate. Or maybe a FR. However I can’t seem to find it now.

**Comment by robdekort** [comment]
🦙
