### ISSUE TITLE
User email invitation expires after 0 hours

### ISSUE THREAD

**Issue by tao** [statamic/cms#2641]
## Bug Description
I'm sending out my user invitations for the Statamic control panel and the text says: 

```
Activate your new Statamic account on www.llresearch.dev to begin managing this website. 
For your security, the link below expires after 0 hours.
After that, please contact the site administrator for a new password.
```

On the Statamic documentation the same text says "48 hours"... is there a config that I'm missing that's not mentioned in the documentation? The documentation doesn't seem to cover this?

I tried updating the `config/auth/passwords/users/expires` to 24 hours but this doesn't seem to help:

```
    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 1440,
        ],
    ],
```

## How to Reproduce
I experience the same problem on `starter-kit-cool-writings`.

## Extra Detail
<img width="836" alt="Screenshot 2020-10-12 at 14 35 51" src="https://user-images.githubusercontent.com/1446331/95742154-3c3b1780-0c98-11eb-9da9-c874419e12c2.png">

## Environment
Statamic 3.0.15 Pro
Laravel 6.18.41
PHP 7.4.6

**Install method:**
- Starter kit
- Existing Statamic app

**Comment by jasonvarga** [comment]
I think it's just the message that's wrong. The functionality itself is fine.

**Comment by tao** [comment]
Yes, I was able to invite my users successfully even if the message said 0 hours.

**Comment by jackmcdade** [comment]
It looks like there's no actual config block for the activations broker, just the standard user password expiry. That's why it's defaulting to zero.

@jasonvarga, I haven't tracked down in Laravel how the `PasswordBrokerManager` works – might we be able to just add the config block and have it work thusly?
