### ISSUE TITLE
Bard Images Broken

### ISSUE THREAD

**Issue by mattrothenberg** [statamic/cms#2649]
##  Bug Description
When using an `image` button inside of a Bard field, the selected image never appears in the editor. Instead, users are stuck looking at the "Choose Image" placeholder UI.

I noticed this when trying to select an image from a remote asset container, and the placeholder UI never went away. Moreover, the image data for this Bard field was serialized differently than other asset fields 👇 

Discord Convo where this was confirmed by another user: https://discord.com/channels/489818810157891584/489819906540568593/765737263769321513

**Featured Image** Asset Field Type
```yaml
 featured_image: articles/Screen-Shot-2020-10-09-at-10.47.05-AM.png
```

**Image** Bard Data
```yaml
-
  type: image
  attrs:
    src: 'asset::media::articles/IMG_5792.jpg'
    alt: null
```

## How to Reproduce
**Given** a Bard field with an Image button
**When** I select an image
**Then** I'm stuck seeing the "Choose Image" placeholder, despite the image data being persisted correctly.

## Extra Detail
<img width="797" alt="Screen_Shot_2020-10-13_at_8 46 12_PM" src="https://user-images.githubusercontent.com/5148596/95932474-f23a5a80-0d99-11eb-98d6-a9d5c4bd4f9c.png">

## Environment

**Statamic version:** 3.0.17

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Hmm, I'm unable to reproduce this issue on the latest version of Statamic (v3.0.19). I followed these steps:

1. Create a bard field with the image button. Also selected an asset container
2. Visit entry and add image with Bard's image button.
3. Preview works fine, save entry.
4. Refresh the entry edit page in the CP, the image continues to display. 

I've tried with both `.jpeg` and `.png` filetypes but got the same result with both of them.

**Comment by mattrothenberg** [comment]
Are you using a remote asset source, as described?

**Comment by damcclean** [comment]
@mattrothenberg Ah... no I'm not. I'll play try and reproduce with a remote addon source tomorrow.

**Comment by narmiel** [comment]
Could be related: https://statamic.dev/knowledge-base/assets-dont-have-urls
Got the same problem when asset url was empty. After i fill asset url, everything works fine.
