### ISSUE TITLE
Base table or view not found: 1146 Table 'forge_local.password_activations' doesn't exist

### ISSUE THREAD

**Issue by jbardnz** [statamic/cms#2650]
## Bug Description

This was mentioned in #2392 but it was closed without being resolved. I have done a fresh install with version 3.0.16 and I get this error when I am trying to invite a new user via the control panel. 

## How to Reproduce

1) Fresh Statamic Install
2) Switch to storing users in the database
3) Invite a user via the control panel

## Extra Detail

![image](https://user-images.githubusercontent.com/1628446/95940468-e357b480-0e3a-11eb-8028-416d4d988f10.png)

## Environment

Statamic 3.0.16 Pro
Laravel 8.8.0
PHP 7.4.9
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Ah, change [this](https://github.com/statamic/statamic/blob/master/config/auth.php#L109) to `password_resets`

**Comment by jbardnz** [comment]
Thanks for getting back to me, I have changed that but I get this error instead: 
![image](https://user-images.githubusercontent.com/1628446/96052697-90cdd500-0eda-11eb-8b77-87ccdbbb008d.png)

From what I can see there is no migration that creates the `password_resets` table?

**Comment by mikemartin** [comment]
@duncanmcclean @jbardnz I ran into this today and used the fix Jason suggested above. In case anyone runs into this again, here's a migration for password_resets:

```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePasswordResetsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('password_resets', function (Blueprint $table) {
            $table->string('email')->index();
            $table->string('token')->index();
            $table->timestamp('created_at');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('password_resets');
    }
}
```

**Comment by BrandonOldenhof** [comment]
Hello everyone!

I just ran into this exact same problem with Statamic 3.1.27 & Laravel 8.49.2.
My users are stored in the DB.

The fixes mentioned above worked for me:
1. Replace the reference to the `password_activations` table to `password_resets`
2. Run `php artisan make:migration create_password_resets_table`
3. Copy the contents of the migration mentioned in [this comment](https://github.com/statamic/cms/issues/2650#issuecomment-828088423) and don't forget to doublecheck the class name
4. Run migrations

**Comment by MadeByMike** [comment]
> on suggested above. In case anyone runs into this again, here's

You'll need a similar migration for `password_activations` but what I'm not sure about is how to get the correct table structure.

I really feel like these details should be added to this post: https://statamic.dev/knowledge-base/storing-users-in-a-database

**Comment by MadeByMike** [comment]
https://stillat.com/blog/2021/02/20/enabling-database-users-in-statamic-3

**Comment by michaelr0** [comment]
If anyone needs it, the default from Laravel is: https://github.com/laravel/laravel/blob/8.x/database/migrations/2014_10_12_100000_create_password_resets_table.php

**Comment by michaelr0** [comment]
> > on suggested above. In case anyone runs into this again, here's
> 
> You'll need a similar migration for `password_activations` but what I'm not sure about is how to get the correct table structure.
> 
> I really feel like these details should be added to this post: https://statamic.dev/knowledge-base/storing-users-in-a-database

My guess, based on the config files.

`auth.php`
```php
    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'resets' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
            'throttle' => 60,
        ],

        'activations' => [
            'provider' => 'users',
            'table' => 'password_activations',
            'expire' => 4320,
            'throttle' => 60,
        ],
    ],
```
And `users.php`
```php
/*
    |--------------------------------------------------------------------------
    | Password Brokers
    |--------------------------------------------------------------------------
    |
    | When resetting passwords, Statamic uses an appropriate password broker.
    | Here you may define which broker should be used for each situation.
    | You may want a longer expiry for user activations, for example.
    |
    */

    'passwords' => [
        'resets' => 'resets',
        'activations' => 'activations',
    ],
```

Are that the table schema is the same, it is just an option to store them in separate tables, but should also be fine to store in the same table.
