### ISSUE TITLE
Custom live preview implementation does not work

### ISSUE THREAD

**Issue by timojokinen** [statamic/cms#2653]
## Bug Description
Custom live preview is currently not possible. The docs are outdated as stated in https://github.com/statamic/docs/issues/283.

## How to Reproduce
Try to override toLivePreviewResponse method of https://github.com/statamic/cms/blob/master/src/Entries/Entry.php.
Live preview does not change, still uses the default live preview.

## Environment
Statamic 3.0.17 Solo
Laravel 8.10.0
PHP 7.4.7
No addons installed

**Statamic version:** 3.0.17

**PHP version:** 7.4.7

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment]
@timojokinen can you try the following for me and tell me if it works:

Please add the following snippet into a boot method, which may be your `AppServiceProvider`.

```php
  $this->app->bind(
      \Statamic\Contracts\Entries\Entry::class,
      \App\YourCustomClass::class
  );
```

Your Custom Class overwriting the toLivePreviewResponse method may look something like this. 

```php
<?php

namespace App\YourCustomClass;

use Statamic\Entries\Entry;

class YourCustomClass extends Entry
{
    public function toLivePreviewResponse($request, $extra)
    {
        return response('some HTML');
    }
}
```

**Comment by jasonvarga** [comment]
The documentation has been updated, sorry it took so long. (Thanks Jonas). If you follow those instructions, it seems to work fine.
