### ISSUE TITLE
modifier & logical operators in conditions

### ISSUE THREAD

**Issue by jens-t** [statamic/cms#2655]
## Bug Description & How to Reproduce
The condition ...
```
{{ if {index|mod:4} == 0 or {index|mod:4} == 3 }}
```
... is always true, even if the index is 1 or 2, should only be true with index 0, 3, 4, 7 and so on. The modifier works as expected, if i output it directly. I tested this on the latest version.

## Extra Detail
https://statamic.com/forum/4900-antlers-modifier-logical-operators-in-combination

## Environment
**Statamic version:** 3.0.14
**PHP version:** 7.4
**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Tha syntax isn't right – try this (parenthesis, not braces): `{{ if (index|mod:4) == 0 || (index|mod:4) == 3 }}`

**Comment by damcclean** [comment]
Related to #2614.

**Comment by jens-t** [comment]
The syntax `{{ if (index|mod:4) == 0 || (index|mod:4) == 3 }}` throws: "syntax error, unexpected '==' (T_IS_EQUAL)".

**Comment by jackmcdade** [comment]
Ah my apologies, try this:
```
{{ if (index|mod:4 == 0) || (index|mod:4 == 3) }}
```

If that doesn't work, we're in bug territory.

**Comment by jens-t** [comment]
Also throws: "syntax error, unexpected '==' (T_IS_EQUAL)".

**Comment by jackmcdade** [comment]
Nuts. 🥜

**Comment by anakadote** [comment]
This bug still exists — commenting to reopen.
