### ISSUE TITLE
3.0.17 breaking if

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#2665]
## Bug Description
I do have a variable (on a multisite setup, which is present on the root only). I reference this variable inside of a ``structure`` tag. On the page that has the variable, every other page evaluates to true as well, even though the variable is not present on the other pages/entries.

## How to Reproduce
Jason, you already have that site from a previous issue of me. Take a look at the navigation on top if you are on the shop page. It always evaluates to true, even though, for other pages the variable is not there and should evaluate to false. 

## Extra Detail

![image](https://user-images.githubusercontent.com/9936988/96200241-bb12a780-0f59-11eb-9329-710db89d7b32.png)

![image](https://user-images.githubusercontent.com/9936988/96200258-c49c0f80-0f59-11eb-8dbe-02e105163c7c.png)

## Environment

**Statamic version:** 3.0.17 

**PHP version:** 7.4

**Install method (choose one):**
- Existing statamic installation

**Comment by jasonvarga** [comment]
The title of this issue says 3.0.17 but inside it says 3.0.19. Can you clarify which one you're actually using?

**Comment by edalzell** [comment]
There were several antlers issues resolved in .19 @AndreasSchantl, can you upgrade and try again?

**Comment by AndreasSchantl** [comment]
I did. It's still present in 3.0.19

**Comment by AndreasSchantl** [comment]
I tried again today with v3.0.28 and the issue does not appear anymore.
