### ISSUE TITLE
User permissions for Multisite Setup

### ISSUE THREAD

**Issue by conradfuhrman** [statamic/cms#2667]
## Bug Description
When multisite is enabled there is no way to localize a user to a specific site and/or restrict them from accessing other sites as needed.

## How to Reproduce
Create a multisite Statamic with multiple sites, then add a user and try to restrict them to a single site.

**Statamic version:** 3.0.17
**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

Ideally if multisite is used it would be nice to have additional permissions added to the roles to ensure the following:
- A role to establish who can add access to sites
- From the users levels, a site field (which technically is already there) to select what sites a user has access to
- Possibly separate users for each site for control so it's not in a global setting except for a super admin.

If this is already possibly I have not found the documentation for it. Thanks in advance!

**Comment by conradfuhrman** [comment]
Thanks @damcclean, is there anyway to disable/limit the site switching or tie into the existing permission system to alter what a user can see in the admin for multisite as currently it only looks like a Boolean exists for the site dropdown. Happy to continue this on the ideas repo once moved. But this is a huge blocker for several of our clients right now unfortunately.

**Comment by damcclean** [comment]
I've just had a look through the permissions on my test multi-site and I can't see any permissions related to site switching so I'd assume it's not something that's currently possible. However, I see that could come in useful in some use cases.

**Comment by conradfuhrman** [comment]
Yeah, one of clients on our most trafficked sites has 7 languages that they need to isolate from a user perspective. If we knew how to tie into the existing system we would do it instantly, but we're still pretty green with how to override core admin items in this area.

**Comment by sheldonkotyk** [comment]
+1 to this. My request would be that a superadmin has access, otherwise a role would be associated to a specific site. So a user can be an editor in one, a member in another, and potentially banned in another... etc.

**Comment by dambridge** [comment]
+1

**Comment by j3ll3yfi5h** [comment]
+1

**Comment by damcclean** [comment]
The best way to upvote issues is to leave a 👍  reaction to the issue. That way the gents can filter issues by most thumbs up so they know what to work on. 😄

**Comment by dambridge** [comment]
@damcclean Done, cheers!

**Comment by sheldonkotyk** [comment]
Still needed.

**Comment by spectrum8** [comment]
Still needed.

**Comment by ty3sc** [comment]
Does anyone know whether this feature is available now? I've searched the Statamic docs but I couldn't see anything. It would be really useful to be able to restrict/assign specific sites to specific users.

**Comment by jasonvarga** [comment]
It's not available. This issue is still open. It's on our high priority list though.

**Comment by torian257x** [comment]
@jasonvarga is there maybe some (more or less) quick win workaround to restrict it? because we cannot offer this to our clients, basically, if everyone can do everything.

**Comment by jasonvarga** [comment]
You could try overwriting the policy classes.

**Comment by jasperjorna** [comment]
This would definitely be a very good core feature!

**Comment by fabianmarz** [comment]
@jasonvarga, could you possibly give an update on this when this will be available?

Asking as we finally convinced the PMs to chose Statamic over WP for a new multi-site project. And the permission thing was something yet to be figured out. Before coming up with a custom solution/workaround I just want to make sure this feature is not to be available soon (think we need a solution around Q3/Q4)

Many thanks :-)
