### ISSUE TITLE
GUI hangs indefinitely when deleting an entry in Safari

### ISSUE THREAD

**Issue by webenapp** [statamic/cms#2674]
## Bug Description
**GUI hangs indefinitely when deleting an entry in Safari**

In Safari, when deleting an entry the progress bar keeps running and the delete dialog won't disappear, not unless you refresh the page.

## How to Reproduce
* Install Statamic v3
* Create a user
* Open Safari and login to CP
* Create a collection
* Create an entry
* In the list of entries, delete the entry

## Extra Detail

On closer inspection, it appears to be a JavaScript error: 
```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.response.data') 

Actions.js:61
```
In Actions.js we can see that the `.text()` method is called on a `Blob` object, which currently [isn't supported](https://caniuse.com/mdn-api_blob_text) by Safari and iOS Safari.

## Workaround

Download the [Blob.js polyfill](https://github.com/eligrey/Blob.js), use Laravel mix to combine it with your `cp.js` and Blob's your uncle.

## But..

I must be missing something here... Deleting an entry is a very common action and surely lots of people use Safari or iOS Safari. But I didn't find a bug report on this, or any mention of this issue in de docs or even on Discord.

## Environment

**Statamic version:** 3.0.19 Pro

**PHP version:** 7.4.11

**Install method:** Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
Hey Arthur, hmm... I can’t seem to reproduce this. What version of MacOS and Safari are you on?
But like you say, you’d think someone must’ve reported this if this was a wide spread thing.

**Comment by webenapp** [comment]
Hi Rob, it is currently happening on:
**macOS** Catalina Version 10.15.7 (19H2)
**Safari** Version 14.0 (15610.1.28.1.9, 15610)

**Comment by robdekort** [comment]
Oh yeah, totally reproducible indeed on Catalina. It just doesn't happen on Safari on Big Sur (which I'm running).

**Comment by robdekort** [comment]
🐖

**Comment by jasonvarga** [comment]
Not sure why it works on Big Sur if apparently `.text()` isn't supported. 

Gonna close this one for now but if it's still affecting you badly enough, say so and we can open it back up.
