### ISSUE TITLE
If conditions in collection tags gets ignored

### ISSUE THREAD

**Issue by ReneWeCode** [statamic/cms#2682]
## Bug Description
I'm trying to add an if statement to a collection tag, but it's just getting ignored.
I've been trying to put different kinds of filters and sortings in the if statement, without any luck to get it work.

## How to Reproduce
 Do something like: 
```
{{ collection:articles 
	limit='3' 
	as='articles' 
	{if articles_from == 'selected'} id:in={selected_articles|raw|option_list} {/if} 
}}
	{{ articles }}
		{{ partial src="articles/partials/block" }}
	{{ /articles }}
{{ /collection:articles }}
```

## Extra Detail

In my example `articles_from` coming from a selectfield, and the value is ofc `selected`

## Environment

**Statamic version:** 3.0.19

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Yeah that's not something that's supported.

Since you already have the selected articles, you don't need to re-query for them. I suggest something like this:


```
{{ if articles_from == "selected" }}
  {{ selected_articles }}
    {{ partial src="articles/partials/block" }}
  {{ /selected_articles }}
{{ else }}
  {{ collection:articles limit='3' as='articles' }}
    {{ articles }}
      {{ partial src="articles/partials/block" }}
    {{ /articles }}
  {{ /collection:articles }}
{{ /if }}
```
