### ISSUE TITLE
Multisite + Windows 10 + Wamp gives Error

### ISSUE THREAD

**Issue by HRR1337** [statamic/cms#2690]
## Bug Description

Before reading: After this error I still can continue to test everything with Multisite, but i'm not sure if this error will give issues in the feature.

--

I'm using the latest statamic on my windows pc with WAMP. Want to test multi-site/language support, so **changed the 'pro' feature in 'editions' to true**, and in shell I type: `php please multisite`. I can continue to fill in everything. In the end I get an error:

ErrorException 

  Undefined offset: 1

  at D:\wamp64\www\hfe-statamic\vendor\statamic\cms\src\Stache\Stores\CollectionEntriesStore.php:103
     99â–•         $collection = pathinfo($path, PATHINFO_DIRNAME);
    100â–•         $collection = str_after($collection, $this->parent->directory());
    101â–• 
    102â–•         if (Site::hasMultiple()) {
  âžœ 103â–•             [$collection, $site] = explode('/', $collection);
    104â–•         }
    105â–• 
    106â–•         // Support entries within subdirectories at any level.
    107â–•         if (Str::contains($collection, '/')) {

  1   D:\wamp64\www\hfe-statamic\vendor\statamic\cms\src\Stache\Stores\CollectionEntriesStore.php:103
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined offset: 1", "D:\wamp64\www\hfe-statamic\vendor\statamic\cms\src\Stache\Stores\CollectionEntriesStore.php", ["D:/wamp64/www/hfe-statamic/content/collections/pages/home.md", "default", "pages"])

  2   D:\wamp64\www\hfe-statamic\vendor\statamic\cms\src\Stache\Stores\CollectionEntriesStore.php:121
      Statamic\Stache\Stores\CollectionEntriesStore::extractAttributesFromPath("D:/wamp64/www/hfe-statamic/content/collections/pages/home.md")

## How to Reproduce

Install fresh statamic on Windows 10 with Wamp 
Set pro feature of editions to 'true'
In shell type: `php please multisite`

## Environment

Statamic 3.0.19 Pro
Laravel 8.10.0
PHP 7.3.12
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic` with composer

**Comment by freshface** [comment]
Did you clear the cache afterwords?

**Comment by HRR1337** [comment]
> Did you clear the cache afterwords?

Probably not. So did it all over again. 

1. Install statamic via composer
2. Set edition to 'true' for pro.
3. cleared cache with `php artisan cache:clear`
4. Enabled multisite with `php please multisite`

And it works! So probably it was indeed the cache!

> And added the site to the sites.php config?

Manual says you have to first do `php please multisite` , and then change the sites.php config.  [https://statamic.dev/knowledge-base/converting-from-single-to-multi-site](url)
