### ISSUE TITLE
Multisite and globals

### ISSUE THREAD

**Issue by freshface** [statamic/cms#2692]
## Bug Description

When you have some globals but do not define the other sites languages for them and switch the site it throws an error.

## How to Reproduce

1. Create a multi-site
2. Create a global, but do not check the other language

<img width="968" alt="Screenshot 2020-10-20 at 10 06 49" src="https://user-images.githubusercontent.com/103913/96558624-3d81cb00-12bc-11eb-9d87-03022564d175.png">

3. Add/edit the global
4. Switch to the other language in the top menu bar

Error: https://flareapp.io/share/oPRLqRk5

## Environment

**Statamic version:** 3.0.19

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by gefangenimnetz** [comment]
Probably duplicate of #2319

**Comment by damcclean** [comment]
Hmm, I'm going to keep this open as the exception thrown isn't the same as in #2319. Although, the steps to reproduce seem pretty similar to me and they could very well be exactly the same.
