### ISSUE TITLE
Search not performed in multisite environment when search field is not localized

### ISSUE THREAD

**Issue by cgrisar** [statamic/cms#2699]
## Bug Description
Search not performed in multisite environment when field is not localized

## How to Reproduce
1) Create multisite environment
2) Create collection
3) Create an entry in the sites, not localizing the title
4) Search returns result in default site, and does not show a result in the localized site if title (or any other search field) has nit been localised

## Environment

**Statamic version:** 3.0.19

**PHP version:** 7.4.10

**Install method (choose one):**
- Starter kit

**Comment by cgrisar** [comment]
AFAIK, In this part of code, the localisations are not performed/

Statamic\Search\Index.php

```
public function insertMultiple($documents)
    {
        $documents = (new Documents($documents))->mapWithKeys(function ($item) {
            return [$item->reference() => $this->searchables()->fields($item)];
        });

        $this->insertDocuments($documents);

        return $this;
    }
```

**Comment by cgrisar** [comment]
I tried a couple of things while diving in the insertMultiple() function

![Screenshot 2020-10-21 at 19 21 19](https://user-images.githubusercontent.com/7884608/96757400-aa3cb880-13d5-11eb-9f36-5a387b8fedc2.png)

![Screenshot 2020-10-21 at 19 21 00](https://user-images.githubusercontent.com/7884608/96757437-b45eb700-13d5-11eb-9719-795de556d018.png)

**Comment by cgrisar** [comment]
Actually, the structure of the indexes transmitted to Algolia is not in line with its recommendations:
- either create an index per language
- or create a single entry with the search data in all locales

**Comment by piljac1** [comment]
+1 Having the same issue (see https://github.com/statamic/cms/issues/2925). Unfortunately, this bug makes search indexes close to useless on a multi-site setup.

**Comment by cgrisar** [comment]
I've been working a bit on this, since search becomes my 100% attention on the site I'm developling.

1) What does Algolia expect ?
- either an index for every language of the site. For instance index_fr, index_en, index_de, ...
- either a record in which every entry has all the localizations of the entry. For instance, an entry would look like
```
{
  'id': '1",
  'description_en: 'the English description',
  'description_fr: 'la description en français',
  ...
}
```

2) what does Statamic provide ?
php please search:update will create an index only for the origin language of every entry

So, whilst Algolia is fed, indexing is something of a haphazard.

I'm not sure why the strategy has changed between v2 and v3. search:update worked perfectly in v2, creating an index for every locale. I guess it has something to do with multisite. 

3) suggested solution:

I'm trying to benefit as much from what's working already in v3

a) add an additional field "locale" in App\config\search.php
```
        'wines_fr' => [
            'driver' => 'algolia',
            'searchables' => 'collection:wines',
            'locale' => 'fr',
            'fields' => ['locale', 'title', 'hero', 'url', 'meta_description', 'price_level', 'c', 'e', 'g', 'r', 't', 'm'],
            ]
        ],
        'wines_en' => [
            'driver' => 'algolia',
            'searchables' => 'collection:wines',
            'locale' => 'en',
            'fields' => ['locale', 'title', 'hero', 'url', 'meta_description', 'price_level', 'c', 'e', 'g', 'r', 't', 'm'],
            ]
        ],
]

```
We'll find indexed 'wines_fr' and 'wines_en' in Algolia after search:update

b) modify Searchables.php
I've added a $locale as a parameter. With that parameter, we can filter the entries, terms, ...

```
public function all( $locale ): Collection
    {
        $searchables = $this->getConfiguredSearchables();

        if ($searchables->contains('all')) {
            return collect()
                ->merge(Entry::all())
                ->merge(Term::all())
                ->merge(Asset::all())
                ->merge(User::all());
        }

        return $searchables->flatMap(function ($item) use ($locale) {
            if (starts_with($item, 'collection:')) {
                $collection = str_after($item, 'collection:');

                $entries = $collection === '*' ? Entry::all() : Entry::whereCollection($collection);
            }
   
           ....

           if( $entries ) 
            {
                return $entries->filter( function($entry, $key) use ($locale)
                                            {
                                                return $entry->locale() === $locale;
                                            });
            }    

            throw new \LogicException("Unknown searchable [$item].");
        });
    }
```

Now, Statamic will return only the entries with the correct locale

c) modify update() in \Search\Algolia\Index.php
We need to pass the $locale

```
    public function update()
    {
        $this->getIndex()->clearObjects();

        $locale = $this->config()['locale'];
        $this->insertMultiple($this->searchables()->all($locale));

        return $this;
    }
```

I understand the work could be optimized, for instance working with a loop through all sites. However, since some sites are not per se meant to be localized sites (amp for instance), ...

Hope it helps

**Comment by cgrisar** [comment]
Hi team, can you have a look at suggested solution and implement it in future releases?

**Comment by piljac1** [comment]
We need this!

**Comment by edalzell** [comment]
@cgrisar do you have a PR that fixes this? I have a multi-site, trying to hook up search now so need this working...happy to reference a PR.

**Comment by cgrisar** [comment]
Hi Erin,

I haven't made a PR for that: I don't really know how to do that.
Plus, what I created above works with Algolia but I'm not sure how it'd work with basic search
But you can be sure that the above instructions do the thing.

Here is how my config/search.php looks like:

```
'indexes' => [

        'wines_fr' => [
            'driver' => 'algolia',
            'searchables' => 'collection:wines',
            'locale' => 'fr',
            'fields' => ['locale', 'title', 'label', 'url', 'meta_description', 'price_level', 'c', 'e', 'g', 'r', 't', 'm'],
            'transformers' => [

                'c' => function($color) {
                    return ['c' => [ 'title' => \Statamic\Facades\Term::findBySlug($color[0], 'c')->in("fr")->title(),
                                     'color' => \Statamic\Facades\Term::findBySlug($color[0], 'c')->get("color")
                                    ]
                            ];
                },

                'e' => function($estate) {
                    return ['e' => \Statamic\Facades\Term::findBySlug($estate[0], 'e')->in("fr")->title()];
                },

                'm' => function($methods) {
                    return ['m' => array_map( function ($method) {
                        $image = \Statamic\Facades\Term::findBySlug($method, 'm')->get("image");
                        return [ 'title' => \Statamic\Facades\Term::findBySlug($method, 'm')->in("fr")->title(),
                                 'image' => isset( $image ) ? $image[0] : ''
                                ];
                    }, $methods)];
                },

                't' => function($type) {
                    return ['t' => \Statamic\Facades\Term::findBySlug($type[0], 't')->in("fr")->title()];
                },

                'g' => function($grapes) {
                        return ['g' => array_map( function ($grape) {
                            return \Statamic\Facades\Term::findBySlug($grape, 'g')->in("fr")->title();
                        }, $grapes)];
                },

                'r' => function($regions) {
                    return ['r' => array_map( function ($region) {
                        return [ 'title' => \Statamic\Facades\Term::findBySlug($region, 'r')->in("fr")->title(),
                                 'level' => \Statamic\Facades\Term::findBySlug($region, 'r')->get("level")
                                ];
                    }, $regions)];
                },
            ]
        ],
```

The sad thing is that one has to copy the whole thing and just change the locale of the other indices and in the `->in() `method

**Comment by vguerrerobosch** [comment]
@piljac1 having the same issue. Had to tell the client to desync the filed even if not translated.

**Comment by kristiana-s** [comment]
Also finding that I'm running into this on a site that needs Algolia on multisite, with a separate index for each site - manually implementing @cgrisar makes it work, but would be nice if was integrated into statamic somehow

**Comment by jasonvarga** [comment]
Ability to store site-specific content in site-specific indexes will be in Statamic 3.4. #6318
