### ISSUE TITLE
Collection and Entries tags hit max execution time

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#2700]
## Bug Description
It seems that since updating to 3.0.14 some of my `{{ collection }}` tags and taxonomy `{{ entries }}}` tags are hitting a max execution time error. I've included the errors and the templates below in extra detail.

I suspect this might be related to sharing a single Taxonomy between multiple collections.

<img width="1021" alt="Screen Shot 2020-10-21 at 9 49 13 am" src="https://user-images.githubusercontent.com/414211/96652495-bcd9d200-1382-11eb-90dd-ae6bd478cdbb.png">

## Extra Detail

**Collection index template error**
url: `/inspiration`
https://flareapp.io/share/NPLYg087#F1

view: `/inspiration/show.antlers.html`
```html
---
cm_navbar_static: true
cm_navbar_filled: false
show_inspiration_nav: true
---
{{ partial src="hero/inspiration" }}
{{ partial src="nav/badge-tags" }}

<section class="bg-faded py-3">
  <div class="container">
    {{ collection:inspiration as="posts" :limit="page_limit" paginate="true" is_hidden:isnt="true" }}
      {{ if no_results }}
        Sorry, there are no entries yet
      {{ /if }}
      <div class="grid mb-3">
        {{ posts scope="post" }}
          {{ if favourite }}
            <div class="grid-col grid-col-{{ span or '2' }}">
              {{ partial src="cards/inspiration_wide" }}
            </div>
            {{ else }}
            <div class="grid-col">
              {{ partial src="cards/inspiration" }}
            </div>
          {{ /if }}
        {{ /posts}}
      </div>
      {{ partial src="nav/pagination" }}
    {{ /collection:inspiration }}
  </div>
</section>
```

**Taxonomy term page error**
url: `/blog/tags/onboarding`
https://flareapp.io/share/V7je2QbP#F1

view: `/blog/tags/show.antlers.html`
```html
---
cm_navbar_static: true
cm_navbar_inverse: true
---
{{get_content from="/{segment_1}"}}
  {{ partial src="hero/blog" }}
  {{ partial src="nav/badge-tags" }}
{{/get_content}}

<section id="blog-listing" class="bg-faded py-3">

  <div class="container">
    <div class="grid mb-3">
        {{ entries is_hidden:isnt="true" sort="date:desc" }}
        {{ if no_results }}
              <p>No "{{ segment_3 }}" posts.</p>
          {{ else }}
            {{ if favourite }}
            <div class="grid-col grid-col-{{ span or '2' }}">
              {{ partial src="cards/entry_wide" }}
            </div>
            {{ else }}
            <div class="grid-col">
              {{ partial src="cards/entry" }}
            </div>
          {{ /if }}
        {{/if }}
      {{ /entries }}
    </div>
  </div>

</section>
```

## Environment

Statamic 3.0.20 Pro
Laravel 7.28.3
PHP 7.4.9
rias/statamic-redirect 1.3.1
simonridley/tracking-code-manager dev-master
statamic/migrator dev-master
statamic/seo-pro 2.0.14
statamic/ssg 0.2.0

**Install method (choose one):**
- Migrated site from Statamic v2

**Comment by jasonvarga** [comment]
Do you know what version you updated from?

**Comment by damcclean** [comment]
Someone else was having this same issue in the #v3 channel of the Discord today and it couldn't be resolved. See it for yourself: https://discord.com/channels/489818810157891584/489819906540568593/768425510958268458

**Comment by mikemartin** [comment]
@jasonvarga It works fine when I roll back to 3.0.13.

**Comment by jasonvarga** [comment]
Thanks Mike. And thanks Duncan for pointing out that conversation.

**Comment by axelferdinand** [comment]
I'm having this issue, too! +1

**Comment by mikemartin** [comment]
@jasonvarga I did some investigation into this today and it seems like my Blueprint is the bottleneck.

I've disabled static caching to test server response times and here's what I found:

- Even with 20 entries I was experiencing 15sec response times on my collection listing template. 

- Removing my [content_types](https://gist.github.com/mikemartin/40a558e795c66139ce53f172d8fe34ae) replicator field from my blueprint reduced the response time to 10 secs for all 157 entries. 

- Removing all fields in my collection blueprint except for Title, Image and Subtitle reduced the response time to 2.38 secs.

Hopefully this helps you get to the bottom of it.

**Comment by jasonvarga** [comment]
Have you tried again on the latest release? Still an issue?

**Comment by axelferdinand** [comment]
I still experience the same issue after updating.

**Comment by mikemartin** [comment]
Can confirm that this fixed each of the issues I experienced. Including issues with the sitemap generated by SEO Pro.
