### ISSUE TITLE
Fieldtype number saved as string

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2703]
## Bug Description
I've added some text fields with the type number, but the values are saved as strings. This causes some problems, for example to sum the numbers.

## How to Reproduce

`{{ sitzplaetze | sum:verfuegbar }}`
```
Statamic\Modifiers\ModifierException
Object of class Statamic\Fields\Value could not be converted to number
```

## Extra Detail

![image](https://user-images.githubusercontent.com/3351449/96702556-257c7b00-1392-11eb-8a8b-c5ea07066ee9.png)
![image](https://user-images.githubusercontent.com/3351449/96702595-34632d80-1392-11eb-8166-2328ca6dbe67.png)
![image](https://user-images.githubusercontent.com/3351449/96702639-3fb65900-1392-11eb-809e-ce8477acb782.png)

## Environment

**Statamic version:** 3.0.18

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I've created a pull request to fix this bug: #2708.

**Comment by jasonvarga** [comment]
You could also just use the `integer` fieldtype instead of `text`.

**Comment by Pfeifakopf** [comment]
Tried it with integer, but it causes the same error. Perhaps it's a bug in the modifier.
