### ISSUE TITLE
Cant see replicator content

### ISSUE THREAD

**Issue by philipboomy** [statamic/cms#2705]
## Bug Description

Cant see replicator content despite clicking collapse / expand all - There are JS errors.

## Extra Detail
https://share.getcloudapp.com/12ur00mp

https://share.getcloudapp.com/yAulkkR2

## Environment

Statamic 3.0.20 Pro
Laravel 8.11.2
PHP 7.4.8
No addons installed

**Install method (choose one):**
- Upgrade from V2 to V3 using the migrator (which used a fresh install as per the docs)

**Comment by damcclean** [comment]
I'm unable to replicate this issue. Would you mind sharing the contents of the replicator field and the replicator field in your blueprint?

**Comment by damcclean** [comment]
@philipboomy has sent me over a blueprint and an entry where he is having the issue and I confirm, it's happening for me too.

**Comment by philipboomy** [comment]
This was created using the CP after a bad migration using the migration plugin. Not manually created this using YAML.
