### ISSUE TITLE
Entries field on users breaks CP

### ISSUE THREAD

**Issue by Lampone** [statamic/cms#2706]
## Bug Description
If you add a entries field-type to users they can't login.

## How to Reproduce
Add relation field of entries to a user and try to login.

## Extra Detail
The following pull-request seems to be the problem: https://github.com/statamic/cms/pull/2657 

### Error
`Call to undefined method Statamic\Auth\File\User::locale() (View: vendor/statamic/cms/resources/views/partials/scripts.blade.php)`

vendor/statamic/cms/src/Fieldtypes/Entries.php:198
```
    protected function augmentValue($value)

    {

        if (is_string($value)) {

            $value = Entry::find($value);

            if ($value != null && $entry = $this->field()->parent()) {

                $value = $value->in($entry->locale());

            }

        }

 

        return $value;

    }
```

## Environment

**Statamic version:3.0.20 Pro

**PHP version:7.4.10

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Thanks!

**Comment by damcclean** [comment]
I can confirm this issue, here's a [full Flare stack trace](https://flareapp.io/share/lm2OR9nP).
