### ISSUE TITLE
Taxonomy term details routes do not work when the taxonomy name is more than one word

### ISSUE THREAD

**Issue by BobHumphrey** [statamic/cms#2710]
## Bug Description

If the name of a taxonomy contains two words, navigating to any of the term detail routes for that taxonomy returns a 404 error.

First, I created a taxonomy named Camping Tags, and the links to the term detail routes (i.e. http://localhost:8000/camping/camping-tags/advice) returned a 404 error.

Then I created a second taxonomy with a one word name: CampingTags. With this taxonomy, the links to the term detail routes (i.e. http://localhost:8000/camping/campingtags/advice) worked as described in your [documentation](https://statamic.dev/taxonomies).

## How to Reproduce

I was building a Travel Notes application based on the Cool Writings starter kit.

I created a Camping collection and a Camping Tags taxonomy, along with antler views.

My directory structure looked like this:

```
views
+----camping
         +----camping-tags
                  +----index.antlers.php
                  +----show.antlers.php
         +----_summary.antlers.php
         +----index.antlers.php
         +----show.antlers.php
+----camping-tags
         +----index.antlers.php
         +----show.antlers.php
```

The url for one of the links to the detail terms page looked like this:

http://localhost:8000/camping/camping-tags/advice

Clicking that link returns only the message "404 Page not found."

Here are the views:

**camping/camping-tags/index.antlers.php**

```php
{{ partial:camping-tags.index }}
```

**camping/camping-tags/show.antlers.php**

```php
{{ partial:camping-tags.show }}
```

**camping/_summary.antlers.php**

```php
<div class="grid grid-cols-12 mb-2">
  <div class="col-span-1">
    <a href="{{ link }}" target="_blank" rel="noopener noreferrer">
      {{ svg src="o-external-link" class="h-5 w-5 text-blue-500" }}
    </a>
  </div>

  <div class="col-span-1">
    <a href="{{ url }}">
      {{ svg src="o-link" class="h-5 w-5 text-blue-500" }}
    </a>
  </div>

  <div class="col-span-7 hover:text-blue-500">
    <a href="{{ link }}" target="_blank" rel="noopener noreferrer">
      {{ title }}
    </a>
  </div>

  <div class="col-span-3">
    {{ camping_tags }}
    <a href="{{ url }}" class="text-blue-500 mr-4">{{ title | title }}</a>
    {{ /camping_tags }}
  </div>
</div>
```

**camping/index.antlers.php**

```php
<div class="w-3/4 mx-auto mt-8 ">
  <h2 class="text-3xl font-extrabold text-blue-800 mb-4">{{ title }}</h2>

  <div class="mb-6">
    <a href="{{ link to="camping-tags" }}" class="text-blue-500">
      Camping Tags
    </a>
  </div>

  {{ collection:camping as="camping" }}

  <div>
    {{ if no_results }}
    <div class="text-xl font-bold text-gray-600">
      No entries yet.
    </div>
    {{ /if }}
  </div>

  <div>
    {{ camping }} {{ partial:camping.summary }} {{ /camping }}
  </div>

  {{ /collection:camping }}
</div>
```

**camping-tags/index.antlers.php**

```php
<div class="w-3/4 mx-auto mt-8 ">
  <h2 class="text-3xl font-extrabold text-blue-800 mb-8">{{ title }}</h2>

  {{ taxonomy from="camping_tags" }}

  <h3 class="text-2xl font-nunito_semibold mb-4 pb-1 border-b border-gray-300">
    {{ title }}
  </h3>

  {{ if entries }} {{ entries }}
  <div>{{ partial:camping.summary }}</div>
  {{ /entries }} {{ /if }} {{ /taxonomy }}
</div>
```

**camping-tags/show.antlers.php**

```php
<div class="w-3/4 mx-auto mt-8 ">
  <h2 class="text-3xl font-extrabold text-blue-800 mb-8">
    {{ title | title }}
  </h2>

  {{ if entries }} {{ entries }}
  <div>{{ partial:camping.summary }}</div>
  {{ /entries }} {{ /if }}
</div>
```

I created a second taxonomy with a one word name: CampingTags. All of the directories and files were the same as above, except I changed the directory names "camping-tags" to "campingtags",  and in the code I changed "camping_tags" to "campingtags".

When I did this, all of the routes worked as described in your [documentation](https://statamic.dev/taxonomies).

## Extra Detail

Taxonomy index page for Camping Tags (2 word name)

![image](https://user-images.githubusercontent.com/1383168/96762051-48655a00-13a7-11eb-8886-87dbcfa61c88.png)

Taxonomy index page for CampingTags (1 word name)

![image](https://user-images.githubusercontent.com/1383168/96766021-739c7900-13a8-11eb-840c-0a36d36b7cb4.png)

404 error returned for http://localhost:8000/camping/camping-tags/advice

![image](https://user-images.githubusercontent.com/1383168/96765828-359f5500-13a8-11eb-8ced-80c7e8f80d8d.png)

Correct page returned for http://localhost:8000/camping/campingtags/advice

![image](https://user-images.githubusercontent.com/1383168/96764754-ebb66f00-13a7-11eb-8bb1-4d8c8fd67720.png)

## Environment

Laravel 6.18.43
PHP 7.4.3
statamic/ssg dev-master

**Statamic version:** 3.0.19

**Install method (choose one):**
- Starter kit Cool Writings

**Comment by brnmonteiro** [comment]
not working here too.

**Comment by jasonvarga** [comment]
We can definitely improve the documentation here, but your view directory needs to match the **taxonomy handle** (which would have an underscore). Rename your views to `views/camping-tags` directory to `camping_tags` and you should be good to go.
