### ISSUE TITLE
Half Cache not clearing on server

### ISSUE THREAD

**Issue by DrTrills** [statamic/cms#2714]
## Bug Description
I have 2 environments. Local with no cache and a forge server set to Prod. Trying both cache methods I found that the half cache is not able to fully clear despite running both Laravel commands and Statamic commands and using the CP. **Worth noting**: this appeared to only be an issues on a select page and not the whole site.

When I would use the live preview on the forge server, it would show the changes I want to make confirming it has the latest theme/layout files on it. Once clicking save nothing would change despite a radically different codebase for the view. 

Once I updated cache from `half` to `full` it seemed the driver change fixed it and the new changes were visible.

The half cache was the same for over 12 hours with no changes or clearings.

## How to Reproduce
Enable half cache on your instance, push changes and try to clear cache. They don't appear on some pages.

Live Preview was working

## Environment

**Statamic version:** 3.0.20 Pro
**Laravel:** 7.28.4
**PHP version:** 7.4.11
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by dannyuk1982** [comment]
I'm having a similar issue with a site but on full caching. It seems intermittent, when I clear the static cache and then test is, it works fine, but then a couple of days later the client says it's not updating again, and I have to clear the static cache for it to work. Guessing these might be related, but I can open a new issue if needed. Sorry I don't have more details - hard one to reproduce.

**Comment by jasonvarga** [comment]
> Enable half cache on your instance, push changes and try to clear cache.

How are you clearing your cache?

**Comment by DrTrills** [comment]
I was using the PHP please commands but found the /CP clear cache seemed to work better

**Comment by jasonvarga** [comment]
I've just run into this issue and have worked out the cause.

This one appears to be that when the cached page is served, we're also re-caching it. Basically extending the expiration time every time it's hit.

(Danny, pretty sure your issue is separate, sorry. If you're still running into it, yes please open another.)

**Comment by jasonvarga** [comment]
Closing this as it's not reproducible. Perhaps you have some aggressive server side caching? Maybe using cloudflare? Reopen if necessary.

**Comment by justrustyspoons** [comment]
I have this issue, too. Did anyone ever find a solution?

**Comment by dannyuk1982** [comment]
It's from 6 years ago so have you tried upgrading to a modern version of Statamic?
