### ISSUE TITLE
Entries field shows unpublished items in frontend

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2721]
## Bug Description
When you use an entries field to select content and loop over it in Antlers it renders unpublished entries. I feel unpublished entries should never show unless someone explicitly asks for drafts. 

## How to Reproduce

1. Add entries to a collection. Make sure one of them is unpublished
2. Add an entries field and selected those entries.
3. Loop through the entries in Antlers.
4. Both will show up.

## Extra Detail
Download an [example project](https://www.icloud.com/iclouddrive/0KnXt00zTJ2bQydgHPbbTkKCw#statamic-issue-2721) here and visit the front page. A workaround is to manually test the published status using `{{ if published }}`.
<img width="1439" alt="Screenshot 2020-10-23 at 14 51 38" src="https://user-images.githubusercontent.com/69107412/97005846-4afab780-153f-11eb-913f-8c155e9be55e.png">
<img width="1439" alt="Screenshot 2020-10-23 at 14 51 44" src="https://user-images.githubusercontent.com/69107412/97005860-4cc47b00-153f-11eb-8f69-02cf136c4b19.png">
<img width="1439" alt="Screenshot 2020-10-23 at 14 51 46" src="https://user-images.githubusercontent.com/69107412/97005866-4e8e3e80-153f-11eb-95bd-23379e51143b.png">

## Environment
Statamic 3.0.20 Pro
Laravel 8.11.2
PHP 7.4.10
No addons installed

**Install method (choose one):**
- Starter kit install from `studio1902/statamic-peak`

**Comment by robdekort** [comment]
🦚

**Comment by robdekort** [comment]
I've just noticed future dated entries also get shown.

**Comment by stephenmeehanuk** [comment]
`{{entries}} ... {{/entries}}` outputs both published and unpublished entires. I'd expect if something was in draft, it'd be excluded by default. As a workaround I use `{{entries status:is="published"}}... {{/entries}}`

I'm finding `entries_count` also  includes both published and unpublished entries - Can't find a workaround for this though?
