### ISSUE TITLE
Some Antlers logic not working combining modifiers

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2722]
## Bug Description
I've got an antlers statements that I feel should work but doesn't. I ended up making a custom modifier.

`{{ if pin:event_date|is_today || pin:event_date|is_future }}`
`{{ if (pin:event_date|is_today) || (pin:event_date|is_future) }}`

`pin` is an `entries` field with `max_items: 1`.

## How to Reproduce

1. Give a blueprint a field called `event_date`.
2. Use the entries field to add events to a page for example.
3. Loop through the entries.
4. Use the above logic in your template.

## Extra Detail
<img width="1445" alt="Screenshot 2020-10-23 at 16 03 20" src="https://user-images.githubusercontent.com/69107412/97013383-49ce8800-1549-11eb-86cd-6acb8fbf3769.png">

## Environment
Statamic 3.0.20 Pro
Laravel 7.28.4
PHP 7.4.10
edalzell/mailchimp 2.1
jonassiewertsen/statamic-livewire 2.1.1

**Comment by jasonvarga** [comment]
Not saying what you have shouldn't work as-is, but try replacing `||` with `or`.

**Comment by robdekort** [comment]
I remember trying that as well with the same result. But I’ll confirm next week. 

_On a side node:_ I kinda didn’t want to open this issue because I was afraid of having to go back to this bit of this site already in production. I mean it’s working fine, but since adding something that I didn’t account for from the start, it screams: “Refactor me!”. And now you make me go back! At least you end up with more work now as well 😬. Sorry Jason!

**Comment by robdekort** [comment]
FYI: I just tested, but using or doesn't make a difference.

**Comment by damcclean** [comment]
I wonder if this is the same issue as someone's having on the Lodge... https://statamic.com/forum/4944-conditional-if-inside-template

**Comment by robdekort** [comment]
Oh yeah, that looks exactly the same indeed!

**Comment by ashbakernz** [comment]
> I wonder if this is the same issue as someone's having on the Lodge... https://statamic.com/forum/4944-conditional-if-inside-template

Yep, this is me. I cannot seem to resolve it. Maybe I'll take a look at the source code and try to figure it out.

**Comment by robdekort** [comment]
🦩
