### ISSUE TITLE
Hideous Antlers statement not working

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2723]
## Bug Description
Don't judge, but this should work right? Found a workaround for this one but might be important to know.

`{{ if (pin:collection == 'events' && pin:event_date|is_today) || pin:collection != 'events' }}`

`pin` is an `entries` field with `max_items: 1`.

## How to Reproduce
Add a collection called 'events'
Add a field to that blueprint field called event_date.
Use an entries field to add entries to a page 
Loop through the entries
Use the above logic in your template.

## Extra Detail
<img width="1445" alt="Screenshot 2020-10-23 at 15 59 01" src="https://user-images.githubusercontent.com/69107412/97013012-cf056d00-1548-11eb-8521-fef22a8f79b1.png">

## Environment
Statamic 3.0.20 Pro
Laravel 7.28.4
PHP 7.4.10
edalzell/mailchimp 2.1
jonassiewertsen/statamic-livewire 2.1.1

**Comment by jasonvarga** [comment]
Basically the same as #2722 that you just opened.

**Comment by robdekort** [comment]
Glad you picked this one to close ;-).
