### ISSUE TITLE
Search score not included in output

### ISSUE THREAD

**Issue by tomhelmer** [statamic/cms#2728]
## Bug Description
The `search_score` as mentioned in the documentation https://statamic.dev/tags/search#variables is not included in the output.

## How to Reproduce

- make search template with `{{ dump }}` inside `search:results` tag using the `local` driver
- or add `{{ search_score }}` inside the `search:results` loop

## Environment

Statamic 3.0.20 Pro
Laravel 7.28.4
PHP 7.4.9

**Comment by EricBusch** [comment]
I'm also experiencing the exact same issue.

Statamic 3.0.27
Laravel 8.13.0
PHP 7.4.11
