### ISSUE TITLE
Fieldtype 'radio' shows key instead of label

### ISSUE THREAD

**Issue by Winitoe** [statamic/cms#2730]
## Bug Description
In a collections table of entries when adding a column of fieldtype 'radio' the values are the option keys instead of the labels.

## How to Reproduce
1. Create a field of type 'radio' in a collection with some options.
2. Add this field as a column to the collection table of entries.
3. Create an entry and choose an option of the radio field.

## Extra Detail
I tried with the 'select' field, this does give the expected result.

## Environment
**Statamic version:** 3.0.20
**PHP version:** 7.4.11

**Comment by damcclean** [comment]
I've submitted a pull request to fix this issue: #2731.
