### ISSUE TITLE
BuilderTest not compatible w/ Composer 2.0

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2732]
## Bug Description

`BuilderTest.php` is not compatible w/ Composer 2.0

## How to Reproduce

1. Run composer install on the Statamic project

## Extra Detail
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/6069653/97094568-a3e35200-160a-11eb-8984-22ed769fdbd0.png">

## Environment

**Statamic version:** 3.0.20

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
It might be worth Statamic running it’s test suite for both Composer 1 and 2 for at least a little while.
