### ISSUE TITLE
is_url Modifier returns false on entry

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2739]
## Bug Description
The `is_url` modifier returns `false` on a variable that links to an entry. It should return `true`.

## How to Reproduce
1. Add a link fieldtype to your blueprint
2. Select an entry
3. Use the `is_url` modifier on the variable in your template

## Environment
Statamic 3.0.20 Pro
Laravel 8.11.2
PHP 7.4.9
aerni/zipper 1.1.0

**Comment by jasonvarga** [comment]
Why would is_url be true on an entry? It's an entry, not a url.

**Comment by aerni** [comment]
Let's say you have a Link Fieldtype with the handle `link` and select an entry. The data will be saved as `link: 'entry::my-entry'`. In the view `{{ link }}` will be augmented to the URL of the entry. And that URL is relative like `/my-entry`. As of now, the `is_url` modifier will return false. It should return true though, as it's a URL.

**Comment by jasonvarga** [comment]
My mistake, I think I read this as "entries" fieldtype, not "link" fieldtype.

**Comment by aerni** [comment]
Sorry for the confusion 😅
