### ISSUE TITLE
Multi-site: {{ nav from="/{segment_1}" }} fails on non-default sites

### ISSUE THREAD

**Issue by remiduval** [statamic/cms#2741]
## Bug Description
`{{ nav from="/{segment_1}" }}` fails on non-default sites

## How to Reproduce
`config/statamic/sites.php`
```
    'sites' => [
        'french' => [
            'name' => 'French',
            'locale' => 'fr_FR',
            'url' => '/fr/',
        ],
        'english' => [
            'name' => 'English',
            'locale' => 'en_GB',
            'url' => '/en/',
        ],
        'portuguese' => [
            'name' => 'Portuguese',
            'locale' => 'pt_PT',
            'url' => '/pt/',
        ],
    ],
```

All 3 sites have this page tree:
- Page 1
  - Page 1.1
  - Page 1.2

`page.antlers.html`
```
{{ nav from="/{segment_1}" }}
    <li>
       {{ title }}
    </li>
{{ /nav }}
```

Works on /fr site, error on /en and /pt site:
`Call to a member function id() on null`

## Environment

Statamic 3.0.20 Pro
Laravel 7.28.4
PHP 7.3.11
4rn0/statamic-v3-image-optimizer 1.0.4
spatie/statamic-responsive-images 1.3.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by Pfeifakopf** [comment]
Should be the same: #2269

**Comment by remiduval** [comment]
Solved by https://github.com/statamic/cms/issues/2269#issuecomment-724886455
