### ISSUE TITLE
Unable to unlocalize slug in the blueprint builder

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2743]
## Bug Description
It's not possible to set the slug to `localizable: false` in the blueprint builder. After save and reload, the slug is localizable again. Manually setting `localizable: false` in the blueprint works as expected.

## How to Reproduce
1. Create a collection on a multi-site and click the globe icon in the blueprint builder to remove localization on the slug. 
2. Reload.
3. The slug is localizable again.

## Environment
Statamic 3.0.20 Pro
Laravel 8.11.2
PHP 7.4.9
aerni/zipper 1.1.0

**Comment by aerni** [comment]
Still an issue.

**Comment by jasonvarga** [comment]
#8926 was attempting to fix this, which I reverted in #9094 because it caused an unrelated issue.

But it looks like this issue isn't there anymore anyway. You can make the slug field un-localizable.
