### ISSUE TITLE
Static cache expiry config key is wrong

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#2744]
## Bug Description

You should be able to define the `expiry` as explained in the docs. Currently it uses what looks like a ported v2 version.

This needs to be backwards compatible, since users may have worked out that you can define `default_cache_length`. (We should check for `expiry` _and_ `default_cache_length`).

## Extra Detail

https://github.com/statamic/docs/pull/294

## Environment

**Statamic version:** 3.0.20

**Comment by jelleroorda** [comment]
Would it be an idea to change this to "default" laravel behaviour as well, by choosing an expiry in seconds instead of minutes?

**Comment by okologisk** [comment]
After updating to 3.0.38, it looks like cache is not clear - even when clearing via CP.

`'strategies' => [

        'half' => [
            'driver' => 'application',
            'expiry' => 5,
        ],

        'full' => [
            'driver' => 'file',
            'path' => public_path('static'),
            'lock_hold_length' => 0,
        ],

    ],
`

**Comment by jasonvarga** [comment]
Provide some more details in a separate issue please.
