### ISSUE TITLE
Update composer requirement?

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2746]
## Bug Description

Composer 2 has been released, might be worth updating the internal requirement?

## How to Reproduce

Run composer update:

## Extra Detail
<img width="430" alt="image" src="https://user-images.githubusercontent.com/6069653/97245369-22c9bd80-17b8-11eb-8562-9a4127316f57.png">

**Comment by jasonvarga** [comment]
If it ain't broke, don't fix it. 

When us using Composer 1 is an issue for someone, we can revisit this.

**Comment by jasonvarga** [comment]
(Added anyway in a4b2e790393d4763ba0194643341a62841b71b39)
