### ISSUE TITLE
Mail Notifications unstyled

### ISSUE THREAD

**Issue by admench** [statamic/cms#2747]
## How to Reproduce
`composer create-project --prefer-dist statamic/statamic test`
`php artisan make:notification TestNotification`

...set up mail sending for mailtrap and add in default from address to `.env`
```
Illuminate\Support\Facades\Notification::route(
    'mail',
    'my@email.com'
)->notify(new App\Notifications\TestNotification());
```

...then do the same but using `laravel new test`

## Extra Detail

Result from new statamic project:

<img width="979" alt="Screenshot 2020-10-27 at 11 39 20" src="https://user-images.githubusercontent.com/672916/97296878-2c4f3600-1849-11eb-97c0-0fab5f5ef1c4.png">

Result from new laravel `8.11.2` project:

<img width="940" alt="Screenshot 2020-10-27 at 11 39 25" src="https://user-images.githubusercontent.com/672916/97296897-34a77100-1849-11eb-9911-9723378f8e43.png">

## Environment

```
Statamic 3.0.20 Solo
Laravel 8.11.2
PHP 7.4.8
No addons installed
```

**Comment by edalzell** [comment]
Guessing that Statamic doesn't "register" that theme folder?

**Comment by admench** [comment]
This bug still exists in `statamic/cms 3.0.22` - any reason why this is closed?

**Comment by edalzell** [comment]
It's not closed?
<img width="514" alt="image" src="https://user-images.githubusercontent.com/6069653/97607128-d657cb00-19cd-11eb-80db-fbe35867905c.png">

**Comment by admench** [comment]
Sorry man - I mistook the Closed tag in the #2760 issue.

My bad. Many thanks

**Comment by mikefrancis** [comment]
Just stumbled across this bug in a non-Statamic app so posting my solution here just in case it helps anyone.

I had the file `./resources/views/default.blade.php` - if I rename this I get the styling back.

Somehow this must be overriding the markdown email's default theme layout.

**Comment by admench** [comment]
Thanks for the tip @mikefrancis .

I don't have that view, but I do have the statamic standard `resources/views/default.antlers.html`

Can you clarify what renaming action you actually did?

**Comment by mikefrancis** [comment]
@admench I just renamed `./resources/views/default.blade.php` to `./resources/views/something.blade.php` and updated any child views that were extending the `default` view from:

```
@extends('default')
```

to:

```
@extends('something')
```

**Comment by admench** [comment]
Yes I can confirm this fixes the styling issue with Notifications.

@jasonvarga can you possibly investigate this possible naming convention clash?

New notification after renaming `default.antlers.html` to `main.antlers.html`:

<img width="671" alt="Screenshot_2020-11-03_at_08_35_51" src="https://user-images.githubusercontent.com/672916/97963818-a5054380-1daf-11eb-932e-99e264b6c6cf.png">

**Comment by damcclean** [comment]
Looks like the only place in the Laravel codebase that mentions `default` in the context of emails/notifications is in [this file](https://github.com/laravel/framework/blob/5f78c90a7af118dd07703a78da06586016973a66/src/Illuminate/Mail/Markdown.php#L46).

I've had a similar look at the Statamic codebase but couldn't find anything with `default` coded in, again with the context of mail.

**Comment by damcclean** [comment]
Someone just ran into this same issue on the Discord this afternoon so I've re-opened. [Link to conversation](https://discord.com/channels/489818810157891584/489819906540568593/805480000748519444)

**Comment by robdekort** [comment]
Yep, still an issue indeed in 3.0.42.

**Comment by duncanmcclean** [comment]
I'll hopefully have time to look at this over the next couple of days, got a project where it's pretty important the notification styles work. 😅

**Comment by philipboomy** [comment]
I think this stale bot should be removed. It keeps closing issues that is not fixed yet.

**Comment by philipboomy** [comment]
I forgot to mention that it is working for v2 updates to V3

**Comment by duncanmcclean** [comment]
Just managed to replicate and I think I've figured out why it's trying to find a `default` view.

Essentially, Laravel has a concept of themes for its emails so you can customise the CSS & HTML in your emails. The default theme is `default`.

Laravel tries to find a view called `default`, the first one it can find is the one in `resources/views/default.antlers.html`, hence why it uses that view instead.

A **workaround** for now would be to create your own mail theme, there's documentation on that over in the [Laravel docs](https://laravel.com/docs/master/notifications#customizing-the-css).

Make sure to change the theme in your `config/mail.php` file as that's where the current theme is configured.

**Comment by admench** [comment]
Thanks for investigating.

@jackmcdade this seems to be something that should be in the docs.

**Comment by philipboomy** [comment]
@duncanmcclean Thanks for looking into it. On a V2 upgrade to V3 I have a default.antlers.html and it's still working. I get the styling correctly.

**Comment by duncanmcclean** [comment]
> @duncanmcclean Thanks for looking into it. On a V2 upgrade to V3 I have a default.antlers.html and it's still working. I get the styling correctly.

That's weird, I'm guessing it's in the default place (`resources/views`) and `theme` is set to `default` in your `config/mail.php`?

**Comment by philipboomy** [comment]
Yeah - I tried finding the difference between the two setups yesterday.

https://share.getcloudapp.com/p9u8GeJe

**Comment by duncanmcclean** [comment]
> Yeah - I tried finding the difference between the two setups yesterday.
> 
> https://share.getcloudapp.com/p9u8GeJe

Hmm, that's strange. I'm not sure why that would be happening.

**Comment by philipboomy** [comment]
Did you manage to get the new mail theme working?

**Comment by duncanmcclean** [comment]
> Did you manage to get the new mail theme working?

Yeah, we're using one anyway on this project.

**Comment by mikemartin** [comment]
@duncanmcclean I just ran into this myself. Seems like the workaround is:

1. `php artisan vendor:publish --tag=laravel-mail`
2. Rename `default.css` to your new theme name. ie.`theme.css`
3. Set the theme to your theme name in /config/mail.php

**Comment by jasonvarga** [comment]
I PR'd a fix to Laravel. Once the next `laravel/framework` release is tagged you should be able to `composer update` and it'll be fixed. (Assuming you're using Laravel 8)
