### ISSUE TITLE
Error submitting forms in FormController; Call to a member function shortLocale() on null

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2748]
## Bug Description

When trying to submit my form, i get the following error:
`[2020-10-28 01:54:50] local.ERROR: Call to a member function shortLocale() on null {"exception":"[object] (Error(code: 0): Call to a member function shortLocale() on null at /Users/pixney/Development/Web/xx/vendor/statamic/cms/src/Http/Controllers/FormController.php:49)`

When dumping $site in the FormController that is null.

More people has reported having this issue in Discord, so it should be a verified existing issue for more instances than mine:
- https://discord.com/channels/489818810157891584/489819906540568593/767370134167224320
- https://discord.com/channels/489818810157891584/489819906540568593/767666364805677067
- https://discord.com/channels/489818810157891584/489819906540568593/768550145624899584

I just updated from v3.0.12 where it works. 

**Statamic version:** 3.0.20

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by Pixney-William** [comment]
My site config as follows 

```
'sites' => [

    'default' => [
        'name' => config('app.name'),
        'locale' => 'en_US',
        'url' => env('APP_URL'),
    ]

]
```

**Comment by jasonvarga** [comment]
What URL is your form on?

**Comment by Pixney-William** [comment]
So just found that it only occur when you are on Localhost, if you are on "example.test" instead of "localhost:3000", it works.

**Comment by jasonvarga** [comment]
Yes. You should use the URL that you've defined in your config.

**Comment by Pixney-William** [comment]
All good! Thanks and no worries!
