### ISSUE TITLE
Make container field required when adding an asset field

### ISSUE THREAD

**Issue by freshface** [statamic/cms#2752]
## Bug Description

When i add an asset field to a blueprint the container is not required.
But if i use the blueprint on a collection i get an error that i need de define an container.

## Environment

**Statamic version:** 3.0.20

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Related to #1166.

**Comment by jasonvarga** [comment]
Closing this as it's pretty vague. When/where do you get that error?
There are other issues opened that are similar, I'm going to assume they are for the same thing.
