### ISSUE TITLE
Select field max 1 items causes issues

### ISSUE THREAD

**Issue by philipboomy** [statamic/cms#2756]
## Bug Description
Cannot change dropdown selection when using max items 1 - I later found out I dont that setting as I have not toggled on multiple selection however this is still a bug that can cause issues in the future or for other people

## How to Reproduce
Create a select field
Set max-item 1
Go to entry and select in dropdown.
See red validation issue https://share.getcloudapp.com/YEuyexzr
You cannot change the dropdown now.

## Extra Detail
The red 9 in the above screenshot is actually not the amount of selections but its the length of the key in the dropdown. The key is full-time which is 9 characters.

https://share.getcloudapp.com/eDuPrqZ9

## Environment

Statamic 3.0.20 Pro
Laravel 8.11.2
PHP 7.4.8

**Install method (choose one):**
- Starter kit: The Amazing Peak

**Comment by philipboomy** [comment]
wwwwwwwwww

Kind regards
Philip Thygesen
Boomy.co.uk <https://www.boomy.co.uk/>

**Comment by arthurperton** [comment]
This works well now in the latest version. It looks it was fixes in [this commit](https://github.com/statamic/cms/commit/7ce0200f).

I am closing the issue now.
