### ISSUE TITLE
Nav tag with include_home="false" still shows home if it's the only entry

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#2757]
## Bug Description

Nav tag using structured collection and include_home="false" still shows home if it's the only entry.

## How to Reproduce

In a stock Statamic base install, add this to the layout.

```
{{ nav:collection:pages include_home="false" }}
    <a href="{{ url }}">{{ title }}</a>
{{ /nav:collection:pages }}
```

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This a no_results situation. It's falling back to the current page, which is home.

The ol' `if/unless no_results` condition trick will sort that out.

```
{{ nav:collection:pages include_home="false" }}
   {{ unless no_results }}
      <a href="{{ url }}">{{ title }}</a>
   {{ /unless }}
{{ /nav:collection:pages }}
```

Or, just add more pages. Only having a home page is probably a problem just when you're starting development.
