### ISSUE TITLE
Setting parent field in entry edit / .md, doesn't update collection structure tree

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#2762]
## Bug Description
If you set the parent field of an entry in a orderable collection, it doesn't update the structure tree on the collection .yaml.

## How to Reproduce

1. Clean install 3.0.21
2. Make an orderable collection called `Test collection`
3. Add entry called `Test parent`
4. Create entry called `Test child` and set its parent to `Test parent`
5. Confirm that works.
6. Now create an entry via the Entry facade make method (I'm using Tinkerwell):

```php
$entry = \Statamic\Facades\Entry::make()  
  ->collection('test_collection')
  ->slug('test-child-api')
  ->locale('default')
  ->published(true)
  ->data([
    'title' => 'Test child via API',
    'parent' => 'use-your-parent-id-here', // e.g. b802f28f-60fe-44ba-abe5-099f5e036232
  ]);

$entry->save();
```
7. Now check the tree view / `test_collection.yaml` to confirm the collection tree is not updated.

**Statamic version:** 3.0.21
**PHP version:** 7.4
**Fresh install from `statamic/statamic`**

**Comment by johncarter-** [comment]
I have posted a hacky resolution to this on the forum. But is there a better way to do this:

```php
// Create the entry as above, then 
$entry->structure()
    ->in($entry->locale())
    ->appendTo('use-your-parent-id-here', $entry)
    ->save();
```

**Comment by jasonvarga** [comment]
The `parent` variable is not a thing. Inserting the entry into the tree is the way to go.

The parent field you see in the edit page of the CP is just to control where it gets inserted into the structure. It doesn't actually save a variable.

**Comment by johncarter-** [comment]
Thanks for your time Jason.
