### ISSUE TITLE
Issue accessing validate attribute in published form views

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2765]
## Bug Description / How to Reproduce
I have published the form views.
I have set a field to be required. I am able to show the display value and placeholder values correctly using `{{display}} and {{placeholder}}`.

When i am trying to display the validate attribute using `{{validate}}` it returns nothing. Dumping (see image) shows that the value is there. 

Is this a bug or what am i missing?

This worked in 3.0.12, but not in the latest 3.0.22

## Extra Detail
![Screenshot 2020-10-29 at 19 27 54](https://user-images.githubusercontent.com/31292231/97616454-e054ea80-1a1c-11eb-90e0-0086aa83a6c4.png)

## Environment

Statamic 3.0.22 Pro
Laravel 7.29.1
PHP 7.4.11
doublethreedigital/duplicator 1.1.1
pixney/statamic-image-generator 1.0.0-beta.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by Pixney-William** [comment]
To continue this, i also wonder if there is a regex issue with antlers or am i doing something wrong because this seems wrong to me : 

```
{{ if display == "What's your name?*" }}
    This is not printed, even though it's true.
{{ /if }}
```

Some examples : 

```
{{ if width == "50" }}
    This is printed.
{{ /if }}

{{ if display == "What's your name?*" }}
    This is not printed, even though it's true.
{{ /if }}

{{ if validate == "kimwildeinthe80s" }}
    This is printed even though it's false
{{ /if }}

{{ if validate == "Required" }}
    This is printed as well, and should be printed
{{ /if }}

```

**Comment by jasonvarga** [comment]
Can you please provide your entire template?

**Comment by Pixney-William** [comment]
It won't help you. But here it is : 

```

<div
    class="o-form-field col-span-12 {{ if width == 25 }} lg:col-span-3 {{ /if }} {{ if width == 33 }} lg:col-span-4 {{ /if }} {{ if width == 50 }} lg:col-span-6 {{ /if }} {{ if width == 66 }} lg:col-span-8 {{ /if }} {{ if width == 75 }} lg:col-span-9 {{ /if }} {{ if width == 100 }} lg:col-span-12 {{ /if }}">
    <label class="c-form-label">{{ display }}</label>
    <input class="c-form-input w-full" name="{{ handle }}" value="{{ old }}" placeholder="{{ placeholder }}"
        {{ validations laravelValidationString='{{validate}}' }}
        data-pristine-required-message="{{instructions}}"
        data-pristine-minlength-message="{{instructions}}"
        data-pristine-maxlength-message="{{instructions}}"
        data-pristine-number-message="{{instructions}}"
        data-pristine-min-message="{{instructions}}"
        data-pristine-email-message="{{instructions}}"
        type="{{ if input_type=='text' || input_type=='email' || !input_type }}text{{ else }}{{input_type}}{{ /if }}">
    <div class="pristine-error c-form-field-error"></div>
</div>
```

**Comment by Pixney-William** [comment]
Maybe i miss-understood what you needed though?

**Comment by Pixney-William** [comment]
Hmm, i just went back to 3.0.12, and it actually has the same problem. So not sure what version this started failing at.

**Comment by Pixney-William** [comment]
Basically what i did ( way back.. ) is publishing according to this : https://statamic.dev/tags/form-create#dynamic-rendering . Looking at it, it does not say i should have the validate attribute. However, it is there when i dump.

**Comment by Pixney-William** [comment]
Unless i re-save it works, because of the old data. But i guess there is a change from earlier with the new validation introduces. Because i have a string there, and according to people in discord it should now be an array.

**Comment by Pixney-William** [comment]
So this is the diff, if i after your validation change removes the required, then save the blueprint, then add required back and save : 

![image](https://user-images.githubusercontent.com/31292231/97620343-be119b80-1a21-11eb-9d45-c1c5cd9a1b0b.png)

**Comment by Pixney-William** [comment]
Ok.. unless you think this has something to do with the system, i guess you can close it @jasonvarga 

I had a custom implementation using the validate field. And since that was earlier saved as a string, and after an update at some point you now store it as an array, it broke it for me.

So ill just rewrite that to use an array instead.

**Comment by jackmcdade** [comment]
Glad you got it sorted! 👏
