### ISSUE TITLE
Editing a non localizable field on the origin, does not update the localized read only fields

### ISSUE THREAD

**Issue by martink635** [statamic/cms#2769]
## Bug Description
On a multisite, when editing the origin entry - a read only (non localizable) field in my case a **replicator** - the localized entries still keep the old values.

It's a bit weird that the read only data gets pushed to the localized entries, and currently it is not kept in sync. I had to manually remove and save again all entries in order for the new values to get copied over. Since we have the origin id I don't see the point in having the read only data stored in the localized entry yaml file.

I am open to hepling with this issue if you can point me what an acceptable fix would be (keeping them in sync or not storing read only data at all)

## How to Reproduce

- Have a multiste with at least 2 locales
- Have some read only fields (editable only on the origin)
- Change the value of the read only field
- Save the entry
- Data is not the same on the localized version

## Environment

Statamic 3.0.22 Pro
Laravel 7.28.3
PHP 7.4.5

**Statamic version:** 3.0.22

**PHP version:** 7.4

**Install method (choose one):**
- Other

A plain basic multisite with some non localizable fields and at least 2 locales/sites is needed to reproduce this error. I can provide a simple site if required.

**Comment by jasonvarga** [comment]
Are these fields at the top level of your blueprint? Or are they _inside_ another field like a Replicator or Grid?

**Comment by martink635** [comment]
Yes, now that you mention it it's always in the replicator. But the whole replicator field is not localizable, so I would assume it does not act like this

**Comment by jasonvarga** [comment]
Only top level fields are localizable. ie. the entire replicator. You can't control individual child fields unfortunately. So if you edit the replicator at all, the whole replicator is saved in the localized entry.

**Comment by martink635** [comment]
That makes sense Jason, as you can't possibly know how to connect them/sync them. 

But shouldn't it be that if the top level replicator is not localizable that it's not copied?

**Comment by martink635** [comment]
@jasonvarga I'd hate to reopen it, not sure if you get notifications on closed issues, but like I said, not trying to control child fields, but the whole replicator is not localizable and it still gets copied over. 

Is this also how it should behave?
