### ISSUE TITLE
Toggles in a grid aren't centred in publish forms

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2770]
## Bug Description

If you put a toggle in between two text fields in a grid, the toggle is not centred vertically nor horizontally.

## How to Reproduce

In a grid, put toggle between two text fields.

## Extra Detail

<img width="380" alt="image" src="https://user-images.githubusercontent.com/6069653/97654584-72aabd80-1a20-11eb-90c6-0c3db5173881.png">

## Environment

Statamic 3.0.20 Pro
Laravel 7.28.4
PHP 7.4.11

**Comment by robdekort** [comment]
Probably the same as #2518

**Comment by edalzell** [comment]
Duplicate of #2518
