### ISSUE TITLE
Live Preview: Translate Tag doesn't work

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2775]
## Bug Description
The Translate Tag doesn't work in Live Preview.

## How to Reproduce
Add a `{{ trans }}` tag to a view, eg. `{{ trans:auth.failed }}`, and look at it in the CP Live Preview.

## Extra Detail
<img width="1712" alt="Bildschirmfoto 2020-10-30 um 16 49 30" src="https://user-images.githubusercontent.com/23167701/97726913-08e9ec80-1ad0-11eb-857e-c0e9d16e7ffd.png">

## Environment
Statamic 3.0.22 Pro
Laravel 8.12.3
PHP 7.4.9
aerni/zipper 1.2.0

**Comment by damcclean** [comment]
Looks like it's working fine me to me. I added `{{ trans:auth.failed }}` to the top of my layout, in the site name. Are you using custom translations?

![image](https://user-images.githubusercontent.com/19637309/97805194-85a1d580-1c4c-11eb-9986-3574afd71606.png)

**Comment by aerni** [comment]
Yes, I'm using custom translation files. Good catch, Duncan.

**Comment by damcclean** [comment]
> Yes, I'm using custom translation files. Good catch, Duncan.

Ah cool. I'll recreate this issue when I have some time over the next few days.

**Comment by damcclean** [comment]
Hmm, I'm still unable to recreate, even after creating a custom translation file. Here's what I'm doing, let me know if you're doing something different:

**`resources/lang/en/shop.php`**

```php
<?php

return [
	'cart' => 'Basket',
];
```

**`resources/views/_nav.antlers.html`**
```html
{{ trans:shop.cart }}

<!-- The rest... -->
```

**Live Preview screenshot (string is shown on top left of preview frame)**
![image](https://user-images.githubusercontent.com/19637309/98176467-85c1ff80-1ef0-11eb-98f1-13a73500c55e.png)


Just a quick thought: Does the page you're on have a locale/site set? You should be able to check either using the `{{ dump }}` tag or by outputting the `{{ site }}` variable.

**Comment by aerni** [comment]
Another good catch. Yes, it's a multi-site setup and the collection has a site set.

**Comment by robdekort** [comment]
Do you get back the correct {{ site:handle }} in live preview @aerni?

**Comment by aerni** [comment]
@robdekort No, I also get the wrong site handle.

**Comment by robdekort** [comment]
Aight, thanks. Def. a bug then.

**Comment by RafaelKr** [comment]
Same issue for me. I have a multisite setup with language DE and EN. DE is my primary locale. I have a Global Set named `translations`.

In my template I use it like this: `{{ translations:form_job_applications_salutation }}`

When I open the Live Preview for the EN page the translations for the DE locale are shown. It works on the frontend, though.

It's a repository in a private GitLab. I can give access to it when it helps with debugging.
