### ISSUE TITLE
anchor not possible in collection route

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#2779]
## Bug Description
I'm not sure, if it's a bug or a missing feature.

I've tried in my collection this route :
```
{mount}#{slug}
```
But the anchor was removed in the url, the output was `{mount}{slug}`.

## How to Reproduce
Set collection route to `{mount}#{slug}`

## Environment

**Statamic version:** 3.0.21

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by wm-simon** [comment]
This is still an issue.

**Comment by jasonvarga** [comment]
I'm not sure this is something we need to support.

There'd be no way to visit "the entry URL".

For example:

If your route is `/foo#{slug}` then when you go to `/foo#the-slug` you'd actually be on `/foo`, so it's not the URL of the entry.

I guess if you're fine with that, then okay.

Leave a comment if this is really something you need/want.
