### ISSUE TITLE
Partials loading duplicates 

### ISSUE THREAD

**Issue by DrTrills** [statamic/cms#2785]
## Bug Description
My partials are loading multiple times. For example I have partials for components which I am editing in the CP (reusable components from my theme, e.g CTA box/button). I load the code into my partial 

## How to Reproduce

**Original Code**

```
<!-- CTA Section -->
<div class="container">
  <div class="w-lg-85 mx-lg-auto">
    <div class="card overflow-hidden p-5">
      <div class="row justify-content-md-start align-items-md-center text-center text-md-left">
        <div class="col-md-8 col-lg-5 offset-lg-3 mb-3 mb-md-0">
          <h3 class="h4 text-indigo mb-0">Revolutionizing the way your team works!</h3>
        </div>

        <div class="col-md-4 text-md-right">
          <a class="btn btn-primary transition-3d-hover" href="#">Explore Docs</a>
        </div>
      </div>

      <!-- SVG Component -->
      <figure class="w-35 position-absolute top-0 left-0 mt-n11 ml-n11">
        <img class="img-fluid" src="../../assets/svg/components/half-circle-2.svg" alt="Image Description">
      </figure>
      <!-- End SVG Component -->
    </div>
  </div>
</div>
<!-- End CTA Section -->
```

**Modified code**

```
{{# CTA Section #}}
<div class="container {{ spacing_options ?? 'space' }}-{{ space_size ?? '0' }}">
  <div class="w-lg-85 mx-lg-auto">
    <div class="card overflow-hidden p-5">
      <div class="row justify-content-md-start align-items-md-center text-center text-md-left">
        <div class="col-md-8 col-lg-5 offset-lg-3 mb-3 mb-md-0">
          {{ text | wrap:h3.h4 text-indigo mb-0 }}
        </div>

        <div class="col-md-4 text-md-right">
          <a class="btn btn-primary transition-3d-hover" href="{{ link }}">{{ btn_text ?? 'Click'}}</a>
        </div>
      </div>

      {{# SVG Component #}}
      <figure class="w-35 position-absolute top-0 left-0 mt-n11 ml-n11">
        <img class="img-fluid" src="{{ background_image ?? '../../assets/svg/components/half-circle-2.svg' }}" alt="Image Description">
      </figure>
      {{# End SVG Component #}}
    </div>
  </div>
</div>
{{# End CTA Section #}}
```

## Extra Detail

When I call this code into my page, it loads twice. For a work around, I found adding the if statement around the text **{{ if layout_type == "component-3"}}** and then select the component style within the CP specifically will load the component 1 time.

I am loading these components into a replicator and then editing the editable content from the replicator as my page editor.

Screenshot with no if statement
<img width="1208" alt="Screen Shot 2020-11-02 at 12 23 03 AM" src="https://user-images.githubusercontent.com/1430005/97818234-b4966680-1ca1-11eb-853d-f2f90249fbeb.png">

With if statement 
<img width="1142" alt="Screen Shot 2020-11-02 at 12 24 19 AM" src="https://user-images.githubusercontent.com/1430005/97818251-cd068100-1ca1-11eb-939b-c64156859a9d.png">

## Environment

Statamic 3.0.22 Pro
Laravel 7.29.2
PHP 7.4.8
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Please show the replicator template loop.
