### ISSUE TITLE
Live Preview not correctly loading all images/assets

### ISSUE THREAD

**Issue by DrTrills** [statamic/cms#2786]
## Bug Description
When using Live Preview, not all the images/assets are loading. When i save/ view the published page all assets load as expected. 

## How to Reproduce

Use Live preview with many assets. In my case some SVGs load and others don't.

## Extra Detail

In this screenshot we see one SVG correctly loading (man sitting) but the CTA box under has no backgound image loaded (works fine in browser, screenshot can be seen in this issue: https://github.com/statamic/cms/issues/2785
<img width="1763" alt="Screen Shot 2020-11-02 at 12 28 22 AM" src="https://user-images.githubusercontent.com/1430005/97818374-54ec8b00-1ca2-11eb-8ab5-6bc25b318423.png">

Same here from live preview:
<img width="832" alt="Screen Shot 2020-11-02 at 12 30 58 AM" src="https://user-images.githubusercontent.com/1430005/97818427-b7458b80-1ca2-11eb-9756-f6e6125c2227.png">

how it correctly loads on the site
<img width="319" alt="Screen Shot 2020-11-02 at 12 31 24 AM" src="https://user-images.githubusercontent.com/1430005/97818437-bf053000-1ca2-11eb-968c-e80283c7fe1c.png">

Environment
Statamic 3.0.22 Pro
Laravel 7.29.2
PHP 7.4.8
No addons installed

Install method (choose one):

Fresh install from statamic/statamic

**Comment by jasonvarga** [comment]
Please show the template code for where you are loading the svg.

**Comment by DrTrills** [comment]
After getting the code it seems the common theme is anything with hardcoded URL to assets doesn't load in preview, but things selected by the media manager do load. Code below:

Code for the nav with USA flag for language drop down. Hardcoded SVG
```
        {{# Language #}}
        <div class="hs-unfold">
          <a class="js-hs-unfold-invoker dropdown-nav-link dropdown-toggle d-flex align-items-center" href="javascript:;"
             data-hs-unfold-options='{
              "target": "#languageDropdown",
              "type": "css-animation",
              "event": "hover",
              "hideOnScroll": "true"
             }'>
            <img class="dropdown-item-icon mr-2" src="../../assets/vendor/flag-icon-css/flags/4x3/us.svg" alt="SVG">
            <span class="d-inline-block d-sm-none">US</span>
            <span class="d-none d-sm-inline-block">United States</span>
          </a>

          <div id="languageDropdown" class="hs-unfold-content dropdown-menu">
            <a class="dropdown-item active" href="#">English</a>
            <a class="dropdown-item" href="#">Deutsch</a>
            <a class="dropdown-item" href="#">Español‎</a>
          </div>
        </div>
        {{# End Language #}}
```

Hero. The SVG loading in the screenshot above is selected in the CP and not the hardcoded URL. 
```
{{# Hero Section #}}
<div class="container space-top-3 space-top-lg-2 space-bottom-2 space-bottom-lg-3">
  <div class="row justify-content-lg-between mb-7">
    <div class="col-md-6 col-lg-5">
      {{# Info #}}
      <div class="mb-5">
        {{ if enable_custom_title == "true" }}
        {{ title | wrap:h1.display-4.text-dark }}
        {{ else }}
        {{ hero_title | wrap:p.display-4.text-dark }}
        {{ /if }}
        {{ hero_body | wrap:p.text-dark }}
      </div>

      <div class="mb-3">
        {{ if enable_hero_buttons == "true" }}
        {{ partial:components/button }}
        {{ /if }}
      </div>
      {{# End Info #}}
    </div>

    <div class="col-md-6 d-none d-md-inline-block">
      {{# SVG Illustration #}}
      <figure class="w-100">
        <img class="img-fluid" src="{{ hero_image ?? '../../assets/svg/illustrations/hiker-man.svg' }}" alt="Image Description">
      </figure>
      {{# End SVG Illustration #}}
    </div>
  </div>
</div>
{{# End Hero Section #}}
```

## CTA - hardcoded SVG
```
<div class="container {{ spacing_options ?? 'space' }}-{{ space_size ?? '0' }}">
  <div class="w-lg-85 mx-lg-auto">
    <div class="card overflow-hidden p-5">
      <div class="row justify-content-md-start align-items-md-center text-center text-md-left">
        <div class="col-md-8 col-lg-5 offset-lg-3 mb-3 mb-md-0">
          {{ text | wrap:h3.h4 text-indigo mb-0 }}
        </div>

        <div class="col-md-4 text-md-right">
          <a class="btn btn-primary transition-3d-hover" href="{{ link }}">{{ btn_text ?? 'Click'}}</a>
        </div>
      </div>

      {{# SVG Component #}}
      <figure class="w-35 position-absolute top-0 left-0 mt-n11 ml-n11">
        <img class="img-fluid" src="{{ background_image ?? '../../assets/svg/components/half-circle-2.svg' }}" alt="Image Description">
      </figure>
      {{# End SVG Component #}}
    </div>
  </div>
</div>
```

**Comment by jasonvarga** [comment]
You definitely shouldn't be using `../../` in your URLs. Can't you use a root-relative url? `/something`

**Comment by damcclean** [comment]
Like Jason said, you shouldn't be using absolute URLs, they can often cause issues, like the one happening here. If you change the URLs to be relative instead, like `/assets/svg/components/half-circle-2.svg` it should start working.

As it's not really a Statamic bug, I'm going to close this issue now. If you're still having issues after converting to relative URLs, comment below and we can re open this issue.
