### ISSUE TITLE
Table Fieldtype - Not showing Close button when a Single Column is used

### ISSUE THREAD

**Issue by aadind** [statamic/cms#2790]
Bug Description
Insert A Table in bard content - table fieldtype does not allow deleting/removing row if there is only one column. 
## How to Reproduce
Create a bard content fieldtype --> Create a table fieldtype as a set. --> While inserting in the Content writing window insert a table in single column and multiple rows. The X button at right edge shows only if i add another column to it. [minimum two columns]. If i have to detele a row, then i have to add a column, delete the row i want, then delete the new column again to achieve it. 

## Extra Detail

![image](https://user-images.githubusercontent.com/13034288/97861888-7e50f980-1d2a-11eb-9691-91669440e8f9.png)

![image](https://user-images.githubusercontent.com/13034288/97861951-945eba00-1d2a-11eb-9e21-845d7c5c0e2c.png)

## Environment

**Statamic version:** 3.0.22

**PHP version:** 7.4

**Install method (choose one):**
-Migrated from Statamic v2

**Comment by jelleroorda** [comment]
Should stay open.
