### ISSUE TITLE
Slug not possible with default value

### ISSUE THREAD

**Issue by Lampone** [statamic/cms#2799]
## Bug Description
I have created a UUID Fieldtype which sets the value to default to a uuid string. If this fieldtype is a slug, the default value gets set to null.
This is the line that overrides a default value for slugs:
https://github.com/statamic/cms/blob/3e2df7260e80458b6d51a71726250987a2eea912/src/Http/Controllers/CP/Collections/EntriesController.php#L225

In the fieldtype the default value is set with the defaultValue function:
`    public function defaultValue()
    {
        return Str::uuid();
    }
`

## Extra Detail

I wanted to have uuid field as a slug so I don't have to deal with conflicts about slugs not being unique. 

## Environment

**Statamic version:3.0.20 Pro

**PHP version:7.4.10

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Just to confirm, you've created a field called `slug` with the UUID fieldtype you created and you've added that to a blueprint?

**Comment by Lampone** [comment]
Sorry for the delay. Just to clarify it can be any fieldtype, a defaultValue and naming the field "slug" is not possible. The defaultValue will be overwritten. 

The Uuid field with a default value:
```
<?php

namespace App\Fieldtypes;

use Illuminate\Support\Str;
use Statamic\Fields\Fieldtype;

class SlugUuid extends Fieldtype
{
    /**
     * The blank/default value.
     *
     * @return array
     */
    public function defaultValue()
    {
        return Str::uuid();
    }

    /**
     * Pre-process the data before it gets sent to the publish page.
     *
     * @param mixed $data
     * @return array|mixed
     */
    public function preProcess($data)
    {
        return $data;
    }

    /**
     * Process the data before it gets saved.
     *
     * @param mixed $data
     * @return array|mixed
     */
    public function process($data)
    {
        return $data;
    }
}
```

**Comment by damcclean** [comment]
Thanks for providing more information. I'll look into it later today.

**Comment by damcclean** [comment]
I can confirm this is a bug. No `default` set in the slug field seems to be used. I've tried this with the normal slug fieldtype, the text fieldtype and the textarea fieldtype.
