### ISSUE TITLE
`multisite` command fails w/ 'undefined offset' error

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2802]
## Bug Description

Created a brand new site, no content (only the default home page), then did `php please multisite` and got an error (see below.

Maybe exit with an explanation if `pro` isn't enabled?

## How to Reproduce

1. create site w/ `statamic new multi-site`
2. create user
3. run `php please multisite`

## Extra Detail

```
[2020-11-05 01:00:46] local.ERROR: Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:103)
[stacktrace]
#0 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php(103): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/Users/erin/Sit...', 103, Array)
#1 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php(121): Statamic\\Stache\\Stores\\CollectionEntriesStore->extractAttributesFromPath('/Users/erin/Sit...')
#2 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Stache/Stores/Store.php(223): Statamic\\Stache\\Stores\\CollectionEntriesStore->handleDeletedItem('/Users/erin/Sit...', 'home')
#3 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Statamic\\Stache\\Stores\\Store->Statamic\\Stache\\Stores\\{closure}('/Users/erin/Sit...', 0)
#4 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Stache/Stores/Store.php(225): Illuminate\\Support\\Collection->each(Object(Closure))
#5 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Stache/Stores/Store.php(38): Statamic\\Stache\\Stores\\Store->handleFileChanges()
#6 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Stache/Stores/CollectionsStore.php(81): Statamic\\Stache\\Stores\\Store->index('uri')
#7 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Stache/Repositories/CollectionRepository.php(83): Statamic\\Stache\\Stores\\CollectionsStore->updateEntryUris(Object(Statamic\\Entries\\Collection))
#8 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Stache\\Repositories\\CollectionRepository->updateEntryUris(Object(Statamic\\Entries\\Collection))
#9 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Entries/Collection.php(337): Illuminate\\Support\\Facades\\Facade::__callStatic('updateEntryUris', Array)
#10 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Entries/Collection.php(327): Statamic\\Entries\\Collection->updateEntryUris()
#11 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Console/Commands/Multisite.php(112): Statamic\\Entries\\Collection->save()
#12 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Console/Commands/Multisite.php(50): Statamic\\Console\\Commands\\Multisite->updateCollection(Object(Statamic\\Entries\\Collection))
#13 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Statamic\\Console\\Commands\\Multisite->Statamic\\Console\\Commands\\{closure}(Object(Statamic\\Entries\\Collection), 0)
#14 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Console/Commands/Multisite.php(52): Illuminate\\Support\\Collection->each(Object(Closure))
#15 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Statamic\\Console\\Commands\\Multisite->handle()
#16 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#18 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#19 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#20 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#21 /Users/erin/Sites/multi-site/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 /Users/erin/Sites/multi-site/vendor/statamic/cms/src/Console/EnhancesCommands.php(15): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /Users/erin/Sites/multi-site/vendor/symfony/console/Application.php(920): Statamic\\Console\\Commands\\Multisite->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /Users/erin/Sites/multi-site/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand(Object(Statamic\\Console\\Commands\\Multisite), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /Users/erin/Sites/multi-site/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /Users/erin/Sites/multi-site/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /Users/erin/Sites/multi-site/please(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 {main}
"} 
```
Statamic 3.0.24 Solo
Laravel 8.13.0
PHP 7.4.12
No addons installed
```
## Environment

Statamic 3.0.24 Solo
Laravel 8.13.0
PHP 7.4.12
No addons installed

**Comment by riasvdv** [comment]
I had the same error just now, but pro was enabled, so it might be something else

**Comment by cgrisar** [comment]
You don't need php please multisite to make your site multisite.
It's a tool, no more.

It should work if you set the config/statamic/sites.php correctly

This is mine:

```
'sites' => [

        'en' => [
            'name' => 'en',
            'locale' => 'en_US',
            'url' => '/',
        ],
        'fr' => [
            'name' => 'fr',
            'locale' => 'fr_FR',
            'url' => '/fr/',
        ],
        'nl' => [
            'name' => 'nl',
            'locale' => 'nl_NL',
            'url' => '/nl/',
        ],

```

**Comment by damcclean** [comment]
Hmm, I just tried to re-create this on a fresh site, with a single user and running the `php please multisite` command, the command worked properly and gave me the expected output (the updated sites config, see below).

![image](https://user-images.githubusercontent.com/19637309/98852851-36c81d00-2450-11eb-8f97-67d362e1c01c.png)

And when I update the sites config in the file, and try and open my site in a browser, I get the expected `Statamic Pro is required` error, along with the Ignition solution.

Is there anything else you might be doing that might be causing the issue?

**Comment by edalzell** [comment]
hit this again on an existing site with content, `pro` is `true`

**Comment by edalzell** [comment]
ok, think I may have found the issue; if you have updated the `sites` config, in my case to change the 'url' to `env('APP_URL')` it doesn't work and you get that error.

Changing it back to `'/'` makes it work.

**Comment by riasvdv** [comment]
Can't remember unfortunately

**Comment by gefangenimnetz** [comment]
I had the same issue. Problem was that the site handles "en", etc. are not allowed. Not even newsite_en is working. No special chars and no lang abbreviations are allowed as far as I can tell.

Go with "english", "frensh", etc.

**Comment by cgrisar** [comment]
@gefangenimnetz I can work with handles "en", "fr", "nl"

**Comment by dwainscheeren** [comment]
When will this be fixed?!

**Comment by damcclean** [comment]
> When will this be fixed?!

Whenever the Statamic team or a contributor finds the time to fix the issue.

**Comment by edalzell** [comment]
> When will this be fixed?!

@dwainscheeren did you see this: https://github.com/statamic/cms/issues/2802#issuecomment-726385101?

**Comment by dwainscheeren** [comment]
Yes, but my sites already has the / @edalzell

**Comment by tao** [comment]
I tried `php please multisite` on a fresh install of Statamic and it failed:

<img width="628" alt="Screenshot 2021-01-01 at 11 16 33" src="https://user-images.githubusercontent.com/1446331/103436307-d0c36f00-4c22-11eb-91c2-4864d7670067.png">

I used `Italian` as my second site because I thought it was asking me for the name to populate the config file... but I hadn't edited my config yet as the Statamic docs start with the instructions to just run the multisite command.

**Comment by damcclean** [comment]
> I tried `php please multisite` on a fresh install of Statamic and it failed:
> 
> <img alt="Screenshot 2021-01-01 at 11 16 33" width="628" src="https://user-images.githubusercontent.com/1446331/103436307-d0c36f00-4c22-11eb-91c2-4864d7670067.png">
> 
> I used `Italian` as my second site because I thought it was asking me for the name to populate the config file... but I hadn't edited my config yet as the Statamic docs start with the instructions to just run the multisite command.

What does your `config/statamic/sites.php` file currently look like?

**Comment by jasonvarga** [comment]
Have you done anything weird like changing where entries are stored?
We can't recreate this using a stock installation.

If someone continues to run into this issue, it would be really helpful you zip your site in the state *before* running the `multisite` command and send it to support@statamic.com

**Comment by tao** [comment]
I've run this again and encountered the same error, I'll email over a zip.

The steps to re-create it are:

1. `statamic new multisite-please`
2. `cd multisite-please`
3. `php please multisite`

If you leave "Handle of the second site" blank then it works fine and uses the default `two`. 

```bash
 The current site handle is [default], content will be moved into folders with this name. Is this okay? (yes/no) [no]:
 > yes

 Handle of the second site [two]:
 > 

[✓] Collection [pages] updated.
[✓] Done!
[!] Update config/statamic/sites.php's sites array to the following:
[
    'default' => [
        'name' => 'Statamic',
        'locale' => 'en_US',
        'url' => '/',
    ],
    'two' => [
        'name' => 'two',
        'locale' => 'en_US',
        'url' => '/two/',
    ],
]
```

If you enter a custom handle it fails.

```bash
 The current site handle is [default], content will be moved into folders with this name. Is this okay? (yes/no) [no]:
 > yes

 Handle of the second site [two]:
 > italian


   ErrorException 

  Undefined offset: 1

  at vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:103
     99▕         $collection = pathinfo($path, PATHINFO_DIRNAME);
    100▕         $collection = str_after($collection, $this->parent->directory());
    101▕ 
    102▕         if (Site::hasMultiple()) {
  ➜ 103▕             [$collection, $site] = explode('/', $collection);
    104▕         }
    105▕ 
    106▕         // Support entries within subdirectories at any level.
    107▕         if (Str::contains($collection, '/')) {

      +29 vendor frames 
  30  please:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

The error logged starts as follows:
```
[2021-01-07 18:40:32] local.ERROR: Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /Users/daniel/Code/statamic/multisite-please/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:103)
[stacktrace]
#0 /Users/daniel/Code/statamic/multisite-please/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php(103): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/Users/daniel/C...', 103, Array)
#1 /Users/daniel/Code/statamic/multisite-please/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php(121): Statamic\\Stache\\Stores\\CollectionEntriesStore->extractAttributesFromPath('/Users/daniel/C...')
```

**Comment by mnlmaier** [comment]
+1 just stumbled across this error aswell

**Comment by jasonvarga** [comment]
I'm getting the feeling that the handle doesn't matter. Feels like a red herring.

**Comment by edalzell** [comment]
> ok, think I may have found the issue; if you have updated the `sites` config, in my case to change the 'url' to `env('APP_URL')` it doesn't work and you get that error.
> 
> Changing it back to `'/'` makes it work.
> 
> @riasvdv had you changed that file?

This is not true, have a site that won't convert and `pro` is true and `url` is `'/'`

**Comment by jegardiner** [comment]
I am also experience this problem on a clean installation of Statamic.

Steps to reproduce:

1. Install Statamic via composer.
2. Change config/statamic/editions.php to set `'pro' => true`.
3. Run `php please multisite`.
4. Choose "yes" for using the name "default".
5. Leave the second site handle as "two".

![image](https://user-images.githubusercontent.com/2896538/104848937-0b91fc00-58df-11eb-93fa-e80a8ca5fdd1.png)

Any ideas on how this can be avoided, whether there is a potential fix? About to embark on a large multi-site build and this is causing me to fall at the first hurdle.

**Comment by dwainscheeren** [comment]
I also got this on the Butik Starter kit installation. I install the starter kit https://www.butik.dev/installation/installation/starter-kit then enable pro and t hen run the command and got the same error.

**Comment by jasonvarga** [comment]
I'm now able to replicate this issue on a fresh install. But only if you've opened site at least once so the cache gets built.

If you run the `multisite` command, you'll see the issue.
If you literally do `statamic new mysite` and then `php please multisite`, it works.

So, a workaround for now is to clear your cache before running the command.

```
php artisan cache:clear
php please multisite
```

**Comment by AndreasSchantl** [comment]
Still a problem. 
![image](https://user-images.githubusercontent.com/9936988/116545148-5b299000-a8f0-11eb-9268-6da66f731606.png)

Statamic 3.1.9

**Comment by AndreasSchantl** [comment]
Three sites have remained inside the ``collections/pages`` folder. I imagine they must have been called/rendered before the stache got rebuilt. Copies of them were actually inside the ``de`` folder.

Deleting these remaining files fixed the error for me.

**Comment by jackmcdade** [comment]
Huzzah!

**Comment by edulazaro** [comment]
Hello, I reached this page searching for a solution. In my case, I started to get the error on the `$this->collection()->sites()` after switching the cache to memcached. The issue is that I also had a dev environment and it was clonflicting with it. It will happen the same with Redis in the same scenario. Of you have a dev/staging environment, just use the file driver for the cache on those.

**Comment by maxi032** [comment]
This is still not fixed. I am getting the same error.

```
'sites' => [

        'en' => [
            'name' => 'English',
            'locale' => 'en_US',
            'url' => env('APP_URL')
        ],
        'ro' => [
            'name' => 'Romana',
            'locale' => 'ro_RO',
            'url' => env('APP_URL').'/ro'
        ],
        'nl' => [
            'name' => 'Nederland',
            'locale' => 'nl_NL',
            'url' => env('APP_URL').'/nl'
        ]
    ]
```

**Comment by duncanmcclean** [comment]
> This is still not fixed. I am getting the same error.
> 
> ```
> 'sites' => [
> 
>         'en' => [
>             'name' => 'English',
>             'locale' => 'en_US',
>             'url' => env('APP_URL')
>         ],
>         'ro' => [
>             'name' => 'Romana',
>             'locale' => 'ro_RO',
>             'url' => env('APP_URL').'/ro'
>         ],
>         'nl' => [
>             'name' => 'Nederland',
>             'locale' => 'nl_NL',
>             'url' => env('APP_URL').'/nl'
>         ]
>     ]
> ```

This is an old issue. If you're still experiencing this, please open a new issue.
