### ISSUE TITLE
Update Statamic with Composer 2 throws back conflict messages

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2803]
## Bug Description
Running `composer update statamic/cms --with-dependencies` throws back some conflict messages when using Composer 2. I am not a dev-guy so I am lost how to handle this. Using -W works, but I need to add it every time. If this behaviour is as expected, an update on the docs would be good. 

## How to Reproduce
```
composer self-update --2
composer update statamic/cms --with-dependencies
```

## Extra Detail
<img width="668" alt="Bildschirmfoto 2020-11-05 um 09 57 51" src="https://user-images.githubusercontent.com/8265902/98219507-61e0d700-1f4d-11eb-856e-75d18c80d6a2.png">

## Environment

Statamic 3.0.24 Solo
Laravel 8.13.0
PHP 7.4.8
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
If you run `composer update statamic/cms`, without the `--with-dependencies` parameter it should solve that issue. Let me know if it doesn't.

**Comment by helloDanuk** [comment]
Thanks that is working! An update to the docs would still be good for not dev savy people.

**Comment by damcclean** [comment]
> Thanks that is working! An update to the docs would still be good for not dev savy people.

Feel free to PR a change to the docs :) which page is it on?

**Comment by helloDanuk** [comment]
https://statamic.dev/installation#updating

Due to a lack of dev knowledge I do not trust myself with a PR in documentation. 🤷‍♂️

**Comment by damcclean** [comment]
I've created a pull request to the docs for you then :) statamic/docs#302
