### ISSUE TITLE
Entries field inside Bard Set results in long loading time or page crash

### ISSUE THREAD

**Issue by mindshaped** [statamic/cms#2805]
## Bug Description
Selecting and saving an entries field inside a bard field (set) and saving the page, results in extremely long loading time (or even page crash) when trying to open and edit the same page again.

## How to Reproduce

1. clone our prepared public repo: https://github.com/teamnovu/statamic-test-entries-field
2. after installation, head to: collections > pages > home
3. select an entry inside the home page's bard field (i.e. select "test" entry) and save page
4. try opening and editing page again

or

1. Create a new blueprint for pages
2. add bard field to blueprint
3. add new set to bard field
4. add entries field to bard set (from 3.)
5. create a page with blueprint (from 1.) and add a new entries selection inside bard
6. choose at least 1 entry from selection and save page
7. try to open and edit the page again, error occurs when trying to open

**Issue persist ever since upgrading to version 3.0.23**

## Environment

Statamic 3.0.24 Solo
Laravel 8.13.0
PHP 7.4.9
No addons installed

**Statamic version:** 3.0.24

**PHP version:** 7.4.9

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by twd3** [comment]
Verified. I can not edit my entries that have a set with an entries field right now.

**Comment by goellner** [comment]
Maybe this is related? https://github.com/statamic/cms/issues/2801
