### ISSUE TITLE
Collections showing incorrect results when using multiple filters

### ISSUE THREAD

**Issue by callum-veloxcommerce** [statamic/cms#2806]
## Bug Description
When using multiple filters on a collection (currently 3 but I need to add more) the results are showing fine for some scenarios and showing complete nonsense for others. This is quite a big blocker and I have not found any way to resolve it in the forums or discord.

## How to Reproduce
When I am not filtering by anything the collection works fine
Example: https://qa.allumandsidawaybridal.co.uk/wedding-dresses 

When I am filtering by template and only a slug (which is the brand name and effectively a top level category) the collection works fine.
Example: https://qa.allumandsidawaybridal.co.uk/wedding-dresses/catherine-deane

When I am filtering by template and only a fabric (query param for next level of filtering) the collection works fine.
Example: https://qa.allumandsidawaybridal.co.uk/wedding-dresses?fabrics=tulle

When I am filtering by template and slug and fabric the collection shows me the wrong results, and actually shows me an entry which does not even match the template filter and is a completely different template. 
Example: https://qa.allumandsidawaybridal.co.uk/wedding-dresses/catherine-deane?fabrics=tulle

See the below example:

Collection code:
```javascript
{{ if slug !== 'wedding-dresses' }}
    {{ collection:products template:is="product-detail-page" :brand:contains="slug" :fabrics:contains="get:fabrics" }}
         <!--HTML redacted-->
         <a href="{{ url }}">{{ title }} </a>
    {{ /collection:products }}
{{ else }}
    {{ collection:products template:is="product-detail-page" :fabrics:contains="get:fabrics"}}
         <!--HTML redacted-->
         <a href="{{ url }}">{{ title }} </a>
    {{ /collection:products }}
{{ /if }}
```
Entry structure:
![Screenshot 2020-11-05 at 14 18 37](https://user-images.githubusercontent.com/53309514/98252654-1987e000-1f72-11eb-8bda-477d4d8e73e2.png)

## Environment
Statamic 3.0.24 Pro
Laravel 7.28.4
PHP 7.2.17-1+ubuntu18.04.1+deb.sury.org+3
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
What kind of fields are `brand` and `fabrics`?

**Comment by callum-veloxcommerce** [comment]
Brand is a single select field and fabrics is a multi select.

**Comment by jasonvarga** [comment]
We received the site via a support request. The issue here was that there were no product matches, so the current page's entry was being shown in the collection:products tag pair. Adding an `if no_results` condition inside it solves it.
