### ISSUE TITLE
Collection sorting in CP broken

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [statamic/cms#2807]
## Bug Description
Sorting on non visible field does not work in cp.

## How to Reproduce
In a collection overview in CP, Toggle the visibility of a column and then sort on the column. the new column will disappear again.

## Extra Detail

![Screen Recording 2020-11-05 at 3 37 36 PM](https://user-images.githubusercontent.com/33224052/98255561-cfa4f700-1f7d-11eb-8be5-e9d4ec2b0013.gif)

## Environment

Statamic 3.0.17 Pro
Laravel 6.18.43
PHP 7.4.6
doublethreedigital/duplicator 1.1.1
spatie/statamic-responsive-images 1.3.0
stillat/meerkat 2.0.12-beta1

**Install method (choose one):**
- Fresh install from `statamic/statamic`, upgraded throughout the beta.

**Comment by jasonvarga** [comment]
Not saying this is the solution, but a workaround. Save your column selections before changing sort order.

**Comment by damcclean** [comment]
This issue is still a problem, robot.

**Comment by duncanmcclean** [comment]
I'm no longer able to reproduce this on the latest Statamic version. I imagine it was fixed in the [v4](https://github.com/statamic/cms/releases/v4.0.0/) listing table changes.
