### ISSUE TITLE
Collection tag, from mixed collections does not work when collection has date_behavior

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [statamic/cms#2812]
## Bug Description
The collection tag `{{ collection from="events|articles"}}` does not work as intended when one of the collections has a date behavior 
```
date_behavior:
  past: private
  future: public
```
It **only** shows collections from the one with date behavior instead of from both.

## How to Reproduce
```
{{ collection from="events|articles" limit="10" sort="published_date:desc" }}
     {{dump}}
{{ /collection }}
```
event.yaml contains
```
date_behavior:
  past: private
  future: public
```

## Environment

Statamic 3.0.23 Pro
Laravel 6.20.2
PHP 7.4.6
spatie/statamic-responsive-images 1.3.0
stillat/meerkat 2.1.5-beta2

**Install method (choose one):**
- Fresh install from `statamic/statamic` upgraded throughout the beta period

**Comment by damcclean** [comment]
I've just tried this on a fresh Statamic install on the latest version of Statamic (v2.0.26) and I'm unable to replicate it. 

I have two collections, a `pages` collection and an `articles` collection. The articles collection is dated and has the same date behaviour configuration as you have for events.

On my page, I see a dump for each page and each of the articles which is what I would expect to happen.

Could you let me know if what I'm doing is correct to re-create the issue and could you try again on the latest version? Thanks
