### ISSUE TITLE
Glide-Tag doesn't base64 encode filenames

### ISSUE THREAD

**Issue by Lampone** [statamic/cms#2814]
## Bug Description
The glide tag currently base64 encodes the filename. I don't really know why it does it, but it is pretty bad from a user and seo perspective. We need an option to turn this behavior off and have the normal filename in the url.

## Extra Detail

Google Image best practices: [https://support.google.com/webmasters/answer/114016?hl=en](url)

> Google uses the URL path as well as the file name to help it understand your images. Consider organizing your image content so that URLs are constructed logically.

## Environment

**Statamic version:3.0.20 Pro

**PHP version:7.4.10

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
This is what the Glide library does. But since the URL includes the full original filename the negative SEO impacts are none to minimal.

**Comment by robdekort** [comment]
However personally I’d rather have Glide not do this. Just append the preset name or whatever to the original filename.

**Comment by Lampone** [comment]
For me the filename is not included, it is replaced with a base64 encoded string of the filename.

Just to clarify it is statamic that does this and not glide:
https://github.com/statamic/cms/blob/13b70fa79976791e4574c46abb856e2a6ecbe9fc/src/Imaging/GlideUrlBuilder.php#L38-L52

If there is any way to get the original filename i would be happy to know. 

There are 3 potential factors for SEO performance of a image (title, filename/path, alt), eliminiating one of the factors is not what I would call minimal.
It would be nice to have config option to disable this (I guess there is a reason to why this was implemented in the first place)

**Comment by robdekort** [comment]
I was mistaken who sets the filename. But the full path/url does include the original filename for me. Something like this:

https://site.nl/img/containers/assets/general/filename.png/b453f147a414847b1746aba987251fd6.webp

That doesn’t happen for you?

**Comment by Lampone** [comment]
No for me it looks like:
http://example.org/img/asset/c3RhbmRvcnRlL2hlaWxicm9ubi90ZXN0LUJhdW1nYXJ0LW5hY2hoZXIucG5n?w=400&h=400&fit=max&s=b1fe01453100edac8cc1688699d8ab41

`<img src="{{ glide:image width="400" height="400" fit="max" }}" >`

**Comment by robdekort** [comment]
That's not good. I suspect you can work around this by serving cached images directly. Can you try this? https://statamic.dev/tags/glide#serving-cached-images-directly

**Comment by Lampone** [comment]
If the cache is enabled I get the same behavior as @robdekort . That is way better, thank you.

Still hope it gets changed in the future, but with the cache enabled it kinda works for now.

**Comment by robdekort** [comment]
Glad to hear! It'll make your site faster this way so that's a plus!

**Comment by robdekort** [comment]
I think this is still valid although it's more a FR. Maybe it should be moved there for now? Base encoding the filename regularly causes questions on Discord and I don't think it really serves a purpose. When using glide presets the SEO penalties are minimal, but when using Glide on the fly this definitely hurts. A beter alternative I think would be to slugify the original filename and prepend/append the glide preset name or width + height.

**Comment by ahinkle** [comment]
Ran into this client request today.

I know it's not 100% intuitive, but what about a config option where we have:

(filename)+(hash).(extension)

e.g.
man-preparing-for-a-fishing-trip.jpg/362f0ebb44098e8ed543c10e90403712.jpg (current)
man-preparing-for-a-fishing-trip-(hash).jpg (proposed)

I can whip together this PR if someone might find this useful. It would be an "opt-in" to include the filename. My only other thoughts are file name limitations for really long names - given why they are limited to 64 here - we could provide a warning on that.

**Comment by stuartcusackie** [comment]
@ahinkle That sounds great but for me my filenames are already massive:
`/img/asset/aW1hZ2VzL2NsdWJzL3Jvd2Vycy1hdC13ZXN0LXdvb2QtZ3ltLWNsb250YXJmLWR1Ymxpbi0zLmpwZw==?w=1500&h=1125&s=16bf568b932363b439d94833a5a7eafc`

**Comment by stuartcusackie** [comment]
ahinkle's idea seems like it would only be good for those with glide cache enabled. Without the glide cache my filenames are not pretty:
`/img/asset/aW1hZ2VzL2NsdWJzL3Jvd2Vycy1hdC13ZXN0LXdvb2QtZ3ltLWNsb250YXJmLWR1Ymxpbi0zLmpwZw==?w=1500&h=1125&s=16bf568b932363b439d94833a5a7eafc`

It seems like cache needs to be used to avoid this problem.

**Comment by ncla** [comment]
I am not particularly invested into this issue but here is a maybe clever way to workaround this issue.

Basically you would utilize `<picture>` tag, like this:

```
<picture>
  <source type="image/jpeg" srcset="{{ glide ... }} 600w">
  <img src="{{ asset .. }}" alt="{{ alt }}">
<picture>
```

Most modern browsers will very rarely, if ever, request the original `<img>` src tag as it was mostly used, to my knowledge, as a fallback option if browsers did not support the `<picture>` tag. As such, just link the original asset in `<img>` `src` and your Glide manipulated image(s) in `srcset` on `<source>` tag. You get descriptive filename and the manipulated image.

However I would advise against this and use `alt` attribute to describe the image instead. The `filename` is one of many ways how Google determines what is in the image.

**Comment by robdekort** [comment]
I had completely forgotten about this, but since this issue was reported, Peak changed it's strategy regarding images:

- It now does Glide transformations on the fly so you can crop and do all Glide magic from within your templates. This also saves a lot of bandwidth for end users because images can be really size optimised as opposed to using a set of presets where you have to crop them in the browser.
- `save_cached_images` is set to false now. This way the browser only requests the image it needs for the current visitor and it doesn't await generating them but pops them in on the fly. No more long wait times for the first visitor. And no unneeded sizes being generated, which potentially saves disk space.

While this strategy is working out great, filenames are not. We've been talking about this in the Peak Discord and would love a solution where the original filename is preserved.

**Comment by joschuba** [comment]
What @robdekort said in the last comment. I also ran into the problem. SEO-friendly image URLs would as well be important for me. A current client website is virtually unusable with `save_cached_images` set to `true`, but the image URLs are very important.
