### ISSUE TITLE
Format for Date Fieldset Working Incorrectly

### ISSUE THREAD

**Issue by simonkincaidkintronix** [statamic/cms#2818]
## Bug Description

I had a situation where I wanted the 'title' field  to be a date. I can go into the reasons necessary if required, but will move on for now.

It's worked absolutely fine until I wanted to apply formatting to the date.

When using a Date Field as the 'title' handle, and using the Date format ... you get unexpected results. 

## How to Reproduce
Create a new collection for testing

1. Create a new collection for testing
2. Configure Collection/Open blueprints
3. Remove the title field
4. Create a date field with handle title 
5. Add some formatting as per moment.js i.e. YYYY-MM-DD
6. Create an entry with whatever date i.e. 1st jan 2021
7. Look at the results in the MD file 
8. I get '2021202120212021-JanJan-FriFri' in the date field

## Extra Detail

<img width="518" alt="Screenshot 2020-11-09 at 09 15 49" src="https://user-images.githubusercontent.com/32284731/98522163-45ee7580-226c-11eb-9dd9-0b2d5da02b5b.png">

## Environment

Statamic 3.0.25 Pro
Laravel 7.29.3
PHP 7.4.9
aryehraber/statamic-logbook 2.0.1

**Statamic version:** 3.0.25

**PHP version:** 7.4.9

**Install method (choose one):**
- Existing Laravel app

**Comment by ebeauchamps** [comment]
Change your formatting to Y-M-D (you can check PHP date format)

**Comment by damcclean** [comment]
I don't think the moment format setting affects the format that the date/time is saved in the markdown file. 

[Moment](https://momentjs.com/) is a front-end time library so it doesn't touch the actual saving process.

**Comment by simonkincaidkintronix** [comment]
@ebeauchamps Yeah PHP date format works, but the UI mentions use Moment formatting "Optionally format the date string using moment.js." ... 
and ... 
@damcclean The moment format setting definately does set the format in the MD file 

I've found my workaround anyway, but I think it would be better to store the raw date and date format seperately for one reason ... if you wanted at a later date to change the date format (perhaps you've been storing it in textual day format i.e. Mon/Tue ... and then want to change it to numeric 10/11, etc) then because the raw date isnt available anymore it couldnt do a conversion.

**Comment by simonkincaidkintronix** [comment]
Also, i've noticed that when you change the format to something else, and go into the entry, the CP spits out a format error and doesnt let you continue until you go into the MD file and remove the old incorrectly formatted date.
Defo needs to be looked at imho
