### ISSUE TITLE
Duplicated submissions when updating submissions through SubmissionCreated event

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#2822]
## Bug Description
We have a contact form that has an encrypted value, to prevent bots/people from seeing the email adresses inside the hidden input. Basically what we're trying to achieve is to customize the receiver of the submission. 

Everything works just fine, but after updating the Submission (through the `SubmissionCreated` event) 

and calling `$submission->save()` a duplicated submission is created, instead of actually updating the submission that just got created. This is due to the fact that the `id` of the submission is not set in the `Statamic\Http\Controllers\FormController`, which makes the submission fall back to `microtime(true)` for a unique identifier (which will be unique every time you call `$submission->save()`.

**Proposed solution**: initialize the id on the submission in the FormController

## How to Reproduce
Create a simple form through the CP. Create a listener for the `SubmissionCreated` event, then update something in your form through the event and call `$submission->save()`.

## Extra Detail
Here you can see what we're achieving through the event, we only suspect to see the 'after' submission though.

![Screenshot 2020-11-09 at 19 32 55](https://user-images.githubusercontent.com/9193686/98581964-90024600-22c2-11eb-8fd4-3925b052e6bf.png)

Here you can see why the `id` will be different every time you call the `save` method on the submission.
 
![Screenshot 2020-11-09 at 19 37 27](https://user-images.githubusercontent.com/9193686/98582246-0141f900-22c3-11eb-90ce-8f6d55e3e122.png)

## Environment

Statamic 3.0.20 Pro
Laravel 7.28.4
PHP 7.4.9

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Your PR is probably a fine change, but what about listening for the FormSubmitted event instead and setting a value that way?

```php
public function handle($event)
{
  $event->submission->set('field', 'value');
}
```

**Comment by jelleroorda** [comment]
Hi Jason, it turns out you're right. I thought that when you pass a variable off to an event, any updates to that object would not affect the rest of the flow (as in: would not affect code in the controller). Apparently you implicitly pass down a reference which means that your suggestion indeed works. Thanks! I learned something new today.

Although your suggestion fixes my problem, I still think that not setting the identifier in advance is a bug, since updating/saving the entry in any of the events of the controller should not create any duplicate entries.
