### ISSUE TITLE
Circular call to script handler 'post-package-install' detected

### ISSUE THREAD

**Issue by ashokgelal** [statamic/cms#2824]
## Bug Description
I'm running into `Circular call to script handler 'post-package-install' detected` error when running `composer install`. I don't have any custom post-package-install script installed and seems to be happening when installing `statamic/cms`.

## How to Reproduce
rm -rf vendor && composer install

## Extra Detail

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/401055/98581505-d2a22f00-227e-11eb-8225-4a7652dc8bde.png">

## Environment
* Laravel: 6.2
* statamic/cms: 3.0.12
* statamic/ssg: dev-master
* Composer version 2.0.6

**Statamic version:** 3.0.12

**PHP version:** 7.4.12

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Related to https://github.com/pixelfear/composer-dist-plugin/issues/4

Workaround is to use Composer 1 for now (`composer self-update --1`) or just composer install again, the error shouldn't happen the second time.

**Comment by ashokgelal** [comment]
I'm sorry, I didn't know about it. My Google search fu failed me. Thanks for the pointer.
