### ISSUE TITLE
Structure variables don't seem to work

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/cms#2825]
## Bug Description
Trying to build a site menu consisting of links to both pages and external URIs. From the documentation, it appears that using "is_page" and "is_entry" should be able to indicate whether a structure item is a page or url entry.

I'm trying to use this to set a "new window" option on any off-site menu links. I have a structure that is a mix of these types, but using "is_page" returns null for all links, while "is_entry" returns 1 for all links, regardless of whether they are pages or url entries.

## How to Reproduce
Set up a nav section for a structure that contains a mix of site pages and url entries.

## Environment

**Statamic version:** 3.0.25

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
There's an `is_external` variable. Give that a try.

**Comment by theblacksheepltd** [comment]
I added a quick check for that:

{{ nav:main_menu }}
                <li>{{ title }}{{ if is_external }} URL{{ /if }}</li>
                {{ if children }}
                    <ul>{{ *recursive children* }}</ul>
                {{ /if }}
              {{ /nav:main_menu }}

but all entries append "URL" the the item, regardless of type.

**Comment by theblacksheepltd** [comment]
From the Nav tag variables list in documentation, my (admittedly unscientific) testing shows the following. Please let me know if I'm just trying to use these incorrectly. I'd love to be able to use something like "is_external" to append a blank target on all off-site links, for example.

**is_published**: No results
**is_page**: No results
**is_entry**: Returns true (1) regardless of page or entry
**has_entries**: Not tested
**children**: Works as expected
**parent**: Works as expected
**is_parent**: No result
**is_current**: No result
**depth**: Works as expected
**page data**: Seems to be working
**recursive children**: Works as expected
**is_external**: Not in documentation, but returns true for pages or external URLS, unless it's a link back to site:url
