### ISSUE TITLE
Adding a taxonomy term to user causes error

### ISSUE THREAD

**Issue by jbardnz** [statamic/cms#2826]
## Bug Description

Error message: `Call to undefined method Statamic\Auth\Eloquent\User::locale() (View: /home/jarrad/projects/partners/vendor/statamic/cms/resources/views/partials/scripts.blade.php)`

## How to Reproduce

Add a taxonomy term field to the user blueprint (In my case I am using the eloquent user driver)

## Extra Detail

![image](https://user-images.githubusercontent.com/1628446/98616237-43ba1300-2361-11eb-9a0f-6cf793fa4d92.png)

## Environment

Statamic 3.0.25 Pro
Laravel 8.13.0
PHP 7.4.9
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I can confirm, it happens when a user with a taxonomy term in their user file attempts to login to the Control Panel.
