### ISSUE TITLE
Asset browser showing folders on every paginated result set

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#2829]
## Bug Description

Asset browser is showing folders on every paginated result set. This is not necessarily an issue when user only has a folder or two, but it's a bit confusing if user has lots of folders.

## Extra Detail

![2020-11-10 17 00 26](https://user-images.githubusercontent.com/5187394/98738846-5854d600-2376-11eb-8aca-c9ed7e932e6d.gif)

**Statamic version:** 3.0.25

**PHP version:** 7.4

**Comment by jesseleite** [comment]
Keep this one Mr. Roboto! This isn't exactly a bug per se, but feels like one to some users. We've talked about maybe moving folders into a sidebar of some kind, so that folders are not mixed in with paginated results.

**Comment by jackmcdade** [comment]
Closed in https://github.com/statamic/cms/pull/7559
