### ISSUE TITLE
Cached metadata has empty data property

### ISSUE THREAD

**Issue by tomhelmer** [statamic/cms#2831]
## Bug Description

When asset metadata is fetched from the cache the data key is overwritten with an empty collection in:

    if ($this->meta) {
        return array_merge($this->meta, ['data' => $this->data->all()]);
    }

.. as $this->data isn't hydrated.

## How to Reproduce
- Add metadata to asset ( eg. alt text )
- View asset and check that metadata is used
- Reload page to get cached version and check metadata is gone 

## Extra Detail

[Pull request](https://github.com/statamic/cms/pull/2830)

## Environment
Statamic 3.0.26 Pro
Laravel 7.29.3
PHP 7.4.9

**Comment by timojokinen** [comment]
thanks, i just bumped into this

**Comment by aerni** [comment]
Just run into this as well. Worked fine on Statamic 3.0.25.

**Comment by damcclean** [comment]
I can confirm this is a bug, likely related to the changes made in #2828.

**Comment by jesseleite** [comment]
Should be fixed in 3.0.27, let us know if you have any issues going forward!

**Comment by duncanmcclean** [comment]
> Broken again in 3.0.46? :-/ @jesseleite 
> 
> 
> 
> **.meta/B0002040_2.jpg.yaml**
> 
> ```yaml
> 
> data:
> 
>   text: "Image description"
> 
>   alt: "Alt text"
> 
> size: 15246105
> 
>  ```
> 
> 
> 
> **Antlers**
> 
> ```html
> 
> {{ images }}
> 
>     <img src="{{ url }}" alt="{{ alt }}" />
> 
> {{ /images }}
> 
> ```
> 
> 
> 
> **Output**
> 
> ```html
> 
> <img src="/img/B0002040_2.jpg" alt="">
> 
> ````

Hey! If it's broken again, would you mind opening a fresh issue. Thanks!
