### ISSUE TITLE
All users able to access /horizon, how to i prevent that?

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2833]
## Bug Description
If i install horizon, in production environment any authenticated user can access /horizon. I have tried to set up the gate as you normally do with Laravel, however, it seems as if Statamic overrides it?

How do i set up the gate with Statamic to make sure only certain users is able to access this route?

**Statamic version:** 3.0.26

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Is that a super user?

**Comment by Pixney-William** [comment]
Yes, haven't checked with a non-super user.

**Comment by Pixney-William** [comment]
Should i ?

**Comment by damcclean** [comment]
Yeah, I'd check with a non-super user and a guest user (you should be able to check a guest pretty quickly with Incognito mode).

**Comment by Pixney-William** [comment]
Ill check that later today, however, with the gate in regular Laravel you are able to define per user email which is nice. There could be more than one super admin per side, and it doesn't necessarily mean all super admins should have access to this,

**Comment by damcclean** [comment]
I've just did some testing with a fresh Statamic install where `APP_ENV` was set to `production`. It seemed that the only case I could access Horizon was from a super user account.

I tried to use the gate authentication for Horizon that is mentioned in the Laravel documentation but I didn't manage to get it working, [see this](https://laravel.com/docs/8.x/horizon#dashboard-authorization).

I'm not sure how/if this is a Statamic issue but I do know that Statamic does some funky stuff with auth that plays funny with other first-party Laravel packages like Nova and Telescope.

Let me know how you get on when you give it a go.

**Comment by jasonvarga** [comment]
[Super users can do anything.](https://github.com/statamic/cms/blob/master/src/Providers/AuthServiceProvider.php#L76-L78) Even non Statamic stuff.

If you don't want that, then don't make them a super user. You could create a role and check all the permission boxes. Just don't check the super user box.
