### ISSUE TITLE
Editing user record reverts email field to current user's email address

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/cms#2837]
## Bug Description
When logged in as an admin, I open another user file and the email field is populated to current user email, so apparently not reading back in the filename of the user being edited.

## How to Reproduce
Open a user other than the current logged in user to edit.

## Environment

**Statamic version:** 3.0.25+

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
This sounds like it could be an issue related to the Stache. Does it work fine if you run `php please stache:clear`?

**Comment by theblacksheepltd** [comment]
Cleared the stache but doesn't fix it. When I open a user record, I can sometimes see a flash of the correct email address before it's replaced with the incorrect one (easiest to see this in Safari).

**Comment by damcclean** [comment]
Hmm, I just tried in Chrome and I'm unable to replicate this issue. I created a second user in my site, then went to update the user's name and email and it worked as expected.

Could the issue be from an extension or some sort of autofill functionality in Chrome that is overriding it because it's an `email` input? Does it happen in Incognito/Private mode.

**Comment by theblacksheepltd** [comment]
You're right — turns out to be LastPass. Incognito mode works as expected, and logging out and/or removing the LastPass plugin fixes it. Also works fine in mobile Safari, Brave, and Firefox.

I tried logging in as the second user, who doesn't have any existing records in LastPass, and it still populates with my email address, whether editing my account or the secondary user account.

More of an annoyance than anything else, but could be very confusing to any clients who have LastPass enabled.

**Comment by damcclean** [comment]
I’m going to close this issue as it isn’t really a Statamic issue, more of an issue with the password managers.
