### ISSUE TITLE
Error when deleting asset

### ISSUE THREAD

**Issue by pkarczmarczyk94** [statamic/cms#2840]
## Bug Description
When deleting an asset I get 500 response with "Call to a member function id() on null" message. After running command `php please stache:clear` or `php please cache:clear` it gets fixed.

## How to Reproduce
1. Upload assset (image in my case)
2. Check asset on list
3. Click "Delete Button"

## Extra Detail

![image](https://user-images.githubusercontent.com/15942667/98954182-d2639700-24fd-11eb-9f2e-54a55b85bcc5.png)

Part of a stack trace:
```json
 
"message": "Call to a member function id() on null",
    "exception": "Error",
    "file": "/var/www/deravesoftware/statamic.localhost/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php",
    "line": 23,
    "trace": [
        {
            "file": "/var/www/deravesoftware/statamic.localhost/vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php",
            "line": 148,
            "function": "forwardCallTo",
            "class": "Illuminate\\Http\\Resources\\Json\\JsonResource",
            "type": "->"
        },
        {
            "file": "/var/www/deravesoftware/statamic.localhost/vendor/statamic/cms/src/Http/Resources/CP/Assets/FolderAsset.php",
            "line": 14,
            "function": "__call",
            "class": "Illuminate\\Http\\Resources\\Json\\JsonResource",
            "type": "->"
        },
        {
            "file": "/var/www/deravesoftware/statamic.localhost/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php",
            "line": 95,
            "function": "toArray",
            "class": "Statamic\\Http\\Resources\\CP\\Assets\\FolderAsset",
            "type": "->"
        }

```
## Environment
Statamic 3.0.26 Solo
Laravel 8.14.0
PHP 7.4.11
aerni/social-links 2.0.1
cnj/seotamic 2.0.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jesseleite** [comment]
Should be fixed in 3.0.27, let us know if you have any issues going forward!

**Comment by davideprevosto** [comment]
I am using Statamic 3.4.9 and I got the same issue with one of out Assets (we have 3: Media, PDF, QRCodes).

```
Error ·POST /myproject/assets/actions
Call to a member function delete() on null
```

I run the following commands and I was able to delete our asset's entries:

```
$ php please stache:clear
$ php please cache:clear
```

**Comment by jasonvarga** [comment]
Please open a new issue instead of commenting on a 3 year old closed one.
