### ISSUE TITLE
Collection mount with Multisite

### ISSUE THREAD

**Issue by billmn** [statamic/cms#2841]
## Bug Description
I have enabled multisite to support two locales: Italian and English.

I would link an entry in the "mount" section of a collection but, when I click on "Link an existing item", Statamic show all entries twice (because each has content in both languages).

Also, I should be able to select an entry for each language but now is not possibile.

## How to Reproduce
1. Enable multisite and set 2 sites (e.g. italian, english)
2. Create a new page in both languages
3. Create a collection and try to link the previous entry in the mount section.

**Statamic version:** 3.0.27

**PHP version:** 7.3.23

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by FlorianMoser** [comment]
This issue also leads to another problem: the collection term page can only be accessed using the URL of the mounted page of the first site.

Using the example from above, you can only access `/it/italian-collection-slug/taxonomy-slug/term-slug/` and `/en/italian-collection-slug/taxonomy-slug/term-slug/` instead of `/en/english-collection-slug/taxonomy-slug/term-slug/`.

**Comment by GertTimmerman** [comment]
Our website has now several dead links due this bug, is this bug an a roadmap or anything?

**Comment by j3ll3yfi5h** [comment]
Maybe part of: https://statamic.com/roadmap -> Next Up -> Multi-site improvements

**Comment by jasonvarga** [comment]
The original issue is going to be solved by #4279.

The taxonomy URL thing is completely separate. I've opened #4281 for you to follow.

**Comment by j3ll3yfi5h** [comment]
Is it now possible to define a mounted entry for each site? Or did I miss something?

**Comment by Prophe1** [comment]
> Is it now possible to define a mounted entry for each site? Or did I miss something?

Well, still the same. You can't set a mounted entry for each site. Looks like a bug to me.

**Comment by max-g** [comment]
I believe part of the original ticket is still unresolved or unanswered.

> Also, I should be able to select an entry for each language but now is not possible.

Should we open a new ticket to track this ?
