### ISSUE TITLE
Set avatar and delete image from assets error

### ISSUE THREAD

**Issue by Sceko** [statamic/cms#2850]
After delete image from assets error if that image using on avatar
i fix remove avatar: myavatar.jpg from user file but did posible fix this in feature

**Comment by damcclean** [comment]
Hey @Sceko, would you mind keeping with the [provided format](https://github.com/statamic/cms/issues/new?assignees=&labels=&template=bug_report.md&title=) when creating Github issues? It makes the process of re-creating bugs much easier. Thanks!
