### ISSUE TITLE
fix api marketplace

### ISSUE THREAD

**Issue by Sceko** [statamic/cms#2859]
sometime on /cp

cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://statamic.com/api/v1/marketplace/packages/statamic/cms/releases

**Comment by damcclean** [comment]
Hey! Thanks for reporting this. 

Although, like the other issues - could you please create another issue using the [issue template](https://github.com/statamic/cms/issues/new?assignees=&labels=&template=bug_report.md&title=). It really does help the maintainers re-create this issue so we can get this issue fixed sooner. 🙂
