### ISSUE TITLE
auto scrolling up while dragging a set in a bard fieldtype doesn't work

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#2861]
## Bug Description
automatic scrolling up while dragging a set in a bard fieldtype doesn't work but automatic scrolling down works.

## Extra Detail

https://www.dropbox.com/s/yk9dyo6uldjv4bt/Bildschirmvideo%20aufnehmen%202020-11-18%20um%2015.37.29.mov?dl=0

## Environment

**Statamic version:** 3.0.26

**PHP version:** 7.3.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by WiebkeVog** [comment]
Let us know if you still need hints to reproduce the behavior.

**Comment by arthurperton** [comment]
The area that triggers the autoscroll is hidden under the header bar.. I'll see if I can fix that somehow.
