### ISSUE TITLE
The field "Select" does not allow to add additions when editing an entry

### ISSUE THREAD

**Issue by philipboomy** [statamic/cms#2867]
## Bug Description
The field "Select" does not allow to add additions when editing an entry. Like there are no place to type anything in.

## Extra Detail

Settings: https://share.getcloudapp.com/BluQ7Be7
Editing: https://share.getcloudapp.com/Koul0W6k

## Environment

Statamic 3.0.28 Pro
Laravel 7.29.3
PHP 7.4.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by edalzell** [comment]
I can't delete from a select field either

**Comment by jasonvarga** [comment]
Ah, enable `Searchable` to make it a text field.

Erin, make sure its `Clearable` to allow you to remove selections.

**Comment by philipboomy** [comment]
Yeah I can clear a selection but cant add any despite the toggle on as seen in screenshot above.

**Comment by jasonvarga** [comment]
In the screenshot, `searchable` is _not_ enabled.

**Comment by philipboomy** [comment]
@jasonvarga That did not help me. I can type in but its not saving the value nor is it pushing the option to the option list.

**Comment by jasonvarga** [comment]
Did you hit enter?

**Comment by philipboomy** [comment]
No I didnt as I didnt know that and I highly doubt my clients would know that either. It still does not push the option to the list though. So to recap:

1) Searchable toggle is not related so I suggest either changing the wording or make it into a text field based on the toggles I had toggled on in my screenshot.
2) Somehow make it apparent that you need to hit enter before it works.
3) The term is not showing up in the list when I visit another entry. It is saved though for the current entry.

**Comment by jasonvarga** [comment]
Please provide the field's yaml from your blueprint.

**Comment by philipboomy** [comment]
handle: category
        field:
          options:
            publications: Publications
            dissemination: Dissemination
          multiple: false
          clearable: true
          searchable: true
          taggable: true
          push_tags: true
          cast_booleans: false
          display: Category
          type: select
          icon: select
          width: 50
          listable: hidden
