### ISSUE TITLE
Replicator performance issues

### ISSUE THREAD

**Issue by marcusand** [statamic/cms#2868]
## Bug Description
I saw #2787 and #1915 and I am on the newest version of statamic but still experiencing some massive performance issues with the replicator field. 

The entry I am testing with has 230 rows in the replicator. I know this is a lot but I am still surprised by the performance in the control panel.
Opening the entry takes around 30-40s until the DOM is fully loaded. When its loaded and I start entering text I experience a big delay, very similar as reported in #1171. 

## How to Reproduce
One replicator in the blueprint with one type of set looking like this:

<img width="876" alt="Bildschirmfoto 2020-11-19 um 13 18 10" src="https://user-images.githubusercontent.com/28539818/99665402-e7927580-2a69-11eb-8772-4604d532e846.png">

~230 of these in a row.

## Extra Detail
Opening the entry in the control panel:

<img width="2039" alt="Bildschirmfoto 2020-11-19 um 13 18 32" src="https://user-images.githubusercontent.com/28539818/99665531-08f36180-2a6a-11eb-85a5-4fb569656f45.png">

## Environment

Statamic 3.0.28 Pro
Laravel 7.29.3
PHP 7.4.12
statamic/migrator dev-master

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Can you zip up your site and send it to us in a support request?

**Comment by marcusand** [comment]
oh thanks for your answer @jasonvarga . 
I did already send you a support mail a few minutes ago but not with the project zipped. I'll have to ask if we can do that and will eventually send it later. thanks!

**Comment by jasonvarga** [comment]
Resolved through support. Closing this one.

**Comment by globalexport** [comment]
> Resolved through support. Closing this one.

Hi @jasonvarga,

Do you remember how you solved this case? 
I am having similar issues with pages containing many elements in the cp. Creating a new page with a lot of elements is relatively responsive, but opening a saved document is consuming very much time and text fields become unresponsive when editing. 

Thank you for your help!
