### ISSUE TITLE
Should be able to set protection via Route::statamic()

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#2871]
## Bug Description

You should be able to pass a `protect` var into a Statamic route and have it behave just like an entry. Right now nothing happens because all of the Protectable logic is only attached to Entries.

```php
Route::statamic('/secret', 'default', [
    'title' => 'Secret Informations',
    'protect' => 'logged_in'
]);
```

**Comment by damcclean** [comment]
Duplicate of statamic/ideas#331.

**Comment by jackmcdade** [comment]
Sorry, overreacted. I'm not used to having someone else close my issues when I decide it's time to work on them. 😊  I moved the other one into this repo.

**Comment by damcclean** [comment]
No problem Jack!
