### ISSUE TITLE
Password reset page invalidates token too quickly.

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/cms#2875]
## Bug Description
Password reset page invalidates token too quickly.

## How to Reproduce
1. Send password reset from CP
2. User clicks reset link from email
3. User fills out the password reset form at `/!/auth/password/reset/[token]` with a password that fails validation.
4. User fills out form with proper, matching and longer password.
5. User receives error response: `The password token is invalid`

## Environment

**Statamic version:** 3.0.27

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
How long between steps 1 and 2?

**Comment by jeremydouglas** [comment]
Immediate, less than a minute.

**Comment by jasonvarga** [comment]
Does it work if you fill out the form correctly the first time?

**Comment by jeremydouglas** [comment]
Yes, it does.

**Comment by jasonvarga** [comment]
Thanks!

**Comment by damcclean** [comment]
Out of interest, what is your `SESSION_DRIVER` and `SESSION_LIFETIME` in your `.env`?

**Comment by jeremydouglas** [comment]
SESSION_DRIVER=file
SESSION_LIFETIME=120
