### ISSUE TITLE
Wrong blueprint when creating another entry

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2885]
## Bug Description
I have a collection with multiple blueprints. When choosing the `Create Another` option on the `Save & Publish` button in a collection entry, the wrong blueprint gets selected for the new entry. The new entry will be created with the first blueprint in line, rather than with the blueprint of the entry that I wanted to create another of.

**Example**
- Blueprints: `Archive`, `Default`, `Media`
- Create an entry with the blueprint `Default`
- Choose to add another entry
- The new entry will be created with the blueprint `Archive`

## How to Reproduce
- Create a collection with multiple blueprints
- Add an entry with any but the first blueprint in the dropdown
- Set the `After Saving` option on the `Save & Publish` button to `Create Another`
- You're now creating a new entry with the wrong blueprint

## Environment
Statamic 3.0.30 Pro
Laravel 8.15.0
PHP 7.4.12
aerni/social-links 2.1.0
aerni/zipper 1.2.0
jonassiewertsen/statamic-livewire 2.1.2
spatie/statamic-responsive-images 1.4.0
visuellverstehen/statamic-classify 2.0.0

**Comment by damcclean** [comment]
Can confirm this is a bug. It would make sense for the chosen blueprint to be passed along to the new entry.

**Comment by damcclean** [comment]
I've submitted a pull request to fix this issue: #2886.

**Comment by aerni** [comment]
You're the man @damcclean !
