### ISSUE TITLE
SVG's don't get properly loaded when using view cache.

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#2887]
##  Bug Description
We deploy the application with caching, but one of the latest updates (presumably [99e812e6c](https://github.com/statamic/cms/commit/99e812e6c)) has broken the SVG's in the CP. One of the steps of the deployment is `php artisan view:cache` which pre-compiles all blade views. 

## How to Reproduce
1. Install a fresh application
2. Override the global header by copy-pasting the global header with (from top of my head: `mkdir -p resources/views/vendor/statamic/partials && cp ./vendor/statamic/cms/resources/views/partials/global-header.blade.php resources/views/vendor/statamic/partials`)
3. Run `php artisan view:cache` and notice the broken SVG's in the CP.

## Extra Detail
![Screenshot 2020-11-21 at 11 39 22](https://user-images.githubusercontent.com/9193686/99875232-3537eb00-2bee-11eb-9dd8-071fd156dc95.png)

## Environment
Statamic 3.0.28 Pro
Laravel 7.29.3
PHP 7.4.9
No addons installed
Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I can't seem to re-create this issue.

 I ran `php artisan view:cache` and couldn't see a difference to how the SVG icons are being loaded. [See video]()https://drive.google.com/file/d/1Rhz9ZJW_ygm72NwCsbt2rsiUDekcp2vB/view?usp=sharing.

I'm running it on a fairly fresh site, only installed it today from `statamic/statamic` and on the latest Statamic version (v3.0.30).

I've got a couple of questions:
* By any chance have you published any Statamic views to your `resources/views` directory?
* Have you done anything custom with Statamic's routes, like override them?
* Have you registered any of your own Blade directives or do you have any Laravel packages that could potentially be causing issues.

**Comment by jelleroorda** [comment]
I have published the `partials/global-header.blade.php`. I have updated the original text with the extra reproduction steps.

**Comment by damcclean** [comment]
Thanks! Looks like publishing the global header is what breaks things... 

Is there any particular reason you are maintaining your own copy? For a custom logo or something?

**Comment by damcclean** [comment]
Ah... I know why it's broken. As the views are being cached, they cant find the custom blade directive, as its being registered in the middleware which isn't helpful as the views have already been built. 🤔

**Comment by jelleroorda** [comment]
We are maintaining a copy because we want to style the control panel / auth flow in customer style. I'm aware it was moved to a middleware (see referenced commit). Not sure how you would go about tackeling this without something ugly as registering it in a ServiceProvider with something along the lines of:

```php
if (Request::is('cp/*')) {
    // register directive
}
```

**Comment by damcclean** [comment]
I don't even think doing something like that would work as the views don't go through the router so they don't know what the route is going to be.

I think your best bet would be to use that work around, unfortunately.

**Comment by jelleroorda** [comment]
Yes you're right. The 'obvious' solution could be to simply use `{{ Statamic::svg() }}` instead though 🤔 . Since I published the views that could be a thing, but it's still a workaround yes.

**Comment by jasonvarga** [comment]
Good find about the middleware. Didn't know this would be an issue. Good to know!

**Comment by jasonvarga** [comment]
We'll probably need to replace our `@svg` directive with `@statamic_svg` or `@cp_svg`. Ugly, but what can you do.

**Comment by jelleroorda** [comment]
💨 🤖

**Comment by jasonvarga** [comment]
Will be in the next 3.1 alpha release.
