### ISSUE TITLE
Dashboard blank from version 3.0.29 >

### ISSUE THREAD

**Issue by dellow** [statamic/cms#2899]
## Bug Description
I have Statamic installed in an existing Laravel app. As of version 3.0.29 I get a blank screen in the control panel. Each page shows a flash of content then disappears. I have a `showBanner is not defined` error in the console which seems to be do with this commit: https://github.com/statamic/cms/commit/d9396a838.

## How to Reproduce
Install version 3.0.29 or above in a Laravel app

## Extra Detail
![Screenshot 2020-11-23 at 11 02 50](https://user-images.githubusercontent.com/1047476/99955201-d30cf080-2d7b-11eb-970a-e592d35487de.png)

## Environment
Statamic 3.0.29 Pro
Laravel 8.15.0
PHP 7.4.9
No addons installed

**Install method (choose one):**
- Existing Laravel app

**Comment by damcclean** [comment]
Try running `php artisan statamic:install`, clear your browsers cache and try again.

**Comment by fitzage** [comment]
I had an issue similar to this, but the error messages were different. It worked locally, and worked if accessing the production site by IP address, so after all the usual suspects, I tried clearing my browser cache and the problem was resolved.

**Comment by jasonvarga** [comment]
Try the suggestions above and sounds like you should be good to go.

**Comment by geekish** [comment]
In case anyone runs into this same problem and clearing browser cache does not help, I had to remove the public/vendor/statamic/cp folder and republished. Publish alone did not work.
