### ISSUE TITLE
Countable exception in Statamic\Tags\Collection\Entries

### ISSUE THREAD

**Issue by Daynnnnn** [statamic/cms#2904]
## Bug Description
Sometimes when getting collections filtered by taxonomies, we get a countable error.

## How to Reproduce
The code which causes the error for us is:
`{{ collection:blog_posts as="posts" limit="6" :taxonomy:categories="categories" :slug:not="slug"}}`

## Extra Detail
I believe this could have been introduced in #2672 as the issue wasn't there until we updated statamic to 3.0.20. To get around the 500 I've used `is_countable` on line 312 of Statamic\Tags\Collection\Entries to check if what's being passed in is countable before counting it. Although; I'm not sure if that's going to cause other issues, and it would mean the minimum supported PHP version would need to be bumped up to PHP 7.3.

Currently the variable being counted seems to be set to null, which could be related to me using the eloquent driver? I'm not sure. But in the past the variable has been of type `Statamic\Taxonomies\LocalizedTerm`, which doesn't implement countable hence the error.

## Environment
Statamic 3.0.20 Pro
Laravel 7.29.3
PHP 7.4.12
statamic/eloquent-driver 0.1.0
statamic/seo-pro 2.0.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by edalzell** [comment]
More details, I'm passing in an array of terms and get this:

```
[2020-11-24 21:31:59] local.ERROR: count(): Parameter must be an array or an object that implements Countable {"userId":"325e3745-3d5b-44d6-b57b-ed3f16e1c607","exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): count(): Parameter must be an array or an object that implements Countable at /Users/erin/Sites/betteroregon/resources/views/partials/sets/collection_carousel_block.antlers.html:0)
[stacktrace]
#0 /Users/erin/Sites/betteroregon/resources/views/partials/sets/collection_carousel_block.antlers.html(0): ()
#1 /Users/erin/Sites/betteroregon/vendor/statamic/cms/src/Tags/Collection/Entries.php(312): ()
#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/Users/erin/Sit...', 312, Array)
#3 /Users/erin/Sites/betteroregon/vendor/statamic/cms/src/Tags/Collection/Entries.php(312): count(NULL)
#4 /Users/erin/Sites/betteroregon/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Statamic\\Tags\\Collection\\Entries->Statamic\\Tags\\Collection\\{closure}(NULL, 'taxonomy:tags')
#5 /Users/erin/Sites/betteroregon/vendor/statamic/cms/src/Tags/Collection/Entries.php(335): Illuminate\\Support\\Collection->each(Object(Closure))
#6 /Users/erin/Sites/betteroregon/vendor/statamic/cms/src/Tags/Collection/Entries.php(151): Statamic\\Tags\\Collection\\Entries->queryTaxonomies(Object(Statamic\\Stache\\Query\\EntryQueryBuilder))
#7 /Users/erin/Sites/betteroregon/vendor/statamic/cms/src/Tags/Collection/Entries.php(46): Statamic\\Tags\\Collection\\Entries->query()
#8 /Users/erin/Sites/betteroregon/vendor/statamic/cms/src/Tags/Collection/Collection.php(37): Statamic\\Tags\\Collection\\Entries->get()
#9 [internal function]: Statamic\\Tags\\Collection\\Collection->index()
#10 /Users/erin/Sites/betteroregon/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func(Array)
#11 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'collection', Array, '\
              ...', Array)
```
