### ISSUE TITLE
Missing UserBlueprintFound event

### ISSUE THREAD

**Issue by arthurperton** [statamic/cms#2905]
## Bug Description
The [PublishFieldsetFound](https://v2.statamic.com/addons/events/publish-fieldset-found) in v2 was replaced in v3 by the [XxBlueprintFound events](https://statamic.dev/extending/events), but the UserBlueprintFound event is missing. 

So you can't modify the user blueprint on the fly, as you can with blueprints for other data types. Also any custom code depending on PublishFieldsetFound with data type user cannot be ported to v3.

## Extra Detail
In v2 there was a PublishFieldsetFound event. It was dispatched for all data types (page, entry, term, globals and user). In v3 these are replaced by separate events per data type, like EntryBlueprintFound, TermBlueprintFound, GlobalVariablesBlueprintFound. There is no UserBlueprintFound though.

## Environment

**Statamic version:** 3.0.30 Pro

**PHP version:** 7.4.12

**Install method** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Done in #2983
