### ISSUE TITLE
Asset browser Vue component should use Asset.php's editUrl instead of building its own

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#2906]
## Bug Description

We have a custom Asset.php class (extending Statamic\Assets\Asset.php) and override editUrl() in there to use an ID from our backend instead of the filename in the path. (We have a custom AssetRepository as well, expecting this ID in calls to find().) Double clicking an image in the AssetManager/Browser opens the edit view in a stack and pushes a wrong edit URL to the browser history.

The URL that's pushed is built (like in your Asset.php, from the asset's basename) in Browser.vue. Since we override the URL in PHP, the URL built in the frontend won't work for us. Instead, the Browser should wait for the Editor to load the asset and emit the correct editURL as an event, and use that to push an entry to the browser history.

## How to Reproduce

See above: change editUrl() in Asset.php, compare to the URL pushed to the history when double clicking an image in the AssetManager.

**Comment by jasonvarga** [comment]
Closing as this doesn't seem like a common enough problem, and it's quite old. But of course feel free to let us know if this is still an issue for you and we can revisit.
