### ISSUE TITLE
Weird GlideServer error

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2917]
## Bug Description
I came across this issue when deploying my site. Deployment always fails because of it. This always happens when installing the composer dependencies. I can't even clear the cache or execute any other please command. It always screams at me with the `GlideServer` error. Any hint?

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In GlideServiceProvider.php line 35:
                                                          
  Class 'Facades\Statamic\Imaging\GlideServer' not found  
                                                          

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

## Environment
Statamic 3.0.30 Pro
Laravel 8.16.0
PHP 7.4.12
aerni/social-links 2.1.0
aerni/zipper 1.2.0
jonassiewertsen/statamic-livewire 2.1.2
spatie/statamic-responsive-images 1.4.0
visuellverstehen/statamic-classify 2.0.0

**Comment by damcclean** [comment]
Might be something to do with [Laravel's Real-Time facades](https://laravel.com/docs/master/facades#real-time-facades) not working. I believe that's what gives it the `Facades\` namespace. 

Have you tried running `composer dump-autoload` and dumping your entire `vendor` directory and re-running `composer install`?

**Comment by aerni** [comment]
Yes, nothing works. I deleted the `vendor` folder. Ran `composer install` again. It always hangs at the end at `Generating optimized autoload files`.

**Comment by damcclean** [comment]
Hmm, are you using Composer 1 or 2?

**Comment by aerni** [comment]
Composer 1.10.17

**Comment by damcclean** [comment]
> Composer 1.10.17

Try upgrading to Composer 2 and try again if possible - `composer self-update && composer self-update --2`.

If it breaks anything, you can downgrade with `composer self-update --1` but it shouldn't.

**Comment by aerni** [comment]
Ok, I was able to fix it. Had to manually delete all the caches within the `storage` directory.

**Comment by Haris1994** [comment]
Thanks @aerni
