### ISSUE TITLE
Multiple versions of Prosemirror-model loaded

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#2919]
## Bug Description

When editing a Bard field inside a Bard set, you get the following error when creating a new line: 
`Uncaught RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)`.

This is possibly related to https://github.com/ueberdosis/tiptap/issues/577 or the latest Statamic update: https://github.com/statamic/cms/commit/b74c61e05

## Extra Detail
<img width="1440" alt="Screen Shot 2020-11-26 at 10 38 38 am" src="https://user-images.githubusercontent.com/414211/100292259-0e096100-2fd4-11eb-9b19-393699c4a15d.png">

## Environment

Statamic 3.0.31 Pro
Laravel 8.16.1
PHP 7.4.9
statamic/migrator dev-master
statamic/seo-pro 2.0.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
Was able to reproduce this in Firefox. In Safari it seems to work.

**Comment by robdekort** [comment]
I took the liberty to label this critical.

**Comment by felixstoessel** [comment]
Same issue here using Firefox. If I am at the **end of a paragraph/line** in Bard and try to enter `<return>`, I get this issue.

**Comment by adnankussair** [comment]
Yup same issue here. Certain bard formatting options are throwing the prose mirror console error the one we experiencing it on was blockquote.

**Comment by ellukesmith** [comment]
I'm getting the same error in Chrome, but I don't have a Bard field inside a Bard set - adding a Bard field with default options to any Blueprint has the same issue. I'm also getting the same error in Safari - every time I hit enter, it throws the same error in the console.

Running the same version of Statamic (3.0.31 Pro).

**Comment by jeremydouglas** [comment]
I get this error on `3.0.31` when there's multiple Bards on a collection entry. Both in Chrome and Firefox.

**Comment by jasonvarga** [comment]
Tackling this shortly.

**Comment by adnankussair** [comment]
> Tackling this shortly.

Whoot! Thanks @jasonvarga
