### ISSUE TITLE
Time Field Type — NaN Property appearing as you use backspace

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2920]
## Bug Description
See gif for example. As you hit backspace i would prefer it to stay 00. As it is now, it messes up the ui when you display NaN.

## Extra Detail
![time](https://user-images.githubusercontent.com/31292231/100344924-d9040b00-2fe1-11eb-9e65-902798c5b456.gif)

## Environment
Statamic 3.0.30 Solo
Laravel 8.15.0
PHP 7.3.23
No addons installed

**Comment by sjclark** [comment]
This is definitely still an issue
Silly robot 🤖 ❤️

**Comment by icemancast** [comment]
Confirmed still an issue.
