### ISSUE TITLE
Blueprints: Link single field config screen returns Vue error.

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#2924]
## Bug Description

When editing a blueprint and linking an existing single field, the console returns the error:
`vue.common.prod.js:6 Error: Cannot find module './undefined.svg'`

## How to Reproduce

1. Create blueprint
2. Create replicator field 
3. Link existing
4. Link a single field
5. See loading screen and vue error in console

## Extra Detail

<img width="1424" alt="Screen Shot 2020-11-27 at 9 09 50 am" src="https://user-images.githubusercontent.com/414211/100394436-44f17c80-3091-11eb-8b47-e0fd221b258a.png">

<img width="1428" alt="Screen Shot 2020-11-27 at 9 07 42 am" src="https://user-images.githubusercontent.com/414211/100394423-386d2400-3091-11eb-9519-7f5bfe0578aa.png">

## Environment

Statamic 3.0.29 Pro
Laravel 8.16.1
PHP 7.4.9
statamic/migrator dev-master
statamic/seo-pro 2.0.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I can re-create this issue. I think it could be something related to fieldtype icons. However, the user can continue to use the blueprint editor and the replicator stack after the console error appears.

**Comment by jasonvarga** [comment]
Is any functionality affected or is it just an error in the log?

**Comment by JonKaric** [comment]
+1 for this. It hangs on the loading screen meaning you can't edit settings/validation through the admin, even after save

**Comment by damcclean** [comment]
The same issue was reported in #2942. It only crashes/freezes for the user if the field you're importing (like a replicator or grid) has fields within it. A blank one will only throw the icon error.

**Comment by nkheng** [comment]
I'm also experiencing this issue. 

Adding the below code here: vendor > statamic > cms > src > Fields > FieldTransformer.php line 61 (see snip (https://enee.d.pr/rpO869) seems to work for now. 

```
if (!isset($field['field'])){
            $field['field'] = $field;
}
```
