### ISSUE TITLE
[Multi-Site][Search] Search indexes not updating automatically for non-origin entries

### ISSUE THREAD

**Issue by piljac1** [statamic/cms#2925]
## Bug Description

When updating a non-localizable field on an origin entry, search indexes are not updated automatically for entries linked to that origin. For example, if you update the origin title (assuming it isn't localizable), the search indexes will get updated in the origin's locale and you will be able to find the entry by searching the new title, but that won't be the case for other sites/locales linked to that origin.

## How to Reproduce

1. Make sure you have a default index that looks like this (it should already be part of your `config/statamic/search.php` file):
```
'default' => [
    'driver' => 'local',
    'searchables' => 'all',
    'fields' => ['title'],
],
```
2. Update an existing origin entry's title (make sure the title is not localizable and that the new title is unique)
3. In the dashboard's search bar, search for the new title
4. Only one entry is part of search results (when normally, there would be X entries where X is your number of sites)

## Extra Detail

1. You can also test this behavior on the front-end if you have a search page set. If your origin is "en", you will get a result on your "en" website, but if you switch to another locale, you'll get no results.
2. You can refresh linked non-origin entry indexes by manually saving (Save & Publish) those non-origin entries manually (that's not ideal, but it is a temporary workaround to this bug).
3. This issue also seems to affect all referenced entries. For example, if you change the title of an author, all posts by this author will not be found with the new authors name. You need to go save (Save & Publish) each individual non-origin posts to fix the issue.

## Environment

Statamic 3.0.28 Pro
Laravel 7.28.4
PHP 7.4.3
doublethreedigital/duplicator 1.2.1

**Install method:**
Fresh install from `statamic/statamic`

**Comment by piljac1** [comment]
I just realized it is probably a duplicate of https://github.com/statamic/cms/issues/2699

But you can see this as additional info and close it if needed.

**Comment by damcclean** [comment]
Looks like the same issue to me. I'll close this issue.
