### ISSUE TITLE
Conditionally hidden fields are being validated when not visible

### ISSUE THREAD

**Issue by ellukesmith** [statamic/cms#2926]
## Bug Description
Validation rules added to a conditionally hidden field still fire even when the field is hidden.
 
## How to Reproduce

1. Create a new fieldset
2. Add a couple of fields, and set one to be conditionally hidden
3. Set the hidden field to required
4. Test adding content and saving the page with the field hidden
5. On save, check the request in the network tab for the validation error

## Extra Detail
In this example, I have two text fields, Text1 and Text2. Text2 is set to only display if Text1 equals 'show'. When submitting the page with Text2 hidden, I get a validation error response.
![image](https://user-images.githubusercontent.com/5304632/100407713-0cfe2f80-30b9-11eb-8051-8f8446e84330.png)

## Environment
Statamic 3.0.30 Pro
Laravel 8.15.0
PHP 7.3.24
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
They way it works is you need to use `required_if` for validation to only kick in when a field is not hidden. Closing this for now, if you feel this is still a bug please reopen.

**Comment by ellukesmith** [comment]
@robdekort - I tried this, but was unable to get it to work for fields nested within a Replicator. I've outlined an example below:

- Text Field (text1)
- Replicator Field
    - Text Field (text2)
    - Text Field (text3)

Adding `required_if=text2,required` to `text3` does not work. Validation always passes successfully, regardless of the value in `text2`. If I add `required_if=text1,required` to `text3`, typing the text "required" into `text1` causes the validation to correctly fail.

It appears to me that the `required_if` and `require_unless` rules are looking at the root field context, and not at the scope within the repeater block. Is that expected behaviour? If so, it doesn't seem I am able to enable required fields for conditionally hidden fields within a replicator field.

**Comment by robdekort** [comment]
True. Within replicators it's unfortunately not working atm. See this draft PR https://github.com/statamic/cms/pull/1703
