### ISSUE TITLE
Scope filtering on boolean values

### ISSUE THREAD

**Issue by FrankPeters** [statamic/cms#2927]
## Bug Description
The following boolean whereIn filter does not work:

```php
class SubTaxonomy extends Scope
{
    /**
     * Apply the scope.
     *
     * @param \Statamic\Query\Builder $query
     * @param array $values
     * @return void
     */
    public function apply($query, $values)
    {
        $parentSlug = $values['parent_slug'];

        $query
            ->where('parent', '!=', null)
            ->where('parent_slug', $parentSlug)
            ->whereIn('include_as_sub', ['yes', true, null])
            ->whereIn('visible', ['yes', true, null])
            ->orderBy('title');
    }
}

```

**Expectations:**

1. Set `visible` toggle to `false`.
2. Load page and expect to not see the taxonomy.
3. Set `visible` toggle to `true` and `include_as_sub` to `false`.
4. Load page and expect to not see the taxonomy.

**Bug:**
The filtering does not seem to apply the `whereIn` at all.

## How to Reproduce
I have created a Scope to filter on sub taxonomies. This relationship is defined by use of a string based `parent_slug` field. In addition to the parent relationship we also have two boolean values to control visibility; `visible` and `include_as_sub`. The former is basically a way to control published state which is migrated from v2. The later is to control whether we want this taxonomy to even show up in a sub taxonomy list. 

Note that the `'yes'` value is backwards compatibility from v2 taxonomies. Note that the `null` is used as we want to treat taxonomies that do NOT have any preference as allowed to be shown.

## Extra Detail
I have tried to filter solely on the boolean value like:
```php
$query->where('visible', true);
```
But then nothing is visible, even the taxonomies that have `visible` set to `true`.

## Environment

Statamic 3.0.31 Pro
Laravel 7.28.4
PHP 7.4.4
statamic/migrator dev-master

**Install method (choose one):**
- Fresh install from `statamic/statamic` and migration from a v2 installation.

**Comment by FrankPeters** [comment]
I have removed the `whereIn()` in favour of just a simple boolean check and will just update all my old content to be compatible. It's a pain, but then at least it's a toggle.

**Comment by ryanmitchell** [comment]
I suspect this is just a legacy of bad data, on a new Statamic install if I set up two toggle fields and query them:

```php
\Statamic\Facades\Entry::query()
        ->where('toggle_field', true)
        ->where('toggle_field_2', true)
       ->get();
```  

no matter which combination I use of true/false I get the correct results.
