### ISSUE TITLE
Error on deleting multisite entries

### ISSUE THREAD

**Issue by GertTimmerman** [statamic/cms#2929]
## Bug Description
When i want delete all entries of a collection, i always get an "Call to a member function id() on null" error. Even when i clear or refresh the cache (stache).

## How to Reproduce
I have created several entries at a multi site environment. Some entries i have translated, some not. When I clear all filters to see all the entries of each site, and select all the entries and click on the delete button and check 'delete' to delete the localizations, then i get in the left bottom corner the message: Call to a member function id() on null

## Extra Detail
 ```
message: "Call to a member function id() on null"
exception: "Error"
file: "/Users/**********/*******/site/vendor/statamic/cms/src/Stache/Stores/Store.php"
line: 79
```

## Environment
Statamic 3.0.31 Pro
Laravel 8.15.0
PHP 7.4.12
edalzell/blade-directives 1.6
optimoapps/statamic-bard-text-align V1.0.1
spatie/statamic-algolia-places 1.0.2
statamic/seo-pro 2.0.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by cgrisar** [comment]
An entry must be present in every site if you want multisite to work properly. I'd suggest to unpublish an entry iso deleting it

**Comment by jasonvarga** [comment]
@cgrisar that's not true in v3 anymore.
