### ISSUE TITLE
3.0.31 - Bard buttons issue

### ISSUE THREAD

**Issue by matteboy99** [statamic/cms#2934]
After the most recent update 3.0.31, the list item buttons don't fire to create an ordered or unordered list - paragraphs are created in their place. They are active in my bard blueprint.

**Comment by damcclean** [comment]
Hey! Thanks for the bug report.

However, I'm going to have to close this issue as it doesn't use the [issue template](https://github.com/statamic/cms/issues/new?assignees=&labels=&template=bug_report.md&title=) for bug reports. Using the template helps to keep all issues consistent and helps to make sure all issues provide enough information for maintainers to recreate your issue.

I know it might be a bit of a hassle but would you mind creating a fresh issue with the template? Thanks
