### ISSUE TITLE
Can't use if statement with get tag

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#2936]
## Bug Description

I've created a `select` dropdown to filter products by title and price. It works fine. However, when on a filter, I'd like for that filter to be selected in the dropdown, here's the code I'm trying to use:

```html
<select name="sort">
  <option value="title:asc" {{ if {get:sort} === 'title:asc' }} selected {{ /if }}>Alphabetically, A-Z</option>
  <option value="title:desc" {{ if {get:sort} === 'title:desc' }} selected {{ /if }}>Alphabetically, Z-A</option>
  <option value="price:asc" {{ if {get:sort} === 'price:asc' }} selected {{ /if }}>Price, Low-High</option>
  <option value="price:desc" {{ if {get:sort} === 'price:desc' }} selected {{ /if }}>Price, High-Low</option>
</select>
```

The issue I'm having is that the if statements around the `selected` attribute isn't returning true and the `selected` attribute isn't seen in the outputted markup.

Example of url params that should trigger one of them `?sort=price%3Adesc`

## How to Reproduce
I've provided information on reproducing the issue in the Bug Description.

## Environment

```
Statamic 3.0.30 Solo
Laravel 8.15.0
PHP 7.4.3
doublethreedigital/simple-commerce 2.1.7
```

**Comment by jasonvarga** [comment]
You shouldn't need the braces around get. It's a variable, not a tag.

Try `{{ if get:sort == "title:asc" }}`

**Comment by damcclean** [comment]
Ah, good catch. Although, your suggestion doesn't seem to be working either 🤔

```html
<option value="title:asc" {{ if get:sort == 'title:asc' }} selected {{ /if }}>Alphabetically, A-Z</option>
<option value="title:desc" {{ if get:sort == 'title:desc' }} selected {{ /if }}>Alphabetically, Z-A</option>
<option value="price:asc" {{ if get:sort == 'price:asc' }} selected {{ /if }}>Price, Low-High</option>
<option value="price:desc" {{ if get:sort == 'price:desc' }} selected {{ /if }}>Price, High-Low</option>
```

**Comment by damcclean** [comment]
Still an issue

**Comment by arthurperton** [comment]
Hi Duncan, I just tried your code in a fresh Statamic 3.0.43 install and it works as intended. Could you check if your case works too now in the latest version?

**Steps:**
put the code below in the ```home``` template 

```html
<select name="sort">
    <option value="title:asc" {{ if get:sort === 'title:asc' }} selected {{ /if }}>Alphabetically, A-Z</option>
    <option value="title:desc" {{ if get:sort === 'title:desc' }} selected {{ /if }}>Alphabetically, Z-A</option>
    <option value="price:asc" {{ if get:sort === 'price:asc' }} selected {{ /if }}>Price, Low-High</option>
    <option value="price:desc" {{ if get:sort === 'price:desc' }} selected {{ /if }}>Price, High-Low</option>
</select>
```
.  
and visit ```/?sort=price:desc```, which shows:

<img width="469" alt="Screenshot 2021-02-13 at 11 20 24" src="https://user-images.githubusercontent.com/4067531/107847649-9cc89580-6ded-11eb-89c1-1d1098b98be3.png">

The url-encoded version ```/?sort=price%3Adesc``` also works.

**Comment by duncanmcclean** [comment]
Ah, thanks for pointing that out! It looks like this has been resolved since the issue was created.
