### ISSUE TITLE
3.0.31 - Bard buttons issue

### ISSUE THREAD

**Issue by matteboy99** [statamic/cms#2937]
## Bug Description
I'm using a bard within a grid field set. After upgrading to 3.0.31, I can no longer change content into an ordered or unordered list.

## How to Reproduce
- Use version 3.0.31
- Use a grid field type
- Within this repeatable grid have an option for body copy using the bard field type: 9 max rows, min 1 row, stacked, reorder-able turned on.

## Extra Detail
Below is an active click state of the unordered list button - the content still remains as a paragraph. If I have the option to view source code of the bard, the tags still remain as paragraph tags after clicking.

![Screenshot 2020-11-28 at 16 05 31](https://user-images.githubusercontent.com/16179868/100520235-ab12f800-3194-11eb-9862-31f9f344366f.png)

edit: the console is spitting this out when clicking a list button:
`RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)`

## Environment
- Statamic 3.0.31 Pro
- Laravel 8.16.1
- PHP 7.4.11
- aerni/social-links 2.1.0
- cnj/seotamic 2.0.2
- nineteensquared/instagram 1.0.4

**Statamic version:** 3.0.31

**PHP version:** 7.4.11

**Install method (choose one):**
- Fresh install from `statamic/statamic` with upgrades from 3.0.1 to 3.031

**Comment by robdekort** [comment]
Duplicate, closing in favour of #2919
