### ISSUE TITLE
Taxonomy Terms Override

### ISSUE THREAD

**Issue by matteogigi7** [statamic/cms#2938]
## Bug Description
If i create a taxonomy term, let's say for example with "Term 1" as Title, it gets saved with the slug "term-1".
Then I create a new taxonomy term with same title "Term 1". If I save, then the previous created term gets overridden, because there's no check on the slug uniqueness, unlike with collection entries.

## Environment

**Statamic version:** 3.0.29

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Can confirm, some validation should probably be added there.
