### ISSUE TITLE
Updating to 3.0.31 attempts to create /.gitkeep at filesystem root

### ISSUE THREAD

**Issue by ehibun** [statamic/cms#2939]
## Bug Description
I'm getting.a weird error when upgrading to Statamic 3.0.31 on two of my projects. When `php please statamic:install` runs, it's attempting to create `.gitkeep` files, but one of them is returning an empty string so the install fails with the following message:

```
file_put_contents(/.gitkeep): failed to open stream: Read-only file system
```

## How to Reproduce

- Start a new project using `statamic/statamic` from during the Statamic beta - the two projects affected started with CMS versions v3.0.0-beta.23 and v3.0.0-beta.28, respectively.
- From Statamic 3.0.30 or earlier, upgrade the `composer.json` dependency to 3.0.31.
- Run `composer install`

## Extra Detail
If I edit `vendor/statamic/cms/src/Console/Commands/Install.php` and change line 66 to the following, it works: 

```php
if ($dir && ! File::exists($gitkeep = $dir.'/.gitkeep')) {
```

Based on my fiddling, it seems to fail because `config('statamic.stache.stores.navigation.directory')` is undefined - I can only assume it's because both projects started in the mid-beta phases and that the navigation directory noted here might not exist? For reference, one project uses navigations, the other does not.

## Environment
```
Statamic 3.0.31 Pro
Laravel 8.16.1
PHP 7.4.13
No addons installed
```

**Install method (choose one):**
- Fresh install from `statamic/statamic`, originally at v3.0.0-beta.23 and v3.0.0-beta.28

**Comment by marcusand** [comment]
I have the same problem when trying to update...

**Comment by damcclean** [comment]
@ehibun Did you find a workaround for this issue, I think I remember you mentioning one on Discord.

**Comment by ehibun** [comment]
@damcclean I did - open `vendor/statamic/cms/src/Console/Commands/Install.php` and edit line 66 to match the following:

```php
if ($dir && ! File::exists($gitkeep = $dir.'/.gitkeep')) {
```

Specifically, I'm changing the if statement to add that `$dir &&` check - so the script just skips creating the .gitkeep file if the  variable is blank.

**Comment by jasonvarga** [comment]
Thanks! @marcusand I'm assuming you also upgraded from a pretty early version?

**Comment by marcusand** [comment]
@jasonvarga no, actually I am on 3.0.30

**Comment by fitzage** [comment]
The upgrade appears to have succeeded for me, despite this error. Is it going to break anything if I proceed as-is?

I’m unclear why this issue is closed at this point. Fix in the next version?

**Comment by jasonvarga** [comment]
It's fixed on master but not released yet. Coming soon.
