### ISSUE TITLE
Clear cache after re-ordering

### ISSUE THREAD

**Issue by freshface** [statamic/cms#2941]
## How to Reproduce

Set caching to full.
Re-order a collection.
You will see the cache is not emptied.

**Statamic version:** 3.0.31

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Please re-open and follow the issue template.

The cache shouldn't just be emptied for no reason. Explain what the actual issue is that you're experiencing. Thanks.
