### ISSUE TITLE
Preview broken if api is enabled

### ISSUE THREAD

**Issue by tomhelmer** [statamic/cms#2953]
## Bug Description
If api is enabled the preview is broken when previewing a new (non-saved) page.

## How to Reproduce

- enable api
- create new page
- preview before saving

## Extra Detail

```
Illuminate\Routing\Exceptions\UrlGenerationException
Missing required parameters for [Route: statamic.api.collections.entries.show] [URI: api/collections/{collection}/entries/{entry}].
```

## Environment

Statamic 3.0.31 Pro
Laravel 8.17.0
PHP 7.4.11

**Install method**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Confirmed. Here's a [full flare exception](2924).
