### ISSUE TITLE
Call to undefined function Intervention\Image\Gd\imagecreatefromjpeg() when uploading jpg asset on local

### ISSUE THREAD

**Issue by kristiana-s** [statamic/cms#2957]
## Bug Description
Uploading a jpg/jpeg image to local statamic v3 installation get this error 
`Call to undefined function Intervention\Image\Gd\imagecreatefromjpeg()`

Upon refreshing assets page can see that image files have actually uploaded but have no preview icon, still show image upon clicking.
Images can still be selected in fields and be used in antlers templates.
However uploading an jpg image into fieldset will not link it with field, need to then click to select image from assets.

No issues with png.

## Environment
Statamic 3.0.31 Solo
Laravel 8.15.0
PHP 7.4.12
doublethreedigital/duplicator 1.2.1

**Comment by jasonvarga** [comment]
Do you have GD installed? https://statamic.dev/requirements#server-requirements

**Comment by kristiana-s** [comment]
Oh yep, checked with our team, we had imagick on our  docker server but statamic setup was looking for gd, hence the error.

**Comment by jasonvarga** [comment]
You can use imagick if you prefer. Change it here https://github.com/statamic/statamic/blob/master/config/statamic/assets.php#L42
