### ISSUE TITLE
In live preview {{ site:handle }} returns the wrong locale

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2958]
## Bug Description
I'm using {{ site:handle }} in my template and in Live Preview mode it returns the wrong locale. Probably the default?

## How to Reproduce
1. Use multisite
2. Use `{{ site:handle }}` in your template
3. Visit the frontend: you'll get back the correct handle.
4. Visit the entry from live preview: you get the wrong handle.

## Extra Detail
On the english CP page here:
<img width="354" alt="Screenshot 2020-12-02 at 20 52 07" src="https://user-images.githubusercontent.com/69107412/100924057-64990280-34e0-11eb-8ceb-d33b8a10dd9e.png">

Watching `{{ site | dd }}` using Live preview:
<img width="811" alt="Screenshot 2020-12-02 at 20 53 08" src="https://user-images.githubusercontent.com/69107412/100924109-78446900-34e0-11eb-965e-cc3322e99fbc.png">

## Environment
Statamic 3.0.32 Pro
Laravel 8.17.0
PHP 7.4.10
edalzell/forma 0.7.2
jonassiewertsen/statamic-livewire 2.2.0
silentz/mailchimp 2.4.1

**Install method (choose one):**
- Starter kit

**Comment by aerni** [comment]
I can confirm this issue. The Live Preview always returns the site handle of the default site rather than the one of the selected site.
