### ISSUE TITLE
$user->hasRole() doesn't check through groups

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#2961]
## Bug Description
I think this is a bug, but correct me if this is intended functionality. I'm writing a policy, where I checked whether a user has a specific role. The user can have zero or more groups, in addition to having zero or more additional roles. The group can also have zero or more assigned roles to it. Let's say the user is in the group `rad_boys`, and the `rad_boys` group has the role `rad_functionality`. If I then check whether `$user->hasRole('rad_functionality');` it returns `false`. I would expect this to return `true`, since I can't think of any cases where you would not want this to overlap?

## How to Reproduce
Create the above sketched scenario.

## Environment
Statamic 3.0.30 Pro
Laravel 7.29.3
PHP 7.4.9

- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Roles and groups are different concepts. A role is a permission level a user can have and a group is just a group of different users.

**Comment by jasonvarga** [comment]
It's working as intended. The hasRole method is checking if the user has that role directly applied to them.

If your app code is trying to determine if a user can do something, you should ask if the user has permission to do something rather than if they have a role. Permissions flow through roles and groups.

**Comment by jelleroorda** [comment]
@jasonvarga I understand the concept of checking for permissions, but then how would you solve the following use case:
The customer has a 'media' collection. The media entries should only be visible to one or more groups (or roles) that they select on the Entry level. I don't see how you could solve that with permissions.
