### ISSUE TITLE
New input_type: hidden form field doesn't show data when you view the form submission in the CP

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2962]
I just implemented an "input_type: hidden" for a text field. Any data saved in that hidden field is NOT rendering when you go to view the form data in the CP.

This is just for a simple frontend form. ***I can see the value in the column preview of the submission, but when I select to view the entire details the value doesn't show.

## How to Reproduce
Make a new text field with "input_type: hidden" on a form. Add data to that field and submit the form. My specific use case is a Google script adds the Gclid to this hidden field.

Go view the form submission in CP. If you add that new hidden field type to your default columns the value shows and if it's long you get a "...". Click to view the entire submission details and look at that new field. It should show just the Title of the field with no data and that data is clearly there because you can see it in the other initial view.

## Extra Detail
https://discord.com/channels/489818810157891584/489819906540568593/784123557013356604

## Environment
Statamic 3.0.32 Pro
Laravel 8.17.0
PHP 7.4.6
jimblue/htmlmin 1.0.0
silentz/akismet 2.2.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by twd3** [comment]
I just found out if I export the form details I can get the type=hidden inputs full data so that's working.

**Comment by damcclean** [comment]
I think this is how it's meant to work.

If an input element's `type` is `hidden`, it means that the input field will not be displayed. This also happens in an entry if you add the hidden text field to its blueprint, only the label is displayed.

If you're wanting to view the data in the Control Panel, I don't think a hidden input field is the best choice. You might be better with a standard input field and doing something on your frontend to change the type to `hidden`.

I'm closing this issue now as I don't really feel that it's a 'bug'.

**Comment by stuartcusackie** [comment]
I've just been through the same process to realise that hidden fields don't show up in form submissions. I went with a regular text field in the end and hid it manually in my template. This works fine but it puts a lot of limitation on forms and allowing admins to create them dynamically.

It would be nice if forms had two sets of blueprints: https://github.com/statamic/ideas/issues/585
