### ISSUE TITLE
Searching for an empty string results in a 500 error

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#2971]
## Bug Description
A very low prio bug; but a bug nonetheless. When you search for something like a space in the CP, `Statamic/Search/Comb/Comb` throws a `Statamic\Search\Comb\Exceptions\NoQuery` exception. This is showing up in our error reporting, I think that this exception should be caught at controller level and return an empty result set instead.

## How to Reproduce
Search in the CP for an empty string (after trimming whitespace)

## Environment
Statamic 3.0.30 Pro
Laravel 7.29.3
PHP 7.4.9

- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Confirmed. Ideally this should probably return no results I'd guess.
