### ISSUE TITLE
Error message for User:Register_Form email is not very descriptive

### ISSUE THREAD

**Issue by MikeHarrison** [statamic/cms#2977]
## Bug Description
When filling in the `User:Register_Form`, and entering an email address that is already registered, the error text that appears is "validation.unique_user_value". This would be better having a more descriptive error e.g. "This email address is already registered"

## How to Reproduce
Try to fill in a `User:Register_Form` using an email address already used for a user.

## Environment

**Statamic 3.0.32 Pro
Laravel 8.17.2
PHP 7.4.12
austenc/statamic-instagram-feed 2.2.0
edalzell/forma 0.7.2
silentz/mailchimp 2.4.1**

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Nice find. If you add these lines to the validation.php file, you should be good to go. https://github.com/statamic/statamic/commit/6ca0956620cbf726b87e82c8e2fe6939cee3aa55
