### ISSUE TITLE
Form submissions display receives wrong date

### ISSUE THREAD

**Issue by forby** [statamic/cms#2978]
## Bug Description

When displaying a list of form submissions, each item has the same date instead of displaying the date when it was submitted. I have confirmed that each submission _filename_ consists of the correct UTC timestamp, but each displayed form submission seems to use only the first timestamp from the list.

## How to Reproduce

Use basic `form:submissions` loop and display date as suggested in docs:
```
{{ form:submissions in="guestbook" }}
    <div>
        <p>Submitted on {{ date }}</p>
    </div>
{{ /form:submissions }}
```

## Extra Detail
![image](https://user-images.githubusercontent.com/295742/101422225-2e82c680-38c4-11eb-93e3-adb373214ace.png)

## Environment

Statamic 3.0.32 Solo
Laravel 8.17.2
PHP 7.3.25
No addons installed

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Good catch! Doesn't look like there's any way to get the date while looping through submissions. In my opinion, that should probably be do able.

A workaround for now would be to add a date field onto the form yourself (you might need to make it a text field to start with then adjust the type in your form blueprint). And in the form to create submissions, store the current date, which you can get with [`{{ now }}`](https://statamic.dev/variables/now#content).

I know it's not ideal but it should get round the issue until it's been properly fixed/implemented.

**Comment by forby** [comment]
Nice, that's a really great suggestion @damcclean. 

I was able to get the date stored as a `submit_date` date field with that workaround and displayed fine, but it looks like form submissions are not sortable. At least it doesn't seem to be responding to any sorts that I throw at it—none of the stored fields. Maybe my issue is larger than just getting the date. The whole thing I was after was being able to sort by submission date.

```php
{{ form:submissions in="guestbook" sort="submit_date:desc" }}
    <div>
        Submitted on {{ submit_date format="M j Y (H:i:s)" }}<br>
        Name: {{ name }}<br>
        Comment: {{ comment }}
    </div>
{{ /form:submissions }}
```

**Comment by damcclean** [comment]
I think the sorting issue is different completely, I think it's the case of it possibly not being implemented at all. Would you mind opening another issue for that?

**Comment by forby** [comment]
Totally, yeah I can do that. Thanks!
