### ISSUE TITLE
Generic publishables aren't auto-published

### ISSUE THREAD

**Issue by Mamaduka** [statamic/cms#2979]
## Bug Description
In the addon, `$publishables` aren't automagically published when running `composer update` and  `$scripts`, `$stylesheets` properties are empty

## How to Reproduce
1. Add generic assets for publishing to the `$publishables` array.
2. Run `composer update`
3. Check if the origin directory was copied to the destination.

## Extra Detail
* Probably regression after c455733.
* I haven't tested this, but the issue might also be affecting auto-publishing `$config` and `$translations`.

## Environment

Statamic 3.0.32 Solo
Laravel 7.30.0
PHP 7.4.8
sortarad/ghostwriter dev-main
statamic/ssg 0.2.0

**Install method (choose one):**
- Starter kit

**Comment by damcclean** [comment]
What happens if you use `$scripts` and `$stylesheets` instead of using `$publishables`? Does that solve the problem or is it still the same?

**Comment by Mamaduka** [comment]
Hi @damcclean,

Yes, they work. But in my case, I don't need to provide them, since I'm not loading any assets in CP.

I mostly opened PR because [documantaion](https://statamic.dev/extending/addons#publishing-assets) says  `$publishables` are published after install.

**Comment by duncanmcclean** [comment]
Is this still an issue for you after #8151?

**Comment by duncanmcclean** [comment]
I'm going to close this issue now as I don't think this is a issue anymore after #8151.
