### ISSUE TITLE
Replicator labels don't turn red when there's a nested error

### ISSUE THREAD

**Issue by sjclark** [statamic/cms#2990]
![Screen Shot 2020-09-14 at 4 42 12 PM](https://user-images.githubusercontent.com/4531017/93052815-2858c180-f6aa-11ea-9211-c951e3a7246b.png)

It's possible to have this "given data was invalid" generic error triggered when you attempt to **Save & Publish** a page that has **fields that have failed validation** - an expected behaviour. However, if the fields failing validation are hidden within a collapsed element then you have to open all elements to track it down.

**Ideally it would be good to have items failing validation automatically re-open/toggle to highlight the red validation failure state.** OR maybe add a red failure state to the parent of the failed element?

EDIT: There was mention in the discord of this also occurring with **fields hidden in other tab sections**.

Have tried to somewhat explain through screenshots below as well:

![Screen Shot 2020-09-14 at 4 51 33 PM](https://user-images.githubusercontent.com/4531017/93053093-a74dfa00-f6aa-11ea-866d-a661e3176406.png)

![Screen Shot 2020-09-14 at 4 52 07 PM](https://user-images.githubusercontent.com/4531017/93053104-ac12ae00-f6aa-11ea-8f19-2da756548dcd.png)

**Comment by damcclean** [comment]
From what I can see this issue only happens when the replicator set is collapsed.

**Comment by sjclark** [comment]
@damcclean when I first lodged this it would also happen to fields in other **tabs**, or really anything hidden (including collapsed sets) - possible the tab issues been fixed, might be able to check later
