### ISSUE TITLE
Localize Entities in Antlers by default? - Multi-Site

### ISSUE THREAD

**Issue by jwahdatehagh** [statamic/cms#2991]
**What i have:**
- Two sites: `en` and `de`. 
- Two Entities - let's call them `Parent` and `Child`
- In the childs' blueprint an "Entry" Fieldtype points to a Parent. The field is not marked as "localizable" so that editors don't have to re-link entries in every language (which imho wouldn't make sense).
- There are translations for both a Parent entity and a Child entity; The latter points to the parent (by choosing the relationship in the 

**The problem:**
If i do the following in the template for a single parent it always shows me the default (en) version of the content, as that is what the parent ID links to.
```html
<p>Parent: <a href="{{ parent:url }}">{{ parent:title }}</a></p>
```

But if i e.g. do the following, all the entries resolve to the ones in the current locale/site.
```html
{{ collection:parents }}
    <li><a href="{{ url }}">{{ title }}</a></li>
{{ /collection:parents }}
```

I can't find a reasonable solution to this and would suggest to always resolve entity fields to the version in the current locale (if that exists), like the `collection` tag does...

**Comment by jasonvarga** [comment]
This is happening because your relationship field is called `parent`, which is a reserved word because it has its own special functionality associated to it.

If you rename it to `parents` or `parent_entry` it works fine.
