### ISSUE TITLE
Display-Rules not working for imported fieldset

### ISSUE THREAD

**Issue by HellPat** [statamic/cms#2992]
## Bug Description

When i import a field/fieldset into a blueprint it's not possible to display it depending on a rule.

![image](https://user-images.githubusercontent.com/1016798/101767993-50a75f00-3ae5-11eb-9154-40b1b5bf91ec.png)

with the field included directly this works.

![image](https://user-images.githubusercontent.com/1016798/101768058-67e64c80-3ae5-11eb-8ca7-24b4fc9e6c7b.png)

## Extra Detail

Does not work

```diff
  -
    handle: hide_content_on_mobile
    field:
      display: 'Inhalt mobil ausblenden'
      type: toggle
      icon: toggle
      width: 50
      listable: hidden
      if:
        content_align: 'not none'
  -
    import: wysiwyg
+    if:
+        content_align: 'not none'
```

Does not work

```diff
title: Wysiwyg
fields:
  -
    handle: content
+    if:
+      content_align: 'not none'
```

## Environment

```sh
$ php please support:details
Statamic 3.0.34 Pro
Laravel 7.29.3
PHP 7.4.9
No addons installed
```

**Install method (choose one):**
- [x] Fresh install from `statamic/statamic`
- [ ] Starter kit
- [ ] Existing Laravel app
- [ ] Other (please explain this magic!)

**Comment by jasonvarga** [comment]
This feature is for individual fields only.
