### ISSUE TITLE
Subject line in forms is not localisable

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2994]
## Bug Description
The subject line in forms is not localisable.

## How to Reproduce
Make a form on a localised site, use {{ trans:whatever.string }} in the subject field in the form builder. Won't translate in the actual mail. 

## Environment
Statamic 3.0.34 Pro
Laravel 8.18.1
PHP 7.4.10
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I've just tested on my test site (it's just a single site) and it works like it should. With both a out-the-box Laravel translation file and a custom one.

I'll try again later with a multi-site to see if that is causing the iissue.

**Comment by robdekort** [comment]
Yeah it uses the default sites translation for all sites if I remember correctly.

**Comment by robdekort** [comment]
Labeled my own issue as a bug as others confirmed it here https://github.com/statamic/cms/pull/2658
