### ISSUE TITLE
Sorting on entries field type doesn't sort by title

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#2995]
## Bug Description
When I have an entries field type in a blueprint, and then try to sort on that field in the CP, it doesn't sort in a logical way for the client. It seems that it's sorting on ID instead of title (even though it's showing the title in the table rows).

## How to Reproduce
Create an entries field type on a blueprint and try to sort on it after creating a few entries.

## Extra Detail
See two screenshots below (sorted ascending and descending), where the sort is not logical.

![Screenshot 2020-12-10 at 16 02 43](https://user-images.githubusercontent.com/9193686/101789103-26fc3100-3b01-11eb-9dcf-37f26d3e0882.png)
![Screenshot 2020-12-10 at 16 02 37](https://user-images.githubusercontent.com/9193686/101789123-2fed0280-3b01-11eb-8420-5c2b92e113cd.png)

## Environment
Statamic 3.0.30 Pro
Laravel 7.29.3
PHP 7.4.9

- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Confirmed. This type of sorting would probably only make sense if `max_items` on the entries fieldtype was set to 1.

**Comment by jelleroorda** [comment]
I think it would be nice if this could be fixed, though I’m not really sure myself how to go about it.

**Comment by ryanmitchell** [comment]
This seems to be working now, probably due to https://github.com/statamic/cms/pull/4967

![CleanShot 2023-12-03 at 09 36 48@2x](https://github.com/statamic/cms/assets/51899/c6bc223d-8bc8-4865-9ede-de66a321fa6c)

![CleanShot 2023-12-03 at 09 36 39@2x](https://github.com/statamic/cms/assets/51899/33831201-cf78-4f67-b8b1-046e8859aae1)
