### ISSUE TITLE
Overriding shallowAugmentedArrayKeys not working

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2997]
## Bug Description
Overriding shallowAugmentedArrayKeys according to docs do not work from the default sp. However, if you do create an addon and bind it there, it works.

I have also tried wrapping it in Statamic::booted. 

I was recommended to file this here. But there is also a support question through your website support area with the subject : API overriding shallowAugmentedArrayKeys for more information.

## Environment
**Statamic version:** 3.0.32

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Could you share the code your trying to use please?

**Comment by Pixney-William** [comment]
@damcclean 

```
// Neither of these work in the service provider.

$this->app->bind(
    \Statamic\Contracts\Entries\Entry::class,
    \App\CustomEntry::class
);

Statamic::booted(function () {
    $this->app->bind(
        \Statamic\Contracts\Entries\Entry::class,
        \App\CustomEntry::class
    );
});

// Custom entry class
class CustomEntry extends Entry
{
    protected function shallowAugmentedArrayKeys()
    {
        return ['title', 'mything'];
    }
}
```

**Comment by damcclean** [comment]
I'm not at my computer right now but does Statamic::bind work instead of $app->bind?

It might not but might be worth a chance.

**Comment by Pixney-William** [comment]
I will have a look when i get back to the project after the new year. If i can get around to it earlier i will update you.

Other then that, i am just following the docs: https://statamic.dev/extending/augmentation#shallow-augmentation

**Comment by Pixney-William** [comment]
For the record, Jason suggested in the support mail: $this->app->booted()

Couldn't get that to work either.. But i was stressed at that point so no gurarantees on my testing there :)

**Comment by afonic** [comment]
Shouldn't it be:

```
$this->app->bind(\Statamic\Contracts\Entries\Entry::class, function() {
    return new \App\CustomEntry;
});
```

**Comment by Pixney-William** [comment]
This has now been updated and fixed by the Statamic Team. 

[Updated documentation here](https://statamic.dev/content-api#customizing-resources)
