### ISSUE TITLE
Passing an array in partials is null or empty string

### ISSUE THREAD

**Issue by DoubleJ-G** [statamic/cms#3014]
## Bug Description
Trying to pass an array from one partial to another either results in `null` or `""` in the other view.

## How to Reproduce

- Fresh install of Statamic
- Create two partials
- Define an array in the frontmatter 

``` 
---
items: 
  - oranges
  - apples
  - bananas
---
```
- Pass the variable to another partial

`{{ partial:partial2 :items="view:items"}}` when using `{{ items | dump }}` in partial2 returns `null`
`{{ partial:partial2 items="{view:items}"}}` when using `{{ items | dump }}` in partial2 returns `""`

Viewing this data works fine in partial1, if the data is also anything other than an array it passes to partial2 just fine.

## Environment

Statamic 3.0.34 Solo
Laravel 8.18.1
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Nice find.

Looks like the parameter interpolation doesn't reach into `view`.
