### ISSUE TITLE
Blueprints: Conditions using other 'tab sections'

### ISSUE THREAD

**Issue by DoubleJ-G** [statamic/cms#3017]
## Bug Description

Using two tab sections such as `Main` and `Sidebar` setting a condition to show/hide the only displayed handles in the dropdown are from the current section. Although you are able to manually input a handle and this will be valid if it matches the handle of another field in a different section. If this is the expected behavior it would be nice to also have those handles show in the dropdown

## How to Reproduce

For a test case you can create a new toggle fieldtype with the handle `toggle` in the sidebar of a blueprint and in the main section add a plain text field with a show when condition, `toggle` won't be shown in the dropdown but you can enter it manually and set to show when enabled. Save the blueprint and create a new entry and use the toggle button and it will show/hide the field

## Environment

Statamic 3.0.34 Solo
Laravel 8.18.1
PHP 7.4.13
No addons install

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
So basically the bug here is "not all the fields are suggested".

There's nothing wrong with the conditions themselves, right?

**Comment by DoubleJ-G** [comment]
Hi Jason, that is correct.

**Comment by duncanmcclean** [comment]
This seems to be fixed now. I believe #8160 might have fixed it.
