### ISSUE TITLE
Multiple Conditions not persisting when looking at different values on select field

### ISSUE THREAD

**Issue by myleshyson** [statamic/cms#3019]
## Bug Description
Multiple conditions don't seem to persist when checking against multiple possible values on a single field, in this case the select field.

## How to Reproduce
Create a new blueprint with two select fields.  On the second select field, go to conditions and try to add a two conditions based on the first select field. Click finish and then go to conditions again on the second select field and notice only one condition persisted out of the two.

## Extra Detail

![ezgif-4-a6908db58192](https://user-images.githubusercontent.com/11747187/102251458-d440c180-3ed2-11eb-9ece-5d5fe2756884.gif)

## Environment

**Statamic version:** 3.0.34

**PHP version:** 7.4

**Install method (choose one):**
- Existing Laravel app

**Comment by jasonvarga** [comment]
The screenshot was so small that I couldn't actually see what you're doing, but I tried this and seems to fail if you've selected the same field twice.

If each condition is a different field, they all persist.

**Comment by jesseleite** [comment]
The way these conditions are stored in yaml, you can't have multiple conditions on the same field.  We should probably add validation errors for this in the UI.

I can't see what you're doing there, but what is your use case?  Can you screenshot the conditions you are wanting to setup so we can see?  Thanks!

**Comment by myleshyson** [comment]
Hey sorry about the small screencast. [Here is the dropbox sharing link for it](https://www.dropbox.com/s/77xfqsis6vfs4vj/Screen%20Recording%202020-12-15%20at%2012.36.23%20PM.mov?dl=0)

Here are screenshots describing what I mean as well. Essentially, I have an Events entry with a repeater field, Event Repeats. Within Event Repeats, have a group of fields like so. 
![Screen Shot 2020-12-16 at 12 13 34 PM](https://user-images.githubusercontent.com/11747187/102382178-226bc880-3f98-11eb-9926-1933c55d0757.png)

The Frequency field here is a select field with the following options. 
![Screen Shot 2020-12-16 at 12 16 17 PM](https://user-images.githubusercontent.com/11747187/102382496-82fb0580-3f98-11eb-9fe1-a382a92ca0db.png)

Now here is the bit I'm getting stuck on. I want the Day field **to only appear when either week or month are selected from the Frequency field**. So the thing that kicked off this report was me going into conditions in the Day field and trying to do something like this.
![Screen Shot 2020-12-16 at 12 19 31 PM](https://user-images.githubusercontent.com/11747187/102382938-f56be580-3f98-11eb-98f7-89ea3d4208a5.png)

Trying to get this to work so that when a user goes to select how often an event repeats, when they pick something like "Every weekday" the Day field doesn't show up, but if they pick "Every Month" then the day field does show up. 

![Screen Shot 2020-12-16 at 12 24 57 PM](https://user-images.githubusercontent.com/11747187/102383678-d1f56a80-3f99-11eb-9237-b64c10a46363.png)

All that being said, if it's impossible to get this to work with yaml, I might need to figure something else out. Validation here would help if that's the case.

**Comment by jesseleite** [comment]
![](https://user-images.githubusercontent.com/11747187/102382938-f56be580-3f98-11eb-98f7-89ea3d4208a5.png)

^ Thanks for the clarification on that. Right now the only way for checking a single field value against multiple values or conditions is to use a [custom JS condition](https://statamic.dev/conditional-fields#custom-logic).  In your case, I think you could:

```yaml
if:
  frequency: custom hasValue:week,month
```

```js
Statamic.$conditions.add('hasValue', ({ target, params }) => {
    return new RegExp(params.join('|')).test(target);
});
```

**Comment by myleshyson** [comment]
Oh snap thanks! Had to modify the snippet above a little but this works great. Also definitely missed that part of the docs 😅

**Comment by SuperHydroman** [comment]
Will the ever become a functionality in Statamic? For example being able to add more values for a the same field handle using <value1>|<value2>?

**Comment by SuperHydroman** [comment]
Will the ever become a functionality in Statamic? Being able to add more values for a the same field handle using |?

For example: <value1>|<value2>

**Comment by duncanmcclean** [comment]
> Will the ever become a functionality in Statamic? Being able to add more values for a the same field handle using |?

Maybe?

Feel free to add a 👍 reaction to the feature request: statamic/ideas#1101
