### ISSUE TITLE
Activation link not working

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#3020]
## Bug Description
When you skip to send the activation link via e-mail, there is shown a massage with the activation link.
When you copy the link and paste it, you get redirected to the homepage and it's not possible to set the password.

## How to Reproduce

1. Create user
2. Skip sending e-mail
3. Copy activation link and test it

## Environment

Statamic 3.0.34 Pro
Laravel 7.30.0
PHP 7.3.25

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
That's because you're already logged in.

Try testing the link in a different browser, or a private session.
