### ISSUE TITLE
Action Illuminate\Broadcasting\BroadcastController@authenticate not defined

### ISSUE THREAD

**Issue by aimensasi** [statamic/cms#3021]
## Bug Description
Integrating Statamic into an existing Laravel project.

Setting up locally (Mac OS), everything works as expected. However, during installation of composer packages on a staging server running (CentOS 7), I start receiving this issue and was not able to complete the setup.

```
Action Illuminate\Broadcasting\BroadcastController@authenticate not defined
```

Not sure what statamic has to do with broadcasting. However, After changing the following code inside `Statamic\Providers\BroadcastServiceProvider`, everything started working as expected.

```
   public function boot() {
        $this->app->booted(function () {
            $variables = $this->enabled() ? $this->variables() : ['enabled' => false];
            Statamic::provideToScript(['broadcasting' => $variables]);
        });
    }
```

Changes to 

```
   public function boot() {
        $this->app->booted(function () {
            $variables = ['enabled' => false];
            Statamic::provideToScript(['broadcasting' => $variables]);
        });
    }
```

## Extra Detail
```
[2020-12-16 11:30:44] local.ERROR: Action Illuminate\Broadcasting\BroadcastController@authenticate not defined. {"exception":"[object] (InvalidArgumentException(code: 0): Action Illuminate\\Broadcasting\\BroadcastController@authenticate not defined. at /var/www/myemcq.tth.asia/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:468)
[stacktrace]
#0 /var/www/myemcq.tth.asia/vendor/statamic/cms/src/Providers/BroadcastServiceProvider.php(42): Illuminate\\Routing\\UrlGenerator->action('Illuminate\\\\Broa...')
#1 /var/www/myemcq.tth.asia/vendor/statamic/cms/src/Providers/BroadcastServiceProvider.php(23): Statamic\\Providers\\BroadcastServiceProvider->authEndpoint()
#2 /var/www/myemcq.tth.asia/vendor/statamic/cms/src/Providers/BroadcastServiceProvider.php(14): Statamic\\Providers\\BroadcastServiceProvider->variables()
#3 /var/www/myemcq.tth.asia/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): Statamic\\Providers\\BroadcastServiceProvider->Statamic\\Providers\\{closure}(Object(Illuminate\\Foundation\\Application))
#4 /var/www/myemcq.tth.asia/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\\Foundation\\Application->fireAppCallbacks(Array)
#5 /var/www/myemcq.tth.asia/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#6 /var/www/myemcq.tth.asia/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#7 /var/www/myemcq.tth.asia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#8 /var/www/myemcq.tth.asia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#9 /var/www/myemcq.tth.asia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#10 /var/www/myemcq.tth.asia/public/index.php(60): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#11 {main}
"}
```

## Environment

Statamic 3.0.33 Pro
Laravel 8.16.1
PHP 7.4.13

**Install method (choose one):**

- Existing Laravel app

**Comment by jasonvarga** [comment]
Does `vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastController.php` exist on the server? Does it have an `authenticate` method?

**Comment by aimensasi** [comment]
Sorry for the late replay, did not see your response.

Yes the controller exists and has an authenticate method.

```
<?php

namespace Illuminate\Broadcasting;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Broadcast;

class BroadcastController extends Controller
{
    /**
     * Authenticate the request for channel access.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function authenticate(Request $request)
    {
        if ($request->hasSession()) {
            $request->session()->reflash();
        }

        return Broadcast::auth($request);
    }
}
```

**Comment by damcclean** [comment]
In the `providers` array in `config/app.php`, is the Illuminate `BroadcastServiceProvider` in there?

**Comment by aimensasi** [comment]
yes it is and FYI, I am using the broadcast service in the project with websockets

**Comment by aimensasi** [comment]
This is what I have inside the broadcast service 


```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Broadcast;
use Illuminate\Support\ServiceProvider;

class BroadcastServiceProvider extends ServiceProvider {
	/**
	 * Bootstrap any application services.
	 *
	 * @return void
	 */
	public function boot() {
		Broadcast::routes();

		require base_path('routes/channels.php');
	}
}
```

**Comment by damcclean** [comment]
Okay! I'm not entirely sure what's causing the issue that you're running into. I would have presumed Statamic would just work out of the box with the broadcasting stuff.

Just one more thing: if you temporarily comment out your `BroadcastServiceProvider` in your `app.php` and just leave the Illuminate one in place, does it start to work, or is it just the same thing? 

I'm basing that on the fact that the `config/app.php` file provided in the default `statamic/statamic` starter kit has the Illuminate one uncommented and the custom one commented out. [See here](https://github.com/statamic/statamic/blob/master/config/app.php#L174).

It might be a good idea to wait for the Statamic Team to come back online after the new year to look into the issue. I'm stuck sadly, I don't know much about broadcasting and my Googling didn't really help at all  😂

**Comment by aimensasi** [comment]
I actually have tried that, but it did not help. Thanks for your help. I hope to see a response from them soon.

**Comment by jasonvarga** [comment]
Just to confirm, when I [asked](https://github.com/statamic/cms/issues/3021#issuecomment-746562538) if the class existed, you're definitely checking on the server and not just in your local repository?

**Comment by aimensasi** [comment]
May be it is because of the cache, because after upgrading to the latest version to get the fix for [this](https://github.com/statamic/cms/issues/1721#issue-604931785). The issue started appearing on local too during running the caching command. 

the command is `php artisan optimize`

**Comment by podcasthosting** [comment]
We have the same problem. We also use Websockets. The problem also only arises after running `php artisan optimize`. Emptying the bootstrap/cache directory helps temporarily.

**Comment by AlexanderFalkenberg** [comment]
I have the same issue on production, when using php artisan route:cache.

**Comment by jasonvarga** [comment]
For for 3.1
