### ISSUE TITLE
The [class*=btn] selector in the control panel breaks fieldtypes with btn in their handle

### ISSUE THREAD

**Issue by Eworm** [statamic/cms#3022]
## Bug Description
There's a ```[class*=btn]``` selector in the control panel css. This styles elements based on their classname, but will also style fieldtypes if they have ```btn``` in their name.

## How to Reproduce
Add a text fieldtype with a handle ```btn_title```.

## Extra Detail
<img width="924" alt="Schermafbeelding 2020-12-16 om 12 23 26" src="https://user-images.githubusercontent.com/511488/102342479-9195ec80-3f99-11eb-8581-b23e0dc6995f.png">
<img width="956" alt="Schermafbeelding 2020-12-16 om 12 23 45" src="https://user-images.githubusercontent.com/511488/102342482-92c71980-3f99-11eb-8eae-9dacccc9bf1e.png">

## Environment
Statamic 3.0.32 Pro
Laravel 8.17.0
PHP 7.4.13
serieseight/statamic-uuid 2.0.0
statamic/migrator dev-master

**Install method (choose one):**
Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Yup, it's most defiantly broken 😆
