### ISSUE TITLE
[UI] The mobile interface doesn't fill with the width of the layout.

### ISSUE THREAD

**Issue by tolawho** [statamic/cms#3030]
## Bug Description
1. The mobile interface doesn't fill with the width of the layout.
2. When the number of columns of the data sheet exceeds the width of the layout screen you will see it breaks as I marked in figure 2. 
## How to Reproduce

1. Visit collection entry view
2. Open Chrome Dev Tools and the mobile simulator thingy
3. Select responsive as the device (My case is Iphone X ).
4. Search things to show "No results"

## Extra Detail
![Profile-20201218T112711](https://user-images.githubusercontent.com/12527881/102574739-1a409400-4124-11eb-970f-d387b1dd2ada.gif)
![image](https://user-images.githubusercontent.com/12527881/102575126-14977e00-4125-11eb-87d2-a046e29337bd.png)

![image](https://user-images.githubusercontent.com/12527881/102575916-e5820c00-4126-11eb-9416-629a83998b18.png)

## Environment

Statamic 3.0.35 Pro
Laravel 8.19.0
PHP 7.4.3

**Comment by duncanmcclean** [comment]
I can confirm, I can see the same issue where the full width of the screen isn't used on mobile.

**Comment by robdekort** [comment]
I noticed there's still a lot of UI issues on mobile. Even on a Max iPhone a bunch of pages contain visual issues and can't be used properly. In case core wants to tackle this: my own site has a public repo, is multisite and up to date. It might be a nice one to test with. 
![image](https://user-images.githubusercontent.com/69107412/199500350-e1850735-0f6a-465f-9d19-737e6e29601c.png)![image](https://user-images.githubusercontent.com/69107412/199500377-81bef38d-81cb-4c44-b4f1-44dcd28cefa4.png)![image](https://user-images.githubusercontent.com/69107412/199500403-a4fbbb04-ed4e-433c-b81c-3de0d19eb0f4.png)![image](https://user-images.githubusercontent.com/69107412/199500425-03eeb2b0-3a8f-4cb3-bacd-5deab5024815.png)![image](https://user-images.githubusercontent.com/69107412/199500451-41197bfc-3d89-4c02-bf3d-51af386fac9a.png)

**Comment by jackmcdade** [comment]
Fixed by https://github.com/statamic/cms/pull/7589
