### ISSUE TITLE
Markdown links with params can return a "Format is invalid" error

### ISSUE THREAD

**Issue by tao** [statamic/cms#3041]
## Bug Description
I'm encountering a 422 error when creating a markdown link. The content in the markdown field causing the problem is:

```markdown
If you are interested in purchasing a copy for yourself, you can visit the book's listing in our online store by clicking on [this link](http://store.bring4th.org/product_info.php?cPath=21&products_id=54).
```

The CMS returns a popup error "The given data was invalid."

```json
{
    "message": "The given data was invalid.",
    "errors": {
        "content": [
            "Format is invalid."
        ]
    }
}
```

The link however works if you remove the url parameters:

```markdown
[this link](http://store.bring4th.org/product_info.php)
```

There is nothing being added to the log about the error.

## Environment
Statamic 3.0.35 Pro
Laravel 8.19.0
PHP 7.4.12

**Comment by tao** [comment]
I just encountered this with another link too:

```markdown
[Living the Law of One 101 Audiobook, Audible.com](https://www.audible.com/pd/B075313LTV/?source_code=AUDFPWS0223189MWT-BK-ACX0-094612&ref=acx_bty_BK_ACX0_094612_rh_us)
```

**Comment by jackmcdade** [comment]
I can't recreate this. What browser are you using?

**Comment by tao** [comment]
Okay. I investigated this some more, it seems there was some strange regex validation in the blueprint causing this issue. So that must have been my fault from ages ago... sorry about that.

```
      -
        handle: content
        field:
          ...
          validate:
            - required
            - 'not_regex:/(\_(.*)\_)/i'
```

https://user-images.githubusercontent.com/1446331/102860312-42870600-4436-11eb-9276-a5708fc45632.mov

That was a tricky one to figure out... maybe we can learn from this and start thinking about a new feature request for better validation errors?

**Comment by jackmcdade** [comment]
Sounds good!
