### ISSUE TITLE
My custom fieldtype not available when adding fields to a form blueprint.

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#3044]
## Bug Description
Before you supported file uploads, i created a custom "dropzone" fieldtype, Which my client used within their forms. Recently with one of the updates the number of fields offered to you when creating a form field time has been limited to just a few. And so , my custom field type don't show up.

What can i do to make it possible for them to use it again?

**These are the only fields available to choose from:**
![image](https://user-images.githubusercontent.com/31292231/102803370-70c60080-43b8-11eb-91a6-3ca7d896c1c7.png)

**Comment by jasonvarga** [comment]
Only those 7 fieldtypes are intentionally selectable.

Similar request to statamic/ideas#409
