### ISSUE TITLE
Locales tag does mix up the actual used locale on a page

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#3047]
### The problem

In the head of my page, I do have a link to visit the page in my second language. There are only 2 languages available.

```
{{ if site === 'default' }}
     {{ locales:en }}
        <a href="{{ url }}">EN</a>
    {{ /locales:en }}
  
{{ else }}
    {{ locales:default }}
        <a href="{{ url }}">DE</a>
    {{ /locales:default }}
{{ /if }}
```

Everything else coming after this snippet will be translated into the wrong locale. It feels like there are some problems with scoping. 

### My workaround for this:

```
{{ if site === 'default' }}
     {{ locales:en }}
        <a href="{{ url }}">EN</a>
    {{ /locales:en }}
   {{ locales:default }}{{ /locales:default }}
{{ else }}
    {{ locales:default }}
        <a href="{{ url }}">DE</a>
    {{ /locales:default }}
    {{ locales:en }}{{ /locales:en }}
{{ /if }}
```

**Statamic version:** 3.0.34

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by arthurperton** [comment]
Hi Jonas, I can't seem to recreate this one. Is it still happening in v3.1.3? And if so, could you provide some detailed steps?

**Comment by jonassiewertsen** [comment]
I didn't check with 3.1 for now but will update soon and get back to this issue then.
