### ISSUE TITLE
Pushed CP routes have Statamic namespace

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#3048]
## Bug Description

While reviewing https://github.com/statamic/docs/pull/235 I noticed that manually using `Statamic::pushCpRoutes()`, the namespace used is `Statamic\Http\Controllers\CP`. This is pointless if you're using it an app - you aren't going to put your controllers in our namespace. For addons, we explicitly override it, which is fine, but for app code it should just default to the Laravel default of `App\Http\Controllers`.

## How to Reproduce

```php
    public function boot()
    {
        Statamic::pushCpRoutes(function () {
            Route::get('foo', 'FooController@show');
        });
    }
```

Run `php artisan route:list --path=foo` and notice the class of the controller.

## Environment

**Statamic version:** 3.0.35

**Comment by jelleroorda** [comment]
I personally always use the callable syntax, but I believe that doesn’t work when a namespace is set. So could we not set the namespace? If someone wants to use a namespace they can always add it on a route group that they put inside the pushCpRoutes.

**Comment by jasonvarga** [comment]
I'd rather default to whatever Laravel defaults to. You're free to wrap in a Route::namespace(null)->group(...) closure.

**Comment by damcclean** [comment]
From Laravel 8 onwards, I think that using strings for the controller names is [no longer the recommended way](https://laravel.com/docs/8.x/upgrade#automatic-controller-namespace-prefixing) to do it and that instead it's to [use the class syntax](https://laravel.com/docs/8.x/routing#the-default-route-files), like so:

```php
Statamic::pushCpRoutes(function () {
  Route::get('/foo', [FooController::class, 'index']);
});
```

In which case I think it would probably just be best to document using the class syntax instead of the string syntax when referencing controllers?

**Comment by jasonvarga** [comment]
Good find. 

But then we're left in the situation that addon routes _do_ have the prefix, and removing it would be a breaking change.
If we add a Laravel 7 standard prefix to non-addon routes, it would be consistent with our existing addon routes, but not consistent with Laravel 8.

🤔

**Comment by edalzell** [comment]
Can we check to see if the 
<img width="524" alt="CleanShot 2021-08-29 at 12 05 41@2x" src="https://user-images.githubusercontent.com/6069653/131262397-2ef7cf8d-3c4a-4db8-9c27-59af718c1678.png">
 is set?

**Comment by duncanmcclean** [comment]
Can this issue be closed now? I see it was mentioned in a PR back in February #7069.

**Comment by jasonvarga** [comment]
Yup! Namespace is removed in v4.
