### ISSUE TITLE
From param on navigation not working in some cases

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#3049]
## Bug Description
I get a `Cannot get a nested starting position on a navigation structure.` error when I try to use, on a sub nav.

```
{{ nav:portfolio from="{segment_1}/{segment_2}" }}
  <li>
    {{ title }}
  </li>
{{ /nav:portfolio }}
```

My URLs look like:
- http://donfoulds.com.test/portfolio/birds
- http://donfoulds.com.test/portfolio/birds/cormorant
- http://donfoulds.com.test/portfolio/birds/cormorant-with-fish
- ...

My Navigation is configured like:
![image](https://user-images.githubusercontent.com/1778271/103009430-c60f2880-4504-11eb-9eb9-aa93c083f740.png)

I find if I comment out lines 21-25 in `vendor/statamic/cms/src/Structures/TreeBuilder.php` it just works ... not sure why this code is there, or if it is just a bug?

```php
if ($from && $structure instanceof Nav) {
    throw new \Exception(
        'Cannot get a nested starting position on a navigation structure.'
    );
}
```

## Extra Detail
Here is the start of where I asked about this in Discord: https://discord.com/channels/489818810157891584/489819906540568593/791304631493591050

## Environment

```
Statamic 3.0.35 Solo
Laravel 8.20.1
PHP 7.4.13
No addons installed
```

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
The `from` parameter only works on collections.

It's not reliable on navs because you can place links wherever you want. They don't always correspond to your actual URL structure.

If your nav _does_ correspond to your actual URL structure, perhaps you're better off just making the collection structured.
Is there a reason why you have a separate portfolio nav and don't just make the portfolio collection orderable?

**Comment by jcohlmeyer** [comment]
I saw navigation, and thought they were the way you made navigation, I did not know you could use structured collections for navigation. I will remove my navigation and just collections. Thanks.

**Comment by jcohlmeyer** [comment]
Maybe this error message could be improved to say something like:

`The from parameter is not supported for navigations, it only works for collections. See [Link to Docs](...).
