### ISSUE TITLE
Cannot query a custom date field with a carbon instance

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#3050]
## Bug Description

When querying against a `date` field, we can pass a carbon instance like this:

```php
$query->where('date', '>=', \Carbon\Carbon::today());
```

But an exception is thrown when querying custom date field with a carbon instance:

```php
$query->where('event_start', '>=', \Carbon\Carbon::today());
```

There was a hacky attempt at fixing this in #2624. I don't know the proper solution.

## Environment

**Statamic version:** 3.0.35

**PHP version:** 7.4

**Comment by jelleroorda** [comment]
Haven’t tested, but I suppose this one should also be fixed through https://github.com/statamic/cms/pull/5156

**Comment by jesseleite** [comment]
Yessir 🎉
