### ISSUE TITLE
Variable in partial doesn't show

### ISSUE THREAD

**Issue by cgrisar** [statamic/cms#3056]
## Bug Description
Variable passed in partial doesn't show
## How to Reproduce

- Create a partial that contains the variable
- tag the variable eg {{ variable }}
- Pass the variable with the partial tag {{ partial:partial variable="variable_to_show" }}
- 
## Environment

**Statamic version:** 3.0.35

**PHP version:** 7.4.13

**Install method (choose one):**
- Starter kit

**Comment by damcclean** [comment]
Hey! You'll need to add a `:` before the parameter name. From your provided example, here's how I would do it.

`{{ partial:partial :variable="variable_to_show" }}`

Without the `:`, it'll treat `variable_to_show` as just a string and that will be what is passed in, whereas if you use the `:`, it'll know to fetch the value of the parameter from the Cascade and pass it into the partial.

Hopefully that solves your issue!

**Comment by cgrisar** [comment]
Yes, I tried that before entering the bug.
It doesn't work (on my side)

**Comment by jasonvarga** [comment]
How are you using it inside your partial?

**Comment by cgrisar** [comment]
First, I tried using variables inside my partial.

For instance:

`_wineheader.antlers.html`

```
<div class="flex flex-row items-center justify-between mb-4">

    <div class="flex">
        <!-- color of the wine --> 
        {{ c }}
            <span class="rounded-full h-6 w-6 bg-{{ color }}" title="{{ title }}"></span>
        {{ /c }}

        <!-- type of wine -->
        {{ t }}
            {{ if image }}
                <img class="w-6 h-6 ml-2" src="{{ image }}{{ url }}{{ /image }}" alt="{{ title }}" title="{{ title }}">
            {{ /if }}
        {{ /t }}

        <!-- mode of culture -->
        {{ m }}
            {{ if image }}
                <img class="w-6 h-6 ml-2" src="{{ image }}{{ url }}{{ /image }}" alt="{{ title }}" title="{{ title }}">
            {{ /if }}
        {{ /m }}
    </div>

    <div class="flex items-center">
        <a href="https://www.facebook.com/sharer.php?u=levipe.be{{url}}" title="Facebook">
```

On the last line, the url doesn't show

So, I tried passing a variable in my partial tag:

`{{ partial:wineheader :page="url" }}`

Using `{{ page }}` in my partial shows nothing

**Comment by damcclean** [comment]
Could you try renaming the variable from `page` to something else? `page` could be a reserved term in the cascade which might cause the issue?

Also, when you're referencing variables in your partial, you should be able to do it like this:

```
{{ page:image }}
{{ page:url }}
```

**Comment by cgrisar** [comment]
Well, I finally found it.
It was in the filename.
Some variables work with the .html extension and some only with antlers.html extension.
My apologies!

**Comment by damcclean** [comment]
Glad you managed to sort it!
