### ISSUE TITLE
Call to a member function allowUploads() on null on multiple images

### ISSUE THREAD

**Issue by icemancast** [statamic/cms#3059]
## Bug Description
When uploading multiple images more than 2 I get a ui "server error" and 500 error in the console. The actual server log error is below. It is successful in uploading only 2 images of at a time while anything above the 2 will error out with the same message. Each image is less than 1mb.

## How to Reproduce
Drag and drop more than 2 images onto the image field to upload.

## Extra Detail

```
[2020-12-30 22:50:56] production.ERROR: Call to a member function allowUploads() on null {"userId":"6631af6b-dddb-45c9-bf35-1c5fd6331d7d","exception":"[object] (Error(code: 0): Call to a member function allowUploads() on null at /home/forge/solomonsphotography.com/vendor/statamic/cms/src/Http/Controllers/CP/Assets/AssetsController.php:76)
```

## Environment

Statamic 3.0.31 Solo
Laravel 7.29.3
PHP 7.4.5
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Two questions:

1. Have you got a `container` set on the asset field you're uploading in (provided you're using an asset field and not the asset browser)
2. Are you using a local filesystem or a remote one like S3 or DigitalOcean Spaces?

From the face of it, this issue seems to be the same as #1663, your other issue.

**Comment by icemancast** [comment]
1. Yes I do have a container. The container is called assets and I wonder if that is a naming conflict.
2. filesystem is s3

**Comment by damcclean** [comment]
Okay, sounds like it's the same as the other issue. I'll close this one now.

**Comment by icemancast** [comment]
It was, didn't realize I submitted already. It's fixed now.
