### ISSUE TITLE
Taxonomies ignore locale (for sorting)

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#3063]
I have a multi-site installation with three languages: de/fr/en, where fr is the default. The site has a simple taxonomy with title and slug. On the german page (note that "de" is not the default site, but probably the first one when sorted alphabetically: de -> en -> fr), the terms are correctly sorted by title in the CP:

<img width="535" alt="grafik" src="https://user-images.githubusercontent.com/8578668/103482013-9c94ad80-4dde-11eb-9b67-5537fb25902e.png">

When I switch to the french page, the terms are in the same order they are on the german page, while they should now be sorted by the french titles (same goes for english page):

<img width="540" alt="grafik" src="https://user-images.githubusercontent.com/8578668/103482066-e2517600-4dde-11eb-912e-30828a447827.png">

This also happens on the frontend, when I render the taxonomies using:

```
{{ taxonomy:project_sections sort="title" }}
{{ title }}
{{ /taxonomy:project_sections }}
```

My guess is, that the first locale (de) is used internally to retrieve the taxonomies.

I also tried pure PHP to retrieve the taxonomies:

```
dd(\Statamic\Facades\Term::whereTaxonomy('project_sections'));
```

The output is always the same, no matter the site I visit:

<img width="369" alt="grafik" src="https://user-images.githubusercontent.com/8578668/103482295-65270080-4de0-11eb-97ab-21277ae69a95.png">

Note that "locale" is always "de".

**Statamic version:** 3.0.36

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`, but upgrading a V2 site using the Migrator

**Comment by damcclean** [comment]
I wonder if it's being sorted before you switch locales instead? Anyway, I think [this is the place](https://github.com/statamic/cms/blob/1f11c9c89338de0a980ff476875c7f0a9bf697a8/src/Http/Controllers/CP/Taxonomies/TermsController.php#L41) the ordering is coming from...

**Comment by FlorianMoser** [comment]
> I wonder if it's being sorted before you switch locales instead?

I'm not sure what you mean. But the default locale on my site is "fr". So "fr" is set by default, before sorting is done. So I don't think its something like a session issue.

**Comment by j3ll3yfi5h** [comment]
Same problem...

@FlorianMoser Did you find a workaround?

**Comment by FlorianMoser** [comment]
> @FlorianMoser Did you find a workaround?

You mean besides keeping my fingers crossed so the client doesn't notice it? Nope ;-)

But a workaround for the frontend would be to read the taxonomies into an array and sort it before displaying it.

**Comment by j3ll3yfi5h** [comment]
I finally did a workaround in a global with a term field per taxonomy. Sorting manually works as expected. 👍
