### ISSUE TITLE
Save current date on entry save as default

### ISSUE THREAD

**Issue by tofraweb** [statamic/cms#3069]
The current date is populated in the date field (as default) but when trying to save the new entry, the 'date field is required' message shows up. I have to pick the same date manually, then I can save the entry. It looks like a vue component issue.
## How to Reproduce
Trying to save a new entry
## Extra Detail
![Screenshot from 2021-01-05 10-41-04](https://user-images.githubusercontent.com/27404850/103625020-08902680-4f43-11eb-917c-80696b2846ac.png)

## Environment

Statamic 3.0.36 Pro
Laravel 7.28.4
PHP 7.4.9
statamic/seo-pro 2.0.14
statamic/ssg 0.2.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by tofraweb** [comment]
I have to pick the date manually again, then I can save the entry. It looks like a vue component issue.

**Comment by damcclean** [comment]
Are you using the date field provided by Statamic on dated collections or are you using a custom date field (if so, would you mind providing the field from your blueprint file)?

**Comment by tofraweb** [comment]
Using date field the Statamic provides.
----
      -
        handle: publish_date
        field:
          mode: single
          time_enabled: true
          time_required: true
          earliest_date: '2000-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: 'Publish Date'
          type: date
          icon: date
          listable: true
          validate:
            - required
      -

**Comment by j3ll3yfi5h** [comment]
Having the same issue

**Comment by grideca** [comment]
Same issue here, for me this happens on every save of the entry.

**Comment by jackmcdade** [comment]
Statamic's native date field is named `date`, not `publish_date`. Did you add that field yourself? Just trying to recreate this issue.

**Comment by helloiamlukas** [comment]
I think I found the issue. The problem is that the `Statamic\Fieldtypes\Date` field only checks for the `required` attribute within the blueprint. 

https://github.com/statamic/cms/blob/3.1/src/Fieldtypes/Date.php#L96

If you are configurating the blueprint via the CMS and want to make this field required, you have to define a validator rule. But after that, the blueprint looks like this

```yaml
    handle: xyz_date
    field:
      validate:
        - required
      ...
```

and not like this

```yaml
    handle: xyz_date
    field:
      required: true
      ...
```

Therefore the value of this field will be `null` instead of the current timestamp. Still, within the Vue component the current date will be shown.

**Comment by tofraweb** [comment]
> I think I found the issue. The problem is that the `Statamic\Fieldtypes\Date` field only checks for the `required` attribute within the blueprint.
> 
> https://github.com/statamic/cms/blob/83aededfed1bdacbb1c51f1452d0167803d98f38/src/Fieldtypes/Date.php#L96
> 
> If you are configurating the blueprint via the CMS and want to make this field required, you have to define a validator rule. But after that, the blueprint looks like this
> 
> ```yaml
>     handle: xyz_date
>     field:
>       validate:
>         - required
>       ...
> ```
> 
> and not like this
> 
> ```yaml
>     handle: xyz_date
>     field:
>       required: true
>       ...
> ```
> 
> Therefore the value of this field will be `null` instead of the current timestamp. Still, within the Vue component the current date will be shown.
> 
> **Edit:** I created a pull request now that fixes this issue – Feedback is welcome

Yes! It works now, thanks @helloiamlukas!
