### ISSUE TITLE
Visit URL button shows on entries in a collection that has no routes

### ISSUE THREAD

**Issue by twd3** [statamic/cms#3072]
## Bug Description
I have some collections that don't need routes and Jason said today that if you have a collection with no route the "Visit URL" button shouldn't show but it is.

Jason comment: https://github.com/statamic/ideas/issues/424#issuecomment-754789137

## How to Reproduce
Make collection without a route. Make an entry in collection and see that the "Visit URL" button is showing and it just goes to the home page if you click it.

## Extra Detail
![see](https://user-images.githubusercontent.com/16004958/103716100-722e2600-4f7f-11eb-9e9d-43b0a02eedaa.jpg)

## Environment
Statamic 3.0.36 Solo
Laravel 8.20.1
PHP 7.4.13
aryehraber/statamic-captcha 1.1.0
spatie/statamic-responsive-images 1.7.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by twd3** [comment]
Just realized the live preview button is the one that currently hides on these route-less collections. I'm thinking they should both hide...

**Comment by damcclean** [comment]
I've submitted a pull request to fix this issue: #3080.
