### ISSUE TITLE
Bard field does not parse for horizontal rules in v3

### ISSUE THREAD

**Issue by jtfridsma** [statamic/cms#3074]
## Bug Description

When entering text content into any Bard field via the control panel, Bard no longer parses for horizontal rules. On a new line, it is expected that typing three dashes (`---`) will result in a replacement of the dashes with an `<hr>` element. This happened with v2 and no longer happens with v3.

## How to Reproduce

1. Log into control panel for a Statamic v3.0.x site
2. Locate any Bard field
3. Type `---` on a new line within the Bard field
4. If a horizontal rule does not replace the dashes, hit Enter to attempt to persuade Bard to do so
5. Still no horizontal rule

#### V3
![image](https://user-images.githubusercontent.com/20193414/103793974-2b3d4080-5012-11eb-8354-9ba47c0f5bd6.png)
![image](https://user-images.githubusercontent.com/20193414/103793990-2ed0c780-5012-11eb-859f-e1f0b879f7e5.png)
![image](https://user-images.githubusercontent.com/20193414/103794000-31cbb800-5012-11eb-995a-fa7387ae1bfd.png)

#### V2 comparison
![image](https://user-images.githubusercontent.com/20193414/103794291-8ec76e00-5012-11eb-8d0a-043cf3a45f4c.png)
![image](https://user-images.githubusercontent.com/20193414/103794326-98e96c80-5012-11eb-9b36-58b9744e94e9.png)
![image](https://user-images.githubusercontent.com/20193414/103794476-c0d8d000-5012-11eb-93e9-dcf5c523efce.png)

## Environment
All environments (production, dev).

**Statamic version:** 3.0.30

**PHP version:** 7.4

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
Great issue, thanks.
