### ISSUE TITLE
Moving assets causes entries to lose those assets

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#3081]
## Bug Description

When moving an asset in the asset manager, entries that had that asset selected lose a reference to it.

## How to Reproduce

1. Create an entry with an asset field
2. Add an asset to that field
3. Move the asset to a folder

## Environment

**Statamic version:** 3.0.37

**PHP version:** 8.0

**Install method (choose one):**
- Starter kit

**Comment by jackmcdade** [comment]
That's how basically every CMS asset manager works – it's a huge endeavor to come up with a solution to scan all of the data in the entire site to update references whenever a file name is changed. I think this is more a feature request than a bug – what do you think @jasonvarga?

**Comment by riasvdv** [comment]
> That's how basically every CMS asset manager works

That's a wrong statement, I know for a fact this works in CraftCMS as an example, but I do know this is easier to solve in a database driven environment, as they use IDs to reference assets, the path is stored in the db next to the id

**Comment by jasonvarga** [comment]
We have the scary warning when you try to rename an asset, but not when you move it. I wrongly assumed it was on both actions.

We can easily add that warning, at least.

![image](https://user-images.githubusercontent.com/105211/103904132-dd384380-50ca-11eb-94da-dd1e14a10ee9.png)
![image](https://user-images.githubusercontent.com/105211/103904154-e45f5180-50ca-11eb-9ab0-b9b66718ee24.png)

**Comment by afonic** [comment]
I know that we are in feature request territory here, but couldn't adding an asset to an entry update the asset's meta .yaml file to add that association? This association could be deleted if the asset is removed from the entry or if the entry is deleted.

That way it could at least show a warning, like "This asset is linked to these entries: [...] if you move/delete it will result in broken links" rather than a general warning that appears everywhere and provides no useful info.

**Comment by felixstoessel** [comment]
@jasonvarga Yes. Please add this warning for every way things can break (move, rename, something else?).

**Comment by strebl** [comment]
Any updates on this issue? I think the warning for moving assets would improve the situation. But in my opinion it is important to handle the moving of assets.

For example: We have a client with a growing site. Now they are at the point on which they want to create folders to improve the clarity. 

Currently they can't move the assets without losing them on the entries and they also have no way to see where the assets are used or even if they are in use at all. I'm kinda fine with the rename limitations. But I think moving assets on growing sites isn't a negligible special case. What do you guys think?

**Comment by jesseleite** [comment]
Coming in 3.2 🤘

**Comment by axelferdinand** [comment]
I just tried relocating a few assets from Assets in CP on one of my sites (latest update 4.52.0) and none of the paths were updated..?

**Comment by duncanmcclean** [comment]
> I just tried relocating a few assets from Assets in CP on one of my sites (latest update 4.52.0) and none of the paths were updated..?

This issue is over 2 years old at this point. Are you able to open a new issue instead? Feel free to reference this one.

**Comment by theLeroy** [comment]
@axelferdinand we are also running into very strange behaviour.. have you found a solution?
