### ISSUE TITLE
User last login date

### ISSUE THREAD

**Issue by crackAT** [statamic/cms#3084]
## Bug Description
User last_login field not set (always null)
## How to Reproduce
using Database User and login
## Environment

Statamic 3.0.37 Pro
Laravel 8.21.0
PHP 7.3.11
4rn0/statamic-v3-image-optimizer 1.0.4
phpsa/statamic-analytics 1.0.0
statamic/eloquent-driver 0.1.0

**Comment by damcclean** [comment]
After some digging, looks like it's related to #1195, where if the user is not an instance of the Statamic User contract, then the last login date won't be set. 

I'm not quite sure of a fix for this at the moment but if you need it to be set, here's a workaround:

1. Create a new event listener, which sets the `last_login` column on your `User` model (make sure that `last_login` is fillable and it is cast to a `datetime` in your model)
2. Register that event listener in your `app/Providers/EventServiceProvider.php`, under the `Login` event provided by Laravel...

**app/Providers/EventServiceProvider.php**

```php
protected $listen = [
  \Illuminate\Auth\Events\Login::class => [
    \App\Listeners\SetLastLoginTimestamp::class,
  ],
];
```

**app\Listeners\SetLastLoginTimestamp.php**

```php
<?php

namespace App\Listeners;

use Illuminate\Auth\Events\Login;
use App\User;

class SetLastLoginTimestamp
{
    public function handle(Login $event)
    {
        // $event->user in this case would be your User model
        $event->user->update(['last_login' => now()]);
    }
}
```

**Comment by kevnk** [comment]
Thanks, @duncanmcclean — That worked perfectly for me!
