### ISSUE TITLE
Image validation type disallows SVG assets

### ISSUE THREAD

**Issue by sjclark** [statamic/cms#3087]
## Bug Description
Saving an asset field with the validation type `image` results in an error message `must be an image` when you attempt to save an uploaded/selected SVG.

## How to Reproduce
Attempt to save an SVG image into an asset fieldtype with `image` validation type.

## Extra Detail
See [Laravel Validation Docs -> Direct Link to Image Rule](https://laravel.com/docs/8.x/validation#rule-image)
<img width="365" alt="Screen Shot 2021-01-08 at 11 22 13 am" src="https://user-images.githubusercontent.com/4531017/103959587-2f00cc80-51a4-11eb-9f44-0525e9300fdc.png">
<img width="331" alt="Screen Shot 2021-01-08 at 11 22 35 am" src="https://user-images.githubusercontent.com/4531017/103959592-31fbbd00-51a4-11eb-9a26-f1c7d63dd397.png">
<img width="677" alt="Screen Shot 2021-01-08 at 11 22 42 am" src="https://user-images.githubusercontent.com/4531017/103959598-34f6ad80-51a4-11eb-8a34-63545602e93b.png">

## Environment
```
Statamic 3.0.37 Pro
Laravel 8.21.0
PHP 7.4.12
No addons installed
Fresh Install
```

**Comment by jasonvarga** [comment]
See #1956

**Comment by sjclark** [comment]
Is there any context in which the filters in that menu actually work then?
If `image` `mime` `file` etc don't work then would it not make more sense to remove them from the dialogue?

**Comment by jasonvarga** [comment]
Maybe, but it's simply a list of all of Laravel's validation rules.
If we removed this, we'd need to conditionally remove any other validation rules that don't apply to every applicable field too. Pretty complicated!
