### ISSUE TITLE
If you turn on STATAMIC_OAUTH_ENABLED=true in your .env file, control panel will very often show the message "Too many request to statamic.com" appears.

### ISSUE THREAD

**Issue by PatrikCo** [statamic/cms#3092]
## Bug Description
If you turn on STATAMIC_OAUTH_ENABLED=true in your .env file, control panel will very often show the message "Too many request to statamic.com" appears.

## How to Reproduce
Turn on STATAMIC_OAUTH_ENABLED=true in your .env file

## Extra Detail

<img width="430" alt="image" src="https://user-images.githubusercontent.com/70567345/104226119-95594980-5447-11eb-892f-d32ab73e06df.png">

## Environment

**Statamic version:** 3.0.{?}

**PHP version:** 7.{?}

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Perhaps a silly question, but if you set it to false, does the message go away?
