### ISSUE TITLE
Collection tag flawed. Maybe deeper Antlers/Syntax issues?

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#3097]
## Bug Description
Very weird things happen with my collection tag.

```
{{ collection from="faq" limit="3"
  faq_categories:contains="{faq_categories:0:id}"
  :id:isnt="id"
  sort="random"
}}
```

When I change it to:
```
{{ collection from="faq" limit="3"
  faq_categories:contains="{faq_categories:0:id}"
  :id:isnt="id"
  sort="{{ randomizer ? 'random' : 'order' }}"
}}
```
I get
```
Facade\Ignition\Exceptions\ViewExceptionWithSolution
Modifier [from] not found
The from modifier was not found.
```

For more weirder things: When I change it to (linebreak before 'from='):
```
{{ collection
  from="faq" limit="3"
  faq_categories:contains="{faq_categories:0:id}"
  :id:isnt="id"
  sort="{{ more ? 'random' : 'order' }}"
}}
```

I get my entries, but they are from a completely different collection. Seems something really flawed with Antlers?

## Environment
Statamic 3.0.38 Solo
Laravel 8.21.0
PHP 7.4.10

**Comment by jasonvarga** [comment]
I don't think you can put those `{{ a ? b : c }}` ternaries inside a parameter like that.

**Comment by felixstoessel** [comment]
Okay... Well, `foo="{{ test }}"` works, so ternaries don't? If this is so, then the whole Antlers syntax and its restrictions are very confusing. In retrospect, I should have used Blade, but then I wouldn't have any access to Statamic tags and modifiers. Very hard to do stuff that is a little more than simple template logic.

Also would be great if the restrictions are documented somewhere.

**Comment by jasonvarga** [comment]
I'm not saying you shouldn't be able to do it. I'm just saying what the issue is.

**Comment by felixstoessel** [comment]
Sorry, my comment sounded more angry than it was. Just a little frustrating :)

**Comment by jasonvarga** [comment]
Mine probably did too. ❤️

**Comment by mikemartin** [comment]
@jasonvarga Sorry, the first example throws this error.

```
[previous exception] [object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): strtolower(): Argument #1 ($string) must be of type string, array given at /Users/mike/Sites/new.burlingame/resources/views/partials/community/properties.antlers.html:0)
```

**Comment by mikemartin** [comment]
Thanks @jasonvarga. What I'm wondering here is if it would be faster for the parser to do the match on the raw ID and not look at the augmented data at all. 

Here's the field config:
```
-
        handle: community
        field:
          type: entries
          display: Community
          max_items: 1
          width: 50
          collections:
            - communities
```
