### ISSUE TITLE
Nested collections only work with specific syntax

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#3099]
Using the collection tag with `collection:foo` works when multiple collection tags, but `collection from="foo"` does not.

### Variant 1 works
```
{{ collection:faq_categories scope="faq_category" }}
  <h3>{{ faq_category:title }}</h3>

  {{ collection:faq faq_categories:contains="{faq_category:id}" }}
    <a class="faq-item h4" href="{{ url }}">
      {{ title }}
    </a>
  {{ /collection:faq }}
{{ /collection:faq_categories }}
```

### Variant 2 does not work
```
{{ collection from="faq_categories" scope="faq_category" }}
  <h3>{{ faq_category:title }}</h3>
  
  {{ collection from="faq" faq_categories:contains="{faq_category:id}" }}
    <a class="faq-item h4" href="{{ url }}">
      {{ title }}
    </a>
  {{ /collection }}
{{ /collection }}
```

## Environment
Statamic 3.0.38 Solo
Laravel 8.21.0
PHP 7.4.10

**Comment by jasonvarga** [comment]
You can work around this by placing the inner collection tag in a partial. The parser seems to get confused by the two identical closing tags.

**Comment by jackmcdade** [comment]
For future reference, here's how the regex sees this code. https://regex101.com/r/LPmi4h/1 Syntax variant 2 won't be possible without recursive extractions on tag pairs, which is a pretty big chunk to bite off.

**Comment by felixstoessel** [comment]
I don't have an issue with the other syntax, but then it must be clear for people to decide which syntax fits best. It took me a lot of time to figure out this bug... So I believe it would be best to either fix it or remove the syntax from the docs. What do you think?

**Comment by jackmcdade** [comment]
The other syntax is still useful for when you need to pass a variable as the name of the collection. There’s no need to remove it except for the fact you can’t beat them inside each other. :thinking:

**Comment by jackmcdade** [comment]
Pretty sure we have a fix for this coming in the sorta-near future too.

**Comment by MadeByMike** [comment]
An eventual workaround I found was to split these into different partials. If you do want to continue with the regex path you could simply split every tag pair first into their own strings and then do the regex on each section.

**Comment by jackmcdade** [comment]
Fixed in the new parser.
