### ISSUE TITLE
Empty check condition for array throws error

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#3100]
When trying to filter a collection articles to only show articles that don't have any related_articles attached, I use following from the docs: `{{ collection:articles related_articles:doesnt_exist="true" }}`

But it doesn't work, throws an issue:

```
Facade\Ignition\Exceptions\ViewException
strtolower() expects parameter 1 to be string, array given

# vendor/statamic/cms/src/Query/Builder.php:178:
protected function filterTestEquals($item, $value) {
  return strtolower($item) === strtolower($value);
}
```

## Environment
Statamic 3.0.38 Solo
Laravel 8.21.0
PHP 7.4.10

**Comment by damcclean** [comment]
For others: `null` and `is_empty` also don't work, they throw the same issue. This is where the parameters are documented: https://statamic.dev/conditions#string-conditions

**Comment by jackmcdade** [comment]
Everything seems to be working as intended now. Must have been fixed along the way here. Feel free to reopen with new info if you can still recreate it!

**Comment by sheldonkotyk** [comment]
I'm having this error

This works:
{{ collection:faculty  adjunct:exists="true" as="entry" limit="3" }}

This does not:
{{ collection:faculty  adjunct:doesnt_exist="true" as="entry" limit="3" }}
