### ISSUE TITLE
Relaxing a collection's unique slug requirement

### ISSUE THREAD

**Issue by skylennard** [statamic/cms#3101]
I have identified many valid scenarios in my fairly large website where I will need duplicating slugs for distinct pieces of content that are nested beneath other distinct pieces of content.  Here are some examples:

- newsletter (collection) has multiple issues (ie. the `January 2021` issue), and each issue can have a duplicative page slug, like `events.md` and `updates.md` (both of these could exist uniquely in every distinct issue).
- book (collection) has multiple chapters (ie. `chapter-1`, `chapter-2`, etc), and each chapter has duplicative page slugs from other chapters, like `page-1`, `page-2`, etc.  This might also be abstracted further to include multiple books in a `library` collection, where each book has duplicative chapter slugs of other books, in addition to duplicative page slugs from other chapters.
- pages (collection) has multiple sections (ie. "about-us" and "contact"), and each section has a need for a separate duplicative page slug, like "faqs" or "locations".

Ideally, a slug would *only* need to be unique for it's collection siblings, meaning slugs should be allowed to be repeated in different parent containers.

In the content files, this could be handled by creating subfolders to house nested child content files, rather than relying only on the collection.yaml to organize child/parent relationships of a flat folder full of files at different hierarchies.

in the Statamic CP, verifying the uniqueness of slugs in nested collection items could be handled as validation for the following events:

1. a new piece of child content is created
2. an existing piece of child content is moved to a different parent
3. an existing piece of child content is re-slugged to something that already exists inside of the same parent content.

In each of these scenarios, the slug uniqueness would just need to be verified against it's siblings during the usual "save" action.

**Comment by jasonvarga** [comment]
Thanks for the detailed issue, but this is essentially #714 if you want to comment there instead.
