### ISSUE TITLE
Horiztonal Rule in Bard throws an error

### ISSUE THREAD

**Issue by kupe517** [statamic/cms#3105]
## Bug Description
When adding a horizontal rule to a bard field the app throws the error: 
`ErrorException Undefined property: stdClass::$index` tracing back to the return on line 21 of vendor/statamic/cms/src/Fieldtypes/Bard/SetNode.php:21

## How to Reproduce
Add a horizontal rule to a Bard field

## Environment

**Statamic version:** 3.0.{?}
Statamic 3.0.38 Pro
Laravel 8.21.0

**PHP version:** 7.{?}
PHP 7.4.12

**Install method (choose one):**
- Existing Laravel app

**Comment by jasonvarga** [comment]
Can you please show the output of `composer info | grep prosemirror`

**Comment by kupe517** [comment]
ueberdosis/html-to-prosemirror     1.4.0   Takes HTML and outputs ProseMi...
ueberdosis/prosemirror-to-html     2.3.0   Takes HTML and outputs ProseMi...

**Comment by askonomm** [comment]
Can confirm, I have the same exact issue with a vanilla install of Statamic.

**Comment by sjclark** [comment]
Can confirm same issue;
```
ueberdosis/html-to-prosemirror     1.4.0   Takes HTML and outputs ProseMirror compatible JSON.
ueberdosis/prosemirror-to-html     2.3.0   Takes HTML and outputs ProseMirror compatible JSON.
```
```
ErrorException
Undefined property: stdClass::$index
```
```
PHP version 7.4.12
Laravel version 8.21.0
```
I'm nested a couple of levels deep here within fieldtypes - Bard within a replicator within replicator.

Happy to share zipped site if needed?

**Comment by jasonvarga** [comment]
This is another package's issue. I've opened a PR there: https://github.com/ueberdosis/prosemirror-to-html/pull/46

Once that's merged, you should be able to run `composer update ueberdosis/prosemirror-to-html` and get the fix.

**Comment by sjclark** [comment]
Can confirm with updated dependencies and/or `3.0.39` this now works! Thanks @jasonvarga 👍
```
ueberdosis/html-to-prosemirror     1.5.0   Takes HTML and outputs ProseMirror compatible JSON.
ueberdosis/prosemirror-to-html     2.4.0   Takes HTML and outputs ProseMirror compatible JSON.
```
