### ISSUE TITLE
Bard (Antler): formatting inside link breaks up the link

### ISSUE THREAD

**Issue by notnek** [statamic/cms#3108]
## Bug Description
While bf06d80 fixed #2109 with regard to the CP output, the frontend output of the link still breaks up the link per formatting tag. This is the same issue, but for the antler output of the Bard field.

## How to Reproduce
1. Select some text in Bard
2. Make it a link
3. Select a substring of the link text and make it bold
4. View live preview of the page and inspect the link

## Extra Detail
![bard-link-frontend](https://user-images.githubusercontent.com/114763/104740077-7f80a880-5715-11eb-8ee8-b3661b661b05.png)
![bard-link-frontend-source](https://user-images.githubusercontent.com/114763/104740079-80b1d580-5715-11eb-8de8-4db101a4bbb8.png)

## Environment

Statamic 3.0.38 Pro
Laravel 7.30.2
PHP 7.4.14

Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
I've done a bit of digging and it looks like this is a upstream issue with the way TipTap/ProseMirror handles the nodes. I'll look at opening an issue there.
