### ISSUE TITLE
Can't create entry if collection isn't in default site

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#3110]
## Bug Description

If a collection does not belong to the default site, you can't create an entry, you get a blank screen

## How to Reproduce

1. Have 2 `sites` in your multi-site, say `default` and `two`.
2. Create a collection and have it in only `two`.
3. Attempt to create an entry in that collection, you'll see the url is `http://yoursite.test/cp/collections/artists/entries/create/default` and a blank screen is shown.

## Extra Detail

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/6069653/104759764-3f212a80-5715-11eb-9d29-f15d41d60001.png">

## Environment

Statamic 3.0.38 Pro
Laravel 8.22.1
PHP 7.4.14
austenc/statamic-instagram-feed 2.2.0
edalzell/variable 1.0.3
statamic/eloquent-driver dev-fixed_closures

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
I can't seem to reproduce this issue unfortunately. I created a new collection that is only in my secondary site and I went to create an entry and the blueprint form loaded up just fine. No problems.

Don't suppose if you comment out some of the fields in your blueprint it starts working again?

**Comment by edalzell** [comment]
Haven't seen this in ages, closing
