### ISSUE TITLE
If Revisions are enabled globally but disabled for the Collection, a Revision is still created when localizing an Entry

### ISSUE THREAD

**Issue by nfragkos** [statamic/cms#3116]
https://github.com/statamic/cms/blob/937aceba6a81589624585775024de6bde85dc905/src/Http/Controllers/CP/Collections/LocalizeEntryController.php#L19

If revisions are enabled globally but disabled for the collection, a revision is created when localizing an entry.  The referenced line of code above doesn't check if revisions are enabled.

**Comment by damcclean** [comment]
Hey! 

Unfortunately, I'm going to have to close this issue as it doesn't follow the [issue template](https://github.com/statamic/cms/issues/new?assignees=&labels=&template=bug_report.md&title=) for bug reports. Using the template helps to keep all issues consistent and helps to make sure all issues provide enough information for maintainers to recreate your issue.

Would you mind creating a fresh issue with the template?
