### ISSUE TITLE
If Revisions are enabled globally but disabled for the Collection, a Revision is still created when localizing an Entry

### ISSUE THREAD

**Issue by nfragkos** [statamic/cms#3117]
## Bug Description
If revisions are enabled globally but disabled for the collection, a revision is created when localizing an entry. The referenced line of code above doesn't check if revisions are enabled.
https://github.com/statamic/cms/blob/937aceba6a81589624585775024de6bde85dc905/src/Http/Controllers/CP/Collections/LocalizeEntryController.php#L19

## How to Reproduce
1. Enable revisions globally via .env STATAMIC_REVISIONS_ENABLED=true
2. In content/collections/pages.yaml set revisions: false
3. Add a second site in config/statamic/sites.php
4. Edit an entry and click on another site to localize it.
5. A revision is created even though revisions are disable on the collection.

## Environment
Statamic 3.0.38 Pro
Laravel 8.21.0
PHP 8.0.0
edalzell/blade-directives 2.1.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Thanks for re-creating the issue 🙂
