### ISSUE TITLE
Glide Presets & Format Not Working

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#3122]
## Bug Description
Glide presets are not respecting the 'format' parameter the same way using the glide tag directly does, it always makes `jpg` images not `webp` images ...

## How to Reproduce
`{{ glide:image format='webp' }}` works, it produces a webp image

However this does not:
`{{ glide:image preset='homepage_webp' }}`
where my preset is ...
```php
'homepage_webp' => [
    'w' => 940,
    'h' => 368,
    'fit' => 'crop',
    'format' => 'webp',
],
```

## Environment

Statamic 3.0.36 Solo
Laravel 8.20.1
PHP 7.4.13
statamic/ssg 0.2.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by riasvdv** [comment]
Try using `fm` instead of `format` as the key, that works in PHP code, so it might with the presets

**Comment by jasonvarga** [comment]
Yeah, in the presets you have to use the actual glide parameters, not the aliases we provide to the tag.

**Comment by jcohlmeyer** [comment]
Is this document somewhere? I could not find any documentation on this.

**Comment by damcclean** [comment]
It's probably not the easiest documentation to find, but here's the [format docs](https://glide.thephpleague.com/1.0/api/encode/#format-fm) and here's the [presets docs](https://glide.thephpleague.com/1.0/config/defaults-and-presets/#presets).

**Comment by sjclark** [comment]
> It's probably not the easiest documentation to find, but here's the [format docs](https://glide.thephpleague.com/1.0/api/encode/#format-fm) and here's the [presets docs](https://glide.thephpleague.com/1.0/config/defaults-and-presets/#presets).

Still think it seems fairly unusual that presets are not documented or referenced anywhere within Statamic - or certainly not somewhere that the Statamic docs search or google search yielded for me. Every time I forget how it works I end up back at robs 2020 documentation; https://studio1902.nl/blog/responsive-images-with-statamic-tailwind-and-glide/

I guess everyone just uses the Spatie addon these days.

**Comment by jasonvarga** [comment]
Presets are documented now. Thanks for the nudge. https://statamic.dev/tags/glide#presets
