### ISSUE TITLE
Question / issue regarding localising form e-mails

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3128]
## Bug Description
I work in English (field labels, code etc), also the CP for this site has to be English. My site is not localised and the locale is set to `nl` (Dutch). It all works fine. I use this pattern to translate form labels on the frontend:

```
{{ trans key="{display}" }}
```

For that to work I maintain a `nl.json` file like this:

```
{
    "City": "Woonplaats", 
    etc
}
```

In my mail template I use the same pattern but I have to sent the locale with it. Like this:

```
{{ trans key="{display}" locale="{locale}" }}
```

For the default locale however Statamic uses `default`. So in order to translate the e-mails I have to maintain another json file called `default.json` with the same strings and translations as `nl.json`. 

I wonder if it's intended that Statamic uses `default` instead of the actual locale? Or maybe I should do it differently. 

## Environment
Statamic 3.0.38 Pro
Laravel 8.21.0
PHP 7.4.13
edalzell/forma 0.8.5
nineteensquared/instagram 1.0.4
silentz/mailchimp 2.5.4

**Install method (choose one):**
- Starter kit Peak

**Comment by jasonvarga** [comment]
{{ locale }} how you're using it is the handle of the current site (defined in config/statamic/sites.php)

Try using {{ site:locale }} instead.

**Comment by robdekort** [comment]
Ha! Yes, of course. That's it. Thanks a bunch Jason!
