### ISSUE TITLE
Localize-settings on fieldsets not working when linked in a replicator

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#3131]
## Bug Description
When adding localization to fields within a fieldset and this fieldset is then included in a replicator then the localization setting does not have any effect. If adding localization to the replicator then localization is enabled on all fields within the fieldset – even though some of them are disabled.

## How to Reproduce
* Create a multi-site with two languages
* Create a fieldset containing two text fields. Add localized to one of them.
* Create a replicator in the blueprint and link the fieldset
(At this point - if you create an entry both fields are read only)
* Enable localize on the replicator
(Now both fields are translatable)

## Environment
Statamic 3.0.38 Pro
Laravel 8.21.0
PHP 7.3.12
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Only top level fields can be localized.

statamic/ideas#429

**Comment by espenlg** [comment]
> Only top level fields can be localized, e.g. the entire replicator field.
> 
> [statamic/ideas#429](https://github.com/statamic/ideas/issues/429)

I'm not sure how this relates to the link you provided about globals?

And I have to admit it feels a bit brutal to close issue. Could this at least be considered as a future improvement? Having a website in two or more languages is not rare in my part of the world and the lack of being able to define fields like assets, settings like padding/margin/color(s), email address, phonenumbers, names and such as read only seems strange.

**Comment by sjclark** [comment]
@jasonvarga think you may have linked to the wrong issue/idea above there 😄 
@espenlg he may have been meaning this? https://github.com/statamic/ideas/issues/226

**Comment by espenlg** [comment]
> @espenlg he may have been meaning this? [statamic/ideas#226](https://github.com/statamic/ideas/issues/226)

Now that makes sense. Thank you!

**Comment by jasonvarga** [comment]
I think I meant to link to statamic/ideas#439 but 226 is good too.
