### ISSUE TITLE
Asset Browser only allows to grab 30 files at once and not all of the folder.

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#3142]
## Bug Description
If you want to grab more than 30 files at once, you have to grab them one by one.

## How to Reproduce
Try to add for example 60 files at once.

## Environment
Statamic 3.0.38 Pro
Laravel 8.19.0
PHP 7.4.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by snoopy21** [comment]
This behaviour is still present in Statamic 3.1.18.

**Comment by duncanmcclean** [comment]
If you’re still seeing this issue, please leave a 👍 reaction on the initial post.

**Comment by jackmcdade** [comment]
What do you mean by "grab" exactly

**Comment by j3ll3yfi5h** [comment]
https://user-images.githubusercontent.com/6337411/124560636-54158580-de3d-11eb-9c9a-bc769ae82447.mov

**Comment by jackmcdade** [comment]
Got it. Will be addressed in 3.2 from a few different angles.
