### ISSUE TITLE
Multiple collection with pagination on one site

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#3147]
## Bug Description
I have multiple collections with pagination on one site. There are 2 problems with it. When you click another site, the page is reloading with no output anymore. None collection is shown.
Next problem is, they have all the param `page`. That's the reason, why all collection moving to the next page, instead of just the clicked one. The param should be changeable to prevent this.

## How to Reproduce
Add multiple collections with pagination to a template.

## Extra Detail
```
                {{ collection:col1 limit="2" paginate="true" as="items" }}
                {{ partial:pagination }}
                <ul>
                    {{ items }}
                    <li>{{ title }}</li>
                    {{ /items }}
                </ul>
                {{ /collection:col1 }}

                {{ collection:col2 limit="2" paginate="true" as="items" }}
                {{ partial:partials/pagination }}
                <ul>
                    {{ items }}
                    <li>{{ title }}</li>
                    {{ /items }}
                </ul>
                {{ /collection:col2 }}

                {{ collection:col3 limit="2" paginate="true" as="items" }}
                {{ partial:pagination }}
                <ul>
                    {{ items }}
                    <li>{{ title }}</li>
                    {{ /items }}
                </ul>
                {{ /collection:col3 }}
```

## Environment

**Statamic version:** 3.0.40

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Sounds similar to statamic/ideas#445 which I just moved from this repo.
Yours however sounds like an actual issue rather than a feature request. 👍

**Comment by jasonvarga** [comment]
Done in https://github.com/statamic/cms/pull/6593
