### ISSUE TITLE
Saved entries in pages collection are moved to last position

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#3148]
## Bug Description
When you edit an entry in the pages collection and save it, the entry gets moved to the last position in the tree. You have to reorder the entries after that. 

## How to Reproduce
1. Open entry
2. Save entry
3. Go back to the pages tree
4. Saved entry is on last position 

## Environment

**Statamic version:** 3.0.40

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Where would you expect a new page to go in the tree? Personally, I'd expect it to be last in the tree.

**Comment by wm-simon** [comment]
I've never said, it's a new page ;-) I just edit an existing entry.

**Comment by wm-simon** [comment]
https://screencast-o-matic.com/watch/crVTIa9dAW

**Comment by robdekort** [comment]
Not  a discussion. Bug. Just encountered this. Very weird. Save an existing entry and it moves to the last position.

**Comment by jasonvarga** [comment]
Definitely a bug. On it!

**Comment by robdekort** [comment]
You beat me to labeling it

**Comment by robdekort** [comment]
Is this scheduled to release soon? My customers are confused by this.
