### ISSUE TITLE
Updating an entry doesn't update its translation in the search index

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#3158]
## Bug Description

When you have a field that isn't localizable on your default site, and you change that field, the entry in the other site doesn't get updated in the search index.

## How to Reproduce

- Have 2 sites (default, second)
- Set up a search index
- Create a field that isn't localizable
- Save the field

## Environment

Statamic 3.0.40 Pro
Laravel 7.30.4
PHP 8.0.0

**Comment by jasonvarga** [comment]
Nice find
