### ISSUE TITLE
@svg causes conflict with blade-ui-kit / blade-icons in CP 

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#3162]
I am having one of those intermittent issues that are difficult to replicate, sorry.

If I install https://github.com/blade-ui-kit/blade-icons and https://github.com/statamic/cms occasionally I run into this error in the Statamic CP:

![image](https://user-images.githubusercontent.com/3776888/106020084-47854800-60bb-11eb-8a70-9766a5d675dc.png)

"Svg by name "arrow-right" from set "default" not found. "

I assume it's because the `@svg` directive is being registered twice, sometimes it is registered first by Statamic and in other cases it is registered by Blade UI Kit.

Blade UI Kit:
https://github.com/blade-ui-kit/blade-icons/blob/a7b5b2a8093d7355e279b73b0f5c6e72ab70fe1f/src/BladeIconsServiceProvider.php#L55

Statamic: https://github.com/statamic/cms/blob/1f11c9c89338de0a980ff476875c7f0a9bf697a8/src/Http/Middleware/CP/ControlPanel.php

It seems quite difficult to replicate, so I was wondering if I could somehow change the directive handle in either package?

Related: #956

**Comment by jasonvarga** [comment]
Thanks for the details but not sure why you discarded the issue template.

What version of Statamic are you using?

**Comment by johncarter-** [comment]
## Bug Description
As per above.

## How to Reproduce
Intermittent / cannot easily reproduce.

## Extra Detail
None.

## Environment
Statamic 3.0.40 Pro
Laravel 8.24.0
PHP 8.0.0
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic` ( Although cannot remember precisely)

**Comment by johncarter-** [comment]
It seems to go away if I `composer install` again.

**Comment by jackmcdade** [comment]
🎉

**Comment by johncarter-** [comment]
I'm getting this again - again seemingly random occurrence.

Tried these steps:
- `php artisan cache:clear`
- `php artisan config:clear`
- `rm -rf vendor/ && rm composer.lock`
- `composer install`

Would you guys accept a pull request to rename the Statamic SVG CP Blade directive from `@svg` to `@statamic_svg`, or similar?

**Comment by jackmcdade** [comment]
I would merge one for “cp_svg()” 👍🏼

**Comment by johncarter-** [comment]
Consider it done.

**Comment by jasonvarga** [comment]
Will be in the next 3.1 alpha release.
