### ISSUE TITLE
When navigating away from a listing while the ajax request is loading, you get the toast

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#3166]
## Bug Description

I saw this in an action that returns a redirect (using the `redirect` method) that opened an app. See a "Something went wrong" error before the redirect happens. 

## How to Reproduce

1. Make an action that does a redirect to an app, like a `mailto` link.
2. run action

## Environment

Statamic 3.0.40 Pro
Laravel 8.23.1
PHP 7.4.14
aryehraber/statamic-captcha 1.2.0
serieseight/statamic-uuid 2.0.0
statamic/seo-pro 2.1.0
transformstudios/drafts 2.1.1
transformstudios/events dev-main
transformstudios/front 1.0.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
When the ajax request is aborted (triggered by the redirect, or even just navigating away), the "error" is caught and you get the toast:

https://github.com/statamic/cms/blob/fc4d56dfd426e0d4be42a243743b23450862cc08/resources/js/components/Listing.vue#L133-L138

We need to be able to check if the request is aborted.

Here's me redirecting to google from the action:

![image](https://user-images.githubusercontent.com/105211/106042701-6845a180-60ab-11eb-9fdd-baeee15ce5f6.png)

Firefox doesn't give a response code, just a 🚷
