### ISSUE TITLE
Collection delete button is missing

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#3174]
## Bug Description
It's not possible to delete collection entries, the delete Button is missing.

## How to Reproduce
Selected entry in the overview, Button is not shown anymore.

## Extra Detail

![image](https://user-images.githubusercontent.com/3351449/106268837-f183e200-622b-11eb-8336-4aaa6ea15b4e.png)

## Environment

**Statamic version:** 3.0.40

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
If you don't have permission to delete, the button won't show up.

Does your user have permission?

**Comment by wm-simon** [comment]
Yes, `super` is `true`.

**Comment by damcclean** [comment]
Hmm I don't seem to be able to reproduce with a super user. Does your user account have any roles specified (even though they're a super user)? 

Also, would you mind sharing your collection's config, in case there's anything in there that could be causing the issue? (it's the YAML file located in `content/collections`)

**Comment by jonassiewertsen** [comment]
I can confirm this bug and will create a PR in a few minutes. 

It is related to the following line and will only appear in a none multisite-context. 

```php
public function visibleTo($item)
    {
        if ($item instanceof Entry && $item->collection()->sites()->count() > 1) {
            return false;
        }

        return true;
    }
```

https://github.com/statamic/cms/blob/3.0/src/Actions/Delete.php#L19-L21

The statement is not correct if we do compare to the multisite action to delete entries:
https://github.com/statamic/cms/blob/3.0/src/Actions/DeleteMultisiteEntry.php#L12-L13

Solution:
```php
       if (! $item instanceof Entry) {
            return false;
        }
        
        if ($item->collection()->sites()->count() > 1) {
            return false
        }

        return true;
```

**Comment by jasonvarga** [comment]
How did you reproduce the issue? The conditionals are correct.

**Comment by jonassiewertsen** [comment]
Something is off, for sure if loading Actions in an addon context. 

I'll get back to this issue later with better information 😎

**Comment by jonassiewertsen** [comment]
Hmmmm ... I can't reproduce the issue anymore somehow.

**Comment by wm-simon** [comment]
I've made some more test. The result was, after uninstalling butik (https://statamic.com/addons/jonassiewertsen/statamic-butik) the delete button is back.  So i think this issue could be closed and @jonassiewertsen should take a look, if he can reproduce it.

**Comment by wm-simon** [comment]
https://github.com/jonassiewertsen/statamic-butik/issues/197
