### ISSUE TITLE
multisite command throws error

### ISSUE THREAD

**Issue by freshface** [statamic/cms#3175]
## Bug Description

When i run ```php artisan statamic:multisite``` i always get:

```
 Error 

  Call to a member function hasStructure() on null

  at vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:130
    126|     }
    127| 
    128|     protected function removeEntryFromStructure($collection, $id)
    129|     {
  > 130|         if (! $collection->hasStructure()) {
    131|             return;
    132|         }
    133| 
    134|         $contents = $collection->structureContents();

      +31 vendor frames 
  32  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

## How to Reproduce

run ```php artisan statamic:multisite```

## Environment

Statamic 3.0.23 Pro
Laravel 7.29.3
PHP 7.3.20
No addons installed

**Install method (choose one):**

- Fresh install with added collections and content.

**Comment by freshface** [comment]
Running ```php artisan cache:clear``` before running this fixes my issues.
I created a PR to reflect the docs https://github.com/statamic/docs/pull/373

**Comment by damcclean** [comment]
This issue should be resolved in a later release. The `multisite` command has been improved since v3.0.23. If you're still having the same issue after updating, let me know and I can re-open this issue.

**Comment by stuartcusackie** [comment]
Just ran into this same error on 3.0.45. 

php artisan cache:clear fixes it.

**Comment by duncanmcclean** [comment]
If you're still having an issue here, please create a new issue. Thanks!
