### ISSUE TITLE
Creating a new Statamic project Via Statamic CLI Installer Fails with PHP 8

### ISSUE THREAD

**Issue by LloydThinks** [statamic/cms#3177]
## Bug Description

`composer global require statamic/cli` fails due to an issue with PHP versions. I'm not sure how to proceed. Does Statamic only work with certain versions of PHP? If so, I don't see this requirement listed in the https://statamic.dev/installation page.

## How to Reproduce

Just run `composer global require statamic/cli` with PHP version 8.0.1 and it throws the following error.

## Extra Detail

```bash
 % composer global require statamic/cli
Changed current directory to /Users/Hermes/.composer
Using version ^2.0 for statamic/cli
./composer.json has been updated
Running composer update statamic/cli
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/container v7.25.0 requires php ^7.2.5 -> your php version (8.0.1) does not satisfy that requirement.
    - laravel/valet v2.11.0 requires illuminate/container ~5.1 | ^6.0 | ^7.0 -> satisfiable by illuminate/container[v7.25.0].
    - laravel/valet is locked to version v2.11.0 and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.

```

## Environment

**Statamic version:** N/A

**PHP version:** 8.0.1

**Comment by damcclean** [comment]
Statamic itself supports from PHP 7.3 up I believe. The issue here looks to be related to your global composer dependencies and not really a Statamic issue.

You should be able to update your global composer dependencies inside your `~/.composer/composer.json` file and update them to PHP 8 ready versions.

**Comment by LloydThinks** [comment]
Hmmm I see what you mean @damcclean . I went through and updated them. I am now able to run without issue.

Cheers,
Lloyd

**Comment by damcclean** [comment]
Awesome!
