### ISSUE TITLE
Form field - content API

### ISSUE THREAD

**Issue by pitcher-maarten** [statamic/cms#3182]
## Bug Description
The content API is not providing any data from the **form field** which results in an empty Object key.
As Duncan (damcclean#1270 @Discord) told me there should be a shallow augmentation issue for the form field.

`"form": {}`

## How to Reproduce

1. Add form field to blueprint.
2. Connect field with existing form.
3. GET page response with postman.

## Extra Detail
If the API is able to response with a form ID or other ref we can built our own controller to fetch the fields and create form submissions from a headless installation like Nuxt.js

## Environment
**Statamic version:** 3.0.40
**PHP version:** 7.4.13
Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Can confirm: `form` my form field is an empty object in the JSON response. 
![image](https://user-images.githubusercontent.com/19637309/106655194-f5e42e00-6590-11eb-8f0a-adc149966d3a.png)
