### ISSUE TITLE
Collection filter by date bugs?

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#3184]
## Bug Description
I try to explain it.
I have an events collection and want to show all events in future including today.
`is_future` did not show the same day. 
So I tried `is_after`, like suggested here:
https://github.com/statamic/cms/issues/2688 

Width `date:is_after="{today format='Y-m-d'}"` the event on the same is not shown. 
So I tried `date:is_after="{today modify_date='-1 day' format='Y-m-d'}"`, but this shows all events beginning 2 days before.

## Extra Detail

`{{ collection:termine limit="3" as="posts" sort="date:asc" date:is_after="{today modify_date='-1 day' format='Y-m-d'}" }}`

## Environment

**Statamic version:** 3.0.38

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by felixstoessel** [comment]
I can confirm this bug.

A simple `{{ collection:projects scope="project" show_future="true" }}` does not work. `show_future` get's ignored. My blueprint has the default `date` field.

**Comment by wm-simon** [comment]
@felixstoessel Hey, did you find a solution for it? This issue causes bigger problems on multiple sites.

**Comment by felixstoessel** [comment]
No, did not find a solution.

**Comment by jackmcdade** [comment]
There's no need to format the date when passing it as a prop. Also, I think the quotes inside quotes are confusing the parser, which isn't _exactly_ designed to do this kind of thing. But...try this. It seems to work for me.

```
date:is_after="{today | modify_date:-1 day}"
```

**Comment by wm-simon** [comment]
Thanks Jack, it worked without the format param. When I just use this `date:is_after="{today}"`, the events at the same day (today) are not shown anymore. I think the events from `today` should be shown as well and get hidden on the next day. Is this a bug or I am wrong here?

**Comment by jackmcdade** [comment]
If the date is after today, how would it include today? If you want to include today, make it after yesterday.

**Comment by j3ll3yfi5h** [comment]
https://github.com/statamic/ideas/issues/634
