### ISSUE TITLE
Entry::make() does not trigger EntrySaved event

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#3189]
## Bug Description
When using an addon like https://github.com/riasvdv/statamic-data-import that internally is using `Entry::make()` to create entries on import, the EntrySaved event does not trigger.

## Environment
Statamic 3.0.40 Solo
Laravel 8.21.0
PHP 7.4.11

**Comment by damcclean** [comment]
Can you share your code?

**Comment by jasonvarga** [comment]
Please open an issue on the addon's repository.

They can investigate their implementation and then they can open an issue here if needed.

**Comment by felixstoessel** [comment]
I am pretty sure this is Statamic related. I wrote a simple Resave action like this:

```
<?php

namespace App\Actions;

use Statamic\Actions\Action;

class Resave extends Action {
  public function run($items, $values) {
    $items->each(function ($item) {
      $item->save();
    });
  }
}
```

The resave works but the event does not get triggered. So I assume this is the same issue and not addon related.

**Comment by damcclean** [comment]
How are you checking that the event is fired?

**Comment by riasvdv** [comment]
Replying here, the addon just uses $entry->save(), which should trigger the event https://github.com/riasvdv/statamic-data-import/blob/master/src/Jobs/ImportJob.php#L101

**Comment by felixstoessel** [comment]
Now I got it to work, but previously it didn't trigger. But no idea why this works now. It didn't change anything. I will close this for now.
