### ISSUE TITLE
Error when converting to multisite and using two-character handle

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#3192]
## Bug Description
When trying to convert a site to multi-site by using `php please multisite` and then using like a short locale for handle - example "fr" then it does not work. If I reset everything - pull from git and try again with a longer handle it works fine.

## How to Reproduce
Described above

## Extra Detail
![Screenshot 2021-02-03 at 10 44 04](https://user-images.githubusercontent.com/1135679/106739787-d218fa80-6619-11eb-81e0-336a9424c1a0.png)

## Environment

Statamic 3.0.38 Pro
Laravel 8.22.1
PHP 7.3.12
No addons installed

**Statamic version:** 3.0.38

**PHP version:** 7.3.12

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment]
Could you try updating to v3.0.39 or higher? There were some updates to the multi-site command in [v3.0.39](https://github.com/statamic/cms/releases/tag/v3.0.39).

Let me know if that helps.

**Comment by espenlg** [comment]
> Could you try updating to v3.0.39 or higher? There were some updates to the multi-site command in [v3.0.39](https://github.com/statamic/cms/releases/tag/v3.0.39).
> 
> Let me know if that helps.

You may be right. I did solve it this time by using a longer handler, but the next time I need to convert to a multi-site I'm most likely on 3.0.39+ and maybe it is no longer a problem.

**Comment by damcclean** [comment]
Okay! I'll close this issue now as it should be fixed in v3.0.39. If you run into it again on another site, please comment on here and we can re-open or open a new issue.
