### ISSUE TITLE
Fields in assets not translatable

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#3203]
## Bug Description
I've added some text fields to the assets container that I use. All these fields are marked as translatable, but this doesn't seem to be working. The field value always changes no matter which language is active.

## Extra Detail

![image](https://user-images.githubusercontent.com/11161180/107029231-feb24b00-67ae-11eb-92ae-b72d9cfd973c.png)

![image](https://user-images.githubusercontent.com/11161180/107029272-0c67d080-67af-11eb-9893-3e4e19c797d5.png)

For example: I changed copyright to 'Test 2 en' on the english site. Switched back to dutch and the value changed too.

## Environment

**Statamic version:** 3.0.40

**PHP version:** 7.4.12

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Assets are not localizable at the moment.
https://github.com/statamic/ideas/issues/223
