### ISSUE TITLE
Full Cache Query String Crashes

### ISSUE THREAD

**Issue by ericlbarnes** [statamic/cms#3210]
## Bug Description

With Full Caching, by default, it tries to use the query string when saving the static file. For most things this is fine, but if you have a long query string it can throw a 500 error. 

## How to Reproduce

Enable full caching. Load a URL, and append a long query string like GA tracking code: 

```
https://yoursite.com?utm_campaign=Laravel%20811%20Livewire%20Charts%20RandoPHP%20and%20more%20-%20330&utm_content=Laravel%20811%20Livewire%20Charts%20RandoPHP%20and%20more%20-%20330%20CID_3b180aa1535178ab3ccb597b4a92741c&utm_medium=email&utm_source=email%20marketing&utm_term=PHP%20Progress%20Library%20to%20Track%20User%20Progress
```

This throws an error on the server: `Failed to open stream: File name too long` so it can't write the file. 

## Extra Detail

I found a hidden setting that seems to fix it, but I'm guessing this will mess up any paginated collections. 

```
'ignore_query_strings' => true,
```

**Comment by jasonvarga** [comment]
File name too long.

Of course that's a thing. 🙄  Great! 😆

**Comment by edalzell** [comment]
maybe it could be hashed?

**Comment by jasonvarga** [comment]
If you can work out a way for nginx (and htaccess/web.config) to make hashes in the config, then that would be a good solution. I doubt it's possible though.

**Comment by arthurperton** [comment]
Bummer 😆

If you can't create hashes in the config files... Maybe you could use a lookup table using the [map directive](http://nginx.org/en/docs/http/ngx_http_map_module.html#map) like this:
```
map $uri $hash {
    default "";
    /about 77102f70526b1c2db0eced54632dc618;    
    /contact 90609cfd31a32bdbd3d81843c57d356b;
    /?utm_campaign=Laravel%20811%20Livewire%20Charts%20RandoPHP%20and%20more%20-%20330&utm_content=Laravel%20811%20Livewire%20Charts%20RandoPHP%20and%20more%20-%20330%20CID_3b180aa1535178ab3ccb597b4a92741c&utm_medium=email&utm_source=email%20marketing&utm_term=PHP%20Progress%20Library%20to%20Track%20User%20Progress 35b87281be99f098ca4f562434124fbb;
}
```

You could put this list in a separate file that you include in your main nginx config file. 

The lookup table would have to be updated from the Statamic caching PHP module though, which adds complexity.

**Comment by bacheson** [comment]
this basically throws a 500 on any click from any advertising platform...talk about a critical bug

**Comment by ericlbarnes** [comment]
Here is a crud workaround Jason helped me with for this that might help. 

1. Set ignore_query_strings to true. So they aren't included in the cache files. This will cause pagination to break because they use query strings. 
2. To address that, create a new file to change the way files are cached: (app/Caching/CustomFileCacher.php)
 
```php
<?php

namespace App\Caching;

use Illuminate\Http\Request;
use Statamic\Facades\File;
use Statamic\StaticCaching\Cachers\FileCacher as Cacher;

class CustomFileCacher extends Cacher
{
    public function getFilePath($url)
    {
        $parts = parse_url($url);
        $query = parse_url($url, PHP_URL_QUERY);
        parse_str($query, $queryArr);
        return sprintf('%s%s_page=%s.html',
            $this->getCachePath(),
            $parts['path'],
            $queryArr['page'] ?? ''
        );
    }

    /**
     * Exactly the same as the parent method, but without the log.
     *
     * Workaround for https://github.com/statamic/cms/issues/3209
     */
    public function getCachedPage(Request $request)
    {
        $url = $this->getUrl($request);

        return File::get($this->getFilePath($url));
    }
}
```

Finally, change your Nginx rule to: 

```
location / {
    try_files /static${uri}_page=${arg_page}.html $uri /index.php?$args;
}
```

**Comment by jasonvarga** [comment]
Thank you Eric

**Comment by jasonvarga** [comment]
In the next release, the error will be silenced so the page at least loads. But it doesn't get cached, which is still something we would need a solution for.

I've noticed static caching implementations on other platforms have the same problem. Here's one for Drupal. https://www.drupal.org/node/2050849

**Comment by jeremydouglas** [comment]
@jasonvarga would it work to hash the URL?
