### ISSUE TITLE
Slug error when saving new created Entry again

### ISSUE THREAD

**Issue by crackAT** [statamic/cms#3215]
## Bug Description
Slug error: This value has already been taken. after saving a new entry draft twice. 

## How to Reproduce
Create a new Entry. 
Save draft with "Continue editing". 
Save draft again. 

## Extra Detail
redirecting to new editing url after saving will fix this issue

## Environment

Statamic 3.0.42 Pro
Laravel 8.26.1
PHP 7.3.11
4rn0/statamic-v3-image-optimizer 1.0.5
aryehraber/statamic-logbook 2.0.1
phpsa/statamic-analytics 1.0.0
statamic/eloquent-driver 0.1.1

**Comment by duncanmcclean** [comment]
I seem to be unable to reproduce this bug, maybe I'm doing something wrong? [Here's a video of me attempting to reproduce](https://drive.google.com/file/d/1dJE1QogRQj43xPvstIvh5JdQH89-sp-g/view?usp=sharing)

**Comment by crackAT** [comment]
Hi, thats exactly what i did. Maybe thats an eloquent-driver issue?

**Comment by duncanmcclean** [comment]
> Hi, thats exactly what i did. Maybe thats an eloquent-driver issue?

You might be right 🤔

**Comment by jasonvarga** [comment]
Please open an issue on the statamic/eloquent-driver repo if this is still an issue for you.
