### ISSUE TITLE
New form button is missing

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#3222]
## Bug Description
When on `/cp/forms` and you have at least 1 form, the button disappears to create a new form from the CP.

## Environment
Statamic 3.0.42 Solo
Laravel 8.27.0
PHP 7.4.11

**Comment by duncanmcclean** [comment]
When you're using Statamic Solo, you are limited to a single form. To enable multiple forms, you'll need to upgrade to Statamic Pro. [See pricing](https://statamic.com/pricing).
