### ISSUE TITLE
Lowercase Taxonomy created from Taxonomy Terms Dropdown is not saved correctly

### ISSUE THREAD

**Issue by Buffalom** [statamic/cms#3228]
## Bug Description
When a new taxonomy term containing only lowercase characters is created inside an entry using the taxonomy terms dropdown the connection to the term is saved on the entry but the term itself (the yaml file) is not created in the taxonomy.

## How to Reproduce
Just a simple taxonomy that's used on an entry using a taxonomy terms fieldtype in "select dropdown" mode.
In this dropdown enter an all lowercase term that does not yet exist in the taxonomy.

## Environment

Statamic 3.0.42 Solo
Laravel 8.27.0
PHP 7.4.14
No addons installed

**Install method:**
Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
The term files only need to exist if they are defining something extra, like custom fields or title.

Since your term in the entry is just a slug, a file doesn't need to exist.

If this is causing an actual *problem* for you, let us know!

**Comment by arthurperton** [comment]
I believe this causes actual problems. As a user I expect an actual term to be created, whether it starts with an uppercase character or not. 

Currently the lowercase ones are left out in several places, where the others are shown. They are missing on the Taxonomy's page in the control panel. They also won't show up when you use the Taxonomy tag.

All three of these terms are created in the dropdown:

<img width="770" alt="Screenshot 2021-03-09 at 17 04 08" src="https://user-images.githubusercontent.com/4067531/110502651-ad71e000-80fb-11eb-8607-b8dca26f9bcd.png">

But only the ones that start with an uppercase character show up:

<img width="839" alt="Screenshot 2021-03-09 at 17 03 56" src="https://user-images.githubusercontent.com/4067531/110502672-b4005780-80fb-11eb-83d2-12512d382343.png">

```html
{{ taxonomy:fruit }}
    <li><a href="{{ url }}">{{ title }}</a></li>
{{ /taxonomy:fruit }}
```

<img width="157" alt="Screenshot 2021-03-09 at 17 03 43" src="https://user-images.githubusercontent.com/4067531/110502752-c5496400-80fb-11eb-86e3-4fcfa24e83ba.png">

**Comment by jasonvarga** [comment]
If they aren't showing in the listing then yes, it's an issue. Although it should have been showing up even without a dedicated file.

**Comment by arthurperton** [comment]
How could they show up? Where would they exist otherwise, if not as a file in ```content/taxonomies/{taxonomy}``` ?

**Comment by edalzell** [comment]
They exist in the stache, added when added to the entry. No file needed. I.e. they are inferred from their existence in the entry.

**Comment by arthurperton** [comment]
Thanks yeah in the stache. Under ```Statamic\Stache\Stores``` I see a ```TermsStore``` (with ```TaxonomyTermsStore```s) and the files are persisted in ```content/taxonomies```.

And the stache is fast, which is good. If the stache is cleared, it can be rebuild from those files. Sounds like a solid system.

I could not find where terms are inferred from their existence in an entry though. Do you know where the code for that can be found? At least it currently isn't working as intended. 

I also wonder why... It sounds like a lot of trouble, just for not having to create a file for some of the terms... Does it pay? Or would it if it was working?
