### ISSUE TITLE
Bard Toolbar Not Fixed

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3230]
## Bug Description
Bard's toolbar doesn't stay fixed on scroll when the Bard field is inside a Replicator set. 

## How to Reproduce
- Create a Replicator field
- Add a set that includes a Bard field
- Set the bard option `toolbar_mode: fixed`

## Environment
Statamic 3.0.42 Pro
Laravel 8.26.1
PHP 7.4.15
aerni/social-links 2.1.0
aerni/zipper 1.2.0
aryehraber/statamic-impersonator 2.1.0
jonassiewertsen/statamic-livewire 2.4.0
spatie/statamic-responsive-images 1.8.0
visuellverstehen/statamic-classify 2.0.1
withcandour/aardvark-seo 2.0.7

**Comment by twd3** [comment]
I'm running into this as well right now.

**Comment by duncanmcclean** [comment]
Which browser are you using? I'm unable to replicate this in Chrome.

**Comment by aerni** [comment]
I'm using Chrome.

**Comment by duncanmcclean** [comment]
Ah, nevermind, I hadn't put Bard in a replicator set. I see the issue now. 🤦‍♂️

**Comment by robdekort** [comment]
It would also be nice if it would be fixed/sticky in full screen mode.
