### ISSUE TITLE
Taxonomy terms field does not return correct site data through content API

### ISSUE THREAD

**Issue by RobbertUpgraders** [statamic/cms#3233]
## Bug Description
**Update: Issue is still present in 3.1.30.**

I am using a Taxonomy Terms field to connect a taxonomy collection called Subcategories to a taxonomy collection called Categories. For this I use the Taxonomy terms field and in our custom framework we filter this. 

But the problem is that when changing language (site) the content that comes from that Taxonomy terms field is not translated even though the multisite each have a different translation for the categories. 

## How to Reproduce
Create a multisite CMS
Add 2 taxonomy collections with entries (translated) and connect them together (one way)
Check the content api output and filter using filter[site]=english

## Extra Detail
English (note that industrie should be industry):
![image](https://user-images.githubusercontent.com/75248241/107742512-72080f80-6d0f-11eb-9a26-9ae91c0fc226.png)

German (Note that industrie in german is the same as Dutch (atleast according to google translate) but the point is for all languages its the same output): 
![image](https://user-images.githubusercontent.com/75248241/107742608-a8458f00-6d0f-11eb-94d6-958f017d437a.png)

## Environment
Statamic 3.0.43 Pro
Laravel 8.26.1
PHP 7.3.26
No addons installed

- Fresh install from `statamic/statamic`

**Comment by RobbertUpgraders** [comment]
This issue is still present in 3.1.30. I can see "Taxonomy improvements" on the roadmap but is there an update about this issue? Or maybe a quick and dirty fix?

**Comment by duncanmcclean** [comment]
This seems to be working now, on the latest version of Statamic.
