### ISSUE TITLE
UI: Improve multi-site toggle to be more clear about which site is currently active

### ISSUE THREAD

**Issue by tao** [statamic/cms#3236]
Sorry, I'm not sure if this should be a bug or a feature request.

After using Statamic for a while, I find that I (very) often end up editing content on the wrong (language) site, especially when I'm switching between pages / tabs. I find this difficult especially when I don't understand both languages and end up copying data to the wrong one.

This tiny blue badge is the only indication of which site I'm on, and I don't seem to visually notice when I scan the page if I'm on the wrong one.

![ui-small-diff](https://user-images.githubusercontent.com/1446331/107846568-7145ab00-6ded-11eb-8675-c60529510eff.png)

Can we improve the UI somehow so it's more clear which site someone is on with a glance? 

![multisite-ui](https://user-images.githubusercontent.com/1446331/107846452-8cfc8180-6dec-11eb-95f2-f0b7ffeec2e8.png)

**Comment by duncanmcclean** [comment]
Improvement could be combined with #3173.
