### ISSUE TITLE
Form submission fails on getRenderableFieldData

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#3238]
## Bug Description

When sending a form submission email, it fails with an exception of "Call to a member function field() on string "

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/3626559/107849265-62b1c080-6dfa-11eb-91cf-723be2639314.png">

The `$values` this errors on are `date` and `id`, these are values of the submission, but aren't fields.

## How to Reproduce

1. Create a form
2. Submit the form

## Environment

Statamic 3.0.43 Pro
Laravel 7.30.4
PHP 7.4.13

**Comment by mikemartin** [comment]
@robdekort Can confirm that this was introduced in 3.0.43 and you can roll back to 3.0.42 as a workaround.
