### ISSUE TITLE
Call to a member function icon() on null

### ISSUE THREAD

**Issue by netwrkx** [statamic/cms#3242]
## Bug Description
i tried extending statamic cms by using my own route, changed the 
`'enabled' => env('CP_ENABLED', false),`
and declared my route
```
if (!config('statamic.cp.enabled')) {
    Route::middleware(SwapCpExceptionHandler::class)->group(function () {
        Route::middleware('web')
            ->name('statamic.cp.')
            ->prefix(config('statamic.cp.route'))
            ->namespace('CP')
            ->group(__DIR__.'/statamic_cp.php');
    });
}
```
everything i login to statamic using my custom route, i get the following error
```

Error
Call to a member function icon() on null (View: D:\laravel\n\laravel8\statamic_project\vendor\statamic\cms\resources\views\layout.blade.php)
http://localhost:8002/cp/dashboard

D:\laravel\n\laravel8\statamic_project\vendor\statamic\cms\src\CP\Navigation\CoreNav.php:54

    protected function makeTopLevel()
    {
        Nav::topLevel('Dashboard')
            ->route('dashboard')
            ->icon('charts');
   }
```

## How to Reproduce
```
install statamic
update statamic cp config to enabled' => env('CP_ENABLED', false)
declare custom route
if (!config('statamic.cp.enabled')) {
    Route::middleware(SwapCpExceptionHandler::class)->group(function () {
        Route::middleware('web')
            ->name('statamic.cp.')
            ->prefix(config('statamic.cp.route'))
            ->namespace('CP')
            ->group(__DIR__.'/statamic_cp.php');
    });
}
```
## Environment
Statamic 3.0.43 Solo
Laravel 8.27.0
PHP 7.4.7

**Statamic version:** 3.0.{?}
v3.0.43
**PHP version:** 7.{?}
Laravel v8.27.0 (PHP v7.4.7)
**Install method (choose one):**
- Existing Laravel app

**Comment by duncanmcclean** [comment]
I'll try and reproduce this evening but is there any reason you're defining the CP routes yourself?

**Comment by netwrkx** [comment]
I'm adding statamic to an existing application

**Comment by netwrkx** [comment]
@duncanmcclean 
```
removing this code snippet fixed the error
        if (! config('statamic.cp.enabled')) {
            return null;
        }


    public static function cpRoute($route, $params = [])
    {
        if (! config('statamic.cp.enabled')) {
            return null;
        }

        $route = route('statamic.cp.'.$route, $params);

        // TODO: This is a temporary workaround to routes like
        // `route('assets.browse.edit', 'some/image.jpg')` outputting two slashes.
        // Can it be fixed with route regex, or is it a laravel bug?
        $route = preg_replace('/(?<!:)\/\//', '/', $route);

        return $route;
    }

```

**Comment by duncanmcclean** [comment]
> @duncanmcclean
> 
> ```
> removing this code snippet fixed the error
>         if (! config('statamic.cp.enabled')) {
>             return null;
>         }
> 
> 
>     public static function cpRoute($route, $params = [])
>     {
>         if (! config('statamic.cp.enabled')) {
>             return null;
>         }
> 
>         $route = route('statamic.cp.'.$route, $params);
> 
>         // TODO: This is a temporary workaround to routes like
>         // `route('assets.browse.edit', 'some/image.jpg')` outputting two slashes.
>         // Can it be fixed with route regex, or is it a laravel bug?
>         $route = preg_replace('/(?<!:)\/\//', '/', $route);
> 
>         return $route;
>     }
> ```

Hmm okay, it shouldn't need you to do the routing yourself but I'm glad you've managed to resolve the issue.

**Comment by duncanmcclean** [comment]
I'm closing this issue as you've managed to fix it. If you run into it again, let me know and I can re-open the issue.
