### ISSUE TITLE
Page Blink Cache Issue 

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3245]
## Bug Description
I need to get the URLs of all entries from within an `EntrySaved` listener. When I change the slug of a parent entry in the CP, the URL's of the child entries still prepend the old slug of the parent entry. 

URLs before save of the parent entry:

```yaml
/about
/about/contact
```

URLs after save of the parent entry:

```yaml
/about-me
/about/contact
```

I expect it to be like this:

```yaml
/about-me
/about-me/contact
```

I narrowed the issue down to the `Blink` cache. If you uncomment this line, the URL's will be returned as expected:
https://github.com/statamic/cms/blob/86c2b96bd1d0b135717c17944cf120b0051bf433/src/Structures/Page.php#L160

Current workaround: The child entry's URL will be correct when you hit the save button on the parent entry twice.

## How to Reproduce
1. Create and hook up this listener:

```php
class EntrySavedListener
{
    public function handle(EntrySaved $event): void
    {
        $urls = Entry::all()->map(function ($entry) {
            return $entry->url();
        });

        ray($urls);
    }
}
```

2. Add a parent and a child entry 
3. Change the slug on the parent entry and hit save
4. The child's URL will not update
5. Uncomment the line mentioned above
6. Save the parent entry again
7. The child's URL will update correctly.

## Environment
Statamic 3.0.43 Solo
Laravel 8.27.0
PHP 7.4.15

**Comment by aerni** [comment]
This can also be fixed by uncommenting this line here:
https://github.com/statamic/cms/blob/fb4dcbc49dd0863e859a6cec87a83636dd0f07f5/src/Entries/Entry.php#L299

I'm not exactly sure if this would break anything else though.

**Comment by jasonvarga** [comment]
Is this still an issue for you on 3.1.x?

**Comment by aerni** [comment]
Looks like this is not an issue anymore. I'm on `3.1.5`.
