### ISSUE TITLE
Variable interpolation issue

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#3248]
This syntax should work, but doesn't.

```
{{ form:create :in="form_fieldtype_field:handle" }}
```

**Comment by aerni** [comment]
Ran into this as well. Thought I was going crazy. Glad it's a bug 😅

**Comment by sandersjj** [comment]
Can anyone please explain to me what the `in` modifier should do. This way I can try to reproduce it and fix it in the right way. Thanks!

**Comment by duncanmcclean** [comment]
> Can anyone please explain to me what the `in` modifier should do. This way I can try to reproduce it and fix it in the right way. Thanks!

It specifies the form for which to create the HTML form for.

**Comment by jackmcdade** [comment]
I don't think the issue is the `in` parameter specifically, but rather some part of the Antlers Parser that isn't applied to certain types of parameters, and this is just one of them.

**Comment by jackmcdade** [comment]
Fix in progress: https://github.com/statamic/cms/pull/3267
