### ISSUE TITLE
Create Entry defaults to first blueprint alphabetically 

### ISSUE THREAD

**Issue by sjclark** [statamic/cms#3251]
## Bug Description
When only a single blueprint is available (due to hiding others) Statamic will default to the first blueprint **alphabetically** instead of using the only one available. 

## How to Reproduce
1. Create a few blueprints for a collection
2. Hide all blueprints except one (ensure the chosen one is not the first alphabetically)
3. Add a new item to a collection with "Create Entry"
4. Watch as it defaults to the first Blueprint **alphabetically**, instead of the only visible one

## Extra Detail
Seems to always choose the first blueprint **alphabetically**

![Screen Shot 2021-02-16 at 8 30 13 pm](https://user-images.githubusercontent.com/4531017/108045585-bdb41380-7097-11eb-8cfe-06da473f74fb.png)

![Screen Shot 2021-02-16 at 8 30 34 pm](https://user-images.githubusercontent.com/4531017/108045598-c0166d80-7097-11eb-91a4-09dfe6ba9c83.png)

![Screen Shot 2021-02-16 at 8 30 55 pm](https://user-images.githubusercontent.com/4531017/108045603-c278c780-7097-11eb-9bac-afbe3fe4cf8e.png)

![Screen Shot 2021-02-16 at 8 44 42 pm](https://user-images.githubusercontent.com/4531017/108045644-cf95b680-7097-11eb-99ad-63a8ac9cf09e.png)

^ Create Entry will now default to the **Programme** Blueprint despite it being hidden

## Workaround
🤷‍♂️ Make the Blueprint you actually want to use **first alphabetically**

## Environment
Statamic 3.0.43 Pro
Laravel 8.27.0
PHP 7.4.12
doublethreedigital/duplicator 1.2.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
Can confirm this, just worked with Sam to figure out this issue. A new entry will used the alphabetically first blueprint even when they're hidden.

**Comment by jasonvarga** [comment]
Nice find
