### ISSUE TITLE
array_key_exists error on integer values

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/cms#3254]
## Bug Description

When using the link tag, and editing in the control panel, I would click on `Link Existing Item`. This gives the error:

```
local.ERROR: array_key_exists(): The first argument should be either a string or an integer 
```

https://user-images.githubusercontent.com/113216/108118204-005ff680-706c-11eb-8e68-162a4f8c3d36.mov

I narrowed this down to an unquoted string:

`sitemap_priority: 0.5`

This was put in my .md file by the Aardvark SEO add-on. I've tested and the updated add-on saves as:

`sitemap_priority: '0.5'`

I tried this and it also gives the error:

`sitemap_priority: 1`

And all is lovely.

Just opening the issue to see if there's a better way to handle the value. It takes quite a while to debug down to the root issue.

**Statamic version:** 3.0.43

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Using Aardvark SEO add-on.

**Comment by duncanmcclean** [comment]
For context of anyone looking at this issue: it looks like `sitemap_priority` is a Select field, [see blueprint](https://github.com/WithCandour/statamic-aardvark-seo/blob/7c25e17ec542d8fd797556a3fe7624e81d41509d/src/Blueprints/CP/OnPageSeoBlueprint.php#L149). Maybe the select field is being weird with floats when it saves it or something?

**Comment by jackmcdade** [comment]
I can't recreate this issue – and there have been a few updates to both fieldtypes here. I think it should be all resolved at this point, but feel free to reopen if it's an issue specifically with the Select fieldtype.
