### ISSUE TITLE
If asset's meta file is empty, CP & site throw errors

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#3257]
## Bug Description

If an asset's .meta file is empty (only `data: {}`), then trying to list that asset folder in the CP throws a `Invalid index: size`. error.

Not sure how we're getting these blank'ish meta files but has happened a few times now. Likely a git merge thing.

## How to Reproduce

1) Add an asset
2) manually remove the fields in it's meta file.
3) try to list that asset folder in the cp.

## Extra Detail

It's right here:
```
    public function size()
    {
        return $this->meta()['size'];
    }
```

This should be a bit more robust, if possible. Perhaps using the `Arr:get` method?

## Environment

Statamic 3.0.43 Pro
Laravel 8.28.1
PHP 7.4.11
aryehraber/statamic-captcha dev-disable-captcha
aryehraber/statamic-uuid 2.0.3
edalzell/forma 0.8.5
statamic/seo-pro 2.1.0
transformstudios/drafts 2.1.1
transformstudios/events dev-main
transformstudios/front 1.1
transformstudios/memorial dev-staging
transformstudios/price-of dev-staging

**Comment by edalzell** [comment]
@jasonvarga looks like it was saved this way:

<img width="1168" alt="CleanShot 2021-02-23 at 19 15 25@2x" src="https://user-images.githubusercontent.com/6069653/108942285-91564500-760b-11eb-8715-33ae940c3984.png">

**Comment by jackmcdade** [comment]
Fixed by @arthurperton in https://github.com/statamic/cms/pull/3280. Thank you! ❤️
