### ISSUE TITLE
Date fieldtype doesn't use the right format

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#3265]
## Bug Description

This issue is for the second part of #1310 

The date fieldtype uses a hardcoded format on the publish form (not the listings).

## How to Reproduce

- Have a date field
- Set a custom format in `config/statamic/cp.php` `date_format` (as that feels like the natural place to do it)
- See the date field in the hardcoded format

## Extra Detail

Since the Vue part of the date fieldtype needs a moment.js compatible date format (different from the PHP format the `date_format` config uses), we'll probably need _another_ config value, like `date_format_js` or something.

Unless there's some cool way to convert from PHP date to moment.js.
...As I'm writing this, I decided to Google if such a thing already exists. [It might](https://stackoverflow.com/questions/30186611/php-dateformat-to-moment-js-format).

## Environment

**Statamic version:** 3.0.44

**Comment by jackmcdade** [comment]
It's worth mentioning that the Date fieldtype is actually set to the format automatically based on your locale. For example, if your locale is `fi` for Finland, you'll see today's date as `11.03.2021`, `sv` for Swedish gets you `2021-03-20`, and so on. I know this isn't rolled all the way across the CMS so it's not something you'd be able to "set and forget", but if anyone is reading this and needs a solution, this could very much be one.

**Comment by wesort** [comment]
Is this the `locale` set in `/config/app.php`? And what would be appropriate for the UK? 
Both `en_UK` `en_GB` break the date field. I cannot find this in the docs (Statamic or Laravel).

Below is from a project where the date field displays `08/02/2012` (when it's not open showing the datepicker). In the UK, `08/02/2012` is read as `08 Feb 2012` but the CMS has this as `02 Aug 2012`.

.

![UK locale](https://user-images.githubusercontent.com/3920126/110836294-cadbb100-8297-11eb-8ee8-3179514da944.png)

**Comment by jonatanalvarsson** [comment]
Yeah, the date picker completely ignores both the `app.locale` and the `statamic.cp.date_format` config values when formatting the picked date.

It still "works". I mean you get the date "2nd August 2012" when ju select "2nd August 2012" in the mini calendar. But it's very annoying and confusing for us non-Americans to keep remembering to interpret "08/02/2012" in the date picker as 2 aug - and not 8 feb. Especially when the rest of the front end, like the entry listing uses the configured date format.

I vote for a `statamic.cp.date_format_js` config value (in Moment.js format) to be able to change the default US format used by the date picker.

**Comment by jacksleight** [comment]
I've been trying to figure this out as well (also in UK).

Setting `app.locale` to `en-GB` fixes the date format in the UI, however, it breaks other stuff. It looks like the CP does not like locales with a country part, as a lot of the text becomes placeholders:

![Screenshot 2021-03-18 at 17 14 07](https://user-images.githubusercontent.com/126740/111668329-8dce6c00-880d-11eb-9930-59f4b3a4a997.png)

I thought the CP might use the `app.fallback_locale` in this situation, but it doesn't.

I'm currently solving this by leaving `app.locale` as `en`, and then adding this to my `cp.js`:

```js
Statamic.booting(() => {
    Statamic.$config.set('locale', 'en-GB');
});
```

That works, and the text is still right, but it's not ideal as I'd really prefer to set my application's locale the the full `en-GB` value. I think it makes sense to use the locale for the date display format. If the translation logic could be tweaked to use the fallback locale as well (or just the language part of `app.locale`) that would work great.

**Comment by verybigelephants** [comment]
> I've been trying to figure this out as well (also in UK).
> 
> Setting `app.locale` to `en-GB` fixes the date format in the CP:
> 
> ![Screenshot 2021-03-18 at 17 31 11](https://user-images.githubusercontent.com/126740/111670456-c2dbbe00-880f-11eb-80c4-5903d5a3f846.png)
> 
> However it breaks other stuff. It looks like the CP does not like locales with a country part, as a lot of the text becomes placeholders:
> 
> ![Screenshot 2021-03-18 at 17 14 07](https://user-images.githubusercontent.com/126740/111668329-8dce6c00-880d-11eb-9930-59f4b3a4a997.png)
> 
> I thought the CP might use the `app.fallback_locale` in this situation, but it doesn't.
> 
> I'm currently solving this by leaving `app.locale` as `en`, and then adding this to my `cp.js`:
> 
> ```js
> Statamic.booting(() => {
>     Statamic.$config.set('locale', 'en-GB');
> });
> ```
> 
> That works, and the text is still right, but it's not ideal. I'd really prefer to set my application's locale the the full `en-GB` value, and it feels hacky overriding this just on the JS side.
> 
> I think it makes sense to use the locale for the date display format, and if the translation logic could use the fallback locale as well (or just the language part of `app.locale`) it would all work fine.

this is a good suggestion, but then it breaks the whole control panel if you use statamic in anything other than the few cp- supported languages and instead of messages displays only lang keys like `messages.blueprints_title_instructions` instead of `Usually a singular noun, like Article or Product`
