### ISSUE TITLE
Custom asset validation rules should check mime types

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#3277]
## Bug Description

The validation rules introduced in #3253 validate against the file extensions. They really should be validating the actual mime types, as per the native Laravel `mimes` and `image` rules.

## Extra Detail

We should introduce a mimeType method on the Asset class.
It should read the mime type from the meta file. So, we should be saving the mime type to the meta file, too.

This also means that existing assets wouldn't have a mime in their meta files. We'll probably want a way to lazily regenerate the meta file. Right now when we call `meta` to get the whole array, it'll regenerate it if the file doesn't exist. But we'll need a way to see if a key is missing, and regenerate it.

## Environment

**Statamic version:** 3.0.44

**Comment by arthurperton** [comment]
I guess this one can be closed now, right?

**Comment by duncanmcclean** [comment]
> I guess this one can be closed now, right?

Yeah, looks like it.
