### ISSUE TITLE
Live preview: Javascript only loads on first render when using <script type="module">

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [statamic/cms#3287]
## Bug Description
The live preview loads and executes javascript only on first render, when the javascript is included via `<script type="module" src="…"></script>`.

## How to Reproduce
1. Install [`statamic/statamic`](https://github.com/statamic/statamic) empty starter site. 
2. Add a `console.log('Hello world')` to `resources/js/site.js` or directly to `public/js/site.js` to skip the npm build script.
3. Add `type="module"` to the script tag in line 14 in `resources/views/layout.antlers.html` like this: 
```html
<script type="module" src="{{ mix src='/js/site.js' }}"></script>
```
4. Open live preview for any page, make changes and watch the dev tools console: `Hello world` is only logged once.

## Extra Detail
Using an inline script like this works on every live preview reload:
```html
<script type="module">
    console.log('Hello world')
</script>
```
So my current workaround is to inline the javascript when the live preview is active.

----

Since build tools like Webpack, Rollup and Parcel support the `module/nomodule` pattern when bundling javascript, it would be nice if the Statamic live preview also works with `<script type="module" src="…">`.
For more info about the `module/nomodule` pattern see: https://web.dev/publish-modern-javascript/

## Environment
Both on local Valet server and Digital Ocean production server.

**Statamic version:** 3.0.44

**PHP version:** 7.4.15

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by felixstoessel** [comment]
I can confirm this. I use Rollup to build my JavaScript bundle. It get's included just like this `<script src="app.js"></script>`.

Whould be great to have some global event like `live_preview:updated` on `document` so I can listen to and react.

**Comment by SebastianEberlein-JUNO** [comment]
@felixstoessel You could use a `Mutation Observer` instead of a `setInterval()` to watch for class changes. Example: https://www.seanmcp.com/articles/event-listener-for-class-change/

**Comment by jasonvarga** [comment]
I haven't tested this yet, but if you can recreate it, that's great!

Could this be the same issue as #832 ?

**Comment by SebastianEberlein-JUNO** [comment]
@jasonvarga I’m not sure if it’s the same issue as #832. They implemented a custom live preview function and scripts that are conditionally added to the head.

My issue is maybe related to how the browser handles `<script type="module">` in general. Maybe the script is only executed once, because on second load, it already exists and cannot be redeclared (?). I am still looking into it, but haven’t found any helpful information yet.

**Comment by duncanmcclean** [comment]
I can confirm. It does look like the browser makes an HTTP request when something is changed but for whatever reason the code is not run. 

Maybe it has something to do with the way `type="module"` works? I removed the `type` attribute from the tag and the console log works fine after every change, which makes me think it's possibly not Statamic related.
