### ISSUE TITLE
Scripts added by addons don't get versioned

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#3294]
## Bug Description
When adding a script to the CP through the `Statamic\Statamic` facade, there is not version number getting appended. Is there a way to add cache busting to these scripts?

## How to Reproduce
Add an extra script to the CP with `Statamic\Statamic::script('vendor', 'script_name');`. Notice in the devtools how there's not version number / cache busting.

## Extra Detail
Note how a version number get's added to the standard CP scripts. 
![Screenshot 2021-02-23 at 12 12 07](https://user-images.githubusercontent.com/9193686/108836037-a2359500-75d0-11eb-85fe-05fd12680429.png)

## Environment
Statamic 3.0.44 Pro
Laravel 7.30.4
PHP 7.4.9

- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
I think probably the best fix for this would be to version the assets by the addon version.

Laravel Mix does have versioning, however not all addons provide a mix manifest file which would be needed for that to work.

**Comment by JohnathonKoster** [comment]
Would something like this work?

```php
Statamic::script('package', 'asset'); // asset.js -- no change from current behavior
Statamic::script('package', 'scriptName', '2.1.0'); // scriptName.js?v=2.1.0
Statamic::script('package', 'test', ['v' => '2', 'key' => 'api-key']); // test.js?v=2&key=api-key
```

**Comment by jelleroorda** [comment]
@JohnathonKoster that would work for me

**Comment by jelleroorda** [comment]
Just to recap Jason from the closed PR  (or my translation from it);

1. We should think of a way to integrate the versioning into addons 'by default'. One solution could probably be to add the addon version to the params, just like how normal 'statamic' assets have their version appended. In my opinion this really 'just covers' the simple usecase, which is when you're already done developing the entire addon. For addons that you'd publish to the marketplace this is probably fine. When you just have local addons in your project this would probably not be a good solution, since you won't be tagging new versions for your addon all the time.
2. We should think of how we would integrate Laravel Mix (or any build process that outputs some kind of manifest) into this versioning. Since helpers like `mix()` are not usable in properties like `$scripts` in the `AddonServiceProvider` I think it'd have to boil down into manually calling `$this->registerScript()` inside your boot method. To also make it compatible with application level code, we would have to extend `Statamic::script()` which is what gets called under the hood by the `registerScript` method.

**Comment by jelleroorda** [comment]
After thinking about a for a bit, I think it could look something like this (with the something along those lines for stylesheets as well).

1. For registering scripts in addons

```php
    public function registerScript(string $path)
    {
        $name = $this->getAddon()->packageName();
        $version = $this->getAddon()->version();
        $filenameWithExtension = pathinfo($path, PATHINFO_BASENAME);

        $this->publishes([
            $path => public_path("vendor/{$name}/js/{$filenameWithExtension}"),
        ], $this->getAddon()->slug());

        Statamic::script($name, "{$filenameWithExtension}?v={$version}");
    }
```

2. Which would then impact the `Statamic::script` to be something like this:
```php
    public static function script($name, $path)
    {
        // If the path doesn't contain any query parameters, we'll make sure the script ends with `.js`,
        // this allows developers to register additional scripts without specifying the extension.
        // If there are query parameters, the developer has already specified the extension.
        if (! Str::contains($path, '?')) {
            $path = Str::finish($path, '.js');
        }
        
        static::$scripts[$name][] = $path;

        return new static;
    }
```

This would then allow the following code:

**For addon devs, that just need simple versioning**
```php
class ServiceProvider extends AddonServiceProvider
{
    protected $scripts = [
        __DIR__.'/../resources/js/example.js',
    ];
}
```

**For addon devs, that use Laravel Mix or something similar**
(not as pretty obviously, but more control)
```php
class ServiceProvider extends AddonServiceProvider
{
    public function boot()
    {
        Statamic::booted(function () {
            // Note: `getAddon` would have to become protected for this to work
            $name = $this->getAddon()->name();

            $this->publishes([
                __DIR__.'/../dist/js/example.js' => public_path("vendor/{$name}/js/example.js"),
            ], $this->getAddon()->slug());

            Statamic::script($name, mix('js/bar.js'));
        });

        parent::boot();
    }
}
```

Maybe we could add more 'sugar' so it would be reduced to something like this?

```php
class ServiceProvider extends AddonServiceProvider
{
    public function extraScripts()
    {
        return [
            __DIR__.'/../dist/js/example.js' => mix('js/bar.js'),
        ];
    }
}
```
