### ISSUE TITLE
{{ nav:collection :from="mount" }} causes error

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#3295]
## Bug Description
I want to show the entries from a mounted structured collection, but this error is shown:
```
array_key_exists(): The first argument should be either a string or an integer
```

## How to Reproduce
```
{{ nav:pages }}
{{ collection :from="mount" }}
// Shows all entries, but not structured
{{ /collection }}
{{ /nav:pages }}
```
```
{{ nav:pages }}
{{ nav:collection :from="mount" }}
// Causes error
{{ /nav:collection }}
{{ /nav:pages }}
```

## Environment

**Statamic version:** 3.0.44

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
In the second code snippet you shared above, you didn't include the handle of the collection you're wanting to get the nav for.

This worked for me: (`pages` is the handle of my collection)

```
{{ nav:pages }}
  {{ nav:collection:pages :from="mount" }}
    <!-- Whatever you want here... -->
  {{ /nav:collection:pages }}
{{ /nav:pages }}
```

Also, is there a reason you're using the `nav` tag inside of another `nav` tag, what are you trying to do?

**Comment by wm-simon** [comment]
This makes no sense for me. `mount` is the mounted collection, which should shown as children. When I use the handle, the mounted collection will not be shown.

### collection pages:
 - **parent 1**
   - Item 1
   - item 2
   - item 3
 - **parent 2**
   - mounted collection 
 - **parent 3**

### mounted collection:
 - **mounted parent 1**
   - mounted Item 1
   - mounted item 2
   - mounted item 3
 - **mounted parent 2**
     - mounted item 1
     - mounted item 2
     - mounted item 3
 - **mounted parent 3**

### Result should be:
 - **parent 1**
   - Item 1
   - item 2
   - item 3
 - **parent 2**
   - **mounted parent 1**
     - mounted item 1
     - mounted item 2
   - **mounted parent 2**
     - mounted item 1
     - mounted item 2
     - mounted item 3
   - **mounted parent 3**
 - **parent 3**

**Comment by duncanmcclean** [comment]
Ah gotcha! That makes sense. 

However, I'm not sure if you can pass anything dynamic into the `{{ nav:collection }}` tag (from quickly looking at the code). Looks like it has to be specified like `{{ nav:collection:handleOfCollection }}`. 🤔

**Comment by wm-simon** [comment]
If you search for `collection :from="mount"` on discord, you can find results with `{{ collection :from="mount" }}{{ /collection }}` to mount the entries. I thought this should work with a structured collection too.

**Comment by duncanmcclean** [comment]
Yeah, that's from the collection tag, not the nav:collection tag. They're different, which ones are you trying to use?

**Comment by acerempel** [comment]
Perhaps you are looking for the [`handle` parameter](https://statamic.dev/tags/nav#parameters)? As in, `{{ nav:collection :handle="mount" }}`. That is the equivalent of the `from` parameter for the `nav` tag. (The `from` parameter does something different with `nav` – it set point in hierarchy from which to start iterating.)

**Comment by jackmcdade** [comment]
@acerempel hit it on the head. `{{ nav :handle="mount" }}` should be the way to go. Feel free to reopen if this isn't the ticket.
