### ISSUE TITLE
Date field in Mode:Range is broken on index

### ISSUE THREAD

**Issue by caseydwyer** [statamic/cms#3301]
## Bug Description
Using a Date field with Mode set to Range throws an error on the index view of the Collection.

## How to Reproduce
1. Create a `Date` on a Blueprint.
2. Set the `Mode` to Range, and show on index by default.
3. Create a record in the Collection.
4. Visit the Collection index page.

## Extra Detail
With a Date field on the Blueprint and its `Mode` set to **Range**, we're getting the following error on the index page:
`DateTime::__construct() expects parameter 1 to be string, array given`

Was working fine on v3.0.43, bumped to v3.0.45 and it was broken.

## Environment
Statamic 3.0.45 Pro
Laravel 8.29.0
PHP 7.4.3
cubitcreative/statamic-places dev-master
jonassiewertsen/statamic-livewire 2.4.0

**Comment by duncanmcclean** [comment]
Hmm, I don't seem to be able to reproduce that exception but I'm guessing this probably shouldn't be JSON anyway. 😆  

![image](https://user-images.githubusercontent.com/19637309/109075151-abb61e80-76f0-11eb-9029-a7bfdbd863f5.png)

**Comment by caseydwyer** [comment]
I think maybe that's on an older version of Statamic...is that possible? What you're seeing is exactly what I had **prior** to updating Statamic yesterday. Did a sanity check by installing a fresh Statamic app, running on latest version, and couldn't recreate that JSON format on index. 

PR above addresses both issues. Thanks for looking into this, @duncanmcclean—let me know if I'm missing something obvious! Always a strong possibility. 🙂

**Comment by duncanmcclean** [comment]
Hmm, that's my sandbox site which is running whatever is on the `3.0` branch but there is a possibility it might be messed up somehow, it's happened before.

Awesome! The pull request looks good to me 😄

**Comment by AndreasSchantl** [comment]
I do experience the same error when trying to mount a collection to a page. I'll try if your PR fixes the issue for that too!

**Comment by AndreasSchantl** [comment]
It does! Thanks @caseydwyer
