### ISSUE TITLE
Default site variables alias don't work

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#3313]
## Bug Description

Like the [doc explain it](https://statamic.dev/variables/site), for single sites application with such configuration:

```php
// config/statamic/sites.php

'sites' => [
    'default' => [
        'name' => 'My Statamic Site',
        'locale' => 'en_US',
        'url' => 'http://mysite.com/',
    ]
]
```

The following variables alias should work:
```twig
{{ site:name }}
{{ site:url }}
```

Which is not the case for me.

## Environment

Statamic 3.0.45 Pro
Laravel 8.29.0
PHP 8.0.2
4rn0/statamic-v3-image-optimizer 1.0.5
jimblue/htmlmin 1.1.0
jimblue/instagram dev-develop
jimblue/mapbox 1.2.0
jimblue/webpacker dev-develop
statamic/seo-pro 2.1.3

**Comment by robdekort** [comment]
That's odd, just tried and it works here, both in multisite and non multisite.

**Comment by jasonvarga** [comment]
Seems to be fine!

What isn't working? What do those variables output?

**Comment by jimblue** [comment]
OK I've just found what happened.
It's due to a collision with one of my **globals** that I've smartly named **site** 💩

Sorry for the noise guys, I close the issue ! 👋
