### ISSUE TITLE
Option to ignore EXIF for processing after issues

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#3316]
## Bug Description
I had an image on a website where somehow the EXIF data was either corrupted or wrongly interpreted. The saved meta data for this asset also had the width and height values flipped.

A simple way to avoid this is a global option to ignore all the EXIF data.

## How to Reproduce
In my stupidity, I deleted the image so no easy way to reproduce. Sorry.

## Environment
Statamic 3.0.45 Pro
Laravel 8.27.0
PHP 7.4.11

**Comment by jasonvarga** [comment]
We don't use exif data. We use [getimagesize](https://www.php.net/manual/en/function.getimagesize.php) to find the dimensions, which doesn't use exif.

If you can find another asset to reproduce your issue, feel free to comment or open a new issue.

**Comment by felixstoessel** [comment]
@jasonvarga Well, in the Statamic docs (https://statamic.dev/tags/glide#parameters) there is a `orient` parameter that uses EXIF. Maybe pass this option through Glide globally if Glide has some EXIF ignore logic.

FYI: I did remove all the EXIF data of this image and then I had to rotate it manually. After reuploading, everything worked. So I assume the issue is with some EXIF handling.
