### ISSUE TITLE
Asset meta information not removed when asset deleted

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#3319]
## Bug Description

If you delete an asset via the asset browser, the `.meta` information for that asset is not removed.

## How to Reproduce

1. upload an asset
2. delete an asset
3. see the meta info file is still there.

## Environment

Statamic 3.0.43 Pro
Laravel 8.27.0
PHP 7.4.15
austenc/statamic-instagram-feed 2.2.0
edalzell/variable 1.0.3
rias/statamic-data-import dev-remove-empty-data
statamic/eloquent-driver dev-with-prs

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
It does get deleted.

Can you provide any more details? What disk are you using?

**Comment by edalzell** [comment]
LOL, so you're saying I shouldn't delete from a staging env but look at the git history on my local dev?
