### ISSUE TITLE
Modifier format_localized ignores locale settings?

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#3321]
## Bug Description
I'm not sure if it's a bug or if I'm doing something wrong, but `format_localized` modifier ignores the locale settings in sites.php.

## How to Reproduce
I have a multisite setup with the following block in sites.php
```
 'sites' => [

        'default' => [
            'name' => 'Norsk',
            'locale' => 'nb_NO',
            'url' => '/',
        ],
        'en' => [
            'name' => 'English',
            'locale' => 'en_US',
            'url' => '/en/',
        ],
    ],
```

Then when I use like {{ date format_localized="%d %B %Y" }} I would expect the month name to be in Norwegian. This is not happening.

## Extra Detail
n/a

## Environment

Statamic 3.0.45 Pro
Laravel 8.26.1
PHP 7.4.15
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Make sure you are using a locale that is installed on your system.

You can run `locale -a` to see everything you have, or `locale -a | grep no` to filter down all the ones containing "no".

**Comment by espenlg** [comment]
I was like 110% sure I had the locale installed, but you're absolutely right. It now works, thank you 🙏 .
