### ISSUE TITLE
The lower modifier has no effect on {{ date }}

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#3322]
## Bug Description
When adding the lower modifier like this `{{ date format_localized="%d %B %Y" | lower }}` the result is not in lowercase: `01 March 2021`

## How to Reproduce
See description

## Extra Detail
n/a

## Environment
Statamic 3.0.45 Pro
Laravel 8.26.1
PHP 7.4.15
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
The issue here is that you're mixing modifier types. Be consistent and it should work.

```
{{ date format_localized="%d %B %Y" lower="true" }}
```
