### ISSUE TITLE
Update count is wrong

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3323]
## Bug Description
The update count in the CP navigation shows pending updates. But the page says that everything is up to date.

## Extra Detail
<img width="1199" alt="Screenshot 2021-03-02 at 11 53 43 AM" src="https://user-images.githubusercontent.com/23167701/109638213-0535a780-7b4e-11eb-88a0-ca55f580a40b.png">

## Environment
Statamic 3.0.45 Pro
Laravel 8.29.0
PHP 7.4.15
aerni/dynamic-cache 1.0.0
aerni/social-links 2.2.0
aerni/zipper 1.2.0
aryehraber/statamic-impersonator 2.1.0
jonassiewertsen/statamic-livewire 2.4.0
spatie/statamic-responsive-images 2.5.0
visuellverstehen/statamic-classify 2.0.1
withcandour/aardvark-seo 2.0.9

**Comment by duncanmcclean** [comment]
Does the count go away if you clear your cache? `php artisan cache:clear`

**Comment by aerni** [comment]
No, it doesn't.

**Comment by duncanmcclean** [comment]
Hmm, that's strange. What about if you run `composer update`.. maybe you're lock file is somehow out-of-date?

**Comment by aerni** [comment]
That doesn't fix it either. I also deleted the `composer.lock` and the `vendor` folder and ran `composer update` again. Still didn't remove the count.

**Comment by duncanmcclean** [comment]
Hmm, I'll investigate this afternoon. It's not something I've seen come up before, at least not that I can remember.

**Comment by aerni** [comment]
I ran into this before. Just never pursued it further.

**Comment by duncanmcclean** [comment]
Hmm, I'm unable to reproduce on any of my local Statamic sites. By the looks of the code, clearing the cache should have fixed it (as long as the dependencies are out-of-date).

I know it sounds like a silly question, but are you sure Statamic and each of the Statamic addons are actually on the latest version available? Would you be able to share your `composer.json` file?

**Comment by aerni** [comment]
Yes, all dependencies are up to date. I think I found the issue though. The `Dynamic Cache` and `Zipper` addon show the correct version on the overview page, but throw an error in their detail page:

**Detail Page in the CP:**

<img width="1277" alt="Screenshot 2021-03-03 at 10 40 23 AM" src="https://user-images.githubusercontent.com/23167701/109785866-dcc0b280-7c0c-11eb-80a1-e5baa4f71f86.png">

**Looking at the Marketplace, both addons seem to be stuck on Version `vdev-master`.**

<img width="1201" alt="Screenshot 2021-03-03 at 10 42 09 AM" src="https://user-images.githubusercontent.com/23167701/109786100-1c879a00-7c0d-11eb-90fe-912fcefceb90.png">

<img width="1222" alt="Screenshot 2021-03-03 at 10 40 46 AM" src="https://user-images.githubusercontent.com/23167701/109785916-ea763800-7c0c-11eb-9405-b6e47b8f5a82.png">

I think that's what's causing the issue. The Marketplace version is out of date. Any idea how to get them updated? I already tried saving both addons on their edit page. Didn't work.

**Comment by duncanmcclean** [comment]
Hmm, do the versions for the addons look right if you look at them in Packagist?

**Comment by aerni** [comment]
Yes, they are correct. Also, no problem to install the latest versions with composer. Only the Statamic Marketplace is off.

https://packagist.org/packages/aerni/dynamic-cache
https://packagist.org/packages/aerni/zipper

**Comment by duncanmcclean** [comment]
Hmm, sounds like it's something for the Statamic Team to have a look at, maybe something's not configured correctly on the Marketplace end or a cache somewhere needs to be cleared. Might be worth contacting support (or maybe one of the team are wondering on here... 👀 )

However, as this doesn't look like a Statamic Core issue (rather one of the Marketplace), I'm going to close this issue. If it doesn't end up being a Marketplace issue, let me know and I can re-open this issue.

**Comment by jasonvarga** [comment]
@aerni In your statamic.com account, edit your products and make sure the `min version` corresponds to your git tags. Not the Statamic version.

Dynamic Cache and Zipper are both still only on v1.x so you should enter `1` for min version.

**Comment by aerni** [comment]
Thanks @jasonvarga. Works like a charm. How could I miss that 😅

**Comment by jasonvarga** [comment]
Does it fix the badge count?

**Comment by aerni** [comment]
Hmm, no it doesn't. I cleared both the `cache` and `stache`. The count is still stuck at `2`.

**Comment by aerni** [comment]
If it helps, this is my `composer.json`:

```json
{
    "name": "statamic/statamic",
    "description": "Statamic",
    "keywords": ["statamic", "cms", "flat file", "laravel"],
    "type": "project",
    "require": {
        "php": "^7.4",
        "aerni/dynamic-cache": "^1.0",
        "aerni/social-links": "^2.2",
        "aerni/sync": "^1.1",
        "aerni/zipper": "^1.2",
        "aryehraber/statamic-font-awesome": "^2.0",
        "aryehraber/statamic-impersonator": "^2.1",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.2",
        "jonassiewertsen/statamic-livewire": "^2.4",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0",
        "spatie/statamic-responsive-images": "^2.5",
        "statamic/cms": "^3.0",
        "visuellverstehen/statamic-classify": "^2.0",
        "withcandour/aardvark-seo": "^2.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.5",
        "facade/ignition": "^2.4",
        "fzaninotto/faker": "^1.9",
        "mockery/mockery": "^1.4",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.4",
        "spatie/laravel-ray": "^1.13"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan statamic:install --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

**Comment by duncanmcclean** [comment]
I've just created a fresh site, from the `composer.json` file that you provided above. However, I don't seem to be able to see the issue. 😅 

There's no counter on the left hand side.

![image](https://user-images.githubusercontent.com/19637309/111871807-eaec2e00-8983-11eb-9c47-928d0955fa6b.png)

If you're still seeing it there, would you mind popping your `composer.lock` file instead into a Github Gist (if you copied it here, this thread would become very long haha) so I can copy that and try and create a site from that? 

The lock file should hopefully let me use the exact same versions of every dependency that you're using which should hopefully in help :)

**Comment by aerni** [comment]
I ran another `composer update` today and the issue seems to be fixed now. Really odd … Closing this issue for now.
