### ISSUE TITLE
Antlers condition broken in 3.0.45?

### ISSUE THREAD

**Issue by idonix** [statamic/cms#3326]
## Bug Description
Reading a field for "truthiness" works on first call, but fails on second

## How to Reproduce
My blueprint has a "target" field of type "link"

My view has some debug code in it like this:
```
{{ if target }}
  <p>I HAVE A TARGET!!!</p>
{{ else }}
  <p>I DON'T HAVE A TARGET!!!</p>
{{ /if }}

{{ if target }}
  <p>NOW I STILL HAVE A TARGET!!!</p>
{{ else }}
  <p>NOW I DON'T HAVE A TARGET!!!</p>
{{ /if }}
```

Here's what it spits out:
```
<p>I HAVE A TARGET!!!</p>
<p>NOW I DON'T HAVE A TARGET!!!</p>
```

I'm expecting this:
```
<p>I HAVE A TARGET!!!</p>
<p>NOW I STILL HAVE A TARGET!!!</p>
```

## Extra Detail

This seems to have broken in 3.0.45 - it worked fine in 3.0.44

## Environment

Statamic 3.0.45 Pro
Laravel 8.29.0
PHP 7.4.13
aryehraber/statamic-captcha 1.3.0

**Statamic version:** 3.0.{?}
3.0.45

**PHP version:** 7.{?}
7.4.13

**Install method (choose one):**
- Fresh install from `statamic/statamic` <THIS ONE (a migrator upgrade from v2)
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by duncanmcclean** [comment]
I'm unable to reproduce this, here's what I'm seeing... 
![image](https://user-images.githubusercontent.com/19637309/110155866-2b717680-7dde-11eb-8e34-43058823fdd5.png)

**Comment by idonix** [comment]
@duncanmcclean I can't reproduce it in a new, clean blueprint and view either. Must be something weird about my particular use case, which I'll need to invetigate further. I'm going to close this issue.
