### ISSUE TITLE
Getting an 500 errors while using Glide in asset loop

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#3328]
## Bug Description

When using Glide in assets loop, each image request return a 500 error.

To get more info about the error, I've try to navigate to one of the Glide generated url, and this is the error I get:

```
GuzzleHttp\Exception\RequestException
cURL error 60: SSL certificate problem: unable to get local issuer certificate 
```

## How to Reproduce

**THIS IS WORKING**

view
```twig
{{ collection:photos }}
  {{ glide:cover width='600' }}
    <img scr="{{ url }}">
  {{ /glide:cover }}
{{ /collection:photos }}
````

output
```html
<img scr="/assets/glide/asset/cGFnZXMvcGhvdG9zL3VuZGVyd2F0ZXIvZWNoaW5vZGVybXMvZmVhdGhlcnN0YXIuanBn?w=600&s=a6021b3d3b9dc2468ff2a76dcd9637a2">
```

**THIS IS NOT WORKING**

view
```twig
{{ collection:photos }}
  {{ cover }}
    <img scr="{{ glide:url width='600' }}">
  {{ /cover }}
{{ /collection:photos }}
````

output
```html
<img scr="/assets/glide/http/aHR0cHM6Ly9pbW1lcnNpb24tcGljdHVyZXMudGVzdC9zdG9yYWdlL3BhZ2VzL3Bob3Rvcy91bmRlcndhdGVyL2VjaGlub2Rlcm1zL2ZlYXRoZXJzdGFyLmpwZw==?w=600&amp;s=a56d5d6ff85318333adb59a2e14ff46a">
```

error
```
GuzzleHttp\Exception\RequestException
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://jimblue.test/storage/pages/photos/underwater/echinoderms/featherstar.jpg
https://jimblue.test/assets/glide/http/aHR0cHM6Ly9pbW1lcnNpb24tcGljdHVyZXMudGVzdC9zdG9yYWdlL3BhZ2VzL3Bob3Rvcy91bmRlcndhdGVyL2VjaGlub2Rlcm1zL2ZlYXRoZXJzdGFyLmpwZw==?s=a56d5d6ff85318333adb59a2e14ff46a&w=600
```

## Environment

Statamic 3.0.45 Pro
Laravel 8.29.0
PHP 8.0.2
4rn0/statamic-v3-image-optimizer 1.0.5
jimblue/htmlmin 1.1.0
jimblue/instagram dev-develop
jimblue/mapbox 1.2.0
jimblue/webpacker dev-develop
statamic/seo-pro 2.1.3

**Comment by duncanmcclean** [comment]
What is `cover` is it an Asset fieldtype and does it have `max_items` set?

**Comment by jasonvarga** [comment]
Use `glide:id` instead of `glide:url`.

When you use a url, it'll do a http-based attempt. Since you're running on local, there's probably issues with Valets SSL certificate.

If you use the ID, it'll use the actual asset, and should work fine.

**Comment by jimblue** [comment]
Thank you @jasonvarga for the little explanation, it totally make sens.
I've just try to use `glide:id` instead of `glide:url`  and I confirm that it's working 🔥 🚀 🎉
