### ISSUE TITLE
Using SVG with Glide throws error, but should return url

### ISSUE THREAD

**Issue by codedge** [statamic/cms#3332]
## Bug Description

When passing in a SVG image to Glide, it throws an `Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files.` error, although in the [Statamic documentation](https://statamic.dev/tags/glide#unsupported-formats) it is said that it will just return the url.

## How to Reproduce

Having a mix of `png`, `jpg`, `xyz` formats of images and use Glide to display these like this:

```php
{{ glide:image }}
        <img src="{{ url }}" width="{{ width }}" height="{{ height }}" alt="{{ alt }}"/>
{{ /glide:image }}
```

## Extra Detail
![image](https://user-images.githubusercontent.com/4409904/109879481-e4687180-7c75-11eb-8365-51bb87058c29.png)

## Environment

Statamic 3.0.45 Solo
Laravel 7.30.4
PHP 7.4.15
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Ah yes it looks like we only added support for the svg smartness on the single tags.
