### ISSUE TITLE
Sorting Sections within a replicator field is not working as intended

### ISSUE THREAD

**Issue by jamie-brown** [statamic/cms#3333]
## Bug Description
When I try and re-order the sets within a replicator field, it doesn't move to the intended location and other sets all jump around and become out of place.

## How to Reproduce
Create a fieldset that has a replicator field. Inside the replicator, add a few sets. Add some fields to each set. Then try re-ordering the sets as per the video in the link below.

## Extra Detail
https://user-images.githubusercontent.com/3788827/109954918-cb91a780-7cd9-11eb-8bbd-3c4e37eaa668.mov

## Environment

**Statamic** 3.0.45 Pro
**Laravel** 8.28.1
**PHP** 7.4.12
**edalzell/blade-directives** 2.1.3
**jonassiewertsen/statamic-livewire** 2.4.0
**pattern/statamic-business-mode** 1.0
**rias/statamic-data-import** 1.1.1
**rias/statamic-redirect** 1.4.2
**spatie/statamic-responsive-images** 2.5.0
**xyzmedia/bulk-seo-updater** dev-main

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Thanks for reporting! However, this issue looks like it's basically the same as #3218, so I'm going to close this in favour of that other one.

**Comment by jamie-brown** [comment]
Ah ok, great stuff and apologies for the duplicate. 

I did try and search for anything related to sorting and reordering but it came up with unrelated issues. Glad it is in hand 👍🏻

**Comment by duncanmcclean** [comment]
It's fine dude, don't worry about it!
