### ISSUE TITLE
Site-wide protect exposes / when used with half-measure static caching

### ISSUE THREAD

**Issue by fspoettel** [statamic/cms#3336]
## Bug Description

There is a case where a site-wide protect setting can be circumvented for the `/` root page when `static_caching.stragegy: half` is used. The `/` page is exposed to everyone regardless of their login status once a logged-in user has visited it at least once, adding it to the cache. Protect continues to work fine for other routes in that case, only `/` seems to be affected.

I could not find in the docs whether these two features are supposed to work together.

## How to Reproduce

 1. Set `protect.default` to `logged_in`
 2. set `static_caching.strategy` to `half`
 3. visit `/` - it correctly redirects to the login page
 4. login with a user
 5. visit `/`
 6. log out or visit the page in an incognito tab
 7. :boom: `/` now renders for everyone regardless of their login status
 8. visiting any other page correctly redirects to the login

`php please cache:clear` restores correct functionality.

## Extra Detail

``` php
  # config/statamic/protect.php
  'default' => env('APP_ENV') == 'staging' ? 'logged_in' : null,
  'logged_in' => [
    'driver' => 'auth',
    'login_url' => '/cp',
    'append_redirect' => false,
  ],
```

``` php
    # config/statamic/static_caching.php
    'strategy' => env('APP_ENV') != 'local' ? 'half' : null,
```

## Environment

Statamic 3.0.45 Pro
Laravel 8.18.1
PHP 7.4.3
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
This certainly looks like something to do with the use of static caching, especially as it works initially, then after login, it'll just stay cached.

**Comment by jasonvarga** [comment]
You cannot use dynamic features like these when using static caching.

The page will be cached as it is for whoever hits it first.

See https://github.com/statamic/ideas/issues/190
