### ISSUE TITLE
Globals interfere with local variables 

### ISSUE THREAD

**Issue by codedge** [statamic/cms#3342]
## Bug Description

When using custom (form) variables/field, f. ex. in email templates, these interfere with globals.

* I have a form field `company`, that I want to insert into a custom html/text view for form notifications by using `{{ company }}`.
* I have a global variable `company`. These would be called `{{ company }}` inside an Antlers template.

In this situation, sending the email notification runs into an error, as it tries to access the global instead of the form field.

## How to Reproduce

* Create a global variable with `company` (or any other name)
* Create a form and name a fied `company`

Assign a custom html/text view to that template, and access the `{{ company }}`. Now fill out the form, a notification should be sent - but it does not.

The form submission is saved but the notification is not sent. An error is thrown in the  `laravel.log`.

## Environment

Statamic 3.0.46 Solo
Laravel 7.30.4
PHP 8.0.2
codedge/statamic-here-maps 0.1.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Can you share the exception/error that you're running into?

**Comment by codedge** [comment]
Cannot reproduce now. I had the issue some days ago and just prefixed the form field handles with `msg_`. 
Just tried with Statamic a completely fresh `3.0.46` and it does not produce any error, the email notification is sent. 

All good. I will get back if I encounter it again.
