### ISSUE TITLE
When assigning a license it refreshes the page and removes added domains (on statamic.com)

### ISSUE THREAD

**Issue by philipboomy** [statamic/cms#3343]
When assigning a license it refreshes the page and removes added domains so you have to type them in again or reverse the order and assign licences before adding domains.

See this to understand the issues: https://share.getcloudapp.com/Qwu9yByQ

**Comment by duncanmcclean** [comment]
Hey! 

Unfortunately, I'm going to have to close this issue as it doesn't follow the [issue template](https://github.com/statamic/cms/issues/new?assignees=&labels=&template=bug_report.md&title=) for bug reports. Using the template helps to keep all issues consistent and helps to make sure all issues provide enough information for maintainers to recreate your issue.

Would you mind creating a fresh issue with the template? Thanks 😄

**Comment by duncanmcclean** [comment]
I've closed this issue as it's not related to Statamic Core, rather the statamic.com site. Would you mind reporting this via support instead? Thanks
