### ISSUE TITLE
nav:breadcrumbs parameter url not working

### ISSUE THREAD

**Issue by kesse** [statamic/cms#3345]
## Bug Description
The tag nav:breadcrumbs have a parameter url according to the documentation, https://statamic.dev/tags/nav-breadcrumbs
But setting the property doesn't have any effect. 

## How to Reproduce

Create a page /about and /contact

Add the follow on the contact page
`
{{ nav:breadcrumbs url="/about" }}
  <a href="{{ url }}">{{ title }}</a>
{{ /nav:breadcrumbs }}
`

It should render `<a href="/about">About</a>` but it renders `<a href="/contact">Contact</a>`

## Environment

Statamic 3.0.45 Pro
Laravel 8.30.0
PHP 8.0.2
No addons installed

**Statamic version:** 3.0.45

**PHP version:** 8.0.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by berdjabrahamian** [comment]
@kesse Is there a reason you want Breadcrumbs to show a different url. This reads like a wrong use of the breadcrumbs tag.

Using your example

```
Contact Page
Breadcrumbs =  Home / About Us
```

```
About Us Page
Breadcrumbs = Home / Contact Us
``` 

Can you elaborate on what you are trying to achieve.

**Comment by jasonvarga** [comment]
I see that the documentation shows a url parameter - but it was mistakenly brought over from the v2 docs. It doesn't exist in v3.

I'm still not sure why you need the breadcrumbs tag. Can you show your full template example? It sounds like you should just be able to use {{ url }}.

**Comment by kesse** [comment]
Here is the template that I use.

```
<div class="row">
        {{ collection from="pages" limit="3"}}
        <div class="col-md-4">
            <a href="{{ url }}" class="breadcrumb">
                {{ nav:breadcrumbs include_home="false" :url="url" }}
                <span>{{ title }}</span>
                {{ /nav:breadcrumbs }}
            </a><br />

            <h4>{{ title }}</h4>
            <p>{{ ingress }}</p>
        </div>
        {{ /collection }}
    </div>
```

**Comment by jasonvarga** [comment]
What are you hoping those `<a>` tags to say?

**Comment by berdjabrahamian** [comment]
The way you have it, each of the 3 items will have its own breadcrumb trail. 

Do you want to show the breadcrumb trail for each of the collection items you are loading?
For example
```
about-us <- breadcrumb
ABOUT US <- title
About us page ingress info <- ingress

contact-us <- breadcrumb
CONTACT US <- title
Contact us page ingress info <- ingress

learn-more / why-choose-us <- breadcrumb
WHY CHOOSE US <- title
Why Choose Us page ingress info <- ingress

etc
etc

```
The code you provided will achieve this

However this appears to be the wrong use of the breadcrumbs tag
You can achieve the same thing as what I showed above using the {{url}} tag and a modifier


```
<div class="row">
   {{ collection from="pages" limit="3"}}
        <div class="col-md-4">
             <a href="{{url}}"> //This will link to the specific page, remove it if you dont want to link it to the page itself
                 <span>  {{url  | modifier to make it look like the above breadcrumb line item}} </span>
            </a>
            <h4>{{ title }}</h4>
            <p>{{ ingress }}</p>
        </div>
        {{ /collection }}
</div>
```

**Comment by kesse** [comment]
I agree.
I will create my own tag to solve this, saw that the url parameter is now removed from the docuemtentation.
