### ISSUE TITLE
Delete Action always showing in Addon

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#3350]
The core 'delete action' will always be visible and can't be hidden. The condition does work in core context and will only be visible if the multisite delete action is not needed. So far it seems working. 

# The issue
The `visibleTo` method can be true, even if it's not an instance of Entry. This is a problem if actions will be used differently, like with butik. 

<img width="1536" alt="Screenshot 2021-03-08 at 22 52 48" src="https://user-images.githubusercontent.com/38906163/110387185-8a92ed80-8061-11eb-9885-f074f8b85705.png">

https://github.com/statamic/cms/blob/3.0/src/Actions/Delete.php#L17-L24

In case it's not an instance of Entry and if the collections are exceeding one, it won't be displayed. Saying so, it will show up even if not an instance of Entry. That does not make sense.
```php
if ($item instanceof Entry && $item->collection()->sites()->count() > 1) {
    return false;
}

return true;
```

To work correctly in every context, it should work the other way around:
The action should only be visible, in case it is an Entry and if the sites are exactly 1. 
```php
return $item instanceof Entry && $item->collection()->sites()->count() === 1;
``` 

It will work as before, but with the difference that it will work correctly in addon context as well. 

Side note: As it seems, this is **not** related to the issue https://github.com/statamic/cms/issues/3174 as I thought before.

**Statamic version:** 3.0.46

**PHP version:** 8.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
I actually came across this the other day as well, can confirm, it's pretty annoying. It should probably only be visible to native Statamic things (entries, assets, etc)

**Comment by edalzell** [comment]
Thought I added something in the ideas repo for this, checking....

**Comment by edalzell** [comment]
Why would this NOT be visible if there are multiple sites?

**Comment by duncanmcclean** [comment]
> Why would this NOT be visible if there are multiple sites?

In an addon, I may want a delete action and maybe also run some other custom code during the delete process.
