### ISSUE TITLE
Stache store not filtering values when fetching items from files

### ISSUE THREAD

**Issue by simonworkhouse** [statamic/cms#3355]
## Bug Description

The function `Statamic\Stache\Stores\Store::getItemsFromFiles()` doesn't filter the fetched items and can fail with the error `Call to a member function id() on null` when calling `$this->getItemKey($item)`.

## How to Reproduce

This seems to occur if the content on the file system differs to what the Stache expects to exist. I _could_ generate a test scenario if absolutely required, but I think that reviewing the code would be sufficient enough to demonstrate the issue. 

## Environment

**Statamic version:** 3.0.43

**PHP version:** 7.4.9

**Install method:** Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Related to #2967 (same exception)
