### ISSUE TITLE
app locale not set correctly if using a custom controller

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#3361]
My Controller:
```php
use Statamic\View\View as StatamicView;

class ShopController extends WebController
{
    public function index()
    {
        return (new StatamicView())
            ->template('my.template')
            ->layout('my.layout');
```

If using the translate tag, it won't work correctly. 
`{{ trans key="my.key" }}`

![Screenshot 2021-03-09 at 22 56 18](https://user-images.githubusercontent.com/38906163/110544588-491b4480-812c-11eb-803e-0295bed475ec.png)

`{{ site:short_locale }}` will return the correct locale, but the app locale is not correct (as shown in the picture). 

In my case I am loading the default english version, but everything will be translated to german / de. To avoid this, I am setting the locale manually as shown in my workaround. 

## Workaround 
Set the locale manually in your controller.

```php
app()->setLocale(Site::current()->shortLocale());
```

## Environment

**Statamic version:** 3.0.43

**PHP version:** 7.4

**Comment by duncanmcclean** [comment]
As far as I'm aware, this is the intentional behaviour. Statamic will only set the current site for Statamic front-end requests, which a custom controller isn't one of (as you define it yourself). 

However, I'll let one of the team to verify.

**Comment by jasonvarga** [comment]
You can use the `Statamic\Http\Middleware\Localize` middleware on your route and it'll do it for you.

**Comment by jonassiewertsen** [comment]
I see. Thank for the quick response. 

What made me wonder is less that the locale has not been set, but that the site:short_locale is "just working", but on the other the translation tags do need extra information.
