### ISSUE TITLE
Can't create term on multisite installation other than default site

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#3364]
## Bug Description
Can't create term on multisite installation other than default site

## How to Reproduce
1. install Statamic
2. enable multisite
2. create taxonomy
3. create term in other than default site

## Extra Detail
Call to a member function all() on array {"userId":"95344886-887a-4bd2-b5da-cbca4345fb12","exception":"[object] (Error(code: 0): Call to a member function all() on array at /PATH_XYZ/vendor/statamic/cms/src/Taxonomies/Term.php:110)

## Environment
Statamic 3.0.45 Pro
Laravel 8.31.0
PHP 7.4.13

**Statamic version:** 3.0.45

**PHP version:** 7.4.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Confirmed. Seems to be something to do with this code on the `Term` class...

https://github.com/statamic/cms/blob/423a19edf6792e8cfe77e2da76875dbd969ae6dc/src/Taxonomies/Term.php#L110

`$array` seems to just be an array, so not sure why it's calling the `->all()` method on there. I tried to remove the `->all()` method but I ran into some Stache related issues (probably just something to do with my setup)

**Comment by jasonvarga** [comment]
How did you create the term in the non-default site in the first place?

**Comment by j3ll3yfi5h** [comment]
@jasonvarga

CP -> Taxonomies -> MyTaxonomy -> add Term

**Comment by jasonvarga** [comment]
That's in the default site though, isn't it?

**Comment by j3ll3yfi5h** [comment]
@jasonvarga no, tried it two different ways:
- used CP over second site domain
- used default domain and changed site over site switcher (top right)

**Comment by jasonvarga** [comment]
Ah yes, duh. I had not enabled the second site for the taxonomy I tried. Thanks for confirming.
