### ISSUE TITLE
[3.1] Bug - GraphQL Taxonomy Term query error: Blueprint null

### ISSUE THREAD

**Issue by sebszocinski** [statamic/cms#3371]
I have two different taxonomies and when trying to query them using GraphQL I get an error with one of them depending on which one had a blueprint saved most recently. Very strange.

This is the error I get when querying one of the two:
```
Argument 2 passed to Statamic\\GraphQL\\Types\\TermType::buildName() must be an instance of Statamic\\Fields\\Blueprint, null given, called in /***/vendor/statamic/cms/src/GraphQL/Types/TermInterface.php on line 57
```
But the other taxonomy works just fine... the error says an instance of a Blueprint is null... so I go and save that Blueprint and it starts working.... but then the OTHER taxonomy stops working again...

No idea what's going on here? I have all permissions enabled and i'm using the latest beta of 3.1 as of today.

**Comment by jasonvarga** [comment]
I can only get this error to happen if one of my terms has an invalid blueprint init.
Like, `blueprint: this_doesnt_exist`

Could you please check the terms, provide more details? 

You can run `php artisan tinker` and paste this in:

```
Statamic\Facades\Term::all()->mapWithKeys(function ($t) { return [$t->path() => optional($t->blueprint())->handle()]; })->reject();
```

It should show you which one has an invalid blueprint.

Also, please follow the issue template. 🙂

**Comment by sebszocinski** [comment]
Ok that's strange, I never edited the blueprints to begin with, I just created two Taxonomies and started adding some dummy terms... the only thing I can think of is I had GraphQL Cache enabled and perhaps something went wrong there... I've cleared cache now and went in and manually updated all the blueprint references and it's working now.

Thanks!

RE Issue Template - noted!
