### ISSUE TITLE
Radiobutton with boolean values not working

### ISSUE THREAD

**Issue by SchuBu** [statamic/cms#3372]
## Bug Description
If i add a boolean radio button with the option "cast booleans" activated and true/false as keys and "yes"/"no" as values i get an error in the frontend "array_key_exists(): The first argument should be either a string or an integer"

## How to Reproduce
add an boolean radio field and activate the "cast booleans" option
<img width="374" alt="2021-03-14_172455" src="https://user-images.githubusercontent.com/30638214/111075874-34eb9480-84ea-11eb-9a35-b02f5990558d.png">

## Environment
Statamic 3.0.46 Pro
Laravel 8.32.1
PHP 7.4.15
edalzell/blade-directives 2.1.5
jonassiewertsen/statamic-livewire 2.4.0
octoper/statamic-blade-components 0.0.1

**Statamic version:** 3.0.46
<img width="839" alt="2021-03-14_173744" src="https://user-images.githubusercontent.com/30638214/111076288-066eb900-84ec-11eb-8604-e69e9035e72c.png">

**PHP version:** 7.4

**Install method**
- Existing Laravel app

**Comment by duncanmcclean** [comment]
Can you share what the YAML of that radio field looks like in your blueprint?

**Comment by jackmcdade** [comment]
We haven't heard back on this one for a month so we'll be marking it as stale and closing it. If it pops up again and have more info you can share, we'll happily take another look!
