### ISSUE TITLE
Updater Widget, looks a bit weird at 50% width

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#3376]
## Bug Description

If you use the updater widget with a 50% width, it sometimes looks a bit weird as the addons are outside of the widget. It looks like it probably need's flex wrapped or something (not quite sure).

![image](https://user-images.githubusercontent.com/19637309/111201359-9844f780-85ba-11eb-94c0-b57e67cd3321.png)

## How to Reproduce

1. Add updater widget to `config/statamic/cp/.php`

```php
[
  'type' => 'updater',
  'width' => 50,
],
```

## Environment

Statamic 3.0.47 Pro
Laravel 8.31.0
PHP 8.0.2
doublethreedigital/duplicator 1.2.4
statamic/collaboration dev-master
statamic/ssg dev-master

**Comment by jackmcdade** [comment]
Fixed in 3b853881400fbed274973cc23ab889476bc0393b.

**Comment by duncanmcclean** [comment]
Noice!
