### ISSUE TITLE
New user activation redirect

### ISSUE THREAD

**Issue by byron-roots** [statamic/cms#3388]
## Bug Description
When creating a new user through the CP, the activation email link is missing the redirect back to the CP. So after a new user activates an account they get sent to the homepage, instead of the control panel.

## How to Reproduce
Create a new user through the CP, both email and the generated link you can copy are missing the redirect parameter.

## Extra Detail
![Screenshot 2021-03-17 at 12 19 50](https://user-images.githubusercontent.com/38127763/111466372-1c15f580-871b-11eb-8221-a7f65c1d8600.png)

**Statamic version:** 3.0.*

**PHP version:** 7.32

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Can you make sure that you're not logged in when you test that URL?

**Comment by byron-roots** [comment]
The URL works fine, but after setting a password and activating the account I get sent to https://crazemgmt.local instead of https://crazemgmt.local/cp.

When using the reset password option the link has ?redirect=https://crazemgmt.local/cp added to it.

**Comment by duncanmcclean** [comment]
I can confirm, the `redirect` query parameter should probably be added to the URL if the user was created through the CP.

**Comment by jesseleite** [comment]
Should be fixed in next 3.1 release, thanks!
