### ISSUE TITLE
[3.1] White labelling error when using multiple logo's and env variables

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3394]
## Bug Description
When using multiple custom logo URL's this doesn't work:

```php
'custom_logo_url' => [
    'nav' => env('STATAMIC_CUSTOM_LOGO_NAV_URL', null),
    'outside' => env('STATAMIC_CUSTOM_LOGO_OUTSIDE_URL', null)
]
```

Gives an error:

```
ErrorException
htmlspecialchars() expects parameter 1 to be string, array given (View: /Users/robdekort/Sites/anne-meithe/vendor/statamic/cms/resources/views/partials/global-header.blade.php)
```

It wil work when you set the logo's to empty strings, but then the CP doesn't fallback to the default logo's. 

<img width="237" alt="Screenshot 2021-03-18 at 15 55 04" src="https://user-images.githubusercontent.com/69107412/111646933-5c9c6e80-8802-11eb-86ab-6624ec84fdde.png">

## How to Reproduce

Try to use `.env` variables for setting the `nav` and `outside` logo in `config/statamic/cp.php` like above. 

## Extra Detail
<img width="1216" alt="Screenshot 2021-03-18 at 15 52 11" src="https://user-images.githubusercontent.com/69107412/111646410-e992f800-8801-11eb-8dc1-5e36eb1d0061.png">

## Environment
Statamic 3.1.0-beta.1 Pro
Laravel 8.33.1
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by duncanmcclean** [comment]
If you run `php artisan tinker` and enter `config('statamic.cp.custom_logo_url')`, what's returned?

**Comment by robdekort** [comment]
This is what's returned when it's set to `null`. Then I get the above error. <img width="475" alt="Screenshot 2021-03-19 at 19 47 56" src="https://user-images.githubusercontent.com/69107412/111828720-0146ab00-88ec-11eb-8db9-2d1b6348f559.png">

When I set the env to nothing I don't get the error, but here's no logo in the CP nav bar. Then it returns this.

<img width="469" alt="Screenshot 2021-03-19 at 19 49 16" src="https://user-images.githubusercontent.com/69107412/111828849-30f5b300-88ec-11eb-9682-8bd48d472ac4.png">
 
So with the current options it seems you can't keep the default Statamic logo in the nav bar.

**Comment by robdekort** [comment]
I just noticed this on another site which might be relevant:
![Uploading Screenshot 2021-03-22 at 15.32.28.png…]()

**Comment by jasonvarga** [comment]
On that site, have you published the views? Do you have a login.blade.php?

**Comment by robdekort** [comment]
Yep, that was it indeed. I just wanted to remove my comment. Hahaha. And it seems you fixed the initial issue already. Awesome!
