### ISSUE TITLE
When you add a new entry in Safari/Firefox, the title field isn't focused

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3396]
## Bug Description
When you add a new entry in Safari the title field get's a visual focus, however the field doesn't have actual focus, the cursor is not in it.

It's seems to get focus for a brief period on loading.

This works as expected in Chrome.

## How to reproduce
Add a new entry in Safari/Firefox and watch the title field. Type when the page is loaded and be annoyed.

## Extra Detail
<img width="1152" alt="Screenshot 2021-03-18 at 17 01 27" src="https://user-images.githubusercontent.com/69107412/111657818-151ae000-880c-11eb-9e88-a4c5c4f2dc9c.png">

## Environment
Statamic 3.0.47 Pro
Laravel 8.32.1
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by sjclark** [comment]
I tried to replicate this, but was unable to reproduce the second step `"Type when the page is loaded and be annoyed."` - upon typing I was instead mildly inconvenienced, and slightly hungry. Probably needs more investigation.

**Comment by robdekort** [comment]
Oh yeah. Slightly inconvenienced is definitely a better way to put it!

**Comment by duncanmcclean** [comment]
I don't have Firefox but I tried in Safari and the title field is focused like it should be. I'm using Safari 'Version 14.0.3 (16610.4.3.1.4)', in case that makes any difference.

**Comment by robdekort** [comment]
I run the same version. This is what happens, visual focus, but no actual cursor focus:

![Uploading Screen Recording 2021-03-19 at 19.42.22.gifcask.2021-03-19 19_44_42.gif…]()

**Comment by duncanmcclean** [comment]
Ah gotcha, I see what you mean now. The flicking cursor thing isn't flicking on the create entry page 👍

**Comment by robdekort** [comment]
You got it. No flicking cursor thingy.
