### ISSUE TITLE
errors variable in `form:create` tag are not localized

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#3400]
## Bug Description
When using the `errors` variable inside `{{ form:create }}` to show the validation errors after a form submit, I only get English text. The whole websites uses German (de_DE). I also tested adding `{{ value | trans }}` inside `{{ errors }}{{ /errors }}` without success.

## Environment
Statamic 3.0.40 Solo
Laravel 8.21.0
PHP 7.4.11

**Comment by jasonvarga** [comment]
Make sure you have a `resources/lang/de_CH/validation.php` file. You can grab one from here: https://github.com/Laravel-Lang/lang/blob/master/src/de_CH/validation.php

Since it's the front-end, it doesn't use Statamic's custom validation language files.

**Comment by felixstoessel** [comment]
Okay. Just to clarify and maybe as an idea for the docs:
Everything that is displayed in the frontend must be used translated manually.
Everything that is displayed in the backend is batteries-included and already translated by Statamic?

**Comment by duncanmcclean** [comment]
Related to statamic/docs#396
