### ISSUE TITLE
Grid columns for toggles too wide, leaving little space for other fields

### ISSUE THREAD

**Issue by arthurperton** [statamic/cms#3402]
## Bug Description

Minor issue. When you create a grid, all columns have the same width. For toggles (and other small, fixed width fieldtypes) the column often ends up way wider than necessary, which leaves a lot of horizontal whitespace. Sometimes it looks a bit funny and, more importantly, you'd like to use that space for other fields.

## Extra Detail
<img width="869" alt="Screenshot 2021-03-19 at 15 58 20" src="https://user-images.githubusercontent.com/4067531/111800896-b23d4d80-88cc-11eb-8d90-e1de1cbde121.png">

## Environment

Statamic 3.0.47
Laravel 8.33.1
PHP 7.4.16

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
I'm not sure this is necessarily a bug but more of a 'ux tweak' that could be made to make the CP that little bit nicer.

**Comment by arthurperton** [comment]
I agree. It is a ‘nice to have’. I have an idea for a PR; gonna try to get it in next week.

**Comment by arthurperton** [comment]
If this is not the right place, feel free to close it or move it to ideas or anything.

**Comment by duncanmcclean** [comment]
I think here is fine. I don't have permission to move things to different repos anyway 😄
