### ISSUE TITLE
Can't enable/disable Stache file watcher per environment

### ISSUE THREAD

**Issue by arthurperton** [statamic/cms#3403]
## Bug Description

There is no environment variable to enable or disable the file watcher for the Stache. Sometimes you do want a different setting for it per environment.

## Extra Detail
See the `'watcher'` setting in `statamic/config/stache.php`.

## Environment

Statamic 3.0.47
Laravel 8.33.1
PHP 7.4.16

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
You can just make your own. It doesn't need to exist in the bundled config file.

But, this is something that we suggest changing often so yeah it should be there. 👍
