### ISSUE TITLE
Multisite doesn't save emptied / blank fields or assets on translations and instead returns the original.

### ISSUE THREAD

**Issue by tao** [statamic/cms#3406]
## Bug Description

If you have translations with fields that can be empty on non-english translations, then it doesn't save the empty field.

For example, lets say we have translator names and a PDF in the blueprint:

```
ENGLISH
title: 'My title'
translator: 'Username'
pdf: '/assets/my-english-document.pdf'
---
content...
```

Let's make a Spanish translation of the file:

```
SPANISH
title: 'Mi título`
---
content...
```

The `translator` and `pdf` fields are still returning the parent English fields as we haven't changed them yet.

Now, on the Control Panel if you edit the field `translator` setting it to empty and delete the `pdf` asset, then it doesn't remove them.

```
SPANISH
title: 'Mi título`
---
content...
```

The fields from the parent English file are still returned because it should be saving them as blank fields:

```
SPANISH
title: 'Mi título`
translator: false
pdf: false
---
content...
```

These should instead be saved as either as false, null or empty strings so that it doesn't return the English values anymore.

## Environment

Statamic 3.1.0-beta.1 Pro
Laravel 8.33.1
PHP 8.0.3

**Comment by tobinski** [comment]
I can confirm this issue.
