### ISSUE TITLE
Vimeo video prevents browsing assets and publishing pages in Safari

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#3417]
## Bug Description

I've a replicator field with a set where an external video can be added. When I add a Vimeo URL (example: https://vimeo.com/473880102), then save the page everything goes well. But after that I cannot publish any other changes, also clicking on the 'Browse' button for images does nothing.

**I only get this in Safari 14.0.3 (didn't test other Safari versions). In Chrome there's no problem.**

What I did:
- Add Vimeo URL in video type field
- Save changes / publish page
- Refresh page 
- Made some other changes
- Click 'Publish' (nothing happens) or try to upload field by clicking on 'Browse' and also nothing happens.

I also get the following javascript error:
`ResizeObserver loop completed with undelivered notifications`

## Extra Detail

![image](https://user-images.githubusercontent.com/11161180/112329786-c790ee00-8cb7-11eb-9d45-297daa4bc5d4.png)

![image](https://user-images.githubusercontent.com/11161180/112329814-cd86cf00-8cb7-11eb-8efd-d170e94759bf.png)

## Environment

**Statamic version:** 3.0.48

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Hmm, I seem to be unable to reproduce. i added a video field to my blueprint, created a new entry with a vimeo video, saved it, opened the entry back up, made changes and saved again and it worked as I'd expect. 

Would you mind sharing your blueprint, in case it's a combination of the video field and something else that's causing the issue? Also, which version of Safari are you using?

Thanks

**Comment by jackmcdade** [comment]
This issue has not had recent activity and I'm going to mark it as stale. Feel free to reply with more info in the future and we'll take another look!
