### ISSUE TITLE
Nav tag doesn't show all items since 3.1

### ISSUE THREAD

**Issue by JoeriE** [statamic/cms#3419]
## Bug Description
I've updated my site to v3.1 and since then the nav tag behaves strangely. It shows different items for all pages. I didn't change anything to my code and the new trees file seems to be correct.

**Code:**
```
<div class="nav__list">

    {{ nav:spaces }}
        <div class="nav__item {{ if is_current || is_parent }}is-active{{ /if }}">
            <a href="{{ url }}" class="nav__link h1 md:text-md md:font-sans">
                {{ title }}
            </a>
        </div>
    {{ /nav:spaces }}

</div>
```

**Trees file: content/trees/navigation/spaces.yaml**
```tree:
  -
    entry: e25de0c0-9585-4ef2-9ffc-de19889328c4
  -
    entry: b245d206-f7ff-4b91-8a76-af3febbe402d
  -
    entry: 2f06cfb7-e236-4f1c-8030-f910b29e9d31
  -
    entry: 12407f94-781f-49d7-a38e-78b3c9ed3955
  -
    entry: 0e828f9d-a3cb-4b5a-921f-c03fe1f0c9b0
  -
    entry: d7902869-fde7-48bf-b280-24a751793556
  -
    entry: 371af6cb-e3fb-43f7-a74b-5232660c9f4c
```

## Extra Detail
Projects page:

![image](https://user-images.githubusercontent.com/11161180/112370914-44cf5980-8cde-11eb-84ac-7a9e44856f9b.png)

Stories page:

![image](https://user-images.githubusercontent.com/11161180/112370955-4f89ee80-8cde-11eb-8bb7-8dbceb5fbbc0.png)

Admin view:

![image](https://user-images.githubusercontent.com/11161180/112370971-53b60c00-8cde-11eb-8fe9-db2dbf075d92.png)

## Environment

**Statamic version:** 3.1.0

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic` - Update from 3.0.48

**Comment by jasonvarga** [comment]
Can you show what you think it _should_ look like?

**Comment by JoeriE** [comment]
@jasonvarga 
The second screenshot (stories page) shows the nav how it should look like with all the items rendered. The first screenshot is how it shows on most of the pages. There only two of the seven items that are in the navigation are rendered. Sometimes only one item is rendered.

**Comment by jasonvarga** [comment]
Are any of those pages drafts?

**Comment by JoeriE** [comment]
@jasonvarga  No these are all published pages

**Comment by jasonvarga** [comment]
Are you using static caching?

I'm a bit stumped. Would you be able to zip up your site and send it to support@statamic.com ?

**Comment by JoeriE** [comment]
@jasonvarga I've send you and email with the website!
