### ISSUE TITLE
Links in the updater changelog are styled the same as text

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#3423]
## Bug Description

Only when you (accidentally) hover them you can see they're links (I hovered over the upgrade guide)

![image](https://user-images.githubusercontent.com/3626559/112440423-97def600-8d4a-11eb-99ce-0a48f32523b4.png)

**Comment by jasonvarga** [comment]
Thanks! Obviously I can't fix the color for older installations, so I've made those links bold in the actual changelog.
If you clear your cache and view the updater again, they should at least be more noticeable. Just not blue.
