### ISSUE TITLE
Can't delete entries in 3.1

### ISSUE THREAD

**Issue by delz-dev** [statamic/cms#3424]
## Bug Description

I'm unable to delete entries in a collection.

## How to Reproduce

1. Create a collection
2. Create an entry
3. Try to delete it …

## Extra Detail

![image](https://user-images.githubusercontent.com/54885840/112440581-ca88ee80-8d4a-11eb-95b2-941338774ab2.png)

## Environment

Big Sur, PHP 7.3

**Statamic version:** 3.1.0

**PHP version:** 7.3

**Install method (choose one):**
- Updated from 3.*

**Comment by duncanmcclean** [comment]
Will be fixed in next release. #3420 fdc5ff0
