### ISSUE TITLE
Illegal offset type when visiting /cp/auth when already logged in

### ISSUE THREAD

**Issue by benaja** [statamic/cms#3425]
## Bug Description
When you are logged in to your statamic cms and go to the route /cp/auth it produces an server error.

I know it's kind of an edge case. But it appeared on one of our production environments, because CMS users accessed this url somehow. 

## How to Reproduce
- New or existing Statamic project
- Login as any user
- After successful login to to the route /cp/auth
- It displays an server error

## Extra Detail
Error message:
Illegal offset type (View: /vendor/statamic/cms/resources/views/partials/scripts.blade.php)

## Environment
**Statamic version:** 3.1.0 Solo
**PHP version:** 8.0.3
**Laravel Version:** 8.34.0
**Install method:** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Funky bug. Nice.
