### ISSUE TITLE
Unit tests complaints about missing pre-update-cmd

### ISSUE THREAD

**Issue by codedge** [statamic/cms#3427]
## Bug Description

Since Statamic 3.1 and the introduction of the Update Scripts (good thing!) the HTTP tests that I run complain about missing 
`pre-update-cmd` scripts section.

```php
/** @test */
public function can_see_magic_link_link(): void
{
        $this->get(cp_route('login'))
             ->assertSee('Send Magic Link')
             ->assertOk();
}
```

When debugging this I found this is raised in the [`CheckComposerJsonScripts`](https://github.com/statamic/cms/blob/3.1/src/Http/Middleware/CheckComposerJsonScripts.php#L18) middleware and checking if the proper `scripts` section is present. Unfortunately [this](https://github.com/statamic/cms/blob/3.1/src/Console/Composer/Json.php#L12) is checking the `composer.json` of `orchestra/testbench` which I use.

`base_path('composer.json')` results in `"/Users/holger/code/statamic-magiclink/vendor/orchestra/testbench-core/laravel/composer.json`.

Shouldn't this only check the `composer.json` of the package it belongs to? 

## How to Reproduce

See the [repository](https://github.com/codedge/statamic-magiclink) of my Statamic Addon.

## Environment

**Statamic version:** 3.1
**PHP version:** 8.0.1

**Install method (choose one):**
- Statamic Addon, no complete installation

**Comment by jasonvarga** [comment]
We should probably disable that thing in tests 👍
