### ISSUE TITLE
Undefined method initialPath with Statamic 3.1 when configured to use eloquent users

### ISSUE THREAD

**Issue by jackwakefield** [statamic/cms#3431]
## Bug Description

I updated an existing Statamic 3.0 project to 3.1 and received the following error when running `php please stache:clear`

```
  Call to undefined method Statamic\Auth\Eloquent\User::initialPath()

  at vendor/statamic/cms/src/Stache/Stores/UsersStore.php:40
     36▕         }
     37▕ 
     38▕         $user = User::make()
     39▕             ->id($id)
  ➜  40▕             ->initialPath($path)
     41▕             ->email(pathinfo($path, PATHINFO_FILENAME))
     42▕             ->preferences(array_pull($data, 'preferences', []))
     43▕             ->data($data);
     44▕ 

      +23 vendor frames 
  24  please:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

## How to Reproduce

Configure a Statamic 3.1 project to use the `eloquent` repository in `config/statamic/users.php` and run `php please stache:clear`

## Environment

Statamic 3.1.0 Pro
Laravel 8.34.0
PHP 8.0.3
withcandour/aardvark-seo 2.0.10
withcandour/statamic-blog-helpers 0.1.2
withcandour/statamic-imgix 0.1.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Do you still have user yaml files?

**Comment by jackwakefield** [comment]
I do indeed, I removed those and the error's gone.

**Comment by jasonvarga** [comment]
Beauty 👍
