### ISSUE TITLE
Adding Users in CP fails at last step with Error "Route [statamic.account.activate] not defined..."

### ISSUE THREAD

**Issue by olivererdmann** [statamic/cms#3433]
## Bug Description

When creating a user from Control Panel, filling out all fields, the last step always fails with error "Route [statamic.account.activate] not defined..."
The users-yaml still is created, but there's no way to activate it.

## How to Reproduce

* In CP, go to Users 
* Click "Create User" button
* fill out all steps
* in the last step, click either "Create User" or "Create and Send Email", both action fail

## Environment

Statamic 3.1.1 Pro
Laravel 8.34.0
PHP 7.4.9
No addons installed

**Install method (choose one):**
- install from `statamic/statamic` with Statamic Peak

**Comment by jasonvarga** [comment]
I can't recreate this. Are there any other details about your site that you can provide?
Any user customization? Using custom guards?

**Comment by olivererdmann** [comment]
We're using mainly the adjustments from https://github.com/studio1902/statamic-peak along with custom fieldsets.
There's also multisite enabled with 4 different locales and GraphQL is active for all resources and queries. 
I get the same error locally running on Docker and in production on AWS.

**Comment by jasonvarga** [comment]
Can you run `php artisan tinker` and put in `route('statamic.account.activate', 'foo')`? What does it say?

What about `php artisan route:list -c` ?

**Comment by olivererdmann** [comment]
Hi Jason, i've been digging through the config and think i figured it out.
Somehow the `config/statamic/routes.php` had `'enabled' => false` set. After enabling it, all runs well. 
Thanks for your awesome support!

**Comment by jasonvarga** [comment]
Thanks for following up!
