### ISSUE TITLE
Markdown modifier cannot be applied to code fieldtype

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#3437]
## Bug Description
After updating from 3.0.46 to 3.1.1 I noticed a change in how a page was rendered. I've used the markdown modifier to parse a string, and it's no longer happening.

## How to Reproduce
Create a blueprint with a **code** fieldtype. Try to render this in a template with the markdown modifier.

## Extra Detail
![fieldset](https://user-images.githubusercontent.com/1135679/112767114-25ee0180-9015-11eb-90d3-9928a7957c80.png)
![result](https://user-images.githubusercontent.com/1135679/112767117-271f2e80-9015-11eb-8f7c-62d5e3a3042b.png)
![code](https://user-images.githubusercontent.com/1135679/112767118-27b7c500-9015-11eb-9b19-3d75b16b3043.png)
![content](https://user-images.githubusercontent.com/1135679/112767119-27b7c500-9015-11eb-9191-3baf9d16c74d.png)

## Environment
Statamic 3.1.1 Pro
Laravel 8.26.1
PHP 7.3.12
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Code fieldtype would be what's doing it! We made some changes there. I would still expect this to work though.

You know we have a `markdown` fieldtype, right? If you use that you don't need to use the markdown modifier on the front end at all. You could use that as a workaround for now. Or even just change it to a `textarea` fieldtype if you don't want to make any template changes.

**Comment by espenlg** [comment]
For this use the Markdown fieldtype was a bit overwhelming as I wanted to keep to the interface as simple as possible (like without buttons and cheatsheet link). But textarea works fine 👍  Keeping the handle and just changing the fieldtype worked like a charm. Not sure why I ended up with Code fieldtype in the first place. Maybe the fixed font triggered something in me 😆
