### ISSUE TITLE
Not able to move text input cursor in Bard field

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#3438]
## Bug Description
After inserting a piece of text in a Bard field and then try to move the input cursor down by using the down-arrow on the keyboard the cursors stops at the first forced word-break.

## How to Reproduce
Paste in a text. Set the cursor at the first character and then press arrow down until you get to the line where a forced word-break occures.
If moving the cursor one step to the left or right it works fine, but still confusing.

## Extra Detail
https://user-images.githubusercontent.com/1135679/112770687-3065c680-9028-11eb-934a-5e4b06e81849.mov
(Example shows me trying to move the cursors a few times)

## Environment
Statamic 3.1.1 Pro
Laravel 8.26.1
PHP 7.3.12
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by arthurperton** [comment]
I looked into this one, and it is not an issue with Statamic or Bard. It is a Chrome issue with any `contenteditable="true"` element that has `hyphens: auto;`. You won't see this issue when you use Safari for example.

**Comment by espenlg** [comment]
I wouldn't mind getting rid of the `hyphens: auto;` but I guess that's a different request :)

**Comment by arthurperton** [comment]
Let's give it a try.
