### ISSUE TITLE
Taxonomy term selector shows no alternatives before typing in some letters

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#3439]
## Bug Description
I have a taxonomy term selector connected to a taxonomy. When using this, trying to edit a page it does not show any alternatives before I've manually entered some input.

## How to Reproduce
Create a taxonomy, then create a taxonomy term input field in a blueprint, and try to edit the page where it's in use.

## Extra Detail
https://user-images.githubusercontent.com/1135679/112770869-12e52c80-9029-11eb-8552-d8a2e660898b.mov
![Screenshot 2021-03-29 at 00 50 44](https://user-images.githubusercontent.com/1135679/112770871-15e01d00-9029-11eb-9e96-3a7bd19f0cad.png)

## Environment
Statamic 3.1.1 Pro
Laravel 8.26.1
PHP 7.3.12
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by espenlg** [comment]
Maybe it's the way a "Typeahead Field" should work, but I find it confusing it's working different before/after adding a taxonomy so I wanted to address this just in case.

**Comment by jasonvarga** [comment]
That's how the typeahead field works. You gotta type something. It's a good option if you'll have a huge number of options and want to avoid loading them all up front.

You can use the 'select dropdown' option. It'll show all the options by default, and let you type to filter them.

**Comment by espenlg** [comment]
Aha, so starting to type triggers the load at the same time. Then it's closer to understandable :) Thank you!
