### ISSUE TITLE
Date doesn't update for Multisite Entries.

### ISSUE THREAD

**Issue by dagy304** [statamic/cms#3440]
## Bug Description
If i update a Date Field (generated with "Enable Publish Dates") for an Entry in my Collection, the Date field in the Entries of the other Languages doesn't update.
## How to Reproduce
Create Entry for Collection with "Enable Publish Dates" active.
Change the Date fot the Created Entry.
Edit other Multisite locale for the Entry and the Date field is still the old Date.

## Extra Detail
New Entry for Site "Statamic"
![Create Entry ‹ Test ‹ Collections ‹ Statamic 1](https://user-images.githubusercontent.com/22611881/112838016-e3700780-909c-11eb-822f-d4ea651fb2b0.jpg)
Entry Translation for Site "two"
![Test ‹ Collections ‹ Statamic 2](https://user-images.githubusercontent.com/22611881/112838278-2d58ed80-909d-11eb-901f-a8d04cdd3ee3.jpg)
Changed Date Field for Site "Statamic"
![Test ‹ Collections ‹ Statamic 3](https://user-images.githubusercontent.com/22611881/112838284-2f22b100-909d-11eb-960d-203c57e515c1.jpg)
Date Field not updated for Site "two"
![Test ‹ Collections ‹ Statamic 4](https://user-images.githubusercontent.com/22611881/112838291-3053de00-909d-11eb-8df8-a54fd9a54287.png)

## Environment

**Statamic version:** 3.0.48

**PHP version:** 7.4

**Install method (choose one):**
- Existing Laravel app
- Also tried on fresh installation with `statamic/statamic`

**Comment by duncanmcclean** [comment]
What does that date field look like in your blueprint? Is it localised?

**Comment by dagy304** [comment]
Yes, this is how my test blueprint looks like:

    title: test
    sections:
      main:
        display: Main
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              type: markdown
              localizable: true
      sidebar:
        display: Sidebar
        fields:
          -
            handle: slug
            field:
              type: slug
              required: true
              localizable: true
              validate:
                - required
          -
            handle: date
            field:
              type: date
              required: true
              localizable: true
              validate:
                - required

**Comment by robdekort** [comment]
Just ran into this. Confirmed!

**Comment by j3ll3yfi5h** [comment]
Just ran into this too... 😕

**Comment by dryven-daniel** [comment]
Having the same issue

**Comment by chopperoon** [comment]
I'm also having the same issue on two current projects. Is there any current workaround, or even a possible fix on the horizon?
