### ISSUE TITLE
Statamic 3.0.46: {{ honeypot }} doesn't output it's name

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#3449]
## Bug Description
I used the honeypot variable in my form template: previous the update it worked like this, now it is empty.

## How to Reproduce
Use {{ honeypot }} in your template and switch between 3.0.* and 3.1.*.

## Environment
Statamic 3.1.2 Pro
Laravel 8.35.0
PHP 7.4.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Workaround is to hardcode it.

**Comment by j3ll3yfi5h** [comment]
@jasonvarga I did, but I had to do it on 10 sites... 🙄  And it is less dynamic now, so I hope you will fix this soon.🙏🏻

**Comment by jasonvarga** [comment]
Can you show your template code for how you were getting the form and honeypot?

**Comment by j3ll3yfi5h** [comment]
```
{{ form:create in="{ c_form:handle }" class="m-form" id="form-{ index }" redirect="{ current_uri }#form-{ index }" }}

	{{# ERFOLG #}}
	{{ if success }}

		{{ success_txt ?? success|wrap:strong }}

	{{ else }}

		{{# FEHLER #}}
		{{# if errors }}
			<p>
			{{ errors }}
				<strong>{{ value }}</strong><br>
			{{ /errors }}
			</p>
		{{ /if #}}

		{{# FELDER #}}
		{{ fields }}
			<label for="{{ handle }}">{{ display }}{{ instructions|wrap:span.m-fieldinstructions }}</label>
			{{ field }}<br>
			{{ if index == 1 }}
			<label for="{{ honeypot }}" data-hp>{{ honeypot|ucfirst }}</label>
			<input type="url" name="{{ honeypot }}" id="{{ honeypot }}" data-hp><br data-hp>
			{{ /if }}
		{{ /fields }}

		<button>{{ if submit_txt }}{{ submit_txt }}{{ else }}Absenden{{ /if }}</button>

	{{ /if }}

{{ /form:create }}
```

**Comment by jasonvarga** [comment]
`{{ honeypot }}` doesn't output anything there for me on 3.0.49.

Are you doing anything else in that template?

**Comment by j3ll3yfi5h** [comment]
I updated from 3.0.45 to 3.1.1, maybe it broke earlier then?

**Comment by jasonvarga** [comment]
Can you confirm that `{{ honeypot }}` was actually outputting anything on 3.0.45?

You should be able to see the `label` and `input`, but the `name=""` might have been empty.

We can't reproduce that it ever output anything.

**Comment by j3ll3yfi5h** [comment]
@jasonvarga

just found out, that it already broke from 3.0.45 to 3.0.46

**Comment by jasonvarga** [comment]
It didn't work on 3.0.45 either though.

Are you sure there's nothing outside of your `{{ form:create }}` tags? Like `c_form` somewhere?

**Comment by j3ll3yfi5h** [comment]
but I can switch between 3.0.45, were it outputs the honeypot, to 3.0.46, were it doesn't. Doesn't make any sense.
![Bildschirmfoto 2021-04-01 um 17 08 04](https://user-images.githubusercontent.com/6337411/113314758-ec671000-930c-11eb-9a0b-360a9b3e5561.png)
![Bildschirmfoto 2021-04-01 um 17 08 32](https://user-images.githubusercontent.com/6337411/113314765-ecffa680-930c-11eb-970d-20d6fba9f504.png)

**Comment by jasonvarga** [comment]
Thanks. Can you please paste the whole template and layout files.

**Comment by jasonvarga** [comment]
We spoke in discord. The missing piece was that `{{ c_form }} ... {{ /c_form }}` was wrapping around the entire template.
