### ISSUE TITLE
Extending Statamic User model

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/cms#3455]
I want to extend the default user model without having to use eloquent or database, for example to override the notifications methods to take a different approach to password reset notifications.

On discord @jasonvarga suggested it can be done if you:

```
- make a custom User class. you can extend Statamic\Auth\File\User
- make a custom user repository. you can extend Statamic\Stache\Repositories\UserRepository
- override the make method so that it returns your User.
- In a service provider, add this:

(new \Statamic\Auth\UserRepositoryManager)->extend('stache', function () {
  return new YourCustomRepository;
});

```

This feels like quite a few steps, and it would be nice if it was simpler to do - ideally only one model and one change to service provider.

**Comment by ryanmitchell** [comment]
Yep sorry, the issue template didnt really follow the flow. 
Jason suggested I open an issue so he cna see if it can be simplified.

**Comment by duncanmcclean** [comment]
Also, sorry if that last reply came across negatively, didn't mean for it to. 😃

**Comment by edalzell** [comment]
Might also be possible if the base data class is macroable

**Comment by jasonvarga** [comment]
Macroable adds methods, it doesn't change existing ones.

**Comment by ryanmitchell** [comment]
It would be lovely if `config/auth.php -- /providers/users` allowed an optional 'model' key, which `Statamic\Stache\Repositories\UserRepository::make()` checked for and if present used, or defaulted back to `FileUser`. That would allow you extend FileUser and change methods.

**Comment by jasonvarga** [comment]
I'll use the same method outlined in https://statamic.dev/extending/repositories#custom-data-classes

**Comment by ryanmitchell** [comment]
Oh thats great, I hadn't come across that doc yet. Thank you.

**Comment by ryanmitchell** [comment]
Closing at this seems to be fixed in 3.2 by https://github.com/statamic/cms/pull/4243

**Comment by jasonvarga** [comment]
Oh thanks for following up. Missed this issue!

**Comment by ryanmitchell** [comment]
No problem - do you plan to document this?
