### ISSUE TITLE
Minor Toggle UI Issue.

### ISSUE THREAD

**Issue by johncarter-** [statamic/cms#3456]
## Bug Description
When you have a toggle with instructions in the sidebar there is an alignment issue that make the UI look wonky.

## How to Reproduce
Put toggle fieldtype with instructions in the sidebar of a blueprint.

## Extra Detail
![image](https://user-images.githubusercontent.com/3776888/113175406-4b605280-9243-11eb-8396-d000df5ddb28.png)

## Environment

Statamic 3.1.0 Pro
Laravel 8.34.0
PHP 8.0.1
spatie/statamic-responsive-images 2.5.3

**Comment by duncanmcclean** [comment]
I've also come across this recently, can confirm.
