### ISSUE TITLE
Changing cp_route to '' breaks image upload

### ISSUE THREAD

**Issue by RobbertUpgraders** [statamic/cms#3458]
## Bug Description
When changing the cp_route variable in cp.php in config/statamic. It breaks the image upload. When uploading an image to the root directory, the page and image work fine. But when uploading an image to a folder, the image only shows up after a refresh and this also does not happen every time. Sometimes the image does not show up at all. 

(not sure if related but going to mention it anyway), it also seems that the delete function / popup seems to break aswell. When deleting an image, the delete popup pops up like usual but after clicking delete, the page behind the popup reloads but the popup and the image are still visible. 

## How to Reproduce
Set cp_route config to '' and upload an image in both root directory and folder. 

## Extra Detail

I have video's on this error which I cannot add here. Hit me up on discord Robbert#3398 and I can send you anything you need!

## Environment

Statamic 3.1.2 Pro
Laravel 8.34.0
PHP 7.3.27
No addons installed

**Install method (choose one):**
Fresh install with only minor config tweaks.

**Comment by duncanmcclean** [comment]
Why are you changing the `cp_route` to an empty string? Are you running headless?

**Comment by RobbertUpgraders** [comment]
> Why are you changing the `cp_route` to an empty string? Are you running headless and don't need a front-end?

Yes, I am running headless. I am currently using a .htaccess to redirect to /cp but this is really unreliable. So changing the cp_route to the root, it skips that whole step.

**Comment by duncanmcclean** [comment]
> > Why are you changing the `cp_route` to an empty string? Are you running headless and don't need a front-end?
> 
> Yes, I am running headless. I am currently using a .htaccess to redirect to /cp but this is really unreliable. So changing the cp_route to the root, it skips that whole step.

Cool, make sense. As a workaround for now, try adding something like this to your `routes/web.php` which will redirect any non `/cp` URL to the CP dashboard.

```
Route::redirect('/{any}', '/cp/dashboard')->where('segments', '^(?!cp).*$');

```

**Comment by RobbertUpgraders** [comment]
> > > Why are you changing the `cp_route` to an empty string? Are you running headless and don't need a front-end?
> > 
> > 
> > Yes, I am running headless. I am currently using a .htaccess to redirect to /cp but this is really unreliable. So changing the cp_route to the root, it skips that whole step.
> 
> Cool, make sense. As a workaround for now, try adding something like this to your `routes/web.php` which will redirect any non `/cp` URL to the CP dashboard.
> 
> ```
> Route::redirect('/{any}', '/cp/dashboard')->where('segments', '^(?!cp).*$');
> ```

Ill check that out this weekend, got a day off tomorrow :-) ! Thanks for the tip!

**Comment by duncanmcclean** [comment]
> > > > Why are you changing the `cp_route` to an empty string? Are you running headless and don't need a front-end?
> > > 
> > > 
> > > Yes, I am running headless. I am currently using a .htaccess to redirect to /cp but this is really unreliable. So changing the cp_route to the root, it skips that whole step.
> > 
> > 
> > Cool, make sense. As a workaround for now, try adding something like this to your `routes/web.php` which will redirect any non `/cp` URL to the CP dashboard.
> > ```
> > Route::redirect('/{any}', '/cp/dashboard')->where('segments', '^(?!cp).*$');
> > ```
> 
> Ill check that out this weekend, got a day off tomorrow :-) ! Thanks for the tip!

No problem! It'll hopefully be more reliable than doing it with Apache.

**Comment by RobbertUpgraders** [comment]
> > > > > Why are you changing the `cp_route` to an empty string? Are you running headless and don't need a front-end?
> > > > 
> > > > 
> > > > Yes, I am running headless. I am currently using a .htaccess to redirect to /cp but this is really unreliable. So changing the cp_route to the root, it skips that whole step.
> > > 
> > > 
> > > Cool, make sense. As a workaround for now, try adding something like this to your `routes/web.php` which will redirect any non `/cp` URL to the CP dashboard.
> > > ```
> > > Route::redirect('/{any}', '/cp/dashboard')->where('segments', '^(?!cp).*$');
> > > ```
> > 
> > 
> > Ill check that out this weekend, got a day off tomorrow :-) ! Thanks for the tip!
> 
> No problem! It'll hopefully be more reliable than doing it with Apache.

Hi Duncan, hope you had a great weekend. I tried the piece of code but it seems to do nothing. For example, when I visit cms.example.com (which is pointed to the public folder in root) it just shows the statamic logo with the 3 links underneath. It does not seem to trigger the new route redirect. Any tips?

**Comment by duncanmcclean** [comment]
Do you have anything else in your `routes/web.php` file or is it just that?

**Comment by RobbertUpgraders** [comment]
> Do you have anything else in your `routes/web.php` file or is it just that?

Nope, just that

**Comment by duncanmcclean** [comment]
Ah sorry, try this instead, forgot the `?`..

```
Route::redirect('/{any?}', '/cp/dashboard')->where('segments', '^(?!cp).*$');
```

**Comment by RobbertUpgraders** [comment]
> ```
> Route::redirect('/{any?}', '/cp/dashboard')->where('segments', '^(?!cp).*$');
> ```

That does seem to do the trick :) I am gonna roll it out and check if it works on all our Statamic instances (the last method worked great for some but not for all) But I doubt that this will not work. if it does not work ill report back :) If not, consider it working fine :) ! Thanks!

**Comment by jackmcdade** [comment]
I really don't like the idea of supporting `''` as a valid CP location. 🤔  What would `'/'` have done?

**Comment by duncanmcclean** [comment]
> I really don't like the idea of supporting `''` as a valid CP location. 🤔 What would `'/'` have done?

Looks like it just tries to redirect to `https://dashboard/` when you set it to `/`.

**Comment by RobbertUpgraders** [comment]
> I really don't like the idea of supporting `''` as a valid CP location. 🤔 What would `'/'` have done?

'/' gave me pretty much the same result. The route::direct() seems like a solid work around so the question if this ' ' or '/' needs to be supported, is up to you.

**Comment by RobbertUpgraders** [comment]
> > I really don't like the idea of supporting `''` as a valid CP location. 🤔 What would `'/'` have done?
> 
> '/' gave me pretty much the same result. The route::direct() seems like a solid work around so the question if this ' ' or '/' needs to be supported, is up to you.

Actually scrap that, what Duncan said '/' redirects to https://dashboard/. I thought I tried that and got the same result but maybe I didn't

**Comment by duncanmcclean** [comment]
Also, I've just tried an image upload with an empty `cp_route` and it seems to work just fine. Are you sure it works in general? How are you uploading the image?

**Comment by jackmcdade** [comment]
This has gotten stale and isn't something I really want to support anyway. You can disable the CP if you don't want someone using it, and/or you can rename it something obscure. Setting it to a non-functional URL will create non-functioning features.
