### ISSUE TITLE
[i18n] CP not always displayed in the user's locale (app.php locale "races" user's preference)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#3467]
## Bug Description
Related or same as #2041 

In some parts of the CP, there is a race condition between the locale defined in app.php and the locale defined in your user's yaml file

## How to Reproduce
Set the locale to ```en``` in ```config/app.php``` and set the locale to another language in your user yaml file.
Login to the CP. It's apparently fully translated in your user's locale
Create a new set of Permissions
Look as most settings are still displayed in English

Then, change the locale to your user's language in ```config/app.php```and navigate to the same set of permissions
Look as ALL settings are now displayed in your user's locale.

## Extra Detail

![Capture d’écran 2021-04-02 à 22 23 40](https://user-images.githubusercontent.com/1823359/113451406-37168400-9402-11eb-9036-787914fdc9e4.png)

![Capture d’écran 2021-04-02 à 22 24 03](https://user-images.githubusercontent.com/1823359/113451423-3da4fb80-9402-11eb-806e-1d0cb95da5e5.png)

![Capture d’écran 2021-04-02 à 22 24 18](https://user-images.githubusercontent.com/1823359/113451433-43024600-9402-11eb-900d-8dfda6bdae36.png)

## Environment

**Statamic version:** 3.1.3 Pro

**PHP version:** 7.4.2 via MAMP

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ebeauchamps** [comment]
This should get a "bug" label. #2041 has been closed in favor of this issue. A solution has been worked on by @arthurperton and @jasonvarga but is not available yet.

**Comment by jasonvarga** [comment]
Fixed in #7343 and will be in 3.4.
