### ISSUE TITLE
Cannot update statamic's starter kits to 3.1.x : composer error

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#3468]
## Bug Description
I followed the documentation to update an existing site:
- in composer.json, I changed statamic/cms to require 3.1.*
- in the same file, under scripts, I added the pre-update-cmd

I get a composer error: ```Class Statamic\Console\Composer\Scripts is not autoloadable, can not call pre-update-cmd script```

Additional composer message:

```
- statamic/ssg is locked to version dev-master and an update of this package was not requested.
- statamic/ssg dev-master requires statamic/cms 3.0.* -> found statamic/cms[v3.0.0-beta.1, ..., 3.0.x-dev] but it conflicts with your root composer.json require (3.1.*).
```

I get the same error with 2 statamic starter kits

**Statamic version:** 3.0.49

**PHP version:** 7.4.2 via MAMP

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
Also change `statamic/ssg` to `^0.4.0` in your `composer.json` then run `composer update`. We added 3.1 support in that version.
