### ISSUE TITLE
Trailing slash and query string returns 404

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#3469]
## Bug Description
It appears that appending urls with a trailing slash and a query string produces a 404 error.

## How to Reproduce

- Visit `/slug/?foo=bar`
- See 404 page error

## Environment

Statamic 3.0.49 Pro
Laravel 7.28.3
PHP 7.4.14
aryehraber/statamic-font-awesome 2.0.0
doublethreedigital/duplicator 1.1.0
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 1.2.0
statamic/seo-pro 2.0.14

**Comment by jasonvarga** [comment]
Happens without static caching.

**Comment by jasonvarga** [comment]
Note to self: it's because `Data::findByUri` ends up getting a `$uri` ending with `/`, which is wrong. We'll need to strip that off.

https://github.com/statamic/cms/blob/fc034eec145a174be4cb485cea524156e09b9866/src/Http/Controllers/FrontendController.php#L48
