### ISSUE TITLE
Call to a member function structure() on null

### ISSUE THREAD

**Issue by Robinvm** [statamic/cms#3478]
## Bug Description
I suddenly get the error: Call to a member function structure() on null

Statamic\Structures\CollectionTree::Statamic\Structures{closure} vendor/statamic/cms/src/Structures/CollectionTree.php:19

return Blink::once('collection-tree-structure-'.$this->handle(), function () {

       ERROR====> return Collection::findByHandle($this->handle())->structure();

    });

## How to Reproduce
I made a new collection, and after that pages collection started to do this. When i save it says saved, save again, error, save again, saved, save again, error. 

## Extra Detail

![Schermafbeelding 2021-04-06 om 11 06 18](https://user-images.githubusercontent.com/22294849/113686973-2303a880-96c8-11eb-98ea-ec895fd1c560.png)

## Environment

Statamic 3.1.3 Pro
Laravel 8.35.1
PHP 7.4.16
cnj/seotamic 2.0.3
pecotamic/sitemap 1.2.1

**Statamic version:** 3.0.{?}
3.1.3 Pro

**PHP version:** 7.4.16

**Install method (choose one):**
- Fresh install from `statamic/statamic` THIS ONE
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by duncanmcclean** [comment]
So you created a new collection, then you went back to your Pages collection and it gave you that error? Correct?

**Comment by taylorcammack** [comment]
Looks like it also throws the error after every page update. Resolves on a refresh. Any idea for where to start poking around?

**Comment by robdekort** [comment]
Getting a similar issue on the site I'm working. It happens when warming the stache here.
<img width="1490" alt="Screenshot 2021-04-21 at 09 24 46" src="https://user-images.githubusercontent.com/69107412/115513556-79a1e280-a283-11eb-9350-056a5edeb01c.png">

**Comment by robdekort** [comment]
And when saving pages

**Comment by Robinvm** [comment]
I got a fix for it. In the tree directory, i deleted the pages.yaml or something, it just regenerated and now it works correctly on my side. Not the best fix i guess, but it works.

**Comment by robdekort** [comment]
Hmmm, doesn't seem to work here. I just loose my page tree ;-)

**Comment by Robinvm** [comment]
Yes but then just save a page and it regenerates

**Comment by robdekort** [comment]
Ah! I removed `content/trees/pages.yaml` while the issue was with `content/trees/projects.yaml`. It just contained:
```yaml
{ }
```

Projects _was_ as a structured collection before and then later I turned it into a date based collections. This seems to leave behind a nearly empty tree file which causes this error.

Hope it helps solving this one.

**Comment by robdekort** [comment]
I was able to reproduce this on a fresh install by:

1. Making a new orderable collection
2. Adding some entries so you get a tree
3. Turn collection into a non structured collection (date based for example)
4. Warm the stache.

If you use [statamic-issue-3478.zip](https://github.com/statamic/cms/files/6349067/statamic-issue-3478.zip) you'll get it for free. Just run `php please stache:warm`.

Switching to non structured collection should probably remove the tree collection.yaml file.

**Comment by DrTrills** [comment]
I have the same issue. New site install. in terminal if I run `php please stache:warm`


```
Warming Stache...

   Error

  Call to a member function structure() on null

  at vendor/statamic/cms/src/Structures/CollectionTree.php:19
     15▕ {
     16▕     public function structure()
     17▕     {
     18▕         return Blink::once('collection-tree-structure-'.$this->handle(), function () {
  ➜  19▕             return Collection::findByHandle($this->handle())->structure();
     20▕         });
     21▕     }
     22▕
     23▕     public function path()

      +8 vendor frames
  9   [internal]:0
      Statamic\Stache\Indexes\Value::Statamic\Stache\Indexes\{closure}()

      +26 vendor frames
  36  please:37
      Illuminate\Foundation\Console\Kernel::handle()
```

Also possibly related, in the CP when I click `clear content stache` I get a 500 error
