### ISSUE TITLE
SVG width/height values are always treated as pixels

### ISSUE THREAD

**Issue by xjoke** [statamic/cms#3479]
## Bug Description

Regarding #2865, the `witdth` and `height` values are always interpreted as pixels, even if values like `pt`, `em`, `cm` are passed. Since these attributes are CSS attributes [1], other units of measurement are allowed, the most common one probably being `%`. Affinity Products (like Designer and Publisher) export SVGs with the `width` and `height` value set to `100%`. The SVGs my clients upload thus have a supposed width and height of `100`(px).

I would argue that if a unit other than pixels is used, the value from the `viewBox` should be used instead of a wrong value.

[1] https://www.w3.org/TR/SVG2/geometry.html#Sizing

## How to Reproduce

Upload any SVG with a `width` and `height` set to a non-pixel value. As an example: [The SVG logo used on Wikipedia](https://upload.wikimedia.org/wikipedia/commons/4/4f/SVG_Logo.svg)

## Extra Detail

"Problematic" code:
https://github.com/statamic/cms/blob/de8b1847243ca3ccb46f7b98d54ce82aa78ff309/src/Assets/Dimensions.php#L122-L128

## Environment

**Statamic version:** 3.1.3

**PHP version:** 7.4.16

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
@jasonvarga — Is there any reason we couldn't store `100%` instead of `100` in the meta data?

**Comment by jasonvarga** [comment]
I guess we could, but if you asked me what the dimensions of an image were and I told you "100%" you'd probably look at me like 🤨

**Comment by jackmcdade** [comment]
I use that for svgs all the time so they fill their container. Rarely for regular images tho.

**Comment by xjoke** [comment]
If I may throw in my two cents: I think storing the values in percentage would go directly against the original issue #2865, since the browser, again, had no way of knowing how much space the image is going to take, prior to actually loading it. Consistency is also a thing to consider: SVGs are images after all and most of the time I don’t care (and I don’t want my clients to care) whether an image on the site has pixels or vectors; they should just be able to use any image they want. The dev shouldn’t have to care either. 

(100%/100% is not only used for square images, so this might also be problematic if the aspect ratio might be needed)
