### ISSUE TITLE
Search tag doesn't work right when setting supplement_data to false

### ISSUE THREAD

**Issue by arthurperton** [statamic/cms#3480]
## Bug Description

When you set `supplement_data` to `false` you are not getting any results.

## How to Reproduce

Add something like this to your (home) template and perform a search that should return results:

```html
<form action="">
    <input type="search" name="q" placeholder="Search">
    <button type="submit">Make it so!</button>
</form>
<br/>
Results:<br/>
{{ search:results supplement_data="false" }}

  {{ if no_results }}

    <h2>No results.</h2>

  {{ else }}

    <a href="{{ url }}" class="result">
      <h2>{{ title }}</h2>
      <p>{{ content | truncate:240 }}</p>
    </a>

  {{ /if }}

{{ /search:results }}
```

## Extra Detail
* The first problem is that `Statamic\Search\Tags` is adding a `$query->where('status', 'published')` and the published field is not indexed by default. So no results in that case.
* If you remove the where clause, you'll get an error (see screenshot). In `Statamic\Search\QueryBuilder` a collection of associative arrays is returned when `supplement_data` is `false`. Other code is expecting (data) objects like `Entry`, `Term`, etc. so things go wrong in `Tags->addResultTypes()` where the `supplement()` method is called on the associative arrays.

<img width="1250" alt="Screenshot 2021-04-06 at 12 47 57" src="https://user-images.githubusercontent.com/4067531/113701298-40407300-96d8-11eb-9282-0285984682f5.png">

## Environment

Statamic 3.1.3 Solo
Laravel 8.34.0
PHP 7.4.16
No addons installed

**Install method (choose one):**
Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
I think we'll need to add a caveat to the `supplement_data="false"` parameter saying that if you do that, you must add the appropriate fields to your search index.

Maybe we can also only run `addResultTypes` if you have chosen to supplement data.

**Comment by arthurperton** [comment]
> I think we'll need to add a caveat to the `supplement_data="false"` parameter saying that if you do that, you must add the appropriate fields to your search index.
>
> Maybe we can also only run `addResultTypes` if you have chosen to supplement data.

Let's! I'll make the changes to this PR. Could you do the update to the docs?
