### ISSUE TITLE
UI: Text Links show blank Published Status in tree view

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#3489]
## Bug Description

 It looks like Navigation **Text Links** were missed in the update that adds the Published status in tree view (#3461). I think the appropriate status for them would be 'unpublished' grey status or no status at all.

## Extra Detail
<img width="974" alt="Screen Shot 2021-04-08 at 12 17 07 am" src="https://user-images.githubusercontent.com/414211/113882254-7b3dc600-9800-11eb-9a79-5ec637667ef9.png">

**Comment by jackmcdade** [comment]
I feel like an unpublished grey status would imply it wouldn't show. There already isn't a status already. 🤔

**Comment by mikemartin** [comment]
@jackmcdade How about a "ghost dot" using a gray border when there's no status then? 
`border border-gray-60 bg-transparent`

<img width="321" alt="Screen Shot 2021-04-08 at 12 35 09 am" src="https://user-images.githubusercontent.com/414211/113884595-6feb9a00-9802-11eb-9aac-85bda4a11d6f.png">

**Comment by jackmcdade** [comment]
Technically that style already means expired or scheduled, but I think that would work fine. I think I'll combine this with a tooltip in hover to clarify the meaning.
