### ISSUE TITLE
Entry::id($id) in a queued job throws an error

### ISSUE THREAD

**Issue by Krzemo** [statamic/cms#3493]
## Bug Description
When trying to get an entry by id in a job, an error is thrown.

## How to Reproduce
1. Dispatch a job from an event - i.e. EntryCreated and pass entry ID to it
2. In this job get the entry:
`Entry::find($id)`
and try to delete it.

An error is thrown:
`Call to a member function handle() on null {"exception":"[object] (Error(code: 0): Call to a member function handle() on null at /www/vendor/statamic/cms/src/Stache/Stores/CollectionsStore.php:21)`

## Environment
Statamic 3.1.3 Pro
Laravel 8.35.1
PHP 7.4.16
edalzell/variable 1.0.3
stillat/meerkat 2.4.5-beta3

**Statamic version:** 3.1.3

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Possibly related to #2993.

**Comment by duncanmcclean** [comment]
If you run your code outside of a queued job, does it work?

**Comment by jasonvarga** [comment]
Probably related to https://github.com/statamic/cms/issues/2993

**Comment by duncanmcclean** [comment]
> Probably related to #2993 or maybe even a duplicate.

I thought that initially but there wasn't any exception in that original issue, I don't think?

**Comment by jasonvarga** [comment]
No exception was provided, but I assume that's what "messed up" meant.
