### ISSUE TITLE
Assets manager not loading behind a load balancer that terminates SSL

### ISSUE THREAD

**Issue by phyroslam** [statamic/cms#3495]
## Bug Description
Assets manager not loading behind a load balancer that terminates SSL. Browser is blocking a non https call to  assets/browse/folders/assets/

Seems that a trailing slash on the call URL would cause the Apache server on the node handling the request to respond with a 301 Code indicating that the URL is moved to an URL without the trailing slash but the Apache server is not aware it is behind a load balancer and the new URL that offers to the browser is not https thus the browser blocks the second request

The issue seems to have its origin in component Browser.vue

## How to Reproduce

Set up statamic behind a load balancer, in this case the node that handles the response is an Apache server

Visiting any root asset container will cause the Apache server to respond with a 301 code sending a none https url

Any browser will block the second none https call since the context is an https session

## Extra Detail

Browser console shows a none http call being blocked

![Screen Shot 2021-04-07 at 4 08 45 PM](https://user-images.githubusercontent.com/5395518/113952866-68f56500-97cb-11eb-9a59-3c0078954e92.png)

Network tab shows what call is being blocked

assets/browse/folders/assets/?queryparamshere

![Screen Shot 2021-04-07 at 4 11 04 PM](https://user-images.githubusercontent.com/5395518/113953019-bd004980-97cb-11eb-8115-7304e3c54fa8.png)

Visiting directly the node behind the firewall the call succeeds but not before recording a 301 Redirect

![Screen Shot 2021-04-07 at 5 35 23 PM](https://user-images.githubusercontent.com/5395518/113953096-e620da00-97cb-11eb-8f6f-cd792c8d17df.png)

This is only happening to root asset containers, any subfolder will not contain a trailing slash and will not cause a 301 redirect even through the load balancer

![Screen Shot 2021-04-07 at 5 52 27 PM](https://user-images.githubusercontent.com/5395518/113953618-1157f900-97cd-11eb-8b14-32d7bc95ab9d.png)

The origin of the call is Browser.vue component

![Screen Shot 2021-04-07 at 5 58 28 PM](https://user-images.githubusercontent.com/5395518/113953555-f1283a00-97cc-11eb-9af2-895a16150985.png)

## Environment

Traefik loadbalancer

Apache server node

**Statamic version:** 3.1.4

**PHP version:** 7.4.15

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Have you got trusted proxies configured correctly?

**Comment by phyroslam** [comment]
Yes, everything works fine, except for that call that as I already mentioned because of that trailing slash Apache responds with a 301 redirect, so the initial call does not even make it to statamic.

Take a look at the response of the initial request to: https://...../cp/assets/browse/folders/assets/?page=1...
Is clear that because the trailing slash Apache repond with a redirect and a new location, the new location is correct because clears the trailing slash but incorrectly uses none secure scheme
![Screen Shot 2021-04-07 at 11 49 10 PM](https://user-images.githubusercontent.com/5395518/113981799-eab1b680-97fc-11eb-9987-f7fe17593554.png)

**Comment by jasonvarga** [comment]
Are you using cloudflare or any amazon services?

**Comment by jasonvarga** [comment]
I see that you answered "yes everything works fine" to Duncan's question but did you actually configure trusted proxies as described here? https://laravel.com/docs/8.x/requests#configuring-trusted-proxies

If you're using Cloudflare, you can install this https://github.com/monicahq/laravel-cloudflare

**Comment by phyroslam** [comment]
I am not using Cloudflare or Amazon, and yes I did configure trusted proxies and for now it is trusting any server, I am using my custom set up of Traefik load balancer, but for a minute forget that this issue is affecting my load balancer set up. You can see in the following screenshot that the 301 redirection happens even in my local environment, as matter of fact the 301 redirection happens on any statamic v3 installation, you can check it in your own statamic install if you navigate to a root folder and open your browser network console, you'll see to request to the same resource and the 301 redirect.

![Screen Shot 2021-04-08 at 10 15 08 AM](https://user-images.githubusercontent.com/5395518/114069271-a998c100-9853-11eb-8390-36ec756c4c3f.png)

The issue resides on that the path parameter for root folders is just a slash, I'll take a deeper look to see if I can propose a fix, let's see if we can save the world from a redundant http call, just kidding, thanks for your help.

**Comment by jasonvarga** [comment]
For me, it doesn't do a 301. I wonder whats different about your setup.

I see you're using localhost:8000 - how are you serving your site?

**Comment by phyroslam** [comment]
Found the root cause and proposed a fix with this pull request

https://github.com/statamic/cms/pull/3503

**Comment by jasonvarga** [comment]
Ah! You mentioned that you're using apache. I'm curious if you have an htaccess rule that removes trailing slashes?

**Comment by phyroslam** [comment]
Ok, finally found the root cause and proposed a proper fix

**Comment by phyroslam** [comment]
By the way, I am using docker image php:7.4-apache with no special configuration on htaccess so what I am describing is the default behavior of Apache at least on this Docker image
