### ISSUE TITLE
modifier :as expects an associative array

### ISSUE THREAD

**Issue by lostika86** [statamic/cms#3506]
## Bug Description
According to documentation :as modifier aliases an array.  When you try to reach value by key, throws an error 

> InvalidArgumentException
Expecting an associative array

## How to Reproduce

Simply copy code from [documentation](https://statamic.dev/modifiers/as), and try to write out `            {{ block | partial:type }}`

## Extra Detail

![image](https://user-images.githubusercontent.com/10046659/114170750-a6750200-9933-11eb-8316-4518e4cc5212.png)
The `block | dump` output 
![image](https://user-images.githubusercontent.com/10046659/114170875-d6bca080-9933-11eb-93dc-e796e850e72e.png)

## Environment

**Statamic version:** 3.1.4

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
That was an issue with the `regex` parser. I updated docs to represent a working use case for the newer `runtime` antlers parser.
