### ISSUE TITLE
Published status greyed out in navigation tree until you save and refresh

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3510]
## Bug Description
When you add an entry to the navigation tree it has a greyed out (unpublished?) icon. I don't know what it means, but only when you save changes and refresh it turns green.

## How to Reproduce

1. Add a page to the navigation
2. See it's not a green circle
3. Save changes 
4. Refresh
5. See it's a green circle

## Extra Detail
<img width="1568" alt="Screenshot 2021-04-09 at 16 13 10" src="https://user-images.githubusercontent.com/69107412/114193329-b3531f00-994e-11eb-8a95-50b1fcab1761.png">
<img width="1568" alt="Screenshot 2021-04-09 at 16 13 15" src="https://user-images.githubusercontent.com/69107412/114193340-b77f3c80-994e-11eb-8e3e-286e872142cc.png">

## Environment
Statamic 3.1.5 Pro
Laravel 8.36.2
PHP 7.4.13

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
I can confirm, noticed this the other day.
