### ISSUE TITLE
Setting to block Google FLoC

### ISSUE THREAD

**Issue by websmyth** [statamic/cms#3520]
Google’s new FLoC (replacement for ad-based cookies) test opts in *all* websites by default. This introduces some [privacy concerns](https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea) and site owners/Chrome users [have not consented to be involved in the trial](https://amifloced.org/).

Sites can only opt-out of the trial by [adding an HTTP response header](https://web.dev/floc/#how-can-websites-opt-out-of-the-floc-computation):

`Permissions-Policy: interest-cohort=()`

@edalzell suggested a setting [could be built into Statamic core](https://twitter.com/emd/status/1381697483579920384?s=20). That would be a great help for people who want to block this.

**Suggested implementation:**
- Config setting to disable the Permissions Policy
- Permissions Policy enabled by default (i.e. sites opt-out of Google’s test)

**Comment by websmyth** [comment]
Excellent, thanks 🔥

**Comment by jasonvarga** [comment]
You can do this yourself right now in the mean time by:

```
php artisan make:middleware Floc
```

Which creates `app/Middleware/Floc.php`.

Then you can paste in:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class Floc
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $response = $next($request);

        $response->headers->set('Permissions-Policy', 'interest-cohort=()');

        return $response;
    }
}
```

and register it in `app/Http/Kernel.php`'s `web` middleware group:

```php
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            // ...
            \App\Http\Middleware\Floc::class,
        ],
```

You should then see it working in the network tab of your devtools:

![image](https://user-images.githubusercontent.com/105211/114563245-41742180-9c3d-11eb-831d-8093ee6d8e43.png)

(That'll add the header, although I don't know enough about this new thing to make sure whatever it's not supposed to be doing isn't actually happening)

**Comment by edalzell** [comment]
@websmyth released an addon until/when pulled into core: https://statamic.com/addons/silentz/floc

**Comment by Rabjam** [comment]
What if I'm just using duckduckgo on bromite

**Comment by Rabjam** [comment]
What if I'm using duckduckgo on bromite  why not ad duckduckgo and ublock extension that has blocked floc

**Comment by websmyth** [comment]
@jasonvarga @edalzell – thank you so much! You’re both ace ✌️

@Rabjam – you can use the DuckDuckGo browser extension for sure (or use a non-Chrome browser): that’ll help. These Statamic extensions are so website owners can prevent their users being added to the FLoC experiment by Google.

**Comment by jackmcdade** [comment]
WP is looking to make this core, default behavior. I’m in favor of a more private web, so I see no reason why we shouldn’t implement this as default and let people opt into FLoC if they choose. 

https://twitter.com/magicroundabout/status/1383787254305357831
