### ISSUE TITLE
Trouble getting breadcrumbs working on multi-site

### ISSUE THREAD

**Issue by tao** [statamic/cms#3523]
## Bug Description
The breadcrumbs tag works fine on my English site but doesn't seem to work on multi-sites with the site handle is in the url.

## How to Reproduce
I created a demo repository: https://github.com/tao/statamic-multisite-breadcrumbs

## Extra Detail
![Screenshot 2021-04-13 at 22 36 57](https://user-images.githubusercontent.com/1446331/114617700-c5172800-9ca8-11eb-8bc3-82aadd3944f9.png)

On the default site when the url is `/articles/dance` then the breadcrumbs work.

![Screenshot 2021-04-13 at 22 37 53](https://user-images.githubusercontent.com/1446331/114617817-e5df7d80-9ca8-11eb-8a02-7396159599fe.png)

If you visit the urls `/italian/articles/dance` or `/french/articles/dance` then it seems to only show the title.

## Environment
Statamic 3.1.6 Pro
Laravel 8.37.0
PHP 8.0.3
statamic/ssg 0.4.0

**Install method**
- Starter kit (cool writings)

**Comment by jasonvarga** [comment]
Do you have entries that exist at `/italian/articles/dance` and `/french/articles/dance`?

**Comment by tao** [comment]
Yes, in the screenshot you can see the lead paragraph changed to Lorem Ipsum because its placeholder content for the new language.

**Comment by jasonvarga** [comment]
Sorry I guess I meant to ask about `/italian/articles` and `/french/articles`

**Comment by tao** [comment]
Ok, I get it.

![Screenshot 2021-04-13 at 23 09 59](https://user-images.githubusercontent.com/1446331/114621798-6f914a00-9cad-11eb-92f9-13a285962d7d.png)

So I added the `/italian/articles` by translating `articles` in the `pages` collection and now I've got some breadcrumbs but `Home` is missing.

I'm not sure if that's also a bug we need to look at but could we please add a warning on the Statamic docs about this because it's been quite difficult to figure out on my side.

Something like: "To get breadcrumbs working on multi-site: remember to create translations for the parent pages in the page collection too."

**Comment by jasonvarga** [comment]
We can definitely improve the docs. 👍 

The way it works is that it looks at the url and outputs the data for the corresponding pages.

If you visit `/italian/articles/dance`,
- first it looks for an entry with a url of `/italian/articles/dance`
- then it pops the last segment off (`dance`) and looks for an entry with a url of `/italian/articles`
- rinse and repeat until it's out of segments. next is `/italian`

Do you have an italian home page entry?

**Comment by tao** [comment]
Okay, so the Home page doesn't exist in the breadcrumbs because it's not translated either...

It's difficult to understand at first, or counterintuitive because the multi-site usually falls back to the default sites content when no translation exists... but the breadcrumbs don't work that way.

**Comment by jasonvarga** [comment]
Chalking this one up to documentation.

It's URL based. Not structure based. Just something to keep in mind.

It works that way because you could go in and out of collections, custom routes, whatever, depending on how many segments into the URL you are.
