### ISSUE TITLE
Data list filter empty check returns true on numbers

### ISSUE THREAD

**Issue by martink635** [statamic/cms#3526]
## Bug Description
Custom Fieldtypes, that return numbers as value instead of strings, have problems when used as fields for data list filters.

The `Filter.vue` component triggers the `updateValues` function on an update from the `publish-container`. The `updateValues` should delete all empty keys, so they do not get passed on, but since the underscore `isEmpty` method is being used, for a value of ie `1`, the method returns true (`_.isEmpty(1) === true`). 

This is the intended behavior of the `isEmpty` method from the underscore library, but I am pretty sure this is not intended here. Copy from the [underscore docs:](https://underscorejs.org/#isEmpty) 

> Returns true if collection has no elements. For strings and array-like objects _.isEmpty checks if the length property is 0. For other objects, it returns true if the object has no enumerable own-properties. **Note that primitive numbers, booleans and symbols are always empty by this definition.**

## Environment

Statamic 3.1.6 Pro
Laravel 8.37.0
PHP 7.4.12
No addons installed

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Can you please provide an example of your fieldtype so we don't have to reinvent any wheels when trying to reproduce this issue for you?

**Comment by martink635** [comment]
Sure!

The fieldtype itself doesn't really matter in this case, this is a small example to reproduce the behavior:

**Non working:**
```javascript
<template>
    <div>
        <text-input type="text" :value="value" @input="updateWithInteger" />
    </div>
</template>

<script>
export default {
    mixins: [Fieldtype],

    methods: {
        updateWithInteger(event) {
            this.update("1");
        }
    }
};
</script>
```

**Working:**
```javascript
<template>
    <div>
        <text-input type="text" :value="value" @input="updateWithInteger" />
    </div>
</template>

<script>
export default {
    mixins: [Fieldtype],

    methods: {
        updateWithInteger(event) {
            this.update(1);
        }
    }
};
</script>
```

The non working example doesn't trigger an update since the `isEmpty` clears it out. Hope this is clear. Of course this example is dumb, I get integers in a key/value store from a json object from a database.

**Comment by duncanmcclean** [comment]
In #10393, we stopped using Underscore's `_.isEmpty` check in favour of another approach, which should mean this issue is now resolved.

If it's still an issue for you on the latest version of Statamic, let us know and we can re-open. Thanks!
