### ISSUE TITLE
Not possible to hardcode links in multisite setup

### ISSUE THREAD

**Issue by goellner** [statamic/cms#3529]
## Bug Description
There is no native way to hardcode a link and have support for multisite setup, maybe the `{{link}}` tag could support ids

## How to Reproduce
1. make multisite
2. try to hardcode a link from an id. not possible, since the ids of the entries are different

**Comment by duncanmcclean** [comment]
Please include the output of `php please support:details` in your post and follow the whole issue template on future issues. Thanks 😄

**Comment by goellner** [comment]
will do, thought its not necessary, since its related to all v3 versions

Environement: 

Statamic 3.1.6 Pro
Laravel 8.33.1
PHP 7.4.15
jonassiewertsen/statamic-livewire 2.5.0
spatie/statamic-responsive-images 2.5.3
statamic/seo-pro 2.1.5

**Comment by jasonvarga** [comment]
Please let us determine what's necessary. We provide the template for a reason. 👍

**Comment by jasonvarga** [comment]
Note: support for `to="123"` was added in #3530 (3.1.7) but changed in #3576 (3.1.10).

You'll need to do `{{ link id="123" }}`
