### ISSUE TITLE
`get_content` doesn't read the local "view" context

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#3532]
## Bug Description

If you have an id defined in the front matter, `get_content` won't use it.

## How to Reproduce

in your front matter:
```
---
page_id: valid-id
---
{{ get_content:page_id }}{{ permalink }}{{ /get_content }}
```

You'll see that the `permalink` is from the page you're on, NOT the url of that content. Get content should look "up" the context.

Note that `{{ get_content :from="view:page_id" }} ...` DOES work.

## Environment

Statamic 3.1.0 Pro
Laravel 8.34.0
PHP 7.4.16
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by JohnathonKoster** [comment]
Both of these variants should also work:

```
{{ get_content:view.page_id }}
    {{ permalink }}
{{ /get_content:view.page_id }}

{{ get_content:view:page_id }}
    {{ permalink }}
{{ /get_content:view:page_id }}
```

**Comment by jasonvarga** [comment]
Remember, template front matter is always in `view`.

You should do `get_content:view:page_id` like @JohnathonKoster said.
