### ISSUE TITLE
input type number stores 0

### ISSUE THREAD

**Issue by vguerrerobosch** [statamic/cms#3536]
## Bug Description
A text field will type number and nullable and numeric validation is stored as 0.

## How to Reproduce
Setup a text field type number with nullable and numeric validation rules for a collection. Save an entry. The value of the field is 0 and not null. You can clone [this repo](https://github.com/vguerrerobosch/statamic-issues) will all the scaffold if you like.

## Extra Detail
Can't really tell in what version this showed up but I been using Statamic since beta 8 or something and this wasn't an issue at least until beta 30ish.. maybe more not really sure.

## Environment

**Statamic version:** 3.1.6

**PHP version:** 7.4

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
The nullable validation is irrelevant here, but bug confirmed.

**Comment by vguerrerobosch** [comment]
Related to this, I've just been reported about issues with decimals, which are removed when saving. Not sure if there is the option to set the step attribute or something.

**Comment by jasonvarga** [comment]
Yeah I can see why that would happen. Feel free to open a separate issue for that.

If you want decimals though (all the time) then you can use the `float` fieldtype instead of `text`.

**Comment by jasonvarga** [comment]
Actually don't worry. It's easy to fix.
