### ISSUE TITLE
Mount entries field in configure collection shows ID [minor]

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3537]
## Bug Description
The entries fields where you can select an entry to mount a collection shows just the ID when you selected an entry. After a reload it shows the title:

**Before reload**:
<img width="945" alt="Screenshot 2021-04-16 at 11 56 27" src="https://user-images.githubusercontent.com/69107412/115008179-1b53b900-9eab-11eb-9073-ae528bc8480c.png">

**After reload**:
<img width="939" alt="Screenshot 2021-04-16 at 11 56 48" src="https://user-images.githubusercontent.com/69107412/115008186-1db61300-9eab-11eb-8302-ba595453a97b.png">

## How to Reproduce
Mount a collection to an entry and observe the entry field behaviour. 

## Environment
Statamic 3.1.7 Pro
Laravel 8.37.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by duncanmcclean** [comment]
Huh, I was able to replicate two minutes ago on every other entry but I refreshed and tried to record a video and every entry I selected started to work. 🤔

**Comment by robdekort** [comment]
Weird, still happening here though on the latest version.
