### ISSUE TITLE
entries_count includes published and unpublished entries

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#3539]
## Bug Description

`entries_count` includes published and unpublished entries.

I'd like to see a way to filter this, in a similar way we can with `{{entries  status:is="published"}}`
       

## How to Reproduce
Add a term to three entries, mark one entry as a draft. `entries_count` will display the number 3.

```
<ul>
      {{ taxonomy:group }}
          <li>
              <a href="{{ url }}">{{ title }}</a> ({{ entries_count }})
          </li>
      {{ /taxonomy:group }}
</ul>
```

## Environment

**Statamic version:** 3.1.5 Pro

**PHP version:** 7.4.11

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Related to #2721.

**Comment by mikemartin** [comment]
@arthurperton I have an entries fieldtype with published and unpublished entries, and augmentation filters the unpublished entries out. There seems to be no work around in the meantime.

<img width="692" alt="Screen Shot 2021-06-01 at 2 31 02 pm" src="https://user-images.githubusercontent.com/414211/120267018-7409d480-c2e6-11eb-829a-4c1a18295c00.png">

Would love to output them like [Jason's solution](https://github.com/statamic/cms/pull/3544#pullrequestreview-663661152). For example:

```
{{ features status:in="draft|published" }}
...
{{ /features }}
```

**Comment by jasonvarga** [comment]
@mikemartin looks like you've commented on the wrong issue?

**Comment by dominikradl** [comment]
Is there any progress on this?

**Comment by binoclard** [comment]
Hi,
Is there any new updates or workaround concerning this issue?

I am using
```
{{ taxonomy:categories collection="projets|imagerie" }}
  <option value="{{ url }}">{{ title }}</option>
{{ /taxonomy:categories }}
  ```
And it outputs Terms that are assigned only to draft/unpublished entries.
  
```{{ taxonomy:categories collection="projets|imagerie" status:is="published" }}``` does not work either.

Thanks

**Comment by j-jalving** [comment]
`entries_count` als includes future posts. I don't think unpublished or future should be included anywhere, only when explicitly requesting it.

Anyone found a workaround?

**Comment by tenmillionteeth** [comment]
A workaround I'm using is to check if the entry count is 0 (which only includes published entries), and if so, hide the taxonomy term from the listing. 

For example:

`{{ if {{collection:count from="collection" taxonomy:topics:any="{{slug}}"}} == 0}}
                                
         {{else}}
          {{ title }} ({{ collection:count from="{{collection}}" taxonomy:topics:any="{{slug}}"}})
 {{/if}}`

**Comment by SG-fabian** [comment]
This is still an issue. Our client unpublished some news and which let to empty news category pages. This solution is not unambiguous, since the taxonomy could be be unpublished:

    {{ taxonomy:categories min_count="1" status:is="published" }}

But it would be really nice to have some kind of "clean" solution in the future.

**Comment by KevinGrant12** [comment]
I am running into this same issue.
Not sure what "status:is="published" but that is not Statamic code?

```
{{ taxonomy:categories collection:is="blog" }}
                        <a href="#" id="slug" data-category="category-{{ slug }}" class="sidebar-nav-item {{ if active }}active{{/if}}">{{ title }}</a>
                    {{ /taxonomy:categories }}
```

**Comment by mehdismekouar** [comment]
```antlers
{{ taxonomy:tags collection="articles" min_count="1" status:is="published" }}
```
The above code throws an error
```
Call to undefined method Statamic\Stache\Query\TermQueryBuilder::whereStatus()
```

**Comment by duncanmcclean** [comment]
Terms don't _really_ have statuses, in the same way that entries do.

The `{{ entries_count }}` won't be affected by any parameters on the taxonomy tag anyway, since that's [not handled](https://github.com/statamic/cms/blob/e7fffc011762b6a14e74e29c46761b201d6c0bf8/src/Taxonomies/LocalizedTerm.php#L219) by the query.

**Comment by mehdismekouar** [comment]
Thanks for the clarification

But i tried ```{{ {taxonomy:tags collection="articles" min_count="1" title:contains="test"} | count }}``` and it does affect the count, i tried other filters and the count gets affected too, only the "published" filter doesn't

Any help on that?

**Comment by mehdismekouar** [comment]
Oops! i think it's my bad

The title in ```title:contains="test"``` refers to the tag title and not to the articles entries title
I get it now, sorry for that

Now my real question should be, how can can i query the **taxonomy:tags** of **collection="articles"** where the articles entries are published only? 

Any guidance on that? Thanks for your patience

**Comment by duncanmcclean** [comment]
For now, you can workaround it with a custom tag:

```php
// app/Tags/TermEntriesCount.php

<?php

namespace App\Tags;

use Statamic\Facades\Entry;
use Statamic\Tags\Tags;

class TermEntriesCount extends Tags
{
    /**
     * The {{ term_entries_count }} tag.
     *
     * @return string|array
     */
    public function index()
    {
        return Entry::query()
            ->where('collection', $this->params->get('collection'))
            ->whereTaxonomy($this->params->get('term'))
            ->where('published', true)
            ->count();
    }
}
```

```antlers
{{ taxonomy:tags }}
    <a href="{{ url }}">{{ title }} ( {{ term_entries_count collection="articles" :term="id" }} )</a>
{{ /taxonomy:tags }}
```

**Comment by mehdismekouar** [comment]
Much respect sir!
Thank you for your time
