### ISSUE TITLE
Link tag throw an error when param to is equal to handle name of any collection

### ISSUE THREAD

**Issue by jbrhel** [statamic/cms#3548]
## Bug Description

When the **link**  (or path) tag is present and the **to param is the same as handle name** of any existing collection  eg. `{{ link to="posts" }}` it throws an error.

## How to Reproduce
Put the handle name of any existing collection as a to param of the link or path tag. Reload the page.

## Extra Detail
`Call to undefined method Statamic\Entries\Collection::in() `

It could be an issue related to https://github.com/statamic/cms/pull/3530 . With Statamic version 3.1.7. works as expected.

## Environment

**Statamic version:** 3.1.9

**PHP version:** 7.4

**Comment by jasonvarga** [comment]
Workaround for now: If you prefix it with a slash, it'll know you just mean a regular path.

```
{{ link to="/posts" }}
```
