### ISSUE TITLE
Large file uploads don't always show "file too large" error messages.

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#3558]
## How to Reproduce

Go to the Asset Browser and try to upload something huge. You'll just see a spinner and the JS console will throw and error but the CP looks like it's trying.

## Extra Detail

<img width="522" alt="Screen Shot 2021-04-20 at 9 39 38 AM" src="https://user-images.githubusercontent.com/44739/115405795-91fafa00-a1bc-11eb-9241-e0144d59976b.png">

## Environment

**Statamic version:** 3.1.x

**Comment by jackmcdade** [comment]
Think you could knock this one out @arthurperton?

**Comment by arthurperton** [comment]
I’ll have a go at it 🔨
