### ISSUE TITLE
Delete asset folder

### ISSUE THREAD

**Issue by rrelmy** [statamic/cms#3565]
## Bug Description
In the asset browser there is sometimes no option to delete a directory.

![image](https://user-images.githubusercontent.com/442683/115538982-bcbc7f80-a29c-11eb-85a1-a68013d96b13.png)

## How to Reproduce

I have a hard time filling the bug because I have two sites, same version, similar config, same server but only one has the bug.
One had an older Laravel Version (8.33.0 vs. 8.36.2), but this was Statamic 3.1.5 
They break after doing `composer update`

Excuse me if this is not very helpful :-(

## Extra Detail

Shouldn't the AssetFolder class be listed in the Delete action too?
https://github.com/statamic/cms/blob/5705df401eafe082c134a6ef67dd52d49c00728f/src/Actions/Delete.php#L21

When adding it solves the issue locally.

## Environment

**Statamic version:** 3.1.5 / 3.19

**PHP version:** 7.4 and 8.0.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
> Shouldn't the AssetFolder class be listed in the Delete action too?

Yes it should. 👍  Introduced in 8a4d84fcb5fc9fb6e5bfb606be63336fbf4a2439
