### ISSUE TITLE
Bard 'Show HTML Source' button not working

### ISSUE THREAD

**Issue by arthurperton** [statamic/cms#3567]
## Bug Description
It happens when you add a link to an entry and then another one, or anything that contains a double quote. Then you can't switch to 'Show HTML Source' anymore. The button just doesn't respond.

## How to Reproduce

1. Add a Bard field to your blueprint.
2. Add a link to an entry in it.
3. Add another link, or just a word between double quotes.
4. Click the 'Show HTML Source' button.

## Extra Detail
<img width="846" alt="Screenshot 2021-04-21 at 15 23 31" src="https://user-images.githubusercontent.com/4067531/115561189-9b1bc200-a2b5-11eb-8fce-43a43af7de1e.png">
<img width="612" alt="Screenshot 2021-04-21 at 15 18 57" src="https://user-images.githubusercontent.com/4067531/115560459-e8e3fa80-a2b4-11eb-8b71-0bd05020ef36.png">

## Environment

Statamic 3.1.9 Pro
Laravel 8.35.1
PHP 7.4.16
No addons installed

**Install method (choose one):**
Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Hmm. I can't recreate this issue. Maybe it stemmed from that error with TipTap? @arthurperton can you test this without https://github.com/statamic/cms/pull/3585 ?

**Comment by arthurperton** [comment]
Ah yeah I forgot, sorry for the confusion. This issue is already solved by #3591. 

I tried to keep the fix for this issue separate in #3585. But it ended up in #3591 too which has been merged already.

So I'm closing this issue now and #3585 too.
