### ISSUE TITLE
User registration form, does not return error messages localized

### ISSUE THREAD

**Issue by goellner** [statamic/cms#3568]
## Bug Description
The error messages in a user registration form (https://statamic.dev/tags/user-register_form#example) are not localized and always show the english value.

## How to Reproduce
```
    'sites' => [

        'default' => [
            'name' => 'de',
            'locale' => 'de_DE',
            'url' => '/',
        ],

        'en' => [
            'name' => 'en',
            'locale' => 'en_US',
            'url' => '/en/',
        ],
    ],
```

add a user registration form
when your default is not english, the validation errors are not translated

## Extra Detail
haven't tested what happens, when the default is english and the second one is german for example

## Environment

Statamic 3.1.7 Pro
Laravel 8.33.1
PHP 7.4.15
aryehraber/statamic-captcha 1.4.0
jonassiewertsen/statamic-livewire 2.5.0
spatie/statamic-responsive-images 2.5.3
statamic/seo-pro 2.1.5

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by goellner** [comment]
Same issue with the login form too

**Comment by jasonvarga** [comment]
Front end validation translations are managed outside of Statamic.

https://github.com/Laravel-Lang/lang/blob/master/locales/de/validation.php

Put this into `resources/lang/de/validation.php`
