### ISSUE TITLE
The title 'Create Entry' should be customisable

### ISSUE THREAD

**Issue by arthurperton** [statamic/cms#3569]
## Bug Description

It says 'Create Entry' on the button for a new entry and as a title above the create entry form. For us developers it is clear what is meant, but for a user who is managing Shoes or Blog Posts for example, the word Entry can be sort of generic / meaningless / confusing.

It would be better to be able to optionally customise this text, just like you can with 'Add Row' for Grids. 

If I remember correctly, you could customise the 'Create Entry' text in v2.

## How to Reproduce
Add an entry to a collection.

## Environment

Statamic 3.1.9 Pro
Laravel 8.35.1
PHP 7.4.16
No addons installed

**Install method (choose one):**
Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
I had a look at one of my v2 sites last night but I can't see a text input for it in the CP, do you know if it was a hidden setting?

**Comment by arthurperton** [comment]
Good thing you looked at it.

I also still have a v2 site in production, just browsed through the source code and there is actually no such setting. It was just that the text / translation for the title would show e.g. 'New Shoe' instead of 'New Entry' button:

```php
    'create_entry_button' => 'Create Entry',
    'create_entry' => 'New :noun',
```  

where  :noun would be replaced by the fieldset tittle.

**Comment by duncanmcclean** [comment]
Ah gotcha, that's about all I could see to. 

I'll have a look at adding this setting over the weekend!

**Comment by arthurperton** [comment]
Nice!!
