### ISSUE TITLE
Can't clear Stache

### ISSUE THREAD

**Issue by Lampone** [statamic/cms#3587]
## Bug Description
Running `php artisan statamic:stache:clear` throws an error if users are stored in eloquent. 

I think it is because commit 6454e620c50a3191ed69279c61fa79ef838b35dd commented out the users config for the stache. 
If I comment the users config `statamic/cms/config/stache.php` the `stache:clear` command works again. 

## How to Reproduce
Stores users in DB and try to clear the stache. 

## Extra Detail

```
  Call to undefined method Statamic\Auth\Eloquent\User::initialPath()

  at vendor/statamic/cms/src/Stache/Stores/UsersStore.php:40
    36|         }
    37|
    38|         $user = User::make()
    39|             ->id($id)
  > 40|             ->initialPath($path)
    41|             ->email(pathinfo($path, PATHINFO_FILENAME))
    42|             ->preferences(array_pull($data, 'preferences', []))
    43|             ->data($data);
    44|

```

## Environment

Statamic 3.1.10 Pro
Laravel 7.30.4
PHP 7.4.16
pecotamic/sitemap 1.2.1
statamic/eloquent-driver 0.1.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
'php artisan cache:clear' should work as an alternative. It clears the Stache, amongst other things.

**Comment by jasonvarga** [comment]
If you're storing users in Eloquent, get rid of your user yaml files.
