### ISSUE TITLE
Section tags broken per example in docs as of 3.1.10

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#3594]
## Bug Description

When I updated to 3.1.10, it broke my section tags which were formatted per the [docs](https://statamic.dev/tags/section#content) to include the name in the closing tag.

```
{{ section:hero }}
   Stuff
{{ /section:hero }}
```

However, noticed in some examples that people weren't including the name in the tag. Tested and it corrected the issue.

```
{{ section:hero }}
   Stuff
{{ /section }}
```

So, I'm good for now – was just curious whether the docs just needed to be updated or it was an inadvertent change, etc.

## Environment
**Statamic** 3.1.10 Solo
**Laravel** 7.30.4
**PHP** 7.4.16
**aryehraber/statamic-captcha** 1.4.0
**spatie/statamic-responsive-images** 2.5.3
**statamic/migrator** dev-master

**Install method (choose one):**
- Migrated from V2 app

**Comment by taylorcammack** [comment]
**UPDATE:**  Sorry, I was wrong. When I amended the tags to the second example, it was parsing the content, but per `template_content` not `yield` so something is buggy.

**Comment by jasonvarga** [comment]
Are you saying we document it without the name in the closing tag?

```
{{ section:hero }}
   Stuff
{{ /section }}
```

Where?

**Comment by taylorcammack** [comment]
No, the docs are correct. In trying to debug this issue, I saw a snippet [here](https://github.com/statamic/cms/issues/3286), the `{{ section:dark_mode }}` tag that didn't have a matching closing name.

Tried it and thought it fixed the issue, but in the last comment, updated that it didn't actually fix the problem. The parser was just ignoring the section tag and rendering in template_content.

**Comment by jasonvarga** [comment]
That snippet was a mistake. Just a crappy copy/paste. It should have had a matching closing tag.

**Comment by taylorcammack** [comment]
Gotcha, yeah I figured.

So, my problem is, going from 3.1.9 > 3.1.10 broke the section tags which are formatted according to the documentation.

**Comment by jasonvarga** [comment]
You're right 👍

**Comment by jasonvarga** [comment]
Does it work correctly if you disable debugbar?

**Comment by taylorcammack** [comment]
Yep, it does
