### ISSUE TITLE
Unintended reserved fieldname: `authors`

### ISSUE THREAD

**Issue by tao** [statamic/cms#3597]
## Bug Description
I'm trying to get content from a related entry and it was working but it seems to have broken lately? I even watched the video tutorial on the relationships page in the docs and I can't seem to figure it out (https://www.youtube.com/watch?v=WWbsM5u9afc&feature=youtu.be). This worked a few months ago on my site during the beta so it seems to have stopped working or there was a breaking change?

On my site I'm trying to get speeches by an author, in the example I've attached I'm using actors and scenes.

```
---
id: 49b15bb0-dadf-4304-86b5-8c558f2e8f8e
title: 'Nulla facilisi.'
authors:
  - e16fb069-21a0-4b3a-adaf-a648ae89fa2e
  - 9f7ff95d-c345-4440-9c7c-507feb7f4868
  - 3f2812bb-641e-4be3-92a6-c100b9e44694
updated_by: e80058c6-d4d1-404f-9789-a9d00dd9cbae
updated_at: 1619468096
---
```

The authors are all very simple:

```
---
id: e16fb069-21a0-4b3a-adaf-a648ae89fa2e
title: Morpheus
updated_by: e80058c6-d4d1-404f-9789-a9d00dd9cbae
updated_at: 1619468024
---
```

On the homepage (in the example) I have a bunch of different ways I've tried to get the related authors but none seem to work. I know this used to work on my site in the past but it seems it stopped working recently. 

For example I'm just trying to filter collections where the author exists:

```
  <h4 class="text-3xl text-purple-700">Scenes with (authors:contains) Neo</h4>
  <ul class="space-y-8 divide-y divide-dashed">
  {{ collection:articles authors:contains="9f7ff95d-c345-4440-9c7c-507feb7f4868" as="entries" }}
    {{ if no_results }}
      No results.
    {{ /if }}

    {{ entries }}
    <li>
      <span class="text-lg font-bold">{{ title }}</span>
      <span class="text-indigo-700">{{ authors }} {{ title }} {{ /authors }}</span>
    </li>
    {{ /entries }}
  {{ /collection:articles }}
  </ul>
  ```
  
  Nothing seems to be returned, and even if I visit the articles page (in the example repo) I'm unable to list the authors
  
  ```
  <ul>
    {{ authors }}
      <li>{{ title }} | {{ value }} | {{ id }}</li>
    {{ /authors }}
  </ul>
```

Was there a breaking change I missed? Am I doing something wrong? What's going on...

## How to Reproduce
I have an example repo here: [statamic-relationships](https://github.com/tao/statamic-relationships)

## Environment
Statamic 3.1.10 Solo
Laravel 8.38.0
PHP 8.0.3
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Looks like this was introduced in 3.1 as part of the entry author permissions feature.

This issue specifically looks like an unintentional change, though. We'll sort something out shortly.

But, 3.1 will be the place where it changed for you, if you need somewhere to roll back to in the mean time.

**Comment by jackmcdade** [comment]
In the mean time you could also rename your entries field from `authors` to anything else and it'll work as you're intending.

**Comment by tao** [comment]
Great, I tried this out with the recent update. It seems to print the authors now but filtering with `authors:contains="{id}"` is still giving me an issue. If I update the field to `team` then it works fine. So not sure if you want to take another look at this or just add something to the docs that `authors` is a reserved word for more complicated logic.

**Comment by jasonvarga** [comment]
Thanks. I don't want it to be reserved. I'll sort it out.
