### ISSUE TITLE
Collection pagination not functional in Control Panel

### ISSUE THREAD

**Issue by globalexport** [statamic/cms#3611]
The CP collection pagination stopped working. 
Every page link of the pagination control is returning the JSON data of the first page only, although the query parameter is requesting another set of data. 

Example GET address: 
```
https://domain/cp/collections/blog/entries?sort=date&order=asc&page=2&perPage=10&search=&filters=e30%3D&columns=title,slug
``` 

<img width="1443" alt="Bildschirmfoto 2021-04-28 um 18 47 12" src="https://user-images.githubusercontent.com/70586640/116442451-ccb30100-a852-11eb-8066-0843cf771581.png">

## Environment
Statamic version: 3.1.10 (bare installation; updated multiple times since genesis)
PHP version: 7.4

**Comment by jackmcdade** [comment]
Did anything change on your server? Like is there any chance you have some htaccess or nginx rule that be affecting query parameters or anything like that?

**Comment by globalexport** [comment]
Hi Jack!

I am using nginx for dev and prod environment. No special configuration of query param handling on both machines as far as  I see. Nothing has changed over the weeks. 

This is the essential part of my nginx config (docker):

```
location / {
    absolute_redirect off;
    try_files $uri $uri/ /index.php?$query_string;
}

location @rewrite {
    rewrite ^ /index.php;
}

location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass unix:/run/php-fpm.sock;
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_intercept_errors off;
    fastcgi_read_timeout 10m;
    fastcgi_param SERVER_NAME $host;
    fastcgi_param HTTPS $fcgi_https;
}
```

**Comment by globalexport** [comment]
Oh dear, 
I found out what the reason was. 
I followed a tutorial on SSG ([here](https://gist.github.com/jasonvarga/256f293f8f55bf564c907a335a2f40f3)).
This messed up my CP pagination... 

Sorry for the distraction and thank you for taking your time!

**Comment by jackmcdade** [comment]
Glad you got it sorted out!
