### ISSUE TITLE
Additionally added multiline text content corrupts multiline text content by adding dashes

### ISSUE THREAD

**Issue by grischaerbe** [statamic/cms#3612]
## Bug Description

When a blueprint contains a multiline text field like "Code" or "Textarea" and with an existing entry these fields are at first left blank but later get filled out with multiline text, the three dashes that normally mark the end of the document (not really sure what they are actually for…) are now treated as if they belong to the content of the multiline text field and end up as part of the multiline text field content.

## How to Reproduce

- Make a brand new `statamic/statamic installation
- Make a new collection
- Edit the blueprint
- Add a field of type "Code" or "Textarea" to it
- Create a new entry in that collection without entering content in that multiline text field and save it
- Open the entry again, enter multiline text (you need to enter multiple lines) and save the entry
- Open the resulting .md file, it should look like this:
```md
---
id: XXX
title: 'Hello World'
updated_by: XXX
updated_at: XXX
css: |-
  I am a
  multiline text---
```

## Extra Detail
This bug only appears when the multiline text added to the .md file is the last one and also only if it's actual multiline content.
It also get even wilder when the three dashes are already added to the end of a multiline text and the .md file looks like this:
```md
---
id: home
...
textarea: |-
  hello world
  i am a text---
```
If there's another field in the blueprint and the entry does not hold any value for it yet, it gets added below the dashes and corrupts the file (the last line represents the newly saved contents of the default "Content" field that is present in fresh blueprints):
```md
---
id: home
...
textarea: |-
  hello world
  i am a text---
The clients won't like this.
```

## Environment

- Statamic 3.1.11
- Laravel 8.38.0
- PHP 8.0.3

**Statamic version:** 3.1.11

**PHP version:** 8.0.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Those triple dashes are part of the YAML syntax, indicating the end of the front matter and the beginning of the markdown area. Do you need triple dashes in your content or are you just tinkering around?

**Comment by jasonvarga** [comment]
It's reproducible 👍 

Feels like maybe the regex we use to find the front matter fences need a little more cleverness.

**Comment by jackmcdade** [comment]
Yeah, probably a simple start-of-line qualifier would work.
