### ISSUE TITLE
Cannot combine modifier where and count.

### ISSUE THREAD

**Issue by SimonMauvaisGarcons** [statamic/cms#3613]
## Bug Description
Hi,
I'm trying to `count` the number of items in an array base on the `where` modifier.  

`{{ grid | where="is_active:1" | count }}`

## How to Reproduce

- Create a grid field in the control panel.
- Add a toggle `is_active` to each item. 
- In your template:

`{{ grid | count }}` -> Output for exemple 5 (This is good)

`{{ grid | where="is_active:1" | count }}` -> Expected result 3 but .. the output nothing or break the next `if` statement.

## Environment

**Statamic version:** 3.1.10 Pro
**Laravel** 8.35.1
**PHP version:** 8.0.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
You're combining modifier syntaxes. Use one or the other.

```
{{ grid where="is_active|1" count="true" }}
or
{{ grid | where:is_active:1 | count }}
```
