### ISSUE TITLE
Can't disable dashboard link in CP sidebar

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#3615]
## Bug Description

Adding this
```
  {
        Nav::extend(function ($nav) {
            $nav->remove('Content', 'Dashboard');
        });  
    }
```

to `app/Providers/AppServiceProvider.php` doesn't remove the dashboard link.

However, this does work
```
  {
        Nav::extend(function ($nav) {
            $nav->remove('Content', 'Globals);
        });  
    }
```

## How to Reproduce
I've changed the start page in ` cp.php` to use `start_page' => 'collections/pages`. So the dashboard link in the sidebar isn't required.

## Environment

Statamic 3.1.11 Pro
Laravel 8.33.1
PHP 7.4.11
rias/statamic-data-import 1.1.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
The Dashboard isn't part of the 'Content' section which will be why it's not working.

**Comment by edalzell** [comment]
You remove it like this:

```php
            Nav::extend(function ($nav) {
                $nav->remove('Top Level', 'Dashboard');
            });
```

Put that in your app service provider.
