### ISSUE TITLE
`authors` field renders as IDs instead of users

### ISSUE THREAD

**Issue by LloydThinks** [statamic/cms#3646]
## Bug Description

I have a collection called Publications, with various fields such as "authors" and "awards". On my homepage, I display `{{ awards }} {{ title }} {{ /awards }}` and `{{ authors }}{{ first_name | first:1 }} {{ last_name }}{{ /authors }}`. Prior to the update, both of these worked and displayed the details of those two entry arrays. Now, the "authors" entry array is showing IDs for each item, and not objects. I found this out through the use of `{{ dump:awards }}` `{{ dump:authors }}`. Here is that output:

```
Statamic\Entries\EntryCollection {#7598 ▼
  #items: array:1 [▼
    0 => Statamic\Entries\Entry {#7275 ▶}
  ]
}
array:2 [▼
  0 => "9abd190d-dfe0-4b2b-944b-6df09d85e5a3"
  1 => "d5c28c98-6e14-477e-8010-4d222e4a2b19"
]
```

Why has the authors array suddenly become just IDs? This was working before the upgrade, so this is strange. Is there a way to save my data and not recreate this field and adding all of my authors to every paper again?

## How to Reproduce

I don't think you can. I tried adding the authors field again, and this new field (added after the update) shows the authors.

## Environment

Statamic 3.1.11 Solo
Laravel 6.20.15
PHP 8.0.5
statamic/ssg 0.6.0

Starter kit: Cool Writings

**Comment by jasonvarga** [comment]
Looks like I didn't quite do #3599 correctly.

>  I tried adding the authors field again

Is this new field named `authors`?

**Comment by LloydThinks** [comment]
Yes, it is named `authors`.

**Comment by LloydThinks** [comment]
No, the new field is called `authorsagain`. The old field is still called `authors`.

**Comment by jasonvarga** [comment]
This is only an issue for `authors` specifically. 👍 I'll fix it.
