### ISSUE TITLE
trans_choice doesn't work

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3649]
## Bug Description
There's an issue with the `key` parameter of the `{{ trans_choice }}` tag. It returns an integer instead of a string. It's an easy fix. Will do a quick PR.

## How to Reproduce
Try to use `{{ trans_choice key="something" }}`. It will return `0`.

## Environment
Statamic 3.1.11 Pro
Laravel 8.40.0
PHP 7.4.16
aerni/livewire-forms dev-main
jonassiewertsen/statamic-livewire 2.5.0

**Comment by jasonvarga** [comment]
Fixed by #3650
