### ISSUE TITLE
Grid Field: 'Add Row' button disappears when min rows is reached

### ISSUE THREAD

**Issue by aj-adl** [statamic/cms#3654]
## Bug Description

When a Minimum Rows AND Maximum Rows value is set for the grid field, the 'add row' button will disappear / hide itself in the editor when the Minimum rows number is reached, rather than the Maximum Rows.

## How to Reproduce

Create a Grid field, set a min and max, try to use it.

Additional things that may contribute - Grid field is within a Replicator Set

## Extra Detail

Works -https://share.getcloudapp.com/GGuQegzR
Works -  https://share.getcloudapp.com/WnuYWvDp
Doesn't work - https://share.getcloudapp.com/WnuYWvDQ
Example of the Admin UI being borked - https://share.getcloudapp.com/o0u6Ad9L

## Environment

**Statamic version:** 3.0.11

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
For the life of me I cannot recreate this.

**Comment by arthurperton** [comment]
I think this might have been fixed by PR #3782 (version 3.1.18).

**Comment by jasonvarga** [comment]
Yeah this issue doesn't mention its a grid inside a replicator (but it's in the video). I think Arthur is right.

**Comment by aj-adl** [comment]
@jasonvarga it's the second line "How to reproduce" - Is that not clear enough?
