### ISSUE TITLE
Switching to date range returns "strlen() expects parameter 1 to be string, array given"

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#3655]
## Bug Description
Can't save entry with date range after switching date field mode.

## How to Reproduce
- add events collections with the `date: true`
- switch field in blueprint to `mode: range`
- create one with different start date and end date and try to save

## Extra Detail
<img width="570" alt="Bildschirmfoto 2021-05-06 um 10 06 55" src="https://user-images.githubusercontent.com/6337411/117263779-e8ba3200-ae52-11eb-962b-f940e57f918c.png">
<img width="320" alt="Bildschirmfoto 2021-05-06 um 10 07 03" src="https://user-images.githubusercontent.com/6337411/117263783-e9eb5f00-ae52-11eb-9f6d-03e9907bfc1a.png">

vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php#413
<img width="1129" alt="Bildschirmfoto 2021-05-06 um 10 49 32" src="https://user-images.githubusercontent.com/6337411/117269661-c6c3ae00-ae58-11eb-8636-93eb2f706e36.png">

## Environment

Statamic 3.1.11 Pro
Laravel 8.40.0
PHP 7.4.15
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Oh you can't have the actual `date` field be a range.

We'll probably want to make that UX better to prevent that, but for now, just don't choose range.

**Comment by j3ll3yfi5h** [comment]
> Oh you can't have the actual `date` field be a range.
> 
> We'll probably want to make that UX better to prevent that, but for now, just don't choose range.

- I've choosen the date field, because of it's behavior:
<img width="990" alt="Bildschirmfoto 2021-05-06 um 21 23 48" src="https://user-images.githubusercontent.com/6337411/117354253-6b71da00-aeb1-11eb-8ded-efd317397815.png">

- But I also need a range, because there are multi-day events
- And there is also this issue #2441 which tells, that sorting with range fields is not possible

Any other ideas to handle my case?

**Comment by jasonvarga** [comment]
You can use a date field, but just don't call it `date`.
