### ISSUE TITLE
Grid field doesn't respect the column widths

### ISSUE THREAD

**Issue by JayGeorge** [statamic/cms#3656]
## Bug Description

When adding a grid field type, the width for each field seems to have no effect. It's probably easiest to look at the two screenshots attached to understand this problem.

## How to Reproduce

1. Create a grid field type in a blueprint
2. Add two text fields and an asset field, for example
3. Set the two text fields to be 33% in width, and the icon to be 25% in width, for example
4. Go back to the entry to see that these widths have no effect on the grid

## Extra Detail

<img width="1005" alt="Set Grid column widths" src="https://user-images.githubusercontent.com/693601/117287117-e9a69000-ae61-11eb-9467-958ba8f99e44.png">
<img width="784" alt="No effect on grid" src="https://user-images.githubusercontent.com/693601/117287123-eca18080-ae61-11eb-866d-1423b4b910d5.png">

## Environment

Statamic 3.1.11 Solo
Laravel 8.40.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by JayGeorge** [comment]
**Update** I've just noticed that if I switched the `Mode` to 'Stacked' it works. Maybe this is working as intended? Or maybe there should be a note to say that the width % are only applicable to stacked mode.

**Comment by jasonvarga** [comment]
Nah, I think it should work for both.

**Comment by arthurperton** [comment]
Yes it would definitely be nice to have some control over the grid column widths in table mode too. I have been wondering what a suitable method would be.

How would you expect these percentage settings to work for a table? What if they don’t add up to or exceed 100%? And what if you need for example a 10% or 15% column?
