### ISSUE TITLE
Fieldtype Link set to URL seems empty

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#3659]
## Bug Description
When selecting URL and entering anything in the input field when editing a page it is set to "None" the next time you edit the page. Data is stored in the .yaml file, but still confusing. Link entry is working fine.

## How to Reproduce
1) Add a fieldtype Link to a blueprint
2) Edit the page where the blueprint is used, select URL and enter anything
3) Save the page
3) Open the page again, and the Link select is set to None

## Extra Detail
n/a

## Environment
Statamic 3.1.11 Pro
Laravel 8.31.0
PHP 7.4.16
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Already fixed in #3637, will be in the next release.

**Comment by espenlg** [comment]
Sorry 🙈  Next time I'll search in closed issues too :)
