### ISSUE TITLE
Bard link selector shouldn't show entries for collections without a route

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3668]
## Bug Description
The new link selector for bard where you can select an entry shows entries where the collection has no route defined. Those shouldn't be visible.

## How to Reproduce

1. Add a collection without a route.
2. Add one or more entries.
3. Go to Bard
4. Create a link
5. Select the radio button for Entry
6. See entries without a route.

## Environment

Statamic 3.1.12 Pro
Laravel 8.40.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by arthurperton** [comment]
Just a note / workaround: You can hand-pick the collections you want to be available in the Bard field config. If you don't, all collections will be available. This behavior hasn't been changed by the new link selector.
