### ISSUE TITLE
Content API | Select field returns the same value for all 3 items

### ISSUE THREAD

**Issue by RobbertUpgraders** [statamic/cms#3681]
## Bug Description
Select field returns the same value for value, key and label. 

## How to Reproduce
Create a select field with
key: 0 value: Something
key: 1 value: Something
key: 2 value: Something

and return this using the content api

## Extra Detail
![image](https://user-images.githubusercontent.com/75248241/117657286-ac137100-b199-11eb-9d6c-10b59a8141f1.png)
![image](https://user-images.githubusercontent.com/75248241/117657419-cfd6b700-b199-11eb-911d-bf0b7e97085c.png)

## Environment

Statamic 3.1.12 Pro
Laravel 8.36.2
PHP 7.4.16
No addons installed

**Statamic version:** 3.0.{?}

**PHP version:** 7.{?}

**Install method (choose one):**
- Other (please explain this magic!)
Pretty much a clone of statamic repo but with adjusted configs etc

**Comment by jasonvarga** [comment]
Essentially #2215

This is because the values are 0, 1, 2
