### ISSUE TITLE
simple OR/AND condition does not work 

### ISSUE THREAD

**Issue by lostika86** [statamic/cms#3685]
## Bug Description
There is a real need of checking more than one variable in conditions. 
example: when we use multisite, and we check entry id, we have to check localized and origin id.

## How to Reproduce
```
category:
  - 4734e652-c9f7-435d-aaf6-3c40abb7f040
  - 50fc0090-fa52-4d61-9365-040e5fae5a39
```

`{{ category | raw | dump }}`  
![image](https://user-images.githubusercontent.com/10046659/117795931-e723ac00-b24e-11eb-9291-4924adec91a0.png)

```
{{ category | raw | in_array:90f61f30-8994-479a-a55b-e629db2bcc68 | dump }}
{{ category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68 | dump }}
{{ category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040 | dump }}
{{ category | raw | in_array:4734e652-c9f7-435d-aaf6-3c40abb7f040 | dump }}
```
![image](https://user-images.githubusercontent.com/10046659/117796099-0b7f8880-b24f-11eb-887c-fa4363e78ba8.png)
```
{{ if category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68 or category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
// false
```

```
{{ if category | raw | in_array:90f61f30-8994-479a-a55b-e629db2bcc68 or category | raw | in_array:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
// false
```

```
{{ if category | raw | contains:50fc0090-fa52-4d61-9365-040e5fae5a39 and category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
// false
```

## Extra Detail

```
{{ if category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68 or category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
    <small>I need some trust ...</small>
    {{ else }}
    <small>Sry, no time for basics ... </small>
    {{ /if }}
    <br>
    <div>category | raw | in_array:90f61f30-8994-479a-a55b-e629db2bcc68 or category | raw | in_array:4734e652-c9f7-435d-aaf6-3c40abb7f040</div>
    {{ if category | raw | in_array:90f61f30-8994-479a-a55b-e629db2bcc68 or category | raw | in_array:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
    <small>I need some trust ...</small>
    {{ else }}
    <small>Sry, no time for basics ... </small>
    {{ /if }}
    <br>
    <div>category | raw | contains:50fc0090-fa52-4d61-9365-040e5fae5a39 and category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040</div>
    {{ if category | raw | contains:50fc0090-fa52-4d61-9365-040e5fae5a39 and category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040 }}
    <small>I need some trust ...</small>
    {{ else }}
    <small>Sry, no time for basics ... </small>
    {{ /if }}

```
dump is:
![image](https://user-images.githubusercontent.com/10046659/117797347-328a8a00-b250-11eb-94bf-7b86f483ad05.png)

(looks like) same (old) issues: [ #2655](https://github.com/statamic/cms/issues/2655), [#3624](https://github.com/statamic/cms/issues/3624)
## Environment

Statamic 3.1.11 Pro
Laravel 8.40.0
PHP 7.3.12
doublethreedigital/duplicator 1.3.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
@JonKaric has the answer right there — you need to group those sets of vars+modifiers with parenthesis and you should be good to go. Feel free to reopen if that doesn't do it!

**Comment by lostika86** [comment]
> Have you tried adding parenthesis? (https://statamic.dev/antlers#modifiers-inside-conditions)

I tried many variations, .. nothing helps.

**Comment by lostika86** [comment]
> @JonKaric has the answer right there — you need to group those sets of vars+modifiers with parenthesis and you should be good to go. Feel free to reopen if that doesn't do it!

I tried many variations, before I posted. Not every are posted here, but I tried to be descriptive to replicate issue. 

These combinations does not work:
```
   {{ category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68 | dump }}  // true

    {{ if (category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68) or (category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040) }}
    <p>I wanna see you, really ...</p>
    {{ /if }}

    {{ if ((category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68) or (category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040)) }}
    <p>I wanna see you, really ...</p>
    {{ /if }}

    {{ if (category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68) OR (category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040) }}
    <p>I wanna see you, really ...</p>
    {{ /if }}

    {{ if ((category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68) OR (category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040)) }}
    <p>I wanna see you, really ...</p>
    {{ /if }}
```

**Comment by JonKaric** [comment]
@lostika86 Could you try this... 

`{{ if (category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68) == true || (category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040) == true }}`

**Comment by lostika86** [comment]
> {{ if (category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68) == true || (category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040) == true }}

```
   {{ if (category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68) == true || (category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040) == true }}
        <p>Try .. </p>
    {{ /if }}
``` 
throws error 
![image](https://user-images.githubusercontent.com/10046659/119489762-51167800-bd5c-11eb-9b24-c2a694b42b50.png)

**Comment by lostika86** [comment]
another with more parenthesis
```
    {{ if ((category | raw | contains:90f61f30-8994-479a-a55b-e629db2bcc68) == true) || ((category | raw | contains:4734e652-c9f7-435d-aaf6-3c40abb7f040) == true) }}
        <p>Try .. </p>
    {{ /if }}
```
![image](https://user-images.githubusercontent.com/10046659/119490008-9a66c780-bd5c-11eb-9eb0-ba1f0ceada1e.png)

**Comment by jackmcdade** [comment]
Just FYI, Antlers doesn't support nested parenthesis.

**Comment by lostika86** [comment]
Nesting parenthesis was only a try, ... but good to know. Thank you
