### ISSUE TITLE
Breadcrumbs aren't working behind reverse proxy

### ISSUE THREAD

**Issue by CiiDyR** [statamic/cms#3696]
## Bug Description
When you run statamic behind a reverse proxy breadcrumbs no longer generate properly. You only get the Homepage (if you include it) and that's it.
This causes large issues when you deploy statamic in High Availability like on Kubernetes or just alongside many other docker containers with something like https://hub.docker.com/r/jwilder/nginx-proxy in front of it.

I did some investigating and it turns out statamic doesn't respect Forwarded-* headers when determining if a request came over http or over https.

The `URL` Facade returns a http SiteUrl, which in turn produces a mismatch in the `Nav::breadcrumbs()` method. 

#3695 should fix this by simply using Laravel's request class to determine https or http.

## How to Reproduce
Install a fresh statamic/statamic project, configure a nested navigation, configure a reverse proxy to terminate https:// and forward the internal requests to a http:// backend. 
Configure `APP_URL` in `.env` to the https:// address so statamic / Laravel generate most URLs correctly.
Use `{{ nav:breadcrumbs }}`, you'll only see the home link if you chose to `include_home="true"`. 

## Environment

```
Statamic 3.0.49 Pro
Laravel 8.41.0
PHP 7.4.11
optimoapps/statamic-bard-text-align 1.0.2
```

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Thanks for the issue! Although, please try to keep to the issue template when creating future issues. 😄

**Comment by duncanmcclean** [comment]
We've actually just run into this issue as well... hopefully the PR is merged soon 🙂
