### ISSUE TITLE
Updater changelog always shown "N/A" in control panel.

### ISSUE THREAD

**Issue by DanielKaemmerling** [statamic/cms#3697]
## Bug Description
`src/Updater/Presenters/GithubReleasePresenter.php`

```php
public function toHtml()
{
    $string = Html::markdown($this->githubRelease ?: '- [na] Changelog unavailable.');

    // TODO: Move to blade or vue? Or leave in presenter?
    // TODO: Create tailwind classes for these labels.
    $string = Str::replace($string, '[new]', '<span class="label" style="background: #5bc0de;">NEW</span>');
    $string = Str::replace($string, '[fix]', '<span class="label" style="background: #5cb85c;">FIX</span>');
    $string = Str::replace($string, '[break]', '<span class="label" style="background: #d9534f;">BREAK</span>');
    $string = Str::replace($string, '[na]', '<span class="label" style="background: #e8e8e8;">N/A</span>');

    return $string;
}
```

The `githubRelease` variable contains the markdown from GitHub release page. The `Str::replace` parameter signature is `search`,  `replace` and `subject` . The code tries to search the html (converted from markdown) in subject and replace it with [xxx]. Of course, he can't find anything. But the $string variable is set to new subject. The return value of this method is always `<span class="label" style="background: #e8e8e8;">N/A</span>`, because the last replace method set $string to `<span class="label" style="background: #e8e8e8;">N/A</span>`.

## How to Reproduce

Go to "Updates" section.

## Extra Detail
<img width="958" alt="Bildschirmfoto 2021-05-12 um 15 14 54" src="https://user-images.githubusercontent.com/4339392/117984274-fb8fa380-b337-11eb-912c-5ea205194f3a.png">

## Environment

Statamic 3.1.13 Pro
Laravel 8.41.0
PHP 8.0.0
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by DanielKaemmerling** [comment]
The initial content of `$string` after converting to html is: 

```html
<h2>What's improved</h2>
<ul>
<li>In Bard, display the asset container option when using the link or image buttons. <a href="https://github.com/statamic/cms/issues/3665">#3665</a>
</li>
<li>Make dropdown items links, letting you open them in new tabs. <a href="https://github.com/statamic/cms/issues/3667">#3667</a>
</li>
</ul>
<h2>What's fixed</h2>
<ul>
<li>Update tracked keys when saving and deleting <a href="https://github.com/statamic/cms/issues/3684">#3684</a>
</li>
<li>Bard link picker only show entries for collections with a route. <a href="https://github.com/statamic/cms/issues/3679">#3679</a>
</li>
<li>Separate the title and optional translation. <a href="https://github.com/statamic/cms/issues/3675">#3675</a>
</li>
<li>Fix Bard error when linked entries and assets are deleted. <a href="https://github.com/statamic/cms/issues/3678">#3678</a>
</li>
<li>Fix <code>date</code> fieldtype's <code>time_enabled</code> option <a href="https://github.com/statamic/cms/issues/3661">#3661</a>
</li>
<li>Fix <code>link</code> fieldtype alignment. <a href="https://github.com/statamic/cms/commit/83aededfe">83aededfe</a>
</li>
<li>Fix YAML fence when dumping multiline string as last key <a href="https://github.com/statamic/cms/issues/3663">#3663</a>
</li>
<li>Fix &quot;Create Fieldset&quot; button not displaying. <a href="https://github.com/statamic/cms/issues/3645">#3645</a>
</li>
</ul>
```

**Comment by jasonvarga** [comment]
The string replace code seems to be fine. 

I'm not sure why you're not getting changelogs though. Can you clear your cache and view the page again?

**Comment by DanielKaemmerling** [comment]
All done, nothing changes.

```php
$string = Html::markdown($this->githubRelease ?: '- [na] Changelog unavailable.');
// $string = <h2>What's improved</h2>...
$string = Str::replace($string, '[new]', '<span class="label" style="background: #5bc0de;">NEW</span>');
// $string = <span class="label" style="background: #5bc0de;">NEW</span>
$string = Str::replace($string, '[fix]', '<span class="label" style="background: #5cb85c;">FIX</span>');
// $string = <span class="label" style="background: #5cb85c;">FIX</span>
$string = Str::replace($string, '[break]', '<span class="label" style="background: #d9534f;">BREAK</span>');
// $string = <span class="label" style="background: #d9534f;">BREAK</span>
$string = Str::replace($string, '[na]', '<span class="label" style="background: #e8e8e8;">N/A</span>');
// $string = <span class="label" style="background: #e8e8e8;">N/A</span>

return $string; // <span class="label" style="background: #e8e8e8;">N/A</span>
```

I think that's not the behavior you want, is it?

**Comment by jasonvarga** [comment]
Ah I see what's happening, sorry.

Laravel 8.41.0 was just released, and includes a new Str::replace method, which overrides the one we previously were using. https://github.com/laravel/framework/releases/tag/v8.41.0

Nice find, thanks!

**Comment by DanielKaemmerling** [comment]
Oh! I did not see that on Laravel release notes. I create a pull request for that.

**Comment by jasonvarga** [comment]
No worries, I got it!

**Comment by mariordev** [comment]
I'm having the same issue, and I'm stuck in version 3.1.11. Whenever I try to upgrade or downgrade I get this error. Any suggestion as to how to get unstuck? Thanks!

![Screen Shot 2021-05-17 at 4 12 55 PM](https://user-images.githubusercontent.com/10860234/118567579-e4cbc100-b72a-11eb-9c9b-d7f6d9a2f5af.png)

**Comment by duncanmcclean** [comment]
Try and update manually with 'composer update'

**Comment by mariordev** [comment]
That worked. Thank you!
