### ISSUE TITLE
SVGs, once again, don't have dimensions

### ISSUE THREAD

**Issue by xjoke** [statamic/cms#3700]
## Bug Description

After getting access to SVG dimensions (#2865) and fixing parsing problems (#3479), they were taken from us once more (#3609) a fortnight ago. Please give them back to us 🙏 

https://github.com/statamic/cms/blob/595e191b956cca731cb604788bc18aad9b3dbf45/src/Assets/Asset.php#L534-L538

https://github.com/statamic/cms/blob/595e191b956cca731cb604788bc18aad9b3dbf45/src/Assets/Asset.php#L586-L590

## Environment

Statamic 3.1.13 Pro
Laravel 8.41.0
PHP 7.4.16

**Comment by duncanmcclean** [comment]
I'm guessing (not tested this) that if you add `svg` to this array, it starts working again?

https://github.com/statamic/cms/blob/3.1/src/Assets/Asset.php#L345

**Comment by xjoke** [comment]
Yes, it does. However, since SVGs have so far been kept distinct from other images (e.g. also in the Assets Tag) it might be preferable to add `&& ! $this->isSvg()` to the conditions?

https://github.com/statamic/cms/blob/595e191b956cca731cb604788bc18aad9b3dbf45/src/Tags/Assets.php#L140-L142

**Comment by duncanmcclean** [comment]
Good catch, that's probably a better fix. Feel free to submit a pull request.
