### ISSUE TITLE
data() is empty for localized entries.

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#3708]
## Bug Description

I have a multisite collection called locations - The fields are not localizable.

I am getting the collection for a Livewire component like so:

```
$locations = Entry::query()
  ->where('collection', 'locations')
  ->where('locale', Site::current()->handle())
  ->get();
```

And when I want to retrieve field data I do it like so:

```
foreach($locations as $location) {
  $location->data()->get('coordinates')
}
```

This has worked fine but there's something strange happening with the multisite:
* My entry query works perfectly:
  - The correct locations are returned per site.
  - If I created a localized version of a location on another site then it is returned correctly also.
* **The data() function is not working correctly:**
  - data() is returned correctly for non-localized entries
  - **data() is empty for localized entries**

In my screenshot below the .ie entry's data() is empty - only updated_by and updated_at are available, but if I look at this same entry on the .co.uk website the data() is fully available and I can access all fields.

![image](https://user-images.githubusercontent.com/20210934/118110184-03a01f80-b3da-11eb-8364-92f00ae640d8.png)

## Environment

**Statamic version:** 3.1.10

**PHP version:** 7.4.16

**Install method (choose one):**
- Existing Laravel app

**Comment by stuartcusackie** [comment]
I figured out that I can do this instead:

```
$data = $location->toAugmentedArray();
$coordinates = $data['coordinates']->raw();
```

This seems more reliable for my multisite but I'd be more inclined to use `->data()`. Can it be fixed?

**Comment by jasonvarga** [comment]
`data` is specific to the entry.
If you want to get values that fall back to the origin, use `value`.

`$entry->value('field')`

**Comment by stuartcusackie** [comment]
Oh right! I'll try that out. Thank you.
