### ISSUE TITLE
Classes attribute on fieldtype does not work on some fields in grid

### ISSUE THREAD

**Issue by hmalaud** [statamic/cms#3721]
## Bug Description
Some fieldtypes (tested on integer and toggle) do not get additional class when using `classes` on them.

## How to Reproduce
Create grid fieldtype with integer or toggle inner field and add `classes: whatever` in field's configuration in yaml.

## Environment
Mac Big Sur 11.3 (20E232)
Statamic 3.1.14 Solo
Laravel 8.41.0
PHP 8.0.2
codedge/statamic-move-entries 1.1
edalzell/variable 1.0.4

**Statamic version:** 3.1.13/14

**PHP version:** 8.0.2

**Install method (choose one):**
Statamic CLI (`statamic new ... `)

**Comment by duncanmcclean** [comment]
I wasn't aware this was a thing you could even do, is there any docs on it?

**Comment by hmalaud** [comment]
It was in v2, but still works in v3 (and is not documented): https://v2.statamic.com/fieldtypes (bottom of default settings)

**Comment by duncanmcclean** [comment]
Thanks for pointing that out - was new to me! 😆 

---

It's here 

https://github.com/statamic/cms/blob/88b5d27c71057d9e40d3bee304c98c8b8401d775/resources/js/components/fieldtypes/TextFieldtype.vue#L5

But not here:

https://github.com/statamic/cms/blob/88b5d27c71057d9e40d3bee304c98c8b8401d775/resources/js/components/fieldtypes/grid/Grid.vue#L13-L27
