### ISSUE TITLE
Empty asset folder doesn't show after reload of page

### ISSUE THREAD

**Issue by albaur** [statamic/cms#3722]
## Bug Description
When I create a folder inside the assets container and I reload the page the folder is not shown anymore. It is created inside public/assets but since it's empty I can't see it. When I create the folder and add an image to it before reloading then I see it

## How to Reproduce
Create new folder inside assets

## Environment
Statamic 3.1.9 Pro
Laravel 7.30.4
PHP 7.4.19
aryehraber/statamic-captcha 1.4.0
doublethreedigital/duplicator 1.3.1
withcandour/aardvark-seo 2.0.11

**Comment by duncanmcclean** [comment]
Sorry, I seem to be unable to reproduce this issue. When I refresh the folder is still there, even though there's nothing in it.

Could you please try updating Statamic in case that's the issue. Also, which operating system are you using?

**Comment by gilleard** [comment]
This sounds similar to an issue I was about to post.

The ttl of asset contents is cached based on the [stache.watcher config value](https://github.com/statamic/cms/blob/3.1/src/Assets/AssetContainerContents.php#L155).

With this disabled, per the docs recommendation in a production environment, new directories don't show after page reload as the cache will always be used, and it hasn't been invalidated.

We're using the s3 adapter if it makes a difference, but that class seems agnostic anyway.

**Comment by jasonvarga** [comment]
Yup, this is reproducible using the regular local driver. Just gotta make sure to disable the stache watcher.
