### ISSUE TITLE
Asset upload: The given data was invalid.  

### ISSUE THREAD

**Issue by tao** [statamic/cms#3736]
## Bug Description
On my control panel we've been getting these errors when trying to upload an image. This doesn't seem to occur on my local dev site but it's happening on the production sites.

![Screenshot 2021-05-18 at 17 02 27](https://user-images.githubusercontent.com/1446331/118675353-d51bad80-b7fa-11eb-80f9-eae0b5bb3125.png)

The response on the frontend is:

```json
POST /cp/assets HTTP/1.1
URL: https://www.llresearch.dev/cp/assets
Status: 422 Unprocessable Entity

{
    "message": "The given data was invalid.",
    "errors": {
        "file": [
            "Failed to upload."
        ]
    }
}
```

When we refresh the page though, the image appears and the thumbnail exists. I played around the the server permissions to make sure our write access is correct, and nothing appears in the `laravel.log` file so I don't have much more information on what might be causing this issue yet.

## Environment
Statamic 3.1.13 Pro
Laravel 8.41.0
PHP 8.0.2
statamic/ssg 0.6.0

**Comment by jasonvarga** [comment]
Does your field have any validation rules?

**Comment by tao** [comment]
I've only set `max_files: 1` but we deleted the previous photo before trying to upload the replacement. This is working with S3 and I'm using the same IAM profile as localhost where things are working fine. The photo is also only 2.3MB so I don't think it would be too large to upload.

The thumbnail seems to get generated in `public/img/containers` but the photo is not uploaded correctly to S3.

I'll investigating it more to see if I can narrow it down, but if you have any further insights that might help...

**Comment by tao** [comment]
I just tested it again on localhost and it's working fine. It saves the new image to S3 and generates thumbnails... so I'll need to look closer at the permissions on the server and try debug this.

**Comment by tao** [comment]
The mystery has been solved... it seems PHP 8.0 on Amazon EC2 defaults `upload_max_filesize` to 2MB instead of the 10MB that I expected it to be by default.

I'll leave this issue for you to close in-case you'd like to update the error message for when this occurs or add a note to the Statamic Asset docs with a reminder for updating `php.ini`.

**Comment by abuhurairah-aar** [comment]
I've had the same issue while using docker setup (nginx + php-fpm). Thanks for @tao update on his comment, I solved the issue by adding the additional `uploads.ini` into my php-fpm configuration.

In case you are using the same container image as mine (`php:8.0.9-fpm-alpine`) or equivalent, you may do the following:-

1. create `uploads.ini` in your preferred folder
`max_file_uploads = 50000`

2. update your dockerfile 
`ADD ./<your-preferred-folder>/uploads.ini /usr/local/etc/php/conf.d/uploads.ini`

3. restart you php-fpm service
`docker-compose up --build`

**Comment by jackmcdade** [comment]
Closing as the solution is a server config update.
