### ISSUE TITLE
Redirect to 404 page is missing translations

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3747]
## Bug Description
I've got a Laravel route for receipts. I want to redirect to Statamic's `404` page when there's no `$entry`. I'm using the same exception that Statamic's `{{ 404 }}` tag uses. The view gets rendered as expected. But the translations don't get loaded.

```php
// routes/web.php

Route::get('/emails/receipts/{id}', function ($id) {
    $entry = Entry::find($id);

    if (! $entry) {
        throw new \Statamic\Exceptions\NotFoundHttpException;
    }

    return (new PledgeCreated($entry));
})->name('receipts')->middleware('signed');
```

## How to Reproduce
1. Create a route that throws `throw new \Statamic\Exceptions\NotFoundHttpException;`
2. Retrieve a translation string in your `404.antlers.html`, e.g. `{{ trans:misc.404_title }}`

## Extra Detail
The 404 views with missing translations:

![screencapture-siloam-crowdfunding-test-emails-receipts-3cb1daa0-93ba-43af-84d8-1f7122415428-2021-05-20-15_31_31](https://user-images.githubusercontent.com/23167701/118987532-a29bbd00-b980-11eb-98a6-3a62c164dc6e.png)

## Environment
Statamic 3.1.14 Pro
Laravel 8.41.0
PHP 7.4.16
aerni/social-links 2.2.0
jonassiewertsen/statamic-livewire 2.5.0
visuellverstehen/statamic-classify 2.1.1

**Comment by jasonvarga** [comment]
Try adding `statamic.web` middleware to your route. Or at least the `Statamic\Http\Middleware\Localize` middleware.

**Comment by aerni** [comment]
Nice, that did the trick. Thanks!
