### ISSUE TITLE
Select fieldtype is missing field in CP for adding default key

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#3753]
## Bug Description
When adding fieldtype Select to a Fieldset or Blueprint, there is no place to choose the default key. It is documented (https://statamic.dev/fieldtypes/select#config-options) and can be done directly in the yaml-file, but should be available in CP as well.

## Environment
Statamic 3.1.14 Solo
Laravel 8.42.1
PHP 7.4.16
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Like you say this isn't possible in the UI, only in the YAML file at the moment. 

There's an open feature request for this so I'm closing this issue in favour of that: statamic/ideas#356
