### ISSUE TITLE
Should cached assets go to the storage folder?

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#3757]
## Bug Description
I've just enabled the asset cache in config/statamic/assets, and I noticed that all the of the glide generated images were being stored in public/img. When I pushed this change to github I noticed all of these images got added to my repo - I find this very unusual.

Shouldn't the default cache settings be something like this instead:

```
'route' => 'storage/img',
'cache_path' => storage_path('app/public/img'),
```

**Statamic version:** 3.1.14

**Install method (choose one):**
- Existing Laravel app

**Comment by jasonvarga** [comment]
The point of the cached setting is that they go into your public directory to be served directly by your web server.

Without that setting, they're still cached, but in storage.

Feel free to gitignore the directory.

**Comment by stuartcusackie** [comment]
Ah right. I thought files in storage/public could be served directly due to symlinks.

I'll try the gitignore method to be on the safe side.

Cheers.
