### ISSUE TITLE
GraphQL: query will fail with "Link to URL" nav items when title is blank

### ISSUE THREAD

**Issue by St3Ko** [statamic/cms#3758]
## Bug Description

When you add a nav item with "Link to URL" and leave the title blank, the query will fail with an internal server error:
```
Cannot return null for non-nullable field "Page.title".
```

query:
```graphql
query Nav {
  nav(handle: "main") {
    tree {
      page {
        title
        url
      }
    }
  }
}
```
## Expected Behaviour
the title field should be populated with the url, like the description says in the screenshot

## Extra Detail
[screenshot](https://d.pr/i/yO20Mq)

## Environment

Statamic 3.1.16 Pro
Laravel 8.40.0
PHP 7.3.27

**Comment by jasonvarga** [comment]
This is fixed for 3.2
