### ISSUE TITLE
Link field that links to an entry, links to the wrong site in a multisite setup

### ISSUE THREAD

**Issue by kesse** [statamic/cms#3764]
## Bug Description

Link field that links to an entry, links to the wrong site in a multisite setup.

## How to Reproduce
* Multisite setup, English (default) and Swedish
* Create a page that exists in both sites. Page A
* Add a link field in the blueprint and template for pages.
* Create another page, Page B, that exists in both sites that uses the link field to link to Page A.
* Visit Page B in English and it will link to the English version of Page A.
* Visit Page B in Swedish  and it will still link to the English version of Page A.

## Extra Detail

**Template**
`<a href="{{ link_test }}">Page link</a>`

**Blueprint**

```title: Simple
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: link_test
        field:
          display: Link
          type: link
          icon: link
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
```

## Environment

Statamic 3.1.16 Pro
Laravel 8.42.1
PHP 8.0.6
No addons installed

**Statamic version:** 3.1.16

**PHP version:** 8.0.6

**Install method (choose one):**
- Fresh install from `statamic/statamic`

Fix I did is to update Routing/ResolveRedirect.php

Row 27
From:
`$redirect = optional(Facades\Entry::find($id))->url() ?? 404;`

To:

```
$site = $parent instanceof Localization ? $parent->locale() : Site::current()->handle();
$redirect = optional(optional(Facades\Entry::find($id))->in($site))->url() ?? 404;
```

**Comment by dominikradl** [comment]
Hey @kesse,
if that fix works for you, would you like to create a PR for it? Maybe that would help the team to take a look at it.
Thank you for the fix, this is bugging me too.
