### ISSUE TITLE
Error with stache:doctor / Unconfigured indexes in entries

### ISSUE THREAD

**Issue by DrTrills** [statamic/cms#3765]
## Bug Description

When I run stache:doctor I get the following.

```
php please stache:doctor
[✓] No duplicate IDs detected.

[✗] Unconfigured indexes in entries::industries
 * status
 * redirect
 * mega_menu

[✗] Unconfigured indexes in entries::organizations
 * status
 * redirect

[✗] Unconfigured indexes in entries::solutions
 * status
 * redirect
 * mega_menu

[✗] Unconfigured indexes in entries::case_studies_and_testimonials
 * status
 * redirect

```

 Googling I came across this post https://statamic.com/forum/5352-why-does-stache-doctor-complain-about-unconfigured-indexes which seems related, but unable to find the related git issue. I believe these are errors? Or perhaps I have something wrong on my site and doctor is working a expected

## How to Reproduce
Run `php please stache:doctor`

## Environment

```
Statamic 3.1.16 Pro
Laravel 8.41.0
PHP 8.0.0
withcandour/aardvark-seo 2.0.12
```

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
They aren't errors. It's doing what it's supposed to do. Feel free to add those indexes.
https://statamic.dev/stache#configuring-additional-indexes
