### ISSUE TITLE
Illegal offset type in unset when deleting taxonomy terms

### ISSUE THREAD

**Issue by tonybyng** [statamic/cms#3775]
## Bug Description

Illegal offset type in unset

Generated when i delete a taxonomy term

## How to Reproduce

Create a taxonomy tag and then delete it (happens with more than one taxonomy handle)

## Extra Detail

The log shows

[2021-05-26 14:46:27] local.ERROR: Illegal offset type in unset {"userId":1,"exception":"[object] (TypeError(code: 0): Illegal offset type in unset at /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1483)
[stacktrace]
#0 /var/www/html/vendor/statamic/cms/src/Stache/Stores/Store.php(361): Illuminate\\Support\\Collection->offsetUnset()

I added a Log call 

\Illuminate\Support\Facades\Log::alert("alert for $key in store: ".print_r($paths,true));

in the Stache/Stores/Store.php file to track what was happening just before the unset call and when I delete something it fires twice. The first one receives a correct key (in this case "default::test2" and processes it and deletes the term correctly (but not cleared from screen - i have to refresh before i see it cleared from screen)  but then immediately after, its passing an empty array as the key and thats whats triggering the illegal offset error.

[2021-05-26 14:46:27] local.ALERT: alert for default::test2 in store: Illuminate\Support\Collection Object
(
    [items:protected] => Array
        (
            [default::test2] => /var/www/html/content/taxonomies/reg_tags/test2.yaml
        )

)
  
[2021-05-26 14:46:27] local.ALERT: alert for [] in store: Illuminate\Support\Collection Object
(
    [items:protected] => Array
        (
        )

)
  

I guess a simple "check if whats passed in is valid and good" before unsetting is an option but I suppose the proper way is to identify why its being called twice. 

## Environment

Statamic 3.1.16 Pro
Laravel 8.42.1
PHP 8.0.5
rias/statamic-data-import 1.1.2

- Existing Laravel app - running through sail on my dev box currently

**Comment by jasonvarga** [comment]
Likely related to #3739
