### ISSUE TITLE
Appending a Vue component not working

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#3778]
## Bug Description

I'm prototyping out an addon. Part of this addon means adding a Vue component to every page in the Control Panel. I found the documentation around [appending components](https://statamic.dev/extending/vue-components#appending-components). However, this does not seem to work and throws console errors.

After some digging, it turns out `$root` is null in here, not sure why but it is.

https://github.com/statamic/cms/blob/a074abbe6f6a234e5220889a7a8ea9df46656d6e/resources/js/components/Components.js#L17

I managed to find a workaround for now though - basically just doing what the helper does but on `Statamic.app` instead.

```js
Statamic.$app.data.appendedComponents.push(new Component(`appended-zippy`, 'zippy', {}))
```

## How to Reproduce

1. Attempt to append a component to the CP

```js
Statamic.$components.append('zippy', {
  props: {}
})
```

2. Hook up your script in your service provider
3. In the CP, open up the console and see red errors

## Extra Detail

![image](https://user-images.githubusercontent.com/19637309/119737985-ccb91780-be77-11eb-8875-e0371e6f9b94.png)

## Environment

```
Statamic 3.0.49 Pro (pretty sure I'm on a way newer version than this but my sandbox site is all messed up)
Laravel 8.43.0
PHP 8.0.3
doublethreedigital/duplicator 1.3.2
doublethreedigital/static-cache-manager dev-master
doublethreedigital/zippy dev-master
```

**Comment by Djoul** [comment]
Hi Duncan,

I was running into the same kind of issue and noticed that I was appending the component at the wrong place. You'll have to append the component in the 'booted()' function.

`import MyComponent from './components/MyComponent.vue'

Statamic.booting(() => {
    Statamic.$components.register('my-component', MyComponent);
})

Statamic.booted(() => {
    const component = Statamic.$root.$components.append('my-component', {
        props: { foo: 'bar' }
    });
})`

**Comment by jasonvarga** [comment]
Closing as I believe @Djoul 's explanation is correct. Let us know otherwise, Duncan.
