### ISSUE TITLE
Issue when user database users on existing project

### ISSUE THREAD

**Issue by mediabeastnz** [statamic/cms#3793]
## Bug Description
Everything apart from the users area works as expected. But the users, groups and permissions table all have this issue.

It seems that the DataList (or tables) isn't displaying the data even though it seems to have loaded it into the component.

Hard to explain so I've attached a screenshot for reference. 

## How to Reproduce
Install into existing Laravel app and use Database for users.

## Extra Detail
![Screen Shot 2021-06-02 at 12 44 42 PM](https://user-images.githubusercontent.com/909749/120407185-b859ab00-c3a0-11eb-80ac-89341b032c31.png)

## Environment
Statamic 3.1.18 Pro
Laravel 8.44.0
PHP 8.0.3
No addons installed

**Install method (choose one):**
- Existing Laravel app

**Comment by duncanmcclean** [comment]
Hmm, that doesn't look right. The rows should look like this (see the screenshot). However, your rows just seem to contain other objects, which is weird.

![image](https://user-images.githubusercontent.com/19637309/120500650-ecd96100-c3b8-11eb-8143-5cc9909729c7.png)
