### ISSUE TITLE
Global in CP nav not highlighted in a multisite

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3794]
## Bug Description
On a multisite the currently selected global page is not highlighted in the CP main navigation.

## How to Reproduce
Make a multisite site
Add global
Visit it

## Extra Detail
<img width="1538" alt="Screenshot 2021-06-02 at 09 34 56" src="https://user-images.githubusercontent.com/69107412/120442508-f7c6ce00-c385-11eb-8392-a4fc68a8ecf4.png">

## Environment
Statamic 3.1.18 Pro
Laravel 8.44.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by duncanmcclean** [comment]
Confirmed.
