### ISSUE TITLE
Login to multisite with site2.TLD shows CP with site1 as "active"

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#3796]
## Bug Description
If I login to a multisite with at least two different sites and domains, always site1 is "active".

## How to Reproduce
- Create multisite with two different domains: site1.TLD and site2.TLD
- Login to site2.TLD
- site1 is active in CP

## Environment
Statamic 3.1.18 Pro
Laravel 8.44.0
PHP 7.4.15
statamic/collaboration 0.1.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
You should only be using the control panel at the first (default) site.

**Comment by j3ll3yfi5h** [comment]
If it is used for multiple languages, I agree. But even for e.g. different (sub-)companys?

**Comment by jasonvarga** [comment]
Yes.

**Comment by j3ll3yfi5h** [comment]
What could happen/What breaks, if you use the CP over other domains than default?

**Comment by j3ll3yfi5h** [comment]
What is your approach to keep Admin A on Site A and Admin B in Site B?

**Comment by duncanmcclean** [comment]
Closing in favour of the feature request: statamic/ideas#737
