### ISSUE TITLE
Unclear when the fieldset stays in sync

### ISSUE THREAD

**Issue by JonKaric** [statamic/cms#3798]
## Description

Currently, when you attach a single field from a fieldset into a blueprint, the stack selector opens up the settings from the fieldset you've imported. 

Changing the values will overwrite the values you've imported, but:
- Just for the settings you've changed
- And just for that field, **not the original fieldset**. 

This contradicts the '_Changes to this field will stay in sync_' message if you're changing it from a blueprint.

I think we need some clarity that changing values from a linked fieldset inside a blueprint doesn't change the original fieldset. The docs are a bit lacking on this subject too

**Comment by duncanmcclean** [comment]
Thanks for the issue. However, please keep to the issue template in future issues. Thanks.
