### ISSUE TITLE
Storing data in Replicator field produces " Illegal string offset 'type' "

### ISSUE THREAD

**Issue by alexolder** [statamic/cms#3803]
## Bug Description
I am storing User data in a database due to project requirements outside of the CMS. 

I add a Replicator field to the User blueprint and a column to the database to accept JSON. Field gets saved correctly and when empty renders and allows data input. 

After saving and reloading the page I am presented with "Illegal string offset 'type'" when it tries to load the data. 

## How to Reproduce

Add a replicator field to User.
Add column to database to match. column data type doesn't seem to matter. 
Add data to the field and save
Reload the page

## Extra Detail
https://flareapp.io/share/Lm8pJgdm#F80

## Environment

Statamic 3.1.18 Pro
Laravel 8.44.0
PHP 7.4.18
No addons installed

- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Can you paste the content of that column for that user? I suspect it's not correct.

**Comment by alexolder** [comment]
```
[
  {
    "manufacturer": [
      "manufacturer-1"
    ],
    "model": [
      "car-1"
    ],
    "registration": "TEST1234",
    "favourite": false,
    "type": "garage",
    "enabled": true
  }
]
```

This is the JSON put in to the row. As soon as any JSON even an empty [] is in the row it throws the error.

**Comment by alexolder** [comment]
For anyone who comes across this and it probably just needs adding to the docs. If you cast the field as an array (same with taxonomies) in the User model it works as expected.

```
/**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'garage' => 'array',
    ];
```
