### ISSUE TITLE
Composer dependecy should not be required

### ISSUE THREAD

**Issue by martink635** [statamic/cms#3804]
## Bug Description
https://github.com/composer/composer/issues/9937

This issue occured on our production after a `composer install` yesterday. According to the composer maintainer, the composer dependecy is not required (since it's installed on the system anyway) and should be removed. Sadly due to this we had a downtime on our production API for over an hour.

## Environment

Statamic 3.1.18 Pro
Laravel 8.45.1
PHP 7.4.5
No addons installed

**Comment by jasonvarga** [comment]
Composer is a requirement. We use it for a bunch of different things in our codebase.
Run `composer update` in your project to get 2.1.2 where they've fixed the issue and you should be okay.
