### ISSUE TITLE
Link fieldtype lists every entry even if a collections doesn't have a route

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#3805]
## Bug Description

Using the link fieldtype lists all entries, even if a specific collection doesn't have a route.
It would be good to either choose from which collection entries are linkable or that only the ones with a route on collection level are listed.

## How to Reproduce

Edit a page in the CP with a link fieldtype.

## Environment

Statamic 3.1.18 Pro
Laravel 8.44.0
PHP 7.4.19
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 1.4.6
statamic/seo-pro 2.2.1

- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Related: statamic/ideas#562
