### ISSUE TITLE
Grid/List option in asset fieldtype has no effect

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#3806]
## Bug Description
Editing a page page in the CP with an asset fieldtype opens the file browser only in list view even if 'Grid' was selected in the Blueprint.
(And there are no preferences settings stored in the user yaml file.)

## How to Reproduce
Set up a asset fieldtype, choose 'Grid Mode' as the preferred layout style.

## Environment

Statamic 3.1.19 Pro
Laravel 8.45.1
PHP 7.4.20
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 1.4.6
statamic/seo-pro 2.2.1

- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
That setting controls the fieldtype's UI, not the browser.

eg. this vs this

![image](https://user-images.githubusercontent.com/105211/121086319-03186000-c7b1-11eb-8cb1-0655b5017940.png)

![image](https://user-images.githubusercontent.com/105211/121086370-0f042200-c7b1-11eb-920f-1e9b43e66749.png)


The user can adjust the view of the browser with the buttons at the top right:

**Comment by helloDanuk** [comment]
Ups, thanks for clarifying!
