### ISSUE TITLE
Form fieldtype - can't add more than one (even though it's kinda supported)

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#3809]
## Bug Description

If you have a `form` fieldtype, and remove the `max_items` value, you cannot add more forms to the field. However if you manually set it in the file, it shows up in the CP.

## How to Reproduce

Add a `form` fieldtype to a blueprint and remove the `1` from the `max_items`.
Try to add a second form to the field in the CP.

## Environment

```
Statamic 3.1.19 Pro
Laravel 8.45.1
PHP 7.4.20
No addons installed
```

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
I've done some digging into this. Seems like whenever you remove the `1` from the 'Max Items' config option, it removes it from the field's config, hence why it falls back to the default of 1.

A workaround for this would be to set the 'Max Items' value to a value you know will never be reached, like 100, then it should work fine.

https://github.com/statamic/cms/blob/a4ebc24bfd1e186e15f118fcfc3aee3b69eb1290/src/Forms/Fieldtype.php#L29
