### ISSUE TITLE
Entry slug changes not saved

### ISSUE THREAD

**Issue by martyf** [statamic/cms#3813]
## Bug Description
When you edit an Entry, and manually change the slug, when you save, the changes are not actually saved.

Re-opening the Entry to edit shows the old slug. The yaml file remains the old filename.

This was introduced with v3.1.19 or v3.1.20.

v3.1.18 behaves correctly and saves the Entry and slug.

## How to Reproduce
1. Do a fresh Statamic install, no starter kit, create a user
2. Create an Entry and name it "Rename Test" (slug will be "rename-test")
3. Save
4. Edit Entry, and change the slug (i.e. "rename-new-slug")
5. Save

The Entry is not renamed - the slug will be the old slug, and the yaml file has not been renamed.

## Environment

Statamic 3.1.20 Solo
Laravel 8.46.0
PHP 8.0.2

**Install method (choose one):**
Fresh install from `statamic/statamic`, no starter kit

**Comment by jasonvarga** [comment]
On it.

**Comment by jasonvarga** [comment]
3.1.21 has been tagged with this fix.
