### ISSUE TITLE
{{ get }} tag pair not working inside {{ field }}

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#3827]
## Bug Description
Try to output the get value with the tag pair inside a field.

## How to Reproduce
- Create form with e.g. a text field
- `php artisan vendor:publish --tag=statamic-forms`
- Try to output a get value with the tag pair in `views/vendor/statamic/forms/fields/text.antlers.html`

## Extra Detail
- Only the tag pair doesn't work.
- Inside the `{{ fields }}{{ /fields }}` it is working.

## Environment
Statamic 3.1.21 Pro
Laravel 8.46.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Can you show exactly how you are trying to use the `get` tag?

**Comment by j3ll3yfi5h** [comment]
Sure. I tested it like this:

```
<input type="{{ input_type ?? 'text' }}" name="{{ handle }}"{{ if placeholder }} placeholder="{{ placeholder }}"{{ /if }}{{ if old }} value="{{ old }}"{{ /if }}{{ if validate|contains:required }} required{{ /if }}>

{{ get:asdf }}
{{ get }}{{ asdf }}{{ /get }}

```

Finally it should look similar to this:
```
<input type="{{ input_type ?? 'text' }}" name="{{ handle }}"{{ if placeholder }} placeholder="{{ placeholder }}"{{ /if }}{{ if old }} value="{{ old }}"{{ elseif get }}{{ get }} value"{{ handle }}"{{ /get }}{{ /if }}{{ if validate|contains:required }} required{{ /if }}>
```

**Comment by j3ll3yfi5h** [comment]
@jasonvarga Can you confirm?

**Comment by jasonvarga** [comment]
This seems to work fine:

```
{{ get:asdf }}
{{ get }}{{ asdf }}{{ /get }}
```

When I visit `?asdf=foo` I see `foo foo`.

Is your issue because you are missing the equal sign after `value` here?

```
{{ get }} value"{{ handle }}"{{ /get }}
```

**Comment by j3ll3yfi5h** [comment]
There is a typo in the example, right, but this doesn't really matter. The output of the get tag pair inside views/vendor/statamic/forms/fields/text.antlers.html does not happen:

![Bildschirmfoto 2021-06-29 um 08 57 57](https://user-images.githubusercontent.com/6337411/123751554-2918b800-d8b8-11eb-91d8-7ab70f9db88c.png)

**Comment by jackmcdade** [comment]
Can't recreate unfortunately – feel free to reopen with an example repo and we'll get it sorted!
