### ISSUE TITLE
PHP 8 "Call to undefined function"

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#3831]
## Bug Description
Just switched to PHP 8 with the latest Statamic version and while the frontend works just fine, when trying to access the backend, I get the following error 500:

```
[2021-06-10 14:52:54] live.ERROR: Call to undefined function Statamic\Console\Processes\set_time_limit() {"exception":"[object] (Error(code: 0): Call to undefined function Statamic\\Console\\Processes\\set_time_limit() at /home/webapps/stellaprojects/releases/20210610145136/vendor/statamic/cms/src/Console/Processes/Process.php:223)
```

## How to Reproduce
I actually just switched to PHP 8 on my production server. Before that, I also changed the paths to the content folders in my `stache.php` file. The paths look like this: `'directory' => base_path('../../content/taxonomies'),`.

## Environment

Statamic 3.1.21 Pro
Laravel 8.46.0
PHP 7.4.20 (it was PHP 8 when the error occured)
aryehraber/statamic-captcha 1.5.1
jonassiewertsen/statamic-livewire 2.5.0
mitydigital/statamic-tinymce-cloud 1.0.3
octoper/statamic-inline-assets 4.0.3
pecotamic/sitemap 1.2.3

**Install method:**
- Existing Laravel app

**Comment by duncanmcclean** [comment]
Looks like the error is triggered from one of these places:

https://github.com/statamic/cms/blob/87237100aa05916d4f288ca27066e537ea80b21e/src/Imaging/ImageGenerator.php#L127
https://github.com/statamic/cms/blob/74c18fc383083a496b80ba2772cc5df92e3afaff/src/Console/Processes/Process.php#L271

**Comment by jasonvarga** [comment]
Has your web host disabled some functions?

https://php.watch/versions/8.0/disable_functions-redeclare

**Comment by MrMooky** [comment]
Oh man, yes. `set_time_limit` is actually disabled, but I did not pay much attention to it as it works just fine with PHP 7.4, but the article explains it. Thanks. :)

**Comment by jasonvarga** [comment]
Good to know though. I had no idea PHP 8 does that.
