### ISSUE TITLE
Stache Doctor: Symlinked data discovered as duplicates

### ISSUE THREAD

**Issue by jbrhel** [statamic/cms#3832]
## Bug Description
I'm using Envoyer for deploying Statamic to production. I have symlinked content folder. When I run `stache:doctor` after  the new release, I'm runing into the issue with Duplicate ID (many of them). But obviously it's not duplicate. Reported files are identical one.

![php_please_jpg](https://user-images.githubusercontent.com/1133430/121638075-ab1c7a80-ca8a-11eb-859a-f02891f7ae38.jpg)

After clearing cache via: `php please cache:clear` there are no duplicities anymore

## How to Reproduce
Have an infrastructure with symliked content folder (and storage folder). Deploy the new release with Envoyer. Run `php please stache:doctor`when deployment is done and new release is active.

## Extra detail
I have also problems with Stache  _Call to a member function id() on null_  similar to https://github.com/statamic/cms/issues/2967 appering randomly. I think that it could be related to .md path resovling mechanism.

## Environment

Statamic 3.1.18 Pro
Laravel 8.34.0
PHP 7.4.18
Predis as an application cache driver
Using 3 balanced servers
Runing Laravel Horizon on each of them
Using AWS Elastic File System as a shared volume for content/storage data accross balanced servers 

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
What's in your deploy script?

**Comment by jbrhel** [comment]
I have modified statamic:install commnad which is running from post-autoload-dump scripts. I removed clearCache method. This is the root cause of the issue I reported. 

I'm closing this issue as the stache:doctor command is working as expected when the cache is cleared.
