### ISSUE TITLE
Collection tree file not deleted when collection deleted

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#3848]
## Bug Description

When you delete a collection via the CP, the "tree" `.yaml` file is not deleted.

## How to Reproduce

1. Add Collection
2. Add entries
3. Give it some structure (ordered)
4. Delete collection

## Environment

Statamic 3.1.23 Pro
Laravel 8.46.0
PHP 8.0.7
aryehraber/statamic-captcha 1.5.1
aryehraber/statamic-uuid 2.0.3
edalzell/forma 0.8.12
jackabox/statamic-shopify 1.4.3
statamic/seo-pro 2.2.1
transformstudios/events 2.1.4
transformstudios/front 1.2.1
transformstudios/magic-link dev-main
transformstudios/review 3.0.4
transformstudios/simple dev-main
transformstudios/stripe dev-main
transformstudios/takeover-redirects dev-main

**Install method (choose one):**
- Starter kit

**Comment by duncanmcclean** [comment]
Confirmed. The tree's `.yaml` file is not deleted, however the contents are left like so:

```yaml
{  }
```
