### ISSUE TITLE
Tab Section more than 6 is not properly displayed.

### ISSUE THREAD

**Issue by zunnurs01** [statamic/cms#3851]
## Bug Description
Tab Section more than 6 is not properly shown when overflow. I think It's should have horizontal scroll when the tab is overflow.

## How to Reproduce
Globals > Globals Set > Edit Blueprints > Add Tab Section More than 6.

## Extra Detail

![image](https://user-images.githubusercontent.com/28453847/121973651-5b062680-cdb0-11eb-8397-cb426b358d80.png)

**Comment by duncanmcclean** [comment]
Closing, #1050 covers this issue.
