### ISSUE TITLE
Image upload: multiple duplicates generated

### ISSUE THREAD

**Issue by imbwaldo** [statamic/cms#3861]
## Bug Description
Drag and drop (or use "Upload") an image into Assets and multiple duplicates of said image are generated. Deleting the extras generates an error message: "Call to a member function delete() on null"

## How to Reproduce
Drag and drop (or use "Upload") an image into Assets.

## Extra Detail

Tried to upload screenshots, but "Something went really wrong, and we can't process that file."

## Environment

Statamic 3.1.24 Solo
Laravel 8.47.0
PHP 8.0.7
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Could you try uploading screenshots again or record a short video of the issue you're facing. I've never seen there be 'duplicate assets' being uploaded...

**Comment by imbwaldo** [comment]
Here's the screenshot of the duplicates, Duncan. The file at the bottom – the  unnumbered one – is the image I actually added to Assets.

<img width="749" alt="Screen Shot 2021-06-16 at 5 03 11 PM" src="https://user-images.githubusercontent.com/1582379/122452609-4b2c4500-cf5e-11eb-860a-adb6b2a651db.png">

And here's the error message I get when deleting the dupes:

<img width="457" alt="Screen Shot 2021-06-16 at 5 06 21 PM" src="https://user-images.githubusercontent.com/1582379/122452898-9ba3a280-cf5e-11eb-8a1b-7fb624348661.png">

Thanks for taking a look.

**Comment by duncanmcclean** [comment]
Can you show what happens when you add an asset?

**Comment by imbwaldo** [comment]
Oy. Embarrassing. I had the Moesif CORS extension running … and disabling it took care of the issue.

Sorry, Duncan. Where should I send apology gifts?

**Comment by duncanmcclean** [comment]
No worries, it’s fine!
