### ISSUE TITLE
Search index not updating when new item is added

### ISSUE THREAD

**Issue by lardnicus** [statamic/cms#3862]
## Bug Description

When adding a new taxonomy term the search index is not being updated/refreshed.

## How to Reproduce

It seems to only affect one taxonomy with a custom search_index others seem to function fine...
Bug occurs when using either local or algolia.
Running php please search:update resolves the issue.

## Extra Detail

I removed all entries from the taxonomy and also stripped the blueprint back down to a title field only but it was still occurring:
Video: https://youtu.be/ZnOGMntq4G4

## Environment

Both in valet and on production server.
**Statamic version:** 3.0.24
**PHP version:** 7.3.27

**Comment by lardnicus** [comment]
config/statamic/search.php:
```
        'indexes' => [

        'default' => [
            'driver' => 'algolia',
            'searchables' => 'all',
        ],

        'clients' => [
            'driver' => 'algolia',
            'searchables' => 'taxonomy:clients',
            'fields' => ['title', 'company', 'position', 'tags'],
        ],

        'artworks' => [
            'driver' => 'algolia',
            'searchables' => 'collection:artworks',
            'fields' => ['title', 'artist', 'year', 'medium''],
        ],

    ],
```

content/taxonomies/clients.yaml:
```
title: Clients
search_index: clients
```

Note that the "artworks" seems to function just fine?

No logs/errors are being generated...

**Comment by aerni** [comment]
This issue happens for me as well. But also with collection entries. New entries don't get indexed. I have to manually refresh the search.

```php
// config/statamic/search.php

'indexes' => [

    'default' => [
        'driver' => 'local',
        'searchables' => 'all',
        'fields' => ['title', 'id'],
    ],

]
```

**Comment by lardnicus** [comment]
I think this is fixed now
