### ISSUE TITLE
Breacrumbs include link to 404 on a taxonomy when there's no index view

### ISSUE THREAD

**Issue by fabbow** [statamic/cms#3863]
## Bug Description

When you use `{{ nav:breadcrumbs }}` on a taxonomies show.antlers.html template, but do not use an index.antlers.html because you don't want that page to exist, the breadcrumbs include a link to the nonexisting index view.

## How to Reproduce

Create a taxonomy, create the taxonomies show.antlers.html, include `{{ nav:breadcrumbs }}` there. Do not create an index.antlers.html. Visit the taxonomy page. In the Breadcrumb list, you should now see a link to the nonexisting Index view, so a 404. 

## Environment

Statamic 3.1.23 Pro
Laravel 8.47.0
PHP 7.4.3
aryehraber/statamic-font-awesome 2.2.0

**Install method (choose one):**

- Fresh install from `statamic/statamic`

**Comment by davideprevosto** [comment]
@fabbow have you found any workaround in the meantime?
