### ISSUE TITLE
Select field inside replicator cannot be named "type"

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#3865]
## Bug Description
When there is a select field inside a replicator with the handle "type" and some other fields, selecting one option will make the set collapse.

## How to Reproduce
Create a replicator with a set. The set should have a select field with the handle set to "type". See it happening.

## Extra Detail
![out](https://user-images.githubusercontent.com/9936988/122420290-dbcd4a00-cf8b-11eb-8481-f390c38e6af6.gif)

## Environment
Laravel Valet, Statamic installed on Laravel 8

**Statamic version:** 3.1.24

**PHP version:** 8.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
`type` is the name of the set inside a replicator. You'll need to call your field something else.

**Comment by AndreasSchantl** [comment]
Ohh, okay, that makes sense then.

**Comment by freshface** [comment]
Getting a warning or hint in the cp ui would be nice :)

**Comment by jasonvarga** [comment]
Yup. https://github.com/statamic/ideas/issues/46
