### ISSUE TITLE
Structure fieldtype unable to find structures

### ISSUE THREAD

**Issue by stvnthomas** [statamic/cms#3875]
## Bug Description

The structure fieldtype errors for any and all selections. The error is visible when using the stack selector mode, otherwise it fails silently.

## How to Reproduce

1. Add a Structure fieldtype with the stack selector mode to a blueprint
2. Go to the global/entry/... where the blueprint is used and select a structure

## Extra Detail

<img width="752" alt="Screen Shot 2021-06-18 at 11 48 50" src="https://user-images.githubusercontent.com/2236267/122604798-644ef780-d02b-11eb-9d03-0cd23f8b3695.png">

## Environment

Statamic 3.1.25 Pro
Laravel 8.47.0
PHP 7.4.2
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
That fieldtype should have been removed and replaced with a `navs` fieldtype.

You're trying to pick a nav, right?

**Comment by stvnthomas** [comment]
Yeah, it's to pick a collection or navigation for the footer. The structure fieldtype lists collections and navs so that's how I'd been organizing this portion of the site. Is the fieldtype only intended for navigations? Can the collections be filtered out of the list?

This navigation isn't likely to change so I can hardcode it. There are other navs in the footer but they're curated and will use navigations so no problem :)
