### ISSUE TITLE
Route with 'layout' => null breaks on recent update

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#3892]
## Bug Description
A route with `'layout' => null` breaks since the XML routes update. (Jason knows about the nitty gritty).

## How to Reproduce
Use:
```
Route::statamic('/social-images/{id}', 'social_images', [
    'layout' => null
]);
```

Visit the route.

## Extra Detail
<img width="1303" alt="Screenshot 2021-06-22 at 16 03 09" src="https://user-images.githubusercontent.com/69107412/122938794-583ca000-d373-11eb-8ad3-feee73216069.png">

## Environment

Statamic 3.1.25 Pro
Laravel 8.47.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by duncanmcclean** [comment]
What happens if you don't pass a `layout` at all?

**Comment by jelleroorda** [comment]
@duncanmcclean It'll use the `default` layout (you can't see here, but it's from Peak and it that view is an antlers template). This syntax should work. This template should specifically not use the layout. A think a possible fix could be to check for (non)existence of `$this->layout` in `Statamic\View\View@isUsingXmlLayout` and bail early.

**Comment by robdekort** [comment]
Jason tipped me to use a blank layout file with just `{{ template_content }}`, that currently works!
