### ISSUE TITLE
Clearer structures

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#3895]
If you have a complex structure tree with lot of entries and a depth of 3+, it's really hard to orientate and see, on which levels the entries are. Perhaps you could differentiate the levels by colors or lines better.
![image](https://user-images.githubusercontent.com/3351449/77157892-8fead700-6aa2-11ea-9fc0-8a53637754d4.png)

**Comment by jackmcdade** [comment]
We should do what we did in v2 – collapsable depths and use `localstorage` or user prefs to store the tree state so it'll stay how you leave it.

**Comment by jackmcdade** [comment]
@arthurperton – you up for tackling this one?

**Comment by arthurperton** [comment]
@jackmcdade Sure I’ll give it a shot. Are there by any change screenshots or perhaps a movie clip of the v2 mechanics, for inspiration?

**Comment by jackmcdade** [comment]
@arthurperton Whipped this up for ya! <https://d.pr/v/Aj8f68>

**Comment by jasonvarga** [comment]
Great soundtrack

**Comment by arthurperton** [comment]
😁 Nice one, thanks Jack!
