### ISSUE TITLE
Displaying entries by taxonomy fails on non-default site

### ISSUE THREAD

**Issue by remiduval** [statamic/cms#3908]
## Bug Description
**Goal**
Display staff entries when taxonomy "departments" == "professeurs" (french) / "teachers" (english)

**Result**
Works for french site but not english site
http://test-tax.test/french displays "Marine Jadaud"
http://test-tax.test/english displays nothing

## How to Reproduce
Public repo with clean install from the last version: https://github.com/remiduval/test-tax

**Key files**
https://github.com/remiduval/test-tax/blob/main/resources/blueprints/collections/staff/staff.yaml
https://github.com/remiduval/test-tax/blob/main/resources/fieldsets/staff.yaml
https://github.com/remiduval/test-tax/blob/main/resources/blueprints/collections/pages/pages.yaml

https://github.com/remiduval/test-tax/blob/main/content/taxonomies/departments/professeurs.yaml
https://github.com/remiduval/test-tax/blob/main/content/collections/pages/french/home.md
https://github.com/remiduval/test-tax/blob/main/content/collections/pages/english/home.md
https://github.com/remiduval/test-tax/blob/main/content/collections/staff/french/marine-jadaud.md
https://github.com/remiduval/test-tax/blob/main/content/collections/staff/english/marine-jadaud.md

https://github.com/remiduval/test-tax/blob/main/resources/views/home.antlers.html

## Environment
Statamic 3.1.26 Pro
Laravel 8.48.1
PHP 8.0.3
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Hi Remi. You should use the `taxonomy` parameter instead, which is designed to handle a term being passed to it.

```mustache
{{ collection:staff :taxonomy:departments="department" as="persons" }}
```

What you were doing before (`:departments:contains="department:slug"`) was filtering the entries that had the english slug "teachers" in it. None of them do, because the slug for the default site (professeurs) is always saved.

**Comment by remiduval** [comment]
Hi Jason, thank you for looking into it.
Unfortunately, that didn't work (no output) - not sure why but maybe that's because `department` and `departments` have a "many to one" relationship and it needs the `contains` modifier, which is not available using `:taxonomy`.
I found a fix though, by using the same slug for both languages - probably wouldn't be ok for someone using the taxonomy slug in an URL but that's not my case so I'm happy with that fix :)
