### ISSUE TITLE
Relationship Selector stack could re-use the user's listing configuration

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#391]
We believe it would be user-friendly to re-use the listing configuration the user already saved from the "normal" listing page. In case there are multiple collections allowed, we imagine tabs at the top to first pick the collection, then see the respective listing.

We would prefer this over a list of all the entries from all the configured collections in one list, because this also leads to problems when configuring the columns: we might allow entries of collections with completely different columns.

**Comment by jackmcdade** [comment]
I'm a bit confused by this issue now, especially in light of all the changes to Filters at this point.

@sauerbraten – is this issue still a concern for you?

**Comment by jackmcdade** [comment]
I haven't heard back for a few months so I'm going to close this in an effort to organize the repo's issues. Feel free to reopen or comment with more info!
