### ISSUE TITLE
500 errors in control panel when selecting items in Entries tag

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#3911]
## Bug Description

When attempting to select entries using the Entries field, I kept getting a 500 error either when searching for the page I wanted, or when going through the pages one by one to find what I was looking for. Here is the basic error from the logs:

```
[2021-06-25 16:37:47] local.ERROR: Argument 1 passed to Statamic\Markdown\Parser::parse() must be of the type string, array given, called in [path]/vendor/statamic/cms/src/Markdown/Manager.php on line 15 {"userId":"94744219-0829-48d0-91ab-16a29106228c","exception":"[object] (TypeError(code: 0): Argument 1 passed to Statamic\\Markdown\\Parser::parse() must be of the type string, array given, called in [path]/vendor/statamic/cms/src/Markdown/Manager.php on line 15 at [path]/vendor/statamic/cms/src/Markdown/Parser.php:23)
```

## How to Reproduce

1. My Entries field is set to not limit by collection, so it's picking from all my collections.
2. If I set the filter to choose a specific collection, the problem doesn't happen. I went through all pages of each collection individually without a problem. But if I try searching or going through the pages when all collections are visible, I have the error.

**Note:** I THINK the problem is related to having some date-based collections and some collections without dates, but I'm not sure. It may just be having collections with different columns, which usually is date, but can be others (like my blog article list shows a column for the author name from a taxonomy).

## Environment

Statamic 3.1.26 Pro
Laravel 8.46.0
PHP 7.4.20
statamic/seo-pro 2.2.1
statamic/ssg 0.7.0
transformstudios/review 3.0.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`, migrated from v2 using migration tool

**Comment by duncanmcclean** [comment]
By any chance do you have a Bard field with a handle of `content`?

**Comment by fitzage** [comment]
Hmm…I guess I do still have one collection like that.

**Comment by fitzage** [comment]
I changed those to "body" and it made no difference.

**Comment by fitzage** [comment]
OK, I spoke too soon.

Yes, this fixes the problem. Doesn't make sense as to why, but OK.

**Comment by duncanmcclean** [comment]
It's come up a couple of times before, here's some related issues: #2862 #3577
