### ISSUE TITLE
Entries fieldtype: status filter to include unpublished entries

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#3918]
Since 3.1.15, it looks like we're now [filtering unpublished entries out](https://github.com/statamic/cms/pull/3544) when outputting entries from the Entries fieldtype. Unfortunately this has been a nasty breaking change for me as I'd expect that any Entries selected (published or unpublished) would be outputted and there seems to be no way to include unpublished entries at the moment. 

Can we implement [Jason's solution](https://github.com/statamic/cms/pull/3544#pullrequestreview-663661152):

```
{{ features status:in="draft|published" }}
...
{{ /features }}
```

<img width="692" alt="Screen Shot 2021-06-01 at 2 31 02 pm" src="https://user-images.githubusercontent.com/414211/120267018-7409d480-c2e6-11eb-829a-4c1a18295c00.png">

**Comment by jasonvarga** [comment]
In the mean time, you can use a custom fieldtype.

Drop this into `app/Fieldtypes/EntriesWithDrafts.php`

```php
<?php

namespace App\Fieldtypes;

use Statamic\Contracts\Data\Localization;
use Statamic\Facades\Entry;
use Statamic\Facades\Site;
use Statamic\Fieldtypes\Entries;

class EntriesWithDrafts extends Entries
{
    public function augmentValue($value)
    {
        if (! is_object($value)) {
            $value = Entry::find($value);
        }

        if ($value != null && $parent = $this->field()->parent()) {
            $site = $parent instanceof Localization ? $parent->locale() : Site::current()->handle();
            $value = $value->in($site);
        }

        return $value;
    }
}
```

In your blueprint where you want the entries field to output drafts, change `type: entries` to `type: entries_with_drafts`.

All I've done is make a custom field that overrides this single line:

https://github.com/statamic/cms/blob/dc341772fe1657279d79581d6ed860f2a46fdc66/src/Fieldtypes/Entries.php#L222

**Comment by mikemartin** [comment]
@jasonvarga I've added the custom field `entries_with_drafts` and it works locally. However, on production it's throwing a `entries_with_drafts` fieldtype is missing error. Any idea why this could be?

**Comment by jasonvarga** [comment]
Did you commit it? 😄

Is it named `EntriesWithDrafts.php` with that casing? e.g. not `Entrieswithdrafts.php`

**Comment by mikemartin** [comment]
Folder was named FieldTypes and not "Fieldtypes". 🤦‍♂️

**Comment by mikemartin** [comment]
Hey @jasonvarga 
I've been using the "EntriesWithDrafts" fieldtype workaround for a while now. Is there anything we can do to support showing unpublished entries on the frontend? Here's an example of a use case that I use quite often. 

We are using unpublished "Feature" entries for our feature lists and only those features with pages are published.

<img width="1770" alt="Screen Shot 2022-03-18 at 3 58 32 pm" src="https://user-images.githubusercontent.com/414211/158940681-54f5eb4b-435f-4b44-a42b-55b52c80cd9d.png">

**Comment by edalzell** [comment]
Was chatting w/ @mikemartin about this. What about a config field `show_drafts` or something, then in the `augment` method we use a `when` and check it?

**Comment by jasonvarga** [comment]
I'm cool with that.

**Comment by andrew-ireland** [comment]
Was there ever any resolution on showing unpublished entries on the frontend using a custom fieldtype like the 'EntriesWithDrafts.php' shown here?

Looking to do a similar thing. First instinct was to do ```status:in="draft|published"``` but no luck. Have manually set a toggle on the entry to manage it instead, but it's not ideal (other knock-on effects with content queries elsewhere keeping the entry published). 

Would love clean way of showing unpublished entries on the frontend with the entries field for posts/items that are 'Coming Soon', or shouldn't generate a route.

**Comment by clementmas** [comment]
Is there any way in Statamic v5 to include both published and draft entries?

The proposed `status:in` solution doesn't seem to work on the collection tag.

**Comment by duncanmcclean** [comment]
> Is there any way in Statamic v5 to include both published and draft entries?
> 
> The proposed `status:in` solution doesn't seem to work on the collection tag.

No, there's not. You can [now only query entries by a single status](https://statamic.dev/upgrade-guide/4-to-5#entries-may-now-only-be-queried-by-a-single-status), rather than multiple statuses which was previously the case.
