### ISSUE TITLE
Entry breaks if the blueprint does not exist

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#3920]
If trying to open an entry with a non existing blueprint due to renaming etc, we do get a 500 Error in the cp. 

![Screenshot 2021-06-29 at 11 04 07](https://user-images.githubusercontent.com/38906163/123769833-fbd50580-d8c9-11eb-8cd4-045960a3af7c.png)

## How to reproduce

1. Create an entry
2. Rename the blueprint inside the yaml file to something not existing. 
3. Open this entry in the cp

## Expectations

I would hope for better error handling, in case we do open an entry with missing/wrong or outdated information. 

What I would wish for (ordered after priority)
1. A modal, saying that the blueprint does not exist with an option to select a new one. 
2. An error message in the show view somehow
3. An Exception catching the error and informing, that it's due to a not existing Blueprint

One and two would be user friendly, making the cp bulletproof.  

## Environment

**Statamic version:** 3.1.24 Pro

**PHP version:** 8.0.6

**Comment by jonassiewertsen** [comment]
This PR is great and will make the error much more clear. Thanks @duncanmcclean and @jasonvarga for the work!

Throwing an exception would still mean, that the control panel would break. (No doubt that the PR is helpful). 

What would be necessary to offer a solution as mentioned in `wishes` 1 or 2?

> 1. A modal, saying that the blueprint does not exist with an option to select a new one.
> 2. An error message in the show view somehow

**Comment by jonassiewertsen** [comment]
Important things first: Thanks for the PR and it's great that it has been merged. This is a nice improvement. 

I am totally aware of the work, but do think that showing a 500 error is not a user-centric way of handling errors, if a plain user can trigger this kind of exception by using the cp (and he can).

**Comment by jasonvarga** [comment]
How can a user trigger this error through the CP? You can't change blueprint handles in the CP. You can delete them, I suppose, but someone with permission to manage fields should probably know that _deleting_ something is dangerous.

If you'd like to open a feature request in statamic/ideas for the extended solutions you mentioned, that's cool. 👍
