### ISSUE TITLE
White Label SVG will not shown

### ISSUE THREAD

**Issue by Joe2824** [statamic/cms#3925]
## Bug Description
White label Logo will not show at CP

## How to Reproduce
Define 
` 'custom_logo_url' => [
        'nav' => '/assets/webseite/logo.svg',
        'outside' => '/assets/webseite/logo.svg'
    ],` in cp.php

## Extra Detail

html look like: `<img src="/assets/webseite/logo.svg" alt="FAROS Consulting" class="white-label-logo">`
logo.svg exist and is not white.
![Bildschirmfoto 2021-06-29 um 20 20 57](https://user-images.githubusercontent.com/4028085/123848170-ade6ee80-d917-11eb-8f99-650b295d4612.png)

## Environment
Same problem local and on Webserver

Statamic 3.1.26 Pro
Laravel 8.49.0
PHP 8.0.6
doublethreedigital/duplicator 1.3.3
rias/statamic-redirect 1.4.6

**Statamic version:** 3.1.26

**PHP version:** 8.0

**Install method (choose one):**
- Starter kit

**Comment by jackmcdade** [comment]
Can you share the SVG? It's most likely an issue in there (like a missing height/width/viewbox) rather than the actual CP CSS.

**Comment by jackmcdade** [comment]
I haven't heard back for a few weeks so I'm gonna close this and assume you got it sorted out. If you have any more info, please feel free to reply and we'll reopen!
