### ISSUE TITLE
Multisite: slug not generated correctly when publishing different language

### ISSUE THREAD

**Issue by freshface** [statamic/cms#3933]
## Bug Description

Lets say we have a multisite with 2 languages, dutch (NL) and french (FR).
When creating an entry and publishing the NL language a slug is generated.
But when switch to the FR version, entering the title and publishing it takes the slug of the NL version and not FR title.

Jack told me when you empty the slug of the FR version the slug is regenerated but this does not work.
it says the slug is required.

## How to Reproduce

See description.

## Suggestions to solve this

- Regenerate slug when emptied
- When publishing the other language (if the entry for that language does not exist) take the title to generate the slug

## Environment

Statamic 3.1.26 Pro
Laravel 8.48.1
PHP 8.0.8
jimblue/mapbox 1.0.0
youfront/statamic-export 1.0.3

**Statamic version:**  3.1.26 Pro

**PHP version:**8.0.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
I'm in camp automatic. Editors on my multi sites often don't notice the slug and that way they end up with non translated ones. 

I don't really see use cases for multilingual sites where you'd not want this to happen automatically. And if you would it might make more sense for that use case to be manual. To me it feels like the exception.

**Comment by freshface** [comment]
Yes, it should be automatic :)
But it should take the title of that language and not the slug of the first entered entry for that language.

**Comment by robdekort** [comment]
Yeah I agree!

**Comment by stephenmeehanuk** [comment]
Agree with this. For multi site it should be the default behaviour. Ot at least provide a config so it can be the default.

**Comment by jasonvarga** [comment]
statamic/ideas#334
