### ISSUE TITLE
Glide cache in headless mode

### ISSUE THREAD

**Issue by strebl** [statamic/cms#3938]
We are using Statamic as headless CMS with the content api. Works fine 🎉 

But I came across a problem with Glide. I tried to enable the Glide cache. But it seems that's not possible if you use Statamic as a headless cms, is that correct?

#2379 says:
> it also removes the Glide routes entirely if the cached option is being used, since the images get generated on demand in your template and the actual images get served.

Is it a intentional decision that this is not possible?

**Comment by jasonvarga** [comment]
When you use the "cached" option, usually that means the images get generated when there's a glide tag in your Antlers template.

The feature itself should be fine, it's just a matter of somehow triggering the generation of the images.

How are you adding the Glide URLs to your API responses?

**Comment by strebl** [comment]
We're returning the asset as an object from the api and building the glide url on the frontend. Because the frontend "knows" how large the image should be. Therefore the backend can't know what it has to generate.

But it would be great if it would store the image it generated and serve that on the next request. But I see the problem. That wouldn't be as fast as the solution you have now.

**Comment by jasonvarga** [comment]
Have you tried using presets? Then when you initially upload the image, it'll generate all the sizes you might need.

https://github.com/statamic/statamic/blob/master/config/statamic/assets.php#L58-L71

**Comment by strebl** [comment]
Oh that's a nice hint! I'll look into that. Thank you very much!

**Comment by scherii** [comment]
Hi @jasonvarga 
Could you please elaborate on why on-the-fly image transformations cannot be cached?
Is it too complex or just not implemented yet?

**Comment by jasonvarga** [comment]
As I mentioned before, when using the cached option, the image is generated by the glide tag. Since there's no glide tag, the image won't exist.

**Comment by scherii** [comment]
Thanks @jasonvarga 

For now I use this in the `routes/web.php` and it seems to do the job (OTF transformed images are being cached):

```
Route::get(
    config('statamic.assets.image_manipulation.route') . '{path}',
    [GlideController::class, 'generateByPath']
)->where('path', '.*');
```
