### ISSUE TITLE
Multisite template override not being loaded

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#3945]
## Bug Description
If you have multiple sites, and one site is set to use an overridden template, it loads the base template instead of the override template.

## How to Reproduce
Have 2 sites set up, e.g. "default" and "blog" as the keys in `config/statamic/sites.php`
Set up template such as `resources/views/home.antlers.html` and `resources/views/blog/home.antlers.html`
What should happen is the `blog` site uses `resources/views/blog/home.antlers.html`, however it will use `resources/views/home.antlers.html`
This broke as of 3.1.25 - issue confirmed as bug in support request

## Environment
Statamic 3.1.26 Pro - works as expected up to and including 3.1.24
Laravel 8.37.0
PHP 7.4.6
statamic/migrator dev-master

**Install method (choose one):**
- Fresh install from `statamic/statamic` (upgrade from v2)

**Comment by edalzell** [comment]
This is fixed here: https://github.com/statamic/cms/pull/3944
