### ISSUE TITLE
Entries with numeric prefixes produce wrong slug

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#3946]
## Bug Description
If you upgraded from Statamic v2, your entry file names may be in the format `1.this-is-the-slug.md`
Up to and including 3.1.18, the URL output on the front end when using `{{ permalink }}` was `/this-is-the-slug`. As of 3.1.19, the same template outputs `/1` as the URL.
In a support request I was advised the entry names should not have numeric prefixes - this makes sense as newly created entries on v3 do not have this number at the start. However, imported entries from v2 do (or mine do at least, it may have depended on how they were sorted in v2), and have worked from 3.0.0 up to 3.1.18, so people may not have noticed this has broken, and if we need to now rename these files, either the upgrader should do this or users need to be told somehow.

## How to Reproduce
Have an entry file prefixed with a number, such as `1.this-is-the-slug`
On <= 3.1.18, `{{ permalink }}` outputs this as `/this-is-the-slug`
On >= 3.1.19, `{{ permalink }}` outputs this as `/1`

## Environment
Statamic 3.1.26 Pro - works as expected up to and including 3.1.18
Laravel 8.37.0
PHP 7.4.6
statamic/migrator dev-master

**Install method (choose one):**
- Fresh install from `statamic/statamic` (upgrade from v2)

**Comment by edalzell** [comment]
Numeric prefixes aren't support as they are now used to handle content with the same slug in different spots in an ordered collection w/ depth > 1.

How did you update? The migrator should remove those prefixes (and convert them to the `tree` structure).

**Comment by MattRogowski** [comment]
I used the official importer/converter script available at the time, this was on about version 3.0.4 so before the tree structure as it currently is existed (I believe this changed relatively recently?). I did have a few issues with the migration as some entries were in the incorrect order and I had to re-set the published dates on them, but the numerical file names have been there ever since.

**Comment by edalzell** [comment]
Maybe the migrator had a bug then, hard to tell. Looks like it's handled now in the migrator, so that's good.

I know I had some issues at the beginning w/ the migrator that have all been resolved.

**Comment by MattRogowski** [comment]
Okay, I can go through and rename them then, I just wanted to make sure that anyone else who upgraded would have older posts with an incorrect slug all of a sudden.

**Comment by jasonvarga** [comment]
Migrator indeed had a bug, which we've fixed. See more details [in this comment](https://github.com/statamic/cms/pull/3947#issuecomment-874922551).

We suggest to please just rename your entries.
