### ISSUE TITLE
Draft entries are outputted/showing frontend when using entries tag with taxonomy tag and on taxonomy show page.

### ISSUE THREAD

**Issue by philipboomy** [statamic/cms#3952]
## Bug Description
When using the {{ entries }} tag on a taxonomy page as well as inside the {{ taxonomy }} tag it is outputting entries that are in draft. - Related to #2721 

## How to Reproduce
Output entries in a taxonomy tag using the entries tag

## Extra Detail
https://share.getcloudapp.com/BluKzvYJ
https://share.getcloudapp.com/2Nuqp8Ew
https://share.getcloudapp.com/mXurGW1v

With the "published" condition it is working
https://share.getcloudapp.com/rRujzDk8

## Environment
Statamic 3.1.27 Pro
Laravel 8.49.1
PHP 7.4.19
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by austriker27** [comment]
I can confirm I'm in a taxonomy route and getting this bug.

Version: Statamic 3.1.35

PS: Im going to use the following as a work around for now:

file: `resources/views/tags/show.antlers.html`

```
{{ entries paginate="5" status:is="published" }}
            {{ results }}
              {{ partial:components/card
                  :title="title"
                  :url="url"
                }}
            {{ /results }}
          {{ /entries }}
```

**Comment by robdekort** [comment]
Also confirmed.

**Comment by jackmcdade** [comment]
Fixed in 4.x.
