### ISSUE TITLE
Page jumps when reordering images

### ISSUE THREAD

**Issue by jezzdk** [statamic/cms#3953]
## Bug Description
When reordering assets in the assets field, the page jumps to the top.

## How to Reproduce
Add an Assets field to a blueprint. Keep the default settings.
Create an entry and add a bunch of assets.
Reorder the assets and see that the page jumps to the top every time an item is dropped.

## Extra Detail
![Screen Recording 2021-07-05 at 07 55 42 (1)](https://user-images.githubusercontent.com/139632/124491368-7b277500-ddb3-11eb-8b92-443fa624a39c.gif)

## Environment

Statamic 3.1.27 Pro
Laravel 8.49.0
PHP 7.4.16
cnj/seotamic 2.0.4
mattrothenberg/location 1.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
This will be fixed in 3.2.

**Comment by j3ll3yfi5h** [comment]
I do have a similar behavior, if I link a file (e.g. in a bard) from page two of the assets browser. @jackmcdade is this also fixed or another (new) issue?

**Comment by jackmcdade** [comment]
it might!
