### ISSUE TITLE
Blueprint builder should inform user of special or reserved field names

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#3956]
Field names like `date`, `slug`, `title` and so on should have some kind of visible UX to inform the user that the fieldname is special. If we want to prevent certain words, we should do so, and for those where behaviors are special (like `date`), there should be some UX to make that clear. Perhaps a tooltip.

**Comment by jasonvarga** [comment]
Related https://github.com/statamic/ideas/issues/46

**Comment by arthurperton** [comment]
More relevant info:

#2495
#3538
#3956
[statamic/docs#236](https://github.com/statamic/docs/issues/236)
[List of Reserved Words // Statamic 3 Docs](https://statamic.dev/knowledge-base/reserved-words)
