### ISSUE TITLE
Live Preview toolbar covers Bard toolbar

### ISSUE THREAD

**Issue by dmgawel** [statamic/cms#3974]
## Bug Description

When in Live Preview mode and using Bard, Live Preview toolbar covers Bard toolbar after scrolling.

## How to Reproduce

1. Create a Bard field
2. Enter Live Preview
3. Write content long enough to introduce scroll
4. Scroll down

## Extra Detail

<img width="604" alt="Zrzut ekranu 2021-07-8 o 15 47 43" src="https://user-images.githubusercontent.com/1322846/124933104-e9fb0d00-e003-11eb-9067-c6b730844811.png">

## Environment

Statamic 3.1.27 Pro
Laravel 8.41.0
PHP 8.0.6
No addons installed
Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Can confirm.
