### ISSUE TITLE
SelectFieldtype value should reset on options change

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#398]
https://vue-select.org/api/props.html#resetonoptionschange should be set to true or at least be configurable to enable reactive fieldtypes.

**Comment by jasonvarga** [comment]
Noticed an issue with vue-select where reset-on-options-change would reset even if the options are exactly the same, but technically a different javascript object.

See https://github.com/sagalbot/vue-select/pull/1014

I've just changed our implementation to only reset if the value does not exist in the new set of options.

I believe this change will keep your domain/channel field logic working.
The channel will now only be cleared out if it doesn't exist in the newly selected domain.
If it does exist, it'll stay selected. That's probably a benefit. Saves your user from having to re-select the channel.
