### ISSUE TITLE
Shorthand if/else doesn't work with pagination

### ISSUE THREAD

**Issue by nickebdon** [statamic/cms#3980]
## Bug Description

Using the shorthand `if/else` statement does not work when used with pagination, however the basic `if/else` does.

## How to Reproduce

This doesn't work:
```
{{ collection:work limit="8" paginate="true" as="posts" sort="date:desc" }}

    {{ posts }}
        <p>{{ short_title ? short_title : title }}</p>
    {{ /posts }}

    {{ paginate }}
    ...
    {{ /paginate }}

{{ /collection:work }}
```
However, this does:
```
{{ collection:work limit="8" paginate="true" as="posts" sort="date:desc" }}

    {{ posts }}
        <p>{{ if short_title }} {{ short_title }} {{ else }} {{ title }} {{ /if }}</p>
    {{ /posts }}

    {{ paginate }}
    ...
    {{ /paginate }}

{{ /collection:work }}
```
## Environment

**Statamic version:** 3.1.27

**PHP version:** 8.0.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
I'm not sure why that second example is working, you're forgetting the end `{{ /if }}`.

**Comment by nickebdon** [comment]
Sorry, that was a typo. The end `{{ /if }}` should be there (I've updated the second example above).
