### ISSUE TITLE
Glide tag pair after Glide tag generates wrong HTML

### ISSUE THREAD

**Issue by PieterjanNeskens** [statamic/cms#3983]
## Bug Description
When using Glide tag pair after Glide single tag the output HTML breaks, see examples below.

## How to Reproduce
Put Glide tag pair after single Glide tag on same asset (limit: 1).

### NOT working example: single tag + tag pair
antlers:
```
<picture>
  <source srcset="{{ glide:logo width="375" format="webp" }}" type="image/webp">
  {{ glide:logo width="375" }}
	  <img src="{{ url }}" width="{{ width }}" height="{{ height }}" alt="{{ alt }}">
  {{ /glide:logo }}
</picture>
```
produces wrong HTML:
```
<picture>
  <source srcset="" type="image/webp">
  /img/asset/YXNzZXRzL2FsbC1wYWludC1kZXNpZ24tbG9nby5wbmc=?w=375&amp;s=3251bf165ea9cdbb21f8c127f966c93e
  <img src="" width="" height="" alt="">
</picture>
```

### working example: tag pair + tag pair
antlers:
```
<picture>
  {{ glide:logo width="375" format="webp" }}
	  <source srcset="{{ url }}" type="image/webp">
  {{ /glide:logo }}
  {{ glide:logo width="375" }}
	  <img src="{{ url }}" width="{{ width }}" height="{{ height }}" alt="{{ alt }}">
  {{ /glide:logo }}
</picture>
```
produces expected HTML
```
<picture>
  <source srcset="/img/asset/YXNzZXRzL2FsbC1wYWludC1kZXNpZ24tbG9nby5wbmc=?w=375&amp;fm=webp&amp;s=dc4b40047677f799d1676a3909ce185f" type="image/webp">
  <img src="/img/asset/YXNzZXRzL2FsbC1wYWludC1kZXNpZ24tbG9nby5wbmc=?w=375&amp;s=3251bf165ea9cdbb21f8c127f966c93e" width="375" height="244" alt="All Paint Designs logo">
</picture>
```

## Environment

Statamic 3.1.27 Pro
Laravel 8.47.0
PHP 8.0.8
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by afonic** [comment]
If you want to use a single glide tag, the "logo" asset Field must have "Max files" set to 1.

**Comment by PieterjanNeskens** [comment]
Max files is set to 1.

**Comment by jasonvarga** [comment]
I think this is a parser issue. The closing tag of the second tag makes it think it belongs to the first one.

Try adding a closing slash to the first tag. Like this: `{{ glide:logo ... / }}`

**Comment by PieterjanNeskens** [comment]
That doesn't work, however the following does:
`<source srcset="{{ glide:logo width="375" format="webp" }}{{ /glide:logo }}>`
