### ISSUE TITLE
Localizable fields with empty value (null) do return value of origin even if desynced

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#3987]
## Bug Description
A localizable field does return the value of the origin if it's empty AND desynced.
(Can't even check for empty value with `{{ if fieldname }}` because it has always value from the origin.)

## How to Reproduce
- Install Statamic as Multisite
- Add a field to a blueprint and make it localizable
- Fill it with different content in each language. -> Desynced from origin
- Output the values and check
- Clear one language and have a look at the output (without pressing "sync"!)

## Extra Detail
![Bildschirmfoto 2021-07-13 um 14 31 38](https://user-images.githubusercontent.com/6337411/125452083-a1bdd514-d10d-402a-abce-c35dcc264a5d.png)

## Environment
Statamic 3.1.27 Pro
Laravel 8.49.2
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by tao** [comment]
I have the same problem too and it's causing a big issue on my site with translations. It also happens on assets, or on Text fields if you delete the parent text and leave the field blank.

Related: #3738, #3406

**Comment by tao** [comment]
In some cases you can scope the value to the page, for instance:
`{{ if page:fieldname }}` or `{{ page:fieldname }}` 

These will work correctly and return null but `{{ fieldname }}` will fall back to the origin value.

**Comment by sjclark** [comment]
> (Can't even check for empty value with {{ if fieldname }} because it has always value from the origin.)

> In some cases you can scope the value to the page, for instance: `{{ if page:fieldname }}` or `{{ page:fieldname }}`
> These will work correctly and return null but `{{ fieldname }}` will fall back to the origin value.

@tao did you ever find a consistent approach to this? I've got a site where I'm trying to detect if a fields output is from the current locale or is from inheritance - but can't seem to find a way that works.

Trying something like this (based on your post) has not worked and I'm still trying to find a way around this.
```
    {{ if page:page_builder }}
    VALUE IS FROM TRANSLATED
    {{ else }}
    UNFORTUNATELY PAGE NOT TRANSLATED
    {{/if}}
 ```
 The code above just always reports the first value - even if inheriting.

 Think I might suggest that an `inherited=true` or something be added to the frontmatter meta.
 
 🤷‍♂️ Maybe the behaviour was changed in https://github.com/statamic/cms/pull/4301

**Comment by tao** [comment]
@sjclark This issue was closed a while ago, I don't recall any issues anymore but I haven't worked on the code in a while. I recommend you open a new issue with a demo to help the devs debug it... and I'll comment later if I find the same bug in my code.
