### ISSUE TITLE
Using the as tag on search results doesn't work (regression, urgent) 

### ISSUE THREAD

**Issue by MadeByMike** [statamic/cms#3994]
## Bug Description

Using the as tag on search results doesn't work. Verified working in older version, sites upgrading will break.

## How to Reproduce

1. Set-up and new statamic site and do a minimal configuration to get search working.
2. Add a search results tag `{{ search:results index="default" }} ... {{ /search:results }}`
3. Add the `as` param to the results as per documentation `{{ search:results index="default" as="anything" }}`

![image](https://user-images.githubusercontent.com/1320567/125598955-60185dc1-d56e-4856-b295-feab9b14bef6.png)

## Environment

Statamic 3.1.27 Pro
Laravel 8.49.0
PHP 7.4.16
statamic/seo-pro 2.2.1

- Fresh install from `statamic/statamic`

**Comment by JuergenSchadek** [comment]
I have the same error.

**Comment by duncanmcclean** [comment]
Can you share the full stack trace of the exception you're seeing? Thanks.

**Comment by MadeByMike** [comment]
Can we write a test before we close this issue?

**Comment by jasonvarga** [comment]
The issue has been fixed and will be in the next release. If you want to PR a test, go for it.

**Comment by MadeByMike** [comment]
@jasonvarga respectfully mate, this is commercial software and when I buy just a few client licences it nets you thousands of dollars not to mention plugins and other things in the eco system. I write software too and this bug lost me about half a day of time on a client project. I think when you have that kind of impact and the commercial means I mentioned it's not ok to ONLY fling a quick one line commit and close it with "If you want to PR a test, go for it."

Yesterday because of this and other issues I was facing I went through the tests suite for antlers/tags and it's really sparse. You have the opportunity to fix this and it should be a priority with every new issue like this that breaks something in production... in my experience that's just normal practice for software like this.

**Comment by jasonvarga** [comment]
No worries. Tests added in 3d83509.

**Comment by MadeByMike** [comment]
@jasonvarga Thanks for taking this feedback kindly.
