### ISSUE TITLE
Slug field broken in Collection

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#3995]
## Bug Description
After creating a new collection and adding a few entries to it, some (not all) are not updatable due to some bug with the slug field. It tells me the URI is already taken.

## How to Reproduce
Don't know. Some entries work, some don't. Even if I type anything that can't possibly exist (eg. `something-10294343`), the error occurs for those "buggy" entries.

## Extra Detail
https://www.loom.com/share/3bfff4d60f7a42c2a09f2ff19b957a36

<img width="1271" alt="Screenshot 2021-07-14 at 13 51 47" src="https://user-images.githubusercontent.com/3603346/125617720-fe204a6b-0efe-4b99-9566-7372df185ecd.png">

## Environment
Statamic 3.1.27 Pro
Laravel 8.49.1
PHP 8.0.5
jonassiewertsen/statamic-livewire 2.6

**Install method:**
- Existing Laravel app

**Comment by jasonvarga** [comment]
Does that collection have a `route`? What is it?

**Comment by MrMooky** [comment]
I think I know what you are getting at. The route was `/coupon`, because there is no detail page for this collection. I just tried it with `/coupon/{slug}` and the error is gone, which makes sense. I think this will do it. Thanks for your time, though.

**Comment by jasonvarga** [comment]
You could also remove the route completely if you aren't going to have urls for these entries.

**Comment by MrMooky** [comment]
But I won't be able to have a list view then, or am I missing something?

**Comment by jasonvarga** [comment]
The route is just for the urls of the entries.

The list view would be completely separate. Perhaps an entry in a "pages" collection.
https://statamic.dev/collections#mounting

**Comment by MrMooky** [comment]
Ah, I see. Alrighty then, sounds fine to me. Will do it that way. Thanks! :)
