### ISSUE TITLE
Term field set to stack selector mode does not allow creation of new terms

### ISSUE THREAD

**Issue by beckysoll** [statamic/cms#3999]
## Bug Description
When using a term field set to stack selector mode, I am able to link to an already created taxonomy term but i am not able to create a new one on the fly. I AM able to create a new one if i use either of the other 2 modes. Additionally, an entries field set to stack selector mode _does_ allow creation of new entries.

## How to Reproduce
add a term field to a blueprint, set it to stack selector mode,

## Extra Detail

<img width="360" alt="Screen Shot 2021-07-08 at 9 37 50 AM" src="https://user-images.githubusercontent.com/5340428/125650279-6cf7944b-8b5e-43f0-b361-ff93743ac200.png">

## Environment

Statamic 3.1.27 Pro
Laravel 8.47.0
PHP 8.0.7
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Possibly related to #593

**Comment by beckysoll** [comment]
> Possibly related to #593

I don't think so?

**Comment by duncanmcclean** [comment]
Whoopsie, forgot to specify which repo it was. The reference should be fixed now.
