### ISSUE TITLE
Setting a container and folders on assets fieldtype throwing array error as of 3.1.28

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#4007]
## Bug Description
When setting a container and folder for assets, it's yelling at me!

## How to Reproduce
Set up an assets fieldtype in version 3.1.28

## Extra Detail
![Screen Shot 2021-07-15 at 2 38 45 PM](https://user-images.githubusercontent.com/2514935/125847878-37a97d6a-fdca-4ddf-8212-9fd499e671ed.png)

## Environment
**Statamic** 3.1.28 Pro
**Laravel** 7.30.4
**aryehraber/statamic-captcha** 1.5.2
**aryehraber/statamic-color-extractor** 1.1.2
**rias/statamic-data-import** 1.1.2
**spatie/statamic-responsive-images** 2.7.1
**webographen/statamic-dynamic-token** 1.0.0

**PHP version:** 7.4.19

**Comment by jasonvarga** [comment]
Ah thanks 👌

**Comment by jsblair9** [comment]
beat me too it
