### ISSUE TITLE
Live Preview extra data is not visible in view

### ISSUE THREAD

**Issue by dmgawel** [statamic/cms#4013]
## Bug Description

Data from Live Preview additional fields is not properly passed to view while in Live Preview mode. The `live_preview` variable does not exists.

Having checked older Statamic releases, I can confirm that it was working properly in v3.1.9 and stopped in v3.1.10 ([compare changes](https://github.com/statamic/cms/compare/v3.1.9...v3.1.10)).

## How to Reproduce

1. Create additional Live Preview input according to https://statamic.dev/extending/live-preview#additional-inputs
2. Add `{{ live_preview | dump }}` to view
3. Open Live Preview

## Environment

Statamic 3.1.28 Pro
Laravel 8.41.0
PHP 8.0.6
No addons installed
Fresh install from `statamic/statamic`

**Comment by dmgawel** [comment]
I analyzed changes introduced in v3.1.10 and it looks like [this line](https://github.com/statamic/cms/commit/ada5c2ea8d4be2ca37b8a71585d0bbdb132ba399#diff-267a92cc064e8caa89fc3c4b4bd4c72e7125abfbd1066816c7057f9ad3fce6c3R82), introduced in #3562, that resets data in Cascade during hydration, causes the bug. Extra preview fields are set properly in `toLivePreviewResponse()`, but probably later removed during hydration when View is created.

I'm not familiar enough with Statamic internals to attempt a fix, so let me mention original change author: @jasonvarga.

I hope my findings helps a bit ;-)

**Comment by duncanmcclean** [comment]
Confirmed, I see exactly what you mean.
