### ISSUE TITLE
Issue with EntrySaving event and ShouldQueue interface

### ISSUE THREAD

**Issue by aerni** [statamic/cms#4019]
## Bug Description
I've got an event listener listening to the `EntrySaving` event. In this listener, I'm adding some data to the entry. This works as expected. But if you implement the `ShouldQueue` interface, the data is NOT saved to the entry anymore.

## How to Reproduce
1. Create a new listener. I used the following in my testing:
```php
<?php

namespace App\Listeners;

use Illuminate\Contracts\Queue\ShouldQueue;

class UpdateEntryData implements ShouldQueue
{
    public function handle($event)
    {
        $event->entry->set('foo', 'bar');
    }
}
```

2. Register the listener in your `EventServiceProvider`:
```php
protected $listen = [
    EntrySaving::class => [
        UpdateEntryData::class
    ],
];
```

3. Set `QUEUE_CONNECTION=redis` in your `.env`.
4. Start the queue worker: `php artisan queue:work`.
5. Go to the CP and save an entry. The data `foo: bar` will not be saved to the entry.
6. Stop the queue worker, remove the `ShouldQueue` interface from the listener and try again. The data will now be saved.

## Extra Detail
This issue seems only to be happening with the `EntrySaving` event. It doesn't happen with the `EntrySaved` event. You can test this by switching the event in your `EventServiceProvider` and using this line in your event listener instead:

```php
$event->entry->set('foo', 'bar')->saveQuietly();
```

Start your queue worker again and save the entry in the CP. The data will be saved.

## Environment
Statamic 3.1.29 Pro
Laravel 8.50.0
PHP 7.4.20
No addons installed

**Comment by aerni** [comment]
@jason This might be related to the Stache issue we've talked about through support email. It might also be related to https://github.com/statamic/cms/issues/2993.

**Comment by jasonvarga** [comment]
It doesn't make sense to queue a listener that listens for EntrySaving. That event is intended for you to prevent saving, or for adding data to the entry before it's saved. If you queue it, the listener will be run after the entry has already been saved.

If you're saying that EntrySaved works, use that. Or don't queue the listener.

**Comment by aerni** [comment]
Ah, I understand. I thought the saving would also be queued. Thanks for clarifying.
