### ISSUE TITLE
When editing asset media if the image is too large the Save and Delete buttons are off screen and not scrollable to

### ISSUE THREAD

**Issue by mattmultiplied** [statamic/cms#4023]
## Bug Description
When editing asset media if the image is too large the Save and Delete buttons are off screen and not scrollable to. 

## How to Reproduce
This has mainly happened when I've uploaded and image that's 900px X 900px in size. If I use the Chrome Zoom and zoom out the buttons display a lot further down, although for clients editing assets this could be confusing to them. I've recoded a Loom so you can see how the problem has occurred.

## Extra Detail
https://www.loom.com/share/22f64070bd3d4c15a780bca25df46579

## Environment
Statamic 3.1.29 Solo
Laravel 8.49.2
PHP 8.0.3
edalzell/variable 1.0.4
octoper/statamic-html-minify 0.0.5
spatie/statamic-responsive-images 2.7.1
withcandour/aardvark-seo 2.0.14

**Statamic version:** 3.1.29

**PHP version:** 8.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
I believe there were some recent changes to media size handling in that preview area. It's possible that width was considered but not height. Thanks!

https://github.com/statamic/cms/pull/3975
