### ISSUE TITLE
Cant open localized linked entry on multisite

### ISSUE THREAD

**Issue by benaja** [statamic/cms#4026]
## Bug Description
This error appears when you have a localised link field with different entries selected in the different sites.

When Im on an entry and changing the site, I only see the ID of the linked entry and when click on the id (that would normally open the entry in a popup), the popup opens, but it loads forever and in the console appears following error message: 
`isURLSameOrigin.js:57 Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined
    at isURLSameOrigin.js:57
    at xhr.js:108
    at new Promise (<anonymous>)
    at e.exports (xhr.js:13)
    at e.exports (dispatchRequest.js:50)`

## How to Reproduce
1. Fresh statamic installation
2. Enable multisite with 'php please multisite' and add al least a second site
3. Enable both sites in your pages collection
4. Edit the pages blueprint and add a "Link" field (name doesnt matter) and make it localizable.
5. Create two pages and make then available in both languages
6. Create a third page and select one of the pages just created before and click save
7. Go to the created page and switch to the other language
8. Edit the Link and select an other entry, then click save
9. When you now go again on that entry and switch the site it will only show the id of the linked entry and when you click on it the popup will load forever and in the console you can see the error mentioned above.

## Environment
**Statamic version:** 3.1.29 Pro
**PHP version:** 8.0.3
**Laravel version:** 8.50.0
**Install method:** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
I can't reproduce this. If this is still an issue, can you please create an example repo that we can check out? Thanks.
