### ISSUE TITLE
Last login date is not stored in user database

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#4030]
## Bug Description

Not sure if this a bug but I've configured Users to use a database, and last_login is null for all users. I've added the field to fillable and casts in App/Users.php, but the login date is never stored. 
![image](https://user-images.githubusercontent.com/414211/126324682-50ca5ef9-156d-43de-9d77-37c9ca874239.png)

**Comment by hellodavie** [comment]
This is related to https://github.com/statamic/cms/issues/3084, as the User model does not implement `Statamic\Contracts\Auth\User`, it fails the check performed here: https://github.com/statamic/cms/blob/6312ee8c4c9571914fb614f5f503acc41b10df73/src/Auth/SetLastLoginTimestamp.php#L13-L15

Then this results in the last login time not being set.

**Comment by dwainscheeren** [comment]
when will this be fixed?
