### ISSUE TITLE
Customise User Email Views

### ISSUE THREAD

**Issue by aerni** [statamic/cms#4036]
## Bug Description
I'm not sure if this is a bug or idea. So please move to your liking.

It would be great if we could publish the user invitation emails and all the other mails as well. In the CP you have the option to change the subject and message of the email. But there are other fields that you can't customize. This is especially a problem with multilingual sites. I need to translate all the texts, buttons, etc.

## Extra Detail
**Creating a user in the CP**

<img width="968" alt="Bildschirmfoto 2021-07-21 um 4 49 55 PM" src="https://user-images.githubusercontent.com/23167701/126509336-e71a2d3d-8150-4367-b120-e83ae7a51eae.png">

**Email the user receives**

<img width="646" alt="Bildschirmfoto 2021-07-21 um 4 50 52 PM" src="https://user-images.githubusercontent.com/23167701/126509490-07041541-6014-4604-af8c-368b5047d49f.png">

## Environment
Statamic 3.1.29 Pro
Laravel 8.50.0
PHP 7.4.20
aerni/livewire-forms 1.1.0
aryehraber/statamic-impersonator 2.2.0
doublethreedigital/duplicator 1.3.3
jonassiewertsen/statamic-livewire 2.6
spatie/statamic-responsive-images 2.7.1
visuellverstehen/statamic-classify 2.2.0
withcandour/aardvark-seo 2.0.14

**Comment by duncanmcclean** [comment]
Looks like it's currently hardcoded as a notification, there's no view involved right now. See https://github.com/statamic/cms/blob/87237100aa05916d4f288ca27066e537ea80b21e/src/Notifications/ActivateAccount.php#L39

**Comment by aerni** [comment]
Ah, I see. Do you know if it's possible to override that Notification with a custom one?

**Comment by duncanmcclean** [comment]
I don't _think_ you can. Might be wrong though.

**Comment by duncanmcclean** [comment]
Like I thought, seems like the `ActivateAccount` notification is hard coded in a couple places.

https://github.com/statamic/cms/blob/3.1/src/Auth/User.php#L167-L170
https://github.com/statamic/cms/blob/3.1/src/Http/Controllers/CP/Users/UsersController.php#L138-L139

**Comment by aerni** [comment]
Ok. Probably best to move this issue to the ideas repo then.

**Comment by jasonvarga** [comment]
Notifications are a Laravel thing.

You can customize them already: 
- https://statamic.dev/email#customizing
- https://laravel.com/docs/8.x/notifications#customizing-the-templates

**Comment by aerni** [comment]
Ah nice. Thanks Jason!
