### ISSUE TITLE
Content API for collection does not return all taxonomy fields

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#4039]
## Bug Description
When using the Content API to fetch a few entries by their tag, not all fields are returned. When fetching the tag itself via the API `"/taxonomies/tags/terms/${tag}"` (see screenshot 1), I get all additional fields.

But when using `"/taxonomies/tags/terms/{$tag}/entries"` to fetch the entries, only a handful of attributes are returned, see screenshot 2.

## How to Reproduce
Create a few entries, assign them tags and use the Content API to fetch a taxonomy by itself, and then with entries.

## Extra Detail

Screenshot 1

<img width="148" alt="Screenshot 2021-07-22 at 07 14 57" src="https://user-images.githubusercontent.com/3603346/126593247-ac5dc750-11bf-4c97-a5ef-7f4c5556cc89.png">

Screenshot 2

<img width="173" alt="Screenshot 2021-07-22 at 07 14 19" src="https://user-images.githubusercontent.com/3603346/126593317-a4788e6c-c0c2-4713-88f8-694433b9a4f8.png">

## Environment

Statamic 3.1.29 Pro
Laravel 8.50.0
PHP 8.0.5
jonassiewertsen/statamic-livewire 2.6
octoper/statamic-blade-components 1.0.1

**Comment by jasonvarga** [comment]
This is intentional. Nested relations only show a subset.
https://statamic.dev/extending/augmentation#shallow-augmentation
