### ISSUE TITLE
Add set button is showing on bard, even though there are no sets available

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#4044]
## Bug Description

One of my bard editors is showing the plus button (add set) when the field has no sets available. If I click the button then an empty white box is shown.

## How to Reproduce

Set up a bard field without any sets. Not sure if something else is causing the conflict.

## Extra Detail

![image](https://user-images.githubusercontent.com/20210934/126767275-d631b417-2e8e-48d8-b23f-7206cfd08f17.png)

## Environment

Laravel 8.51.0
PHP 7.4.16
edalzell/blade-directives 3.3

**Install method (choose one):**
- Existing Laravel app

**Comment by jasonvarga** [comment]
Can you paste the yaml for that bard field?

**Comment by twd3** [comment]
I would also make sure the "always show set button" option is NOT selected just to make sure it isn't that.

**Comment by stuartcusackie** [comment]
I just tried it out again and the problem is gone. The "always show set button" was not active, I did check at the time.

No problem anymore. Feel free to close the issue.

**Comment by tobyjug** [comment]
I've just experienced this. It only happens when there is no content in the bard field. If you add some text, 'Add set' button is no longer present.

**Comment by arthurperton** [comment]
Thanks @tobyjug, that seems to be it.
