### ISSUE TITLE
Edit Image View: Buttons not shown in certain browser window sizes

### ISSUE THREAD

**Issue by K3CK** [statamic/cms#4049]
## Bug Description
After updating to Statamic 3.1.28 or 3.1.29 the image editing screen doesn't show the edit buttons when the browser window's aspect ratio has certain values. This makes it hard or impossible to edit or save the image on certain devices. In our case especially editors on laptops with small screens did struggle with this problem.

## How to Reproduce
Update to Statamic 3.1.2, edit an image via the asset manager and change the window size so that the width is significantly higher than the height.

## Extra Detail
Example for a window aspect ratio where the buttons are missing:
![Missing_edit_buttons](https://user-images.githubusercontent.com/950495/126970235-c4f092a9-dfc5-46bb-92a7-df92e64c1b01.jpg)

## Environment
Statamic 3.1.29 Pro
Laravel 7.30.4
PHP 7.4.16
doublethreedigital/static-cache-manager 1.0.0
spatie/statamic-responsive-images 2.7.1

**Statamic version:** 3.1.28/29

**PHP version:** 7.4

**Install method (choose one):**
Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
I *think* this issue should be resolved by #4043..

**Comment by jasonvarga** [comment]
Yeah, that PR resolves it. Hang tight for next release.
