### ISSUE TITLE
GraphQL - entry uri filter does not work with multisite

### ISSUE THREAD

**Issue by valschr** [statamic/cms#4054]
## Bug Description
When querying an entry using the "uri" filter localized URLs return null instead of the entry. 

## How to Reproduce

This does return a result
```graphql
entry(uri: "/careers") {
    id
    site {
      name
    }
}
```

This returns null (I verified that the entry exists, is translated and published) 
```graphql
entry(uri: "/gb/careers") {
    id
    site {
      name
    }
}
```
sites.php
```php
'sites' => [
        'default' => [
            'name' => 'English US',
            'locale' => 'en_US',
            'url' => env('APP_URL'),
        ],
        'gb' => [
            'name' => 'English GB',
            'locale' => 'en_GB',
            'url' => env('APP_URL').'gb/',
        ],
    ],
```

Since there can be multiple pages with the same slug it is impossible to query a translated pages via the entry endpoint. 

This is the workaround I'm currently using
```graphql
entries(collection: "pages", limit: 1, filter: {uri: {is: "/careers"}, site: {is: "gb"}}) {
    current_page
    data {
      id
      title
      site {
        url
        locale
        name
        handle
        short_locale
      }
      uri
      url
    }
  }
```

## Environment

**Statamic version:** 3.1.30

**PHP version:** 7.4.19

**Install method (choose one):**
Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
The `uri` of the entry on the `gb` site would still be `/careers`. The `/gb` is not included in the `uri`. (The `url` has it.)

I'd suggest adding a `site` argument to your query, but it looks like we haven't added that yet. I've done this in #4055.

You'll be able to do:

```graphql
entry(uri: "/careers", site: "gb") {
  # ...
}
```

**Comment by valschr** [comment]
awesome, thank you!
