### ISSUE TITLE
Settings, Conditions and Validation are no longer tabs

### ISSUE THREAD

**Issue by granttransition** [statamic/cms#4063]
## Bug Description
Settings, conditions and validation links no longer display as tabs in Statamic dashboard

## Extra Detail
Screenshot
<img width="353" alt="statmic-dashboard" src="https://user-images.githubusercontent.com/23478154/127388290-b3e6e3fa-16ac-40a1-9642-4e6e6d6837d6.png">

## Environment

Statamic 3.1.31 Pro
Laravel 8.52.0
PHP 7.4.21
aryehraber/statamic-captcha 1.5.2
edalzell/forma 0.8.12
rias/statamic-redirect 1.4.6
silentz/mailchimp 2.5.6

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Rats. 🐀

**Comment by jackmcdade** [comment]
Fixed and released. Not gonna let naked tabs flap about in the wind like that!
