### ISSUE TITLE
htmlspecialchars() error after switching to Pro version

### ISSUE THREAD

**Issue by DavidKrenekCZ** [statamic/cms#4064]
## Bug Description
CMS panel stop working after switching from Solo to Pro version because of `htmlspecialchars()` error in menu views (see attachments above). If I'll remove menu labels, panel start working (but there are of course no labels in menu items :-) ). Only change in code is in `editions.php` config file - `pro` value set from `false` to `true`.

## Extra Detail
![statamic-1](https://user-images.githubusercontent.com/22493634/127450345-bacddb12-3b6c-47fa-a334-26098ce7dd9f.png)
![statamic-2](https://user-images.githubusercontent.com/22493634/127450347-9a39b59d-8105-49c3-adfe-0b0a67bfed1d.png)
![statamic-3](https://user-images.githubusercontent.com/22493634/127450353-c7c34a14-bcfb-46fd-b85f-94cbad822dd9.png)
![statamic-4](https://user-images.githubusercontent.com/22493634/127450357-12ad4b8a-a143-499d-b697-53a42b49b661.png)

## Environment
Statamic 3.1.32 Pro
Laravel 8.52.0
PHP 7.4.2
No addons installed

**Install method:**
- Existing Laravel app

**Comment by jbrhel** [comment]
@DavidKrenekCZ Are you using any translations from resources/lang? I think that I had a similar issue recently. Try to put your frontend translations to separate folder eg: resources/lang/front/menu.php.

**Comment by duncanmcclean** [comment]
Which locale are you using in `app.php`?

**Comment by DavidKrenekCZ** [comment]
Thank you guys, it was caused by different locale in `app.php`. I wanted to prepare `cs` locale, but for now there was only boilerplate files of new translation in resources folder, where was maybe some mistake .. ? So I switched back to default `en` locale and now everything works. So I don't know if it should be treated also in CMS in any way? For me can be closed.

**Comment by edalzell** [comment]
> For me can be closed.
