### ISSUE TITLE
diffForHumans() not working correctly with German locale

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#4065]
## Bug Description
Within an antlers.html file, I include a Livewire Blade component (via [this addon](https://statamic.com/addons/jonassiewertsen/livewire)). In the Blade file, I have this line: `$comment->created_at->diffForHumans()`. It gives me `XX minutes ago`, in English. I also have a few regular Blade files that are not connected with Statamic and using the same code (`$model->created_at->diffForHumans()`), I get `vor XX Minuten`, in German.

Due to the fact that I have my locale set to German (de), the latter is expected and Statamic views don't seem to care about that setting. Within my AppServiceProvider `boot()` method, I also set this: `Carbon::setLocale(config('app.locale'));`.

## How to Reproduce
Just do what is described in the bug description. The same problem occurs without that addon. Maybe I missed something setting the language for Statamic, but the CP is also German, so that works.

## Environment

Statamic 3.1.32 Pro
Laravel 8.52.0
PHP 8.0.5
jonassiewertsen/statamic-livewire 2.6
octoper/statamic-blade-components 1.0.1

**Install method:**
- Existing Laravel app

**Comment by jackmcdade** [comment]
How did you set your locale to German?

**Comment by MrMooky** [comment]
In `config/app.php` I set `'locale' => 'de'`. Right after that, the CP appeared in German. Additionally, I set `Carbon::setLocale(config('app.locale'))` in my `boot()` method, as described in the bug description. That's all I did.

**Comment by duncanmcclean** [comment]
Thanks! I can reproduce as well, by instead using `{{ now | relative }}` in one of my templates.

**Comment by jasonvarga** [comment]
The locale comes from the site you're visiting as defined in `config/statamic/sites.php`.
