### ISSUE TITLE
in_array or contains not working as expected

### ISSUE THREAD

**Issue by rustypaul** [statamic/cms#4066]
Hi Guys, 

I'm having trouble checking to see if a value is in an array. I have a collection called websites, and it has an array of software which is an entries field pointing to another collection called software. I'm running the code below on the show page for the specific software entry

```
{{ collection:websites }}
            {{ software }}
                {{ if id == page:id }} 
                    <p>manual: {{ id }}</p>
                {{ /if }}
            {{ /software }}

            {{ if software | contains:{page:id} }}
                <p>in_array: {{ id }}</p>
            {{ /if }}
{{ /collection:websites }}
```

The manual loop running through the software loop correctly matches ids, but the contains loop doesn't. I get the same result using in_array.

The software entry id looks like this in its .md file
```
id: 61dec82d-101f-4417-a208-ad5d0d7dc34d
```

and the website entry looks like this
```
software:
  - 61dec82d-101f-4417-a208-ad5d0d7dc34d
```

Even if I manually add the id as a string to the `contains` variable it still doesn't recognise it

**Comment by duncanmcclean** [comment]
Hey! When creating future issues, please go along with the provided issue template. It really does help us to collect all the information required to fix issues.

Anyways, to your issue - I've had success in the past by converting an array like that to json just before doing a `contains` check. Maybe that way will work for you?

```
{{ if software | to_json | contains:{page:id} }}
    <p>in_array: {{ id }}</p>
{{ /if }}
```

**Comment by duncanmcclean** [comment]
Ahh, in fact, I can't get that working either. 🤔  Nevermind.

**Comment by j3ll3yfi5h** [comment]
I'm quite sure that this one is related:
#3954 

I think you're collection loop could also look like this:
`{{ collection:websites :software:contains="{id}" }}`

But currenty this does not work.

(also my question of today: https://discord.com/channels/489818810157891584/861719048697675786/885832028879192094)

**Comment by edalzell** [comment]
> I think you're collection loop could also look like this:
> `{{ collection:websites :software:contains="{id}" }}`

This syntax would be wrong. Can't use `:` AND `{... }`
