### ISSUE TITLE
Package installation method failed: league/commonmark conflict

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#4071]
## Bug Description

Laravel 8.5.22 is using league/commonmark 2.0, where as the latest statamic is locked at ^1.5.

Just flagging in case nobody spotted it. I can install statamic using the cli instead.

## How to Reproduce

Install latest laravel and then install statamic using package method.

## Environment
**Statamic version:** 3.1.32

**Comment by duncanmcclean** [comment]
Linking this Discord conversation in here (related to updating Statamic to use Commonmark 2) https://discord.com/channels/489818810157891584/489818810157891586/869187690363498506

**Comment by miclf** [comment]
The `^1.5` version locked by Statamic indeed prevents anybody to use version `2+`. I’ve stumbled upon this very annoying issue yesterday.

In addition, [Laravel will drop support for version 1](https://github.com/laravel/framework/pull/37953) in its next major release.

**Comment by jasonvarga** [comment]
If you install Statamic _after_ installing Laravel, you will need to do `composer require statamic/cms --with-dependencies`.

We'll update the docs.
