### ISSUE TITLE
Warming Static Cache shows errors

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#4082]
## Bug Description

When I warm the static cache locally (for testing purposes), I see the first bunch of urls get an `x` instead of a checkmark. There are no errors in the log.

<img width="591" alt="CleanShot 2021-08-02 at 14 10 32@2x" src="https://user-images.githubusercontent.com/6069653/127924296-b2d92845-ecbc-4bb7-970f-4ad45c57c532.png">
<img width="501" alt="CleanShot 2021-08-02 at 14 10 47@2x" src="https://user-images.githubusercontent.com/6069653/127924324-626d30e4-33e4-436d-b6a8-609ad79e9de0.png">

All those URLs work fine when you visit them.

In production it's only `x`s, looks like it doesn't work there?
<img width="509" alt="CleanShot 2021-08-02 at 14 11 26@2x" src="https://user-images.githubusercontent.com/6069653/127924418-4e08967f-d5fa-4b01-b074-0035f5cde5e1.png">

## How to Reproduce

1. have a big site
2. clear the cache
3. warm the stache
4. clear the static cache
5. warm the static cache

## Environment

```
Statamic 3.1.32 Pro
Laravel 8.52.0
PHP 8.0.8
aryehraber/statamic-captcha 1.5.2
aryehraber/statamic-uuid 2.0.3
edalzell/forma 0.8.12
jonassiewertsen/statamic-livewire 2.6
statamic/seo-pro 2.2.1
transformstudios/events 2.2
transformstudios/front 1.2.1
transformstudios/magic-link dev-main
transformstudios/prayer-times dev-staging
transformstudios/review 3.1
transformstudios/simple dev-main
transformstudios/stripe dev-main
transformstudios/takeover-redirects dev-main
```

**Comment by arthurperton** [comment]
Hi Erin, could you check if it helps to have the correct `APP_URL` in your `.env` file?

**Comment by edalzell** [comment]
I always have that set

**Comment by arthurperton** [comment]
I'm not able to replicate this, so let's have a closer look at your setup. There is some things you could try to help analyse the problem:

* You could add `$response->throw();` to the end of `outputResponseLine()` to get some more info on what goes wrong.
* Switching between `APP_ENV=local` and `APP_ENV=production` in my `.env` file doesn't make a difference. Does that change anything for you when testing locally? If not, what might be the other differences between your local and production setup?
* Do you have any idea why locally your `/articles/...` work and your `/events/...` don't? Any remarkable differences in configuration?

**Comment by edalzell** [comment]
ok @arthurperton got some time to try this locally.

First failure is:
```
[✗] /zf-expands-services-opening-east-coast-office
HTTP request returned status code 500:
<!doctype html>
<html class="theme-light">
<!--
Error: Class &quot;Facades\Statamic\Fields\FieldsetRepository&quot; not  (truncated...)
```

This page DOES exist and does NOT throw an error if you visit it.

Next bunch were:

```
[✗] /zf-ground-tornado-struck-alabama
HTTP request returned status code 504:
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><c (truncated...)
```

Again, pages exist do not throw an error.

**Comment by edalzell** [comment]
I also noticed that when there are errors I don't see all the routes actually shown.

If break (dd) in the `uris()` method, on this site, I get 2500 URIs, which is about right. When I get errors I only see maybe 50 uris.

<img width="1338" alt="CleanShot 2021-08-14 at 16 36 08@2x" src="https://user-images.githubusercontent.com/6069653/129462700-7e225307-0b9d-442e-b7a6-b2befe3973a5.png">

**Comment by arthurperton** [comment]
Thanks Erin, this is very helpful. I’m gonna try and look into this tomorrow. First thoughts:

- I’m very curious about the full version of the first error. Something about the FieldsetRepository, wonder what that could be. Perhaps there is a way to see the full error.
- The other bunch are timeouts obviously. I’m starting to think the pool size for the concurrent requests might be too large. I think that can be configured. If so we should give that a try.

Thanks again and if you find out anything more please add.

**Comment by edalzell** [comment]
First error was class not found

**Comment by arthurperton** [comment]
Just added a lot (250+) of entries. Still not getting any errors, but it does take a long time and **it just shows only a small portion of the URLs**, just like you described Erin.

I am not able to configure the pool size through the Laravel wrapper with any positive effect. Switching back to the original Guzzle implementation seems to work, at least all the available URLs are visited and displayed.

To be continued.
