### ISSUE TITLE
Querying a dimension of a SVG with GraphQL breaks when it is of type float

### ISSUE THREAD

**Issue by el-schneider** [statamic/cms#4088]
## How to Reproduce
Querying `width` or `height` of an `svg` image breaks when it is a float
```graphql
image {
  width
  height
}
```

## Extra Detail

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1519.18 668.62">
```

```json
"debugMessage": "Expected a value of type \"Int\" but received: 1519.18",
"message": "Internal server error",
"extensions": {
  "category": "internal"
},
```

## Environment

**Statamic** 3.1.32 Pro
**Laravel** 8.49.1
**PHP** 7.4.22

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by el-schneider** [comment]
Thanks @arthurperton! Saves my day.

**Comment by arthurperton** [comment]
😄 You're welcome @el-schneider!
