### ISSUE TITLE
Independent Auth Guard and inviting new Statamic users

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#4089]
## Bug Description
When using an Independent Authentication Guard, I am not able to invite users to join the Statamic backend. I create a new user, send the "Activation URL", but the user cannot sign up. Error says that the user cannot be found. The `user-email.yaml` is created, though.

## How to Reproduce
See video.

## Extra Detail
https://www.loom.com/share/40d6c627efc64aa582b60e0bfbd80a03

**config/statamic/users.php**

```
'guards' => [
    'cp' => 'statamic',
    'web' => 'web',
],
```

**config/auth.php**

```
'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],

    'statamic' => [
        'driver' => 'session',
        'provider' => 'statamic',
    ],

    'api' => [
        'driver' => 'token',
        'provider' => 'users',
        'hash' => false,
    ],
],
```

## Environment

Statamic 3.1.32 Pro
Laravel 8.52.0
PHP 8.0.5
jonassiewertsen/statamic-livewire 2.6
octoper/statamic-blade-components 1.0.1

**Install method:**
- Existing Laravel app

**Comment by duncanmcclean** [comment]
I wonder if this could be related to #3795... maybe it's looking in Eloquent rather than Statamic?

**Comment by MrMooky** [comment]
@duncanmcclean It appears so because when I try to enter an existing user (in database), I get the following error:

<img width="1235" alt="Screenshot 2021-08-04 at 12 05 34" src="https://user-images.githubusercontent.com/3603346/128163267-0ec01e4e-5b35-4a21-8d40-b59351eea3bd.png">

**Comment by duncanmcclean** [comment]
Gotcha, that's the same error mentioned in the other issue. 👍 

I'll close this now as it's a duplicate. If you find anything else, feel free to pop it in the other issue.
