### ISSUE TITLE
No "tree" storage configuration - issue with Envoyer setup

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#4096]
## Bug Description
Due to the fact that I'm deploying Statamic with Envoyer, my folder structure is a bit different on my production server, see below. So I updated my `stache.php` file like this:

```
'collections' => [
    'class' => Stores\CollectionsStore::class,
    'directory' => base_path((config('app.env') == 'local' ? '' : '../../').'content/collections'),
],
```

Due to a sorting difference on localhost vs. production, I noticed that there was no "Store::class" for trees. But since they store the sorting I do in the backend, I have different results on dev and live.

When I log into the backend on my live server and sort again, a "content/trees/collections/" folder is created inside the current release with the correct sorting. All other content is stored in my root because of the changes I made you see at the top. But the tree is not present here, so I cannot set the storage path.

So basically, Statamic looks in `root/current` (which is a symlink to root/releases/latest/content/trees/collections/something.yaml), instead of `root/content...`.

I hope that makes sense. It does for me, obviously. ._.

## Extra Detail

This is my folder structure on my production server:

<img width="157" alt="Screenshot 2021-08-07 at 12 32 57" src="https://user-images.githubusercontent.com/3603346/128597295-31adf0b5-b09a-43ac-9f5e-86817ea2a029.png">

`content` and `users` belong to Statamic and are not deployed during pushing via Envoyer. I do that manually via FTP... To be honest, I did not know how to set this up and could not find a documentation for this.

## Environment

Statamic 3.1.32 Pro
Laravel 8.53.1
PHP 8.0.5
aryehraber/statamic-captcha 1.5.2
jonassiewertsen/statamic-livewire 2.6
mitydigital/statamic-tinymce-cloud 1.0.3
octoper/statamic-inline-assets 4.0.3
pecotamic/sitemap 1.2.5

**Install method:**
- Existing Laravel app

**Comment by jasonvarga** [comment]
We changed the `stache.php` config file to not requiring the `stores` be listed there unless you want to customize them.

Take a look at the current stache config file:

https://github.com/statamic/statamic/blob/556fd68f1ec2a1a8089cc308945c40361e9a0fd2/config/statamic/stache.php#L29-L31

There are no stores at all.

```php
'stores' => [
    //
],
```

You're probably using an older version of the config file which had them all.

You're free to just add the tree stores and customize them as needed:

```php
'collection-trees' => [
    'directory' => base_path('content/trees/collections'),
],

'nav-trees' => [
    'directory' => base_path('content/trees/navigation'),
],
```

**Comment by MrMooky** [comment]
@jasonvarga Thanks for the info. It works now after adding the missing store there. But just FYI, I recently started another project (2 minor versions prior to the current one) and the `stores` array was definitely not empty, it even included the one missing (`collection-trees`) from my somewhat older project.

**Comment by jasonvarga** [comment]
If you use statamic/statamic to start your project it should be gone.
If you used a starter kit like Peak, it looks like there's an outdated config file there, which is out of our control.

**Comment by duncanmcclean** [comment]
Ah, that's a good point. I presume that when installing in an existing application, this config will be used. https://github.com/statamic/cms/blob/3.1/config/stache.php

**Comment by jasonvarga** [comment]
Ah yes good point. Thanks!
