### ISSUE TITLE
All files using `image` validation rule error with 'file does not exist' since v3.1.27 when using S3

### ISSUE THREAD

**Issue by bakerkretzmar** [statamic/cms#4097]
## Bug Description

Since Statamic v3.1.27, all asset fields using the `image` validation rule and pointing to an S3 filesystem disk fail validation and can't be saved, the control panel shows a 'File does not exist' error for all files. The error originates from the `passes` method in the new `AssetRule`, because it tries to instantiate a Symfony file using a filesystem path that doesn't include the remote asset URL (e.g. `/profile-pic-2.jpeg`), but when using an S3 disk the file is of course not present locally.

https://github.com/statamic/cms/blob/e2b4fd90b50348464ad0b8576bffb76a9e27015a/src/Fieldtypes/Assets/AssetRule.php#L44-L50

## How to Reproduce

Verified in a fresh site locally:

1. Set up a new Statamic site.
1. Install `league/flysystem-aws-s3-v3` v1, may require downgrading guzzle.
1. Create a DigitalOcean 'Space' and a new filesystem disk in the Statamic app using the S3 driver and the Spaces credentials.
1. Edit the default Page blueprint to include an asset field using the `image` validation rule.
1. Go to Assets and upload anything.
1. Edit the homepage to choose an image.
1. Save the page, see a 'file does not exist' error for the file you just uploaded.

## Environment

**Statamic version:** 3.1.27 Pro

**Laravel version:** 8.53.1

**PHP version:** 8.0.9

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Thanks!

**Comment by arthurperton** [comment]
I just had a look and tried falling back to the `absoluteUrl()` when the file doesn't exist locally:

```php
try {
    $file = new File($asset->resolvedPath());
} catch (FileNotFoundException $e) {
    $file = new File($asset->absoluteUrl(), false);
}
```
 
That logic actually works, but the underlying Symfony code that checks the mime type just isn't written to work with remote files via http(s) and fails 🙁.

So, I'm afraid I'll have to revert #3922 and fix #3820 by just adding another custom rule.

**Comment by arthurperton** [comment]
...or we could just copy the file locally to do the inspection, just like in `Statamic\Assets\Dimensions->getImageDimensions()`. What do you think of that option @jasonvarga ?

**Comment by jasonvarga** [comment]
Copying the file (in your `catch` example there) to a temporary local place sounds like a pretty good solution.

**Comment by arthurperton** [comment]
I am a bit worried about performance / UX. All assets would be copied locally, for every validator, every time you save.

**Comment by jasonvarga** [comment]
Then try the other thing 🙂

**Comment by arthurperton** [comment]
Hahaha 😆 okay will do!
