### ISSUE TITLE
Improve User-Based Collection Filters

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#4101]
RIght now if you want to filter by Author (for example) you need to do `is` and pass the user's ID. Would be great if this field had an "is me" option, as well as the ability to search by related object fields (name, email, etc). 

<img width="284" alt="CleanShot 2021-08-09 at 08 58 39@2x" src="https://user-images.githubusercontent.com/44739/128710017-789fff99-ba14-4d7c-83b1-66ef609933f0.png">

**Comment by jasonvarga** [comment]
We already have full control over those.

We just don't have special handling for the `users` fieldtype, so it falls back to those generic options.
We could make a separate filter just for the `users` fieldtype.
