### ISSUE TITLE
Creating a search index for users doesn't seem to return any results

### ISSUE THREAD

**Issue by rustypaul** [statamic/cms#4102]
## Bug Description
I've created a search for users in the front end of our website (it's internal so only employees who have accounts can see it). The search index doesn't return anything though.

## How to Reproduce
Create a search index
```
        'all_users' => [
            'driver' => 'local',
            'searchables' => 'users',
            'fields' => ['name', 'description', 'title', 'email'],
        ],
```

return search results
```
{{ search:results index="all_users" paginate="true" limit="20"}}
   {{ if no_results }}
      <h2 class="py-3 px-4">No users found for <span class="font-semibold">{{ get:q | sanitize }}</span>.</h2>
   {{ else }}
      {{ partial:users.table-row }}
   {{ /if }}
{{ /search:results }}
```

**Platform info:**
Mac Big Sur running on Laravel Valet
Statamic 3.1.32 Pro
Laravel 8.52.0
PHP 8.0.8
aryehraber/statamic-font-awesome 2.2.0
edalzell/variable 1.0.4
simonhamp/statamic-heroicons 1.0.1
spatie/statamic-responsive-images 2.7.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Just came across this issue. It looks like the problem is you are doing `'searchables' => 'users'` but it should be an array. `'searchables' => ['users']`
