### ISSUE TITLE
Difficulty retrieving a variable via page id reference in a `get_content` from a global

### ISSUE THREAD

**Issue by sjclark** [statamic/cms#4105]
## Bug Description
Have just updated a site from 3.0.49 to Statamic 3.1.32 Pro - bit of a jump. A few things broke - but this is the only one I don't seem to be able to figure out.

Previously this code worked:
```
{{ programme_settings:homepage_selector }}
<div class="w-full" style="background-color: {{ header_image_extended_colour }};">
    <div class="max-w-screen-xl mx-auto">
        <img class="object-cover w-full" src="{{ homepage_header_desktop:url }}" alt="">
    </div>
</div>
{{ /programme_settings:homepage_selector }}
```
However, after updating this no longer works.

<img width="313" alt="Screen Shot 2021-08-10 at 11 09 45 pm" src="https://user-images.githubusercontent.com/4531017/128872722-8d494478-0f93-48ff-85c2-0f445db4a267.png">
<img width="402" alt="Screen Shot 2021-08-10 at 11 10 08 pm" src="https://user-images.githubusercontent.com/4531017/128872727-75d0c437-c418-4dc3-949a-22b39be6cd90.png">

`programme_settings` is a global, with a **page select** field called `homepage_selector` - which is stored as an id

`header_image_extended_colour` is a variable from the `homepage_selector` page which I'm trying to get.

I thought maybe something has been changed and I would have to refactor my code to something like this:
`{{ get_content from="{programme_settings:homepage_selector}" }}` 
however, that also doesn't work. If I hard-code in the page id from the global (`homepage_selector: e0699782-5d03-4240-9f8b-617ce25b25bb`), then it works.

I've gone through the changelog but can't seem to find what would have broken the code above.

Bit of a hard one to explain, but would really appreciate any ideas / assistance. 😀

**Essentially I'm just trying to find the best way to pull a value from a page via it's page id reference in a site global.**

## Environment
Statamic 3.1.32 Pro
Laravel 8.53.1
PHP 8.0.9
doublethreedigital/duplicator 1.3.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Try this: `{{ get_content :from="programme_settings.homepage_selector" }}`

**Comment by sjclark** [comment]
> Try this: `{{ get_content :from="programme_settings.homepage_selector" }}`
> 
> Also, maybe try your original again but with a `.`, not a `:`.

Thanks @damcclean - have tried:
```
{{ get_content :from="programme_settings.homepage_selector"  }}
{{ get_content :from="{programme_settings.homepage_selector}" }}
{{ get_content :from="programme_settings:homepage_selector"  }}
{{ get_content :from="{programme_settings:homepage_selector}" }}
```
and also with and without the leading `:` on the `from` (and probably a few others)

Having a hard time wrapping my head around how to approach this! 😆 

Just to confirm the data stored in the global:
<img width="640" alt="Screen Shot 2021-08-11 at 8 28 44 am" src="https://user-images.githubusercontent.com/4531017/128943118-d1162f84-80b5-4183-b043-380bc64277dc.png">

and the page data itself (have moved the id to the top);
<img width="793" alt="Screen Shot 2021-08-11 at 8 31 36 am" src="https://user-images.githubusercontent.com/4531017/128943361-70280677-8425-483d-9775-a08ae92a548d.png">

**Comment by edalzell** [comment]
`{{ get_content from="{programme_settings:homepage_selector}" }}`

Note the missing `:`

**Comment by sjclark** [comment]
> `{{ get_content from="{programme_settings:homepage_selector}" }}`
> 
> Note the missing `:`

Thanks @edalzell but unfortunately that was one of the first things I tried - referenced in my first post, and response to Duncan

<img width="713" alt="Screen Shot 2021-08-12 at 8 25 41 am" src="https://user-images.githubusercontent.com/4531017/129111751-01c86115-c05f-4d04-b470-4832a7af3717.png">

**Comment by edalzell** [comment]
What about:

```
{{ programme_settings }}
    {{ get_content :from="homepage_selector" }}
{{ /programme_settings }}
```

**Comment by sjclark** [comment]
> What about:
> 
> ```
> {{ programme_settings }}
>     {{ get_content :from="homepage_selector" }}
> {{ /programme_settings }}
> ```

@edalzell didn't work BUT you 100% got me thinking down the right path - turns out its something to do with **augmentation** (should've thought of it earlier). Did a few more dumps, threw in a `raw`. Success.

```
{{ programme_settings }}
    {{ get_content from="{homepage_selector|raw}" }}
<div class="w-full" style="background-color: {{ header_image_extended_colour }};">
    <div class="max-w-screen-xl mx-auto">
        <img class="object-cover w-full" src="{{ branding_header_desktop|url }}" alt="">
    </div>
    </div>
    {{ /get_content }}
{{ /programme_settings }}
```
I guess previously it used to directly augment my initial code right through to the necessary content (without the need for get_content), whereas now it augments to ahhhh something else that doesn't work for me but is no doubt logical in some bigger context!

Cheers for the help - definitely got me facing in the right direction. 👍
