### ISSUE TITLE
GraphQL: render Forms

### ISSUE THREAD

**Issue by SteJW** [statamic/cms#4112]
## Bug Description
I'm getting an error when I try to get a form from an entry using the GraphQL. The error I get is:
Expected a value of type \"String\" but received: instance of Statamic\\Forms\\Form

I'm assuming the Forms hasn't been added to the GraphQL yet.

## How to Reproduce
- Add an entry
- Connect a form using the grid or the page builder
- Run the GraphQL Query builder with:
`query MyQuery {
  entry(slug: "home", collection: "pages") {
    id
    title
    slug
    ... on Entry_Pages_Page {
      id
      grid {
        label
        title
        form
      }
    }
  }
}
`
## Environment
Statamic 3.1.32 Pro
Laravel 8.52.0
PHP 7.4.12

**Comment by jasonvarga** [comment]
How were you planning to use `form` there?
If you were able to get the handle, what would you do with it?

**Comment by SteJW** [comment]
We're building the frontend using Next.js and are using the GraphQL to setup the components. The navigation, entries etc. are perfectly accessible, except for the forms. That's why we need all the functionality in Forms that is available in the Statamic CMS to get with GraphQL. Or are there other ways to do it?

**Comment by SteJW** [comment]
Do you have enough information of the usage case? Or would you like me to clarify it a bit more?
