### ISSUE TITLE
Using a colon in a blueprint's title breaks things

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#4114]
## Bug Description

It's probably a bad idea but I tried to call a blueprint **Page: Why** (it's a blueprint for a 'Why' page).

Anyway, this happened:

`Statamic\Http\Controllers\CP\Collections\CollectionBlueprintsController::toVueObject(): Argument #1 ($blueprint) must be of type Statamic\Fields\Blueprint, null given, called in /home/vagrant/example.test/vendor/statamic/cms/src/Http/Controllers/CP/Collections/CollectionBlueprintsController.php on line 44`

## How to Reproduce

Stick a colon in the title when creating a new blueprint.

## Extra Detail

![image](https://user-images.githubusercontent.com/20210934/129181796-230d8ee3-bed4-4837-86f7-795bfd85bfcb.png)

## Environment
Statamic 3.1.32 Pro
Laravel 8.54.0
PHP 7.4.16

**Comment by jasonvarga** [comment]
I couldn't trigger an error when calling the blueprint `Page: Why` - however I was able to get the error when calling it `Page: Why?` with a question mark.

If you used a question mark when you actually tried it - but just didn't put it in the issue - I'd say that's the actual problem here.

**Comment by stuartcusackie** [comment]
I've doubled-checked this and I actually did not use a question mark. A simple colon instantly breaks it for me.

If I check the resources/blueprints/collections/pages folder then I see this:

![image](https://user-images.githubusercontent.com/20210934/130056491-52b45f10-788a-4678-876c-5513caefb13e.png)

**Comment by jasonvarga** [comment]
What URL do you end up on after you hit the Create Blueprint button?

**Comment by stuartcusackie** [comment]
Oh yeah, that is an important clue that I forgot to mention. This is the url of the error screen that shows when I click 'Create Blueprint':

`http://mywebsite.test/cp/collections/pages/blueprints/page:_why/edit`

The 'Page: ' bit has been stripped automatically.

**Comment by jasonvarga** [comment]
I couldn't reproduce creating a `page` file (without .yaml) at all.

In the fix I committed, it'll slugify the name anyway. e.g. Enter `Page: Why?` and it'll make `page_why.yaml`.
