### ISSUE TITLE
Entries Fieldtype Throws Error

### ISSUE THREAD

**Issue by aerni** [statamic/cms#4117]
## Bug Description
I've got a custom fieldtype that groups several core Statamic fieldtypes, including an `Entries` fieldtype. The `Entries` fieldtype throws an error in the CP: `Component entries-fieldtype does not exist.`

I inspected my custom fieldtype with the Vue devtools and noticed that it's missing the config item `component: relationship`. This config item gets added automatically to any other `Entries` fieldtype you manually add to your blueprint.

You can get around this issue by adding `'component' => 'relationship'` to your fieldtypes field config.

I'm not sure if there are other things involved with this issue, that I didn't notice in plain sight.

## How to Reproduce

1. Use the following Fieldtype and Component and add it to your blueprint.
2. You will notice the error (see screenshot below).
3. Add `'component' => 'relationship'` to the entries fieldtype config.
4. The error is now gone.

**Fieldtype:**

```php
<?php

namespace App\Fieldtypes;

use Statamic\Fields\Fields;
use Statamic\Fields\Fieldtype;

class CustomFieldtype extends Fieldtype
{
    public function preProcess($data): array
    {
        return $this->fields()->addValues($data ?? [])->preProcess()->values()->all();
    }

    public function preload(): array
    {
        return [
            'fields' => $this->fieldConfig(),
            'meta' => $this->fields()->addValues($this->field->value())->meta(),
        ];
    }

    protected function fields(): Fields
    {
        return new Fields($this->fieldConfig());
    }

    protected function fieldConfig(): array
    {
        return [
            [
                'handle' => 'entries',
                'field' => [
                    'type' => 'entries',
                    'mode' => 'default',
                    'listable' => 'hidden',
                    'display' => 'Entries',
                    'localizable' => true,
                ],
            ],
        ];
    }
}
```

**Component:**

```vue
<template>
    <div class="publish-fields">
        <publish-field
            v-for="field in fields"
            :key="field.handle"
            :config="field"
            :value="value[field.handle]"
            :meta="meta.meta[field.handle]"
            :read-only="! field.localizable"
            class="form-group"
            @meta-updated="metaUpdated(field.handle, $event)"
            @focus="$emit('focus')"
            @blur="$emit('blur')"
            @input="updateKey(field.handle, $event)"
        />
    </div>
</template>

<style>
    .custom-fieldtype > .field-inner > label {
        display: none !important;
    }
    .custom-fieldtype,
    .custom-fieldtype .publish-fields {
        padding: 0 !important;
    }
</style>

<script>
    export default {
        mixins: [Fieldtype],
        computed: {
            fields() {
                return _.chain(this.meta.fields)
                    .map(field => {
                        return {
                            handle: field.handle,
                            ...field.field
                        };
                    })
                    .values()
                    .value();
            }
        },
        methods: {
            updateKey(handle, value) {
                let customValue = this.value;
                Vue.set(customValue, handle, value);
                this.update(customValue);
            }
        },
    }
</script>

```

## Extra Detail

**This is how the error looks like:**

 <img width="890" alt="Bildschirmfoto 2021-08-13 um 12 01 44 PM" src="https://user-images.githubusercontent.com/23167701/129340624-2375e595-aebc-4050-80dc-d65a69d7d7e2.png">

**And this is how it looks AFTER adding `'component' => 'relationship'` to the field's config:**

<img width="892" alt="Bildschirmfoto 2021-08-13 um 12 02 14 PM" src="https://user-images.githubusercontent.com/23167701/129340714-1eb89b7e-0bf7-479a-9f70-2704af98b99c.png">

## Environment

Statamic 3.1.32 Pro
Laravel 8.54.0
PHP 7.4.20

**Comment by jasonvarga** [comment]
That's just how it works. If you're going to manually pass along config like that, make sure component is in there.
