### ISSUE TITLE
GraphQL - Linked entries & taxonomies are always using the default site / language

### ISSUE THREAD

**Issue by valschr** [statamic/cms#4119]
## Bug Description

When linking an entry or a taxonomy using the Entries / Taxonomy Terms fieldtype the entries or taxomies are always using the default language rather than the parent entry language. 

## How to Reproduce
(variables were changed for ease of readablilty) 
```graphql
query TeamSorter {
  terms(taxonomy: "team_tax", filter: {site: "de"}) {
    data {
      id
      ... on TeamTax {
        id
        title
        display_title
        main_category
        order
        main_children {
          ... on Term_TeamTax_TeamTax {
            id
            title
            display_title
            order
            seo
          }
        }
      }
    }
  }
}

```

## Environment
Statamic 3.1.30 Pro
Laravel 8.44.0
PHP 7.4.19
latam/gitamic dev-master
statamic/seo-pro 2.2.1

**Statamic version:** 3.1.30

**PHP version:** 7.4.19

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by arthurperton** [comment]
Hi @valschr, thanks for your report.  I'm trying to reproduce your issue but whatever I try I'm getting the term's data in the correct language. Could you check if this is still an issue on v.3.1.34 and if so, provide some exact steps to reproduce the issue from a fresh install?

**Comment by jasonvarga** [comment]
Same here. Everything seems fine unless we're misunderstanding the issue.

If you could provide a github repo with this bug recreated, that would be helpful.
