### ISSUE TITLE
No rounded corners on the blueprint table cell :hover

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#4120]
## Bug Description
Another show stopper here ;-)

## How to Reproduce
Hover over one of the top items in the blueprints table. 

## Extra Detail
https://user-images.githubusercontent.com/69107412/129364075-bc4690bc-1421-43f1-a07b-1c36bef9a78a.mov

## Environment
Statamic 3.1.33 Pro
Laravel 8.54.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by jackmcdade** [comment]
Fixed in 1ea06666b546e33f5b21b47448c76fd25f1acdd8
