### ISSUE TITLE
Entries field on User blueprint causing error

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#4123]
## Bug Description

When you have an `Entries` field on the User blueprint and an entry is selected, the whole Control Panel is rendered useless for the current user.

![image](https://user-images.githubusercontent.com/19637309/129445053-69f5a058-cccb-4534-8dbf-cd238fcc35d9.png)

## How to Reproduce

1. Add `Entries` field to User blueprint & save blueprint
2. Edit current user's profile, select entry and save.
3. Go to another page in the CP - nothing works.

## Extra Detail

Screenshot provided in 'Bug Description'

## Environment

Statamic 3.1.33 Pro
Laravel 7.30.4
PHP 7.4.21
aryehraber/statamic-captcha 1.5.2
doublethreedigital/sc-digital-products 2.2.1
doublethreedigital/simple-commerce 2.3.18
statamic/seo-pro 2.2.1

**Comment by arthurperton** [comment]
Hi Duncan, thanks for the report. Currently I am not able to reproduce this using the described steps. Other pages keep working, no JS errors.

Any more specifics you can share?

Tested in Safari and Chrome
Statamic 3.1.34 Pro
Laravel 8.51.0
PHP 7.4.22
No addons installed

**Comment by duncanmcclean** [comment]
I'll see if I can reproduce it this evening on a fresh site 👍

**Comment by duncanmcclean** [comment]
Just closed a duplicate issue of this issue, #4183. 

There's slightly different reproduction steps in there, maybe that'll help you to reproduce the issue @arthurperton?

**Comment by duncanmcclean** [comment]
Figured it out - I have a collection called 'Orders' which has a User field for the customer. Then on the user side I have a Entries field called 'Orders'.

I think what must be happening is an infinite loop. The user is stored on the order so we know who the customer is and the orders are stored on the user so we know which orders they have (useful for looking in the CP, getting their orders in the frontend etc).

I've made a repository which should help you to reproduce: https://github.com/duncanmcclean/cms-4123 (login as statamic@test.com with `password`)

**Comment by OleksiiBrylin** [comment]
I have the same issue for Statamic v3.3.11.

**Comment by marcorieser** [comment]
Same issue here with v.3.3.11

**Comment by arthurperton** [comment]
I think this may have been solved by #6163 as wel. If so, it should be fixed in 3.3.15 and up. Can you confirm this?

**Comment by duncanmcclean** [comment]
> I think this may have been solved by #6163 as wel. If so, it should be fixed in 3.3.15 and up. Can you confirm this?

Looks to be fixed to me - thanks for following up. I'll close this issue now.
