### ISSUE TITLE
Nav blueprint: 'Save' might be better wording than 'Submit'?

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#4136]
## Bug Description

In the 'New Nav Item' stack dialog the button is called 'Submit'. I am not a native english speaker. But as for german I run into problems with translations. We use 'Submit' i.e. for a password reset. Which statamic also has a few of such meaningful use cases with `__('Submit')`.

But for this stack button the same translation is not 100% coherent. 'Save' would be the better option. 

I didn't open a PR because I am not sure how you feel about this in english? The code is in `resources/js/components/structures` on line 53 if you feel good about this change.

## Extra Detail

<img width="1050" alt="Bildschirmfoto 2021-08-18 um 08 49 15" src="https://user-images.githubusercontent.com/8265902/129853043-d93cab8b-5f71-40f3-9748-5d8bd2677ca4.png">

## Environment

Statamic 3.2.0-beta.1 Solo
Laravel 8.55.0
PHP 7.4.22
No addons installed

- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment]
It actually only saves when you submit the stack and then press `Save changes` so I think `Submit` does make more sense!

**Comment by jasonvarga** [comment]
Yeah, that's the reasoning why it says submit and not save. ☝️
