### ISSUE TITLE
Renaming an asset from the asset fields results in saving entry error

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#4138]
## Bug Description
Rename an asset from an asset field (in an entry). It works. Asset get's renamed. Reference get's updated. However, when you try to save you get an error. When you refresh all is good.

## How to Reproduce
Add a blueprint for a collection with an asset field.
Have an entry with a selected asset saved an opened.
Rename the asset from the asset field.
Save the entry

## Extra Detail
<img width="1637" alt="Screenshot 2021-08-18 at 11 40 33" src="https://user-images.githubusercontent.com/69107412/129876314-3bada8cc-bfed-4a2f-aea6-036451efae6c.png">

## Environment
Statamic 3.2.0-beta.1 Pro
Laravel 8.55.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
A bit complicated with how it's all wired together using actions. 🤔 
I wonder if we can get around this by just preventing renaming from publish forms.

**Comment by robdekort** [comment]
That's very fair. I'd go for that!

**Comment by jasonvarga** [comment]
Also, this same behavior happens on 3.1.

**Comment by robdekort** [comment]
(Don't tell: I never renamed an asset before 3.2 🙈)

**Comment by jasonvarga** [comment]
I know you were just being thorough in your testing. Thank you!

**Comment by j3ll3yfi5h** [comment]
My client found it as well😔

https://user-images.githubusercontent.com/6337411/144813255-ce62400a-41d9-4702-8f77-4c73a7707d27.mov

**Comment by robdekort** [comment]
Not an issue anymore. Got fixed somewhere along the way.
