### ISSUE TITLE
3.2 Nav blueprints: wrong explainer text?

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#4140]
## Bug Description
The Link to Entry stack explains if you leave the title black, it'll fall back to the URL. But it seems to use the `title` as a fallback. Which I think makes most sense anyway. Maybe a tpyo in the explainer string?

## How to Reproduce
Open the link to entry stack
Admire the explainer

## Extra Detail
<img width="396" alt="Screenshot 2021-08-18 at 14 00 22" src="https://user-images.githubusercontent.com/69107412/129894515-e1981a7c-3b24-417c-b3d0-ab8745ba26a0.png">

## Environment
Statamic 3.2.0-beta.1 Pro
Laravel 8.55.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment]
Good catch.

For regular nav items, a missing title will fall back to the URL.
For entry nav items, it'll fall back to the entry's title.

We'll see what we can do about that text. 👍

**Comment by jasonvarga** [comment]
Actually that's a lie. Looks like the fallback behavior doesn't happen anywhere, and after thinking about it some more, we're happy that it doesn't. So we're gonna just remove the instructions.

**Comment by robdekort** [comment]
Perfect. Easy to fix stuff is the best. Next!
