### ISSUE TITLE
.php_cs.dist and .styleci.yml mismatch

### ISSUE THREAD

**Issue by michaelr0** [statamic/cms#4154]
It seems like .php_cs.dist and .styleci.yml don't match, as I would have expected that https://github.com/statamic/cms/pull/4144 would not have needed manual adjustments to the tests to pass Style CI.

**Comment by jasonvarga** [comment]
Are you talking about how phpcs moves the anonymous classes braces to the same line and styleci moves them back? Yeah it's pretty annoying and not much we can do about it right now. It's already been reported at https://github.com/matt-allan/laravel-code-style/issues/47

I just avoid committing those lines whenever I'm in one of those test classes.

**Comment by michaelr0** [comment]
Fair enough, thanks.

**Comment by edalzell** [comment]
also note that that .php_cs.dist is the legacy file name, newer versions of php cs fixer have a different file name

**Comment by jasonvarga** [comment]
Where'd you see that?

**Comment by edalzell** [comment]
When I upgraded it locally, but also: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/doc/config.rst
