### ISSUE TITLE
Assets don't use the encoded url in control panel

### ISSUE THREAD

**Issue by DoubleJ-G** [statamic/cms#4155]
## Bug Description

If you upload an asset with a special character in the file name such as `+` the control panel will not display or link to the asset correctly. This only effects the control panel, the asset is available using the url encoded file name.

## How to Reproduce

Upload/copy a file to assets with a special character 

## Extra Detail

Example: `File+Name.jpg` will be encoded and accessible at `/assets/File%2BName.jpg` but the control panel will try and fetch the unencoded resource path `/assets/File+Name.jpg` which 404s and won't preview. This also effects the "Open in new window" button. 

## Environment

Statamic 3.1.34 Pro
Laravel 8.55.0
PHP 7.3.27

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by sjclark** [comment]
Related to https://github.com/statamic/cms/issues/3398 ?
Seems like their might need to be some more testing around asset names?

**Comment by arthurperton** [comment]
Hi @DoubleJ-G, thanks for the report! I am getting different behavior than you are describing. I tried the following with an image named `File+Name.jpg`:

1. Upload the file in the Asset Browser -> The asset is renamed to `File-Name.jpg` and it opens fine in the Asset Editor and via the 'Open in a new window' button.
2. Place the file using the filesystem in the `public/assets` folder and reload the Asset Browser -> The asset is still called `File+Name.jpg` and it opens fine in the Asset Editor and via the 'Open in a new window' button.
3. I also used the Asset Editor to rename an image without special characters to `File+Name.jpg` -> The asset is called `File+Name.jpg` and it opens fine in the Asset Editor and via the 'Open in a new window' button.
4. For good measure I uploaded a file in the Asset Browser named `File%2BName.jpg`-> The asset is renamed to `File+Name.jpg` and it opens fine in the Asset Editor and via the 'Open in a new window' button.

I see that the renaming is not totally consistent, but that is a different issue. I _can_ open all the files in the Control Panel. What should I do differently to make the issue happen?

Tested in Chrome and Safari
Statamic 3.1.34 Pro
Laravel 8.51.0
PHP 7.4.22

**Comment by j3ll3yfi5h** [comment]
Slugifying would help...
https://github.com/statamic/ideas/issues/385

**Comment by j3ll3yfi5h** [comment]
Still an issue...

**Comment by j3ll3yfi5h** [comment]
Still a thing.
