### ISSUE TITLE
Super Users causing havoc in existing Laravel apps

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#4159]
## Bug Description

We've added Statamic onto a chunky Laravel app we're building. All of our developers share a single user account. This account is a super user.

The issue we have is: whenever a user is a super user in Statamic, it means they have permission to **everything** in the rest of the Laravel app. We don't want our developers to have access to everything, especially not in our production environment. 

Ideally, when a user is a super user, they have full permission over everything in the CP but they wouldn't have any Laravel permissions unless otherwise given. (we use Spatie's Laravel Permissions package elsewhere if it matters)

I've tracked down the 'over-riding' to [this line](https://github.com/statamic/cms/blob/87237100aa05916d4f288ca27066e537ea80b21e/src/Providers/AuthServiceProvider.php#L77) in Statamic's `AuthServiceProvider`. Unfortunately, because of where it's loaded there's no way to check if a permission is a Statamic one or not (because the Statamic ones aren't loaded at that point).

## How to Reproduce

1. Create a super user
2. Add a little route in your app for testing...

```php
Route::get('/non-statamic', function () {
    dd([
        'is super user' => auth()->user()->super,
        'can access laravel permission (should be false)' => auth()->user()->can('everywhere and nowhere'),
        'can access some statamic permission' => auth()->user()->can('configure collections'),
    ]);
});
```

3. Login as the super user and go to that route you created. You should see the laravel permission and the statamic one are `true` (the laravel permission doesn't even exist so it should always be `false`)

## Environment

Statamic 3.1.32 Pro
Laravel 8.42.1
PHP 8.0.7
No addons installed

**Comment by jasonvarga** [comment]
I guess having multiple users is not an option?

**Comment by duncanmcclean** [comment]
Multiple users wouldn't really make a difference - they'd still be super users.

**Comment by jasonvarga** [comment]
Then don't make them super users

**Comment by duncanmcclean** [comment]
> Then don't make them super users

Yeah, we thought about that and it's probably what we'll end up doing.

Still doesn't feel great to me though that it bypasses all permissions for super users, regardless of whether they were registered by Statamic in the first place. I'd have thought it would make sense to scope the permissions to just those from Statamic.

**Comment by jasonvarga** [comment]
A super user gets access to everything.

If you want to split the authorization logic between Statamic and the rest of your project, you can use two different auth guards.

https://statamic.dev/knowledge-base/using-an-independent-authentication-guard

You can have one Statamic super user login to get into the CP, then you have regular Laravel DB users to do the rest of the Laravel user things.
