### ISSUE TITLE
Link from CP Updates section to "Statamic 3.2 Launch Announcement blog post" 404s

### ISSUE THREAD

**Issue by bruceontheloose** [statamic/cms#4168]
## Bug Description
In the control panel's screen to update Statamic, the link to the "Statamic 3.2 Launch Announcement blog post" 404s because it points to `https://statamic.com/statamic-3.2` instead of `https://statamic.com/blog/statamic-3.2`.

## How to Reproduce
1. Go to __Tools__ > __Updates__ in the CP.
2. On the Updates screen, choose __Statamic__.
3. Click/tap the "Statamic 3.2 Launch Announcement blog post" link in the opening paragraph.

## Extra Detail

Here's the part in question:

![image](https://user-images.githubusercontent.com/1419972/130658580-baabc120-1310-49d8-9ef7-a1a88b11ff41.png)

## Environment

**Statamic version:** 3.1.35

**PHP version:** 7.4.2

**Install method (choose one):**
- Starter kit (don't recall which one, but I imagine it doesn't matter for this issue).

**Comment by jasonvarga** [comment]
Thanks, it should be fixed now. If not, clear your cache.

**Comment by bruceontheloose** [comment]
Thanks, Jason. It's working now.
