### ISSUE TITLE
3.2: Saving navigation does not work

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#4174]
## Bug Description
I tried to upgrade a 3.1.34 to 3.2 and as a result editing the navigation in CP does not work. I may have missed something in the upgrade guide, but when opening navigation all the titles (on entries) are gone. When I try to change something and press Save it returns a 404 in console. Also the upgrade did not go smooth. Trying to upgrade in CP resulted in an error, and I then tried upgrading in CLI and this also returned an error. See screenshots. Not sure if it's relevant though.

## How to Reproduce
Go to Navigation in CP. Change something and press Save.

## Extra Detail
![Screenshot 2021-08-24 at 22 52 29](https://user-images.githubusercontent.com/1135679/130690051-fe4bcc85-f082-4589-a74b-32d4f9c33c72.png)
![Screenshot 2021-08-24 at 23 00 55](https://user-images.githubusercontent.com/1135679/130690071-d6e1df30-d6c4-4b03-b4ad-450ca7a9af66.png)
![Screenshot 2021-08-24 at 23 07 03](https://user-images.githubusercontent.com/1135679/130690088-72f7beb3-ce8c-4476-96d7-8868fdc77999.png)
![Screenshot 2021-08-24 at 23 08 18](https://user-images.githubusercontent.com/1135679/130690166-097c380b-a93c-43f9-a93f-edfc5d060190.png)

## Environment
Statamic 3.2.0 Pro
Laravel 8.54.0
PHP 7.4.20
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic` (when starting this site. If I remember correctly I started with 3.1.34)

**Comment by espenlg** [comment]
Deleting the vendor folder and doing `composer install` solved the problem. I would still argue there is an issue with upgrading from 3.1.34 to 3.2.

**Comment by jackmcdade** [comment]
Github has been glitching on and off all day – I've had a few hiccups myself kinda like this that went away by just waiting a few minutes and trying again. I don't think you did anything wrong nor do I think there's anything we can do at this point! Glad you got it sorted though!
