### ISSUE TITLE
Assets: Stuck on page 2 when opening Assets folders with one page of files

### ISSUE THREAD

**Issue by fishpatrol** [statamic/cms#4189]
This happens when I open an Assets folder with more than one page of files and go to, for example, the second page of files. If I then click on another Assets folder, it continues to show me the second page of files. If there isn't a second page of assets to list, the list is empty. If there are subfolders within that folder, the subfolders are still shown. But the contents of the folder you're in aren't paginated, and the URL doesn't show that you're on the 2nd+ page of the folder. So it looks like you're in an empty folder

The only way I've found to get back to the first page is to find an Asset folder that has more than one page of assets. On that page it shows that I'm on page 2 of the folder. If I go to the first page of that folder and then open a different folder, then I can see the 1st-page files in the folder. Also if I click Assets in the sidebar, folders then show the 1st-page files. Opening any folder should show you the first page of files in that folder.

This is in Statamic 3.1.32

**Comment by edalzell** [comment]
Same issue, different result.

If I'm on page 2 of an asset listing, and I click on another folder that also has more than one page, I'm taken to the 2nd page, instead of the first.

Guessing the (`currentPage`) is in the VueX store or something?

**Comment by jasonvarga** [comment]
This looks resolved/irrelevant now.
