### ISSUE TITLE
GraphQL:  Multiple replicators with the same handle leads to error on querying their containing data

### ISSUE THREAD

**Issue by Kylewalow** [statamic/cms#4205]
## Bug Description
I have several blueprints for several collection items. Each of these blueprints contains in the main tab a replicator fieldtype with the handle "hero".
Multiple blueprint are defined like this:
![image](https://user-images.githubusercontent.com/48148789/131681870-4b3b5cdd-4dbd-488b-aa85-3566874bb159.png)

The replicators sets links to my hero filedsets:
![image](https://user-images.githubusercontent.com/48148789/131681995-c9292917-78cb-4fe8-a725-b3fa524ac657.png)

For each collection are pages with data defined.

**The error appears on querying the data of any replicator which has no unique handle even if they are defined in their own blueprint.**
In my case all the replicators have the handle "hero"

## How to Reproduce

1. Create 2 collections
2. Edit the blueprint of both collections and add a replicator in the main tab with the handle "hero"
3. Link a prepared fieldset or create new fields as "set" in the replicator (the sets handle doesn't matter in this case)
4. Create for each collection and corresponding blueprint a site and fill some data e.g. Title etc.
5. Go to statamic Tools GraphQl and open explorer
6. Try to query the data defined in the hero

## Extra Detail

With the following query i tried to get the data:
``` 
  query getPageByUri($uri: String) {
    entry(uri: "/", collection: "pages") {
      ... on Entry_Pages_Home {
        id
      }
    }
  }
```

- Collection: "pages" and blueprint: "home"
- The replicator "hero"
-> The replicator in the explorer has a child element "Set_Hero_SmallHero". This is wrong.
I have blueprints with the "SmallHero" defined as "set" in the replicator but its not the "home" blueprint. The "home" blueprint should display a "Set_Hero_HomeHero"
Moreover the child "Set_Hero_SmallHero" is not clickable but generates the `... on Set_Hero_SmallHero` in the query ass it can be seen on the picture.
To run this query leads in the "not found" error which is actually right due to there is not "smallHero" in this blueprint.

![image](https://user-images.githubusercontent.com/48148789/131678729-d3d390e3-c377-4e64-97c7-272b1eca7eb2.png)

If i give each replicator in each blueprint a unique name it works as expected. It seems to be a Problem with that unique name but this workaround would be lavishly to define dynamic queries later on in the project.

Here the result with a unique name as handle for the replicator in the "home" blueprint: 
![image](https://user-images.githubusercontent.com/48148789/131681443-be9f2429-a010-47b5-aa80-1e3163b732f3.png)

## Environment

Statamic 3.1.32.1 Pro
Laravel 8.55.0
PHP 8.0.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Are you able to make a sample repo with this setup?

**Comment by Kylewalow** [comment]
Here we go:
https://github.com/Kylewalow/statamic-graphql-error

**Comment by Kylewalow** [comment]
https://github.com/Kylewalow/statamic-graphql-error

**Comment by jasonvarga** [comment]
Thanks!

I see the issue now. I'm not sure we can do a whole lot about it at this point. I suggest you just make the field in your home blueprint different, like `home_hero`.

They are technically completely different fields, even though you've named them the same.

It's like if you had a field named `stuff`, and in one blueprint you defined it as a text field and in another you defined it as an array. It would be confusing to have different types of data returned to you using the same name.

GraphQL generates all the types with names based on the fields. Like, `Set_{fieldname}`.
We could technically make it work if we forced you to put the blueprint name in each type but it would be really horribly ugly, extra confusing, and unnecessary for the majority of users.

**Comment by Kylewalow** [comment]
Ok i got the point.

Thank you for your fast help and hope you have a nice day
