### ISSUE TITLE
Spaces aren’t converted to dashes when manually updating a slug

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#4209]
## Bug Description

When you create a new entry the slug is automatically generated from the title, converting capitals to lowercase, replacing spaces with dashes etc. When you manually update a slug and hit save Statamic will convert any capitals to lowercase for you, but it doesn’t replace spaces with dashes, instead it throws a validation error.

Maybe this is intended behaviour, but it seems like an odd inconsistency to me. Why automatically make some alterations to the input but not all?

Most of the time when I’m updating a slug it’s because the title has changed and I want them to be in sync. It'd be really quick and easy if I could just copy the title to the slug field, hit save, and have Statamic format it correctly for me, just like it does when creating a new entry, but at the moment you have to manually replace the spaces first.

## How to Reproduce

1. Go to an entry
2. Modify the slug, adding spaces and capitals
3. Hit save, validation will fail
4. Replace the spaces but leave the capitals
5. Hit save, it works
6. Reload the page
7. The capitals have been converted to lowercase

## Environment

Statamic 3.2.1 Pro
Laravel 8.56.0
PHP 7.4.21

**Comment by jasonvarga** [comment]
The capitals being allowed is a surprise to me. If anything I'd say it should validate for that too, rather than change it without you realizing.

The initial state is synced from the title field because the slug starts empty.

I'm sure I've seen someone request a feature where the slug could be updated from the title field with a click. I can't find an issue though, maybe it was just in Discord.

**Comment by jacksleight** [comment]
> The capitals being allowed is a surprise to me. If anything I'd say it should validate for that too, rather than change it without you realizing.

Yeah, I think it would make sense for it to be consistent, whichever way round that is.

> I'm sure I've seen someone request a feature where the slug could be updated from the title field with a click. I can't find an issue though, maybe it was just in Discord.

Something like that would be really useful. Particularly during development titles can change a lot, so making it as easy as possible to update them would be handy. Now that I think about it perhaps a bulk slug updater would be a good candidate for an addon.
