### ISSUE TITLE
Margins and padding in CP

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#4211]
Spotted this today, could do with a little bit of margin bottom.
![](https://cdn.discordapp.com/attachments/491735338377805835/882918082337706055/Screenshot_2021-09-02_at_09.41.17.png)

Text and textarea padding doesn't match, intentional?
![](https://cdn.discordapp.com/attachments/491735338377805835/882918243738714132/Screenshot_2021-09-02_at_10.17.08.png)

**Comment by jackmcdade** [comment]
Thanks!
