### ISSUE TITLE
CP 404 page used if URL contains `cp`

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#4213]
## Bug Description

Really minor thing I just found - if you go to `/cpsomething`, it will show Statamic's CP 404 page, rather than the custom 404 page used for sites.

I know obviously it's correct to show the 404 one if you were to do `/cp/something` but seems like a glitch that it does it for `/cpsomething`.

## How to Reproduce

1. Go to `/cpsomething` (`something` can be whatever)
2. See it 404s 

## Extra Detail

![image](https://user-images.githubusercontent.com/19637309/131882819-2c2ff87a-987a-4f65-8fa2-fd52224765ce.png)

Example 1: https://duncanmcclean.com/cpaaa
Example 2: https://duncanmcclean.com/caaa

## Environment

**Statamic version:** 3.2.0

**PHP version:** 7.4.22

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- **Existing Laravel app**
- Other (please explain this magic!)

**Comment by mynetx** [comment]
Seems to be related to this method:
https://github.com/statamic/cms/blob/7911d611c737c4d2c3edc8bc9e03c4ab153d1a4d/src/Statamic.php#L147-L154

```
    public static function isCpRoute()
    {
        if (! config('statamic.cp.enabled')) {
            return false;
        }


        return starts_with(request()->path(), config('statamic.cp.route'));
    }
```

And the default for this route is just `cp`, without any trailing slash.

So – provided there are no other side effects, maybe this’d be fixed with an amendment like this one:

```
        return starts_with(
            request()->path(),
            str_finish(config('statamic.cp.route'), '/')
        );
```

**Comment by duncanmcclean** [comment]
@mynetx That does the job for me!
