### ISSUE TITLE
validate file-size on asset fields doesn't work

### ISSUE THREAD

**Issue by schmidex** [statamic/cms#4217]
## Bug Description
I'm trying to set a file size limit on an asset-field in my form.
Laravel documentation says I have to use `max:` . But adding this to the field in my forms blueprint doesn't work.  It checks for the maximum number of files and is not checking each file for size.
Looking into the code there doesn't seem to be a AssetRule for checking filesize. So is this (relatively common) validation really not possible at the moment?

**Statamic version:** 3.2.2

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Nice find. Looks like it's not possible at the moment. But it should be added in #4116.

**Comment by el-schneider** [comment]
This unfortunately also doesn't work with asset fields in the cp and #4116 did not fix it
