### ISSUE TITLE
Using Content API endpoint with spaces

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#4219]
## Bug Description
I was not sure whether to file this as a bug report or "Support Questions & Other", but it kind of _feels_ like a bug that could be fixed. I could be wrong though, feel free to move if possible...

For a recent project, I'm heavily relying on Taxonomies and the Content API. The client just started inserting content and of course created tags with spaces, so something like "Word 1", or "My wonderful tag". While this is possible in the title field, retrieving entries throws an error 500. This is the route I'm using to get entries with a specific tag:

```
$response = $this->connect("/taxonomies/tags/terms/{$tag}/entries?limit={$limit}");
```

Everything works as expected when using tags without spaces, but for obvious reasons it fails when there is a space. I tried it with the slug, ie. `word-1` and also replaced the space with `%20`. Everything fails.

I filed it as a bug because it is possible to use spaces in tags via the title field so there should be some sort of logic behind the scenes to deal with that.

## How to Reproduce
Use the API endpoint above with a space in the url.

## Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.10
jacksleight/bard-paragraph-style 1.0.0
jonassiewertsen/statamic-livewire 2.7.0
octoper/statamic-blade-components 1.0.1
optimoapps/statamic-bard-text-align 1.0.2

**Install method:**
- Existing Laravel app

**Comment by jasonvarga** [comment]
The slug should be used in URLs. So, `word-1` like you've mentioned.

When you say that "fails", can you elaborate?

**Comment by MrMooky** [comment]
Yeah sorry, I should have shown the error message. The log says this:

```
local.ERROR: Call to a member function in() on null {"exception":"[object] (Error(code: 0): Call to a member function in() on null at /.../vendor/statamic/cms/src/Providers/RouteServiceProvider.php:88)
```

And the debug shows this:

<img width="333" alt="Screenshot 2021-09-04 at 07 22 46" src="https://user-images.githubusercontent.com/3603346/132083600-805b1079-f14f-49eb-9f8b-ed80f18a958e.png">

But I think this might be on my end. I'm not giving the slug to the url, but the tag title, which is "Word 1" and not "word-1". The same (tag as title and not as slug) works fine when I get entries from a collection directly in my Antlers template. But the Content API is not changing the title into the slug automatically, whereas the Antlers condition does. At least so it seems. Again, I'm not sure if this is a bug, or me just doing it wrong.
