### ISSUE TITLE
Structure fieldtype augmentation broken

### ISSUE THREAD

**Issue by goldnead** [statamic/cms#4221]
## Bug Description

(Might be related: https://github.com/statamic/cms/issues/3875)
When using the structure fieldtype I only get it to work properly without augmentation like so:

```
{{ nav handle="{structure_field | raw}" }}
    <li><a href="{{ url }}">{{ title }}</a></li>
{{ /nav }}
```

This also only works when limiting the selected structures to one.
The intended behaviour as described in the [docs](https://statamic.dev/fieldtypes/structures) should be:

```
{{ structure_field }}
    <li><a href="{{ url }}">{{ title }}</a></li>
{{ /structure_field }}
```

But using it like in the example outputs nothing.

## How to Reproduce
1. Create new statamic site
2. Add structure-fieldtype to page blueprint
3. In the Page, select a structure
4. Try template from the docs to iterate through selected structures
5. Voilá

## Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.8

**Comment by jackmcdade** [comment]
Fixed in a950ef47d28a7a23986ac2734728d1241601851f.
