### ISSUE TITLE
SVG uploaded to Asset fieldtype breaks that field's frontend 

### ISSUE THREAD

**Issue by artemverbo** [statamic/cms#4233]
## Bug Description
When uploading SVG to an Asset field, nothing is displayed in the CMS field view with no ability to delete/replace the image. 
## How to Reproduce
Create an Asset field and upload SVG file there (s3-based container).

## Extra Detail
The frontend fails here when checking for includes('::') and asset.url is `null` (not sure if that's my s3-based asset container setup, but other images formats work ok).

**fieldtypes/assets/Asset.js**
```
 canShowSvg() {
      return this.asset.extension === 'svg' && ! this.asset.url.includes('::');
  },

```

![Markup 2021-09-08 at 10 13 13](https://user-images.githubusercontent.com/1530975/132417387-5b6a6031-e200-4221-99cf-16120e61b990.png)

## Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 7.4.22

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by valschr** [comment]
We are also experiencing this issue for quite a while now. Is there a fix in sight? 

thanks!

**Comment by duncanmcclean** [comment]
> We are also experiencing this issue for quite a while now. Is there a fix in sight?
> 
> thanks!

Did you add the `AWS_URL` to your `.env` file? It's the workaround (or even the fix) for this issue.

**Comment by valschr** [comment]
Thank you, this did the trick!

**Comment by arthurperton** [comment]
Setting the `AWS_URL` definitely fixes this. Nice find!

I'm going to open a PR just to make sure the Assets field doesn't fail when the URL is missing. And maybe show a more useful error message in a toast.
