### ISSUE TITLE
Set inside bard, inside fieldset?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#4237]
I've got a Bard inside a common fieldset. I can add it to a blueprint and click on it (within the blueprint) and it works. But if I edit the bard - add a set to it and go back to the blueprint I can't click on the fieldtype.

Checking `laravel.log` I see this message (edited):
```
local.ERROR: Undefined array key "field" {"userId":"7271a04e-c484-47f5-ac94-599bd2913731","exception":"[object] (ErrorException(code: 0): Undefined array key \"field\" at /Users/stephenmeehan/Repositories/statamic-bones/vendor/statamic/cms/src/Fields/FieldTransformer.php:61)
[stacktrace]
#0 /Users/stephenmeehan/Repositories/statamic-bones/vendor/statamic/cms/src/Fields/FieldTransformer.php(61): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/Users/stephenm...', 61)
```

It happens when adding a set to the bard. Link Existing and Create Field options trigger the same problem

## How to Reproduce
Short screencast shows steps to recreate.
https://youtu.be/wJiqRiWNXPs

## Environment
Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 8.0.10

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Very well demonstrated - thanks for the video.

**Comment by jasonvarga** [comment]
Oops wrong button.

**Comment by jackmcdade** [comment]
> Oops wrong button.

Great bug report! Bye! 🤣
