### ISSUE TITLE
Problem with searching for Taxonomy Terms using PHP

### ISSUE THREAD

**Issue by sunscreem** [statamic/cms#4238]
## Bug Description

Using Statamic's facades in PHPto find taxonomy terms, I can't find a term even if it's in the data set.

## How to Reproduce

In tinker, if I manually display my taxonomy term, you will see it has a data value called `status_code`, in this case `3`.

![image](https://user-images.githubusercontent.com/7523595/132699659-11e98d69-e0bc-4d15-a535-d5e24adabb85.png)

If the try to find that term by looking for `status_code` of `3` it returns an empty collection:

![image](https://user-images.githubusercontent.com/7523595/132700088-eb839bbf-1d5d-4773-baac-3f096e0dc878.png)
## Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 7.4.22
doublethreedigital/duplicator 1.3.4
jonassiewertsen/statamic-external-link 1.4.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
You can't do that unfortunately because `status_code` isn't a property on the [`Term`](https://github.com/statamic/cms/blob/3.2/src/Taxonomies/Term.php) class, instead you can do something like this:

```php
\Statamic\Facades\Term::query()
    ->where('taxonomy_status_codes')
    ->get()
    ->filter(function ($term) {
        return $term->data()->get('status_code') === 3;
    });
```

**Comment by jasonvarga** [comment]
You should totally be able to do what you're doing.

**Comment by sunscreem** [comment]
@duncanmcclean Thanks - I fell back to using collections to find the term.

@jasonvarga do you think this is a bug?

**Comment by jasonvarga** [comment]
It works for me. Can you provide a sample repo where you get this behavior?

**Comment by sunscreem** [comment]
@jasonvarga Now I know it's working for you and is the expected behaviour, I'm 99% sure this will be something silly I'm doing in that case.  I'll dig a bit more and re-open this if I don't get to the bottom of it.
