### ISSUE TITLE
Unsetting an asset in a duplicated grid row unsets both the original and duplicated fields

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#4245]
## Bug Description

If you have a grid field with a child asset field, and you duplicate a row where the asset is set, and then unset the asset field by clicking on the trash can, both the original and duplicated fields are unset.

## How to Reproduce

1. Create a grid field with a child asset field
2. Add a row and set the asset
2. Duplicate the row
3. Unset the asset by clicking on the trash icon
4. Both rows's assets are unset

## Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 7.4.21

**Comment by arthurperton** [comment]
Note for devs:

This issue is caused by shallow cloning, see notes in #4997.

https://github.com/statamic/cms/blob/1e6380a1d1527ec95458141b3c1abd92eba5e142/resources/js/components/fieldtypes/grid/Grid.vue#L176

This should be a deep clone ^^
