### ISSUE TITLE
Dynamic form fields doesn't work in {{ slot }}

### ISSUE THREAD

**Issue by kimoxlund** [statamic/cms#4247]
## Bug Description
I'm trying to create a form component with a slot for either building custom forms or using the dynamic fields loop, but the dynamic fields are not being rendered in the slot. Any idea why that might be? 

## Extra Detail
Overly simplified form component:
```
{{ form:create :in="handle" }}
    {{ slot }}
    <button type="submit">Submit</button>
{{ /form:create }}
```

Main component where fields are not rendered:
```
{{ partial:components/form handle="contact" }}
    {{ fields }}
        {{ field }}
    {{ /fields }}
{{ /partial:components/form }}
```

This works perfectly:
```
{{ partial:components/form handle="contact" }}
    <input type="text" name="first_name" value="{{ old:first_name }}">
    <input type="text" name="last_name" value="{{ old:last_name }}">
{{ /partial:components/form }}
```

## Environment
Statamic 3.0.32 Solo
Laravel 8.17.2
PHP 7.4.12
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
This is because the contents of the slot are evaluated at the parent level.

The result of the slot is passed as a string into the partial.

Where you're using the `{{ fields }}` loop, it's not inside a `{{ form }}` tag yet.
