### ISSUE TITLE
Unpublished entries are not visible on the frontend while logged in

### ISSUE THREAD

**Issue by davidzumini** [statamic/cms#4248]
## Bug Description
Unpublished entries cannot be previewed on the frontend while logged in to the Control Panel. This differs from the behavior of v2 sites in which unpublished pages were visible on the frontend while logged in. I don't know if this was an intentional change or not, but it was a nice feature to have.

## How to Reproduce
- Create a new entry in any collection and set it as unpublished
- Attempt to view the new entry on the site's frontend
- You will get a 404, where the expected behavior is to see the entry's content **assuming you are logged in**, of course

## Extra Detail
I can confirm this works on a v2 site I have running, but does not appear to work on any v3 site I've tried it on. I was logged in as a super user in all cases.

## Environment
Statamic 3.2.4 Pro
Laravel 8.60.0
PHP 8.0.8

**Comment by jasonvarga** [comment]
It was an intentional change. Too many people were confused by the behavior.

You can see the draft entry while using Live Preview, though.
