### ISSUE TITLE
{{ if session:bewertung === 1 }} not working

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#4250]
## Bug Description
Conditions with sessions seems not to work.

## How to Reproduce
```
{{ session:set bewertung="true" }}

{{ session:bewertung }} // output: 1

{{ if session:bewertung === 1 }}
{{ if session:bewertung == 1 }}
{{ if session:bewertung === true }}
{{ if session:bewertung == true }}

```
All conditions have no effect.

The debugbar contains the correct entry in the session tab:
`bewertung true`

## Environment

**Statamic version:** 3.2.4

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Since it's a tag, not a variable, you should do `{{ if {session:bewertung} }}`

**Comment by wm-simon** [comment]
Ah OK, thank you! Worked perfect.
