### ISSUE TITLE
UX: instructions positions (new in 3.2.3)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#4256]
## Bug Description
Ironically, the text located BELOW the "Instructions" (while creating any fieldtype) refers to a text shown UNDER the field's display label, while the new "Instructions Position" allows to choose either "Above" or "Below"...

First, the default Instructions text should be changed and second I think the default behaviour should probably be BELOW though it's ABOVE right now.

In order to improve the UX, could the 2 zones be merged in a single one, with the Instructions being paired with some kind of a switch or radio button to choose either Above or Below?

## Extra Detail

![Capture d’écran 2021-09-13 à 21 31 06](https://user-images.githubusercontent.com/1823359/133145609-a95eb510-50a6-4b32-b92b-258ae06b2d26.png)

**Statamic version:** 3.2.4

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
The position says "relative to the field", not relative to the display text.

It seems accurate to me.

**Comment by ebeauchamps** [comment]
ah...well, OK then.
