### ISSUE TITLE
GraphQL Schema is against the spec

### ISSUE THREAD

**Issue by grischaerbe** [statamic/cms#4260]
## Bug Description
As described here: https://github.com/graphql-editor/graphql-zeus/issues/211 the GraphQL schema rendered by Statamic is against the spec. According to the [official (?) docs](https://graphql.org/learn/schema/#interfaces) an `interface` needs to be implemented by a `type`.
The query `globalSets` returns an interface `GlobalSetInterface` but the interface is not implemented anywhere.

## How to Reproduce
- Fresh Statamic install
- Make it pro
- Activate GQL
- Enable querying globals
- Fetch schema

## Environment

**Statamic version:** 3.2.4

**PHP version:** 8.0

**Comment by jasonvarga** [comment]
There's a `GlobalSet` implementation for each set.

e.g. if you have a `settings.yaml` set, then there's a `GlobalSet_Settings` implementation.

**Comment by jasonvarga** [comment]
Oh, do you not have any globals?

**Comment by grischaerbe** [comment]
Nope, the moment you do a fresh install, there are no globals. Therefore the interface is unimplemented.

**Comment by jasonvarga** [comment]
Okay, that makes sense then.

But where does it say an implementation is required?

**Comment by grischaerbe** [comment]
From my understanding: If the return type of a query is an interface which is not implemented anywhere, it's `__typename` is implicitly `never` and renders the query invalid? I guess the properties of the interface are still queryable…

**Comment by grischaerbe** [comment]
From: https://spec.graphql.org/June2018/#sec-Interfaces

> Result Coercion
> 
> The interface type should have some way of determining which object a given result corresponds to. Once it has done so, the result coercion of the interface is the same as the result coercion of the object.

**Comment by jackmcdade** [comment]
Closing as this is pretty stale. If there's something to be gained functionally (or something that is broken by not implementing this case), we can absolutely revisit. But so far in the last 2 years nothing has popped up that warrants attention here, as far as I can tell. 🤷
