### ISSUE TITLE
500 hundred error occasionally when using glide in php?

### ISSUE THREAD

**Issue by sunscreem** [statamic/cms#4261]
## Bug Description

This is a tricky one to explain so I'll do my best.

I'm needing to pass urls for images into vue.js for a staff directory. I do this by creating a tag. All works fine. Here's the code for getting the staff members profile picture and running it through glide:

```php
private function getProfilePicture($user)
    {


        $image = $user->augmentedValue('profile_picture')->value();

        if ($image) {
            return url(Image::manipulate(Asset::find($image))->width('300')->height('300')->quality('70')->build());
        }

        return '/images/gray.jpg';
    }
```

This all work fine, except every now and again users are getting a 500 and looking at the stack trace its something to do with certificates?

<details>
  <summary>Here's the full trace... it's not small:</summary>

  Aws\S3\Exception\S3Exception Error executing "ListObjects" on "https://ts-assets.ams3.digitaloceanspaces.com/?prefix=lc-int%2F&encoding-type=url"; AWS HTTP error: cURL error 51: Unable to communicate securely with peer: requested domain name does not match the server's certificate. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://ts-assets.ams3.digitaloceanspaces.com/?prefix=lc-int%2F&encoding-type=url 
    vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195 Aws\WrappedHttpHandler::parseError
    vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:97 Aws\WrappedHttpHandler::Aws\{closure}
    vendor/guzzlehttp/promises/src/Promise.php:204 GuzzleHttp\Promise\Promise::callHandler
    vendor/guzzlehttp/promises/src/Promise.php:169 GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}
    vendor/guzzlehttp/promises/src/RejectedPromise.php:42 GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}
    vendor/guzzlehttp/promises/src/TaskQueue.php:48 GuzzleHttp\Promise\TaskQueue::run
    vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:158 GuzzleHttp\Handler\CurlMultiHandler::tick
    vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:183 GuzzleHttp\Handler\CurlMultiHandler::execute
    vendor/guzzlehttp/promises/src/Promise.php:248 GuzzleHttp\Promise\Promise::invokeWaitFn
    vendor/guzzlehttp/promises/src/Promise.php:224 GuzzleHttp\Promise\Promise::waitIfPending
    vendor/guzzlehttp/promises/src/Promise.php:269 GuzzleHttp\Promise\Promise::invokeWaitList
    vendor/guzzlehttp/promises/src/Promise.php:226 GuzzleHttp\Promise\Promise::waitIfPending
    vendor/guzzlehttp/promises/src/Promise.php:269 GuzzleHttp\Promise\Promise::invokeWaitList
    vendor/guzzlehttp/promises/src/Promise.php:226 GuzzleHttp\Promise\Promise::waitIfPending
    vendor/guzzlehttp/promises/src/Promise.php:62 GuzzleHttp\Promise\Promise::wait
    vendor/aws/aws-sdk-php/src/AwsClientTrait.php:58 Aws\AwsClient::execute
    vendor/aws/aws-sdk-php/src/ResultPaginator.php:127 Aws\ResultPaginator::valid
    vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php:292 League\Flysystem\AwsS3v3\AwsS3Adapter::retrievePaginatedListing
    vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php:275 League\Flysystem\AwsS3v3\AwsS3Adapter::listContents
    vendor/league/flysystem/src/Filesystem.php:272 League\Flysystem\Filesystem::listContents
    vendor/statamic/cms/src/Assets/AssetContainerContents.php:27 Statamic\Assets\AssetContainerContents::Statamic\Assets\{closure}
    vendor/laravel/framework/src/Illuminate/Cache/Repository.php:385 Illuminate\Cache\Repository::remember
    vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:418 Illuminate\Cache\CacheManager::__call
    vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261 Illuminate\Support\Facades\Facade::__callStatic
    vendor/statamic/cms/src/Assets/AssetContainerContents.php:30 Statamic\Assets\AssetContainerContents::all
    vendor/statamic/cms/src/Assets/AssetContainerContents.php:40 Statamic\Assets\AssetContainerContents::files
    vendor/statamic/cms/src/Assets/AssetContainerContents.php:54 Statamic\Assets\AssetContainerContents::filteredFilesIn
    vendor/statamic/cms/src/Assets/AssetContainer.php:240 Statamic\Assets\AssetContainer::files
    vendor/statamic/cms/src/Assets/Asset.php:116 Statamic\Assets\Asset::exists
    vendor/statamic/cms/src/Assets/AssetContainer.php:339 Statamic\Assets\AssetContainer::asset
    vendor/statamic/cms/src/Fieldtypes/Assets/Assets.php:148 Statamic\Fieldtypes\Assets\Assets::Statamic\Fieldtypes\Assets\{closure}
    [internal] array_map
    vendor/laravel/framework/src/Illuminate/Collections/Collection.php:640 Illuminate\Support\Collection::map
    vendor/statamic/cms/src/Fieldtypes/Assets/Assets.php:149 Statamic\Fieldtypes\Assets\Assets::getAssetsForAugmentation
    vendor/statamic/cms/src/Fieldtypes/Assets/Assets.php:133 Statamic\Fieldtypes\Assets\Assets::augment
    vendor/statamic/cms/src/Fields/Value.php:47 Statamic\Fields\Value::value
    app/Tags/Staff.php:46 App\Tags\Staff::getProfilePicture
    app/Tags/Staff.php:25 App\Tags\Staff::App\Tags\{closure}
    [internal] array_map
    vendor/laravel/framework/src/Illuminate/Collections/Collection.php:640 Illuminate\Support\Collection::map
    app/Tags/Staff.php:38 App\Tags\Staff::index
    [internal] call_user_func
    vendor/statamic/cms/src/View/Antlers/Engine.php:159 Statamic\View\Antlers\Engine::renderTag
    [internal] call_user_func_array
    vendor/statamic/cms/src/View/Antlers/Parser.php:578 Statamic\View\Antlers\Parser::parseCallbackTags
    vendor/statamic/cms/src/View/Antlers/Parser.php:177 Statamic\View\Antlers\Parser::parse
    vendor/statamic/cms/src/View/Antlers/Parser.php:132 Statamic\View\Antlers\Parser::parseView
    vendor/statamic/cms/src/View/Antlers/Engine.php:95 Statamic\View\Antlers\Engine::get
    vendor/laravel/framework/src/Illuminate/View/View.php:139 Illuminate\View\View::getContents
    vendor/laravel/framework/src/Illuminate/View/View.php:122 Illuminate\View\View::renderContents
    vendor/laravel/framework/src/Illuminate/View/View.php:91 Illuminate\View\View::render
    vendor/statamic/cms/src/View/View.php:89 Statamic\View\View::render
    vendor/statamic/cms/src/Http/Responses/DataResponse.php:155 Statamic\Http\Responses\DataResponse::contents
    vendor/statamic/cms/src/Http/Responses/DataResponse.php:46 Statamic\Http\Responses\DataResponse::toResponse
    vendor/statamic/cms/src/Structures/Page.php:377 Statamic\Structures\Page::toResponse
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:776 Illuminate\Routing\Router::toResponse
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:763 Illuminate\Routing\Router::prepareResponse
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:695 Illuminate\Routing\Router::Illuminate\Routing\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php:34 Statamic\StaticCaching\Middleware\Cache::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/AuthGuard.php:14 Statamic\Http\Middleware\AuthGuard::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/Localize.php:26 Statamic\Http\Middleware\Localize::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/StacheLock.php:29 Statamic\Http\Middleware\StacheLock::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50 Illuminate\Routing\Middleware\SubstituteBindings::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49 Illuminate\View\Middleware\ShareErrorsFromSession::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:121 Illuminate\Session\Middleware\StartSession::handleStatefulRequest
    vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64 Illuminate\Session\Middleware\StartSession::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67 Illuminate\Cookie\Middleware\EncryptCookies::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 Illuminate\Pipeline\Pipeline::then
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:697 Illuminate\Routing\Router::runRouteWithinStack
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:672 Illuminate\Routing\Router::runRoute
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:636 Illuminate\Routing\Router::dispatchToRoute
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:625 Illuminate\Routing\Router::dispatch
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:166 Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/DisableFloc.php:18 Statamic\Http\Middleware\DisableFloc::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php:14 Statamic\Http\Middleware\CheckMultisite::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php:14 Statamic\Http\Middleware\CheckComposerJsonScripts::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php:19 Statamic\Http\Middleware\PoweredByHeader::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php:31 Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php:40 Illuminate\Foundation\Http\Middleware\TrimStrings::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27 Illuminate\Foundation\Http\Middleware\ValidatePostSize::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php:86 Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/fruitcake/laravel-cors/src/HandleCors.php:38 Fruitcake\Cors\HandleCors::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/fideloper/proxy/src/TrustProxies.php:57 Fideloper\Proxy\TrustProxies::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 Illuminate\Pipeline\Pipeline::then
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:141 Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:110 Illuminate\Foundation\Http\Kernel::handle
    public/index.php:52 [main]

Caused by: GuzzleHttp\Exception\RequestException cURL error 51: Unable to communicate securely with peer: requested domain name does not match the server's certificate. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://ts-assets.ams3.digitaloceanspaces.com/?prefix=lc-int%2F&encoding-type=url 
    vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211 GuzzleHttp\Handler\CurlFactory::createRejection
    vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:158 GuzzleHttp\Handler\CurlFactory::finishError
    vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:110 GuzzleHttp\Handler\CurlFactory::finish
    vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:236 GuzzleHttp\Handler\CurlMultiHandler::processMessages
    vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:168 GuzzleHttp\Handler\CurlMultiHandler::tick
    vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:183 GuzzleHttp\Handler\CurlMultiHandler::execute
    vendor/guzzlehttp/promises/src/Promise.php:248 GuzzleHttp\Promise\Promise::invokeWaitFn
    vendor/guzzlehttp/promises/src/Promise.php:224 GuzzleHttp\Promise\Promise::waitIfPending
    vendor/guzzlehttp/promises/src/Promise.php:269 GuzzleHttp\Promise\Promise::invokeWaitList
    vendor/guzzlehttp/promises/src/Promise.php:226 GuzzleHttp\Promise\Promise::waitIfPending
    vendor/guzzlehttp/promises/src/Promise.php:269 GuzzleHttp\Promise\Promise::invokeWaitList
    vendor/guzzlehttp/promises/src/Promise.php:226 GuzzleHttp\Promise\Promise::waitIfPending
    vendor/guzzlehttp/promises/src/Promise.php:62 GuzzleHttp\Promise\Promise::wait
    vendor/aws/aws-sdk-php/src/AwsClientTrait.php:58 Aws\AwsClient::execute
    vendor/aws/aws-sdk-php/src/ResultPaginator.php:127 Aws\ResultPaginator::valid
    vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php:292 League\Flysystem\AwsS3v3\AwsS3Adapter::retrievePaginatedListing
    vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php:275 League\Flysystem\AwsS3v3\AwsS3Adapter::listContents
    vendor/league/flysystem/src/Filesystem.php:272 League\Flysystem\Filesystem::listContents
    vendor/statamic/cms/src/Assets/AssetContainerContents.php:27 Statamic\Assets\AssetContainerContents::Statamic\Assets\{closure}
    vendor/laravel/framework/src/Illuminate/Cache/Repository.php:385 Illuminate\Cache\Repository::remember
    vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:418 Illuminate\Cache\CacheManager::__call
    vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261 Illuminate\Support\Facades\Facade::__callStatic
    vendor/statamic/cms/src/Assets/AssetContainerContents.php:30 Statamic\Assets\AssetContainerContents::all
    vendor/statamic/cms/src/Assets/AssetContainerContents.php:40 Statamic\Assets\AssetContainerContents::files
    vendor/statamic/cms/src/Assets/AssetContainerContents.php:54 Statamic\Assets\AssetContainerContents::filteredFilesIn
    vendor/statamic/cms/src/Assets/AssetContainer.php:240 Statamic\Assets\AssetContainer::files
    vendor/statamic/cms/src/Assets/Asset.php:116 Statamic\Assets\Asset::exists
    vendor/statamic/cms/src/Assets/AssetContainer.php:339 Statamic\Assets\AssetContainer::asset
    vendor/statamic/cms/src/Fieldtypes/Assets/Assets.php:148 Statamic\Fieldtypes\Assets\Assets::Statamic\Fieldtypes\Assets\{closure}
    [internal] array_map
    vendor/laravel/framework/src/Illuminate/Collections/Collection.php:640 Illuminate\Support\Collection::map
    vendor/statamic/cms/src/Fieldtypes/Assets/Assets.php:149 Statamic\Fieldtypes\Assets\Assets::getAssetsForAugmentation
    vendor/statamic/cms/src/Fieldtypes/Assets/Assets.php:133 Statamic\Fieldtypes\Assets\Assets::augment
    vendor/statamic/cms/src/Fields/Value.php:47 Statamic\Fields\Value::value
    app/Tags/Staff.php:46 App\Tags\Staff::getProfilePicture
    app/Tags/Staff.php:25 App\Tags\Staff::App\Tags\{closure}
    [internal] array_map
    vendor/laravel/framework/src/Illuminate/Collections/Collection.php:640 Illuminate\Support\Collection::map
    app/Tags/Staff.php:38 App\Tags\Staff::index
    [internal] call_user_func
    vendor/statamic/cms/src/View/Antlers/Engine.php:159 Statamic\View\Antlers\Engine::renderTag
    [internal] call_user_func_array
    vendor/statamic/cms/src/View/Antlers/Parser.php:578 Statamic\View\Antlers\Parser::parseCallbackTags
    vendor/statamic/cms/src/View/Antlers/Parser.php:177 Statamic\View\Antlers\Parser::parse
    vendor/statamic/cms/src/View/Antlers/Parser.php:132 Statamic\View\Antlers\Parser::parseView
    vendor/statamic/cms/src/View/Antlers/Engine.php:95 Statamic\View\Antlers\Engine::get
    vendor/laravel/framework/src/Illuminate/View/View.php:139 Illuminate\View\View::getContents
    vendor/laravel/framework/src/Illuminate/View/View.php:122 Illuminate\View\View::renderContents
    vendor/laravel/framework/src/Illuminate/View/View.php:91 Illuminate\View\View::render
    vendor/statamic/cms/src/View/View.php:89 Statamic\View\View::render
    vendor/statamic/cms/src/Http/Responses/DataResponse.php:155 Statamic\Http\Responses\DataResponse::contents
    vendor/statamic/cms/src/Http/Responses/DataResponse.php:46 Statamic\Http\Responses\DataResponse::toResponse
    vendor/statamic/cms/src/Structures/Page.php:377 Statamic\Structures\Page::toResponse
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:776 Illuminate\Routing\Router::toResponse
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:763 Illuminate\Routing\Router::prepareResponse
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:695 Illuminate\Routing\Router::Illuminate\Routing\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php:34 Statamic\StaticCaching\Middleware\Cache::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/AuthGuard.php:14 Statamic\Http\Middleware\AuthGuard::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/Localize.php:26 Statamic\Http\Middleware\Localize::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/StacheLock.php:29 Statamic\Http\Middleware\StacheLock::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50 Illuminate\Routing\Middleware\SubstituteBindings::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49 Illuminate\View\Middleware\ShareErrorsFromSession::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:121 Illuminate\Session\Middleware\StartSession::handleStatefulRequest
    vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64 Illuminate\Session\Middleware\StartSession::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67 Illuminate\Cookie\Middleware\EncryptCookies::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 Illuminate\Pipeline\Pipeline::then
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:697 Illuminate\Routing\Router::runRouteWithinStack
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:672 Illuminate\Routing\Router::runRoute
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:636 Illuminate\Routing\Router::dispatchToRoute
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:625 Illuminate\Routing\Router::dispatch
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:166 Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/DisableFloc.php:18 Statamic\Http\Middleware\DisableFloc::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php:14 Statamic\Http\Middleware\CheckMultisite::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php:14 Statamic\Http\Middleware\CheckComposerJsonScripts::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php:19 Statamic\Http\Middleware\PoweredByHeader::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php:31 Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php:40 Illuminate\Foundation\Http\Middleware\TrimStrings::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27 Illuminate\Foundation\Http\Middleware\ValidatePostSize::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php:86 Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/fruitcake/laravel-cors/src/HandleCors.php:38 Fruitcake\Cors\HandleCors::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/fideloper/proxy/src/TrustProxies.php:57 Fideloper\Proxy\TrustProxies::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 Illuminate\Pipeline\Pipeline::then
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:141 Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:110 Illuminate\Foundation\Http\Kernel::handle
    public/index.php:52 [main]

</details>

I found [this issue](https://github.com/statamic/cms/issues/3328) which gives me the hint that maybe my approach is wrong vs this being a bug?

## How to Reproduce

It's really hard to replicate as it's only happening very rarely.

## Environment

```
Statamic 3.2.4 Pro
Laravel 8.58.0
PHP 8.0.10
doublethreedigital/duplicator 1.3.4
jonassiewertsen/statamic-external-link 1.4.1
```

**Comment by jasonvarga** [comment]
Looks like an S3 issue. Reopen if still a problem.
