### ISSUE TITLE
Related items limit exceeded due to GET request query length

### ISSUE THREAD

**Issue by christophrumpel** [statamic/cms#4264]
## Bug Description

When you have a `relationship:fieldtype` there is currently a `limit` of related entries to select due to the fact that a `GET` request is being used to store them.

In our case, the limit was `216`, and it failed with trying to add one more. (see screenshot below)

## How to Reproduce

* Use a `relationship:fieldtype`
* Select around ~217 entries
* Click the `select` button to save
* See the error

## Extra Detail

Given error message:

![CleanShot 2021-09-15 at 10 26 04@2x](https://user-images.githubusercontent.com/1394539/133399284-d0c5813a-c3a2-4c57-b420-3ce4e297981d.png)

Selecting the entries:

![CleanShot 2021-09-15 at 10 35 36@2x](https://user-images.githubusercontent.com/1394539/133399879-8d335c02-3b59-415f-adb7-d6e3e31697cc.png)

The issue is similar to #3293, except that we haven't customized any limit. (from what I see)

## Environment

Statamic 3.2.4 Pro
Laravel 8.60.0
PHP 8.0.8

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
There's no problem that you're wanting to select so many items, but I am curious what the use case is there.

**Comment by christophrumpel** [comment]
I can't tell too much, but it's basically a portal where the client can add items to a city.

**Comment by christophrumpel** [comment]
Hey @jasonvarga, I didn't realize you are working at Statamic.

We are currently using Statamic for a bigger application where we often have to deal with a large number of collections, entities, and `related items/selections` like here in my shown case. We know Statamic is an opinionated backend and that's fine.

We just want to make sure it is the right tool for our use case. If this is something Statamic is not built for, please let us know, because otherwise, we might run into similar issues more often on the way.

**Comment by mynetx** [comment]
One could resort to using POST for storing the selection, or to split the GET request into multiple – but I don’t think that second approach would scale too well, since the more selections, the more requests, the longer the user would have to wait.

**Comment by jasonvarga** [comment]
It was only a GET route because we were using the CRUD methodology. Changing a route to POST isn't the end of the world.
