### ISSUE TITLE
How to order collections by custom taxonomy field=

### ISSUE THREAD

**Issue by DonxDaniyar** [statamic/cms#4268]
## Bug Description
How to order collections by custom taxonomy field in one query with entry query with paginate? Is that possible
## How to Reproduce
Any Entry Query
## Environment

**Statamic version:** 3.1.26 Pro

**PHP version:** 8.0.5

**Install method (choose one):**
- Existing Laravel app

**Comment by jasonvarga** [comment]
This is not a bug report. Feel free to open a discussion instead, or visit discord.
