### ISSUE TITLE
Incorrect displaying of month titles with date format modifier

### ISSUE THREAD

**Issue by dragomano** [statamic/cms#4271]
## Bug Description
Currently, it is impossible to display translated month titles with current date formats (format, format_localized).
`{{ date format="j F Y" }}` => `11 March 2021`
`{{ date format_localized="%d %B %Y" }}` => `11 ���� 2021`

## How to Reproduce
- Enable `ru` locale in sites.php:
`
'sites' => [

        'default' => [
            'name' => config('app.name'),
            'locale' => 'ru',
            'url' => '/',
        ],

    ],
`
- Add the format modifier for date in your template: `{{ date format="j F Y" }}`. As a result, you will see: ``11 March 2021`` (should be `11 марта 2021`)

## Environment
**Statamic version:** 3.2.4
**PHP version:** 7.4.23

**Comment by jasonvarga** [comment]
The `format_localized` modifier should work if you set your site's `locale` properly.

Instead of `ru`, it should be `ru_RU`. Something you have installed.
Run `locale -a | grep ru` to see what Russian locales are on your system.
