### ISSUE TITLE
The lower modifies has no effect on {{ trans:xxx.xxx }}

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#4275]
## Bug Description
My translation file contains this:
`'sell' => 'Sell'`
and when trying `{{ trans:r8property.sell | lower }}` (or `{{ trans:r8property.sell lower="true" }}` for that matter) it has no effect. Same thing with the `lcfirst` modifier.

## Environment
Statamic 3.2.1 Pro
Laravel 8.38.0
PHP 7.4.20
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Since `trans` is a tag, not a variable, you cannot apply modifiers to it.

You can create a simple tag in `app/Tags/TransLower.php` with this:

```php
<?php

namespace App\Tags;

use Statamic\Tags\Trans;

class TransLower extends Trans
{
    public function wildcard($tag)
    {
        return strtolower(parent::wildcard($tag));
    }
}
```

Then use `{{ trans_lower:r8property.sell }}`.
