### ISSUE TITLE
GraphQL multiple taxonomies error

### ISSUE THREAD

**Issue by montapro** [statamic/cms#4277]
## Bug Description
Using multiple taxonomies renames already existing taxonomies. For example: Existing Taxonomy “Term_Jahr_Jahr” will be renamed to “Term_Jahr_Sektor” after creating Taxonomy “Sektor”.

## How to Reproduce
Create multiple (3 or more) taxonomies and use it in fieldsets as taxonomiy_terms and check your graphQL. (screenshots)

## Extra Detail

![Screenshot 2021-09-17 at 12 19 57](https://user-images.githubusercontent.com/3441850/133767559-4cc9277c-b242-47a9-9d23-90f7f62af6cd.png)
![Screenshot 2021-09-17 at 12 20 00](https://user-images.githubusercontent.com/3441850/133767565-d95b48c3-c5b1-46c2-88da-f931208a9f52.png)
![Screenshot 2021-09-17 at 12 20 06](https://user-images.githubusercontent.com/3441850/133767566-c3cad9b1-2947-4ae7-9121-fdf88a7ec73d.png)

## Environment

Statamic 3.2.4 Pro
Laravel 8.58.0
PHP 7.4.23
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by martink635** [comment]
This is a similar issue: https://github.com/statamic/cms/issues/5420
