### ISSUE TITLE
[i18n] Missing string for translation in 3.2.5

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#4280]
## Bug Description
The string "Buy licenses" appears to be missing in the languages files.

## Extra Detail

In Utility/license

![Capture d’écran 2021-09-17 à 22 31 04](https://user-images.githubusercontent.com/1823359/133850002-e810511b-a477-4721-9611-6629aa2002eb.png)

**Statamic version:** 3.2.5 Pro

**PHP version:** 7.4.12

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Whoops, thanks!
