### ISSUE TITLE
Relationship field causes duplicate field error

### ISSUE THREAD

**Issue by aerni** [statamic/cms#4286]
## Bug Description
I've got a subscriber that extends the blueprint of every entry on `Entry\EntryBlueprintFound`.

I'm running into a `
Duplicate field [seo_section_meta_tags] on blueprint [pages].` exception. I can confirm though that this field only exists once.

I tracked the error down to the following field in the extending blueprint. The error disappears when I remove the field:

```php
[
    'handle' => 'seo_canonical_current',
    'field' => [
        'type' => 'entries',
        'display' => 'Canonical URL',
        'instructions' => 'If this is an entry with duplicate content, link to the entry with the original content.',
        'component' => 'relationship',
        'mode' => 'select',
        'max_items' => 1,
        'localizable' => true,
        'listable' => 'hidden',
        'validate' => [
            'required_if:seo_canonical_type,current',
        ],
        'if' => [
            'seo_canonical_type' => 'equals current',
        ],
    ],
],
```

The exception didn't show up in the CP. It only popped up in Ray.

## How to Reproduce
- Extend a blueprint on `Entry\EntryBlueprintFound`
- Add the field above to the extending blueprint
- Visit an entry in the CP

## Extra Detail
Here's the full exception: https://flareapp.io/share/dPb28w4P#F75

## Environment
Statamic 3.2.5 Pro
Laravel 8.61.0
PHP 7.4.20
aerni/advanced-seo dev-main

**Comment by jasonvarga** [comment]
How are you adding the field?

**Comment by aerni** [comment]
I've got the following in an event subsriber. The `OnPageSeoBlueprint` returns a blueprint with the same structure as `$event->blueprint->contents()`.

```php
public function addFieldsToBlueprint(Event $event): void
{
    if (Str::contains(request()->path(), '/blueprints/' . $event->blueprint->handle()) || app()->runningInConsole()) {
        return;
    }

    $contents = array_merge_recursive(
        $event->blueprint->contents(),
        OnPageSeoBlueprint::make()->get()->contents()
    );

    $event->blueprint->setContents($contents);
}
```

**Comment by aerni** [comment]
It's called in a subscriber on `Events\EntryBlueprintFound` and `Events\TermBlueprintFound`.

**Comment by jasonvarga** [comment]
Right but can you confirm `addFieldsToBlueprint` only gets called once for that blueprint? If it happens twice that would mean you've added the field twice, and the error would make sense.

**Comment by aerni** [comment]
Yes, `addFieldsToBlueprint ` is only called once. If I dump the merged blueprint content, there is no duplicate in there as well. And the error only happens when the field above is in the blueprint. If I remove it, the error disappears.

**Comment by duncanmcclean** [comment]
Hmm, I'm unable to reproduce this issue myself, here's the code I'm using:

```php
Event::listen(EntryBlueprintFound::class, function (EntryBlueprintFound $event) {
    if (\Illuminate\Support\Str::contains(request()->path(), '/blueprints/' . $event->blueprint->handle()) || app()->runningInConsole()) {
        return;
    }

    $contents = array_merge_recursive(
        $event->blueprint->contents(),
        [
            'sections' => [
                'sidebar' => [
                    'fields' => [
                        ['handle' => 'foobar', 'field' => ['type' => 'entries']],
                    ],
                ],
            ],
        ],
    );

    $event->blueprint->setContents($contents);
});
```

I've opened a couple different entries and refreshed a few times but I can't see it... is there anything I might be missing?

**Comment by jasonvarga** [comment]
If you could provide a github repo with this reproduced, that'd be really helpful.

**Comment by aerni** [comment]
I also tested without my custom Blueprint wrapper and simply merged the blueprints like this. But the issue persists. Use any other fieldtype and it works.

```php
public function addFieldsToBlueprint(Event $event): void
{
    if (Str::contains(request()->path(), '/blueprints/' . $event->blueprint->handle()) || app()->runningInConsole()) {
        return;
    }

    $contents = array_merge_recursive(
        $event->blueprint->contents(),
        Blueprint::make()->setHandle('seo')->setContents(['sections' => [
            'seo' => [
                'display' => 'SEO',
                'fields' => [
                    [
                        'handle' => 'seo_canonical_current',
                        'field' => [
                            'type' => 'entries',
                            'display' => 'Canonical URL',
                            'instructions' => 'If this is an entry with duplicate content, link to the entry with the original content.',
                            'component' => 'relationship',
                            'mode' => 'select',
                            'max_items' => 1,
                            'localizable' => true,
                            'listable' => 'hidden',
                            'validate' => [
                                'required_if:seo_canonical_type,current',
                            ],
                            'if' => [
                                'seo_canonical_type' => 'equals current',
                            ],
                        ],
                    ],
                 ],
            ],
        ]])->contents()
    );
}
```

**Comment by jasonvarga** [comment]
Instead of re-setting the contents, try using the `$blueprint->ensureFieldInSection()` method.

```php
$blueprint->ensureFieldInSection('seo_canonical_current', [
   'type' => 'entries',
   // etc
], 'SEO');
```

**Comment by aerni** [comment]
This resolves the error. However, I have a bunch of fields I need to set. And I don't see a method in the Blueprint class like `ensureFieldsInSection`. Do you suggest running `ensureFieldInSection` for every single field? Or is there a way I don't see?

**Comment by aerni** [comment]
I went ahead and [created a PR](https://github.com/statamic/cms/pull/4333). This allows adding multiple fields at once.

**Comment by jasonvarga** [comment]
Yeah you could just call it multiple times.
