### ISSUE TITLE
Multisite: when you add a new translation it populates the content from the current entry, not the root entry

### ISSUE THREAD

**Issue by tao** [statamic/cms#4287]
## Bug Description
I'm working with many different languages and adding translations. 

The correct flow for me is:
1. start on the English content, 
2. find the translation and add it, 
3. save translation, 
4. move onto the next one.

When we share content to be translated we send out the English version and everyone sends the translation back with the English version next to it so we can see where the content matches.

Let's say I add a new Chinese translation, then click on a new entry to create... it ends up breaking the flow:

1. Chinese translation is active
2. create new Russian translation
3. ?? (😵 Chinese content)

At this point I don't know what content to paste because the words are Russian and not English like the root entry. So I can't reference and match them. I think by default it should always populate the new entry content from the root site.

I think the same would apply if we have many translators working on the site, I assume they would all be `English <-> X` translators, so creating a new entry after looking at the other translations and seeing `Chinese <-> X` would also be confusing for them.

**Comment by tao** [comment]
The other problem this causes is that the `origin` changes, which will cause problems because I do some custom Laravel sorting and filtering by the origin ID.

```
EN (root)
title: Copyright
id: a5d32520-3c8d-45c1-95a0-c5804a45422b
```

```
Chinese
id: 2a4e56d5-b49e-479f-9772-2220b0552853
origin: a5d32520-3c8d-45c1-95a0-c5804a45422b (references English ID)
```

```
Russian
id: 7fb1cc3a-92d7-424a-ab47-2b3c10d433a5
origin: 2a4e56d5-b49e-479f-9772-2220b0552853 (references Chinese ID - not root ID)
```

**Comment by jasonvarga** [comment]
Totally a valid issue, but technically not a bug because it's working as intended.

**Comment by tao** [comment]
If the localized entries don't have the same origin ID then I don't know how you could loop them them to find translations? A quick example is that we have a dropdown to toggle between languages:

```
Also read this in:
{{ locales }}
  - {{ locale:name }}
{{ /locales }}
```

If they don't have the same origin then you wouldn't be able to show the Russian translation because that origin belongs to Chinese? There is no way to know where the entry belongs if the slug OR origin are not linked to the root?

**Comment by tao** [comment]
After playing with this problem today, I found a simple solution that seems to work for us:

```php
'Statamic\Events\EntrySaving' => [
    'App\Listeners\TranslateRootEntryOnly',
],
```

```php
namespace App\Listeners;

class TranslateRootEntryOnly
{
    public function handle(EntrySaving $event)
    {
        // Get the root entry
        $root = $event->entry->root();
        
        // Set the origin to the root entry
        $event->entry->origin($root);
    }
}
```

I haven't run into any problems yet. If this works as a valid / long term solution perhaps it would be better to add this to the Localization articles in the Knowledge Base?

**Comment by jasonvarga** [comment]
Interesting solution, nice!

![](https://media.giphy.com/media/d3mlE7uhX8KFgEmY/giphy.gif?cid=ecf05e47n7r51pn93x81ll2f2gb7samfpyyc3xt1mt2gbpth&rid=giphy.gif&ct=g)

**Comment by tao** [comment]
After some more work, I found that taxonomies don't really need this... the translation system works a bit differently and puts them all inside the same file. However, the new English entries we added ended up being their own origin, so we just need a `isRoot()` check in the sample code above. I'll do some more testing and update it soon.

**Comment by webformatik-pyrocms-pro** [comment]
@tao I'm facing the same issue - can you please share your final listener solution?

Perhaps its this one? https://statamic.com/forum/5112-default-origin-for-all-entries-in-a-collection

**Comment by tao** [comment]
@mmodler I updated the previous post so that example is what I use on my website.

```php
<?php

namespace App\Listeners;

use Statamic\Events\EntrySaving;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;

class TranslateRootEntryOnly
{
    /**
     * Handle the event.
     *
     * @param  EntrySaving  $event
     * @return void
     */
    public function handle(EntrySaving $event)
    {
        if (!$event->entry->isRoot()) {
            // Get the root entry
            $root = $event->entry->root();
            // Set the origin to the root entry
            $event->entry->origin($root);
        }
    }
}
```
