### ISSUE TITLE
Make packageName available in AddonServiceProvider

### ISSUE THREAD

**Issue by RafaelKr** [statamic/cms#4288]
> I only use this bug report template, so the code snippets are inlined. This is unfortunately not happening when creating it in statamic/ideas

## Bug Description
I would like to use this in an addon template file:

```blade
<script src="{{ Statamic::vendorAssetUrl($packageName . '/js/script.js') }}"></script>
```

For this I'm required to get the package name in my template.

As a workaround I had to copy this into my ServiceProvider:
https://github.com/statamic/cms/blob/8ad6f269be7b51af12da2f29480fc2890eed7874/src/Providers/AddonServiceProvider.php#L432-L437

So one possibility would be to make this one `protected` instead of `private`, so we can access all `Statamic\Extend\Addon` instance properties inside our addon:
https://github.com/statamic/cms/blob/8ad6f269be7b51af12da2f29480fc2890eed7874/src/Providers/AddonServiceProvider.php#L418-L430

The other possibility is to add a `packageName` method like the one which already exists for `namespace`.

**Comment by duncanmcclean** [comment]
Out of interest, why do you have to get the package name? Don't you just know what it is?

**Comment by RafaelKr** [comment]
I wanted to make my plugin extendable from the users code and pass the packageName to the users class. So he can use the script-tag I showed in my initial post to load some base JavaScript from my plugin and extend that. But I now solved it with another way anyway and don't really need it anymore.

**Comment by duncanmcclean** [comment]
Yeah, I can't think of much use of it - most people know what their package is called. And if someone really needs it, they can use the workaround you suggested in your original post.

I'll close it for now - if anyone has a use case for it in the future, then we can re-open it.
