### ISSUE TITLE
Navigation Blueprint: Toggle value not saved

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#4290]
## Bug Description

There's something wrong when saving a Toggle on a nav blueprint. The value (true/false) does not get saved to YAML unless I engage the toggle, then disengage it.

## How to Reproduce

**The Problem**
1. Add a Toggle to a navigation blueprint.
2. Click a link to bring up the sidebar.
3. Click save
4. Note that the 'false' value DOES NOT get saved to yaml

**Workaround**
1. Add a Toggle to a navigation blueprint.
2. Click a link to bring up the sidebar.
3. Turn on the toggle, then turn it off again.
4. Click save.
5. Note that the 'false' value DOES get saved to yaml

## Extra Detail
![image](https://user-images.githubusercontent.com/20210934/134044614-43bee44d-a1ea-46cc-904a-8e6faec7923d.png)

## Environment

Statamic 3.2.5 Solo
Laravel 8.61.0
PHP 8.0.10
edalzell/blade-directives 3.5

**Comment by jasonvarga** [comment]
If there's no value saved, it's null. Doing `{{ if toggle_field }}` should have the same behavior whether it's null or false.

**Comment by stuartcusackie** [comment]
This logic isn't quite as straightforward as that when using Blade and the Blade directives package. I'll open an issue on there instead.
