### ISSUE TITLE
Multisite: homepage translations append page the `home` slug

### ISSUE THREAD

**Issue by tao** [statamic/cms#4293]
## Bug Description

When you visit the homepage on the default site, the url is `/` and it removes the slug `home`. 

```
filename: en/home.md
---
id: home
blueprint: page
template: home/index
---
```

If you translate the entry to another language: I expected the translated homepage to be `/it` or `/fr` however it appends the slug and the actual url ends up being `/it/home` or `/fr/home`. This took me a while to figure out what was happening when the translated home page was empty.

```
filename: fr/home.md
filename: it/home.md
---
id: home
blueprint: page
template: home/index
---
```

The default behaviour seems strange and not sure if it's intentional or a bug?

If you generated the site with SSG it would also create a strange subfolder layout:

```
├── index.html
├── fr
│   └── home
│       └── index.html
└── it
    └── home
        └── index.html
```

## Environment
Statamic 3.2.4 Pro
Laravel 8.61.0
PHP 8.0.6
statamic/ssg 0.8.0

**Comment by jasonvarga** [comment]
Are your home pages the root in the other site's trees?

**Comment by tao** [comment]
Oh wow, I didn't even know you could toggle to other site trees... I'll need some time to figure this out.

So in the default (English) tree you can see other translations of pages content and publish them, and if you publish a translation they'll show up in the other site tree... then you can make another tree structure 😮

**Comment by jasonvarga** [comment]
Admittedly it's a bit tedious but yes, the trees are separate for each site. Some people like to have different orders for each site.

I had an idea for an option for all additional site trees to just inherit from the first. I could have sworn there was an issue for that, but I can't find it.
