### ISSUE TITLE
Linked field icon SVG has dimension issue

### ISSUE THREAD

**Issue by mynetx** [statamic/cms#4297]
## Bug Description
The link icon for a single linked field has incorrect width/height.

## How to Reproduce
1. Create a fieldset and a field.
2. Create a single field link in a Replicator set.

## Extra Detail
This bug is related to #4285.

![image](https://user-images.githubusercontent.com/6348321/134393676-7b575e26-d6e6-4ccf-ad53-c81aead1c445.png)

## Environment

* Statamic 3.2.6 Pro
* Laravel 8.58.0
* PHP 8.0.9
* withcandour/aardvark-seo 2.0.15

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by mynetx** [comment]
Fixed in ee498c0.

**Comment by jackmcdade** [comment]
👍
