### ISSUE TITLE
Taxonomy Entries Count is wrong on Multisite

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#4320]
## Bug Description

It seems the entries count is wrong when in a multisite context.

## How to Reproduce
In a multisite where a taxonomy term is used in multiple sites, the following will return the wrong, inflated total.
```
{{ taxonomy from="tags" collection="blog" }}
    {{ entries_count }}
{{ /taxonomy }}
```

## Environment

**Statamic version:** 3.2.x

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by stephenmeehanuk** [comment]
I'm seeing an issue with `entries_count` showing `0` when there are translated entries?


```
Statamic 3.2.15 Pro
Laravel 8.56.0
PHP 8.0.8
No addons installed
```
