### ISSUE TITLE
Parent tag is `null`

### ISSUE THREAD

**Issue by stvnthomas** [statamic/cms#4325]
## Bug Description

The parent tag doesn't resolve the parent entry begining with Statamic 3.2.7.

I have a collection of articles mounted to a news page. The parent page title (News) is output with:

```
<h2>
    {{ parent:title }}
</h2>
```

This works fine with Statamic 3.2.6, the `parent` and `mounted` page data keys are set correctly. After updating to 3.2.7+, these keys are `null` making the parent tag resolve the root home page.

## How to Reproduce

Use the parent tag for something, e.g. `{{ parent:title }}`.

## Environment

Statamic 3.2.8 Pro
Laravel 8.61.0
PHP 7.4.2
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
What's the `{{ url }}` if you put it at the same position as `{{ parent:title }}`?

**Comment by stvnthomas** [comment]
It's `/`. Dumping from `{{ parent }}` tag pair shows `mount` and `parent` are null.

![CleanShot 2021-09-27 at 15 09 13@2x](https://user-images.githubusercontent.com/2236267/134992316-6be07e16-f6e2-49f6-b029-88c3e71de960.png)

**Comment by stvnthomas** [comment]
Works when I downgrade to 3.2.6.

![CleanShot 2021-09-27 at 15 12 23@2x](https://user-images.githubusercontent.com/2236267/134992551-9dd20ef7-2ae9-4a8a-a0f8-45ccb0a8a68d.png)

**Comment by jasonvarga** [comment]
Sorry I mean what's `{{ url }}` on 3.2.6

```
<h2>
    {{ url }}
    {{ parent:title }}
</h2>
```

**Comment by stvnthomas** [comment]
Oh, `{{ url }}` outputs `/about/news/explicabo-ducimus-repellendus` on 3.2.6.

**Comment by stvnthomas** [comment]
Sorry if I'm misunderstanding. They're both page entries so both are valid urls containing content. There's a collection of news articles mounted to /about/news. The news articles are auto-generated so no about or news urls/slugs in that collection.

I put together a quick repo demonstrating the issue if it helps: https://github.com/stvnthomas/parent-demo.
