### ISSUE TITLE
Deleting high amount of entries slow

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#4326]
## Bug Description
I have a collection with about 2500 entries. I tried to delete 500 entries, marked them in the cp and and clicked delete.
The process seems to freeze so I watched on the server and saw, that per second there are about 1-3 entries deleted. This took so long. Can you reproduce this or is this just my server? 

Running on Ubuntu 18.04.6 LTS.

## Environment

**Statamic version:** 3.2.8

**PHP version:** 8.0.10

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by wm-simon** [comment]
Btw, during the deleting process the frontend shows errors like this:
`RuntimeException
SplFileInfo::getMTime(): stat failed for /content/collections/collection/file.md`

**Comment by jasonvarga** [comment]
Remember you can also just delete the files.

**Comment by wm-simon** [comment]
I've deleted the files via ftp. The problem is, the client can't ;-)

**Comment by jasonvarga** [comment]
Is deleting 500 entries something that needs to happen regularly?

**Comment by wm-simon** [comment]
These entries are event reservations from guests, which should be deleted from time to time. I can't say right now, how many there will come in future. Because of the GDPR they should be deleted. But about 100-200 will be a minimum, i think. I will test next time, if the deleting process is still so slow with this amount of entries.

**Comment by duncanmcclean** [comment]
Just a thought: instead of your users needing to delete past ones manually, could you have a scheduled command setup that goes through and deletes old entries every day or so?

**Comment by jasonvarga** [comment]
There's actually a lot happening when you delete an entry.

- If you're using multisite, it has to find and delete any localizations first.
- It removes itself from a structure, and saves the tree.
- It deletes the entry file.
- It dispatches an event. Anyone listening for that even does the thing.
- There are 3 things listening for that event in the core. If you have addons there could be more.
  - Search index is updated
  - Static caching is invalidated.
  - Git integration does a commit.

Then it does that 500 times.

Are you using multisite?
Are you using Algolia or another non-local search driver?
Are you using static caching?
Are you using the Git integration?

**Comment by wm-simon** [comment]
A command, that deletes entries older then 30 days, could be work. Perhaps with an cronjob? Or is this possible with statamic?

Deleting an entry seems to be a little more complicated, than I thought. The problem is more, that the site shows the error during the process. In my case, the name from the person is saved to the filename of the entry, like `forename-surname.md` . The error shows the filename with the name from the person, what is really not good. But the error message will not shown anymore, when I set `APP_DEBUG` to `false`, right?

Multisite: false
Search driver: false
static: false
git: false

**Comment by duncanmcclean** [comment]
Yes, you can create a scheduled command. There's documentation around on it in the Laravel Documentation.

**Comment by jackmcdade** [comment]
This issue has gotten stale and we've made many improvements to Statamic in the last 2 years. Feel free to open a new issue or discussion if you have performance issues now. Thanks!
