### ISSUE TITLE
Images not visible in CP collection listing in Safari 15

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#4327]
## Bug Description
In Safari 15 (available for Big Sur) images won't display in collection listings in the CP.

## How to Reproduce
Add a collection with an image and make the image listable. 

## Extra Detail
<img width="1118" alt="Screenshot 2021-09-28 at 10 56 05" src="https://user-images.githubusercontent.com/69107412/135056438-c09af056-6b25-4fc2-9d27-45b6c92c85de.png">

## Environment
Statamic 3.2.8 Pro
Laravel 8.61.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by robdekort** [comment]
It seems to have to do with the anchor wrapping the image that doesn't get any width. 

I'd like to dive in but I don't know how to compile the CP assets, or even where to start Vue wise... Sorry!

**Comment by marcorieser** [comment]
This is very strange. Toggling any css property causes the image to show. 
Safari Version 15.0 (16612.1.29.41.4, 16612) on Bug Sur

![safari-image-listing](https://user-images.githubusercontent.com/2395800/140502157-5cbfee25-c809-4505-94bb-9b04baee0925.gif)

**Comment by robdekort** [comment]
Yeah I think they need a width/height. Just like recent issues with icons in the CP not displaying or being very large.

**Comment by robdekort** [comment]
I'd love to dive in this because I miss lot's of useful information but I honestly don't know how to run/compile the CP :-).

**Comment by marcorieser** [comment]
I tried that for a couple of minutes but nothing helped. The image is always 2x2px initially and on css props toggling Safari detects the correct size.
You can play around with the classes applied by changing the `staticClass` prop in `public/vendor/cp/js/app.js`. To find the right spot you can search for e.g. `asset-thumbnail rounded max-h-full max-w-full rounded`. Not very comfortable but works 😁

**Comment by marcorieser** [comment]
Would be interested in "how to compile core assets" too. I guess it's like cloning the cms repo into `vendor/statamic/cms` and then running `npx mix watch` there.

**Comment by jasonvarga** [comment]
It looks like it's an issue with the lazysizes package.
https://afarkas.github.io/lazysizes/index.html Not a bug necessarily, but maybe our usage is wonky here.

If I change `img data-src` to `src`, and removed the `lazysizes` class, it works fine.

**Comment by marcorieser** [comment]
@jasonvarga by changing `data-src` to `src` and removing the `lazyload` class, it does **not** work. Where is the `lazysizes` class?

**Comment by jasonvarga** [comment]
You have to do it in the component and compile it. You can't just do it in the devtools.

**Comment by marcorieser** [comment]
I changed it in the compiled app.js which should have the same effect like compile, right?

**Comment by robdekort** [comment]
Just a thought. Maybe it can be replaced with native `loading="lazy"`. It's about to get great support.
