### ISSUE TITLE
throw ValidationException::withMessages not working

### ISSUE THREAD

**Issue by crackAT** [statamic/cms#4329]
## Bug Description
tried to use "throw ValidationException::withMessages(["Test"]);" in EntrySaving Event but displayed Error Message is "The given data was invalid" and not my "Test" Error Message. 

## How to Reproduce
throw ValidationExceptin with Messages in Entry Saving Event

## Environment

Statamic 3.2.8 Pro
Laravel 8.62.0
PHP 7.3.29-to-be-removed-in-future-macOS
4rn0/statamic-v3-image-optimizer 1.0.8
aryehraber/statamic-impersonator 2.2.0
aryehraber/statamic-logbook 2.0.2
phpsa/statamic-analytics 1.3.0
statamic/eloquent-driver 0.1.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
That's expected. The general validation message is shown in the toast, then specific field error messages get shown inline with the fields.

**Comment by crackAT** [comment]
Hi, thanks for that, but if i use this in the EntrySaving Event i have to set the field where the error message should appear? How can i do that? 

THanks

**Comment by jasonvarga** [comment]
What's the validation message? What's preventing the entry from being saved?

**Comment by crackAT** [comment]
i'm checking on Entry saving if the slug has changed because our editors are not allowed to change the slug after the entry was published. And if the slug has changed, i would like to throw an error message to the editor. 

Code Example 

```
if($entryModel->slug != $event->entry->slug()){
                throw ValidationException::withMessages(["Changing the URL is not allowed"]);
            }
```

**Comment by jasonvarga** [comment]
Include the slug field in the array and the message will appear by the slug field.

```
throw ValidationException::withMessages(["slug" => "Changing the URL is not allowed"]);
```

**Comment by crackAT** [comment]
Thanks!
