### ISSUE TITLE
Custom modifier - Variable as parameter doesn't work when using shorthand syntax

### ISSUE THREAD

**Issue by sebszocinski** [statamic/cms#4347]
## Bug Description

I created a custom modifier and when I try to pass a variable from my entry's data it doesn't read the variable value. 

If I do a `dd($params);` I get the variable name instead of the value.

Not a huge deal but just weird that it's returning the variable name instead of the value?

## How to Reproduce

```
php please make:modifier percent
```

### Percent.php:
```
public function index($value, $params, $context)
{
    dd($params);
    $percent = (int)array_get($params, 0);
    return ($value - $value * ($percent / 100));
}
```

### some-entry.md:
```
fee: '17000'
percentage_amount: '35'
```
_Note: I have tested both string and integer for percentage_amount_

### Antlers tags and `dd($params);` results:

Tag:
```
{{ fee | percent:percentage_amount }}
```
Result:
```
array:1 [▼
  0 => "percentage_amount"
]
```
Tag (using double antlers!?!?)
```
{{ fee percent="{{percentage_amount}}" }}
```
Result (works):
```
array:1 [▼
  0 => "35"
]
```
Tag (using syntax shared [here](https://github.com/statamic/docs/issues/546#issuecomment-931597489) Works:
```
{{ fee :percent="percentage_amount" }}
```
Result (works):
```
array:1 [▼
  0 => Statamic\Fields\Value {#2902 ▼
    #raw: 35
    #handle: "percentage_amount"
    #fieldtype: Statamic\Fieldtypes\Text {#2904 ▶}
    #augmentable: Statamic\Entries\Entry {#2331 ▶}
    #shallow: false
  }
]
```

## Environment

Statamic 3.2.9 Pro
Laravel 6.20.34
PHP 7.4.23
doublethreedigital/duplicator 2.0.0
statamic/seo-pro 2.3.1

**Comment by jasonvarga** [comment]
Modifiers don't get the values automatically. If you pass a field name, you get exactly what you passed - the string.

You can get the value yourself.

For example, look at the `repeat` modifier.

https://github.com/statamic/cms/blob/e1d2a86344ab92dd8871ad9b37eb2a731c5e3708/src/Modifiers/CoreModifiers.php#L1783-L1786

If the param is not a number, we grab it from the context.
