### ISSUE TITLE
Core Translation not loading

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#4353]
## Bug Description
It seems that the available translations from `vendor/statamic` are not loaded properly at all places.
Maybe I am wrong but wouldn't Statamic have to load the translations from `vendor` if they are present?

## How to Reproduce
I set `'locale' => 'de_CH'` in `config/app.php` and `'sites' => [ 'default' => [ 'name' => config('app.name'), 'locale' => 'de_CH', 'url' => '/', ], ],` in `config/statamic/sites.php`. The control panel is Swiss German but some translations in the frontend and emails remain English.

This happens for example with the errors in the `forgot_password_form`. When I copy the `de_CH.json` and `de_CH folder` from `vendor/statamic/cms/resources/lang` into my `resources/lang` directory it works.

The email which gets sent becomes mostly Swiss German without copying the files mentioned above. But the "Hello!", the reset button text, "Regards" and the " If you're having trouble clicking the "Reset Password" button, copy and paste the URL below into your web browser" remains English.
## Environment
Statamic 3.2.16 Pro
Laravel 8.64.0
PHP 8.0.11
octoper/statamic-html-minify 0.0.5

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
In the reset email, I would expect English because it's probably what's still set as the app's default.
Try changing your app's `locale` in `config/app.php` to `de_CH`.

As for other translations, could you be more specific as to which words or phrases you are seeing in English?

**Comment by marcorieser** [comment]
Thanks for responding. I rechecked that, the locale is set to `de_CH` in  `config/app.php`. 
I don't use translation in my frontend because my page is only Swiss German. Because of that my `resources/lang` directory contains only the default and unmodified Laravel language files:
- `en/auth.php`
- `en/pagination.php`
- `en/passwords.php`
- `en/validation.php`

As far as I can tell, all of the translation in the frontend remain English. All of them should come from Statamic or Laravel itself because I don't overwrite something. In my case this are the validation messages, error messages and success messages connected with the login, reset and forgot password forms. 

For example the reset password email is just partially translated:
https://usehelo.com/shares/mail/285f17d9-284c-4046-9c4e-25bf75d42c31. 
It seems that the parts coming from Statamic are translated but all texts coming from the blade template in Laravel remain English: https://github.com/laravel/framework/blob/568e74170659bc38d0cfcbb1d6006b437d55feb0/src/Illuminate/Notifications/resources/views/email.blade.php

**Comment by jasonvarga** [comment]
It's still the frontend of your site. So no.

**Comment by marcorieser** [comment]
Okey I think now I get it. Every translation I want in my frontend I have to provide in `resources/lang/{locale}`. I did that and it works. But there is one issue left (I think).

As I mentioned above the validation for the [form fields](https://statamic.dev/tags/form-create) don't pick my translation from `resources/lang/de_CH/validation.php` but take the one from `resources/lang/en/validation.php`. I can make it work by deleting the `en` translations and rename my `de_CH` to `en`.
