### ISSUE TITLE
User fieldtype is unusable

### ISSUE THREAD

**Issue by aerni** [statamic/cms#4357]
## Bug Description
I've got a `user` fieldtype on an entry to link the entry to a user. I've got over 6000 users in a database. I'm using the fieldtype in stack selector mode. The stack selector is suuuper slow. It's just a giant list of users with no pagination. And the search doesn't work either. No way I can find the user I'm looking for. 

## How to Reproduce
- Add a user fieldtype to a blueprint
- Have tons of users
- Create an entry and try selecting a user
- Get frustrated because it's slow and search doesn't work

## Environment
Statamic 3.2.10 Pro
Laravel 8.62.0
PHP 7.4.20
aerni/social-links 2.3.0
jonassiewertsen/statamic-livewire 2.7.0
spatie/statamic-responsive-images 2.8.0
visuellverstehen/statamic-classify 2.3.1

**Comment by edalzell** [comment]
How would you want it to work @aerni ?

**Comment by jasonvarga** [comment]
With pagination and search, I imagine.

**Comment by aerni** [comment]
I believe the entries fieldtype does have pagination? I expect it to work the same way. And the search bar is already there. It just breaks with a huge list like that.
