### ISSUE TITLE
Password reset form redirects to home page

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#4370]
## Bug Description
When no `redirect` parameter is set on the `{{ user:reset_password_form }}` tag the user gets redirected to `/` instead of staying at the same route as the form. 
## How to Reproduce
1. Create a fresh Statamic installation
2. Set up routes for `login`, `forgot_password` and `reset_password`
3. Go trough the process of reseting a password
4. Recognise that you end on the home page and not on the page with the reset_password password and the success message
## Extra Detail
Maybe it's easier to just clone a demo (https://github.com/marcorieser/statamic-login).
## Environment
Statamic 3.2.10 Pro
Laravel 8.62.0
PHP 8.0.11
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
I have a feeling this might be the intended bahviour (might be proven wrong). I'd recommend specifying the [`redirect` parameter](https://statamic.dev/tags/user-reset_password_form#parameters).

**Comment by marcorieser** [comment]
Yes for now I redirect to a specific page to say that the password reset worked. 
But then the docs should be changed because the behaviour is not like it's stated there plus the `success` [variable](https://statamic.dev/tags/user-reset_password_form#parameters) should then be present after the redirect. I have not checked if this is the case. But yes it could be okey to implicitly say "If you are redirected, it worked". 
In my opinion the default as stated in the [docs](https://statamic.dev/tags/user-reset_password_form#parameters) would be more logical to me because the other `user:form` tags come back to the same page after submitting.

**Comment by jasonvarga** [comment]
I think the documented behavior "redirect to the same page if `redirect` parameter is not set" is still a good default. If it's not doing that, then I would consider it a bug. 👍
