### ISSUE TITLE
{{ parent }} not working anymore on route

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#4375]
## Bug Description
`{{ parent }}` gives the output from the root, instead of the content from the parent of the route.

## How to Reproduce
That's my collection route:
` route: '{mount}/{year}/{month}/{slug}' `

I'm loading a template with a route in web.php :
` Route::statamic('/{mount}/{year}/{month}/{slug}/request', 'request', ['layout' => 'request', 'protect' => 'password']); `
In this template I show content from the parent. After updating from 3.1 to 3.2 the ` {{ parent }} ` doesn't work anymore.

## Environment

**Statamic version:** 3.2.8

**PHP version:** 8.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Should be fixed in #4345 which will be released today.
