### ISSUE TITLE
Can't delete or edit taxonomy term

### ISSUE THREAD

**Issue by invendi** [statamic/cms#4414]
## Bug Description

I'm unable to delete or edit a certain taxonomy. It was tagged as a bug in the discord, that's why i'm filing this issue.

## How to Reproduce

Not sure, since it only applies to one certain taxonomy. When I delete the taxonomy it's stuck in the Statamic Panel but the YAML file is deleted. When deleting other taxonomies (both in panel and manual YAML), there's no issue.

## Extra Detail
Check out this video: https://streamable.com/jee9ms

## Environment

Statamic 3.2.12 Pro
Laravel 8.34.0
PHP 7.4.23

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment]
Unfortunately we'd need more info on how to recreate this to do anything about it. Please feel free to reopen or open a new issue if you can demonstrate!
