### ISSUE TITLE
Multisite: Full static caching not working on multi domain setup

### ISSUE THREAD

**Issue by andjsch** [statamic/cms#4419]
## Bug Description
The static cache doesn't work properly with full static caching. URLs of different domains overwrite each other in the cache.

## How to Reproduce
Create a setup with multiple domains and enable full static caching. Take the home page as an example, visit it on one site and see that the second site will display the cached page from domain 1.

## Extra Detail

This seems to happen due to the fact that the static cache doesn't put the cached pages into corresponding folders for each site.

## Environment

**Statamic version:** 3.2.12

**PHP version:** 8.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by aerni** [comment]
To reproduce the issue, use this for the site config:

```php
'sites' => [

    'de' => [
        'name' => 'German',
        'locale' => 'de_DE.utf8',
        'url' => 'http://german.test'
    ],

    'fr' => [
        'name' => 'French',
        'locale' => 'fr_FR.utf8',
        'url' => 'http://french.test'
    ],

    'it' => [
        'name' => 'Italian',
        'locale' => 'it_IT.utf8',
        'url' => 'http://italian.test'
    ],

],
```

The static site cache should take the full URL into consideration. As of now, it only uses the path after the domain when generating the static HTML files.
