### ISSUE TITLE
Big Multisite (81 languages) - Very slow (not loading entrys)

### ISSUE THREAD

**Issue by HRR1337** [statamic/cms#4445]
## Bug Description

We have an collection with 66 entries in 81 languages. 

- Loading the collection is not possible anymore.
- Loading another collection + entry with only 3 languages is possible, saving however is not possible.
- Loading the frontsite is not possible 
- php please stache:warm hangs

## How to Reproduce

Install latest statamic
set statamic to pro.
php please multisite
Add in sites.php 81 languages
Create collection with 66 entries
Save every entrie in 81 languages

## Environment

Localhost
Statamic 3.2.14 Pro
Laravel 8.63.0     
PHP 7.4.9
No addons installed

**Statamic version:** 3.2.14

**PHP version:** 7.4.9

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment]
Closing this as "make it faster" is pretty vague.

Might be resolved a little by #3984

**Comment by jasonvarga** [comment]
Did you have the watcher enabled? Did you turn it off?
