### ISSUE TITLE
entries_count is zero in multisite?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#4493]
### Bug description

I'm seeing an issue with `entries_count` showing `0` when translated entries have been published?

This is a problem on the translated site, because I'm using `{{ if entries_count > 0 }}` to hide part of the template if there's no entires and show them if there are more then 0 entries.

### How to reproduce

I've hardcoded the values for this example:

```
{{ taxonomy from="products" collection="solutions" slug:is="control-rooms-and-electrical-panels"}}
  Entries count: {{ entries_count }}
  {{ entries }}
      <li>{{ title }}</li>
  {{ /entries}}  
{{ /taxonomy }}
```

## Default site 
```
site.test/products/control-rooms-and-electrical-panels/solutions
```
![Screenshot 2021-10-15 at 10 06 21](https://user-images.githubusercontent.com/72254741/137462570-5cbb9711-ce4f-4d11-b6cc-a1b4d80ee893.png)

## German site
Even though 2 of the 4 entires are translated and display using the code above, the `entries_count`  is `0`?
```
site-de.test/products/kontrollraume-und-schalttafeln/loesungen
```
![Screenshot 2021-10-15 at 10 05 52](https://user-images.githubusercontent.com/72254741/137462563-8af7990a-0a1d-47d6-b057-b3fe0a8ab928.png)

### Versions

Statamic 3.2.15 Pro
Laravel 8.56.0
PHP 8.0.8
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by kirspuuk** [comment]
Any updates on that? Im seeing the same bug.

**Comment by pauldoerwald** [comment]
I'm seeing this same issue.

**Comment by jasonvarga** [comment]
The issue is due to you targeting the terms by the translated slug. There is an inconsistency with how the entries are counted for the `entries_count` variable.

As a workaround you can use `{{ entries | count }}`. The `entries` contains the correct entries so by counting that you should be okay.

e.g. `{{ if entries|count }}there are entries{{ /if }}`
