### ISSUE TITLE
Calls to model attributes not passed through to user model

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#4499]
### Bug description

I'm using this package: https://github.com/grosv/laravel-passwordless-login.

When you generate a login link, it looks for a specific property on the model, `$login_route_expires_in`, seen here: https://github.com/grosv/laravel-passwordless-login/blob/d06f74f53483721e47d8a2b962bc3307155b5f52/src/LoginUrl.php#L38

You can add a trait (`PasswordlessLogin`) to the `User` model to handle it, but this doesn't really work with Statamic Eloquent Users, cuz the `__get` method doesn't forward to the model: https://github.com/statamic/cms/blob/dbabbc0062914ef74b283afe63d9e139dc46115c/src/Auth/Eloquent/User.php#L377

To work around it I had to do this:

```php
        if ($this->user instanceof \Statamic\Auth\Eloquent\User) {
            $user = $this->user->model();
        } else {
            $user = $this->user;
        }

        $generator = tap(new LoginUrl($user), function (LoginUrl $generator) {
            $generator->setRedirectUrl($this->redirect());
        });
```

Would be great if those attribute references forwarded to the model.

### How to reproduce

1. Have users in the DB
2. `composer require grosv/laravel-passwordless-login`
3. In tinker or Tinkerwell

```php
    $user = User::findbyEmail('foo@bar.com');
    $url = PasswordlessLogin::forUser($user)->generate();
```

### Versions

Statamic 3.2.16 Pro
Laravel 8.64.0
PHP 8.0.11
aryehraber/statamic-captcha 1.5.2
aryehraber/statamic-uuid 2.0.3
doublethreedigital/duplicator 2.0.0
edalzell/forma 1.0
jonassiewertsen/statamic-livewire 2.7.0
statamic/seo-pro 2.3.2
transformstudios/blackbaud dev-main
transformstudios/events 2.2.2
transformstudios/front 1.7.1
transformstudios/gated dev-main
transformstudios/magic-link dev-main
transformstudios/review 3.1
transformstudios/simple dev-main
transformstudios/stripe dev-main
transformstudios/takeover-redirects dev-main

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
This seems to be fixed now (possibly due to changes in #5297).

For example, if I add a getter to my app's `User` model:

```php
public function getSomethingRandomAttribute()
{
    return 'something random';
}
```

Then use Statamic's `User` facade to get a model, I can easily get the getter like this:

```php
use Statamic\Facades\User;

User::all()->first()->something_random;
```
