### ISSUE TITLE
is_parent inside nav tags doen't refer to parent navigation item

### ISSUE THREAD

**Issue by klickreflex** [statamic/cms#4517]
### Bug description

When rendering navigations using e.g. `{{nav:main}}` the `is_parent` variable checks whether an item is a parent according to its hierarchy inside its collection, not inside the nav tree.

I can't see a reason why, when rendering a navigation, one would want the parent indication _not_ be based upon the navigation. 

This makes it virtually impossible to have navigation trees that link to entries of different collections while maintaining correct parent indication. 

### How to reproduce

- Create a navigation that refers to entries of two different collections, e.g.  _Page_ and _Service_

```
- Page 1
  - Page 1.1
  - Service 1.2
  - Page 1.3
- Page 2 
  - Service 2.1
  - Page 2.2
  - Page 2.3
```

- Render that collection and add use `{{ is_parent }}` on first level entries 
- Notice that `{{ is_parent }}`  is not true for first level entries when viewing _Service 1.2_ or _Service 2.1_

### Versions

Statamic 3.2.15 Pro
Laravel 8.61.0
PHP 8.0.8
goldnead/statamic-toc 1.0.5

### Installation

Starter Kit using via CLI

### Additional details

- This might be related: #1559 
- Having parent indication based on nav structure would also solve the problem of not being able to have a nested menu item appear on a root level url (e.g. `site.com/contact` as a slug but that entry being nested unter `site.com/about-us/contact`)

**Comment by robdekort** [comment]
Yeah I noticed this to a while back. Thanks for submitting this. I think I forgot. There could be use cases where you want this behaviour. Maybe a solution could be to add something like a `{{ is_nav_parent }}` variable next to `{{ is_parent }}`.
