### ISSUE TITLE
Replicator field not updating in entry.saving hook

### ISSUE THREAD

**Issue by crackAT** [statamic/cms#4542]
### Bug description

I'm checking some replicator fields in the entry.saving hook. I'm checking for example a bard field in the replicator but if the value was changed after i rejected it i always get the same old value and not the new one. 

here a simple example checking the field length. 
**Bard Field Input in the CP:**
![image](https://user-images.githubusercontent.com/6299060/138254545-8613e02b-d3f3-4e6c-a657-da8e22d3a948.png)
**console.log output:** -> content length: 13
![image](https://user-images.githubusercontent.com/6299060/138254766-6bc4d4a4-4981-498a-8a8c-c9aac99183fd.png)

**Changing Bard field value:**
![image](https://user-images.githubusercontent.com/6299060/138254948-e795610f-71fb-4fed-8c2a-1c2268688821.png)
**console.log output:** -> content length: 13
![image](https://user-images.githubusercontent.com/6299060/138255050-045df30a-4d71-4f52-b3fe-7199ee1ae853.png)

is there a refresh function i missed?

Code:
```
payload.values.content.forEach(function (item) {
        if (item.type == "bard") {
            let description = JSON.parse(item.description);
            console.log(description);
            description = description[0]['content'][0]['text'].replace(/(<([^>]+)>)/gi, "");            
            if (description.length > 1) {
                reject('Error');
            }
        }
    });
```

### How to reproduce

- Add a replicator field in a collection
- add a bard field in the replicator
- insert a value in the bard field
- loop threw the replicator field until bard field found in Statamic.$hooks.on('entry.saving'.... 
- console.log bard value

 

### Versions

Statamic 3.2.12 Pro
Laravel 8.63.0
PHP 7.3.29-to-be-removed-in-future-macOS
4rn0/statamic-v3-image-optimizer 1.0.8
phpsa/statamic-analytics 1.3.0
statamic/eloquent-driver 0.1.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
I'm not quite sure I totally understand what you're trying to achieve but in my testing, the `entry.saving` event always seems to have the latest text from the Bard field, even when saving after a previous rejection.

This issue is quite old now so I'm going to close. If you're still experiencing this issue, please leave a comment and we can re-open. Thanks!
