### ISSUE TITLE
Group_by modifier causes error

### ISSUE THREAD

**Issue by philipboomy** [statamic/cms#4573]
Using group_by modifier on nested array (for example replicator inside replicator causes this error: **modifier ErrorException array_key_exists(): The first argument should be either a string or an integer**

Error is confirmed by Erin via support email.

```
{{ type }}
    {{ virkning group_by="a_virkings_procent" }}
        
    {{ /virkning }}
{{ /type }}
```

Statamic 3.2.17 Pro
Laravel 8.66.0
PHP 7.4.21

**Comment by robdekort** [comment]
Same here:

```html
{{ collection:stores :taxonomy:brands="block:brands|raw|option_list" as="stores" }}
    {{ stores group_by="brands" }}
        <h3>{{ group:title }}</h3>
        {{ items }}
            {{ title }}
        {{ /items }}
    {{ /stores }}
{{ /collection:stores }}
```

**block:brands** comes from a taxonomy terms field.
```yaml
brands:
  - spar
  - meny
```

**Comment by philipboomy** [comment]
Update:

When doing this:
` {{ virkning group_by="a_virkings_procent:label" }}` it doesn't output anything but no errors at least.

**Comment by edalzell** [comment]
I'd leave this open as I still think this is a bug

**Comment by philipboomy** [comment]
Ok reopening

**Comment by jackmcdade** [comment]
Seems to be working properly in the `runtime` parser now.
