### ISSUE TITLE
Navigation endpoint does not output correct content when filtering multisite

### ISSUE THREAD

**Issue by RobbertUpgraders** [statamic/cms#4581]
### Bug description

When trying to fetch a navigation endpoint with ?filter[site]= it will alway return the default site content instead of the correct content. 

### How to reproduce

Setup a multisite Statamic instance. Add navigation tree, fill it with the content of the 2 multisite sites and fetch through the content api the correct navigation endpoint with ?filter[site]= and you will see it always returns the default.

### Versions

Statamic 3.2.18 Pro
Laravel 8.50.0
PHP 7.3.29-1+ubuntu20.04.1+deb.sury.org+1
No addons installed

### Installation

Other (please explain)

### Additional details

Its basically the stock statamic but with added fieldsets, settings etc so we can deploy ready to start instances. WIth all the items we need to start.

**Comment by alanpilloud** [comment]
Hello !

I see the same behaviour without any filters too : using `/api/navs/{nav}/tree` will only return the default language's tree.

**Comment by afonic** [comment]
That sounds about right. You can try the fix above until this is resolved.

**Comment by RobbertUpgraders** [comment]
> Hello !
> 
> I see the same behaviour without any filters too : using `/api/navs/{nav}/tree` will only return the default language's tree.

Not sure if I get what you mean. As adding no filters to your request should return the default entries anyway. Or am I wrong?

**Comment by alanpilloud** [comment]
@RobbertUpgraders From the documentation:

`If you are using Multi-Site, the Content API serves content from all sites at once.`

So I understand that I should have all my sites contents here when I use no filter.

**Comment by afonic** [comment]
The Content API when using the `Entries` endpoint returns content from all sites at once if you don't filter it. You can filter the results using `?filter[site]=`, and it works as it should.

The Navigation or Collection `Tree` endpoint right now returns only the data of the default site. 
In theory you would be able to select another site using `?site={handle}` but it's not working at the moment. You can temporarily work around it by applying the fix above (that will be overwritten when Statamic updates) until it's fixed.
