### ISSUE TITLE
Navigation blueprint: validation doesn't kick in

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#4582]
### Bug description

When you add a required field to your navigation blueprint you can add entries and save the navigation without validation kicking in.

The validation only kicks in when you open an actual nav item to look at the blueprint. 

### How to reproduce

1. Add a a required field to a nav.
2. Add entries to a nav.
3. Save the nav.
4. No validation error.

### Versions

Statamic 3.2.18 Pro
Laravel 8.67.0
PHP 7.4.25

### Installation

Starter Kit using via CLI

**Comment by duncanmcclean** [comment]
Confirmed - only happens if you add entries to the nav.
