### ISSUE TITLE
Select field push_tags not saving new tags

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#4583]
### Bug description

I think I have identified two closely related bugs here. They both occur when enabling 'push_tags' on my select fields.

1. Newly added options are not being saved in the field's yaml (I assume that this is what is supposed to happen??)
2. If you don't add any default options then the control panel crashes when viewing the collection.

Here is my field definition:
```
     -
        handle: event_country
        field:
          options:
            Ireland: null
          multiple: false
          clearable: true
          searchable: true
          taggable: true
          push_tags: true
          cast_booleans: false
          display: Country
          type: select
          icon: select
          width: 50
          listable: hidden
          instructions_position: above
          instructions: 'You can add new items by typing and pressing enter.'
```

### How to reproduce

1. Create a select field
2. Enable searchable, clearable, allow additions and push tags.
3. Add default options to produce bug 1. Leave default options blank to produce bug 2.
4. Create an entry. 
5. Type in a new value to the select field and press enter. 
6. Save the entry.

### Logs

```shell
If I don't add any default options when using these settings then I get these errors:

ERROR 1

[2021-10-26 17:15:37] local.ERROR: Illuminate\Support\Arr::isAssoc(): Argument #1 ($array) must be of type array, null given, called in \vendor\statamic\cms\src\Fieldtypes\HasSelectOptions.php on line 95 {"userId":"faff89d4-1651-4928-a7b3-730cf83e414c","exception":"[object] (TypeError(code: 0): Illuminate\\Support\\Arr::isAssoc(): Argument #1 ($array) must be of type array, null given, called in \vendor\\statamic\\cms\\src\\Fieldtypes\\HasSelectOptions.php on line 95 at \vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php:389)
[stacktrace]
\vendor\\statamic\\cms\\src\\Fieldtypes\\HasSelectOptions.php(95): Illuminate\\Support\\Arr::isAssoc(NULL)
\vendor\\statamic\\cms\\src\\Fieldtypes\\HasSelectOptions.php(88): Statamic\\Fieldtypes\\Select->isOption('Cork')
\vendor\\statamic\\cms\\src\\Fieldtypes\\HasSelectOptions.php(24): Statamic\\Fieldtypes\\Select->getLabel('Cork')
#3 [internal function]: Statamic\\Fieldtypes\\Select->Statamic\\Fieldtypes\\{closure}('Cork', 0)

ERROR 2 (When the value is NULL)

[2021-10-26 17:19:28] local.ERROR: Illuminate\Support\Arr::isAssoc(): Argument #1 ($array) must be of type array, null given, called in \vendor\statamic\cms\src\Fieldtypes\HasSelectOptions.php on line 95 {"userId":"faff89d4-1651-4928-a7b3-730cf83e414c","exception":"[object] (TypeError(code: 0): Illuminate\\Support\\Arr::isAssoc(): Argument #1 ($array) must be of type array, null given, called in \vendor\\statamic\\cms\\src\\Fieldtypes\\HasSelectOptions.php on line 95 at \vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php:389)
[stacktrace]
#0 \vendor\\statamic\\cms\\src\\Fieldtypes\\HasSelectOptions.php(95): Illuminate\\Support\\Arr::isAssoc(NULL)
#1 \vendor\\statamic\\cms\\src\\Fieldtypes\\HasSelectOptions.php(88): Statamic\\Fieldtypes\\Select->isOption(NULL)
#2 \vendor\\statamic\\cms\\src\\Fieldtypes\\HasSelectOptions.php(24): Statamic\\Fieldtypes\\Select->getLabel(NULL)
#3 [internal function]: Statamic\\Fieldtypes\\Select->Statamic\\Fieldtypes\\{closure}(NULL, 0)
```

### Versions

Statamic 3.2.18 Pro
Laravel 8.68.0
PHP 8.0.10
edalzell/blade-directives 3.5.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by samburgers** [comment]
Can confirm issue still exists with `3.3.11`

**Comment by jasonvarga** [comment]
Honestly I'm not even sure what the point of push_tags is. All it really does is make the option persist in the dropdown for the duration of the form being open. It doesn't get saved back to the field.

We don't have any fieldtypes that manipulate the blueprint files.

I would say we should probably remove the push_tags option completely.

For now, I'd suggest using a taxonomy and a terms fieldtype if you want to persist new items.

**Comment by samburgers** [comment]
that certainly clears things up, thanks @jasonvarga

**Comment by stuartcusackie** [comment]
@jasonvarga Sounds fine to me. Taxonomies / terms fields work just fine in my case.

Feel free to close the issue. I'll leave it open in case it's useful as a reminder to remove the push_tags option.
