### ISSUE TITLE
Not able to install starter kits on Windows?

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#4584]
### Bug description

See discussion here: https://github.com/statamic/cms/discussions/4492

- [ ] Ensure starter kits can be installed using statamic/cli on Windows.
- [ ] Ensure starter kits can be installed into existing apps on Windows.

### How to reproduce

Run `php please starter-kit:install` or `statamic new site starter/kit` on Windows.

### Versions

Windows 10/11

**Comment by robdekort** [comment]
I had someone on the Peak Discord who misses all the `view` files after installation on Windows. Is this related Jesse?

**Comment by aspoet** [comment]
@robdekort Correct, that was me :) I am having the same issue on all my windows machines.

I could install starter kits without a problem before and it has stopped working. Last time I successfully installed was about a month ago, now I tried again and it does not work.

### Issue

Neither running `statamic new projectname starter/kit` nor install it into a blank statamic project via `php please starter-kit:install` works. 

After creating the site the starter kit seems to install successfully (see Console Installation Log). Once I fire up the server I get a 404 page – Control Panel and everything is vanilla statamic and works. I can basically use Statamic in a blank state.

However, all starter kit files are missing, the folders are empty except a `.gitkeep` file. This is especially strange that during installation those files are explicitly listed as installing (see log). The installation process finishes successfully and I am prompted to create a user. The starterkit files are, as stated, still missing

**Attachments:**

[Console Installation Log](https://github.com/statamic/cms/files/7590430/starter-kit-installation.txt)
[laravel.log](https://github.com/statamic/cms/files/7590431/laravel.log)

**Environment:**
- Statamic 3.2.*
- Windows 10 Version 10.0.19043 Build 19043
- Composer 2.1.12
- PHP 8.0.12

**Comment by jesseleite** [comment]
Not good, thanks for the info! Need to get Windows dev environment setup again, will take a look soon

**Comment by jesseleite** [comment]
Should be fixed in today's release 👍
