### ISSUE TITLE
Site::selected() output is always the default site

### ISSUE THREAD

**Issue by ddm-dano** [statamic/cms#4605]
### Bug description

I use the Site facade to get the current cp's selected locale with ``Site::selected()->locale()``, but that doesn't work as expected. The session key 'statamic.cp.selected-site' always returns NULL and so its output is always the default site instead of the current selected site. That happens even though the SelectSiteController is called.

### How to reproduce

1. Create a multisite Statamic setup
2. I.e. write in some CpController ``var_dump(session('statamic.cp.selected-site'))``
3. Select different site
4. Still outputs default site with ``Site::selected()->locale()``

### Versions

Statamic 3.2.18 Pro
Laravel 8.68.1
PHP 8.0.11

### Installation

Fresh statamic/statamic site via CLI

**Comment by ddm-dano** [comment]
@jasonvarga and @duncanmcclean Thank you for looking into it, it seems like it had to do with a setup issue, I can't reproduce it anymore either.

**Comment by ddm-dano** [comment]
Oh, I can reproduce it on our addon [ddm-studio/cookie-byte](https://github.com/ddm-studio/cookie-byte). I can't access the Session variable `statamic.cp.selected-site`, because my whole session is flushed before (`session()->all()` gives me an empty array). Thus I can't get the currently select site in the CP and so I always access the default site's settings (in my case German).

It's in the file src/Configuration/CookieByteConfig.php and the method getLocale() where I use:
```php
if (session('statamic.cp.selected-site')) return Site::selected()->locale();
else return Site::current()->locale();
```

**Comment by jasonvarga** [comment]
In your addon, you are creating a `new CookieByteConfig` in the constructor of your controller.
The controller is constructed before the session is ready.

Create it within the individual methods instead.
```php
public function index() {
    $this->config = new CookieByteConfig();
```
