### ISSUE TITLE
URI validation based on route

### ISSUE THREAD

**Issue by aerni** [statamic/cms#4637]
### Bug description

I've got a non-orderable collection with publish dates turned on. The route looks like this `/tours/{year}/{slug}`. I'm expecting to be able to have multiple entries with the same slug as long as their publish year is different. But I'm getting a `This URI has already been taken` error no matter the publish date. Is [this PR](https://github.com/statamic/cms/pull/3671) only meant to work with orderable collections? It would be awesome if it was smart enough to pick up on the route.

### How to reproduce

- Create a non-orderable collection with publish dates turned on
- Change the route to something like `/tours/{year}/{slug}`
- Add two entries with the same slug and try saving

### Versions

Statamic 3.2.19 Pro
Laravel 8.69.0
PHP 7.4.25
aerni/livewire-forms 1.1.0
aryehraber/statamic-impersonator 2.2.0
doublethreedigital/duplicator 1.3.4
jonassiewertsen/statamic-livewire 2.7.0
spatie/statamic-responsive-images 2.8.5
visuellverstehen/statamic-classify 2.3.1
withcandour/aardvark-seo 2.0.16

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Seems fine to me. Can you create a repo with this bug replicated?

**Comment by aerni** [comment]
False alarm. I changed the date but forgot about the year. 🤦‍♂️
