### ISSUE TITLE
Versions > 3.2.15 no longer load assets

### ISSUE THREAD

**Issue by davidatkinswwt** [statamic/cms#4646]
### Bug description

I am currently on 3.2.15 and upgrading to 3.2.16+ (up to current version 20) causes my images on the frontend to not be found and downgrading "fixes" the issue. 

In my content > collections > text.md files the image paths are images/photo.jpg which are all located in my assets container and work on 3.2.15. 

Most of my images are restricted to a specific folder when setting up the fields initially. 

I checked that upgrading past 15 was not reseting the assets container Handle or File Driver. 

Deleting and re-uploading the images also does not fix the issue. 

Hopefully I'm not missing something obvious. Thanks for any help. 

### How to reproduce

Upload images and try to display on 3.2.16+. 

### Versions

Statamic 3.2.15 Pro
Laravel 8.68.1
PHP 8.0.12
statamic/seo-pro 2.3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
When you say they're "not found" on your front-end, can you elaborate?

How are you attempting to show them? Just with a `{{ url }}` tag? Using `glide`? Can you show a snippet of the template?

**Comment by davidatkinswwt** [comment]
> When you say they're "not found" on your front-end, can you elaborate?
> 
> How are you attempting to show them? Just with a `{{ url }}` tag? Using `glide`? Can you show a snippet of the template?

Thank you for the reply.
Here's a snippet. 

```
  <div class="absolute inset-0">
    <img class="object-cover " src="{{ glide:background_image width=" 1920" height="1080" }}">
    <div class=" absolute inset-0 mix-blend-multiply {{ theme:background }}" aria-hidden="true">
    </div>
  </div>
```

I don't know why I didn't do this earlier but removing glide lets me display the image on the frontend without any issues.

**Comment by jasonvarga** [comment]
See you have `width=" 1920"`. Get rid of that extra space: `width="1920"`. That should do it.

**Comment by davidatkinswwt** [comment]
Formatter keeps putting those in there. 😬 Thanks. 👍
