### ISSUE TITLE
Bard in fullscreen mode: bard fields in a bard set also rendered fullscreen

### ISSUE THREAD

**Issue by marflow** [statamic/cms#4666]
### Bug description

 I have a bard field 'article' and in that a bard set 'figure' that´s containing a bard field for the 'caption'. When I enable fullscreen mode, the nested bard field also gets full height. `Allow fullscreen' is disabled for the 'caption ' field.

### How to reproduce

Define a bard field including a bard set with a bard field and switch to fullscreen mode.
![bard-in-bard-set](https://user-images.githubusercontent.com/6233748/140534966-39784289-9af5-4a11-868f-5a63ce91ce76.jpg)

### Versions

3.2.19

### Installation

Fresh statamic/statamic site via CLI

**Comment by jonassiewertsen** [comment]
I can confirm that behavior, as we are running into the same issue.

**Comment by jonassiewertsen** [comment]
Every bard Fieldtype has the `.ProseMirror` class applied, even if a bard fieldtype is inside another Bard fieldtype. 

As every `.ProseMirror` class uses a fullscreen min-height, the second bard fieldtype is toooooo heigh and would fill the complete screen as well:
https://github.com/statamic/cms/blob/3.2/resources/sass/components/fieldtypes/bard.scss#L227

It might be a solution to use some clever css, which only applies for the parent bard fieldtype.
