### ISSUE TITLE
GraphQL: Multi-select fields are not being filtered

### ISSUE THREAD

**Issue by bobevsky** [statamic/cms#4675]
### Bug description

If you have a multi-select field that you need to filter for in the GraphQL API you will get no results.

For example if I run this query:

```query MyQuery {
  entries(collection: "products", filter: {material: {in: ["material-two"]}}) {
    data {
      ... on Entry_Products_Products {
        name
        material {
          label
          value
        }
      }
    }
  }
}
```

I get the following result:

```
{
  "data": {
    "entries": {
      "data": []
    }
  }
}
```

And for instance if material (which in this case is set to multiple) was set to single option select, the filter works just fine!

### How to reproduce

Make a multiselect inside a collection and try to filter the entries inside it by any of it's values. 

### Versions

Statamic version: 3.2.20
PHP version: 8.0

### Installation

Fresh statamic/statamic site via CLI

**Comment by afonic** [comment]
Just to save some time, I think this is related to this: https://github.com/statamic/ideas/issues/434

Generally, unless I missed newer developments, querying multiselect fields doesn't work as intended.

**Comment by bobevsky** [comment]
Found a way to work around this. The query should actually be turned around for multi-selects and deep nesting. For anyone having this problem with Graphql, use the query like this:

```{
  entries(collection: "products", filter: {material: {in: {value: ["material-two"]}}}) {
    data {
      ... on Entry_Products_Products {
        title
        material {
          value
        }
      }
    }
  }
}
```
