### ISSUE TITLE
Limit parameter isn't supported by the ASSETS tag pair

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#4680]
### Bug description

If you have an array of assets, and use this tag pair with the limit parameter:

`{{ assets:figure_featured limit="1" }}
  <img src="{{ glide:url quality="60" fit="crop_focal" width="900" height="600" }}">
{{ /assets:figure_featured }}`

...the limit parameter doesn't work, even though the docs says it should:

https://statamic.dev/tags/assets

For now I use `{{ if first }}` as a way around.

### How to reproduce

1. Create an array of assets.
2. Try the ASSETS tag pair with a limit parameter
3. All the assets in the array is shown, regardless of the limit parameter.

### Versions

Statamic 3.2.20 Pro

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
You don't need the `assets` tag in v3 anymore, although it'll be fixed in the next release anyway.

You can just do `{{ figure_featured limit="1" }} ... {{ /figure_featured }}`
