### ISSUE TITLE
Quotes in Alt Tag Content Break Alt Tag

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#4683]
### Bug description

If a user adds quotes in the contents of an alt tag it will break the alt tag.

### How to reproduce

In an alt tag enter something like:

`This is a great artwork "My Great Artwork Name" and you should buy it.`

Using a standard template such as:

```
{{ my_image }}
  <img src="{{ url }}" alt="{{ alt }} />
{{ /my_image }}
```

The output in the browser is broken and looks like the following:
![image](https://user-images.githubusercontent.com/1778271/140912794-89bd3875-4ad0-451f-b30a-b1694d7e6162.png)

### Versions

Statamic 3.2.20 Solo
Laravel 8.69.0
PHP 7.4.13
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I tried to see if it could create a potential security issue by trying to use this to create an `onload="alert('hacked')` but thankfully this does not seem to be an issue as far as I can tell.

**Comment by jcohlmeyer** [comment]
I found the easiest way to fix it was to use the `smartypants` modifier `... alt={{ alt | smartypants }}`. I would suggest applying this modifier to alt tags by default.

**Comment by jcohlmeyer** [comment]
Another way to solve it would be the way Drupal does, where it encodes the quotes for alt tags: `alt="Opening of &quot;Rare Reflections&quot;, June 23, 2011."` (Statamic currently does this, in the source code, creating invalid source code when you do not use a modifier`alt="Opening of "Rare Reflections", June 23, 2011."`)

**Comment by jasonvarga** [comment]
Use the entities modifier. 👍  We can't start escaping values automatically now.
