### ISSUE TITLE
Adding a set in Bard is not keyboard accessible

### ISSUE THREAD

**Issue by JayGeorge** [statamic/cms#4684]
### Bug description

It used to be possible to add a set in Bard without reaching for a mouse but this broke at some point.

When you're in the main Bard content field you **used to be able to**:

1. Hit enter (which is the point at which the little plus sign appears on the left)
2. Shift + tab to highlight the plus button
3. Enter to get the little dropdown menu to appear
4. I think you used to be able to then press tab or up/down to go through the Set list. Something changed in the last few months which means this last step is no longer possible  

### How to reproduce

10 second silent screencast attached

https://user-images.githubusercontent.com/693601/140915379-6df715f7-1666-4f6c-9154-d8399ddb47e5.mp4

When you're in the main Bard content field:

1. Hit enter (which is the point at which the little plus sign appears on the left)
2. Shift + tab to highlight the plus button
3. Enter to get the little dropdown menu to appear
4. Observe how you need to use the mouse to get any further.

### Versions

Statamic 3.2.20 Solo
Laravel 8.69.0
PHP 8.0.9
jaygeorge/admin-styler dev-main

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Seems like its a heck of a lot better now, except that once you pick the set, your focus gets moved into the void.

**Comment by JayGeorge** [comment]
Oh yeah, the new set picker fixes this. Good to close, I'd say.
