### ISSUE TITLE
Unable to parse YAML

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#4704]
### Bug description

I have a bard field called 'article_content' and it contains an 'image_blockquote' set, which contains a field called 'description' (textarea).

My client tends to go crazy on line breaks and spacing when using the editor and they have managed to produce these errors:

![image](https://user-images.githubusercontent.com/20210934/141143188-453426a9-edbf-4174-b546-ccc6ac44f53b.png)

![image](https://user-images.githubusercontent.com/20210934/141142986-1f8c8e97-0f88-448c-861f-17eccd7b57fa.png)

### How to reproduce

1. Set up a bard field
2. Add a set
3. Add a textarea to the set
4. Add textarea content with lots of line breaks in unusual places.

### Logs

`Unable to parse at line 114 (near \"  Russian novelist and philosopher.\"). at \\vendor\\symfony\\yaml\\Parser.php:495)`

### Versions

Statamic 3.1.34 Pro
Laravel 8.55.0
PHP 8.0.10
edalzell/blade-directives 3.5

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
What's the error?

**Comment by stuartcusackie** [comment]
Just added it now to the issue. Seems the indentation is incorrect at 'Russian novelist'?

**Comment by jasonvarga** [comment]
Thank you.

I'm guessing this is going to be an issue with symfony/yaml though.

Could you put the yaml in here as text so we can copy/paste it?

**Comment by stuartcusackie** [comment]
---
id: a643fcc7-0b32-4fef-8bc3-7945c19ff375
published: false
blueprint: articles
title: 'Finding Authentic Meaning & Purpose       - The Obstacles'
image: pop-zebra-2fV74MiWrVo-unsplash.jpg
category: meaning-and-purpose
part: 1
excerpt: 'A sense of meaning can keep us grounded in the midst of trials, but first, we have to rise above the obstacles that can slow us down in our search for our life’s purpose'
author: c396338f-de3b-4dfe-b987-08fb0ccc6afc
feature: false
style: dark
featured_overlay: true
featured_overlay_opacity: '50'
updated_by: c396338f-de3b-4dfe-b987-08fb0ccc6afc
updated_at: 1636452495
article_content:
  -
    type: paragraph
  -
    type: paragraph
  -
    type: paragraph
  -
    type: heading
    attrs:
      level: 2
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: ' Happy No Matter What - A Short Story'
  -
    type: paragraph
  -
    type: paragraph
    content:
      -
        type: text
        text: 'We were driving along the South Circular Road on our way home to Templeouge, a suburb on the southside of Dublin, when '
      -
        type: text
        marks:
          -
            type: underline
        text: Cushla’s
      -
        type: text
        text: " mobile ‘phone rang. We had been expecting the call from St. Vincents Hospital, where\_ Cushla had been diagnosed with breast cancer eight months earlier. After chemotherapy and radiation, she was given the all-clear, but on a recent check-up, the oncologist had suspected something wasn’t right and had sent her for a battery of tests."
  -
    type: paragraph
    content:
      -
        type: text
        text: "\_Fear and weariness began to creep up my body. I wanted to hear what the caller had to say, so I pulled over to the kerb and parked the car."
  -
    type: paragraph
    content:
      -
        type: text
        text: "The senior hospital administrator on the phone was now telling Cushla they had ‘found something’ and that the oncologist himself would contact her soon. I was devastated. \_I knew the cancer had come back.\_ Before the call, we had been praying together, but I didn’t want to pick up where we had left off—I felt I didn’t have the strength. ‘Now is the time to pray,’ Cushla said. She meant it more for me than for her. I protested, but she continued to encourage me to carry on praying. Despite the bad news, she was thinking of me as she attempted to sustain me in my anguish. Before I joined her again in prayers, to my amazement and eternal admiration, she gently reminded me that we should drive off because she needed to pick up her brother, Peter, from his mental health workshop at the usual time of 3:00 pm. Again, she was putting someone else’s welfare before her own."
  -
    type: paragraph
    content:
      -
        type: text
        text: 'When we got home, Cushla sprang into action, collecting what she needed before heading off in the car to collect her brother. After bringing him to their family home, where he lived with their mother, Patsy, she planned to spend the rest of the afternoon looking after him and Patsy, who had developed dementia a couple of years earlier.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Incredibly, despite the bad news, Cushla was still keeping up her usual light-hearted demeanour. She wasn’t putting on a brave face. Nor was she in denial. Her joy came from somewhere deep in her soul. She even tried to pep me up, smiling and joking, before she closed the front door behind her and headed off to collect Peter.'
  -
    type: paragraph
    content:
      -
        type: text
        text: "Despite many trials, including bearing another debilitating illness for seventeen years, Cushla was easily the happiest person I had ever met. So, where did she get this incredible strength and sense of joy from even when facing her own death?\_ Having known and loved her for twenty-seven years, I can categorically say that it was because of her strong faith in God."
      -
        type: text
        marks:
          -
            type: bold
        text: ' '
      -
        type: text
        marks:
          -
            type: bold
          -
            type: underline
        text: '‘If you have a hundred per cent faith, you will have zero per cent fear.’ '
      -
        type: text
        text: 'was not just saying she coined herself but a tenet she lived by faithfully giving her a sense of meaning and purpose that transcended any suffering she faced in this ‘veil of tears’.'
  -
    type: set
    attrs:
      values:
        type: image_blockquote
        image: pexels-cottonbro-4009402.jpg
        quote: |2+
           ‘The mystery of human existence lies not in just staying alive, but in finding something to live for.’


        description: |-

           – Fyodor Dostoyevsky, 
             

          Russian novelist and philosopher.
  -
    type: paragraph
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Everybody has a different calling, but Cushla knew that her mission was, at its core, to love and take care of those around her. It seems that she made a good choice from a spiritual and psychological standpoint:'
  -
    type: paragraph
    content:
      -
        type: text
        text: "\_There is growing evidence that a sense of meaning and purpose that transcends our own narrow ambitions"
      -
        type: text
        marks:
          -
            type: bold
        text: ' '
      -
        type: text
        text: 'and desires seems to increase our resilience and mental well-being in general. In '
      -
        type: text
        marks:
          -
            type: italic
        text: 'Psychology Today,'
      -
        type: text
        text: ' Sherry Hamby, PhD'
      -
        type: text
        marks:
          -
            type: bold
        text: ','
      -
        type: text
        text: "\_a Research Professor of Psychology, University of the South, states:"
  -
    type: paragraph
    content:
      -
        type: text
        text: "\_‘So far, we have examined 35 different strengths, and the results have been surprisingly consistent: A sense of purpose appears to contribute to well-being more than other strengths."
      -
        type: text
        marks:
          -
            type: bold
        text: ' '
      -
        type: text
        text: 'In one head-to-head comparison, purpose was the only strength that was uniquely associated with healthy functioning after adversity’'
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: "\_"
  -
    type: heading
    attrs:
      level: 2
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: 'Three Obstacles That Prevent You From Finding Your Purpose'
  -
    type: paragraph
  -
    type: paragraph
  -
    type: heading
    attrs:
      level: 3
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: '1) You’ve bought into the world’s values'
  -
    type: paragraph
    content:
      -
        type: text
        text: "\_"
  -
    type: paragraph
    content:
      -
        type: text
        text: "You probably felt, even from an early age, that you \_needed to find a meaningful purpose greater than your own narrow-self interests, but just like me, you might have neglected or delayed\_ your search:"
  -
    type: paragraph
    content:
      -
        type: text
        text: "For years I was captured by the world’s idea of success and achievement. Ironically as soon as I tasted ‘success’, I felt hollow inside. I slowly began to see through the shallow values I had unconsciously picked up. Inspired by Cushla, who had never allowed herself to be shortchanged by our materialistic society, with its lack of imagination about what a human life can be, I began my own search for a more meaningful purpose in life. The journey wasn’t easy, though.\_ I had many \_obstacles and personal faults \_to deal with, including:"
  -
    type: paragraph
  -
    type: paragraph
    content:
      -
        type: text
        text: "\_"
  -
    type: heading
    attrs:
      level: 3
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: "2)\_\_ "
      -
        type: text
        text: Attachments
  -
    type: paragraph
  -
    type: set
    attrs:
      values:
        type: image_blockquote
        image: sofiane-bouzroud-CsK07j-I8V4-unsplash-1636039406.jpg
        quote: |-
          Jesus said to him, ‘If you would be perfect, go, sell what you possess and give to the poor, and you will have treasure in heaven; and come, follow me.’ When the young man heard this, he went away sorrowful; for he had great possessions.







          Matthew 19:16-22
  -
    type: paragraph
  -
    type: paragraph
    content:
      -
        type: text
        text: 'You may not think you have a core negative belief or strong attachment to wealth, as the rich young man in the bible had. Still, if you’re mysteriously stuck regarding finding a meaningful purpose for your life, some unconscious idea you have may be holding you back—or blowing you off course and away from a higher calling.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'You need to become aware of what’s actually driving you. Although I was never materialistic, I had an unexamined core belief that money could buy me the freedom to do what I really wanted to do, so I spent an inordinate amount of time and energy pursuing it.'
  -
    type: paragraph
    content:
      -
        type: text
        text: "The world promises you everything, but it’s a lie. Because of my attachment to ‘success’, I never questioned my approach to finding my purpose: I thought I could pursue wealth, and in time, \_I would find a deeper meaning. Despite going down multiple fruitless paths that eventually made me unhappy, I clung to the idea that ‘this time it will work’, only to be left bereft and feeling empty again. As John Lennon sang in ‘"
      -
        type: text
        marks:
          -
            type: italic
        text: 'Beautiful Boy’'
      -
        type: text
        text: ": ‘Life is what happens\_to you while you’re busy making other plans.’."
  -
    type: paragraph
    content:
      -
        type: text
        text: "\_"
  -
    type: heading
    attrs:
      level: 3
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: "3) \_Impatience"
  -
    type: heading
    attrs:
      level: 3
    content:
      -
        type: text
        text: "\_"
  -
    type: paragraph
    content:
      -
        type: text
        text: "Some of you are saying: ‘But I’m years searching for my life’s purpose!’ This was the case with me.\_ Impatience is one of my trademarks. Sometimes I think that instant gratification takes too long! My attitude is constantly reinforced by our hurry-up society, where we are losing the ability to wait because we want what we want right now. Fortunately, I had Cushla, who would reassure me when I became frustrated in my search, saying: ‘God will reveal His purpose for your life, in time’. I also had passion and persistence, which kept me going during the bleaker moments when \_I thought \_I would never find my calling. \_Looking back on these times, I can now say it was all meant to be:\_ the search for meaning was part of the journey."
  -
    type: paragraph
    content:
      -
        type: text
        text: "\_"
  -
    type: heading
    attrs:
      level: 3
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: 'Recommended Resources:'
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: italic
        text: 'Books:'
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: italic
        text: 'Man’s Search For Meaning '
      -
        type: text
        text: 'by Victor E. Frankl. Published by Beacon Press'
---

**Comment by stuartcusackie** [comment]
Just posted above. As you can see, there are a lot of unnecessary spaces and line breaks. My client is old school.

Can you copy this somewhere and let me know if I can delete it?

**Comment by jasonvarga** [comment]
I edited it down to just the problematic bit and changed the content.

**Comment by stuartcusackie** [comment]
Great. Thank you.
