### ISSUE TITLE
Nav Tag `handle` Param not Working

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#4708]
### Bug description

The handle parameter on the `nav` tag seems to not work.

### How to reproduce

When I try to use the `nav` tag with the `handle` parameter like this:
```
{{ nav :handle='navigation' }}
```
... or even like this ...
```
{{ nav handle='collection:exhibitions' }}
```
... it does not work, but when I do this it does work ....
```
{{ nav:collection:exhibitions }}
```

### Versions

Statamic 3.2.21 Solo
Laravel 8.69.0
PHP 7.4.13
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Additional details

[Nav Tag Parameter Reference](https://statamic.dev/tags/nav#parameters)

**Comment by jelleroorda** [comment]
Hey @jcohlmeyer, when you're using the `nav` tag for a collection, the correct syntax is:

`{{ nav handle="collection::exhibitions }}` or `{{ nav:collection:exhibitions }}` (this one you've already found).

What is the value of `navigation` when you're using `{{ nav :handle='navigation' }}`?

**Comment by jcohlmeyer** [comment]
Yes, that indeed solves it. It is not intuitive to me that I have to use two colons when using the handle syntax. Thanks.
