### ISSUE TITLE
Static cache ignored excluded paths

### ISSUE THREAD

**Issue by m-glass** [statamic/cms#4729]
### Bug description

Usually, in `config/statamic/static_cache.php` there is an option to exclude paths/urls which shouldn't be cached. But at least when running `php please static:warm` this array gets ignored. I, for example, exclude urls because there are no template files for them (view [issue 4468](https://github.com/statamic/cms/issues/4468)).

### How to reproduce

In `config/statamic/static_cache.php`, configure the `exclude` array like

```php
<?php

return [

// ...

'exclude' => [
        '/sitemap.xml',
        '/blog',
        '/blog/*',
        '/*/categories',
        '/*/categories/*',
        '/*/tags',
        '/*/tags/*',
       
        // even with sth manageable (or the exact pattern like in the [docs](https://statamic.dev/static-caching#excluding-pages)) like '/blog/categories/*' the exclusion doesn't work
    ],

// ...

],
```

Then run `php please static:warm`

While running, you'll see that the excluded URLs are still getting called. Because they don't exist, the routes return `404 Not Found`, which drags out the execution time (I think for my site it was ~ 30 min to get this command done. Much content ya know..)

### Versions

Statamic 3.2.20 Pro
Laravel 8.46.0
PHP 7.4.25
transformstudios/review 3.1
withcandour/aardvark-seo 2.0.16

### Installation

Other (please explain)

### Additional details

Site & content already existing

**Comment by edalzell** [comment]
For anyone who wants to fix, the urls are generated here: https://github.com/statamic/cms/blob/c3228252b6dbdbc9918ebc975a00a4520197738e/src/Console/Commands/StaticWarm.php#L109

**Comment by jasonvarga** [comment]
Exists with more detail at statamic/ideas#667
