### ISSUE TITLE
Use excluded URLs from static caching configuration during static:warm

### ISSUE THREAD

**Issue by Sm1lEE** [statamic/cms#4732]
When executing the `static:warm` command in a recent project, I recognized many 404 entries while the crawler visited all the URLs. These were all related to taxonomy routes, that are automatically created when the taxonomy is attached to a collection ([Documentation](https://statamic.dev/taxonomies#collections)).  

In my case, a frontend view and route for these taxonomies and terms are not necessary. Therefore I was wondering if the excluded URLs array from the static_caching.php configuration file could also be used here. This would reduce unnecessary server requests. In my case this cut down the requests by over 1.400 related to taxonomies.  

I've prepared a [feature over here](https://github.com/Sm1lEE/cms/commit/df22f3e0c31fa0acf8e124778222d341524db38e), but wasn't completely sure about potential side effects and would like to get some feedback from you if this could enhance statamic's core functionality.

The feature reuses the [isExcluded() method](https://github.com/statamic/cms/blob/a3d9bbd5ac9bbd4ffad0d9126dd75f4756b6c570/src/StaticCaching/Cachers/AbstractCacher.php#L246) from [src/StaticCaching/Cachers/AbstractCacher.php](https://github.com/statamic/cms/blob/a3d9bbd5ac9bbd4ffad0d9126dd75f4756b6c570/src/StaticCaching/Cachers/AbstractCacher.php) to remove excluded URLs from the crawler's queue.

The original isExcluded() method supports these formats ([Documentation](https://statamic.dev/static-caching#excluding-pages)):
```php
return [
    'exclude' => [
        '/contact',
        '/blog/*',  // Excludes /blog/post-name, but not /blog
        '/news*',   // Exclude /news, /news/article, and /newspaper
    ]
];
```

But the taxonomy part of the URL occurs in different formats, e. g.:
- /**{taxonomy-slug}**
- /{collection-url}/**{taxonomy-slug}**
- /{collection-url}/**{taxonomy slug}**/{term slug}

Therefore I extended the isExcluded() method inside the StaticWarm class to also support URL patterns starting with a wildcard, e. g.:
```php
return [
    'exclude' => [
        '*/blog',  // Excludes /technology/blog
        '*/news*',   // Exclude /technology/news, /technology/newspaper; but not /technology/news/international
        '*/news/*',   // Exclude /technology/news/international
    ]
];
```

My implementation does not explicitly target taxonomies but takes all URLs into account, regardless of their origin or types.

**Comment by MattRogowski** [comment]
Can I confirm with this whether static:warm is called internally at any point? I have had an issue where an excluded page (contact form) has started being cached without any interaction from me - I clear the cache on deploys, but the cache file was created at a time I hadn't touched anything, and hadn't run any manual commands. Does Statamic warm the cache itself periodically which may have triggered it?

**Comment by jasonvarga** [comment]
It doesn't get called anywhere aside from when you manually run the command.
Maybe an addon?

**Comment by MattRogowski** [comment]
Hm, I only have one for redirects. It seemed to start after upgrading from 3.0 to 3.2, the contact page got cached the same day and I didn't notice, cleared cache and monitored and then it randomly got cached again a day or so later when I wasn't doing anything. Will continue monitoring and see if I can come up with anything more concrete.
