### ISSUE TITLE
Form submission ajax call from another domain

### ISSUE THREAD

**Issue by SteJW** [statamic/cms#4744]
### Bug description

When I do a form submission using Next JS, from another domain, Statamic doesn't recognise the URL and therefor the site is null. This creates an error in the Form Controller.

```
{ "message": "Call to a member function lang() on null",
"exception": "Error",
"file": "/home/vagrant/Sites/statamic-cms/vendor/statamic/cms/src/Http/Controllers/FormController.php",
"line": 50
}
```

### How to reproduce

The easiest way to test this is by using Postman or execute the CURL.
First, create a form in the CP "newsletter" with fields name, email.

The first curl call works and gives the "succes:true" because it's missing the referer.

```
curl --location --request POST 'https://statamic-cms.local/!/forms/newsletter' \
--header 'Accept: application/json' \
--form 'name="test"' \
--form 'email="test@test.com"'
```

This call triggers the error.
```
curl --location --request POST 'https://statamic-cms.local/!/forms/newsletter' \
--header 'Referer: https://statamic-other-url.local' \
--header 'Accept: application/json' \
--form 'name="test"' \
--form 'email="test@test.com"'
```

A possible solution in src/Http/FormController.php would be:

```
if(!$site) {
    $site = Site::default();
}
```
        

### Versions

Statamic 3.2.20 Pro
Laravel 8.70.2
PHP 7.4.24

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Ah good find. I haven't tested, but for whoever implements the fix, it's probably as simple as changing this line:

https://github.com/statamic/cms/blob/d49cbf9cf9fc67d4cc6bea77a333e6a682bddafc/src/Http/Controllers/FormController.php#L33

to this:

```php
$site = Site::findByUrl(URL::previous()) ?? Site::default();
```

**Comment by SteJW** [comment]
Thanks! I tried to create a pull request, haven't done that before.

**Comment by jasonvarga** [comment]
The pull request looks good! We'll test it out when we get a chance.
