### ISSUE TITLE
static:warm command failing

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#4749]
### Bug description

If running `static:warm` on a production site I get the following error:

<img width="1022" alt="Screenshot 2021-11-16 at 18 37 02" src="https://user-images.githubusercontent.com/38906163/142036702-b4e6b4e3-7e86-4927-890e-477bc3298214.png">

### How to reproduce

I am not sure how this can be reproduced. As our site has round about 3.000 entries, I am not sure how this is related. 

The page is not doing anything fancy, the does simply has a few more entries than normal.

### Logs

```shell
Statamic\Console\Commands\StaticWarm::outputFailureLine(): Argument #1 ($exception) must be of type Psr\Http\Client\ClientExceptionInterface, GuzzleHttp\Exception\ClientException given at vendor/statamic/cms/src/Console/Commands/StaticWarm.php:78
```

### Versions

Statamic 3.2.22 Pro
Laravel 7.30.4
PHP 8.0.3
pecotamic/sitemap 1.2.7
spatie/statamic-responsive-images 2.8.5
statamic/seo-pro 2.3.2

### Installation

Other (please explain)

**Comment by jasonvarga** [comment]
Okay, the real exception is being masked by this output one.

I wonder if it's related to #4746.

**Comment by jonassiewertsen** [comment]
It might be related somehow for sure. 

The errors are a little different though:
This Error does get thrown if warming the stache `stache:warm`

Issue #4746 does get thrown if updating the search and the Algolia driver `search:update`.

**Comment by jasonvarga** [comment]
I understand they happen at different times. But in both cases you are interacting with entries, so maybe the problem entry is triggering the error in both cases.

**Comment by jonassiewertsen** [comment]
That's really likely.

**Comment by jonassiewertsen** [comment]
This is odd ... as descried in #4746, I had problems using Algolia to search in the cp. 

Setting searchables inside the `config/statamic/search.php` to `all` does include assets. 
As far as I did set searchables to explicit collections only, everything does work as expected. 

This error message from my logs might help
```bash
[2021-11-16 20:36:16] production.ERROR: Call to undefined method Statamic\Assets\Asset::collection() {"userId":"XXXX","exception":"[object] (Error(code: 0): Call to undefined method Statamic\\Assets\\Asset::collection() at /home/forge/production.page.com/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php:31)
```
Somehow the ListedEntry class does try to get a collection from an Asset ... this will not work. 

I couldn't dig deeper but am hoping that this will help.

**Comment by jonassiewertsen** [comment]
> This is odd ... as descried in #4746, I had problems using Algolia to search in the cp.
> 
> Setting searchables inside the `config/statamic/search.php` to `all` does include assets. As far as I did set searchables to explicit collections only, everything does work as expected.
> 
> This error message from my logs might help
> 
> ```shell
> [2021-11-16 20:36:16] production.ERROR: Call to undefined method Statamic\Assets\Asset::collection() {"userId":"XXXX","exception":"[object] (Error(code: 0): Call to undefined method Statamic\\Assets\\Asset::collection() at /home/forge/production.page.com/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php:31)
> ```
> 
> Somehow the ListedEntry class does try to get a collection from an Asset ... this will not work.
> 
> I couldn't dig deeper but am hoping that this will help.

**It seems that those issues are not related.**

**Comment by arthurperton** [comment]
>Statamic\Console\Commands \StaticWarm: :outputFailureLine(): Argument #1 ($exception) must be of tvpe
Pr\Http\Client\ClientExceptionInterface, GuzzleHttp\Exception\ClientException given

I am puzzled, as `GuzzleHttp\Exception\ClientException` actually inherits from a class that implements `Pr\Http\Client\ClientExceptionInterface`.

Maybe it has to do with the installed Guzzle version? Looking at my composer.lock file I am on Guzzle v7.4.1. @jonassiewertsen if this issue still happens for you, can you share the version of Guzzle you have installed please?

**Comment by juliawarnke** [comment]
@jonassiewertsen and @arthurperton. The installed Guzzle version is 6.5.5.

**Comment by jasonvarga** [comment]
Unless you are using Guzzle 6 for a specific reason, we suggest you just update to version 7 of `guzzlehttp/guzzle`.

That should resolve the issue. We'll reopen the issue if you really need Guzzle 6.

**Comment by enxoco** [comment]
I too am experiencing this same issue on a site I am migrating from Statamic 2 to Statamic 3.

![image](https://user-images.githubusercontent.com/34722899/152364753-48ca0f13-97b0-4efe-92e9-31078c20974a.png)

**Comment by jasonvarga** [comment]
Upgrade to Guzzle 7.

**Comment by enxoco** [comment]
@jasonvarga Thanks.  I was initially having an issue upgrading Guzzle because I had a custom plugin requiring guzzle6-adaptor but I got it sorted.  Upgrading Guzzle solved the issue for me.
