### ISSUE TITLE
Action with file download does not complete in control panel

### ISSUE THREAD

**Issue by wanze** [statamic/cms#4772]
### Bug description

I created an `Action` which downloads a .zip file from a given entry. The download works fine, but in the control panel, the confirmation modal is not closed and the progress bar keeps loading endlessly after the file has been downloaded.

### Possible solution

I think that there is a missing `this.$emit('completed', true);` when handling the response in case of a download in the file`vendor/statamic/cms/resources/js/components/data-list/Actions.js`:

```
...
            this.$axios.post(this.url, payload, { responseType: 'blob' }).then(response => {
                if (response.headers['content-disposition']) {
                    this.downloadFile(response);
                    this.$emit('completed', true); // This line has been added.
                }
...
```

This is a guess as I am not sure how to test this possible fix. 😅 

### How to reproduce

1) Create a custom `Action` which downloads a file, here is my implementation which creates the ZIP over a service:

```php
class Build extends Action
{
    private EntryBuilder $entryBuilder;

    protected static $title = 'Build ZIP';

    public function __construct(EntryBuilder $entryBuilder)
    {
        $this->entryBuilder = $entryBuilder;
    }

    public function visibleTo($item)
    {
        return ($item instanceof Entry);
    }

    public function visibleToBulk($items)
    {
        return false;
    }

    public function download($items, $values)
    {
        /** @var Entry $entry */
        $entry = $items[0];

        return $this->entryBuilder->buildZip($entry->id());
    }
}
```

2) Execute the action in the control panel: The download works fine, but the action is not completed in the UI.

### Versions

Statamic 3.2.22 Pro
Laravel 8.71.0
PHP 7.4.25
doublethreedigital/duplicator 2.0.1
statamic/migrator dev-master

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Your proposed solution looks like it would work. Thanks!
