### ISSUE TITLE
Command site:clear doesn't remove default assets

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/cms#4778]
### Bug description

In `config/filesystems.php` the `assets` disk remains when running `php please site:clear`, which results in the `public/assets` and `public/img`(static files) aren't pruned. If you then migrate a site using `php please migrate:site` the script will detect that the `assets` disk already exists, and instead create `assets_main` disk and migrate all assets to that.

### How to reproduce

- Have `public/assets` (and `public/img`) not empty
- Run `php please site:clear`
- Verify that the folders still have content
- Verify that the `assets` disk still exists in `config/filesystems.php`

### Versions

Statamic 3.2.21 Solo
Laravel 8.70.2
PHP 7.4.14
statamic/migrator dev-master

### Installation

Other (please explain)

### Additional details

Migration

**Comment by jackmcdade** [comment]
Not so much of an issue anymore now that we support start with an empty site. Will close this one now as it's not really worth the effort, unless someone can pitch the benefits of it that i'm missing!
