### ISSUE TITLE
Collection tag condition with umlauts in get value don't work

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#4784]
### Bug description

Found out, that umlauts in a get value, used in the collection tag condition, don't work.

### How to reproduce

Pages -> Entry: Title: Über uns (About)

`/?q=Über`

Neither of them works:
```
{{ collection:pages title:contains="{get:q}" }}
    {{ title }}
{{ /collection:pages }}
```
```
{{ collection:pages title:contains="{get}{q}{/get}" }}
    {{ title }}
{{ /collection:pages }}
```
```
{{ collection:pages title:contains="{get:q|urldecode}" }}
    {{ title }}
{{ /collection:pages }}
```
```
{{ collection:pages title:contains="{get}{q|urldecode}{/get}" }}
    {{ title }}
{{ /collection:pages }}
```

This works correctly:
```
{{ collection:pages title:contains="Über" }}
    {{ title }}
{{ /collection:pages }}
```

### Versions

Statamic 3.2.22 Pro
Laravel 8.73.0
PHP 8.0.12
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
This does seem to be related to #4405. 

The `get` variables are sanitised and as part of this sanitisation, characters like ü becomes `&uuml;`. You can see more information about why this is happening [in this comment](https://github.com/statamic/cms/issues/4405#issuecomment-1084784098). 

In the meantime, I think something like this should work:

```antlers
{{ collection:pages title:contains="{get:q | decode}" }}
```

**Comment by duncanmcclean** [comment]
This has been fixed in Statamic 5, which we're hoping to release in the next few days/weeks.
