### ISSUE TITLE
Opening the asset browser from an action modal errors

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#4785]
### Bug description

If you add an assets field to an action's field list you can't browse the files, when you click Browse the overlay does not appear this error is thrown:

![Screenshot 2021-11-19 at 15 00 18](https://user-images.githubusercontent.com/126740/142643852-05781bd9-0822-41df-9c06-5e58bcd1a4e3.png)

### How to reproduce

1. Create a new action
2. Add an assets field
3. Select the action in the CP and click Browse

### Versions

Statamic 3.2.22 Pro
Laravel 8.72.0
PHP 7.4.21
statamic/ssg 0.8.0

### Installation

Starter Kit using via CLI

**Comment by jasonvarga** [comment]
Did you give the field a container?

**Comment by jacksleight** [comment]
Yeah container is set. If you don't set a container an exception is thrown and the actions don't load at all.

The upload button works fine, file ends up in the right container, just Browse that doesn't seem to work.

**Comment by jacksleight** [comment]
Looks like this was fixed, I think in the asset replacement PR 👍
