### ISSUE TITLE
Back/forward cache loads old blueprints/contents when navigating CP in Browser

### ISSUE THREAD

**Issue by goldnead** [statamic/cms#4814]
### Bug description

I noticed this a while ago and it's not a big deal. Still, it lead to data-loss at some points when I didn't think about it:

When navigating between pages in the CP the browser cache uses the blueprints or contents that were present before the latest save. When using the browsers back/forward buttons I always need to manually reload the page to make sure that all the latest changes are displayed.
When, for instance, a blueprint was edited, then navigated to a content page and then used the back buttons to edit the same blueprint again, it would almost always use the blueprint version that the browser loaded before instead of using an updated version.

I don't even know if that "issue" can be even resolved, but I found this [article](https://web.dev/bfcache/) at web.dev that might be helpful.

### How to reproduce

Tested in latest Chrome

1. Edit a blueprint
2. Navigate to an other blueprint or entry/global
3. Edit Entry/Global
4. Use the browsers back-button to navigate back to the blueprint.
5. Notice, that the blueprint isn't at the same state as it was last edited.
6. When using the forward buttons, the same result can be seen with the edited content page in `4.`

Like I said, it's not the biggest of a deal but in certain circumstances (for example, when a replicator/bard set was edited) where you won't see the changes you made, saving without reloading the page would result in a data loss if no git-tracking was active.

Current solutions are:
- Reload when using browser navigation
- Use different tabs to edit blueprints and content entries

Would be nice though, if that wouldn't be an issue since using the browser navigation can be convenient for quick actions.

### Versions

Any Version of Statamic 3, really. Lastly tested with 3.2.17

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
We tried recreating this in a number of ways and it was found to be unclear and inconsistent. If this is still important to you, a video of the behavior would be greatly appreciated.
