### ISSUE TITLE
Case-insensitive search in unicode text doesn't work

### ISSUE THREAD

**Issue by arturslo** [statamic/cms#4826]
### Bug description

When searching for text лариса expected it to match Лариса Короткина
When searching equals text лариса expected to match Лариса

The issue is u (unicode modifier) is not used in preg_* functions.
In equality test strtolower function is used, instead of Str::lower() which uses mb_strtolower to handle unicode.

Part of this is issue was already once mentioned https://github.com/statamic/cms/pull/4284

### How to reproduce

Issue reproduced in added test cases
https://github.com/arturslo/cms/tree/issue/search-unicode

Some passing tests as proof that unaccepted pull request would fix issues with preg_* functions
https://github.com/arturslo/cms/tree/issue/search-unicode-apply-pull-request-4284

Run modified test classes
./vendor/bin/phpunit --filter CombTest
./vendor/bin/phpunit --filter QueryBuilderTest

### Versions

PHP 8.0.12
laravel/framework v8.73.2
statamic 3.2

### Installation

Other (please explain)

### Additional details

Just executed added tests on statamic/cms fork

**Comment by cfreak** [comment]
Some problem for me..

Is there already a workaround?

**Comment by htulibacki** [comment]
This bug still exists in Statamic 3.4.5.

**Comment by duncanmcclean** [comment]
Closing in favour of #4826, which looks to be the same issue.
