### ISSUE TITLE
Can't delete an asset directory that was created in code

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#4835]
### Bug description

I have a complicated form submission process, and within that process I am creating a directory like so:
`Storage::disk('submissions')->makeDirectory($submission->id());`
It's a folder for submission files.

The CP however is having trouble deleting the directory. It says 'Action completed' in green, yet the directory remains and the confirmation dialog doesn't go away. 

See screenshot - Only the 'tmp' folder should remain as I tried to delete the other one.

### Extras details

- It's a DigitalOcean space.
- I can create a folder through control panel and delete it with no problem.
- I can create a folder through DO's control panel and delete it with Statamic's CP no problem.

So I'm confused as to why CP can't delete a folder created by the makeDirectory function?

### How to reproduce

1. Create a directory within a Statamic asset container with the following code:
`Storage::disk('submissions')->makeDirectory($newDirectory);`
2. Attempt to delete it through the Control Panel.

### Versions

Statamic 3.2.24 Pro
Laravel 8.73.2
PHP 8.0.10
edalzell/blade-directives 3.5.1

### Installation

Fresh statamic/statamic site via CLI

### Additional details

![image](https://user-images.githubusercontent.com/20210934/143867951-90fdf862-4427-4231-931b-c33ce3c36c98.png)

**Comment by duncanmcclean** [comment]
Does it leave the folder but just delete the files inside it?
