### ISSUE TITLE
Multisite: Linked entries link to the wrong language

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#4839]
### Bug description

I have a really, really weird bug where strings are translated as they should, but on every single place I refer to an ID (linking to entries) the links and pulled content is from the _wrong_ language.

(see screenshots below)

Despite all ID references in the md-files are correct, referring to the correct pages in all 3 languages, all the generated URLs in my view-files are all mixed up (Norwegian pages links to German pages, English pages link to German pages, and German pages links to English pages)

The weird thing is that the third language in `sites.php`, is "dominant" – all linked entries point to the third language (German), even though it should point to the default language (Norwegian), and the same is the case when viewing the second language (English) – all linked entries point to the third language (German).

Open up sites.php, and try changing the order of the sites, setting the /en version at the bottom (now the /de version is at the bottom) and you will notice how all entries linked to from the home page (or any other page) is completely turned upside down, making English the "dominant" language.

This is by far the weirdest bug I’ve ever encountered with Statamic, and it’s apparent on two v3 multisites I have built.

First, I thought the error was caused by the migrator, but I’ve met this issue on a fresh install as well.

This is the repo:

https://github.com/axelferdinand/norwegianadventurecompany.com

### How to reproduce

I've failed to reproduce the error on a fresh install, but this is what I've got so far:

https://github.com/axelferdinand/multisite (please request access)

1. Install a fresh install of Statamic.
2. Select the `statamic/statamic` theme
3. Create a superuser.
4. Go to Pages and create a page (i.e. "Blog")
5. Create a collection (i. e. "blog").
6. Set up Scaffold view, route and other basic collection settings and set up some simple front-end views. 
7. Create a few entries in the default language.
8. Create a taxonomy (i. e. "tags").
9. Create a few terms in the default language.
10. Add a locale switcher in the layout `view`.
11. Run `php please multisite` and add to extra locales (i.e. "NO" and "DE")
12. Enable "Propagate" in all collections and set up unique routes for each language.
13. Make sure `sites.php` looks something like this:

```
'sites' => [
      'default' => [
        'name' => 'English',
        'locale' => 'en_US',
        'url' => '/',
      ],
      'no' => [
        'name' => 'Norwegian',
        'locale' => 'nb_NO',
        'url' => '/no/',
      ],
      'de' => [
        'name' => 'German',
        'locale' => 'de_DE',
        'url' => '/de/',
      ],
    ],
```

14. Make sure all entries are localized to all 3 languages:

https://user-images.githubusercontent.com/10460870/143884985-f154cef9-0d27-40a1-aa98-75ae9999ee91.mov

15. Make sure all taxonomy terms are localized to all 3 languages:

https://user-images.githubusercontent.com/10460870/143886287-3241c4ae-0389-4c65-a83b-074a34c4579b.mov

16. On the homepage, link to the entries using the Entries fieldtype.

### Logs

```shell
The logs are empty...
```

### Versions

```
Statamic 3.2.24 Pro
Laravel 8.73.2
PHP 7.4.6
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Site ### 1
I already have a support case connected to this issue, writing back and forth with **Erin Dalzell**.

This is the first site where I encountered this issue:

https://github.com/axelferdinand/norwegianadventurecompany.com

Available for testing here (100% synced with the repo):
https://nac.prototypen.no/

Here's some screenshots of the issue:

![image](https://user-images.githubusercontent.com/10460870/143873555-9c3dbbe0-6e05-435a-8057-cadd1c8fe25a.png)

![image](https://user-images.githubusercontent.com/10460870/143873584-50838084-667c-491f-90e7-195b923f27d2.png)

![image](https://user-images.githubusercontent.com/10460870/143873566-9b71821b-7d53-4389-8d0f-07b3f7d3c857.png)

### Site 2
Here's another site with a similar issue, connected to the order of the sites in `sites.php`. This time the taxonomy terms are mixed up (this is not a migrated site, but a fresh install):

https://github.com/perfecthome/spa

Available for testing here (100% synced with the repo):
https://spa.prototypen.no/

I commented the issue on Discord:
https://discord.com/channels/489818810157891584/489819906540568593/913073275691728936
https://discord.com/channels/489818810157891584/489819906540568593/913073384647168050
https://discord.com/channels/489818810157891584/489819906540568593/913073709877714944
https://discord.com/channels/489818810157891584/489819906540568593/913074073582571530
https://discord.com/channels/489818810157891584/489819906540568593/913074435014160434

**Comment by axelferdinand** [comment]
I managed to recreate the exact same issue on site 2. Try navigating here:

https://spa.prototypen.no/products

Now you are on the default (English) version of the site, but when selecting one of the listed products, you are taken to the second (Norwegian) version of the site.

Really weird, because on site 2 I've only had this issue with taxonomies until now, but now it occurs on pages with collections as well.

Here's the repo:
https://github.com/perfecthome/spa

**Comment by axelferdinand** [comment]
Also, on site 2, if you navigate to /ingredients, you will see all the taxonomies (ingredients) listed:

https://spa.prototypen.no/ingredients

Notice how it starts with "Cucumber extract", which starts with the letter C. This is first in the list because the Norwegian version of this word is "Agurkekstrakt", which starts with the letter A. 

On the default version of the site (English) it should start with "Aloe vera gel" – not "Cucumber extract". But it starts with "Cucumber extract" simply because it's the first alphabetical term in the second version of the site (Norwegian).

This seems to me highly related to the issue.

**Comment by axelferdinand** [comment]
For the record – renaming the Norwegian version of the term, changes the order in the English version. Really weird.

**Comment by axelferdinand** [comment]
Any progress on this? :)

**Comment by axelferdinand** [comment]
I discovered a related issue connected to locales:

If you list some entries on the default language page, and those entries aren't available in _all_ the other languages (due to the entries not being created in the other languages yet), they wont display at all. We encountered this on site 2.

**Comment by jasonvarga** [comment]
I've found the cause of this. Working on a solution!

**Comment by axelferdinand** [comment]
THAT IS THE BEST NEWS I'VE GOTTEN IN WEEKS 🤩

**Comment by axelferdinand** [comment]
Will this fix be part of the next update? If so, when is the next update rolled out?

**Comment by jasonvarga** [comment]
Yes, it'll be out today.
