### ISSUE TITLE
Localized globals can't have empty values

### ISSUE THREAD

**Issue by aerni** [statamic/cms#4841]
### Bug description

It's currently not possible to empty a field of a localized global. After reload, the field ends up being synced with the origin again. This is the same issue that was fixed for entries here: https://github.com/statamic/cms/pull/3531

I'm happy to open a PR for this.

### How to reproduce

- Create a multisite
- Create a global, activate both sites, and set one site as the origin of the other.
- Add a value to a regular text field
- Delete the value in the localized global
- Reload, and the value will be synced with the origin again

### Versions

Statamic 3.2.24 Pro
Laravel 8.73.2
PHP 8.0.13

### Installation

Fresh statamic/statamic site via CLI

### Additional details

https://user-images.githubusercontent.com/23167701/144008312-4984033c-ed99-4036-9c82-90aa1d05ab8c.mov

**Comment by jasonvarga** [comment]
Fixed in #4884
