### ISSUE TITLE
Root page is missing icon when max_depth === 1 on a structured collection.

### ISSUE THREAD

**Issue by jelleroorda** [statamic/cms#4850]
### Bug description

When I set my pages collection to be structured, and to be expecting a root page, it does not show the first entry as the root.

**Issue 1:** It does not show the root page icon for the root page.
**Issue 2:** It renders the root slug as `home` (which is what's set on the entry, but it should be `/`).

I'm putting both in a single issue since they can likely be fixed in one go.

### How to reproduce

Edit the pages collection and make it structured like this:

![Schermafbeelding 2021-12-02 om 11 14 00](https://user-images.githubusercontent.com/9193686/144402277-b14a14d1-decf-491c-bb8b-137f49bcf316.png)

### Versions

Statamic 3.2.24 Pro
Laravel 8.74.0
PHP 8.0.6
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Additional details

**See here: `max_depth === 2`**
![Schermafbeelding 2021-12-02 om 11 09 12](https://user-images.githubusercontent.com/9193686/144402571-035f2c89-8737-4bfc-b26f-6b225b223ad6.png)

**And here `max_depth === 1`**
![Schermafbeelding 2021-12-02 om 11 07 07](https://user-images.githubusercontent.com/9193686/144402651-6fb749f8-a318-4664-b78a-fc8f5350d704.png)

**Note, it's the same when 'reordering' the collection (click the Reorder button)**
![Schermafbeelding 2021-12-02 om 11 31 46](https://user-images.githubusercontent.com/9193686/144405464-04a8c1c9-1891-4a74-ad8d-134f6b545bbc.png)

**Comment by jelleroorda** [comment]
Yes, so the functionality is working correctly at the moment in the frontend. With “the functionality” I mean the first entry is treated as the root (= the homepage).

So what I experience as not working is:
- The fact that it is not being displayed as the root (so missing the icon)
- The fact that the slug shown is `home`, even though the slug for the root should be `/`

**Comment by jasonvarga** [comment]
I'm leaving this closed as I don't see it as high priority. The slug of the root showing as the actual slug is still literally the slug. e.g. if you open the entry edit page, you'd see that value in the slug field. The lack of a home icon isn't a big deal. It's something you get in the tree, not a listing.

If this is important to you feel free to address the feedback in the PR. Thanks for your understanding.
