### ISSUE TITLE
Search tag: `supplement_data="false"` throws an exception in combination with pagination

### ISSUE THREAD

**Issue by jakubjo** [statamic/cms#4861]
### Bug description

When using `supplemend_data="false"` in combination with `paginate="true"` and a limit value (eg `limit="10"`) an exception is thrown:

`Call to a member function setSupplement() on array.`

### How to reproduce

Just use the regular search tags as mentioned in the docs:

```
{{ search:results supplement_data="false" as="results" limit="10" paginate="true" }}
  ...
{{ /search:results }}
```

### Versions

Statamic 3.2.24 Pro
Laravel 8.74.0
PHP 8.0.12
aryehraber/statamic-font-awesome 2.2.0
spatie/statamic-responsive-images 2.8.5

### Installation

Fresh statamic/statamic site via CLI

**Comment by arthurperton** [comment]
Hi @jakubjo, thanks for your report. I'm not able to reproduce your bug though. I'm testing on v3.2.28.

We might be able to help out with some additional information:

* Can you check if the problem still persists in the latest version?
* If so can you post the entire error message here, preferably with the stack trace and all? That might help with finding the related code.
* Can you provide the antlers code you used for the search form and the results, this might help in reproducing the error.
* Does it matter what search term you enter?
