### ISSUE TITLE
Password protection messages cannot be localized

### ISSUE THREAD

**Issue by klickreflex** [statamic/cms#4868]
### Bug description

When using `protect: password` on a non-english site there is no way to localize the labels of the password form. Most strings can be overridden by hard coding them into an overridden `password.antlers.html`, but the `Incorrect password.` message can't be changed at all as it's hardwired in the controller.

Affected files:
- https://github.com/statamic/cms/blob/3.2/src/Auth/Protect/Protectors/Password/Controller.php#L23
- https://github.com/statamic/cms/blob/3.2/src/Auth/Protect/Protectors/Password/Controller.php#L29
- https://github.com/statamic/cms/blob/3.2/resources/views/auth/protect/password.antlers.html#L24

### How to reproduce

- use another language but english 
- protect a page using `protect: password`
- try to localize the password entry form and error message

### Versions

Statamic 3.2.24 Pro
Laravel 8.50.0
PHP 8.0.13
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Good find, thanks.
