### ISSUE TITLE
Can't add `title` to a fieldset and use fieldset prefixes at the same time

### ISSUE THREAD

**Issue by JayGeorge** [statamic/cms#4869]
### Bug description

I discovered that when I use `title` as part of a fieldset it has a strange side effect where I can't use multiple of the same fieldsets, even when I prefix them.

[Watch this 3 min video](https://drive.google.com/file/d/111nCpj8lyLMKZ_JY50nq2fs__3NYLZUK/view?usp=sharing) that better explains/shows the problem.

### How to reproduce

[Watch this 3 min video](https://drive.google.com/file/d/111nCpj8lyLMKZ_JY50nq2fs__3NYLZUK/view?usp=sharing) that shows how to reproduce.

## Set up tests

1. Create a fieldset and call it something like 'Test Fieldset with Title'
  1. Add a text field to this fieldset and call it 'Title'
2. Create another fieldset and call it what you like e.g. 'Foo'

## Build a blueprint

1. Create a new blueprint
2. Delete the default title field
3. Link to the fieldset 'Test Fieldset with Title' instead
4. Add another field, linking to the fieldset 'Foo'
5. Add another instance of the fieldset 'Foo', this time prefixing it with `test_`

## Save the Blueprint and see how Statamic gets confused

1. Save the blueprint you've just created
2. See how Statamic merges the second `Foo` fieldset into the first

### Versions

Statamic 3.2.24 Pro
Laravel 8.75.0
PHP 8.0.9
jonassiewertsen/statamic-live-search 1.2.0
jonassiewertsen/statamic-livewire 2.7.0
takepart-media/statamic-oreos 1.1.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by rarespopescu** [comment]
+1 for this, it would be amazing to have a solution in consideration soon. I am experiencing the same issue, with Statamic 3.4.4.

Whenever a blueprint contains the **title** field as part of an imported fieldset, N amount of prefixed fieldsets are merged as one.
