### ISSUE TITLE
Entry or link field return 404 error on attaching existing entry

### ISSUE THREAD

**Issue by FR6** [statamic/cms#4875]
### Bug description

When trying to attach an existing entry to a Link or Entry fields produce a 404 error:

![image](https://user-images.githubusercontent.com/286685/145334192-c0336836-4d0b-437b-ac08-d102d6e78468.png)

Weirdly this route indeed doesn't seem to exist for a POST request:

![image](https://user-images.githubusercontent.com/286685/145334596-5329bcaf-5666-41ff-93e9-2cef79c1c7bb.png)

Pretty sure the error is related to my setup since it use to work properly.

Any idea on whats can be?

### How to reproduce

- Create Entries or Link field
- Create content
- Try linking existing item

### Versions

Statamic 3.2.24 Pro
Laravel 8.61.0
PHP 7.4.3
aryehraber/statamic-font-awesome 2.2.0
joetannenbaum/antlers-stack-tags 0.1.0
jonassiewertsen/statamic-livewire 2.7.0

### Installation

Existing Laravel app

**Comment by jelleroorda** [comment]
Have you tried: `php artisan route:clear`?

**Comment by FR6** [comment]
@jelleroorda Yes I just tried again and keep having the same 404 error.
Any other idea?
