### ISSUE TITLE
ErrorException when grouping by blueprint

### ISSUE THREAD

**Issue by paulhaem** [statamic/cms#4898]
### Bug description

When using `{{ entries group_by="blueprint" }}` on a collection it outputs `ErrorException: array_key_exists()`. However when going through the dump or using `group_by="id"` `blueprint` is available as a string at the item level.

### How to reproduce

1. Create a collection
2. Add two blueprints to the collection
3. Update the template:
```
{{ collection:<insert collection name> as="entries" }}
  {{ entries group_by="blueprint" }}
    {{ groups }}
      {{ group }}
      {{ items }}
        {{ title }}
      {{ /items }}
    {{ /groups }}
  {{ /entries }}
{{ /collection:blog }}
```

### Logs

```shell
[previous exception] [object] (ErrorException(code: 0): array_key_exists(): The first argument should be either a string or an integer at C:\\laragon\\www\\statamic-demo\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php:444)
```

### Versions

Statamic 3.2.26 Pro
Laravel 8.75.0
PHP 7.4.19
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by MacTwister** [comment]
I'm uncertain if related, so thought to share, I had similar error when trying `group_by` with "select" fieldtype. 

Exception: `array_key_exists(): Argument #1 ($key) must be a valid array offset type `


So, what worked for me was to use the `fieldtype:label` property, like below, which worked out for me in this case.
```
{{ entries group_by="group_type:label" }}
```


Though now, `{{ group }}` is always the label and I can't get the selected option's "key" anymore, for stuff like `<div id="group-{{ group_type }}">`.

**Comment by duncanmcclean** [comment]
You might have already tried this and it didn't work but what happens if you do this...? 

`{{ entries group_by="blueprint:handle" }}`

**Comment by paulhaem** [comment]
Thanks for the suggestion but I already tried that one. When using `group_by="blueprint:handle"` the first item of `entries` won't be grouped with the other entries, no mather which one is the first entry. I have 6 blueprints but there are 7 groups. When using `{{ groups | dump }}` it shows the first group does not have `key` or `group` set. This empty group always has but one entry. All other entries are grouped up accordingly.
