### ISSUE TITLE
Database users role & permission problem

### ISSUE THREAD

**Issue by ashkesarmaa** [statamic/cms#4920]
### Bug description

Hi everyone,

I stored my users into database everything seems fine but there is a problem with permission:

I created Editor role and i defined permissions below for it :
editor:
title: Editor
permissions:
- 'access cp'
- 'view blog entries'
- 'edit blog entries'
- 'create blog entries'
- 'delete blog entries'
- 'view page entries'
- 'edit page entries'
- 'create page entries'
- 'delete page entries'

As you can see This role has an access to do CRUD on page and blog collection but when i assign this role to a user and login with that user there is no create entry button :( i checked the code and i find out that this line

:can-create="@can('create', ['statamic\Contracts\Entries\Entry', $collection]) true @else false @endcan" in show.blade.php return false for this user but it should return true so do you have any idea? thanks in advance

My Statamic version is 3.2.25

### How to reproduce

install statamic in fresh laravel project and store users in database insted of file create role & permission and then see if you have create entry button or not

### Versions

3.2.25

### Installation

Existing Laravel app

**Comment by duncanmcclean** [comment]
I can't seem to reproduce this issue using the latest version of Statamic. I can see the "Create Entry" button as expected & creating/editing entries also works.

I'm going to close this issue now but if you're still having issues, leave a comment and we can re-open the issue. Thanks!
