### ISSUE TITLE
*Section* fields don't output `instructions` when used in a Front-End Form

### ISSUE THREAD

**Issue by sjclark** [statamic/cms#4921]
### Bug description

When using **Section Fields** in a form the `instructions` field is **not exposed in the front-end data** - despite `instructions_position` even being available.

![Screen Shot 2021-12-17 at 2 11 28 pm](https://user-images.githubusercontent.com/4531017/146483300-ce120d7b-e89f-4bc6-87e7-1805b58e2c1c.png)

Have set this up as per instructions here:
https://statamic.dev/forms#the-blueprint
ie. `Statamic\Fieldtypes\Section::makeSelectableInForms();`

### How to reproduce

Add a section field to a front-end form.
Enter a value in the Instructions field.
Find it not output on the front-end.

### Versions

Statamic 3.2.26 Pro
Laravel 8.75.0
PHP 8.0.13
aryehraber/statamic-captcha 1.7.0

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Would you be able to share the Antlers code you're using. 

I seem to be getting the `instructions` through just fine but I wonder if I might be doing it differently from you.

**Comment by sjclark** [comment]
huh! curious!

```html
...
{{else}}
<div class="flex flex-col space-y-2 space-y-1 theme-field 
        {{ width == '25' ?= 'md:col-span-1' }}
        {{ width == '33' ?= 'md:col-span-2' }}
        {{ width == '50' ?= 'md:col-span-3' }}
        {{ width == '66' ?= 'md:col-span-4' }}
        {{ width == '100' ?= 'md:col-span-6' }}">
    <label class="font-bold" for="{{ handle }}">
        {{ trans :key="display" }}
        {{ if validate | contains:required }}
        <sup class="font-normal text-red-500" aria-label="Required">*</sup>
        {{ /if }}
        {{ if instructions }}
        <div class="text-sm font-normal prose">
        {{ instructions | markdown }}
        </div>
        {{ /if }}
        {{ if error }}
        <p class="text-sm font-normal text-red-500">{{ error }}</p>
        {{ /if }}
    </label>
    {{ field }}
</div>
{{ /if }}
{{ /fields }}
```

**Comment by sjclark** [comment]
Honestly have no idea why this wasn't working before - reverted back to the exact same code I had previously and now works fine. 🤷  Either way thanks so much @duncanmcclean - got me going again! 🔥

**Comment by duncanmcclean** [comment]
Haha no worries!
