### ISSUE TITLE
Asset container order is inconsistent

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#4939]
### Bug description

The asset container order is inconsistent. In the side menu it's ordered alphabetically which is fine, however the Vue tabs are ordered in another way. It looks random.

<img width="887" alt="Screenshot 2021-12-20 at 14 51 23" src="https://user-images.githubusercontent.com/69107412/146777700-1401bd02-ea54-41d0-99a7-e1ddcee903a3.png">

### How to reproduce

Add some asset containers

### Versions

Statamic 3.2.27 Pro
Laravel 8.76.2
PHP 7.4.25
No addons installed

### Installation

Starter Kit using via CLI

**Comment by sjclark** [comment]
It's ascending ordering by `s` character count in the name 🤷‍♂️

**Comment by jasonvarga** [comment]
I think it sorts by the velocity of the mouse button click when you create the container.

**Comment by robdekort** [comment]
Aaaahhh. That makes sense. Feel free to close this issue 🤣

**Comment by jasonvarga** [comment]
@robdekort Just to confirm... Can you provide the names of the asset container yaml files, and what their `title` is inside?
