### ISSUE TITLE
Deleting or renaming the assets container handler breaks user/create and user/edit

### ISSUE THREAD

**Issue by AdD959** [statamic/cms#4951]
### Bug description

Deleting or renaming the default assets container so that there is no longer an assets.yaml file results in users create and edit pages to break.

### How to reproduce

In my case, I created a new assets container (with a different handle) in CP and then deleted the original. Then I tried to create a new user and the page errored.

### Versions

v3

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Can you share the YAML of your user blueprint (will be found in `resources/blueprints/users`)?

**Comment by AdD959** [comment]
I could, but this is a fresh instance of the site I'm testing on (v3.2.26). The only change I've made is setting the editions file to pro => true

**Comment by duncanmcclean** [comment]
I'm asking because the default user blueprint has a reference to the `assets` container on the Assets field, see here: https://github.com/statamic/statamic/blob/master/resources/blueprints/user.yaml#L29

If you change the container to the handle of your new asset container, you'll be able to create users fine.

**Comment by AdD959** [comment]
yeah this is a workaround. I created this as an issue just because I don't believe it should be possible to break these pages as a CP user

**Comment by jasonvarga** [comment]
Users with permission to rename important stuff like container handles will have the ability to break things.

If you change a handle, you'll have to update references to it.
e.g., if you rename a collection, you'll have to change `{{ collection:oldhandle }}` to `{{ collection:newhandle }}` in templates, etc.
