### ISSUE TITLE
Cannot edit the asset container handle

### ISSUE THREAD

**Issue by AdD959** [statamic/cms#4952]
### Bug description

Via the CP, users (at least super admins) cannot change the name of the asset container handle and it must be done manually by changing the file name from assets.yaml

### How to reproduce

as in bug description. Try changing the handle name via cp

### Versions

v3.2.26

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
I believe this may be intentional so developers don't expect Statamic to automatically update references in blueprints etc (as that needs to be done manually).

**Comment by AdD959** [comment]
ok, I guess it might be worth making the field uneditable in cp
