### ISSUE TITLE
User activation link is broken

### ISSUE THREAD

**Issue by AdD959** [statamic/cms#4953]
### Bug description

At least locally, when manually activating a new user (not via email), the provided link does activate successfully, it just doesn't take the user the CP, but a broken page

### How to reproduce

create user in cp without email activation, use activation url. fill out details to activate. This then redirects to a broken page

### Versions

v3.2.26

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
What does the activation URL look like? Does it have the right domain name?

**Comment by AdD959** [comment]
/cp%20Username:%20test@test.com

domain is correct

**Comment by jasonvarga** [comment]
Seems to work fine here, unless I'm misunderstanding what you're doing. Could you provide more details? Maybe a video of the workflow?

**Comment by jackmcdade** [comment]
Haven't heard back in 3 months. Feel free to reopen with details if you or anyone can recreate!

**Comment by yabdab** [comment]
Maybe this is happening when you are already logged in as Super Admin? 

Try using the activation link in Incognito mode?
