### ISSUE TITLE
Error when linking to entry on a Bard field

### ISSUE THREAD

**Issue by zehfred** [statamic/cms#4961]
### Bug description

When editing an entry in a Bard field, linking to an existing entry throws the following error:

Argument 1 passed to Statamic|Markdown\Parser:parse() must be of the type string, array given, called in
/vendor/statamic/cms/src/Markdown/Manager.php on line 15

### How to reproduce

Add text to a Bard field, click to create link and select "Entry". Clicking on the folder icon results in error.

This only happens when "Link Collections" doesn't have any specified. If a collection is added to the field, no error occurs.

### Versions

Statamic 3.2.28 Pro
Laravel 8.77.1
PHP 7.4.27

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
You have a field in two collections that are named the same, but use different fieldtypes.

e.g. a `content` field in one collection that's `markdown` and `bard` in another.

You should make them consistent.
