### ISSUE TITLE
`{{ date }}` doesn't work correctly on live preview

### ISSUE THREAD

**Issue by tao** [statamic/cms#4965]
### Bug description

In the live preview, using `{{ date }}` only returns the plain timestamp:

```
2017-12-01 00:00:00
```

While the website returns the corrrect date:

```
December 1st, 2017
```

I was testing this a bit and if you use the date modifier it does return the translated date correctly:

```
{{ date format_localized="%B %e, %Y" }}
=> December 1, 2017
```

However, this quick fix doesn't work for us because we want to date ordinals `st`, `th`, etc.

I've also noticed that sometimes the static site generator sometimes renders the dates as plain timestamps, so it might be a larger issue.

### How to reproduce

Try using `{{ date }}` on live preview. The date field is included in a partial if that makes any difference.

![Screenshot 2021-12-24 at 11 08 22](https://user-images.githubusercontent.com/1446331/147338358-4ea49ae5-ee03-4c0b-a36c-4ab57ac3565f.png)

### Versions

Statamic 3.2.26 Pro
Laravel 8.76.1
PHP 8.0.6
statamic/ssg 0.9.0

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Confirmed, just ran into this one myself.

**Comment by jackmcdade** [comment]
Is this still an issue in 3.3?

**Comment by duncanmcclean** [comment]
Doesn't look like it is..

<img width="821" alt="image" src="https://user-images.githubusercontent.com/19637309/158661857-b096b05e-8720-4e09-977e-96ed4d3b0ff6.png">
