### ISSUE TITLE
Explode modifier doesn't behave as expected on tag pairs

### ISSUE THREAD

**Issue by montemartin** [statamic/cms#4979]
### Bug description

When using the explode modifier on a tag the closing tag requires the modifier be repeated.

### How to reproduce

```
# string: testing, explode, modifiers
{{ string | explode:, }} 
{{ value }} 
{{ /string | explode:, }}
``` 
works, but I expected the syntax to be
```
{{ string | explode:, }} 
{{ value }} 
{{ /string }}
``` 

The explode modifier also doesn't work as a pair with parameter style syntax, making it difficult to work with explode on space separated strings. 
This does not work:
```
{{ string explode=" " }}
{{ value }}
{{ /string explode=" " }}
```

### Versions

Statamic 3.2.24 Solo
Laravel 8.74.0
PHP 8.0.12
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Additional details

There was some brief discussion and testing relating to this on [Discord](https://discord.com/channels/489818810157891584/489819906540568593/925155464008851516)

**Comment by jasonvarga** [comment]
Use parameter style but just on the opening tag.

**Comment by edalzell** [comment]
> Use parameter style but just on the opening tag.

Ya we tried that too, didn’t work.

**Comment by edalzell** [comment]
It’s weird, when trying to break on space, we couldn’t get it to work.

**Comment by jackmcdade** [comment]
In the new parser do `{{ string | explode(',') }}` or `{{ string | explode(' ') }}` and you'll be good to go!
