### ISSUE TITLE
Using closures in search.php config file for transformations conflicts with advice on config caching.

### ISSUE THREAD

**Issue by sunscreem** [statamic/cms#4992]
### Bug description

At present the docs suggest [using closures](https://statamic.dev/search#transforming-fields) for transformers when setting up a search. 

I can't see any other way of manipulating the data being sent to a 3rd party service such as Alogia.

This prevents the use of `php artisan config:cache` or `php artisan optimize` which is recommend by Laravel [in their docs](https://laravel.com/docs/8.x/deployment#optimizing-configuration-loading).

### How to reproduce

Add a closure to a config file. Run `php artisan config:cache`.

### Versions

Statamic 3.2.28 Pro
Laravel 8.77.1
PHP 8.0.10
doublethreedigital/duplicator 2.0.1
jonassiewertsen/statamic-external-link 1.4.1
legrisch/statamic-graphql-thumbnails 0.3.0
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 1.9.0

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Config caching and closures in config files can't be combined.

**Comment by sunscreem** [comment]
@duncanmcclean Maybe worth me submitting a "hot tip" for the docs instead of a bug report?

**Comment by duncanmcclean** [comment]
Yeah, it's probably worth adding a little note to the docs. 👍

**Comment by jasonvarga** [comment]
You could also open an issue on statamic/ideas asking for an alternative solution to the closures, if you want. I'm sure something could be worked out.
