### ISSUE TITLE
v3.2.28 breaks replicators

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#4996]
### Bug description

I have a slightly complicated system of replicators for my 'Page' blueprint. Basically it is like this:

- Sections (replicator of sections)
  - Full Section (replicator of blocks)
  - Split Section (two replicators of blocks)

This was all working fine until I updated to 3.2.28, and I have confirmed that rolling back to 3.2.27 fixes the problem.

The problem is a total freeze / crash when clicking the 'Add Set' button on one of my Split Sections (nested replicator).

### How to reproduce

Set up a nested replicator structure that uses fieldsets.

### Versions

Statamic 3.2.28 Solo
Laravel 8.77.1
PHP 7.4.19
edalzell/blade-directives 3.5.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by arthurperton** [comment]
Looking at the changelog I only found one fix that involved a replicator, PR #4903. It fixed another bug but may be causing yours I think. The good thing is that this also helped me find the cause of another bug, see issue #4997.

The challenge now is to solve this issue (#4996) and #4997 without breaking #4774 again 😄

**Comment by stuartcusackie** [comment]
Excellent detective work sir. Let me know if I can provide any additional useful information. I'm afraid I won't be able to help you much more than that because I've no idea how all of this works. :)

**Comment by jasonvarga** [comment]
@jesseleite
