### ISSUE TITLE
Hidden Fields in Form Submission are invisible

### ISSUE THREAD

**Issue by fjahn** [statamic/cms#5018]
### Bug description

Hidden fields are invisible when viewing form submissions. Only the label of the field is visible, while the actual input is missing, as you can see in this screenshot:

<img width="445" alt="grafik" src="https://user-images.githubusercontent.com/74260729/148233291-8b58512e-3dc0-417e-852b-e9d595f8f7fe.png">

The first field is a regular, visible field, while the second field is a hidden one.

In my opinion, hidden fields should be visible when viewing form submission, because they most likely contain meta information about the form that CP users might want to see.

### How to reproduce

- Set up a simple form X with at least one field that is hidden.
- Set up a simple test page that renders the form X.
- Submit the form.
- In the control panel, navigate to form X.
- Open the latest submission.
- **The field label is shown, but actual field along with its content is not shown.**

### Versions

Statamic 3.2.29 Solo
Laravel 8.78.0
PHP 8.1.1
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
How are you populating the hidden field value in the front-end form? Are you using the `fields` loop? Or are you manually doing `<input type="hidden" name="hiddenfield" value="something" />`?

If you're doing it manually, just make it a `text` field.

**Comment by fjahn** [comment]
I was doing it using the `fields` loop. I fixed the issue for now by using an `if` to check for the handle that I want to be hidden within the loop.

The bug does not really block me from solving my issue, but I hope you agree that it would be better if I could just use the hidden fieldtype for the field.

**Comment by jasonvarga** [comment]
I do agree. Although it's introducing a whole new level of complexity in blueprints. You want to be able to have a field that is one thing on the front-end but another inside the CP. It's only really a thing for the hidden fieldtype. 🤔 

I'm still curious how you were populating the value of the hidden field if you were using the `fields` loop.

**Comment by fjahn** [comment]
I understand, there is currently no way of customizing how the field looks just on the form submissions page.

> I'm still curious how you were populating the value of the hidden field if you were using the fields loop.

The field is populated on the client side using javascript.

**Comment by jasonvarga** [comment]
If you're writing JS to populate it, then another line to make it hidden can't hurt. 😄

**Comment by jasonvarga** [comment]
I'm gonna close this down. Another option could be to make a custom fieldtype that inherits from `Hidden`, but has a `protected $component = 'text';` in it so it renders in the CP as text.

```php
class SortaHidden extends Hidden
{
  protected $component = 'text';
}
```

```yml
fields:
  -
    handle: myfield
    field:
      type: sorta_hidden
```

**Comment by arcs-** [comment]
I don't see this as closed; this is still an issue, even if you argue that a field can't have different states in the frontend and backend, then the same should go for its label. A label without a field is bad.

I'd say we could check if the type is hidden and set the type to text within the forms view or at least display a text that says the field is hidden.
