### ISSUE TITLE
max_items allows negative values

### ISSUE THREAD

**Issue by zehfred** [statamic/cms#5022]
### Bug description

I placed a negative value on a `max_items` field and Statamic accepted it. Should throw an error as it shouldn't be possible to add negative items.

![Schermafbeelding_2022-01-05_om_11 20 59](https://user-images.githubusercontent.com/1191865/148362709-bdeeedce-1959-4b18-b33c-2d00137d4ebc.png)

### How to reproduce

Add a negative value to a `max_items` field.

### Versions

Statamic 3.2.29 Pro
Laravel 8.77.1
PHP 8.1.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by edalzell** [comment]
This one is harder than it seems, to implement. Need to add `min`/`max` to the numeric inputs only, then have a config for them.
