### ISSUE TITLE
Dragging fields on top of each other doesn't move them and throws error

### ISSUE THREAD

**Issue by zehfred** [statamic/cms#5023]
### Bug description

Was reordering fields in a Fieldset and they did not move unless I dragged them to the left. Instead they dropped on each other and threw this error:

<img width="965" alt="Screenshot 2021-12-24 at 12 02 51" src="https://user-images.githubusercontent.com/1191865/148365475-84097a65-adf5-48fd-8435-549d690f934a.png">
<img width="1552" alt="Screenshot 2021-12-24 at 12 04 34" src="https://user-images.githubusercontent.com/1191865/148365484-aa4fa57a-622d-4b84-bf4c-63a6a835130f.png">

### How to reproduce

Drag and drop fields on top of each other in the Fieldsets page.

### Versions

Statamic 3.2.29 Pro
Laravel 8.77.1
PHP 8.1.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by arthurperton** [comment]
Thanks for your report and the screenshots. Haven't been able to reproduce this though in Chrome / Safari / Firefox. What browser are you on? It also might help if you can share the fieldset yaml here.

**Comment by byron-roots** [comment]
I've had this happen a few times. When it has happened it's been after adding a bard field. I've only tried this in chrome as well
