### ISSUE TITLE
Collection listing breaks with too many fields

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#5034]
### Bug description

Reproduced on a clean Statamic instance:

![Bildschirmfoto 2022-01-07 um 13 18 12](https://user-images.githubusercontent.com/38906163/148543116-20b912f6-fc99-4790-bfe2-d84aef147427.png)

This is an example on even larger collections, if scrolling to the right the menu breaks as well:
![Wide lists](https://user-images.githubusercontent.com/38906163/148543206-2fe499d4-6975-4820-98de-2f97ab14aab6.png)

### How to reproduce

1. Create a Collection
2. Add enough fields, so the titles combined will be longer than the viewport width.

### Versions

Statamic 3.2.29

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Surely you don't want all those fields in the listing. You can control whether they're shown on the blueprint level by setting `listable` appropriately.

However, we should probably make the table scrollable horizontally if it's too wide.

**Comment by jonassiewertsen** [comment]
A horizontally scrollable list would be great!

What you see is not the default as set by the `listable` property. This is the result from editors customizing their listing.

**Comment by jasonvarga** [comment]
You sure showed me! Apparently people _do_ want that many fields.

**Comment by jonassiewertsen** [comment]
Getting this right involves a few things I guess: Not moving the filters, always showing the checkboxes for selecting but making the other fields scrollable.

@jackmcdade would you accept a PR, giving the container a `overflow-x-scroll`?
This is far away from the perfect solution, but it would stop destroying the list view.

**Comment by jackmcdade** [comment]
Fixed by https://github.com/statamic/cms/pull/7589
