### ISSUE TITLE
Nested lists displaying incorrectly

### ISSUE THREAD

**Issue by benfreke** [statamic/cms#5040]
### Bug description

I've been writing some step by step guides for a blog article on [XDebug](https://benfreke.gitlab.io/blog/phpstorm-docker-xdebug/#cli).

But using a nested list, as I like to use to describe bugs, the nested list has extra space that shouldn't be there.

I've done some debugging, and this is related to the regular expression used correctly matching on a newline character, but matching in a way that results in sub standard output. You can see the output in the link I provided above.

### How to reproduce

A minimist article that should display the error is the following markdown content.

```
- First
    - Second
- Third
```

I have this in my repository here: https://gitlab.com/benfreke/blog/-/blob/main/content/collections/articles/2022-01-08.test.md

### Versions

Statamic 3.2.30 Solo
Laravel 8.78.1
PHP 8.0.7
jedamzik/statamic-toc 1.1.0
mitydigital/statamic-rss-feed 1.4.2
simonridley/tracking-code-manager dev-master
statamic/ssg dev-master

### Installation

Other (please explain)

### Additional details

I can't remember how I installed, but it was one of the starter its on the CLI sorry. 

This is all running via Docker locally, using my own custom images based on Alpine, but as this is using standard PHP functions I don't believe that will impact the output.

I'm pretty confident that replacing the `\s` with `[[:blank:]]` will work for my use case (it did in my limited testing), but given there are only 2 tests for the `widont` function, and this would be a breaking change, I wanted to see if it is worthwhile submitting a PR for this? Potentially there is another workaround available for my use case? 

`\s` matches spaces, tabs and newline characters.
`[[:blank:]` matches spaces and tabs only.

**Comment by jasonvarga** [comment]
Is this bug about the widont modifier? You mention changing a regex. Where?

**Comment by benfreke** [comment]
Sorry @jasonvarga , I forgot to mention the actual line. The widon method is in this file, src/Support/Str.php:168, so \Statamic\Support\Str::widont()

Specifically, it is step 2 where the regex is converting the `\n` to a `&nbsp;`. 

Changing the `\s` on line 181 to be a `::blank::` stops this behaviour on a nested list. 

I can submit a PR showing it if that's easier to explain than the above?

**Comment by jasonvarga** [comment]
Cool yeah we'll accept a PR for sure.

What threw me off is that nothing about the issue mentioned widont except where you explained replacing a line of code.

Does the problem happen if you don't use widont?
