### ISSUE TITLE
[Potential Epic] Support for Laravel 9

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#5042]
### Bug description

Reviewing the [upgrade guide](https://laravel.com/docs/master/upgrade) I see a few possible challenges, especially factoring in backwards compatibility. We'll need to break out a full list of todos after running our test suite on L9. We can close this issue after we build that list.

### [Flysystem 1.x -> 3.x](https://laravel.com/docs/master/upgrade#flysystem-3)

There are a number of different behaviors and defaults that might need adjusting. Supporting both it and 1.x in the same codebase might be challenging. A quick search shows we're _probably_ not relying on most of the stuff that has been removed, but we'll see.

### [Swiftmailer -> Symfony Mailer](https://laravel.com/docs/master/upgrade#symfony-mailer)

I don't _think_ we directly interact with any of the Swiftmailer classes, and many of the renamed methods were undocumented aliases so we might be safe here. But since it's a big package swap, it _could_ present issues.

### [The Lang Directory](https://laravel.com/docs/master/upgrade#the-lang-directory)

L9 moves the `lang/` dir outside of resources and into root. We'll need to replace hardcoded references to the path `/resources/lang` with `app()->langPath()`.

## References

https://laravel.com/docs/master/upgrade
https://laravel-news.com/laravel-9

### How to reproduce

...

### Versions

...

### Installation

Other (please explain)

### Additional details

...

**Comment by jasonvarga** [comment]
We're also waiting for [testbench](https://github.com/orchestral/testbench-core/tree/647d0db9818ab4b63a4ea15d00f90c9a71043a1f) to support Laravel 9.

**Comment by Konafets** [comment]
> L9 moves the lang/ dir outside of resources and into root. We'll need to replace hardcoded references to the path /resources/lang with app()->langPath().

The path to the `lang/` dir is hardcoded in two ways:

1. Referring to the language files inside the package e.g. Statamic.
   This is done by `"{$this->root}/resources/lang"` which returns `/Users/$user/Sites/statamic/docs/vendor/statamic/cms/src/Providers/../../resources/lang`
   
2. Referring to the published language files in the app. This is done by `resource_path('lang/vendor/statamic')` and returns `/Users/$user/Sites/statamic/docs/resources/lang`. This is used for publishing the language files.

The method `app()->langPath()` also returns the path to the language directory of the application, but not to the language files of the package.

To me it looks like a simple replacement of  `/resources/lang` by `app()->langPath()` will not fix the issue. For my understanding there are two options:

1. Keep the language files of the package in `resources/lang` and just replace the hardcoded folder where to publish (`resource_path('lang/vendor/statamic')`) by `app()->langPath()`. This will ensure the backward compatibility and can be implemented right now.
2. Move the files of the package as well to the new location and change the hardcoded path strings to point to the new location _and_ all from 1.

**Comment by jasonvarga** [comment]
I don't think the location of the lang files in our package matter. It's just the location of them in the user's application that matters.

**Comment by Konafets** [comment]
According to Laravel's upgrade guide, the moved to Flysystem 3 **not** 2.

**Comment by duncanmcclean** [comment]
> According to Laravel's upgrade guide, they moved to Flysystem 3 **not** 2.

I believe that's a pretty new thing - within the last week or so - there's not that much of a difference between 2 and 3. I think they just needed a way to fix a few things & make breaking changes along the way. 😅

**Comment by timmydhooghe** [comment]
> We're also waiting for [testbench](https://github.com/orchestral/testbench-core/tree/647d0db9818ab4b63a4ea15d00f90c9a71043a1f) to support Laravel 9.

Quick note: although the readme page doesn't mention it, Laravel 9 is supported [since 5 days (v7.0)](https://github.com/orchestral/testbench-core/releases/tag/v7.0.0)

**Comment by jasonvarga** [comment]
Closing this as we're concentrating on it in #5188
