### ISSUE TITLE
3.2.31 breaks addons that extend query builder

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#5078]
### Bug description

Updating to 3.2.31 breaks my Redirect addon that has its own query builder: https://flareapp.io/share/Lm8EGORP### 

### How to reproduce

Have an addon that implements a query builder, see: https://github.com/riasvdv/statamic-redirect/issues/41

### Versions

Statamic 3.2.31 Solo
Laravel 8.79.0
PHP 8.1.1
rias/statamic-redirect dev-main

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Might be good to make it have a default implementation instead of abstract

**Comment by duncanmcclean** [comment]
I'm seeing exactly the same thing... see GH Actions test run: https://github.com/doublethreedigital/simple-commerce/runs/4927960572?check_suite_focus=true

**Comment by jasonvarga** [comment]
Sorry about that. 🤦
