### ISSUE TITLE
Control panel: replicator preview text generation only happens for last set item and only after opening and closing a set item

### ISSUE THREAD

**Issue by ncla** [statamic/cms#5081]
### Bug description

All set items are identical, yet only the last set item gets the preview text generated upon page load.

![image](https://user-images.githubusercontent.com/5507083/149764803-bd2e6980-6a5c-46e7-85a4-e07518840fe5.png)

And another bug (?) is that the preview text only generates after opening and closing a set item, but I think I read somewhere that this is intentional behavior? Not sure anymore because of these two inconsistencies. 

### How to reproduce

Minimal bug repository: https://github.com/ncla/statamic-replicator-preview-bug-report
Open "Test bug" page in control panel.

### Versions

Statamic 3.2.31 Pro
Laravel 8.79.0
PHP 8.0.14
No addons installed

### Installation

Starter Kit using via CLI

**Comment by TimGr** [comment]
I notice this too. Its working in 3.2.29, but with 3.2.30 or 3.2.31 this bug occurs.

**Comment by TimGr** [comment]
Maybe it is caused by this change? 
https://github.com/statamic/cms/pull/5031 which is part of 3.2.30
