### ISSUE TITLE
Static cache-excluded URLs being cached when trailing slash present

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#5099]
### Bug description

Taking this discussion out of https://github.com/statamic/cms/issues/4732 to avoid derailing it

I seem to have an issue with pages excluded from the static cache being cached regardless, but with no obvious trigger. The static cache is cleared on deploy, and a service worker is installed which loads all pages to cache them for offline viewing - this has the effect of viewing every page, trigging a static cache of all pages.

The contact page is excluded, but is now being cached, but not by simply viewing it. It is also being done at a seemingly random time, as all the other pages were cached by the service worker requests at the same time.

![image](https://user-images.githubusercontent.com/545339/150415311-6d588e11-645b-4f94-9c1d-028066616942.png)

~11:42 is when I did a deploy and the pages would have been re-cached, I didn't do anything at 16:58. Furthermore, if I delete the contact-us file, and re-visit the page, it is (correctly) not cached. So I don't know where it's been coming from.

This page is excluded in the config:

```
'exclude' => [
    '/contact-us',
    '/about-us/join-our-team/jobs/*',
    '/storage',
],
```

I first had this issue after upgrading from 3.0.49 to 3.2.28 on Dec 23rd - the contact page was cached then and I didn't notice. I resolved the on Jan 18th by clearing the cache, today I noticed it had come back. I cleared it again, upgraded from 3.2.28 to 3.2.31, and the problem has since occurred again.

### How to reproduce

~Unsure on reliable reproduction steps unfortunately, it seems sporadic at best~

Configure static caching but visit the URL with a trailing slash, and the page will still be cached.

### Versions

3.2.28, 3.2.31

### Installation

Fresh statamic/statamic site via CLI

### Additional details

~The only addon I have is for redirects but I can disable this to see if the issue still happens.~

**Comment by MattRogowski** [comment]
Okay, so it's if you go to `/contact-us/` (trialing slash) it'll cache it still. I don't know if this can be handled any differently? I guess I should redirect away from trailing slashes, but not sure if this needs to be handled by the static caching logic too.

**Comment by edalzell** [comment]
You can use wildcard `/contact-us*`

**Comment by MattRogowski** [comment]
Sure, but should that be necessary? The documentation example has just `/contact`, but visiting `/contact/` would still cache it. It either needs to be made clearer in the documentation that a trailing slash will be treated as separate URL, or it should just ignore trailing slashes when checking if the URL should be cached.

**Comment by edalzell** [comment]
oh for sure, just giving a workaround.

**Comment by MattRogowski** [comment]
Ah yeah instead of having the duplicated lines 👍

**Comment by jasonvarga** [comment]
Nice detective work. Ideally the slash and non-slash page would be treated the same way, with nothing extra needing to be done by you.
