### ISSUE TITLE
Code field with long un-spaced content makes page too wide

### ISSUE THREAD

**Issue by adevade** [statamic/cms#5117]
### Bug description

I pasted the code to embed a Google Map in a Code field, and the page became scrollable horizontally. 

![image](https://user-images.githubusercontent.com/1066486/150749614-5a28c2a0-2bda-4dd2-8029-0500eb59420d.png)

It pushed the sidebar out of view.

### How to reproduce

1. Add a Code field to any blueprint (wrapping or no wrapping, makes no difference)
2. Paste the following code: 
```html
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1504.3090102696372!2d20.594503416294664!3d67.8497339079867!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x45d0c79c4842e779%3A0x516382f753ff1ebc!2sICEHOTEL!5e0!3m2!1ssv!2sse!4v1643013996045!5m2!1ssv!2sse" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
```
3. See that it makes the screen overflow on the X axis.

### Versions

Statamic 3.2.31 Solo
Laravel 8.80.0
PHP 8.0.8
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Let me know if you need more details.

**Comment by jackmcdade** [comment]
Not an issue in newer versions.
