### ISSUE TITLE
Localized code fieldtype always has dirty state

### ISSUE THREAD

**Issue by aerni** [statamic/cms#5124]
### Bug description

If you localize the content of a code fieldtype in a multi-site, it will always ask if you want to disregard unsaved changes when changing the site.

https://user-images.githubusercontent.com/23167701/151013650-7aacfbf4-f7e2-425b-b0be-f9e9995494f5.mov

### How to reproduce

- Create a multi-site
- Add a code fieldtype and make it localizable
- Create an entry and add some data to the field
- Change to another site, change the data, and save
- Switch back and forth between the sites and see it scream at you

### Versions

Statamic 3.2.x-dev Pro
Laravel 8.80.0
PHP 8.0.14
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by adevade** [comment]
Probably related to https://github.com/statamic/cms/issues/5124
