### ISSUE TITLE
Laravel v8.81 introduces an exception during console commands and package discovery

### ISSUE THREAD

**Issue by dniccum** [statamic/cms#5126]
### Bug description

After performing a version update, I am receiving an error with the `statamic/stringy/src/Stringy.php` utility that is included with the Statamic CMS. This does appear to be a breaking issue as any of the `php artisan` and `php please` commands throw the error.

### How to reproduce

1. Upgrade your installation to use the most recent version of Statamic
2. Make sure that you have the following entry in your `composer.json` file: `"laravel/framework": "^8.81"`
3. Attempt to perform a `composer dumpautoload` command to leverage Laravel's auto package discovery

### Logs

```shell
> Statamic\Console\Composer\Scripts::preUpdateCmd
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading laravel/framework (v8.80.0 => v8.81.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Upgrading laravel/framework (v8.80.0 => v8.81.0): Extracting archive
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   InvalidArgumentException 

  Passed value cannot be an array

  at vendor/statamic/stringy/src/Stringy.php:45
     41▕      */
     42▕     public function __construct($str = '', $encoding = null)
     43▕     {
     44▕         if (is_array($str)) {
  ➜  45▕             throw new InvalidArgumentException(
     46▕                 'Passed value cannot be an array'
     47▕             );
     48▕         } elseif (is_object($str) && !method_exists($str, '__toString')) {
     49▕             throw new InvalidArgumentException(

      +8 vendor frames 
  9   [internal]:0
      Statamic\Extend\AddonRepository::Statamic\Extend\{closure}("aryehraber/statamic-logbook")

      +14 vendor frames 
  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

### Versions

- "laravel/framework": "8.81"
- "php": "7.4.24"
- "statamic/cms": "3.2.31"
- "rias/statamic-redirect": "1.10.36"
- "aryehraber/statamic-logbook": "2.0.2"

### Installation

Starter Kit using via CLI

**Comment by aerni** [comment]
I just ran into this as well.

**Comment by okaufmann** [comment]
Hi @jasonvarga

I ran into the same problem before I found this issue only after I had already looked in the code.

At first, it seemed to be a problem with the parameter order of Statamic\Support\Str where the signature is

    replace($string, $search, $replace)

(in latest version v3.2.31 https://github.com/statamic/cms/blob/v3.2.31/src/Support/Str.php#L262) but Laravel's Str::replace uses

    replace($search, $replace, $subject)

(did not change in the last 9 months https://github.com/laravel/framework/blame/8.x/src/Illuminate/Support/Str.php#L612).

When I did change the arguments of Statamic\Support\Str's replace method to the compatible signature `public static function replace($search, $replace, $string)` (https://github.com/statamic/cms/blob/v3.2.31/src/Support/Str.php#L262) it then goes on.

But then it calls Stringy's replace method (https://github.com/statamic/Stringy/blob/master/src/Stringy.php#L1077).

    public function replace($search, $replacement)
    {
        return $this->regexReplace(preg_quote($search), $replacement);
    }

I think here lays the main problem, that `preg_quote` is just not compatible with $search be an array (what is supported by the default Laravel replace method as it just uses the built-in `str_replace` method and the studly method in Laravel 8.80 did).

As this is fixed now, I thought my deep dive helps identify the core problem about this "bug".

**Comment by okaufmann** [comment]
I just saw that you anyway want to remove the Stringy dependency, which will solve this problem too 👍
