### ISSUE TITLE
AssetsService extends undefined class DataService

### ISSUE THREAD

**Issue by Konafets** [statamic/cms#5138]
### Bug description

The class `Statamic\Contracts\Assets\AssetService` extends an undefined class `Statamic\Contracts\Data\DataService`. 

![2022-01-27_10-46-23](https://user-images.githubusercontent.com/363363/151334120-a9d55ca4-36fd-49c3-8b61-ada87590ac85.jpg)

### How to reproduce

N/A

### Versions

3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
That class is unused and just leftover from v2. We can remove it.
Were you running into a problem with it or were you just looking through every file in the codebase?
