### ISSUE TITLE
Explicitely defined scopes not working when they've been defined inside collections or get_content tags

### ISSUE THREAD

**Issue by kamilahcarter** [statamic/cms#5152]
### Bug description

I was trying to use explicitly defined scopes (documented here: https://statamic.dev/variables#explicitly-defined-scopes) to reference values from a set multiple places in a template. When I setup the item through a related field (as shown below) this did work as expected:
```
{{ colors:brand_color_set }}
  {{ scope:greenish }}
  {{ /scope:greenish }}
{{ /colors:brand_color_set }}
{{ greenish:base_color }}
```
However when I used a collection or get content_item it didn't work 
```
{{ collection:previous limit="1" }}
  {{ scope:greenish }}
  {{ /scope:greenish }}
{{ /collection:previous}}
{{ greenish:base_color }}
```
```
{{ get_content from="/color-sets/green" }}
  {{ scope:greenish }}
  {{ /scope:greenish }}
{{ /get_content }}
{{ greenish:base_color }}
```

### How to reproduce

1. Use the get_content or collection tag in an antlers template
2. Within that tag set a custom scope using the {{ scope }} tag
3. Outside of the get_content or collection tag try to access a value from the custom scope

### Versions

Statamic 3.2.32 Solo
Laravel 8.80.0
PHP 8.0.10
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Additional details

The {{ scope }} tag does not have a lot of documentation information which made it difficult to figure out if this was a bug at all. I think it would be helpful to have more details on {{ scope }} as a tag, for instance is there any way to use {{ scope ____="value" }} style format in addition to the {{ scope:value }} format? Are there any other optional parameters?

**Comment by jasonvarga** [comment]
This issue is quite old now and it looks like you would have been using the older Antlers parser. If you're still running into this issue when using the runtime Antlers parser, feel free to reopen.
