### ISSUE TITLE
Taxonomy Term Field title output empty

### ISSUE THREAD

**Issue by crackAT** [statamic/cms#5175]
### Bug description

Since v3.2.32 the Taxonomy Term fields aren't displaying the title anymore. Saved term is still set but there is no Title output anymore and the Select list contains only slug names. 

Before: 
![image](https://user-images.githubusercontent.com/6299060/151781473-cbd246e3-7427-4606-b6b7-40e6929ede44.png)

After: 
![image](https://user-images.githubusercontent.com/6299060/151781513-235f1e3b-fbde-4799-99f4-8d8d751308bd.png)

### How to reproduce

Add a Taxonomy Term field to a collection, update from 3.2.31 to 3.2.32

### Versions

Statamic 3.2.31 Pro
Laravel 8.81.0
PHP 8.0.8
statamic/eloquent-driver dev-feature/support-all-models

### Installation

Fresh statamic/statamic site via CLI

**Comment by helloiamlukas** [comment]
Same problem here, seems like the changes in `src/Query/EloquentQueryBuilder.php` in https://github.com/statamic/cms/pull/5125 cause this problem

**Comment by helloiamlukas** [comment]
Solved after upgrading to Statamic 3.3
