### ISSUE TITLE
Console error when adding new replicator set

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#5181]
### Bug description

There's a console error when adding a new replicator set.

### How to reproduce

- Create a replicator field
- Click add set
- See the set not appear, but see a console error.

### Errors

```
vue.common.dev.js:630 [Vue warn]: Error in getter for watcher "replicatorPreview": "TypeError: _ is not a function"

TypeError: _ is not a function
```

### Versions

Statamic dev-master 49b2f9d9 (Upcoming 3.3)

### Installation

Other (please explain)

### Additional details

I guess it has to do with #4949 where we upgraded underscore?

**Comment by jackmcdade** [comment]
Affects the Table Fieldtype too.

**Comment by duncanmcclean** [comment]
@jasonvarga Can this one be closed? Looks like the related PR has been merged.
