### ISSUE TITLE
Blueprint data is not returned for new entries when using laravel caching

### ISSUE THREAD

**Issue by arturslo** [statamic/cms#5182]
### Bug description

API tree collection does not return blueprint data for new entries when using caching
Blueprint data is not returned for new records in templates when using caching
This happens if Laravel CACHE_DRIVER redis or file is used

### How to reproduce

Call tree collection API route after new entry is added, it will return new entry with data but blueprint property is missing this only happens if you are using cache. I expect that new entries also provide blueprint data.
![missing_blueprint](https://user-images.githubusercontent.com/29819205/151968015-a7df1504-d3f3-450c-8ffa-3d99773dc548.gif)

Same issue in templates blueprint data is not returned for new records.
Dump for new record, you can see blueprint data is missing.
![new_record](https://user-images.githubusercontent.com/29819205/155088172-68d68e6a-b4c0-4943-811f-bdbc5a9080da.png)
Dump for exsisting record contains blueprint data.
![old_record](https://user-images.githubusercontent.com/29819205/155088411-9f82f8c9-2eb2-4b16-a31a-5a83ef608790.png)

### Versions

Statamic 3.2.32 Pro / 3.2.33
Laravel 8.80.0
PHP 8.0.12
aryehraber/statamic-logbook 2.0.2
avalanche/audit-log dev-main
avalanche/auth dev-main
avalanche/available-support dev-main
avalanche/contacts dev-main
avalanche/events dev-main
avalanche/guidelines-and-regulations dev-main
avalanche/implemented-projects dev-main
avalanche/news-resave dev-main
avalanche/seo dev-main
avalanche/subscriptions dev-main
avalanche/uk-ak-portfolio dev-main
avalanche/view-count dev-main

### Installation

Starter Kit using via CLI

### Additional details

statamic peak starter kit
multisite setup (multiple languages)
Collections uses multiple blueprints

**Comment by jackmcdade** [comment]
Closing as we can't recreate. Please feel free to open a new issue and explanation on how to recreate for v4 if it's still a problem.
