### ISSUE TITLE
hasStructure() on null and missing pages after deployment

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#5183]
### Bug description

After running a deployment and clearing the caches, oftentimes pages are missing from the backend and I have to manually clear the cache again so they appear.

This is one deployment hook I'm running at the end. After that I warm the cache as the last step.

```
php artisan config:cache
php artisan cache:clear
php artisan view:clear
```

When I then try to open a page, I very often get this error:

> [2022-02-01 13:21:02] production.ERROR: Call to a member function hasStructure() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function hasStructure() on null at /home/webapps/yyy/releases/20220201121231/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:138)

I know this `hasStructure` thingy is still a common issue with Statamic, but missing pages are really bad. ._.

### How to reproduce

I honestly don't know. I just run a deployment with Envoyer, clear the caches and then warm them.

### Logs

```shell
[2022-02-01 13:21:02] production.ERROR: Call to a member function hasStructure() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function hasStructure() on null at /home/webapps/yyy/releases/20220201121231/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:138)
[stacktrace]
#0 /home/webapps/yyy/releases/20220201121231/vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php(133): Statamic\\Stache\\Stores\\CollectionEntriesStore->removeEntryFromStructure()
#1 /home/webapps/yyy/releases/20220201121231/vendor/statamic/cms/src/Stache/Stores/Store.php(220): Statamic\\Stache\\Stores\\CollectionEntriesStore->handleDeletedItem()
#2 /home/webapps/yyy/releases/20220201121231/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Statamic\\Stache\\Stores\\Store->Statamic\\Stache\\Stores\\{closure}()
#3 /home/webapps/yyy/releases/20220201121231/vendor/statamic/cms/src/Stache/Stores/Store.php(221): Illuminate\\Support\\Collection->each()
#4 /home/webapps/yyy/releases/20220201121231/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Statamic\\Stache\\Stores\\Store->Statamic\\Stache\\Stores\\{closure}()
#5 /home/webapps/yyy/releases/20220201121231/vendor/statamic/cms/src/Stache/Stores/Store.php(222): Illuminate\\Support\\Collection->each()
#6 /home/webapps/yyy/releases/20220201121231/vendor/statamic/cms/src/Stache/Stores/Store.php(43): Statamic\\Stache\\Stores\\Store->handleFileChanges()
#7 /home/webapps/yyy/releases/20220201121231/vendor/statamic/cms/src/Stache/Query/Builder.php(98): Statamic\\Stache\\Stores\\Store->index()
#8 /home/webapps/yyy/releases/20220201121231/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(90): Statamic\\Stache\\Query\\Builder->getWhereColumnKeysFromStore()
```

### Versions

Statamic 3.2.32 Solo
Laravel 8.81.0
PHP 8.0.15
No addons installed

### Installation

Existing Laravel app

**Comment by jesseleite** [comment]
@MrMooky It happens consistently on every Envoyer deployment?

**Comment by johncarter-** [comment]
I found this when i had two separate sites on the same VPS, both sites using Redis cache driver. I found that i needed to prefix the cache so they wouldn't overwrite each other:

https://github.com/laravel/laravel/blob/9605fb17a3263a7d95124589e17bcee34df60200/config/cache.php#L108

Not sure if that helps you 🤷‍♂️

**Comment by MrMooky** [comment]
> It happens consistently on every Envoyer deployment?

Actually, this has not happened in a while for me. But it did happen when I deployed updated while users were active on the site and viewing articles. I think this issue here can be closed, just noticed that I had already created an issue for that which points into the right direction: https://github.com/statamic/cms/issues/4628

**Comment by jesseleite** [comment]
@MrMooky Did some testing on Envoyer, and you definitely need to make sure you avoid cache sharing between releases. Created a tips doc on how to do this here: https://statamic.dev/tips/zero-downtime-deployments
