### ISSUE TITLE
URL in link-fieldtype is not updated at language-switch

### ISSUE THREAD

**Issue by MizuBishi** [statamic/cms#5185]
### Bug description

I used the build in link fieldtype and noticed, that the url gets not updated in the UI interface at language switch. After I reloaded the page, the correct link url is showing.

### How to reproduce

Prerequisite: set individual link_url for 2 languages (e.g. de & en)
- change link url in "de" and save
- switch to "en" -> "de" link is shown
- reload page -> correct "en" link is shown

Maybe related to: https://github.com/statamic/cms/issues/4042

### Versions

Statamic: 3.2.32

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Looks like someone is already working on fixing this: #5130
