### ISSUE TITLE
Undefined variables `$height` and `width` in `compact()` call 

### ISSUE THREAD

**Issue by Konafets** [statamic/cms#5232]
### Bug description

In [Glide.php](https://github.com/statamic/cms/blob/0a4956670a18f32d21958d22f0be8a010663387a/src/Tags/Glide.php#L150-L150) the variables were used but not defined nor initialized.  

### How to reproduce

N/A

### Versions

3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by jackmcdade** [comment]
Fixed in
