### ISSUE TITLE
Search indexes unpublished items (Algolia)

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#5239]
### Bug description

I'm building out indexing for a client who currently has a lot of unpublished items in one collection. Due to the large discrepancy in number of entries vs the records that showed up in Algolia, I realized that when I submit my search index to Algolia it's indexing all the unpublished entries.

This will certainly create an issue when content that shouldn't yet be public starts showing up in the search index.

### How to reproduce

1. Set up Algolia indexing following the Statamic guide.
2. Index collection with unpublished items.
3. Unpublished items get sent to Algolia.

### Versions

Statamic 3.2.32 Pro
Laravel 8.83.0
PHP 8.0.14
aryehraber/statamic-font-awesome 2.2.0
optimoapps/statamic-bard-text-align 1.0.2
statamic/seo-pro 2.3.2
statamic/ssg 0.9.0

### Installation

Fresh statamic/statamic site via CLI

**Comment by markussorg** [comment]
Hey @fitzage,

I had the same issue. What I ended up doing is the following:

1. Add the "status" field to your index. You can do that in /config/statamic/search.php under indexes->default->fields. Add "status" to that array.

2. Add status to the "attributes for faceting" in the Algolia search ui:

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/3519464/178310197-8d76647c-6db9-42af-80d3-74360a9f98af.png">

3. Configure your javascript algolia driver (in my case [vue instant search](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/vue/)) to only show "published" entries:

![image](https://user-images.githubusercontent.com/3519464/178310510-26f086dd-50e8-4d54-b99f-56576647fe56.png)

Hope this helps!
