### ISSUE TITLE
Data table filters for various fieldtypes

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#525]
Allow for different operators / UI based on fieldtype.  id) `before` or `after` operators on a date field, with a date picker?

![Screen Shot on 2019-07-03 at 14-07-21](https://user-images.githubusercontent.com/5187394/60614915-ec368b00-9d9b-11e9-8d2c-166f17578c4a.png)

**Comment by jackmcdade** [comment]
Added in beta-20.
