### ISSUE TITLE
Graphql missing form field validation

### ISSUE THREAD

**Issue by SteJW** [statamic/cms#5250]
### Bug description

With the pull request at https://github.com/statamic/cms/pull/4115, Arthur created a graphQL call to get the form with the connected fields. All field data was returned. Jason made a small change in there, which makes it possible to select which data of the fields you wish to return, which is very helpful. However, it's missing the validation field where rules suppose to show (like required, email, numeric etc.).

### How to reproduce

Without validation, it works:

```
query {
  
  forms {
    title
    handle
    honeypot
    fields {
      handle
      display
      config
    }
  }
}
```

With validation, it doesn't and you'll get an error that validation does not exist:
```
query {
  forms {
    title
    handle
    honeypot
    fields {
      handle
      display
      config
      validation
    }
  }
}
```

### Versions

>= 3.2.23

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Note for me, or whoever implements this...

The rules should be queryable on the form level, not the field level. It's possible for fieldtypes to output more rules than just what the user has configured. e.g. a replicator field exposes rules for all of its sub fields.

Plus if it's at the form level, the user only has to query in one spot and not loop through anything.

```gql
query {
  forms {
    title
    handle
    rules // should return an array of [fieldname => rules] pairs
  }
}
```

**Comment by SteJW** [comment]
Thanks for the reply. I'm afraid the rules is not queryable. I'm getting an error "Cannot query field "rules" on type "Form".". It's also not available in the explorer of the graphql tool.

```
{
  "errors": [
    {
      "message": "Cannot query field \"rules\" on type \"Form\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ]
    }
  ]
}
```

**Comment by jasonvarga** [comment]
I know. I was leaving a note for when we get around to it.

**Comment by SteJW** [comment]
Right, sorry.
