### ISSUE TITLE
Tag and API does not output entries in collection order

### ISSUE THREAD

**Issue by dryven-dano** [statamic/cms#5268]
### Bug description

I often use Statamic's own API to get entries out of a taxonomy or collection and I usually set them up to be reorderable by the client, so they can choose how these items are displayed on the frontend.

When I use the Collection-Tag to output the entries, it does output them in the given order... most of the times. When it doesn't I usually clear the cache. The same happens with entries queried by the Statamic API and I can't do much about it, but clear the cache every now and then.

I've noticed that editing a single entry it changes position in this order. But there might be more sources when this is changed. It's troublesome since clients are often rightfully confused when they can't take control of the "Reorder" feature and seem to have no control how it's displayed on the page. Showing them how to clear the cache is not an option, since it should be intuitive for everybody. What can be the issue here? It happens on my development setup (Wamp on Windows; Apache \w PHP on Linux) and on the production server (Most of them are Debian-like Apache/PHP package distributions). Could it be that the cache falsely sets the order on these elements?

### How to reproduce

1. Create a reorderable collection "test" with some test entries
2. Retrieve them with the api endpoint, e.g. /api/collections/test/entries?fields=slug,title,image,text
3. Reorder and/or edit items in the collection
4. Retrieve in a new tab the entries with the API
5. Most of the times the updated entry doesn't show up on the right spot

### Versions

Statamic 3.2.32 Pro
Laravel 8.82.0
PHP 8.0.10
aryehraber/statamic-logbook 2.0.2
ddm-studio/cookie-byte 1.0.13
doublethreedigital/duplicator 2.1.0
spatie/statamic-responsive-images 2.8.5
webographen/statamic-admin-log 1.0.6

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Add `&sort=order` to your query.

**Comment by dryven-dano** [comment]
Thanks, but we've been using this parameter in the tag and as a parameter for the API queries, but it still doesn't sort the items correctly some times, especially after some content was edited. I can't actively reproduce this error, but every now and then it doesn't sort them by the collections' order, no matter how strongly I request it. It seems like the cache malforms the order of the entries in these cases.

 And btw: Wouldn't it be more intuitive to order it by the collections' order when you can reorder it?
