### ISSUE TITLE
Page structure don't influence nav's {{ is_parent }} state anymore

### ISSUE THREAD

**Issue by klickreflex** [statamic/cms#5278]
### Bug description

**Update** I updated the title to better reflect the real issue. This is not about the depth as I had first thought, but about the fact that a Navigation items {{ is_parent }} state used to be affected by it's pages position in the page tree -  and it's not anymore since the release of 3.2.32.

After upgrading to 3.2.33 a page nested on the fourth level doesn't cause its first-level parent to have a true state for `{{ is_parent }}`. On 3.2.31 this is still working, on 3.2.32 it's not.

Also I've tried to explicitly add the fourth item to the navigation (additionally to page tree), but this doesn't help either.

### How to reproduce

1. Use Statamic 3.2.32 or 3.2.33
2. Create four levels nested page structure
3. use `{{ is_parent }}`  on first level nav item 
4. visit a 4th-level child page 
5. find out `{{ is_parent }}` is false, despite your current page is nested under that page

### Versions

Statamic 3.2.33 Pro
Laravel 8.79.0
PHP 8.0.14
doublethreedigital/duplicator 2.1.0
goldnead/statamic-toc 1.1.0

### Installation

Starter Kit using via CLI

**Comment by jasonvarga** [comment]
Please provide a repo with this problem reproduced.

**Comment by jasonvarga** [comment]
Since you're using `nav:main` (I'm looking at [this](https://github.com/studio1902/statamic-peak/blob/636c046635411070b443b614bfdbfc23815b902b/resources/views/navigation/_main_desktop.antlers.html#L9)) then the "contact form" page doesn't exist in it, so I _would not_ expect it to be considered is_current.

If you were using `nav` or `nav:pages`, it would be referencing the `pages` collection tree, and it would be.

**Comment by klickreflex** [comment]
I'm pretty sure that's not how  it has worked before the recent updates. I've always rendered nav trees and their active state has been determined by page nesting. So if that has been changed it should be announced to not break existing navigations.

I can downgrade to 3.2.31 and immediately observe that parent menu items of nested pages have `{{ is_current }}` again. (on my production site, in that test setup downgrading breaks the entire site)

**Comment by klickreflex** [comment]
Here how it works on a site that runs 3.2.31. 

- That shown active state gets lost when upgrading to anything between 3.2.32 and 3.2.35
- The nav is also built with `{{ nav:main ... }}`  like in my example repo

![CleanShot 2022-03-02 at 22 59 26@2x](https://user-images.githubusercontent.com/435825/156457381-3cf4f445-2632-402f-a831-cb1764e0a901.png)

**Comment by jasonvarga** [comment]
If it was working, we believe it to have been incorrect behavior.

The is_current is based on the current page's position in the nav. If it's not in the nav, it's not going to be considered.

**Comment by jasonvarga** [comment]
If you use the new parser in 3.3, you can just check against the url instead of using is_current.

```
{{ if current_url | starts_with(permalink) }} current {{ /if }}
```

**Comment by klickreflex** [comment]
> If it was working, we believe it to have been incorrect behavior.
> 
> The is_current is based on the current page's position in the nav. If it's not in the nav, it's not going to be considered.

Could we please check back if that believe is 100% valid?
Let me explain why this is such a huge issue to me  with a concrete example that affects almost every Statamic site I have ever built and now have a way worse user experience just by upgrading:

### Why not `nav:pages` ?
I use navigation entities to build my navigation. Building navs from the page tree is not an option because there pages, many on the top-level pages such as `/privacy`, that must not appear in main navigation.

### Problems since page tree isn't considered in navigations
- There are collections, such as news, for which it makes no sense to each have their own menu. Using the collection's mount point those entries still have a clear belonging in the hierarchy of the page. However, when visiting a news entry, the menu entry of the mount point page is not active anymore. Orientation within the navigation is lost to the user. This just broke with an update and poses a huge problem to existing sites, no matter if the previous behavior was intended or not.
- From a UX perspective, it rarely makes sense to have navigations more than 2 levels deep. However, it is often useful, to have deeper nested page tree and make deeper layers accessible by cards in the content area. Those pages clearly belong to their ancestor, but again, the menu position is lost as soon as a user navigates to a page not in the menu. 

I really cannot imagine I am the only one being affected by this. Also I'd be curious how other people tackle this.

I will check if the 3.3 solution works for me, but I'm hesitating to run 3.3 in production just yet.

**Comment by robdekort** [comment]
Let's say I have a collection, say: `/news/my-article`. The `News` index page is in your navigation tree. Am I correct that when you visit `my-article` (which is of course not in the navigation tree) that `News` doesn't get an `is_parent`? Because that really feels like a big step down and probably means I have 13 sites where the navigation breaks.

**Comment by robdekort** [comment]
I feel this should def. be reopened. We can hop on a chat Jason if you want. I'd love to discuss this and show you how this hurts navigation and usability.

**Comment by robdekort** [comment]
An example why this probably hurts _a lot_ of users but isn't immediately noticeable is a page like this:

https://nieuw-allardsoog.nl/confereren/conferentiezalen/de-vlinder

1. `conferentiezalen` is a mount for `conference_rooms`. 
2. `de-vlinder` is a en entry in `conference_rooms`.
3. `confereren` and `conferentiezalen` are in the nav tree.
4. when visiting `de_vlinder` all upper pages should get an `is_active` like it does here (this production version is not updated).
5. locally when I update this site the `is_active` stuff is gone when visiting `de-vlinder`.

**Comment by arthurperton** [comment]
Thanks for the clarification guys. I was thinking about this a few days ago after the clear explanation by @klickreflex. We can (and judging from this conversation, we should) make `is_parent` true for pages when either one of these is true:
1. The current page (`is_current`) is a child in the nav tree
2. OR The current page is a child considering the URL

Where 1 is the new logic and 2 is the old. Again, actually if either one is true, `is_parent` should be true.
