### ISSUE TITLE
Live Preview Freezes

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5287]
### Bug description

I'm getting a lot of freezing of Live Preview on localhost (laragon), which seems to get progressively worse over time.

Refreshing the page temporarily fixes the issue.

Lots of these errors are appearing in the console:
```
Uncaught SyntaxError: Identifier 'started' has already been declared
Cannot set properties of null (setting 'element')
Cannot read properties of null (reading 'unregisterPlugin')
```

![image](https://user-images.githubusercontent.com/20210934/154047585-cb530c88-8fce-4e99-89f7-bc8ba5278ddf.png)

### How to reproduce

Not sure. Use Live Preview with repeater fields and images on localhost. I use Laragon, which is similar to WAMP.

### Versions

Statamic 3.2.32 Solo
Laravel 8.82.0
PHP 8.1.1
edalzell/blade-directives 3.5.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by jackmcdade** [comment]
Do you still have these issues in 3.3?

**Comment by klickreflex** [comment]
@jackmcdade  

I _started_ to get these errors with 3.3.

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/435825/158850995-78cb80fe-c19f-47f2-8726-4b5beafea873.png">

## Some observations

- I don't need to go to live view to see them, just when editing _most_ pages
- On pages that show the error, I'm having huge trouble saving changes:
    -  Changes e.g. in field X, Y or Z (but certain other fields don't cause it) trigger a validation error on the _required_ field A, despite field A having had a valid value all the time, so I just can't save those pages anymore

<img width="640" alt="image" src="https://user-images.githubusercontent.com/435825/158851771-26f720b4-5199-4acd-893a-0f55ad459fbe.png">

**Comment by klickreflex** [comment]
It's getting worse: 

After removing the required validation on the main_heading field I was able to save the page. However, two fields `main_heading` and `sub_heading` now just got pruned (without me removing anything manually ofc)

![CleanShot 2022-03-17 at 17 52 47@2x](https://user-images.githubusercontent.com/435825/158853206-e37585f6-1cf4-4692-86e2-eb5714f6272a.png)

**Comment by klickreflex** [comment]
> That sounds completely different from what this issue is about. Can you open a separate issue?

I feel stupid now: my problem disappeared with a clear browser cache. JS errors stay though, but are not related to 3.3, sorry for the confusion. Will open a separate issue.

**Comment by jasonvarga** [comment]
No worries. That's a little more confirmation that this issue is just an outdated assets thing.
