### ISSUE TITLE
Create page entry

### ISSUE THREAD

**Issue by HazemMohamed252** [statamic/cms#5288]
### Bug description

Call to a member function field() on null

### How to reproduce

Collections -> Pages -> Create Entry

### Versions

Statamic 3.2.33 Pro
Laravel 8.83.0
PHP 7.4.11

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Please can you provide the full error (the stack trace)? There's not much to go on with what you've provided.
