### ISSUE TITLE
Headless Mode

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#53]
- [ ] Entries
- [ ] Taxonomy Terms
- [ ] Globals
- [ ] Assets
- [ ] Users

It should account for filters/conditions, limiting, offsetting, relationships, and pagination, and be data-source agnostic.

This interface can be used in the CP and the front-end (or external applications) in a "headless" mode.

**Comment by jasonvarga** [comment]
Closed in favor of individual issues.
