### ISSUE TITLE
Modifier [to] not found with Link Tag and Multi-Site

### ISSUE THREAD

**Issue by heidkaemper** [statamic/cms#5306]
### Bug description

When using the link tag in a multi-site setup, there is a "Modifier [to] not found" exception.

But only on the home page of the respective site. On subpages all works as expected.

Multi-Site Config:
![site-setup](https://user-images.githubusercontent.com/10990014/154651565-ea3365c6-9fa1-4e1d-b828-5d683ca50e33.png)

Antlers Template:
![antlers](https://user-images.githubusercontent.com/10990014/154651596-f64a7589-61aa-4e39-9d67-1482a4244660.png)

https://my.site/en thows the ModifierNotFoundException
https://my.site/en/products works

### How to reproduce

1. Configure Multi-Site within the sites.php like this:
```
    'sites' => [
        'DE' => [
            'name' => 'DE',
            'locale' => 'de_DE',
            'url' => '/',
        ],

        'EN' => [
            'name' => 'EN',
            'locale' => 'en_EN',
            'url' => '/en/',
        ],
    ],
```

2. Add a Link Tag to your layout.antlers.html with 'to' or 'id':
```
{{ link to="something" }}
{{ link id="1715c9a8-0662-4ca7-b9ea-1ad642431fae" }}
```

3. Open the home page in your browser

### Logs

```shell
(Statamic\\Modifiers\\ModifierNotFoundException(code: 0): Modifier [to] not found at /web/vendor/statamic/cms/src/Modifiers/Loader.php:19)
```

### Versions

Statamic 3.2.33 Pro
Laravel 8.83.1
PHP 7.4.27
aerni/social-links 2.3.0
joetannenbaum/antlers-stack-tags 0.1.0
pecotamic/sitemap 1.2.7
spatie/statamic-responsive-images 2.8.5

### Installation

Existing Laravel app

**Comment by heidkaemper** [comment]
Update: Yes, there are some link Fields. However, all of them are embedded in other fields (Replicator, Bard Sets, ..).

Example:
![link](https://user-images.githubusercontent.com/10990014/154966797-13754446-6186-4353-b6cf-011774857c59.png)

Strange thing is: even if I remove all fields from the .md files and all sets from the blueprints, the error is still present.

**Comment by ryanmitchell** [comment]
You can ensure you are using the tag instead of a variable by adding % to teh start... ie `{{ %link to="contact" }}`

**Comment by jasonvarga** [comment]
Using the `%` like Ryan said it the solution here. This ensure you get the "link tag" rather than the variable, if one happens to be there.
