### ISSUE TITLE
Regex patterns validation is changing digits to NULL

### ISSUE THREAD

**Issue by simonbedard12** [statamic/cms#5322]
### Bug description

When using the regex validation with digits like `{12}` on a field. 
The regex will be parse by Statamic and modify to NULL when matching curly braces `{..}`

This is what I found out during the validation process. 
When the validation process start, Statamic automatically parse the fields rules and modify the regex from `regex:/CCV\d{12}$/` to `regex:/CCV\dNULL$/`

https://github.com/statamic/cms/blob/f3e0d4018bbf1ac2f04eee16baa1f113a14a3503/src/Fields/Validator.php#L121

```
return preg_replace_callback('/{\s*([a-zA-Z0-9_\-]+)\s*}/', function ($match) {
        return Arr::get($this->replacements, $match[1], 'NULL');
}, $rule);

```

## Possible work around
Im not sure what the 'right' fix is... maybe the 'NULL' should be $match[1] so it falls back to original string
```
 return Arr::get($this->replacements, $match[1], $match[1]);
```

### How to reproduce

Create a field with a regex patterns containing digits 

```
validate:
  - required
  - regex:/CCV\d{12}$/
```

### Versions

```
Statamic 3.2.33 Pro
Laravel 8.83.1
PHP 8.0.14
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Ah we should probably avoid the replacements entirely if dealing with a `regex` rule.

**Comment by simonbedard12** [comment]
> Ah we should probably avoid the replacements entirely if dealing with a `regex` rule.

Something like this could be added to the if statement `Str::startsWith($rule, "regex")`

```
 if (! is_string($rule) || ! Str::contains($rule, '{') || Str::startsWith($rule, "regex")) {  
    return $rule;
 }
```
