### ISSUE TITLE
Error in `contains` modifier in combination with array

### ISSUE THREAD

**Issue by Konafets** [statamic/cms#5324]
### Bug description

I tried [this example](https://statamic.dev/modifiers/contains#arrays) from the docs:

`{{ if (foods | contains:"vegan bacon strips") }}`

and getting an error:

> Statamic\View\Antlers\SyntaxError
> syntax error, unexpected double-quoted string ")): ?>" on line 23 of: <header class="markdown pb-8 mb-8"> {{ partial:breadcrumbs }} <div class="flex items-center"> <h1><code>{{ slug }}</code> Modifier</h1> {{ partial:pro-badge }} </div> {{ intro ?? overview | markdown }} {{ partial:toc }} </header> <article class="markdown md:pb-16"> {{ content | toc:ids }} </article> tag_pair_d790bee5e54a91a55174fe3334a8e490
> 

---

I see double quotes on the value while debugging:
<img width="340" alt="2022-02-22_17-55-56" src="https://user-images.githubusercontent.com/363363/155180548-28e3213a-1d52-434a-b6b4-43c0b050c9f0.png">

### How to reproduce

Add the example from the docs.

### Versions

3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
This is fixed by the new parser in 3.3

**Comment by Konafets** [comment]
Confirmed that the error with double quotes is fixed with new antlers. However the doc states that the above example will return `true`:
> true   (there's no field named "vegan bacon strips", so it searched for literally "vegan bacon strips")

In fact it returns `false`.
