### ISSUE TITLE
Add 'status' to restricted handle list names

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/cms#5343]
### Bug description

Since the status field is augmented based on the published state, it shouldn't be possible to add a custom field with the `status` handle, since it's being overridden anyway.

### How to reproduce

Add any field with the handle `status` and see its value being overridden when dumping output in a template.

### Versions

Statamic 3.2.33 Pro
Laravel 8.83.0
PHP 8.0.15
jacksleight/statamic-bard-mutator 1.0.3

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
There's not currently a notice in the blueprint builder for reserved fields - there is however some [documentation around what fields are reserved](https://statamic.dev/tips/reserved-words#as-field-names) which was added after #3956 & statamic/ideas#46.
