### ISSUE TITLE
composer dump-autoload leads to "Maximum execution time of 30 seconds exceeded"

### ISSUE THREAD

**Issue by torian257x** [statamic/cms#5346]
### Bug description

we have around 2500 cms entries

when I run a dump-autoload and try to access the home / frontpage I get a 
> Maximum execution time of 30 seconds exceeded

I get no timeout problems when accessing any native laravel non-statamic pages

we use blade directives plugin and as well use blade with slightly custom code generally.

### How to reproduce

`composer dump-autoload`

this doesnt help:
```
php artisan optimize:clear
php artisan statamic:stache:clear
```

as well:

```
php artisan statamic:stache:warm
```
seems to be stuck

### Logs
![image](https://user-images.githubusercontent.com/2072058/155726266-daa2677e-6488-4a6e-9728-8a6ade815f1a.png)

```shell
Symfony\Component\ErrorHandler\Error\FatalError
Maximum execution time of 30 seconds exceeded
http://myapp-sites.test/
Stack trace
Request
App
User
Context
Debug
Share 


Collapse vendor frames
1
vendor/laravel/framework/src/Illuminate/Collections/Collection.php
:1572
::[top]
vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1572































     * @return static

     */

    public function pad($size, $value)

    {

        return new static(array_pad($this->items, $size, $value));

    }

 

    /**

     * Get an iterator for the items.

     *

     * @return \ArrayIterator

     */

    #[\ReturnTypeWillChange]

    public function getIterator()

    {

        return new ArrayIterator($this->items);

    }

 

    /**

     * Count the number of items in the collection.

     *

     * @return int

     */

    #[\ReturnTypeWillChange]

    public function count()

    {

        return count($this->items);

    }
```
```


### Versions

Statamic 3.2.32 Pro
Laravel 8.82.0
PHP 8.0.15
edalzell/blade-directives 3.5.2
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.7


### Installation

Existing Laravel app

### Additional details

_No response_

**Comment by duncanmcclean** [comment]
What version of Composer are you using? You should be using Composer 2.

`composer -V` will tell you

**Comment by torian257x** [comment]
> `composer -V` will tell you
Composer version 2.0.8 2020-12-03 17:20:38

**Comment by torian257x** [comment]
looks like the stache warm finally ran through. Now the homepage loads as well.

But that isn't very good for us, because it takes wayyyy to long. Will we have this issue on production as well? we plan to rewrite entries at least once every day.

**Comment by jackmcdade** [comment]
Can you tell us more about the site itself? How many collections/entries/users do you have? Any chance you have some recursion going on (like collection tags inside collection tags) that might be out of control?

**Comment by torian257x** [comment]
actually in the "big" collection we have somewhat over 5000 entries

contents/trees/collections/myfinder.yaml has around 9000 entries

example:

```
tree:
  -
    entry: 0926c013-df4e-42d6-be82-f9052c92bd84
    children:
      -
        entry: a00dff0c-491b-43f3-8cfa-440312b4d202
        children:
          -
            entry: 4ee67c70-f178-4392-994c-c32e6884d8fd
      -
        entry: 1b2414de-d68e-43fa-a024-414f29e9c436
        children:
          -
            entry: 00930bbc-cdfd-4e0d-9de6-3f16e5f78c7c
          -
            entry: 80a2c444-4b12-4da4-a917-33db15d21055
      -
        entry: 2cc8fa28-778e-4559-aada-3bee93448d38
        children:
          -
            entry: 22fc8e2d-c1e8-457a-b02c-267f9a62a7f0
      -
        entry: 820d4d97-0d33-426a-b5de-c0973136d35c
        children:
          -
            entry: 7711ef97-7a58-4da9-8919-9cc8aff1bbad
      -
        entry: 20d76261-f54e-4e05-b31a-af7ea2cad5aa
        children:
          -
            entry: feb819f6-d397-4c55-ae51-aad3e3b172f5
      -
        entry: 925ae681-0d6d-4f7a-a551-bce6902a2a7f
        children:
          -
            entry: c45b6202-e8c9-4dc7-b2f7-97e88d63fa98
  -
  ```
  
the levels arent deeper than that

its basically
country>city>location

rest is all very little
e.g. 2 users, a bunch of pages etc I think the rest totals like 30 entries

the big one is the myfinder

how would I detect recursion? stache warm runs through without errors (at least, so it seems)
we dont really use collection tags afaik


if absolutely necessary I could try to create a fresh new statamic installation and copy the the files over. Even though... i fear that would take substantial time.

**Comment by torian257x** [comment]
manually deleting the myfinder entries and the tree makes dump-autoload not cause any problems

**Comment by Konafets** [comment]
1. Can you update your composer version? You using 2.0.8 from 2020, current is 2.2.7. 

2. The command `composer dump-autoload` does not care about your data (Collections) inside Statamic, it just regenerate the autoloader file in `vendor/` i.e. when you add a new PHP classes. However you should use `composer dump-autoload -o` for faster autoloading. See: https://getcomposer.org/doc/03-cli.md#dump-autoload-dumpautoload-

3. Can you raise your execution time php.ini of your CLI PHP?

**Comment by jasonvarga** [comment]
Do you have any custom code? For example, have you put anything your AppServiceProvider?

**Comment by torian257x** [comment]
When accessing my home page:

I think the call
Inside `Page.php`

```
    public function flattenedPages()
    {
        return $this->pages()->flattenedPages();
    }
```
caused the timeout


reloading home page again gave me this:
![image](https://user-images.githubusercontent.com/2072058/157851210-30384dff-23f5-4d0a-a087-2921ffa79a3f.png)


AppServiceProvider.php ->
we have a singleton, and a blade directive


caused it. So something seems to be slowing us down a lot


havent updated composer yet

**Comment by duncanmcclean** [comment]
Do you use the `{{ nav }}` tag anywhere in your site? If you do, try taking it out, does it make a difference?

**Comment by Konafets** [comment]
I had a look at this today because I also registered a significant bad performance on an uncached homepage. My test site is a local copy of the documentation.

The docs in my copy have 506 pages: 

<img width="905" alt="2022-03-11_18-02-34" src="https://user-images.githubusercontent.com/363363/157913468-b0a57327-42d4-4af5-ac7a-c473ce7dd091.png">

I profiled the request with Blackfire. Here is a screenshot.

The amount of pages can be found in the upper left corner. This leads later to 42550 calls to `flattenPages()` and the `Pages::all()` method. I am not sure yet if this is needed to get the whole tree recursive. Just leave it here ... maybe its useful for someone.

<img width="1009" alt="2022-03-11_17-58-32" src="https://user-images.githubusercontent.com/363363/157912932-c5251900-a1ce-49a0-8427-5c0235422e1d.png">

**Comment by torian257x** [comment]
according to someone

this is most likely related to the stache index set in the config

indexes that are added to "all stores" cause a huge performance issue

https://statamic.dev/stache#configuring-additional-indexes

one has to add it on the level of Entry or so.... 
Im just relaying this information

**Comment by torian257x** [comment]
so the last state is this:

when you access a URL where statamic is routing, and you did composer install or dump-autoload (composer install calls dump-autoload itself) then the stache is gone. And a call to, as said, the URL where statamic works, will force statamic to load all entries all at once, just to figure out which entry is responsible, for say, the root url


See here:

https://github.com/statamic/cms/blob/3.3/src/Structures/CollectionStructure.php#L29

say I access `/` will, afaik, statamic do:

which entry has '/' as URL? -> don't know. Open all files, build URIs for all files, return right file. If there are files and a bit complicated tree structure, it falls apart.

**Comment by jasonvarga** [comment]
Clearly there are some ways to optimize performance in some areas, that's fine. But it would be when using your site.

This issue about seeing a timeout when doing a composer dump-autoload. Doing that shouldn't interact with your data.

Are you doing something custom. Are you doing anything in a server provider?

**Comment by torian257x** [comment]
I discussed this with jack on discord. 

basically your algorithm to figure out a random URL does this:
flatten everything
create tree of everything
after doing this crazy amount of work ask: "who is responsible for this url: '/'"


our workaround was not use statamic URLs for the pages that have a lot of pages and tree structure, and solve it using normal laravel routes and some DB entries.

afaik to not use statamic URLs, wipe the slug field.

**Comment by jasonvarga** [comment]
Good to hear you figured out a workaround.

By the issue title and your description I thought you were getting an error _when you were running_ `composer dump-autoload`. I didn't realize you were saying you saw the error _when you loaded the homepage_.

The actual issue is that when you run that, it clears the cache, so when you hit the homepage it has to build the cache. Since you have a ton of content, it takes a while.

You can use `php please stache:warm` to warm the cache in your console which will not encounter any timeouts. (It'll still take a while.)

I'm closing this since it's really just "make it perform better".
