### ISSUE TITLE
3.3 beta - Taxonomy tags error in runtime parser

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/cms#5357]
### Bug description

We use a replicator to set up panels/blocks, which are calling partials, one of which has the following inside it:

```
                    {{ taxonomy from="news_tags" }}
                    <div class="input checkbox">
                        
                        <input type="checkbox" name="tags[]" value="{{ slug }}" {{ if (get:tags | contains:slug ) }} checked{{ /if }}>
                        <span></span>
                        <label>{{ title }}</label>
                        
                    </div>
                    {{ /taxonomy }}
```

Throws an error:

`Undefined property: stdClass::$index` oddly from `vendor/statamic/cms/src/Fieldtypes/Bard/SetNode.php:21`, so it thinks its handling a Bard field (it isnt).

### How to reproduce

If its helpful I can provide someone with access to a private repo with the code.

### Versions

3.3.0 beta-2

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Just the replicator set up, but its the same setup as some of the starter kits use, so wouldn't be considered abnormal.

**Comment by JohnathonKoster** [comment]
@ryanmitchell  Would it be possible to get access to the site that reproduces this problem? I have some today and can look into this :)

Thanks!

**Comment by ryanmitchell** [comment]
@JohnathonKoster no problem - just invited you. I didnt include the assets as they are a few GB big, but hopefully you can hit the same errors without. This one is at the /news url, the short glide tags is on /recipes, and I've also got a recursive children issues in the layout that I was just trying to debug in case it was our issue (though it works fine in the regex parser).

**Comment by JohnathonKoster** [comment]
" I've also got a recursive children issues in the layout that I was just trying to debug in case it was our issue (though it works fine in the regex parser)." - that's on me - not you :) working on a fix for that as well

I'm having trouble reproducing the glide issue, but will circle back to that once I figure out the recursion

**Comment by ryanmitchell** [comment]
Awesome, thanks. The glide issue is on the homepage - its the news_select panel if that helps identify it.
