### ISSUE TITLE
3.3 beta – Pluck modifier broken on relations

### ISSUE THREAD

**Issue by schmidex** [statamic/cms#5365]
### Bug description

In 3.2 something like the following works:

```{{ entries | pluck:name | sentence_list  }}```

In 3.3 entries are no longer retourned as ```EntryCollection```s. They are instances of ```EntryQueryBuilder``` resulting in an ```Call to undefined method Statamic\Stache\Query\EntryQueryBuilder::map()``` error.
Maybe other modifiers are affected too.

### How to reproduce

Create a relation and try to use the pluck modifier on it.

### Versions

Statamic 3.3-beta2
Laravel 8.*

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Fixed for 3.3 beta 3.
