### ISSUE TITLE
3.3 Beta - New Antlers Parser - Pluck modifier doesn't work correctly on entries

### ISSUE THREAD

**Issue by schmidex** [statamic/cms#5372]
### Bug description

This one is hard to describe (at least for me. I'm not an native English speaker). Better take a look at the "how to reproduce" section.

Only the new runtime parser is affected. Everything works fine in the old regex-parser.

The pluck modifier only works on entries if the relation has been "parsed" before..
This is far beyond my debugging skills.
Maybe @JohnathonKoster can have a look.

### How to reproduce

- Enable the new runtime parser.
- Create a page with a entries relation (in this example called "entries") and add item(s).
- Try to parse this simple template:

```
{{ entries|pluck:title|sentence_list }}
```

An empty template will be returned.

If you do this:
```
{{ entries ))
{{ entries|pluck:title|sentence_list }}
```

Everything works

### Versions

Statamic: current-master (because it includes the modifier fixes #5368)
Laravel:8.*

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Is this not the same as your previous issue, #5365?

**Comment by schmidex** [comment]
no. this was fixed.
This one is only affecting the new runtime parser

**Comment by jackmcdade** [comment]
What if you do this? 
```
{{ entries | pluck('title') | sentence_list }}
```

**Comment by schmidex** [comment]
Same problem :-(
If I put an ```{{ entries }}``` before that like so:
```
{{ entries }}
{{ entries | pluck('title') | sentence_list }}
```
 it works. So I guess this is a "deeper" parser problem and not syntax related

**Comment by jasonvarga** [comment]
@JohnathonKoster Previously I asked you to make the parser use the `query` tag if it encounters a query builder.

Looks like it should only do that if it's a tag pair.

If it's a single tag, could you just run `$builder->get()` to get the items and then just continue treating it as a variable?

**Comment by JohnathonKoster** [comment]
> @JohnathonKoster Previously I asked you to make the parser use the `query` tag if it encounters a query builder.
> 
> Looks like it should only do that if it's a tag pair.
> 
> If it's a single tag, could you just run `$builder->get()` to get the items and then just continue treating it as a variable?

Also finding the same thing -- will have a fix available soon on that open PR branch :)
