### ISSUE TITLE
3.3 beta - Blank stack when using `Create & link entry`

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#5409]
### Bug description

When you use an entries field and have it set to the stack selector, clicking `Create & link entry` opens an empty stack with a bunch of JS errors.
<img width="1412" alt="Screen Shot 2022-03-04 at 20 36 35" src="https://user-images.githubusercontent.com/69107412/156830407-ca69b05b-6711-4c66-97a7-c03dc842c16c.png">
.

### How to reproduce

Add an entries field
Set it to stacked mode
Click on `Create & link entry`

### Versions

Statamic 3.3.0-beta.3 Pro
Laravel 8.83.3
PHP 8.1.2
No addons installed

### Installation

Starter Kit using via CLI

**Comment by jasonvarga** [comment]
Fixed in #5392 - I'll tag beta 4 in a moment.
