### ISSUE TITLE
Value not saved in array if value is 0/zero

### ISSUE THREAD

**Issue by paptito** [statamic/cms#5419]
### Bug description

Used filedtype array in replicator to store values, if i enter 0 (number zero) as value id is not saved.

This is my fields structure:
 -
        handle: variants
        field:
          collapse: false
          sets:
            variant:
              display: Variant
              fields:
                -
                  handle: variant_data
                  field:
                    mode: keyed
                    keys:
                      id: 'Variant ID'
                      title: Title
                      price: Price
                    display: 'Variant data'
                    type: array
                    icon: array
                    listable: hidden
                    instructions_position: above
          display: Variants
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above

### How to reproduce

Create field structure som bug description and save value 0 as Price in a row.

### Versions

Statamic 3.2.9 Pro
Laravel 8.41.0
PHP 8.0.15
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Have you tried updating Statamic? The latest is [v3.2.36](https://github.com/statamic/cms/releases/tag/v3.2.36).

**Comment by paptito** [comment]
> Have you tried updating Statamic? The latest is [v3.2.36](https://github.com/statamic/cms/releases/tag/v3.2.36).

It's the same behaviour after i updated to:
Statamic 3.2.36 Pro
Laravel 8.41.0
PHP 8.0.15
No addons installed

**Comment by jackmcdade** [comment]
This is by design, as data is "falsey" and not stored if false/null. You can account for it in your templates with {{ if value }}.

Maybe you could open a PR to allow fields a setting for "force saving 0, false, null data" or something similar?
