### ISSUE TITLE
Root Page can be added as a child in editor

### ISSUE THREAD

**Issue by splitmango-jenna** [statamic/cms#5426]
### Bug description

When Editing the Root Page in Control Panel, if you set the Root Page's parent you will get the error : "Root page cannot have children"

<img width="222" alt="Screen Shot 2022-03-07 at 11 37 33 AM" src="https://user-images.githubusercontent.com/101138295/157105571-4439c615-63f7-4fca-a975-52321ad01aa1.png"><img width="297" alt="Screen Shot 2022-03-07 at 11 37 40 AM" src="https://user-images.githubusercontent.com/101138295/157105572-71ac6afb-3586-4890-81e7-bf3d590b4966.png">

Even though the error shows, the page successfully saves. Also, **the error is saying Root Page cannot have children, but the Root Page has been set as a child**. 

<img width="841" alt="Screen Shot 2022-03-07 at 10 48 10 AM" src="https://user-images.githubusercontent.com/101138295/157104329-81c393e1-ce46-46d1-8e8c-814791a5c929.png">

This creates a 500 error on the Front End, and forever loading on the CP pages collection. 

<img width="951" alt="Screen Shot 2022-03-07 at 10 48 35 AM" src="https://user-images.githubusercontent.com/101138295/157104389-e5667257-c570-4fec-8623-175f2f59ff28.png">

### How to reproduce

1. log into Control Panel
2. edit Root page
3. Set Root Page's parent to other page in tree
4. Save the Root Page
5. Reload the CP/font end

### Logs

```shell
Root page cannot have children {"userId":"user-id","exception":"[object] (Exception(code: 0): Root page cannot have children at path/vendor/statamic/cms/src/Structures/Structure.php:93)
```

### Versions

Version: 3.2.31

*tried updating to lates (3.2.36) and it did not solve the issue

### Installation

Starter Kit using via CLI

**Comment by duncanmcclean** [comment]
Confirmed - recorded a quick video to demonstrate:

https://www.loom.com/share/30b02f01cc06409fac224c4dfc7bfb44

**Comment by gausoft** [comment]
I accidentally stumbled upon this bug

**Comment by mmodler** [comment]
We just had a broken website with "Root page cannot have children" - are there plans to fix this?

**Comment by christianhanne** [comment]
We had a similar issue. Not sure, if adding the root page as a child was the case here. There might be another way to accidentally break the site through the control panel. I would like to suggest that the CMS than maybe outputs a warning during `stache:warm`, but don't completely fail. 

If the root page is not supposed to have children... ok. But maybe just remove them during the stache:warm process and display an error like "Root page can not have children. Statamic won't display them, make sure to move them to another parent element in the control panel." Failing completely in this case seems a little bit excessive here.

**Comment by tomhelmer** [comment]
I can confirm that setting the root page as parent when creating a new page results in this issue. This is a major issue as normal editor behaviour breaks the entire site.

**Comment by mmodler** [comment]
Thanks @tomhelmer ! We had broken sites because of this issue but we had no info how to reproduce. Now its clear.

**Comment by mmodler** [comment]
I just repaired a broken production site with "Root page cannot have children". Any news on this?
