### ISSUE TITLE
CP Conditional fields on a taxonomy require name::term syntax

### ISSUE THREAD

**Issue by wesort** [statamic/cms#5427]
### Bug description

Was not clear how to hide fields conditionally based on a taxonomy field's value. 

Does not work:
```
if:
  archive_types: 'equals film'
```

I eventually found [via Discord](https://discord.com/channels/489818810157891584/489819906540568593/949097334912995369) that for taxonomies one must:
- use `contains` 
- have a prefixed taxonomy name followed by `::` 
- AND then the value
```
if:
  archive_types: 'contains archive_types::film'
```

This is working for my context, but I'm sure there's a wide spread of usecases. Ideally this would be automatic in the UI, but perhaps docs in the meantime?

### How to reproduce

- Create a taxonomy `archive_types` > add the taxonomy to a collection 
- Add some terms to that `archive_types` (ie: `film`, `photo`, `book`, etc) 
- Create another field in the collection's Blueprint > switch to `Conditions` tab 
- `Show when` > _field_: select the `archive_types` > _operator_: `equals` > _value_: `film`

### Versions

Statamic 3.2.36 Pro
Laravel 7.30.6
PHP 8.0.16

### Installation

Existing Laravel app

**Comment by jasonvarga** [comment]
This is expected. The values you need to define are the _JavaScript_ values. For the taxonomy terms fieldtype, you are always dealing with the IDs in JavaScript, which is that `taxonomy::term` syntax. We can do a better job of documenting the options, though.
