### ISSUE TITLE
Condition evaluates differently with new parser

### ISSUE THREAD

**Issue by aerni** [statamic/cms#5429]
### Bug description

I've got a simple condition in my template that evaluates to `false` with the new `runtime` parser. It evaluates to `true` with the old `regex` parser.

```
{{ if design === 'teaser' }}
```

`design` is a button group field.

### How to reproduce

- Add a button group field with a `teaser` option
- Use the condition above
- Try with both parsers

### Versions

Statamic 3.3.0-beta.5 Solo
Laravel 8.83.3
PHP 8.0.14
aerni/advanced-seo dev-main
doublethreedigital/duplicator 2.1.1
jacksleight/statamic-bard-mutator 1.0.3
jacksleight/statamic-bard-texstyle 0.2.0
spatie/statamic-responsive-images 2.8.5
visuellverstehen/statamic-classify 2.3.2

### Installation

Other (please explain)

### Additional details

Updated from Statamic v3.2.*

**Comment by JohnathonKoster** [comment]
The string comparison operator `===` will compare the original types, without any casting. My guess here is that it's checking against the `LabeledValue` instance and failing.

Using the normal comparison operator should work as you'd expect:

```
{{ if design == 'teaser' }}

{{ /if }}
```

**Comment by jasonvarga** [comment]
@JohnathonKoster I think there should be some exceptions. This is one of them - could it be possible get the value() from the LabeledValue when used in a condition like this?

**Comment by JohnathonKoster** [comment]
Absolutely - I have a fix that I'll be PRing later this evening that does just that :)
