### ISSUE TITLE
Broken reordering/draggable functionality in List field type

### ISSUE THREAD

**Issue by caseydwyer** [statamic/cms#5437]
### Bug description

I think List entries are supposed to be reorderable. Leading with this in case they're _not_ supposed to have that functionality, but from [the List field type docs](https://statamic.dev/fieldtypes/list):

> It has full keyboard controls so you can use up to go up, down to go down, **drag and drop to rearrange the order**, and click an item to select it and begin editing.

The delete function works well; hovering an `li` replaces the bullet with an **x**. But reordering is tricky/buggy. There's a vertical arrow indicating draggability, but it's...hard to find? And even harder to click/drag. Tried to capture this in a GIF:

![list-bug](https://user-images.githubusercontent.com/13950848/157340078-1cf8a30e-efc3-43e7-968d-8584f551718b.gif)

So it's doable, but kinda feels like we're just missing a visual "handle" to grab, like we have in a `Grid` or `Replicator`.

### How to reproduce

1. Add a `List` field type to a blueprint.
2. Create a new entry.
3. Add three items to the `List`
4. Try to drag/reorder the three items

### Versions

Statamic 3.2.37 Pro
Laravel 8.83.4
PHP 7.4.3

### Installation

Fresh statamic/statamic site via CLI

### Additional details

If this needs more detail, let me know—hard to explain or capture, but definitely feels like a UI bug. Also happy to take a stab at PR-ing this, but wasn't sure where to start (eg, assumed there was a mixin for that draggability, just didn't know where to find it). Feel free to point me in the right direction, if an initial attempt to fix this would be helpful. 👍 Thanks team!

**Comment by jackmcdade** [comment]
Closed in https://github.com/statamic/cms/pull/7559
