### ISSUE TITLE
Static cache doesn't get cleared when you re-order entries

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#5451]
### Bug description

The static cache doesn't get cleared when you reorder entries. It should to reflect order on the live site. 

### How to reproduce

1. Make a collection
2. Add entries
3. Make an index view and sort by order
4. Turn on static caching
5. Visit the index url
6. Reorder the entries
7. Visit the index url again

### Versions

Statamic 3.2.35 Pro
Laravel 8.83.2
PHP 8.1.2
No addons installed

### Installation

Starter Kit using via CLI

**Comment by jasonvarga** [comment]
The "index view" of a collection will get cleared if you're using mounting.

https://statamic.dev/collections#mounting

e.g. If you have a `pages` collection with a `blog` entry in it, and you've mounted that entry to your `blog` collection. The `blog` entry url will get invalidated when you reorder the blog collection.

**Comment by robdekort** [comment]
That’s neat and thoughtfully made! There’s use cases though where this isn’t sufficient. For example when you display entries from a page builder block. Ran into this quite a few times already. Granted: saving some other entry with invalidation rules set to all solves this. But it’s probably not what non experienced editors suspect.

**Comment by jasonvarga** [comment]
When you save the collection order, the invalidator picks up that you want to invalidate the collection url.
The collection url is determined by the entry it's mounted to. If it's not mounted to an entry, it won't have a url, so it won't know what to invalidate.

I don't quite follow your page builder example, but if you have some more complicated setup, you can throw a simple event listener into your service provider's boot method:

```php
use Illuminate\Support\Facades\Event;
use Statamic\Events\CollectionTreeSaved;
use Statamic\StaticCaching\Cacher;

Event::listen(function (CollectionTreeSaved $event) {
    $collection = $event->tree->collection();
    $cacher = app(Cacher::class);

    if ($collection->handle() === 'blog') {
        $cacher->invalidateUrls(['/this-url', '/that-url']);
    }
});
```

**Comment by robdekort** [comment]
Couldn't it just follow the invalidation rules when you reorder a collection? 

Regarding my example. Let's say you have a team collection and a page builder (replicator) block that renders all team members. That way you can place them on an about page between other page builder content. When you reordering the team collection currently it doesn't invalidate that page then. It could follow the invalidation rules you set for that collection. In my case (Peak) I set the them to `all` by default. 

Thanks for the example. Whatever you decide I'll save that one for future reference 👍.

**Comment by arthurperton** [comment]
Thanks for the discussion guys! Rob your last comment is spot on, as a matter of fact the custom invalidation rules are currently not executed in this case, and they should be. That is an easy fix though.

Also could you post an example of your invalidation rules? Because currently `all` is only supported as a 'global' rule and not, for example, per collection. That could be a nice addition though.

**Comment by robdekort** [comment]
Yeah I simply use the global rule for each site. It would definitely be nice to have `all` on a collection level.
