### ISSUE TITLE
Structured Collection: `parent:`-value

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#5457]
### Bug description

For what exactly is the `parent`-value of an entry within a structured collection?

1. If you create the entry as child, it gets the `parent`-value.
2. If you create the entry as parent, no `parent`-value is set (seems correct)
3. If you move the parent-entry to a child position, `parent`-value is still missing.

Same happens, if you set parent/child over parent field.
Resaving of structure does not help.

Is it a bug?

### How to reproduce

Create entries as parent and as children and move them around. Have a look at the `parent`-value.

### Versions

Statamic 3.2.37 Solo
Laravel 8.83.4
PHP 8.0.16
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
`parent` shouldn't be saved to the yaml at all. That's a bug.

**Comment by duncanmcclean** [comment]
Can confirm - recorded a demonstration video - the first entry doesn't have it saved (created, then went back in and edited, if it matters) but the second one does: https://www.loom.com/share/4a5419c48cc143e887a5b9d03aa482ea

**Comment by j3ll3yfi5h** [comment]
@jasonvarga What behavior would be correct? Should the parent value be visible in the augmented data?

Currently it looks like it is adding the yaml data:
https://github.com/statamic/cms/blob/2dcba51c3c62e5c1b07b912a010e95eb51643c08/src/Entries/AugmentedEntry.php#L68

**Comment by j3ll3yfi5h** [comment]
Working with the parent value does always contain a `Statamic\Structures\Page` object, is that correct?

Can't get only the id for something like `->where('parent', $parent_id)` or `{{ collection:comments parent:is="id" }}` 🤔
