### ISSUE TITLE
Issue with regex parser

### ISSUE THREAD

**Issue by aerni** [statamic/cms#5459]
### Bug description

After updating to `3.3.0-beta.6` I'm getting the following error:

```
addcslashes(): Argument #1 ($string) must be of type string, Statamic\Query\OrderedQueryBuilder given
```

This error only occurs with the `regex` parser. Changing the parser to `runtime` fixes the issue.

This is in my template, where `testimonial` is an entry field.

```
{{ relate:testimonial }}
    {{ testimonial }}
{{ /relate:testimonial }}
```

If I remove `relate:` the error disappears but nothing gets rendered too. Dropping `relate:` on the `runtime` engine still renders everything correctly.

### How to reproduce

- Use `3.3.0-beta.6`
- Add an entry field
- Try outputting it in the template

### Versions

Statamic 3.3.0-beta.6 Pro
Laravel 8.83.4
PHP 8.0.14
aerni/advanced-seo dev-main
spatie/statamic-responsive-images 2.8.5
visuellverstehen/statamic-classify 2.3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
`testimonial` is an `entries` field... and then the testimonial entry also has a `testimonial` field?

**Comment by aerni** [comment]
Yes. The `testimonial` field on the entry blueprint is a `textarea` field.

**Comment by jasonvarga** [comment]
> If I remove relate: the error disappears but nothing gets rendered too. 

This is because you then run into a regex parser but (fixed in the runtime parser) where the inner `testimonial` tag looks like the opening tag to the closing tag.

If your testimonial entry's `testimonial` variable was named something else, it would work.

```
{{ testimonial }}
  {{ testimonial_content }} this would work
{{ /testimonial }}
```

Anyway, I'm gonna fix it so the relate tag behaves so you don't have to change your site.

**Comment by aerni** [comment]
Did anything change in how the `relate` tag works? Because this all worked before upgrading to the beta.

**Comment by jasonvarga** [comment]
Not the relate field, but the `entries` field used to be a collection of entries, now it's an entry query builder.
