### ISSUE TITLE
```pluck``` modifier ist broken on replicator (and probably grid and bard) fields

### ISSUE THREAD

**Issue by schmidex** [statamic/cms#5460]
### Bug description

#5436 adds a Value Wrapper to replicator/grid/bard fields that breaks the pluck modifier oh them.

### How to reproduce

Simple example:
```
{{ replicator|pluck('type')|dump }}
```
results in an ```Method Statamic\Fields\Values::get does not exist.``` error.

### Versions

3.3.0-beta6
runtime-parser

**Comment by jasonvarga** [comment]
Thanks!
