### ISSUE TITLE
3.3 beta – Weird string with `runtime` parser

### ISSUE THREAD

**Issue by aerni** [statamic/cms#5463]
### Bug description

I've got a SPA kind of site built with [Swup](https://swup.js.org/). After upgrading to `3.3.0-beta.6` and switching to the `runtime` parser, the following string ends up at the bottom of the page: `__literalReplacement::_13315b7a82a97c110028781df31911a6`.

I'm still looking into where this comes from and why it ends up there. But it seems to be connected to the new parser, as it doesn't happen with the `regex` parser.

Just throwing it in here. You might know more?

### How to reproduce

Happy to share the site with you.

### Versions

Statamic 3.3.0-beta.6 Pro
Laravel 8.83.4
PHP 8.0.14
aerni/advanced-seo dev-main
spatie/statamic-responsive-images 2.8.5
visuellverstehen/statamic-classify 2.3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by JohnathonKoster** [comment]
@aerni I wouldn't mind access to the site (will have some time later this evening); and that helps to track these down greatly :)

**Comment by aerni** [comment]
Just invited you. Check out the master branch. Let me know if you need anything more.

**Comment by JohnathonKoster** [comment]
Found it -- will think on what this is trying to do, and how to go about solving it.

Its the part that yields the same section within a section:

```
{{ section:sectionName }}
    {{ yield:sectionName }}
{{ /section:sectionName }}
```

**Comment by aerni** [comment]
Good find! The yield inside the section is to be able to append to the same section if needed.

**Comment by aerni** [comment]
There's also another error I get that looks like it's connected to the new parser too. Should trigger on page `/work/hyve`.

**Comment by robdekort** [comment]
> Good find! The yield inside the section is to be able to append to the same section if needed.

You could probably use stacks for now: https://statamic-3-dot-3.netlify.app/new-antlers-parser/#stacks
