### ISSUE TITLE
3.3 beta - Live preview on unpublished items returning a 404

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#5484]
### Bug description

When you have an unpublished entry and try to use Live Preview you get a 404.

Personally I'd expect an unpublished entry to also resolve with 200 on it's own url while you are logged in. It seems this not working (anymore) is an intended change as folks found it confusing:  #4248. I remember WP also doing this. Maybe it should be configurable?

### How to reproduce

1. Make an entry unpublished
2. Hit live preview

### Versions

3.3 beta 6
No addons

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
It should be visible in live preview, this is a bug.
