### ISSUE TITLE
Asset collection never updated in Horizon worker

### ISSUE THREAD

**Issue by tomhelmer** [statamic/cms#5501]
### Bug description

When running Horizon the AssetContainerContents is set when the Horizon worker is started.
The collection is never updated. Adding an asset will not be reflected in the collection of files.
An asset will run Asset->exists() which check if the asset is in it's collection. As the collection is not updated a newly added asset will return false from Asset->exists()

### How to reproduce

- Setup Horizon
- Add a form with a attachment upload field
- Add a email to the form and enable "Attach uploaded assets to this email"

- Submit the form
  - first time it works the attachment is in the email ( the collection is initialized and contains the new file )
- Submit the form again
  - fail.. no attachment is in the email ( the collection is not containing the new file )

### Versions

Statamic 3.2.37 Pro
Laravel 8.83.4
PHP 8.0.16

### Installation

Fresh statamic/statamic site via CLI

**Comment by tomhelmer** [comment]
Update: The asset content is stored with a blink cache 
```
    public function contents()
    {
        return Blink::once('asset-listing-cache-'.$this->handle(), function () {
            return new AssetContainerContents($this);
        });
    }
```
I a long running process as Horizon this will last forever.

Our (ugly) quick fix is to reset the blink cache :

```
/**
     * Send form submission emails.
     *
     * @param  Submission  $submission
     */
    public function handle()
    {

        if (\Illuminate\Support\Facades\Route::current() === null) {
            \Statamic\Facades\Blink::forget('asset-listing-cache-private');
        }

        $this->parseEmailConfigs($this->submission)->each(function ($config) {
            Mail::send(new Email($this->submission, $config, $this->site));
        });
    } 
```

**Comment by tomhelmer** [comment]
Have anyone had a chance to look at this ? We are still having issues. With the above patch it's a bit better but still sometimes the attachement fails.

The issue in https://github.com/statamic/cms/issues/5933 relevant from 3.3.7 does not makes things better. 

Uploading assets in forms is currently not in a working state.

**Comment by jesseleite** [comment]
Hey @tomhelmer, This should be fixed in #6726 now! Would you be able to pull those changes and give it a test on your end, maybe via [composer patch](https://rias.be/blog/using-composer-patches)?

**Comment by tomhelmer** [comment]
Hi @jesseleite

I have tested the changes and my initial comment is that a Horizon worker returns "horizon:work" so the check should include this. 

```
    public static function isWorker()
    {
        if (! App::runningInConsole()) {
            return false;
        }

        return Str::startsWith(Arr::get(request()->server(), 'argv.1'), ['queue:', 'horizon:']);
    }
```

I will test some some with this change included.

**Comment by tomhelmer** [comment]
Hi Jesse

I just got around to the this properly.

- I have en simple email set up where "Attach uploaded assets to this email." is selected and there's 1 asset field.
- The mails are processed by Horizon

First time I submit the file looks fine, second time it's not present in the mail.

I have added a ray() debug line in vendor/statamic/cms/src/Forms/Email.php : addAttachments() line 123

Andre here's the output :




Regards Tom

**Comment by jasonvarga** [comment]
FYI @tomhelmer you said "here's the output" but showed nothing.

**Comment by tomhelmer** [comment]
Hi's it's an image... maybe something is filtering it out.

Tom

**Comment by tomhelmer** [comment]
Hi Jason

The output from ray in protected function addAttachments()

    ->each(function ($field) {
                $value = $field['value']->value();
                ray($value->get(), $field['value']->raw());
Is :

Statamic\Assets\AssetCollection {#2997 ▼
  #items: array:1 [▶]
  #escapeWhenCastingToString: false
}
Email.php:119

array:1 [▼
  0 => "daisy-1666621422.jpeg"
]
Email.php:119

Statamic\Assets\AssetCollection {#4147 ▼
  #items: []
  #escapeWhenCastingToString: false
}

Email.php:119
array:1 [▼
  0 => "daisy-1666621440.jpeg"
]

As you can see the $value->get()returns 0 items second time it's called.

The raw value is ok.

Tom

**Comment by jesseleite** [comment]
Hey @tomhelmer, Sorry for the delay on this one! Take a look at https://github.com/statamic/cms/pull/7467, which should fix the issue your issues "[the] second time it's called" from within a queue worker 👍

**Comment by tomhelmer** [comment]
Hi @jesseleite I'll test this tomorrow. I have been busy getting a custom search driver to work with 3.4 on the site where I see this issue.

**Comment by tomhelmer** [comment]
Hi @jesseleite I did test this today and my issue has been resolved.
