### ISSUE TITLE
New Antlers – Support hyphens in variable names

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#5510]
### Bug description

{{ fa-icon }} outputs `0` instead of the value.
With the regex version all works fine.

### How to reproduce

content.md
```
fa-icon: comments-question-check
```
template.antlers.html
```
<span class="fa-icon fa-light fa-{{ fa-icon }} w-8 text-center pt-1"></span>
```
output
```
<span class="fa-icon fa-light fa-0 w-8 text-center pt-1"></span>
```

### Versions

Statamic 3.3.0 Pro
Laravel 8.83.5     
PHP 8.0.12

### Installation

Fresh statamic/statamic site via CLI

**Comment by jackmcdade** [comment]
You should switch to using underscores for variable names: `fa_icon` and `{{ fa_icon }}` will work just the way you expect!

**Comment by jasonvarga** [comment]
It's doing subtraction - trying to to `fa minus icon`. We'll make a note that dashes shouldn't be used for variable names.

**Comment by wm-simon** [comment]
Thanks for your feedback. I just use the dash for this icon field, I don't know why... But I use it on every page I have ...
Will the regex parser be removed in the next months/years? I don't know, if it makes sense to change the field name on every website or just stay with the old parser for now.

**Comment by jackmcdade** [comment]
We can support it, it just never was a recommendation to do it :) Give it a few days and i'll be sorted.

**Comment by j3ll3yfi5h** [comment]
@wm-simon Thank you! At first I thought I was the only one who did that... 🤦🏼‍♂️
