### ISSUE TITLE
3.3 Runtime Parser: Variables that work in Rexex parser don't work in the Runtime parser

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#5514]
### Bug description

Testing one of my addons on 3.3 before I tag it's next release and I've spotted a bug around variables when I'm using the Runtime parser - it works when I'm using the Regex parser.

Inside one of my templates, I do `{{ sc:checkout }}` which makes available all of the relevant variables. Inside that, I do `{{ sc:gateways }}` which then loops through the available gateways. 

`gateway-config` is an array available when looping through gateways. Inside that are two keys: `key` and `secret` for some Stripe stuff, in this case.

![image](https://user-images.githubusercontent.com/19637309/158468751-ba769537-ba40-4627-b841-078d0f981531.png)

Essentially, the issue is that instead of outputting the `key` from the `gateway-config` array, I'm getting a `0` back... If I switch to the regex version, it works and gives me the key like it should.

```js
var stripe = Stripe('{{ gateway-config:key }}');
var elements = stripe.elements();
```

### How to reproduce

1. Install the [Simple Commerce starter kit](https://statamic.com/starter-kits/double-three-digital/sc-starter-kit)
2. Setup the [Stripe gateway](https://simple-commerce.duncanmcclean.com/gateways/stripe)
3. Enable the Runtime parser
4. Add a product to your cart and follow through to the payment step.
5. Inspect the HTML, you'll see a `0` is outputted. 
6. Switch to the Regex parser and reload the page. Your key will be outputted as expected.

### Versions

Statamic 3.3.0 Pro
Laravel 8.83.5
PHP 8.0.16
doublethreedigital/duplicator 1.2.6
doublethreedigital/sc-digital-products 2.0.4
doublethreedigital/simple-commerce 2.4.0

### Installation

Starter Kit using via CLI

**Comment by jackmcdade** [comment]
Looks like it's the same issue as this one: https://github.com/statamic/cms/issues/5510

**Comment by duncanmcclean** [comment]
Doh! Should have checked other issues first - sorry!

**Comment by jackmcdade** [comment]
No worries!
