### ISSUE TITLE
Variables in anonymous blade components

### ISSUE THREAD

**Issue by axlf** [statamic/cms#5515]
### Bug description

I tried to use variables like the new ```$page``` or ```$site``` in an anonymous blade component. It has no access.

 

### How to reproduce

- Create a layout file `resources/views/components/guest.blade.php`
```
<div>
    Short locale: {{ $site->short_locale }}
    <div>{{ $slot }}</div>
</div>
```

- Create a template file `resources/views/home.blade.php`
```
<x-guest>
Foobar
</x-guest>
```

Results in 

```
ErrorException

Undefined variable $site
```

### Versions

```bash
#php please support:details
Statamic 3.3.0 Solo
Laravel 9.5.1
PHP 8.1.2
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Unless I'm misunderstanding, I don't think components are supposed to just inherit all the variables. You need to pass them in.

```blade
<x-guest site="{{ $site }}">
Foobar
</x-guest>
```

**Comment by axlf** [comment]
🙈 I'm sorry, how could I have missed that?
Thank you!
