### ISSUE TITLE
Can't save taxononmy (Slug field is broken)

### ISSUE THREAD

**Issue by ruslansteiger** [statamic/cms#5522]
### Bug description

When I try to save a new taxonomy it does say that the slug is required. I have no way to save the taxononmy.

### How to reproduce

I used the statamic CLI to create a fresh `3.3` project. See video:

https://user-images.githubusercontent.com/14092921/158609754-98d9b3c4-f603-43b8-9112-8bc1d45a736b.mov

### Logs

No errors in the logs.

### Versions

Statamic 3.3.0 Solo
Laravel 9.5.1
PHP 8.1.3
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by ruslansteiger** [comment]
Thank you @jasonvarga. It works again on v3.3.1 😘 fantastic job

**Comment by ddm-studio** [comment]
Having the same issue on Statamic 3.2.38. Will this fix also be included in v3.2?
We can not yet upgrade to v3.3 since there are some breaking changes that need to be handled and our customer can't create any taxonomy terms right now.

**Comment by jackmcdade** [comment]
@ddm-studio We can certainly consider it – what breaking changes need to be "handled" though?

**Comment by ddm-studio** [comment]
@jackmcdade That would be great!
ad breaking changes: The customer project I was talking about has a lot of backend programming included. The changes in [augmentation methods and property access](https://statamic.dev/upgrade-guide/3-2-to-3-3#property-access-on-items-now-performs-augmentation) need to be implemented in this project.

**Comment by jasonvarga** [comment]
This is fixed in 3.2.39 now too.
