### ISSUE TITLE
Dirty errors switching between sites in multisite

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#5526]
### Bug description

When switching between sites a grid field inside a bard field will throw dirty "are you sure you want to leave this page?" popups.

### How to reproduce

Install the Multisimplicity Starter Kit, edit any entry, and switch between sites. It's possible that the grid inside bard is a red herring as [this conversation on Discord](https://discord.com/channels/489818810157891584/746357770957357116/953672154908610651) says it happens on empty sites, but I was able to make the error in Multisimplity go away by just removing the Grid field. 🤷‍♂️

### Versions

Statamic 3.3

### Installation

Starter Kit using via CLI

**Comment by SirNovi** [comment]
After installing a fresh 3.3.0 (running php 8.1) and switching to multi-site this problem appears after making changes to the default content field (type: markdown) in another site and it also appears when the slug field gets localised. Localising the template field does not lead to the problem.

**Comment by SirNovi** [comment]
Probaby related to #4958 as well

**Comment by adevade** [comment]
Yes, I put up a repo that illustrates this problem: https://github.com/adevade/statamic-unsaved-changes-bug

Previously linked in https://github.com/statamic/cms/issues/4958#issuecomment-1023239205

1. Navigate to `/cp/collections/pages/entries/home`
2. Login with `admin@example.com` and `password`
3. Switch between the sites under the Published switch.
4. See that the alert comes up telling you that unsaved changes will be lost.
5. Change slug on `another` and `last` to be the same as Statamic (`home`), and see that the alert does not show anymore.

**Comment by SirNovi** [comment]
Is this on a roadmap? 

Need to decide if we are going with Statamic or something else for a multi-language project and we don't feel like handing over a system that feels buggy.
