### ISSUE TITLE
`form` tag does not provide useful data to Blade

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#5534]
### Bug description

The `{{ form:x }}` tag in Antlers provides access to all the variables like `success`/`errors` and the `fields` array etc. If you call the same tag from Blade using `Statamic::tag('form:x')->fetch()` you just receive an HTML string containing the opening and closing `<form>` tags.

It would be great if there was an easy way to access all the same data necessary to build the form in Blade such as:

- Success information
- Error bag
- Fields array
- honeypot field name
- Any other hidden field values (redirect etc.)

[As Jason mentioned](https://github.com/statamic/cms/discussions/5533#discussioncomment-2374623) this probably affects all tags that work the same way. The user form tags like `user:login_form` and `user:register_form` come to mind, but there may be others.

### How to reproduce

Use the `Statamic::tag('form:x')->fetch()` tag in Blade.

### Versions

Statamic 3.3.0 Pro
Laravel 9.5.1
PHP 8.0.15

### Installation

Existing Laravel app

**Comment by jackmcdade** [comment]
@jasonvarga What if we added some extra methods, like `->url()` for the action param, and `->success()` etc etc?

**Comment by jacksleight** [comment]
Closed in https://github.com/statamic/cms/pull/5892
