### ISSUE TITLE
Variables should override tags (Antlers Runtime)

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#5545]
### Bug description

The link fieldtype with the runtime enabled, seems to spit out null instead of the link. If you do a dump, you can see though, that the value is present (inside a value object).

### How to reproduce

Create a link fieldtype (my handle is ``link``), and see that it works as expected with the regex parser. As soon as you switch over to the runtime, it doesn't work.

### Versions

Statamic 3.3.1 Pro
Laravel 9.5.1
PHP 8.0.13
No addons installed

### Installation

Existing Laravel app

**Comment by JohnathonKoster** [comment]
Does it work if you use `{{ $link }}` instead with the Runtime parser? The Runtime version will prioritize tags first when there is a collision.

**Comment by AndreasSchantl** [comment]
That works! Don't know though what the expected behaviour should be in cases as such. But I am satisfied for now with this solution.

**Comment by AndreasSchantl** [comment]
It doesn't seem to be consistent though. Here, inside a global for example, it works as expected:
```html
{{ general:quicklinks }}
    <li>
        <a href="{{ link }}">
            {{ name }}
        </a>
    </li>
{{ /general:quicklinks }}
```

**Comment by jasonvarga** [comment]
I can't reproduce this. It just always seems to work.

Can you provide any more details?

I've:
- Enabled the runtime parser.
- Added a field named `link` of type `link` to my entry's blueprint.
- Chose an entry using the fieldtype.
- Added `{{ link }}` to my template.

The `{{ link }}` outputs the value I'd expect.

@JohnathonKoster you must have been able to reproduce this, what am I missing?

**Comment by AndreasSchantl** [comment]
I don't know if it helps, but in my case I have it inside a replicator field.

**Comment by jasonvarga** [comment]
Thank you, but still seems fine in a Replicator. Are you using partials?

**Comment by AndreasSchantl** [comment]
Well, to be very precise. I have a Page Builder as a fieldset that is a replicator. And in it is a replicator using the link fieldtype. It's used within a partial like this:

```html
{{ if link || pdf }}
    <div>
        {{ if link }}
             <a href="{{ link }}"></a>
        {{ /link }}
    </div>
{{ /if }}
```html
simplified version of the partial

**Comment by JohnathonKoster** [comment]
@jasonvarga I've created a repo here https://github.com/Stillat/antlers-tags-vs-variables that can reproduce this issue. Before the fix, the field _would_ be visible inside a replicator/Bard/grid/etc., but the Runtime would get confused when moving into nested tags (like a partial).

Swapping the logic to be var-first resolved this issue (as well as removing the specialized checks it was doing before). Once loaded, you should be able to go to `/dance` to reproduce the previous behavior (labeled A) and the new variable first behavior (labeled B).
<img width="659" alt="before_after" src="https://user-images.githubusercontent.com/5232890/159381312-09efd4d8-d92e-4b45-99f5-2d3958ce77a6.png">

**Comment by jasonvarga** [comment]
I see, you need to actually have the field in the blueprint, as well as being inside a replicator. Adding a value into the yaml isn't enough to trigger anything. Thanks!

**Comment by jasonvarga** [comment]
@JohnathonKoster I can confirm your fix does fix it, but I noticed something interesting.

In your example `show` template, if I remove this `date` variable, the replicator loop worked before (without the fix):

https://github.com/Stillat/antlers-tags-vs-variables/blob/422cb51f5141171dc570f9c019245e5aa4bdf92e/resources/views/articles/show.antlers.html#L10

Regardless, again, on the PR branch, it works fine anyway.
