### ISSUE TITLE
User activation broken when session middlewares are disabled

### ISSUE THREAD

**Issue by rrelmy** [statamic/cms#5547]
### Bug description

The `/!/auth/activate/**token**` page is broken when session middleware have been disabled in the `web` routes.

### How to reproduce

1. Disable session middlewares in web
2. Create user in CP
3. Open `/!/auth…` link
4. See 500 error message

We have a website with a fully static frontend, therefore all session related middleware have been disabled.

In `app/Http/Kernel.php`
``` php
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
#            \Illuminate\Session\Middleware\StartSession::class,
#            \Illuminate\Session\Middleware\AuthenticateSession::class,
#            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
#            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
```

It would be ideal to have better control over the middlewares running in the actions `/!/`, indepentend from the frontend

### Logs

```shell
(ErrorException(code: 0): Undefined variable $errors at /srv/users/remy/apps/remy/storage/framework/views/be649e2c1fc5db2c683a40b855d1c7ad4ffb03dc.php:22)
[stacktrace]
#0 /srv/users/remy/apps/remy/storage/framework/views/be649e2c1fc5db2c683a40b855d1c7ad4ffb03dc.php(22): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined varia...', '/srv/users/remy...', 22)
#1 /srv/users/remy/apps/remy/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/srv/users/remy...')
#2 /srv/users/remy/apps/remy/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
```

### Versions

Statamic 3.2.38 Pro
Laravel 8.83.5
PHP 8.0.16
4rn0/statamic-v3-image-optimizer 1.0.8
appswithlove/firebase-cloud-messaging 3.0.0
appswithlove/smms-messaging dev-develop
appswithlove/statamic-cp-language-selector dev-develop
brylin/cache-offer-data dev-develop
brylin/import-offers dev-develop
brylin/publish-entries dev-develop
statamic/seo-pro 2.3.2

### Installation

Starter Kit using via CLI

**Comment by rrelmy** [comment]
> Is the app really fully static if it gets bootstrapped every request?
It's a bit complicated :-D

We use `STATAMIC_STATIC_CACHING_STRATEGY=half` and a nginx microcache in front of it.

**Comment by jasonvarga** [comment]
Are you using the control panel on that server? How are you authenticating?

**Comment by rrelmy** [comment]
Yes, control panel is used on the server. Login and everything works without issues as the control panel as it contains the middlewares in the `statamic.cp` group.

Of course it is excluded from the cache

**Comment by jasonvarga** [comment]
Ah sorry it slipped my mind that our action routes are _inside_ our web routes. I see your problem.

You can workaround it by dropping this in your AppServiceProvider:


```php
use Illuminate\Support\Facades\Route;
use Statamic\Statamic;
use Statamic\Support\Str;

Statamic::pushActionRoutes(function () {
    collect(Route::getRoutes()->getRoutes())
        ->filter(fn ($route) => Str::startsWith($route->uri(), '!'))
        ->each(fn ($route) => $route->middleware([
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
        ]));
});
```

You're just popping whatever necessary middleware you need onto each action route.
You use the `pushActionRoutes` because it'll get called after all the routes are registered (even though you aren't pushing any new routes).

**Comment by rrelmy** [comment]
Thanks, I can confirm this worked.

Didn't come to my mind to fix it like that :-)

**Comment by jasonvarga** [comment]
Awesome. You can open an issue in the ideas repo if you're not satisfied with this workaround, but I'm closing this for now.
