### ISSUE TITLE
Antlers Stacks (v3.3) could use a more helpful error message when used in the wrong direction

### ISSUE THREAD

**Issue by theutz** [statamic/cms#5548]
### Bug description

When trying to use the new stacks feature, I kept running into the following error:

```
Undefined array key "<a UUID that changed with each request>"
```

I narrowed the problem down to the new stacks feature. It seems that stacks defined and/or referenced in a different file than their defined throws this error. Which, unfortunately, makes the feature practically useless at the moment. :(

### How to reproduce

1. Check out this repo: https://github.com/theutz/stack-example 
2. Look at the `home.antlers.html` and `layout.antlers.html` file.
    - The goods are at this commit: https://github.com/theutz/stack-example/commit/267c61894b57d4e97c3ccaaa751cce93f7ccea01
3. Run the site and enjoy the fancy Ignition exception screen. :)

### Versions

Statamic 3.3.1 Solo
Laravel 9.5.1
PHP 8.1.2
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
I think you want to be using `{{ stack:example }}` in your layout and `{{ push:example }}` in your template.

**Comment by theutz** [comment]
Ah! Right you are! It does seem to work in that direction. In my opinion, then, [this paragraph from the documentation](https://statamic.dev/new-antlers-parser#stacks) is a bit misleading:

```
Antlers allows you to push to named stacks which
can be rendered somewhere else in another view or
layout. This can be particularly useful for specifying any
JavaScript libraries required by your child views:
```

Additionally, the exception that's thrown doesn't give a very good indication of the underlying problem.

If I'm not mistaken (and apparently I may be...), this existing [stack addon](https://statamic.com/addons/joe-tannenbaum/stack) did not have that particular restriction. What do you think?

**Comment by jackmcdade** [comment]
@JohnathonKoster – might it be possible to provide a better error here when stacks are used incorrectly in the reverse direction?

**Comment by JohnathonKoster** [comment]
Absolutely! Will look into improving that experience 🙂

**Comment by theutz** [comment]
Awesome! Thanks, y'all!

**Comment by theutz** [comment]
For what it's worth, I did a bit more experimenting and realized the exception seems to appear any time there is no `{{ push }}` corresponding to the `{{ stack }}` tag. For instance, if I do this:

```
{{ stack:example }}
```

Then I get the unfriendly exception. But, if I do this:

```
{{ push:example }}
{{ /push:example }}
{{ stack:example }}
```

Then I don't. It seems to essentially be an uninitialized value, I suppose.

I hope this helps the debugging, @JohnathonKoster ! I'm a tremendous fan of the work you put in on this rewrite!

**Comment by JohnathonKoster** [comment]
Thanks for all the additional information, it helps a lot!
