### ISSUE TITLE
Live preview renders wrong view when creating entry/term

### ISSUE THREAD

**Issue by aerni** [statamic/cms#5550]
### Bug description

The live preview doesn't render the template view when creating an entry or term. It just renders the create view instead.

<img width="1840" alt="Bildschirmfoto 2022-03-17 um 10 50 35" src="https://user-images.githubusercontent.com/23167701/158865496-0324ea9b-34b9-46b9-b63c-887e51418ffd.png">

### How to reproduce

Go to the live preview while creating an entry or term.

### Versions

Statamic 3.3.1 Pro
Laravel 8.80.0
PHP 8.0.14
aerni/advanced-seo dev-main
aryehraber/statamic-impersonator 2.4.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by aerni** [comment]
No it doesn't. I just whipped up a fresh site right now with the Statamic CLI. Same issue.

**Comment by jasonvarga** [comment]
You're right, I see the same thing on a fresh site. 👍

**Comment by jasonvarga** [comment]
Funnily enough, this happens on 3.2 too.

It's the same problem as #4966 except on 3.2 you'd get an error/blank page, and on 3.3 you get the create page.

**Comment by mmodler** [comment]
We see this issue in v3.3.31too. Its very confusing for the content editor, because the workflow is often edit - preview - save when good.

**Comment by espenlg** [comment]
Still a problem in v3.4.5.
