### ISSUE TITLE
Live Preview jumps to top

### ISSUE THREAD

**Issue by ruslansteiger** [statamic/cms#5564]
### Bug description

The live preview is always jumping to the top of the screen. See video:

https://user-images.githubusercontent.com/14092921/159039735-6dbf6441-897e-4b4e-bf27-e48c448b134e.mov

### How to reproduce

Create fresh statamic project and try the live preview.

### Logs

```shell
No errors in the logs.
```

### Versions

Statamic 3.3.1 Solo
Laravel 9.5.1
PHP 8.1.3
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by strebl** [comment]
It's not implemented with the new live preview mode. There is even a to-do comment: https://github.com/statamic/cms/blob/3.3/resources/js/components/live-preview/UpdatesIframe.js#L15
