### ISSUE TITLE
Parent tag pair 

### ISSUE THREAD

**Issue by wesort** [statamic/cms#5565]
### Bug description

Using the `parent (url)` and `parent tag pair` should return the same output as `parent single variables` as per the docs. 
https://statamic.dev/tags/parent

Parent URL: outputs nothing
Single variables: works as expected
Tag Pair: outputs homepage

### How to reproduce

**Content:**
```
---
parent: 64ab5c1b-0e3c-42f1-8692-96fabdb5a0dd
---
```
NB: the `id` is from Stills (collection).

**Templating:**
```
<div>parent: {{ parent }}</div>
<div>single variable: <a href="{{ parent:url }}">{{ parent:title }}</a></div>
<div>tag pair: {{ parent }}<a href="{{ url }}">{{ title }}</a>{{ /parent }}</div>
```

**Output:**
```
<div>parent: </div>
<div>single variable: <a href="/test-parent">Test parent</a></div>
<div>tag pair: <a href="/">Home</a></div>
```
NB: the output from the tag pair templating are from the Pages (collection), ie: not from Still collection

### Versions

**Statamic** 3.3.1 Pro
**Laravel** 9.5.1
**PHP** 8.0.16
**aryehraber/statamic-uuid** 2.1.0
**doublethreedigital/duplicator** 2.1.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by joshuablum** [comment]
Similar problem occurred for someone on GitHub. Which parser are you using? The old `regex` or new `runtime` one?

**Comment by joshuablum** [comment]
If you are using the new `runtime` parser please try using `{{ %parent }}`

Explanation from @JohnathonKoster:
With Runtime, if a variable exists it will always use that first. If a matching variable is not found, it then uses the tag (variables are still given priority even if they are `null`).

```
{{# To force something to be a variable and disable the tag fallback #}}
{{ $variable_name }}

{{# To force something to be a tag and ignore variables. #}}
{{ %tag_name }}
```

When using that syntax, the prefix will come after the `/` for closing tags:

```
{{ $variable_name }} {{ /$variable_name }}
{{ %tag_name }} {{ /%tag_name }}
```

**Comment by jackmcdade** [comment]
The parent tag doesn't take a parameter, it just fetches the parent data (e.g. the page above the current page – removing the last segment). What you want here is either an Entries field (not named `parent`) so augmentation lets you work with the data directly, or the `get_content` tag and you can pass that id in and fetched the content.
