### ISSUE TITLE
`taxonomy` variable causes exception

### ISSUE THREAD

**Issue by JohnathonKoster** [statamic/cms#5570]
### Bug description

Having a variable named `taxonomy` will throw:

```
Statamic\Exceptions\TaxonomyNotFoundException Taxonomy [] not found
```

### How to reproduce

Inject a variable named `taxonomy` and attempt to use it as a string `{{ taxonomy }}`.

### Versions

Statamic 3.3.1 Pro
Laravel 8.83.5
PHP 8.0.12

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Extracted from https://github.com/statamic/cms/issues/5560

**Comment by jasonvarga** [comment]
I get the `Taxonomy [] not found` error when there is **no** variable named `taxonomy`. This seems expected as it's trying to run the taxonomy tag without me specifying which one.

When I add a variable of `taxonomy: foo`, then `{{ taxonomy }}` just outputs `foo` as I'd expect.

What am I missing?

**Comment by JohnathonKoster** [comment]
I've created a repo here: https://github.com/Stillat/antlers-tags-vs-variables (specific template file https://github.com/Stillat/antlers-tags-vs-variables/blob/main/resources/views/articles/show.antlers.html#L18).

Once pulled, you should be able to go to `/dance` and trigger the error. Swapping to the updated branch should resolve the issue here. I was able to successfully reproduce this issue by creating the `taxonomy` field and _not_ add anything to it within the entry.
