### ISSUE TITLE
Site in Vuex store is undefined for Taxonomy Term creation

### ISSUE THREAD

**Issue by skr-24** [statamic/cms#5573]
### Bug description

Seems to be the same bug as described here https://github.com/statamic/cms/issues/2237 but with taxonomy term creation

<img width="800" alt="" src="https://user-images.githubusercontent.com/9319520/159142553-211d76f1-4a61-4d20-ac9e-17e6c2f9c826.png">

### How to reproduce

Just installed fresh project, added logo to blueprint and tried to create new taxonomy term

### Versions

PHP Version - 7.3.29
Statamic - 3.2.38
Installed method - statamic new project

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
This issue has been fixed by #5738.
