### ISSUE TITLE
broken translation with Laravel 9

### ISSUE THREAD

**Issue by jimblue** [statamic/cms#5578]
### Bug description

Statamic can't found the translation from the lang folder since I've upgrade to Statamic 3 and Laravel 9.

### How to reproduce

As the [Laravel 9 migration guide](https://laravel.com/docs/9.x/upgrade#the-lang-directory) says the lang folder must be moved from resources to the root.
But doing that breaks all Statamic translations.

### Versions

Statamic 3.3.2 Pro
Laravel 9.5.1
PHP 8.1.4
4rn0/statamic-v3-image-optimizer 1.0.8
handmadeweb/statamic-cloudflare 1.0.5
statamic/seo-pro 3.1.0

### Installation

Existing Laravel app

**Comment by jasonvarga** [comment]
You'll need to give more details. What exactly does "broken" mean?

**Comment by jimblue** [comment]
Sure, I think the exact term is not broken but not found as I do not get error.
Instead in the front it returns the `key`.

For exemple with the following in Antlers template  `{{ trans:theme.blog.reading_time }}`
I get in the front: `theme.blog.reading_time`

**Comment by jasonvarga** [comment]
Seems to work fine for me.

For a tag with `{{ trans:theme.blog.reading_time }}` I would expect to find the translation at `lang/en/theme.php` with the contents:

```php
<?php

return [
  'blog.reading_time' => 'Reading Time',
];
```

Perhaps its the actual language folder that's the issue? e.g the `en` folder. What's in your `config/statamic/sites.php` file?

**Comment by jimblue** [comment]
Yep I've check it should work, the locale value is **en**.

I made a screenshot showing everything in one shot.

<img width="1680" alt="Screenshot 2022-03-21 at 19 09 49" src="https://user-images.githubusercontent.com/10623367/159337278-7e91d052-8e31-4c86-ba26-9fa4482fcc61.png">

**Comment by jimblue** [comment]
If I move back all my translation files in `resources/lang` it's working again.

**Comment by jimblue** [comment]
My Statamic Pro licence was out of date. I just update it and it's working again.
