### ISSUE TITLE
Nav tag: include_home not working (3.3 - new Antlers parser)

### ISSUE THREAD

**Issue by jensolafkoch** [statamic/cms#5580]
### Bug description

When switching to the new Antlers parser, the include_home parameter does not work like in this code snippet (here with explicit parameter – I know it's the default anyway):

```
 {{ nav:collection:seiten include_home = "true" }}

                <a href="{{ url }}">
                    {{ title }}
                </a>

 {{ /nav:collection:seiten }}
```

The designated home page is skipped.

### How to reproduce

Have a designated home page in a nav and switch the parser.

### Versions

Statamic 3.3.2 Solo
Laravel 9.5.1
PHP 8.0.16
doublethreedigital/duplicator 2.1.1
geekish/statamic-ray 1.0.0
jonassiewertsen/statamic-livewire 2.9.0

### Installation

Existing Laravel app

**Comment by jasonvarga** [comment]
Do `include_home="true"` instead of `include_home = "true"`. It's that weird spacing that is causing it to not work.

**Comment by jensolafkoch** [comment]
Yes and no:

Changing the spacing works when the parameter is present.

If it is ommitted it does NOT work: Docs say that "true" is the default for include_home, but omitting it does break the functionality and the home page is not included.

**Comment by jasonvarga** [comment]
The docs say that the default is false. https://statamic.dev/tags/nav#parameters

![image](https://user-images.githubusercontent.com/105211/159269907-68f23fc6-4f1c-4201-8030-b0579bd5bb6b.png)

Where are you seeing that it says the default is true?

**Comment by jasonvarga** [comment]
No problem!
