### ISSUE TITLE
Users Tag filter by parameter

### ISSUE THREAD

**Issue by davidatkinswwt** [statamic/cms#5584]
### Bug description

I am able to render all the users on my site using the {{ users }} tag. 
After which I add the group filter parameter and nothing renders out.

Following the documentation on https://statamic.dev/tags/users

The group is linked to the user. 
I have tried this on a test project with the same outcome. 

Thanks!

```
// staff.antlers.html

{{ users group="staff" }}
  <div>
    {{ name }}
  </div>
{{ /users }}
```

### How to reproduce

Create a user, assign an existing group, try to render the list of users using the {{ users }} tag with the parameter of your assigned group. 

```
// staff.antlers.html

{{ users group="staff" }}
  <div>
    {{ name }}
  </div>
{{ /users }}
```

### Versions

Statamic 3.3.2 Pro
Laravel 8.83.5
PHP 8.1.4
aerni/advanced-seo 1.0.2
aerni/fathom 1.0.0
aerni/social-links 2.3.0
aryehraber/statamic-color-extractor 1.2.0
edalzell/forma 1.0
laraluke/statamic-api-select 1.0.0
ritson/placid-statamic 3.1.0
simonhamp/gitamic 1.8.4
transformstudios/events 3.3.3

### Installation

Fresh statamic/statamic site via CLI

**Comment by jackmcdade** [comment]
This is the same issue as #5584 — you can't use modifiers on query builder instances at the moment. We're looking into options to support this though!
