### ISSUE TITLE
Array to string conversion error

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#5592]
### Bug description

Hi, recently updated to 3.3.2 from 3.2.38, using regex antlers at the moment.

My blog home page gives this error Array to string conversion after a bit of digging I found the issue was related to this:

Read time {{ bard | flatten | join | strip_tags | read_time  }} mins
The page loads when I remove that

I found the snippet above on the forum (https://statamic.com/forum/2970-read-time-from-bard-fieldtype) it's dated 2018.

Is there a workaround for this in 3.3?

### How to reproduce

Add this to a view
```
Read time {{ bard | flatten | join | strip_tags | read_time  }} mins
```

### Versions

Statamic 3.3.2 Pro
Laravel 9.5.1
PHP 8.0.8
simonhamp/statamic-heroicons 1.0.1

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by duncanmcclean** [comment]
If you change the Antlers parser to `runtime` (you can do it inside `config/statamic/antlers.php`), does the error keep happening?

**Comment by jasonvarga** [comment]
It happens on both and has indeed changed on 3.3. Confirmed!

**Comment by jackmcdade** [comment]
I don't think this warrants too much attention — though just making the `read_time` modifier work w/ Bard as a whole would be a nice solution/feature addition.
