### ISSUE TITLE
Blade globals not available

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5596]
### Bug description

The [3.3 docs](https://statamic.dev/blade#globals) state that: "There is a variable for each global set, and its fields can be accessed using the same Eloquent style syntax."

I have a global set called 'footer' and I have tried:
@dump($footer) - Undefined variable
@dump($page->footer) - NULL

### How to reproduce

Use blade and try to output a global set.

### Versions

Statamic 3.3.2 Pro
Laravel 9.5.1
PHP 8.0.10
statamic/seo-pro 3.1.0

### Installation

Existing Laravel app

### Additional details

Upgrading to 3.3 is a total pain when using Blade, and the documentation is lacking a lot of details. I've opened an issue on Statamic docs [here](https://github.com/statamic/docs/issues/764).

**Comment by jasonvarga** [comment]
What page are you on when you are editing this template? Is it a regular Statamic route or is it some custom route/controller you've created?

If it's a regular Statamic route, the variables should be there.
If it's something you've created, you need to make sure you've made the variables available. Show how you've created it.

> Upgrading to 3.3 is a total pain when using Blade, and the documentation is lacking a lot of details. I've opened an issue on Statamic docs https://github.com/statamic/docs/issues/764.

Thanks for mentioning it. We see the issue, no need to leave this line on every issue.

**Comment by stuartcusackie** [comment]
@jasonvarga  

I don't have any custom routing or controller logic, and I have doubled checked that the correct Template and Layout are selection in the collection settings. Actually, I'm not sure if template is required for blade.

So yes, It's a regular Statamic route (my routes file has no entries), and the variables are not available.

"Thanks for mentioning it. We see the issue, no need to leave this line on every issue."
- Gotcha. Just making sure. Feeling a little neglected over here in Blade land. :)

**Comment by jasonvarga** [comment]
Does `{{ $social->facebook_url }}` output anything?
Are you trying to do it in a partial or in the template?
Can you enable debug bar and look at the variables available in the view?

**Comment by stuartcusackie** [comment]
`{{ $social->facebook_url }}`
Produces: `Undefined variable $social`

You have pointed me in the right direction: I am using a Blade layout component. Variables are not being passed down to the layout component. I will have to pass down each global set as component variable.

The SEO addon suffers from a similar problem. Blade layout components are a big part of blade so it would be great if Statamic could provide a simple solution to pass all the variables to a blade layout component.

Thanks!

**Comment by jasonvarga** [comment]
You can't* really just pass all the data components as that would defeat the purpose of having the self-contained components.

\* I say you can't but you can. But probably shouldn't. You could Slap this at the top of your view.

```php
@php(View::composer('*', fn($view) => $view->with($__data)))
```

A better solution for you could be to supply all your views with the global sets. You can put this in your AppServiceProvider.

```php
use Statamic\Facades\GlobalSet;
use Illuminate\Support\Facades\View;

View::composer('*', function ($view) {
    GlobalSet::all()->each(fn ($set) => $view->with($set->handle(), $set->inCurrentSite()));
});
```

**Comment by Christophvh** [comment]
since template inheritance will be removed in laravel in the future in favor of doing everything in components, this will be a major issue. Might be useful add something in the docs for the solution that @jasonvarga provided.

**Comment by stuartcusackie** [comment]
I would imagine that Laravel would keep both approaches but this is possible. Have you heard something?

Layout components are fine once you figure out that Statamic globals must be passed to the component, along with other things like $page and $site. The above solution isn't ideal for these variables because you would technically be re-querying for them and taking a performance hit.

It would be nice if Statamic passed it's variables to all blade components by default, and include $page, $site, $globals along with whatever else we might need.
