### ISSUE TITLE
Cannot pass options to blade Statamic::tag

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5597]
### Bug description

I am trying to do this in blade:
`@foreach(Statamic::tag('nav:footer', ['include_home' => true]) as $item)`

but 'include_home' is having no effect. This used to work fine when using the blade directives package.

Thanks.

### How to reproduce

Set up a nav with a root page and try to output that page in a blade nav loop as described above.

### Versions

Statamic 3.3.2 Pro
Laravel 9.5.1
PHP 8.0.10
statamic/seo-pro 3.1.0

### Installation

Existing Laravel app

### Additional details

Upgrading to 3.3 is a total pain when using Blade, and the documentation is lacking a lot of details. I've opened an issue on Statamic docs [here](https://github.com/statamic/docs/issues/764).

**Comment by jasonvarga** [comment]
Nowhere is it documented that you can pass an array in like that.

Here's where it explains how to use tags in Blade: https://statamic.dev/blade#using-tags-with-blade

Either use the tags fluently like this:

```php
Statamic::tag('nav:footer')->includeHome(true);
```

or pass them in as an array through a `params` method:

```php
Statamic::tag('nav:footer')->params(['include_home' => true]);
```

**Comment by stuartcusackie** [comment]
Yes true, but as a Laravel developer I'm used to passing an array of parameters as the second argument to helper functions.

The docs link you have provided doesn't cover includeHome() or params() by the way. 

Thanks.

**Comment by jasonvarga** [comment]
It tells you to chain parameters using a fluent syntax. This this case, `limit` is a parameter, like `limit="3"` in Antlers.

![image](https://user-images.githubusercontent.com/105211/159495083-06b020fe-a174-41d5-bbc6-918de443a6a3.png)

It's not going to explicitly mention `includeHome` as the example isn't going to cover every parameter of every tag.
