### ISSUE TITLE
Headless > Live Preview not working for REST API

### ISSUE THREAD

**Issue by bryantgillespie** [statamic/cms#5609]
## Description
I've got a Nuxt 2.X site that I'm trying to convert over to use Statamic as a headless CMS. 

Live preview is not working for the REST API. It sends the same response even if you pass the `token` back to the API.

Graph QL appears to work correctly.

## Screenshots

**GraphQL**
![ScreenShot 2022-03-22 at 17 36 49@2x](https://user-images.githubusercontent.com/23302570/159580517-b9064de1-5900-449b-bba0-7bfcda844e27.png)

**Rest**
![ScreenShot 2022-03-22 at 17 35 51@2x](https://user-images.githubusercontent.com/23302570/159580330-5c89a668-7406-46db-accd-59b232160329.png)

### How to reproduce

When you pass the `token` sent to the live preview target using the REST API you still get the same response from the API.

### Versions

Statamic 3.3.2 Pro
Laravel 9.5.1
PHP 8.0.15

### Installation

Starter Kit using via CLI

**Comment by duncanmcclean** [comment]
I wonder if the live preview response is being cached - I think there was a similar problem with GraphQL during the beta. (could be wrong)

**Comment by bryantgillespie** [comment]
> I wonder if the live preview response is being cached - I think there was a similar problem with GraphQL during the beta. (could be wrong)

I had looked at that as well because my first thought was user error. But all the tests I tried were with the `cache` set to `false` within the api.php config.

![Uploading ScreenShot 2022-03-22 at 22.20.33@2x.png…]()

**Comment by jasonvarga** [comment]
Bizarre, I was so sure I added it to the REST API in that initial PR, but I see no trace of it.

**Comment by bryantgillespie** [comment]
You're too fast man 🤣 
Thanks for getting this knocked out.
