### ISSUE TITLE
Translation Loader doesn't utilize fallback_locale

### ISSUE THREAD

**Issue by torian257x** [statamic/cms#5610]
### Bug description

When I open the Roles & Permissions page I see a javascript error in the console... not sure what or if that breaks something

My main issue is I notice that the keys are not translated

![image](https://user-images.githubusercontent.com/2072058/159586873-5a8d435b-6640-47c2-9a72-b69286df7dc1.png)
![image](https://user-images.githubusercontent.com/2072058/159586894-c218162b-2219-4e35-ae12-4fc709b61b1e.png)

### How to reproduce

problem with keys exists in multiple places:
go to cp/console/roles/editor/edit

there is no javascript error on this page

i see the keys and translations exist in `statamic/cms/resources/lang/en/messages.php`

![image](https://user-images.githubusercontent.com/2072058/159587129-e2ab3a3a-d395-4637-bfdb-e629577bab46.png)

### Logs

```shell
there are no log entries
```

### Versions

Statamic 3.2.38 Pro
Laravel 8.83.3
PHP 8.0.15
edalzell/blade-directives 3.5.2
optimoapps/statamic-bard-text-align 1.0.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Regarding the JS error, if you update to [v3.2.39](https://github.com/statamic/cms/releases/tag/v3.2.39) or 3.3, that error should go away.

**Comment by torian257x** [comment]
ok thank you... any ideas about the translation issue?

**Comment by duncanmcclean** [comment]
Not sure about that one, sorry!

**Comment by torian257x** [comment]
any ideas where you would start debugging it?

**Comment by torian257x** [comment]
so praise the lord who made `Statamic.$config.get('translations')` accessible from console in cp. That way I noticed all translations are empty, almost all.

when reading here:
https://statamic.dev/cp-translations#configuration

I notice: fallback_locale and locale. Our locale is on el e.g. greek. Statamic does not have translation in greek.
fallback_locale is set on `en` but somehow, statamic cannot pick them up.

switching the locale to `en` in `app.php` fixes the issue... BUT: we don't want to do this.
We want the locale to be `el` and the fallback_locale working. Does that make sense?


Your bug is here:

https://github.com/statamic/cms/blob/3.3/src/Extensions/Translation/Translator.php#L53
you call load. Is wrong, should be parent::get afaik. load literally does only load, no fallback as there is no argument for that and no code for it either. 


`$value = $this->loader->load($this->locale, $name, $namespace);`

so either imho call parent::get or duplicate the code for the fallback logic somehow yourself

@duncanmcclean can you confirm this please?
