### ISSUE TITLE
Errors when attempting to dynamically output year within markdown field

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#5624]
### Bug description

When attempting to use the new Antlers parser, I ran into an issue with my footer partial. It took a bit to track down, because the error pointed to the wrong part of the file, but I eventually tracked it to my global copyright field, specifically this function in the field: `{{ now format="Y" }}` (note: this field has existed in this way for awhile, so the bug is new)

The resulting error is:

```
Facade\Ignition\Exceptions\ViewException
[ANTLR_069]: Unexpected operator while parsing input text. Line 1 char 18.
```

No matter what is on line one, it still says Line 1 char 18, so that may be a separate bug that it’s not reporting the error in the correct place.

On Erin’s suggestion, I tried `{{ now | format("Y") }}` which changed the error a bit:

```
Facade\Ignition\Exceptions\ViewException
[ANTLR_060]: Unexpected [T_AND] while parsing argument group. Line 1 char 12.
```

And again, Line 1 char 12 isn’t the correct location in the file.

Both of these statements work directly in the template, just not in the content field.

### How to reproduce

1. Upgrade to 3.3 and enable the new runtime antlers parser.
2. Create a markdown field (in my case a global, although I’m not sure it matters), and enable Antlers processing for it.
3. Include a {{ now }} statement in the field content. I’m not sure if there will be issues with other antlers tags, but I know this one is an issue.
4. Output the field with or without the markdown modifier. It doesn’t matter.

Note, in testing, I discovered a couple of things:

1. If you do the same thing in a textarea field, everything works fine. With or without the markdown modifier applied.

2. If you return to the regex parser, everything works fine.  

So the bug is certainly with the new antlers parser, not the markdown modifier and not the regex parser.

### Logs

```shell
I had to upload the log file separately as it made my bug report too long for github. https://d.pr/f/zIqd4z
```

### Versions

Statamic 3.3.2 Pro
Laravel 8.83.5
PHP 8.1.2
statamic/seo-pro 3.1.0
statamic/ssg 1.0.0
transformstudios/review 3.2.1

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
This sounds similar to https://github.com/statamic/cms/issues/5545#issuecomment-1075610427 which is fixed by #5571. I'll confirm your issue is resolved when reviewing that PR.

**Comment by jasonvarga** [comment]
That PR did _not_ fix it, but we have an idea how to.

**Comment by espenlg** [comment]
I'm not sure if it's relevant, but I'm having the same problem - but in a Bard field.
