### ISSUE TITLE
`EntrySaved` event doesn't dispatch

### ISSUE THREAD

**Issue by aerni** [statamic/cms#5628]
### Bug description

I stumbled upon a show-stopping issue with the `Stache` and `$entry->saveQuietly()`. 

I've got a job that saves some data to an entry. The job gets triggered on `EntrySaved`. I use `saveQuietly()` to not end up in an endless loop. The issue is, that the `EntrySaved` event only dispatches ON FIRST SAVE. It won't dispatch when saving the entry consecutive times. Only when you clear the Stache in between saves.

It seems like the `$this->withEvents = false` is somehow cached and prevents dispatching of events on further saves of the same entry.

I only ran into this on production because the Stache watcher is disabled, which makes sense.

I put together a repo that reproduces the issue: https://github.com/aerni/save-quietly

### How to reproduce

1. Clone this repo: https://github.com/aerni/save-quietly
2. Turn the stache watcher off
3. Open Ray; I've got a ray call in `App\Jobs\SaveQuietlyJob`
4. Save the entry -> The job will be triggered
5. Save the entry again -> The job won't be triggered
6. Clear the stache and save the entry -> The job will be triggered again

### Versions

Statamic 3.3.2 Solo
Laravel 9.5.1
PHP 8.0.14
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

### Additional details

I tested this on Statamic 3.2 and Laravel 8 as well. Same problem.

**Comment by jasonvarga** [comment]
Nice find!

**Comment by duncanmcclean** [comment]
I wonder if this is in anyway related to #2993?
