### ISSUE TITLE
Error creating addon

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#5633]
### Bug description

Tried to create an addon via the cli, got an error.

<img width="979" alt="CleanShot 2022-03-24 at 09 29 22@2x" src="https://user-images.githubusercontent.com/6069653/159964631-88409686-4b73-46e0-8085-877af31beb28.png">

### How to reproduce

`php please make addon edalzell/api`

### Versions

```
Statamic 3.3.2 Pro
Laravel 8.83.5
PHP 8.1.4
jmalko/wistia dev-main
rias/statamic-link-it 2.2.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jonassiewertsen** [comment]
I did run into this a few time as well, but am not sure if this is a composer specific issue:

If working with docker containers vs my local machine, one required dev-main and the other part required dev-master. I couldn't figure out the exact issue yet.

**Comment by jasonvarga** [comment]
I'm fairly sure this is a composer issue, it's when your default git branch isn't configured to be `master`.

**Comment by jackmcdade** [comment]
Is this still an issue?
