### ISSUE TITLE
Remove Default for Augmented 'focusCss' value on Assets 

### ISSUE THREAD

**Issue by JayGeorge** [statamic/cms#5636]
### Bug description

I don't believe [this change](https://github.com/statamic/cms/pull/3340) was thought through and produces undesirable behaviour.

The previous behaviour of `{{ focus_css }}` defaulting to null is more desirable from an 'override' perspective.

## The Problem with setting {{ focus_css }} to a default of 50% 50%

Consider, for example, that I want to set a default object-position of top:

```css
.some-image {
    object-fit: cover;
    object-position: top;
}
```

I cannot use `<img style="object-position: {{ focus_css }};" />` because—even if the user has _not_ set any focus—the default value of 50% 50% will override any default I've set in my CSS file.

### Workarounds

With the new behaviour, it is possible I could try to test if the user has effectively set focus like this:

```html
{{ if focus_css !== '50% 50%' }} style="object-position: {{ focus_css }};"{{ /if }} 
```

However, there is still the possibility that the user could click precisely at 50% 50%, in which case the image focus would erroneously be set to the default CSS value of `object-position: top;`

## Why the previous behaviour was better

The previous behaviour worked great because I could do this:

```html
<img style="object-position: {{ focus_css }};" />
```

In this case, Statamic would naturally output `<img style="object-position: ;" />`, and my default CSS value would work unless the focal point was explicitly set.

## Conclusion

The only given reason I can see for this new default was to make things 'prettier'.

While I agree the old output behaviour is not pretty, it worked more naturally with the CSS cascade.

**Please can we either**

1. Revert to the previous default of outputting nothing (not as pretty, but more congruous with CSS)
2. OR enable a way to test for a set value. At the moment `{{ if focus_css }} style="object-position: {{ focus_css }};"{{ /if }}` does not work unfortunately

### How to reproduce

Try setting `<img style="object-position: {{ focus_css }};" />` on an image where no focal point has been set.

You'll see that it defaults to 50% 50%.

### Versions

Statamic 3.3.0 Pro
Laravel 8.83.5
PHP 8.0.9

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
I don't want to introduce another breaking change, so I'm adding a `has_focus` variable for you to use to actually check that it's been set.

```
{{ if has_focus }} style="object-position: {{ focus_css }};"{{ /if }}
```

**Comment by JayGeorge** [comment]
Thank you, that would be much appreciated
