### ISSUE TITLE
Add a delay before saving create folder popup

### ISSUE THREAD

**Issue by afonic** [statamic/cms#5639]
### Bug description

Since a debounce was added to the Fieldtype (https://github.com/statamic/cms/pull/4393), when creating a new folder in the Asset browser if you type a name and press Return the whole folder name is not registered.

Maybe add a delay like https://github.com/statamic/cms/pull/5039 in this dialog?

### How to reproduce

Go the asset browser, click Create folder, type a name as fast as you can and click enter. Watch your folder name getting trimmed. 

### Versions

Statamic 3.2.39 Pro
Laravel 8.83.5
PHP 8.0.14
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by jackmcdade** [comment]
Doesn't seem to be an issue in v4 anymore. Feel free to reopen or open a new one if you can recreate somehow!
