### ISSUE TITLE
GraphQL nav bug: Type GridItem_LocalizedUrls not found

### ISSUE THREAD

**Issue by goellner** [statamic/cms#5648]
### Bug description

Can't query the navigation anymore with GraphQL after updating to 3.3.3. Was on 3.2.xx before, so can't really pinpoint where this was introduced

### How to reproduce

setup nav with handle `main` and then run this query in graphiql: 

```
query GlobalData($site: String) {
  nav(handle: "main") {
    tree(site: $site) {
      page {
        title
        url
      }
      children {
        page {
          title
          url
        }
      }
    }
  }
}
```

### Logs

```shell
"debugMessage": "Type GridItem_LocalizedUrls not found.\nCheck that the config array key for the type matches the name attribute in the type's class.\nIt is required when 'lazyload_types' is enabled",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "nav",
        "tree",
        0,
        "page"
      ],
```

### Versions

3.3.3

### Installation

Fresh statamic/statamic site via CLI

**Comment by arthurperton** [comment]
Hi @goellner, I whipped up a simple nav called `main` and ran the query, but it doesn't cause the issue you're describing. Any more specifics, and can you share a screenshot of your nav?

**Comment by goellner** [comment]
can confirm we have aardvark too, but the plugin shouldn't break the graphql api imho. not sure if this is on aardvark or statamics side tbh.
