### ISSUE TITLE
Entries fieldtype returning instance of OrderedQueryBuilder in globals but array in entries

### ISSUE THREAD

**Issue by dominikradl** [statamic/cms#5654]
### Bug description

Maybe this is a bug in the new Antlers parser:

When I create a global blueprint containing an Entries fieldtype, Antlers gets an instance of `Statamic\Query\OrderedQueryBuilder` which cannot be looped over. When I try to loop over it using `{{ global:entry_field }} […] {{ /global:entry_field }}` I get the following error:

`Call to a member function all() on string` (vendor / statamic / cms / src / View / Antlers / Language / Runtime / NodeProcessor.php : 1340)

When I create a blueprint for an Entry and use the Entries fieldtype, Antlers gets an array of `Statamic\Entries\Entry` instances, which of course can be looped over.

### How to reproduce

1. Create a global blueprint with an Entries fieldtype.
2. Create a Entry blueprint with an Entries fieldtype.
3. Check the output (`dd`) of both in Antlers.

### Versions

Statamic 3.3.3 Pro (Antlers runtime engine activated)
Laravel 9.5.1
PHP 8.1.4

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by ryanmitchell** [comment]
I tried to replicate this issue but am not seeing it in the latest versions of Statamic. Is it still an issue for you?
