### ISSUE TITLE
Utilities page does not use users preferred locale

### ISSUE THREAD

**Issue by adevade** [statamic/cms#5666]
### Bug description

When an app has a `config('app.locale')` with another language (say Swedish) and the users sets their preferred locale to something else (say English), the Utilities page still uses the apps locale.

### How to reproduce

Reproduction repo: [adevade/statamic-utilities-translation-bug](https://github.com/adevade/statamic-utilities-translation-bug)

1. Log in with `admin@example.com` and `password`
2. See that the admin panel is in English (as per the users preferences)
3. Go to Utilities page and see that it is in Swedish (as per the app config)

*Note: Individual utility pages are still in English*

## Settings

- `config/app.php` has `locale => 'sv'`
- `users/admin@example.com.yaml` has `preferences: locale: en`

### Versions

Statamic 3.3.3 Solo
Laravel 9.5.1
PHP 8.1.3
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by ebeauchamps** [comment]
This a race condition problem I discovered a while back and it is visible in other parts of the CP.

**Comment by jasonvarga** [comment]
Fixed in #7343 and will be in 3.4.
