### ISSUE TITLE
Too many assets are slowing down statamic

### ISSUE THREAD

**Issue by crackAT** [statamic/cms#5675]
### Bug description

Migratet over 200k assets to statamic. Now statamic is super slow. Can‘t edit entries -> 504, opening the asset folder takes about 2 Minutes. 

### How to reproduce

Add 200k assets

### Versions

Statamic 3.2.39 Pro
Laravel 8.83.5
PHP 8.0.8

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Can you provide some more information about how your assets are setup? Are you using S3 / storing the assets on the server itself? Is tha 300k assets between multiple containers or all in one?

**Comment by crackAT** [comment]
Assets are stores directly on the server. 
all assets are in multiple containers

**Comment by afonic** [comment]
Did you try generating the thumbnails using `php please assets:generate-presets`

This should speed up the control panel.

**Comment by crackAT** [comment]
> Did you try generating the thumbnails using `php please assets:generate-presets`
> 
> This should speed up the control panel.

yep, but anyway, 200k assets are to much.

**Comment by jasonvarga** [comment]
Of course it shouldn't really matter, but I'm just curious how you ended up with such a large number of assets.

**Comment by crackAT** [comment]
Big site with a large amount of entries

**Comment by jasonvarga** [comment]
Closing in favor of #6495
