### ISSUE TITLE
Bard stores list items as <p>s when saving as HTML

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#568]
I have a Bard field with `save_html: true` set.

Adding a bullet list with the items `foo`, `bar` and `baz`, then saving the entry, I get

```json
[
    {
        "type": "text",
        "text": "<p>fo<\/p><p>bar<\/p><p>baz<\/p>"
    }
]
```

**Comment by stuartcusackie** [comment]
I've just run into this problem - Statamic 3.3.12

Just a standard bard field with sets, and it's saving the content like so:

![image](https://user-images.githubusercontent.com/20210934/172613305-d4fbf295-3679-4ba2-88f0-ffdd8d0deb37.png)

It's usually not a problem but in this case the site has centered text, and a paragraph within a list item using centered text looks wrong and is difficult to style.

**Comment by jackmcdade** [comment]
Unfortunately there's nothing we've been able to figure out to change that. A p inside an li is perfectly valid HTML. Can you not do something like this?

```css
.bard-field li > p {
  text-align: left; 
}
```

**Comment by stuartcusackie** [comment]
It's kind of a weird layout that I've been tasked to code up. The bullets aren't centered so your suggestion won't work. The only way I can figure it out is to remove those paragraphs manualy with simplehtmldom through my [cdom](https://github.com/stuartcusackie/cdom/blob/main/src/cdom.php#L136) package.
