### ISSUE TITLE
Partial tag using variable does not work

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#5680]
### Bug description

When upgrading to v3.3 and enabling the runtime setting the tag `{{ partial:partials/{{ type }} }}` did not work. Changing it to `{{ partial src="partials/{{ type }}" }}` works fine. {{ type }} in this case is from a replicator fieldtype and contains the handle of the item.

### How to reproduce

From what I can tell the bug description should be enough.

### Versions

Statamic 3.3.3 Solo
Laravel 8.83.5
PHP 8.0.16
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
That's an unsupported syntax that worked by fluke in the old parser. Use the alternative that you've mentioned.

**Comment by espenlg** [comment]
Works for me, but would suggest updating the documentation to avoid confusion.

**Comment by espenlg** [comment]
I did made an attempt to update it now.
