### ISSUE TITLE
Passing a variable to Glide has TypeError

### ISSUE THREAD

**Issue by wesort** [statamic/cms#5691]
### Bug description

Similar to #5544:

Using the glide tag as a variable [as per the docs](https://statamic.dev/tags/glide#overview) errors with a TypeError `pathinfo(): Argument #1 ($path) must be of type string, Statamic\Assets\OrderedQueryBuilder given`:

### Entry content:
``` 
archive_assets:
  - test-image-01.jpg
```

### Has `TypeError`:
```
<img src="{{ glide:archive_assets preset="600w" }}">
```

### Works as expected:
```
{{ glide:archive_assets preset="600w" }}
  <img src="{{ url }}">
{{ /glide:archive_assets }}
``` 

### Versions

**Statamic** 3.3.3 Pro
**Laravel** 9.5.1
**PHP** 8.0.16
**aryehraber/statamic-uuid** 2.1.0

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
We can make this work, but if you're using the single tag syntax... it only really makes sense for you to be using on a single image.

How would `archive_assets` (I'm assuming this could store multiple assets?) work with a single tag?

If you only intend for that field to store a single asset, you can add `max_files: 1` to it, and it should work.
