### ISSUE TITLE
If condition inside nested partial not working

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#5695]
### Bug description

If condition in nested partials not working right.

### How to reproduce

View: default
```
{{ sections }}
{{ partial src="sections/{type}" }}
{{ /sections  }}
```
View: sections/main
```
{{ content }}
{{ partial src="contents/{type}" reverse="{ switch between='even | odd' }" }}
{{ /content}}
```
View: contents/text
```
  REVERSE: {{ reverse }}
  {{ if reverse == 'odd' }} text-right {{ else }} text-left {{ /if }}
```
Output
```
  REVERSE: even
  text-left
  ---
  REVERSE: odd
  text-left
  ---
  REVERSE: even
  text-left
  ---
  REVERSE: odd
  text-left
```

### Versions

Statamic 3.3.3 Pro
Laravel 8.83.6
PHP 8.0.12

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by JohnathonKoster** [comment]
I can reproduce this behavior on Regex as well. The root cause is this part of the template:

```
{{ content }}
{{ partial src="contents/{type}" reverse="{ switch between='even | odd' }" }}
{{ /content}}
```

The parameters are split based on the `|` and not trimmed, so the final values in both versions include the space before or after the `|` character.

`even` becomes `even[space]` and `odd` is `[space]odd`. Adjusting the template to the following:

```
{{ content }}
{{ partial src="contents/{type}" reverse="{ switch between='even|odd' }" }}
{{ /content}}
```

produces the intended result.

@jasonvarga  Thoughts on automatically trimming pipe-separated parameters?

**Comment by wm-simon** [comment]
The space is needed for tailwind jit mode. It is in the `HOT TIP!` explained:
https://statamic.dev/tags/switch#repeating-values

**Comment by wm-simon** [comment]
> ```
> {{ content }}
> {{ partial src="contents/{type}" reverse="{ switch between='even|odd' }" }}
> {{ /content}}
> ```
> 
> produces the intended result.

Did you test it in runtime mode? I've removed the spaces and still have this issue.

**Comment by JohnathonKoster** [comment]
I did test in runtime; I'll have some extra time later to do a deeper dive.

**Comment by jasonvarga** [comment]
I don't think the parameters should trim anything. Someone is going to come with intentional spaces and wonder where they went.

**Comment by afonic** [comment]
> The space is needed for tailwind jit mode. It is in the `HOT TIP!` explained: https://statamic.dev/tags/switch#repeating-values

I don't think you need the space in your case, the class you need is `text-right`, not `even` (I think). So the compiler will read it in the partial and add it to the CSS.

The example in the docs directly renders these classes, doesn't pass them to a partial. `bg-white `  and `bg-white` are the same for CSS. :)

**Comment by wm-simon** [comment]
I know, that I don't need the spaces in my case. Like I said, it's still an issue without the spaces.

The Tailwind example was, to keep in mind, that the spaces are used like that.
BTW, there are multiple ways to use tailwind classes and check in partials for the value.
Example:
```
{{ content }}
{{ partial src="contents/{type}" class="{ switch between='text-left | text-right' }" }}
{{ /content}}

<div class="{{ class }}">Blubb</div>
{{ if class == "text-left" }}
<img class="float-right" />
{{ /if }}
``` 
I don't say this is the best way, but it is possible.

**Comment by afonic** [comment]
Yeah but I guess you can always do `{{ if class == "text-left " }}`.

I know that spaces get ignored in similar context in PHP, but Antlers is not PHP. As Jason said, I think it's working as it should.

**Comment by patrickhoehn** [comment]
I have the same issue with if conditions inside of partials resulting in `[ANTLR_008]: Unclosed "if" control structure.`

**Comment by patrickhoehn** [comment]
@jasonvarga, I thought my error has the same origin. I will open a new issue for this.

**Comment by jasonvarga** [comment]
This is working as intended.

You are passing `"[space]even"` and `"odd[space]"` as parameters.

So when you do `{{ if reverse == "odd" }}` it's never going to be `true` since it's never `"odd"` without the space.

You can trim that space off yourself, though.

```
{{ if reverse|trim == "odd" }}...{{ /if }}
```
