### ISSUE TITLE
Replace modifier does't work properly with extended ASCII character sets 

### ISSUE THREAD

**Issue by jbrhel** [statamic/cms#5703]
### Bug description

When antlers version is set to runtime, than the replace modifier doesn't work with extended ASCII character sets eg: ®, ™ 

### How to reproduce

`title = PRODUCT®`

`<h1>{{ title replace="®|<sup>&reg;</sup>" }}</h1>`

**Expected output:**
`<h1>PRODUCT<sup>&reg;</sup></h1>`

**Given output:**
`<h1>PRODUCT<sup>&reg;</sup>/h1>`

Same problem for given example (without html tag as substitute string):

`<h1>{{ title replace="®|foo" }}</h1>`

**Expected output:**
`<h1>PRODUCTfoo</h1>`

**Given output:**
`<h1>PRODUCTfoo/h1>`

### Versions

Statamic 3.3.4 Pro
Laravel 8.83.6
PHP 8.0.14

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by JohnathonKoster** [comment]
Note to self:

To consistently reproduce this there must be an Antlers tag before the Antlers tag containing the extended ASCII character.
