### ISSUE TITLE
`users_field` value changes after tag pair

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#5707]
### Bug description

There seems to be a bug with the new antlers parser: After using a users field tag pair, the value of the field is not the same anymore.

![Bildschirmfoto 2022-03-31 um 09 47 48](https://user-images.githubusercontent.com/6337411/161004637-38b3cd6f-4089-4223-8d83-669f159bb88a.png)

### How to reproduce

1. Add users field
2. Add user to field
3. Dump before and after tag pair
4. Check dumps of `users_field`

```
{{ users_field|dump }}

{{ users_field }}{{ /users_field }}

{{ users_field|dump }}
```

### Versions

Statamic 3.3.4 Pro
Laravel 8.83.6
PHP 8.0.16
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by JohnathonKoster** [comment]
Note to self: impacts query builders specifically
