### ISSUE TITLE
Relationship Selector: Columns don't use custom fieldtypes

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#571]
I override getColumns() in a custom relationship fieldtype like this

```php
protected function getColumns()
{
    return [Column::make('title'), Column::make('domain'), Column::make('channel')->fieldtype('channel_select')->sortable(false), Column::make('collection')];
}
```

but while the `preProcessIndex()` from ChannelSelect.php works fine for entry listings, it isn't used in the selector.

**Comment by jesseleite** [comment]
@sauerbraten Is this still an issue?

**Comment by jasonvarga** [comment]
Hey there, we haven’t heard back on this for a while so I’m going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!
