### ISSUE TITLE
Arr::isAssoc(): Argument #1 ($array) must be of type array when using scope modifier on entries fieldtype output

### ISSUE THREAD

**Issue by AndrewHaine** [statamic/cms#5712]
### Bug description

The error occurs when using the `scope` modifier to output a value from an `entries` fieldtype. This appears to only happen with the new runtime parser as switching back to the regex parser suppresses the error.

### How to reproduce

- Switch site to use the runtime parser
- Create an `entries` fieldtype and populate it with one or more entries.
- Pull the content through in a template and use the scope modifier (see the below example)

```
{{ my_fancy_entries_field scope="scope" }}
    <p>{{ scope:title }}</p>
{{ /my_fancy_entries_field }}
```

### Versions

Statamic 3.3.4 Pro
Laravel 8.80.0
PHP 8.0.17
austenc/statamic-instagram-feed 2.2.0
webographen/statamic-dynamic-token 1.0.0
withcandour/aardvark-seo 2.0.22
withcandour/statamic-blog-helpers 0.1.3
withcandour/statamic-imgix 0.1.4

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Using the details you've provided, I can't trigger any errors. Can you provide a GitHub repo with this bug reproduced?

**Comment by AndrewHaine** [comment]
Hey @jasonvarga ,

Sure thing, I've just set up https://github.com/AndrewHaine/statamic-test-repo to show what I mean.

In the `home` template (lines 3-5) there's a block which pulls from an entries fieldtype in the page blueprint. Interestingly if I remove the `page:` scope from the loop tag it resolves the issue but I think it _should_ work with our without it. 

Let me know what you think/if more info is required :) 

Thanks,
Andrew

**Comment by jackmcdade** [comment]
This should be fixed at this point.
