### ISSUE TITLE
Deprecation notice PHP 8.1

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#5718]
### Bug description

When working with Ray from Spatie the following deprecation notice appears with PHP 8.1:
```
Return type of Statamic\Fields\ArrayableString::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/marco/localweb/statamic-firefly/vendor/statamic/cms/src/Fields/ArrayableString.php on line 39
```

### How to reproduce

Use PHP 8.1 and Statamic 3.3 and have a look into Ray (or the log).

### Versions

Statamic 3.3.4 Solo
Laravel 9.6.0
PHP 8.1.4
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by duncanmcclean** [comment]
I believe this should have been fixed by #5701 - I don't think it's made its way into a release yet.
