### ISSUE TITLE
Performance issues Statamic 3.3

### ISSUE THREAD

**Issue by itsmesaskovic** [statamic/cms#5721]
### Bug description

We have some issues regarding the performance of Statamic in relation to Blueprints with references to Blueprints containing Taxonomies. What I have been able to analyze so far is that on Statamic 3.3.* the site is not able to run with the production data, while it is able to do this with Statamic 3.2.*

We use the corresponding Simple Commerce plugin (2.4.*), but looking at the profile logs it seems that a round trip is being made in Statamic objects.

In our case we have orders (collection), which contain products (collection), which contain authors (taxonomy). 
The issue appears in the shop (/shop) and on the homepage (because of the cart).

At this moment it is pretty hard to locate the place the issue is coming from. We do have profile logs from the stache command which we could share with you.
Here it seems that somewhere a loop occurs in the Statamic code.

Any help is appreciated since at this moment we are not able to deploy the last version of Statamic.

### How to reproduce

The Gitlab repo has been shared with the support team.

You can reproduce the issue which occurs by switching between v3.2.* and v3.3.* (matching Simple Commerce with the corresponding versions)

We ran the Stache warm command and profiled it which got us on a goose hunt arriving at some loop which seems to evolve around assembling the arrays. We were not able to see where it exactly went wrong.

### Versions

```
Statamic 3.3.4 Pro
Laravel 8.83.3
PHP 7.4.20
doublethreedigital/simple-commerce 2.4.6
joetannenbaum/antlers-stack-tags 0.1.0
optimoapps/statamic-bard-text-align 1.0.2
roorda-ict/statamic-entries-export 1.0.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

regex (default)

**Comment by duncanmcclean** [comment]
Hey 👋 ,

I'm the developer behind Simple Commerce. I'm happy to take a look and see if it's anything Simple Commerce related that's causing the performance issues. I can't promise I'll be able to take a look straight away but if you invite me to the repo I'll have a look.

**Comment by itsmesaskovic** [comment]
> Hey! 👋
> 
> I'm the developer behind Simple Commerce. I'm happy to take a look and see if it's anything Simple Commerce related that's causing the performance issues. I can't promise I'll be able to take a look straight away but if you send me an invite I'll see what I can do.

Thanks Duncan! I've sent you a message on Discord.

**Comment by duncanmcclean** [comment]
I've had a look into the issue.... 

Turns out it's an issue with Simple Commerce, rather than Statamic. The issue has to do with [this query](https://github.com/doublethreedigital/simple-commerce/blob/2.4/src/SimpleCommerce.php#L141) which is done whenever an order is created.

```php
$query = Collection::find(self::orderDriver()['collection'])
            ->queryEntries()
            ->orderBy('title', 'asc')
            ->where('title', '!=', null)
            ->get()
            ->map(function ($order) {
                $order->title = str_replace('Order ', '', $order->title);
                $order->title = str_replace('#', '', $order->title);

                return $order->title;
            })
            ->last();
```

This will be something that'll be sorted in the next version of SC (but by using a database instead).
