### ISSUE TITLE
Asset folders missing on DO Spaces - 3.3

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5723]
### Bug description

A lot of my folders are missing when updating to 3.3:

**This is the container after updating to 3.3 (only two folders):**
![image](https://user-images.githubusercontent.com/20210934/161265477-3b955ebc-cbc4-4fb7-865c-6e23ffda49b0.png)

**This is the container after reverting back to my master branch (3.2) and running composer update (all folders shown)**
![image](https://user-images.githubusercontent.com/20210934/161266518-32d1f757-fb0e-4015-a933-09610d78b3d4.png)

I am using Digital Ocean Spaces, with a filesystem config like so:

```
      'do_spaces_images' => [
            'driver' => 's3',
            'key' => 'xxxxxxxxx',
            'secret' =>'xxxxxxxxxx',
            'region' => 'ams3',
            'bucket' => 'xxxxxx',
            'url' => 'https://ams3.digitaloceanspaces.com/xxxxxx',
            'endpoint' => 'https://ams3.digitaloceanspaces.com',
            'root' => 'images',
            'visibility' => 'public'
        ],
```

### How to reproduce

Not sure. Try using DO spaces on Statamic 3.3.

### Versions

Statamic 3.3.4 Pro
Laravel 9.6.0
PHP 8.0.10
rias/statamic-redirect 2.1.2
statamic/seo-pro 3.1.0

### Installation

Existing Laravel app

**Comment by staudenmeir** [comment]
This looks like the same issue as #5535: Are you also getting the `Undefined array key "dirname"` error on the bottom left?

**Comment by stuartcusackie** [comment]
Just to update. The fix from #5535 did not fix this issue.

**Comment by jasonvarga** [comment]
Statamic has its own layer of caching. If you are doing stuff directly on Digital Ocean spaces, Statamic won't know about it. You'll need to clear your cache (`php artisan cache:clear`).

Can you try clearing your cache and see if it just starts working?

**Comment by stuartcusackie** [comment]
I'm fairly certain that I cleared all caches multiple times. Also, my issue didn't present because of a direct file change on the DO spaces interface. It happened with a simple update to Statamic 3.3.

I will recreate all my folders anyway and maybe the problem won't come back.

**Comment by stuartcusackie** [comment]
This problem is back again:

**Both local and production asset containers  - Folders missing**
![image](https://user-images.githubusercontent.com/20210934/208916411-b6b16bd6-a68f-46d1-a38b-483c6601843c.png)

**Digital Ocean Space - Folders visible**
![image](https://user-images.githubusercontent.com/20210934/208916452-940127c9-170f-48b4-88e0-735ba6949b7a.png)

- Happening on both local and production
- Stache watcher flag has no affect
- I have clear every cache using every command, and also through the CP utility
