### ISSUE TITLE
Entries select fieldtype causing horizontal overflow

### ISSUE THREAD

**Issue by websmyth** [statamic/cms#5728]
### Bug description

I have entries without a natural `title` so the collection it autogenerating the `title` from existing fields. Something like: `{{ person_name }} – {{ short_description }}`. `{{ short_description }}` is a Bard fieldtype.

Combining these fields creates a much-longer-than-normal `title`.

In the CP, I’m using an `Entries` fieldtype with a `Select Dropdown` to pick these. Two unrelated issues present:

1. The entry titles are wide enough to cause horizontal overflow in the CP
2. The bard fieldtype displays the HTML in the `title`

### How to reproduce

1. Create a collection a `title` generated from `entry` fields
2. Make at least one of the `entry` fields a Bard fieldtype
3. Create an `entries` fieldtype in another blueprint/fieldset that selects from this collection

### Versions

Statamic 3.3.4 Pro
Laravel 8.83.6
PHP 7.4.27
withcandour/aardvark-seo 2.0.22

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by websmyth** [comment]
Here’s a screenshot to demonstrate the effect inside the CP

The user icon in the top right shows the edge of the browser: **Live Preview** is shunted off screen. Collapsing the `entries` field with these overflowing titles causes the overflow to disappear/CP to display normally.

<img width="1734" alt="Screenshot 2022-04-07 at 14 29 49" src="https://user-images.githubusercontent.com/9350638/162210877-ff7e5ce4-683f-49e3-9162-ce05be443359.png">
.

**Comment by jasonvarga** [comment]
I can't get the overflow to happen. Can you give any more details? Am I missing something?

This is what my dropdown looks like:

![image](https://user-images.githubusercontent.com/105211/162233562-089f56c9-b3b2-465c-b278-83a71a45c737.png)

**Comment by websmyth** [comment]
Hmmm, the only other difference is that this is inside a Replicator. Perhaps that’s it? Collapsing the set with this field causes the overflow issue to disappear.

Would repo access be handy?

**Comment by jasonvarga** [comment]
Worked it out. It's the single select field. You need a `max_items: 1` to see it happen.

**Comment by websmyth** [comment]
Ah, so we should set a `max_items` to stop it?

**Comment by jasonvarga** [comment]
Sorry no I mean it's the single select field that's causing it. The multi-select works fine.

**Comment by jasonvarga** [comment]
It's not you, it's me.

**Comment by websmyth** [comment]
Oh, gotcha. Heard that before 😂
