### ISSUE TITLE
User avatar in control panel header does not cover whole circle if avatar image aspect ratio is not 1:1

### ISSUE THREAD

**Issue by ncla** [statamic/cms#5729]
### Bug description

![image](https://user-images.githubusercontent.com/5507083/161421288-4fa6c276-2b94-4f38-bb7a-cd88672ba92d.png)

### How to reproduce

1. Upload an avatar that is in some weird aspect ratio for currently logged in user

### Versions

Statamic 3.3.4
Laravel 9.5.1
PHP 8.0.16
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Additional details

I can open PR for this, there's two approaches for this:

1. One line CSS fix
2. Force generate a square thumbnail (currently CP outputs URL to the original image)

**Comment by arthurperton** [comment]
Nice find. I would go for the CSS fix.

**Comment by ncla** [comment]
Since I already had looked at how to solve this issue before hand (I know, I know), I present two PRs. One CSS fix, second one uses thumbnail controller adjustments. CSS fix is much simpler obviously. As I said in the 2nd PR, no hard feelings if it's too much, just deep diving cms source code as practice.

**Comment by arthurperton** [comment]
Thank you!
