### ISSUE TITLE
Triple Nested Partials Unexpectedly Render Content

### ISSUE THREAD

**Issue by potentweb** [statamic/cms#5736]
### Bug description

In the new antlers runtime engine...

Content in the third level of nested partials will be output to the frontend even if it should not be.

### How to reproduce

Install a brand new project and set antlers to use the runtime parser.

In the home view add something like this:

```
{{ partial src="wrapper" }}
    {{ partial src="second_wrapper" }}
        {{ partial src="content" }}
    {{ /partial }}
{{ /partial }}
```

In the wrapper view add a slot:

`{{ slot }}`

In the second_wrapper leave it blank so nothing should be output.

In the content view add some text:

`My content`

If you load up the homepage `My content` will be shown.

### Versions

Statamic 3.3.4 Solo
Laravel 9.6.0
PHP 8.0.17
No addons installed

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
This is a result of ambiguity between single tags and tag pairs.

In your example:

```
{{ partial src="wrapper" }}
    {{ partial src="second_wrapper" }}
        {{ partial src="content" }}
    {{ /partial }}
{{ /partial }}
```

Keep in mind that the parser doesn't take into account how your tags are indented. Let's remove the whitespace to make this more obvious:

```
{{ partial src="wrapper" }}
{{ partial src="second_wrapper" }}
{{ partial src="content" }}
{{ /partial }}
{{ /partial }}
```

Now you can see it could be confused by which closing tag belongs to which opening tag.
Maybe wrapper and second_wrapper are pairs, and content is a single, like you're expecting.
Maybe wrapper is a single, and both second_wrapper and content are pairs.
Maybe wrapper and content are pairs, and second_wrapper is a single.

You should be able to clear it up by using a self-closing tag, like this:

```
{{ partial src="wrapper" }}
    {{ partial src="second_wrapper" }}
        {{ partial src="content" /}}  👈
    {{ /partial }}
{{ /partial }}
```

However, there was a bug there too. #5781 fixes it.
