### ISSUE TITLE
Nested {{ confusing the antlers parser

### ISSUE THREAD

**Issue by stefankempf** [statamic/cms#5741]
### Bug description

I'm adding icons as inline svg through a partial, so the user can select the icon as well as size and color. And I'm wrapping those icons with a div.

```
<div class="list-of-classes">
    {{ partial src="svg/{{ article_icon:key }}" values="{{ article_icon_color:key }} {{ article_icon_size:key }}" }}
</div>
```
Within the partial, I call the values like this:
```
<svg class="{{ values }}" …
```
When I do this, the wrapping div tag is not getting closed. It is literally just ignoring the ```</div>``` which therefore destroys the whole DOM afterwards.

### How to reproduce

Follow the steps in bug description.

**_workaround_**: Use single brackets, whenever you're already inside a {{ }} pair.

### Versions

Statamic 3.3.4 Pro
Laravel 8.83.6
PHP 8.1.3
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Use single braces inside parameters.

```
<div class="list-of-classes">
    {{ partial src="svg/{article_icon:key}" values="{article_icon_color:key} {article_icon_size:key}" }}
</div>
```
