### ISSUE TITLE
If statements stopped working with new parser

### ISSUE THREAD

**Issue by stefankempf** [statamic/cms#5744]
### Bug description

I have simple if statements which are not valid anymore after switching to the new parser.

```
{{ if segment_1 && toggle_field }}
```
and
```
{{ if segment_1 || toggle_field }}
```

### How to reproduce

Try above mentioned statements

### Versions

Statamic 3.3.4 Pro
Laravel 8.83.6
PHP 8.1.3
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Seems fine to me. Gonna need some more details. What does "stopped working" mean?

**Comment by stefankempf** [comment]
Please excuse this issue, I'm hustling through a madness day with too much workload and my brain is soft boiled at the end of it. Got it all done but this last piece was just too much and lead to this issue. I somehow oversaw the most simplest typo and struggled through it.
