### ISSUE TITLE
LInked entries aren't returning URL in runtime parser

### ISSUE THREAD

**Issue by montemartin** [statamic/cms#5746]
### Bug description

I've created a Link fieldtype inside a replicator where each item includes a link to another entry. Links are saved with the format `button_link: 'entry::{entry_id}'` and work perfectly fine with the regex parser. 

After swtiching to the runtime parser `{{button_link}}` is returning `null` instead of a URL path. The other elements in the fieldset are still returning correctly. 

### How to reproduce

```html
{{ sections }}
  {{ if type === "feature_list" }}
      {{ features }}
          <h4>{{ headline }}</h4>
          <p>{{ supporting_content | markdown }}</p>
          < href="{{ button_link }}">{{ button_text ?? "Read More" }}</a>
      {{ /features }}
    {{/if}}
{{ /sections }}
```

```markdown
title: Broken 😢 
sections:
  -
    markdown: |-
      ## MD Content
    type: markdown
    enabled: true
  -
    type: feature_list
    enabled: true
    features:
      -
        button_link: 'entry::2a4426dc-bdba-4855-a653-318e4b8affb9'
        type: feature
        headline: 'headline'
        supporting_content: 'Content'
        enabled: true
      -
        button_link: 'entry::5da0402e-ecfc-4408-bc9c-df5214db9fa1'
        type: feature
        headline: 'headline'
        supporting_content: 'Content'
        enabled: true
```

### Logs

```shell
none
```

### Versions

Statamic 3.3.3 Pro
Laravel 8.83.2
PHP 8.1.2

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by JohnathonKoster** [comment]
Is sections also a Bard field? Just trying to make sure I'm attempting to reproduce this exactly :)

**Comment by montemartin** [comment]
No, it's a replicator

**Comment by montemartin** [comment]
FYI, I was able to get this working using `{{ get_content:button_link }}{{ button_link }}{{ /get_content }}`

**Comment by montemartin** [comment]
I'll see what I can pull together. I was able to work around it so I hadn't thought to much more about it.

**Comment by jasonvarga** [comment]
A PR was just merged that fixes an issue where a link fieldtype would not output anything in a specific situation. Maybe that PR also fixes your issue. #6258.
