### ISSUE TITLE
Addons show as unlisted

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#5754]
### Bug description

In some cases, addons are listed in the CP as "unlisted" even though they definitely exist on the marketplace and a correct matching version is installed.

### How to reproduce

Not sure. Working theory is that it happens if there's a rate limit response when generating the addon manifest.

### Versions

Statamic 3.3.1 Pro
Laravel 8.83.5
PHP 8.0.14
aerni/advanced-seo 1.0.1
spatie/statamic-responsive-images 2.10.0

### Installation

Other (please explain)

**Comment by josephrlee** [comment]
I'm getting the error/bug on my install: <img width="979" alt="Screen Shot 2022-05-04 at 9 59 00 AM" src="https://user-images.githubusercontent.com/1631062/166739524-dba80b2e-c9e0-47bd-a993-b0246d998621.png">

**Comment by joshuablum** [comment]
Can replicate with a fresh install.

Statamic 3.3.12 Pro
Laravel 9.14.1
PHP 8.1.6
mitydigital/sitemapamic 2.1.1

`bootstrap/cache/addons.php` shows lot of NULLs
`php
<?php return array (
  'mitydigital/sitemapamic' => 
  array (
    'id' => 'mitydigital/sitemapamic',
    'slug' => NULL,
    'editions' => 
    array (
    ),
    'marketplaceId' => NULL,
    'marketplaceSlug' => NULL,
    'marketplaceUrl' => NULL,
    'marketplaceSellerSlug' => NULL,
    'latestVersion' => NULL,
    'version' => '2.1.1',
    'namespace' => 'MityDigital\\Sitemapamic',
    'autoload' => 'src',
    'provider' => 'MityDigital\\Sitemapamic\\ServiceProvider',
    'name' => 'Sitemapamic',
    'url' => NULL,
    'description' => 'Adds an XML sitemap to a Statamic site.',
    'developer' => 'Marty Friedel',
    'developerUrl' => NULL,
    'email' => NULL,
  ),
);
`

**Comment by martyf** [comment]
This has come courtesy of @jacksleight commenting on Sitemapamic (one of our addons).

Adding the Minimum Git Version to the addon listing in the Statamic Marketplace resolves this issue. 

I've been able to replicate it several times:
1. Look at site, see addons as Unlisted
2. Set "Minimum Git Version" in the Marketplace listing
3. Run `composer dump-autoload`

Addons are now listed correctly, and the `bootstrap/cache/addons.php` sample above no longer has the `NULL` values.

**Comment by jasonvarga** [comment]
Run `php please addons:discover`

**Comment by Buffalom** [comment]
```bash
» php please addons:discover
Discovered Addon: teamnovu/statamic-images-missing-alt
Discovered Addon: webographen/statamic-widget-continue-editing
Addon manifest generated successfully.
```

The command itself succeeded, but the addon is still displayed as unlisted.

**Comment by jasonvarga** [comment]
Which addon?

**Comment by Buffalom** [comment]
`teamnovu/statamic-images-missing-alt`

**Comment by jasonvarga** [comment]
Nope, I didn't do anything.

But the issue cause is unknown.

> How to reproduce
> Not sure. Working theory is that it happens if there's a rate limit response when generating the addon manifest.

Maybe you ran into the rate limit.

**Comment by rrelmy** [comment]
We have this issue with our latest addon

Statamic API can list releases
https://statamic.com/api/v1/marketplace/packages/appswithlove/statamic-one-click-content-translation/releases

But it can not find versions
https://statamic.com/api/v1/marketplace/packages/appswithlove/statamic-one-click-content-translation/0.9

For another addon it works
https://statamic.com/api/v1/marketplace/packages/appswithlove/statamic-extended-section/3.2

**Comment by jasonvarga** [comment]
@rrelmy, set the minimum git version.

![CleanShot 2023-02-21 at 08 33 21](https://user-images.githubusercontent.com/105211/220358758-d1d0f0bc-0f80-4dad-baa7-836a1330c6de.png)

I noticed that you went from 0.9.2 to 3.4.0. I'm guessing you tagged 3.4.0 just to try and make it work?

I've set it to 0.9 for you and now it works.

**Comment by duncanmcclean** [comment]
There are generally two reasons for addons to show as "Unlisted" in the Control Panel:

1. The addon hasn't been published on the Statamic Marketplace. 
    * It might be a private addon, or the addon developer might have not made it that far yet.
3. The "Package" or the "Minimum Git Version" for the addon hasn't been correctly configured by the addon developer.
    * The "Package" field should obviously match the name of the package on [Packagist](https://packagist.org/) (eg. `statamic-rad-pack/runway`).
    * The "Minimum Git Version" field should be set to the earliest Git tag you want to be available for install. Usually this will be the addon's first release.

I've just installed a bunch of addons, including those mentioned in this issue and those mentioned semi-recently in Discord, and none of them seem to be showing up as "Unlisted" anymore.

Since this issue is fairly easily fixable by addon developers, and doesn't seem to be affecting as many addons now, I'm going to close this issue. 

If any addon develoeprs are still having issues with their addons showing up as "Unlisted", even after configuring their addon's package & minimum Git version, let us know and we can take a look. 👍
