### ISSUE TITLE
using offset parameter with collection tag and scoped variable breaks rendering

### ISSUE THREAD

**Issue by dadaxr** [statamic/cms#5758]
### Bug description

Using statamic v3.3.4 with new parser engine I've encountered weird parsing behavior with the collection tag and the offset parameter when using the scope "feature"

### How to reproduce

Just create a  "projects" collection with 3 published entries inside and test the bellow templates : 

```
{{ collection from="projects" as="projects"  }}
     {{ projects scope="project" }}
            {{project.slug|dump}}
     {{ /projects}}
{{ /collection }}
```
OK => outputs all projects slug as expected (**no offset parameter**)
 

```
{{ collection from="projects" as="projects"  offset="2" }}
     {{ projects scope="project" }}
            {{project.slug|dump}}
     {{ /projects}}
{{ /collection }}
```
KO =>  dumps "null" instead of the last project slug.

```
{{ collection from="projects" as="projects" }}
     {{ projects scope="project"  offset="2"}}
            {{project.slug|dump}}
     {{ /projects}}
{{ /collection }}
```
OK =>  works as expected and dumps last project slug (but the offset parameter has to be set on the alias tag which looks like a bug to me and is not documented)

```
{{ collection from="projects" as="projects"  offset="2" }}
    {{ projects }}
         {{slug|dump}}
     {{ /projects}}
{{ /collection }}
```
OK => works as expected and dumps the last project slug (note we dont use the "scope" feature, only "alias" with the "as" parameter)

```
{{ collection from="projects" scope="project" offset="0" }}
      {{project.slug|dump}}
{{ /collection }}
```
OK => works as expected (ie with offset = 0 or no offset parameter, it's the same behavior)

```
{{ collection from="projects" scope="project" offset="1" }}
      {{project.slug|dump}}
{{ /collection }}
```
KO => dumps "null" 3 times (??)

```
{{ collection from="projects" scope="project" offset="2" }}
      {{project.slug|dump}}
{{ /collection }}
```
KO => dumps "null" 2 times (??)

```
{{ collection offset="2" }}
     {{slug|dump}}
{{ /collection }}
```
OK => works as exptected and dump the last project slug

Hope it can helps ;)

### Versions

Statamic 3.3.4 Solo
Laravel 9.6.0
PHP 8.1.3

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by dadaxr** [comment]
Moreover (dont know if it's the same bug or not)  it seems there are also troubles with (front matter) variable parsing ie : 

```
{{ test_var = "2"}}
{{ collection from="projects" as="projects" sort="order" }}
    {{ projects scope="project" :offset="test_var" }}
         {{project.slug|dump}}
    {{ /projects}}
{{ /collection }}
```
OK => works a expected (the *test_var* is interpolated)


```
---
test_var = "2"
---
{{ collection from="projects" as="projects" sort="order" }}
    {{ projects scope="project" :offset="view.test_var" }}
         {{project.slug|dump}}
    {{ /projects}}
{{ /collection }}
```
KO => when using front matter variable (scoped with the "view" prefix) the variable is not interpolated and this results in all projects slug dumped

**Comment by jasonvarga** [comment]
Just to confirm.. when you say KO you mean it's not correct? 😂

**Comment by jasonvarga** [comment]
Seems like the issue lies with `offset` >1. I'm guessing it has something to do with how the underlying collection would have non-zero indexes.

**Comment by jasonvarga** [comment]
Also, this is not unique to 3.3 or the new parser. This happens on 3.2, too.

You can workaround this by calling a modifier that'll do reindexing under the hood. For example, the `sort` modifier.

Do this:

```
{{ collection from="projects" as="projects"  offset="2" }}
     {{ projects sort="" scope="project" }} // 👈 just drop sort="" right in here.
            {{project.slug|dump}}
     {{ /projects}}
{{ /collection }}
```
