### ISSUE TITLE
CP don't work if cloudflare is denying access

### ISSUE THREAD

**Issue by tomhelmer** [statamic/cms#5763]
### Bug description

Sometimes access to cloudflare is denied from our hosting environment ( platform.sh ) 
See details for one such incident here: https://status.platform.sh/incidents/7tmr072zkl2l

It would be nice if the CP did not stop working if this happens

### How to reproduce

Run your site from an IP blocked by Cloudflare

### Logs

```shell
[2022-04-06 10:00:56] test.ERROR: Client error: `POST https://outpost.statamic.com/v3/query` resulted in a `403 Forbidden`
```

### Versions

Statamic 3.3.4 Pro
Laravel 8.83.7
PHP 8.0.17
cnj/seotamic 2.0.5
thehome/statamic-elasticsearch 1.1.0

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by duncanmcclean** [comment]
Possibly related to #5786

**Comment by jackmcdade** [comment]
I'm sorry but I don't see how we'd able to make a URL work if Cloudflare has denied it and you run your DNS though it. If you can show us some way to bypass Cloudflare we've be happy to look into it deeper.
