### ISSUE TITLE
Entry Query Builder does not filter columns from get/select

### ISSUE THREAD

**Issue by digitalam025** [statamic/cms#5765]
### Bug description

From the code below:

**What Happened**
Entries are returned with all the fields defined on its blueprint.

**Expected**
Entries are returned with only the `title` and `other_field` fields.

```php
Entry::query()->where('collection', 'posts')
            ->whereNotNull('content')
            ->get(['title', 'other_field']);
// OR

Entry::query()->where('collection', 'posts')
            ->whereNotNull('content')
            ->select(['title', 'other_field'])
            ->get();
```

### How to reproduce

1. Create a new route and controller.
2. Create at least one entry in a new/existing collection (with 2+ fields).
3. Query the entries from its collection using `Statamic\Facades\Entry::query()`.
4. Use one of the examples provided above with get/select.
5. `dd` the results to find that all entries returned all its fields.

### Versions

Statamic 3.3.4 Pro
Laravel 9.6.0
PHP 8.1.3

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Might be a regression bug. (Thanks Ryan and Duncan!)

My workaround now is `->get()->toArrayWith(['title', 'other_field'])`

**Comment by jasonvarga** [comment]
Entries do get all the fields, but when you `select` or `get` them, only the ones you choose will be output in the augmented data.

Try to `return` the results from the query and you should see what I mean.

```php
return Entry::query()->where('collection', 'posts')
            ->whereNotNull('content')
            ->get(['title', 'other_field']);
```
