### ISSUE TITLE
Modifier `count` causes error, when field not exists

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#5767]
### Bug description

When you check the count of entries and the field does not exists, there is shown an error.

### How to reproduce

The replicator field `sections` exists not in all blueprints. When it does not exist, the error is shown. After adding the field, all works fine.

// layout/hero
```
{{ if sections|count > 1 }} 
```
// error
```
count(): Argument #1 ($value) must be of type Countable|array, null given
```

### Versions

Statamic 3.3.3 Pro
Laravel 8.83.6
PHP 8.0.12

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by duncanmcclean** [comment]
Could you check if the session exists, then check the count? I've not tested it but maybe something like this could work:

```antlers
{{ if sections && sections|count > 1 }} 
```

**Comment by wm-simon** [comment]
If you check it before, it works.
```
{{ if sections }} 
  {{ if sections|count > 1 }} 
   // output
  {{ /if }}
{{ /if }}
```

**Comment by duncanmcclean** [comment]
There you go! That's probably the best way to workaround it 👍 

I'll keep this issue open so the Team can decide if it's a bug/how it should work.
