### ISSUE TITLE
When upgrading to 3.3.> taxonomies filters doesn't work as expected

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#5768]
### Bug description

As of version 3.3.> this markup stopped working:

```
{{ collection:people :taxonomy:disciplines="disciplines" scope="contacts"  }}
{{ partial:contacts-item }}
{{ /collection:people }}
```

See details from this discussion on Discord:
https://discord.com/channels/489818810157891584/489819906540568593/961156438963658772

### How to reproduce

Try this markup in version 3.2.*, and it works perfectly fine (I will gladly share repo access if needed). When upgrading to 3.3.4, it outputs ALL contacts (not just the contacts tagged with the corresponding term)

### Versions

In this version it WORKS:

```
Statamic 3.2.39 Pro
Laravel 8.83.6
PHP 8.0.17
aryehraber/statamic-captcha 1.8.0
jacksleight/statamic-bard-mutator 1.0.3
jacksleight/statamic-bard-texstyle 1.0.0
pecotamic/sitemap 1.2.5
```

In this version it does NOT work:

```
Statamic 3.3.4 Pro
Laravel 8.83.6
PHP 8.0.17
aryehraber/statamic-captcha 1.8.0
jacksleight/statamic-bard-mutator 1.0.3
jacksleight/statamic-bard-texstyle 1.0.0
pecotamic/sitemap 1.2.5
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by axelferdinand** [comment]
Yeah @duncanmcclean – I tried the new parser as well, and the output is the same. It simply doesn't filter the contacts – it just outputs all of them.

**Comment by jbrhel** [comment]
@axelferdinand I had a similar issue. And I found workaround. Code below should works. It could temporarily fix your problem until the fix will be released.

```
{{ collection:people taxonomy:disciplines="{{ disciplines }}" scope="contacts"  }}
  {{ partial:contacts-item }}
{{ /collection:people }}
```

**Comment by axelferdinand** [comment]
Hi @jbrhel ! I tried your markup, and it outputs ALL my contacts – not just the contacts within the taxonomy. So I'm afraid I still have to wait for another fix :D

**Comment by axelferdinand** [comment]
But thanks for reaching out!

**Comment by jasonvarga** [comment]
Yes please share repo access. Or at least go into more detail about what the value of `disciplines` is.

**Comment by jasonvarga** [comment]
If `disciplines` is null or an empty array, it does indeed show all the items. But, this is the same behavior as on 3.2.

In the discord link you shared, I noticed you wrapped the whole tag pair with an `{{ if disciplines }}...{{ /if }}`. This would prevent the collection tag outputting anything if the field is empty or missing. This seems to work just fine though.

I'm going to close this for now, but feel free to comment with more information and we can reopen it.

**Comment by axelferdinand** [comment]
Hi @jasonvarga 

I just invited you to the https://github.com/axelferdinand/vitas.no/ repo. The repo runs on the latest v3.2 version.

I created a test page, where you can review the bug:

`/test-contacts`

This page lists _only two_ contacts on v3.2, which is the expected behavior, since the contacts are filtered with taxonomies. When updating to v3.3, it will list _all_ contacts, which is not the expected behavior.

Try cloning the repo, run the test page, update to latest version, and run the test page again. Completely different behavior, and I don't know how to achieve the expected behavior on v3.3>

Someone suggested updating the markup to this, to make it work:

```
{{ collection:people taxonomy:disciplines="{ disciplines }" scope="contacts"  }}
  {{ partial:contacts-item }}
{{ /collection:people }}
```

However, in v.3.3, this will output all the contacts, as well.

NOTE: I have removed the `{{ if disciplines }}...{{ /if }}` condition, since it has nothing to do with the bug.

Please reopen the ticket.

**Comment by jasonvarga** [comment]
Thanks, confirmed. There must be some extra detail making this happen that you didn't mention, like having the field inside a bard. Will look into it.

**Comment by axelferdinand** [comment]
Hi @jasonvarga 

Seems like this bug isn't fixed completely, unfortunately... Try entering the repo I shared access to, which is now running on v3.2.39, and update the CMS.

Compare this page with before and after updating:

`/analytical-services/lipidomic-analytical-services`

Scroll down to the section "Applications"

<img width="943" alt="image" src="https://user-images.githubusercontent.com/10460870/165070724-00e17630-1cf0-404c-b346-3f64d282cfcc.png">

This is empty running on 3.3, but works perfectly fine on 3.2.

The applications is listed with JS, but data is populated in a controller:

`
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Statamic\Entries\Entry;

class ApplicationsController extends Controller
{
  public function __invoke()
  {
    $results = collect();
    $entries = Entry::query()
    ->where('collection', 'applications')
    ->get();

    foreach ($entries as $entry) {
      $results->push([
        'id' => $entry->id(),
        'url' => $entry->url(),
        'title' => $title = $entry->get('title'),
        'slug' => $entry->slug(),
        'number' => $entry->get('number'),
        'pdf' => $entry->get('pdf'),
        'applications' => collect($entry->get('applications'))->map(function ($slug) {
          return \Statamic\Facades\Term::findBySlug($slug, 'applications')->title();
        }),
        'applications_slug' => $entry->get('applications'),
        'disciplines' => collect($entry->get('disciplines'))->map(function ($slug) {
          return \Statamic\Facades\Term::findBySlug($slug, 'disciplines')->title();
        }),
        'disciplines_slug' => $entry->get('disciplines'),
        'vitamins' => collect($entry->get('vitamins'))->map(function ($slug) {
          return \Statamic\Facades\Term::findBySlug($slug, 'vitamins')->title();
        }),
        'vitamins_slug' => $entry->get('vitamins'),
      ]);
    }

    return response()->json([
      'version' => 'https://jsonfeed.org/version/1',
      'title' => 'Vitas Applications',
      'home_page_url' => 'https://vitas.no/',
      'feed_url' => 'https://vitas.no/api/applications.json',
      'items' => $results
    ]);
  }
}
`

<img width="292" alt="image" src="https://user-images.githubusercontent.com/10460870/165070936-208fd674-8afd-4a0e-9050-08ecd02e940e.png">


Does the markup need to be updated?

**Comment by axelferdinand** [comment]
Hey @jasonvarga Don't wont to bug you, but I still can't get this working. Now the site is 53 versions behind, and I really would like to be able to update the site without vital functions not working properly. Any idea what's wrong?

**Comment by jakubjo** [comment]
Did you try to use something like this?

```
{{ collection:people taxonomy:disciplines="{disciplines.id}" scope="contacts"  }}
  {{ partial:contacts-item }}
{{ /collection:people }}
´´´

I had similar issues when migrating to 3.3 and it helped to use IDs when filtering by taxonomies.

**Comment by axelferdinand** [comment]
Thank you @jakubjo ! I will try your suggestion, maybe it does the trick with the contacts.

Do you have any idea what makes the custom controller not working as expected when upgrading to 3.3? (see latest message from me above)

**Comment by jakubjo** [comment]
Difficult to say with the small snippet. What does the controller returns? I'd check if `$entries` is not empty. If its indeed not empty you can chain the "foreach" directly on to entries. Would simplify things: Less moving parts, less error potential.

```php
$items = Entry::query()
    ->where('collection', 'applications')
    ->get()
    ->map(function(Entry $entry) {
        return [
            'id' => $entry->id(),
            ...
        ];
    });

**Comment by axelferdinand** [comment]
Thanks, I will make sure to try this!

**Comment by jasonvarga** [comment]
The issue originally talks about using the `collection` tag, but now you're saying it doesn't work in a controller? Can you be more specific about what the issue actually is?

**Comment by axelferdinand** [comment]
Yeah, I know I mixed it up, but two things stopped working after updating to 3.3, and I suspect they are related since both issues are connected to filtering content with taxonomies. Here's the second issue described:

https://github.com/statamic/cms/issues/5768#issuecomment-1108381184

Maybe I should make a new ticket?

**Comment by jasonvarga** [comment]
Yes, make a new ticket.

But just FYI the /applications.json url returns the exact same json response in 3.3 that it does in 3.2.

**Comment by axelferdinand** [comment]
It does?? Let me dig deeper into this, I probably messed up somewhere... Thanks, will make a new ticket if I can't get it running. Sorry!

**Comment by jasonvarga** [comment]
It's this line in `resources/views/partials/modules/applications.antlers.html`

```
<tr data-ng-repeat="item in filteredList = (items | orderBy:'number' | reverse:true | filter: '{{ filter }}' | filter: '{{ applications }}{{ title }}{{ /applications }}' | filter: '{{ disciplines }}{{ title }}{{ /disciplines }}' | filter: '{{ vitamins }}{{ title }}{{ /vitamins }}' )" id="[[ item.slug ]]">
```

The `| filter: '{{ vitamins }}{{ title }}{{ /vitamins }}'` at the end.

In 3.3, this returns nothing so you get `filter: ''`. If I remove that filter, the list shows up.

Without looking deeper into it, I'm not sure why you were getting anything in 3.2. The entry doesn't have any `vitamins`.
