### ISSUE TITLE
Cloudflare 403 

### ISSUE THREAD

**Issue by matthiaz** [statamic/cms#5786]
### Bug description

Since yesterday it looks like downloading from statamic.com is failing for certain IP address sources. Other downloads from cloudflare hosted assets are working perfectly fine. So I'm suspecting this is to do with statamics specific cloudflare settings.

The ip addresses in question (but not exclusive to):

```
13.48.116.14
13.51.46.87
13.48.202.56
```

Test: (notice that the last response will give a 404 (not a 403) when tried on your own IP.

```
web@ks-cms.0:~$ curl -Ss http://ifconfig.io
13.48.202.56
web@ks-cms.0:~$ curl -SsI https://nodejs.org/dist | grep HTTP
HTTP/2 301 
web@ks-cms.0:~$ curl -SsI https://outpost.statamic.com | grep HTTP
HTTP/2 403 
```

I suggest changing the cloudflare settings to allow access: 

![image](https://user-images.githubusercontent.com/3532563/162174729-6914a52c-92e6-49d6-a282-f41ceae6ad9c.png)

### How to reproduce

A bit hard to reproduce since only certain IPs are blocked, and I don't know where it is happening. But this is how I did it:

```
web@ks-cms.0:~$ curl -Ss http://ifconfig.io
13.48.202.56
web@ks-cms.0:~$ curl -SsI https://nodejs.org/dist | grep HTTP
HTTP/2 301 
web@ks-cms.0:~$ curl -SsI https://outpost.statamic.com | grep HTTP
HTTP/2 403 
```

### Versions

n/a

### Installation

Other (please explain)

**Comment by duncanmcclean** [comment]
What are you trying to download? Statamic v2/a v2 addon? Are you downloading via a browser or via the terminal?

**Comment by duncanmcclean** [comment]
As it happens, I had the same issue yesterday (a Cloudflare 403) on a client site. Disabling Cloudflare solves the problem but obviously you don't want to do that.

I could reproduce by running a command like this:

```
curl -o - -I https://example.com/whatever
```

^ which makes me thing you're trying to download via the terminal, is that correct?

**Comment by matthiaz** [comment]
That is correct. I was trying to download via the terminal. 

It looks like it is working again though after a modification on the servers in question, so I'm thinking this was not a statamic problem at all. 

Sorry for the wasted time. But thank you for the swift response!
