### ISSUE TITLE
Bard field with antlers enabled not parsing antlers after upgrade to 3.3.5

### ISSUE THREAD

**Issue by beckysoll** [statamic/cms#5816]
### Bug description

I upgraded from 3.2.35 to 3.3.5 and I have a number of bard fields (no sets) in a global set that have antlers enabled where i'm using basic variables like {{ title }} that were working prior to upgrading, but after upgrading, the antlers code is displayed and not parsed.

### How to reproduce

1. add a bard field to a global set eg
`-
        handle: blog_people_page_intro
        field:
          always_show_set_button: false
          buttons:
            - bold
            - italic
            - removeformat
            - anchor
          save_html: true
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          display: 'Blog People Page Intro'
          type: bard
          icon: bard
          listable: hidden
          antlers: true
          instructions: 'Preceded by number of posts eg "*8* posts tagged with..."'`

2. Save field in global to this value:
`blog_people_page_intro: '<p>posts tagged with or written by <a href="/about-cs/who-we-are#{{ slug }}">{{ title }}</a>.</p>'
`
3. view in statamic 3.2.35 and you will see the value of {{ title }} displayed. view in statamic 3.3.5 and you will see {{ title }} displayed on the front end.

### Logs

```shell
nothing in logs
```

### Versions

Statamic 3.3.5 Pro (vs 3.2.35 Pro)
Laravel 8.83.7
PHP 8.1.4
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
I can't reproduce this. If this is still an issue for you, could you please provide a GitHub repo with this issue reproduced? Thanks!
