### ISSUE TITLE
[Antlers Runtime] Modifier not found

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#5817]
### Bug description

I was trying to update a site to the new runtime parser and encountered, that parameters of a livewire component can't be passed anymore.  I always encounter, regardless of the name of the parameter, a modifier not found exception.

I'd expect the runtime to not do anything if a modifier isn't found and rather treat it as a parameter.

### How to reproduce

Create a view that uses the livewire tag and try passing variables to that comonent:
``{{ livewire:events-filter locale="{ site:handle }" :categories="null" :detail_category="null"  }}``

### Versions

Statamic 3.3.6 Pro
Laravel 9.7.0
PHP 8.0.13
doublethreedigital/duplicator 2.1.1
jonassiewertsen/statamic-livewire 2.7.1
rias/statamic-redirect 2.0.0
schantldev/newsletter dev-main
schantldev/shop dev-main
spatie/statamic-responsive-images 2.8.5
stillat/meerkat 2.5.0

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
When you get that error it's because it's treating `livewire:events-filter` as a variable, not a tag.

Do you happen to have a variable named `livewire`?

Can you put a `{{ dump }}` right above your livewire tag and see if there's a `livewire` in there?

**Comment by jasonvarga** [comment]
If you need that, you can force Antlers to use the tag with a `%`.

`{{ %livewire:events-filter }}`
