### ISSUE TITLE
[Runtime Parser] Call to a member function getActiveNode() on null

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#5818]
### Bug description

If I am passing terms to a parameter, I am getting a ``Call to a member function getActiveNode() on null`` exception.

``{{ livewire:events-filter :locale="site:handle" :categories="event_type" :detail_category="event_category" }}``
-> will give me the exception

``{{ livewire:events-filter :locale="site:handle" categories="{ event_type }" detail_category="{ event_category }" }}``
-> will give me no exception. the terms are now inside an array instead of a TermCollection

I would expect to first one to work as well – it works with the regex parser as well.

### How to reproduce

Create a blueprint with a term fieldtype and try to pass that variable as a parameter.

### Versions

Statamic 3.3.6 Pro
Laravel 9.7.0
PHP 8.0.13
doublethreedigital/duplicator 2.1.1
jonassiewertsen/statamic-livewire 2.7.1
rias/statamic-redirect 2.0.0
schantldev/newsletter dev-main
schantldev/shop dev-master
spatie/statamic-responsive-images 2.8.5
stillat/meerkat 2.5.0

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by JohnathonKoster** [comment]
Looks to be the same issue as described in #5811

**Comment by AndreasSchantl** [comment]
True that. Will close this one in favor of that one.

Duplicate of #5811
