### ISSUE TITLE
Modifier truncate doesn't have second parametr working on rutime

### ISSUE THREAD

**Issue by jbrhel** [statamic/cms#5833]
### Bug description

Runtime mode selected. When the second parametr of modifier **truncate** is used, it's not affecting an output.

title = 'More than six chars'

`{{ title | truncate:6:... }}`

**Output:** 
'More t' 

Output is witohut 3 dot's at the end of string.

### How to reproduce

Runtime mode of the antlers parser selected. Then added second parameter to the truncate modifier '...'.

`{{ title | truncate:6:... }}`

### Versions

Statamic 3.3.6 Pro
Laravel 8.81.0
PHP 8.0.14
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by wm-simon** [comment]
@jackmcdade Hey Jack, would it be possible to add the new syntax to all modifier entries?
It would be helpful, if something like this `{{ title | truncate(6, '...') }}` find here:
https://statamic.dev/modifiers/truncate

**Comment by jackmcdade** [comment]
Unfortunately no – we can't update that syntax until the new parser is the default parser. It would cause way more confusion to switch it now.

**Comment by jasonvarga** [comment]
What Jack means is that we aren't going to document the new parser syntax outside of the new parser docs until the new parser is the default. We're not going to remove the old syntax from the code.
