### ISSUE TITLE
Single character variables cause issues unless used with spaces

### ISSUE THREAD

**Issue by richarderoche** [statamic/cms#5842]
### Bug description

This may be pretty niche, but perhaps could point to other issues. When you have a single character variable and don't use spaces inside your antlers brackets, everything after the variable in the html gets ignored until you reach another variable. I encountered this storing X and Y variables for data points. This was not the case in the regex parser.

### How to reproduce

`
{{ a = "A" ab = "AB" }}
{{a}} invisible {{ a }} visible {{ab}} visible
`

### Versions

Statamic 3.3.7 Pro
Laravel 9.8.1
PHP 8.1.4

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by richarderoche** [comment]
One more note: If you throw a modifier in there everything is fine. So it might be related to not having enough characters inside the brackets rather than the length of the variable itself.

**Comment by jasonvarga** [comment]
Having two variable assignments like that without a delimiter, just a space is valid? That seems odd.

**Comment by JohnathonKoster** [comment]
> Having two variable assignments like that without a delimiter, just a space is valid? That seems odd.

Used to be a hard requirement. It inserts semicolons automatically where it can (from early feedback).
