### ISSUE TITLE
Asset URL returns null when using "url", but works with Glide

### ISSUE THREAD

**Issue by bennettblack** [statamic/cms#5851]
### Bug description

As the title states, I'm able to render image URL's using the glide modifier, but not with the URL modifier. 

`{{ cover_photo:url }}` returns null
`{{ cover_photo | url }}` returns null
`{{ glide:cover_photo }}` yields the URL

Antlers / HTML:

```
{{ featured }}
    <div class=" h-[300px] rounded relative ">

        <img src="{{ glide:cover_photo }}" alt="{{ cover_photo:alt }}" class="object-cover h-full w-full rounded " fit="crop_focal">

        <div class="h-full w-full flex flex-col justify-end bg-black bg-opacity-20 hover:bg-opacity-10 absolute top-0 p-4"
            href="#"
            >
            <div class="w-full">
                <div class="text-white font-semibold text-lg w-[300px]">
                    {{ title }}
                </div>
                <div class="text-xs text-white mt-1">
                    {{ date format="F d, Y" }}
                </div>
            </div>
        </div>
        <div class="flex absolute top-4 left-4">
            {{ categories }}
            <a class="bg-swark-blue text-xs rounded-sm bg-opacity-80 text-white mr-2 py-1 px-1.5"
                href="{{ url }}"
                >
                {{ title }}
            </a>
            {{ /categories }}
        </div>
    </div>
{{ /featured }}
```

### How to reproduce

1. Setup the latest version of Statamic on Laravel 9 with PHP 8.0+
2. Serve an asset from a Digital Ocean Space with a root path set.
3. Try to use the 'url' modifier in antlers when retrieving a collection.

### Versions

Statamic **3.3.7 Pro**
Laravel **9.8.1**
PHP **8.0.11**
**No addons installed**

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Assets are being served from a Digital Ocean Space. I am specifying a root path, if that matters. Here's my disk:

```
'articles' => [
    'driver'        => 's3',
    'key'           => env('DIGITALOCEAN_SPACES_KEY'),
    'secret'        => env('DIGITALOCEAN_SPACES_SECRET'),
    'endpoint'      => 'https://nyc3.digitaloceanspaces.com',
    'region'        => 'nyc3',
    'bucket'        => 'swarktoday',
    'visibility'    => 'public',
    'root'          => 'articles'
],
```

**Comment by jasonvarga** [comment]
You need a `url` in your filesystem array. It's probably `https://nyc3.digitaloceanspaces.com/swarktoday/articles/`
