### ISSUE TITLE
Title isn't really optional

### ISSUE THREAD

**Issue by aerni** [statamic/cms#5856]
### Bug description

From what I understand, the new title format feature exists to make the title completely optional. This isn't really the case though.

If I leave the `Title Format` in the collection settings empty, it will still always add a title field to my blueprint. And if I use a hidden field for the title instead – like it does when using the title format – it will throw a validation error when saving the entry because the title is required.

We probably need something like a toggle on the collection settings so we can explicitly set the title to required. If it is required, the blueprint should always add a title field. If the title is not required, it should not add a title field.

### How to reproduce

Try to save an entry without a title. It will always save `title: {whatever}` to the entry. Either because you use the title format feature or because you manually set the title.

### Versions

Statamic 3.2.39 Pro
Laravel 8.83.8
PHP 8.0.14

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
Okay yes we do save `title`, but it's automatic.

What's the problem with having a title if you don't have to manually do it?

**Comment by aerni** [comment]
What if you don't want a title at all? As of now, you still have to come up with some sort of `title_format`. And you might not have a field on the entry that you could use to make the title unique. It's also just cumbersome to have to come up with something you won't use. And the UX in the settings is a bit confusing. I'd expect the title to be empty if the `title_format` is empty.

The UX could easily be improved like this:
- Have a new `Require Title` toggle. This makes it consistent with the already existing `Require Slug` toggle.
- Make the `Title Format` field conditionally appear if the `Require Title` toggle is active.
- If you set the `Title Format` the title will generate automatically. If you leave it empty, you'll have to manually set the title.
- If `Require Title` is false, the title field will be removed from the blueprint and title won't be set on the entry.

**Comment by jasonvarga** [comment]
You need a title. We use it everywhere where there'd be mixed references. Like search results. You could use the id as a title.

**Comment by aerni** [comment]
Gotcha! A good compromise could be to default to the `id` then. Maybe introducing a `Generate Title` toggle instead. If activated, the `title_format` will use the `id` by default. If the toggle is not activated, the title can be set manually like usual.
