### ISSUE TITLE
Cursor in text editor bugs out when resizing window or using live preview

### ISSUE THREAD

**Issue by tao** [statamic/cms#5883]
### Bug description

Our website editor pointed this bug out and found out how to replicate it, I've had it a few times over the last few months but couldn't quite figure it out.

When you **resize** the text editor the cursor position is totally out of sync with the text and doesn't render properly.

The longer the article is as well, the stranger the cursor behaves, and at the top of the article the cursor might only be a few lines out of place, but towards the end of the long article it could be 15 or 20 lines out of sync.

### How to reproduce

When you use the text editor, you can see the cursor is at the end of my first list item:

---
![Screenshot 2022-04-22 at 00 13 13](https://user-images.githubusercontent.com/1446331/164560414-485178fb-878b-46a7-ac9e-e3a4e374002a.png)
---

Then if I enter Live Preview and put the cursor in the same place...

---
![Screenshot 2022-04-22 at 00 13 53](https://user-images.githubusercontent.com/1446331/164560445-cad57ba1-007e-4017-b39c-8221f53719c4.png)
---

And then I close live preview, it puts the cursor in the middle of nowhere and the text editor starts acting really weird:

---
![Screenshot 2022-04-22 at 00 16 00](https://user-images.githubusercontent.com/1446331/164560529-ce157188-3a8d-443e-988a-dfc6fe920e1c.png)
---

If I try type now, it puts "HELLO WORLD" in a random place below the cursor:

---
![Screenshot 2022-04-22 at 00 16 50](https://user-images.githubusercontent.com/1446331/164560630-aff3a209-4beb-4d86-8ee3-21bc5b437400.png)
---

It's totally messed up and my admin has to save and refresh the browser, so my "Spock" Github Integration commit history is getting really messy with all the saves he's making trying to work around this bug.

Also happens to me sometimes if you just enter Live Preview, and drag the resize divider to make the text editor larger.

---
![Screenshot 2022-04-22 at 00 19 30](https://user-images.githubusercontent.com/1446331/164560890-a557eeb0-c0d7-4a69-bbf1-ce65d632c821.png)
---

### Versions

Statamic 3.2.39 Pro
Laravel 8.83.8
PHP 8.0.17
statamic/ssg 0.9.0

### Installation

Fresh statamic/statamic site via CLI

### Additional details

It's very annoying. It also happens a few other times when I'm editing translations but it's very difficult to replicate usually.

**Comment by duncanmcclean** [comment]
I actually don’t like this is limited to Live Preview. I’ve had it happen before too, when not using Live Preview.

**Comment by tao** [comment]
It's a tricky one to figure out but at least it's possible to replicate it using the live preview. I think I also came across it using the browsers find and replace feature a few times, but not 100% sure.

**Comment by jasonvarga** [comment]
@tao could you let us know if 3.3.11 helps with this at all? (See #6016)

**Comment by tao** [comment]
@jasonvarga Unfortunately not, if I follow the steps the cursor is still out of sync... even if I try double click on the first list item with my mouse, the cursor still ends up 3 paragraphs down. However, as soon as you resize the browser window it "refreshes" and the cursor now appears where you click. Maybe you could "repaint" the text editor when the live preview closes the same way as the browser resize does?

https://user-images.githubusercontent.com/1446331/167817979-bcc1fa33-a11b-45b9-9d9b-ecd15ac8dbb1.mov

And if you resize the edit pane during a live preview, the cursor goes out of sync again until you resize the browser window.

https://user-images.githubusercontent.com/1446331/167817597-15471937-b89f-456b-aade-91bbec0123aa.mov

And I'm using the recent update:

```
Statamic 3.3.11 Pro
Laravel 8.83.12
PHP 8.0.17
statamic/ssg 1.0.1
```
