### ISSUE TITLE
special characters not working when static page caching is enabled

### ISSUE THREAD

**Issue by Oleafeon** [statamic/cms#5886]
### Bug description

when i use a special character like "è" in the cp the website will show that character on the frontend just fine, but when i turn static page caching on the character is broken i have tried the ascii modifier but that just replaces the character with a normal e

cp:
![image](https://user-images.githubusercontent.com/20043831/164620626-447fa562-5b4d-4780-8622-6a06b9921fc9.png)

with static page caching enabled:
![image](https://user-images.githubusercontent.com/20043831/164620733-6264bcb5-d711-4c4b-8bcf-fa2bf4c5b49e.png)

with static page caching disabled:
![image](https://user-images.githubusercontent.com/20043831/164620940-023809d7-e674-4d8a-a59b-6d332cda7383.png)

### How to reproduce

go to the cp an edit a page
place an è in a text field
turn on static page caching

### Versions

Statamic 3.2.24 Pro
Laravel 8.73.2
PHP 7.4.29
doublethreedigital/duplicator 2.0.1
jonassiewertsen/statamic-live-search 1.2.0
jonassiewertsen/statamic-livewire 2.7.0
optimoapps/statamic-bard-text-align 1.0.2
rias/statamic-link-it 2.2.3

### Installation

Fresh statamic/statamic site via CLI

**Comment by staudenmeir** [comment]
Which strategy are you using? `half` or `full`?

**Comment by Oleafeon** [comment]
full

**Comment by staudenmeir** [comment]
Are the characters already broken when you visit the page for the first time and the HTML is created or only in subsequent requests when the cached HTML file is delivered?

Are you using Apache or nginx?

Can you share the broken HTML file?

**Comment by Oleafeon** [comment]
when you visit the page after editing the pag in the cp it works but when you reload it breaks

i am using Apache

here you go [home.zip](https://github.com/statamic/cms/files/8620373/home.zip)

Sorry for the late reply i had the rest of the day off

**Comment by staudenmeir** [comment]
Try adding `<meta charset="UTF-8">` to the `<head>` element of your base layout (like in this [Tailwind example](https://tailwindcss.com/docs/installation#:~:text=Start%20using%20Tailwind%20in%20your%20HTML)). This line should be in _every_ HTML document.

**Comment by Oleafeon** [comment]
Seems to work this time
