### ISSUE TITLE
Remote asset folders still disappearing

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5888]
### Bug description

I've brought this up before for DO Spaces: #5723  Now it's happening on S3. Folders are disappearing straight after creation, even though they exist when logging into S3 or DO directly.

Here's a quick video:
https://www.dropbox.com/s/mnwgr2ip50cvj5k/assets.webm?dl=0

The folders do in fact exist on remote storage. If I manually enter this url on Statamic:
http://website.test/cp/asset-containers/images/test-folder
This I can see the previously uploaded assets.

**It seems to be a caching issue.** Running **php artisan cache:clear** fixes it temporarily (only on local server, not production), but then everything dissappears again on the next refresh. This happens regardless of whether my glide cache is enabled.

I'm noticing occasional errors like so, not sure if related:
`production.ERROR: Unable to copy file from source://folder/aston-quay-1.jpg to cache://folder/aston-quay-1.jpg {"userId":"6be0c41a-0ee4-41d2-9ea2-xxxx","exception":"[object] (League\\Flysystem\\UnableToCopyFile(code: 0): at /home/forge/wesbsite.ie/vendor/league/flysystem/src/UnableToCopyFile.php:37)`

### How to reproduce

No idea. Statamic 3.3 seems to the problem because if I revert to 3.2, with either S3 or DO, then all the folders are shown correctly.

I don't think I'm doing anything unusual. I am using the default S3 filesystems config of the latest Laravel. I do have the root set to: '/images'  though (I use the same s3 bucket for multiple disks).

### Versions

Statamic 3.3.9 Pro
Laravel 9.9.0
PHP 8.1.1
rias/statamic-redirect 2.1.2
statamic/seo-pro 3.1.0

### Installation

Existing Laravel app

**Comment by jesseleite** [comment]
Hey @stuartcusackie, can you run the following and paste the output?

```
composer info | grep flysystem
```

Also which cache driver are you using?

**Comment by stuartcusackie** [comment]
```
league/flysystem                   3.0.17   File storage abstraction for PHP
league/flysystem-aws-s3-v3         3.0.13   AWS S3 filesystem adapter for Flysystem.
```

The problem first occurred with only glide caching in place, and no static caching. I'm now not using a glide cache, and I have half static caching turned on. I haven't seen the issue in a couple of days but I haven't been playing with the asset manager much. I have a feeling it will be back.

**Comment by jesseleite** [comment]
@stuartcusackie I'm struggling to recreate this. Using digital ocean spaces, with all the same versions you mention (of statamic, laravel, flysystem, flysystem-aws-s3-v3, etc), using the `root` config on the filesystem, etc. Would you be able to upload/push a bare test repo where you have the minimal config setup to reproduce the problem?

**Comment by stuartcusackie** [comment]
@jesseleite  Happy to give you access to the actual website repo along with s3 credentials if that would work somehow?

**Comment by jesseleite** [comment]
@stuartcusackie Sounds great. Not sure I'll need s3 credentials, maybe we can reproduce with access to the repo only. Let's move this to email... https://statamic.com/support (if you login first, that'll bring you to the developer support form)

**Comment by stuartcusackie** [comment]
Support form filled in. Cheers.

**Comment by stuartcusackie** [comment]
@m-glass I think the docs might need updating. I'm using Laravel 9 and Statamic 3.3 should be compatible with Flysystem 3.

**Comment by jesseleite** [comment]
> @m-glass I think the docs might need updating.

Yep, we support both flysystem 1.x and 3.x. Just [updated the docs](https://github.com/statamic/docs/pull/806), good catch!

**Comment by jesseleite** [comment]
Just an update: Reproducing this issue requires turning off stache watcher. Thanks @stuartcusackie for helping us reproduce the issue 👍

**Comment by stuartcusackie** [comment]
This problem has come back: See https://github.com/statamic/cms/issues/5723
