### ISSUE TITLE
Glide cache custom disk adding %5C to urls

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5894]
### Bug description

I've just tested out remote glide caching and the urls have a %5C (backslash) incorrectly added to them, and so the images don't load. e.g.:
https://mybucket.s3.eu-west-1.amazonaws.com/glide%5C/http/images/hampton-hotel_be49084f.png/03cc33278043cdb1c568bed56e9d8dfc.webp

I'm also not sure why the 'http/images' segment is being added either. Looks a bit odd and I would prefer not to have it.

Thanks.

### How to reproduce

I added this to my config/statamic/assets.php
`'cache' => 's3_glide'`

Here's my filesystem:
```
   's3_glide' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'throw' => false,
            'root' => 'glide',
            'visibility' => 'public'
        ]
```

I am using a 'root' parameter on my disk so perhaps that is having an effect?

### Versions

Statamic 3.3.9 Pro
Laravel 9.9.0
PHP 8.1.1
rias/statamic-redirect 2.1.2
statamic/seo-pro 3.1.0

### Installation

Existing Laravel app

**Comment by staudenmeir** [comment]
What is your asset container called? `images`?

> https://mybucket.s3.eu-west-1.amazonaws.com/glide%5C/http/images/hampton-hotel_be49084f.png/03cc33278043cdb1c568bed56e9d8dfc.webp

Are you generating this URL with a `{{ glide }}` tag?

> I am using a 'root' parameter on my disk so perhaps that is having an effect?

We are also using a `root` parameter on our disk and the cache works for us.

Our URLs look like this (`assets` is the asset container):

https://cdn-domain.com/glide/containers/assets/example.jpg/7524fe78edf806b7e26b0ecbd18648ec.webp

The `/containers/` segment is actually hard-coded into Statamic and so I'm wondering why it is missing in your URL:

https://github.com/statamic/cms/blob/590839b35583b5b9b647da93ae82b8ad170fd5da/src/Imaging/ImageGenerator.php#L160

**Comment by jasonvarga** [comment]
The `/http/` part of the URL tells me that you aren't passing an asset to the Glide tag. Maybe you're just giving it a URL. While this would work most of the time, if you have an asset, you should give it an asset. Could you show what your glide tag looks like @stuartcusackie ?

**Comment by stuartcusackie** [comment]
Hey guys, I might have to close this issue. I have since abandoned my custom glide responsive component, where this problem was occurring. I'm now using spatie's responsive images on this project and I cannot reproduce this error.

I probably won't be using the glide cache now but I did try to to enable a custom caching disk, just to see what would happen with Spatie. Different errors appeared this time:
`Unable to read file from location: containers/images/banners/4-day-trial-membership-banner.jpg/9a61a8b719827681fb8dbf09ce1dc884.jpg.`

I'll park this for now.

**Comment by staudenmeir** [comment]
> Though I don't see how that applies in this case, since the storage is remote and probably linux based.

The URLs are actually generated on your Windows machine and that looks like the cause of the issue.

Can you put `{{? dd(Storage::disk('s3_glide')->url('/')) ?}}` in one of your views and share the result?

**Comment by stuartcusackie** [comment]
That produces:
"https://mybucket.s3.eu-west-1.amazonaws.com/glide\"

I thought Laravel solved this Windows path stuff a while back. Any suggestions?

**Comment by staudenmeir** [comment]
I dug into the code and found that the backslash is set by Laravel as it's your OS's directory separator (of course, that doesn't make sense for S3 disks).

You can override it in your disk config:

```php
's3_glide' => [
    // ...
    'directory_separator' => '/',
]
```

**Comment by stuartcusackie** [comment]
nice find! Thank you very much!!
