### ISSUE TITLE
S3 assets not shown (Container is empty)

### ISSUE THREAD

**Issue by m-glass** [statamic/cms#5904]
### Bug description

I connected an S3 bucket (DO Spaces) as an asset driver and it won't show any items. I can create and delete folders inside the Statamic CP though, but folders already existing inside the bucket (3gb) won't be shown. It just says 'Container is empty'.

Problem already mentioned in #1188 and #2145. Also fixed in #2828 but still seems to appear.

### How to reproduce

Connect a DO space ([just like explained here](https://statamic.dev/tips/digital-ocean-spaces-for-asset-container)), look into the asset browser and see nothing.

### Versions

Statamic 3.3.9 Pro
Laravel 9.9.0
PHP 8.1.3
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by m-glass** [comment]
Additional info: I can create folders on the bucket via the Statamic asset browser though. But I still can't upload files, it gives me some errors in the toast notifications:

'Internal Server Error' when I'm trying to upload a single asset (which is less than 1 MB and meets server (valet) constraints)
'Upload failed. The file might be larger than is allowed by your server' when I'm trying to upload a folder (which is less than 1 MB and meets server (valet) constraints).

**Comment by jackmcdade** [comment]
Have you tried updating to 3.3.11? It includes a fix to s3 listing caches – https://github.com/statamic/cms/pull/5996

**Comment by m-glass** [comment]
Yes, I did. Problem still persists.

**Comment by m-glass** [comment]
Additional info: as I'm trying to upload an asset (simple png image) into the CDN-backed asset container, it still doesn't work but at least it now outputs an error message.

First, in the frontend:

![image](https://user-images.githubusercontent.com/40246628/176273940-73d6117b-3454-4e6e-95f9-92178a7a3ea1.png)

and also in the laravel log:

```log
[2022-06-28 20:55:43] local.ERROR: Call to a member function getClientOriginalName() on null {"userId":"er46618a4-2d8f-[...]f97c1rt4","exception":"[object] (Error(code: 0): Call to a member function getClientOriginalName() on null at [...]/vendor/statamic/cms/src/Http/Controllers/CP/Assets/AssetsController.php:81)
[stacktrace]
```

**Comment by m-glass** [comment]
Alright, I finally got some motivation to dive into this again and found the solution. Indeed, this problem wasn't a Statamic-related one but rather one that stems from a lack of permission control in the DO spaces interfave. The following solution applies to using DigitalOcean Spaces as the S3 provider only.

1. Make sure to set your PHP server/Valet settings correctly in the corresponding `php.ini`. [This](https://dorelljames.com/blog/laravel-valet-increase-max-upload-file-size/) helped me to find my applied php.ini files.
2. Connect your DO space as described [here](https://statamic.dev/tips/digital-ocean-spaces-for-asset-container).
3. Now, if you try to upload a folder containing a few files, you'll see that you can't upload folders to the DO space through Statamic asset browser. Also to a local driver a folder upload is not possible. I'm not sure if that's a bug or if it's intentional or a Laravel thing I didn't know about (@jackmcdade are there any infos out there?). That's why Statamic says `Upload failed. The file might be larger than is allowed by your server.`. Folders _must_ be created either through the Statamic asset browser or within the DO space interface.
4. Because folder uploads aren't possible, I tried to upload the folders through the DO space interface, which worked. But these uploaded folders and their items didn't get shown in the Statamic asset browser (no matter which visibility/permissions are set). File uploads were shown though. So, the problem might be a permission problem. Digital Ocean doesn't set the correct permissions while uploading through their uploader interface.
5. So I tried it with a third-party-application and this is the solution. I used [Cyberduck](https://cyberduck.io/) since it seems to be pretty popular within FTP/S3/etc. clients. Connect with your DO space credentials and upload your folders with your gazillions of assets. Once the upload is done, head to the DO space interface or Statamic asset browser and you'll see your folders and files. But if you try to look at a file in the browser using the absolute URL, you'll only see a XML page with a `permission denied` value.
6. For the last step you need to set permissions recursively. Head to Cyberduck and select all files and folders in the parent directory, right click, `Info` -> `Permissions` -> add a `Everyone` Grantee with a `READ` permission. If these files still show `Private` in the DO spaces interface when you inspect the permissions of a affected file, select the `FULL_CONTROL` permission instead.

I really hope this helps someone out there.
