### ISSUE TITLE
Open and close tags in blade?

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5908]
### Bug description

I just stumbled upon the new no_cache tag, which sounds great, but I'm not seeing an easy way to use it in blade.

With blade we can call a tag like so:
`Statamic::tag('no_cache')`

But how would I output content in between the tag? I assume this wont work but it doesn't cause an error.
```
@php(Statamic::tag('no_cache'))
  <livewire:dynamic-form /> 
@php(Statamic::tag('/no_cache'))
```

Any ideas? I may be misunderstanding the no_cache tag concept so this may not work at all.

### How to reproduce

No details.

### Versions

Statamic 3.3.9 Pro
Laravel 9.9.0
PHP 8.1.1
rias/statamic-redirect 2.1.2
spatie/statamic-responsive-images 2.11.2
statamic/seo-pro 3.1.0

### Installation

Existing Laravel app

**Comment by edalzell** [comment]
Not in Statamic yet, PR has yet to be merged.
