### ISSUE TITLE
User GroupRoles aren’t reflected into the user roles

### ISSUE THREAD

**Issue by mkriegeskorte** [statamic/cms#5931]
### Bug description

I’ve created a user group and attached a role to it. After that I’ve assigned a user the group.

As stated in the docs, the roles of a user group should get automatically reflected into the roles of the user (https://statamic.dev/users#user-groups).

Outcome:
`$user->groups` outputs the group

`
Auth::user()->groups()->map(function($group) {
   $group->roles; // Has the roles as expected!
});
`

`$user->roles` is empty (this seems off!)

Furthermore if I take the naive approach to loop through this via antlers, the roles are missing, too!

`
{{ current_user }}
  {{ groups }}
    {{ roles }}
      {{ name ?? title }} // empty as well
    {{ /roles }}
  {{ /groups }}
{{ /current_user }}
`

I would expect to get the group roles reflected into the users roles.

**Addition:** The role check doesn’t seem to work with group roles either. (https://statamic.dev/tags/user-is)

### How to reproduce

1. Create a role
2. Create a user group, assign the role
3. Assign the group to a user

### Versions

Statamic 3.3.9 Pro
Laravel 9.9.0
PHP 8.0.13

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
The _permissions_ are inherited through the roles.
The roles themselves aren't going to be on the user.

Rather than checking if a user has a role, you should check permissions.

In a tag: https://statamic.dev/tags/user-can
In PHP: `$user->can('something')`
