### ISSUE TITLE
ViewModels don't work on blueprints, just collections.

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5936]
### Bug description

First time using the ViewModels so I might have this wrong, but I found [a comment](https://statamic.com/forum/5514-view-model-controller-for-fieldsets-for-content-api) that says ViewModels can be used on blueprints. I can't get it working however.

I have a 'Pages' collection with many blueprints. I want to use a ViewModel on only one of these blueprints, e.g. a FormPage blueprint.

Under blueprints\collections\pages\form_page:

```
title: FormPage
inject:
  view_model: App\ViewModels\FormPage
```

The above is having no effect but it does work when used in the pages collection (content\collections\pages.yaml).

I can work around it by checking the blueprint from within the ViewModel but just want to know if this is supposed to be supported?

### How to reproduce

Try injecting a view model on a blueprint, rather than a collection.

### Versions

Statamic 3.3.9 Pro
Laravel 9.9.0
PHP 8.1.1
aerni/livewire-forms 3.2.0
jonassiewertsen/statamic-livewire 2.9.0
rias/statamic-redirect 2.1.2
spatie/statamic-responsive-images 2.11.2
statamic/seo-pro 3.1.0

### Installation

Existing Laravel app

**Comment by jasonvarga** [comment]
This is not a blueprint feature. It's a collection feature. That comment may have been a misunderstanding.

**Comment by stuartcusackie** [comment]
Cool. Just double checking. This is what I'm doing to check the blueprint within the viewmodel, in case it's useful to anyone:
`if($this->cascade->get('blueprint')->value()->handle == 'yourblueprint') { doXYZ(); } `

There's probably a simpler way.
