### ISSUE TITLE
Entry search not working on remote

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5953]
### Bug description

Searching for a simple page entry like so on local produces the correct result:

![image](https://user-images.githubusercontent.com/20210934/165940671-0dcc2a63-d459-4517-9d57-a15d91ca4746.png)

Performing the same search on a staging server produces no results:
![image](https://user-images.githubusercontent.com/20210934/165940717-f447b15d-b3cd-45be-b0bc-7975f491afa0.png)

Some results are being returned for other searches on staging but far fewer results than on local.

### How to reproduce

 No clues yet. I've disabled static caching and enabled the stache watcher to test but no difference.

### Versions

Statamic 3.3.9 Pro
Laravel 9.10.1
PHP 8.1.1
aerni/livewire-forms 3.2.0
jonassiewertsen/statamic-livewire 2.9.0
rias/statamic-redirect 2.1.2
spatie/statamic-responsive-images 2.11.2
statamic/seo-pro 3.1.0

### Installation

Existing Laravel app

**Comment by edalzell** [comment]
have you updated the search index?

**Comment by stuartcusackie** [comment]
I've made no changes to config/statamic/search.php, if that's what you mean.

**Comment by grandpalacko** [comment]
@stuartcusackie You can either update the search index via CLI:

```
# Update all indexes
php please search:update
```

Or in the Control Panel under Tools / Utilities / Search.

Updating search index in the docs: https://statamic.dev/search#updating-indexes

**Comment by stuartcusackie** [comment]
@grandpalacko  That fixed it. Thank you!

I wonder what went wrong...
