### ISSUE TITLE
Modifier lower / upper does not work on {{ trans }} tag

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#5965]
### Bug description

I've created a lang file `resources/lang/no/recreate.php` and use it like this `<p>{{ trans:recreate.buy }} / {{ trans:recreate.sell | lower }}</p>` but the `lower` modifier has no effect. Neither does upper if it helps.

![Screenshot 2022-05-01 at 01 33 46](https://user-images.githubusercontent.com/1135679/166126015-0fce4845-32c5-45e9-857a-a898f5f5e869.png)

### How to reproduce

I think it's described enough in the description, but can provide more if needed.

### Versions

Statamic 3.3.10 Pro
Laravel 9.10.1
PHP 8.0.16
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by JohnathonKoster** [comment]
To use the results of a tag as a variable, you need to surround them in `{}`:

```antlers
<p>{{ trans:recreate.buy }} / {{ {trans:recreate.sell} | lower }}</p>
```

**Comment by espenlg** [comment]
I was not aware of this. Thank you!
