### ISSUE TITLE
Passing null parameter to parameter #2 ($replace) of type array|string

### ISSUE THREAD

**Issue by brandon14** [statamic/cms#5967]
### Bug description

Loading a fresh copy of Statamic 3.3 using the peak starter kit results in this warning showing up in the logs running on PHP 8.1.5.

### How to reproduce

Install a new Statamic 3.3 (using the runtime parser) with the Statamic Peak starter kit on PHP 8.1.5.

### Logs

```shell
[06:16:56] LOG.warning: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in D:\Users\b_ran\Sync\php-dev\brand0n.gg-peak\vendor\statamic\cms\src\View\Antlers\Language\Runtime\LiteralReplacementManager.php on line 103
```

### Versions

Statamic: 3.3.10
PHP: 8.1.5
Laravel: 9.10.1

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
This doesn't happen to me on a fresh Peak install, running PHP 8.1.4.
I'd open this issue on the Peak GitHub repo with more information.
Or, provide the rest of the stack trace in the log file.

**Comment by kobe-f8** [comment]
Hi brandon14, I also have this problem on a fresh peak install.

**Comment by hansipete** [comment]
Same here on a site running Peak :(

Statamic 3.3.13 Pro
Laravel 9.16.0
PHP 8.1.7
