### ISSUE TITLE
Select field casts to integer instead of preserving string

### ISSUE THREAD

**Issue by aerni** [statamic/cms#5969]
### Bug description

I've got a select field with options like `0.0` and `1.0`. The value and label of the `LabeledValue` object will be cast to a `0` and `1` instead of `0.0` and `1.0`. Options like `0.5` will be augmented correctly.

### How to reproduce

Add the following select field and choose either option. Then add it to your template and see the issue.

```yaml
'field' => [
    'handle' => 'seo_sitemap_priority',
    'type' => 'select',
    'options' => [
        '0.0' => '0.0',
        '1.0' => '1.0',
    ],
],
```

### Versions

Statamic 3.3.10 Pro
Laravel 9.10.1
PHP 8.0.14
aerni/advanced-seo dev-main

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by caseydwyer** [comment]
Think this is (at least loosely) related to #2215 + #3179 + #3681. We're running into this with a `select` fieldtype as well, and have tried most things outlined in those other Issues, with no luck.
