### ISSUE TITLE
Date not showing in Safari

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#5976]
### Bug description

If you have a dated entry, the date is not showing in Safari, but does show in Firefox:
<img width="841" alt="CleanShot 2022-05-02 at 10 30 25@2x" src="https://user-images.githubusercontent.com/6069653/166314536-a31e0117-1ca6-4baa-8875-54897d043d28.png">

### How to reproduce

Have a dated collection, view an entry with Safari (Version 15.4 (17613.1.17.1.13)).

### Versions

```
Statamic 3.3.10 Pro
Laravel 9.10.1
PHP 8.1.5
aryehraber/statamic-captcha 1.8.0
aryehraber/statamic-uuid 2.1.0
doublethreedigital/duplicator 2.2.0
edalzell/forma 1.1
edalzell/private-eye dev-main
jacksleight/statamic-bard-mutator 1.1.0
jacksleight/statamic-bard-texstyle 1.0.1
jonassiewertsen/statamic-jobs 1.1.0
jonassiewertsen/statamic-livewire 2.9.0
statamic/seo-pro 3.1.0
transformstudios/events 4.0
transformstudios/front 1.10
transformstudios/gated dev-main
transformstudios/github dev-main
transformstudios/magic-link dev-main
transformstudios/review 3.3
transformstudios/simple dev-feature/3.3
transformstudios/takeover-redirects dev-main
transformstudios/uptime dev-main
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by jackmcdade** [comment]
Should mention that this only happens when time is enabled.

**Comment by spaceageliving** [comment]
Hi @jackmcdade, I am still having this issue with 3.3.36 using Safari 15.4:

<img width="329" alt="Screen Shot 2022-09-14 at 11 07 13 AM" src="https://user-images.githubusercontent.com/874600/190218343-f52c83f0-08c3-4870-b171-95bd4a57aa52.png">

Chrome is working fine.

**Comment by jasonvarga** [comment]
Try deleting `vendor` and running `composer install` again. Then hard refresh in your browser.

**Comment by spaceageliving** [comment]
@jasonvarga Yep that worked.

Our site is running in production now and deploys via forge using:

```
$FORGE_COMPOSER install --no-interaction --prefer-dist --optimize-autoloader
```

Should I also delete vendor prior to deploy, or will this composer install be sufficient? Would like to avoid any downtime...

**Comment by jasonvarga** [comment]
No it should be fine. Sounds like there may have been some weird glitch during composer install where it didn't copy the new assets?

Or maybe the hard refresh was all you really needed to do. Not sure.

**Comment by spaceageliving** [comment]
I previously quit safari, restarted, flushed cache before your advice, so I think the composer install was the trick.

I ran the statamic update via the cp, so maybe something went amiss there...
