### ISSUE TITLE
locales:count not working inside if satement

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#5985]
### Bug description

The ``locales:count`` tag is not working inside an if statement.

### How to reproduce

```
{{ if locales:count > 0 }}
    there is always at least one locale - this should be printed
{{ else }}
    {{ locales:count }}
{{ /if }}
```

### Versions

Statamic 3.3.10 Pro
Laravel 9.10.1
PHP 8.0.13
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by ryanmitchell** [comment]
Did you try `{{ if {locales:count} > 0 }}` - I think this is the correct syntax for getting a tag value.
