### ISSUE TITLE
Unable to update roles.yaml file in laravel vapor

### ISSUE THREAD

**Issue by abhishekvijayan-zessta** [statamic/cms#5986]
### Bug description

I am hosting my site in laravel vapor. While adding permissions to roles it is showing an error like the screenshot
<img width="375" alt="image" src="https://user-images.githubusercontent.com/93115521/166669829-d66bce8f-6f6d-4402-966d-1da0eafcef5c.png">
I tried to change the roles.yaml path in "config/statamic/users.php" 
<img width="652" alt="image" src="https://user-images.githubusercontent.com/93115521/166670011-79f131b4-b04f-4c7f-aaa5-9bf751cf3951.png">
even after changing the path it is still taking the roles.yaml file from this path "config/statamic/users.php" 

Please suggest the wayout for this

### How to reproduce

Login to statamic
Goto Permissions
Try try to assign permission to a role

### Versions

Statamic 3.2.27 Pro
Laravel 8.76.2
PHP 8.0.8
daynnnnn/statamic-database 1.5.1
statamic/eloquent-driver 0.1.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
You can't update/change files with Vapor. That won't work.

**Comment by abhishekvijayan-zessta** [comment]
> You can't update/change files with Vapor. That won't work. You'll have to store the roles/permissions in a database if you want to be able to change them.

How can I achieve that

**Comment by duncanmcclean** [comment]
You'll have to wait for #5686 to be merged.

**Comment by crico** [comment]
Hi @duncanmcclean, Do you know if the pull #5686 is already released? We are working with Statamic v3.3.65, but we have not been able to migrate roles.yaml and groups.yaml to database. If not, do you know any workaround?

**Comment by duncanmcclean** [comment]
> Hi @duncanmcclean, Do you know if the pull #5686 is already released? We are working with Statamic v3.3.65, but we have not been able to migrate roles.yaml and groups.yaml to database. If not, do you know any workaround?

The pull request hasn't been merged yet. It'll only be included in a release when it's been merged.

You could potentially use a [Composer patch](https://rias.be/blog/using-composer-patches) to take advantage of the PR in the meantime.
