### ISSUE TITLE
Cannot render newly uploaded image on entry from queue worker

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#5988]
### Bug description

The customer has a queue worker running that will send emails with entry data when new entries are saved. When creating a new entry with a newly uploaded bard image, the queue worker / Statamic app needs to be restarted before the augmented bard value will properly render the new image's `src`.

### How to reproduce

They provided a [test repo](https://github.com/helloiamlukas/image-bug-example) to reproduce issue.  Don't worry about the AWS setup though; This happens with a local asset container too.

### Versions

I reproduced on:

Statamic 3.3.9 Pro
Laravel 9.9.0
PHP 8.1.5

Customer reproduce on:

Statamic 3.2.31 Pro
Laravel 8.61.0
PHP 7.4.29

**Comment by tomhelmer** [comment]
This seems like the same issue as : https://github.com/statamic/cms/issues/5501

**Comment by helloiamlukas** [comment]
This bug still persists when the image is within a Bard set. I updated the [test repo](https://github.com/helloiamlukas/image-bug-example) to reproduce this bug.
