### ISSUE TITLE
z-index in grid field type

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#5992]
### Bug description

Hi, 

Spotted this today, buttons are hidden.

![Screenshot 2022-05-04 at 16 14 21](https://user-images.githubusercontent.com/72254741/166713515-11191951-ecf0-4160-8dd8-6f41f6ba382e.png)

### How to reproduce

- Create a grid field type set to stacked
- Add a bard field
- Add a few rows
- Add a link to some text in a bard

### Versions

Statamic 3.3.10 Pro
Laravel 9.5.1
PHP 8.0.8
simonhamp/statamic-heroicons 1.0.1
statamic/collaboration 0.4.0

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jackmcdade** [comment]
Unfortunately this is an unfixable, stacking context situation. I'll have to redesign this dropdown to be a modal so it can be "portaled" outside the toolbar markup.

**Comment by jackmcdade** [comment]
Fixed in https://github.com/statamic/cms/pull/7589
