### ISSUE TITLE
Declaration of Statamic\Filesystem\FlysystemAdapter::exists($path) must be compatible with Statamic\Filesystem\AbstractAdapter::exists($path = null)

### ISSUE THREAD

**Issue by DEK-Pham-The-Anh** [statamic/cms#6001]
### Bug description

Hey @jasonvarga , I have just upgraded my statamic from v3.2 to v3.3 and now I got this error 
```
Declaration of Statamic\Filesystem\FlysystemAdapter::exists($path) must be compatible with Statamic\Filesystem\AbstractAdapter::exists($path = null)
```
which was probably caused by this change here https://github.com/statamic/cms/pull/5562. 

This error is showing only on the homepage, other pages are OK.

What is the root of the problem? Can you tell me how to get rid of this error? 
I want to avoid modifying vendor files such as `\vendor\statamic\cms\src\Filesystem\FlysystemAdapter.php`, if possible.

### How to reproduce

I upgraded Statamic from 3.2 to 3.3 and visited the homepage. I don't know the root of the problem so I can't tell for sure that anyone can reproduce this error, maybe its a problem specific to my CMS config/content.

### Versions

Statamic 3.3, PHP 8.0.10, Laravel ^8.0

### Installation

Other (please explain)

**Comment by duncanmcclean** [comment]
What is the output of `php please support:details`. You didn't provide that in your original description.

**Comment by DEK-Pham-The-Anh** [comment]
![image](https://user-images.githubusercontent.com/87691698/166911240-28c1f349-013c-46a9-ad62-a0619b8543d9.png)

**Comment by DEK-Pham-The-Anh** [comment]
Issue solved
