### ISSUE TITLE
Live preview don't update right when clearing field value

### ISSUE THREAD

**Issue by meandersen** [statamic/cms#6002]
### Bug description

When live previewing an already saved entry in a collection, empty the value in ex. the Title field. 
The live preview updates but it still shows the last saved value of that field.

### How to reproduce

Go into a collection, edit an existing entry.
Click the live preview button.
Empty the value in a field.
The live preview will still show the saved value

### Versions

Statamic 3.3.4 Pro
Laravel 8.83.5
PHP 8.1.1
jezzdk/statamic-kontainer 1.3.2
pecotamic/sitemap 1.2.8

### Installation

Starter Kit using via CLI

### Antlers Parser

regex (default)

**Comment by juliawarnke** [comment]
Having the same issue.
