### ISSUE TITLE
Checkbox checked with 'accept' validation shows error while it is checked

### ISSUE THREAD

**Issue by Sennik** [statamic/cms#6005]
### Bug description

I am using a checkbox in a form and set the validation rule in CP to 'accept'.

Beven when it is checked, it still shows an error that 'it must be accepted'. All other validations in this form  work like expected. Did I miss something?

### How to reproduce

create a form in CP, add checkbox, add validation 'accept'

### Versions

Statamic 3.3.10
PHP 8.1
Laravel 8.x

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Nope, just the regular shananigans, I used the default suggested Antlers email like suggested ([That automates the fields /field](https://statamic.dev/forms#the-template))

**Comment by staudenmeir** [comment]
Have you tried the `required` setting instead? I think that's supposed to be used in this case.

<img width="398" alt="Bildschirmfoto 2022-05-07 um 11 14 38" src="https://user-images.githubusercontent.com/1853169/167247736-237d54a9-4535-44c8-aaac-f49474f48e84.png">

**Comment by jasonvarga** [comment]
There is no "checkbox" fieldtype. Do you mean "checkboxes"? In that, it stores multiple options, so using an `accepted` validation doesn't make sense.

If you want some boolean value to be stored, you should use the "toggle" fieldtype instead. This works with the `accepted` validation rule.

Also, make sure the validation rule is `accepted`. You wrote `accept` in your issue.

**Comment by jasonvarga** [comment]
@staudenmeir FYI you shouldn't use `required`. It's perfectly valid to submit a boolean field with a falsey value. Requiring just means it has to be in the request. Using the `accepted` rule means it must be true.

**Comment by Sennik** [comment]
@jasonvarga Sorry slip of the pen, I mean of course 'accepted'.

The fieldtype checkboxes creates checkbox(es): <input type="checkbox">, and yes it can post multiple checkboxes in an associative array but when I use one (In html) it is a simple name/value pair which Laravel perfectly validates with the 'accepted' rule. I like the looks of a simple checkbox for a Terms & Conditions question. 

Shouldn't it be logical for Statamic to handle a single checkbox as a name/value pair?

**Comment by jasonvarga** [comment]
Checkboxes implies plural - or an array - which `accepted` doesn't work with.

If you want a single boolean, use a `toggle`. It will be rendered as a checkbox on frontend forms.
