### ISSUE TITLE
Conditionals on Field Not Persisting Correctly

### ISSUE THREAD

**Issue by daylightstudio** [statamic/cms#6008]
### Bug description

I wanted to setup multiple conditions on a field so that it would not appear on two different templates. I added the additional condition but it wound up overwriting the previous conditions value and did not add the additional condition. This explains it better:

### How to reproduce

1. Went to fields sets to edit
2. Clicked on Conditionals for the field I wanted to edit
3. Added the extra condition and clicked Finish
4. Clicked saved on next screen
5. Went back to Conditionals and it overwrote the value previous value with the new value and didn't persist my new condition 
 
[This link best explains the steps](https://share.getcloudapp.com/P8u1Agrz).

### Versions

Statamic 3.2.39 Pro
Laravel 8.80.0
PHP 7.4.21
aryehraber/statamic-captcha 1.8.0
doublethreedigital/duplicator 2.2.0
rias/statamic-redirect 2.0.0
spatie/statamic-responsive-images 2.10.1
statamic/seo-pro 2.3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by staudenmeir** [comment]
This is also happening in `v3.3.10`.

The underlying issue is that the conditions are keyed by the referenced field and so only one condition is stored per field:

<img width="313" alt="Bildschirmfoto 2022-05-07 um 10 56 41" src="https://user-images.githubusercontent.com/1853169/167247170-73bf17fb-0c1a-4793-b8f8-f774fba5f5f7.png">

**Comment by jasonvarga** [comment]
Looks like this is a valid problem, but at the moment we don't support having multiple conditions targeting the same field.

**Comment by robdekort** [comment]
I just got bitten by this. Is this only for when you're targeting the same field?

**Comment by jesseleite** [comment]
Yes, you can only set one condition per field. If you need to define multiple conditions on the same field, you can create a custom condition https://statamic.dev/conditional-fields#custom-logic.

We should probably add validation to the conditions builder UX to prevent users from trying this. We could also possibly look into adding an `&&` operator, so you could do things like: `some_field: 'not bar && not foo'`.

**Comment by robdekort** [comment]
Ah yes. Any of those would be nice. The UI suggests it’s supported indeed. I could work around be reversing the logic in this case 👍.
