### ISSUE TITLE
Revision History on Collections shows No Revision History when there should be

### ISSUE THREAD

**Issue by seventyoneindustries** [statamic/cms#6009]
### Bug description

New CMS build, added pro license, enabled revisions. I've made several revisions to various collections and no matter how many or how I do them (publish, create a revision, etc.), the Revision History popover shows no revision history. No errors and nothing appears in the logs. I can see the revisions files being written to the filesystem. I tried both the default revisions storage location and the custom one in the content directory with the same results.  

### How to reproduce

1. Enable revisions on collections. 
2. Set up collections to allow revisions. 
3. Make edits, save, publish and/or create a revision. 
4. Click on "View History" and the popover displays "No revisions."

### Versions

3.3.10

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by staudenmeir** [comment]
#5968 fixed this and will be in the next release.

**Comment by duncanmcclean** [comment]
Well noticed - I'll close this. Watch out for the next release!
