### ISSUE TITLE
Upgrading statamic from 3.2.x to 3.3.x issues with control panel

### ISSUE THREAD

**Issue by samdgea** [statamic/cms#6011]
### Bug description

Hi I'm upgrading statmic version by documentation but when i open my control panel this error shown 

`count(): Argument #1 ($value) must be of type Countable|array, null given`

### How to reproduce

Change the composer.json as per upgrade requirement
Run composer upgrade
Open control panel

### Logs

```shell
https://flareapp.io/share/w5BKQAXm#F66
```

### Versions

Statamic 3.3.10
Laravel 8.83.11
PHP 8.1.4
aerni/livewire-forms 2.0.0
aryehraber/statamic-impersonator 2.4.1
austenc/socialize 1.0.0
edalzell/forma 1.1
jonassiewertsen/statamic-livewire 2.9.0
kind-work/two-fa 1.5.1
parfaitementweb/statamic-country-fieldtype 1.0.0
simonhamp/gitamic 1.8.4

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
Try running `php artisan view:clear`

**Comment by samdgea** [comment]
![A0196299-3712-41BC-A82D-D990BC2B3AB0](https://user-images.githubusercontent.com/43635222/167242879-1c39b143-f3c0-4c3a-82d1-1db2e12e0a2f.png)

i did, but still same

**Comment by jasonvarga** [comment]
Can you provide your `app/Http/Kernel.php` file?

I wonder if you're missing this middleware for some reason: https://github.com/statamic/statamic/blob/1733fea5ff4855d72ca2a163d155f9a23d6f833a/app/Http/Kernel.php#L37

**Comment by samdgea** [comment]
I thinks it's already same with the current Kernel.php
`<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \App\Http\Middleware\TrustProxies::class,
        \Fruitcake\Cors\HandleCors::class,
        \App\Http\Middleware\PreventRequestsDuringMaintenance::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \Litespeed\LSCache\LSCacheMiddleware::class,
        \Litespeed\LSCache\LSTagsMiddleware::class,
        \Bepsvpt\SecureHeaders\SecureHeadersMiddleware::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \Litespeed\LSCache\LSCacheMiddleware::class,
            \Litespeed\LSCache\LSTagsMiddleware::class
        ],

        'api' => [
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
        'statamic.cp' => [
            \Litespeed\LSCache\LSCacheMiddleware::class,
            \Litespeed\LSCache\LSTagsMiddleware::class
        ], 
        'statamic.web' => [
            \Litespeed\LSCache\LSCacheMiddleware::class,
            \Litespeed\LSCache\LSTagsMiddleware::class
        ]
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'cache.headers' => \Illuminate\Http\Middleware\SetCacheHeaders::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'password.confirm' => \Illuminate\Auth\Middleware\RequirePassword::class,
        'signed' => \Illuminate\Routing\Middleware\ValidateSignature::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,
        'lscache' => \Litespeed\LSCache\LSCacheMiddleware::class,
        'lstags' => \Litespeed\LSCache\LSTagsMiddleware::class,
    ];
}`

**Comment by samdgea** [comment]
Temporary Fixed by remove Litespeed LSCache Middleware, until i found out how to fix it
