### ISSUE TITLE
Images::public on image path in antler template

### ISSUE THREAD

**Issue by chiptu** [statamic/cms#6012]
Hey everyone,

When i try to display my image inside my antler i get images::public/example.jpeg .

In my collection i have only one image uploaded, i have a public asset container.

The article collection data is found in my template and when i dump my image_de_presentation data it seems correct.
![Capture d’écran 2022-05-05 à 23 26 39](https://user-images.githubusercontent.com/35498845/167028616-156885f6-0071-431b-a52e-37531b7c7599.png)
![Capture d’écran 2022-05-05 à 23 26 23](https://user-images.githubusercontent.com/35498845/167028624-267ae43d-a407-4592-ae40-3552fe2562d1.png)
![Capture d’écran 2022-05-05 à 23 29 20](https://user-images.githubusercontent.com/35498845/167028720-9be682a3-262d-4f8c-a54a-aed1c961b067.png)

What am i missing out ?

_Originally posted by @chiptu in https://github.com/statamic/cms/discussions/6004_

**Comment by chiptu** [comment]
Here is one article collection markdown 

---
id: ccd025f2-835c-46bc-9beb-88ef59ce9543
blueprint: article
title: '🤔 QrCodes Quésaco ?'
image_de_presentation:
  - public/exemple.jpg
lien_linkedin: 'https://www.linkedin.com'
temps_lecture: 2
resume: |-
  On en voit partout depuis le COVID-19 mais au juste d'où viennent ces carrés étranges ? <br>
  🕵️  Espionnage étatique ? 👽  Alien ? ou pire encore conspiration de geeks 🤓 ?<br>
  Pourquoi on en voit partout alors qu'il y a 2 ans on en voyait aucun  ? <br>
  On va essayer de clarifier tout ça !
updated_by: 1
updated_at: 1651784746
---
Test contenu



I verified i have image magick and gd library on my macos , i m using statamic with a local laravel 9 installation and php 8.1

**Comment by jasonvarga** [comment]
When an asset container's disk doesn't have a url defined, you will only get the ids.

https://statamic.dev/assets#private-containers

Add a `url` to the filesystem disk config, clear your cache, and it should work.

**Comment by chiptu** [comment]
Thanks for your quick response, i think in someway i broke something in the configuration .

I set an url for my local disk, i verified my images yaml container which is well linked to the local disk, my app url .env is well known but statamic add a public string in the url .

In someway i broke the statamic image viewer also, maybe i m going to close this issue and go for a fresh start unless you have any idea ?
![Capture d’écran 2022-05-07 à 11 25 14](https://user-images.githubusercontent.com/35498845/167248154-1b09a6e2-4cfa-4bae-b3b4-a70b180dd73c.png)
![Capture d’écran 2022-05-07 à 11 18 45](https://user-images.githubusercontent.com/35498845/167248155-d6722f16-37e8-413c-acca-0ce4509eaca1.png)
![Capture d’écran 2022-05-07 à 11 19 03](https://user-images.githubusercontent.com/35498845/167248157-f02e35a8-9413-47ce-98a3-37d0d9d1a21d.png)
![Capture d’écran 2022-05-07 à 11 19 14](https://user-images.githubusercontent.com/35498845/167248158-66ad2636-8c3a-46b8-84ce-030adf39c4c9.png)
![Capture d’écran 2022-05-07 à 11 19 27](https://user-images.githubusercontent.com/35498845/167248159-ba81d806-f520-42f7-8f06-043caa238e6d.png)

**Comment by jasonvarga** [comment]
Okay so the `local` disk you've used is not publicly accessible. The root of the disk needs to be public.

Maybe should create a separate disk for your asset container, or use the `public` disk instead:

https://github.com/statamic/statamic/blob/1733fea5ff4855d72ca2a163d155f9a23d6f833a/config/filesystems.php#L38-L43

Then the URLs will be blog.test/storage/something.jpg

You'll need to adjust any paths you've saved inside entries though since they will need to be relative from the disk root. e.g. 

```yml
image_de_presentation:
  - public/exemple.jpg
```

becomes

```yml
image_de_presentation:
  - exemple.jpg
```

**Comment by chiptu** [comment]
Nice thanks a lot !
