### ISSUE TITLE
Keyboard shortcuts for Markdown fieldtype only works on MacOS

### ISSUE THREAD

**Issue by adevade** [statamic/cms#6024]
### Bug description

Making text **bold**, _italic_ or [inserting a link](https://google.com) via keyboard shortcuts only works on MacOS.

Related JS code: [/resources/js/components/fieldtypes/MarkdownFieldtype.vue](https://github.com/statamic/cms/blob/748d52be072911df450feefe51aed539d2ba08aa/resources/js/components/fieldtypes/MarkdownFieldtype.vue#L433-L454)

### How to reproduce

On a Windows or Linux machine, create a page with a Markdown field and try to use the shortcuts.

### Versions

Statamic 3.3.10 Solo
Laravel 9.11.0
PHP 8.0.8
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Are you using the windows key or control? I believe it should be the windows key.

**Comment by adevade** [comment]
Windows key is rarely used by applications in my experience, because most letters are already bound to OS features.
Like `Win + B` selects a button in the taskbar (weird shortcut), `Win + I` opens Settings, and `Win + K` opens a dialog for connecting wireless displays.
And the Markdown field does not take precedence.

**Any way to check for OS and bind to `CTRL` if not MacOS?**
I have not tried with the Meta key on Linux, but can that try later tonight. Does not work with `CTRL` though.

Most often CTRL is used in Windows as Command is used on Mac, I believe.
Like GitHubs Markdown editor I'm writing this in: `CTRL + B` for **bold**, `CTRL + I` for _italics_ etc.

**Comment by adevade** [comment]
Upon closer inspection, it looks as if it's _trying_ to boldify and italicify the text for a fraction of a second.
In the clip below, I press `CTRL + B` four times and then `CTRL + I` four times.

https://user-images.githubusercontent.com/1066486/167837185-90052928-5a8d-47e5-9c21-81ed69360267.mp4

**Comment by jackmcdade** [comment]
I don't think this is an issue at this point with some of the changes we've made there. Feel free to reopen if i'm mistaken.
