### ISSUE TITLE
Bug: Cannot enable save_html for existing Bard content

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#6045]
### Bug description

It used to be easy to enable/disable save_html for Bard fields. But now it seems that an error is thrown when there is Bard format content and the field is expecting an html string.

https://flareapp.io/share/17Wb6ejP#F92

### How to reproduce

1. Create a Bard with with no sets with save_html set to false
2. Add content and Save
3. Edit bard field with save_html set to true
4. See "content must be string" error

### Versions

Statamic 3.3.11 Solo
Laravel 9.11.0
PHP 8.0.13
mattrothenberg/statamic-mapbox-address 0.7.2
rias/statamic-color-swatches 2.0.5
spatie/statamic-responsive-images 2.11.2
statamic/seo-pro 3.1.0

### Installation

Starter Kit using via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
If you re-save the entries, then it should work on the front-end again.

**Comment by mikemartin** [comment]
Thanks @jasonvarga but the error throws on the entry Edit page, so you can't re-save the entry.

**Comment by jasonvarga** [comment]
Ah yeah okay my bad. 👍  Looks like this shouldn't normally happen, but it's SEO Pro doing it.

**Comment by mikemartin** [comment]
Ahhhh of course. 👍
