### ISSUE TITLE
Toast notifications sent from utility controllers dont display

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#6051]
### Bug description

If you send a toast notification from a utility controller and then redirect (eg. back to the previous page) the notification does not display.

### How to reproduce

Create a utility with its own controller and try to send a toast notification from a method that redirects. eg:

```php
Utility::make('example')
    ->action([ExampleController::class, 'index'])
    ->routes(function ($router) {
        $router->get('/update', [ExampleController::class, 'update'])->name('update');
    })
    ->register();
```

```php
class ExampleController extends CpController
{
    public function index(Request $request)
    {
        // ...
    }

    public function update(Request $request)
    {
        // do thing...

        Toast::success('OK');

        return redirect()->back();
    }
}
```

### Versions

Statamic 3.3.11 Solo
Laravel 9.12.2
PHP 8.0.15

### Installation

Starter Kit using via CLI

**Comment by jasonvarga** [comment]
In the case of a redirect, you should do `return redirect()->back()->with('success', 'OK');`

I'll update the docs.

**Comment by jasonvarga** [comment]
Actually that's wrong. Doing `Toast::success('OK')` should work fine.

I think it's not working because your submission route is a GET request. If you change it to POST it should work.

```php
->routes(function ($router) {
   $router->post('/update', [ExampleController::class, 'update'])->name('update');
})
```

**Comment by jacksleight** [comment]
Turns out my method was accidentally resetting the session data! I think it'd probably be fine even with a GET request.
