### ISSUE TITLE
Nested `{{ children }}` tag broken in new parser

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#6053]
### Bug description

I have a nav that has nested children.

When doing this:

<img width="617" alt="CleanShot 2022-05-17 at 14 56 35@2x" src="https://user-images.githubusercontent.com/6069653/168916720-90a69f3f-0d9e-46b0-aab0-1ccbe5ca5fbd.png">

It broke the site. The workout was to put the nest call in a partial

### How to reproduce

1. create nav w/ nested children
2. in a single partial loop through both children.

### Versions

```
Statamic 3.3.11 Pro
Laravel 9.13.0
PHP 8.1.6
aryehraber/statamic-captcha 1.8.0
aryehraber/statamic-uuid 2.1.0
doublethreedigital/duplicator 2.2.0
doublethreedigital/runway 2.3.5
edalzell/forma 1.1
edalzell/private-eye dev-main
jacksleight/statamic-bard-mutator 1.1.1
jacksleight/statamic-bard-texstyle 1.0.2
jonassiewertsen/statamic-livewire 2.9.0
statamic/seo-pro 3.1.0
transformstudios/events 4.0
transformstudios/front 1.10
transformstudios/gated dev-main
transformstudios/magic-link dev-main
transformstudios/memorial dev-feature/3.3
transformstudios/review 3.3
transformstudios/simple dev-feature/3.3
transformstudios/takeover-redirects dev-main
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by edalzell** [comment]
Note I haven't tested this PR to see if it's the same issue: https://github.com/statamic/cms/pull/5902

**Comment by jasonvarga** [comment]
What's broken about it? Got an error?

I tried nesting a `children` pair inside a `children` pair and it worked fine. We'll need to see more context.

Also try to wrap it in an `{{ if children }} ... {{ /if }}` block.

**Comment by edalzell** [comment]
Bad bug report, sorry!

Don't have time to make a repro site. I worked around it.

Closing until I run into it again and have time to make a proper bug report.
