### ISSUE TITLE
Field Data gets deleted on entry save when not visible

### ISSUE THREAD

**Issue by dryven-lukas** [statamic/cms#6060]
### Bug description

When an entry is saved and a field of the entry isn't visible, it's value is reset to null or the equivalent for that fieldtype. This happens despite the fact, that if you manually toggle the "display:none" stlying property in the developer tools, you can see, that the previously saved data is actually there.

On a normal website I imagine that not really beeing a problem, however when working with custom role-based visibility of fields, and a user with a certain role, that shouldn't be able to access all fields of that blueprint, saves an entry with hidden fields, their values are reset.

### How to reproduce

Easiest way to reproduce:
- Add a toggle to a fieldset
- Add a textfield to the same fieldset, with the visibility getting controlled by the toggle
- Now toggle so that you can save some text in the textfield and save the entry
- Now toggle so that the textfield isn't visible anymore and save the entry again
- If you now reload the page and toggle again so that the textfield is visible again the text saved there before is gone

### Versions

Statamic 3.3.7 Pro
Laravel 8.83.8
PHP 8.1.3
aryehraber/statamic-logbook 2.0.2
ddm-studio/cookie-byte 1.0.14
doublethreedigital/duplicator 2.2.0
spatie/statamic-responsive-images 2.11.2
webographen/statamic-admin-log 1.0.6

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jackmcdade** [comment]
This is actually working as intended. Field Conditions control not only visibility, but also whether data is stored or not. More in that here: https://statamic.dev/conditional-fields#data-flow

For those times when you want to _only_ affect visibility to hide fields, you can use the Revealer fieldtype, which is getting a toggle mode so it works basically how you're using it here. https://github.com/statamic/cms/pull/6052
