### ISSUE TITLE
Issues when generating slug when using title_format

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/cms#6071]
### Bug description

When using title_format to generate the title from two fields ( {last_name}-{first_name} ), saving new records fails when trying to use an auto-generated slug. I get the blue progress bar across the top for 1-2 minutes, but then errors out (console error attached). If I remove the slug field and let the collection use the ID instead, it works fine.

I've done this on two sites with the same issue, although on the first site, it was early enough in the build that I just created a new Statamic site and set it up again and that site now works as expected.

<img width="289" alt="Screen Shot 2022-05-20 at 11 20 31 AM" src="https://user-images.githubusercontent.com/50339975/169580238-53994aca-c881-4a0b-b216-a0f228f1a3c1.png">

### How to reproduce

Created a "personnel" collection, added **first_name** and **last_name** fields to blueprint, then set the collection to use title_format = {last_name}-{first_name}. Attempting to save a new record errors out, but turning off "require slugs" in collection makes it work properly, but saves the filename as id.

Even with "require_slugs" turned off, having a slug field in the blueprint. Have tried deleting/re-creating the collection/blueprint/fields, to no effect.

### Versions

Statamic 3.3.12, 3.3.10
Laravel 9.13.0
PHP 8.0, 8.1

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by ryanmitchell** [comment]
Are you able to provide a basic repository that replicates this issue? I just tried to set up a new collection based on your steps and titles and slugs worked fine for me.

**Comment by JohnathonKoster** [comment]
This one seems to related to (or the same as) #5757

**Comment by stefankempf** [comment]
> This one seems to related to (or the same as) #5757
Yes that seems pretty much the same issue.

>  that I just created a new Statamic site and set it up again and that site now works as expected
@theblacksheepltd did I understood you correct that you simply setup a new statamic site with the same custom dual title config and that site works fine even though its using the same slug auto generation?

**Comment by binoclard** [comment]
I am confronted to this very annoying problem too. I had opened a Discussion, as I was not so sure if it was a bug or just a project problem.
https://github.com/statamic/cms/discussions/6785

I am super interested in any workable solution, as I am working on a projet supposed to go liver very soon, and that relies completely on auto-generated titles.

**Comment by binoclard** [comment]
So, FWIW, per my observations:
slug + title_format, without route: ✅
slug + route, with "normal" user generated title: ✅
slug + title_format + route: ❌

**Comment by jasonvarga** [comment]
Closing in favor of #5757
