### ISSUE TITLE
Static Caching Invalidation: rules=>all no effect

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6072]
### Bug description

First time experimenting with this feature but it doesn't seem to be having an effect.

I am using half caching, with the default sync queue driver, and I'm trying to invalidate all content after every save in the control panel with:
```
'invalidation' => [
        'class' => null,
        'rules' => [
            'rules' => 'all'
        ],
],
```

I have edited the title of an entry in my 'Posts' collection, which appears on my home page. I would assume that this should flush the cache for the home page and the new entry title would show, but this is not happening.

Am I missing something?

### How to reproduce

Use all rules config on static caching invalidation. 

### Versions

Statamic 3.3.12 Pro
Laravel 9.13.0
PHP 8.1.1
spatie/statamic-responsive-images 2.11.2
statamic/seo-pro 3.1.0

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
I've ran into this before on a few sites - built an event listener to work around it.

**Comment by stuartcusackie** [comment]
@duncanmcclean Yeah, that should be a good temporary fix. I can work with that for the moment. Any chance of sharing the code snippet?

**Comment by duncanmcclean** [comment]
Sure, here's a Gist of what we're using on a site at the moment: https://gist.github.com/duncanmcclean/219b81810ce574543fd057d66654d028

It'll clear the entry's own page, it's parent (if it's a page), as well as any additional rules which we have setup.

**Comment by stuartcusackie** [comment]
deadly! Thank you sir.

**Comment by jasonvarga** [comment]
You have a double `rules` in your config.

Change this:

```php
'invalidation' => [
    'class' => null,
    'rules' => [
        'rules' => 'all'
    ],
],
```

to this:

```php
'invalidation' => [
    'rules' => 'all',
]
```

As per the docs. https://statamic.dev/static-caching#when-saving

**Comment by stuartcusackie** [comment]
Good spot. Now I feel dumb. 😔
