### ISSUE TITLE
Can't have User with term that they updated

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#6074]
### Bug description

If you have a user blueprint with a term field, and a user makes a term AND assigns that to their own user, the CP goes blank with some errors:

<img width="431" alt="CleanShot 2022-05-22 at 16 49 52@2x" src="https://user-images.githubusercontent.com/6069653/169721830-a7122482-2926-4172-aa81-542b7af7b963.png">

### How to reproduce

1. Statamic new site, create a user
2. Create a taxonomy `Foo`
3. Make a term `bar`
4. Add a taxonomy term field (max 1) to the user blueprint.
5. Add that term to that user's data.
6. Visit the control panel

### Versions

```
Statamic 3.3.12 Pro
Laravel 9.13.0
PHP 8.1.6
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Sample site that shows the error.

Login with `Erin@silentz.co` pwd 'password'

[user-term.zip](https://github.com/statamic/cms/files/8750499/user-term.zip)

**Comment by duncanmcclean** [comment]
I have ran into a similar issue with the Entries fieldtype, in #6074.

**Comment by ryanmitchell** [comment]
Actually looping back around to this, I think it probably is the right approach as we want to avoid recursion into the augmentation which is causing the json encoding to fail. I'll open a PR and see what Jason thinks.
