### ISSUE TITLE
NavSaved Event only fires when editing nav settings

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6090]
### Bug description

I'm not sure if this is a bug but I would expect the NavSaved Event to fire when re-ordering a nav or editing any of the links / labels. The event only seems to fire when you edit the nav settings.

If this is expected behaviour then can we get a new Event to catch changes to the nav structure?

Thanks.

### How to reproduce

Add a listener to your EventServiceProvider:

```
use Statamic\Events\NavSaved;
use Illuminate\Support\Facades\Log;

// boot()
Event::listen(function (NavSaved $event) {
    Log::info('NavSaved. Handle: ' . $event->nav->handle);
 });
```

Then re-order, rename or change links in your nav. No log will be recorded.
Making changes in the 'Edit Navigation' screen does fire the event.

### Versions

Statamic 3.3.12 Pro
Laravel 9.14.0
PHP 8.1.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
What about the [`NavTreeSaved`](https://github.com/statamic/cms/blob/3.3/src/Events/NavTreeSaved.php) event - does it do what you want?

**Comment by jasonvarga** [comment]
NavTreeSaved is what you're looking for.
