### ISSUE TITLE
If Today is <= to date value doesn't work when dates are equal

### ISSUE THREAD

**Issue by jhorii** [statamic/cms#6107]
### Bug description

I am checking to ensure that today's date is less than or equal to the end date in a date field.  It works until the dates are the same, then it doesn't evaluate to true.

`{{ if today <= end_date }}
    {{ exhibit_title }}
{{ /if }}
`
I've output both values to ensure they are the same, and they are.  I've also updated to the latest version of Statamic (3.3.12) and I'm using the new parser.

### How to reproduce

- Create a date field and set the value to todays date
- Use the above if statement in your antlers template and output something if it evaluates to true

### Versions

Statamic 3.3.12 Pro
Laravel 8.83.14
PHP 7.4.29
statamic/seo-pro 3.1.0

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Running on a windows server with IIS.

**Comment by JohnathonKoster** [comment]
Do you need the time as part of the comparison? If not, this will do the check without checking the time (using `copy` to not update the existing Carbon instances):

```
{{ if today:copy():startOfDay() <= end_date:copy():startOfDay() }}
```

**Comment by jhorii** [comment]
I don't need any time included on my comparison.

This looks like it has resolved my issue (thank you).  The question is though, is it still a bug?  Shouldn't "today" be a date and not a date/time?

**Comment by JohnathonKoster** [comment]
> 



> I don't need any time included on my comparison.
> 
> This looks like it has resolved my issue (thank you). The question is though, is it still a bug? Shouldn't "today" be a date and not a date/time?

That's a great question! I will let the Core team weigh in on that one :)

**Comment by edalzell** [comment]
Carbon instances always have a time

**Comment by jhorii** [comment]
Ok thanks.  I think this would be helpful to see in the Docs.

**Comment by edalzell** [comment]
> Ok thanks. I think this would be helpful to see in the Docs.

PRs gladly accepted.
