### ISSUE TITLE
Multisite Listings are not sorted by site when in List view

### ISSUE THREAD

**Issue by devingray** [statamic/cms#6117]
### Bug description

Access control panel

### How to reproduce

Enable multisite
Create entries for each site 
Go to Listing

<img width="1321" alt="CleanShot 2022-05-30 at 15 21 10@2x" src="https://user-images.githubusercontent.com/11573528/171001030-4c09f6d3-73f1-43fb-a0d2-657880f21c25.png">

Expected to have a filter by site 

### Versions

Latest

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
They are sorted by title by default. Feel free to just click the "Site" column header, and it will sort by site.

**Comment by devingray** [comment]
@jasonvarga unfortunately not, when in tree view it all works as expected but in list view sorting by site still sorts by title
