### ISSUE TITLE
[API] Maximum stack depth exceeded

### ISSUE THREAD

**Issue by pitcher-maarten** [statamic/cms#6123]
### Bug description

When using the **entries** field inside a replicator the Rest API is crashing: Maximum stack depth exceeded.

![Schermafbeelding 2022-05-31 om 16 37 17](https://user-images.githubusercontent.com/77880620/171200097-6d39cebf-f780-4ba6-98c2-987e14c6c59a.png)

### How to reproduce

1. Our homepage does have a replicator with multiple blocks.
2. Inside the Categories block you can setup multiple categories by also a replicator, so basically you have: replicator.replicator.entries (with limit 1)
3. When linking an entry of the same collection the rest API gets broken.

### Versions

3.3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
You are likely linking to an entry which links to the original one, which links to the other, which links to the original, and repeat forever.

**Comment by pitcher-maarten** [comment]
Well @jasonvarga still having the issue and kind of have found what's causing it.

My pages collection has a home page as root page. If i'm getting all entries, again I'm getting maximum stack dept exceeded
```
http://cms.adveedierenartsen.test/api/collections/pages/entries?limit=9998
```

After playing with the fields filter: `http://cms.adveedierenartsen.test/api/collections/pages/entries?limit=9998&fields=id,blocks` it's solved.

When adding `parent` to the fields: `http://cms.adveedierenartsen.test/api/collections/pages/entries?limit=9998&fields=id,blocks,parent` it's broken.

So why it's including all parent entries (full pages) inside the entry in the API response, I don't see that purpose?
