### ISSUE TITLE
Using a glide(possible) breaks the variable inside the loop

### ISSUE THREAD

**Issue by lotarbo** [statamic/cms#6137]
### Bug description

I add replicator field(blocks) with two sets(text, image)
Add some sets on my page.
I have this code 
```blade
    {{ counter = 1 }}
    {{ blocks }}
        {{ counter += 1 }}
        {{ partial src="blocks/{type}" }}
    {{ /blocks }}
```
inside `resources/views/blocks/image.antlers.html`
```html
<p>Counter: {{ counter }} </p>
<picture>
    <source srcset="{{ glide:image format='webp' }}">
     <img src="{{ glide:image}}" alt="Alt">
</picture>
<hr>
```

inside `resources/views/blocks/text.antlers.html`
```html
<p>Counter: {{ counter }} </p>
<p>{{ text }}</p>
<hr>
```

and what i see:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/1766890/171469588-ee0428f7-7196-454b-9c87-c840b7b3770f.png">

but i expected 2,3,4,5,6

### How to reproduce

using my demo repo for this https://github.com/lotarbo/statamic-demo

### Versions

Statamic 3.3.12 Solo
Laravel 9.15.0
PHP 8.1.6
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by JohnathonKoster** [comment]
Note to self: caused by this: https://github.com/statamic/cms/blob/3.3/src/View/Antlers/Language/Runtime/NodeProcessor.php#L1363-L1366

And can be caused by any tag call inside the nested partial (not specific to assets/glide/etc.)
