### ISSUE TITLE
Dropdown for conditional fields in blueprint only show fields in current section

### ISSUE THREAD

**Issue by MariusSpring** [statamic/cms#6151]
### Bug description

When choosing the conditions for a field to show, the "field" dropdown only includes fields from current section. For example, if I want a field in the sidebar to only appear if a field in the main section is set to a certain value, I cannot do this as fields from the main section doesn't appear.

### How to reproduce

1. Create collection
2. Edit blueprint
3. Create a new field in the "main" section
4. Create a new field in the "sidebar" section and try to make it conditional based on a field from the "main section"
5. You will see fields from the main section not showing up in the dropdown

### Versions

3.3.13 (latest as of 3th of June 2022)

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
You're free to type whatever you want in there, though.

**Comment by MariusSpring** [comment]
@jasonvarga Oh! Didn't realize this. But they still should appear in the dropdown?
