### ISSUE TITLE
Bard: merging cells leads to unexpected formatting of combined content

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#616]
Since prosemirror-table and thus tiptap use `<p>` tags to wrap cell content, the content from two cells flows to a column of two paragraphs when you merge them. Small thing and might even be expected, but maybe it would be more intuitive and user-friendly to merge the `<p>`s in simple cases, like one `<p>` in each cell?

**Comment by jasonvarga** [comment]
To confirm, when merging two cells, you get two paragraphs. Feels like correct behavior to me.

This is how tiptap works. https://tiptap.scrumpy.io/tables

If you'd like this behavior changed, it would be an issue to bring up to them. https://github.com/scrumpy/tiptap/
