### ISSUE TITLE
Slow CP page loading

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#6160]
### Bug description

I'm viewing collection pages in the `CP` and the pages are loading quite slow. I'm also using `vue.js` but i'm getting these console errors when i'm viewing the content pages in the `CP` which is probably why the pages are loading slow. 

I'm not getting these errors when viewing the actual pages and I don't get these errors when viewing other collections in the CP

![Screen Shot 2022-06-06 at 2 14 32 pm](https://user-images.githubusercontent.com/7971800/172096603-c41da613-52f5-430e-81fd-320a584d2464.png)
.

### How to reproduce

Go to controll panel/collections. View the content from one of the child pages. Open the developers tools and it show this error.

### Versions

Statamic 3.3.12 Pro
Laravel 8.83.8
PHP 8.1.6
aerni/font-awesome 1.2.0
joetannenbaum/antlers-stack-tags 0.1.0
simonridley/tracking-code-manager dev-master
withcandour/aardvark-seo 2.0.25

### Installation

Fresh statamic/statamic site via CLI

**Comment by edalzell** [comment]
IF you remove those addons do you continue to get those errors?

**Comment by ottz0** [comment]
I've removed all plugins and still get the error. However my addons tell me I have 5 installed but I only have 4 installed, so probably this error is run as it's looking for another addon that is not there.

![Screen Shot 2022-06-06 at 2 14 32 pm](https://user-images.githubusercontent.com/7971800/172301478-39a94fb4-d343-42ef-bf83-0d75bcaab294.png)

**Comment by edalzell** [comment]
How did you remove the addons?

**Comment by ottz0** [comment]
I removed them via the uninstall button in the CP and the Tracking code manager `composer remove simonridley/tracking-code-manager --ignore-platform-reqs`

**Comment by mbryne** [comment]
I had the same issue with aerni/font-awesome

It might be worth opening an issue on that repo?

**Comment by ottz0** [comment]
https://github.com/aerni/statamic-font-awesome/issues/10

**Comment by pushpanda** [comment]
i had the same problems as you have. the font-awesome package is slowing the editor down and for the javascript error see #5061 . the solution provided there worked for me

**Comment by jasonvarga** [comment]
Closing this as it appears to be due to the font-awesome addon.
