### ISSUE TITLE
Broadcasting authorization broken

### ISSUE THREAD

**Issue by MariusSpring** [statamic/cms#6167]
### Bug description

After installing a recent version of Statamic, broadcasting authorization has become broken. This might be related to the recent changes in Statamic's RouteServiceProvider. Attempting to POST to /broadcasting/auth results in the error:
`ArgumentCountError: Too few arguments to function Statamic\Providers\RouteServiceProvider::Statamic\Providers\{closure}(), 1 passed and exactly 2 expected in file`

Related: https://github.com/statamic/collaboration/issues/65.

### How to reproduce

1. Install Statamic
2. Setup broadcasting channel requiring authorization
3. Hit /broadcasting/auth to attempt authorization for the channel.
4. See error.

### Versions

Statamic 3.3.13 Pro
Laravel 8.83.15
PHP 8.1.3
doublethreedigital/runway 2.3.6
spatie/statamic-health 1.0.0
statamic/collaboration 0.4.0

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Using latest version as of 7th of June, 2022 of statamic/collaboration package.

**Comment by jasonvarga** [comment]
Good find, sorry about that. We'll get it sorted.
