### ISSUE TITLE
Field 'slug' validation rule error

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6173]
### Bug description

Just added a simple 'slug' validation rule to a text field:
![image](https://user-images.githubusercontent.com/20210934/172604284-8d533080-b46e-4382-b178-127e50731f12.png)

Which produces this error when saving:
![image](https://user-images.githubusercontent.com/20210934/172604386-4e9f63dd-43e6-4e65-b29c-6b9575ab8014.png)

Thanks.

### How to reproduce

Add 'slug' validation rule to a text field and try to save content.

### Versions

Statamic 3.3.12 Pro
Laravel 9.14.1
PHP 8.1.1
spatie/statamic-responsive-images 2.12.3
stillat/relationships 1.0.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
That's because `slug` isn't a valid validation rule (at least, as far as I know). What are you intending to validate?
