### ISSUE TITLE
New mount tag not working in Antlers

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#6180]
### Bug description

The new `mount` tag by @jacksleight is currently only working Blade using `Statamic::tag('mount:blog')`. When you use `{{ mount:blog }}` in Antlers, it returns nothing. Probably because `mount` is also a variable. When I disambiguate the tag with `{{ %mount:blog }}` things start to work.

The tag probably needs to be renamed to `mount_url` or something but that would technically be a breaking change (to something that doesn't work, only in Blade). Or an exception to the parser? cc: @JohnathonKoster

### How to reproduce

1. Install the latest version (v3.3.14)
2. Add a mounted collection
3. Use `{{ mount:collection_handle }}` in an Antlers template -> _returns nothing_
4. Use `{{ mount handle="collection_handle" }}` in an Antlers template -> _returns error_
5. Use `{{ %mount:collection_handle }}` -> _be happy_

### Versions

Statamic 3.3.14 Pro
Laravel 8.83.16
PHP 8.1.3

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Oh derp. I know it'd technically be a breaking change to rename it now, but it's only one version and been in the wild for a single day, I think we can make an exception. If you don't tell the semantic versioning overlords.

**Comment by robdekort** [comment]
🤣 I'm not gonna tell anyone!
