### ISSUE TITLE
RUNTIME: Can't use site variables with multi-dimensional arrays

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#6183]
### Bug description

I do use YAML front matter in combination with site variables (``{{ site:var }}``). While this works with simple arrays, it stops working when using multidimensional arrays. See example down below.

### How to reproduce

```html
---
highlighting:
  green:
    general: 'bg-logistic-500 text-white'
    logistic: 'bg-logistic-500 text-white'
    play: 'bg-play-500 text-white'
  gray:
    general: 'bg-slate-100'
    logistic: 'bg-slate-100'
    play: 'bg-slate-100'
---
<div class="{{ view:highlighting['green']['logistic'] }}"></div> <!-- this works -->
<div class="{{ view:highlighting[{highlight_text}]['logistic'] }}"></div>  <!-- this works -->
<div class="{{ view:highlighting[{highlight_text}][{site:handle}] }}"></div>  <!-- this doesn't (I'd like to use that one) -->

<!-- I also tried these -->
{{ var = 'logistic' }}
<div class="{{ view:highlighting[highlight_text][{var}] }}"></div>  <!-- this works -->

{{ var = site:handle }}
<div class="{{ view:highlighting[highlight_text][{var}] }}"></div>  <!-- this doesn't -->
```

### Versions

Statamic 3.3.15 Pro
Laravel 9.17.0
PHP 8.0.13
spatie/statamic-responsive-images 2.12.3

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by JohnathonKoster** [comment]
If you `dump` the value of `site:handle` what value is displayed for you?

I will think on it, but may need additional details since I am not able to replicate this with any of the examples provided.

**Comment by AndreasSchantl** [comment]
Left the issue alone yesterday and just came back. Boom, working. Late night typos + Created Issues are for sure something to be ashamed of.
