### ISSUE TITLE
Bard: Empty <p> between two sets

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#619]
Since Bard doesn't allow removing the empty paragraph between two sets, it's included in the saved data. Trying to remove it using Backspace, Bard thinks you want to remove the set before the empty paragraph and asks for confirmation to do that, using Delete it does the same thinking you want to delete the set following the empty paragraph.

The empty paragraph is created when inserting a set immediately below an existing set, by the way.

**Comment by jasonvarga** [comment]
Fixed in cabb33b

**Comment by sauerbraten** [comment]
The new behavior regarding deleting sets works great! However, there are still empty paragraphs between two sets, since now, the set is inserted below the empty paragraph you use to see the + button.

You should be able to reproduce this and see what I mean with these steps:

1. start with an empty Bard field
2. use the + button to insert a set
3. there will be an empty paragraph above the set as well as below it

**Comment by sauerbraten** [comment]
By the way, inserting an empty set below or above the set is what we expect to happen when the set is the first or last block in the Bard field, to enable users to add stuff above/below. But when there are other paragraphs around it, we would like it to have no gaps after inserting a set.

Instead of leaving an empty paragraph between two sets, maybe you could render the same small + button that's shown between replicator sets? Because of course users need a way to insert a set between two sets.

**Comment by tobiaseichert** [comment]
My observation is that you'll always end up with additional paragraph tags right in front of the set when adding it, regardless of the existing type of content. Is there a way to filter those tags?

**Comment by Sceko** [comment]
fixed on last version
