### ISSUE TITLE
Opt-out of new 'Control panel forms now only submit visible fields' functionality / revealer field data loss

### ISSUE THREAD

**Issue by mbryne** [statamic/cms#6190]
### Bug description

I just wanted to submit a big report regarding the following change: 

> [Control panel forms now only submit visible fields](https://statamic.dev/upgrade-guide/3-2-to-3-3#control-panel-forms-now-only-submit-visible-fields)
Control Panel forms now only submit visible fields (as originally intended) which fixes sometimes / required_if / etc. validation rules, among other things.
>
> This could potentially be a breaking change if you were using field conditions purely for cosmetic showing/hiding of form fields, in which case we might recommend using the [revealer fieldtype](https://statamic.dev/fieldtypes/revealer).

I have read and completely understand the justification behind it here and elsewhere: https://github.com/statamic/cms/issues/6018 https://github.com/statamic/cms/issues/6060 https://github.com/statamic/cms/issues/5873 

I understand the examples behind conditional fields but I don't think this should be applied to the revealer field, as per the Revealer field docs:

>If you have some fields that you wish to hide until the user is ready to reveal them, throw a Revealer field in there and those fields may be shown once the button is clicked.
> 
> This fieldtype is intended to be used with our conditional field rules, but unlike regular conditional fields, **it will not disrupt data flow on fields hidden by a Revealer.**

Is this expected behaviour for revealers? If so, can a feature flag or field attribute be added to ensure that this behaviour can be opted out of for revealers? 

### How to reproduce

- We have a 'more' revealer added to every content 'block' / 'element' / 'section' etc
- This more revealer is styled using custom CSS to appear as a slight bar along the left of each element
- This 'more' revealer hides quite a few fields that do not need to be accessed in regular circumstances
- The new 'toggle' mode added to the revealer won't help here as it will need to be toggled everywhere, leaving all fields visible

**Example Screenshots:**

* [More Toggle Example](https://imgur.com/N9ep2Wt)
* [Revealers Collapsed, Nice](https://imgur.com/Ch5sHID)
* [Revealers Exapnded, Not So Nice](https://imgur.com/443odYd)

### Versions

Statamic 3.3.15
Laravel 9.16.0
PHP 8.0.17
doublethreedigital/duplicator 2.2.0
edalzell/blade-directives 3.7
optimoapps/statamic-bard-text-align 1.0.2
withcandour/aardvark-seo 2.0.26
xndbogdan/statamic-bard-text-color 2.2

### Installation

Existing Laravel app

### Antlers Parser

regex (default)

**Comment by mbryne** [comment]
Also roping in this issue: https://github.com/statamic/cms/pull/6052

Toggle mode on the Revealer doesn't resolve this issue for us. 

I still feel like fields hidden behind the revealer shouldn't be stripped from the saved data. At least not without a method for opting out of that behaviour.

**Comment by jasonvarga** [comment]
Fields hidden by a revealer are supposed to be submitted. If they're being lost then that's a bug.

**Comment by mbryne** [comment]
I’ll do up an example repo with the issue

**Comment by mbryne** [comment]
I've narrowed down the issue.  I was overriding the RevealerFieldtype.vue component to achieve a similar behaviour to that new toggle mode.

My code better start doing what I want it to do etc. Homeostasis restored.

Closing the issue.
