### ISSUE TITLE
{{ get_error }} tag outputs error despite being not set

### ISSUE THREAD

**Issue by MariusSpring** [statamic/cms#6196]
### Bug description

The `{{ get_error }}` tag will output the markup inside its scope although a specific error is not set.

For example, the below code will add `is-invalid` class to the input field on form submission despite there being no errors for this field (`{{ message }}` is empty). It will also render the div with "invalid-feedback" class, with no message inside it of course.

```
<label class="form__label visually-hidden">
  First name
</label>
<input
  type="text"
  name="first_name"
  value="{{ old:first_name }}"
  placeholder="First name"
  class="form__control {{ get_error:first_name }} is-invalid {{ /get_error:first_name }}"
>
{{ get_error:first_name }}
  <div class="invalid-feedback">
    {{ message }}
  </div>
{{ /get_error:first_name }}
```

### How to reproduce

1. Create an input field in a form.
2. Use `{{ get_error }}` tag.
3. POST the form to an endpoint with validation, but let validation pass for the specific field.
4. See result.

### Versions

Statamic 3.3.15 Pro
Laravel 8.83.15
PHP 8.1.3
doublethreedigital/runway 2.3.6
spatie/statamic-health 1.0.0
statamic/collaboration 0.4.0

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by MariusSpring** [comment]
@duncanmcclean per the docs (https://statamic.dev/tags/get_errors): 

`get_errors` (plural):

> If there are no errors, the tag will output nothing at all, so you can put your wrapping html around the inner messages tag pair.

This says that you can output any HTML inside the tag without any additional checks as it won't render it as long as there are no errors.

I expect the same to be true for `get_error` (singular).

**Comment by jasonvarga** [comment]
You're right. The issue is that the tag pair will output nothing **if there are no errors at all**.

But for the singular get_error tag, it should output nothing if there isn't an error **for that field**.

Bug!
