### ISSUE TITLE
/collections/foo/entries returns first record correctly, subsequent, not so

### ISSUE THREAD

**Issue by promanapeople** [statamic/cms#6203]
### Bug description

A stable API call broke after upgrading from 3.1 to 3.2.39

The call is to /collections/blog/entries and used to work when the fields included these:

`parent,permalink`

but now only returns the three records in their expected form when I don't request the parent or permalink fields. Weirdly, of the expected records, I always get the first one back. But the 2nd and 3rd objects returned only contain their id - no other data.

This is despite no content changes, just the upgrade. 

To be clear, the issue is that I can get any first record so this is not about a specific first record, but when requesting those two additional fields I never get more than one complete record - just stubs of the 2nd and subsequent records.

Also: even if I only request the permalink (params incl filters shown in "A") I only get one sane record back ("B"), even though they are all published pages

![image](https://user-images.githubusercontent.com/83995152/173463403-ab167548-22b3-41fa-8343-14397f3a0e87.png)

### How to reproduce

Create a collection with a parent and a few children.

Make an API call to request the children, returning the parent and permalink of each.

### Versions

3.2.39

### Installation

Existing Laravel app

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
Interesting. I can't reproduce this. Are you able to provide a GitHub repo with this reproduced?

**Comment by promanapeople** [comment]
Update: 

Downgrading from 3.2.29 to 3.2, still broken.

Down to 3.1, not broken.

* the original upgrade from 3.1 to 3.2.29 included a server upgrade, php 7.4 to php 8. The upgrade and downgrades mentioned are on php 8 and the bug is not apparent on version 3.1 for both php 7 or 8.
*

**Comment by promanapeople** [comment]
> Interesting. I can't reproduce this. Are you able to provide a GitHub repo with this reproduced?

Not right away due to other commitments, but will swing back here in a few days

**Comment by promanapeople** [comment]
Issue was only affecting local. Not a bug
