### ISSUE TITLE
Addon translations are published to wrong directory

### ISSUE THREAD

**Issue by aerni** [statamic/cms#6213]
### Bug description

When publishing an addon's translations, the files are copied into the wrong directory. They are published to `lang/{locale}/` instead of `lang/vendor/{addon}/{locale}/`.

I tracked it down to this line in the `AddonServiceProvider`:
https://github.com/statamic/cms/blob/8a5817e8a9eba3b080fad36579c8a0464a7f37d6/src/Providers/AddonServiceProvider.php#L238

For whatever reason, the `langPath` method doesn't output the correct path. If you use the `lang_path` helper method instead, the path is correct.

**Example output:**

```php
app()->langPath("vendor/{$slug}")
// /Users/michael/Code/rewe-group/resources/lang

lang_path("vendor/{$slug}")
// /Users/michael/Code/rewe-group/resources/lang/vendor/advanced-seo
```

### How to reproduce

1. Create an addon and publish its translation files. 
2. Notice the files ending up in the wrong directory.

### Versions

Statamic 3.3.12 Pro
Laravel 8.83.14
PHP 8.1.6
aerni/advanced-seo 1.1.2
aerni/dynamic-cache 1.1.1
aerni/font-awesome 1.2.0
aerni/social-links 2.3.0
aerni/zipper 1.5.1
aryehraber/statamic-impersonator 2.4.1
jonassiewertsen/statamic-livewire 2.9.0
spatie/statamic-responsive-images 2.12.3
visuellverstehen/statamic-classify 2.4.0

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Good catch. Looks like `app()->langPath()` was updated in Laravel 9 to support accepting a path argument. `lang_path()` already did.
