### ISSUE TITLE
Missing "create form" button in control panel (after creating a form)

### ISSUE THREAD

**Issue by brendanfalkowski** [statamic/cms#6217]
### Bug description

After you've created one form from the control panel, there isn't a "create form" button like in other admin modules. You can only do it from code.

<img width="1155" alt="Screen Shot 2022-06-15 at 10 14 56 AM" src="https://user-images.githubusercontent.com/214924/173886696-d7bace12-8033-48f3-8bab-4b98db97a650.png">

### How to reproduce

1. Create the first form in the CP
2. Follow the wizard
3. Click "forms" in the sidebar

Expecting to see the blue "create form" button.

### Versions

Statamic 3.3.15 Solo
Laravel 9.16.0
PHP 8.1.6
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
That button will only appear if the user has the "Configure forms" permission.

**Comment by brendanfalkowski** [comment]
Ah, got it, thanks!

**Comment by joemaller** [comment]
@jasonvarga FWIW, I'm new to Statamic and just burned a bit of time on this exact issue. Glad there's an easy workaround, but maybe there's some way for new Herd/local users  to avoid this?

**Comment by jasonvarga** [comment]
The new version of the Statamic CLI tool will ask if you want to enable Pro right from the get go.

We don't really want to be upselling you from within the control panel, like dangling a disabled "create form" button with a "you can click this if you upgrade". We'll think on it though!
