### ISSUE TITLE
Unable to register custom Vue components in CP

### ISSUE THREAD

**Issue by DR-DinoMight** [statamic/cms#6223]
### Bug description

Unable to get custom Vue components to render on the CP (currently tried a Publish form and also a custom input
<img width="3352" alt="Screenshot 2022-06-16 at 08 37 35" src="https://user-images.githubusercontent.com/1541665/174089596-bd4bec69-13e1-46c4-90e7-6cb015d1060e.png">

Screenshot shows the component has compiled and has even had stuff triggered to the console through `mounted()` method and also that `props` are being passed  

### How to reproduce

This originally came about in a custom install, I tried registering a new Publish Form, and after following the docs I noticed that component wasn't rendering any markup from the component, however, was still triggering the actual Vue components methods should as `mounted()` as I managed to still get console logs I had printed, and I also noticed in the Vue dev tool extension was showing it as a rendered component too.

After looking into this and comparing it to the docs, I remember I had to put `.vue()`  to prevent the following error 

```bash
ERROR in ./resources/js/components/fieldtypes/ExampleFieldtype.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|     <div class="example-fieldtype-container">
|         <text-input :value="value" @input="update" />

webpack compiled with 1 error
```

As I had deviated from the docs slightly, I've then decided to quickly boot up a new base install of Statamic and try it again exactly as the docs say, upon running `npm run watch` I received the error above, which again was only resolved by adding `.vue`

```js
mix.js('resources/js/cp.js', 'public/vendor/app/js').vue()
   .postCss('resources/css/cp.css', 'public/vendor/app/css', [
    require('postcss-import'),
    require('tailwindcss/nesting'),
    require('tailwindcss'),
])
```
This again allowed everything not to throw an error and to compile, however, no markup was actually being rendered to the browser.

I entirely think this is my fault but not really sure where to go next.

### Versions

```
Statamic 3.3.15 Pro
Laravel 9.12.2
PHP 8.1.5
daynnnnn/statamic-database 1.6.0
```

And `package-lock.json` details

```
"packages": {
        "": {
            "dependencies": {
                "@tailwindcss/forms": "^0.5.2",
                "autoprefixer": "^10.4.7",
                "laravel-mix-purgecss": "^6.0.0",
                "postcss-import": "^14.1.0",
                "postcss-nested": "^5.0.6",
                "postcss-preset-env": "^7.7.1",
                "tailwind": "^4.0.0",
                "vue": "^3.2.37",
                "vue-loader": "^17.0.0"
            },
            "devDependencies": {
                "@tailwindcss/forms": "^0.4.0",
                "alpinejs": "^3.4.2",
                "autoprefixer": "^10.4.2",
                "axios": "^0.25",
                "laravel-mix": "^6.0.6",
                "lodash": "^4.17.19",
                "postcss": "^8.4.6",
                "postcss-import": "^14.0.2",
                "tailwindcss": "^3.0.18",
                "vue-template-compiler": "^2.6.14"
            }
        },
```

### Installation

Existing Laravel app

### Additional details

I had started a conversation about this on Discord - https://discord.com/channels/489818810157891584/986921673980772373 if that's any help.

**Comment by duncanmcclean** [comment]
Can you share the code of your component?

**Comment by DR-DinoMight** [comment]
the original one was 

```vue
<template>
    <h2>Hello World</h2>
</template>

<script>
export default {
    props: ['hello'],
    mounted() {
        console.log('TEST COMPONENT MOUNTED');
        console.log('this.hello', this.hello);
    },
};
</script>
```

but when I did the fresh install it was just the example that's included in the base setup (just with a h2)

```vue

<template>
    <h2>hello world</h2>
    <div>
        <text-input :value="value" @input="update" />
    </div>

</template>

<script>
export default {

    mixins: [Fieldtype],

    data() {
        return {
            //
        };
    }

};
</script>
```

**Comment by duncanmcclean** [comment]
Okay, what does your `resources/js/cp.js` file look like, as well as the view that you're using to show the component?

**Comment by DR-DinoMight** [comment]
Hopefully the screenshot shows all that, but for ease.

`resources/js/cp.js`

```js
import CustomPublishForm from "./components/CustomPublishForm.vue";
import TestComponent from "./components/TestComponent.vue";
import Password from "./components/fieldtypes/Password.vue";

Statamic.booting(() => {
    Statamic.$components.register('custom-publish-form', CustomPublishForm);
    Statamic.$components.register('test-component', TestComponent);
    Statamic.$components.register('password-fieldtype', Password);
});
```
and the view `edit.blade.php`

```php
@extends('statamic::layout')

@section('content')
    <h1>testing</h1>
    <test-component hello="world"></test-component>
    <password-fieldtype></password-fieldtype>
{{--    <custom-publish-form--}}
{{--        title="Edit Product: {{ $product->name }}"--}}
{{--        action="{{ cp_route('products.update', $product) }}"--}}
{{--        method="patch"--}}
{{--        :blueprint='@json($blueprint)'--}}
{{--        :meta='@json($meta)'--}}
{{--        :values='@json($values)'--}}
{{--    ></custom-publish-form>--}}
@endSection
```

I also like to point out I've noticed I uploaded an older screenshot where I was rendering the Components wrong (<test hello="world" />) but even after I corrected it I was still getting issues.

**Comment by ItsRD** [comment]
I came across the same problem creating a field type and I fixed it by using Vue 2 instead of 3.

So I uninstalled vue, template compiler and vue loader

`npm uninstall vue vue-loader vue-template-compiler`

Installed vue 2
`npm install vue@2`

Replace the `vue()` code in webpack.mix.js with `vue({version: 2})`

Should look something like this:
```
mix.js('resources/js/cp.js', 'public/vendor/app/js')
    .vue(({ version: 2 }));
```

Now run `npm run watch`, it will install the correct version of `vue-loader` and `vue-template-compiler` and run watch again.

That should make it work.

**Comment by DR-DinoMight** [comment]
> I came across the same problem creating a field type and I fixed it by using Vue 2 instead of 3 (since Statamic is build on version 2).
> 
> So I uninstalled vue, template compiler and vue loader
> 
> `npm uninstall vue vue-loader vue-template-compiler`
> 
> Installed vue 2 `npm install vue@2`
> 
> Replace the `vue()` code in webpack.mix.js with `vue({version: 2})`
> 
> Should look something like this:
> 
> ```
> mix.js('resources/js/cp.js', 'public/vendor/app/js')
>     .vue(({ version: 2 }));
> ```
> 
> Now run `npm run watch`, it will install the correct version of `vue-loader` and `vue-template-compiler` and run watch again.
> 
> That should make it work.

This fixed it!!!! Thanks, soo much, I'm not sure why I didn't think about rolling back to version 2 of Vue.


Thant being said, I'm not sure if this is still classed as an issue or not, or whether this can now be closed.

**Comment by ryanmitchell** [comment]
I think its accepted that Vue2 is required at this point and there are some reasons for not updating to Vue3 yet. I think the issue could be closed.
