### ISSUE TITLE
Route [statamic.cp.forms.actions.run] not defined.

### ISSUE THREAD

**Issue by freshface** [statamic/cms#6251]
### Bug description

https://flareapp.io/share/omwgLq9m#F73

### How to reproduce

I upgraded from 3.3.13 to 3.3.16 and the form routes throws an error.
I tested this on 3 projects and got 3 times the error.

It is fixed by clearing the routes.

### Versions

Statamic 3.3.16 Pro
Laravel 9.18.0
PHP 8.1.0
aryehraber/statamic-captcha 1.8.0
rias/statamic-address-field 1.0.2

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by joshuablum** [comment]
Hey @freshface,

So running `php artisan route:clear` fixed the issue, right? Not encountering problems anymore?

**Comment by jasonvarga** [comment]
It doesn't, but if you're deciding to cache your routes, you should clear them when updating dependencies.
