### ISSUE TITLE
Safe Truncate with three dots "..." doesn't show dots

### ISSUE THREAD

**Issue by brianshepherd** [statamic/cms#6259]
### Bug description

Added tag: {{ title | safe_truncate:40:...  }}. The three dots don't appear after the truncated text. Replacing with word like "more" works, as does adding a single period. Trying to use special characters (e.g. &#8230; ) causes this page error: _[ANTLR_021]: Unexpected end of modifier value list while parsing modifier._

### How to reproduce

Using antlers runtime parser, add a safe_truncate modifier to a tag using any number and three dots (40:...)

### Versions

Statamic 3.3.16
PHP 8.1

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

Appears to work as expected with regex Antlers parser.

**Comment by JohnathonKoster** [comment]
The syntax you need for the Runtime version is the new method syntax (to let the `.` continue to have meaning when referencing variables/etc):

```antlers
{{ title | safe_truncate(40, '...') }}
```

https://statamic.dev/new-antlers-parser#modifiers

**Comment by brianshepherd** [comment]
Thanks! Got it working now.
