### ISSUE TITLE
Toggle always false

### ISSUE THREAD

**Issue by itsjustk** [statamic/cms#6264]
### Bug description

Hi there, I have a collection with a toggle field, I'm using it to set up a sort of "private post" system, however in antlers, this field always seems to be false, regardless of its toggled status. 

When looking at the entry object with PHP the field will correctly be assigned true/false and the actual .MD file also correctly shows true/false.

Thanks :) 

### How to reproduce

  - Add "toggle" field to collection blueprint. 
  - Create a new entry, with the toggle field clicked to represent "true"
  - add {{ mytogglefield | dump }} to template file

### Versions

PHP 8.1
Statamic 3 3.3.16

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
I can't replicate this. It appears true/false when I'd expect.

Can you provide a repo with this behavior replicated?

**Comment by jackmcdade** [comment]
Closing this issue as we're unable to replicate and haven't heard back with how. Please reopen if that changes, thank you!
