### ISSUE TITLE
sort="entries_count:desc" does not work on the taxonomy tag

### ISSUE THREAD

**Issue by espenlg** [statamic/cms#6267]
### Bug description

I'm using `sort="entries_count:desc"` from the documentation on the taxonomy tag, but it does not sort correctly. If I tweak the template to show `{{ entries_count }}` for each term I can see the order is not right. Same thing with ascending order.

![Screenshot 2022-06-29 at 19 37 31](https://user-images.githubusercontent.com/1135679/176501244-c3620cd3-eaee-462c-ad98-607b2b8282e5.png)

### How to reproduce

![Screenshot 2022-06-29 at 19 38 11](https://user-images.githubusercontent.com/1135679/176501216-e9c9e8f3-f42e-4646-93eb-9c87155fcfca.png)

### Versions

Statamic 3.3.16 Pro
Laravel 9.17.0
PHP 8.0.16
jacksleight/statamic-bard-mutator 1.1.1
jacksleight/statamic-bard-texstyle 1.0.3
pecotamic/sitemap 1.4.0

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by espenlg** [comment]
.. and then it works. Is doing a `php please search:update` relevant?

**Comment by jasonvarga** [comment]
I don't think so. But maybe clearing the cache did it.
