### ISSUE TITLE
Old entries don't get update with new fields when adding new one.

### ISSUE THREAD

**Issue by P4KM4N** [statamic/cms#6269]
### Bug description

1. I added a new field to my articles collection with a default value of {{ title }}, if I look at an article in the control panel I can see the field with my default value
2. but on the frontend of the site, it don't show up, I need to manually update each articles in order to update the markdown file and then it work.

### How to reproduce

1. Create some entries
2. Add a new field with default value
3. add the new field in your template
4. refresh

### Versions

Statamic 3.3.16 Pro
PHP 8.0.16
Laravel Framework 8.83.14
No addons

### Installation

Existing Laravel app

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
Adding a default value to the blueprint fields will just populate the field in the control panel.

If you actually want a value that'll cascade to every entry, you should `inject` it in the collection.

https://statamic.dev/collections#inject

**Comment by P4KM4N** [comment]
Thanks I'll give this a try, it make perfect sense!
