### ISSUE TITLE
Bard menu bar overlapping toolbar

### ISSUE THREAD

**Issue by lakkes-ra** [statamic/cms#6270]
### Bug description

When I have mutliple grid elements on top of each other, the bard menu bar overlaps the toolbars (in this case, it's the link toolbar). 

![Bildschirmfoto 2022-06-30 um 13 05 46](https://user-images.githubusercontent.com/63732644/176663218-51c16486-0cd6-420d-893a-b19159677c4e.png)

### How to reproduce

In your blueprint, create a grid element and use a bard field with links enabled. Inside your entry, add some grid items and click on the link button.  

### Versions

Statamic: 3.3.13
PHP: 8.3.1
Laravel: 8.83.15
Addons: Bard Mutator, Bard Textstyle, Classify, Duplicator, Livewire, Responsive Images, Uuid, Statamic Meilisearch, Pecotamic Sitemap, Meerkat

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

### Additional details

Tested in Chrome, Safari and Firefox

**Comment by jackmcdade** [comment]
Fixed in https://github.com/statamic/cms/pull/7589
