### ISSUE TITLE
Warning - Avoid using abandoned packages ueberdosis/

### ISSUE THREAD

**Issue by beeards** [statamic/cms#6290]
### Bug description

```php
declare(strict_types=1);
``` 
It's not a bug, it's a warning. Every time we call `composer update` we receive the warnings about the abandoned packages. 

### How to reproduce

```sh
composer update
composer depends ueberdosis/html-to-prosemirror
composer depends ueberdosis/prosemirror-to-html
```

### Logs

```shell
⚠️ Package ueberdosis/html-to-prosemirror is abandoned, you should avoid using it. No replacement was suggested.
⚠️ Package ueberdosis/prosemirror-to-html is abandoned, you should avoid using it. No replacement was suggested.

statamic/cms v3.3.16 requires ueberdosis/html-to-prosemirror (^1.3)
statamic/cms v3.3.16 requires ueberdosis/prosemirror-to-html (^2.6)
```

### Versions

```sh
Statamic 3.3.16 Solo
Laravel 9.19.0
PHP 8.1.7
No addons installed
```

### Installation

Existing Laravel app

### Additional details

Maybe you probably want to check out: [ueberdosis/tiptap-php](https://github.com/ueberdosis/tiptap-php) or [enVolt/html-to-prosemirror](https://github.com/enVolt/html-to-prosemirror).

That could be fixed with 2 forks and a note in the README.md of each package pointing the reason to provide them as _not abandoned_.

**Comment by jasonvarga** [comment]
This has been addressed in #6043 and will resolved in 3.4.
