### ISSUE TITLE
Control Panel will still show Saved toast when returning false from EntrySaving listener

### ISSUE THREAD

**Issue by ben182** [statamic/cms#6293]
### Bug description

According to the documentation, the following applies to the EntrySaving event: "You can return false to prevent it from being saved". In the control panel, the saved toast is still displayed, regardless of whether false is returned or not. This is particularly irritating for the user if we want to manually issue a toast, e.g. with Toast::error('message'); because both toasts are then displayed. In my opinion, if a listener returns `false` on the EntrySaving event, the Saved message should not be displayed, because the entry was in fact not saved. It should be recommended to output an error message on your own.

Even worse: If I want to create a completely new entry and false is returned by the listener, the Saved Toast is briefly displayed, and then the user is immediately redirected to a 404.

![Screenshot 2022-07-03 at 15 17 28](https://user-images.githubusercontent.com/17678582/177041780-0fbe4ede-4d83-463a-b52d-5b355350cf31.png)

### How to reproduce

- Install fresh Statamic
- Create a listener on the EntrySaving event

For creation problem
- return false from that listener
- Create a new entry on a collection and save it
- Redirection to 404

For editing problem
- Create a new entry on a collection
- return false from that listener
- Saved toast will be displayed

### Versions

Statamic 3.3.17 Pro
Laravel 9.19.0
PHP 8.1.6
aryehraber/statamic-captcha 1.8.0
doublethreedigital/duplicator 2.3.1
jonassiewertsen/statamic-livewire 2.9.0
pecotamic/sitemap 1.4.0
statamic/collaboration 0.4.0
webographen/statamic-dynamic-token 1.0.0

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by ryanmitchell** [comment]
returning `false` is a silent fail.

If you want to change the toast, then throw an exception in your listener... eg

```php
class EntrySavingListener
{
    public function handle(EntrySaving$event)
    {
        throw new \Exception('My error message');
    }
}
```
