### ISSUE TITLE
Cannot view Assets Fields that are read_only

### ISSUE THREAD

**Issue by fjahn** [statamic/cms#6296]
### Bug description

On read_only fields of type `Assets`, you cannot view the linked assets. In more accurate words: You can see the filetype and name of the file, but you cannot see the *content* of the file.

### How to reproduce

1. Create a field on any blueprint of type `assets` with `read_only` set to `true`, i.e.:
```yaml
-
  handle: cv
  field:
    type: assets
    container: job_applications
    read_only: true
```
2. Create an entry associated with this blueprint, set `cv` to an existing asset via its `md`-file (or temporarily remove the `read_only` to set the asset via CP).
3. Open the entry in the control panel
4. Click on the asset's file name
5. *Nothing happens*
6. Remove the `read_only` in the blueprint above
7. Reload the control panel page, click the asset's file name again *The asset is previewed in the control panel*

### Versions

Statamic 3.3.17 Pro
Laravel 8.83.18
PHP 8.1.7

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
If you add `mode: grid`, there should be buttons to open the asset since 3.3.18

**Comment by fjahn** [comment]
Indeed, thank you!
