### ISSUE TITLE
Floor modifier fails when its passed a string

### ISSUE THREAD

**Issue by austriker27** [statamic/cms#6309]
### Bug description

Floor modifier fails when given a string...  Ideal situation: it should return an `int` rather than fail. At least that's what Erin said. 

### How to reproduce

If `string` is a string, run this:

```antlers
{{ string | length | floor }}
```

### Versions

Statamic 3.3.17 Solo
Laravel 9.19.0
PHP 8.1.7

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
I suspect this is a knock on issue to #6310.

I wouldn't expect the `floor` modifier to know what to do with a string.

**Comment by austriker27** [comment]
> I suspect this is a knock on issue to #6310.
> 
> I wouldn't expect the `floor` modifier to know what to do with a string.

Sorry, I opened 2 different ones upon the advice of Erin.
