### ISSUE TITLE
Cannot pass targeted assets field path to tag using runtime parser

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#6323]
### Bug description

**Edit: This is not specific to the `glide` tag.**

Let's say you want to target the first asset in an `assets` fieldtype. You do this:

```antlers
{{ glide :src="assetsfield:0:id" }}
```

With the regex parser, the `src` parameter gets the id as you'd expect.

With the runtime parser, its an OrderedQueryBuilder instance (which is what `assetsfield` is). It's like it ignored the `:0:id` bit.

### How to reproduce

- Create an `assets` field
- Use the template mentioned above.

### Versions

Statamic 3.3.18
Laravel 9.19.0
PHP 8.1.6

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

You can work around this by wrapping the glide tag.

```antlers
{{ assetsfield:0 }}
  {{ glide :src="id" }}
{{ /assetsfield:0 }}
```

Or, use the regex parser, (although that's overkill).

**Comment by JohnathonKoster** [comment]
@jasonvarga 

Good catch! I will have a fix fairly soon for this. Another way to go about this if you don't want to use the tag pair is to use interpolation (this bug is specific to the dynamic binding):

```antlers
{{ glide src="{assetsfield:0:id}" }}
```
