### ISSUE TITLE
Translation not consistent

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#6334]
### Bug description

My app locale is set to "de", fallback is "de" as well. I usually go blindly through the backend but today I noticed, that there are both German (DE) and English default texts. The HTML lang is correctly set to `de` and some parts of the backend are German some are not. I've never noticed that before.

When I set the locale to "en", everything is English as it should be.

<img width="1309" alt="Screenshot 2022-07-14 at 15 38 01" src="https://user-images.githubusercontent.com/3603346/178996083-0bb5cc5a-e350-4213-8b50-307fcc4d7b34.png">

### How to reproduce

Don't know. Have just set the variables in `app.php`.

### Versions

Statamic 3.3.20 Pro
Laravel 9.20.0
PHP 8.1.4
jonassiewertsen/statamic-livewire 2.9.0
octoper/statamic-blade-components 2.0.0

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
How are you setting your locale?

**Comment by MrMooky** [comment]
In my `app.php` I just do this:

`'locale' => 'de',`

`'fallback_locale' => 'de',`

**Comment by MrMooky** [comment]
Really odd. Here it is a weird mix of both... It's not a major bug or anything so feel free to close it as it must be somewhere on my end then. I'll try to recreate this in a blank app and if possible, share the repository.

<img width="412" alt="Screenshot 2022-07-14 at 17 57 59" src="https://user-images.githubusercontent.com/3603346/179026290-a179dc29-3ec4-439d-b1dc-eca79bcd81b1.png">
