### ISSUE TITLE
Popover in Bard is "visually" hidden at the end of the page in control panel

### ISSUE THREAD

**Issue by Sukrams** [statamic/cms#6335]
### Bug description

I have a set with two Bard fields (and a page with lots of content). When I want to add a set with the "+" in the second bard field the Popover ist visually hidden and doesn't appear in the editor.

It's at the end of the page and the `.popover` gets a style-attribute with a transform with more than 37.000px:   `transform: translate3d(0px, 37642.5px, 0px);`.

Want to add a set... but it seems there's no popover...
<img width="866" alt="Bildschirmfoto 2022-07-14 um 17 28 40" src="https://user-images.githubusercontent.com/15678176/179020448-67a8b036-b58c-4d14-a53b-554f77e97b38.png">

...but with lots of scrolling it appears at the end of the cp.
<img width="1220" alt="Bildschirmfoto 2022-07-14 um 17 28 54" src="https://user-images.githubusercontent.com/15678176/179020456-9b776be8-c860-4809-a4a8-0f1df00bf9bc.png">

### How to reproduce

- create a fieldset with 2 bard fields and add sets to the Bard
- create some content on a page with a replicator
- add content to the second bard field
- click on the "+"
- it appear with lots of scrolling at the end of the page

### Versions

Statamic 3.3.18 Pro
Laravel 9.19.0
PHP 8.1.8
doublethreedigital/duplicator 2.3.1
rias/statamic-redirect 2.3.6
spatie/statamic-responsive-images 2.12.4

### Installation

Fresh statamic/statamic site via CLI

**Comment by jackmcdade** [comment]
Fixed in v4.
