### ISSUE TITLE
Floating Buttons in Bard Extend Beyond Screen in Live Preview

### ISSUE THREAD

**Issue by stoffelio** [statamic/cms#6359]
### Bug description

One of our clients loves to use the live preview to edit their content. However, when using the floating setting for the button row, some of the buttons aren't visible if the editor is rather slim (common on smaller screens).

The floating bar needs to be positioned differently in live preview so it doesn't go beyond the left screen edge.

### How to reproduce

This should be the same in any installation.

### Environment

```yaml
v3.3.22
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

<img width="766" alt="image" src="https://user-images.githubusercontent.com/65236157/180140195-3a5d0aee-1b64-49e0-bedd-0558a054fa0f.png">

**Comment by jasonvarga** [comment]
This is fixed in TipTap 2, which was done in #6043 and will be available in Statamic 3.4.
