### ISSUE TITLE
Modulo throwing DivisionByZeroError (Modulo by Zero) in new Antlers Parser

### ISSUE THREAD

**Issue by PhillipMahlke** [statamic/cms#6360]
### Bug description

After upgrading to Statamic 3.3.22 and activating the new runtime antlers parser, all modulo operations stopped working. and started to throw DivisionByZeroError (Modulo By Zero).

It doesn't matter, what operands i use in the Module equation. A simple  `{{ if 6 % 2 == 0 }} ... {{ /if }}` is enough to throw the error.

### How to reproduce

1. Setup Statamic 3.3.22
2. Activate new Antlers Parser
3. Implement any Modulo check. (I did so in page_builder views)
4. Visit the page, the Modulo is being used.
5. see Error being thrown

### Environment

```yaml
Statamic 3.3.22 Pro
Laravel 8.61.0
PHP 8.0.0
doublethreedigital/duplicator 2.2.0

Starter Kit: Peak
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Good find. You can work around the bug for now by using brackets.

```antlers
{{ if (6 % 2) == 0 }} ... {{ /if }}
```

**Comment by PhillipMahlke** [comment]
Works like a charm. Thanks
