### ISSUE TITLE
Call to undefined method Statamic\Extensions\FileStore::rememberWithExpiration()

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#6365]
### Bug description

After upgrading to 3.3.23 and trying to deploy to my production server, I get the following error:

```
In Repository.php line 668:
                                                                               
  Call to undefined method Statamic\Extensions\FileStore::rememberWithExpiration()
                                                                               
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

After downgrading to the version I had before (3.3.20) the problem does not exist.

### How to reproduce

Just upgraded to 3.3.23 and deployed via Envoyer.

### Environment

```yaml
Statamic 3.3.23 Pro
Laravel 9.21.5
PHP 8.1.4
jonassiewertsen/statamic-livewire 2.9.0
octoper/statamic-blade-components 2.0.0
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Try upgrading back to 3.3.23 - That error seems like an anomaly. Maybe a glitch in the composer install.

**Comment by adnankussair** [comment]
@jasonvarga Just setup a new site and ran into same issue. Had to set composer version to 3.3.22 to get it to load without errors.

**Comment by jasonvarga** [comment]
Still, try running composer update again.

**Comment by adnankussair** [comment]
@jasonvarga Okay trying now...

**Comment by adnankussair** [comment]
@jasonvarga Yup that worked. Thanks! Just needed you in the room to get it to work. 😉

**Comment by jasonvarga** [comment]
Ok 😄 Gonna close this down.

**Comment by adnankussair** [comment]
> Ok 😄 Gonna close this down.

Coolio. Just a heads up though when deploying first time to server, same issue. Had to then downgrade to 3.3.22, deploy first time, upgrade locally then deploy again. Super odd issue.

**Comment by nikolas-m4m** [comment]
I have the same issue on production servers that I'm deploying with Laravel Envoyer. My local installation works fine though. Anyone has an explanation regarding this weird issue?

**Comment by MrMooky** [comment]
@adnankussair Are you also using Envoyer to deploy? Both @nikolas-m4m and I are also using Envoyer. I'd just like to pinpoint this issue.

**Comment by adnankussair** [comment]
> @adnankussair Are you also using Envoyer to deploy? Both @nikolas-m4m and I are also using Envoyer. I'd just like to pinpoint this issue.

@MrMooky we're using forge to deploy.

**Comment by MrMooky** [comment]
This is not working and keeps throwing the error, no matter how often I try to run `composer update`. With Envoyer, `composer update` is basically a new call every time as it creates a separate `releases` folder each time. So running it again won't work here. Again, when using `3.3.22` no errors at all during deployment.

<img width="398" alt="Screenshot 2022-07-25 at 11 20 04" src="https://user-images.githubusercontent.com/3603346/180743402-2af2595d-a5ab-485f-a622-e4b09385a4b3.png">

**Comment by ahinkle** [comment]
We are also having this issue (not using Envoyer) on upgrading with Laravel Forge. Our CI test tool (GitHub Actions) also caught this with `composer update`. Ultimately, we ended up rolling to 3.3.23. Unable to replicate locally.

**Comment by nfragkos** [comment]
Latest Statamic can only be installed on production when limiting Laravel to v9.20.0.
