### ISSUE TITLE
`runtime` parser – `{{ trans }}` not working inside partial

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#6366]
### Bug description

After changing the parser to `runtime` this `{{ trans:form.anmelden }}` is not parsed anymore.

### How to reproduce

/views/sb/newsletter
```
<div class="newsletter">

    <h4 class="title"><i class="fa-icon label-icon fas fa-envelope-open-text"></i> Newsletter</h4>

    <form action="/aktuelles/newsletter" class="form">
        <label for="email" class="form-label email">
            <input class="input" placeholder="E-Mail" type="email" name="email" />
        </label>
        <label class="form-label">
            <button class="btn"><i class="fa-icon fas fa-paper-plane"></i>&nbsp;&nbsp;{{ trans:form.anmelden }}</button>
        </label>
    </form>

</div>
```
/resources/lang/de/form.php
```
    'anmelden' => 'Jetzt anmelden',
```

Before:
![image](https://user-images.githubusercontent.com/3351449/180400680-6687794b-72d0-4643-8853-9f7afe2cb785.png)

After:
![image](https://user-images.githubusercontent.com/3351449/180400540-95042a97-90ca-4691-8611-61d4eab4671d.png)

### Environment

```yaml
Statamic 3.3.22 Pro
Laravel 8.83.20
PHP 8.0.21
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by JohnathonKoster** [comment]
Would it be possible to get some more information on how that partial is being included? Thanks!

**Comment by wm-simon** [comment]
Ah, sorry! My mistake.

`show.antlers.html`
```
{{ section:sidebar }}
{{ partial:sidebars/newsletter }}
{{ /section:sidebar }}

{{ partial:sections/main }}
```

`partial:sections/main` has
```
{{ yield:sidebar }}
```

`partial:sidebars/newsletter`
```
{{ trans:form.anmelden }}
```

Hope, this helps...

**Comment by JohnathonKoster** [comment]
Out of curiosity, does the `/views/sb/newsletter` file have the `.antlers.html` extension?

I'm having trouble reproducing, and the `{{` and `}}` in the after screenshot makes me wonder if Antlers isn't getting parsed there 🤔

**Comment by wm-simon** [comment]
Hey John, now I found time to take a look at it again. It is, like you said, the `.antlers.html` was missing in the filename, I'm really sorry for wasting your time!
I did not expect this, because the regex parser worked fine the last 2 years.
