### ISSUE TITLE
"Signature is missing" with glide:generate

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#6369]
### Bug description

When using `glide:generate` to use within a Blade view, I get an error 400 when using within a style tag. When opening the source I get `Signature is missing`.

Usage with background image in a style tag (not working):

```
@if ($item->preview_image)
    @foreach (Statamic::tag('glide:generate')->src($item->preview_image)->width(235)->height(235) as $image)
        <style>
            .cycle__{{ $loop->index }} {
                background-image: url("{{ $image['url'] }}");
            }
        </style>
    @endforeach
@endif
```

Although it generates the image, so when inspecting the CSS it seems to generally work just fine.

```
<style>
    .cycle__0 {
        background-image: url("/img/asset/ZGF0ZWllbi81NTZFNUM4OS1FOEMxLTQ5RjEtOTM3Ni1ENDAzQTQxRkMwNzdfMV8xMDVfYy5qcGVn?w=235&amp;h=235&amp;s=18a87cc2e04896568e2a5f3876da7782");
    }
</style>
```

Usage with inline image (working):

```
@foreach (Statamic::tag('glide:generate')->src($step->bild)->width(460) as $image)
    <img loading="lazy" src="{{ $image['url'] }}" width="{{ $image['width'] }}" />
@endforeach
```

### How to reproduce

Use `glide:generate` with background image within a `style` tag as seen in the bug description.

### Environment

```yaml
Statamic 3.3.22 Pro
Laravel 9.21.5
PHP 8.1.4
jonassiewertsen/statamic-livewire 2.9.0
octoper/statamic-blade-components 2.0.0
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by MrMooky** [comment]
It works fine when setting `'secure' => false` (saw that in another issue). Which is not what I want on my production server, obviously. But it's weird that the error only occurs when using without an actual `img` tag. It works fine otherwise.

**Comment by jasonvarga** [comment]
Can you look in your devtools and see the URL that actually gets requested? I wonder if the `s` query parameter dropped off somehow.

**Comment by MrMooky** [comment]
> Can you look in your devtools and see the URL that actually gets requested? I wonder if the `s` query parameter dropped off somehow.

It's the one you see above. The `s` parameter is present:

`...?w=235&amp;h=235&amp;s=18a87cc2e04896568e2a5f3876da7782`

The `&amp;` is not the problem, or is it?

**Comment by jasonvarga** [comment]
Try `{!! $image['url'] !!}` instead of `{{ }}`

**Comment by MrMooky** [comment]
That worked. Thanks.
