### ISSUE TITLE
Filters need to support taxonomy and relationship fields

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#637]

**Comment by jackmcdade** [comment]
Looks like we still need to do this one.

**Comment by jackmcdade** [comment]
If i do "taxonomy_field contains {value}" it seems to work okay but if i do `"taxonomy_field **is** value"` it throws an exception.

**Comment by jesseleite** [comment]
> If i do "taxonomy_field contains {value}" it seems to work okay but if i do "taxonomy_field is value" it throws an exception.

Doesn't this make sense though, given that an entry's terms are stored as an array?

```yaml
tags:
  - favourite
  - non-favourite
```

`tags is favourite` would be comparing a `favourite` string to the `['favourite', 'non-favourite']` array on the entry right?

**Comment by jasonvarga** [comment]
We should prevent "is" from even showing up as an option.

**Comment by jesseleite** [comment]
Added a proper taxonomy filter...

![2020-08-12 19 21 55](https://user-images.githubusercontent.com/5187394/90077854-31342d00-dcd1-11ea-9d52-9c36beeaa146.gif)
