### ISSUE TITLE
Blueprint change doesn't stick

### ISSUE THREAD

**Issue by spaceageliving** [statamic/cms#6372]
### Bug description

I have a blueprint for a collection that has 11 items:

<img width="943" alt="Screen Shot 2022-07-23 at 12 52 57 PM" src="https://user-images.githubusercontent.com/874600/180619078-506a5a27-902b-4040-bebc-07a6050d383f.png">

I'm trying to remove the "Equipment" field (bottom of sidebar).

When I use the CP to delete and save, the save notice appears. On page reload, the field is still there.

Then I tried opening the .yaml file (resources/blueprints/collections/equipment/equipment.yaml), deleting the block from the yaml file and saving:

<img width="378" alt="Screen Shot 2022-07-23 at 12 55 44 PM" src="https://user-images.githubusercontent.com/874600/180619137-5b1f5ef6-7629-4970-a621-07d3add8968f.png">

<img width="378" alt="Screen Shot 2022-07-23 at 12 56 39 PM" src="https://user-images.githubusercontent.com/874600/180619156-82646948-643d-4acd-9f9f-31032339f77d.png">

When I return to the CP and try to configure the blueprint again, the field reappears (well, it technically never went away in the CP):

<img width="468" alt="Screen Shot 2022-07-23 at 12 57 08 PM" src="https://user-images.githubusercontent.com/874600/180619197-14891823-134f-4548-9504-d7244e221e8f.png">

Checking the yaml file when the CP is reloaded, shows that the field is not there, yet the CP is still showing the field:

<img width="351" alt="Screen Shot 2022-07-23 at 12 59 15 PM" src="https://user-images.githubusercontent.com/874600/180619245-92eaebf1-8724-410a-b6ca-072c9e585a03.png">

Is there some additional yaml file I am needing to update? cache to clear? (I tired clearing the static cache and stache...)

### How to reproduce

See above.

### Environment

```yaml
Statamic 3.3.23 Pro
Laravel 8.83.15
PHP 8.1.7
stillat/meerkat 2.6.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Nothing special, using blade templates for views, but not related to this issue.

**Comment by duncanmcclean** [comment]
I believe this will be happening because the taxonomy is 'attached' to the collection. If you go to the collection's settings page, there should be an option to remove that taxonomy:

![image](https://user-images.githubusercontent.com/19637309/180619504-0867a040-eb74-431b-8101-8c15f3fb1a60.png)

**Comment by spaceageliving** [comment]
OK I suspected that could be the issue, so I did remove the taxonomy from the field I am trying to delete. Since I am using the taxonomy on the other "equipment_type" field that I don't want to delete, I left it on the collection (and on the field I am keeping). That didn't work--the deleted field keeps reappearing.

Taking your suggestion, I removed the taxonomy from the collection, and from both of the fields. Then, I was able to delete the field (and it stayed deleted). So, after deleting the field, I went back to the collection, adding the taxonomy back (since I need it for the equipment_type field), and the deleted field has now returned.

Must need some adjustment to the taxonomy yaml?

**Comment by duncanmcclean** [comment]
It's intentional behaviour. If you want a collection to be related to a taxonomy, a field is created (so it has some way to relate).

What's your use case for not wanting it to be a field but setup as a 'related taxonomy'?

**Comment by spaceageliving** [comment]
Maybe I'm misunderstanding how taxonomies work, but I have a field 'equipment_type' that is a dropdown that references the "equipment" taxonomy for the dropdown items. The other field I am trying to delete (which is named "equipment") was placed in error....I was basically trying to change the reference for the field to "equipment_type" from "equipment" and got both fields in the blueprint, and can't delete the field referenced as "equipment".

So it sounds like if a field uses a taxonomy, they must have the same name?

**Comment by jasonvarga** [comment]
Right. If you have a taxonomy associated with a collection, a field will be added with a name identical to the taxonomy.

**Comment by spaceageliving** [comment]
OK...opinionated, but I get it. Thanks for your help guys, I think I can fix it from here.

**Comment by jasonvarga** [comment]
To clarify, the one with the same name is the one that does the "taxonomizing" or "tagging". Whatever you pick in that field associates that entry with that term.

So later when you go to try and list all the entries tagged with a certain term... it'll only use that field for the relation.

You're free to add other terms fields to your blueprint, but they won't taxonomize the entry.

**Comment by spaceageliving** [comment]
Thanks @jasonvarga
