### ISSUE TITLE
Copying Password Reset Link on Mobile doesn't work

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#6378]
### Bug description

I tried to copy the password reset link for a user from my iPhone and got only an alert box with a cut-off link I could not copy. 

### How to reproduce

Try to copy a password reset on iPhone. 

### Environment

```yaml
Statamic 3
```

### Installation

Starter Kit using via CLI

**Comment by joshuablum** [comment]
Hey @jcohlmeyer,

Could you maybe provide more details or a screenshot?
I just tried to replicate it and it works fine for me.

Are you maybe using an iPhone with a smaller viewport width (iPhone SE, 8, Mini etc.)

![IMG_F4E7BB89D580-1](https://user-images.githubusercontent.com/3824203/180997919-c7f22670-0410-4f80-8eac-6cfde5c3f0dc.jpeg)

**Comment by jcohlmeyer** [comment]
Here is a screenshot. Additionally, I can not select text in the alert. 

![image](https://user-images.githubusercontent.com/1778271/180999760-0c061d5f-1a3f-4fb2-9e74-8d9a9d3015b8.png)

**Comment by joshuablum** [comment]
Thanks!

Does it work in mobile Safari for you?

**Comment by jcohlmeyer** [comment]
Yes, it works in Safari, but not Brave.

**Comment by joshuablum** [comment]
We can't really do anything about this, sorry. It's Brave's implementation of how the alert gets shown. Closing this issue but opening one in https://github.com/statamic/ideas. Could be a good idea to move away from the system `alert` to a more custom solution / modal.

**Comment by jcohlmeyer** [comment]
Thanks, should the issue re opened then, @joshuablum?

**Comment by joshuablum** [comment]
Yes, reopened it 👍
