### ISSUE TITLE
Forms: "add email"  in control panel does not validate on email field

### ISSUE THREAD

**Issue by freshface** [statamic/cms#6384]
### Bug description

When creating a form and adding an email the first field "email" doest not validate for a valid email address.

<img width="936" alt="Screenshot 2022-07-27 at 15 29 19" src="https://user-images.githubusercontent.com/103913/181259212-df647406-0300-47d7-a364-d7b948913a44.png">

### How to reproduce

When creating a form and adding an email the first field "email" doest not validate for a valid email address.

### Environment

```yaml
Statamic 3.3.17 Pro
Laravel 9.16.0
PHP 8.1.5
aryehraber/statamic-captcha 1.8.0
rias/statamic-address-field 1.0.2
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)

**Comment by duncanmcclean** [comment]
Note for whoever implements this: you can also add Antlers into that 'Recipient' box so probably need to do some kind of validation there too?

**Comment by jacksleight** [comment]
You can also add multiple email addresses, so would need to work with that.

**Comment by jackmcdade** [comment]
@duncanmcclean and @jacksleight, that's exactly why it doesn't perform strict email validation here 😂
