### ISSUE TITLE
Save always config field

### ISSUE THREAD

**Issue by niktwenty3** [statamic/cms#6386]
The idea is to create a "Save always" configuration field that when it is `true` saves the field's value regardless of visibility settings. This setting could be used in fields that a "Select" or "Button group" controls their visibility, essentially giving the user the capability to create "faux-tabbed" content. 

<img width="367" alt="Save_always_field" src="https://user-images.githubusercontent.com/10053187/181230440-44f8f19b-cb5d-4dea-aba1-b613d11b9110.png">

I've done a tiny bit of leg work and figured out on my own where I could add this option so that it can be displayed on the backend, but, since I have not worked with Laravel before, it's probably just a tiny step. 

Still, to add the button on my end I added the following code in `cms/src/Http/Controllers/CP/Fields/FieldsController.php` after `visibility`. 

```
            'save_always' => [
                'display' => __('Save always'),
                'instructions' => __('statamic::messages.fields_save_always_instructions'),
                'type' => 'toggle',
                'validate' => 'boolean',
                'width' => 33,
            ],
```

And for the message I just edited `cms/resources/lang/en/messages.php` and added `'fields_save_always_instructions' => 'Save field value always regardless visibility status.',` after `fields_visibility_instructions`.

My next goal is to try and understand how Entries are saved/validated to potentially offer a patch for this.

**Comment by jesseleite** [comment]
We've talked about adding config for this, figured it would come up at some point! Feel free to give [this PR](https://github.com/statamic/cms/pull/6387) a whirl 👍

>Save field value always, regardless of visibility status.

^ I tweaked the config instructions in your example though, as the hidden option in the `Visibility` drop down doesn't affect actually data flow at all. This is more to override [data flow behaviour on conditional fields](https://statamic.dev/conditional-fields#data-flow).
