### ISSUE TITLE
Missing 'boolean' and 'empty' options in blueprint conditions

### ISSUE THREAD

**Issue by pschaub** [statamic/cms#6401]
### Bug description

I am not able to select 'boolean' or 'empty' or 'not empty' in the conditions during creation of a field in a blueprint:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/11846736/181854802-10900571-2e0a-4dec-9540-db532f32e305.png">

According to the documentation it should be possible: https://statamic.dev/conditional-fields

### How to reproduce

Add a field to a blueprint and try to add a condition

### Environment

```yaml
statamic/cms v3.3.24
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jesseleite** [comment]
You can select 'equals' and type 'empty' into the text input to the right.

Or if you're defining conditions in the yaml, you can:

```yaml
show_when:
  title: equals empty
```

This also works:

```yaml
if:
  title: is empty
```

The full list of the options [are documented here](https://statamic.dev/conditional-fields#advanced-comparisons)...

![image](https://user-images.githubusercontent.com/5187394/181866713-a9e3d6d0-133d-471d-916e-85163d398c39.png)
