### ISSUE TITLE
Broken Password Reset for Unactivated Accounts

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#6402]
### Bug description

When an account is not activated within the 72 hour window subsequent password reset links do not work and show the message invalid token.

### How to reproduce

1. Create an account and send an activation email.
2. Do not activate the account and let the link expire.
3. Send a password reset link (copy it from the CP).
4. Try to use the password reset link.
5. Get an invalid token error.
6. Get emails from your clients saying the password reset link will not work or let them log into their ✨new website 😱 

### Environment

```yaml
Statamic 3.3.23 Pro
Laravel 8.83.12
PHP 8.1.7
kind-work/two-fa 1.5.1
statamic/ssg 1.0.1
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
You can configure the length of time until the activation link expires in your [`config/auth.php`](https://github.com/statamic/statamic/blob/master/config/auth.php#L104) file.

```php
'activations' => [
    'provider' => 'users',
    'table' => 'password_activations',
    'expire' => 4320,
    'throttle' => 60,
],
```

The default length is `4320` minutes (72 hours). You can change this to whatever you want.

**Comment by jcohlmeyer** [comment]
This does not fix the issue, a password reset for an unactivated account does not work and does not give any indication in the CP when you create a password reset link that it will not work.

**Comment by duncanmcclean** [comment]
Ah gotcha! 

I _think_ I see what you mean... you send the activation link, then the user requests a password reset after the link expires, then you get an error? Is that right?

**Comment by jcohlmeyer** [comment]
> Ah gotcha!
> 
> I _think_ I see what you mean... you send the activation link, then the user requests a password reset after the link expires, then you get an error? Is that right?

Yes, that is correct.

**Comment by duncanmcclean** [comment]
Cool, thanks for confirming. I've re-opened this issue. Apologies
