### ISSUE TITLE
User Account Disclosure

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/cms#6403]
### Bug description

Enter an email address in the CP Password reset form, and get a different message depending on whether the account exists or not.

This lets users know what accounts and email addresses are registered with the server, and what are valid email addresses to use for all kinds of other nasty things.

I expect the password reset page to say the same thing whether this is a matching account or not.

### How to reproduce

1. Try CP password reset with a valid email address (note message).
2. Try CP pass reset with an invalid email address (note a different message).
3. Not messages are different, now you can harvest email addresses, etc. 😱 

### Environment

```yaml
Statamic 3.3.23 Pro
Laravel 8.83.12
PHP 8.1.7
kind-work/two-fa 1.5.1
statamic/ssg 1.0.1
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
See response in https://github.com/statamic/ideas/issues/752

Thanks!
