### ISSUE TITLE
When a Page is deleted from Control Panel its entry is not removed from `content/trees/collections/pages.yaml`

### ISSUE THREAD

**Issue by tldrcoder** [statamic/cms#6441]
### Bug description

I created some pages inside control panel

Then deleted them

However, `content/trees/collections/pages.yaml `is still listing those deleted entries.

Also, if you update a Page's id, the pages.yaml is not updated to reflect the change.

### How to reproduce

1. create a page from inside control panel
2. delete page from inside control panel

### Environment

```yaml
Statamic 3.3.23 Solo
Laravel 8.83.22
PHP 7.4.19
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by joshuablum** [comment]
Changed the title since it could be confused with the actual thing called [cPanel](https://www.cpanel.net/). I was confused myself when I read the title tbh 😅

Will try to replicate it.

**Comment by duncanmcclean** [comment]
Hmm, I'm unable to reproduce this. How are you deleting the entry?

Also, where are you updating the entry's ID? If you edit it in the file itself, then yes, it won't get changed because Statamic won't know what to change. That bit's up to you.

**Comment by jasonvarga** [comment]
Going to assume that 

> Then deleted them

means that you deleted them directly through the filesystem.

If that's not the case, let us know and we can reopen this.
