### ISSUE TITLE
Vite tag doesn't work with print stylesheets, etc

### ISSUE THREAD

**Issue by tao** [statamic/cms#6442]
### Bug description

It seems like the new tag only works with the `src` attribute but I have a print stylesheet and it's ignoring the `media` role. I also use [Turbo](https://github.com/hotwired/turbo) on my site to improve the static website experience but that attribute looks like it's getting ignored too.

**Tags**
```antlers
    {{ vite src="resources/css/tailwind.css" data-turbo-track="reload" }}
    {{ vite src="resources/css/print.css" media="print" data-turbo-track="reload" }}
```

**Output**
```html
<script type="module" src="http://localhost:5173/@vite/client"></script>
<link rel="stylesheet" href="http://localhost:5173/resources/css/tailwind.css">

<script type="module" src="http://localhost:5173/@vite/client"></script>
<link rel="stylesheet" href="http://localhost:5173/resources/css/print.css">
```

And if I run `vite build` it produces this output so it's not working correctly either for production

```html
<link rel="stylesheet" href="http://127.0.0.1:8000/build/assets/tailwind.6adf28fa.css">
<link rel="stylesheet" href="http://127.0.0.1:8000/build/assets/print.1ee39e21.css">
```

### How to reproduce

```antlers
    {{ vite src="resources/css/tailwind.css" data-turbo-track="reload" }}
    {{ vite src="resources/css/print.css" media="print" data-turbo-track="reload" }}
```

### Environment

```yaml
Environment
Laravel Version: 9.23.0
PHP Version: 8.0.21
Composer Version: 2.0.11
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
The vite tag is just a wrapper around Laravel's Vite feature.

You can follow the instructions here to add additional attributes.

https://laravel.com/docs/9.x/vite#arbitrary-attributes

**Comment by tao** [comment]
Sorry, thanks.

For anyone else stuck with this you can add this to the `AppServiceProvider.php`:

```php
    /**
     * Bootstrap any application services.
     */
    public function boot()
    {
        ...

        Vite::useStyleTagAttributes(fn (string $src, string $url, array|null $chunk, array|null $manifest) => [
            'data-turbo-track' => 'reload',
            'media' => ($src === 'resources/css/print.css' ? 'print' : false),
        ]);
    }
```
