### ISSUE TITLE
Telescope didn't report anything

### ISSUE THREAD

**Issue by samdgea** [statamic/cms#6468]
### Bug description

Recently i install Laravel telescope and following the steps on [https://laravel.com/docs/9.x/telescope#installation](https://laravel.com/docs/9.x/telescope#installation)

But i try submit the form no action recorded on Laravel Telescope.

Is there any configuration i need to do ?

### How to reproduce

1. Set database configuration on .env
2. Run `composer require laravel/telescope`
3. Then run `php artisan telescope:install`
4. Finally run `php artisan migrate`
5. Try fill the form input
6. Check to Telescope, but nothing happend

### Logs

```shell
No Log was created
```

### Environment

```yaml
Statamic 3.3.26
Laravel 8.83.23
PHP 8.1.8
aerni/livewire-forms 3.4.0
austenc/socialize 1.0.0
edalzell/forma 1.2
jonassiewertsen/statamic-livewire 2.9.0
kind-work/two-fa 1.5.1
parfaitementweb/statamic-country-fieldtype 1.0.0
plugrbase/statamic-maintenance-mode 1.0.4
silentz/akismet 3.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by joshuablum** [comment]
Hey @samdgea,

This is not necessarily a bug.

But could you please provide a little more context?

- You submitted a Statamic Form?
- Using the Livewire Forms addon or Livewire in general?
- Does it work for other types of requests?
- Which tabs did you check in Telescope?
