### ISSUE TITLE
WhereTaxonomy not working as expected

### ISSUE THREAD

**Issue by justkidding96** [statamic/cms#6497]
### Bug description

I've a custom query for a filter which I'm building. 
I use ```whereTaxonomy``` to get entries by a taxonomy except this give me zero results.

### How to reproduce

```blade
@php
    use Statamic\Facades\Entry;

    $entries = Entry::query()
        ->where('collection', 'posts')
        ->whereTaxonomy('categories::blog')
        ->get();
    dd($entries->get()); // Empty collection
@endphp

### Logs

_No response_

### Environment

```yaml
Environment
Application Name: App
Laravel Version: 9.24.0
PHP Version: 8.0.8
Composer Version: 2.0.9
Environment: local
Debug Mode: ENABLED
URL: app.lcl
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Version: 3.3.28 PRO

Statamic Addons
statamic/seo-pro: 3.1.0
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
You'll need to provide more details. It seems to work fine here.

Is your `posts` collection configured to use the `categories` taxonomy?
Do any entries in the `posts` collection have a `categories` value?

**Comment by justkidding96** [comment]
@jasonvarga I'm really sorry. Turn out for some reason the link is removed so you where right. It works now!
