### ISSUE TITLE
There is no existing directory at storage/logs and it could not be created: Permission denied

### ISSUE THREAD

**Issue by markcoogan** [statamic/cms#6522]
### UPDATE - I've checked the folder permissions, if I work down through the files mentioned and make sure they have 755, I eventually arrive at an error message:

file_get_contents(/var/www/html/composer.lock): Failed to open stream: No such file or directory (View: /var/www/html/vendor/statamic/cms/resources/views/partials/head.blade.php) (View: /var/www/html/vendor/statamic/cms/resources/views/partials/head.blade.php) (View: /var/www/html/vendor/statamic/cms/resources/views/partials/head.blade.php)

### END UPDATE The file permission eventually seem to reset themselves and I end up back where I started.

I updated Statamic to the latest version and after it finished, I'm getting the message:

There is no existing directory at storage/logs and it could not be created: Permission denied

This is happening on a local version using Docker.  I've run all the commands I can find in other articles where the issue has being raised:

php artisan route:clear

php artisan config:clear

php artisan cache:clear

... and lots of other variations on this, but I can't get passed this error.

### How to reproduce

Update to latest version

### Environment

```yaml
Statamic 3.3.6 Pro
Laravel 9.25.1
PHP 8.1.7
aryehraber/statamic-captcha 1.8.0
pecotamic/sitemap 1.4.0
spatie/statamic-responsive-images 2.13.0
statamic/seo-pro 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by edalzell** [comment]
What was the issue?

**Comment by markcoogan** [comment]
Sorry, I thought I updated this before I closed it.  It wasn't a Statamic issue at all, it was a docker issue.  I noticed it was working fine in Laravel server, checked Docker, there was an update waiting.  I updated Docker and restarted and all seems ok.
