### ISSUE TITLE
Form Fieldtype: {{ field }} is empty

### ISSUE THREAD

**Issue by fjahn** [statamic/cms#6542]
### Bug description

The [documentation for the form fieldtype](https://statamic.dev/fieldtypes/form#templating) states that within antlers, the value of form fieldtype fields can be used like the [`form` tag](https://statamic.dev/tags/form).

While `{{ display }}` works fine, `{{ field}}` always results in an empty string instead of the html for the field. If I use the [`form` tag](https://statamic.dev/tags/form) instead of the field form fieldtype field (so the form handle is hardcoded), it works fine.

Side note: I am using the regex antlers parser. With the runtime parser, even the labels for the fields do not show up properly.

### How to reproduce

1. Setup a blueprint `home` with this field:

```yaml
-
  handle: form_field
  field:
    type: form
```

2. Setup antlers with this content (example from the [docs](https://statamic.dev/fieldtypes/form#templating)):

```antlers
<h2>Form Tag</h2>

{{ form:example_form }}
  {{ fields }}
      <div class="p-2">
          <label>{{ display }}</label>
          <div class="p-1">{{ field }}</div>
          {{ if error }}
              <p class="text-gray-500">{{ error }}</p>
          {{ /if }}
      </div>
  {{ /fields }}
  <button type="submit">Submit</button>
{{ /form:example_form }}

<h2>Field</h2>

{{ form_field }}
  {{ fields }}
      <div class="p-2">
          <label>{{ display }}</label>
          <div class="p-1">{{ field }}</div>
          {{ if error }}
              <p class="text-gray-500">{{ error }}</p>
          {{ /if }}
      </div>
  {{ /fields }}
  <button type="submit">Submit</button>
{{ /form_field }}
```

3. Setup an entry with blueprint `home` with this content:

```markdown
---
form_field:
  - example_form
---
```

4. Open that entry in the browser
5. While the first section shows the fields just fine, the second section (using the fields directly) have no actual field elements.

### Environment

```yaml
Statamic 3.3.31 Pro
Laravel 8.83.23
PHP 8.1.7
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by fjahn** [comment]
I found a workaround for the issue:
**This only works when using the newer runtime parser for antlers.**

```antlers
{{ form:create :in="form_field->handle()" }}
  {{ fields }}
      <div class="p-2">
          <label>{{ display }}</label>
          <div class="p-1">{{ field }}</div>
          {{ if error }}
              <p class="text-gray-500">{{ error }}</p>
          {{ /if }}
      </div>
  {{ /fields }}
  <button type="submit">Submit</button>
{{ /form:create }}
```

Still, I found no way to make this work with the regex parser, and this is pretty akward to use.

**Comment by jasonvarga** [comment]
The docs are wrong, sorry about that. The form fieldtype augments to a form instance, not a form:create tag. Not sure where that idea came from.

Do this:

```
{{ form:create :in="form_field:handle" }}
   ...
{{ /form:create }}
```

**Comment by jasonvarga** [comment]
Docs updated. https://github.com/statamic/docs/commit/a827c9558a53026810e06cd861b24c015b0a3d36
