### ISSUE TITLE
{nocache} tag and 404 pages

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/cms#6543]
### Bug description

Using `{nocache}` in a layout means that on 404 pages we see a lot of `{NOCACHE_PLACEHOLDER}` being output instead of what we wanted not to be cached.

It seems the middleware is not being run?

### How to reproduce

Add {nocache} to your layout and hit a 404 page on your install.

### Environment

```yaml
Statamic 3.3.29 Pro
Laravel 8.83.23
PHP 8.1.7
aerni/social-links 2.3.1
cnj/seotamic 2.0.6
doublethreedigital/duplicator 2.3.1
mitydigital/iconamic 1.0.2
pecotamic/sitemap 1.4.0
thoughtco/statamic-minify 1.1.1
thoughtco/statamic-redirects 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Confirmed.

**Comment by mikemartin** [comment]
Just hit this one myself
