### ISSUE TITLE
Custom routes override cp routes

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6551]
### Bug description

Not exactly a bug but I have an unusual routing requirement for a project. Here are my web.php routes:

```
Route::get('{exhibition}', [ExhibitionController::class, 'viewExhibition']);
Route::get('{exhibition}/{material}', [ExhibitionController::class, 'viewMaterial']);
```

Exhibitions and Materials are both collections and I retrieve them in my routeserviceprovider.

The problem is that /cp/xxx/ gets overridden by the above and the control panel becomes inaccessible. I get errors like these:
`Too few arguments to function App\Http\Controllers\ExhibitionController::viewExhibition()`

Maybe cp routes should always override custom routes when Statamic is defining them??

Or perhaps someone can suggest another solution to this?

Thanks!

### How to reproduce

Add some custom routes as described and try to access control panel.

### Environment

```yaml
Version: 3.3.30 PRO
Laravel Version: 9.25.1
PHP Version: 8.1.1
```

### Installation

Existing Laravel app

**Comment by ryanmitchell** [comment]
It sounds to me like there is a parameter in your ExhibitionController `viewExhibition` method that you havent defined in the URL - can you share that function?

**Comment by jasonvarga** [comment]
Your wildcard route is going to override all your content routes too.

You can use regex to tell it to ignore the CP.

```php
Route::get(...)->where('exhibition', '(?!cp).*');
```

**Comment by stuartcusackie** [comment]
@jasonvarga Perfect. Thank you. I couldn't figure that out.
