### ISSUE TITLE
Changing `statamic.users.repositories.file.paths.users` config value has no effect

### ISSUE THREAD

**Issue by hivokas** [statamic/cms#6568]
### Bug description

I want to use different path depending on the environment:

```
'users' => base_path(env('APP_ENV') === 'local' ? 'users-local' : 'users'),
```

However, changing `statamic.users.repositories.file.paths.users` config value has no effect. 

After some digging I found out that users path can be customized by changing `statamic.stache.stores.users.directory` config value.

Is that by design? Does `statamic.users.repositories.file.paths.users` affect anything? 

### How to reproduce

See above

### Environment

```yaml
Statamic 3.3.19 Pro
Laravel 9.19.0
PHP 8.1.8
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Good catch. We should remove that config. The rules and users are correct though.

**Comment by hivokas** [comment]
Nice, thanks!
