### ISSUE TITLE
Asset upload errors not shown on Safari

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#657]
I was trying to upload an asset in Safari and all I got was: https://cl.ly/5e9fa6c21c67

In Firefox I got: https://cl.ly/0838b0c7eae4

The issue was that the max upload size needed to be set/increased.

**Comment by damcclean** [comment]
Looks like this issue has been fixed now. I tried to upload the movie, Brave to my test Statamic site and I got this message, which I'm guessing is good.

![image](https://user-images.githubusercontent.com/19637309/102695398-0463c980-421f-11eb-860c-53b764a369b7.png)

**Comment by jasonvarga** [comment]
@damcclean did you do it in Safari though?

**Comment by damcclean** [comment]
> @damcclean did you do it in Safari though?

Yup.
