### ISSUE TITLE
Entry relationship field is empty on listing on localised site

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6605]
### Bug description

Just a small glitch here. This is my default site. Notice that exhibition title is shown
![image](https://user-images.githubusercontent.com/20210934/187692994-2fecfbf5-11e5-421d-bec1-c0bc303b8777.png)

And this is one of my localised sites. Exhibition title is missing.
![image](https://user-images.githubusercontent.com/20210934/187692929-d8d4b394-e1c5-48fa-8a45-439efd6a0e89.png)

The exhibition title field is localisable but at the moment it is falling back to the default title. For some reason this isn't displaying on the listing.

The exhibition relationship field is not localisable.

Thanks!

### How to reproduce

- Set up a multisite
- Set up an entry relationship field (not localisable). Make it listable.
- Set entry title to localisable
- View listings on each site.

### Environment

```yaml
Laravel Version: 9.27.0
PHP Version: 8.1.1
Version: 3.3.32 PRO
```

### Installation

Existing Laravel app

**Comment by volkeransmann** [comment]
Same here...

**Comment by mathamel** [comment]
I have the same issue, on front-end.
