### ISSUE TITLE
Content in CP does overflow

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#6627]
### Bug description

It is possible to scroll some cp content on the x axis.

### How to reproduce

https://user-images.githubusercontent.com/38906163/188173348-718c35bc-05bd-41b4-aea5-ed15080d0c2c.mov

### Environment

```yaml
Statamic Version: 3.3.33 Solo

Shown on Chrome 105.xxx
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jackmcdade** [comment]
Tracked this down with `git bisect` and found it was from the Popper changes in https://github.com/statamic/cms/pull/6601. Digging deeper.

**Comment by jasonvarga** [comment]
@jonassiewertsen see #6628
