### ISSUE TITLE
Link existing stuff button stopped working after updating to 3.3.34

### ISSUE THREAD

**Issue by alwanof** [statamic/cms#6674]
### Bug description

https://www.awesomescreenshot.com/video/10961808?key=a1b1467cd4de9a18a89f7cba58d3ac91

### How to reproduce

https://www.awesomescreenshot.com/video/10961808?key=a1b1467cd4de9a18a89f7cba58d3ac91

### Environment

```yaml
PHP Version 8.1.9
Laravel 9
Statamic v3.3.34
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Do you have any javascript errors in your developer console?

**Comment by alwanof** [comment]
@jasonvarga thank  you for your quick response, 
no errors in the console, also no request in the network
recently I installed a Coloporation addon then I remove it

**Comment by jasonvarga** [comment]
Try deleting the `vendor` directory and running `composer install`.

**Comment by alwanof** [comment]
thanks @jasonvarga that works
