### ISSUE TITLE
Independent auth guards: Default guard ignored

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6683]
### Bug description

I'm not sure if this is a bug or intended behaviour but I have followed this guide:
https://statamic.dev/tips/using-an-independent-authentication-guard
To provide an auth config like so:

```
'defaults' => [
  'guard' => 'web',
  'passwords' => 'resets',
],

'guards' => [
  'web' => [
    'driver' => 'session',
    'provider' => 'users',
  ],
  'statamic' => [
    'driver' => 'session',
    'provider' => 'statamic',
  ]
],

'providers' => [
  'users' => [
    'driver' => 'eloquent',
    'model' => \App\Models\User::class,
  ],
  'statamic' => [
    'driver' => 'statamic',
  ],
],
```

In order to get static caching and the nocache working I have applied the statamic.web middleware to my custom protected routes:
`->middleware(['auth', 'statamic.web']);`

The problem I am having is that I have to make sure that I pass the 'web' guard to any logic that interacts with my non-statamic users, e.g.:
```
Auth::guard('web')->logout();
Auth::guard('web')->user()->delete();
```

My query is, shouldn't the default guard in config/auth.php be adhered to? It's a little worrying that I might accidentally modify a Statamic user rather than my apps users and I'll have to be extra vigilant to always pass the correct guard to auth functions.

Thanks

### How to reproduce

- Set up independent auth guards as described in the docs.
- Apply statamic.web middleware to custom routes
- Use auth helpers and facades to interact with users. Note that the Statamic guard is applied rather than the default.

### Environment

```yaml
Version: 3.3.34 PRO
Laravel Version: 9.28.0
PHP Version: 8.1.1
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Don't add the entire `statamic.web` middleware group to your routes. Only add the ones you need.

There is a middleware within that group that sets the auth guard to the statamic one.

**Comment by stuartcusackie** [comment]
I have created a custom middleware group and left out the Guard Middleware. It works for my custom routes but I've just realised that it's not a great approach because Statamic is adding the guard to all the collection routes.

So I'm still leaning towards my original point. Should Statamic be applying it's guard to front-end routes when we've set a different default guard in our Laravel auth config?

**Comment by jasonvarga** [comment]
> I have submitted a PR to update the example 

I don't see a PR from you.

But I believe it's correct the way it already is.
On routes that use the Statamic web middleware group (or just the AuthGuard middleware), it will use whatever guard you define in `config/statamic/users.php` `guards.web`.

Since you had `web` set to `statamic`, it will use the Statamic auth guard. On Statamic automatic routes, they'll use the Statamic auth guard on purpose.

You're free to change that option to avoid using the Statamic auth guard though.

**Comment by stuartcusackie** [comment]
> I don't see a PR from you.

I don't see it either. I must have not submitted it!

I get this now. My PR may not have made sense in the context anyway.

I think the docs page could be improved by running through a full example of using the statamic guard for the control panel and the web guard for the front-end. The [current doc page](https://statamic.dev/tips/using-an-independent-authentication-guard) almost covers it but this issue, and another issue with password resets (docs issue open), could be covered better on that page.
