### ISSUE TITLE
Can't switch to Sidebar tab

### ISSUE THREAD

**Issue by arthurperton** [statamic/cms#6693]
### Bug description

On an entry edit screen, you can't switch to the Sidebar tab.

Workaround: if possible, make the window wide enough so you have a separate sidebar.

### How to reproduce

1. Edit a page
2. Make the window narrow enough to make the sidebar become a tab
3. Click the Sidebar tab

### Environment

```yaml
Statamic 3.3.35 Pro
Laravel 8.83.23
PHP 8.1.8
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

This issue is new in v3.3.35, introduced by #6680.

**Comment by labSupport** [comment]
It seems that this issue is still present.

I updated from 3.3.35 => 3.3.39 and I'm still not able to get the sidebar tab working.

Environment
`Statamic 3.3.39 Pro
Laravel 8.0
PHP 8.1.8`

**Comment by jasonvarga** [comment]
Your assets may somehow be outdated. Delete `public/vendor/statamic/cp` and run `php please install` then hard refresh in your browser.

**Comment by labSupport** [comment]
That worked very well, thanks!
