### ISSUE TITLE
Statamic images hash bug

### ISSUE THREAD

**Issue by mihaicirstea** [statamic/cms#6697]
### Bug description

A bug into the statamic code is that the hash from the image url `YXNzZXRzL29jdG9wdXMuanBn` can sometimes contain equal `=` signs.

For example if you have a `img/asset/donut.jpg` image in the `GlideUrlBuilder.php` file you will pass to the asset case with the following values:

```
$this->itemType() -> "asset"
$this->item->containerId() -> "assets"
$this->item->path() -> "donut.jpg"
$path -> "asset/YXNzZXRzL2RvbnV0LmpwZw=="
$params -> array:3 [▼
  "h" => "570"
  "w" => "1472"
  "fit" => "crop"
]
case 'asset':
    $path = 'asset/'.base64_encode($this->item->containerId().'/'.$this->item->path());
    break;
```

The end result because of the base64_encode function would be:

`/img/asset/YXNzZXRzL2RvbnV0LmpwZw==?h=570&w=1472&fit=crop&s=60f26b060eef8d737ec826f05946024d`

But notice that this hash `YXNzZXRzL2RvbnV0LmpwZw==` has 2 `==` signs at the end.

This is causing an issue when the method generateSignature from `League\Glide\Signatures\Signature` is called, because the parameters used to create the signature hash will be like so:

```
$params -> array:4 [▼
  "/img/asset/YXNzZXRzL2RvbnV0LmpwZw" => "="
  "fit" => "crop"
  "h" => "570"
  "w" => "1472"
]
```

This is a preview of the cards not displaying images in some cases:
<img width="1402" alt="Screen Shot 2022-09-12 at 8 14 15 AM" src="https://user-images.githubusercontent.com/10725789/189650597-5b64acd5-6de4-4a05-a852-4db7f979c548.png">

### How to reproduce

Notice that in the previous `$params` array you will not have the first element `"/img/asset/YXNzZXRzL2RvbnV0LmpwZw" => "=" `which is there only because the hash contains == signs.

Let me know if anyone else could reproduce this, I think just by replacing the = signs from the generated hash would fix the issue.

Thank you!

### Environment

```yaml
Statamic v3
Laravel 8
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
Can you show the template you're using?

**Comment by iulyanp** [comment]
Hi @jasonvarga 

The template is this:

`<a href="{{ $url }}" class="transition-all duration-75 ease-in-out h-full block relative top-0 hover:-top-2 shadow-lg hover:shadow-xl bg-white rounded-xl overflow-hidden">
    <img class="{{ $oversized ? 'hidden md:block' : 'hidden' }} squiggle" height="285" src="{{ glide:hero_image height="570" width="1472" fit="crop_focal" }}" alt="{{ $hero_image:alt }}">
    <img class="squiggle {{ $oversized ?= 'md:hidden' }}" height="285" src="{{ glide:hero_image height="570" width="736" fit="crop_focal" }}" alt="{{ $hero_image:alt }}">
    <div class="py-6 px-8">
        <h2 class="font-bold text-2xl leading-tight">
            {{ $title }}
        </h2>
        <p class="text-xs text-gray-600 mt-4 flex items-center">
            {{ $date }}
        </p>
    </div>
</a>
`

The issue I think it's with this kind of generated urls: `/img/asset/YXNzZXRzL21vcnRnYWdlLWRvd25wYXltZW50LmpwZw==?h=570&w=736&fit=crop&s=70f04ad087bc441f99a827da8c3e8d7a`

In `GlideController::validateSignature` you will have this path:

```
"/img/asset/YXNzZXRzL21vcnRnYWdlLWRvd25wYXltZW50LmpwZw=="
```

And the`SignatureFactory::create(Config::getAppKey())->validateRequest(` method will use this params into `http_build_query($params)` 

```
array:4 [▼
  "/img/asset/YXNzZXRzL21vcnRnYWdlLWRvd25wYXltZW50LmpwZw" => "="
  "fit" => "crop"
  "h" => "570"
  "w" => "736"
]
```

Hope it helps to reproduce it.

**Comment by jasonvarga** [comment]
Are you doing something weird with the server config? The path shouldn't be in that array.

**Comment by jasonvarga** [comment]
I assume it's something weird about the setup you're explaining in #6681.

**Comment by iulyanp** [comment]
@jasonvarga I investigate it a little more and I think you're right. Something it's not ok on nginx with that alias config.
Thanks for your help!
