### ISSUE TITLE
Static cache exclusion not working for custom route

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6735]
### Bug description

I have a settings page for authenticated users that is not being excluded from the static cache. It's an unusual set up so I might have misconfigured something.

**config/statamic/static_caching.php**
```
'exclude' => [
  '/livewire*', 
  '/settings'
],
```

**routes/web.php**
The main reason I am applying statamic.web middleware is so that the @nocache tag gets parsed correctly in my header, which shows different menus based on auth status.
```
Route::middleware(['auth', 'statamic.web'])->group(function () {
  Route::get('/settings', function () {
    return view('settings');
  })->name('settings');
});
```

**views/settings.blade.php**

The view contains a form for editing the user's profile. The update to the database works correctly but the input values are being cached. They are livewire forms.

Any ideas? I don't understand why anything on this page would be statically cached since the url is on the list of exclusions. Perhaps something to do with my custom route middleware?

### How to reproduce

1. Set up a custom settings page and route as described
2. Add '/settings' to static cache exclusions
3. Enabled static cache
4. Update input values.
5. Refresh page, notice no changes.

### Environment

```yaml
Version: 3.3.36 PRO
Laravel Version: 9.30.0
PHP Version: 8.1.1
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by edalzell** [comment]
Try using the `Route::statamic` for it.

**Comment by stuartcusackie** [comment]
That doesn't work either. Weird.

I thought maybe because it is a Blade Layout Component that that might affect it, but using simple template inheritance doesn't work either. I've stripped it down to the bare minimum now:

**routes/web.php**
No middleware. Just this line:
`Route::statamic('settings', 'settings2');`

**config/statamic/static-caching.php**
Just a single exclusion:
```
'exclude' => [
  '/settings'
],
```

**views/settings.blade.php**
A single line of html that won't update without clearing the static cache:
`<p>Settings 4</p>`

Something strange going on....

**Comment by stuartcusackie** [comment]
I have stumbled upon the cause. The forward slash is causing a problem:

**This doesn't work:**
```
'exclude' => [
  '/settings'
],
```

**This does work**
```
'exclude' => [
  'settings'
],
```

I thought I tried this previously but I guess not. So when defining custom routes I guess you have to leave out the leading slash?

**Comment by edalzell** [comment]
Let's see the `sites.php`

**Comment by stuartcusackie** [comment]
It's just the default config from using the CLI install (asides from the change of locale):

```
'sites' => [
  'default' => [
    'name' => config('app.name'),
    'locale' => 'en_IE',
    'url' => '/',
  ],
],
```

**Comment by stuartcusackie** [comment]
I thought that maybe this was a Windows slashes issue, but I can confirm that problem persists on a linux staging server. In fact it is worse on my staging server. Adding or removing slashes does not and my '/settings' page inputs are cached no matter what I do.

**Comment by jasonvarga** [comment]
This might be fixed in 3.3.37. Let me know once you upgrade and try it out.

**Comment by stuartcusackie** [comment]
It partially fixed things. Static caching now works fine on my local environment but my /settings page fields are still being cache on my staging server.

**Comment by stuartcusackie** [comment]
Nevermind! My app url was incorrectly using 'http' instead of 'https' on the staging server. Updating to 'https' fixed it.
