### ISSUE TITLE
Save & Redirect behavior

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#675]
Let's bring back the Save & ... behavior from v2. 

![image](https://user-images.githubusercontent.com/44739/64965724-840c2700-d86b-11e9-808d-464ab7760c7b.png)

**Comment by jesseleite** [comment]
From a Slack conversation, we were talking about being a bit more explicit with "Save & Continue Editing", to better explain what "Continue" means 🙂

**Comment by edalzell** [comment]
Please do this in terms as well

**Comment by studio1902** [comment]
I love that this is coming back. Much appreciated feature :-).
