### ISSUE TITLE
Asset thumbnails are not being cropped correctly

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#6751]
### Bug description

Newly uploaded asset thumbnails are being cropped incorrectly since updating to the latest version:

![Screenshot 2022-09-20 at 15 11 18](https://user-images.githubusercontent.com/126740/191280727-c1e7b587-94d3-4fcb-a7e4-089fafc5119e.png)

Previously uploaded assets are fine if the thumbnails have been cached.

It looks like this issue was introduced in 3.3.34, perhaps in https://github.com/statamic/cms/pull/6638 ?

In 3.3.33 they're fine:

![Screenshot 2022-09-20 at 15 00 17](https://user-images.githubusercontent.com/126740/191280619-2ae103bd-6604-4ad3-a50a-129410dc15c4.png)

### How to reproduce

Upload a new asset and check the thumbnail. Alternatively clear the image cache and do a force-refresh on the asset container page, newly generated thumbnails will be incorrect.

### Environment

```yaml
Statamic
Addons: 1
Antlers: runtime
Version: 3.3.36 Solo
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Judging by the description of that PR, it seems intentional. It's not cropping anymore, it's showing you the proper ratio of the image.

>  image ratios are now properly shown in landscape and portrait orientations

**Comment by jacksleight** [comment]
Ah OK. I think all the whitespace between the image and filename makes it looks a bit off. But it looks like the changes in https://github.com/statamic/cms/pull/6715 will fix that anyway.
