### ISSUE TITLE
Partial Slots not working as expected

### ISSUE THREAD

**Issue by ranuss** [statamic/cms#6784]
### Bug description

As soon i try to use slots, all other implementations of this specific partial stop to work. The slot itself is not working too.

### How to reproduce

The Partial:
`<div class="{{ if class }}{{ class }} {{ /if }}form-control{{ if floating_label }} -floating-label{{ /if }}{{ if inline }} -inline{{ /if }}">
  {{ if type == "select" }}
    <select
      class="input"
      type="select"
      id="{{ id or 'Undefined Id' }}"
      name="{{ name or id or 'Undefined Name or Id' }}"
      {{ if value }}value="{{ value }}"{{ /if }}
      autocomplete="{{ autocomplete or 'on' }}"
      {{ if required == 'true' }}required{{ /if }}
      onchange="this.setAttribute('value', this.value);"
    >
      {{ slot }}
    </select>
  {{ else }}
    <input
      class="input"
      type="{{ type or 'text' }}"
      id="{{ id or 'Undefined Id' }}"
      name="{{ name or id or 'Undefined Name or Id' }}"
      placeholder="{{ placeholder or label or 'Undefined Label or Placeholder' }}"
      {{ if value }}value="{{ value }}"{{ /if }}
      autocomplete="{{ autocomplete or 'on' }}"
      {{ if required == 'true' }}required{{ /if }}
    >
  {{ /if }}

  <label
    class="label"
    for="{{ id or 'Undefined Id' }}"
  >
    {{ label or "Undefined Label" }}
  </label>

  {{ if message }}
    <p class="message">
      {{ message }}
    </p>
  {{ /if }}
</div>`

How i use the partial inside a template:
`{{ partial:components/form_control
       class=""
       type="select"
       id="select-3"
       name="select-3"
       label="Form Control Select w/ Floating Label"
       placeholder="Choose an option"
       value=""
       message="Something is wrong"
       autocomplete="on"
       required="false"
       inline="false"
       floating_label="true"
     }}
       <option value="">Choose an option</option>
       <option value="dog">Dog</option>
       <option value="cat">Cat</option>
       <option value="hamster">Hamster</option>
       <option value="parrot">Parrot</option>
       <option value="spider">Spider</option>
       <option value="goldfish">Goldfish</option>
     {{ /partial:components/form_control }}`

### Environment

```yaml
Laravel Version: 9.26.1
PHP Version: 8.1.9
Composer Version: 2.2.7
Environment: local
Debug Mode: ENABLED
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by JohnathonKoster** [comment]
@ranuss  Would you be able to attach the partial file to this issue, as well as provide the Statamic and Antlers versions? The formatting here makes it difficult to see what is happening and I don't want to assume things, since the tiny details sometimes matter.

Thanks!

**Comment by ranuss** [comment]
@JohnathonKoster I am running Statamic 3.3.39. In the meantime i found out, that it is not possible to use {{ slot }} inside an if statement. Can you check on that?

**Comment by JohnathonKoster** [comment]
> @JohnathonKoster I am running Statamic 3.3.39. In the meantime i found out, that it is not possible to use {{ slot }} inside an if statement. Can you check on that?

I am not able to replicate the `{{ slot }}` inside an if-statement issue. Quick setup:

in `test.antlers.html`:
```antlers
{{ if categories || title }}
    {{ if true == true }}
        {{ if slot | length > 0 }}
            Content: {{ slot }}<br />
        {{ else }}
            No content!<br />
        {{ /if }}
    {{ /if }}
{{ /if }}
```

template file:
```antlers

{{ partial:test /}}

{{ partial:test }}
    {{ if true }}
        Conditional slot content.
    {{ /if }}
{{ /partial:test }}

{{ partial:test }}
Test2
{{ /partial:test }}


{{ partial:test }}
Test3
{{ /partial:test }}
```

Which produces the following output for me on the latest versions:

```
No content!
Content: Conditional slot content.
Content: Test2
Content: Test3
```

If you are able to create a repo that reproduces the issue(s), that would help a lot :)

**Comment by jackmcdade** [comment]
We can't seem to recreate any issues here and without any more info to go on I'll mark this as stale. Feel free to reopen with more info anytime!
