### ISSUE TITLE
Sometimes a new entry is appended to a structure

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#679]
New entries automatically get appended to a structure if you don't add it yourself.

However sometimes I notice - mostly after a `git pull` - even if the entry is added to the structure somewhere, it still gets appended, resulting in a duplicate entry.

**Comment by derekjones** [comment]
Anecdotally, if `php please stache:clear` is called *prior* to the `git pull` / `git checkout`, new entries don't appear to be re-added (duplicated) in structures.

**Comment by jackmcdade** [comment]
This also happens when the site path changes. For example, if i'm running a site in `~/Sites/test` and rename it to `~/Sites/testing`, voila. All the entries in a collection that aren't in the structure get appended to the bottom.

**Comment by jasonvarga** [comment]
Fixed by #1445 

We no longer magically add the entries to the YAML. Missing entries are just assumed to be at the top level.
