### ISSUE TITLE
Performance issues with 3.3.41

### ISSUE THREAD

**Issue by dominikradl** [statamic/cms#6821]
### Bug description

I updated Statamic from 3.3.12 to 3.3.41 and experienced a major peformance drop from ~1.04s to ~2.5s (that was a random subpage of the local installation).
As I also updated 2 addons, I downgraded them again which showed no effect. Then I updated Statamic one version after the other. Up until 3.3.40 everything is fine, in fact it's a bit faster (~890ms), but 3.3.41 slows it down.
Did anyone else experience such a slowdown?

### How to reproduce

I tried the same thing on another installation and couldn't reproduce it. One difference is that the problematic installation uses S3 as a filesystem, maybe it's related to https://github.com/statamic/cms/pull/6769?

### Environment

```yaml
Statamic 3.3.40 Pro
Laravel 8.83.25
PHP 7.4.30
edalzell/variable 1.0.4
mia/statamic-image-renderer 1.0.20
withcandour/aardvark-seo 2.0.28
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by leganz** [comment]
I can verify that it has to be an issue with 3.3.41. And i guess it has to be the glide/cache/asset-management or something.
I just updated from 3.3.40 to 3.3.41 and the drop of performance was massive. The asset manger/control center (~2500 files via s3) doesnt react at all.

We downgraded back to .40 (with the asset control issue) and dann back to .39 to resolve that issue.
I dont know if it helps but running the eloquent-driver-asset import takes much more time (for the same stuff). I can't see any exceptions in the logs


![CleanShot 2022-10-03 at 14 10 47@2x](https://user-images.githubusercontent.com/3373530/193573793-1b72ae26-21c2-413f-9c49-c581628b08c1.png)

**Comment by ericlbarnes** [comment]
I had the same issue. 

Running `php artisan statamic:stache:refresh` with 3024 article entries: 

* v3.3.41 - 4 minutes+
* v3.3.40 - around 30 seconds.

**Comment by jasonvarga** [comment]
Thanks guys, will take a look.

**Comment by jasonvarga** [comment]
@ericlbarnes are you using s3 too?

**Comment by ericlbarnes** [comment]
Yes, I am.

**Comment by jasonvarga** [comment]
Thanks. And yes it's because of #6769. May need to rethink that one.

Do any of you have the stache watcher enabled? (config/statamic/stache.php)

On the slow pages, are they also slow the second time you load that page?

**Comment by dominikradl** [comment]
No stache watcher enabled. Mine is slow on all subsequent requests.

**Comment by jasonvarga** [comment]
Eric, you're using static caching though? That doesn't count then. 😄

**Comment by ericlbarnes** [comment]
> Eric, you're using static caching though? That doesn't count then. 😄

Sorry, I should have mentioned this is on half caching. We are trying to move off full static caching.

**Comment by jasonvarga** [comment]
Still, even half measure means that the asset part wouldn't happen the second time.

**Comment by leganz** [comment]
We have set 
STATAMIC_STACHE_WATCHER=false
STATAMIC_STATIC_CACHING_STRATEGY=half

We use eloquent-driver and s3
We run the eloquent-import while deploying it via envoyer

**Comment by jasonvarga** [comment]
Thanks. I see the issue, working on a solution.

**Comment by nfragkos** [comment]
Hi issue still persists with v3.3.42 for me. 

Running `php please optimize:clear ; php please stache:warm` commands on 3.3.40 takes 8 seconds. On v3.3.42 takes 1min and 20 seconds which is a huge difference. I'm stuck on v3.3.40 for now.

**Comment by dominikradl** [comment]
Hi, thank you @jasonvarga for the super fast fix. Works for me. The test page from the original issue is now at ~890ms.

**Comment by dominikradl** [comment]
Sorry, @jasonvarga I think the problem persists for me too.
I just deployed it to staging (with production content) and the page timed out again.
