### ISSUE TITLE
Static caching invalidation not working for some pages

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#6859]
### Bug description

When saving an entry, sometimes the expected pages to invalidate aren't invalidated.

### How to reproduce

1. Visit a page that you expect to be invalid, but use a query string.
2. Then visit the same page without the query string.
3. Save an entry that expects the above page to be invalidated.
4. See that the page without the query string was not invalidated.

### Environment

```yaml
tbd
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

This is coming from a support request. Making the issue to keep track of it. Will add more details later.

I looked at the cache data from the production site and saw that the url manifest for statically cached urls contain duplicates.

```php
[
  'abc' => '/page',
  'def' => '/page',
  'ghi' => '/another',
]
```

When we go to invalidate by URL, the array gets flipped, which makes any duplicates get squashed.

```php
[
  '/page' => 'abc',
  '/another' => 'ghi',
]
```

Then probably the wrong key gets invalidated.

https://github.com/statamic/cms/blob/28154d331d2d4c48ed707cf0145fb83370d3384d/src/StaticCaching/Cachers/ApplicationCacher.php#L106

There shouldn't be duplicates in there. That's why I'm thinking it's due to the page being hit with a query string, but not being saved with the query string in the manifest.

**Comment by jsblair9** [comment]
Thanks Jason!
