### ISSUE TITLE
Text in Bard enclosed between two asterisks is displayed italic

### ISSUE THREAD

**Issue by doriengr** [statamic/cms#6863]
### Bug description

This problem occurs when text in a bard is enclosed in two asterisks - like when you want to italicize text in Markdown. However, it only occurs when italicization is selected as an option in the bard itself.

Since the texts of the websites are written in German, the asterisks are often used as gender asterisks for inclusive language usage. As a result, it often happens that text is incorrectly italicized.

As an example, the following text 

`»Lehrer*innen und Schüler*innen«`

would be misrepresented because _innen and Schüler_ are italicized.

![image](https://user-images.githubusercontent.com/57871803/195036424-03349e78-2fb6-4482-ae29-270dd08fb2c0.png)

This text is also saved accordingly as italicized text:
```
  -
    text:
      -
        type: paragraph
        content:
          -
            type: text
            text: Lehrer
          -
            type: text
            marks:
              -
                type: italic
            text: 'innen und Schüler'
          -
            type: text
            text: innen
    type: text
    enabled: true
```

Normally the complete text should not be italicized and the asterisks should be visible.

### How to reproduce

1. Create a Blueprint with a bard
2. Select `italic` in the toolbar of the bard
3. Create an entry and fill in a text with some asterisks
4. Save it

### Logs

```shell
No output in the logs for this bug.
```

### Environment

```yaml
Statamic: 3.3.43,
Laravel Version: 9.21.6
PHP Version: 8.1.10
Composer Version: 2.4.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
Working as expected.

You can disable the markdown shortcuts by editing the bard field in your blueprint.

![CleanShot 2022-10-11 at 20 42 46](https://user-images.githubusercontent.com/105211/195223462-f4bb1002-e9f0-448a-8d70-7afb91c34f79.png)

You should disable input rules, and probably also paste rules.
