### ISSUE TITLE
Error 500 when S3 asset container can't connect

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#6885]
### Bug description

Whenever you use an S3 asset container and for some reason it can't connect the site crashes with an error 500. In my case the buckets' SSL certificate expired. 

Ideally the site wouldn't crash but just not load the requested assets. Error handling could probably be improved in this situation.

### How to reproduce

Reproduce this by using a faulty S3 environment configuration. If you want please DM me to share a repo that has this all set up and I'd be happy to share a faulty configuration.

### Logs

```shell
Error executing "ListObjectsV2" on "https://cdn.studio1902.nl/assets?list-type=2&prefix=socialebenadering.nl%2Fvideos%2F"; AWS HTTP error: cURL error 6: Could not resolve host: cdn.studio1902.nl (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://cdn.studio1902.nl/assets?list-type=2&prefix=socialebenadering.nl%2Fvideos%2F
```

### Environment

```yaml
Statamic 3.3.35 Pro
Laravel 8.83.23
PHP 8.1.10
rias/statamic-color-swatches 2.0.5
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Personally I think the error is preferable.

If we somehow mask the error and just make assets disappear, then the next issues we'll be seeing are "my assets are broken" and other issues related to assets being filtered out unexpectedly.

For example, if we filtered out the assets, then you hit save on an entry without noticing that your asset fields were emptied, you'd be frustrated about losing that data.

By just fixing the S3 issue it's complaining about, everything else would fall into place.

**Comment by robdekort** [comment]
Hmmm. That is a very fair point. Especially your argument regarding save assets that currently don't seem to exist. It just feels so drastic that - say when your cloud provider is down - a site will completely fail. But maybe that's just the drawback of depending on another service.

**Comment by robdekort** [comment]
Only triggering an error on the CP _could_ be a best of both worlds solution, but I can imagine that's beyond the scope of what Statamic should take care of. No hard feelings when you close this issue :-).

**Comment by jasonvarga** [comment]
> No hard feelings when you close this issue

Okay I will close it then. 😬 ❤️ 

The time and effort to "fix" this and consider all the things I just brought up would far outweigh just addressing the S3 issue. Thanks for understanding!

**Comment by robdekort** [comment]
Yeah of course, your point of view is super fair. Another issue closed. Weekend Jason! ❤️
