### ISSUE TITLE
Title for the entry does not update after saving

### ISSUE THREAD

**Issue by wiebkevogel** [statamic/cms#6925]
### Bug description

When an entry is updated, the display title is not updated after saving. The title is updated only on the second save, after a reload or after the entry is published.

### How to reproduce

https://www.dropbox.com/s/9bu4ieh8avvkmx7/Bildschirmaufnahme%202022-10-20%20um%2011.37.34.mov?dl=0

### Environment

```yaml
Statamic 3.3.20 Pro
Laravel 8.83.7
PHP 8.1.11
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by zunnurs01** [comment]
@wiebkevogel Maybe can try update laravel version to 9.x

**Comment by edalzell** [comment]
> @wiebkevogel Maybe can try update laravel version to 9.x

I don't see how this is a laravel issue.

**Comment by wiebkevogel** [comment]
I'll close the ticket, could not reproduce it with the latest Statamic version. We had an older version for testing 😅
