### ISSUE TITLE
When we delete a Fieldset and that is used elsewhere we get an error

### ISSUE THREAD

**Issue by prateekshaweb** [statamic/cms#6941]
### Bug description

When we delete a Fieldset and that is used elsewhere we get an error

https://flareapp.io/share/17DZWQ6m#F104

### How to reproduce

Add a fieldset and include the same into the page blueprint then delete the fieldset from the fieldset mvc

go back to the page and you will see the error

### Environment

```yaml
linux
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by robdekort** [comment]
That seems like intended behaviour. When you delete a fieldset that's in use it'll trigger an error. Or maybe I've mistaken your issue?

**Comment by jasonvarga** [comment]
See https://github.com/statamic/ideas/issues/416
