### ISSUE TITLE
Template key not added to .md file

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#6951]
### Bug description

When I created a new blueprint added a new view then created a new page, the template key value is not written to the `content/collections/thepage.md` file. There is no `template: thepage `in the .md file.

Also my older version of my blueprint used the key inside of the` collections.md `file as template_field, when I create a new blueprint the key is now template:

My guess that there is a breaking change where the key to bind the template to the page used to be `'template_field'` and this has now changed to `'template'` as I can only make existing blueprints work with new pages, not new blueprint with new pages

### How to reproduce

Create a new Blueprint, Create a new view template, create an new page. The template: key is not added to the content/collections/pages/thepage.md or template_field is assigned as the key where it should be template. Changing the key in the .md file to template or adding the key binds the template view to the page

### Environment

```yaml
Laravel Sail, Docker
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Tried this on my existing site and also on a new statamic install

**Comment by jasonvarga** [comment]
A `template` key will only be saved to the entry if there is a `template` field in the blueprint.

**Comment by ottz0** [comment]
Sorry, there is a template field in the Blueprint

**Comment by jasonvarga** [comment]
Can you show a screenshot of the template field?

**Comment by ottz0** [comment]
So I've again tested this in a fresh install of Statamic. If the default value of `'template_field'` is used in my existing site, nothing is written to the .md file. In the fresh install of Statamic the `'template_field'` is written to the .md file but does not display the template in the browser.

If I add `template:viewPath` to the .md file in the existing site or rename `'template_field'` to just template in the new Statamic then it works correctly.

![Screen Shot 2022-10-26 at 9 13 16 am](https://user-images.githubusercontent.com/7971800/197894640-13da7fb3-26e4-41c2-a86f-2195573d2a33.png)
![Screen Shot 2022-10-26 at 9 14 37 am](https://user-images.githubusercontent.com/7971800/197894656-e6b58a66-0600-4c81-ba22-178177506474.png)
![Screen Shot 2022-10-26 at 9 15 26 am](https://user-images.githubusercontent.com/7971800/197894697-a8a84252-4d87-4da9-aefb-b069c4ca0d43.png)
![Screen Shot 2022-10-26 at 9 08 25 am](https://user-images.githubusercontent.com/7971800/197894793-4ae5cae9-54f1-41f5-8904-bfe3826bfe24.png)

**Comment by jasonvarga** [comment]
Templates will only be used for the entry if you name the field `template`.
