### ISSUE TITLE
Readonly Assets View and Download Buttons (AssetRow component)

### ISSUE THREAD

**Issue by reaboivictor** [statamic/cms#6952]
### Bug description

There are no show or download buttons for read-only assets displayed as a list.

![image](https://user-images.githubusercontent.com/69897526/197768147-dcc89753-3ef8-41ab-892c-2f3fb14a6dcc.png)

### How to reproduce

1. Create a read-only asset field
2. Set display mode to List

![image](https://user-images.githubusercontent.com/69897526/197768536-de33f2ec-be63-45c6-ac9d-b180d8990bff.png)

### Environment

```yaml
Statamic 3.3.48
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Semi-related: #6501
