### ISSUE TITLE
Rest api not working

### ISSUE THREAD

**Issue by addgod** [statamic/cms#6954]
### Bug description

Calling the rest api, with a specific resource throws an error on the content replacer.

### How to reproduce

Call and direct entry on a collection.

```
cms/api/collections/events/entries/7a6ed47e-ee85-4c54-84e2-69976d54af86
```

### Logs

```shell
Statamic\\StaticCaching\\Replacers\\NoCacheReplacer::replaceInCachedResponse(): Argument #1 ($response) must be of type Illuminate\\Http\\Response, Illuminate\\Http\\JsonResponse given, called in /app/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php on line 71
```

### Environment

```
php 8.1, laravel 9, latest statamic.
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by duncanmcclean** [comment]
Do you have static caching enabled?

**Comment by jasonvarga** [comment]
Can you edit `latest statamic` in your issue to the actual version?

**Comment by jasonvarga** [comment]
Have you changed anything regarding routing? The static caching middleware causing that error isn't used on api routes.

**Comment by addgod** [comment]
Nevermind, it is a routing issue, when you have it running with the nova, so in that the cms api has to be excluded aswell.

So in the where segments the api routes have to be excluded aswell.
```
Route::any('/{segments?}', [\Statamic\Http\Controllers\FrontendController::class, 'index'])
    ->where('segments', '(?!nova|admin|cp|telescope|horizon|img).*')
    ->name('statamic.site')
;
```
