### ISSUE TITLE
Struggling with awful performances

### ISSUE THREAD

**Issue by axeloz** [statamic/cms#6999]
### Bug description

Hello, 

Using Statamic 3.3.*, I face awful performances on a yet-to-be-released website. No traffic at all on it. 
Stache watcher is disabled. Cache tags are enabled. I tried so many things to understand where is the bottleneck. 
- I tried `stach:refresh`, `assets:generate-presets`, `assets:meta`. Image cache is On
- If I set the cache strategy to half, the pages are loading fast once cached a first time. When running `static:warm`, 70% of requests fail (timeout). For the 30% left, when I visit the page, it is still long to show as if the static cache wasn't properly generated. The next visits on the same page are very fast. 
- I tried to add cache tags on consuming peaces of code. No luck. 
- I try to reverse-engineer the code including Statamic. When I empty the `layout.antlers.html` template, the page is blank (normal so far) but still lang to display. 
- If I issue a `stache:doctor`, no error, it seems happy

In `vendor/statamic/cms/src/Providers/AppServiceProvider.php` line 122, when I comment the line `->setRepository('entry', \Statamic\Contracts\Entries\EntryRepository::class)` : header, main and footer blocks are showing up (main is empty obvisouly) but I can navigate with the header menu. Lightning fast (which makes pretty much sense are all entries repository is ignored). 

So I keep digging into Statamic. 

On my local environment, one page takes 5s to load. 
On my preprod environment (SSD dedicated server doing pretty much nothing): 15 to 30s (when it doesn't timeout). 
I'm also unable to use any debugbar. The laravel debugbar adds 5s or more at load time. And quite often, it crashed my browser (Brave). Safari is more stable in this case. I think there is so much content inside the debugbar that my browser just gives up (3500 events, 1450 files, 1967 caches, 50 messages, ...). I tried Telescope but there is a compatibility issue. I also tried Clockwork but load is bad. Plus Clockwork breaks my website when authenticated.
I also tried xdebug but I always get a max_execution_time error.

If you have any idea, that'd be nice. 
Thanks

### How to reproduce

I would love to know

### Environment

```yaml
Statamic 3.3.49 Pro
Laravel 8.83.25
PHP 8.1.11
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jackmcdade** [comment]
Hey there, we already have the open support ticket with you, so let's continue working through this there until we know for sure whether there's actually a bug or if there's some server/config/dependency issue. Hang in there!

**Comment by axeloz** [comment]
@jackmcdade sorry man, I didn't realize you guys were still actively working on this issue. 
Thanks
