### ISSUE TITLE
Drag and drop asset upload goes to base folder

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#7018]
### Bug description

Just a minor issue here. Dragging and dropping an asset into an asset folder doesn't work as I would expect. The file gets uploaded to the top level directory and not the folder that is currently open.

I opened a [similar issue](https://github.com/statamic/cms/issues/5893) a few months ago - changing folder while an upload queue is processing makes the queued files go to wrong folder. Just in case two birds can be killed with one stone here.

Thanks.

### How to reproduce

drag and drop a file into a folder in an asset container.

### Environment

```yaml
Version: 3.3.51 PRO
Laravel Version: 9.24.0
PHP Version: 8.1.11
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
Are you still running into this on the latest version? I'm unable to reproduce myself - dragged files go into the current folder, not the base folder.

**Comment by stuartcusackie** [comment]
I just tested two sites.
Statamic 3.4.11: asset goes to base folder
Statamic 4.2.0: asset goes to correct folder 

So it seems version 4 has fixed it. Thanks for looking into this.
