### ISSUE TITLE
Massive asset container (10000+ assets) unusably slow for non super users

### ISSUE THREAD

**Issue by Daynnnnn** [statamic/cms#7027]
### Bug description

AssetFolderPolicy checks take over a minute (not sure un exact figure due to 504) with massive asset containers due to the below code:

```
return $assetFolder
    ->assets(true)
    ->reject(fn ($asset) => $user->can('delete', $asset))
    ->isEmpty();
```

### How to reproduce

Create an asset container with 10000+ assets, try and load the asset container page without being a super user.

### Environment

```yaml
Laravel: v9.34.0
Statamic: v3.3.53
Asset container driver: S3
```

```
STATAMIC_LICENSE_KEY=
STATAMIC_STACHE_WATCHER=false
STATAMIC_STATIC_CACHING_STRATEGY=null
STATAMIC_REVISIONS_ENABLED=false
STATAMIC_GRAPHQL_ENABLED=false
STATAMIC_API_ENABLED=false
STATAMIC_GIT_ENABLED=false
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Do you have the stache watcher enabled? Disable it.

**Comment by Daynnnnn** [comment]
<img width="987" alt="Screenshot 2022-11-09 at 14 47 26" src="https://user-images.githubusercontent.com/25618897/200861468-6bbdfd5d-a393-4cc8-a992-1b198f17db00.png">
<img width="499" alt="Screenshot 2022-11-09 at 14 47 31" src="https://user-images.githubusercontent.com/25618897/200861455-d9ced2f9-1d9c-4132-ae74-6ca28959ced6.png">

**Comment by jasonvarga** [comment]
Ah yeah sorry it's the "without super user" part I missed.

**Comment by jasonvarga** [comment]
The asset folder policy also checks all the assets because it's possible for someone to customize the asset's delete method. (Same for rename and move)

Since you are not customizing the asset policy, you can remove those checks.

In your app service provider's boot method, rebind the policy to a custom class:

```php
$this->app->bind(
    \Statamic\Policies\AssetFolderPolicy::class,
    \App\AssetFolderPolicy::class
);
```

```php
<?php

namespace App;

use Statamic\Facades\User;
use Statamic\Policies\AssetFolderPolicy as Policy;

class AssetFolderPolicy extends Policy
{
    public function move($user, $assetFolder)
    {
        $user = User::fromUser($user);

        if (! $user->hasPermission("move {$assetFolder->container()->handle()} assets")) {
            return false;
        }
    }

    public function rename($user, $assetFolder)
    {
        $user = User::fromUser($user);

        if (! $user->hasPermission("rename {$assetFolder->container()->handle()} assets")) {
            return false;
        }
    }

    public function delete($user, $assetFolder)
    {
        $user = User::fromUser($user);

        if (! $user->hasPermission("delete {$assetFolder->container()->handle()} assets")) {
            return false;
        }
    }
}
```

**Comment by Daynnnnn** [comment]
Thanks! We've added something to the same extent for now, just raising so it's on the radar :)

**Comment by jasonvarga** [comment]
We're leaving the overriding of the policy the solution for now.

We prefer the permissions to be accurate for the majority, then if you're dealing with scale, you can tweak things as needed.
