### ISSUE TITLE
Mangled static cache resulting in broken html

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7033]
### Bug description

I've seen this odd issue for a while now. It only happens on one of my sites. This site uses full static caching. Let me try to explain. The client makes edits via the CP and every now and then this results in broken pages. 

**Broken page**
See the SVG characters and repeated address in the wrong spot (bottom of the page).
<img width="1426" alt="Screenshot_2022-11-10_at_09 15 00" src="https://user-images.githubusercontent.com/69107412/201046878-01e9fcd4-4ac1-44fa-97da-3ca9a9a5baab.png">

**Source**
Might not be relevant. But it turns out this is part of the instagram icon.
<img width="2372" alt="Screenshot_2022-11-10_at_09 17 46" src="https://user-images.githubusercontent.com/69107412/201047093-e278f526-cf72-4766-a8fd-c1b1e86537e0.png">

**Code responsible for that icon**
<img width="1323" alt="Screenshot_2022-11-10_at_09 18 16" src="https://user-images.githubusercontent.com/69107412/201047155-d70f7440-3dc0-4d21-9c02-674da23fe55d.png">

**Broken rendered result**
<img width="679" alt="Screenshot_2022-11-10_at_09 19 41" src="https://user-images.githubusercontent.com/69107412/201047263-68a26919-ccce-47e6-8299-a3c0548d0c43.png">

**Fix**
I can fix this by clearing the static cache. It then looks good until it breaks again:
<img width="1050" alt="Screenshot_2022-11-10_at_09 19 59" src="https://user-images.githubusercontent.com/69107412/201047354-e0a49b04-901b-47e5-82b6-f66f08870d4e.png">

Look, all neat and nice:
<img width="1426" alt="Screenshot_2022-11-10_at_09 21 39" src="https://user-images.githubusercontent.com/69107412/201047417-1f4aebf2-289f-431c-a49a-5c1fe4b77449.png">

**Broken  HTML file**
This is the cache file in a broken state:
[ca1e6a6eb70d8d75.html.zip](https://github.com/statamic/cms/files/9979118/ca1e6a6eb70d8d75.html.zip)

**Extra information**
Even with cache available this is what the cache utility look like (0 pages in cache):
<img width="888" alt="Screenshot_2022-11-10_at_09 23 57" src="https://user-images.githubusercontent.com/69107412/201047645-12abef09-3c31-41ce-9327-2b8b0ae372db.png">

You can see there's definitely cache stuff:
<img width="1345" alt="Screenshot_2022-11-10_at_09 24 25" src="https://user-images.githubusercontent.com/69107412/201047735-55c5a765-11cb-455e-a279-0afa701b6395.png">

### How to reproduce

It's very hard to reproduce. I couldn't find clear steps (yet). DM me for repo access.

### Environment

```yaml
Statamic 3.3.36 Pro
Laravel 8.83.23
PHP 8.1.10
No addons installed
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by robdekort** [comment]
For now I've disabled the full static cache and enabled half measure to see if that still triggers the issue.

**Comment by robdekort** [comment]
I've re-enabled full static caching and added a timestring to the HTML for debugging purposes:
<img width="374" alt="Screenshot 2022-11-10 at 10 24 50" src="https://user-images.githubusercontent.com/69107412/201052023-8001b288-cd80-42a7-9eaf-e31fa8a03f63.png">

Not because I'm brilliant. It was @JohnathonKoster who suspects something.

**Comment by jasonvarga** [comment]
In `config/statamic/static_caching.php`, try increasing `lock_hold_length` to `1`.

**Comment by robdekort** [comment]
Done! Curious. What does that do. I can't seem to find it in the docs.

**Comment by robdekort** [comment]
Unfortunately this didn't fix the issue. I just ran into it again.

<img width="1500" alt="Screenshot 2022-11-12 at 16 44 40" src="https://user-images.githubusercontent.com/69107412/201482273-75092fbe-d786-411a-a6fe-4bcecf414578.png">

**Comment by robdekort** [comment]
Client informed me it just happened again. I managed to download the [generated cache file](https://github.com/statamic/cms/files/10218589/cache_file.html.zip) and you can see the string "Generated on: TIMESTAMP" with two different timestamps in there.

**Comment by jeroenimpres** [comment]
@robdekort Sorry to have no solution for you, but I can tell you what the `lock_hold_length` does. 
It `sleeps()` for $value seconds before closing the file, to prevent other files from writing to it at the same time. I'm not sure if this actually fixes anything, because of course it will also sleep for another request

**Comment by robdekort** [comment]
Hey thanks for the explanation @jeroenimpres. So after writing to the html file it locks it? I can confirm a `lock_hold_length` of `1` doesn't help. Are you running into similar issues?

**Comment by jeroenimpres** [comment]
I think it might help some cases, I was a bit to quick to judge it. It 'locks' the file because it was opened by PHP, and before any writing is done it checks with [flock()](https://www.php.net/manual/en/function.flock.php) if there is a lock, if there it, it will not write anything. So in your case it's probably mangled before the actual writing is done.

I do not run into this myself, I was just browsing open tickets with the Cache-tag, looking for a way to not (static) cache pages when the visitor is also logged into the CP (because it now caches the peak toolbar haha).

**Comment by robdekort** [comment]
(Side note: If you use the toolbar in production you could consider wrapping it with the `{{ nocache }}` tag).

**Comment by robdekort** [comment]
Hey @jasonvarga. Sorry to ping you but would you willing to look into another workaround? This keeps happening and I can't solve it.

**Comment by robdekort** [comment]
Happening on my own site now as well. Can't pinpoint when or how.
<img width="1458" alt="Screenshot 2023-02-25 at 14 51 59" src="https://user-images.githubusercontent.com/69107412/221360697-2a23483c-32b9-4665-8310-c7635f85af81.png">

**Comment by aerni** [comment]
I've been running into this on my own website as well. Every now and then, there's a broken piece of SVG displayed at the bottom of the page. Exactly how Rob is describing it. The site uses full static caching too.

**Comment by robdekort** [comment]
Sorry to hear that. It's not always svgs in my case. In my latest screenshot it appears to be an html comment. 

John Koster is convinced its a cache race condition.

**Comment by elmanvebs** [comment]
I had the same issue, but only with the multi-site. To fix it, I had to delete the affected page, deploy the changes (including app cache/static clean up), and then manually restore the page. After completing these steps, the page rendered properly. And I am not sure what caused the issue.

**Comment by robdekort** [comment]
I'm afraid I don't know.

**Comment by aerni** [comment]
I haven't tested with half measure. I can only confirm the issue with full measure.

**Comment by jasonvarga** [comment]
How frequently does it happen?

**Comment by jasonvarga** [comment]
Do you know if it's mangling the pages around the time they are being edited by a client? (I know that may be hard to answer.)

**Comment by robdekort** [comment]
It does seem like that yep!

**Comment by jasonvarga** [comment]
New theory is a race condition where the url is invalidated and the page is hit on the frontend at the same time.

**Comment by robdekort** [comment]
Makes sense. And it could very well be the client checking changes.

**Comment by robdekort** [comment]
Is there an update on this one or is on hold?

**Comment by jasonvarga** [comment]
#7722 is fixing this. Would you be able to try this PR using a Composer patch?

**Comment by robdekort** [comment]
Thanks for your work on this Jason. I just installed the composer patch but I get the following error upon visiting the site:
<img width="1515" alt="Screenshot 2023-03-18 at 14 53 34" src="https://user-images.githubusercontent.com/69107412/226110330-826b68cc-f4e7-4975-a4c0-c22a7ebb90a6.png">

**Comment by jasonvarga** [comment]
You shouldn't get that error if you have static caching enabled.

**Comment by robdekort** [comment]
Figures! Just pushed to production where static caching is on.

**Comment by jasonvarga** [comment]
I've fixed it anyway if you want to update.

**Comment by robdekort** [comment]
Cool. Thanks. Done!

**Comment by jasonvarga** [comment]
I'll consider 2 weeks of silence a win.

**Comment by robdekort** [comment]
Hahaha. I'll find you if it breaks again ;-).

**Comment by robdekort** [comment]
I'm afraid I've seen this happen again, on two separate sites.

**Comment by robdekort** [comment]
<img width="1355" alt="Screenshot 2024-09-23 at 20 25 58" src="https://github.com/user-attachments/assets/30cc1d88-597e-4742-b73c-047f23a475a0">
Here's an example.

**Comment by duncanmcclean** [comment]
@robdekort This issue is pretty old at this point. Are you able to open a new issue instead?

**Comment by robdekort** [comment]
Seriously?
