### ISSUE TITLE
`nocache`: Memory usage gets bigger and bigger

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#7039]
### Bug description

~~Using~~ `logged_in` ~~condition inside~~ `nocache` ~~tags causes memory usage to get bigger and bigger~~

`nocache` tags files (`storage/framework/views/nocache`) are created on every page request and get never cleaned.

### How to reproduce

Add a collection with entries.

```
{{ collection from="your_collection" }}
	{{ title|wrap:h2 }}
	{{ nocache }}
		{{ if logged_in }}Logged in{{ else }}Logged out{{ /if }}
	{{ /nocache }}
{{ /collection }}
```

![Bildschirm­foto 2022-11-11 um 16 54 10](https://user-images.githubusercontent.com/6337411/201379474-56db167b-0b45-4875-b852-16127551576a.png)
![Bildschirm­foto 2022-11-11 um 16 54 20](https://user-images.githubusercontent.com/6337411/201379482-d5bf3b71-404f-4ddc-ba6e-7c2e7c7c4462.png)
![Bildschirm­foto 2022-11-11 um 16 54 30](https://user-images.githubusercontent.com/6337411/201379489-d3c03d2e-5f73-4bfb-b8c5-b835883649ca.png)
![Bildschirm­foto 2022-11-11 um 16 54 46](https://user-images.githubusercontent.com/6337411/201379497-d960e9bb-682c-44e0-8bb1-6f35ca9e9d62.png)
![Bildschirm­foto 2022-11-11 um 16 54 57](https://user-images.githubusercontent.com/6337411/201379502-13199ffb-4f54-482e-8ba6-3a041b5022fb.png)

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.39.0
PHP Version: 8.0.16
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by j3ll3yfi5h** [comment]
Hm. This seems to be a general issue with all nocache tags, the `storage/framework/views/nocache` gets bigger and bigger.

**Comment by mikemartin** [comment]
We had 2 site outages over the weekend after introducing the {{nocache}} tag on a half static cached site.
```
Environment
Application Name: ShiftCare
Laravel Version: 9.39.0
PHP Version: 8.0.21
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: shiftcare.test
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 9
Antlers: runtime
Version: 3.3.54 PRO

Statamic Addons
aerni/advanced-seo: 1.3.3
doublethreedigital/duplicator: 2.3.3
mattrothenberg/statamic-mapbox-address: 0.7.2
mikemartin/helpscout-beacon: 1.0.2
reachweb/multisite-propagator: 1.0.0
rias/statamic-color-swatches: 2.1.7
rias/statamic-redirect: 2.5.0
spatie/statamic-responsive-images: 2.14.4
webographen/statamic-widget-continue-editing: 1.0.1
```

**Comment by j3ll3yfi5h** [comment]
@arthurperton after about 10 refreshes it says:

```
[2022-11-16 08:01:52] local.ERROR: Allowed memory size of 536870912 bytes exhausted (tried to allocate 79695872 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 536870912 bytes exhausted (tried to allocate 79695872 bytes) at /.../.../.../.../vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:77)
[stacktrace]
#0 {main}
"} 
```

**Comment by j3ll3yfi5h** [comment]
layout.antlers.html
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ title }}</title>
</head>
<body>
	{{ template_content }}
</body>
</html>
```

default.antlers.html
```
{{ title|wrap:h1 }}

{{ collection from="jobs" }}
	{{ title|wrap:h2 }}
	{{ nocache }}
		{{ if logged_in }}Logged in{{ else }}Logged out{{ /if }}
	{{ /nocache }}
{{ /collection }}
```

**Comment by jasonvarga** [comment]
Thanks!

**Comment by marijoo** [comment]
Anything new on this one? This needs to be addressed as it makes Static Caching unusable more or less.

**Comment by marijoo** [comment]
Nothing? We are running a relatively small site (about) 100-200 pages in total and the load is insane. The site is unusable without static caching since load times explode to 10 seconds or so.

With full measure caching everything is fine – besides the fact that warming the static cache with `static:warm` takes a huuuuge amount of memory and CPU and a lot of time – until everything breaks after a few days of usage and `nocache` tags aren’t replaced anymore.

**Comment by jasonvarga** [comment]
> nocache tags files (storage/framework/views/nocache) are created on every page request and get never cleaned.

Do more get created _on every request_ or only the first request for a page?

**Comment by j3ll3yfi5h** [comment]
> > nocache tags files (storage/framework/views/nocache) are created on every page request and get never cleaned.
> 
> Do more get created _on every request_ or only the first request for a page?

@jasonvarga 
_on every request_

**Comment by jasonvarga** [comment]
Do you even have static caching enabled?

**Comment by marijoo** [comment]
We do have static caching enabled and after a few days of usage the `nocache` directory has an insane amount of files:

```sh
ls -la storage/framework/views/nocache/ | wc -l
521019
```

Again the `nocache` tags were not replaced anymore. I don’t know if this is a coincidence. After manually deleting everything from `storage/framework/views/nocache/` the `nocache` tags stayed empty. After running `php please static:clear && php please static:warm` everything is back to normal again.

Here is the info from `artisan about`:

```
  Environment ............................................................  
  Laravel Version ................................................. 9.52.6  
  PHP Version ...................................................... 8.2.3  
  Composer Version ................................................. 2.5.4  
  Environment ................................................. production  
  Debug Mode ......................................................... OFF  
  Maintenance Mode ................................................... OFF  

  Cache ..................................................................  
  Config .......................................................... CACHED  
  Events .......................................................... CACHED  
  Routes .......................................................... CACHED  
  Views ........................................................... CACHED  

  Drivers ................................................................  
  Broadcasting ....................................................... log  
  Cache ......................................................... statamic  
  Database ......................................................... mysql  
  Logs ............................................................. daily  
  Mail .............................................................. smtp  
  Queue ............................................................. sync  
  Session ........................................................... file  

  Localization ...........................................................  
  Installed ....................................................... de, en  
  LaravelLang\Attributes\Plugin ................................... v2.3.3  
  LaravelLang\Lang\Plugin ........................................ 12.21.1  
  Protected Locales ............................................... de, en  
  Publisher Version .............................................. v14.6.4  

  Statamic ...............................................................  
  Addons ............................................................... 1  
  Antlers ........................................................ runtime  
  Stache Watcher ................................................ Disabled  
  Static Caching .................................................... full  
  Version ...................................................... 3.4.7 PRO  

  Statamic Addons ........................................................  
  thoughtco/statamic-blurhash ...................................... 1.0.4
```

**Comment by marijoo** [comment]
Maybe this is another topic, but wouldn’t it be nice to have the possibility to specify a `key` that would be used instead of the auto-generated one if passed? In our case there is no need to even have 300 different versions of the `nocache` content. It is the same across all pages, so we could just pass the same key in all files:

```antlers
{{ nocache key="announcements" }}
    // output dynamic announcements here
{{ /nocache }}
```

**Comment by jasonvarga** [comment]
> We do have static caching enabled

I was directing the question to @j3ll3yfi5h. Since more stuff is generated on every request, it seems like maybe Static Caching wasn't enabled at all. Even since you say you can sit there and hit refresh and watch the files grow. If the page was cached, there shouldn't have been another `nocache` tag for Statamic to parse and create a new file.

> Maybe this is another topic

This is sorta the exact topic. 😄 The reason so many files are being generated is because keys are unique for each instance of the nocache tag. We give each region a unique ID so that if you're in a loop, we can be sure that instance of the loop gets its proper data. ([See commit](https://github.com/statamic/cms/pull/6231/commits/59b896c6b4ecf19622df6f3a27bf4e22ca9fd24b)) A separate file is generated even if it's identical to another.

It should be possible to re-use the files, but store the data uniquely.

But that would only solve the issue of there being lots of temporary view files. I'm not 100% sure the number of files is the actual issue.

I wonder if the array of cached URLs ends up being the problem. Maybe if the URLs are being hit with different variations of query parameters.

Would you be able to run `php artisan tinker` and then `\Illuminate\Support\Facades\Cache::get('nocache::urls');`?
How many items are in the returned array?

**Comment by jasonvarga** [comment]
That's probably it, then. 😄 

Can you look at the values in there? Are there are duplicates?

**Comment by j3ll3yfi5h** [comment]
> Do you even have static caching enabled?

@jasonvarga Hm, I hope I had. But without enabling it, it definitely happens...😅

I'm not sure anymore, if I missed this with testing, sorry!

**Comment by j3ll3yfi5h** [comment]
@jasonvarga Am I right, that the nocache folder will never be empty after any artisan command? It gets bigger again, because after clearing the cache, new files are generated?

**Comment by jasonvarga** [comment]
There's currently nothing that would delete files from the nocache directory, so that'll just keep growing.

We should add some garbage collection to that, but I'm not convinced the number of files in that directory is the issue.

**Comment by marijoo** [comment]
> Can you look at the values in there? Are there are duplicates?

Absolutely, I checked some of the files and they contain recurring contents. There are `6879` files now and by the filesize I can determine that there are only 5 different contents repeating over and over again. I attached a screenshot.

> We should add some garbage collection to that, but I'm not convinced the number of files in that directory is the issue.

A million redundant files is a problem for sure. As described above deleting these files and rebuilding the static cache fixes the problems for a few days.

**Comment by marijoo** [comment]
Sorry, here is the screenshot.

Just in case: There are `9672` files now and `count(\Illuminate\Support\Facades\Cache::get('nocache::urls'))` gives a count of `197`. Let me know if I can help with additional information.

<img width="955" alt="nocache" src="https://user-images.githubusercontent.com/360736/234885590-6b48d5f1-7ae7-4803-acd7-1540a704d077.png">

**Comment by jasonvarga** [comment]
Oh I thought it was going to be a screenshot of the cached array. I believe you that there are lots of files.

**Comment by marijoo** [comment]
Here is a screenshot of a part of the array. The array seems to be blown up by non-existing URLs, which is [expected behavior](https://github.com/statamic/cms/pull/7687) afaik – even though this seems to be some kind of brute force vector if this is what messes up the site.

The pages like `/`, `/events` and `/parkplan` all exist, but the query string versions don’t and I wouldn’t want them cached if this was configurable.

I cannot tell if the array had an enormous size when the site broke down the last time, but I will check next time.

![nocache_array](https://user-images.githubusercontent.com/360736/234892341-065bfbd0-9e0e-4e1f-91db-fa1594927dbf.jpg)

**Comment by marijoo** [comment]
Little update — 5 more days down the road: `82700` files, `155` array records. We now delete the folder contents on deploy and on a daily basis.

**Comment by johncarter-** [comment]
`public_html/storage/framework/views/nocache: 3656487` 🤯

**Comment by seamofreality** [comment]
I'd be very interested to learn about the underlying issue here since we've run into the same problem.

From what I've read here I'd also argue, that the amount of files doesn't seem to be a limiting factor.
Our nocache directory is currently `491M` with `123335` files within. 
Most files are the same size and there's no surprisingly large files there. 

Our memory exhaustion error occurs just like described above, in the file FileStore.php, Line 77 - see [file on GitHub](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Cache/FileStore.php#L77). 
That'd make me think whatever the `$value` is has become a problem for serialization? 

The issue occured after the website has been live for a couple of weeks. We had to clear the cache via `php artisan cache:clear` which got rid of the `Allowed memory size exhausted` error. Then it was another couple of weeks before it reoccured. 

We're using a nocache partial on some sub pages and in the navigation part of our website, which is included on every page of the website. The problem occured with caching completely disabled at first. Now we've enabled 'half' caching and are waiting to see what happens. Haven't been able to trigger the error. Not very much fun to anticipate the customer's website going down, tho. 🫣

**Comment by simonolog** [comment]
We ran into this issue big time in a recent project. As there is a good amount of traffic on that page, the server response time got worse and worse within _minutes_. 

As observed by others, the cause of the problem doesn't look to be the amount of files in the `storage/framework/views/nocache`, but rather the content of the `nocache::session.{md5_page_url}` cache object. As described by Jason above, every nocache region gets it's unique id. For every region id there is a corresponding file in the `views` folder, but _also_ an array value in the cache, that contains rendered data (?):

![Screenshot_2023-10-12_13-29-17](https://github.com/statamic/cms/assets/7941370/ea8ab64d-252a-46af-8d79-cc8f90d3cbd1)

Same as with the files, this array never gets cleaned and with _every request_ to a page, data for every `nocache` region on the page is added to the array. The bigger the array, the longer it takes the application to load a key. Within a day of the application running, we ran into a "memory limit exhausted" error.

What currently makes the application work fine is running this command every five minutes:

```php 
collect(Cache::get('nocache::urls', []))->each(function ($url) {
    Cache::forget('nocache::session.' . md5($url));
});
```

This effectively clears the whole `nocache` session cache. 

Obviously we would prefer to have a more appropriate solution than this.

**Comment by marijoo** [comment]
> Maybe this is another topic, but wouldn’t it be nice to have the possibility to specify a `key` that would be used instead of the auto-generated one if passed? In our case there is no need to even have 300 different versions of the `nocache` content. It is the same across all pages, so we could just pass the same key in all files:
> 
> 
> 
> ```antlers
> 
> {{ nocache key="announcements" }}
> 
>     // output dynamic announcements here
> 
> {{ /nocache }}
> 
> ```

The proposal I made a while back would not help with the problem that the cache never gets cleared but it could prevent hundreds or thousands of redundant copies in a lot of cases and give control to developers to summarize regions.

**Comment by stanbridge-wcorrea** [comment]
I'm running out of memory and I think it's related to this issue. I'm using the full measure caching and I have just one URL that is excluded from the Static cache, when I hit that URL I run into that issue. The error seems to be in FileStore.php, Line 77 - see [file on GitHub](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Cache/FileStore.php#L77). 

The funny thing is ... I'm getting this error after more or less 13 hours after I clear the cache. 

The solution for me was to set up a cron to clear the cache again every 12 hours. 

If I included all URLS to static cache, it doesn't run into issues.

**Comment by stanbridge-wcorrea** [comment]
> We ran into this issue big time in a recent project. There is a good amount of traffic on that page and the server response time got worse and worse within _minutes_.
> 
> As observed by others, the cause of the problem doesn't look to be the amount of files in the `storage/framework/views/nocache`, but rather the content of the `nocache::session.{md5_page_url}` cache object. As described by Jason above, every nocache region gets it's unique id. For every region id there is a corresponding file in the `views` folder, but _also_ an array value in the cache, that contains rendered data (?):
> 
> ![Screenshot_2023-10-12_13-29-17](https://user-images.githubusercontent.com/7941370/274585069-ea8ab64d-252a-46af-8d79-cc8f90d3cbd1.png)
> 
> Same as with the files, this array never gets cleaned and with _every request_ to a page, data for every `nocache` region on the page is added to the array. The bigger the array, the longer it takes the application to load a key. Within a day of the application running, we ran into a "memory limit exhausted" error.
> 
> What currently makes the application work fine is running this command every five minutes:
> 
> ```
> collect(Cache::get('nocache::urls', []))->each(function ($url) {
>     Cache::forget('nocache::session.' . md5($url));
> });
> ```
> 
> This effectively clears the whole `nocache` session cache.
> 
> Obviously we would prefer to have a more appropriate solution than this.

Are you using full measure static cache? I tried to run your code for clearing the nocache cache, but that gives me errors when loading those tags.

**Comment by stanbridge-wcorrea** [comment]
> > Are you using full measure static cache? I tried to run your code for clearing the nocache cache, but that gives me errors when loading those tags.
> 
> Sorry, I didn't mention that. We're using half measure caching.
> 
> For full measure caching it seems fine to create new files and add data to the `nocache::session` array on every request, as this should only happen on a "first" request, as the corresponding html file is also generated on that request and the next request wouldn't go through the application. I assume that if you kill the array (and therefore all stored region ids), the generated html doesn't have a matching region id to render. However, if you have pages excluded from static caching, the problem still exists but you _can't_ resolve it via the described way.
> 
> Makes the problem even more urgent, it seems.

Yes, as you mentioned when you have pages excluded from static cache and those pages use the {{ nocache }} tag, those pages will run out of memory at some point, however you can use the code that you mentioned cleaning the nocache::session cache when you visit those pages. 

I have fixed (workaround) creating a custom tag that clears the nocache::session only for excluded pages, but that fixes the issue for me that is using the static cache full measure, not sure for those using half measure, I think it's worse. 

I'm not sure if I should open a new issue about this, but I have detailed steps on how to reproduce it.

**Comment by jasonvarga** [comment]
To anyone that was following along with this, we fixed it in #8956 but it has shown to be problematic.

The automatic performance improvements will be reverted in the next release. You can still use them but you need to opt into them. See details in #9124.

**Comment by jeroenimpres** [comment]
Thanks for commenting it here @jasonvarga I like the solution to have it be opt in

**Comment by ajcsilva** [comment]
Hi, I was wondering the the support for keys on the `nocache` tag were going to be implemented? I'm still dealing with a memory/views build up issue. Thanks!
