### ISSUE TITLE
When attempting to utilize existing eloquent users in existing laravel app, cp fails to load with Call to undefined method App\Models\User::avatar() 

### ISSUE THREAD

**Issue by tdondich** [statamic/cms#7071]
### Bug description

Attempted to install within existing laravel app and ran migrations.  When attempting to login and access /cp (after setting super flag on user to true), I get following:

Call to undefined method App\Models\User::avatar() (View: /var/www/html/vendor/statamic/cms/resources/views/partials/global-header.blade.php) 

### How to reproduce

Attempt to install in existing Laravel app.

Setup eloquent as the user store.

Access /cp

Call to undefined method App\Models\User::avatar() (View: /var/www/html/vendor/statamic/cms/resources/views/partials/global-header.blade.php) 

### Environment

```yaml
Stamatic 3.3, PHP 8.1.  Laravel 9.0
```

### Installation

Existing Laravel app

**Comment by edalzell** [comment]
what versions of statamic and laravel?

**Comment by nihongomaster** [comment]
I'm closing this ticket.  I had to juggle multiple guards.  All good now!

**Comment by tdondich** [comment]
I'm closing this ticket.  I had to juggle different guards and auth providers due to my unique setup.
