### ISSUE TITLE
Page URLs are case-insensitive

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#7102]
### Bug description

I've just noticed that Statamic allows URLs in any case, these all load the same page:

```
/blog/DONUTS
/blog/DoNuTs
/blog/donuts
```

I'd have expected the URLs to be case-sensitive. Regular Laravel routes and `Route::statamic()` routes are (anything else will 404). And the control panel enforces lowercase in the slug field.

Or is this intentional? If so I think there should be a way to prevent it. Maybe it could be configurable:

- `case-insensitive`
- `case-sensitive` (404 non matching)
- `redirect` (301 non matching)

### How to reproduce

Try to access an entry page with capital letters in the URL.

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Version: 3.3.58 Solo
```

### Installation

Starter Kit using via CLI

**Comment by jasonvarga** [comment]
Isn't that normal?

I can go to `https://github.com/StataMIC/CMS/issues/7102` and I end up at this issue.

**Comment by jacksleight** [comment]
I guess it depends on the website?

`https://laravel.com/docs/9.x/frontEND` - 404

Also Statamic's CP routes don't behave that way:

`http://example.test/cp/collections/PAGES` - 404

Case-insensitive seems to be the default for normal Laravel routes.

**Comment by jasonvarga** [comment]
Fair. I'm fine with that. 👍 

This is just an oversight anyway though. I definitely didn't _intend_ for them to be case insensitive.

**Comment by jasonvarga** [comment]
The issue comes from the query.

We take the url and query for entries with a matching url.

`$query->where('uri', $uri)`

This does a case insensitive search.

The same thing would happen in a regular Laravel/Eloquent/DB query, so it's not an "issue" with our query builder.

The difference is that a Laravel route doesn't resolve using queries.

Fix incoming.

**Comment by jacksleight** [comment]
Cool 👍

And if anyone _wants_ them to be insensitive I think there are ways to make that happen either in NGINX/Apache config or a tweak to Laravel's routing/request. Advantage then being that it would apply to all routes, not just things that go through the `FrontendController`.
