### ISSUE TITLE
Antlers null-coalesce fallback not working with translations

### ISSUE THREAD

**Issue by jlmmns** [statamic/cms#7107]
### Bug description

Using a translation as a null-coalesce (or ternary) fallback won't get parsed.

### How to reproduce

`{{ heading ?? trans:portfolio.heading }}`

### Environment

```yaml
Statamic 3.3.50 Pro
Laravel 9.20.0
PHP 8.1.7
No addons installed
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
`trans` is a tag, not a variable, so you'll need to wrap it in single braces.


```antlers
{{ heading ?? {trans:portfolio.heading} }}
```

**Comment by jlmmns** [comment]
Aha! Thanks for clearing that up, Jason! 🙌
