### ISSUE TITLE
Dissappearing asset fields

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#7109]
### Bug description

I'm seeing empty asset fields after editing one through the modal. This is happening on various entries and fieldsets - usually as part of a replicator. The JS console error seems to explain why (see screenshots). Refreshing the page restores the field.

![image](https://user-images.githubusercontent.com/20210934/203793433-bfc3bb1c-bfd0-4ddd-bec8-268ec134974b.png)
![image](https://user-images.githubusercontent.com/20210934/203791524-8e7944b1-3671-4458-80f1-16ef6132437e.png)
![image](https://user-images.githubusercontent.com/20210934/203791203-f6fb7a0d-956e-4c63-a260-a590c8d427f3.png)
![image](https://user-images.githubusercontent.com/20210934/203791379-8f52b581-a74c-4369-acd5-fafc3aee6a6a.png)
![image](https://user-images.githubusercontent.com/20210934/203791580-e9e904b5-f44a-481a-bd61-f6d4ebf022ae.png)

### How to reproduce

- Edit an asset through it's modal and click save.
- This may only happen as part of a replicator
- Check JS console for errors.

### Environment

```yaml
Version: 3.3.58 PRO
Laravel Version: 9.41.0
PHP Version: 8.1.12
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by dannyuk1982** [comment]
getting this too - just pressing the save button (with no changes) seems to cause it
