### ISSUE TITLE
Statamic Navigation - unable to link collections or create Link to Entry

### ISSUE THREAD

**Issue by Smilodown** [statamic/cms#7117]
### Bug description

Hi everyone,
On a Statamic fresh install, i just created Posts collection.
I'd like to link Posts ans Pages to navigation items, but when I select the Collections selector, it shows : 
<img width="916" alt="Capture d’écran 2022-11-25 à 14 02 48" src="https://user-images.githubusercontent.com/9696724/203991807-d67cdd13-7e79-48e7-9d2d-d106fd42201f.png">

On the console :
<img width="407" alt="Capture d’écran 2022-11-25 à 14 02 56" src="https://user-images.githubusercontent.com/9696724/203991898-e36e28a3-8c56-4146-951b-b47513a1fd0b.png">

I didn't have this error before....

I'm stuck right now. My Pro licences are useless for now.

### How to reproduce

Install Statamic (CLI)
Create Posts Collection (no blueprint attached)
Create Navigation
Configure Navigation > Try to select Pages/Posts on the Collection Selector

### Environment

```yaml
MAMP Pro :
PHP: 8.1
Statamic: 3.3.58
Coffee : Nespresso Pixie
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by stephanbouman** [comment]
I have the same issue. Fresh statamic installation and tried running with Artisan Serve. The error on the php-side:

```  
{
  "message": "Trying to access array offset on value of type null",
  "exception": "ErrorException",
  "file": "/Users/username/Projects/demoproject/vendor/statamic/cms/src/Http/Controllers/CP/Fieldtypes/RelationshipFieldtypeController.php",
  "line": 47
}
```

The same issue appears when you try to select an entry from an 'entries' field.

**Comment by Smilodown** [comment]
@stephanbouman 
Just gave a try and ! Ta-dam ! It works again.
As you said, it must be a PHP 8.0 & PHP 8.1 specific issue.
Thanks a lot ! You saved my day.
