### ISSUE TITLE
gatekeeper does execute even when left side is falsey when using pluck

### ISSUE THREAD

**Issue by hairness** [statamic/cms#7148]
### Bug description

Special behavior with the gatekeeper in antlers.
```
 {{ var_exists ?= (test = "testing") }}
 {{ test }} // works output "testing"

 {{ does_not_exist ?= (test = {does_not_exist pluck ('slug')}) }} //throws error

```

 I get this error foreach() argument must be of type array|object, null given

### How to reproduce

try the code from above. It looks like it needs to be an dictionary of some sort so you can use the pluck "modifier"

### Environment

```yaml
Statamic 3.3.16 Pro
Laravel 9.17.0
PHP 8.1.2
doublethreedigital/duplicator 2.3.1
jacksleight/statamic-bard-mutator 1.1.1
jacksleight/statamic-bard-texstyle 1.0.3
jonassiewertsen/statamic-livewire 2.9.0
stillat/relationships 1.0.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by JohnathonKoster** [comment]
This type of assignment was not intended to actually work

```antlers
{{ var_exists ?= (test = "testing") }}
```

To make it lazy, you can use `{}` instead:

```antlers
{{ var_exists ?= {test = "testing"} }}
```

I will look into improving the pluck operator, but using the actual modifier will also work just fine:

```antlers
{{ does_not_exist | pluck ('slug') }}
```

**Comment by jasonvarga** [comment]
I don't think pluck is the issue here. It just seems that the right hand side still gets evaluated if the left side is falsey.

**Comment by jasonvarga** [comment]
```antlers
{{ undefined_variable ?= {mytag} }}
```

```php
<?php

namespace App\Tags;

use Statamic\Tags\Tags;

class Mytag extends Tags
{
    public function index()
    {
        dump('tag is executed');

        return 'test';
    }
}
```

That'll correctly output nothing because the left side is falsey, but you'll see the dump because the tag is still executed.

**Comment by JohnathonKoster** [comment]
> ```
> {{ undefined_variable ?= {mytag} }}
> ```
> 
> ```
> <?php
> 
> namespace App\Tags;
> 
> use Statamic\Tags\Tags;
> 
> class Mytag extends Tags
> {
>     public function index()
>     {
>         dump('tag is executed');
> 
>         return 'test';
>     }
> }
> ```
> 
> That'll correctly output nothing because the left side is falsey, but you'll see the dump because the tag is still executed.

Yup - will look at making those lazy as well 🙂
