### ISSUE TITLE
Being able to use vendor:publish for addon config files

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cms#715]
Like you can use the `php artisan vendor:publish` command to [push addon assets](https://statamic3-docs.netlify.com/guide/extending/addons.html#assets), there's no way when creating a Statamic addon to set configuration files that can be published.

**Comment by aerni** [comment]
@damcclean Do you publish your addon config into the `config/statamic` subfolder or simply into `config`? I'm thinking `config/statamic` makes more sense. Especially when installing Statamic into an existing Laravel app. This way all the Statamic related configs are sorted.

**Comment by damcclean** [comment]
> @damcclean Do you publish your addon config into the `config/statamic` subfolder or simply into `config`? I'm thinking `config/statamic` makes more sense. Especially when installing Statamic into an existing Laravel app. This way all the Statamic related configs are sorted.

I just put them in the `config` folder itself. 

I did think about putting it in `config/statamic` originally but I must have changed my mind 😂  I could always change it.

**Comment by aerni** [comment]
Yeah, I'm torn too. I'm just thinking that it would be great if all addons followed the same pattern …

**Comment by damcclean** [comment]
Yeah I agree. I was probably just waiting to see what others were going to do.

**Comment by jasonvarga** [comment]
![](https://media3.giphy.com/media/3o6Mb2WBUzb7PGcgj6/giphy.gif?cid=4d1e4f29ca35084322a9cf0c4c20d49af3242f3615191844&rid=giphy.gif)

Put it in the root. We use a directory because we have multiple files and didn’t want to clog the root. But we can’t stop you from putting them wherever you want.

**Comment by aerni** [comment]
Alright! You da boss! 🤓
