### ISSUE TITLE
Default search using "+" gives an error

### ISSUE THREAD

**Issue by yusuf** [statamic/cms#7163]
### Bug description

For default search as implemented in the documentation https://statamic.dev/tags/search additing "+" sign to the beginning search string gives an error : Array to string conversion

### How to reproduce

Just follow : https://statamic.dev/tags/search

Example:
https://appellcenter.org/search-results?q=%2Bmembership%2Bsupport

### Environment

```yaml
Statamic 3 - with peak starterkit
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
Sorry, I can't seem to reproduce this error myself.

However, I did notice that the site you linked to is a Statamic v2 site.

**Comment by murilosantosgoco** [comment]
I can reproduce on my end, but i can't provide a repo easily, however [the demo that was just sent in the newsletter](https://demo.statamic.com/) has this problem, just hit the search button type "+" and search and a 500 should appear

**Comment by jasonvarga** [comment]
Reproduced. Thanks!
