### ISSUE TITLE
Global sets unavailable when abort(404) called

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#7210]
### Bug description

I am seeing error log warnings about 10 times a day saying things like:

```
`production.ERROR: Attempt to read property "cta_link" on null`
```

This property exists on a global set and I am trying to access it through the cascade in my Blade layout component, like so:
```
$cascade = Cascade::instance()->toArray();
$this->page = $cascade['page'] ?? null;
$this->globalFooter = $cascade['global_footer'] ?? null
$cta_link = $this->globalFooter['cta_link']
```

I have caught the exceptions and they only occur on custom routes and in vendor routes, e.g.:
`/_ignition/health-check` (Part of the laravel-ignition package)

In both cases it happens when the route / middleware calls `abort(404)`

It's only a minor issue and easy to work around, but can the Statamic middleware be added sooner making the cascade available before abort() is called?

### How to reproduce

- Access a global set from the cascade in a view or component
- Call abort 404 in your application

### Environment

```yaml
Version: 3.3.60 PRO
Laravel Version: 9.43.0
PHP Version: 8.1.12
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by stuartcusackie** [comment]
Nevermind. Me doing something dumb.

**Comment by stuartcusackie** [comment]
Closing again. I'll just avoid using abort(404) for now and try the null coalesce operator for the relationship field problem, e.g.:
```
<x-blog-footer
  :avatar="$page->staff_author->avatar ?? $page->user->avatar"
```

**Comment by stuartcusackie** [comment]
Re-opening as I've now found the error occurring in vendor package routes.

**Comment by duncanmcclean** [comment]
In your issue description, you say:

> Call abort 404 in your application

Where are you doing this?

**Comment by duncanmcclean** [comment]
I don't know if there's a great deal that Statamic can do about this...

Normally, any entry URLs or custom routes (if you use `Route::statamic` or return Statamic's `View` instance) will come included with all the variables you might need, like Globals.

However, on _normal_ Laravel routes or when calling `abort(...)`, that bypasses any of Statamic's stuff and is handled by Laravel. This means Statamic doesn't do any of it's "adding variables" that it would usually get to do if it was a Statamic `View` that was being dealt with.

I could be wrong - happy for someone to correct me but this is the way I think it works & may be what's causing the issue for you here.

**Comment by jasonvarga** [comment]
Avoid getting the global from the cascade. Since you're in PHP, get it using the repository.

```php
$set = Statamic\Facades\GlobalSet::find('global_footer')->inDefaultSite();
$cta_link = $set->cta_link;
```
