### ISSUE TITLE
Bard nested lists

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#7212]
### Bug description

Just revisiting this [issue](https://github.com/statamic/cms/issues/1815). I should have added this to statamic/ideas. Apologies.

Nested lists are not possible, and if you paste one from another source, or migrate from WP content, then the editor can't handle it very well.

Thank you.

### How to reproduce

Try to set up a nested list

### Environment

```yaml
Version: 3.3.60 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
Nested lists work fine. Please provide a repo with the issue reproduced.

![CleanShot 2022-12-13 at 09 40 58](https://user-images.githubusercontent.com/105211/207363184-7fae1ca2-70dd-4fc1-9a41-4a0b5ad4a958.png)

**Comment by stuartcusackie** [comment]
Sorry if I'm missing something obvious, but I can't see a way to achieve the indentation shown in your screenshot...? Is it a keyboard shortcut or something?

**Comment by jasonvarga** [comment]
The tab key.

**Comment by stuartcusackie** [comment]
This doesn't work on Windows. I think we may need indent buttons.

**Comment by jasonvarga** [comment]
We just tested it on windows and it works fine.

Perhaps you could provide a repo with this problem reproduced.

I'm closing this and going to reference https://github.com/ueberdosis/tiptap/issues/3018 since it would be a tiptap issue. Perhaps you can chime in there.

**Comment by stuartcusackie** [comment]
Interesting. I have tried both windows 10 and windows 11 and tab just navigates through fields as it normal does with the tabindex html property. Tiptap probably needs to override that so I'll keep an eye on that thread.

I still think indent buttons would be better. I imagine the average user doesn't use keyboard shortcuts, and most web interfaces I've seen provide indent buttons.

**Comment by jasonvarga** [comment]
Are you still using Statamic 3.3? Have you tried on 3.4?

**Comment by stuartcusackie** [comment]
Sorry, I just tried it. It works on 3.4!

I still feel that optional indent buttons would be useful though. I think that only technical people would know that tab can be used for indenting lists.

Anyway, this works fine for now. You might consider adding it in future. Thanks again.

**Comment by benedictsc** [comment]
I'd second the request for indent buttons – very confusing for a regular user without the technical fluency without them.

**Comment by jasonvarga** [comment]
Feel free to open a feature request in the github.com/statamic/ideas repo, or open a PR implementing the feature.
