### ISSUE TITLE
No Image button on bard

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#7233]
### Bug description

I have added the image tag to the blueprint but the bard does not render the image button

```
buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
            - superscript
```

<img width="872" alt="Screenshot 2022-12-16 at 3 16 41 pm" src="https://user-images.githubusercontent.com/7971800/208021084-2fd98d64-6323-4051-9930-7752c9e4c1e7.png">

### How to reproduce

Add the image to the bard then check the image button is rendered on the page

### Environment

```yaml
Statamic 3.3.60
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
You must set an asset ` container` on the field in order for the image button to work.
