### ISSUE TITLE
Updating dynamic variable in loop

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#7297]
### Discussed in https://github.com/statamic/cms/discussions/7285

<div type='discussions-op-text'>

<sup>Originally posted by **imakeitworknet** January  3, 2023</sup>
Hi. I have a page with Related Entries (bard block Entries) in it. Like:

```
related_entries:
          - 69677794-6d85-496f-b22c-ab054c2f269e
          - 43e250f2-df2c-452f-828b-54e4383dcd41
```
          
I also have a dynamic variable named {{ found = 0 }} in the antlers template. Is there a way to update that variable while looping through related entries, and getting it later in the template? Here's complete example:

```
<section>
  {{ found = 0 }}
       {{ related_entries }}
           {{ if SOME LOGIC }}
                  {{ found = 1 }}
           {{ /if }}
       {{ /related_entries }}

{{ if found==1 }}
   /* do something */
{{ /if }}
</section>
```

Currently everything what happens in {{ related_entries }} loop stays in it, so {{ found }} variable does not get through.
Thanks!</div>

**Comment by JohnathonKoster** [comment]
@jackmcdade  I am not able to reproduce this with the latest Statamic versions, using the Runtime parser:

![image](https://user-images.githubusercontent.com/5232890/210592611-b955c0e2-9223-4735-b3f3-77fd59b2ba79.png)

Perhaps I am missing something

**Comment by imakeitworknet** [comment]
After a day off from the problem is seems that it's not antler's bug - it's my own bug. Sorry for wasting your time!

**Comment by jasonvarga** [comment]
No problem! Thanks for letting us know.
