### ISSUE TITLE
Allowed memory size exhausted errors with a huge amount of assets (images)

### ISSUE THREAD

**Issue by aparraga** [statamic/cms#7385]
### Bug description

With a large amount of assets (more than 20K images), we start experiencing performance issues and memory size exhausted errors.

We think that this is because how assets are checked against assets containers, since statamic recovers all the assets in the AssetContainerContents::files method, and them they are filtered in order to check if an image exists, or to get the metadata or whatever.
Problem is that, "scan" all assets at that point takes a long time, and after that, operating with the resultant collection of assets produces memory issues.

### How to reproduce

Just upload 20K images and use some of them in an article. After publishing you won't be able to see the article since the issues described

### Environment

```yaml
Statamic 3.3.64
Laravel 9.47.0
PHP 8.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
Is this the same as #7317?

**Comment by aparraga** [comment]
No. It's related but different issue. This issue is regarding memory consumption, and it affects whatever file storage (no matter local storage, Google Cloud, S3, or whatever), resulting in a memory exhausted error with a big number of files on your storage.
We are in fact fixing it in our local project and we'll make a pull request with the solution (we love open source!). We have more than 20,000 images.

**Comment by jasonvarga** [comment]
It's the same issue. It poops itself when it tries to filter down an array with that many items in it. Curious to see what you've come up with! 😍 

Closing this one down in favor of #7317

**Comment by aparraga** [comment]
I mean, everything is related and can be considered as the same issue, but I see both issues as different because I'm able to fix this one (#7385) without fixing the #7317, so this is the reason because I have opened a different issue.
In fact, we have already fixed this guy to continue our developments, but still need to fix the #7317, but anyway :)

**Comment by johncarter-** [comment]
I'm facing the same issue. Do you have a solution that you can share?
