### ISSUE TITLE
Call to undefined method App\Models\User::preferences()

### ISSUE THREAD

**Issue by davideprevosto** [statamic/cms#7423]
### Bug description

I update to the 3.4 version, navigate to /preferences (the gear icon in the top right corner) I am getting:

`Call to undefined method App\Models\User::preferences() (View: /Users/xx/Sviluppo/www/xx/project/vendor/statamic/cms/resources/views/preferences/index.blade.php)`

`Call to undefined method App\Models\User::hasPreference() (View: /Users/xx/Sviluppo/www/xx/project/vendor/statamic/cms/resources/views/nav/index.blade.php)
`
### How to reproduce

Click on the top right gear icon, Preferences or CP Nav

### Environment

```yaml
Statamic 3.4 
PHP 8.1.x
Laravel 9.48.x
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by ItsJustPW** [comment]
Similar issue for me, this is `User::hasPreferences`

Screenshot:

<img width="1462" alt="Screenshot 2023-01-28 at 18 16 55" src="https://user-images.githubusercontent.com/40368729/215284021-50712bca-8ffe-45fb-82ee-808a8802e195.png">

Copy of laravel log:

`[2023-01-28 18:18:02] local.ERROR: Call to undefined method App\Models\User::hasPreference() (View: /Users/paul/Projects/ttg/vendor/statamic/cms/resources/views/nav/index.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Call to undefined method App\\Models\\User::hasPreference() (View: /Users/paul/Projects/ttg/vendor/statamic/cms/resources/views/nav/index.blade.php) at /Users/paul/Projects/ttg/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71)`

**Comment by jesseleite** [comment]
@davideprevosto @ItsJustPW I assume you're both running with Eloquent instead of flat-file users, given `App\Models\User`?

**Comment by ItsJustPW** [comment]
Yes that's correct I'm using a DB for users as I'm using spark also.

Not sure if it's related, but author and author:avatar don't seem to function any more also. However this could just be me having messed something up.

**Comment by ryanmitchell** [comment]
@jesseleite did you guys ever consider adding a trait that could be added to the user model to provide the methods statamic needs?

**Comment by davideprevosto** [comment]
> @davideprevosto @ItsJustPW I assume you're both running with Eloquent instead of flat-file users, given `App\Models\User`?

Yes, we're using Eloquent to store our users.

**Comment by ItsJustPW** [comment]
> @jesseleite did you guys ever consider adding a trait that could be added to the user model to provide the methods statamic needs?

In all honesty... I wouldn't have a clue how to or what to do

**Comment by ryanmitchell** [comment]
@ItsJustPW it was a question to the Statamic team, seems like theres enough 'additional' stuff now needed that offering a Trait to add that functionality to the user model makes sense.

**Comment by jasonvarga** [comment]
We shouldn't be interacting with the model though.

@jesseleite I believe this can be fixed by changing https://github.com/statamic/cms/blob/1411509600cafa4a5737d67cfb44defb59840a67/resources/views/nav/index.blade.php#L62 to `@if (Statamic\Facades\User::current()->hasPreference('nav'))`
