### ISSUE TITLE
Typo in the new preference menu

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#7446]
### Bug description

I clicked on "preferences" then on "Default" and I read this:

"The page to be should be shown when logging into the control panel."

<img width="583" alt="Capture d’écran 2023-01-31 à 23 33 13" src="https://user-images.githubusercontent.com/1823359/215899639-44ffa6ee-966c-43e4-afbd-ba86300edf53.png">

What about: "The page that should be shown when logging into the control panel." or simpler: "The first page to display after logging into the CP"

Anyway.

### How to reproduce

Click on preferences (new top menu) then on Default

### Environment

```yaml
Statamic 3.4.0
PHP 8.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Haha looks like two sentences got merged.
