### ISSUE TITLE
Provided value is being overridden in the method \Statamic\Query\Builder::orWhereJsonLength(...)

### ISSUE THREAD

**Issue by simonworkhouse** [statamic/cms#7460]
### Bug description

The `$value` variable is always being set to `null` due to `$value = null` within `\Statamic\Query\Builder::orWhereJsonLength(...)`:

```
    public function orWhereJsonLength($column, $operator, $value)
    {
        return $this->whereJsonLength($column, $operator, $value = null, 'or');
    }
```

See https://github.com/statamic/cms/blob/a701611230232956e8c3703547b440c7d25c7ac6/src/Query/Builder.php#L276

### How to reproduce

N/A

### Logs

```shell
N/A
```

### Environment

```yaml
N/A
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

N/A

**Comment by ryanmitchell** [comment]
Good spot!
