### ISSUE TITLE
Since 3.4: Buggy CodeBlocks

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#7483]
### Bug description

Having CodeBlocks in the Bard field does have buggy behaviors.
If it is the only content, it looses it's content after saving.
If it is between other sets, sometimes bard ends with an console error and the textarea is not visible.
<img width="930" alt="Bildschirm­foto 2023-02-06 um 20 52 11" src="https://user-images.githubusercontent.com/6337411/217080477-5eff6453-ea74-4a55-b29a-de024903b166.png">
<img width="621" alt="Bildschirm­foto 2023-02-06 um 20 52 03" src="https://user-images.githubusercontent.com/6337411/217080493-411cacf9-b0ba-4c97-923a-3e05d27e3980.png">

### How to reproduce

1. Add a bard field.
2. Enable CodeBlocks
3. Open entry, enable Codeblock, write something and save.
4. Reload the page.

https://user-images.githubusercontent.com/6337411/217080190-7bb64437-2cc6-4a2d-a222-8d0b28ba316a.mov

### Environment

```yaml
Environment
Laravel Version: 9.46.0
PHP Version: 8.1.14

Statamic
Addons: 0
Version: 3.4.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by ebeauchamps** [comment]
Also related somehow to #7459 ?
