### ISSUE TITLE
Cannot add fieldset to nested Bard

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#7530]
### Bug description

I have a Bard field within a Bard field and cannot seem to add a fieldset within the second Bard field. It is allowed as a set but when I click the + icon, nothing appears.

<img width="541" alt="Screenshot 2023-02-13 at 12 51 25" src="https://user-images.githubusercontent.com/3603346/218450750-f6d127f9-2e8d-42dd-82f4-10dbc2b98a7b.png">

I made a short recording:

https://www.loom.com/share/06fd51ea08d940a7a47167975e25fcea

### How to reproduce

Create a Bard field and another Bard field within. Then create a fieldset that is allowed within both fields.

### Environment

```yaml
Statamic 3.4.3 Pro
Laravel 8.83.27
PHP 8.1.14
Stache Watcher Enabled
Static Caching Disabled
jacksleight/statamic-bard-texstyle 2.0.1
jonassiewertsen/statamic-livewire 2.11.0
octoper/statamic-blade-components 1.0.1
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by o1y** [comment]
@MrMooky Does it also glitch when you remove the text align buttons from Bard? My Editor is just crashing when I try to replicate your issue due to the Text Alignment Feature not really working in a nested context.

**Comment by jacksleight** [comment]
Sets are block level elements so aren't supported in inline mode. Same as images, tables etc. This probably needs to be documented (if it's not already), I'll check.

**Comment by jacksleight** [comment]
Oh ha, I missed the video. Never mind, ignore me! 😄

**Comment by MrMooky** [comment]
> @MrMooky Does it also glitch when you remove the text align buttons from Bard? My Editor is just crashing when I try to replicate your issue due to the Text Alignment Feature not really working in a nested context. Maybe this is somehow related.

I did not further debug this yet because I'm dealing with other v3.4 issues right now as well. But I quickly created a Replicator instead, that does what I want. Bard within Bard seems to be buggy in a few ways and a crashing editor also indicates that something is wrong, obviously.

**Comment by o1y** [comment]
@MrMooky Can you try if the latest release 3.4.4 fixes this issue for you?

**Comment by MrMooky** [comment]
> @MrMooky Can you try if the latest release 3.4.4 fixes this issue for you?

Same issue, cannot open the plus icon in the second Bard.

<img width="256" alt="Screenshot 2023-02-17 at 08 25 14" src="https://user-images.githubusercontent.com/3603346/219577804-d9fd1e62-bd99-4230-874a-53e9ac8288b9.png">

**Comment by atomicjam** [comment]
This looks to be fixed in Statamic v4, just doing some further testing.

**Comment by jasonvarga** [comment]
Glad to hear!
