### ISSUE TITLE
Using Soketi for broadcasting needs configurable Echo host/port/enabledTransports

### ISSUE THREAD

**Issue by eminos** [statamic/cms#7573]
### Bug description

I'm using Soketi for websockets/broadcasting/Echo in an existing Laravel app.
Statamic Admin sees that I use the BroadcastProvider and then tries to connect to websockets, but fails. (falls back to trying to connect to ws.pusherapp.com)
https://github.com/statamic/cms/blob/8607bf98b0a3ae3680ef84f78259a2198d9afa3f/src/Providers/BroadcastServiceProvider.php#L31-L37

Also Soketi needs some extra connection configuration.
https://docs.soketi.app/getting-started/client-configuration/laravel-echo

Ideally we should be able to enable/disable the broadcasting in Statamic Admin ourselves.
I use broadcasting in my Laravel app, but I don't need it in Statamic.
We should also be able to configure the Echo connection details. Preferably the full config object.

### How to reproduce

Try using Soketi for websockets/broadcasting :)

### Environment

```yaml
Laravel Version: 9.52.0
PHP Version: 8.1.14
Version: 3.4.4 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

None

**Comment by jasonvarga** [comment]
You can disable the Statamic broadcasting in the CP with this workaround in your AppServiceProvider:

```php
public function boot()
{
    $this->app->booted(function () {
        Statamic::provideToScript(['broadcasting' => ['enabled' => false]]);
    });
}
```
