### ISSUE TITLE
Unable to search in CP for users (with SearchIndex)

### ISSUE THREAD

**Issue by Keoghan** [statamic/cms#7680]
### Bug description

Using Statamic 3.4.5 we are unable to search users in the control panel when using a search index.

We receive the error: 

`Call to undefined method Statamic\Http\Resources\CP\Users\ListedUser::id()`

I believe this is due to the change to returning a `Statamic\Search\Result` rather than the resulting model.

If we add the following to `Statamic\Http\Controllers\CP\Users\UsersController::json()` line 77

``` 
if ($users->getCollection()->isNotEmpty() && $users->getCollection()->first() instanceof \Statamic\Search\Result) {
    $users->setCollection($users->getCollection()->map->getSearchable());
}
```

Then we can map the object back to the object and search works again.

### How to reproduce

Add some users to CP, add a search index, and try to search.

### Environment

```yaml
Laravel 9, Statamic 3.4.5.
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by Keoghan** [comment]
I can see a similar solution in place for Entries.

```
if (request('search') && $collection->hasSearchIndex()) {
            $entries->setCollection($entries->getCollection()->map->getSearchable());
        }```

**Comment by edalzell** [comment]
I believe the issue here is that `User` is missing `ContainsQueryableValues`. I ran into this trying to do a nested query on users: `User::query()->whereJsonContains('client->everhour_client->id', 1672597)->get()`
