### ISSUE TITLE
collection taxonomy filter, when taxonomy field is limit to 1

### ISSUE THREAD

**Issue by ithuis** [statamic/cms#7697]
### Bug description

when taxonomy field is limit to 1 in the blueprint, the function queryTaxonomies in Statamic\Tags\Collection\Entries.php cant handle that. There is a check for "isQueryBuilder", but when the limit is set to 1 it gets an instance of LocalizedTerm

### How to reproduce

add a taxonomy field to blueprint wit max_entries = 1

then add code 

{{ collection:things :taxonomy:category:any="category" }}
echo
{{ /collection:things }}

### Environment

```yaml
upgraded statamic 3 from 2. 
now running in laravel sail
```

### Installation

Other (please explain)

### Antlers Parser

None

**Comment by robdekort** [comment]
I noticed this bug as well on a project by @websmyth. A workaround I found was to use `{{ collection:things :taxonomy:category:any="category.slug" }}` but I don't think it should be this way.

**Comment by ithuis** [comment]
This works great! Although i agree it probably shouldn't work this way.
