### ISSUE TITLE
collection taxonomy filter using taxonomy name to filter, not the on giving in filter

### ISSUE THREAD

**Issue by ithuis** [statamic/cms#7698]
### Bug description

when using something like
{{ collection:things :taxonomy:tags:any="category" }}

i expected that the "things" collection would filter on the field "tags" that is on the blueprint of "things".
But, it forces to filter on "catagory". 

in the function queryTaxonomies in entries.php, there is a line "return $term->id()". Which return the ( in my case ) wrong code of "catagory::value" instead of the next line in the function, which would return "tags::value".

### How to reproduce

create taxonomy named taxA
create blueprint with field "taxonomy terms" named "taxb" while using "taxa"

try filter

{{ collection:things :taxonomy:taxa:any="taxb" }}

### Environment

```yaml
statamic updated (2.0 to current ) running via laravel sail
```

### Installation

Other (please explain)

### Antlers Parser

None

**Comment by ryanmitchell** [comment]
The `$term->id()` will always return the handle and id of the taxonomy.
For the taxonomy filters to work the field handle needs to match the name of the taxonomy - when you mount a taxonomy to a collection this field is automatically created.

To have a different handle I would suggest you look at a [query scope](https://statamic.dev/extending/query-scopes-and-filters#scopes) instead, and use whereJsonContains() on the query builder instance.
