### ISSUE TITLE
RelationshipFieldtype's Selector ignores collection's default sort field

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#771]
When we configure a relationship field with just one collection of which entries can be "linked", we expect the Selector to use this single collections `sort_by` configuration to be used. Instead, `title` is hardcoded: https://github.com/statamic/three-cms/blob/master/resources/js/components/inputs/relationship/RelationshipInput.vue#L66

**Comment by jelleroorda** [comment]
Open sesame
