### ISSUE TITLE
*Code* fieldtype is missing `antlers` toggle in the Blueprint Editor

### ISSUE THREAD

**Issue by sjclark** [statamic/cms#7758]
### Bug description

I was creating a JSON-LD `code` fieldtype which included some antlers tags that I wanted parsed. The default output on the front-end does **not** parse antlers tags, so I went to enable it in the admin blueprint editor, but there is no configuration option, also nothing referenced in the docs.

However, enabling `antlers: true` in the field yaml does work.

I suggest the `antlers` toggle be added to this fieldtype to be consistent with others?

### How to reproduce

1. Create a `code` fieldtype
2. Add antlers tags within the code field content
3. Add to a front-end template and notice the field output on front-end without antlers tags parsed
4. Manually add `antlers: true` in blueprint yaml

### Environment

```yaml
Statamic 3.4.7 Pro
Laravel 8.80.0
PHP 8.2.3
Stache Watcher Enabled
Static Caching Disabled
aryehraber/statamic-captcha 1.9.1
spatie/statamic-responsive-images 3.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jackmcdade** [comment]
Fixed in https://github.com/statamic/cms/pull/7873
