### ISSUE TITLE
Error at utilities: search, cache, email

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#777]
It looks like the utilities: cache, search and email are broken. 

Here are small excerpts from the Error Exceptions:
**cache:** _Route [statamic.cp.utilities.cache.clear] not defined. (View: /var/www/core/resources/views/utilities/cache.blade.php)_

**email + search:** _Call to a member function view() on null -> /var/www/core/src/Http/Controllers/CP/Utilities/UtilitiesController.php22_

**Comment by jesseleite** [comment]
Should be good now, feel free to re-open if not.
