### ISSUE TITLE
[4.x] Bard Add Link button jumps window position to the top.

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#7797]
And I can't figure out why.

**Comment by o1y** [comment]
It jumps to the top due to the url input being focused before opening the popover: https://github.com/statamic/cms/blob/master/resources/js/components/fieldtypes/bard/LinkToolbar.vue#L302-L303

This could be a hacky workaround:

```diff
this.$nextTick(() => {
+    setTimeout(() => {
        this.$refs.urlInput.focus()
+    }, 1)
});
```

**Comment by o1y** [comment]
And this issue seems to be a duplicate from #7787 😅

**Comment by jackmcdade** [comment]
Perfect @o1y! That's just the sort of hacky workaround we use all over, not sure why i didn't think of it 😅 .
