### ISSUE TITLE
[4.x] Adding a Bard set in Safari doesn't work

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7810]
### Bug description

When you add a set to a Bard field in the entry editor nothing happens.

### How to reproduce

1. Open Safari
2. Add a bard field with a set to a blueprint
3. Go to the entry
4. Edit the Bard field
5. Hit the plus
6. Pick a set
7. Confirm my findings

### Environment

```yaml
`statamic new test studio1902/statamic-peak --dev`
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
I can do everything except step 7.

**Comment by robdekort** [comment]
Haha that me laugh. Turns out this is on `dev-master`. Sorry about that.

https://user-images.githubusercontent.com/69107412/229143935-83f708fb-ab4f-4599-95eb-b8d60a912b25.mov

**Comment by jasonvarga** [comment]
Fixed in #7818
