### ISSUE TITLE
`always_show_filters` returns back to default view after adding a new filter

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#7837]
### Bug description

I would expect that the header does not go back to the 'default' view, as if the `always_show_filters` has not been activated via config setting:

https://user-images.githubusercontent.com/38906163/230049064-b020be31-6235-4757-aece-e3590c0296b7.mov

### How to reproduce

1. Set `always_show_filters ` to true:
https://github.com/statamic/cms/blob/master/config/cp.php#L40

2. Create or delete a new filter as shown in the video above.

### Environment

```yaml
Version: 4.0.0-alpha.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jackmcdade** [comment]
Getting rid of this setting.
