### ISSUE TITLE
[4.x] Text in select box gets cut off vertically

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7876]
### Bug description

The text in a select box (on the right) is cut off vertically and not perfectly centered.

Suggestion: perhaps the text size should be the same as the select box on the left.
<img width="561" alt="Screenshot 2023-04-08 at 14 03 23" src="https://user-images.githubusercontent.com/69107412/230720102-4c2df9d1-198b-4a45-9d06-17052270634d.png">

### How to reproduce

.

### Environment

```yaml
.
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by jackmcdade** [comment]
can you share any more details? Browser/field settings? Looks good for me... 
<img width="656" alt="CleanShot 2023-04-11 at 11 03 33@2x" src="https://user-images.githubusercontent.com/44739/231205431-07167f2d-36a5-4fa1-b606-319336e31e3e.png">

**Comment by robdekort** [comment]
This is in Safari but I also noticed it in Chrome.

It's a collections field and a regular select field used within a stacked grid. Maybe that explains the difference?
