### ISSUE TITLE
[4.x] Listing: Customize Columns can't handle many columns

### ISSUE THREAD

**Issue by wiebkevogel** [statamic/cms#7897]
### Bug description

If there are few entries in the listing, the column configuration may not be displayed completely.

![Bildschirmfoto 2023-04-13 um 10 58 54](https://user-images.githubusercontent.com/54707973/231709855-a897186c-f3c9-4fce-a338-b4bde865e17b.png)

### How to reproduce

- Open listing
- Show few entries by pagination or filter
- Open 'Customize Columns' with a lot of Columns

### Environment

```yaml
Version: v4.0.0-alpha.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jackmcdade** [comment]
Good catch! How do you feel about switching to a side-by-side modal with some scrolling when you run out of room? 
![image](https://user-images.githubusercontent.com/44739/231798713-4ce26f69-8a5e-4aaa-aa23-b5f2c49af02b.png)

**Comment by wiebkevogel** [comment]
Sounds like a good solution! :)

**Comment by jasonvarga** [comment]
Fixed by #7905
