### ISSUE TITLE
[4.x] Filter doesn't close automatically

### ISSUE THREAD

**Issue by wiebkevogel** [statamic/cms#7898]
### Bug description

When switching between filters, the previous selection always remains open. 

https://user-images.githubusercontent.com/54707973/231711737-77011909-1f8c-443b-ba81-3b2d011811e2.mov

### How to reproduce

See video

### Environment

```yaml
Version: v4.0.0-alpha.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
Fixed in #7907
