### ISSUE TITLE
[4.x] Replicator-Set-Picker and Dropdown can not be opened in live preview

### ISSUE THREAD

**Issue by wiebkevogel** [statamic/cms#7900]
### Bug description

It is not possible to add or edit a Replicator-Set in Live-Preview:

https://user-images.githubusercontent.com/54707973/231747546-eae15aab-5e33-4acb-9009-64be8ca666d4.mov

### How to reproduce

Open the Live-Preview with the Replicator-Fieldtype and try to add or edit a set

### Environment

```yaml
Version: v4.0.0-alpha.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
Fixed in #7907
