### ISSUE TITLE
[4.x] Global Search has a tiny z-index problem

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#7908]
### Bug description

The `.checkbox-column` is stacked on top of it. Removing z-index didn't do it, and I don't want to just start playing the increment game. We could/should probably refactor this to act more like a modal.

<img width="697" alt="CleanShot 2023-04-13 at 19 22 11@2x" src="https://user-images.githubusercontent.com/44739/231903512-5def1cab-acd9-4313-8c99-0e222584728e.png">

### How to reproduce

Search for anything that returns results.

### Environment

```yaml
`dev-master`
```

**Comment by jasonvarga** [comment]
Fixed by #7907
