### ISSUE TITLE
Tabs in assets look weird

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7915]
### Bug description

The tabs above asset containers look odd. There are some grey lines next to the tab lines. They might also need some vertical spacing between them just like tabs in collection entries. And the top left corner isn't rounded currently.
<img width="421" alt="Screenshot 2023-04-15 at 12 05 51" src="https://user-images.githubusercontent.com/69107412/232207506-be875c6a-5ba2-4c23-835a-a01a01a8f140.png">

### How to reproduce

.

### Environment

```yaml
dev-master
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
Fixed in #7911
