### ISSUE TITLE
Color picker field z-index issue

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7924]
### Bug description

The controls disappear behind the next section.
<img width="442" alt="Screenshot 2023-04-17 at 13 13 13" src="https://user-images.githubusercontent.com/69107412/232468573-fbf8df64-2eda-42cd-8278-c6dcccfb2b5b.png">

### How to reproduce

Add a color field as the last field followed by a new section.

### Environment

```yaml
alpha-3
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
Fixed in #7973
