### ISSUE TITLE
Focal picker broken

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#7929]
### Bug description

You can't set focus points anymore to the point you want focus on:
https://user-images.githubusercontent.com/69107412/232588094-0ec2bdff-3296-4183-9bfa-b5fd18d96ff7.mp4

### How to reproduce

Try the focal point editor

### Environment

```yaml
`dev-master`
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

**Comment by robdekort** [comment]
Uploading vids doesn't seem to work propertly. I can't playback that video. Here's a gif, bit hard to see. Sorry about that.
![gif](https://user-images.githubusercontent.com/69107412/232589690-a2e23b5a-bc4a-4dc9-86b5-25e8cc49b36b.gif)

**Comment by jasonvarga** [comment]
This is not v4 specific. It seems to happen on 3.4 too when you have a much taller than wide image.

**Comment by jasonvarga** [comment]
Can you upload that image here?

**Comment by robdekort** [comment]
It happens for all my images 4.0

**Comment by robdekort** [comment]
[Here's a bunch though](https://github.com/statamic/cms/files/11255189/Archive.zip)

**Comment by jasonvarga** [comment]
They all seem fine here. 🤔

**Comment by robdekort** [comment]
That's weird. Thinks I can think of. I'm using the eloquent driver, but only for entries. Want repo access?

**Comment by robdekort** [comment]
Ok. I recompiled the CP assets and now it seems fine. Sorry about this.

**Comment by robdekort** [comment]
Weird though, very weird. Glad it's nothing.

**Comment by robdekort** [comment]
Sorry again, but it's back. 🤷🏻‍♂️

**Comment by jasonvarga** [comment]
![](https://media.giphy.com/media/MBy2eijcjNNr9jWHxF/giphy-downsized.gif)

**Comment by jasonvarga** [comment]
What browser? What commit are you on?

**Comment by robdekort** [comment]
Haha. It's like you're stuck with it once you trigger it on a ![hero-fc-groningen](tall image). Both in Safari and Chrome on 42d3241792d461bffa3fd821af62689efba3e4ca

**Comment by robdekort** [comment]
Sorry my commenting capabilities seem to be a train wreck tonight.

**Comment by jasonvarga** [comment]
That image seems to work fine too.

**Comment by jasonvarga** [comment]
Got it. It's when you use it within an assets fieldtype.

**Comment by robdekort** [comment]
Ah there you go! Clever man!

**Comment by robdekort** [comment]
Can I get my label back now?

**Comment by jasonvarga** [comment]
Yes!

**Comment by jasonvarga** [comment]
Fixed in #7930
