### ISSUE TITLE
Editing asset metadata does not update last_modified 

### ISSUE THREAD

**Issue by admench** [statamic/cms#7975]
### Bug description

Changing meta data on assets does not touch the modified datestamp.

The motivation behind needing this is to invalidate browser cache on images.
I'm appending last_modified to the image url.

Here is the git diff after making changes:

<img width="715" alt="Screenshot 2023-04-21 at 10 11 18" src="https://user-images.githubusercontent.com/672916/233597448-451456ab-539c-4256-9cd1-e24e88e10d7f.png">

### How to reproduce

I edit an asset's focal point / alt text. Click save.
Last Modified in the .meta/ yaml file does not update.

assets.php  config:

```
'cache' => true,
```

### Environment

```yaml
PHP v8.1.17

Statamic v3.4.7
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by admench** [comment]
I have resolved my browser cache issue by doing the following:

```
{{ glide:image preset="large" }}{{ url }}?focus={{ focus }}&alt={{ alt | urlencode }}{{ /glide:image }}

**Comment by jasonvarga** [comment]
The last modified there means the date the actual file was modified, not the metadata.
