### ISSUE TITLE
Deleting a Replicator Set will throw an exception when editing a page that used it

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#8008]
Ideally blueprints should be a bit less brittle than that. 
<img width="1246" alt="CleanShot 2023-04-27 at 09 48 09@2x" src="https://user-images.githubusercontent.com/44739/234882383-8ed3fb19-0e82-422b-bc65-66584b86bb9c.png">

**Comment by jasonvarga** [comment]
You mean you deleted the set in the blueprint? Not the value, right?

**Comment by jackmcdade** [comment]
Correct.
