### ISSUE TITLE
Bard/ProseMirror Link

### ISSUE THREAD

**Issue by luizboaretto** [statamic/cms#801]
Possibility to select Pages, Collections or custom in the link button.

![Edit_Entry_‹_Blog_‹_Collections_‹_Statamic](https://user-images.githubusercontent.com/32047234/66972229-57198280-f06a-11e9-82a8-abd26ae4935d.png)

The link could be saved internally with the ID. If the URL changes (slug), the link would still work.

**Comment by steveooo1** [comment]
Yeah, this link feature is used by us in other CMS a lot, so it would be great to have an ID saved internally so it still works on URL change and maybe a better UX for selecting existing entries as a link.

**Comment by ReneWeCode** [comment]
Me: Just told how smart and clever the bard editor is. 
Client: Tries to create an inline link.
Me: Had to get off the horse.

Is this one at the bottom of the pile? 🙃

**Comment by FlorianMoser** [comment]
This is a pretty important feature for a CMS. Any plans on porting this soon?

**Comment by jtomek** [comment]
I concur. This is really important feature. 

Could you please comment on the plans to implement it?

**Comment by j3ll3yfi5h** [comment]
Same! This would be very helpful for clients!

**Comment by jmartsch** [comment]
Please take a look at my ideas for this feature: https://github.com/statamic/ideas/issues/236
and https://github.com/statamic/ideas/issues/234

**Comment by edalzell** [comment]
Just hit this in a large migration, still an issue and important (to us)

**Comment by AndreasSchantl** [comment]
Same here. This should be added relatively soon. It's a bummer if you want to link some file, let's say a PDF and you need to copy the URL from the assets browser first.

**Comment by Hesesses** [comment]
vote for this

**Comment by delz-dev** [comment]
More votes on this …

**Comment by duncanmcclean** [comment]
If you've not already, please add a 👍  reaction to the top post on this issue. The team can easily filter by reactions, not as easily by comments. Thanks!

**Comment by purplespider** [comment]
Would love for this to do something like Silverstripe, where it asks what you'd like to link to:

![image](https://user-images.githubusercontent.com/329880/111289293-eac6f800-863c-11eb-90ce-c01851941055.png)

Being able to easily link to email addresses (without needing to know about `mailto:`) and files (without needing to find the full URL) is essential for ease of use.

**Comment by robdekort** [comment]
Since this is an issue here and not a FR, those two FR's are relevant and can maybe be closed in favour of this issue. https://github.com/statamic/ideas/issues/217 and https://github.com/statamic/ideas/issues/236.

**Comment by j3ll3yfi5h** [comment]
#2199

**Comment by goellner** [comment]
Is the idea to only enable links to entries or also for assets? Assets would be as important, for example: FAQ items, where there are some pdfs linked. Pretty much everything should be linkable like @purplespider already said, and the example is pretty good too.

> Would love for this to do something like Silverstripe, where it asks what you'd like to link to:
> 
> ![image](https://user-images.githubusercontent.com/329880/111289293-eac6f800-863c-11eb-90ce-c01851941055.png)
> 
> Being able to easily link to email addresses (without needing to know about `mailto:`) and files (without needing to find the full URL) is essential for ease of use.

**Comment by jasonvarga** [comment]
I figure you would like the ability to at least link to entries ASAP. The PR I'm working on does that. We can add assets in a future release.

**Comment by jasonvarga** [comment]
Ability to add entries will be in 3.1.5.

For assets, keep an eye on #2199

**Comment by j3ll3yfi5h** [comment]
#3668
