### ISSUE TITLE
AssetsFieldtype is not reactive to changes in its :value prop

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#803]
We noticed that fields of type `assets` don't react when their `value` changes. It occured when editing the same page with multiple users: the one selecting an assets sees the correct thumbnail, but for other users on the page, the value changed, but `this.assets` in AssetsFieldtype never updated (since `value` isn't watched).

This is the same type of bug we fixed together for GridFieldtype, where a component-local variable was used for state and was disconnected from the fieltype's `value`.

**Comment by sauerbraten** [comment]
Very likely still an issue.

**Comment by jasonvarga** [comment]
There's a watcher on the `value`.

https://github.com/statamic/cms/blob/1a9b4c6e090dc38699114306ea8512ea0c231c4d/resources/js/components/fieldtypes/assets/AssetsFieldtype.vue#L469-L473

If you can confirm it's happening though (and not just "likely") we'll definitely reopen this.
