### ISSUE TITLE
CP Images not loading on live server but fine work on local server

### ISSUE THREAD

**Issue by umerdev228** [statamic/cms#8040]
### Bug description

Our Statamic CMS works fine on local server but when deployed to server images not loading on CP. Project deployed on root domain, not on subdomain.

![Screenshot_2](https://user-images.githubusercontent.com/75834709/235887329-b90e4420-b0d0-4dea-988a-cbeacae86ebb.png)

### How to reproduce

upload images from assets CP

### Environment

```yaml
production
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
Please add more details about the site's environment using the `php please support:details` command.

**Comment by umerdev228** [comment]
![image_2023_05_03T10_44_59_356Z](https://user-images.githubusercontent.com/75834709/235895680-95f6102e-0704-4fba-88cc-a9fa610a26f9.png)
![image_2023_05_03T10_45_32_309Z](https://user-images.githubusercontent.com/75834709/235895687-af463f47-944e-46c7-b376-cdc8e420d52e.png)

**Comment by umerdev228** [comment]
php please assets:generate-presets

this is the solution

**Comment by jasonvarga** [comment]
That shouldn't be a solution. But what would have been helpful is the error you see for those image urls.

**Comment by edalzell** [comment]
@umerdev228 are you using S3 for your assets?

**Comment by jackmcdade** [comment]
Closing because we need more info and haven't gotten any. Feel free to reopen!
