### ISSUE TITLE
[4.x] Dragging a field into new blueprint section requires two attempts

### ISSUE THREAD

**Issue by o1y** [statamic/cms#8063]
### Bug description

If I drag a field into a previously created blueprint section, it only works on the second attempt. Dragging the field into an empty section works as expected.

### How to reproduce

1. Add new Blueprint section.
2. Drag an existing field into the new section.

![2023-05-05 18 42 00](https://user-images.githubusercontent.com/1102712/236517706-a42c822d-6088-4994-9387-f88242471722.gif)

### Environment

```yaml
v4 master
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
We wanted to be sure you really meant it.

**Comment by jasonvarga** [comment]
Fixed by #8065
