### ISSUE TITLE
No Gapcursor between Bard sets when Bard is in fullscreen mode

### ISSUE THREAD

**Issue by o1y** [statamic/cms#8069]
### Bug description

You cannot add a cursor between two sets when Bard is in fullscreen mode.

### How to reproduce

1. Add two Bard sets.
2. Try to add another set in between, when Bard is in fullscreen mode.

![2023-05-07 18 49 24](https://user-images.githubusercontent.com/1102712/236691197-3d293ceb-eed3-4ee3-a8bf-630310cb4fcb.gif)

### Environment

```yaml
3.4.10 / v4.0.0-beta.4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

### Additional details

The issue can be resolved by removing the `flex flex-col` from [bard.css#L223](https://github.com/statamic/cms/blob/master/resources/css/components/fieldtypes/bard.css#L223). I have no idea why there is a flex layout in fullscreen mode only, so I'm not feeling confident to create a pull request for that .. 😅

**Comment by jasonvarga** [comment]
Fixed by #8074
