### ISSUE TITLE
[4.x] Entire publish form gets highlighted when accidentally dragging during bard set selection

### ISSUE THREAD

**Issue by o1y** [statamic/cms#8070]
### Bug description

When accidentally clicking and dragging with the trackpad while selecting a set from set picker, this will cause the entire text on the publish form to be selected. Feel free to decide whether this is a bug or not. Personally, I've experienced this issue a few times ... maybe I should avoid doing it that way 🤷‍♂️

### How to reproduce

* Click and drag on a Label in Bard's set picker

![2023-05-07 13 43 19](https://user-images.githubusercontent.com/1102712/236692103-f95de38c-79ee-4bcb-a80d-396cb9d96361.gif)

### Environment

```yaml
v4.0.0-beta.4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
What browser are you using?

I can't recreate it, but if you can, maybe you can try fixing it by adding the `select-none` tailwind class to the set picker?
