### ISSUE TITLE
Demo SEO Pro error 500

### ISSUE THREAD

**Issue by generator85** [statamic/cms#8098]
### Bug description

When you open the demo from statamic.com, the SEO Pro plugin throws a Server Error (500). 

### How to reproduce

Go to statamic.com, press the "Try the demo" button. Login and then go to Tools / SEO Pro / Reports (or Site Defaults).

### Environment

```yaml
statamic.com
```

### Installation

Other (please explain)

### Antlers Parser

None

### Additional details

Was asked to create a ticket, but there doesn't seem to be a repo for the homepage or the demo environment.

**Comment by duncanmcclean** [comment]
Please open the issue in [the addon's repository](https://github.com/statamic/seo-pro/issues). This is the repository for the CMS itself.
