### ISSUE TITLE
[4.x] Duplicate translation key

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#8106]
### Bug description

When translating the new keys for fr.json using the translator command, found both `Toggle FullScreen Mode`(new key) and `Toggle Fullscreen Mode`(old key, already translated)

S or s?

### How to reproduce

update your locale language file using the translator command

### Environment

```yaml
4.0.0 updated from latest 3.4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by jasonvarga** [comment]
Lowercase s. I've fixed this in #8108, thanks!
