### ISSUE TITLE
Template field options obscured by section

### ISSUE THREAD

**Issue by wesort** [statamic/cms#8117]
### Bug description

Focusing a `Template` field when a _Section_ is below it and the template options are covered up by the _Section_. 

### How to reproduce

- Go to [demo.statamic.com and edit a blueprint](https://demo.statamic.com/cp/collections/pages/blueprints/page/edit)
- Create a new _Section_ in the `Main` _Tab_ and move the `Content` field into it > Save

![Screenshot 2023-05-11 13 54 10](https://github.com/statamic/cms/assets/3920126/cf636d1f-effe-45ed-8051-9958e693e6bb)

- [Create a new page using the `Page` blueprint](https://demo.statamic.com/cp/collections/pages/entries/create/default?blueprint=page)
- Select a template and see that the _Section_ covers the list options (z-index?)

![Screenshot 2023-05-11 13 54 18](https://github.com/statamic/cms/assets/3920126/528edcc6-914c-4b5d-875a-d2090acf5f2d)

### Environment

```yaml
demo.statamic.com
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by mundgold** [comment]
I have upgradet to Statamic 4.1.0 
the dropdown menu is still behind the following element

![image](https://github.com/statamic/cms/assets/5293053/1b441b35-9667-4db4-8c92-6adcdc7b1c93)

**Comment by jasonvarga** [comment]
What fieldtype is that, @mundgold ?

**Comment by mundgold** [comment]
It's the Link Fieltype @jasonvarga

**Comment by jasonvarga** [comment]
Thanks, there's #8123 for that.
