### ISSUE TITLE
Structure: Add possibility to change the "Create Page" label

### ISSUE THREAD

**Issue by wanze** [statamic/cms#812]
I think it would be neat if we could customize the "Create Page" label of the button when managing entries of a collection. Let's say that I have a collection of "team members" and I use a structure to group team members by departments. From the content editor's perspective, a button "Create Team-Member" fits better than "Create Page", because he/she is not managing pages in this structure.

**Comment by jasonvarga** [comment]
Should be irrelevant in the next release with all the structure-related changes.

The button is now `Create Entry` with a dropdown containing all the available blueprint names. In your case you probably have `Team Member`.
