### ISSUE TITLE
[4.x] Missing translation: Default color

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#8170]
### Bug description

When I add a Color fieldtype, the new "Default Color" text is partially translated.

<img width="950" alt="Capture d’écran 2023-05-18 à 19 18 44" src="https://github.com/statamic/cms/assets/1823359/9b2e9e45-6449-4cbd-bf26-d2433f3a8873">

"Choose a default color." isn't in my fr.json file (I am using the php translator command)

### How to reproduce

Set your user language to anything else than English. Add a Color Fieldtype to a Blueprint.

### Environment

```yaml
Statamic 4.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
It's definitely translated. If you run `php translator generate fr`, it'll appear in the file.

**Comment by ebeauchamps** [comment]
Sorry @jasonvarga , but when I ran this command it only detected the "Default Color" key.
I am going to add the second key by hand in my file and complete my first PR then
