### ISSUE TITLE
Conditions on imported fieldsets with prefixes isn't working

### ISSUE THREAD

**Issue by twd3** [statamic/cms#830]
Trying to make one field hidden and only show when other field in same fieldset is toggled on via cp.

**Comment by goellner** [comment]
just ran into the same issue

**Comment by stuffedmotion** [comment]
Would love to see this fixed!

**Comment by hmalaud** [comment]
Sorry to comment on an old issue, but I still have the issue: `validate: "after_or_equal:{this}.prefixed_field"` works but from what I understand this should be automatically done by just simply using `validate: "after_or_equal: {this}.field` (I'm importing a fieldset in a Replicator), right? 
I can open an issue regarding this if bug is confirmed.
