### ISSUE TITLE
Live preview only loads javascript on first render

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#832]
We noticed that the live preview only loads resources like Javascript referenced from the HTML we provide via our custom Entry's `toLivePreviewResponse()` function once, when the content is written into the iframe the first time. After that, changing any value results in a visual update, but when an additional JS dependency appears, it isn't fetched, which in our case results in visually broken iframe content.

**Comment by jasonvarga** [comment]
Closing this issue to keep organized. If you can provide a reproducible example of the bug we'd be more than happy to address it. Or, perhaps a PR to address this issue in a way that doesn't add additional requests for people not experiencing it.
