### ISSUE TITLE
Taxonomies in collections are not syncing with origin

### ISSUE THREAD

**Issue by Oleafeon** [statamic/cms#8338]
### Bug description

When we add an entry with translations and add a taxonomy the taxonomy will be set on all translations but when we change the taxonomy on the origin the synced taxonomies are not changed to the new taxonomy

I made a video that explains shows what i mean
https://www.youtube.com/watch?v=Zsy4kI-i0pg

### How to reproduce

1. Make a new entry
2. connect a taxonomy
3. switch to different site
4. check if the taxonomy is synced with origin
5. go back to origin site
6. change origin taxonomy
7. go back to other site
8. see that the taxonomy is still the old one

### Environment

```yaml
Statamic 3.4.11 Pro
Laravel 8.83.27
PHP 8.2.6
Stache Watcher Disabled
Static Caching Disabled
4rn0/statamic-v3-image-optimizer 1.1.1
aryehraber/statamic-logbook 2.2.0
doublethreedigital/duplicator 3.0.0
optimoapps/statamic-bard-text-align 1.0.3
rias/statamic-button-box 2.0.3
spatie/statamic-algolia-places 1.1.0
spatie/statamic-responsive-images 3.1.3
webographen/statamic-admin-log 1.0.8
webographen/statamic-widget-cache-controller 1.0.2
withcandour/aardvark-seo 2.0.31
withcandour/statamic-markdown-table 1.0.0-beta
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by wanze** [comment]
Same issue: https://github.com/statamic/cms/issues/6714
This happens with any non-localized fields, not just taxonomies. See details and solution in the linked issue.
