### ISSUE TITLE
Antlers Profiler - missing expressions in "view graph"

### ISSUE THREAD

**Issue by dadaxr** [statamic/cms#8361]
### Bug description

Not sure if it's a bug but kinda look surprising to me ...

In the new Antlers Profiler (debug bar) some antlers expressions are only shown in "expression graph" but not in "view graph" : 

I have a "home" template with this code : 

```
<div id="homePage-projectsSection-columns">
{{ projects = {collection:projects limit="4"} }}
{{ loop from="1" to="2" }}
    <div class="homePage-projectsSection-col">
        {{ projects scope="project" }}
            {{ partial:preview-project :project="project" :isLarge="first" }}
        {{ /projects}}
    </div>
{{ /loop }}
</div>
```

In expression graph they do appear  : 

![image](https://github.com/statamic/cms/assets/1267495/dcf74341-0ae9-47f7-afd7-00a6655f4d52)

But not in "view graph" : 

![image](https://github.com/statamic/cms/assets/1267495/dbb7bdb6-8f4d-431a-9b67-02d54533c739)

(I have toggled down only the "home" template, but I've double checked before, and the missing expressions dont appear elsewhere)

### How to reproduce

dont know :roll_eyes: 

### Environment

```yaml
statamic 4.9
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by dadaxr** [comment]
The problem was also present in statamic 4.8

**Comment by JohnathonKoster** [comment]
Would you be able to provide the contents of your `home.antlers.html` file and the `layout.antlers.html` file?

I am not able to reproduce this issue.

**Comment by dadaxr** [comment]
Ok so I tried to narrow down the problem. 

I will create One comment per "issue"

**Comment by dadaxr** [comment]
I have a very simple "page" entry (from a page collection) : 


```
---
id: 65ecee1e-3585-4a14-8c0a-061ffedb9024
blueprint: home
template: templates/test
layout: false
title: 'home test'
customers_logo:
  - megasun.svg
  - Younup.svg
updated_by: 76f54a89-16a4-4f48-b677-ce2bc3e06eeb
updated_at: 1687866398
---
```

I have disabled the "layout" and force the template to "test" which is a minimalist template to avoid side effect.

I've encountered different strange behaviors : 

### number one : some tag seems to be outputed twice in view graph 

first a working example : ( only 5 rows in view graph)
```
<ul>
        {{ collection:articles }}
            <li>{{ title }}</li>
        {{ /collection:articles }}
    </ul>
    
    <ul>
        {{ customers_logo }}
        <li>logo url : {{ url }}</li>
        {{ /customers_logo }}
    </ul>
```
![image](https://github.com/statamic/cms/assets/1267495/9b64bddf-691b-4591-a952-d69fea9103f5)


Then the same example but just inverting the 2 "ul" order : 

```
<ul>
    {{ customers_logo }}
    <li>logo url : {{ url }}</li>
    {{ /customers_logo }}
</ul>

<ul>
    {{ collection:articles }}
        <li>{{ title }}</li>
    {{ /collection:articles }}
</ul>
```

![image](https://github.com/statamic/cms/assets/1267495/a383a2f6-40d7-413a-b5d2-e8b116a0f80c)


=> there are 6 rows in view graph, the last one is duplicated : why ?

As you can see, there is only 1 article in my "articles" collection ... BUT If I now add a 2nd article ... and retry the previous working template (the first one) ... it has now also another "additional" row : 

![image](https://github.com/statamic/cms/assets/1267495/1d7e98a4-5de0-4b45-9dd1-cd530d09401f)

**Comment by dadaxr** [comment]
### number 2 : some expressions are wiped out from view graph (original issue)

Still using the same "test" template with no layout...

I now have added a third entry in my articles collection ... and guess what : the issue is weirder !

First, a "working" example (customers_logo displayed first)

```
<ul>
    {{ customers_logo }}
    <li>logo url : {{ url }}</li>
    {{ /customers_logo }}
</ul>
<ul>
    {{ collection:articles }}
        <li>{{ title }}</li>
    {{ /collection:articles }}
</ul>
```

![image](https://github.com/statamic/cms/assets/1267495/84166e67-34d0-4d1a-8591-0257937c9db7)

But If I display articles first ...

```
<ul>
    {{ collection:articles }}
        <li>{{ title }}</li>
    {{ /collection:articles }}
</ul>
<ul>
    {{ customers_logo }}
    <li>logo url : {{ url }}</li>
    {{ /customers_logo }}
</ul>
```

![image](https://github.com/statamic/cms/assets/1267495/d7fd8aaa-cb2e-4a34-8547-ccd7fc809106)


@JohnathonKoster for what it worth, here are my 3 articles md content

```
---
id: 88b63521-6092-42d6-a64b-2a2fb48339b2
blueprint: articles
title: 'first article'
author: 76f54a89-16a4-4f48-b677-ce2bc3e06eeb
updated_by: 76f54a89-16a4-4f48-b677-ce2bc3e06eeb
updated_at: 1648557881
hero_image:
  - 002.png
---
balbla
```

```
---
id: 832b8692-b8fa-4b61-86fb-7311ab17df0b
blueprint: articles
title: 'Second article'
author: 76f54a89-16a4-4f48-b677-ce2bc3e06eeb
updated_by: 76f54a89-16a4-4f48-b677-ce2bc3e06eeb
updated_at: 1687871682
---
testing some stuff
```

```
---
id: cb30cacf-2f1b-4392-b2ba-cf6f4dd73300
blueprint: articles
title: 'third article'
author: 76f54a89-16a4-4f48-b677-ce2bc3e06eeb
updated_by: 76f54a89-16a4-4f48-b677-ce2bc3e06eeb
updated_at: 1687873346
---
dsfdsfdsfsd
```
