### ISSUE TITLE
Access level to Statamic\Extensions\FileStore::path() must be public

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#8364]
### Bug description

I just upgraded to the latest 4.x and got this error:

`Access level to Statamic\Extensions\FileStore::path() must be public (as in class Illuminate\Cache\FileStore)`

at `vendor/statamic/cms/src/Extensions/FileStore.php:11`

I also tried to downgrade, but the error remains.

### How to reproduce

I just ran `composer update`.

### Environment

```yaml
Cannot run command. Terminal outputs the error message. Cannot even downgrade...
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by UglyMau** [comment]
I have the same problem (error) in installation

**Comment by jasonvarga** [comment]
Yup. Just tagged it. Should be available for you now.
