### ISSUE TITLE
Call to a member function field() on null on selecting entry and viewing collection

### ISSUE THREAD

**Issue by krokusmoen** [statamic/cms#8374]
### Bug description

I have a collection with it's own blueprint.

Suddenly I am unable to view the collection index and choosing entries from that collection with the error message "Call to member function field() on null".

This breaks a big site and not sure how to proceed. It would be a nightmare to create a new collection and manually recreate all entries in that new collection.

What could be wrong?

### How to reproduce

Run Statamic 3.3.68

### Environment

```yaml
Statamic 3.3.68, PHP 7.4, Laravel 8
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
Are you able to provide the full stack trace?

**Comment by krokusmoen** [comment]
Call to a member function field() on null {"userId":"cf911b50-1bc3-4861-9ff9-beef824f3d86","exception":"[object] (Error(code: 0): Call to a member function field() on null at /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Entries/Entry.php:848)
[stacktrace]
#0 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Query/ResolveValue.php(47): Statamic\\Entries\\Entry->getQueryableValue('title')
#1 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Query/ResolveValue.php(29): Statamic\\Query\\ResolveValue->getItemPartValue(Object(Statamic\\Entries\\Entry), 'title')
#2 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Query/ResolveValue.php(17): Statamic\\Query\\ResolveValue->resolveItemPartValue(Object(Statamic\\Entries\\Entry), 'title')
#3 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Indexes/Value.php(18): Statamic\\Query\\ResolveValue->__invoke(Object(Statamic\\Entries\\Entry), 'title')
#4 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Indexes/Value.php(12): Statamic\\Stache\\Indexes\\Value->getItemValue(Object(Statamic\\Entries\\Entry))
#5 [internal function]: Statamic\\Stache\\Indexes\\Value->Statamic\\Stache\\Indexes\\{closure}(Object(Statamic\\Entries\\Entry), '7b056732-8b12-4...')
#6 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(695): array_map(Object(Closure), Array, Array)
#7 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Indexes/Value.php(13): Illuminate\\Support\\Collection->map(Object(Closure))
#8 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Indexes/Index.php(90): Statamic\\Stache\\Indexes\\Value->getItems()
#9 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Indexes/Index.php(74): Statamic\\Stache\\Indexes\\Index->update()
#10 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Stores/Store.php(46): Statamic\\Stache\\Indexes\\Index->load()
#11 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(104): Statamic\\Stache\\Stores\\Store->index('title')
#12 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(742): Statamic\\Stache\\Query\\EntryQueryBuilder->Statamic\\Stache\\Query\\{closure}(Object(Statamic\\Query\\OrderBy), 0)
#13 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(111): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#14 [internal function]: Statamic\\Stache\\Query\\EntryQueryBuilder->Statamic\\Stache\\Query\\{closure}('sider', 6)
#15 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(695): array_map(Object(Closure), Array, Array)
#16 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Query/EntryQueryBuilder.php(112): Illuminate\\Support\\Collection->map(Object(Closure))
#17 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Query/Builder.php(75): Statamic\\Stache\\Query\\EntryQueryBuilder->getOrderKeyValuesByIndex()
#18 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Stache/Query/Builder.php(28): Statamic\\Stache\\Query\\Builder->orderKeys(Object(Illuminate\\Support\\Collection))
#19 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Query/Builder.php(532): Statamic\\Stache\\Query\\Builder->get(Array)
#20 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Fieldtypes/Entries.php(94): Statamic\\Query\\Builder->paginate()
#21 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Controllers/CP/Fieldtypes/RelationshipFieldtypeController.php(18): Statamic\\Fieldtypes\\Entries->getIndexItems(Object(Statamic\\Http\\Requests\\FilteredRequest))
#22 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Fieldtypes\\RelationshipFieldtypeController->index(Object(Statamic\\Http\\Requests\\FilteredRequest))
#23 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#24 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Fieldtypes\\RelationshipFieldtypeController), 'index')
#25 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#26 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#27 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#50 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#59 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#60 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#61 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#62 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#63 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/kgrpet/Code/ytf/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/kgrpet/Code/ytf/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /Users/kgrpet/Code/ytf/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /Users/kgrpet/Code/ytf/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#90 /Users/kgrpet/Code/ytf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#91 /Users/kgrpet/Code/ytf/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#92 /Users/kgrpet/.composer/vendor/laravel/valet/server.php(250): require('/Users/kgrpet/C...')
#93 {main}
"}

**Comment by ryanmitchell** [comment]
Looks like you have any entry that has no blueprint associated with it, or the blueprint no longer exists.

**Comment by krokusmoen** [comment]
@ryanmitchell 

There are several of the pages in this collection that does not have blueprint: set on them. Since it is a huge collection it would take take to test this, but would it fail without a blueprint when the default is set?

**Comment by ryanmitchell** [comment]
You could try to do it programatically

```
\Statamic\Facades\Entry::whereCollection('your_collection_handle')->each(function ($entry) {
   if (! $entry->get('blueprint')) {
      $entry->merge(['blueprint'=> 'xxx'])->save();
   }
});
```

**Comment by krokusmoen** [comment]
Found the cause of the bug.

Previously I enabled "Links" on this collection. Added one entry and it cause problems. I then disabled "Links" and the .md file was still in the directory.

When I now deleted it everything in this collection worked again.

Thanks for the help. I discovered this when browsing through every file in the collection directory for blueprint.
