### ISSUE TITLE
Dropdown component needs to be location aware

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#839]
When the replicator is the last field in a fieldset, the Add Set dropdown can appear off screen. Dropdown placement should flip when there is not enough space on the screen.

<img width="1168" alt="Screen Shot 2019-10-24 at 11 16 47 am" src="https://user-images.githubusercontent.com/414211/67532443-f34e2400-f711-11e9-9d24-5db3e444497d.png">

**Comment by jackmcdade** [comment]
The best way to fix this is for us to replace all popover styles with [Popper 2.x](https://popper.js.org/) components. Alas, all the vue components we rely on use popper 1.x. Nuts.

**Comment by jackmcdade** [comment]
Fixed in 5d14468e48ca9d1ec11304efc08956d2dbcac8f4 (on a branch but will merge in soon).
