### ISSUE TITLE
Cache Tag Does Not Render Strings using Sections

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#8399]
### Discussed in https://github.com/statamic/cms/discussions/8394

<div type='discussions-op-text'>

<sup>Originally posted by **martbock** July  3, 2023</sup>
I have an Antlers template that uses a user-scoped cache tag to render HTML content wrapped in partials. For some reason, Antlers renders obscure IDs like `__literalReplacement::_3bc4ba0c73ddc55b90df9094c7d2676e` (cache identifier?) instead of the intended strings.

Does anyone have a tip on what could be wrong here?

Shortened template example:

```antlers
{{ cache scope="user" }}
    ...
    {{ partial:card }}
        {{ section:header }}
            {{ user }}
                <div>
                    Hello {{ name }}
                </div>
            {{ /user }}
        {{ /section:header }}
    {{ /partial:card }}
    ...
{{ /cache }}
```

First render (uncached): `Hello Jon Doe`
Subsequent renders (cached): `__literalReplacement::_3bc4ba0c73ddc55b90df9094c7d2676e`</div>

**Comment by martbock** [comment]
Hey :smile: I have just revisited the issue and have tried my previous setup with the current Statamic version 4.47.0. Unfortunately, it seems that the behavior I described is still present.

When I have a template containing something like the following, the title is still only rendered on the first visit and is replaced by  `__literalReplacement::XYZ` on subsequent requests.

```antlers
{{ cache tags="foo" }}
    {{ partial:page-template }}
        {{ section:title }}
            {{ title }}
        {{ /section:title }}

        ...

    {{ /partial:page-template }}
{{ /cache }}
```
