### ISSUE TITLE
Structure: Contextual add child link doesn't respect max depth setting

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#843]
Not sure if this is a duplicate of #783. 

When setting a Max depth on a Structure it does not appear to work or save to the Structure's settings.

<img width="1489" alt="Screen Shot 2019-10-24 at 2 27 52 pm" src="https://user-images.githubusercontent.com/414211/67534067-2d222900-f718-11e9-87c9-193c04fc344a.png">

**Comment by jackmcdade** [comment]
Thanks for the heads up! Structures are getting a bit of a rework this week. Stay tuned.

**Comment by jasonvarga** [comment]
Fixed for next release.
