### ISSUE TITLE
Saving CP Nav Preferences remove spaces before ampersand (&) characters

### ISSUE THREAD

**Issue by Swennet** [statamic/cms#8477]
### Bug description

In the CP Nav, when you have a section title in the following format: "Foo & Bar". Saving the CP Nav (without editing the ampersanded section title) removes a space, changing it to "Foo& Bar".

### How to reproduce

1. Create a new section "Foo & Bar"
2. Save the CP Nav
3. Edit something else on the CP Nav and save the Nav.
4. The section title is now "Foo& Bar" (without the space before &)

Note: This only happens on a second save of the Nav. On first save, the space before the ampersand is not removed.

### Environment

```yaml
Statamic 4.12.0 and PHP 8.2
```

### Installation

Existing Laravel app

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
Are you able to record a video? I'm unable to reproduce this bug.

**Comment by Swennet** [comment]
@duncanmcclean 

https://github.com/statamic/cms/assets/18725185/08102747-fa76-40b0-945d-086201a80520
