### ISSUE TITLE
Generating one thumbnail for one image would load all image infoes

### ISSUE THREAD

**Issue by videni** [statamic/cms#8484]
### Bug description

I also reported   [here ](https://github.com/statamic/eloquent-driver/issues/191), I thought it is supposed to be fixed in the `statamic/eloquent-driver`, it turns out it is best to do in this repo. 

### How to reproduce

It is very easy to reproduce

1. Enable the statamic/eloquent-driver
2. Try to acess an image thumbnail.

Please check the link above. 

### Environment

```yaml
any version of statamic, statamic/eloquent-driver
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by ryanmitchell** [comment]
Just FYI this isnt just eloquent driver related which is why I suggested moving it to statamic/cms. 

At the moment the way we check if a file exists is to get all the files in the container, then check the path is in the keys. This doesn't seem like a very performant way to approach this.

Maybe adding a `fileExists` method to AssetContainerContents would be a better approach?

**Comment by jasonvarga** [comment]
Do you have the stache watcher enabled? In that case, this is expected.

Disable the stache watcher, then it should only load the file listing one time and it will then be cached.

**Comment by videni** [comment]
@jasonvarga , hi,  even the one time cost is also not appceptable in my case, I got lots of images which are uploaded to aws s3 ahead,  may be 500,000 - 1000,000 pictures.

**Comment by jasonvarga** [comment]
Ok, fair.

I'm just curious, are you actually using all those assets?

**Comment by duncanmcclean** [comment]
Closing in favour of #7317 which relates to a similar issue with lots of assets.

In the meantime, I believe a [recent version](https://github.com/statamic/eloquent-driver/releases/tag/v3.0.0) of the Eloquent Driver includes a database-driven asset query builder which should help with performance.
