### ISSUE TITLE
How to use a blank `taggable` fieldtype is unclear

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#8534]
### Bug description

Since [this PR](https://github.com/statamic/cms/pull/8456) I've seen a few people struggle with the value of the config field not saving, which is happening because you have to hit enter to add it to the list first. At the moment it's not really clear that you have to do that, other than the X icon on the right this just looks like a regular text field:

![Screenshot 2023-08-02 at 10 42 04](https://github.com/statamic/cms/assets/126740/158882df-242c-4661-9294-d616389ee5f7)

I don't know what the best solution is. A quick-fix might just be adding a placeholder to the field, something like this:

![Screenshot 2023-08-02 at 10 43 00](https://github.com/statamic/cms/assets/126740/00030493-a8fe-40b1-96bf-c201ce571e71)

But maybe there's a better way that doesn't require spelling it out?

### How to reproduce

Try to add a query scope to an entries field.

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.14.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
We could probably make it commit whatever is in the field on `blur`?
