### ISSUE TITLE
is_image variable does not include SVG 

### ISSUE THREAD

**Issue by exophunk** [statamic/cms#8546]
### Bug description

`{{ is_image }}`

There is an [is_image](https://statamic.dev/variables/is_image) variable, that can be used to check if the current context is an image. It validates for ['jpg', 'jpeg', 'png', 'gif', 'webp'](https://github.com/statamic/cms/blob/c588fc164f72d16a95154d7d6e76a4d626d20bc3/src/Assets/Asset.php#L476), but not for `svg`

isn't an SVG also an image? Internally, there is also an `isSvg()` method on the [Asset](https://github.com/statamic/cms/blob/c588fc164f72d16a95154d7d6e76a4d626d20bc3/src/Assets/Asset.php#L484), but this method is [not passed](https://github.com/statamic/cms/blob/c588fc164f72d16a95154d7d6e76a4d626d20bc3/src/Assets/AugmentedAsset.php#L25) as variable to the antlers frontend.

I would argue that either `is_image` should also return true for SVG or `is_svg` should be available in antlers.

Use case: Check if an assets is a renderable image and then use a image component (that also works for svg).

### How to reproduce

Output an SVG in antlers and check if it is an image:

```antlers
{{ asset :url="image" }}
    {{ if is_image }}
        {{# Not true for SVG #}}
    {{ /if }}

    {{# Method not available #}}    
    {{ if is_svg }}
    {{ /if }}
{{ /asset }}

### Logs

_No response_

### Environment

```yaml
Laravel Version: 10.14.1
PHP Version: 8.2.8
Composer Version: 2.5.8
Statamic Version: 4.9.2 PRO
```

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
We can add `is_svg` to Antlers. Changing the logic of `is_image` at this point would have too much impact.
