### ISSUE TITLE
Clearing the application cache causes the cache invalidator to fail

### ISSUE THREAD

**Issue by miicah** [statamic/cms#8566]
Versions: can replicate on 3.4 and 4.8
Static caching strategy: full

## How to reproduce

1. Visit a page so a static page is generated
2. Edit the content on that page and click publish
   - The file in the static cache is correctly invalidated and deleted
   - Visit the page again and the static page is created
3. Now go and clear the application cache
4. Go back to the page, change some content and click publish
5. The page is not invalidated and thus the original static file remains in the static folder

From what I can understand, this is happening because clearing the application cache means the entire stache is blown away and there is never a call to go back and re-index (re-check?) all of the files in the content folders.

**Why do we do this?** Because we need to upload very large files to Statamic and cannot use the CMS, so they are copied directly into the assets folder - unfortunately this won't show up in the CMS until the application cache is cleared. This is how we came across the issue, but there are many reasons you might need to clear the application cache.

The simple solution is to run `php please static:warm` but this doesn't work for us as our production server is behind authentication, so the guzzle requests don't actually hit any of the real pages.

What I'm trying to understand is if this is a bug or an oversight in how full static caching is implemented? Should a `php please stache:warm` scan the static folders as well?

_Originally posted by @miicah in https://github.com/statamic/cms/discussions/8502_

**Comment by duncanmcclean** [comment]
Closing in favour of #7333.
