### ISSUE TITLE
Creating a field with a handle named "views" in a Blueprint causes error

### ISSUE THREAD

**Issue by pekka** [statamic/cms#8575]
### Bug description

Creating a field with a handle named "views" in a Blueprint causes the following error:

![image](https://github.com/statamic/cms/assets/262464/4084938c-745f-46ed-959a-df0914c941ea)

### How to reproduce

- Create a new collection (in my case, it was "Landing pages")
- Edit the blueprint for the collection
- A field named "views" (in my case, a numeric text field to count how many views the landing)
- Create an entry in the collection and go to the front-end

### Environment

```yaml
Statamic 4.17.0
Statamic Peak (latest)
PHP 8.2
All running in a local dev environment on MacOS
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
I'm marking that as reserved in #8576. It'll stop you from using that as a variable name in the future.

The `views` variable is used under the hood for keeping track of any view-specific data. e.g. in a template you can have YAML front matter like this:

```antlers
---
hello: world
---
{{ view:hello }} // outputs "world"
```
