### ISSUE TITLE
Assets appear broken/missing when uploading multiple at once

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#8587]
### Bug description

Experiencing this issue when uploading multiple assets at once:

1. When you upload some of them appear as broken or they're completely missing
2. All files are correctly uploaded into the filesystem
3. All files are reported as uploading successfully (toast notification)
4. Refreshing the page does not resolve it
5. Clearing the cache and then refreshing does resolve it

- It's pretty inconsistent and not specific to certain files
- I can replicate this issue all the way back to v4.0 and with both PHP 8.1 and 8.2 and on multiple servers
- Far as I can tell it only happens with the stache watcher switched off
- The stache lock is enabled and set to the default 30 seconds

Heres a video, notice I'm uploading 5 files but only 4 appear (3 broken), then clearing the cache restores them all:

https://github.com/statamic/cms/assets/126740/2c1b11a4-bdc3-4ca4-a7d1-46dd19717e8e

### How to reproduce

Try to upload multiple files into an asset container.

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.17.0 Solo
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

**Comment by jacksleight** [comment]
I'm also seeing this randomly, not sure if it's related:

![Screenshot 2023-08-16 at 17 24 03](https://github.com/statamic/cms/assets/126740/4883cf56-5c41-4be8-9a03-9dcfaee3fa3e)

**Comment by jacksleight** [comment]
I've been doing some more digging and this appears to be some kind of race condition when updating the stache indexes:

- The files that appear in the list but are broken aren't in the ID index
- The files that are completely missing from the list aren't in the folder index 
   (I assume that's index that's used for the list, files were often missing from the path and basename indexes as well)

I've also updated the description/video above.

**Comment by jasonvarga** [comment]
Thanks for the digging. Maybe the simplest short term fix is to figure out how to get that uploader package to upload files one at a time.

**Comment by jacksleight** [comment]
Looks as though it only handles one file per instance, the `Uploader.vue` component is [creating a new instance for each file](https://github.com/statamic/cms/blob/4.x/resources/js/components/assets/Uploader.vue#L123), so I guess it would require some kind of queueing logic in that component?

**Comment by jasonvarga** [comment]
Done. Can you check out #8592 and see if it fixes the issue for you?

**Comment by jacksleight** [comment]
Yep perfect! Thank you!

**Comment by jasonvarga** [comment]
Thanks for confirming.
