### ISSUE TITLE
Code field is executed in collapsed set view

### ISSUE THREAD

**Issue by Swennet** [statamic/cms#8596]
### Bug description

When using a code field with some HTML in it, collapsing a "set" actually executes the code in set bar, which leads to weird behavior with iframes and stuff like that.

![Screenshot 2023-08-18 at 13 23 49](https://github.com/statamic/cms/assets/18725185/5be2d6e2-c6ae-4440-9453-f68211e62970)

### How to reproduce

Paste some HTML (like an iframe) in a set's "Code" field, then collapse the set.

### Environment

```yaml
Statamic 4.17.0
```

### Installation

Existing Laravel app

### Antlers Parser

None

**Comment by robdekort** [comment]
For now you can probably prevent this by setting `replicator_preview: false` on your code field.
