### ISSUE TITLE
Select fieldtype - Add newly created tags to the options list?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#8639]
### Bug description

Hi

I've got a select fieldtype, allow additions and push tags are turned on, but new items aren't added to the options list.
<img width="1207" alt="Screenshot 2023-08-29 at 05 58 16" src="https://github.com/statamic/cms/assets/72254741/23b50afa-a066-4209-8c95-37507d1d610a">

When creating an entry that uses the select fieldtype I can add additional options, but they don't get added to the options list? I mean when I create another post, the new option I've just added isn't available.

Is it supposed to work like that? The way I read it "Add newly created tags to the options list." Anything added to the list is then available in other posts that use the same Blueprint?

30 second video shows the problem

https://github.com/statamic/cms/assets/72254741/04ac2c2d-393c-4b28-8d5b-8f8d4a6ad59a

### How to reproduce

Create an select fieldtype, add allow additions and push tags.

### Environment

```yaml
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.19.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Antlers: runtime

**Comment by ryanmitchell** [comment]
I believe it only adds them on that page view. 
But I agree - I have always expected it to act the way you are suggesting.
