### ISSUE TITLE
Display Order of Entries in Relationship is Not Respected

### ISSUE THREAD

**Issue by conradfuhrman** [statamic/cms#8723]
### Bug description

Created a new Collection that is orderable as shown below. 

![Screenshot 2023-09-18 at 12 52 40 PM](https://github.com/statamic/cms/assets/455824/6af0fdd0-a3ef-4011-b2dc-589e58e5700d)

On a seperate collection where this is a linked field with the dropdown selection as the display, the list of items doesn't appear in the proper order as set by the collections order:

![Screenshot 2023-09-18 at 12 49 49 PM](https://github.com/statamic/cms/assets/455824/81641c02-1fcf-4d36-b7dd-0ec1da98c200)

### How to reproduce

Create a collection that is orderable with only a title. Add a few items, re-order it. In a separate collection like pages, link this as a entry relationship field and ensure that dropdown is selected. When selecting an item from the dropdown the order of the elements will not match the order set in the collection.

### Environment

```yaml
Latest Statamic. Herd etc.
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment]
Note to self, or whoever ends up tackling this: It's because the ordering in the `entries` fieldtype doesn't have enough smarts. We even have a todo in there.

https://github.com/statamic/cms/blob/d98f8224f03f08b35574358d687b88e455f4c841/src/Fieldtypes/Entries.php#L159-L168
