### ISSUE TITLE
100mb limits on cloudflare

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#8769]
### Bug description

I'm getting 'request entity too large' responses when uploading audio assets which are over 100mb. This error is caused by the 100mb HTTP POST request size limits on CloudFlare free plans. I know this is technically a limitation of CloudFlare free plans but I imagine most Statamic users are on this plan. The business plan for 200mb uploads is a crazy price.

I have solved this problem before in my own applications by uploading files over 100mb directly to AWS compatible filesystems with JavaScript and Presigned URLs, bypassing the site's dns server and cloudflare limits. A lot of WordPress plugins would use a similar solution. I can open an idea if this is a possibility for Statamic.

Any suggestions for a workaround in the meantime would be appreciated. Unfortunately we have to host these audio files in our own cloud filesystems as we need to process them and generate custom audio waveforms. We can't use an external stream service to host our audio - It's a digital archive for a museum.

### How to reproduce

Try uploading a file over 100mb when using cloudflare free plan.

### Environment

```yaml
Laravel Version: 10.21.0
PHP Version: 8.2.5
Version: 4.20.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by ryanmitchell** [comment]
I dont think theres anything Statamic can offer to get around this as its effectively a hosting issue

**Comment by jasonvarga** [comment]
You'll need to build a fieldtype that uploads directly to the service of your choosing.

Our native assets fieldtype uses an `Uploader.vue` component under the hood and points to a Statamic URL. You can re-use this component but pass in the direct AWS URL, for example:

```html
<your-fieldtype>
  <uploader :url="theAmazonUrl" ... />
</your-fieldtype>
```
