### ISSUE TITLE
Variables not being overwritten by scope, regression by #8818 / v4.25.0

### ISSUE THREAD

**Issue by tobimori** [statamic/cms#8829]
### Bug description

I use a Replicator field as a Page Builder, and the following snippet to render my Sets as partials:

```
{{ blocks }}
	{{ partial src="page_builder/{type}" }}
{{ /blocks }}

```

Starting with 4.25, I have weird behaviour where variables set in such partials override variables in other partials.

### How to reproduce

Example code:

This is a partial used by the first Replicator set.
```
{{ items = verticals ?? {collection:verticals :taxonomy:tags:all="filter"} }}
{{ items limit="4" }}
	<div class="blabla loop">
	</div>
{{ /items }}
```

Now later, in a different partial, I want to loop through `{{ items }}` that should be set by the field.

```
{{ items }}
   ...
{{ /items }}
```

Now with the {{ blocks }} loop, my items variable should be overwritten, because {{ items }} is a field in my replicator set. Yet this doesn't happen, and it worked again when downgrading to 4.24.0

### Environment

```yaml
Statamic v4.26.0/4.25.0
works with v4.24.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by tobimori** [comment]
Also tagging @JohnathonKoster as author of the corresponding PR

**Comment by tobimori** [comment]
Hi @JohnathonKoster - did you find time to look at this issue? this is sadly blocking our upgrade for multi-site permissions.

**Comment by JohnathonKoster** [comment]
I have not looked into this issue (and generally rely on the core team assigning an issue/asking). Do you have a simple repository that reproduces your issue?

Thanks!

**Comment by tobimori** [comment]
Honestly, this makes no sense - but it seems upgrading to 4.30 fixed the issue. I swear it was previously fixed by rolling back 😂

**Comment by tobimori** [comment]
Ok no, it still doesn't work. But I can't pinpoint it.

**Comment by JohnathonKoster** [comment]
Is the project one you could share (even privately) to help look into and debug?

**Comment by tobimori** [comment]
i'll send you a message on discord
