### ISSUE TITLE
Can't use optional condition on collection

### ISSUE THREAD

**Issue by MattRogowski** [statamic/cms#8933]
### Bug description

I'm not sure if there is a way to do this I'm missing, but if you're filtering a collection based on a value passed to a query string, you'll have nothing returned if the query string is not supplied, as opposed to it returning everything.

### How to reproduce

On a URL such as `/resources?type=video`, if you wanted to filter entries by the blueprint used, you'd do this:

`{{ collection :from="mount" paginate="10" as="resources" :blueprint:is="get.type" }}`

However if no query string is supplied (i.e. just on `/resources`), you get no entries returned at all.

I feel like maybe there needs to be a way to optionally apply a condition, such as prefixing it with a `?`

`{{ collection :from="mount" paginate="10" as="resources" ?:blueprint:is="get.type" }}`

Right now I think only query scopes can achieve what I need here, but an optional condition would be a lot easier.

### Environment

```yaml
Version: 4.31.0 PRO
Laravel Version: 10.30.0
PHP Version: 8.1.21
Composer Version: 2.6.3
Environment: local
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by duncanmcclean** [comment]
Are you on the latest version of Statamic - 4.32.0? That release included a fix for this issue - see https://github.com/statamic/cms/pull/8915.

**Comment by MattRogowski** [comment]
Was on 4.31.0 (realised that wasn't int he info above). Just upgraded to 4.32 and it works if the query string is supplied but it empty (i.e. `/resources?type=`) but not if it's not supplied at all. I think this would be explained by Jason's feedback on leaving `null` values, as `get.type` would be null in this instance.

**Comment by ryanmitchell** [comment]
Did you try using void? https://statamic.dev/antlers#tag-parameters

`blueprint:is="get.type ?? void"`

**Comment by MattRogowski** [comment]
Ah that work, actually so does `blueprint:is="get.type ?? ''"`

Will treat this as not a bug then.
