### ISSUE TITLE
Recently my field labels started to be translated automatically by default

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#9014]
### Bug description

Something with the field labels changed recently: In German we call the default text size "Copy", now it shows "Kopieren" instead "Copy".

![Bildschirmfoto 2023-11-17 um 10 40 54](https://github.com/statamic/cms/assets/6337411/d87db3c4-c768-4c88-9dcc-08f6f40ffdc5)
![Bildschirmfoto 2023-11-17 um 10 41 07](https://github.com/statamic/cms/assets/6337411/e4132637-f0f1-43d6-b947-867c6b21a4b4)
![Bildschirmfoto 2023-11-17 um 10 42 09](https://github.com/statamic/cms/assets/6337411/45a64d36-32b9-43a5-a710-ac3734c1219b)

### How to reproduce

Give a field the label Copy and set your language to German.

Is there a way to prevent this behaviour?

### Environment

```yaml
Version: 4.34.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
This was introduced in #8664.

There's no way to disable the behaviour but you can override it by providing your own translation for `Copy` which'll get used instead. 

Create a file called `lang/de.json`:

```json
{
    "Copy": "Copy",
}
```

**Comment by ebeauchamps** [comment]
I second Jellyfish on this. Statamic should not impose a behavior, and #8664 should not have introduced a behavior we cannot disable. Can this be considered again?

**Comment by ryanmitchell** [comment]
You can use translation keys instead to prevent them being translated out side of your default:
https://statamic.dev/fields#translating-ui
