### ISSUE TITLE
Unlink relationship field from a set in bard isn't possible

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#910]
It isn't possible to unlink a relationship field from a set if it is displayed in a bard field.
If we delete the relationship field it disappears, but after a reload it is back again.

![Bildschirmvideo aufnehmen 2019-11-14 um 14 12 25](https://user-images.githubusercontent.com/54707973/68860165-413ec200-06e9-11ea-96a3-c9e46f629a61.gif)

**Comment by WiebkeVog** [comment]
It's a custom version

**Comment by WiebkeVog** [comment]
I tried to reproduce the behaviour with `type: bard` and unlink doesn't work, too. I don't think it is only a custom problem.

**Comment by WiebkeVog** [comment]
Oh shit, our mistake!
We have integrated this PR into our project: https://github.com/statamic/cms/pull/899

Add and remove works again when we removed `if (JSON.stringify(selection) == JSON.stringify(this.value)) return;` I would send you a new PR with this update and think the old one can be removed. Are you okay with that?

**Comment by sauerbraten** [comment]
https://github.com/statamic/cms/pull/1062 has a clean fix for this (it's basically #899 but from a fresh fork of the now public repo, plus a fix for this issue).
