### ISSUE TITLE
Collection with Entries aren't listed in CP after update to Statamic 4.38.0

### ISSUE THREAD

**Issue by priskahuber** [statamic/cms#9122]
After Update to Version 4.38.0 out customers multisite Statamic won't list collection entries.
The collections are shown in CP Navigation, but the overview doesn't show any entries (blank page).
An empty collection works and shows "add new entry" etc...

I have installed:
- PHP 8.1.23
- Statamic 4.38.0
- Collaboration 0.7.3
- Relationships 2.1.3

It shows an javascript error: 
`TypeError: Cannot read properties of undefined (reading 'dokutool_de'))`

"dokutool_de" is the name of German Site. But it throws the same error with "dokutool_fr" if i try it on French Site...

![Bildschirmfoto 2023-12-05 um 11 29 43](https://github.com/statamic/ideas/assets/17765613/1ed4858f-cabc-44a7-a8e4-326b4d9aee96)
![Bildschirmfoto 2023-12-05 um 11 29 57](https://github.com/statamic/ideas/assets/17765613/87af299e-9f91-4819-ba03-a2a1fc5bbc81)

**Comment by duncanmcclean** [comment]
Which page is this on? The entries listing page or the edit entry page?

**Comment by priskahuber** [comment]
Entries Listing Page.

**Comment by duncanmcclean** [comment]
Does this happen on all collections or just the "Bern" collection? Can you send me the contents of the collection YAML file (it'll live in `content/collections`)?

**Comment by priskahuber** [comment]
It happens on all Collections including Pages... 
I'll attach all Yaml-Files for Collections of "Bern", Pages, "Verjüngungsart" and Comments with all dependencies (fieldsets, assets, taxonomies), including composer.json as ZIP

All Taxonomies are listed as normal. It only appears in collections
[collection_problem.zip](https://github.com/statamic/cms/files/13577885/collection_problem.zip)

**Comment by priskahuber** [comment]
Sites config look like this:
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Sites
    |--------------------------------------------------------------------------
    |
    | Each site should have root URL that is either relative or absolute. Sites
    | are typically used for localization (eg. English/French) but may also
    | be used for related content (eg. different franchise locations).
    |
    */

    'sites' => [

        'dokutool_de' => [
            'name' => 'Deutsch',
            'locale' => 'de_CH.utf8',
            'lang' => 'de_CH',
            'url' => config('app.url'),
        ],

        'dokutool_fr' => [
            'name' => 'Français',
            'locale' => 'fr_CH.utf8',
            'lang' => 'fr',
            'url' => config('app.url').'/fr',
        ],

    ],
];
`

**Comment by priskahuber** [comment]
Main overview over all Collections is also working. And you can see, that there are 4 entries p.e. in "Bern". But they are not listed, only gray screen :(
![Bildschirmfoto 2023-12-06 um 08 37 19](https://github.com/statamic/cms/assets/17765613/cccab91f-5bbe-4421-b8f7-f8c4d47e670c)

**Comment by duncanmcclean** [comment]
Thanks for all the information! Can you send me the YAML files in the `content/collections` directory?

**Comment by priskahuber** [comment]
Hi Duncan. I've added them yesterday. But i'll add them again. Here you go:
[collection_problem.zip](https://github.com/statamic/cms/files/13602416/collection_problem.zip)

**Comment by priskahuber** [comment]
Oh, i've sent the wrong files, my bad :( So here they are, all the Yaml files in` content/collections`
[collections.zip](https://github.com/statamic/cms/files/13602442/collections.zip)

**Comment by duncanmcclean** [comment]
Hmm, even after copying all the files into a fresh site I can't reproduce this 🤔 

Which Statamic version did you update from?

**Comment by priskahuber** [comment]
Version 4.12.0
Collaboration 0.6.0
Relationships 2.1.1

**Comment by duncanmcclean** [comment]
I can't seem to reproduce the issue on your site which suggests it has to do with content. Are you able to add entries to one of the collections that's broken for you?

**Comment by priskahuber** [comment]
I tried it with a fresh clone and only added 2 pages... then i've updated... after the update, no page was shown in the collection...
I've add you a zip with the created pages (content/collections/pages)... 
[pages.zip](https://github.com/statamic/cms/files/13664643/pages.zip)

**Comment by priskahuber** [comment]
The steps were:
- Clone Repository
- npm install
- composer install
- added 2 pages to "Seiten/Pages" collection -> they are listed
- Updated via "composer update -W"
- reload collection "Seiten/Pages" -> no pages listed, only gray...

**Comment by duncanmcclean** [comment]
Thanks - I see the issue now.

**Comment by duncanmcclean** [comment]
It looks like this is breaking because you're overriding some of Statamic's built-in views (including the one for the collection show page). 

![image](https://github.com/statamic/cms/assets/19637309/70aaa887-ecf7-4cd5-ba97-f0a6e454a19f)

Statamic has made some updates to the collection show view which the JavaScript is expecting to exist but because you're overriding the view, those changes aren't there so the JavaScript side is throwing errors.

For this reason, I wouldn't recommend overriding views in Statamic Core.
