### ISSUE TITLE
Recent `{{ nocache }}` tag improvements seem to ignore variable usages in if statements or usages within partials

### ISSUE THREAD

**Issue by morhi** [statamic/cms#9123]
### Bug description

This happened after #8956 was released. When using the `{{ nocache }}` tag, variables are only available inside the tag, if their value was directly used, but not, if they are only used within `if` statements. The also get ignored, when used (even when simply outputting the value) within a partial inside the `nocache` tag.

To me this seems like an unwanted breaking change. Do you think it is possible to fix this issue?

### How to reproduce

1. Create any template with the nocache tag:

```antlers
{{ nocache }}
  {{ if show_me }}
    <span>hi there</span>
  {{ /if }}
{{ /nocache }}
```

2. The `if` within the `nocache` tag will not trigger the variable to be stored for the `nocache` context. This would work though:

```antlers
{{ nocache }}
  {{ show_me }}
  {{ if show_me }}
    <span>hi there</span>
  {{ /if }}
{{ /nocache }}
```

Of course, it would output the value of the variable, which I don't want. 

Possible workaround: Using the `{{ nocache select="show_me" }}` syntax instead.

### Environment

```yaml
Environment
Laravel Version: 10.34.2
PHP Version: 8.1.24

Statamic
Antlers: runtime
Static Caching: Disabled
Version: 4.38.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by duncanmcclean** [comment]
As a workaround, you can specify the variables you want to use with the `select` parameter:

```
{{ nocache select="variable_name|another|foo" }}
  <!-- And your code here -->
{{ /nocache }}
```

**Comment by jasonvarga** [comment]
I can't reproduce the condition thing. It even picks up the `if`.

Maybe there's another part to your issue that you didn't describe.

Nevertheless, this behavior is being changed to opt-in in #9124, and you can opt-in like Duncan described.
