### ISSUE TITLE
Form Export To CSV Issue 

### ISSUE THREAD

**Issue by emran-alhaddad** [statamic/cms#9220]
### Bug description

When I tried to export the form submissions to csv from statamic dashboard it gave me this issue "Array to string conversion"

<img width="1727" alt="image" src="https://github.com/statamic/cms/assets/65433346/89fbefa6-ee2b-4ed4-bab8-9e545cefee80">

### How to reproduce

nothing, just click export btn 

### Environment

```yaml
https://flareapp.io/share/17WJMnjP this is the issue details
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by ryanmitchell** [comment]
Are you able to share an example of a submission that is causing the issue? It seems to me like there might be something thats multi-nested in your data.

**Comment by lokmanm** [comment]
@emran-alhaddad @ryanmitchell is correct. I had this happen once when using a Replicator field inside my form and then exporting it to CSV. 

Do you have something like that?

**Comment by ryanmitchell** [comment]
I think you would need to add your own custom exporter to handle this then. The default exporter isn’t designed to handle nested fields like that.

**Comment by duncanmcclean** [comment]
By default, Statamic doesn't let you add Replicator fields to forms.

As suggested, you can workaround this by defining your own exporter. See https://github.com/statamic/cms/pull/8837 for more details.

**Comment by emran-alhaddad** [comment]
Thanks @ryanmitchell @duncanmcclean for your support

But another point I want you guys to make it in consideration that the same scenario works when exporting into json
