### ISSUE TITLE
Entries relation field doesn't work

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#926]
When I have a simple Entries field to add a relationship, no previews are shown and searching in the typeahead doesn't work either, see screenshot for error.

It has to do something with filters?

![image](https://user-images.githubusercontent.com/3626559/69326027-697b7300-0c4b-11ea-994f-77f8986ef633.png)

**Comment by riasvdv** [comment]
Doesn't seem to be completely fixed. On an initial load it still shows "Sorry, no matching options"

![image](https://user-images.githubusercontent.com/3626559/69350062-2afcad00-0c79-11ea-9758-5e5241679eb9.png)

Once you type something it's fixed

![image](https://user-images.githubusercontent.com/3626559/69350035-1fa98180-0c79-11ea-8993-75f966edaf3f.png)

Or is this expected behavior? Maybe it should show "Start typing" or something then

**Comment by jasonvarga** [comment]
Yeah that’s expected behavior but you’re right the text needs to be adjusted.

If you want all entries to be shown immediately you can use ‘mode: select’ instead of ‘typeahead’
