### ISSUE TITLE
Better descriptions in Collection wizard

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#936]
Would be super great if there were explanations or link or tooltips or something that gave or offered an explanation of what this (and other fields) means:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/6069653/69396293-9dc85100-0c96-11ea-8679-434c6ed1414f.png">

**Comment by jasonvarga** [comment]
You mean like the text next to the information icon? :) What you're probably asking for is a _better_ explanation.
