### ISSUE TITLE
Can't see OK/Save button in Taxonomy widget on small screen with debugbar

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#939]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/6069653/69396945-eda81780-0c98-11ea-8fd7-ef624fe0726b.png">

**Comment by jasonvarga** [comment]
That's annoying. 🤔 

Not saying this fixes it of course, but you know you can minimize debug bar until you actually need it?

**Comment by edalzell** [comment]
Yup

**Comment by jackmcdade** [comment]
I can't design around the debugbar, it's jut not practical. Gonna need to close this one (just like you will unfortunately need to close the bar sometimes to click stuff).
