### ISSUE TITLE
Principles, not principals

### ISSUE THREAD

**Issue by mtimofiiv** [statamic/cms#943]
https://statamic.dev/principals
^ You probably meant "principles", as in a code of conduct:

https://www.dictionary.com/browse/principle?s=t

A "principal" is the head of a school or leader in some field.

**Comment by mikemartin** [comment]
@mtimofiiv There’s also a docs repo where you can leave feedback here: https://github.com/statamic/docs/issues

**Comment by jackmcdade** [comment]
How embarrassing, thank you! 😊
