### ISSUE TITLE
Extend Bard Extension Classes

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#944]
Can you extend the bard extension classes with `Node` and `Extension` like https://github.com/statamic/cms/blob/master/resources/js/components/fieldtypes/bard/Mark.js

Related to: https://github.com/statamic/cms/pull/883

**Comment by jasonvarga** [comment]
No you can't. That's intentional since that PR so you don't have to import the tiptap yourself.

Why do you want to extend them? What's the issue?

**Comment by WiebkeVog** [comment]
Yes I know that we can't. We write some custom bard extensions where we have to import Node or Extension from tiptap. Or am I mistaken, and we can use your adjustment like this way: 

`Statamic.$bard.extend(({ bard, node }) =>node(new CleaningQuote(bard)));`

**Comment by jasonvarga** [comment]
Oh I see what you're saying. We only have the `mark` function at the moment. 

I was hoping you wouldn't need other types so soon :) I can add support for those soon!

**Comment by WiebkeVog** [comment]
Yes :) Right now we have a workaround. But it would be nicer when it worked the same way for all extensions.

**Comment by sheldonkotyk** [comment]
Any plans to be able to use sub and super tags in bard? If not, any plans to allow extensions soon?

**Comment by felixstoessel** [comment]
@jasonvarga I stumbled upon this same issue. It seems that Statamic only supports `mark()` which is not able to create block-like behavior. As far as I can understand, ProseMirror has the type `Node` that should be used for this.

Would be great if this could get added.

Some easy way to say: This is an inline element (like bold, underline inside a paragraph) and block element (like blockquote).

**Comment by jasonvarga** [comment]
Will accept pull requests!

**Comment by felixstoessel** [comment]
I have great confidence that Jesse or Jack will do a fantastic pull request ;)

**Comment by felixstoessel** [comment]
[Just a reply to avoid auto-closing of issue]

**Comment by jasonvarga** [comment]
`mark` is supported in #3657 (3.1.14)
