### ISSUE TITLE
Adjust width of fields belonging to a fieldset in CP

### ISSUE THREAD

**Issue by marflow** [statamic/cms#945]
The width of a field in a Blueprint can be adjusted, but I could not find that option for fields belongig to a fieldset. Should this be available in the CP as well? (If I add the widths in the fieldset yaml, it´s respected correctly.)

**Comment by jackmcdade** [comment]
That's on purpose as the Blueprint is the one that controls the layout and order, and Fieldsets are intended for reusable groups of fields. On the Blueprint level you can override any "imported" field and so on. It just so happens that because of the way the data is assembled between the two, manually setting the width in the Fieldset _does_ work. 

Does that make sense?

**Comment by marflow** [comment]
I did not say it´s a bug, only noticed I could not adjust the fields anywhere in CP. I thought that maybe a Blueprint would control the widths, but I did not find it. Example: A contact-info fieldset with 'phone', 'mobile' and 'email' and you want each to be 33%. Where do you do that (besides in the file)?

**Comment by jasonvarga** [comment]
In a blueprint section, if you expand it (the button at the top right), you will be able to adjust the widths.

![image](https://user-images.githubusercontent.com/105211/69432293-6fcf2500-0d07-11ea-9627-e90802c03d9a.png)
![image](https://user-images.githubusercontent.com/105211/69432364-92f9d480-0d07-11ea-8800-db229e87486f.png)

This could definitely be clearer.

**Comment by marflow** [comment]
Thanks Jason, I did find that, but it does not work for the fieldsets (fields).

**Comment by jasonvarga** [comment]
Right, you can't set the widths in the CP for fields in a _fieldset_. But you can in Blueprints. I was just addressing where you said this:

> I thought that maybe a Blueprint would control the widths, but I did not find it.

**Comment by marflow** [comment]
So if I have the blueprint with

- Company
- Contacts (field set)
   - phone
   - mobile
   - mail

I can only adjust the width of those three contact fields in the field set file, correct?

**Comment by jackmcdade** [comment]
No, you can adjust the widths in the **Blueprint UI**.

**Comment by marflow** [comment]
Send you a screenshot if I have the site back. No worries for now, seems it´s just me.

**Comment by jasonvarga** [comment]
Okay you're right there's no way to adjust those widths when you import an entire fieldset.

I guess we can add the width selector thingy to fieldsets too.

**Comment by marflow** [comment]
Thanks, feeling a bit better now for not overlooking something. Not a big thing, but would be convenient.

**Comment by jasonvarga** [comment]
In the next release, the width selector is available in the fieldset editor and the blueprint editor without needing to expand the section.

**Comment by minemindmedia** [comment]
Was this ever released?
I am running everything current and I do not see an option for adjusting the width of a grouped fieldset.

**Comment by jasonvarga** [comment]
You can only adjust the widths on a per-field basis.

If you're importing an entire fieldset, you'll need to define the field widths in the fieldset.
If you're importing individual fields, you'll be able to adjust the field widths in the blueprint.

**Comment by minemindmedia** [comment]
Understood, thank you.
