### ISSUE TITLE
[Control Panel] Uncaught ReferenceError: Statamic is not defined

### ISSUE THREAD

**Issue by mattrothenberg** [statamic/cms#947]
Howdy!

I'm on a fresh installation of the v3 dev preview, installed via the following command.

```
composer create-project statamic/statamic my-site --prefer-dist --stability=dev
```

When opening the control panel, I get the following error in my console, rendering the control panel unusable.

<img width="1438" alt="Screen Shot 2019-11-22 at 7 34 02 AM" src="https://user-images.githubusercontent.com/5148596/69430904-3644ec80-0cfc-11ea-9602-f4f8f20aed1a.png">

Could I have missed a step in the installation process? Perhaps I have a broken install and should try reinstalling?

```
"name": "statamic/cms",
"version": "dev-master",
"source": {
    "type": "git",
    "url": "https://github.com/statamic/cms.git",
    "reference": "30844a20407d61cd21775be1d0583c75e974d572"
},
"dist": {
    "type": "zip",
    "url": "https://api.github.com/repos/statamic/cms/zipball/30844a20407d61cd21775be1d0583c75e974d572",
    "reference": "30844a20407d61cd21775be1d0583c75e974d572",
    "shasum": ""
},
```

Thanks for the hard work, y'all!

**Comment by jasonvarga** [comment]
I just did the same and see the same issue. It's not you. Hold tight.

**Comment by jasonvarga** [comment]
Give `composer update statamic/cms` a whirl now.

**Comment by mattrothenberg** [comment]
Works like a charm. Thanks @jasonvarga .
