### ISSUE TITLE
Group field Graphql type incorrect

### ISSUE THREAD

**Issue by plexus77** [statamic/cms#9494]
<img width="900" alt="Screenshot 2024-02-09 at 10 50 30 am" src="https://github.com/statamic/ideas/assets/1281305/3ded2ebe-e5cf-4e3d-95f4-c5274a995284">

I set up a group field with a text field in it inside the global set and noticed that when I query this that the group fieldtype appears to have the wrong graphql type, string instead of object.

<img width="812" alt="Screenshot 2024-02-09 at 10 52 55 am" src="https://github.com/statamic/ideas/assets/1281305/40afef01-4ce2-49dd-a017-81740219e6ac">

Attempting too add the sub selection also fails.

**Comment by duncanmcclean** [comment]
This sounds more like a bug. I've moved it into the `cms` repository.

**Comment by plexus77** [comment]
Apologies, wasn't sure where to put this.
