### ISSUE TITLE
Stacks won't scroll on mobile Safari

### ISSUE THREAD

**Issue by afonic** [statamic/cms#9501]
### Bug description

I've noticed that when I open stacks on the control panel using **mobile** Safari, the content won't scroll.

### How to reproduce

**Use your iPhone**. On desktop Safari it works fine, even if you are in responsive mode.
Open an entry that has a field that opens in a wide stack. For example a `Link` with `Entry` selected. Click on the popover and select "Edit" to edit without navigating away. The stack that opens cannot scroll.

For example go here:

![IMG_E76C62B3267C-1](https://github.com/statamic/cms/assets/7423993/bd5bbf57-dd88-43e2-985b-ca9dd73afe08)

This page won't scroll:

![IMG_788D916BDDFC-1](https://github.com/statamic/cms/assets/7423993/1ef132a5-95e5-42ce-a9d1-f53928446bf2)

I tried using Safari on my Mac with the inspect tool to try and narrow down the problem but it's one of those things. I'd appreciate any help.

### Environment

```yaml
iPhone 14 Pro, iOS 17.2.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

**Comment by duncanmcclean** [comment]
What version of Statamic are you using?

**Comment by afonic** [comment]
It's 4.48.0 but it happens in multiple 4.x versions.
