### ISSUE TITLE
Expected status code 403 but received 302

### ISSUE THREAD

**Issue by vguerrerobosch** [statamic/cms#955]
Well first of all, congratulations! I've been expecting v3 for so long. Second thing, given that many of the issues coming up here will be closer to what I understand as customer support, I just acquired a license for V2.

I just included statamic/cms to a project I'm working on and everything has gone really well.

In this project we have our test suite and after setting all up and running our tests we found that all assertStatus(403) are now failing because Statamic hooks in there and performs a 302 to the Control Panel. These 403 are being handled by a model Policy.

I don't know if that default behavior can be changed somehow or even if it's desired in the first place.

Thank you very much!

Additional note (don't want to open an issue about this): our project is using adamwathan/blade-svg with the svg blade directive. Found out that Statamic registers it's own svg directive and that broke up our layout. Solved just using the alternate icon directive given by adamwathan. If you feel like this is worth opening as issue I can do it with pleasure.

**Comment by jasonvarga** [comment]
Thanks for the report! Feel free to open a separate issue for the svg directive.
