### ISSUE TITLE
Confict in svg directive between statamic/cms and adamwathan/blade-svg

### ISSUE THREAD

**Issue by vguerrerobosch** [statamic/cms#956]
Just found out that statamic/cms is registering its own `svg` blade directive that collides with https://github.com/adamwathan/blade-svg that we were using in a project. Solved it switching to the alternate `icon` directive given by @adamwathan. Thanks!

**Comment by jackmcdade** [comment]
Glad you got it sorted!

**Comment by vguerrerobosch** [comment]
You might want to review this as nothingworks/blade-svg has been deprected in favor of [blade-ui-kit/blade-icons](https://github.com/blade-ui-kit/blade-icons) and so has been the `@icon` directive. Still have `<x-icon>` blade component, but when dealing with dynamic components it's sometimes useful to go like `@svg($icon)` rather than `<x-dynamic-component :component="icon-$icon" class="mt-4" />`

**Comment by jasonvarga** [comment]
99e812e moves the registration of the `@svg` directive into the CP to prevent conflicts with Blade UI kit etc.
