### ISSUE TITLE
Call to undefined method Statamic\Stache\Repositories\CollectionRepository::handleExists()

### ISSUE THREAD

**Issue by Treggats** [statamic/cms#958]
I have created a fresh v3 site, installed the migrator package and migrated an existing v2 site.
This all went fine, but when I opened the Control Panel I am meeted with the following error message.

`Call to undefined method Statamic\Stache\Repositories\CollectionRepository::handleExists()`
More info here: https://flareapp.io/share/LPlAVn7B#F61

`handleExists` is something that exists in v2, what's the equivalent of this in v3?

Thanks a bunch, in advance.

**Comment by jimblue** [comment]
Got the exact same problem, it seems to be related to control panel widgets.
The error happen in my case because Statamic can't found the collection.
I used migrator for migration obviously 😄 but it seems that something went wrong.
Also error handling is buggy in that case apparently.

**Comment by jimblue** [comment]
thanks :D
