### ISSUE TITLE
Missing Nav/Structure Tag Parameters

### ISSUE THREAD

**Issue by matrad** [statamic/cms#967]
Hello,

for my template the Parameters within `nav` listed [here](https://statamic.dev/tags/nav) are not working at all. For example `exclude` is ignored, also the example from `is_hidden:isnt` is not working.

The Code at statamic.dev is at the `WRITING STAGE: PREWRITING`, but I think when we migrate old statamic-pages, then it'd be usefull if we do not must rewrite the entire nav-logic and change this "basic" tags?

Or do I miss something and the tags should work also in v3?

**Comment by jackmcdade** [comment]
The Nav/Structure isn't finished. I was pretty sure we had an open issue for it but I can't find it, so this will be that issue :)

**Comment by matrad** [comment]
@jackmcdade ok great - btw. I [saw](https://statamic.dev/structures) that you migrated to `structure`, but currently also there an `exclude` or `is_hidden` is missing.

**Comment by admench** [comment]
I too am having issues using the nav tag, even simple tasks such as rendering children from the current page doesn't seem to be working. Rendering global nav from root is fine, but not from a 2nd level page showing its children.

**Comment by admench** [comment]
It seems that using the `{{ nav }}` tag in a simple way on a subpage does not respect the current entry as a `from` location. Instead the page tree is show from root.

**Comment by admench** [comment]
@jackmcdade / @jasonvarga Any idea when you could possibly fix the nav parameters not working on the current beta? It would be fantastic if these features worked - many thanks. Adam

**Comment by admench** [comment]
@jackmcdade / @jasonvarga do you have an eta on this, or an alternative workaround to achieve passing parameters to the `nav` tag? As it stands the nav tag only works from root, not from a specified URL using `from`. Thanks so much

**Comment by jasonvarga** [comment]
`:from="url"` doesn't work?

**Comment by admench** [comment]
No, I just get a blank output:

```
<div class="max-w-7xl px-4 mx-auto py-8">
    <div class="flex flex-wrap justify-center sm:-mx-3 staggered">
        {{ nav :from="url" }} {{ if children }} {{ children }}
        <div class="sm:px-3 mb-4 w-full sm:w-1/2 lg:w-1/3" data-scroll>
            <a href="{{ url }}" class="btn btn-blue w-full text-center">
                {{ title }}
            </a>
        </div>
        {{ /children }} {{ /if }} {{ /nav }}
    </div>
</div>

```

Using `{{ nav }}`without any `from` does output a heirarchy of pages from the root however.

**Comment by admench** [comment]
I even tried `from="{url}"` to no avail.

**Comment by jasonvarga** [comment]
Okay then no workaround at the moment.

We're tightening taxonomy stuff right now then moving onto structures. Can't give you an ETA really. Soon-ish?

**Comment by admench** [comment]
OK Thanks

**Comment by jackmcdade** [comment]
Thanks for the heads up! Structures are getting a bit of a rework this week. Stay tuned.

**Comment by admench** [comment]
Amazing @jackmcdade I look forward to getting `nav` up and running on v3.

**Comment by admench** [comment]
Any update @jasonvarga  - hate to chase but this nav tag is the only thing I need to finish my site. Many thanks for your work and communication.

**Comment by admench** [comment]
Any chance this can be implemented soon please? Thanks a lot.

**Comment by jonassiewertsen** [comment]
Running into the same issue, that parameters do not work with the nav tag yet.

As I understand, the nav tag hasn't been implemented until now.

**Comment by mikemartin** [comment]
Nice to see I'm not the only person hitting this issue. Looking forward to the new Structures update.

**Comment by jackmcdade** [comment]
We're really close!

**Comment by dakisan** [comment]
suuuuper looking forward to have a not-hardcoded-nav again :)

**Comment by jasonvarga** [comment]
Hi everyone, sorry for delay on this!

In the next release, the nav tag will support `from="/some-url"` again. (Although by default it's always from the root. You have to explicitly set it now.)

As I'm writing this comment, the filtering parameters don't yet work, (`is_hidden:is="true"` kinda thing) but that _may_ change by the actual release.
