### ISSUE TITLE
Possibility to link to a page-id url (with the defined site's url)

### ISSUE THREAD

**Issue by matrad** [statamic/cms#968]
The solution in the [statamic Forum](https://statamic.com/forum/3940-linking-to-a-permanent-page-id) to link to a dedicated page-id is not working in v3.

`{{ 4dfb27a3-b415-4ef6-a7d0-bed80707c6f6 | get:url }}` - in this case I get an empty string.

It'd be great if in v3 you can review this, also respecting the multisite (multilanguage) config, what may change in v3 because we do not have unique id's for different sites:

- In the template there are sometimes parts like imprint/privacy
- In our example we've two sites `de` and `en`.
- If we link to `{{ page_id | get:url }}` and are on page `de`, then get the page-url of page `de`
- If we link to `{{ page_id | get:url }}` and are on page `en`, then get the page-url of page `en`
- In v3 the `page_id` is unique and belongs either to `en` or to `de`, so it would be great if there's a way to get the url of a page for a relevant page-id by passing a single url.
- A workaround would be to create a generic option-page containing these links

**Comment by matrad** [comment]
Also the `{{ link to="4dfb27a3-b415-4ef6-a7d0-bed80707c6f6" }}` returns a link to  `/4dfb27a3-b415-4ef6-a7d0-bed80707c6f6`, but it should return `/impressum` as it was in statamic-v2.

**Comment by jasonvarga** [comment]
We need to make sure the `link` tag is working in v3. Thanks for bringing it to our attention!

**Comment by matrad** [comment]
@jasonvarga in v3 there is another possibility to link static sites like these or is this still the default way?

**Comment by jasonvarga** [comment]
I'm not sure what you mean?

**Comment by matrad** [comment]
@jasonvarga you tagged this as "v2 compatibility" so I think this method is added only because of v2-migrations? If we're creating a new site with v3 shouldn't this be used?

**Comment by jasonvarga** [comment]
I tagged it like that because it's a feature in v2 but not in v3 yet.

**Comment by jasonvarga** [comment]
Related to #801

**Comment by Hesesses** [comment]
Is there any workarounds for this currently?

**Comment by jasonvarga** [comment]
`{{ "the-id" | get:url }}` and `{{ link id="the-id" }}` both work.
