### ISSUE TITLE
"Scheduled for future" indicator for entry should also be used in Entry

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#970]
Could you also display the indicator from d39ea55 and 0894524 in the Entry? I think in `PublishForm.vue` you currently only use the green and grey dot.

**Comment by jackmcdade** [comment]
We should circle back around to the "Scheduled" state and affordance soon and close this up.

**Comment by jackmcdade** [comment]
Added in 3e3c25f3c9b5712fb760a061e93bf3a414ee5b07
