### ISSUE TITLE
Ability to set replicator_preview: false to disable preview on a specific field

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#971]
The replicator collapsed previews are displayed some information which aren't really important for us. So it would be a nice extension if we could configure the displayed content ourselves. Maybe the Blueprints would be a good place for that. What do you think?

**Comment by jasonvarga** [comment]
Do you need to customize the content or is disabling particular fields enough?

We have the ability to add `replicator_preview: false` to a field in v2 which I think just isn't hooked up yet in v3.

**Comment by WiebkeVog** [comment]
It would be great if we had the opportunity to set `replicator_preview: false`

**Comment by jasonvarga** [comment]
No problem!
