### ISSUE TITLE
Docker/Sail installation broken

### ISSUE THREAD

**Issue by colinmollenhour** [statamic/cms#9728]
### Bug description

I am new to Statamic, but not PHP. I wanted to give Statamic a try on my WSL2 environment using Docker as I don't run PHP locally.

The instructions at https://statamic.dev/installing/docker say to use `curl -s "https://laravel.build/example-app" | bash`, but this command results in installing Laravel 11.x which seems to not work with Statamic. 

From what I can tell the laravel.build method does not allow you to specify a version. However, this did work:

```
docker run --rm \
    --pull=always \
    -v "$(pwd)":/opt \
    -w /opt \
    laravelsail/php80-composer:latest \
    bash -c "composer create-project laravel/laravel=\"9.*\" statamic && cd statamic && php ./artisan sail:install --with=none "
```

### How to reproduce

Run a new installation with `curl -s "https://laravel.build/example-app" | bash`. It installs Laravel 11.x just fine, but Statamic does not work with Laravel 11.x so you get composer dependency errors when trying to require Statamic.

### Environment

```yaml
Any Docker environment.
```

### Installation

Other (please explain)

### Antlers Parser

None

**Comment by jasonvarga** [comment]
Statamic 5 will support Laravel 11. Keep an eye out. For now what you're doing is a great workaround. But you probably should use `10.*` not `9.*`.
