### ISSUE TITLE
version="true" on theme:css, theme:js tags

### ISSUE THREAD

**Issue by matrad** [statamic/cms#974]
In v2 we had the possibility to generate Version-Strings to a js/css file by defining this in a antlers template:

CSS: `{{ theme:css src="main" tag="true" version="true" }}`

JS: `{{ theme:js src="main" tag="true" version="true" }}`

In V2 the version string is not added, also not when defining `mix.version()` in the webpack.mix.js file.

Content of webpack.mix.js:
```
let mix = require('laravel-mix');
mix.sass('resources/sass/mietzentrum/main.scss', 'public/css/main.scss')
mix.version()
```

Content of layout.antlers.html:
```
...
{{ theme:css src="main" tag="true" version="true" }}
...
```

**Comment by matrad** [comment]
Close this issue - sorry this way my fault - typo in we webpack, the result should be `main.css`, not `main.scss`.

**Comment by jasonvarga** [comment]
Thanks for following up!
