### ISSUE TITLE
Multisite "site" toggler on nav and within content

### ISSUE THREAD

**Issue by matrad** [statamic/cms#975]
Hello,

for me first it was really confused to understand the difference between the TOP NAV toggler what contains "de", and then the Sidebar what contains also a "page" toggle - and these two settings are not in sync.

Maybe it would be a solution to:
 - Change also the content to de if we change the site to de if we are within the edit section
 - Move the nav toggler away from the navbar and only place it on some views where the toggler is relevant?

Just an idea, feel free to close if you think this is irrelevant.

Matthias

![Edit_Entry_‹_Pages_‹_Strukturen_‹_Statamic](https://user-images.githubusercontent.com/660903/69552617-09fcca80-0f9f-11ea-937f-418fa95c92a0.png)

**Comment by jasonvarga** [comment]
The one in the top nav is your default state as you browse the control panel. eg. If you were to browse to another collection's entry listing, it would show in de.

The one in the form is specific to the thing you're editing. 

Of course, open to feedback here.

**Comment by matrad** [comment]
@jasonvarga 
I think it would help a lot of people if we are within the editor context and change the language of the control panel that also the "page-edit" language changes, because this was the behaviour in v2.

**Comment by manogi** [comment]
I am also for the change @matrad suggested above.

**Comment by jackmcdade** [comment]
It still makes sense to me to be able to leave the site in a default language (up top) but switch between languages/locales on a given entry as you're working through translations. I'm going to close this one.

**Comment by matrad** [comment]
@jackmcdade so the language of the cp depends on the setting on the top right - correct? Is there any way to force the cp to a specific language? As we are using `de` and `it` and they're both not really translated - so it would be better to show the cp in the english language for all - but this settings should be independent of the frontend-locale.
