### ISSUE TITLE
The Template Dropdown with the property readonly is not readonly

### ISSUE THREAD

**Issue by matrad** [statamic/cms#976]
The Template Dropdown with the property readonly is not readonly

"Schreibgeschützt" means readonly in english.

![Edit_Entry_‹_Pages_‹_Strukturen_‹_Statamic](https://user-images.githubusercontent.com/660903/69552963-a3c47780-0f9f-11ea-9e52-77bf07b227de.png)

**Comment by jasonvarga** [comment]
Thanks!
