### ISSUE TITLE
Git committing fails in nix environment

### ISSUE THREAD

**Issue by sbrow** [statamic/cms#9767]
### Bug description

Following up on #3392
automatic commits don't work by default in (my) nix environment. In order to get things working, I had to update the default git commands to include the git binary config.

P.S. It should be noted that commands like `php please git:commit` worked fine, but making edits through the Control Panel did not.

<details>
<summary>Example (Removing some fields for brevity):</summary>

```php
// config/statamic/git.php
<?php

$binary = env('STATAMIC_GIT_BINARY', 'git');

return [
    // ...

    /*
    |--------------------------------------------------------------------------
    | Git Binary
    |--------------------------------------------------------------------------
    |
    | By default, Statamic will try to use the "git" command, but you can set
    | an absolute path to the git binary if necessary for your environment.
    |
    */
    'binary' => $binary,

    /*
    |--------------------------------------------------------------------------
    | Commands
    |--------------------------------------------------------------------------
    |
    | Define a list commands to be run when Statamic is ready to `git add`
    | and `git commit` your changes. These commands will be run once
    | per repo, attempting to consolidate commits where possible.
    |
    | https://statamic.dev/git-automation#customizing-commits
    |
    */
    'commands' => [
        "$binary add {{ paths }}",
        $binary.' -c "user.name={{ name }}" -c "user.email={{ email }}" commit -m "{{ message }}"',
    ],

    // ...
];
```

```.env
# .env

# ...
STATAMIC_GIT_ENABLED=true
# realpath $(which git)
STATAMIC_GIT_BINARY=/nix/store/zrs710jpfn7ngy5z4c6rrwwjq33b2a0y-git-2.42.0/bin/git
# ...
```

```nix
# flake.nix
{
  description = "Testing statamic";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/23.11";

    sbrow.url = "github:sbrow/nix";

    flake-parts.url = "github:hercules-ci/flake-parts";
    process-compose-flake.url = "github:Platonic-Systems/process-compose-flake";
  };

  outputs = inputs@{ self, flake-parts, nixpkgs, process-compose-flake, sbrow }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      imports = [
        inputs.process-compose-flake.flakeModule
      ];
      systems = [ "x86_64-linux" ];

      perSystem = { pkgs, system, ... }:
      {
        formatter = pkgs.nixpkgs-fmt;

        # See process-compose.yaml for details
        process-compose.default.settings = {
          processes = {
            web.command = "sudo ${pkgs.caddy}/bin/caddy run";
            php.command = "${pkgs.php}/bin/php-fpm -F -y php-fpm.conf";
          };
        };

        devShells.default = pkgs.mkShell
          {
            buildInputs = with pkgs; [
              caddy
              php
              yarn
              process-compose
              git
            ] ++ (with phpPackages; [
              composer
            ]);
          };
      };
    };
}
```
</details>

### How to reproduce

1. Follow the instructions here: https://statamic.dev/quick-start-guide#install-statamic
2. Run `git init`.
3. Install [nix](https://nixos.org/download/). (Must be in a Linux environment)
4. Create a nix flake with the following contents
5. run `$ nix run` to start the dev server
6. add/edit the `.env` file as shown below
7. Edit a file in the control panel and see if it commits for you.

**.env**
```.env
# Append to the bottom of the file
STATAMIC_GIT_ENABLED=true
STATAMIC_GIT_BINARY=/nix/store/zrs710jpfn7ngy5z4c6rrwwjq33b2a0y-git-2.42.0/bin/git
```

flake.nix
```nix
{
  description = "Testing statamic";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/23.11";

    sbrow.url = "github:sbrow/nix";

    flake-parts.url = "github:hercules-ci/flake-parts";
    process-compose-flake.url = "github:Platonic-Systems/process-compose-flake";
  };

  outputs = inputs@{ self, flake-parts, nixpkgs, process-compose-flake, sbrow }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      imports = [
        inputs.process-compose-flake.flakeModule
      ];
      systems = [ "x86_64-linux" ];

      perSystem = { pkgs, system, ... }:
      {
        formatter = pkgs.nixpkgs-fmt;

        # See process-compose.yaml for details
        process-compose.default.settings = {
          processes = {
            web.command = "sudo ${pkgs.caddy}/bin/caddy run";
            php.command = "${pkgs.php}/bin/php-fpm -F -y php-fpm.conf";
          };
        };

        devShells.default = pkgs.mkShell
          {
            buildInputs = with pkgs; [
              caddy
              php
              yarn
              process-compose
              git
            ] ++ (with phpPackages; [
              composer
            ]);
          };
      };
    };
}
```

Caddyfile
```Caddyfile
cyberspace-place.test, :80, :443 {
	root * ./public

        try_files {path} /static/{uri}_{args}.html {uri} /index.php{query}

	encode gzip
	file_server
	php_fastcgi 127.0.0.1:9009

	tls internal
}
```

php-fpm.conf
```conf
error_log = /dev/stderr

[site]
access.log = /dev/stderr
listen = 127.0.0.1:9009
; Choose how the process manager will control the number of child processes.
pm = dynamic
pm.max_children = 75
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 20
pm.process_idle_timeout = 10s
```

### Logs

```shell
[2024-03-20 15:58:47] local.ERROR: Process Class: Git
Command: git add /home/spencer/github.com/cyberspace-place/content /home/spencer/github.com/cyberspace-place/users /home/spencer/github.com/cyberspace-place/resources/blueprints /home/spencer/github.com/cyberspace-place/resources/users /home/spencer/github.com/cyberspace-place/resources/preferences.yaml /home/spencer/github.com/cyberspace-place/public/assets
```

### Environment

```yaml
Environment
Application Name: Cyberspace Place
Laravel Version: 10.47.0
PHP Version: 8.2.13
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: cyberspace-place.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.53.2 PRO

Statamic Addons
aryehraber/statamic-impersonator: 2.6.0
stefangalescu/statamic-heroicons: 2.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

**Comment by duncanmcclean** [comment]
Thanks for opening this issue!

Apologies for my ignorance, I haven't come across Nix before so not sure about the specifics of how it works. 

Outside of a Statamic context, how do you use Git commands in Nix? Can you use it normally with `git` or do you always need to prefix the path to the Git binary?

For example, can you do just this?

```
git fetch
```

Or do you always need to do this?

```
/nix/store/zrs710jpfn7ngy5z4c6rrwwjq33b2a0y-git-2.42.0/bin/git fetch
```

**Comment by sbrow** [comment]
I can use `git` no problem from the commandline, and like I said, `php please git:commit` works just fine. It's only when the php-fpm process tries to invoke it that I get issues.

Technically, I use use [direnv](https://direnv.net/) to invoke a development environment whenever I enter a project directory. This calls `nix develop` behind the scenes to set up my `$PATH` to  contain all the project dependencies.

You may be more familiar with tools like Python's `venv` or conda. They all rely on a virtual environment to manage your dependencies.

It's possible that I can also solve my problem by ensuring that the `php-fpm` process runs inside the devShell environment, but I opened an issue because I saw the `binary` option and the `commands` option, and it looks on the surface like the commands don't use the binary- It looks like they just use whatever `git` command is in your path. Now if that's not the case, then maybe it's all wrong on my end.

---

P.S. [Nix](https://nixos.org/) is well worth your attention. Nix flakes in particular is like having a `package.json`/`package.lock` on the level of operating system packages. There's a bit of a learning curve, but if you're not already invested in using Docker or Vagrant to manage your dependencies it can be a invaluable; and it's PHP friendly!

**Comment by duncanmcclean** [comment]
Thanks for the additional information. 

As you mentioned, I reckon the reason you're running into this issue in the first place is _probably_ due to the user running the PHP-FPM process not having `git` available, whereas it is for the user you're SSH'ing into (or however you're accessing the server).

We can probably update the `commands` in the default config so at least you only need to configure custom binaries in one spot.
