### ISSUE TITLE
When using Multisite-Configuration the Translate Toggle is not visible

### ISSUE THREAD

**Issue by matrad** [statamic/cms#977]
When using Multisite-Configuration the Translate Toogle is not visible

The Page of the Blueprint:

![Blaupausen_bearbeiten_‹_Statamic](https://user-images.githubusercontent.com/660903/69554007-65c85300-0fa1-11ea-8561-a16a923c5554.png)

The editor of the Blueprint:

![Blaupausen_bearbeiten_‹_Statamic](https://user-images.githubusercontent.com/660903/69554042-77115f80-0fa1-11ea-822f-8438b1be1e67.png)

How it is in v2 at the overview screen:

![Bildschirmfoto_2019-11-25_um_16_35_03](https://user-images.githubusercontent.com/660903/69554112-97411e80-0fa1-11ea-9e8b-b593f0561e73.png)

How it is in v2 at the detail screen:

![Wird_gerade_bearbeitet_meta_yaml___Statamic](https://user-images.githubusercontent.com/660903/69554175-ac1db200-0fa1-11ea-91e0-acbae8d80b52.png)

Manually changing the `localizable` in the blueprint yml to true is working, so the editor respects the `localizable` blueprint-setting

**Comment by matrad** [comment]
@jackmcdade any roadmap when this will be fixed? it's really heavy always changing that manually in the yams.

**Comment by matrad** [comment]
PS: By default on localized pages the title is readonly. It would be great if we can make that by default localized. The title is always added by default.

**Comment by jasonvarga** [comment]
Closing in favor of #2045
