### ISSUE TITLE
Session data is not accessible in v3

### ISSUE THREAD

**Issue by matrad** [statamic/cms#979]
In v2 we can access the session data in this way:

![Session_-_Tags_-_Statamic_2_Docs](https://user-images.githubusercontent.com/660903/69559290-f0ad4b80-0fa9-11ea-923f-72a52f654c08.png)

in v3 `{{ session:dump }}` is returning nothing, the workaround is to add a partial blade where the `session()` object is accessible.

**Comment by jasonvarga** [comment]
Duplicate of #905
