### ISSUE TITLE
Display column are not shown, for the type terms(taxonomy)

### ISSUE THREAD

**Issue by LorikHa** [statamic/cms#9795]
### Bug description

The display columns are not working for all the type that are terms( taxonomies), if we change this type to text, we could see the data.
![image](https://github.com/statamic/cms/assets/17572404/f9aa83f8-b067-44c8-b16a-16d21e15d12c)
Here is the image of yaml file that does not work
![image](https://github.com/statamic/cms/assets/17572404/d02fdb26-de11-44b3-8af1-74832f222e1e)
And here is the image that works
![image](https://github.com/statamic/cms/assets/17572404/a51e3ff8-b52c-48d2-b885-57ec221cac9d)
Also below you can see the result( I changed the author from type:terms to type:text)

![image](https://github.com/statamic/cms/assets/17572404/b5a543c6-b522-4743-a785-7d369727d5b5)

### How to reproduce

Just connect in the article some taxonomy, and put in the articles type:terms

### Environment

```yaml
Statamic 4.48.0 Pro
thoughtco/statamic-restrict-fieldshtco/statamic-restrict-fieldsg Disabled
my-packages/statamic-utility-translations-manager 1.0
my-packages/statamic-widget-uncompleted-assets 1.0
aryehraber/statamic-logbook 2.2.0
cp-statamic/eloquent-entries 1.0
thoughtco/statamic-restrict-fieldshtco/statamic-restrict-fields 1.0.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
Thanks for opening this issue. 

It looks like you only provided part of the `support:details` output so I wasn't able to tell but are you using multi-site?

**Comment by LorikHa** [comment]
@duncanmcclean  not for this site, I am not using multi-site

**Comment by duncanmcclean** [comment]
Can you provide the Markdown file for one of the entries w/ categories & tags attached?

**Comment by LorikHa** [comment]
> Can you provide the Markdown file for one of the entries w/ categories & tags attached?

{
  "topline": "top line text",
  "title": "test title",
  "teaser": "teaset text",
  "header_media": null,
  "media_fs_type": "1",
  "media_fs_image": "_gettyimages-1266344041.jpg",
  "media_fs_gallery": null,
  "media_fs_video": null,
  "content_section": null,
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "type": "text",
          "text": "test content"
        }
      ]
    }
  ],
  "needs_review": null,
  "author": "adfgadfsg",
  "additional_authors": [
    "adfgadfsg"
  ],
  "author_visible": true,
  "publish_date": "2024-03-28 13:55",
  "expiry_date": null,
  "tags": [
    "anzeige",
    "arbeitskraftabsicherung"
  ],
  "category": "biometrie",
  "label": null,
  "special": null,
  "newsletter": true,
  "meta_title": null,
  "meta_description": null,
  "meta_keywords": null,
  "related_articles": null,
  "display_related_articles": null,
  "updated_by": 30,
  "updated_at": 1711630519
}

**Comment by LorikHa** [comment]
Hi @duncanmcclean , thank you for responding so fast about this issue, please find below all the details about my statamic web

**Environment
Application Name: Statamic
Laravel Version: 9.52.16
PHP Version: 8.2.13
Composer Version: 2.6.2
Environment: local
Debug Mode: ENABLED
URL: my-site.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: cron
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: regex
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 PRO

Statamic Addons
my-packages/statamic-utility-translations-manager: 1.0
my-packages/statamic-widget-uncompleted-assets: 1.0
aryehraber/statamic-logbook: 3.2.0
cp-statamic/eloquent-entries: 1.0
statamic/collaboration: 0.6.0
thoughtco/statamic-restrict-fields: 1.1.0**

**Comment by duncanmcclean** [comment]
I've just tested this again and I'm still not able to reproduce... terms show fine for me:

![CleanShot 2024-04-03 at 14 58 29](https://github.com/statamic/cms/assets/19637309/f5d68729-96c1-4125-a685-77bd2c20b8d4)

I notice you're using `cp-statamic/eloquent-entries` which isn't our official [Eloquent Driver](https://github.com/statamic/eloquent-driver). I can't find the `eloquent-entries` package on Packagist so I assume it's custom. 

If you create a fresh site using flat-files or the official Eloquent Driver, are you still able to reproduce the issue?

**Comment by duncanmcclean** [comment]
Since I'm not able to reproduce and haven't heard back from you since my last comment, I'm going to close this issue now.

If you're still experiencing this issue using the _official_ Eloquent Driver, leave a comment and we can re-open this issue.
