### ISSUE TITLE
[feature-request] Statamic modifies the errors array from laravel

### ISSUE THREAD

**Issue by matrad** [statamic/cms#980]
When integrating statamic into existing laravel integrations it would be useful if we can access to the default `$errors` bag.

What I did is:
- Create  a Controller with a custom Request
- Added a blade-template with the (old) logic from a migrated application
- It won't work because the statamic-core overwrites the default error behaviour of forms

![Bildschirmfoto 2019-11-25 um 17 54 17](https://user-images.githubusercontent.com/660903/69560990-efc9e900-0fac-11ea-8eea-56a62a581864.png)

**Comment by matrad** [comment]
My fault, it was because of missing translation in the resources/lang directory

**Comment by jasonvarga** [comment]
Are we missing something or did you delete it?

**Comment by matrad** [comment]
@jasonvarga no, it's all ok - the errors are ok, from the screenshot I saw only `validation.required` messages and thought that statamic overwrites the error-bag, but it was the missing `de` translation in laravel and the missing fallback to `en`.

Adding the `de` translations in `resources/lang/de` it worked, I was too fast opening the bug :)

**Comment by jasonvarga** [comment]
Got it! Thanks.
