### ISSUE TITLE
Grid field type custom "add row" not working

### ISSUE THREAD

**Issue by twd3** [statamic/cms#985]
I customized the "add row" button text for a grid field type and it still just says add row.
`add_row: 'Add List Item'`

**Comment by billmn** [comment]
All works fine with my installation ... are you using an updated version of statamic/cms?

This was fixed ~1 month ago (https://github.com/statamic/cms/pull/855)

## Blueprint
![Schermata 2019-11-25 alle 23 16 57](https://user-images.githubusercontent.com/779534/69583445-37676980-0fdb-11ea-80f1-1c8510416cb6.png)

## Grid Field
![Schermata 2019-11-25 alle 23 17 05](https://user-images.githubusercontent.com/779534/69583447-3a625a00-0fdb-11ea-8a59-3fb9a272623c.png)

## Blueprint YAML file
![Schermata 2019-11-25 alle 23 17 23](https://user-images.githubusercontent.com/779534/69583450-3cc4b400-0fdb-11ea-9fbe-c426dc2e88d0.png)

**Comment by twd3** [comment]
Crap I reverted back trying to fix something and forgot to update!
