### ISSUE TITLE
[5.x] `php please` issues with default application structure on Laravel 11

### ISSUE THREAD

**Issue by o1y** [statamic/cms#9887]
### Bug description

Not sure if you classify this as a bug, but I stumbled upon it and it could possibly happen to others as well. When using Laravel Shift to Upgrade from Laravel 10 -> 11, the default `app` files are deleted (although it's not really necessary).

This results in `php please` not working anymore (and possibly other errors).

```bash
Fatal error: Uncaught Error: Class "App\Console\Kernel" not found in /.../statamic/vendor/statamic/cms/src/Console/Please/Kernel.php:9
```

If you want to follow the Laravel Upgrade Guide recommendations, feel free to close this issue. Maybe a hint in the Upgrade-Guide (when you plan to promote Laravel Shift), would help :)

### How to reproduce

1. Upgrade Statamic from Laravel 10 to Laravel 11 using Laravel Shift.
2. Use latest `v5.0.0-alpha.3` release.
3. Run `php please`

### Environment

```yaml
🤷‍♂️
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment]
The `please` file needed to be rewritten for Laravel 11 applications.

I've just added a step to the [upgrade guide](https://github.com/statamic/docs/blob/5.0/content/collections/docs/4-to-5.md#updated-please-file-for-laravel-11) for those upgrading via Laravel Shift. 😄
