### ISSUE TITLE
Filtering by "site" leads to an error

### ISSUE THREAD

**Issue by psren** [statamic/cms#993]
I have a multi-site `de_DE`,  `fr_FR` and try to use revisions.

1. I have one revision _published_ in each of the two sites
1. I am on the overview of the collection (the list page)
1. Switching the sites works like expected
1. When I use the filters to filter for a site
1. Then I get the following error

```
Call to a member function collection() on null
```

https://flareapp.io/share/oPRbLZPV

![image](https://user-images.githubusercontent.com/1016798/69668347-fbdaa700-108f-11ea-92c2-29a41130a0eb.png)

**Comment by jackmcdade** [comment]
This should be fixed along with the refactor/redesign of the filters. If you have any further problems with it feel free to open a new issue!
