### ISSUE TITLE
Starter Kit install broken

### ISSUE THREAD

**Issue by lpeterke** [statamic/cms#9952]
### Bug description

Your latest release 4.57.1 broke php please starterkit:install

Error: Could not open input file: vendor/bin/composer

### How to reproduce

1. statamic new testproject
2. php please starterkit:install studio1902/statamic-peak

### Environment

```yaml
Latest
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by lpeterke** [comment]
Issue can be fixed by locking statamic/cms to 4.57.0 after installation in composer.json, then reinstall composer dependencies.

**Comment by joshuablum** [comment]
There is already an open PR to fix this, see https://github.com/statamic/cms/pull/9950.

**Comment by the-goodies** [comment]
Still broken on Windows:

```
In NewCommand.php line 555:

  There was a problem installing Statamic with the chosen starter kit!


new [--dev] [--license [LICENSE]] [--local] [--with-config] [--without-dependencies] [-f|--force] [--] <name> [<starter-kit>]
```

**Comment by duncanmcclean** [comment]
@the-goodies This seems like a different issue - please open a new issue.
