### ISSUE TITLE
CP: selecting an entry in Collections leads to strange UX (UI question)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#996]
Example: within the Pages collection I select the Home entry.
3 buttons are displayed: Publish, Unpublish and Delete

When I click on the "3 dots" button at the far right of the selected entry, the modal displays : View and Edit, but Publish, Unpublish and Delete are once again displayed.

My CP is now in French and those 3 are not translated. Are they really intended to be in this modal?

![Capture d'écran 2019-11-26 21 50 04](https://user-images.githubusercontent.com/1823359/69673714-385fd000-109b-11ea-8366-955ab1b22e99.png)

**Comment by jasonvarga** [comment]
The actions listed in the 3 dots are applicable for that single row.

The ones at the top appear for bulk actions (when you use the checkbox to select the row) and you clicking the dots triggered the row to be selected.

Clicking the dots should not trigger the row to be selected, IMO.

The items need to be translated too.
