### ISSUE TITLE
CP: when creating or editing an entry, Slug isn't translated into the CP locale (i18n?)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#997]
My CP is displayed in French.
```slug```is a translated word

Slug is displayed in English when creating or editing an entry, is this intended?

![Capture d'écran 2019-11-26 21 50 58](https://user-images.githubusercontent.com/1823359/69674158-2a5e7f00-109c-11ea-8eab-95b6c8236989.png)

**Comment by ebeauchamps** [comment]
hum...I guess I wasn't clear enough here.
I want to translate the word "Slug", not the ```slug```itself.
Any chance you could check this please?

**Comment by jackmcdade** [comment]
Yes it's fixed but we haven't released the build yet.
