### ISSUE TITLE
CP: missing keys when creating Assets Container leads to English strings instead of localized ones

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#999]
My CP is displayed in French. When creating an asset container, 6 labels are still in English, and that includes Handle which is displayed in French on other screens.

![Capture d'écran 2019-11-26 21 56 30](https://user-images.githubusercontent.com/1823359/69674948-d81e5d80-109d-11ea-9bb3-d4d7333bb8dc.png)

**Comment by jackmcdade** [comment]
Thanks!
